@interface AWEAwemeKeSongView : UIView
@property (nonatomic) double containerViewWidth;
@property (nonatomic) double containerViewHeight;
@property (nonatomic) UIButton keSongButton;
@property (nonatomic) UIView keSongContainerView;
@property (nonatomic) UIView textContainerView;
@property (nonatomic) UIView loopContainerView;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) double subviewWidth;
@property (nonatomic) q subviewCount;
@property (nonatomic) NSString keSongLabelText;
@property (nonatomic) NSString referString;
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) <AWEAwemeKeSongViewDelegate> delegate;
- (id)awemeModel;
- (void)setAwemeModel:;
- (id)referString;
- (void)setReferString:;
- (id)aAWEPadModuleAdapter;
- (double)containerViewHeight;
- (void)setContainerViewWidth:;
- (void)setContainerViewHeight:;
- (double)widthWithLabelString:;
- (void)setSubviewWidth:;
- (double)containerViewWidth;
- (double)subviewWidth;
- (void)setSubviewCount:;
- (long long)subviewCount;
- (id)loopContainerView;
- (void)setLoopContainerView:;
- (void)setupBind;
- (void)setKeSongContainerView:;
- (id)keSongButton;
- (id)keSongContainerView;
- (void)handleContainerViewClicked:;
- (id)keSongLabelText;
- (double)keSongContainerViewX;
- (void)setKeSongLabelText:;
- (void)updatekeSongButtonImage;
- (id)subviewWithLabelString:;
- (void)handleKeSongButtonClicked:;
- (void)configRollingAnimationWithLabelString:awemeModel:animation:trackParams:;
- (void)setFlatStretchLabelIfNeeded:;
- (void)setKeSongButton:;
- (id)labelFont;
- (void)dealloc;
- (id)delegate;
- (id)initWithFrame:;
- (void)startAnimation;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)layoutSubviews;
- (void)resumeAnimation;
- (void)pauseAnimation;
- (id)gradientLayer;
- (void)stopAnimation;
- (void)setGradientLayer:;
- (void)setupUI;
- (void)setTextContainerView:;
- (id)textContainerView;
+ (Class)aAWEPadModuleAdapterClass;
@end
