@interface AWEAddressBookListManager : NSObject
@property (nonatomic) NSMutableArray addressBookUserList;
@property (nonatomic) NSMutableArray addressBookUnfollowUsers;
@property (nonatomic) NSMutableArray addressBookNotUnfollowUsers;
@property (nonatomic) NSNumber type;
@property (nonatomic) NSNumber cursor;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) NSNumber registerCount;
@property (nonatomic) NSMutableArray removedUsers;
- (id)userList;
- (void)loadMore:;
- (BOOL)canLoadMore;
- (void)setAddressBookUserList:;
- (id)addressBookUserList;
- (id)addressBookUnfollowUsers;
- (id)addressBookNotUnfollowUsers;
- (id)registerCount;
- (void)setRegisterCount:;
- (id)filterRemovedUsers:;
- (void)loadAddressListPartUsers;
- (void)refresh:needDegraded:;
- (id)filterDuplicateUsers:;
- (void)changeUserList:;
- (id)unfollowUserList;
- (id)notUnfollowUserList;
- (void)removeUser:isUnfollow:;
- (void)insertUser:index:isUnfollow:;
- (void)removeUserFromFullUserList:;
- (void)insertUserToFullUserList:index:;
- (void)addressBookDislikeUserItem:enterFrom:completion:;
- (void)setAddressBookUnfollowUsers:;
- (void)setAddressBookNotUnfollowUsers:;
- (id)cursor;
- (id)init;
- (void)setHasMore:;
- (BOOL)hasMore;
- (void)setCursor:;
- (id)type;
- (void)setType:;
- (void).cxx_destruct;
- (void)refresh:;
- (id)removedUsers;
- (void)setRemovedUsers:;
+ (BOOL)enableAddressBookListNewOrderStyle;
+ (BOOL)enableChangeAddressbookListStyle;
@end
