@interface AWEAddWidgetGuideView : UIView
@property (nonatomic) UIView overlayView;
@property (nonatomic) UIView contentView;
@property (nonatomic) UIButton closeButton;
@property (nonatomic) UIPageControl pageControl;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel nextTitleLabel;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) UILabel nextDescLabel;
@property (nonatomic) UIButton bottomButton;
@property (nonatomic) UIButton nextBottomButton;
@property (nonatomic) q currCellIndex;
@property (nonatomic) q nextCellIndex;
@property (nonatomic) AWEAddWidgetGuideCell currCell;
@property (nonatomic) AWEAddWidgetGuideCell nextCell;
@property (nonatomic) NSArray models;
@property (nonatomic) <AWEAddWidgetGuideViewDelegate> delegate;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) NSString widgetType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)aAWEPadModuleAdapter;
- (id)descLabel;
- (void)setDescLabel:;
- (id)aAWEPadBizUIAdapter;
- (double)titleViewTopMargin;
- (void)setupTapGesture;
- (double)collectionViewBottomMargin;
- (void)overlayViewTapAction:;
- (void)trackUGWidgetGuideClickWithClickTarget:;
- (void)setNextTitleLabel:;
- (void)refreshLayout:;
- (void)clickToClose:;
- (void)showWithContainer:useMask:;
- (void)updateCAMaskedCorners:;
- (id)guideImageSize;
- (BOOL)isIphoneLandscape;
- (double)potraitContentHeight;
- (id)nextDescLabel;
- (id)nextBottomButton;
- (double)collectionViewTopMargin;
- (double)buttonButtomMargin;
- (void)clickTapGesture:;
- (long long)currCellIndex;
- (void)trackGuideViewClickWithShowType:clickTarget:;
- (void)refreshWithModel:nextModel:;
- (void)setCurrCell:;
- (void)setCurrCellIndex:;
- (void)setNextCell:;
- (void)setNextCellIndex:;
- (long long)nextCellIndex;
- (void)updateUIAlpha:;
- (id)currCell;
- (void)clickToNextStep:;
- (double)landscapeContentWidget;
- (void)setNextDescLabel:;
- (void)setNextBottomButton:;
- (id)overlayView;
- (void)setPageControl:;
- (id)collectionView;
- (void)hide;
- (BOOL)isShowing;
- (id)pageControl;
- (id)delegate;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setWidgetType:;
- (id)contentSize;
- (void)setOverlayView:;
- (id)widgetType;
- (id)contentView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)scrollViewDidScroll:;
- (void)setModels:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (void)setContentView:;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (id)titleLabel;
- (void)setDelegate:;
- (id)models;
- (void)setupSubviews;
- (void)setCloseButton:;
- (id)closeButton;
- (id)initWithModels:;
- (id)nextTitleLabel;
- (id)bottomButton;
- (void)setBottomButton:;
- (id)nextCell;
+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWEPadBizUIAdapterClass;
@end
