@interface AWEAntiAddictMaskBlockInteractionView : UIView
@property (nonatomic) AWEAntiAddictMaskContext context;
@property (nonatomic) UIView contentView;
@property (nonatomic) AWEGradientView gradientView;
@property (nonatomic) UILabel mainTitleLabel;
@property (nonatomic) UILabel blockAfterLabel;
@property (nonatomic) UILabel subTitleLabel;
@property (nonatomic) UIButton feedbackButton;
@property (nonatomic) NSString mainTitle;
@property (nonatomic) NSString blockAfterTitle;
@property (nonatomic) NSString subTitle;
@property (nonatomic) NSString feedbackTitle;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)feedbackTitle;
- (void)setFeedbackTitle:;
- (void)addGestureRecognizer;
- (id)mainTitleLabel;
- (void)setMainTitleLabel:;
- (void)didClickFeedbackButton;
- (void)setBlockAfterLabel:;
- (id)blockAfterLabel;
- (void)catchGesture:;
- (id)blockAfterTitle;
- (void)setBlockAfterTitle:;
- (id)gradientView;
- (id)initWithFrame:;
- (void)setup;
- (id)contentView;
- (id)initWithContext:;
- (void)setSubTitle:;
- (BOOL)gestureRecognizerShouldBegin:;
- (id)subTitle;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setContentView:;
- (void)setGradientView:;
- (void)reset;
- (id)context;
- (void)showWithCompletion:;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
- (id)mainTitle;
- (void)setMainTitle:;
- (id)feedbackButton;
- (void)setFeedbackButton:;
@end
