@interface AWEAdIndicatorLinkModel : MTLModel
@property (nonatomic) AWEURLModel positionURL;
@property (nonatomic) NSArray positions;
@property (nonatomic) AWEAdIndicatorLinkPositionModel startPosition;
@property (nonatomic) AWEURLModel icon;
@property (nonatomic) AWEAdConversionAreaModel buttonInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSMutableDictionary componentStages;
@property (nonatomic) <AWEAdPreloadComponentContext> componentContext;
- (id)componentContext;
- (void)setComponentContext:;
- (id)buttonInfo;
- (void)setButtonInfo:;
- (void)setPositions:;
- (id)positionURL;
- (id)componentRefer;
- (id)componentCreativeID;
- (id)componentLogExtra;
- (id)componentGroupID;
- (id)componentExtraID;
- (id)componentStages;
- (void)setComponentStages:;
- (void)setPositionURL:;
- (id)icon;
- (id)componentType;
- (void)setIcon:;
- (void).cxx_destruct;
- (void)setStartPosition:;
- (id)startPosition;
- (id)positions;
+ (id)iconJSONTransformer;
+ (id)startPositionJSONTransformer;
+ (id)positionURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
+ (unsigned long long)storageBehaviorForPropertyWithKey:;
+ (id)buttonInfoJSONTransformer;
@end
