@interface AWEAlbumSelectTemplateFeedViewController : UIViewController
@property (nonatomic) BOOL isFetchingData;
@property (nonatomic) BOOL isFirstRequest;
@property (nonatomic) AWEAlbumSelectTemplateFeedViewModel viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView<ACCLoadingViewProtocol> loadingView;
@property (nonatomic) <ACCMVTemplatesDataControllerProtocol> dataProvider;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) <AWEAlbumSelectTemplateFeedViewControllerDelegate> delegate;
@property (nonatomic) AWEVideoPublishViewModel publishModel;
@property (nonatomic) @? willEnterDetailVCBlock;
@property (nonatomic) @? didAppearBlock;
- (void)p_setupUI;
- (id)accui_emptyPageConfigForState:;
- (void)accui_emptyPagePrimaryButtonTapped:;
- (id)publishModel;
- (BOOL)isFirstRequest;
- (void)setIsFirstRequest:;
- (void)setPublishModel:;
- (id)transitionCollectionCellForItemOffset:;
- (void)p_fetchDataWithRetry:;
- (void)p_setupRefresh;
- (void)setIsFetchingData:;
- (void)p_updateEmpteStateWithError:andContentCount:;
- (void)p_endLoadingAndRefreshingWithMoreData:;
- (void)p_monitorReportWithError:;
- (void)diffReloadContent;
- (id)willEnterDetailVCBlock;
- (void)setWillEnterDetailVCBlock:;
- (id)collectionView;
- (id)delegate;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)loadingView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setDataProvider:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)viewDidAppear:;
- (void)setDelegate:;
- (id)dataProvider;
- (void)reloadContent;
- (id)didAppearBlock;
- (void)setDidAppearBlock:;
- (BOOL)isFetchingData;
@end
