@interface AWEAwemeDetailPreloadController : NSObject
@property (nonatomic) double cellPreloadDelay;
@property (nonatomic) q scheduledPreloadIndex;
@property (nonatomic) BOOL isCellPreloadingEnabled;
@property (nonatomic) UITableViewCell<AWEAwemeContainerTableViewCellPreloadProtocol> willDisplayPreloadedCell;
@property (nonatomic) UIViewController<AWEAwemeDetailPreloadControllerProtocol> viewController;
@property (nonatomic) BOOL isLastDirectionSlideToBottom;
@property (nonatomic) q needContinuousDirectionCount;
@property (nonatomic) q continuousDirectionCount;
@property (nonatomic) q currentCellPreloadCount;
@property (nonatomic) q cellPreloadDelayCount;
@property (nonatomic) BOOL cellPreloadOptimizeEnable;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)willDisplayPreloadedCell;
- (void)cancelCellPreloading;
- (void)scheduleCellPreloading;
- (void)initialFetchCompletion:error:;
- (void)setIsLastDirectionSlideToBottom:;
- (double)cellPreloadDelay;
- (void)setCellPreloadDelay:;
- (void)setIsCellPreloadingEnabled:;
- (void)setNeedContinuousDirectionCount:;
- (long long)cellPreloadDelayCount;
- (void)setCellPreloadDelayCount:;
- (void)setCellPreloadOptimizeEnable:;
- (BOOL)isCellPreloadingEnabled;
- (void)setWillDisplayPreloadedCell:;
- (void)setScheduledPreloadIndex:;
- (void)preloadNextCellIfNeeded;
- (BOOL)cellPreloadOptimizeEnable;
- (long long)currentCellPreloadCount;
- (void)setCurrentCellPreloadCount:;
- (long long)nextPreloadedIndex;
- (long long)scheduledPreloadIndex;
- (long long)needContinuousDirectionCount;
- (long long)continuousDirectionCount;
- (BOOL)isLastDirectionSlideToBottom;
- (void)setupCellPreload;
- (id)fetchPreloadedCellForRowWithModel:atIndexPath:;
- (void)setContinuousDirectionCount:;
- (void)controllerViewDidLoad;
- (void)controllerFinishTransition:;
- (void)prepareForPadViewTransitionAnimated;
- (void)scheduleCellPreloadOnScrollEnd;
- (id)initWithViewController:;
- (void)play;
- (id)viewController;
- (void).cxx_destruct;
- (id)cellForRowAtIndexPath:;
- (void)stop;
- (void)pause;
- (void)setViewController:;
- (id)preloadedCell;
@end
