@interface AWEAdMannorLivePreManager : NSObject
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) NSMutableSet readyComponentTypes;
@property (nonatomic) NSMutableDictionary cardHeights;
@property (nonatomic) NSObject<BDMannorAdComponentProtocol> mannorComponent;
@property (nonatomic) BDMannorManager mannorManager;
@property (nonatomic) NSDictionary containerDict;
@property (nonatomic) double startTime;
@property (nonatomic) NSTimer timer;
@property (nonatomic) q cumulativeDuration;
@property (nonatomic) NSMutableDictionary componentDict;
@property (nonatomic) NSMutableDictionary componentShowBlockDict;
@property (nonatomic) NSMutableDictionary componentHideBlockDict;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @? showLivePreviewInfoBlock;
@property (nonatomic) @? showLargeStyleAdCardBlock;
@property (nonatomic) @? showSmallStyleAdCardBlock;
@property (nonatomic) @? hideSmallStyleAdCardBlock;
@property (nonatomic) @? hideLivePreviewInfoBlock;
@property (nonatomic) @? enterLiveRoomBlock;
- (id)awemeModel;
- (void)setAwemeModel:;
- (void)onLeaveConvertPage:;
- (void)audienceQuitAllRoom;
- (void)sendEvent:params:callback:;
- (id)lynxBridges;
- (void)p_setupMannorCard;
- (id)mannorManager;
- (id)p_mannorContext;
- (void)mannorComponentDidStartLoad:componentType:;
- (void)mannorComponentDidFinishLoad:componentType:;
- (void)mannorComponentDowngrade:errorMessage:componentType:;
- (void)mannorComponentClose:componentType:;
- (void)setMannorManager:;
- (id)p_mannorJSBInjectHandlerMethodMap;
- (id)mannorComponent;
- (void)setMannorComponent:;
- (void)p_setupComponentRelation;
- (void)setComponentShowBlockDict:;
- (id)componentShowBlockDict;
- (id)showLivePreviewInfoBlock;
- (void)setComponentHideBlockDict:;
- (id)componentHideBlockDict;
- (id)hideLivePreviewInfoBlock;
- (id)p_layoutModelForComponentType:;
- (id)componentDict;
- (id)containerDict;
- (long long)cumulativeDuration;
- (id)p_componentSpecificJSBridgesWithComponentType:;
- (id)readyComponentTypes;
- (id)cardHeights;
- (void)startShowComponent:height:;
- (id)enterLiveRoomBlock;
- (void)startHideComponent:;
- (void)p_trackCreativeComponentCloseClickEvent:;
- (id)hideSmallStyleAdCardBlock;
- (void)trackOtherShowFailed:;
- (void)trackOtherShow:;
- (id)showSmallStyleAdCardBlock;
- (id)showLargeStyleAdCardBlock;
- (void)setCumulativeDuration:;
- (id)p_adExtraDictWithComponentType:;
- (id)p_userEventParams;
- (void)setupMannorCardWithContainerDict:awemeModel:;
- (void)livePreviewPause;
- (void)livePreviewResume;
- (BOOL)needHigherEnterRoomButton:;
- (void)setShowLivePreviewInfoBlock:;
- (void)setShowLargeStyleAdCardBlock:;
- (void)setShowSmallStyleAdCardBlock:;
- (void)setHideSmallStyleAdCardBlock:;
- (void)setHideLivePreviewInfoBlock:;
- (void)setEnterLiveRoomBlock:;
- (void)setReadyComponentTypes:;
- (void)setCardHeights:;
- (void)setContainerDict:;
- (void)setComponentDict:;
- (void)updateTimer;
- (void)setTimer:;
- (id)timer;
- (void)setStartTime:;
- (void)startTimer;
- (void).cxx_destruct;
- (void)reset;
- (double)startTime;
+ (BOOL)shouldUseMannorRenderInLivePreviewWithAwemeModel:;
+ (BOOL)shouldShowBottomCardInLivePreviewWithAwemeModel:;
@end
