@interface AWEAdRifleLearnMoreLynxButton : UIView
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) Q adLynxComponentType;
@property (nonatomic) AWEBDARifleView bdaRifleView;
@property (nonatomic) BOOL isAnimating;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} enterFrame;
@property (nonatomic) NSString userID;
@property (nonatomic) q followStatus;
@property (nonatomic) BOOL liveAppointmentStatus;
@property (nonatomic) Q componentType;
@property (nonatomic) NSDictionary animationParams;
@property (nonatomic) NSString refer;
@property (nonatomic) BOOL enterFromWebView;
@property (nonatomic) BOOL didConstructJSRuntime;
@property (nonatomic) BOOL isLoadFailed;
@property (nonatomic) double loadStartTimeStamp;
@property (nonatomic) double loadStartFirstScreenTimeStamp;
@property (nonatomic) AWEAdGeneralSearchLynxComponentMonitorContext lynxMonitorContext;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) BOOL transformedToCard;
@property (nonatomic) double lynxContainerHeight;
@property (nonatomic) NSString liveGroupId;
@property (nonatomic) BOOL isLynxButtonOptABTest;
@property (nonatomic) double lynxButtonAnimationDelayTime;
@property (nonatomic) BOOL renderInDoubleColumn;
@property (nonatomic) BOOL useLynxAir;
@property (nonatomic) BOOL isFeedButtonStartFlash;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <AWEAdLearnMoreLynxButtonDelegate> delegate;
@property (nonatomic) @? lynxButtonLoadFailBlock;
@property (nonatomic) @? updateLynxButtonHeightBlock;
@property (nonatomic) @? updateLynxButtonFrameBlock;
@property (nonatomic) NSString lynxButtonPositionEvent;
@property (nonatomic) BOOL useStackViewLayout;
@property (nonatomic) BOOL isAutoAdaptive;
@property (nonatomic) BOOL isFallback;
@property (nonatomic) BOOL isTop;
@property (nonatomic) BOOL isMerchandiseType;
@property (nonatomic) q merchandiseOrder;
@property (nonatomic) @? lynxButtonLoadFailWithButtonModelBlock;
- (long long)followStatus;
- (void)didFinishFollowUser:status:error:;
- (void)didFinishUnFollowUser:status:error:;
- (BOOL)canShow;
- (void)setFollowStatus:;
- (void)setRefer:;
- (void)notifyScreenRotation;
- (id)refer;
- (id)bdaRifleView;
- (void)playFlashAnimated:;
- (void)lynxAnimationStartWithNotification:;
- (void)setIsLoadFailed:;
- (BOOL)isLoadFailed;
- (id)liveGroupId;
- (BOOL)isMerchandiseType;
- (void)setIsMerchandiseType:;
- (long long)merchandiseOrder;
- (void)setMerchandiseOrder:;
- (void)rifleView:didChangeIntrinsicContentSize:;
- (void)rifleViewDidStartLoading:;
- (void)rifleViewvDidFirstScreen:;
- (void)rifleView:didFinishLoadWithURL:;
- (void)rifleView:didLoadFailedWithURL:error:;
- (void)rifleViewDidConstructJSRuntime:;
- (id)lynxBridges;
- (id)lynxButtonLoadFailBlock;
- (void)notifyAppear;
- (void)notifyDisappear;
- (void)sendVideoLoopEvent:;
- (void)setLynxButtonLoadFailBlock:;
- (void)notifyLynxButtonWidth:;
- (void)setRenderInDoubleColumn:;
- (void)playerTimerTriggeredWithNotification:;
- (void)adLiveFailStatusUpdate:;
- (id)createLynxMonitorContext;
- (void)setLynxMonitorContext:;
- (void)setLoadStartTimeStamp:;
- (id)lynxMonitorContext;
- (BOOL)renderInDoubleColumn;
- (BOOL)enterFromWebView;
- (id)globalPropsPageDataWith:withComponent:;
- (void)addAdTypeParamsWithConfiguration:;
- (void)updateRifleConfiguration:;
- (double)loadStartTimeStamp;
- (void)setEnterFromWebView:;
- (void)updateLearnMoreLynxButtonWithModel:;
- (void)setBdaRifleView:;
- (id)enterFrame;
- (BOOL)isLynxButtonOptABTest;
- (void)configureBdaRifleViewWithModel:;
- (void)setUpFollowComponentIfNeeded;
- (void)setUpLiveAppointmentComponentIfNeeded;
- (unsigned long long)adLynxComponentType;
- (void)setAdLynxComponentType:;
- (BOOL)canShowLynxWithComponent:;
- (void)configureBdaRifleViewWithComponent:;
- (unsigned long long)componentTypeOfModel:;
- (id)currentLynxRawData;
- (void)setTransformedToCard:;
- (void)setAnimationParams:;
- (void)setDidConstructJSRuntime:;
- (void)setIsFeedButtonStartFlash:;
- (void)asyncOpenAppStoreWithParams:completion:;
- (BOOL)openAppStoreWithParams:;
- (BOOL)handleDownloadClick:;
- (void)updateLynxViewHeightInsearch:;
- (void)startFeedButtonAnimation:duration:fromAlpha:toAlpha:;
- (void)startFeedButtonAnimationWithHeight:durationa:fromAlpha:toAlpha:;
- (void)setLiveGroupId:;
- (void)setLiveAppointmentStatus:;
- (BOOL)liveAppointmentStatus;
- (id)getAuthorAvatar;
- (BOOL)useStackViewLayout;
- (double)lynxButtonAnimationDelayTime;
- (void)updateLynxViewHeight:;
- (id)lynxButtonPositionEvent;
- (id)topviewLiveStatus;
- (void)setUseLynxAir:;
- (void)setLoadStartFirstScreenTimeStamp:;
- (double)loadStartFirstScreenTimeStamp;
- (void)postSearchOutFlowMonitorShowEventIfNeed;
- (id)lynxButtonLoadFailWithButtonModelBlock;
- (void)notifyAppearIfLynxRunTimeDidConstruct;
- (id)currentLynxButtonTemplateSchema;
- (BOOL)useLynxAir;
- (void)notifyTimerTriggered:;
- (id)animationParams;
- (void)setLynxContainerHeight:;
- (BOOL)transformedToCard;
- (BOOL)didConstructJSRuntime;
- (id)updateLynxButtonHeightBlock;
- (id)updateLynxButtonFrameBlock;
- (id)initWithFrame:renderInDoubleColumn:;
- (void)updateLearnMoreLynxWebBottomButtonWithModel:;
- (void)updateLearnMoreLynxButtonWithComponentModel:type:;
- (void)playUnfoldAnimated:;
- (void)notifyRestartAnimation;
- (void)notifyAggregationButtonIndex:;
- (void)setLynxViewAlpha:;
- (void)updateLynxViewFrame:;
- (void)updateContentWithHeight:;
- (void)setUpdateLynxButtonHeightBlock:;
- (void)setUpdateLynxButtonFrameBlock:;
- (void)setLynxButtonPositionEvent:;
- (void)setUseStackViewLayout:;
- (BOOL)isAutoAdaptive;
- (void)setIsAutoAdaptive:;
- (void)setIsTop:;
- (double)lynxContainerHeight;
- (BOOL)isFeedButtonStartFlash;
- (void)setEnterFrame:;
- (void)setLynxButtonLoadFailWithButtonModelBlock:;
- (void)setModel:;
- (id)userID;
- (BOOL)isShowing;
- (void)dealloc;
- (id)delegate;
- (void)addObserver;
- (id)initWithFrame:;
- (unsigned long long)componentType;
- (id)model;
- (BOOL)isAnimating;
- (void)setComponentType:;
- (void).cxx_destruct;
- (void)setIsAnimating:;
- (void)reset;
- (void)setDelegate:;
- (BOOL)isFallback;
- (void)setUserID:;
- (BOOL)isTop;
- (void)setIsFallback:;
- (void)setIsShowing:;
@end
