@interface AWEAwemeDetailQualityMetricCenterController : AWEAwemeNewDetailBaseController
@property (nonatomic) double pipDuration;
@property (nonatomic) double pipStartTimeStamp;
@property (nonatomic) double pipEndTimeStamp;
@property (nonatomic) BOOL isLoadMoreNoMoreData;
@property (nonatomic) MMKV mmkv;
@property (nonatomic) BOOL isDidAppear;
@property (nonatomic) double pipStartPlayTimeStamp;
@property (nonatomic) double pipEndPlayTimeStamp;
@property (nonatomic) double mixVideoCurrentPlayBackTime;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)onScrollViewWillBeginDragging:;
- (id)aAWEPadModuleAdapter;
- (long long)currentPlayIndex;
- (void)onScrollDidEndWithIndexPath:;
- (void)loadMoreCompletion:error:isFooterRefreshing:;
- (void)detailCellViewController:didChangePlaybackStateWithAction:;
- (void)detailCellViewController:awemeModel:playerPlayTime:canPlayTime:totalTime:;
- (void)setMmkv:;
- (id)mmkv;
- (double)getCurrentPlayTime;
- (void)p_appDidBecomeActive:;
- (BOOL)shouldBackgroundPlay;
- (long long)feedAutoPlaySwitchStyle;
- (void)p_addObserversAndNotifications;
- (void)pip_init;
- (void)pip_updateStatus;
- (void)setIsDidAppear:;
- (void)handleFeedAutoPlayNextNotification:;
- (void)appWillBecomeUnavailable:;
- (void)handlePiPStorageSwitchChangeNotification:;
- (BOOL)shouldBackgroundSmallWindow;
- (BOOL)isDidAppear;
- (BOOL)enableGeneralCellSupportPiP;
- (void)setPipEndTimeStamp:;
- (double)pipEndTimeStamp;
- (double)pipStartTimeStamp;
- (void)setPipDuration:;
- (void)updatePlayTime;
- (void)setPipEndPlayTimeStamp:;
- (double)pipEndPlayTimeStamp;
- (double)pipStartPlayTimeStamp;
- (void)pip_stopPiPIfActive;
- (void)trackSmallWindowPlayTimeWithDuration:;
- (void)pip_playWhenTableViewDidEndDisplay:;
- (void)setIsLoadMoreNoMoreData:;
- (void)trackCloseSmallWindowModeWithEventType:;
- (void)trackSmallWindowModeDurationWithDuration:enterMethod:;
- (void)setPipStartPlayTimeStamp:;
- (void)pip_updateProgress:playTime:totalTime:;
- (void)trackPiPVideoWithEvent:;
- (void)setPipStartTimeStamp:;
- (void)trackEnterSmallWindowMode;
- (void)trackSmallWindowFailWithParams:;
- (id)realAutoReferString;
- (void)trackPiPVideoWithEvent:params:;
- (void)p_pipUpdateStatus;
- (void)p_pipUpdatePregress:playTime:totalTime:;
- (void)pip_playWithIndex:;
- (BOOL)isLoadMoreNoMoreData;
- (void)pip_playNext;
- (void)p_pipPlayWhenTableViewDidEndDisplay:;
- (void)pip_serviceWillStart:;
- (void)pip_serviceDidStart:;
- (void)pip_service:willStopForRestore:;
- (void)pip_service:didStopForRestore:;
- (void)pip_service:restoreFromForeground:;
- (void)pip_service:failedToStartWithError:;
- (void)pip_service:didTransToNewSize:;
- (void)pip_service:seekToTime:completion:;
- (void)pip_service:isPlaying:;
- (void)pip_service:getPlayerContext:;
- (void)pip_service:unbindPlayerContext:;
- (void)pip_service:bindPlayerContext:;
- (void)pip_servicePlayBtnClicked:;
- (void)pip_serviceTrackForClickVideoPlay:;
- (void)pip_service:triggeredWithType:ToScene:;
- (void)pip_serviceTrackForProgressSpeed:sFront:;
- (void)pip_playPre;
- (double)mixVideoCurrentPlayBackTime;
- (void)setMixVideoCurrentPlayBackTime:;
- (void)applicationWillResignActive:;
- (void)dealloc;
- (void)play;
- (void)viewDidLoad;
- (void)viewDidDisappear:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)tableView:didEndDisplayingCell:forRowAtIndexPath:;
- (void)applicationWillTerminate:;
- (id)videoController;
- (double)pipDuration;
+ (Class)aAWEPadModuleAdapterClass;
@end
