@interface AWEAdvanceSettingActionViewController : UIViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <AFDModalViewHelperProtocol> helper;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIView navigationView;
@property (nonatomic) UIView lineView;
@property (nonatomic) UIView bar;
@property (nonatomic) UITableView tableView;
@property (nonatomic) AWEAdvanceSettingActionDataController dataController;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @? confirmDuetPermissonBlock;
@property (nonatomic) @? confirmCommentPermissonBlock;
@property (nonatomic) @? confirmCommentProtectionModeBlock;
@property (nonatomic) @? confirmDanmakuPermissonBlock;
@property (nonatomic) @? confirmXiguaPrivacyTypeBlock;
- (BOOL)wantsDimmingTransitionBackground;
- (void)transitionBackgroundViewTapped:;
- (void)setDataController:;
- (id)initWithDataController:;
- (void)p_setupViews;
- (void)dismissHalfScreen;
- (id)navigationView;
- (void)setNavigationView:;
- (void)updateCommentProtectionModeWithSelectedIndexPath:;
- (void)updateCommentAllowedStateWithSelectedIndexPath:;
- (void)updateCommentAllowedStateBeforePublishWithSelectedIndexPath:;
- (void)updateDanmakuAllowedStateWithSelectedIndexPath:;
- (void)updateXiguaPrivacyTypeWithSelectedIndexPath:;
- (void)updateDanmakuAllowedStateBeforePublishWithSelectedIndexPath:;
- (void)updateDuetAllowedStateWithSelectedIndexPath:;
- (void)dismissCurrentViewControllerWithCompletion:;
- (double)navigationViewH;
- (void)registerTableViewCellReuse;
- (id)identifierForCardUIStyleWithOriginalID:;
- (id)confirmDuetPermissonBlock;
- (id)confirmCommentPermissonBlock;
- (id)confirmCommentProtectionModeBlock;
- (id)confirmDanmakuPermissonBlock;
- (id)confirmXiguaPrivacyTypeBlock;
- (void)setConfirmDuetPermissonBlock:;
- (void)setConfirmCommentPermissonBlock:;
- (void)setConfirmCommentProtectionModeBlock:;
- (void)setConfirmDanmakuPermissonBlock:;
- (void)setConfirmXiguaPrivacyTypeBlock:;
- (void)dismissHalfScreenWithChildVC;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)viewDidLoad;
- (id)tableView;
- (double)contentHeight;
- (void)setTitleLabel:;
- (void)viewWillAppear:;
- (void)setHelper:;
- (void).cxx_destruct;
- (double)tableView:heightForRowAtIndexPath:;
- (id)helper;
- (id)titleLabel;
- (void)setBar:;
- (id)bar;
- (id)lineView;
- (void)setLineView:;
- (double)tableViewHeight;
- (id)dataController;
- (double)bottomOffset;
@end
