@interface AWEActivityXTabViewController : UIViewController
@property (nonatomic) UIViewController<BDXContainerProtocol> activityVC;
@property (nonatomic) NSString schema;
@property (nonatomic) NSString originSchema;
@property (nonatomic) BOOL hasViewDidAppear;
@property (nonatomic) @? animatedRefreshCompletion;
@property (nonatomic) NSString activityId;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) BOOL disableShake;
@property (nonatomic) UIView topBarBackgroundView;
@property (nonatomic) NSString mainScrollViewName;
@property (nonatomic) UIScrollView mainScrollView;
@property (nonatomic) double slidingHeight;
@property (nonatomic) UIPanGestureRecognizer lynxPanGes;
@property (nonatomic) UIColor topBarBackgroundViewColor;
@property (nonatomic) AWEUGLoadActivityErrorView errorView;
@property (nonatomic) q throwLynxScrollEvent;
@property (nonatomic) NSString tabID;
@property (nonatomic) BOOL usedForUGContainer;
@property (nonatomic) BDXMultiDelegate multiDelegate;
@property (nonatomic) BOOL hasBindTouchObserver;
@property (nonatomic) BOOL forbidTrackStayTime;
@property (nonatomic) BOOL needReloadWhenAppear;
@property (nonatomic) NSString channel;
@property (nonatomic) q viewGeckoVersion;
@property (nonatomic) q localGeckoVersion;
@property (nonatomic) q currentP0Version;
@property (nonatomic) q currentP1Version;
@property (nonatomic) NSString reloadSchema;
@property (nonatomic) NSString backupSchema;
@property (nonatomic) <AWEXTabBaseChannelControllerProtocol> channelController;
@property (nonatomic) NSString referString;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q type;
- (BOOL)canRefresh;
- (id)referString;
- (void)container:didFinishLoadWithURL:;
- (void)container:didLoadFailedWithUrl:error:;
- (void)containerWillStartLoading:;
- (void)container:didFetchedResource:error:;
- (void)container:didRecieveError:;
- (void)didFinishLogin;
- (void)didFinishLogoutWithUid:;
- (void)pauseWithAnimation;
- (void)setReferString:;
- (BOOL)currentTabIsTop;
- (void)animatedRefreshWithCompletion:;
- (BOOL)onSegmentRepeatedClickWithIndex:;
- (id)channelController;
- (void)setChannelController:;
- (id)awe_staytimeKey;
- (id)animatedRefreshCompletion;
- (void)recordStartTime;
- (id)backupSchema;
- (void)setBackupSchema:;
- (void)didReceiveMemoryWarningNotification:;
- (id)originSchema;
- (void)setOriginSchema:;
- (void)setTabID:;
- (void)selfPanned:;
- (BOOL)hasViewDidAppear;
- (void)setHasViewDidAppear:;
- (void)updateTopBarAlpha:;
- (void)setLocalGeckoVersion:;
- (long long)localGeckoVersion;
- (void)setAnimatedRefreshCompletion:;
- (void)reloadWithSchema:extraParams:;
- (void)setupSchema:;
- (id)lynxPanGes;
- (void)stopMainAnimatedRefresh;
- (void)pageRefreshedWithCompletion;
- (id)initWithSchema:extraParams:;
- (BOOL)disableShake;
- (void)setLynxPanGes:;
- (void)setActivityVC:;
- (id)activityVC;
- (double)slidingHeight;
- (id)topBarBackgroundView;
- (void)setTopBarBackgroundView:;
- (void)setSlidingHeight:;
- (void)logCampaignViewLoadResult:loadUrlResult:activityID:isFlowerContainer:;
- (void)setUsedForUGContainer:;
- (BOOL)usedForUGContainer;
- (void)logGetRealSchema:withSuccess:originSchema:activityID:isFlowerContainer:;
- (void)setDisableShake:;
- (void)subscriberEvent;
- (BOOL)needReloadWhenAppear;
- (void)setViewGeckoVersion:;
- (void)setNeedReloadWhenAppear:;
- (id)reloadSchema;
- (void)setReloadSchema:;
- (void)rebuildActivityVCWithSchema:;
- (BOOL)shouldUseCampaignMemoryStrategy;
- (void)reportStayTime;
- (id)createActivityViewController:;
- (void)clearActivityVC;
- (void)rebuildActivityVC;
- (void)campaignMemoryMonitorNotification:;
- (void)handleAppDidBecomeActive;
- (void)xTabReloadPageBridgeNotification:;
- (void)staticSettingDidUpdateWithNotification:;
- (void)nativeCallViewWillAppearNotification:;
- (void)nativeCallViewDidAppearNotification:;
- (void)updateTopBarClolorWithString:;
- (void)updateGeckoIfNeededForVersion:;
- (long long)currentP0Version;
- (long long)viewGeckoVersion;
- (void)logTabHotReloadWithViewGeckoVersion:targetGeckoVersion:refreshType:triggerVersion:;
- (long long)currentP1Version;
- (void)setTopBarBackgroundViewColor:;
- (id)topBarBackgroundViewColor;
- (void)updateSettingGeckoVersionIfNeeded;
- (void)setCurrentP0Version:;
- (void)setCurrentP1Version:;
- (void)setThrowLynxScrollEvent:;
- (void)setForbidTrackStayTime:;
- (id)mainScrollViewName;
- (id)recursivelyFindLynxScrollView:;
- (long long)throwLynxScrollEvent;
- (BOOL)hasBindTouchObserver;
- (void)setHasBindTouchObserver:;
- (void)bindGestureObserversIfNeeded;
- (id)findLynxScrollViewFromVC;
- (void)scrollContentOffsetForGraduallyShowMode:;
- (BOOL)forbidTrackStayTime;
- (id)getActivityId;
- (void)setMainScrollViewName:;
- (id)multiDelegate;
- (void)setMultiDelegate:;
- (void)setScrollEnabled:;
- (id)schema;
- (BOOL)isShowing;
- (void)dealloc;
- (void)play;
- (void)setSchema:;
- (void)viewDidLayoutSubviews;
- (id)channel;
- (void)viewDidLoad;
- (void)reload;
- (void)setChannel:;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)viewDidDisappear:;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:shouldReceiveTouch:;
- (BOOL)gestureRecognizer:shouldRequireFailureOfGestureRecognizer:;
- (void)viewDidAppear:;
- (void)stop;
- (void)pause;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (id)mainScrollView;
- (void)setMainScrollView:;
- (void)setupUI;
- (id)activityId;
- (void)setActivityId:;
- (void)addObservers;
- (id)tabID;
- (void)handleAppWillResignActive;
- (id)errorView;
- (void)setErrorView:;
- (void)setIsShowing:;
@end
