@interface AWEAwemeOfflineTableViewCell : UITableViewCell
@property (nonatomic) BOOL isPad;
@property (nonatomic) UIView offlineCellMaskView;
@property (nonatomic) AWEAwemeModel aweModel;
@property (nonatomic) q indexPath;
@property (nonatomic) AWEAwemeOfflineCellViewController viewController;
@property (nonatomic) double defaultSeekToTime;
@property (nonatomic) NSString reactId;
@property (nonatomic) NSString previousPage;
@property (nonatomic) UIViewController parentVC;
@property (nonatomic) BOOL shouldHideMusicInfo;
@property (nonatomic) BOOL shouldShowGoodsElement;
@property (nonatomic) BOOL shouldShowGoodsCardAnchorElement;
@property (nonatomic) NSString offlineEnterFrom;
@property (nonatomic) NSString offlineReferString;
@property (nonatomic) NSDictionary context;
@property (nonatomic) BOOL isActive;
@property (nonatomic) BOOL hasEntryFullPage;
@property (nonatomic) AWEAwemeModel registerElementModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL hadPrepareToDisplay;
@property (nonatomic) NSString referString;
@property (nonatomic) q cellDisplayState;
@property (nonatomic) q cellPageAppearState;
@property (nonatomic) @? currentCellPageAppearStateBlock;
@property (nonatomic) ^{EngineAudioWrapper=^?^?^?^?^v} audioWrapper;
@property (nonatomic) ^{EngineVideoWrapper=^?^?^v} videoWrapper;
@property (nonatomic) UIView feedTableViewCellMaskView;
@property (nonatomic) <UIScrollViewDelegate> scrollViewDelegate;
- (id)reactId;
- (void)setReactId:;
- (id)referString;
- (void)pauseWithAnimation;
- (void)setReferString:;
- (double)defaultSeekToTime;
- (BOOL)isScrolledAutomatically;
- (void)setIsScrolledAutomatically:;
- (id)audioWrapper;
- (void)setAudioWrapper:;
- (id)videoWrapper;
- (void)setVideoWrapper:;
- (void)setDefaultSeekToTime:;
- (id)aAWEPadModuleAdapter;
- (id)registerElementModel;
- (void)setRegisterElementModel:;
- (void)configWithModel:;
- (long long)cellDisplayState;
- (void)setCellDisplayState:;
- (long long)cellPageAppearState;
- (void)setCellPageAppearState:;
- (id)currentCellPageAppearStateBlock;
- (void)setCurrentCellPageAppearStateBlock:;
- (void)removeCellChildVCForMemoryOpt;
- (void)configWithModel:parentVC:;
- (id)aweModel;
- (void)setAweModel:;
- (BOOL)shouldHideMusicInfo;
- (void)setShouldHideMusicInfo:;
- (BOOL)shouldShowGoodsElement;
- (void)setShouldShowGoodsElement:;
- (BOOL)shouldShowGoodsCardAnchorElement;
- (void)setShouldShowGoodsCardAnchorElement:;
- (BOOL)hasEntryFullPage;
- (void)setHasEntryFullPage:;
- (void)adjustVideoFrameIfNeeded;
- (void)addChildVC;
- (void)removeChildVC;
- (void)setOfflineCellMaskView:;
- (id)offlineCellMaskView;
- (void)removeOfflineCellMaskView;
- (id)offlineEnterFrom;
- (id)offlineReferString;
- (void)addOfflineCellMaskView:;
- (void)setOfflineEnterFrom:;
- (void)setOfflineReferString:;
- (void)setIsActive:;
- (void)dealloc;
- (void)play;
- (long long)indexPath;
- (void)prepareForReuse;
- (void)prepareForDisplay;
- (id)viewController;
- (void)setIndexPath:;
- (void)setContext:;
- (void)setIsPad:;
- (void).cxx_destruct;
- (void)reset;
- (BOOL)isActive;
- (id)context;
- (BOOL)isPad;
- (void)stop;
- (void)pause;
- (void)setViewController:;
- (BOOL)accessibilityScroll:;
- (id)previousPage;
- (void)setPreviousPage:;
- (void)configureWithModel:;
- (void)didEndDisplaying;
- (void)willDisplay;
- (id)parentVC;
- (void)setParentVC:;
+ (Class)aAWEPadModuleAdapterClass;
+ (id)reuseIdentifierWithMediaType:;
+ (id)reuseIdentifierWithMediaType:isFakeAweme:;
@end
