@interface AWEAdCommentBaseViewController : UIViewController
@property (nonatomic) NSDictionary extraParams;
@property (nonatomic) UITableView tableView;
@property (nonatomic) AWEAdFeedCommentViewController commentViewController;
@property (nonatomic) <AWECommentListServiceContainerProtocol> commentServiceContainerDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setCommentServiceContainerDelegate:;
- (id)commentServiceContainerDelegate;
- (long long)businessServiceDataSourceCount;
- (id)identifierForBusinessServiceDataSourceInSection:;
- (id)replyCountForSection:;
- (void)updateReplyCountForSection:count:;
- (void)setExtraParams:;
- (id)extraParams;
- (id)commentViewController;
- (void)setCommentViewController:;
- (void)container_changeServiceContainerPage:;
- (BOOL)container_shouldTriggerAccessCommentCell;
- (long long)container_scrollView:numberOfRowsInSection:;
- (double)container_scrollView:heightForRowAtIndexPath:;
- (double)container_scrollView:heightForHeaderInSection:;
- (double)container_scrollView:heightForFooterInSection:;
- (id)container_scrollView:viewForHeaderInSection:;
- (id)container_scrollView:viewForFooterInSection:;
- (void)container_scrollView:willDisplayHeaderView:forSection:;
- (void)container_scrollView:didEndDisplayingHeaderView:forSection:;
- (void)container_scrollView:willDisplayFooterView:forSection:;
- (void)container_scrollView:didEndDisplayingFooterView:forSection:;
- (void)container_scrollView:didSelectRowAtIndexPath:;
- (id)container_scrollViewT:cellForRowAtIndexPath:;
- (void)container_scrollViewT:cellOfContainer:atIndexPath:;
- (void)container_scrollViewT:willDisplayCell:forRowAtIndexPath:;
- (void)container_scrollViewT:didEndDisplayingCell:forRowAtIndexPath:;
- (void)setTableView:;
- (void)viewDidLoad;
- (id)tableView;
- (long long)sectionForIdentifier:;
- (void).cxx_destruct;
- (id)currentList;
+ (void)configBusinessCommentListServiceContainerWithAweme:vc:colorMode:businessExtraParams:;
@end
