@interface AWEAdItemCommentEggModel : MTLModel
@property (nonatomic) NSString sourceURL;
@property (nonatomic) NSString sourceType;
@property (nonatomic) AWEURLModel sourceURLList;
@property (nonatomic) NSString openURL;
@property (nonatomic) NSString webURL;
@property (nonatomic) NSString regex;
@property (nonatomic) NSString ID;
@property (nonatomic) NSString complianceData;
@property (nonatomic) BOOL isDownloadCompleted;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString webTitle;
@property (nonatomic) BOOL isH5;
@property (nonatomic) BOOL isLynx;
@property (nonatomic) NSString lynxURL;
@property (nonatomic) NSMutableDictionary componentStages;
@property (nonatomic) <AWEAdPreloadComponentContext> componentContext;
- (id)componentContext;
- (void)setComponentContext:;
- (void)setOpenURL:;
- (void)setComplianceData:;
- (id)complianceData;
- (id)sourceURLList;
- (void)setIsDownloadCompleted:;
- (id)componentRefer;
- (id)componentCreativeID;
- (id)componentLogExtra;
- (id)componentGroupID;
- (id)componentExtraID;
- (id)componentStages;
- (void)setComponentStages:;
- (void)setSourceURLList:;
- (BOOL)isDownloadCompleted;
- (void)setSourceType:;
- (id)sourceType;
- (void)setID:;
- (id)ID;
- (id)regex;
- (id)init;
- (id)sourceURL;
- (void)setWebURL:;
- (id)componentType;
- (void)setRegex:;
- (void).cxx_destruct;
- (void)setSourceURL:;
- (id)webURL;
- (id)openURL;
+ (id)JSONKeyPathsByPropertyKey;
+ (unsigned long long)storageBehaviorForPropertyWithKey:;
@end
