@interface AWEBizDowngradeSettingViewController : UIViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) UITableView tableView;
@property (nonatomic) NSMutableArray itemArray;
@property (nonatomic) UIView sectionFooterView;
@property (nonatomic) UILabel discriptionLabel;
@property (nonatomic) NSString referString;
@property (nonatomic) NSNumber preFluencySwitch;
@property (nonatomic) NSNumber prePowerSwitch;
@property (nonatomic) q highlightType;
@property (nonatomic) BOOL needInvisibleToast;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)itemArray;
- (void)setItemArray:;
- (id)referString;
- (void)setEnterFrom:;
- (BOOL)configWithRouterParamDict:;
- (id)enterFrom;
- (void)presentHalfScreenVC:withView:;
- (void)setNeedInvisibleToast:;
- (void)highlightCellIfNeeded;
- (id)selectItemModelWithTitle:settingIndexValue:isSelected:;
- (BOOL)needInvisibleToast;
- (void)p_highlightCellIfNeeded;
- (void)highlightCellWithIndex:;
- (void)createDataSource;
- (id)sectionFooterView;
- (id)p_highlightIndexPathWithType:;
- (void)speedPerformancePageShow;
- (void)setFooterView;
- (void)setPreFluencySwitch:;
- (id)powerSwitchNum;
- (void)setPrePowerSwitch:;
- (void)speedPerformancePageLeave;
- (id)discriptionLabel;
- (id)fluencyItem;
- (id)energyItem;
- (void)fluencySwitchValueChanged:;
- (id)energyDetail;
- (void)didTapEnergyItem;
- (void)speedPerformanceButtonClick:;
- (id)prepareSheetItemsOnVC:;
- (id)subtitleSelectItemModelWithTitle:subtitle:settingIndexValue:isSelected:;
- (void)actionAfterTap;
- (id)preFluencySwitch;
- (id)prePowerSwitch;
- (void)setSectionFooterView:;
- (void)setDiscriptionLabel:;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (void)dealloc;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)setHighlightType:;
- (long long)highlightType;
- (void)viewDidLoad;
- (id)tableView;
- (void).cxx_destruct;
- (void)viewDidAppear:;
+ (id)settingSearchRegisterDic;
+ (unsigned long long)itemStatusWithSettingItem:;
@end
