@interface AWEBindGuideStrategyService : HTSService
@property (nonatomic) BOOL isRequesting;
@property (nonatomic) BOOL isMyTabRedDotShow;
@property (nonatomic) AWEBindStrategyModel model;
@property (nonatomic) AWEBindGuideTaskModel shownTaskModel;
@property (nonatomic) AWEBindGuideSceneModel shownSceneModel;
@property (nonatomic) DUXContentSheet sheet;
@property (nonatomic) AWEAlertCallbackWrapper callbackWrapper;
@property (nonatomic) AWEAlertContext alertContext;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)didFinishLogin;
- (void)sheetDidClickMaskArea:;
- (void)sheetDidClickCloseButton:;
- (void)sheetDidDismiss:;
- (void)sheetDidDragToDismiss:;
- (BOOL)isRequesting;
- (void)setIsRequesting:;
- (id)alertContext;
- (void)setAlertContext:;
- (id)callbackWrapper;
- (void)setCallbackWrapper:;
- (id)currentTaskId;
- (void)trackGuideShow;
- (BOOL)shouldShowBindGuideRedDotEnterFrom:;
- (BOOL)shouldShowBindGuideEnterFrom:;
- (void)showBindGuideIfNeedEnterFrom:context:callbackWrapper:;
- (id)bindRedDotDisplayModelWithScene:;
- (id)bindRedDotDefaultModel;
- (id)redDotTypeMap;
- (void)transferToLinkIfNeed:params:;
- (void)updateBindRedDotDataCompletion:;
- (void)recordRedDotShow;
- (void)recordRedDotClickScene:;
- (void)readStorageModelIfNeed;
- (void)requestDataIfNeed;
- (void)networkingReachabilityDidChange;
- (void)updateMyTabRedDotShow;
- (BOOL)shouldShowBindGuideEnterFrom:isRedDot:;
- (BOOL)baseCheck:uid:;
- (void)showBindGuideAfterRequestUid:enterFrom:;
- (void)requestDataUid:completion:;
- (BOOL)shouldUseBindRedDot;
- (BOOL)IsNowInDayInterval:lastShowDate:;
- (BOOL)hasAlertToShow;
- (BOOL)isRedDotFrequencySatisfiedWithDisplayTotalTimes:displayInterval:taskId:uid:configModel:;
- (void)canShowUid:enterFrom:isRedDot:completion:;
- (void)logForItem:message:uid:enterFrom:;
- (void)showPanelEnterFrom:sceneModel:taskModel:uid:;
- (void)setIsMyTabRedDotShow:;
- (BOOL)needRequestServerUid:;
- (void)handleRequestResult:error:uid:;
- (void)storeRequestResult:uid:;
- (id)strategyKeyUid:;
- (void)forceReadStorageModel;
- (BOOL)isFrequencySatisfied:uid:enterFrom:;
- (void)setShownSceneModel:;
- (void)setShownTaskModel:;
- (void)leftBtnClicked;
- (void)highLightRightBtnClicked;
- (void)notHighLightRightBtnClicked;
- (void)trackGuideClickType:;
- (id)shownSceneModel;
- (id)shownTaskModel;
- (void)trackForAlertClickType:;
- (id)sceneToEnterFromMap;
- (void)trackForAlertCloseType:;
- (void)resetRedDotShow;
- (BOOL)isMyTabRedDotShow;
- (void)startup;
- (void)setModel:;
- (void)dealloc;
- (id)model;
- (void).cxx_destruct;
- (id)sheet;
- (void)setSheet:;
@end
