@interface AWECodeGenShareModel : AWEBaseDataModel
@property (nonatomic) NSString shareUrl;
@property (nonatomic) NSString shareWeiboDesc;
@property (nonatomic) NSString shareDesc;
@property (nonatomic) NSString shareTitle;
@property (nonatomic) AWECodeGenUrlModel shareQrcodeUrlModel;
@property (nonatomic) NSString manageGoodsUrl;
@property (nonatomic) AWECodeGenUrlModel shareImageUrlModel;
@property (nonatomic) NSInteger boolPersist;
@property (nonatomic) NSString goodsRecUrl;
@property (nonatomic) NSString shareTitleMyself;
@property (nonatomic) NSString shareTitleOther;
@property (nonatomic) NSString shareLinkDesc;
@property (nonatomic) NSString shareSignatureUrl;
@property (nonatomic) NSString shareSignatureDesc;
@property (nonatomic) NSString shareQuote;
@property (nonatomic) NSString whatsappDesc;
@property (nonatomic) NSString shareDescInfo;
@property (nonatomic) NSString shareShortenBelong;
@property (nonatomic) NSString shareChannelConfig;
@property (nonatomic) NSString lifeShareExt;
- (void)setShareWeiboDesc:;
- (void)setShareDesc:;
- (void)setShareTitle:;
- (void)setShareTitleMyself:;
- (void)setShareTitleOther:;
- (void)setShareLinkDesc:;
- (void)setShareSignatureUrl:;
- (void)setShareSignatureDesc:;
- (void)setShareQuote:;
- (void)setWhatsappDesc:;
- (void)setShareDescInfo:;
- (void)setShareShortenBelong:;
- (void)setShareChannelConfig:;
- (void)setLifeShareExt:;
- (void)setShareUrl:;
- (id)shareDesc;
- (id)shareWeiboDesc;
- (id)shareLinkDesc;
- (id)shareUrl;
- (id)lifeShareExt;
- (id)shareSignatureDesc;
- (id)shareSignatureUrl;
- (id)shareChannelConfig;
- (id)shareShortenBelong;
- (id)shareTitleMyself;
- (id)shareTitleOther;
- (id)shareQrcodeUrlModel;
- (void)setShareQrcodeUrlModel:;
- (id)manageGoodsUrl;
- (void)setManageGoodsUrl:;
- (id)shareImageUrlModel;
- (void)setShareImageUrlModel:;
- (id)goodsRecUrl;
- (void)setGoodsRecUrl:;
- (void).cxx_destruct;
- (id)shareTitle;
- (int)boolPersist;
- (id)whatsappDesc;
- (id)shareDescInfo;
- (id)shareQuote;
- (void)setBoolPersist:;
+ (id)JSONKeyPathsByPropertyKey;
@end
