@interface AWECampaignKSetting : MTLModel
@property (nonatomic) q randomTime;
@property (nonatomic) q roundRobinInterval;
@property (nonatomic) NSArray popups;
@property (nonatomic) NSArray redPacketResources;
@property (nonatomic) NSArray noticeInfo;
@property (nonatomic) NSArray noticeMultiInfo;
@property (nonatomic) NSArray activityButton;
@property (nonatomic) NSDictionary fcoinInfo;
@property (nonatomic) NSDictionary fcoinNotLoginConfig;
@property (nonatomic) NSDictionary feedPendantInfo;
@property (nonatomic) NSArray activityCardInfos;
@property (nonatomic) q version;
@property (nonatomic) q onlineVersion;
@property (nonatomic) AWEPineappleCampaignKPopupModel popupsConfig;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (long long)randomTime;
- (void)setRandomTime:;
- (id)feedPendantInfo;
- (void)setFeedPendantInfo:;
- (id)fcoinInfo;
- (id)fcoinNotLoginConfig;
- (id)redPacketResources;
- (id)noticeInfo;
- (id)noticeMultiInfo;
- (id)popupsConfig;
- (long long)onlineVersion;
- (long long)feedOnlineVersion;
- (long long)roundRobinInterval;
- (id)activityCardInfos;
- (void)setActivityCardInfos:;
- (void)setOnlineVersion:;
- (void)setRoundRobinInterval:;
- (void)setRedPacketResources:;
- (void)setNoticeInfo:;
- (void)setNoticeMultiInfo:;
- (void)setFcoinInfo:;
- (void)setFcoinNotLoginConfig:;
- (void)setPopupsConfig:;
- (long long)version;
- (void)setVersion:;
- (void).cxx_destruct;
- (id)activityButton;
- (void)setActivityButton:;
- (id)popups;
- (void)setPopups:;
+ (id)popupsJSONTransformer;
+ (id)popupsConfigJSONTransformer;
+ (id)redPacketResourcesJSONTransformer;
+ (id)noticeInfoJSONTransformer;
+ (id)noticeMultiInfoJSONTransformer;
+ (id)activityButtonJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
