@interface AWECloudAlbumDetailPublishProcessor : NSObject
@property (nonatomic) <AWECloudAlbumPublishProcessorDataSource> dataSource;
@property (nonatomic) NSArray publishAssets;
@property (nonatomic) NSMutableArray lostAssets;
@property (nonatomic) NSMutableDictionary publishAssetDic;
@property (nonatomic) BOOL isDownloadTaskRunning;
@property (nonatomic) Q downloadFlag;
@property (nonatomic) NSMutableArray downloadAssets;
@property (nonatomic) q saveIndex;
@property (nonatomic) q retryDownloadNumber;
@property (nonatomic) UIView<ACCTextLoadingViewProtcol> loadingView;
@property (nonatomic) BOOL canceled;
@property (nonatomic) AWEAlbumDefaultViewModel albumViewModel;
@property (nonatomic) <AWECloudAlbumPublishProcessorDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)taskItemChanges:;
- (void)taskProgressChanges:;
- (void)taskStateChanges:;
- (id)albumViewModel;
- (void)setAlbumViewModel:;
- (id)assetIDsWithAssets:;
- (void)p_resetPublishState;
- (void)setPublishAssets:;
- (id)p_verifyAssets:errorTips:;
- (id)lostAssets;
- (void)p_downloadAsset:;
- (BOOL)isDownloadTaskRunning;
- (long long)saveIndex;
- (void)setSaveIndex:;
- (void)p_checkCloudDownloadComplete;
- (id)publishAssetDic;
- (void)setLostAssets:;
- (void)setPublishAssetDic:;
- (void)setIsDownloadTaskRunning:;
- (void)setDownloadFlag:;
- (void)setDownloadAssets:;
- (void)setRetryDownloadNumber:;
- (unsigned long long)downloadFlag;
- (void)p_fetchSandBoxPublishModelWithAssets:cloudAssets:;
- (void)p_fetchLocalPublishModelWithLocalAssets:cloudAssets:;
- (BOOL)p_fetchCloudPublishModelWithAssets:;
- (void)p_checkDownloadComplete;
- (void)p_startDownloadCloudAsset:;
- (id)downloadAssets;
- (long long)retryDownloadNumber;
- (void)p_gotoEditPage;
- (id)generateAlbumViewModelWith:;
- (id)publishAssets;
- (BOOL)isCanceled;
- (id)delegate;
- (id)initWithDataSource:;
- (void)setLoadingView:;
- (id)loadingView;
- (void)setCanceled:;
- (void).cxx_destruct;
- (void)publish:;
- (void)setDataSource:;
- (void)setDelegate:;
- (id)dataSource;
@end
