@interface AWECityModel : MTLModel
@property (nonatomic) NSString name;
@property (nonatomic) NSString cityName;
@property (nonatomic) NSString code;
@property (nonatomic) NSString districtCode;
@property (nonatomic) NSNumber districtType;
@property (nonatomic) NSString en;
@property (nonatomic) NSString cnPinyin;
@property (nonatomic) NSString displayName;
@property (nonatomic) NSString displayNameEn;
@property (nonatomic) q displayType;
@property (nonatomic) NSString country;
@property (nonatomic) NSString countryCode;
@property (nonatomic) NSString adCode;
@property (nonatomic) NSString currentPositionName;
@property (nonatomic) NSArray districtsArray;
@property (nonatomic) NSString L2CityName;
@property (nonatomic) NSArray l2ReCodeList;
@property (nonatomic) <IESLLCityModel> upperCity;
@property (nonatomic) BOOL isL3;
@property (nonatomic) NSArray subCities;
@property (nonatomic) NSArray center;
@property (nonatomic) NSString level;
@property (nonatomic) NSString asciName;
@property (nonatomic) NSString grouponCityName;
@property (nonatomic) BOOL isSchoolCircle;
@property (nonatomic) BOOL needForceBackToNormalNearby;
@property (nonatomic) BOOL isChannelPage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString name;
@property (nonatomic) NSString cityName;
@property (nonatomic) NSString code;
@property (nonatomic) NSString districtCode;
@property (nonatomic) NSNumber districtType;
@property (nonatomic) NSString en;
@property (nonatomic) NSString cnPinyin;
@property (nonatomic) NSString displayName;
@property (nonatomic) NSString displayNameEn;
@property (nonatomic) q displayType;
@property (nonatomic) NSString country;
@property (nonatomic) NSString countryCode;
@property (nonatomic) NSString adCode;
@property (nonatomic) NSString localizedName;
@property (nonatomic) NSString nearbyLabelName;
@property (nonatomic) NSString nearbyTabName;
@property (nonatomic) NSString currentPositionName;
@property (nonatomic) NSArray districtsArray;
@property (nonatomic) NSString L2CityName;
@property (nonatomic) NSArray l2ReCodeList;
@property (nonatomic) AWECityModel upperCity;
@property (nonatomic) BOOL isL3;
@property (nonatomic) NSArray subCities;
@property (nonatomic) NSArray center;
@property (nonatomic) NSString level;
@property (nonatomic) NSString asciName;
@property (nonatomic) NSString grouponCityName;
@property (nonatomic) BOOL isSchoolCircle;
@property (nonatomic) BOOL needForceBackToNormalNearby;
@property (nonatomic) BOOL isChannelPage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)districtCode;
- (void)setDistrictCode:;
- (id)asciName;
- (void)setAsciName:;
- (id)nearbyTabName;
- (void)setNearbyTabName:;
- (id)nearbyLabelName;
- (void)setNearbyLabelName:;
- (id)currentPositionName;
- (void)setCurrentPositionName:;
- (id)grouponCityName;
- (void)setGrouponCityName:;
- (id)L2CityName;
- (id)l2ReCodeList;
- (BOOL)isL3;
- (id)subCities;
- (void)setNeedForceBackToNormalNearby:;
- (BOOL)isSchoolCircle;
- (void)setIsChannelPage:;
- (id)cnPinyin;
- (id)upperCity;
- (BOOL)isChannelPage;
- (id)districtType;
- (void)setDistrictType:;
- (id)en;
- (void)setEn:;
- (void)setCnPinyin:;
- (id)displayNameEn;
- (void)setDisplayNameEn:;
- (id)adCode;
- (void)setAdCode:;
- (id)districtsArray;
- (void)setDistrictsArray:;
- (void)setL2CityName:;
- (void)setL2ReCodeList:;
- (void)setUpperCity:;
- (void)setIsL3:;
- (void)setSubCities:;
- (void)setIsSchoolCircle:;
- (BOOL)needForceBackToNormalNearby;
- (void)setLevel:;
- (id)code;
- (id)country;
- (id)displayName;
- (void)setCountryCode:;
- (id)level;
- (void)setCode:;
- (long long)displayType;
- (void)setDisplayName:;
- (void)setDisplayType:;
- (id)localizedName;
- (id)center;
- (void)setCenter:;
- (void).cxx_destruct;
- (id)countryCode;
- (void)setCountry:;
- (void)setName:;
- (id)name;
- (id)cityName;
- (void)setCityName:;
+ (id)districtsArrayJSONTransformer;
+ (id)subCitiesJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
