@interface AWEConcernGoodsLifeFeedSpu : MTLModel
@property (nonatomic) NSString ID;
@property (nonatomic) NSString name;
@property (nonatomic) NSArray images;
@property (nonatomic) NSString activityPrice;
@property (nonatomic) NSString originPrice;
@property (nonatomic) NSString discountInfo;
@property (nonatomic) NSArray saleTags;
@property (nonatomic) NSString soldCountTag;
@property (nonatomic) q soldCount;
@property (nonatomic) NSString detailSchema;
@property (nonatomic) NSArray rateComments;
@property (nonatomic) NSString activityText;
@property (nonatomic) NSString activityPriceSuffix;
@property (nonatomic) AWEConcernGoodsLifeFeedSpuPriceTag priceTag;
@property (nonatomic) AWECOncernGoodsLifeFeedSpuExtraInfo extra;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setExtra:;
- (id)activityPrice;
- (void)setActivityPrice:;
- (id)originPrice;
- (void)setOriginPrice:;
- (id)discountInfo;
- (void)setDiscountInfo:;
- (id)saleTags;
- (void)setSaleTags:;
- (id)soldCountTag;
- (void)setSoldCountTag:;
- (long long)soldCount;
- (void)setSoldCount:;
- (id)detailSchema;
- (void)setDetailSchema:;
- (id)rateComments;
- (void)setRateComments:;
- (id)activityPriceSuffix;
- (void)setActivityPriceSuffix:;
- (id)priceTag;
- (void)setPriceTag:;
- (id)images;
- (void)setID:;
- (id)ID;
- (id)extra;
- (void)setImages:;
- (void).cxx_destruct;
- (void)setName:;
- (id)name;
- (id)activityText;
- (void)setActivityText:;
+ (id)activityPriceJSONTransformer;
+ (id)originPriceJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)imagesJSONTransformer;
+ (id)IDJSONTransformer;
@end
