@interface AWEChallengeDetailIntroductionView : UIView
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) AWEChallengeFoldingTextView descriptionTextView;
@property (nonatomic) AWEChallengeModel challenge;
@property (nonatomic) UIView descriptionLabelContainer;
@property (nonatomic) BOOL useSelectableView;
@property (nonatomic) <AWEChallengeDetailIntroductionViewDelegate> delegate;
@property (nonatomic) UIView<AWEChallengeDetailTaskInfoView> taskView;
@property (nonatomic) UIView<AWEFoldingLabel> descriptionLabel;
@property (nonatomic) UIView<AWEFoldingLabel> disclaimerLabel;
@property (nonatomic) BOOL isHalfScreen;
@property (nonatomic) q halfScreenStyle;
@property (nonatomic) UIView<AWEStarActivityEntranceViewProtocol> starActivityEntranceView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)starActivityEntranceView;
- (void)updateDescriptionLabelWithChallenge:;
- (id)layoutWithConstrainedWidth:;
- (void)updateWithChallenge:;
- (BOOL)label:shouldTreatAsInteractiveElementForCheckingResult:;
- (id)label:attributesForCheckingResult:;
- (void)buttonDidTapped:;
- (void)labelDidUnfold:;
- (void)labelDidFold:;
- (void)label:didInteractWithURL:;
- (void)setIsHalfScreen:;
- (BOOL)isHalfScreen;
- (long long)halfScreenStyle;
- (void)setHalfScreenStyle:;
- (id)taskView;
- (id)descriptionLabelContainer;
- (BOOL)hasStarUserData:;
- (BOOL)useSelectableView;
- (void)updateDescriptionTextViewWithChallenge:;
- (void)updateDescriptionTextViewContainerLayoutWithConstrainedWidth:recentlyPositionedView:;
- (void)updateDescriptionLabelContainerLayoutWithConstrainedWidth:recentlyPositionedView:;
- (void)descriptionLabelContainerTapped:;
- (BOOL)isBaike;
- (void)trackBaikeShow;
- (void)descriptionTextViewContainerTapped:;
- (id)baikeDocID;
- (void)goToBaike;
- (void)textViewDidUnfold:;
- (void)textViewDidFold:;
- (void)textView:didInteractWithURL:;
- (void)textViewButtonDidTapped:;
- (void)textViewDidSearch:;
- (void)textViewDidShowSearchMenu:;
- (void)setDescriptionLabelContainer:;
- (void)setStarActivityEntranceView:;
- (void)setUseSelectableView:;
- (id)delegate;
- (id)intrinsicContentSize;
- (id)initWithFrame:;
- (id)challenge;
- (void)setChallenge:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (id)descriptionLabel;
- (void)setDelegate:;
- (void)layoutSubviews;
- (id)descriptionTextView;
- (void)setDescriptionTextView:;
- (id)disclaimerLabel;
+ (double)preferedContentLineHeight;
+ (double)preferedContentLineSpacing;
@end
