@interface AWEChallengeDetailFeedSectionViewModel : AWEBaseListSectionViewModel
@property (nonatomic) NSArray slideList;
@property (nonatomic) NSArray taskModels;
@property (nonatomic) q contentType;
@property (nonatomic) NSString enterFromPageString;
@property (nonatomic) NSString enterMethodString;
@property (nonatomic) NSMutableDictionary logExtraDict;
@property (nonatomic) NSDictionary searchLogPassback;
@property (nonatomic) NSString searchType;
@property (nonatomic) NSString hashTagProcessId;
@property (nonatomic) NSString hashTagId;
@property (nonatomic) BOOL isHalfScreen;
@property (nonatomic) Q halfScreenStyle;
@property (nonatomic) BOOL feedDataFirstTimeRequestFinished;
@property (nonatomic) NSString processId;
@property (nonatomic) NSString authorID;
@property (nonatomic) BOOL generalSortDataListEmpty;
@property (nonatomic) NSString fromGroupID;
@property (nonatomic) AWESubChallengeModel subChallengeModel;
@property (nonatomic) BOOL isSubChallenge;
@property (nonatomic) AWEChallengeAwemeListDataController dataController;
@property (nonatomic) Q sortType;
@property (nonatomic) NSError networkError;
@property (nonatomic) BOOL loadMoreErrorOrEmpty;
@property (nonatomic) NSString uniqueKey;
@property (nonatomic) BOOL isNewLayoutUI;
@property (nonatomic) NSString trackTabId;
@property (nonatomic) AWEChallengeModel challengeModel;
@property (nonatomic) NSString adLotteryRequirements;
@property (nonatomic) NSString missionID;
@property (nonatomic) BOOL isCommerceChallenge;
@property (nonatomic) NSString challengeId;
@property (nonatomic) NSString hashtagName;
@property (nonatomic) BOOL commerce;
- (void)setLogExtraDict:;
- (id)logExtraDict;
- (void)setDataController:;
- (void)fetchSectionData;
- (BOOL)isCommerce;
- (id)fromGroupID;
- (void)setMissionID:;
- (void)loadMoreSectionData;
- (id)challengeId;
- (id)missionID;
- (id)challengeModel;
- (void)setChallengeModel:;
- (id)networkError;
- (void)setNetworkError:;
- (id)slideList;
- (id)enterFromPageString;
- (void)setIsHalfScreen:;
- (BOOL)isHalfScreen;
- (void)setFromGroupID:;
- (id)searchLogPassback;
- (void)setEnterFromPageString:;
- (void)setSearchLogPassback:;
- (unsigned long long)halfScreenStyle;
- (void)setHalfScreenStyle:;
- (BOOL)isNewLayoutUI;
- (BOOL)isSubChallenge;
- (id)subChallengeModel;
- (id)trackTabId;
- (void)setTrackTabId:;
- (void)setCommerceDataControllerVideoShowType:;
- (void)setIsNewLayoutUI:;
- (void)setAdLotteryRequirements:;
- (void)setEnterMethodString:;
- (void)updateHashtagName:;
- (BOOL)feedDataFirstTimeRequestFinished;
- (void)setSlideList:;
- (void)setTaskModels:;
- (void)updateSortType:;
- (id)recommendedAwemeCoversArrayForShare;
- (id)coverURLStringForShare;
- (id)enterMethodString;
- (void)setIsSubChallenge:;
- (void)setSubChallengeModel:;
- (void)setHashTagProcessId:;
- (void)setGeneralSortDataListEmpty:;
- (id)adLotteryRequirements;
- (void)setIsCommerceChallenge:;
- (void)trackFeedEnterAtIndex:model:;
- (void)trackFeedItemDidTappedAtIndex:model:;
- (void)trackFeedItemWillDisplayAtIndex:model:;
- (long long)modelIndexInHeaderWithModel:;
- (long long)modelIndexInFeedWithModel:;
- (void)appendModelFromDetailTableView:;
- (id)multiColumnLogExtraDictionaryWithModel:;
- (id)dataControllerAfterInsertingSlideList;
- (void)setFeedDataFirstTimeRequestFinished:;
- (void)setLoadMoreErrorOrEmpty:;
- (id)hashTagId;
- (BOOL)isCommerceChallenge;
- (id)copiedDataController;
- (id)multiColumnLogExtraDictionary;
- (id)taskModels;
- (id)hashTagProcessId;
- (BOOL)generalSortDataListEmpty;
- (BOOL)loadMoreErrorOrEmpty;
- (void)setHashTagId:;
- (id)uniqueKey;
- (id)searchType;
- (void)setSearchType:;
- (id)processId;
- (long long)contentType;
- (void)setContentType:;
- (void)setProcessId:;
- (void).cxx_destruct;
- (BOOL)hasMoreData;
- (void)setSortType:;
- (unsigned long long)sortType;
- (id)dataController;
- (id)hashtagName;
- (id)authorID;
- (void)setAuthorID:;
+ (id)viewModelWithChallengeID:hashtagName:authorID:isCommerce:enterFrom:;
@end
