@interface AWEChallengeDetailBaseFeedViewController : AWEBaseListViewController
@property (nonatomic) <UIViewControllerPreviewing> forceTouchToken;
@property (nonatomic) AWEChallengeDetailFeedSectionController feedSectionController;
@property (nonatomic) {CGPoint=dd} originalScrollViewOffset;
@property (nonatomic) UIViewController<AWEChallengeDetailContainerContextProtocol> containerViewController;
@property (nonatomic) <AWEChallengeDetailBaseFeedViewControllerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)listDidReloadDataWithCollectionView:;
- (id)zoomTransitionStartViewForOffset:;
- (void)listDidPerformBatchUpdatesWithCollectionView:;
- (id)sectionControllerClassArray;
- (void)dataSourceDidCreateSectionController:forSectionViewModel:;
- (void)bindViewModel;
- (BOOL)shouldHideNoMoreText;
- (void)unregisterForceTouch;
- (void)setForceTouchToken:;
- (void)showFooter:;
- (void)setFeedSectionController:;
- (id)feedSectionController;
- (void)updateStreamingCellIfNeeded;
- (void)updateContainerOffset:;
- (void)setOriginalScrollViewOffset:;
- (id)originalScrollViewOffset;
- (id)previewingViewControllerAtIndexPath:;
- (void)updateFeedWithDataState:;
- (id)forceTouchToken;
- (id)previewingViewControllerForView:atPoint:;
- (id)previewingSourceRectForView:atPoint:;
- (void)didCommitViewController:;
- (BOOL)checkCellIsInScreen:;
- (void)dealloc;
- (id)delegate;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (void)setContainerViewController:;
- (void)scrollViewWillBeginDragging:;
- (id)containerViewController;
- (void)scrollViewDidEndDecelerating:;
- (void).cxx_destruct;
- (id)navigationController;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void)setDelegate:;
- (void)setupUI;
- (void)setupCollectionView:;
- (void)releaseMemory;
+ (id)controllerWithFeedSectionViewModel:;
@end
