@interface AWECoverTextStickerView : UIView
@property (nonatomic) double fontScale;
@property (nonatomic) double currentScale;
@property (nonatomic) UIView<AWECoverTextStickerProtocol> currentView;
@property (nonatomic) AWECoverTextStoryTextView storyView;
@property (nonatomic) AWECoverTextPackageView packageView;
@property (nonatomic) AWECoverTextPlainTextView plainTextView;
@property (nonatomic) AWECoverTextStoryTextView storyTextView;
@property (nonatomic) BOOL canEdit;
@property (nonatomic) @? coordinateDidChange;
@property (nonatomic) <ACCStickerContainerProtocol> stickerContainer;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setStickerContainer:;
- (id)stickerContainer;
- (id)coordinateDidChange;
- (void)setCoordinateDidChange:;
- (void)contentDidUpdateToScale:;
- (id)initWithFrame:fontScale:;
- (void)updateEditInfo:;
- (void)setPlaceholderHide:;
- (id)viewWithModel:;
- (id)plainTextView;
- (id)storyTextView;
- (void)setPlainTextView:;
- (id)packageView;
- (void)setPackageView:;
- (void).cxx_destruct;
- (void)updateBounds;
- (double)currentScale;
- (void)setCurrentScale:;
- (double)fontScale;
- (void)setFontScale:;
- (BOOL)canEdit;
- (void)setCanEdit:;
- (id)storyView;
- (void)setStoryView:;
- (void)setCurrentView:;
- (id)currentView;
@end
