@interface AWECodeGenShootPositionModel : AWEBaseDataModel
@property (nonatomic) NSString modelID;
@property (nonatomic) NSString name;
@property (nonatomic) AWECodeGenUserModel authorInfoModel;
@property (nonatomic) NSArray coverUrlListModelArray;
@property (nonatomic) NSArray coverUrlListMediumModelArray;
@property (nonatomic) NSArray originCoverUrlListMediumModelArray;
@property (nonatomic) AWECodeGenSicilyUrlModel iconModel;
@property (nonatomic) AWECodeGenLocationInfoModel locationInfoModel;
@property (nonatomic) NSArray guideListModelArray;
@property (nonatomic) AWECodeGenShootSuggestionModel shootSuggestModel;
@property (nonatomic) AWECodeGenShootSuggestionModel moreSuggestModel;
@property (nonatomic) AWECodeGenShootPositionStatsModel statsModel;
@property (nonatomic) AWECodeGenShareModel shareInfoModel;
@property (nonatomic) AWECodeGenOperationLabelModel operationLabelModel;
@property (nonatomic) AWECodeGenStatsLabelModel statsLabelModel;
@property (nonatomic) AWECodeGenCoverThemeColorModel coverThemeColorModel;
@property (nonatomic) AWECodeGenShootPositionBusinessInfoModel businessInfoModel;
@property (nonatomic) AWECodeGenSicilyUrlModel navBarIconModel;
@property (nonatomic) NSString recommendDesc;
@property (nonatomic) NSString logExtra;
@property (nonatomic) NSArray mixIdArray;
@property (nonatomic) NSArray bestCoverUrlListModelArray;
- (void)setLogExtra:;
- (id)logExtra;
- (id)shareInfoModel;
- (void)setShareInfoModel:;
- (void)setAuthorInfoModel:;
- (id)authorInfoModel;
- (id)coverUrlListModelArray;
- (void)setCoverUrlListModelArray:;
- (id)coverUrlListMediumModelArray;
- (void)setCoverUrlListMediumModelArray:;
- (id)originCoverUrlListMediumModelArray;
- (void)setOriginCoverUrlListMediumModelArray:;
- (id)locationInfoModel;
- (void)setLocationInfoModel:;
- (id)guideListModelArray;
- (void)setGuideListModelArray:;
- (id)shootSuggestModel;
- (void)setShootSuggestModel:;
- (id)moreSuggestModel;
- (void)setMoreSuggestModel:;
- (id)statsModel;
- (void)setStatsModel:;
- (id)operationLabelModel;
- (void)setOperationLabelModel:;
- (id)statsLabelModel;
- (void)setStatsLabelModel:;
- (id)coverThemeColorModel;
- (void)setCoverThemeColorModel:;
- (id)businessInfoModel;
- (void)setBusinessInfoModel:;
- (id)navBarIconModel;
- (void)setNavBarIconModel:;
- (id)recommendDesc;
- (void)setRecommendDesc:;
- (id)mixIdArray;
- (void)setMixIdArray:;
- (id)bestCoverUrlListModelArray;
- (void)setBestCoverUrlListModelArray:;
- (void)setModelID:;
- (id)modelID;
- (void).cxx_destruct;
- (void)setIconModel:;
- (void)setName:;
- (id)name;
- (id)iconModel;
+ (id)propertyToModelClassInArrayMap;
+ (id)JSONKeyPathsByPropertyKey;
@end
