@interface AWEChapterAbstractTableViewCell : UITableViewCell
@property (nonatomic) TTTAttributedLabel collapseLabel;
@property (nonatomic) TTTAttributedLabel expandLabel;
@property (nonatomic) UIView bottomLine;
@property (nonatomic) <AWEChapterAbstractTableViewCellDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEChapterContext chapterContext;
@property (nonatomic) BOOL isLoop;
- (void)attributedLabel:didSelectLinkWithTransitInformation:;
- (void)setIsLoop:;
- (void)configWithUIConfig:;
- (void)updateSelectedStatus:;
- (void)configExpandLabelWithAbstractString:;
- (void)configCollapseLabelWithAbstractString:;
- (id)collapseLabel;
- (id)expandLabel;
- (id)chapterContext;
- (void)configureWithChapterInfo:model:context:coverImageLoadCompletion:;
- (void)setChapterContext:;
- (void)configWithAbstractString:isExpanded:;
- (void)setCollapseLabel:;
- (void)setExpandLabel:;
- (id)delegate;
- (id)textFont;
- (BOOL)isLoop;
- (void)prepareForReuse;
- (id)initWithStyle:reuseIdentifier:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)colorNamed:;
- (void)setupSubviews;
- (id)bottomLine;
- (void)setBottomLine:;
+ (double)heightWithAbstractString:width:isExpanded:context:;
+ (double)heightWithChapterInfo:width:context:;
+ (id)identifier;
@end
