@interface AWECloudAlbumDetailListComponent : AWECloudAlbumDetailBaseComponent
@property (nonatomic) <AWECloudAlbumDetailNavigationServiceProtocol> navigationService;
@property (nonatomic) <AWECloudAlbumDetailDataServiceProtocol> dataService;
@property (nonatomic) <AWECloudAlbumDetailBottomServiceProtocol> bottomService;
@property (nonatomic) <AWECloudAlbumDetailDownloadServiceProtocol> downloadService;
@property (nonatomic) <AWECloudAlbumDetailPublishServiceProtocol> publishService;
@property (nonatomic) AWECloudAlbumDetailListViewModel viewModel;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) AWECloudAlbumDetailLoadingView loadingView;
@property (nonatomic) q selectedCellIndex;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)dataService;
- (void)componentDidLoad;
- (void)p_loadMore;
- (void)componentWillAppear;
- (void)setPublishService:;
- (id)publishService;
- (void)setDataService:;
- (void)p_addNotification;
- (void)p_endRefreshing;
- (id)bottomService;
- (void)setBottomService:;
- (id)serviceBinding;
- (id)acc_zoomTransitionStartViewForItemOffset:;
- (void)detailCellDidTapAdd:;
- (id)downloadService;
- (void)p_updateBottomStateAnimated:;
- (void)dataDidChangeTaskStatusWithService:;
- (void)dataDidChangeTaskProgressWithService:;
- (void)dataService:didChangeItems:;
- (void)setDownloadService:;
- (void)bottomDidCancelTaskWithService:;
- (void)bottomDidDeleteSelectedItemsWithService:;
- (void)downloadShouldExitSelectModeWithService:;
- (void)p_updateLoadingView;
- (void)setSelectedCellIndex:;
- (long long)selectedCellIndex;
- (void)p_addMore;
- (void)p_deleteAssetsWithAssets:;
- (void)p_resetDataSource;
- (void)p_onReceivedReloadData:;
- (void)p_removeNotification;
- (void)detailCellDidTapRetry:;
- (void)detailCellDidTapDelete:;
- (void)detailCellDidTapSelect:;
- (void)navigationDidClickSelectWithService:;
- (void)navigationDidClickCancelWithService:;
- (void)navigationDidClickAddContentWithService:;
- (void)publishShouldExitSelectModeWithService:;
- (void)previewController:didRemoveAsset:;
- (void)setNavigationService:;
- (id)collectionView;
- (double)collectionView:layout:minimumLineSpacingForSectionAtIndex:;
- (void)dealloc;
- (double)collectionView:layout:minimumInteritemSpacingForSectionAtIndex:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setLoadingView:;
- (id)viewModel;
- (id)loadingView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (id)navigationService;
@end
