@interface AWECompanyToolBubbleCell : UITableViewCell
@property (nonatomic) UICollectionView companyToolCollectionView;
@property (nonatomic) NSMutableSet selectedBubbleUniqueKeys;
@property (nonatomic) NSMutableArray tempSelectFromFEBubbleArray;
@property (nonatomic) q switchBubbleTimes;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <AWECompanyToolBubbleCellDelegate> delegate;
@property (nonatomic) NSMutableArray bubbleTools;
@property (nonatomic) BOOL disableTrackShowBubble;
- (id)selectedBubbleUniqueKeys;
- (id)p_findBubbleWithUniqueKey:;
- (long long)p_indexOfBubbleUniqueKey:;
- (id)bubbleTools;
- (id)companyToolCollectionView;
- (BOOL)p_isBubbleUniqueKeyInBubbleTools:;
- (id)tempSelectFromFEBubbleArray;
- (void)setSwitchBubbleTimes:;
- (void)addSubviewsForContentView;
- (BOOL)disableTrackShowBubble;
- (long long)switchBubbleTimes;
- (void)scrollToSelectedBubbleIfNeeded;
- (void)didViewModelSelectNewBubble:;
- (void)setBubbleTools:;
- (void)setDisableTrackShowBubble:;
- (void)setCompanyToolCollectionView:;
- (void)setSelectedBubbleUniqueKeys:;
- (void)setTempSelectFromFEBubbleArray:;
- (id)delegate;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)refreshUI;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (id)initWithStyle:reuseIdentifier:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)setDelegate:;
- (void)cleanData;
@end
