@interface AWEChallengeDetailHeaderSectionViewModel : AWEBaseListSectionViewModel
@property (nonatomic) NSString challengeId;
@property (nonatomic) NSString processId;
@property (nonatomic) NSString authorID;
@property (nonatomic) NSString groupID;
@property (nonatomic) NSString enterFromPageString;
@property (nonatomic) NSDictionary searchLogPassback;
@property (nonatomic) BOOL isCommerce;
@property (nonatomic) BOOL isHalfScreen;
@property (nonatomic) Q halfScreenStyle;
@property (nonatomic) BOOL requestFavoriteOnAir;
@property (nonatomic) NSError collectionError;
@property (nonatomic) Q showFavoriteBubbleAction;
@property (nonatomic) NSString challengeName;
@property (nonatomic) BOOL isNewLayoutUI;
@property (nonatomic) BOOL isCommonChallenge;
@property (nonatomic) AWEChallengeModel challengeModel;
- (BOOL)isCommerce;
- (void)setIsCommerce:;
- (id)challengeName;
- (void)setChallengeName:;
- (id)challengeId;
- (void)setChallengeId:;
- (id)challengeModel;
- (id)enterFromPageString;
- (void)setIsHalfScreen:;
- (BOOL)isHalfScreen;
- (id)searchLogPassback;
- (void)setEnterFromPageString:;
- (void)setSearchLogPassback:;
- (unsigned long long)halfScreenStyle;
- (void)setHalfScreenStyle:;
- (BOOL)isNewLayoutUI;
- (void)onFavoriteButtonClicked:;
- (void)setIsNewLayoutUI:;
- (void)setIsCommonChallenge:;
- (BOOL)isCommonChallenge;
- (BOOL)canCollection;
- (void)startCollecting:;
- (void)trackBannerViewShow;
- (void)trackOwnerNameDidTap;
- (void)trackGoButtonDidTap;
- (void)trackBannerViewDidTap;
- (void)trackDidTapFavoriteHintBubble;
- (void)trackVideoCardDidClickAtIndex:;
- (BOOL)isRequestFavoriteOnAir;
- (BOOL)checkNetworkConnected;
- (void)setRequestFavoriteOnAir:;
- (void)setCollectionError:;
- (void)trackCollectionButtonDidTap:;
- (void)processCollectionBubbleWithActionType:isHeaderFavoriteButton:;
- (void)setShowFavoriteBubbleAction:;
- (void)trackAvatarDidTap;
- (unsigned long long)showFavoriteBubbleAction;
- (id)collectionError;
- (void)setGroupID:;
- (id)groupID;
- (id)processId;
- (void)setProcessId:;
- (void).cxx_destruct;
- (id)authorID;
- (void)setAuthorID:;
@end
