@interface AWECommerceAnchorTableViewCell : UITableViewCell
@property (nonatomic) UIImageView iconImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) YYLabel betaLabel;
@property (nonatomic) UIView lineView;
@property (nonatomic) UIView remindView;
@property (nonatomic) UIButton addAnchorButton;
@property (nonatomic) UIImageView accessImageView;
@property (nonatomic) UIView separatorLine;
@property (nonatomic) UILabel tagTitleLabel;
@property (nonatomic) UIButton removeButton;
@property (nonatomic) BOOL disableAndGrey;
@property (nonatomic) @? addAIAnchorBlock;
@property (nonatomic) @? removeAnchorButtonDidClickBlock;
- (id)descLabel;
- (void)setDescLabel:;
- (void)buildViews;
- (void)addAnchorTapped:;
- (id)remindView;
- (void)setRemindView:;
- (BOOL)disableAndGrey;
- (void)setDisableAndGrey:;
- (id)accessImageView;
- (void)setRemoveAnchorButtonDidClickBlock:;
- (id)tagTitleLabel;
- (id)betaLabel;
- (id)addAnchorButton;
- (void)addRemindViewWithModel:;
- (void)removeRemindView;
- (void)addRemindView;
- (id)addAIAnchorBlock;
- (id)removeAnchorButtonDidClickBlock;
- (void)removeButtonDidClicked:;
- (void)updateCellContentWith:;
- (void)setAddAIAnchorBlock:;
- (void)setBetaLabel:;
- (void)setAddAnchorButton:;
- (void)setAccessImageView:;
- (void)setTagTitleLabel:;
- (id)initWithStyle:reuseIdentifier:;
- (void)setTitleLabel:;
- (id)iconImageView;
- (void).cxx_destruct;
- (id)titleLabel;
- (unsigned long long)accessibilityTraits;
- (id)lineView;
- (void)setIconImageView:;
- (void)setLineView:;
- (id)separatorLine;
- (void)setSeparatorLine:;
- (id)removeButton;
- (void)setRemoveButton:;
+ (id)cellIdentifier;
@end
