@interface AWECodeGenUserAtNoticeModel : AWEBaseDataModel
@property (nonatomic) NSString content;
@property (nonatomic) NSString title;
@property (nonatomic) NSString schemaUrl;
@property (nonatomic) AWECodeGenUrlModel imageUrlModel;
@property (nonatomic) q subType;
@property (nonatomic) AWECodeGenUserModel userInfoModel;
@property (nonatomic) AWECodeGenRelationDynamicLableModel relationLabelModel;
@property (nonatomic) AWECodeGenCommentModel replyCommentModel;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSString labelText;
@property (nonatomic) AWECodeGenIMStickerModel stickerModel;
@property (nonatomic) NSInteger commentStatus;
@property (nonatomic) NSInteger itemStatus;
@property (nonatomic) AWECodeGenCommentModel level1CommentModel;
@property (nonatomic) AWECodeGenAwemeModel awemeModel;
@property (nonatomic) NSInteger labelType;
@property (nonatomic) NSInteger commentUnvisible;
@property (nonatomic) NSString labelTracking;
@property (nonatomic) NSArray imageListModelArray;
@property (nonatomic) NSString desc;
@property (nonatomic) NSArray labelListModelArray;
@property (nonatomic) AWECodeGenVsNoticeDetailModel vsNoticeDetailModel;
@property (nonatomic) AWECodeGenUrlModel maskImageUrlModel;
@property (nonatomic) NSArray effectIdArray;
@property (nonatomic) NSArray videoListModelArray;
@property (nonatomic) q interestGroupId;
@property (nonatomic) NSDictionary commentAudio;
@property (nonatomic) BOOL showCommentInvisible;
- (id)awemeModel;
- (void)setAwemeModel:;
- (id)userInfoModel;
- (void)setUserInfoModel:;
- (id)replyCommentModel;
- (id)stickerModel;
- (void)setStickerModel:;
- (void)setSchemaUrl:;
- (int)commentUnvisible;
- (id)schemaUrl;
- (id)videoListModelArray;
- (id)commentAudio;
- (id)relationLabelModel;
- (id)vsNoticeDetailModel;
- (id)labelTracking;
- (BOOL)showCommentInvisible;
- (id)imageListModelArray;
- (id)level1CommentModel;
- (id)imageUrlModel;
- (id)labelListModelArray;
- (long long)interestGroupId;
- (void)setInterestGroupId:;
- (void)setReplyCommentModel:;
- (void)setImageUrlModel:;
- (void)setCommentUnvisible:;
- (void)setLevel1CommentModel:;
- (void)setRelationLabelModel:;
- (void)setLabelTracking:;
- (void)setLabelListModelArray:;
- (void)setVsNoticeDetailModel:;
- (void)setImageListModelArray:;
- (int)commentStatus;
- (void)setCommentStatus:;
- (id)maskImageUrlModel;
- (void)setMaskImageUrlModel:;
- (id)effectIdArray;
- (void)setEffectIdArray:;
- (void)setVideoListModelArray:;
- (void)setCommentAudio:;
- (void)setShowCommentInvisible:;
- (id)labelText;
- (id)content;
- (void)setStatus:;
- (int)labelType;
- (void)setLabelType:;
- (void)setDesc:;
- (id)desc;
- (long long)subType;
- (void)setContent:;
- (void)setLabelText:;
- (void).cxx_destruct;
- (int)status;
- (id)title;
- (void)setSubType:;
- (void)setTitle:;
- (int)itemStatus;
- (void)setItemStatus:;
+ (id)propertyToModelClassInArrayMap;
+ (id)JSONKeyPathsByPropertyKey;
@end
