@interface AWECommerceMannorAdDataModel : BDMannorAdDataModel
@property (nonatomic) AWEAdDoubleColumnFeedbackModel doubleColumnFeedbackModel;
@property (nonatomic) Q adStyleType;
@property (nonatomic) BOOL softAdAddClickEvent;
@property (nonatomic) BOOL needBlockStarlasEvent;
@property (nonatomic) BOOL isHalfScreenLp;
@property (nonatomic) NSString ecomSkuSchema;
@property (nonatomic) Q showAdTagOnAvatarStyle;
@property (nonatomic) BOOL feedQcpxShowtoast;
@property (nonatomic) BOOL enableComponentShowAdvance;
@property (nonatomic) q adLabelShowType;
@property (nonatomic) q batManScene;
@property (nonatomic) NSString batManURL;
@property (nonatomic) NSString channelName;
@property (nonatomic) NSDictionary qponInfos;
@property (nonatomic) NSDictionary videoInfo;
@property (nonatomic) NSArray productInfos;
@property (nonatomic) NSDictionary liveRoomInfo;
@property (nonatomic) BOOL showGuaranteeLabel;
@property (nonatomic) NSString aggOpenUrl;
@property (nonatomic) NSString aggregateAbParams;
@property (nonatomic) Q enableClueExtraUrl;
@property (nonatomic) NSString imOpenUrl;
@property (nonatomic) BOOL needThirdAutoFill;
@property (nonatomic) NSString productDetailUrl;
@property (nonatomic) NSString enterpriseExtra;
@property (nonatomic) NSString searchFeedbackURL;
@property (nonatomic) NSString softAdEcomLiveParams;
@property (nonatomic) NSString softAdAvatarSchema;
@property (nonatomic) BOOL softAdAddClickTrack;
@property (nonatomic) NSArray repeatFilterWordArray;
@property (nonatomic) q filterWordsType;
@property (nonatomic) q broadcastControlSpeedUp;
@property (nonatomic) q broadcastControlCleanMode;
- (id)videoInfo;
- (void)setVideoInfo:;
- (id)ecomSkuSchema;
- (unsigned long long)showAdTagOnAvatarStyle;
- (id)softAdEcomLiveParams;
- (BOOL)needThirdAutoFill;
- (id)enterpriseExtra;
- (BOOL)needBlockStarlasEvent;
- (unsigned long long)adStyleType;
- (BOOL)isHalfScreenLp;
- (BOOL)feedQcpxShowtoast;
- (id)searchFeedbackURL;
- (void)setAdStyleType:;
- (long long)batManScene;
- (id)batManURL;
- (id)doubleColumnFeedbackModel;
- (BOOL)enableComponentShowAdvance;
- (unsigned long long)enableClueExtraUrl;
- (id)imOpenUrl;
- (id)liveRoomInfo;
- (void)setLiveRoomInfo:;
- (long long)adLabelShowType;
- (id)productDetailUrl;
- (void)setShowAdTagOnAvatarStyle:;
- (BOOL)softAdAddClickTrack;
- (void)setDoubleColumnFeedbackModel:;
- (BOOL)softAdAddClickEvent;
- (void)setSoftAdAddClickEvent:;
- (void)setNeedBlockStarlasEvent:;
- (void)setIsHalfScreenLp:;
- (void)setEcomSkuSchema:;
- (void)setFeedQcpxShowtoast:;
- (void)setEnableComponentShowAdvance:;
- (void)setAdLabelShowType:;
- (void)setBatManScene:;
- (void)setBatManURL:;
- (id)qponInfos;
- (void)setQponInfos:;
- (id)productInfos;
- (void)setProductInfos:;
- (BOOL)showGuaranteeLabel;
- (void)setShowGuaranteeLabel:;
- (id)aggOpenUrl;
- (void)setAggOpenUrl:;
- (id)aggregateAbParams;
- (void)setAggregateAbParams:;
- (void)setEnableClueExtraUrl:;
- (void)setImOpenUrl:;
- (void)setNeedThirdAutoFill:;
- (void)setProductDetailUrl:;
- (void)setEnterpriseExtra:;
- (void)setSearchFeedbackURL:;
- (void)setSoftAdEcomLiveParams:;
- (id)softAdAvatarSchema;
- (void)setSoftAdAvatarSchema:;
- (void)setSoftAdAddClickTrack:;
- (id)repeatFilterWordArray;
- (void)setRepeatFilterWordArray:;
- (long long)filterWordsType;
- (void)setFilterWordsType:;
- (long long)broadcastControlSpeedUp;
- (void)setBroadcastControlSpeedUp:;
- (long long)broadcastControlCleanMode;
- (void)setBroadcastControlCleanMode:;
- (void).cxx_destruct;
- (id)channelName;
- (void)setChannelName:;
+ (id)realUserProfileAdTypeJSONTransformer;
+ (id)repeatFilterWordArrayJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
