@interface AWEDemaciaPlayerView : UIView
@property (nonatomic) q acc_currentPlayState;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <IESCommonVideoPlayerProtocol> playerController;
@property (nonatomic) UIView loadingView;
@property (nonatomic) AWEDemaciaLoadingAndVolumeView volumeLoadingView;
@property (nonatomic) UIImageView coverImageView;
@property (nonatomic) CADisplayLink displayLink;
@property (nonatomic) double playTime;
@property (nonatomic) double originHeight;
@property (nonatomic) double originWidth;
@property (nonatomic) AWEDemaciaVideoBSModel bsModel;
@property (nonatomic) AWEDemaciaPlayerVideoModel videoModel;
@property (nonatomic) AWEDemaciaPlayerInitModel infoModel;
@property (nonatomic) NSDictionary paramDic;
@property (nonatomic) q currentPlayState;
@property (nonatomic) q trategyType;
@property (nonatomic) NSTimer quietModeTimer;
@property (nonatomic) BOOL slidingSeekTime;
@property (nonatomic) BOOL slidingSeekTimeSucceed;
@property (nonatomic) double eachPlayTime;
@property (nonatomic) double stallStartTimestamp;
@property (nonatomic) Q stallCount;
@property (nonatomic) double stallTotalDuration;
@property (nonatomic) BOOL firstFramePlay;
@property (nonatomic) BOOL finishedLog;
@property (nonatomic) NSMutableDictionary trackContext;
@property (nonatomic) BOOL isResourceRecallEnabled;
@property (nonatomic) <AWEDemaciaPlayerViewDelegate> delegate;
@property (nonatomic) UITapGestureRecognizer tap;
@property (nonatomic) double fullScreenWidth;
@property (nonatomic) double fullScreenHeight;
@property (nonatomic) BOOL isQuiet;
@property (nonatomic) BOOL notPlayWhenAppear;
@property (nonatomic) AWEDemaciaPlayerControlView controlView;
@property (nonatomic) BOOL usingForLongVideoNewStyle;
@property (nonatomic) BOOL isTTPlayer;
@property (nonatomic) BOOL isQuietModedisabled;
@property (nonatomic) NSNumber realStartPlayTime;
@property (nonatomic) NSNumber realEndPlayTime;
@property (nonatomic) BOOL notStop;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) BOOL needsRespondingToVideoResourceRecall;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setStallCount:;
- (void)setEnterFrom:;
- (id)trackContext;
- (void)updatePlayerIfNeeded;
- (id)enterFrom;
- (void)setTrackContext:;
- (unsigned long long)stallCount;
- (void)setStartPlayTime:;
- (id)videoModel;
- (void)setVideoModel:;
- (id)infoModel;
- (id)coverImageView;
- (void)setCoverImageView:;
- (id)bsModel;
- (void)setBsModel:;
- (BOOL)needsRespondingToVideoResourceRecall;
- (void)setNeedsRespondingToVideoResourceRecall:;
- (void)updateCoverImage;
- (BOOL)alertIfNotValid;
- (long long)scaleModeForVideo;
- (void)setInfoModel:;
- (void)setPlayTime:;
- (id)paramDic;
- (void)onVolumeChangeNotification:;
- (void)setOriginWidth:;
- (void)setOriginHeight:;
- (double)originWidth;
- (double)originHeight;
- (long long)currentPlayState;
- (void)refreshDemaciaVideoModel:paramDic:;
- (void)demaciaPlayerSliderTouchBegan:;
- (void)demaciaPlayerSliderValueChanged:;
- (void)demaciaPlayerSliderTouchEnded:;
- (void)demaciaPlayerFullScreenButtonClicked:;
- (void)demaciaPlayButtonClicked:;
- (void)demaciaPlayerBackButtonClicked;
- (void)demaciaPlayerReplayButtonClicked;
- (void)demaciaPlayerHideFullScreenBtn:;
- (BOOL)isResourceRecallEnabled;
- (id)initWithFrame:initModel:;
- (id)acc_initWithFrame:initModel:;
- (void)acc_refreshDemaciaVideoModel:paramDic:;
- (long long)acc_currentPlayState;
- (void)realPlay;
- (void)setFullScreenWidth:;
- (void)setFullScreenHeight:;
- (void)setSlidingSeekTimeSucceed:;
- (void)setCurrentPlayState:;
- (void)addVideoLoadingView;
- (void)addControlView;
- (void)screenTap:;
- (void)addIESVideoPlayer;
- (void)addVolumeLoadingView;
- (void)stopAllPlayerNotice:;
- (void)setIsResourceRecallEnabled:;
- (BOOL)_isResourceRecalledForRecallMessage:;
- (double)fullScreenHeight;
- (double)fullScreenWidth;
- (id)volumeLoadingView;
- (void)setParamDic:;
- (void)initCommonTrack;
- (void)resetToBeginTime;
- (void)enterQuietMode:;
- (BOOL)firstFramePlay;
- (double)videoStartPlayTime;
- (id)realStartPlayTime;
- (long long)trategyType;
- (id)_isCurrentVideoH265;
- (id)monitorSeekStateKey;
- (void)setEachPlayTime:;
- (void)setFirstFramePlay:;
- (BOOL)isQuietModedisabled;
- (id)quietModeTimer;
- (void)setQuietModeTimer:;
- (BOOL)usingForLongVideoNewStyle;
- (BOOL)slidingSeekTime;
- (void)addPeriodicTimeObserver;
- (void)registerWillLoopBlock;
- (void)registerVideoDownloadBlock;
- (void)registerNoVideoDownloadBlock;
- (void)registerPlaybackFailedBlock;
- (void)registerStallStateChangeBlock;
- (void)registerDidReadyForDisplayBlock;
- (void)registerPlaybackStateChangeBlock;
- (void)registerSingleUrlPlaybackFailedBlock;
- (BOOL)slidingSeekTimeSucceed;
- (id)realEndPlayTime;
- (BOOL)notStop;
- (long long)contentModeForDefaultVideoCover;
- (void)setVolumeLoadingView:;
- (id)longAndShortVideoModel;
- (void)setFinishedLog:;
- (void)setTrategyType:;
- (id)playURIString;
- (void)checkVideoSize:fromPlayer:;
- (void)setNotPlayWhenAppear:;
- (void)setSlidingSeekTime:;
- (id)monitorFirstFrameKey;
- (id)monitorFirstFrameLogKey;
- (id)monitorpPlayErrorKey;
- (void)playResumeDisplayLink;
- (id)__qualityType;
- (void)resetDisplayLink;
- (void)setStallStartTimestamp:;
- (double)eachPlayTime;
- (BOOL)finishedLog;
- (void)commitMonitor;
- (double)stallStartTimestamp;
- (double)stallTotalDuration;
- (void)setStallTotalDuration:;
- (id)monitorpPlayBlockKey;
- (void)doActionIfNotValid;
- (void)doActionIfNotValidWithText:;
- (void)setControlViewMode:;
- (void)setControlRotateMode:;
- (void)rotateAnimation:complete:;
- (BOOL)notPlayWhenAppear;
- (void)setUsingForLongVideoNewStyle:;
- (BOOL)isTTPlayer;
- (void)setIsTTPlayer:;
- (void)setIsQuietModedisabled:;
- (void)setRealStartPlayTime:;
- (void)setRealEndPlayTime:;
- (void)setNotStop:;
- (void)setAlpha:;
- (void)dealloc;
- (BOOL)play;
- (id)delegate;
- (void)setPlayerController:;
- (void)setLoadingView:;
- (id)displayLink;
- (double)playTime;
- (id)loadingView;
- (id)playerController;
- (void)replay;
- (void)setDisplayLink:;
- (void)setHidden:;
- (void).cxx_destruct;
- (void)reset;
- (id)controlView;
- (void)stopDisplayLink;
- (void)setDelegate:;
- (void)layoutSubviews;
- (BOOL)stop;
- (BOOL)pause;
- (id)loginUser;
- (id)tap;
- (void)setTap:;
- (void)setControlView:;
- (BOOL)isQuiet;
- (void)setIsQuiet:;
- (void)seekToTime:completion:;
@end
