@interface AWEDanmakuSettingsViewOptionCell : UITableViewCell
@property (nonatomic) UIView mainView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) UIView bottomLine;
@property (nonatomic) UIButton descButton;
@property (nonatomic) UILabel danmakuUnSupportMaskLabel;
@property (nonatomic) DUXSwitch danmakuMaskSwitch;
@property (nonatomic) UILabel danmakuCountLabel;
@property (nonatomic) UIImageView enterDanmakuListIcon;
@property (nonatomic) UIView bottomView;
@property (nonatomic) Q danmakuScene;
@property (nonatomic) AWEDanamkuSettingsViewOptionCellConfigModel config;
@property (nonatomic) BOOL showUnSupportMaskDesc;
- (id)descLabel;
- (void)setDescLabel:;
- (id)descButton;
- (void)setDescButton:;
- (void)setMainView:;
- (void)setDanmakuScene:;
- (void)updateDanmakuCount:;
- (unsigned long long)danmakuScene;
- (void)updateCellWithConfig:danmakuScene:;
- (void)setShowUnSupportMaskDesc:;
- (BOOL)showUnSupportMaskDesc;
- (id)danmakuMaskSwitch;
- (id)danmakuUnSupportMaskLabel;
- (id)enterDanmakuListIcon;
- (id)danmakuCountLabel;
- (void)updateDanmakuListUI;
- (void)updateDanmakuUIWithScene:;
- (void)updateDanmakuSwitchStyleUI;
- (void)handleDescButtonClick;
- (void)handleCellClick;
- (void)setDanmakuUnSupportMaskLabel:;
- (void)setDanmakuMaskSwitch:;
- (void)setDanmakuCountLabel:;
- (void)setEnterDanmakuListIcon:;
- (void)setConfig:;
- (void)prepareForReuse;
- (id)config;
- (id)initWithStyle:reuseIdentifier:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (id)bottomView;
- (void)setBottomView:;
- (id)mainView;
- (id)bottomLine;
- (void)setBottomLine:;
- (void)setUpUI;
@end
