@interface AWEDCFeedCellRecommendReasonConfigModel : NSObject
@property (nonatomic) NSString text;
@property (nonatomic) AWEURLModel urlModel;
@property (nonatomic) UIImage image;
@property (nonatomic) NSArray lightUrls;
@property (nonatomic) NSArray darkUrls;
@property (nonatomic) BOOL useV2;
@property (nonatomic) double containerHeight;
@property (nonatomic) double containerCornerRadius;
@property (nonatomic) UIColor containerColorInLight;
@property (nonatomic) UIColor containerColorInDark;
@property (nonatomic) double iconWidth;
@property (nonatomic) double iconHeight;
@property (nonatomic) UIColor iconPlaceholderColorInLight;
@property (nonatomic) UIColor iconPlaceholderColorInDark;
@property (nonatomic) double fontSize;
@property (nonatomic) UIColor textColorInLight;
@property (nonatomic) UIColor textColorInDark;
@property (nonatomic) double iconLeftMargin;
@property (nonatomic) double iconAndTextMargin;
@property (nonatomic) double textRightMargin;
- (id)urlModel;
- (void)setUrlModel:;
- (double)iconLeftMargin;
- (id)lightUrls;
- (void)setLightUrls:;
- (id)darkUrls;
- (void)setDarkUrls:;
- (BOOL)useV2;
- (void)setUseV2:;
- (id)containerColorInLight;
- (void)setContainerColorInLight:;
- (id)containerColorInDark;
- (void)setContainerColorInDark:;
- (id)iconPlaceholderColorInLight;
- (void)setIconPlaceholderColorInLight:;
- (id)iconPlaceholderColorInDark;
- (void)setIconPlaceholderColorInDark:;
- (id)textColorInLight;
- (void)setTextColorInLight:;
- (id)textColorInDark;
- (void)setTextColorInDark:;
- (void)setIconLeftMargin:;
- (double)iconAndTextMargin;
- (void)setIconAndTextMargin:;
- (double)textRightMargin;
- (void)setTextRightMargin:;
- (id)init;
- (id)image;
- (double)fontSize;
- (void)setImage:;
- (void)setText:;
- (id)text;
- (void)setFontSize:;
- (double)iconWidth;
- (void).cxx_destruct;
- (double)iconHeight;
- (void)setIconHeight:;
- (void)setIconWidth:;
- (double)containerCornerRadius;
- (void)setContainerCornerRadius:;
- (double)containerHeight;
- (void)setContainerHeight:;
@end
