@interface AWEDitoPOIFavoriteChannelCellComponentView : DitoComponentView
@property (nonatomic) AWEDitoPOIFavoriteChannelCellComponentViewModel viewModel;
@property (nonatomic) AWEDitoPOIFavoritePageContext context;
@property (nonatomic) UIImageView coverImageView;
@property (nonatomic) UIImageView playIcon;
@property (nonatomic) UIView rightItemsContainer;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIView subTextContainer;
@property (nonatomic) UILabel categoryLabel;
@property (nonatomic) UILabel priceLabel;
@property (nonatomic) UILabel districtLabel;
@property (nonatomic) UILabel distanceLabel;
@property (nonatomic) UIView tagImgCollectInfoContainer;
@property (nonatomic) AWEDitoPOIFavoriteRankLabel rankLabel;
@property (nonatomic) YYLabel popularityLabel;
@property (nonatomic) YYLabel recommendCountLabel;
@property (nonatomic) UIView spuContainer;
@property (nonatomic) UIImageView spuHeadImageView;
@property (nonatomic) UILabel spuNameLabel;
@property (nonatomic) UILabel spuPriceLabel;
@property (nonatomic) UILabel collectTimeLabel;
@property (nonatomic) YYLabel cornerLabel;
@property (nonatomic) YYLabel arrivedLabel;
@property (nonatomic) YYLabel priceReductionLabel;
@property (nonatomic) CAShapeLayer bgShapeLayer;
@property (nonatomic) BOOL shouldShowLargeMode;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)coverImageView;
- (void)setCoverImageView:;
- (id)playIcon;
- (void)setPlayIcon:;
- (void)updateViewModel:;
- (void)setCornerLabel:;
- (id)cornerLabel;
- (void)coverTapped:;
- (id)bgShapeLayer;
- (void)setBgShapeLayer:;
- (double)largeModeSizeWithFont:;
- (void)setShouldShowLargeMode:;
- (BOOL)shouldShowLargeMode;
- (id)districtLabel;
- (id)recommendCountLabel;
- (id)popularityLabel;
- (id)collectTimeLabel;
- (id)spuNameLabel;
- (id)spuHeadImageView;
- (id)spuPriceLabel;
- (void)updatePriceReductionTag;
- (void)updateArrivedTag;
- (void)discriminateProfileScene;
- (id)rightItemsContainer;
- (double)largeModeWithMargin:;
- (id)arrivedLabel;
- (id)subTextContainer;
- (id)tagImgCollectInfoContainer;
- (id)spuContainer;
- (id)priceReductionLabel;
- (BOOL)tapGesture:inView:;
- (void)didSelectedWithAreaString:;
- (void)startBackgroundAnimation;
- (void)openPOIDetailWithAreaString:;
- (id)spuTextColor;
- (void)componentViewDidCompleteShow;
- (void)setRightItemsContainer:;
- (void)setSubTextContainer:;
- (void)setDistrictLabel:;
- (void)setTagImgCollectInfoContainer:;
- (void)setPopularityLabel:;
- (void)setRecommendCountLabel:;
- (void)setSpuContainer:;
- (void)setSpuHeadImageView:;
- (void)setSpuNameLabel:;
- (void)setSpuPriceLabel:;
- (void)setCollectTimeLabel:;
- (void)setArrivedLabel:;
- (void)setPriceReductionLabel:;
- (void)layoutSublayersOfLayer:;
- (void)prepareForReuse;
- (id)viewModel;
- (id)initWithFrame:;
- (void)setTitleLabel:;
- (void)updateLayout;
- (void)setViewModel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (id)distanceLabel;
- (void)setDistanceLabel:;
- (void)setupUI;
- (id)categoryLabel;
- (id)rankLabel;
- (void)setCategoryLabel:;
- (void)setRankLabel:;
- (id)priceLabel;
- (void)setPriceLabel:;
+ (BOOL)enableAdaptLargeFont;
+ (id)rankAndRecommendLabelFont;
+ (double)insetOfImageAndContainer;
+ (id)subTextFont;
+ (double)imageWidth;
@end
