@interface AWEDiscoverDPlayletDetailHeaderView : UIView
@property (nonatomic) UIImageView playletCoverView;
@property (nonatomic) UIImageView playletIcon;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) YYLabel authorLabel;
@property (nonatomic) UIImageView tailIcon;
@property (nonatomic) NSMutableAttributedString authorAttrString;
@property (nonatomic) UILabel updateCountLabel;
@property (nonatomic) UILabel continueWatchLabel;
@property (nonatomic) UIView<AWEChallengeDetailDescViewProtocol> descView;
@property (nonatomic) UILabel playTimesLabel;
@property (nonatomic) UIView seperateView;
@property (nonatomic) AWEPlayletInfoModel playletModel;
@property (nonatomic) double lastDescHeight;
@property (nonatomic) AWEPlayletDetailHeaderButtonGroupView buttonGroupView;
@property (nonatomic) AWEPaymentBadgeView paymentBadgeView;
@property (nonatomic) UIButton paymentUserNoticeButton;
@property (nonatomic) UILabel expectedUpdateCompletionTimeLabel;
@property (nonatomic) <AWEPlayletDetailHeaderViewDelegate> delegate;
@property (nonatomic) double topOffset;
@property (nonatomic) BOOL fromPersonPage;
@property (nonatomic) NSString previousPage;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSString fromGroupID;
@property (nonatomic) NSNumber continueEpisode;
@property (nonatomic) double mixButtonViewBottomOffset;
@property (nonatomic) NSObject<AWEPaymentEventHandlerProtocol><AWEPaymentDetailEventHandlerProtocol> paymentEventHandle;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)fromGroupID;
- (void)configureUI;
- (void)setAuthorLabel:;
- (id)authorLabel;
- (id)tailIcon;
- (void)setTailIcon:;
- (id)descView;
- (void)setDescView:;
- (id)seperateView;
- (void)setSeperateView:;
- (id)buttonGroupView;
- (void)setButtonGroupView:;
- (void)setFromGroupID:;
- (id)paymentBadgeView;
- (void)setPaymentBadgeView:;
- (void)needUpdateConstraits:;
- (void)didSelectLinkWithURL:;
- (id)paymentEventHandle;
- (void)setPaymentEventHandle:;
- (void)tailIconTapped:;
- (id)completionTimeText:;
- (id)getDataYear:;
- (id)updateCountLabel;
- (void)setUpdateCountLabel:;
- (id)playletModel;
- (void)refreshPlayletForPaymentVideosUpdate;
- (void)setPlayletModel:;
- (id)playletCoverView;
- (id)playletIcon;
- (id)continueWatchLabel;
- (id)playTimesLabel;
- (id)paymentUserNoticeButton;
- (id)expectedUpdateCompletionTimeLabel;
- (void)setAuthorAttrString:;
- (id)authorAttrString;
- (void)openPersonalPage;
- (BOOL)shouldShowExpectedCompletionTimeButton:;
- (id)continueEpisode;
- (void)setContinueEpisode:;
- (void)updateContinueString:;
- (void)setLastDescHeight:;
- (BOOL)fromPersonPage;
- (double)lastDescHeight;
- (void)contiuePlayVideo;
- (void)paymentUserNoticeTapped:;
- (void)updatePlayletID:lastEpisode:;
- (void)updatePlayletInfo:;
- (void)dismissHintBubble;
- (void)setHintTrackDict:;
- (double)mixButtonViewBottomOffset;
- (void)setFromPersonPage:;
- (void)setPlayletCoverView:;
- (void)setPlayletIcon:;
- (void)setContinueWatchLabel:;
- (void)setPlayTimesLabel:;
- (void)setPaymentUserNoticeButton:;
- (void)setExpectedUpdateCompletionTimeLabel:;
- (void)setTopOffset:;
- (double)topOffset;
- (id)init;
- (id)delegate;
- (void)setTitleLabel:;
- (void)updateLayout;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (id)previousPage;
- (void)setPreviousPage:;
@end
