@interface AWEDiscoverDPlayletListTableViewCell : UITableViewCell
@property (nonatomic) UIImageView mixVideoCoverView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel durationLabel;
@property (nonatomic) UIImageView digIcon;
@property (nonatomic) UILabel playLabel;
@property (nonatomic) UIView lockMaskView;
@property (nonatomic) UIImageView lockImageView;
@property (nonatomic) UIColor titleLabelTextColor;
@property (nonatomic) UIColor contentViewBackgroundColor;
@property (nonatomic) UIColor locatedContentViewBackgroundColor;
@property (nonatomic) UIColor lineAttributesColor;
@property (nonatomic) BOOL isBGColorWhite;
@property (nonatomic) AWEPaymentBadgeView paymentBadgeView;
@property (nonatomic) UILabel fromRelateLabel;
@property (nonatomic) UIImageView fromRelateIcon;
@property (nonatomic) UIImageView materialLabelDecorateImage;
@property (nonatomic) UILabel calclulateMaterialLabel;
@property (nonatomic) AWEAwemeModel awemeModel;
- (id)awemeModel;
- (void)setIsBGColorWhite:;
- (BOOL)isBGColorWhite;
- (void)configureUI;
- (id)contentViewBackgroundColor;
- (void)setContentViewBackgroundColor:;
- (void)updateUIWithModel:;
- (id)paymentBadgeView;
- (void)setPaymentBadgeView:;
- (id)locatedContentViewBackgroundColor;
- (id)playLabel;
- (void)setPlayLabel:;
- (void)setLocatedContentViewBackgroundColor:;
- (void)setLineAttributesColor:;
- (void)setConstDarkMode;
- (id)lineAttributesColor;
- (id)minuteFormatStringWithDuration:;
- (id)secondsFormatStringWithDuration:;
- (id)digIcon;
- (void)setDigIcon:;
- (id)mixVideoCoverView;
- (id)getFormatTimeStringWithDuration:;
- (void)setMixVideoCoverView:;
- (id)materialLabelDecorateImage;
- (id)lockMaskView;
- (id)fromRelateLabel;
- (id)fromRelateIcon;
- (id)calclulateMaterialLabel;
- (BOOL)materialLabelDecorateImageNeedShow:;
- (BOOL)fromRelateLabelNeedShow:;
- (void)setLockMaskView:;
- (void)setFromRelateLabel:;
- (void)setFromRelateIcon:;
- (void)setMaterialLabelDecorateImage:;
- (void)setCalclulateMaterialLabel:;
- (void)prepareForReuse;
- (id)initWithStyle:reuseIdentifier:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setSelected:animated:;
- (id)durationLabel;
- (void)setDurationLabel:;
- (void)setTitleLabelTextColor:;
- (id)lockImageView;
- (void)setLockImageView:;
- (id)titleLabelTextColor;
+ (id)reuseIdentifier;
+ (double)cellHeight;
@end
