@interface AWEDCFeedDataConfig : AWEDCFeedBaseConfig
@property (nonatomic) Q dataLoadTiming;
@property (nonatomic) Q dataStyle;
@property (nonatomic) BOOL validByResponseData;
@property (nonatomic) NSString requestURL;
@property (nonatomic) NSString requestMethod;
@property (nonatomic) NSDictionary requestParams;
@property (nonatomic) NSDictionary requestBodyParams;
@property (nonatomic) BOOL enableCommonParams;
@property (nonatomic) AWEDCFeedDataDuplicateFilterConfig duplicateFilterConfig;
@property (nonatomic) NSArray dataProcessors;
@property (nonatomic) NSString prfPageLoadURLPath;
@property (nonatomic) <AWEDCFeedDataControllerProtocol> dcFeedDataController;
@property (nonatomic) AWEListDataController dataController;
@property (nonatomic) AWEListDataController innerDataController;
@property (nonatomic) @? innerDataControllerConfigBlock;
@property (nonatomic) @? sectionViewModelActionAfterFetch;
- (void)setDataController:;
- (void)setDcFeedDataController:;
- (void)setDataLoadTiming:;
- (void)setInnerDataControllerConfigBlock:;
- (id)duplicateFilterConfig;
- (void)setEnableCommonParams:;
- (void)setDataProcessors:;
- (id)sectionViewModelActionAfterFetch;
- (id)dcFeedDataController;
- (BOOL)enableCommonParams;
- (id)dataProcessors;
- (void)setupDefaultConfig;
- (void)setDuplicateFilterConfig:;
- (unsigned long long)dataLoadTiming;
- (void)setDataStyle:;
- (BOOL)validByResponseData;
- (void)setValidByResponseData:;
- (id)requestBodyParams;
- (void)setRequestBodyParams:;
- (id)prfPageLoadURLPath;
- (void)setPrfPageLoadURLPath:;
- (id)innerDataController;
- (void)setInnerDataController:;
- (id)innerDataControllerConfigBlock;
- (void)setSectionViewModelActionAfterFetch:;
- (id)requestURL;
- (unsigned long long)dataStyle;
- (void)setRequestURL:;
- (void).cxx_destruct;
- (id)dataController;
- (id)requestMethod;
- (id)requestParams;
- (void)setRequestParams:;
- (void)setRequestMethod:;
@end
