@interface AWEDanmakuItemNode : NSObject
@property (nonatomic) AWEVideoPlayDanmakuModel danmakuModel;
@property (nonatomic) SkityTextBlob textBlob;
@property (nonatomic) NSString itemType;
@property (nonatomic) q danmakuType;
@property (nonatomic) BOOL hidden;
@property (nonatomic) double alpha;
@property (nonatomic) AWEDanmakuItemPrefixImageInfo prefixImageInfo;
@property (nonatomic) AWEDanmakuItemTextInfo textInfo;
@property (nonatomic) AWEDanmakuItemDiggInfo diggInfo;
@property (nonatomic) AWEDanmakuItemBackgroundInfo backgroundInfo;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} dmk_frame;
@property (nonatomic) {CGSize=dd} dmk_size;
@property (nonatomic) double dmk_left;
@property (nonatomic) double dmk_right;
@property (nonatomic) double dmk_width;
@property (nonatomic) double dmk_height;
@property (nonatomic) double dmk_centerY;
@property (nonatomic) double dmk_topY;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setDmk_left:;
- (void)setDmk_right:;
- (void)setDmk_width:;
- (double)dmk_height;
- (void)setDmk_height:;
- (double)dmk_centerY;
- (void)setDmk_centerY:;
- (id)dmk_size;
- (void)setDmk_size:;
- (double)dmk_left;
- (double)dmk_width;
- (double)dmk_right;
- (void)updateWithDescriptor:;
- (id)backgroundInfo;
- (id)dmk_frame;
- (id)diggInfo;
- (void)refreshDanmakuInfoInNeed;
- (id)danmakuModel;
- (void)setDanmakuModel:;
- (id)textBlob;
- (void)setTextBlob:;
- (id)prefixImageInfo;
- (void)setDanmakuType:;
- (void)configDanmakuPrefixImageIfNeed;
- (void)configDanmakuTextInfo;
- (void)configDanmakuBackgroundInfoIfNeed;
- (void)configDanmakuDiggInfoIfNeed;
- (long long)danmakuType;
- (double)dmk_topY;
- (void)setPrefixImageInfo:;
- (void)setDiggInfo:;
- (void)setBackgroundInfo:;
- (void)setDmk_topY:;
- (id)itemType;
- (void)setItemType:;
- (void)setAlpha:;
- (void)prepareForReuse;
- (double)alpha;
- (void)setHidden:;
- (void).cxx_destruct;
- (BOOL)hidden;
- (void)setTextInfo:;
- (id)textInfo;
- (id)initWithItemType:;
+ (id)borderPaint;
+ (id)borderGroundPaint;
@end
