@interface AWEDiscoverDWidgetGuideManager : NSObject
@property (nonatomic) AWEDiscoverDWidgetGuideManagerEvader hotspotTabImageSnackbarEvader;
@property (nonatomic) AWEDiscoverDWidgetGuideManagerEvader hotspotTabHalfScreenEvader;
@property (nonatomic) AWEDiscoverDWidgetGuideManagerEvader hotSearchCombineSnackbarEvader;
@property (nonatomic) AWEDiscoverDWidgetGuideManagerEvader hotSearchCombineCardEvader;
@property (nonatomic) AWEDiscoverDWidgetGuideManagerEvader hotSearchHotSpotListEvader;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)enableHotspotCombineWidgetGuide;
- (BOOL)meetsHotSearchCombineCondition;
- (void)showGuideWithEnterFrom:completion:;
- (id)hotspotTabImageSnackbarEvader;
- (id)hotspotTabHalfScreenEvader;
- (id)hotSearchCombineSnackbarEvader;
- (id)hotSearchCombineCardEvader;
- (id)hotSearchHotSpotListEvader;
- (BOOL)p_checkTodayWithKey:;
- (long long)hotTrendWidgetGuideChannelVideoCount;
- (long long)hotTrendWidgetGuideChannelDwellTime;
- (long long)hotTrendWidgetGuideCombineVisitTimes;
- (BOOL)enableHotspotWidgetGuide;
- (id)p_createGuideRequestModel:;
- (void)p_checkWidgetInstalledWithCompletion:;
- (id)p_getSavedDayWithKey:;
- (void)p_setSavedDayWithKey:day:;
- (void)addToXTabPlayStartedList:;
- (BOOL)meetsXTabPlayStartedCondition;
- (void)markHotSearchCombineVisit;
- (void)addHotSpotTabStayTime:;
- (BOOL)meetsXTabStayTimeCondition;
- (void)setHotspotTabImageSnackbarEvader:;
- (void)setHotspotTabHalfScreenEvader:;
- (void)setHotSearchCombineSnackbarEvader:;
- (void)setHotSearchCombineCardEvader:;
- (void)setHotSearchHotSpotListEvader:;
- (id)init;
- (void).cxx_destruct;
+ (id)sharedManager;
@end
