@interface AWEDiscoverDPlayletProfileListViewController : UIViewController
@property (nonatomic) NSString referString;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) AWEButton shareBtn;
@property (nonatomic) UITableView tableView;
@property (nonatomic) UILabel emptyLabel;
@property (nonatomic) BOOL isAppear;
@property (nonatomic) AWEDiscoverDPlayletProfileListDataController dataController;
@property (nonatomic) AWELoadMoreFooter footer;
@property (nonatomic) NSString userID;
@property (nonatomic) NSString secUserID;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)secUserID;
- (void)setSecUserID:;
- (id)referString;
- (id)aweui_emptyPageConfigForState:;
- (void)aweui_emptyPagePrimaryButtonTapped:;
- (void)setEnterMethod:;
- (BOOL)configWithRouterParamDict:;
- (void)setReferString:;
- (id)enterMethod;
- (void)loadMore;
- (void)setDataController:;
- (BOOL)isAppear;
- (void)setIsAppear:;
- (id)initWithDataController:;
- (id)shareBtn;
- (void)setShareBtn:;
- (void)hideNavigationBar;
- (void)backBtnClicked:;
- (void)onShareBtnClicked:;
- (void)p_mixLiveCellTrackerWithUser:isClick:;
- (BOOL)prefersStatusBarHidden;
- (id)footer;
- (id)userID;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (id)init;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)viewDidLoad;
- (id)tableView;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (void)setFooter:;
- (void)setUserID:;
- (id)dataController;
- (void)refreshData;
- (id)emptyLabel;
- (void)setEmptyLabel:;
@end
