@interface AWEDCFeedDislikeConfig : AWEDCFeedBaseConfig
@property (nonatomic) # viewModelClass;
@property (nonatomic) q currentBigMode;
@property (nonatomic) BOOL enableFeedbackToast;
@property (nonatomic) @? shouldShowDislikeVCBlock;
@property (nonatomic) @? customDislikeVCBlock;
@property (nonatomic) @? dislikeShowBlock;
@property (nonatomic) @? onDidClickItem;
@property (nonatomic) AWEDCFeedDislikeCommonPanelConfig dislikeCommonPanelConfig;
@property (nonatomic) @? isDislikedAfterRevokeBlock;
@property (nonatomic) NSString feedbackTitle;
@property (nonatomic) NSString feedbackDescription;
@property (nonatomic) @? revokeFeedbackProcessBlock;
@property (nonatomic) <AWEDCFeedDislikeVCDelegate> delegate;
@property (nonatomic) @? dislikePanelCalculateHeightAfterConfigBlock;
@property (nonatomic) @? dislikePanelUseAdaptiveHeightBlock;
@property (nonatomic) @? dislikePanelNeedRearrangeSectionBlock;
@property (nonatomic) @? dislikePanelRearrangedSectionDataBlock;
@property (nonatomic) @? dislikePanelHeaderHeightForSectionBlock;
@property (nonatomic) @? dislikePanelCellWidthForIndexPathBlock;
@property (nonatomic) @? dislikePanelNeedSendDislikeRequest;
@property (nonatomic) @? dislikePanelNeedTrackDislike;
@property (nonatomic) @? dislikePanelWatchLaterSectionDataBlock;
- (Class)viewModelClass;
- (void)setEnableFeedbackToast:;
- (void)setDislikeShowBlock:;
- (void)setOnDidClickItem:;
- (void)setCurrentBigMode:;
- (void)setViewModelClass:;
- (void)setShouldShowDislikeVCBlock:;
- (void)setCustomDislikeVCBlock:;
- (id)customDislikeVCBlock;
- (id)feedbackTitle;
- (void)setFeedbackTitle:;
- (void)setupDefaultConfig;
- (id)isDislikedAfterRevokeBlock;
- (id)revokeFeedbackProcessBlock;
- (void)setDislikeCommonPanelConfig:;
- (void)setFeedbackDescription:;
- (long long)currentBigMode;
- (BOOL)enableFeedbackToast;
- (id)shouldShowDislikeVCBlock;
- (id)dislikeShowBlock;
- (id)onDidClickItem;
- (id)dislikeCommonPanelConfig;
- (void)setIsDislikedAfterRevokeBlock:;
- (void)setRevokeFeedbackProcessBlock:;
- (id)dislikePanelCalculateHeightAfterConfigBlock;
- (void)setDislikePanelCalculateHeightAfterConfigBlock:;
- (id)dislikePanelUseAdaptiveHeightBlock;
- (void)setDislikePanelUseAdaptiveHeightBlock:;
- (id)dislikePanelNeedRearrangeSectionBlock;
- (void)setDislikePanelNeedRearrangeSectionBlock:;
- (id)dislikePanelRearrangedSectionDataBlock;
- (void)setDislikePanelRearrangedSectionDataBlock:;
- (id)dislikePanelHeaderHeightForSectionBlock;
- (void)setDislikePanelHeaderHeightForSectionBlock:;
- (id)dislikePanelCellWidthForIndexPathBlock;
- (void)setDislikePanelCellWidthForIndexPathBlock:;
- (id)dislikePanelNeedSendDislikeRequest;
- (void)setDislikePanelNeedSendDislikeRequest:;
- (id)dislikePanelNeedTrackDislike;
- (void)setDislikePanelNeedTrackDislike:;
- (id)dislikePanelWatchLaterSectionDataBlock;
- (void)setDislikePanelWatchLaterSectionDataBlock:;
- (id)delegate;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)feedbackDescription;
@end
