@interface AWEDetailMVViewModel : NSObject
@property (nonatomic) AWEDetailNaviBarModel naviBarObject;
@property (nonatomic) AWEDetailShimmerModel shimmerViewObject;
@property (nonatomic) AWEDetailHeaderInfoModel headerInfoObject;
@property (nonatomic) AWEDetailUserProfileModel verifiedUserObject;
@property (nonatomic) AWEDetailWelfareModel welfareObject;
@property (nonatomic) AWEDetailAIWarningNoticeModel aiWarningNoticeObject;
@property (nonatomic) AWEDetailDiffableMultiModelObject awemeListObject;
@property (nonatomic) AWEDetailAwemeListDataController awemeListDataController;
@property (nonatomic) NSArray cachedObjectArray;
@property (nonatomic) NSString mvID;
@property (nonatomic) NSString mvLokiID;
@property (nonatomic) q mvType;
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) AWEMVDetailResponseModel cutSameResponse;
@property (nonatomic) AWEMvDetailResponse classicMVResponse;
@property (nonatomic) AWEMediaTemplateDetailResponseModel mediaResponse;
@property (nonatomic) CKGenericTemplateModel pixelTemplateModel;
@property (nonatomic) BOOL isFetchPixelForCutSame;
@property (nonatomic) q pixelTemplateErrorCode;
@property (nonatomic) BOOL templateContainGamePlay;
@property (nonatomic) q detailInfoFetchState;
@property (nonatomic) q awemeListFetchState;
@property (nonatomic) q awemeListInitFetchStatus;
@property (nonatomic) BOOL isCutSame;
@property (nonatomic) BOOL isMediaTemplate;
@property (nonatomic) BOOL isOneClickFilming;
@property (nonatomic) BOOL isClassicMV;
@property (nonatomic) BOOL isPixelTemplate;
@property (nonatomic) NSNumber cutSameStatusCode;
@property (nonatomic) AWEAweMVTemplateModel cutSameTemplateModel;
@property (nonatomic) AWEMvDetailModel classicMVModel;
@property (nonatomic) NSNumber mediaStatusCode;
@property (nonatomic) AWEMediaTemplateModel mediaTemplateModel;
@property (nonatomic) NSNumber mediaProvider;
@property (nonatomic) NSNumber mediaFilterType;
@property (nonatomic) NSMutableDictionary paramDict;
@property (nonatomic) NSArray sectionControllerModelObjectArray;
@property (nonatomic) NSIndexPath awemeListSectionSelectedIndexPath;
@property (nonatomic) BOOL awemeListUpdated;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeModel;
- (void)setAwemeModel:;
- (id)mvID;
- (void)setMvID:;
- (id)cutSameStatusCode;
- (id)mediaStatusCode;
- (long long)mvType;
- (void)setMvType:;
- (id)paramDict;
- (void)setParamDict:;
- (BOOL)isMediaTemplate;
- (BOOL)isPixelTemplate;
- (BOOL)isOneClickFilming;
- (BOOL)isClassicMV;
- (void)configViewModelWithParamDict:;
- (void)fetchDetailInfo;
- (id)awemeListDataController;
- (void)fetchAwemeList;
- (BOOL)isFetchingInitialAwemeList;
- (id)sectionControllerModelObjectArray;
- (id)naviBarObject;
- (id)shimmerViewObject;
- (id)headerInfoObject;
- (id)awemeListObject;
- (long long)detailInfoFetchState;
- (long long)awemeListFetchState;
- (long long)awemeListInitFetchStatus;
- (id)awemeListSectionSelectedIndexPath;
- (void)setAwemeListSectionSelectedIndexPath:;
- (BOOL)awemeListUpdated;
- (void)setAwemeListUpdated:;
- (void)setDetailInfoFetchState:;
- (void)setCachedObjectArray:;
- (void)setHeaderInfoObject:;
- (void)setNaviBarObject:;
- (void)setAwemeListFetchState:;
- (id)cachedObjectArray;
- (void)setShimmerViewObject:;
- (void)setAwemeListObject:;
- (void)setAwemeListDataController:;
- (void)setAwemeListInitFetchStatus:;
- (id)verifiedUserObject;
- (void)setVerifiedUserObject:;
- (id)mvLokiID;
- (BOOL)isCutSame;
- (id)cutSameTemplateModel;
- (id)mediaTemplateModel;
- (id)mediaFilterType;
- (id)pixelTemplateModel;
- (id)classicMVModel;
- (id)welfareObject;
- (BOOL)isFetchPixelForCutSame;
- (void)setMvLokiID:;
- (BOOL)isIntNumber:;
- (void)p_fetchPixelTemplate;
- (void)setMediaResponse:;
- (void)p_decomposeMediaTemplateResponse:;
- (void)setIsFetchPixelForCutSame:;
- (void)setCutSameResponse:;
- (void)p_decomposeCutSameDetailResponse:;
- (void)p_decomposeClassicMVDetailResponse:;
- (void)setClassicMVResponse:;
- (id)p_slotsInfoWithCutSameDetailResponse:;
- (id)p_templateCreatorEntranceLinkWithModelIfNeed;
- (BOOL)enableFlexibleSlot;
- (void)setTemplateContainGamePlay:;
- (void)setWelfareObject:;
- (void)setPixelTemplateErrorCode:;
- (void)p_decomposePixelDetailResponse:;
- (void)setPixelTemplateModel:;
- (id)p_slotsInfoWithPixelDetailResponse:;
- (void)setAiWarningNoticeObject:;
- (BOOL)templateContainGamePlay;
- (BOOL)wouldUsePresetPath;
- (id)aiWarningNoticeObject;
- (long long)pixelTemplateErrorCode;
- (id)cutSameResponse;
- (id)classicMVResponse;
- (id)mediaResponse;
- (id)mediaProvider;
- (void).cxx_destruct;
@end
