@interface AWEDCFeedBaseCell : UICollectionViewCell
@property (nonatomic) UIStackView elementStackView;
@property (nonatomic) NSMutableArray elementArray;
@property (nonatomic) NSArray elementClassArray;
@property (nonatomic) AWEDCFeedTapGuideView tapGuideView;
@property (nonatomic) UILongPressGestureRecognizer longPressGR;
@property (nonatomic) UIView overlayMaskView;
@property (nonatomic) AWEDCFeedDislikeRevokableView dcDislikeRevokableView;
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) AWEDCFeedPageContext context;
@property (nonatomic) AWEDCFeedBaseSectionController sectionController;
@property (nonatomic) @? longPressedBlock;
@property (nonatomic) @? revokeFeedbackBlock;
@property (nonatomic) @? hitTestBlock;
@property (nonatomic) NSDictionary feedbackInfo;
@property (nonatomic) q hitViewType;
@property (nonatomic) @? lynxContainerSingleTapBlock;
@property (nonatomic) Q resetTimingType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL isActive;
@property (nonatomic) AWEDCFeedAutoPlayHandler autoPlayHandler;
@property (nonatomic) <AWEDCFeedAutoPlayRuleProtocol> associateRule;
- (id)awemeModel;
- (void)p_setupUI;
- (void)setAwemeModel:;
- (void)cellWillDisplay;
- (void)awe_themeDidChange:;
- (id)elementArray;
- (void)configWithModel:context:;
- (long long)hitViewType;
- (void)cellDidEndDisplaying;
- (id)elementClassArray;
- (void)willBeginDragging;
- (id)feedbackInfo;
- (void)setFeedbackInfo:;
- (void)pageDidDisappear;
- (void)pageWillAppear;
- (id)autoPlayHandler;
- (void)setAutoPlayHandler:;
- (id)associateRule;
- (void)setAssociateRule:;
- (BOOL)forceNotActive;
- (BOOL)shouldNotActive;
- (double)currentPlayBackTime;
- (long long)currentPlayBackIndex;
- (id)padDCConfig;
- (id)classNameWithReferString;
- (void)setElementArray:;
- (void)p_addGesture;
- (id)elementStackView;
- (unsigned long long)customDisabledGesture;
- (void)updateColorWithTheme:;
- (void)removeTapGuideViewIfNeeded;
- (void)setHitViewType:;
- (id)hitTestBlock;
- (id)dcDislikeRevokableView;
- (id)longPressedBlock;
- (unsigned long long)resetTimingType;
- (Class)elementClassWithString:;
- (BOOL)enableCardCreationInfoRefactor;
- (BOOL)enablePadConfig;
- (void)showTapGuideOnCellIfNeeded;
- (void)showFeedbackViewWithRevoke;
- (id)overlayMaskView;
- (void)setOverlayMaskView:;
- (id)tapGuideView;
- (void)setDcDislikeRevokableView:;
- (void)revokeButtonPressed;
- (void)dismissFeedbackMask;
- (BOOL)isTargetAwemeForTapGuide;
- (int)tapGuideMaxTime;
- (BOOL)frequencyTimeControlIsOkByLastDate:checkDate:cooldownHours:;
- (BOOL)shouldShowTapGuideOnCell;
- (void)setTapGuideView:;
- (void)setResetTimingType:;
- (void)seekToPlayTime:completion:;
- (void)pageDidAppear;
- (void)pageWillDisappear;
- (void)screenWillRotate;
- (void)screenDidRotate;
- (void)didEndScrolling;
- (void)showMaskViewIfNeeded:completion:;
- (void)removeMaskViewIfNeeded:completion:;
- (id)elementWithClass:;
- (void)setLongPressedBlock:;
- (id)revokeFeedbackBlock;
- (void)setRevokeFeedbackBlock:;
- (void)setHitTestBlock:;
- (id)lynxContainerSingleTapBlock;
- (void)setLynxContainerSingleTapBlock:;
- (void)setElementStackView:;
- (void)setElementClassArray:;
- (void)didBecomeActive;
- (void)setSectionController:;
- (void)setIsActive:;
- (void)play;
- (id)longPressGR;
- (void)didResignActive;
- (id)initWithFrame:;
- (id)sectionController;
- (id)cellBackgroundColor;
- (void)replay;
- (void)setContext:;
- (void).cxx_destruct;
- (id)hitTest:withEvent:;
- (void)setLongPressGR:;
- (void)reset;
- (BOOL)isActive;
- (id)context;
- (void)stop;
- (void)pause;
- (long long)currentIndex;
- (id)activeView;
- (void)longPressGestureRecognized:;
- (void)didEndDragging;
- (void)willStartScrolling;
+ (id)elementArray;
+ (double)heightWithCellWidth:awemeModel:context:;
+ (id)cellBackgroundColorWithConfig:;
@end
