@interface AWEDiscoverDPlayletPanelViewController : UIViewController
@property (nonatomic) AWEPlayletSchemaModel schemaModel;
@property (nonatomic) NSDictionary schemaLogExtras;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIButton closeButton;
@property (nonatomic) UIView bottomCollectView;
@property (nonatomic) UITapGestureRecognizer tapGes;
@property (nonatomic) {CGPoint=dd} lastLocation;
@property (nonatomic) double baseViewBottomOffset;
@property (nonatomic) MASConstraint baseViewBottom;
@property (nonatomic) BDXBridgeEventSubscriber subscriber;
@property (nonatomic) AWEPlayletInfoModel playletModel;
@property (nonatomic) AWEPaymentDetailBuyButton paymentButton;
@property (nonatomic) AWEPlayletPanelHeaderView panelHeadView;
@property (nonatomic) NSObject<AWEPaymentEventHandlerProtocol><AWEPaymentDetailEventHandlerProtocol> paymentEventHandle;
@property (nonatomic) AWEPlayletPanelRecommendCardViewController lynxRecommendCardVC;
@property (nonatomic) AWEPlayletPanelRelativeAnnieXCardViewController lynxRelativeCardVC;
@property (nonatomic) DUXTabBarContainerController tabBarContainer;
@property (nonatomic) DUXTabBar tabBar;
@property (nonatomic) AWEShowCouponInfoTipView couponInfoTipView;
@property (nonatomic) <AWEShowMonetizeCouponTimelineService> couponTimelineService;
@property (nonatomic) NSMutableDictionary tabModels;
@property (nonatomic) UIView lineView;
@property (nonatomic) <AWEDiscoverDPlayletPanelDelegate> delegate;
@property (nonatomic) AWEDiscoverDPlayletPanelTableViewController panelTableViewController;
@property (nonatomic) AWEDiscoverDPlayletCollectionButton collectionButton;
@property (nonatomic) AWEAwemeModel currentModel;
@property (nonatomic) AWEAwemePageContext context;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)duxGrid_viewDidChangeBreakPointFrom:toBreakPoint:;
- (long long)numberOfControllers:;
- (id)slidingViewController:viewControllerAtIndex:;
- (id)schemaModel;
- (void)panelWillShow;
- (void)setCollectionButton:;
- (id)collectionButton;
- (id)tabBarContainer;
- (void)setTabBarContainer:;
- (void)setSchemaModel:;
- (id)tapGes;
- (void)setTapGes:;
- (id)panelTableViewController;
- (void)selfTapped:;
- (void)trackWithEventName:params:;
- (id)aAWEPadDetailTableAdapter;
- (void)setBaseViewBottomOffset:;
- (void)setBaseViewBottom:;
- (double)baseViewBottomOffset;
- (id)baseViewBottom;
- (id)tabModels;
- (void)setTabModels:;
- (id)bottomCollectView;
- (void)setBottomCollectView:;
- (id)panelHeadView;
- (void)updatePaymentButtonIfNeeded;
- (BOOL)shouldShowPaymentButton;
- (id)paymentButton;
- (void)setPaymentButton:;
- (id)paymentEventHandle;
- (void)refreshFeedData;
- (void)trackPurchaseFullEpisodeShow;
- (void)orderMix:;
- (void)handlePayEvent:;
- (void)handleLoginEvent:;
- (void)setPanelHeadView:;
- (void)setPaymentEventHandle:;
- (void)panelDidShow;
- (void)setPanelTableViewController:;
- (id)playletModel;
- (void)setSchemaLogExtras:;
- (id)schemaLogExtras;
- (void)setPlayletModel:;
- (id)playletVIPPaidPanelExtraParamsHasPaid:;
- (id)initWithSchemaModel:delegate:;
- (void)setLynxRecommendCardVC:;
- (id)tabConfigWithNumber:;
- (id)createPanelTabModelWithName:subController:tag:trackerTabName:;
- (id)lynxRecommendCardVC;
- (void)setCouponTimelineService:;
- (id)couponTimelineService;
- (void)createTabBar;
- (void)layoutTabBar;
- (id)aAWEDiscoverDPlayletPanelViewControllerAdapter;
- (void)openBillPage:;
- (id)lynxRelativeCardVC;
- (void)setLynxRelativeCardVC:;
- (void)trackerTabParamsWithIndex:trackName:;
- (BOOL)shouldShowBottomCollectView;
- (void)updateCouponTimelineService;
- (id)playletPanelTrackCommonParams;
- (void)trackCollectionButtonShow;
- (void)trackPurchaseVipCardShow;
- (id)playletPanelTrackVipParamsHasPaid:;
- (id)couponInfoTipView;
- (void)updatePayButtonIfNeeded;
- (void)updatePlayletVIPButtonIfNeeded;
- (void)buyPlayletVIP:;
- (void)tryStartCouponInfoTimeline;
- (id)createDUXTabBarTextItem:;
- (void)timeline:willStartTimelineForCouponInfo:;
- (void)timeline:updateTimelineForCouponInfo:timelineText:;
- (void)timeline:originCouponInfo:changeToNewCouponInfo:;
- (void)timeline:deadForCouponInfo:;
- (void)timeline:didStopTimeLineForCouponInfo:;
- (id)couponReceiveHandlerEventContainerID:;
- (void)coupon:didLoadCouponInfoForScene:timing:hasCouponInfo:;
- (void)refreshTabsWithPlayletInfoModel:index:;
- (void)updateBottomViewWithModel:;
- (void)playletDataHasChanged:awemeModels:;
- (void)setCouponInfoTipView:;
- (id)lastLocation;
- (void)dealloc;
- (id)delegate;
- (void)viewDidLayoutSubviews;
- (id)subscriber;
- (void)setSubscriber:;
- (void)viewDidLoad;
- (id)containerView;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)setContainerView:;
- (id)tabBar;
- (void)setLastLocation:;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setTabBar:;
- (BOOL)gestureRecognizer:shouldRequireFailureOfGestureRecognizer:;
- (void)setDelegate:;
- (id)context;
- (id)lineView;
- (void)setLineView:;
- (id)currentModel;
- (void)setCloseButton:;
- (id)closeButton;
- (void)closeButtonTapped;
- (void)setCurrentModel:;
+ (Class)aAWEPadDetailTableAdapterClass;
+ (Class)aAWEDiscoverDPlayletPanelViewControllerAdapterClass;
@end
