@interface AWEEcomSearchListBaseController : AWEBaseController
@property (nonatomic) NSString currentFormat;
@property (nonatomic) BOOL isFromECommerce;
@property (nonatomic) NSString ecomScene;
@property (nonatomic) NSString originalFormat;
@property (nonatomic) AWESearchEcommerceActionRecord actionRecord;
@property (nonatomic) UIViewController<AWEEcomSearchSuspensionLayerProtocol> suspensionLayer;
@property (nonatomic) AWESearchCorrectView suggestView;
@property (nonatomic) AWETrackerContext trackerContext;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) UIView view;
@property (nonatomic) NSString keyword;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) UIViewController<AWESearchResultVCEcomProtocol> searchResultViewController;
@property (nonatomic) @ playerView;
@property (nonatomic) @ player;
@property (nonatomic) AWEDoubleColumnSearchMerchandiseAwemeListController awemeListController;
@property (nonatomic) NSIndexPath transitionIndexPath;
- (id)enterFrom;
- (id)btm_pageIdentifier;
- (id)insertCouponConfig;
- (BOOL)isFromECommerce;
- (id)trackerContext;
- (id)getEnterFromSource;
- (id)awemeListController;
- (void)setAwemeListController:;
- (id)transitionIndexPath;
- (void)setTransitionIndexPath:;
- (id)createDataController;
- (void)jumpToFeedBoxBannerPageWithTypeSort:;
- (void)jumpToUseIndustryCouponWithModel:atIndexPath:;
- (void)sendShowDocsReportRequest:initialParams:;
- (void)calculateBackgroundPositionAndShow;
- (void)adjustFilterExpandViewPosition:;
- (id)actionRecord;
- (id)suspensionLayer;
- (id)suggestView;
- (id)ecomScene;
- (id)resultSourceForIndexPath:;
- (id)appendCommondParamsInLogExtra:;
- (id)btmForCellType:index:isRecommend:model:;
- (id)bcmDescriptionForCellType:;
- (id)getSearchPassThroughParams:;
- (id)bstGroupTypeForCellType:;
- (id)btmInfoForCellType:enterNewPage:index:isRecommend:model:;
- (id)collectionView;
- (id)view;
- (id)searchResultViewController;
- (id)player;
- (void)setPlayerView:;
- (void)setPlayer:;
- (id)playerView;
- (id)originalFormat;
- (id)keyword;
- (id)currentFormat;
- (id)srp;
@end
