@interface AWEECOMIMExtraOrderView : AWEECOMIMCustomBaseView
@property (nonatomic) UIView fullBgView;
@property (nonatomic) UIView bgView;
@property (nonatomic) UIView containerView;
@property (nonatomic) DUXBaseImageView logoView;
@property (nonatomic) DUXBaseImageView importantActivitiesView;
@property (nonatomic) YYLabel titleLabel;
@property (nonatomic) DUXBaseLabel subTitleLabel;
@property (nonatomic) BDPCDDynamicCardPriceView priceView;
@property (nonatomic) DUXBaseButton closeButton;
@property (nonatomic) DUXBaseButton sendButton;
@property (nonatomic) AWEECOMIMExtraOrderOldView orderOldView;
@property (nonatomic) @? animationCompletionBlock;
@property (nonatomic) AWEECOMIMExtraCardModel itemModel;
@property (nonatomic) q style;
@property (nonatomic) <AWEECOMIMExtraOrderViewDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)closeButtonClick:;
- (id)itemModel;
- (void)setItemModel:;
- (id)priceView;
- (void)setPriceView:;
- (void)startShowAnimation;
- (void)updateWithItemModel:style:;
- (void)startHideAnimation;
- (id)importantActivitiesView;
- (void)setImportantActivitiesView:;
- (void)sendButtonClick:;
- (id)fullBgView;
- (void)updateWithRectangleOldStyle;
- (id)orderOldView;
- (void)setOrderOldView:;
- (void)updateAccessibilityElement;
- (void)setFullBgView:;
- (void)animationDidStop:finished:;
- (id)delegate;
- (id)containerView;
- (long long)style;
- (void)setContainerView:;
- (void)customInit;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (void)setStyle:;
- (id)animationCompletionBlock;
- (id)bgView;
- (void)setAnimationCompletionBlock:;
- (void)setBgView:;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
- (void)setCloseButton:;
- (id)closeButton;
- (id)sendButton;
- (void)setSendButton:;
- (id)logoView;
- (void)setLogoView:;
+ (id)designSizeWithWidth:style:;
+ (double)horizontalMarginWithStyle:;
@end
