@interface AWEECOMIMPaasMessageBridgeNew : NSObject
@property (nonatomic) <BDECPigeonMessageInterface> pigeonMessage;
@property (nonatomic) NSString belongingBizConversationIdentifier;
@property (nonatomic) q senderRoleType;
@property (nonatomic) NSString pigeonBizType;
@property (nonatomic) NSString hintContentCustomer;
@property (nonatomic) q sharkState;
@property (nonatomic) NSNumber indexInConversation;
@property (nonatomic) NSNumber orderInConversation;
@property (nonatomic) NSString identifier;
@property (nonatomic) NSString serverMessageID;
@property (nonatomic) NSString clientMessageIDInExt;
@property (nonatomic) NSString bizConversationID;
@property (nonatomic) BOOL isRiskControlled;
@property (nonatomic) NSString riskControlledContent;
@property (nonatomic) NSString content;
@property (nonatomic) NSString receiverSpecialContent;
@property (nonatomic) NSString sharkSpecialContent;
@property (nonatomic) q messageType;
@property (nonatomic) NSString pigeonMessageType;
@property (nonatomic) BOOL isRecalled;
@property (nonatomic) NSString recalledTime;
@property (nonatomic) NSString talkId;
@property (nonatomic) q messageStatus;
@property (nonatomic) NSString customerHint;
@property (nonatomic) NSString sender;
@property (nonatomic) BOOL isSelf;
@property (nonatomic) NSDictionary syncedExt;
@property (nonatomic) NSDictionary syncedExtInternal;
@property (nonatomic) NSDictionary localExt;
@property (nonatomic) NSDictionary originExt;
@property (nonatomic) NSString createTime;
@property (nonatomic) BDECPigeonReferMessageInfo referMessageInfo;
@property (nonatomic) NSNumber indexInPigeonConversation;
@property (nonatomic) NSDictionary msgRenderModel;
@property (nonatomic) NSDictionary renderBody;
@property (nonatomic) NSString subCardType;
@property (nonatomic) NSString localMediaFilePath;
@property (nonatomic) AWEECOMIMRateServiceModel rateServiceModel;
@property (nonatomic) BOOL isRecalledByShark;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awe_bindObserverKeyPath:receiver:receiverKeyPath:;
- (id)awe_observerKeyPath:;
- (id)serverMessageID;
- (id)syncedExt;
- (id)localExt;
- (id)syncedExtInternal;
- (void)setLocalExtEntry:value:completion:;
- (id)indexInConversation;
- (id)orderInConversation;
- (void)updateMessageBody:completion:;
- (id)clientMessageIDInExt;
- (id)pigeonBizType;
- (id)bizConversationID;
- (id)originExt;
- (BOOL)isRiskControlled;
- (id)receiverSpecialContent;
- (id)riskControlledContent;
- (BOOL)isRecalled;
- (id)recalledTime;
- (id)talkId;
- (id)customerHint;
- (id)pigeonMessageType;
- (long long)senderRoleType;
- (id)hintContentCustomer;
- (long long)sharkState;
- (id)belongingBizConversationIdentifier;
- (id)subCardType;
- (id)renderBody;
- (BOOL)isRecalledByShark;
- (void)setLocalMediaFilePath:;
- (id)localMediaFilePath;
- (id)msgRenderModel;
- (id)objectFromExtForKey:;
- (id)referMessageInfo;
- (id)sharkSpecialContent;
- (id)rateServiceModel;
- (void)setRateServiceModel:;
- (id)pigeonMessage;
- (id)initMessageWithIdentifier:inConversation:belongClient:;
- (id)initMessageWithMessageServerID:inConversation:belongClient:;
- (id)indexInPigeonConversation;
- (void)setIsRecalledByShark:;
- (void)setPigeonMessage:;
- (id)sender;
- (void)setSender:;
- (unsigned long long)hash;
- (id)createTime;
- (id)content;
- (id)identifier;
- (void).cxx_destruct;
- (BOOL)isEqual:;
- (long long)messageType;
- (long long)messageStatus;
- (BOOL)isSelf;
+ (id)messageWithPigeonMessage:;
@end
