@interface AWEECShopLiveRoomProfileView : UIView
@property (nonatomic) UIButton backButton;
@property (nonatomic) UIView backgroundColorView;
@property (nonatomic) UIImageView logoImageView;
@property (nonatomic) UIView infoContainer;
@property (nonatomic) UILabel nameView;
@property (nonatomic) UIStackView reputationView;
@property (nonatomic) UILabel visitorNumberLabel;
@property (nonatomic) IESECRelationMultipleFunctionsFollowView followView;
@property (nonatomic) IESECRelationBubbleView bubbleView;
@property (nonatomic) IESECServiceProxy<IESECShopFollowService> followService;
@property (nonatomic) IESECServiceProxy<IESECShopForwardCoService> forwardService;
@property (nonatomic) IESECServiceProxy<IESECShopDataService> dataService;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) double topMargin;
- (id)dataService;
- (id)forwardService;
- (void)exitShop;
- (id)initWithShopContext:;
- (void)setForwardService:;
- (long long)fansClubLevel;
- (void)follow;
- (void)unfollow;
- (void)jumpToJoinFansClubBoard;
- (void)jumpToFansClubMissionBoard;
- (id)followViewBackgroundColor:;
- (id)followViewTextColor:;
- (void)setupBindings;
- (id)followService;
- (id)followView;
- (id)reputationView;
- (void)bindAuthorTracker:;
- (void)jumpToShopDetailPage;
- (void)jumpToShopOwnerProfilePage;
- (void)experienceScoreTracker:;
- (void)p_updateLiveRoomVisitorNumbers:;
- (id)visitorNumberLabel;
- (void)tapLogo;
- (void)tapName;
- (void)tapReputation;
- (void)updateLiveRoomVisitorNumbers:;
- (void)updateFollowStatus:userID:;
- (void)updateWithInfoModel:;
- (void)setInfoContainer:;
- (void)setReputationView:;
- (void)setVisitorNumberLabel:;
- (void)setFollowView:;
- (void)setFollowService:;
- (void)setDataService:;
- (id)backButton;
- (id)nameView;
- (void)setBackButton:;
- (id)backgroundColorView;
- (void).cxx_destruct;
- (void)setBackgroundColorView:;
- (void)setNameView:;
- (double)topMargin;
- (void)setupViews;
- (void)setTopMargin:;
- (id)bubbleView;
- (id)logoImageView;
- (void)setBubbleView:;
- (void)setLogoImageView:;
- (id)infoContainer;
@end
