@interface AWEECImmerseHalfMallViewController : AWEECMallBaseViewController
@property (nonatomic) <AWEECTopMallWrapperImmerseSceneProtocol> delegate;
@property (nonatomic) q currentSizeType;
@property (nonatomic) IESECLynxCardBridgeEventSubscriber subscriber;
@property (nonatomic) NSTimer lazyLoadTimer;
@property (nonatomic) BOOL hasLoadFirstScreenRealData;
@property (nonatomic) BOOL hasCatchControlPower;
@property (nonatomic) BOOL hasStraightOut;
@property (nonatomic) BOOL hasFirstScreen;
@property (nonatomic) BOOL hasSentToolVisibleEvent;
@property (nonatomic) BOOL needRollBackToFullMall;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) BOOL isGradientLayerHidden;
@property (nonatomic) BOOL disableLazyLoad;
@property (nonatomic) q type;
@property (nonatomic) NSString referString;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)canRefresh;
- (id)referString;
- (id)aweui_emptyPageConfigForState:;
- (void)aweui_emptyPagePrimaryButtonTapped:;
- (void)pauseWithAnimation;
- (BOOL)currentTabIsTop;
- (void)animatedRefreshWithCompletion:;
- (void)setTopbarFrame:;
- (id)routerParams;
- (void)configWithRouterParams:;
- (void)buildUI;
- (void)setBcmPageParams;
- (void)mallChannelInnerTheme:;
- (void)mallChannelTransInfo:;
- (id)currentSplicingEnterFrom;
- (void)enterMallWithParams:;
- (id)btmPageBID;
- (id)allNeededRouterParams;
- (void)refreshFirstScreen;
- (BOOL)isFromHomepageHotVideo;
- (id)initWithParams:delegate:;
- (void)contentListDidScroll:;
- (void)mallDidFinishRender:;
- (id)defaultEnterFrom;
- (void)needRefreshSkinInfo:;
- (void)pendantsLayoutUpdated;
- (id)outerBTMHost;
- (void)invalidateLazyTimer;
- (void)unregisterSubscriber;
- (void)setDisableLazyLoad:;
- (BOOL)disableLazyLoad;
- (void)setupLazyLoad;
- (void)buildSubscriber;
- (void)setUpGradientBGLayer;
- (BOOL)needRollBackToFullMall;
- (long long)currentSizeType;
- (void)setNeedRollBackToFullMall:;
- (BOOL)hasLoadFirstScreenRealData;
- (void)setHasLoadFirstScreenRealData:;
- (void)trySentPopFirstScreenToolVisibleEvent;
- (void)setCurrentSizeType:;
- (BOOL)hasCatchControlPower;
- (void)setHasCatchControlPower:;
- (void)setIsGradientLayerHidden:;
- (BOOL)isGradientLayerHidden;
- (void)loadFirstScreen;
- (void)setLazyLoadTimer:;
- (id)lazyLoadTimer;
- (BOOL)hasSentToolVisibleEvent;
- (BOOL)hasFirstScreen;
- (void)setHasSentToolVisibleEvent:;
- (void)topTabChangedWithMallVisible:;
- (void)bottomTabChangedWithMallVisible:;
- (void)needSwitchToGrey:;
- (void)setHasStraightOut:;
- (void)updateSearchBarFrame;
- (void)updateToolBarFrame;
- (void)mallViewDidFirstScreen;
- (void)setHasFirstScreen:;
- (void)slideInMall;
- (void)slideOutMall;
- (void)trackRedDotEvent:params:;
- (id)realContentChildVC;
- (void)mallContainerSizeChanged:;
- (void)transferMallControlPower;
- (void)takeAwayMallControlPower;
- (void)mallContainerBGShow:;
- (void)mallDidFinishStraightOutRender;
- (BOOL)isImmerseSceneMall;
- (long long)immerseMallPageType;
- (BOOL)hasStraightOut;
- (void)setScrollEnabled:;
- (void)viewWillDisappear:;
- (id)init;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)dealloc;
- (void)play;
- (id)delegate;
- (void)scrollToTopAnimated:;
- (id)subscriber;
- (void)setSubscriber:;
- (void)viewDidLoad;
- (void)reload;
- (void)viewDidDisappear:;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)setDelegate:;
- (void)stop;
- (void)pause;
- (id)gradientLayer;
- (void)setGradientLayer:;
- (void)handlePanGesture:;
- (double)contentTopMargin;
- (id)pageName;
@end
