@interface AWEEccsIMLoginParamModel : IESLiveBridgeModel
@property (nonatomic) NSString appID;
@property (nonatomic) NSString fpID;
@property (nonatomic) NSString token;
@property (nonatomic) NSString pigeonCID;
@property (nonatomic) NSString httpDomain;
@property (nonatomic) NSString frontierDomain;
@property (nonatomic) NSDictionary wsCustomHeaders;
@property (nonatomic) NSArray inboxes;
@property (nonatomic) NSString appKey;
@property (nonatomic) NSNumber service;
@property (nonatomic) NSNumber method;
@property (nonatomic) NSArray bizCustomMethods;
@property (nonatomic) NSArray filterMsgTypeSet;
@property (nonatomic) NSDictionary pullReadStateInboxToBizRoleMapper;
@property (nonatomic) NSDictionary pbHeaders;
@property (nonatomic) NSDictionary imHttpQuery;
@property (nonatomic) NSNumber sendConversationList;
@property (nonatomic) NSNumber doNotLogoutButCloseWsWhenLostHeartbeat;
- (void)setAppKey:;
- (id)appKey;
- (id)httpDomain;
- (id)fpID;
- (void)setFpID:;
- (void)setInboxes:;
- (id)pullReadStateInboxToBizRoleMapper;
- (void)setPullReadStateInboxToBizRoleMapper:;
- (void)setBizCustomMethods:;
- (id)filterMsgTypeSet;
- (void)setFilterMsgTypeSet:;
- (id)bizCustomMethods;
- (id)wsCustomHeaders;
- (void)setWsCustomHeaders:;
- (id)pigeonCID;
- (void)setPigeonCID:;
- (void)setHttpDomain:;
- (id)frontierDomain;
- (void)setFrontierDomain:;
- (id)pbHeaders;
- (void)setPbHeaders:;
- (id)imHttpQuery;
- (void)setImHttpQuery:;
- (id)sendConversationList;
- (void)setSendConversationList:;
- (id)doNotLogoutButCloseWsWhenLostHeartbeat;
- (void)setDoNotLogoutButCloseWsWhenLostHeartbeat:;
- (id)service;
- (void)setService:;
- (void)setMethod:;
- (id)appID;
- (void)setAppID:;
- (void).cxx_destruct;
- (id)method;
- (void)setToken:;
- (id)token;
- (id)inboxes;
+ (id)modelCustomPropertyMapper;
@end
