@interface AWEEcommerceSearchLynxBaseView : UIView
@property (nonatomic) BOOL shouldReuseLynxView;
@property (nonatomic) <AWESearchDynamicEngineProtocol> searchLynxEngine;
@property (nonatomic) AWEDynamicPatchModel dynamicPatch;
@property (nonatomic) BOOL isActive;
@property (nonatomic) double currPlaybackTime;
@property (nonatomic) UIViewController hostViewController;
@property (nonatomic) @? lynxElementDidMount;
@property (nonatomic) @? lynxEngineDidUpdate;
@property (nonatomic) @? lynxEngineDidPageUpdate;
@property (nonatomic) @? lynxViewDidFailLoad;
@property (nonatomic) @? lynxViewSizeChanged;
@property (nonatomic) @? lynxElementWillEnterFullScreen;
@property (nonatomic) @? lynxElementDidBecomeActive;
@property (nonatomic) @? lynxElementDidResignActive;
@property (nonatomic) @? lynxElementScrollToTop;
@property (nonatomic) @? LynxElementScrollelement;
@property (nonatomic) @? lynxWillTransitionBackToVideoFeed;
@property (nonatomic) @? lynxDidTransitionBackToVideoFeed;
@property (nonatomic) @? LynxElemenVideoPlayerDidEnd;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL needPlayFinish;
@property (nonatomic) double playInterval;
@property (nonatomic) @? playDidFinishBlock;
- (double)currPlaybackTime;
- (id)dynamicPatch;
- (void)setDynamicPatch:;
- (void)setCurrPlaybackTime:;
- (id)lynxViewSizeChanged;
- (void)setLynxViewSizeChanged:;
- (id)livePlayerView;
- (void)notifyDisappear:;
- (void)notifyAppear:;
- (void)didStartShowing;
- (void)didEndShowing;
- (id)initWithShouldReuseLynxView:;
- (id)lynxViewDidFailLoad;
- (void)updateWithModel:containerWidth:;
- (id)searchLynxEngine;
- (void)lynxEngineDidUpdate:;
- (void)lynxEngine:didFailLoadWithError:;
- (void)setLynxViewDidFailLoad:;
- (void)setLynxElementDidMount:;
- (void)setLynxEngineDidPageUpdate:;
- (void)setLynxEngineDidUpdate:;
- (void)setLynxElementWillEnterFullScreen:;
- (void)setLynxElementDidBecomeActive:;
- (void)setLynxElementDidResignActive:;
- (void)setLynxWillTransitionBackToVideoFeed:;
- (void)setLynxDidTransitionBackToVideoFeed:;
- (void)setLynxElementScrollelement:;
- (void)setLynxElementScrollToTop:;
- (void)setLynxElemenVideoPlayerDidEnd:;
- (void)addEcomLynxImageIfNeeded:dynamicPatchModel:;
- (BOOL)isCommerceCard:;
- (void)setSearchLynxEngine:;
- (id)lynxElementDidMount;
- (id)lynxEngineDidUpdate;
- (id)lynxEngineDidPageUpdate;
- (id)lynxElementWillEnterFullScreen;
- (id)lynxElementDidBecomeActive;
- (id)lynxElementDidResignActive;
- (id)lynxElementScrollToTop;
- (id)LynxElementScrollelement;
- (id)lynxWillTransitionBackToVideoFeed;
- (id)lynxDidTransitionBackToVideoFeed;
- (id)LynxElemenVideoPlayerDidEnd;
- (void)lynxEngine:viewDidChangeIntrinsicContentSize:;
- (void)lynxEngineDidPageUpdate:;
- (void)lynxEngineSearchLynxElementDidMount:;
- (void)lynxEngineSearchLynxElementDidBecomeActive:;
- (void)lynxEngineSearchLynxElementWillEnterFullScreen:;
- (void)lynxEngineSearchLynxElementDidResignActive:;
- (void)lynxEngineSearchLynxElementScrollToTopWithOffset:animated:;
- (void)lynxEngineSearchLynxElementScrollelement:toPosition:offset:;
- (void)lynxEngineSearchLynxElemenVideoPlayerDidEnd:;
- (void)lynxEngineWillTransitionBackToVideoFeed;
- (void)lynxEngineDidTransitionBackToVideoFeed;
- (BOOL)lynxEngineNotUpdataPlayerForTransition;
- (void)lynxEngine:updateAwemeList:;
- (void)setShouldReuseLynxView:;
- (BOOL)shouldReuseLynxView;
- (void)didBecomeActive;
- (void)setIsActive:;
- (void)dealloc;
- (void)prepareForReuse;
- (void)didResignActive;
- (void).cxx_destruct;
- (BOOL)isActive;
- (id)activeView;
- (void)addObservers;
- (id)hostViewController;
- (void)setHostViewController:;
- (void)resetPlayer;
- (id)livePlayer;
+ (void)appendSearchCommonParamsWithModel:containerWidth:logData:isFromECommerce:extraParams:;
+ (id)dynamicPatchModelWithPreprocessed:;
+ (BOOL)useECImageWithDynamicPatch:;
+ (id)newSchema:cardTypeName:;
@end
