@interface AWEEcomSearchModuleService : HTSService
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (Class)merchandiseViewControllerClass;
- (Class)ecomSearchLynxBaseCellClass;
- (Class)ecomSearchLiveTabViewControllerClass;
- (BOOL)SRPOptimizeWithResponder:;
- (BOOL)isGeckoSearchDynamicWithScene:;
- (id)progressSearchDynamic:schema:searchScene:;
- (void)trackLynxLoadInfoWithModel:searchScene:;
- (void)ecomSearchShowComponentWithContainer:params:completion:;
- (id)searchGoodsScanViewControllerWithImage:extra:;
- (id)createLiveGoodsCellInEcomLivePhotoSearchPanel:;
- (id)createSketchViewWithFrame:geckoImageName:type:;
- (id)createDoubleMerchandiseDataProvider;
- (id)createDoubleMerchandiseResourceLoader;
- (Class)getPendantHelper;
- (id)getSuspensionLayer;
- (Class)getApiUpgradeAdapter;
- (BOOL)isSaasEcomSearchResultPageShowing:;
- (void)ecSearchHookEvent:withParams:;
- (id)ecSearchHookConfig;
- (void)saveEcomVirtualWords:;
- (id)getEcomVirtualWordsWithType:;
- (id)getEcomVirtualWordsSessionId;
- (void)pullEcomSearchGeckoPreload:;
- (void)pullEcomSearchGeckoPreloadWithMall;
- (id)identifierForPreRequestWithRootTag:;
- (id)loadEcommerceTabModels;
- (id)loadEcomLiveSearchTabModels;
- (id)loadEcomSceneViewControllers;
- (id)imageSearchResultsViewControllerWithGoodsImage:extra:;
- (id)merchandiseViewController;
- (id)ecommerceSearchLiveTabViewController;
- (id)ecommerceSearchBigSaleTabViewController;
- (id)ecommerceSearchContentTabViewController;
- (id)ecommerceSearchInstantTabViewController;
- (Class)merchandiseUserWindowCellClass;
- (Class)merchandiseTextTagCellClass;
- (id)middlePagePrefetcher:;
- (id)getEstimatedHeightWithPatchModel:;
- (void)setEstimatedHeight:withPatchModel:;
- (id)createPhotoSearchResultsViewControllerWithExtraDict:;
+ (id)getSearchHistory:;
@end
