@interface AWEEnterpriseServiceEvaluateView : AWEEnterpriseMessageBaseView
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) AWERatingView starView;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) UIView feedbacksView;
@property (nonatomic) UIButton submitButton;
@property (nonatomic) NSMutableArray feedBackButtons;
@property (nonatomic) AWEEnterpriseServiceEvaluateViewModel viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)descLabel;
- (void)setDescLabel:;
- (id)starView;
- (void)setStarView:;
- (void)onRateViewTapped:;
- (void)bindViewModel:;
- (void)constraintSubviews;
- (id)feedbacksView;
- (void)updateDescLabel:;
- (void)setupFeedbacks:enabled:localFeedbackIDs:;
- (id)feedBackButtons;
- (void)setFeedBackButtons:;
- (void)changeFeedbackButtonColor:;
- (void)handleSubmitButtonClick;
- (void)setFeedbacksView:;
- (id)currentContentSize;
- (id)viewModel;
- (void)setTitleLabel:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)layoutSubviews;
- (void)setupUI;
- (id)feedbackButton;
- (void)setSubmitButton:;
- (id)submitButton;
@end
