@interface AWEECBcmNetworkChecker : NSObject
@property (nonatomic) BOOL hookFinish;
@property (nonatomic) BOOL syncFinish;
@property (nonatomic) NSDictionary originSettings;
@property (nonatomic) NSInteger enable;
@property (nonatomic) NSInteger shouldReportSuccess;
@property (nonatomic) NSArray monitorList;
@property (nonatomic) NSArray methodList;
@property (nonatomic) NSArray extraOrderPath;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)methodList;
- (void)setMethodList:;
- (void)hookNetwork;
- (BOOL)syncFinish;
- (void)setSyncFinish:;
- (void)setOriginSettings:;
- (id)originSettings;
- (void)setShouldReportSuccess:;
- (void)setMonitorList:;
- (id)monitorList;
- (void)setExtraOrderPath:;
- (BOOL)hookFinish;
- (void)setHookFinish:;
- (void)checkRequest:response:data:;
- (void)checkRequest:accordingToMonitor:response:data:;
- (id)bodyToParams:;
- (id)checkPointsResultFrom:requestParams:;
- (id)appendInfo:accordingToData:;
- (void)reportResultIsSuccess:info:;
- (id)_queryParamDictDecoded:;
- (id)checkRequestParams:accordingToCheckPoint:;
- (id)checkRequestParams:location:paramName:allowValue:uploadRow:;
- (BOOL)isObjectEmpty:;
- (id)valueOfLocation:inParams:;
- (id)valueFrom:index:locations:;
- (void)reportBcmChainLossWithPath:;
- (int)shouldReportSuccess;
- (id)extraOrderPath;
- (id)generateBackupBcmChain;
- (int)enable;
- (void)syncSettings;
- (id)init;
- (void).cxx_destruct;
- (void)setEnable:;
+ (id)pathPrefixToIntercept;
+ (void)handleRequestWithContext:;
+ (id)shared;
@end
