@interface AWEFeedLiveTabRevisitControlView : UIView
@property (nonatomic) NSInteger visitType;
@property (nonatomic) UIView contentView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIImageView arrowImageView;
@property (nonatomic) UIView<AWEFeedLiveMarkViewProtocol> liveMarkView;
@property (nonatomic) UIImageView avatarImageView;
@property (nonatomic) IESLiveGCDTimer timer;
@property (nonatomic) BOOL hasFollowup;
@property (nonatomic) @? clickBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)layoutSubviews;
- (void)didSetAttachingDIContext;
- (void)setClickBlock:;
- (id)clickBlock;
- (void)setLiveMarkView:;
- (id)liveMarkView;
- (void)tapGestureAction;
- (void)setupNormalUI;
- (void)feedLiveTabDidEnter:;
- (void)feedLiveTabDidLeave;
- (void)feedLiveTabWillAppear:;
- (void)feedLiveTabDidDisappear;
- (void)feedLiveTabDidEnterBackground;
- (void)feedLiveTabDidEnterForeground;
- (void)setHasFollowup:;
- (BOOL)hasFollowup;
- (int)visitType;
- (void)setupAnchorAvatarUIWithData:;
- (void)restartShowAnchorLiveAvatarIfNeed;
- (void)hideAnchorLiveAvatar:;
- (void)setVisitType:;
- (void)pauseShowAnchorLiveAvatarTime;
- (void)autoOpenRevisitSection;
- (void)showAnchorLiveAvatarWithData:visitType:;
- (void)showControlView:animation:;
- (void)setTimer:;
- (id)timer;
- (BOOL)pointInside:withEvent:;
- (id)initWithFrame:;
- (id)contentView;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (void)setContentView:;
- (id)titleLabel;
- (void)setupUI;
- (id)avatarImageView;
- (void)setAvatarImageView:;
- (id)arrowImageView;
- (void)setArrowImageView:;
@end
