@interface AWEFeedLongVideoTableViewCell : UITableViewCell
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) AWEFeedLongVideoCellViewController viewController;
@property (nonatomic) q indexPath;
@property (nonatomic) UIViewController parentVC;
@property (nonatomic) NSString referString;
@property (nonatomic) AWEAwemeModel registerElementModel;
@property (nonatomic) q cellDisplayState;
@property (nonatomic) q cellPageAppearState;
@property (nonatomic) @? currentCellPageAppearStateBlock;
@property (nonatomic) ^{EngineAudioWrapper=^?^?^?^?^v} audioWrapper;
@property (nonatomic) ^{EngineVideoWrapper=^?^?^v} videoWrapper;
@property (nonatomic) UIView feedTableViewCellMaskView;
@property (nonatomic) <UIScrollViewDelegate> scrollViewDelegate;
@property (nonatomic) BOOL hadPrepareToDisplay;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)setReferString:;
- (void)prepareForDisplayWithoutCoverImage;
- (id)audioWrapper;
- (void)setAudioWrapper:;
- (id)videoWrapper;
- (void)setVideoWrapper:;
- (void)didDisplay;
- (id)registerElementModel;
- (void)setRegisterElementModel:;
- (void)configWithModel:;
- (long long)cellDisplayState;
- (void)setCellDisplayState:;
- (long long)cellPageAppearState;
- (void)setCellPageAppearState:;
- (id)currentCellPageAppearStateBlock;
- (void)setCurrentCellPageAppearStateBlock:;
- (id)feedTableViewCellMaskView;
- (void)setFeedTableViewCellMaskView:;
- (BOOL)hadPrepareToDisplay;
- (void)setHadPrepareToDisplay:;
- (void)replaceViewController:removeIfExisting:;
- (void)removeCellChildVCForMemoryOpt;
- (void)p_removeChildVC;
- (void)p_addChildVC;
- (void)setModel:;
- (void)dealloc;
- (void)play;
- (long long)indexPath;
- (void)prepareForDisplay;
- (id)viewController;
- (void)setIndexPath:;
- (id)model;
- (void).cxx_destruct;
- (void)reset;
- (void)stop;
- (void)pause;
- (void)setViewController:;
- (void)configureWithModel:;
- (void)didEndDisplaying;
- (void)willDisplay;
- (id)parentVC;
- (void)setParentVC:;
@end
