@interface AWEFamiliarDetailDataController : AWEListDataController
@property (nonatomic) NSNumber cursor;
@property (nonatomic) NSNumber level;
@property (nonatomic) NSNumber fetchCursor;
@property (nonatomic) NSNumber fetchLevel;
@property (nonatomic) Q totalCount;
@property (nonatomic) NSString logID;
@property (nonatomic) Q autoPullCount;
@property (nonatomic) BOOL isRefresh;
@property (nonatomic) q lastPullType;
@property (nonatomic) NSMutableArray filteredAwemeIDs;
@property (nonatomic) NSArray dataSourceDuplicateAwemeIDs;
@property (nonatomic) BOOL hasBlockedInitFetch;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)didFinishLogoutWithUid:;
- (void)loadMoreWithCompletion:;
- (void)initFetchWithCompletion:;
- (id)isEqualBlock;
- (id)addressBookAccess;
- (void)albumAppendImagesNotificationHandler:;
- (void)updateConcernCardListInfo:feedType:;
- (id)locationAccess;
- (id)transferAwemeListIfNeededWithArray:;
- (void)reloadListWithPullType:completion:;
- (id)aAWELiteUGSocialModuleAdapter;
- (long long)lastPullType;
- (void)registerCloneManager;
- (id)transferAwemeModelForLive:;
- (BOOL)hasBlockedInitFetch;
- (void)setHasBlockedInitFetch:;
- (id)aAFDServiceDOUYINLiteAdaper;
- (id)aAWELiteUGMainModuleAdapter;
- (void)addDuplicateAwemeModel:inToBeRemovedArray:;
- (void)listenNotification;
- (void)setLastPullType:;
- (id)__commonParams;
- (void)addAdditionalParams:;
- (void)setAutoPullCount:;
- (unsigned long long)autoPullCount;
- (id)loadmoreDataSourceWithArray:requestId:response:;
- (id)refreshDataSourceWithArray:requestId:response:;
- (void)loadMoreWithCompletion:isReloadToLoadMore:;
- (void)p_storeLiveListWithData:isFetch:;
- (void)p_cachedActiveUserDataWithData:;
- (void)p_postWithURLString:pullType:params:modelClass:completion:;
- (id)transferAwemeModelForUser:;
- (id)transferUserModel:;
- (id)filteredAwemeIDs;
- (id)handleDailyAwemes:;
- (id)filterDuplicatedDatasourceWithArray:requestId:isEqual:didGetDuplicatedArray:needDataSourceDeduplicate:filteredInfo:;
- (BOOL)hasDrawBackPreloadFeed;
- (void)recordDuplicateArray:;
- (id)dataSourceDuplicateAwemeIDs;
- (void)setDataSourceDuplicateAwemeIDs:;
- (void)setFilteredAwemeIDs:;
- (id)fetchCursor;
- (id)fetchLevel;
- (void)reportWithDuplicateArray:;
- (id)initWithCursor:level:;
- (void)setFetchCursor:;
- (void)setFetchLevel:;
- (void)setLevel:;
- (id)cursor;
- (id)URLString;
- (void)dealloc;
- (unsigned long long)totalCount;
- (BOOL)isRefresh;
- (id)level;
- (void)setCursor:;
- (void).cxx_destruct;
- (void)refreshWithCompletion:;
- (void)setIsRefresh:;
- (id)logID;
- (void)setTotalCount:;
- (void)setLogID:;
+ (Class)aAWELiteUGSocialModuleAdapterClass;
+ (Class)aAFDServiceDOUYINLiteAdaperClass;
+ (Class)aAWELiteUGMainModuleAdapterClass;
@end
