@interface AWEFeedDCMidSearchMonitor : NSObject
@property (nonatomic) q containerInitStartTime;
@property (nonatomic) q requestGuessListTime;
@property (nonatomic) q responseGuessListTime;
@property (nonatomic) q getGuessListEndTime;
@property (nonatomic) q guessListRenderStartTime;
@property (nonatomic) q guessListRenderEndTime;
@property (nonatomic) q guessListFirstImageLoadStartTime;
@property (nonatomic) q guessListFirstImageLoadEndTime;
@property (nonatomic) Q pageState;
@property (nonatomic) q requestType;
@property (nonatomic) @? searchDCFeedMonitorBlock;
- (void)setContainerInitStartTime:;
- (long long)containerInitStartTime;
- (void)setRequestGuessListTime:;
- (void)setResponseGuessListTime:;
- (void)setGetGuessListEndTime:;
- (void)setGuessListRenderStartTime:;
- (void)setGuessListRenderEndTime:;
- (void)setGuessListFirstImageLoadStartTime:;
- (void)setGuessListFirstImageLoadEndTime:;
- (void)trackFMPIfNeeded;
- (long long)guessListRenderEndTime;
- (long long)guessListFirstImageLoadEndTime;
- (long long)requestGuessListTime;
- (long long)responseGuessListTime;
- (long long)getGuessListEndTime;
- (long long)guessListRenderStartTime;
- (long long)guessListFirstImageLoadStartTime;
- (id)searchDCFeedMonitorBlock;
- (void)markDCContainerInitIfNeeded;
- (void)resetRequestTimeIfNeeded;
- (void)markRequestGuessListIfNeeded;
- (void)markRequestGuessListIfNeeded:;
- (void)markRequestType:;
- (void)markResponseGuessListIfNeeded;
- (void)markDCPageFetchedDataIfNeeded;
- (void)markDCPageRenderStartIfNeeded;
- (void)markDCPageFirstImageLoadStartIfNeeded;
- (void)markDCPageRenderEndIfNeeded;
- (void)markDCPageFirstImageLoadEndIfNeeded;
- (void)setSearchDCFeedMonitorBlock:;
- (void)setRequestType:;
- (long long)requestType;
- (void)resetAll;
- (void).cxx_destruct;
- (unsigned long long)pageState;
- (void)setPageState:;
+ (id)sharedInstance;
@end
