@interface AWEFeedRVCardVideoControlFakeProgressController : AWEFeedRVCardVideoControlBaseController
@property (nonatomic) AWEFeedRVCardVideoControlFakeProgressContainerView fakeProgressContainerView;
@property (nonatomic) UIView<AWEFakeProgressSliderViewProtocol> fakeProgressSliderView;
@property (nonatomic) UIView progressTimeContainerView;
@property (nonatomic) UILabel progressTimeLeftLabelView;
@property (nonatomic) UILabel divideLabelView;
@property (nonatomic) UILabel progressTimeRightLabelView;
@property (nonatomic) UIView gradientBackgroundView;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) {CGPoint=dd} lastLocation;
@property (nonatomic) double lastPlayTime;
- (double)lastPlayTime;
- (void)setLastPlayTime:;
- (void)setGradientBackgroundView:;
- (void)setFakeProgressContainerView:;
- (void)setupGradientBackgroundView;
- (id)fakeProgressContainerView;
- (id)fakeProgressSliderView;
- (id)progressTimeContainerView;
- (id)progressTimeLeftLabelView;
- (id)divideLabelView;
- (id)progressTimeRightLabelView;
- (void)updateProgressTimeLeftRightLabelView;
- (void)showFakeProgress:completion:;
- (void)trackClickProgressBarWithActionType:;
- (void)setFakeProgressSliderView:;
- (void)setProgressTimeContainerView:;
- (void)setProgressTimeLeftLabelView:;
- (void)setDivideLabelView:;
- (void)setProgressTimeRightLabelView:;
- (id)lastLocation;
- (void)viewDidLoad;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)setLastLocation:;
- (void).cxx_destruct;
- (id)gradientLayer;
- (void)setGradientLayer:;
- (void)setupUI;
- (void)handlePanGesture:;
- (id)gradientBackgroundView;
@end
