@interface AWEFeedLiveHeadDecorationView : UIView
@property (nonatomic) UIView containerView;
@property (nonatomic) UIView topContainerView;
@property (nonatomic) UIImageView iconImageView;
@property (nonatomic) UIImageView mainIconImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel nextTitleLabel;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) NSDictionary roomDict;
@property (nonatomic) BOOL isAnimating;
@property (nonatomic) BOOL showMainIconAnimation;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setRoomDict:;
- (id)roomDict;
- (id)topContainerView;
- (void)setTopContainerView:;
- (void)p_setUpUI;
- (void)updateWithRoomDict:;
- (void)setMainIconImageView:;
- (id)mainIconImageView;
- (void)setNextTitleLabel:;
- (id)p_contents;
- (id)p_iconUrls;
- (BOOL)isTreasureBox;
- (void)setShowMainIconAnimation:;
- (double)timeBeforeContentRoll;
- (BOOL)showMainIconAnimation;
- (BOOL)boxAnimationRepeat;
- (int)couponMateId;
- (id)initWithFrame:;
- (id)containerView;
- (void)startAnimation;
- (void)setContainerView:;
- (BOOL)isAnimating;
- (void)setTitleLabel:;
- (id)iconImageView;
- (void).cxx_destruct;
- (void)setIsAnimating:;
- (id)titleLabel;
- (void)layoutSubviews;
- (id)gradientLayer;
- (void)stopAnimation;
- (void)setGradientLayer:;
- (void)setIconImageView:;
- (id)nextTitleLabel;
@end
