@interface AWEFormatRTCClientConfig : NSObject
@property (nonatomic) q env;
@property (nonatomic) NSString rtcAppID;
@property (nonatomic) NSString rtcToken;
@property (nonatomic) NSString rtcBusinessID;
@property (nonatomic) NSString rtcUserID;
@property (nonatomic) NSString rtcRoomID;
@property (nonatomic) NSString rtcSignKey;
@property (nonatomic) NSDictionary rtcVideoParam;
@property (nonatomic) NSString appID;
@property (nonatomic) NSString appVersion;
@property (nonatomic) NSString deviceID;
@property (nonatomic) NSString abTestConfig;
- (long long)env;
- (void)setRtcToken:;
- (void)setRtcUserID:;
- (void)setRtcRoomID:;
- (void)setRtcAppID:;
- (void)setEnv:;
- (id)abTestConfig;
- (void)setupWithConfigDict:;
- (void)setRtcSignKey:;
- (id)initWithConfigString:;
- (id)rtcAppID;
- (id)rtcToken;
- (id)rtcBusinessID;
- (void)setRtcBusinessID:;
- (id)rtcUserID;
- (id)rtcRoomID;
- (id)rtcSignKey;
- (id)rtcVideoParam;
- (void)setRtcVideoParam:;
- (void)setAbTestConfig:;
- (id)appVersion;
- (void)setDeviceID:;
- (void)setAppVersion:;
- (id)appID;
- (void)setAppID:;
- (void).cxx_destruct;
- (id)deviceID;
- (id)initWithConfigDict:;
@end
