@interface AWEFeedDoubleColumnManager : NSObject
@property (nonatomic) NSMutableArray feedModelsItemIDs;
@property (nonatomic) BOOL isDoubleColumnIconDebugOn;
@property (nonatomic) BOOL alreadyTrackC2RecommendEntryShow;
@property (nonatomic) BOOL isInC2Channel;
@property (nonatomic) BOOL alreadyClick;
@property (nonatomic) BOOL alreadyStayEnough;
@property (nonatomic) NSMutableSet hasTrackedEntranceShow;
@property (nonatomic) AWEHotListDataController hotListDataController;
@property (nonatomic) UIViewController doubleColumnVC;
@property (nonatomic) BOOL isPersonalRecommendSwitchOn;
@property (nonatomic) BOOL canEnterDoubleColumnChannel;
@property (nonatomic) BOOL isViewControllerShowing;
@property (nonatomic) BOOL isShowingTabBarEntryGuide;
@property (nonatomic) NSString processID;
@property (nonatomic) double enterTimestamp;
@property (nonatomic) double innerEnterTimestamp;
@property (nonatomic) BOOL hasTrackFMPEvent;
@property (nonatomic) BOOL useVCPreload;
@property (nonatomic) BOOL isDefaultLanding;
@property (nonatomic) double firstEnterTimestamp;
@property (nonatomic) double firstEnterSwitchPreviewTimestamp;
@property (nonatomic) BOOL hasAlreadyPreload;
@property (nonatomic) BOOL isOuterFirstReq;
@property (nonatomic) double firstEnterDoubleColumnTime;
@property (nonatomic) q outerPreloadType;
@property (nonatomic) BOOL hasReportVCCreatTime;
@property (nonatomic) NSString enterHomepageTabEnterMethod;
@property (nonatomic) NSString seleectedItemID;
@property (nonatomic) NSString tapGuideItemID;
@property (nonatomic) BOOL hasCheckTapGuide;
@property (nonatomic) BOOL hasEnterInnerFeed;
@property (nonatomic) q innerBackMethod;
@property (nonatomic) BOOL isInnerFlowShowing;
@property (nonatomic) BOOL isFirstEnterDoubleColumnChannel;
@property (nonatomic) NSString topTabTapRegion;
@property (nonatomic) BOOL enterByLandingOptimize;
@property (nonatomic) double landingOptimizeEnterTimestamp;
@property (nonatomic) double needPlayedAwemeTime;
@property (nonatomic) AWEAwemeModel needPlayedAweme;
@property (nonatomic) BOOL isOuterPlaying;
@property (nonatomic) BOOL hasFirstRefresh;
@property (nonatomic) BOOL couldPlayOuterVideo;
@property (nonatomic) q needPlayedImageIndex;
@property (nonatomic) BOOL isFeedPlaying;
@property (nonatomic) AWEAwemeModel prePlayedAweme;
@property (nonatomic) AWEAwemeModel curPlayedAweme;
@property (nonatomic) BOOL couldRearrange;
@property (nonatomic) BOOL shouldSyncImageIndexToFeed;
@property (nonatomic) q needSyncImageIndex;
@property (nonatomic) AWEAwemeModel continuePlayInsertedAweme;
@property (nonatomic) BOOL didClickC2RecommendEntrance;
@property (nonatomic) BOOL didEnterC2;
@property (nonatomic) BOOL isFromFeed;
@property (nonatomic) BOOL willEnterSwitchPreviewPage;
@property (nonatomic) BOOL isInSwitchPreviewPage;
@property (nonatomic) BOOL willLeaveSwitchPreviewPage;
@property (nonatomic) q enterSwitchPreviewTimes;
@property (nonatomic) UIViewController<AWEDCFeedSwitchPreviewVCProtocol> feedSwitchPreviewVC;
@property (nonatomic) AWEFeedTableViewController feedTableVC;
@property (nonatomic) double entryTouchOptLastClickTimestamp;
@property (nonatomic) BOOL isRadicalLeaveGuideShowing;
@property (nonatomic) AWEFeedDoubleColumnTabQuitGuideView leaveGuideMaskView;
@property (nonatomic) BOOL isRadicalEntryGuideShowing;
@property (nonatomic) AWEAwemeModel currentAweme;
- (id)currentAweme;
- (double)enterTimestamp;
- (void)setEnterTimestamp:;
- (BOOL)isPersonalRecommendSwitchOn;
- (id)pageTypeString;
- (void)setEntryTouchOptLastClickTimestamp:;
- (BOOL)canEnterDoubleColumnChannel;
- (void)c2LandingCheckVidIfNeeded;
- (BOOL)isFirstOuterFromDoulbeColumnWithItemID:;
- (BOOL)inSwitchPreviewPage;
- (void)trackC2RecommendEntryShowWithParams:;
- (BOOL)didClickC2RecommendEntrance;
- (void)setCurrentAweme:;
- (void)setIsFromFeed:;
- (BOOL)isFromFeed;
- (id)feedTableVC;
- (id)tapGuideItemID;
- (void)setTapGuideItemID:;
- (void)setIsViewControllerShowing:;
- (BOOL)isViewControllerShowing;
- (void)setIsDefaultLanding:;
- (BOOL)isDefaultLanding;
- (double)innerEnterTimestamp;
- (void)resetC2EntryInfoAndBringToStrongBySettingChange;
- (void)setIsInSwitchPreviewPage:;
- (void)setWillEnterSwitchPreviewPage:;
- (id)curPlayedAweme;
- (void)setWillLeaveSwitchPreviewPage:;
- (BOOL)willLeaveSwitchPreviewPage;
- (void)setFeedTableVC:;
- (id)doubleColumnVC;
- (BOOL)ignoreLiveAutoPlay;
- (void)setHotListDataController:;
- (BOOL)couldPlayOuterVideo;
- (BOOL)isNeedPlayedAweme:;
- (double)needPlayedAwemeTime;
- (long long)needPlayedImageIndex;
- (void)setIsOuterPlaying:;
- (void)setNeedPlayedAwemeTime:;
- (BOOL)isFeedPlaying;
- (void)setNeedPlayedImageIndex:;
- (void)setInnerEnterTimestamp:;
- (void)setSeleectedItemID:;
- (void)setIsOuterFirstReq:;
- (id)enterHomepageTabEnterMethod;
- (void)setOuterPreloadType:;
- (BOOL)isOuterFirstReq;
- (void)recordFeedScrollIfNeed:referString:;
- (BOOL)hasAlreadyPreload;
- (void)setHasAlreadyPreload:;
- (BOOL)willEnterSwitchPreviewPage;
- (void)trackEntranceShowEvent:;
- (BOOL)readIconDebugOnStatus;
- (void)setIsDoubleColumnIconDebugOn:;
- (void)setIsInC2Channel:;
- (void)setAlreadyClick:;
- (void)setAlreadyStayEnough:;
- (void)setHasTrackedEntranceShow:;
- (id)seleectedItemID;
- (void)setTopTabTapRegion:;
- (void)trackEntranceShowEventWithParams:;
- (id)hasTrackedEntranceShow;
- (void)c2LandingCheckMaxClickByClickDateArray:currentDate:;
- (void)c2LandingClearAllRecord;
- (void)c2LandingPostUpdateByQuit:;
- (BOOL)enterByLandingOptimize;
- (double)landingOptimizeEnterTimestamp;
- (BOOL)isInSwitchPreviewPage;
- (BOOL)isSwitchPreviewTargetDoubleColumn;
- (id)feedSwitchPreviewVC;
- (void)clearReturnStrongInfo;
- (void)setDidEnterC2:;
- (void)beginStayTimeIfNeededForWeakEntry;
- (BOOL)alreadyStayEnough;
- (BOOL)isInC2Channel;
- (BOOL)alreadyClick;
- (void)updateEnterC2TimeStampIfNeededWithAction:;
- (BOOL)didEnterC2;
- (id)feedModelsItemIDs;
- (BOOL)isInnerFlowShowing;
- (void)trackInnerBack;
- (void)setInnerBackMethod:;
- (long long)innerBackMethod;
- (void)setNeedPlayedAweme:;
- (BOOL)hasFirstRefresh;
- (void)setCouldRearrange:;
- (BOOL)isSwitchPreviewSourceHomepageHot;
- (BOOL)couldBringToDoubleColumn:;
- (void)clearPlayInfo;
- (void)setIsFeedPlaying:;
- (void)setCouldPlayOuterVideo:;
- (void)setPrePlayedAweme:;
- (void)setCurPlayedAweme:;
- (id)needPlayedAweme;
- (void)setHasFirstRefresh:;
- (void)setNeedSyncImageIndex:;
- (void)setShouldSyncImageIndexToFeed:;
- (void)recordTopBarClickPosition:itemSize:;
- (void)trackEntranceNotShowEvent;
- (void)c2LandingRecordLeaveByMethod:;
- (void)c2LandingRecordClick;
- (void)handleC2LandingOptimizeQuitIfNeeded;
- (void)c2LandingRecordEnter:;
- (BOOL)shouldPreventDCAutoActionInPreview;
- (BOOL)shouldIgnoreStayTimeInPreview;
- (BOOL)isClickRefreshedInSwitchPreview;
- (void)setHasEnterInnerFeed:;
- (void)syncFeedVideoToDoubleColumn;
- (void)resignVideoPlayerByModel:;
- (void)insertNeedPlayedAwemeToSectionViewModels:withSectionModel:inStatus:ignoreFirstLimit:;
- (void)recordImageAlbumIndex:;
- (BOOL)entryShowAlreadyTrack:;
- (id)hotListDataController;
- (void)setDoubleColumnVC:;
- (void)setIsPersonalRecommendSwitchOn:;
- (void)setCanEnterDoubleColumnChannel:;
- (BOOL)isShowingTabBarEntryGuide;
- (void)setIsShowingTabBarEntryGuide:;
- (BOOL)hasTrackFMPEvent;
- (void)setHasTrackFMPEvent:;
- (BOOL)useVCPreload;
- (void)setUseVCPreload:;
- (double)firstEnterTimestamp;
- (void)setFirstEnterTimestamp:;
- (double)firstEnterSwitchPreviewTimestamp;
- (void)setFirstEnterSwitchPreviewTimestamp:;
- (double)firstEnterDoubleColumnTime;
- (void)setFirstEnterDoubleColumnTime:;
- (long long)outerPreloadType;
- (BOOL)hasReportVCCreatTime;
- (void)setHasReportVCCreatTime:;
- (void)setEnterHomepageTabEnterMethod:;
- (BOOL)hasCheckTapGuide;
- (void)setHasCheckTapGuide:;
- (BOOL)hasEnterInnerFeed;
- (void)setIsInnerFlowShowing:;
- (BOOL)isFirstEnterDoubleColumnChannel;
- (void)setIsFirstEnterDoubleColumnChannel:;
- (id)topTabTapRegion;
- (void)setEnterByLandingOptimize:;
- (void)setLandingOptimizeEnterTimestamp:;
- (BOOL)isOuterPlaying;
- (id)prePlayedAweme;
- (BOOL)couldRearrange;
- (BOOL)shouldSyncImageIndexToFeed;
- (long long)needSyncImageIndex;
- (id)continuePlayInsertedAweme;
- (void)setContinuePlayInsertedAweme:;
- (void)setDidClickC2RecommendEntrance:;
- (long long)enterSwitchPreviewTimes;
- (void)setEnterSwitchPreviewTimes:;
- (void)setFeedSwitchPreviewVC:;
- (double)entryTouchOptLastClickTimestamp;
- (BOOL)isRadicalLeaveGuideShowing;
- (void)setIsRadicalLeaveGuideShowing:;
- (id)leaveGuideMaskView;
- (void)setLeaveGuideMaskView:;
- (BOOL)isRadicalEntryGuideShowing;
- (void)setIsRadicalEntryGuideShowing:;
- (void)setFeedModelsItemIDs:;
- (BOOL)isDoubleColumnIconDebugOn;
- (BOOL)alreadyTrackC2RecommendEntryShow;
- (void)setAlreadyTrackC2RecommendEntryShow:;
- (id)init;
- (id)processID;
- (void).cxx_destruct;
- (void)setProcessID:;
+ (long long)doubleColumnBigModeOptThird;
+ (void)startPrefetchVideo:tag:preloadSize:bussinessID:customHeaderDic:successBlock:failureBlock:cancelBlock:;
+ (BOOL)longPressHomepageEnable;
+ (BOOL)isFeedDoubleColumnModel:;
+ (BOOL)switchPreviewEntryEnable;
+ (BOOL)fixLandingConfig;
+ (BOOL)doubleColumnShouldUseBigFont:;
+ (long long)doubleColumnBigModeOpt;
+ (BOOL)enableDoubleColumnSearchAfterClick;
+ (long long)c2RecommendEntryNewEntryDetailType;
+ (id)c2RecommendEntryNewEntryDetailIconUrl;
+ (BOOL)c2RecommendEntryNewEntryEnable;
+ (id)c2RecommendEntryNewEntryDetailBackground;
+ (double)c2RecommendEntryNewEntryDetailRadius;
+ (id)c2RecommendEntryNewEntryDetailText;
+ (BOOL)shouldShowC2RecommendEntry;
+ (BOOL)c2RecommendEntrySettingSwitch;
+ (void)updateRecommendEntryPanelWithImageView:;
+ (BOOL)c2RecommendEntrySettingSwitchDefaultOff;
+ (BOOL)c2RecommendEntryUseBigFontEnable;
+ (BOOL)c2RecommendEntryHotZoneEnable;
+ (long long)c2RecommendEntryHotZoneLeft;
+ (long long)c2RecommendEntryHotZoneRight;
+ (long long)c2RecommendEntryHotZoneTop;
+ (long long)c2RecommendEntryHotZoneBottom;
+ (long long)c2RecommendEntryMarginBottom;
+ (long long)c2RecommendEntryMarginTop;
+ (BOOL)c2RecommendEntryNewEntryDisableHardAd;
+ (BOOL)c2RecommendWeakEntryStyleEnable;
+ (long long)shouldShowC2RecommendWeakEntrance;
+ (long long)c2RecommendWeakEntryStyle;
+ (BOOL)c2RecommendWeakEntryRecoveryWhenClick;
+ (id)c2RecommendWeakEntryIconInfo;
+ (void)updateRecommendEntryMarginBottom:;
+ (double)getRecommendEntryMarginBottom;
+ (BOOL)c2RecommendEntryDragEnable;
+ (BOOL)c2RecommendEntryDragEnableLeftHide;
+ (BOOL)c2RecommendEntryDragEnableRightWeak;
+ (long long)c2RecommendEntryDragWeakThreshold;
+ (long long)c2RecommendEntryDragTipsThreshold;
+ (long long)c2RecommendEntryDragHideThreshold;
+ (BOOL)c2RecommendEntrySwipeEnable;
+ (void)updateEnterC2WeakCustom;
+ (void)resetEnterC2WeakCustom;
+ (BOOL)c2RecommendEntryTouchOptConfigEnable;
+ (long long)c2RecommendEntryTouchOptConfigClickTimeLimit;
+ (BOOL)c2RecommendEntryTouchOptConfigEnableAdaptDoubleClick;
+ (BOOL)frequencyTimeControlIsOkByLastDate:checkDate:cooldownHours:;
+ (long long)maxUnconsumedItemCount;
+ (long long)minUnconsumedScreenCount;
+ (id)smartLoadMoreConfig;
+ (id)dislikeLongPressPanelConfig;
+ (id)innerGuideText;
+ (BOOL)enableDoubleColunmDetailSearchBar;
+ (BOOL)isFrequencyControlOK:;
+ (unsigned long long)switchPreviewLayoutStyle;
+ (BOOL)enableOptSwitchPreviewClickAnimation;
+ (unsigned long long)switchPreviewTabIconType;
+ (BOOL)shouldShowC2RecommendEntryInSwitchPreView;
+ (long long)getDoubleColumnContinueImageAndReinsert;
+ (BOOL)useTidyModelFirstRefresh;
+ (BOOL)enableChunkPreloadOpt;
+ (BOOL)enableTidyModelDetailOpt;
+ (BOOL)addPlayOrderToVideoPlayQualityTrack;
+ (long long)c2PreloadDataType;
+ (long long)radicalEntryGuideType;
+ (double)c2PreloadMinDayInterval;
+ (BOOL)dayOverIntervalSinceTimeStamp:interval:;
+ (BOOL)doubleColumnPlaceHolderEnableWhenNotLogin;
+ (long long)entranceStyle;
+ (id)doubleColumnExp;
+ (BOOL)enableShowSwitchNewStyle;
+ (BOOL)c2RecommendEntrySwitchButton;
+ (BOOL)enableSwitchButtonNewStyle;
+ (id)recBackButtonOptConfig;
+ (BOOL)isEqualHeightMode;
+ (id)c2LandingOptimizeConfig;
+ (BOOL)c2LandingOptimizeEnable;
+ (long long)c2LandingOptimizeEffectivePeriod;
+ (long long)c2LandingOptimizeVid;
+ (long long)c2LandingOptimizeExitProtectionTime;
+ (long long)c2LandingOptimizeEffectiveCardClickTime;
+ (long long)c2LandingOptimizeConsecutiveExitTime;
+ (long long)c2LandingOptimizeExitC2Time;
+ (BOOL)switchPreviewContainerRefactor;
+ (id)switchPreviewClickOptDict;
+ (BOOL)enableOptSwitchPreviewClickDuration;
+ (id)c2RecommendEntrySettingSwitchDetail;
+ (id)c2RecommendEntryHotZoneSettings;
+ (id)c2RecommendEntryTouchOptConfig;
+ (id)c2RecommendWeakEntryStyleSettings;
+ (id)c2RecommendEntryStyle;
+ (BOOL)c2RecommendEntryTotalEnable;
+ (BOOL)screenHeightEnableNewEntry;
+ (id)c2RecommendEntryEnableDragSettings;
+ (BOOL)c2RecommendWeakEntryTotalEnable;
+ (void)resetInfoForBringStrong;
+ (BOOL)enableKeepStrong;
+ (BOOL)c2RecommendWeakEntryDefaultWeak;
+ (BOOL)c2EntryReturnStrongEnable;
+ (long long)entryReturnStrongVersion;
+ (long long)getReturnStrongABMaxCount;
+ (long long)strongDayForLoop:;
+ (long long)c2EntryEnableKeepStrongVersion;
+ (void)logStrongTimeIfNeeded;
+ (long long)c2EntryEnableKeepStrongDay;
+ (BOOL)shouldResetC2EntryWeakStatus;
+ (void)trackC2NewEntryBringStrongWithType:;
+ (long long)weakDayForLoop:;
+ (long long)getReturnStrongABType;
+ (id)getC2EntryKeepStrongDict;
+ (id)getReturnStrongABDict;
+ (id)doubleColumnSearchExpDict;
+ (id)getRadicalGuideExperiment;
+ (long long)radicalLeaveGuideType;
+ (long long)radicalLeaveMaskShowCount;
+ (long long)radicalLeavePopoverShowCount;
+ (BOOL)needShowRadicalLeaveGuide;
+ (long long)radicalEntryGuideNeedVideosNumber;
+ (id)modelTypeWhiteList;
+ (id)getEntryPopoverGuideCountKey;
+ (long long)radicalEntryPopoverShowCount;
+ (id)getEntryGuideMaskHasShowKey;
+ (id)radicalGuideOptimizeKevaKey;
+ (BOOL)alreadyShowRefreshBubbleByType:;
+ (long long)getDoubleColumnContinuePlayStyle;
+ (long long)bigFontType;
+ (BOOL)isEnableDash:;
+ (id)hpEntryLeaveGuideConfig;
+ (id)hpEntryEnterGuideConfig;
+ (id)recommendEntryReverseConfig;
+ (BOOL)enableReverseRecommendEntry;
+ (long long)enterDoubleColumnTimesFromHPEntry;
+ (BOOL)shouldOptimizeRefresh;
+ (BOOL)preloadTaskSwitch;
+ (BOOL)quickSwitchOfOldStyleShow;
+ (BOOL)quickSwitchOfNewStyleShow;
+ (id)quickSwitchText;
+ (id)switchRecommendChannelText;
+ (id)switchDoubleColumnChannelText;
+ (double)maxImageRateNotEqualHeight;
+ (BOOL)useNewCoverImageSize;
+ (BOOL)disableZoomTranstionOpti;
+ (id)getDoubleColumnTitle:;
+ (BOOL)livePreviewEnable;
+ (BOOL)quickSwitchDisableFoldWhenScroll;
+ (BOOL)switchPreviewEntryImpactEnable;
+ (double)switchPreviewClickDuration;
+ (BOOL)switchPreviewHideReturn;
+ (id)switchPreviewHideReturnArray;
+ (BOOL)c2RecommendEntryContinuePlayCardEnable;
+ (id)c2RecommendEntrySwitchButtonDetailIconMidUrl;
+ (id)c2RecommendEntrySwitchButtonDetailIconRightUrl;
+ (id)c2RecommendEntrySwitchButtonDetailText;
+ (BOOL)c2RecommendEntrySwitchButtonDetailDisableFold;
+ (double)c2SwitchButtonFoldDistance;
+ (id)c2SwitchButtonFoldForeverScene;
+ (BOOL)c2SwitchButtonUIOptimizeEnable;
+ (BOOL)c2SwitchButtonEnableFold;
+ (BOOL)isSupportEnterAnimationModel:;
+ (BOOL)c2RecommendEnterAnimationOpt;
+ (long long)c2CardCoverRatioCutType;
+ (long long)doubleColumnSearchRequiredCount;
+ (long long)radicalEntryMaskAnimationLoopCount;
+ (id)radicalEntryMaskText;
+ (long long)radicalEntryPopoverShowDuration;
+ (id)radicalEntryPopoverText;
+ (long long)radicalEntryPopoverAnimationDelay;
+ (long long)radicalLeaveMaskAnimationLoopCount;
+ (id)radicalLeaveMaskText;
+ (long long)radicalLeavePopoverShowDuration;
+ (id)radicalLeavePopoverText;
+ (long long)radicalLeavePopoverAnimationDelay;
+ (void)setRadicalLeaveGuideAlreadyShow;
+ (void)setRadicalLeaveGuideBeBlocked;
+ (BOOL)radicalLeaveGuideNeedBlockOtherGuide;
+ (BOOL)showAlbumIcon;
+ (BOOL)showVideoIcon;
+ (void)showRadicalLeaveMask;
+ (BOOL)needShowRadicalEntryGuideWithAweme:referString:;
+ (void)setAlreadyEnterDoubleColumn;
+ (void)setRadicalEntryGuideAlreadyShow;
+ (void)showRadicalEntryMaskWithModel:;
+ (BOOL)clickRecommendGuideEnable;
+ (id)clickRecommendGuideText;
+ (BOOL)doubleClickHomepageEnable;
+ (BOOL)doubleClickHomepageGuideEnable;
+ (id)doubleClickHomepageGuideText;
+ (BOOL)longPressHomepageGuideEnable;
+ (id)longPressHomepageGuideText;
+ (BOOL)returnToSingleRefreshEnable;
+ (BOOL)showRefreshTip;
+ (void)updateNoNeedShowDictIfNeededByType:;
+ (BOOL)fixAlreadyShow;
+ (BOOL)enableSelectedIndicatorOpt;
+ (void)insertNeedReserveAwemeToSectionViewModels:withSectionModels:inStatus:isFirstRefresh:hasClickedModel:;
+ (id)quickSwitchBackgroundColor;
+ (id)backToSingleColumnLabelTextColor;
+ (BOOL)shouldEffectViewHidden;
+ (id)quickSwitchWithCoverBackgroundColor;
+ (id)quickSwitchWithCoverLabelTextColor;
+ (long long)getCurrentBigMode;
+ (double)c2PreloadFakeRefreshTime;
+ (BOOL)enableDoubleColumnOuterSettingEntrance;
+ (long long)doubleColumnPrefetchImageAfterFetchCount;
+ (long long)doubleColumnAdaptPad;
+ (BOOL)placeHolderUseDoubleColumnCacheEnable;
+ (BOOL)placeHolderUseDoubleColumnDidAppearCacheEnable;
+ (BOOL)placeHolderUseDoubleColumnUnusedCacheEnable;
+ (BOOL)enableSmartLoadMore;
+ (BOOL)enableScrollVelocityDetect;
+ (double)timesAfterEnterDoubleColumn;
+ (id)hpEntryLeaveGuideID;
+ (id)hpEntryLeaveGuideText;
+ (id)hpEntryEnterGuideID;
+ (id)hpEntryEnterGuideText;
+ (void)recordTimesWhenEnterFromPreView;
+ (BOOL)isReversingRecommendEntry;
+ (id)sharedInstance;
@end
