@interface AWEFeedSubtitleContainerView : UIView
@property (nonatomic) UILabel subtitleLabel;
@property (nonatomic) Q type;
@property (nonatomic) NSTimer timer;
@property (nonatomic) double currentPTS;
@property (nonatomic) NSArray subtitleList;
@property (nonatomic) double duration;
@property (nonatomic) double showedTimestamp;
@property (nonatomic) double remainingDuration;
@property (nonatomic) NSString text;
@property (nonatomic) double speed;
@property (nonatomic) double maxWidth;
- (void)updateBackgroundColorType:;
- (id)attributedTextWithContent:;
- (BOOL)downgradeToTruncation;
- (void)setSubtitleList:;
- (void)setRemainingDuration:;
- (id)subtitleListWithContent:;
- (id)subtitleList;
- (void)setShowedTimestamp:;
- (double)showedTimestamp;
- (id)sentenceWithContent:;
- (void)updateContentWithSubInfo:;
- (void)setSpeed:;
- (void)setTimer:;
- (double)speed;
- (void)dealloc;
- (double)remainingDuration;
- (void)play;
- (id)timer;
- (long long)numberOfLines;
- (void)setText:;
- (void)setDuration:;
- (id)text;
- (void)setSubtitleLabel:;
- (double)maxWidth;
- (unsigned long long)type;
- (void)setType:;
- (void)setMaxWidth:;
- (void).cxx_destruct;
- (double)duration;
- (void)reset;
- (void)resetTimer;
- (id)subtitleLabel;
- (void)pause;
- (void)setupUI;
- (id)subtitleLabelFont;
- (id)initWithFrame:type:;
- (double)currentPTS;
- (void)setCurrentPTS:;
@end
