@interface AWEFeedGeneralViewCell : DUXBaseTableViewCell
@property (nonatomic) AWEFeedDetailTableViewLastCellMaskView lastCellMaskView;
@property (nonatomic) # pInteractionControllerFactory;
@property (nonatomic) AWEFeedGeneralCellViewController viewController;
@property (nonatomic) q indexPath;
@property (nonatomic) UIViewController parentVC;
@property (nonatomic) AWEAwemeModel registerElementModel;
@property (nonatomic) BOOL hadPrepareToDisplay;
@property (nonatomic) q feedCellType;
@property (nonatomic) BOOL hasConfig;
@property (nonatomic) # viewControllerClassType;
@property (nonatomic) double defaultSeekToTime;
@property (nonatomic) NSString reactId;
@property (nonatomic) NSString previousPage;
@property (nonatomic) BOOL shouldHideMusicInfo;
@property (nonatomic) BOOL shouldShowGoodsElement;
@property (nonatomic) BOOL shouldShowGoodsCardAnchorElement;
@property (nonatomic) BOOL innerInteractionDelay;
@property (nonatomic) NSString detailEnterFrom;
@property (nonatomic) NSString detailReferString;
@property (nonatomic) BOOL forbidResetVideo;
@property (nonatomic) NSDictionary context;
@property (nonatomic) BOOL isActive;
@property (nonatomic) AWEUserModel homepageUser;
@property (nonatomic) BOOL hasEntryFullPage;
@property (nonatomic) BOOL banGlobalRelay;
@property (nonatomic) ^{EngineAudioWrapper=^?^?^?^?^v} audioWrapper;
@property (nonatomic) ^{EngineVideoWrapper=^?^?^v} videoWrapper;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString referString;
@property (nonatomic) q cellDisplayState;
@property (nonatomic) q cellPageAppearState;
@property (nonatomic) @? currentCellPageAppearStateBlock;
@property (nonatomic) UIView feedTableViewCellMaskView;
@property (nonatomic) <UIScrollViewDelegate> scrollViewDelegate;
@property (nonatomic) UIViewController<AWEFeelGoodCellViewControllerProtocol> feelGoodViewController;
- (id)reactId;
- (void)setReactId:;
- (id)referString;
- (void)pauseWithAnimation;
- (void)playWithAnimation;
- (void)duxGrid_viewDidChangeBreakPointFrom:toBreakPoint:;
- (void)setReferString:;
- (void)prepareForDisplayWithoutCoverImage;
- (void)pauseIfNotStop;
- (double)defaultSeekToTime;
- (BOOL)isScrolledAutomatically;
- (void)setIsScrolledAutomatically:;
- (id)audioWrapper;
- (void)setAudioWrapper:;
- (id)videoWrapper;
- (void)setVideoWrapper:;
- (void)setDefaultSeekToTime:;
- (BOOL)isVideoRelatedPanelShowing;
- (void)didDisplay;
- (BOOL)isRelatedVideoPanelShowing;
- (BOOL)isCommentPanelShowing;
- (BOOL)isLikeUserPanelShowing;
- (BOOL)isAITextPanelShowing;
- (id)aAWEPadModuleAdapter;
- (id)registerElementModel;
- (void)setRegisterElementModel:;
- (BOOL)fullDetaillHalfScreenViewShowed;
- (void)updateAntiAddictedOptStrongRemindView:;
- (void)didEndDisplayingBeforeReset;
- (BOOL)isViewerListShowing;
- (void)configWithModel:;
- (long long)cellDisplayState;
- (void)setCellDisplayState:;
- (long long)cellPageAppearState;
- (void)setCellPageAppearState:;
- (id)currentCellPageAppearStateBlock;
- (void)setCurrentCellPageAppearStateBlock:;
- (id)feedTableViewCellMaskView;
- (void)setFeedTableViewCellMaskView:;
- (BOOL)hadPrepareToDisplay;
- (void)setHadPrepareToDisplay:;
- (void)afterDidEndDisplaying;
- (void)resetRefreshFlag;
- (void)seekTime:completion:;
- (void)addFeedTableViewCellMaskView:;
- (void)removeFeedTableViewCellMaskView;
- (void)mutePlayerController:;
- (void)replaceViewController:removeIfExisting:;
- (BOOL)isCommonFeedCell;
- (long long)currentVideoScaleMode;
- (void)removeCellChildVCForMemoryOpt;
- (void)setInteractionControllerFactory:;
- (Class)interactionControllerFactory;
- (void)showLastCellMaskView:;
- (void)configLastCellMaskViewWithTitle:backHintText:backAction:;
- (void)p_removeChildVC;
- (void)configCommentInputView;
- (void)replaceCurrentViewController:;
- (Class)viewControllerClassType;
- (void)setViewControllerClassType:;
- (BOOL)shouldHideMusicInfo;
- (void)setShouldHideMusicInfo:;
- (BOOL)shouldShowGoodsElement;
- (void)setShouldShowGoodsElement:;
- (BOOL)shouldShowGoodsCardAnchorElement;
- (void)setShouldShowGoodsCardAnchorElement:;
- (BOOL)innerInteractionDelay;
- (void)setInnerInteractionDelay:;
- (id)detailEnterFrom;
- (void)setDetailEnterFrom:;
- (id)detailReferString;
- (void)setDetailReferString:;
- (BOOL)forbidResetVideo;
- (void)setForbidResetVideo:;
- (id)homepageUser;
- (void)setHomepageUser:;
- (BOOL)hasEntryFullPage;
- (void)setHasEntryFullPage:;
- (void)setHasConfig:;
- (BOOL)banGlobalRelay;
- (void)setBanGlobalRelay:;
- (void)addInteract;
- (void)setFeelGoodViewController:;
- (id)feelGoodViewController;
- (id)aAWEPadDetailTableAdapter;
- (long long)feedCellType;
- (void)p_addChildVC;
- (Class)pInteractionControllerFactory;
- (void)setPInteractionControllerFactory:;
- (BOOL)enableVideoVCResetLayout;
- (void)adjustVideoFrameIfNeeded;
- (void)p_adjustVideoFrameIfNeeded:;
- (id)lastCellMaskView;
- (void)adjustVideoFrameIfNeededWithPanelType:;
- (BOOL)enableFullScreenPlay:;
- (BOOL)enableFullScreenEntranceFix;
- (void)setLastCellMaskView:;
- (void)setFeedCellType:;
- (void)p_configVoiceOverElements;
- (void)p_setupChildVC;
- (id)scrollViewDelegate;
- (void)setIsActive:;
- (void)dealloc;
- (void)play;
- (long long)indexPath;
- (void)prepareForReuse;
- (void)prepareForDisplay;
- (id)viewController;
- (void)setIndexPath:;
- (id)initWithStyle:reuseIdentifier:;
- (void)setContext:;
- (void).cxx_destruct;
- (double)currentPlaybackTime;
- (void)reset;
- (BOOL)isActive;
- (void)layoutSubviews;
- (id)context;
- (void)stop;
- (void)pause;
- (void)setViewController:;
- (BOOL)accessibilityScroll:;
- (id)previousPage;
- (void)setPreviousPage:;
- (void)configureWithModel:;
- (void)didEndDisplaying;
- (void)pauseIfPlaying;
- (BOOL)hasConfig;
- (void)willDisplay;
- (void)pageDidDisappear:;
- (id)parentVC;
- (void)setParentVC:;
- (void)pageWillAppear:;
- (void)pageDidAppear:;
- (void)pageWillDisappear:;
+ (Class)aAWEPadModuleAdapterClass;
+ (id)reuseIdentifierWithMediaType:;
+ (id)reuseIdentifierWithMediaType:isFakeAweme:;
+ (Class)aAWEPadDetailTableAdapterClass;
@end
