@interface AWEFeedLiveStickerDisplayHandler : AWEFeedBasicStickerDisplayHandler
@property (nonatomic) UIView<ACCStickerContentProtocol><ACCLiveStickerViewProtocol> contentView;
@property (nonatomic) BOOL didDisplay;
@property (nonatomic) BOOL didAppear;
@property (nonatomic) BOOL showSticker;
- (BOOL)didDisplay;
- (id)trackParams;
- (void)removeSticker:;
- (void)setDidDisplay:;
- (void)setDidAppear:;
- (void)showShareTicketWith:;
- (id)p_liveModuleService;
- (BOOL)displayByNative;
- (BOOL)canHandleTapAtPoint:;
- (void)displaySticker:;
- (void)p_trackLiveShowWithSticker:;
- (void)setShowSticker:;
- (BOOL)hiddenSubscriberView;
- (void)configWithModel:Config:;
- (void)fetchSubscriberListWithCompletion:;
- (BOOL)showSticker;
- (void)trackLiveStickerEvent:;
- (BOOL)isContainCurrentUser:;
- (void)adTrackLiveStickerEventWithActionType:;
- (BOOL)isNeedRequestForTicket:;
- (void)requestForTicketWith:;
- (id)successToastContent;
- (id)addSelfSubscriber:;
- (id)removeSelfSubscriber:;
- (void)jumpToLiveRoom;
- (void)trackLiveStickerEvent:withTicket:;
- (id)contentView;
- (void)viewWillAppear;
- (BOOL)didAppear;
- (void).cxx_destruct;
- (void)setContentView:;
- (void)handleTapAtPoint:;
- (BOOL)isMySelf;
- (void)willDisplay;
+ (BOOL)canDisplaySticker:;
@end
