@interface AWEFollowRecentUserUpdateEmptyCell : UITableViewCell
@property (nonatomic) UIImageView bgAvatarImgView;
@property (nonatomic) UIVisualEffectView blurEffectView;
@property (nonatomic) UIView primaryView;
@property (nonatomic) UIImageView avatarImgView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel subtitleLabel;
@property (nonatomic) UIButton actionButton;
@property (nonatomic) UIImageView arrowImgView;
@property (nonatomic) UILabel bottomPromptLabel;
@property (nonatomic) AWEUserModel userModel;
@property (nonatomic) NSString referString;
@property (nonatomic) BOOL isLastOne;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)setReferString:;
- (id)avatarImgView;
- (void)setAvatarImgView:;
- (void)emptyCell_configCell:atIndexPath:tableView:referString:;
- (void)emptyCell_cellWillDisplay:atIndexPath:tableView:enterFrom:;
- (void)emptyCell_cellDidEndDisplay:;
- (BOOL)isLastOne;
- (void)setIsLastOne:;
- (void)enterProfileAction;
- (id)labelWithFont:textColor:;
- (void)layoutBottomPromptLabel;
- (id)bgAvatarImgView;
- (void)eventTrack4EnterProfileWithMethod:;
- (id)bottomPromptLabel;
- (id)arrowImgView;
- (void)handleAvatarTapGestureRecognizer:;
- (void)handleActionButtonEvent:;
- (void)setBgAvatarImgView:;
- (void)setArrowImgView:;
- (void)setBottomPromptLabel:;
- (void)setPrimaryView:;
- (void)setSubtitleLabel:;
- (id)primaryView;
- (id)initWithStyle:reuseIdentifier:;
- (void)setTitleLabel:;
- (void)setUserModel:;
- (void).cxx_destruct;
- (id)userModel;
- (id)titleLabel;
- (void)layoutSubviews;
- (id)subtitleLabel;
- (id)actionButton;
- (void)setActionButton:;
- (void)setupSubviews;
- (id)blurEffectView;
- (void)setBlurEffectView:;
- (void)addBlurEffect;
@end
