@interface AWEFeedCGDirectPlayMaskView : UIView
@property (nonatomic) <AWEFeedCGDirectPlayMaskViewDelegate> delegate;
@property (nonatomic) UIImageView bgImageView;
@property (nonatomic) AWESpecialCardGradientOverlayView topOverlayView;
@property (nonatomic) AWESpecialCardGradientOverlayView topDeepOverlayView;
@property (nonatomic) AWESpecialCardGradientOverlayView bottomOverlayView;
@property (nonatomic) UIView tabbarOverlayView;
@property (nonatomic) UIButton leftButton;
@property (nonatomic) UIView rightButtonContainer;
@property (nonatomic) UIImageView rightButtonImageView;
@property (nonatomic) UILabel rightButtonLabel;
@property (nonatomic) AWESpecialCardScrollTipView tipView;
@property (nonatomic) AWESpecialCardInfoView infoView;
@property (nonatomic) AWEFeedCGDirectPlayMaskViewConfig config;
- (void)onLeftButtonClick;
- (void)updateOrientation:;
- (void)setRightButtonContainer:;
- (id)rightButtonContainer;
- (void)addTapGesture;
- (id)topOverlayView;
- (id)topDeepOverlayView;
- (id)bottomOverlayView;
- (id)tabbarOverlayView;
- (id)rightButtonImageView;
- (id)rightButtonLabel;
- (BOOL)p_isBlackColorWithRed:green:blue:;
- (void)onActionButtonClick;
- (void)updateTopMaskWithColor:;
- (void)updateBottomMaskWithColor:;
- (void)updateWithSubscribedStatus:;
- (void)updateBackgroundImage:;
- (void)showPlaceholderBgImage;
- (void)setTopOverlayView:;
- (void)setTopDeepOverlayView:;
- (void)setBottomOverlayView:;
- (void)setTabbarOverlayView:;
- (void)setRightButtonImageView:;
- (void)setRightButtonLabel:;
- (void)setConfig:;
- (void)setLeftButton:;
- (void)setTipView:;
- (id)delegate;
- (id)leftButton;
- (id)initWithDelegate:;
- (id)config;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)setupUI;
- (void)handleTapGesture;
- (id)infoView;
- (void)setInfoView:;
- (void)updateContent:;
- (void)setBgImageView:;
- (id)bgImageView;
- (id)tipView;
@end
