@interface AWEFollowUserUpdateViewModel : AWERelationUserListBaseSectionViewModel
@property (nonatomic) AWEFollowRecentUserUpdateDataController dataController;
@property (nonatomic) AWEFollowRecentUserUnreadListDataController recentUserDataController;
@property (nonatomic) NSString previousPage;
@property (nonatomic) NSNumber totalUnreadItems;
@property (nonatomic) BOOL forceAllUnread;
@property (nonatomic) NSString insertIds;
@property (nonatomic) NSNumber firstFetched;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)didFinishFollowUser:status:error:;
- (void)didFinishUnFollowUser:status:error:;
- (void)didFinishTopFollowingUser:status:;
- (void)didFinishUnTopFollowingUser:status:;
- (void)didFinishBlockUser:status:;
- (void)didFinishTapTAIsFriendWithUser:isFriend:;
- (void)didFinishSetRemarkWithUser:;
- (void)didFinishRemoveFansWithUser:;
- (id)enterFrom;
- (void)setDataController:;
- (id)insertIds;
- (void)setInsertIds:;
- (void)loadMoreSectionData;
- (void)registerMessage;
- (void)unfollowUser:;
- (void)syncModelFollowStatus:status:;
- (void)onClickUnFollowUserOnProfileMenu:trackerParam:;
- (BOOL)isFriends;
- (void)followListUnreadCacheDidChangeWithUserID:deleteItemIDs:;
- (void)followListUnreadCacheDidReplaceWithUserID:;
- (BOOL)forceAllUnread;
- (void)setForceAllUnread:;
- (id)currentUnreadUserIDList;
- (BOOL)noMoreUserData;
- (void)loadMoreUnreadUserWithCompletion:;
- (id)userModelWithUserID:;
- (Class)emptyCellClass;
- (id)convertUserModel:;
- (void)cacheUnreadItemsIfNeededWithFollowingUser:;
- (void)configTrackDict:;
- (unsigned long long)getEnterFrom;
- (void)setFirstFetched:;
- (id)totalUnreadItems;
- (void)forceUseAllUnread;
- (void)fetchSectionData:completion:;
- (void)loadMoreSectionDataWithCompletion:;
- (BOOL)shouldUseTotal;
- (id)recentUserDataController;
- (void)setTotalUnreadItems:;
- (void)updateUnreadCount:unreadCount:;
- (id)firstFetched;
- (void)setRecentUserDataController:;
- (void)dealloc;
- (long long)type;
- (void).cxx_destruct;
- (id)previousPage;
- (void)setPreviousPage:;
- (BOOL)isMine;
- (id)dataController;
@end
