@interface AWEGoldenHouseManager : NSObject
@property (nonatomic) BOOL hasReadStorage;
@property (nonatomic) NSMutableArray feedPreCacheList;
@property (nonatomic) NSMutableArray feedCachedList;
@property (nonatomic) NSMutableDictionary downloadedDict;
@property (nonatomic) q cachedCount;
@property (nonatomic) q shouldCachedCount;
@property (nonatomic) NSTimer feedCacheCheckTimer;
@property (nonatomic) NSTimer feedGHCacheTimer;
@property (nonatomic) AWEGoldenHouseDataController dataController;
@property (nonatomic) NSRecursiveLock lock;
@property (nonatomic) BOOL enablePeriodDownload;
@property (nonatomic) double lastDownloadTime;
@property (nonatomic) BOOL downloadPermit;
@property (nonatomic) NSArray periodLimitArray;
@property (nonatomic) NSString lastVideoItemID;
@property (nonatomic) AWEListDataController foryouFeedDataController;
@property (nonatomic) NSMutableSet playedVideos;
@property (nonatomic) NSMutableSet releasedVideos;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)filterDuplicatedDatasourceWithArray:isEqual:;
- (void)setDataController:;
- (void)videoSafetyCheckIfNeeded;
- (unsigned long long)loadMoreType;
- (void)teenModeDidChange:isLogout:;
- (id)transToMinString:;
- (id)transPeakTimeType:;
- (BOOL)checkLeftSpaceEnough;
- (void)setFeedPreCacheList:;
- (id)feedPreCacheList;
- (id)getValidCacheFromLocalCache:;
- (id)setProFeedPreCache:;
- (void)storageToFlieWithFeedPreCacheList:key:completion:;
- (id)foryouFeedDataController;
- (void)invalidateFeedCacheTimer;
- (void)setForyouFeedDataController:;
- (id)periodLimitArray;
- (void)setPeriodLimitArray:;
- (id)getFeedCachedWithCount:;
- (id)getFeedCachedModels;
- (id)returnNoDuplicatedReleaseFeed:;
- (void)clearCacheInGoldenHouseWithCount:;
- (void)clearCacheInGoldenHouseAtOnce:;
- (void)timerFetchFeedCache;
- (void)clearReleasedVideoCache;
- (void)setDownloadedDict:;
- (id)downloadedDict;
- (void)getFeedCachedDictFromFileWithCompletion:;
- (void)setHasReadStorage:;
- (void)getFeedCacheArrayFromFileWithCompletion:;
- (void)setDownloadPermit:;
- (BOOL)downloadPermit;
- (BOOL)checkDownloadCondition;
- (void)fetchFeedOrContinueDownloading;
- (void)asyncToStorageWithKey:list:;
- (long long)shouldCachedCount;
- (void)updateOfflineModeUserID;
- (void)preloadCacheFeedModels:;
- (void)asyncToStorageWithKey:Dic:;
- (id)feedCachedList;
- (id)feedGHCacheTimer;
- (void)setFeedGHCacheTimer:;
- (id)releasedVideos;
- (void)setReleasedVideos:;
- (void)clearVideoCache;
- (BOOL)checkIfSwitchIdChanged;
- (id)playedVideos;
- (void)handleVideoSafetyPreCheckWithResults:;
- (void)setFeedCachedList:;
- (void)videoPrivacySafetyCheck:;
- (void)storageToFlieWithFeedPreCacheDic:key:completion:;
- (id)getFeedNoCachedModels;
- (void)fetchPreCacheFeedWithCount:;
- (double)lastDownloadTime;
- (BOOL)checkDownloadPeriodVaild;
- (void)setLastDownloadTime:;
- (BOOL)checkDownloadPeriodVaildOpt;
- (void)clearDuplicatedFeedPreCacheModels;
- (void)clearDuplicatedFeedPreCacheModelsWithArray:;
- (void)setPlayedVideos:;
- (BOOL)hasReadStorage;
- (void)setShouldCachedCount:;
- (id)feedCacheCheckTimer;
- (void)setFeedCacheCheckTimer:;
- (BOOL)enablePeriodDownload;
- (void)setEnablePeriodDownload:;
- (id)lastVideoItemID;
- (void)setLastVideoItemID:;
- (long long)cachedCount;
- (id)init;
- (void)dealloc;
- (void)setLock:;
- (id)lock;
- (void).cxx_destruct;
- (void)setCachedCount:;
- (void)appDidEnterBackground;
- (id)dataController;
+ (id)sharedInstance;
@end
