@interface AWEGeneralSearchAdCombinateLiveCellController : AWEGeneralSearchCombinateLiveCellController
@property (nonatomic) AWESearchEcommerceAdGoodsView adGoodsView;
@property (nonatomic) double startPlayerTime;
@property (nonatomic) UIImageView spotImageView;
@property (nonatomic) UIView<AWEAdLearnMoreLynxButton> adLearnMoreLynxButton;
@property (nonatomic) AWEAdTagView adTagView;
@property (nonatomic) BOOL lynxButtonLoadFail;
@property (nonatomic) AWESearchLiveOnlyStatusView statusView;
@property (nonatomic) AWESearchLiveAssistLabel assistView;
@property (nonatomic) @? playbackTimeBlock;
@property (nonatomic) NSTimer playbackTimeTimer;
@property (nonatomic) double playbackTime;
- (id)adExtraData;
- (void)setPlaybackTimeBlock:;
- (BOOL)shouldShowAdLearnMoreLynxButton:;
- (id)adTagView;
- (id)assistView;
- (void)setAdTagView:;
- (void)trackPlay;
- (void)didStartShowing;
- (void)didBecomeActiveForReason:;
- (void)didEndShowing;
- (id)searchTrackParams;
- (void)setUpLearnMoreLynxButtonWithModel:;
- (id)appendLynxRawAdDataWithSearchCommonParams:;
- (double)startPlayerTime;
- (void)setStartPlayerTime:;
- (id)adLearnMoreLynxButton;
- (void)setLynxButtonLoadFail:;
- (BOOL)lynxButtonLoadFail;
- (id)spotImageView;
- (void)registerCallback:forReachingPlaybackTime:;
- (id)playbackTimeBlock;
- (void)setSpotImageView:;
- (void)updateLiveLabel;
- (id)adGoodsView;
- (void)stopPlaybackTimeTimer;
- (void)resetAdComponentWithModelIfNeeded:;
- (void)showAdLiveLynxButtonWithModel:;
- (void)trackSearchResultShowForLive;
- (id)getGeneralSearchTrackBaseParams;
- (void)startPlaybackTimeTimer;
- (void)clickGoodAtIndex:;
- (void)trackClickWithRefer:;
- (void)clickLiveView;
- (void)onTimerAction;
- (id)playbackTimeTimer;
- (void)setPlaybackTimeTimer:;
- (void)clickGoods;
- (void)clickGoodsMore;
- (void)setAdGoodsView:;
- (void)setAdLearnMoreLynxButton:;
- (void)setAssistView:;
- (void)viewDidLoad;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)setupUI;
- (double)playbackTime;
- (void)setPlaybackTime:;
- (void)updateWithModel:;
- (void)setStatusView:;
- (id)statusView;
+ (double)modernFeedCellPreferedHeightForModel:width:;
+ (void)__awe__codeRunnerRun___LINE__;
@end
