@interface AWEGCPEvaluationPublishStarView : UIView
@property (nonatomic) UIVisualEffectView blurEffectView;
@property (nonatomic) UIView firstBackgroundView;
@property (nonatomic) IESGCPEvaluationStarsView fiveStarView;
@property (nonatomic) UIView closeView;
@property (nonatomic) UIImageView closeImageView;
@property (nonatomic) UIImageView gameIconImageView;
@property (nonatomic) UILabel gameLabel;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) NSDictionary extraParams;
@property (nonatomic) <AWEGCPEvaluationPublishStarViewDelegate> delegate;
- (void)setExtraParams:;
- (id)extraParams;
- (id)closeView;
- (void)setCloseView:;
- (void)viewDidDisposed;
- (void)viewDidDisplay;
- (void)updateWithAwemeModel:extraParams:;
- (void)closeStarCardView;
- (void)setFirstBackgroundView:;
- (id)firstBackgroundView;
- (id)gameLabel;
- (id)fiveStarView;
- (void)setFiveStarView:;
- (void)setGameLabel:;
- (id)init;
- (id)delegate;
- (void)setup;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (id)blurEffectView;
- (void)setBlurEffectView:;
- (id)gameIconImageView;
- (void)setGameIconImageView:;
- (id)closeImageView;
- (void)setCloseImageView:;
@end
