@interface AWEGCPGameFeedVideoElement : LynxUI
@property (nonatomic) <AWEGCPFeedVideoSyncRouter> feedVideoSyncRouter;
@property (nonatomic) BOOL isFeedVideoPaused;
@property (nonatomic) BOOL isAssociatedMode;
@property (nonatomic) BOOL hasSetupAutoPlay;
@property (nonatomic) BOOL loop;
@property (nonatomic) BOOL muted;
@property (nonatomic) NSString fillMode;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)onPlay;
- (void)play:withResult:;
- (void)pause:withResult:;
- (void)stop:withResult:;
- (void)updateVideoData:;
- (void)seek:withResult:;
- (void)muted:requestReset:;
- (void)onReady;
- (void)onBufferChangeWithInfo:;
- (void)onError:msg:;
- (void)onEnded;
- (void)onTimeUpdate:canPlayTime:totalTime:;
- (void)setupDefaultProps;
- (void)setIsAssociatedMode:;
- (BOOL)isAssociatedMode;
- (void)setFeedVideoSyncRouter:;
- (void)setIsFeedVideoPaused:;
- (id)feedVideoSyncRouter;
- (void)updateMutedIfNeeded;
- (void)updateRepeatIfNeeded;
- (void)updateFitModeIfNeeded;
- (void)sendCustomEvent:params:;
- (BOOL)isFeedVideoPaused;
- (void)onSeek:;
- (void)playFeedVideoIfNeeded:withResult:;
- (void)videoData:requestReset:;
- (void)loop:requestReset:;
- (void)objectFit:requestReset:;
- (void)logextra:requestReset:;
- (BOOL)hasSetupAutoPlay;
- (void)setHasSetupAutoPlay:;
- (BOOL)muted;
- (void)setMuted:;
- (id)fillMode;
- (void).cxx_destruct;
- (void)setFillMode:;
- (BOOL)loop;
- (id)createView;
- (void)updateWithModel:;
- (void)setLoop:;
- (void)onPause;
- (void)onStop;
- (void)frameDidChange;
+ (void)lynxLazyLoad;
+ (id)__lynx_ui_method_config__2081;
+ (id)__lynx_ui_method_config__2162;
+ (id)__lynx_ui_method_config__2273;
+ (id)__lynx_ui_method_config__2384;
+ (id)__lynx_ui_method_config__2495;
+ (id)__lynx_prop_config__2786;
+ (id)__lynx_prop_config__2837;
+ (id)__lynx_prop_config__2898;
+ (id)__lynx_prop_config__2959;
+ (id)__lynx_prop_config__30210;
@end
