@interface AWEGDContainerViewController : AWEDitoViewController
@property (nonatomic) <AWENearbyGrouponSubPageContianerHelper> nearbySubpageDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView<AWEGDContainerDetailPayFootDownGradeProtocol> payFooterView;
@property (nonatomic) q pageAppearCount;
@property (nonatomic) UIView popupDecorationView;
@property (nonatomic) NSString originRouterUrl;
@property (nonatomic) NSString errorMsg;
@property (nonatomic) NSString fromPOIId;
@property (nonatomic) <DitoLynxExtensionProtocol> ditoLynxExtension;
@property (nonatomic) NSMutableDictionary actionMaps;
@property (nonatomic) <AWEPOIHalfScreenContainerProtocol> container;
@property (nonatomic) AWEPOIAgreementProvider agreementProvider;
@property (nonatomic) q closeType;
@property (nonatomic) BOOL fixedToHalf;
@property (nonatomic) NSMutableDictionary updatedRouterParams;
@property (nonatomic) double pageCreateTimeInterval;
@property (nonatomic) NSMutableDictionary baseRequestParams;
@property (nonatomic) NSMutableDictionary updatedRequestParams;
@property (nonatomic) NSMutableDictionary appendIntoRequestParams;
@property (nonatomic) NSMutableDictionary baseRouterParams;
@property (nonatomic) NSDictionary ditoDataDict;
@property (nonatomic) BOOL isFullScreenStatus;
@property (nonatomic) BOOL isNewGoodsDetailChanging;
@property (nonatomic) BOOL isRefreshNativeNode;
@property (nonatomic) BOOL forbiddenRefreshShowEvent;
@property (nonatomic) double swipeAbsoluteTime;
@property (nonatomic) double originModalHeight;
@property (nonatomic) UIView bodyView;
@property (nonatomic) BOOL popupIsClosing;
@property (nonatomic) AWEPOIGoodsDetailPreviewInstanceManager previewManager;
@property (nonatomic) AWEPOIGoodsDetailRenderPriorityManager priorityManager;
@property (nonatomic) AWEGDTimeTracker stayTimeTracker;
@property (nonatomic) BOOL hideVideoBar;
@property (nonatomic) BOOL forceFullScreen;
@property (nonatomic) BOOL fromLive;
@property (nonatomic) AWEPOIGoodsDetailNestedScrollManager nestedScrollManager;
@property (nonatomic) NSString bizCode;
@property (nonatomic) NSString server_task_duration;
@property (nonatomic) AWEGDBizAbilityProvider currentAbilityProvider;
@property (nonatomic) <AWEGDContainerMainRequestProtocol> mainReqProvider;
@property (nonatomic) <AWEGDContainerDitoProtocol> ditoProvider;
@property (nonatomic) <AWEGDContainerPreReqProtocol> preReqProvider;
@property (nonatomic) <AWEGDContainerPreLoadProtocol> preloadProvider;
@property (nonatomic) <AWEGDContainerTrackerProtocol> trackerProvider;
@property (nonatomic) <AWEGDContainerRecoveryProtocol> recoveryProvider;
@property (nonatomic) <AWEGDContainerDownGradeH5Protocol> downGradeProvider;
@property (nonatomic) AWEGDNoActionEventHandler noActionEventHandler;
@property (nonatomic) AWEPOIGoodsDetailCollectGuideBubbleManager collectGuideBtnManager;
@property (nonatomic) AWEGDSkeletonExtension skeletonExtension;
@property (nonatomic) AWEGDErrorViewExtension errorViewExtension;
@property (nonatomic) AWEGDLoadingExtension loadingExtension;
@property (nonatomic) AWEGoodsParamsValidatorExtension goodsParamsValidatorExtension;
@property (nonatomic) BOOL isPadSplitting;
@property (nonatomic) UIPanGestureRecognizer fullScreenSwipeGesture;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString lifeBdxTag;
@property (nonatomic) q splitViewScene;
@property (nonatomic) AWEPadSplitPageContext splitViewContext;
@property (nonatomic) <AWEPadSplitViewService> splitService;
@property (nonatomic) <AWEPadSplitViewBizAdapter> splitViewAdapter;
- (void)duxGrid_viewDidChangeBreakPointFrom:toBreakPoint:;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (BOOL)btm_autoManaged;
- (id)btm_pageIdentifier;
- (void)setIsPadSplitting:;
- (id)bizCode;
- (BOOL)isPadSplitting;
- (void)setErrorMsg:;
- (id)errorMsg;
- (id)placeholderConfig;
- (void)setBizCode:;
- (long long)closeType;
- (void)setCloseType:;
- (id)priorityManager;
- (void)setPriorityManager:;
- (void)setIsProcessing:;
- (id)aAWEPadSplitScreenAdapter;
- (id)splitService;
- (long long)splitViewScene;
- (id)splitViewContext;
- (void)setSplitViewContext:;
- (void)setSplitService:;
- (id)splitViewAdapter;
- (void)setSplitViewAdapter:;
- (void)windowDidResignKeyNotification:;
- (void)windowDidBecomeKeyNotification:;
- (BOOL)isFullScreenStatus;
- (BOOL)popupIsClosing;
- (void)containerDidCloseWithCloseType:;
- (void)setIsFullScreenStatus:;
- (void)setPopupIsClosing:;
- (void)containerDidShowCompletion:;
- (void)containerDidSwitchTo:;
- (void)containerFrameDidChangeWithFrame:containerFullHeight:;
- (void)containerWillCloseWithCloseType:;
- (void)containerArrivingTopArea;
- (void)containerLeavingTopArea;
- (BOOL)containerShouldShowMask;
- (void)embedInContainer:;
- (void)pageDidScroll:;
- (id)buildRequestParams;
- (void)setUpNotification;
- (void)preloadGoodsDetail;
- (id)DitoPageScene;
- (void)didLoadPageModel:;
- (void)didEndReload;
- (id)nearbySubpageDelegate;
- (void)setNearbySubpageDelegate:;
- (id)actionMaps;
- (void)registerAgents;
- (void)configDisasterFallback:degradeInfo:completion:;
- (id)performanceTrackParams;
- (void)ditoMonitorExtensionDidFMPCalculateFinished:;
- (void)handleLynxBroadcastEvent:;
- (void)recoveryPayFooter:onPay:;
- (void)ditoExtension:didReceiveSizeChangeWithViewTag:;
- (void)setDitoDataDict:;
- (id)ditoDataDict;
- (void)checkValidityForPageModel:;
- (void)parsePageTrackParams:;
- (id)buildRouterParams;
- (BOOL)isNewGoodsDetailChanging;
- (void)setIsNewGoodsDetailChanging:;
- (void)optimizeLynxRender:;
- (void)removeUselessContextRouterParams;
- (BOOL)forbiddenRefreshShowEvent;
- (void)sendLogProjectDetailShow;
- (BOOL)isRefreshNativeNode;
- (void)setIsRefreshNativeNode:;
- (id)preReqProvider;
- (id)trackerProvider;
- (id)errorViewExtension;
- (id)nestedScrollManager;
- (BOOL)hitNewHalfContainer;
- (BOOL)disasterRequestMainDataWithPath:;
- (id)baseRouterParams;
- (void)refreshPreRequestViewByTag:;
- (void)ditoExtensionDidPreloadLynx:;
- (id)preloadProvider;
- (void)notifyGoodsDetailFMPEnd;
- (void)failureLoadData:;
- (void)ditoExtension:didStartToLoadCubeModel:tag:;
- (id)fullScreenSwipeGesture;
- (void)handlePanSwipeGesture:;
- (void)setFullScreenSwipeGesture:;
- (id)closeInterceptManager;
- (void)interruptAllGestures;
- (void)interruptGestures:;
- (void)interruptGesture:;
- (void)addFullScreenSwipeGesture;
- (BOOL)forceFullScreen;
- (void)bindActionCenter;
- (void)setHalfExtension:;
- (id)halfExtension;
- (void)setQueryForContainerShouldShowMask:;
- (id)placeholderConfigRaw;
- (void)showHalfContainerIfNeeds;
- (BOOL)fromLive;
- (void)p_handleLivePowerSaveClear:;
- (long long)getCloseTypeWithConatinerCloseType:;
- (void)trackCloseWithCloseType:;
- (BOOL)hideVideoBar;
- (void)setHideVideoBar:;
- (BOOL)queryForContainerShouldShowMask;
- (double)originModalHeight;
- (void)updateTopDistance:forceDispatch:;
- (void)updateRecoveryFooterFrameIfNeeded;
- (double)swipeAbsoluteTime;
- (void)setSwipeAbsoluteTime:;
- (BOOL)isFirstMoving;
- (void)setIsFirstMoving:;
- (void)dispathDitoAlphaMessageWithAlpha:animated:;
- (void)updateContainerViewUIWithAlpha:;
- (double)bodyContainerCornerRadius;
- (void)initHalfContainerExtension:;
- (void)addNewHalfContainerWithTransitionInfo:;
- (void)loadPlaceholderSketch;
- (void)pageViewDidReloadSynchronously:;
- (void)gdHalfScreenContainerLifeCycleStateDidChange:currentContainerMode:;
- (void)gdHalfScreenContainerModeDidChange:currentLifeCycle:;
- (BOOL)gdHalfScreenContainerWillClose:currentContainerMode:currentLifeCycle:;
- (void)setupFrom:to:percent:;
- (void)containerMoving;
- (void)dismissAndPopViewControllerWithCloseType:animation:;
- (void)setLiveFloatManager:;
- (id)liveFloatManager;
- (void)showLiveFloat;
- (void)hideLiveFloat;
- (void)dismissLiveFloat;
- (void)initLiveFloatIfsNeeds;
- (double)projectDetailShowTimeInterval;
- (id)baseRequestParams;
- (BOOL)hasMarkProjectDetailShow;
- (void)requestMainDataOnlyWithCache:;
- (id)mainReqProvider;
- (id)buildRequestHeaders;
- (void)didRequestMainInfoWithDitoData:requestParam:response:error:;
- (void)updateContainerConfigrationByBizCode:;
- (void)mergeNetworkTrackParams:;
- (void)checkPayFooterAfterRequest:;
- (BOOL)detailPayFooterLayoutExist:;
- (BOOL)detailPayFooterDataEmpty:;
- (id)detailPayFooterLynxRecovery:;
- (BOOL)detailPayFooterLoadFail;
- (BOOL)detailPayFooterForceNativeDoor;
- (void)loadNativePayFooter;
- (void)setServer_task_duration:;
- (id)getProcessedOneStepAbilityRequestParams;
- (id)updatedRequestParams;
- (id)appendParamsIntoRequestParams:;
- (id)appendIntoRequestParams;
- (id)requestParamsManager;
- (id)getCJSharkInfo;
- (id)buildRPCPersistHeader;
- (void)setHasMarkProjectDetailShow:;
- (void)setProjectDetailShowTimeInterval:;
- (double)pageCreateTimeInterval;
- (void)processBypassLogic;
- (BOOL)isGoodsDetailForceLoginPage;
- (void)requestMainDataWithCache:;
- (void)markProjectDetailShow;
- (id)cubeTrackParams;
- (id)getGDRequestParams;
- (void)refreshGoodsDetail:;
- (void)notifyAppendRequestParams:;
- (void)switchToFullScreenMode:;
- (void)closeGoodsDetail:;
- (void)scrollNode:;
- (void)checkAgreementGoodsDetail:;
- (void)jumpToGoodsDetailAlbumPage:;
- (void)goodsDetailNetworkDidFinish:;
- (void)poiAddRecommendExpose:;
- (void)handleNearbyCheckOrderUndertake:;
- (id)stayTimeTracker;
- (id)stayTimeTrackingKey;
- (void)setForbiddenRefreshShowEvent:;
- (void)setUpdatedRouterParams:;
- (void)setUpdatedRequestParams:;
- (void)setAppendIntoRequestParams:;
- (BOOL)fixedToHalf;
- (id)agreementProvider;
- (void)removeElevatorItemWithInfo:;
- (id)initWithBizCode:;
- (void)setFixedToHalf:;
- (id)buildHalfScreenParamsWithOriginParams:;
- (void)setForceFullScreen:;
- (BOOL)configWithRouterURL:paramsDictionary:;
- (void)setFromLive:;
- (void)updateContainerFrameForPadWithDUXBreakPoint:;
- (void)reloadScreenWidthIfNeed;
- (void)reloadNativeCard;
- (void)reloadScreenWidth;
- (void)sendEventToLynxView:params:;
- (id)collectGuideBtnManager;
- (id)noActionEventHandler;
- (void)dismissFromSplitViewStatusIfNeed;
- (void)sendEventToLynxViewWithUniqueTag:eventName:params:;
- (id)updatedRouterParams;
- (void)registerSubscribe;
- (long long)getHeightPercentWithParams:;
- (id)payFooterView;
- (id)recoveryProvider;
- (id)currentAbilityProvider;
- (void)setDownGradeProvider:;
- (id)downGradeProvider;
- (void)setPayFooterView:;
- (id)calculateRealFrameWithOriginFrame:;
- (id)visibleAreaInWindow;
- (BOOL)isRobustVisibleRect:;
- (BOOL)findTargetNode:targetTemplateUrl:;
- (id)detailPayFooterView;
- (void)routerToPay;
- (id)initWithBizCode:sessionId:;
- (BOOL)configWithRouterTransitionInfo:;
- (void)initContainerProviderByBizCode:;
- (void)registerLynxViewExtension;
- (void)registerParamsValidatorExtension;
- (void)registProfessionDitoConfigration;
- (void)setActionMaps:;
- (void)setupUIAppearance;
- (void)setupRenderPriorityManager;
- (void)setNestedScrollManager:;
- (void)preDecodeLynxTemplateIfNeed;
- (void)setupNoActionEventHandler;
- (void)setCollectGuideBtnManager:;
- (void)registNewBtm;
- (void)setNoActionEventHandler:;
- (long long)pageAppearCount;
- (void)setPageAppearCount:;
- (void)viewDidAppearMoreThanOnce;
- (void)viewDidAppearFirstTime;
- (id)fromPOIId;
- (void)setPopupDecorationView:;
- (id)popupDecorationView;
- (void)setOriginRouterUrl:;
- (void)setPageCreateTimeInterval:;
- (void)setBaseRouterParams:;
- (void)setFromPOIId:;
- (void)setLifeBdxTag:;
- (void)setBaseRequestParams:;
- (void)setStayTimeTracker:;
- (void)setupLynxResourcePrefetch;
- (void)preloadHeaderImageFromShelf;
- (id)server_task_duration;
- (void)setCurrentAbilityProvider:;
- (void)setMainReqProvider:;
- (void)setDitoProvider:;
- (void)setPreReqProvider:;
- (void)setPreloadProvider:;
- (void)setTrackerProvider:;
- (void)setRecoveryProvider:;
- (void)setDitoLynxExtension:;
- (id)ditoLynxExtension;
- (void)setSkeletonExtension:;
- (void)setLoadingExtension:;
- (void)setErrorViewExtension:;
- (void)setGoodsParamsValidatorExtension:;
- (id)ditoProvider;
- (void)processContainerConfigrationByBizCode:;
- (void)removeOriginDitoAction;
- (void)updateProviderByBizCode:;
- (void)optimizeLynxRenderThreadStrategy:;
- (double)getInitOpenTime;
- (void)setOriginModalHeight:;
- (id)lifeBdxTag;
- (id)lynxCommonTrackParams;
- (void)initializeWithParameters:;
- (void)setLiveFloatOnTopMuteAction:;
- (void)registDitoAction:byBizCode:handler:;
- (id)pageView:bodyContainerVisibleRect:headerContainer:footerContainer:;
- (void)setupContainerHeader;
- (id)findContentView;
- (void)setAgreementProvider:;
- (id)skeletonExtension;
- (id)loadingExtension;
- (id)goodsParamsValidatorExtension;
- (id)originRouterUrl;
- (void)setContainer:;
- (id)container;
- (void)viewWillDisappear:;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)createContext;
- (void)viewDidDisappear:;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)applicationDidBecomeActive;
- (id)buttonTitle;
- (void)applicationWillResignActive;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (id)bodyView;
- (void)setBodyView:;
- (BOOL)isProcessing;
- (id)pageContext;
- (id)previewManager;
- (void)setPreviewManager:;
+ (Class)aAWEPadSplitScreenAdapterClass;
+ (id)transitionWithURL:paramsDictionary:;
+ (id)buildRecoveryH5UrlFrom:param:;
+ (void)transitionWithTransitionInfo:compensateBizCode:;
@end
