@interface AWEGrouponBubbleView : UIView
@property (nonatomic) UIImageView backgroundView;
@property (nonatomic) UIImageView leftImageView;
@property (nonatomic) UIImageView arrowView;
@property (nonatomic) UIButton actionButton;
@property (nonatomic) UIButton closeButton;
@property (nonatomic) UIButton backgroundButton;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) AWEGrouponAttributedLabel attributedLabel;
@property (nonatomic) BOOL didSetup;
@property (nonatomic) AWEGrouponBubbleModel model;
@property (nonatomic) q position;
@property (nonatomic) @? actionHandler;
@property (nonatomic) @? closeHandler;
@property (nonatomic) @? backgroundHandler;
- (id)closeHandler;
- (void)onCloseButtonClicked:;
- (void)setCloseHandler:;
- (void)onActionButtonClicked:;
- (void)setBackgroundButton:;
- (id)backgroundButton;
- (void)setBackgroundHandler:;
- (void)setup:position:;
- (void)updateArrowPosition:;
- (void)setupWhiteBubble:;
- (void)setupGradientBubble:;
- (id)stretchableImageWithType:;
- (id)arrowImageWithType:;
- (id)stretchableImageWithType:position:;
- (id)backgroundHandler;
- (void)onBackgroundButtonClicked:;
- (id)getPositionString:;
- (void)setModel:;
- (id)actionHandler;
- (void)setActionHandler:;
- (void)setBackgroundView:;
- (long long)position;
- (id)backgroundView;
- (id)model;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setPosition:;
- (BOOL)didSetup;
- (void)setDidSetup:;
- (id)arrowView;
- (void)setArrowView:;
- (id)actionButton;
- (void)setActionButton:;
- (void)setCloseButton:;
- (id)closeButton;
- (id)attributedLabel;
- (void)setAttributedLabel:;
- (id)leftImageView;
- (void)setLeftImageView:;
@end
