@interface AWEHotSpotPublishEntranceDoubleItemView : AWEHotSpotPublishEntranceBaseView
@property (nonatomic) UIView leftBgView;
@property (nonatomic) UIImageView leftIcon;
@property (nonatomic) UILabel leftText;
@property (nonatomic) UIView rightBgView;
@property (nonatomic) UIImageView rightIcon;
@property (nonatomic) UILabel rightText;
@property (nonatomic) AWEHotSpotPublishEntranceShadowView shadowView;
@property (nonatomic) q viewType;
- (void)setupSubViews;
- (void)setLeftIcon:;
- (void)setRightIcon:;
- (void)setLeftBgView:;
- (id)leftBgView;
- (void)setRightBgView:;
- (id)rightBgView;
- (void)updateBarRightTextContent:;
- (void)_setupLayoutForSubViews;
- (void)_setupContentForSubviews;
- (void)setupClickedAction;
- (void)_updateLayoutForLeftPart:;
- (void)configUIStyle;
- (void)_addColorForView;
- (void)_addShadowsForView;
- (void)_addCornerForView;
- (void)onDiscussClicked;
- (void)onShotClicked;
- (id)initWithBarType:;
- (id)shadowView;
- (void)setShadowView:;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (long long)viewType;
- (id)leftText;
- (id)rightText;
- (void)setLeftText:;
- (void)setRightText:;
- (id)leftIcon;
- (id)rightIcon;
- (void)setViewType:;
@end
