@interface AWEHPTabJumpGuideBusinessHandler : NSObject
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) NSString referString;
@property (nonatomic) AWEFeedTabJumpConditionTriggerManager triggerManager;
@property (nonatomic) AWEJumpTabInfoModel infoModel;
@property (nonatomic) AWEFeedTabJumpStrategyItemModel itemModel;
@property (nonatomic) <AWEHPTabJumpModelProtocol> jumpModel;
@property (nonatomic) <AWEHPTabJumpGuideBusinessHandlerDelegate> delegate;
@property (nonatomic) AWEFeedTabJumpRollBackConfig rollBackConfig;
- (id)awemeModel;
- (void)setAwemeModel:;
- (id)referString;
- (void)setReferString:;
- (id)infoModel;
- (id)itemModel;
- (void)setItemModel:;
- (void)setRollBackConfig:;
- (void)setInfoModel:;
- (id)nearbyService;
- (id)rollBackConfig;
- (void)triggerEventWithEventType:;
- (BOOL)shouldLoadTabJumpGuide;
- (id)createTabJumpModelWithTabID:withAwemeModel:withReferString:withInfoModel:;
- (void)setJumpModel:;
- (id)p_schemaWithPath:schema:byAddingQueryDict:;
- (id)jumpModel;
- (void)p_lifeClientAITriggerIfNeededWithProgress:;
- (id)tabJumpModelRegisterDic;
- (id)initWithAwemeModel:withInfoModel:withItemModel:withRollBackConfig:withReferString:withDelegate:;
- (void)handleJumpInfoModelIfNeed;
- (void)tabJumpGuideShowWithComponent:withTrackParams:;
- (void)tabJumpGuideClickWithComponent:withTrackParams:;
- (void)landingTabWithModel:withComponent:;
- (void)onChangeAwemePlayTime:withTotalTime:;
- (void)onChangeAwemeDigg;
- (void)onChangeAwemeAddComment;
- (void)onChangeAwemeFavorite;
- (void)onChangeAwemeShare;
- (void)onChangeAwemeAnchorToMall;
- (void)onChangeAwemeAnchorToPOI;
- (void)onImageAlbumBack;
- (void)onChangeAwemeFollow;
- (void)onChangeAwemeBottomBar:;
- (id)delegate;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)triggerManager;
- (void)setTriggerManager:;
@end
