@interface AWEHPBadgeManager : NSObject
@property (nonatomic) NSMutableDictionary showBadgeMap;
@property (nonatomic) NSMutableDictionary badgeMap;
@property (nonatomic) NSDictionary priority;
@property (nonatomic) BOOL needDownGrade;
@property (nonatomic) NSArray redDotWhiteList;
@property (nonatomic) <AWEPzEngineProtocol> engine;
@property (nonatomic) NSDictionary badgeTypeMap;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)createTask;
- (void)tryShowBadgeWithTask:canShowCallBack:;
- (id)redDotWhiteList;
- (void)setRedDotWhiteList:;
- (void)trackShowBadgeWithModel:;
- (void)trackHideBadgeWithModel:;
- (void)setupPriority;
- (id)needDownGradeBadgeWithNewBadge:;
- (id)badgeMap;
- (BOOL)badgeMigratePizza;
- (BOOL)canReUseComponentWithCurTask:newTask:;
- (BOOL)badgeStrategyEnable;
- (void)needDownGradeBadgeWithNewBadge:callBack:;
- (id)showBadgeMap;
- (id)getDowngradeTypeTrackString:;
- (id)badgeTypeMap;
- (id)currentTabID;
- (id)getHideTypeTrackString:;
- (BOOL)needDownGrade;
- (BOOL)comparePriorityWithFirstTab:secondTab:;
- (void)setNeedDownGrade:;
- (void)setBadgeTypeMap:;
- (void)setShowBadgeMap:;
- (void)setBadgeMap:;
- (id)init;
- (id)engine;
- (id)priority;
- (void)setPriority:;
- (void)setEngine:;
- (void).cxx_destruct;
+ (id)sharedInstance;
@end
