@interface AWEHotSearchCommentFeedPageContext : NSObject
@property (nonatomic) q currentOuterType;
@property (nonatomic) q currentTabType;
@property (nonatomic) NSString keyword;
@property (nonatomic) NSString sentenceId;
@property (nonatomic) NSString discussTitle;
@property (nonatomic) NSString hotSpotDesc;
@property (nonatomic) NSArray avatars;
@property (nonatomic) NSString hotListInfo;
@property (nonatomic) NSNumber discussingPV;
@property (nonatomic) NSDictionary hotListParam;
@property (nonatomic) AWEHotSearchCommentDataSourceModel dataSource;
@property (nonatomic) q currTheme;
@property (nonatomic) NSMutableDictionary logExtraDict;
@property (nonatomic) NSString referString;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSString previousPage;
@property (nonatomic) BOOL isGray;
@property (nonatomic) NSString inputPlaceholder;
@property (nonatomic) BOOL hotspotExpired;
@property (nonatomic) NSString insertCid;
@property (nonatomic) NSString insertReplyCid;
@property (nonatomic) NSString fromGroupID;
@property (nonatomic) BOOL hasAISummary;
@property (nonatomic) NSNumber eventDiscussID;
@property (nonatomic) BOOL isEventDiscuss;
@property (nonatomic) BOOL needLandAISummary;
@property (nonatomic) NSNumber landAISummaryID;
@property (nonatomic) BOOL isLoadedFullData;
@property (nonatomic) NSNumber countOfAISummary;
@property (nonatomic) NSString userVoteTags;
@property (nonatomic) BOOL voteIsEmphasis;
- (void)setLogExtraDict:;
- (id)referString;
- (void)setEnterMethod:;
- (void)setReferString:;
- (id)logExtraDict;
- (id)enterMethod;
- (id)inputPlaceholder;
- (id)fromGroupID;
- (BOOL)isGray;
- (id)sentenceId;
- (void)setSentenceId:;
- (void)setInputPlaceholder:;
- (void)setIsGray:;
- (void)setAvatars:;
- (void)setFromGroupID:;
- (id)eventDiscussID;
- (void)setEventDiscussID:;
- (id)countOfAISummary;
- (void)setCountOfAISummary:;
- (BOOL)isLoadedFullData;
- (id)landAISummaryID;
- (void)setLandAISummaryID:;
- (long long)currTheme;
- (void)setIsEventDiscuss:;
- (BOOL)isEventDiscuss;
- (id)hotSpotDesc;
- (id)discussingPV;
- (id)hotListInfo;
- (void)setDiscussTitle:;
- (void)setInsertCid:;
- (void)setInsertReplyCid:;
- (void)setCurrTheme:;
- (void)setDiscussingPV:;
- (void)updateFeedTabType:;
- (void)setVoteIsEmphasis:;
- (void)setUserVoteTags:;
- (long long)currentTabType;
- (long long)currentOuterType;
- (BOOL)hasAISummary;
- (BOOL)needLandAISummary;
- (void)updateOuterTabType:;
- (void)setHotSpotDesc:;
- (void)setHasAISummary:;
- (void)setNeedLandAISummary:;
- (id)userVoteTags;
- (BOOL)voteIsEmphasis;
- (void)setHotspotExpired:;
- (id)hotListParam;
- (void)setHotListParam:;
- (void)setHotListInfo:;
- (void)setIsLoadedFullData:;
- (BOOL)hotspotExpired;
- (id)insertCid;
- (id)insertReplyCid;
- (void)setCurrentOuterType:;
- (void)setCurrentTabType:;
- (id)discussTitle;
- (void).cxx_destruct;
- (void)setDataSource:;
- (id)dataSource;
- (id)previousPage;
- (void)setPreviousPage:;
- (id)keyword;
- (void)setKeyword:;
- (id)avatars;
@end
