@interface AWEHPMessageManager : NSObject
@property (nonatomic) AWEHPMessageManagerConfig config;
@property (nonatomic) MMKV mmkv;
@property (nonatomic) NSMutableDictionary observers;
@property (nonatomic) {_opaque_pthread_mutex_t=q[56c]} mutexLock;
@property (nonatomic) NSMutableDictionary trackLog;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setMmkv:;
- (id)mmkv;
- (id)mutexLock;
- (void)setMutexLock:;
- (void)revokeMessageIfNeedWithCmd:res:version:;
- (void)registerMessageObserver:withCmd:res:;
- (id)getMessageWithCmd:res:;
- (void)handleHPMessageData:;
- (id)p_readMessageWithCmd:res:;
- (id)keyWithCmd:res:;
- (void)p_revokeMessageIfNeedWithCmd:res:version:;
- (BOOL)p_checkMessageDataValid:error:;
- (id)p_writeMessageData:;
- (void)p_sendMsg:withObservers:;
- (id)p_getCacheMessageWithCmd:res:error:;
- (void)trackMessageReadIfNeedWithCmd:res:params:;
- (void)trackMessageRevokeWithParams:;
- (BOOL)p_cacheMessage:;
- (BOOL)p_checkMessageValid:error:;
- (void)trackMessageHandleWithMessage:status:localVersion:errorCode:;
- (id)trackLog;
- (void)unregisterMessageObserver:;
- (void)setTrackLog:;
- (void)setConfig:;
- (void)dealloc;
- (id)initWithConfig:;
- (id)config;
- (id)observers;
- (void).cxx_destruct;
- (void)setObservers:;
@end
