@interface AWEHotSpotBrandUpgradeLayouts : NSObject
@property (nonatomic) q type;
@property (nonatomic) {CGSize=dd} iconSize;
@property (nonatomic) double iconLeftWidth;
@property (nonatomic) double gradientLeftPadding;
@property (nonatomic) double gradientRightPadding;
@property (nonatomic) double chineseAndTopDistance;
@property (nonatomic) double TopAndXDistance;
@property (nonatomic) double chineseAndArrowDistance;
@property (nonatomic) double gradientHeight;
@property (nonatomic) double topXFrameY;
@property (nonatomic) double chineseFrameY;
@property (nonatomic) double containerHeight;
@property (nonatomic) UIFont chineseFont;
@property (nonatomic) UIFont topXFont;
@property (nonatomic) BOOL hasPreferredThemeStyle;
@property (nonatomic) q preferredThemeStyle;
- (void)setGradientLeftPadding:;
- (double)gradientLeftPadding;
- (BOOL)hasPreferredThemeStyle;
- (void)updateLayoutWithBoardTabModel:;
- (long long)preferredThemeStyle;
- (double)iconLeftWidth;
- (void)setIconLeftWidth:;
- (double)gradientRightPadding;
- (void)setGradientRightPadding:;
- (double)chineseAndTopDistance;
- (void)setChineseAndTopDistance:;
- (double)TopAndXDistance;
- (void)setTopAndXDistance:;
- (double)chineseAndArrowDistance;
- (void)setChineseAndArrowDistance:;
- (double)topXFrameY;
- (void)setTopXFrameY:;
- (double)chineseFrameY;
- (void)setChineseFrameY:;
- (id)chineseFont;
- (void)setChineseFont:;
- (id)topXFont;
- (void)setTopXFont:;
- (void)setHasPreferredThemeStyle:;
- (void)setPreferredThemeStyle:;
- (void)setIconSize:;
- (long long)type;
- (id)iconSize;
- (void)setType:;
- (void).cxx_destruct;
- (id)initWithType:;
- (double)gradientHeight;
- (void)setGradientHeight:;
- (double)containerHeight;
- (void)setContainerHeight:;
@end
