@interface AWEIMPickerConfiguration : NSObject
@property (nonatomic) BOOL disableSendVideo;
@property (nonatomic) BOOL enableShowOriginSelection;
@property (nonatomic) BOOL enableDefaultSetOrigin;
@property (nonatomic) BOOL showSelectedListAndEditInPreview;
@property (nonatomic) BOOL enableLowQualityEarlyReturn;
@property (nonatomic) q maxSelectCount;
@property (nonatomic) q itemCountPerRow;
@property (nonatomic) @? shouldBeSelectedFilter;
@property (nonatomic) NSArray supportAssetCategoryList;
@property (nonatomic) BOOL enableTapOpenPreview;
@property (nonatomic) NSString BPEAAuthorizationKey;
@property (nonatomic) NSString BPEAAppJumpPrivacyKey;
@property (nonatomic) NSArray initialSelectedAssets;
@property (nonatomic) NSArray initialLivePhotoAssetID;
@property (nonatomic) <AWEIMPickerlViewControllerDelegate> delegate;
@property (nonatomic) <AWEIMPickerViewControllerDataSource> dataSource;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) double enterPickerTimeStamp;
- (void)setEnterMethod:;
- (id)enterMethod;
- (void)setMaxSelectCount:;
- (long long)maxSelectCount;
- (void)setDisableSendVideo:;
- (void)setInitialSelectedAssets:;
- (id)initialSelectedAssets;
- (void)setupDefaultValue;
- (BOOL)disableSendVideo;
- (BOOL)enableLowQualityEarlyReturn;
- (void)setEnableLowQualityEarlyReturn:;
- (id)supportAssetCategoryList;
- (long long)itemCountPerRow;
- (id)BPEAAuthorizationKey;
- (id)BPEAAppJumpPrivacyKey;
- (id)shouldBeSelectedFilter;
- (BOOL)enableTapOpenPreview;
- (double)enterPickerTimeStamp;
- (void)setBPEAAuthorizationKey:;
- (void)setBPEAAppJumpPrivacyKey:;
- (void)setShowSelectedListAndEditInPreview:;
- (void)setEnterPickerTimeStamp:;
- (void)setSupportAssetCategoryList:;
- (void)setEnableShowOriginSelection:;
- (void)setShouldBeSelectedFilter:;
- (BOOL)enableDefaultSetOrigin;
- (id)initialLivePhotoAssetID;
- (id)createCategory;
- (BOOL)enableShowOriginSelection;
- (void)setEnableDefaultSetOrigin:;
- (BOOL)showSelectedListAndEditInPreview;
- (void)setItemCountPerRow:;
- (void)setEnableTapOpenPreview:;
- (void)setInitialLivePhotoAssetID:;
- (id)init;
- (id)delegate;
- (void).cxx_destruct;
- (void)setDataSource:;
- (void)setDelegate:;
- (id)dataSource;
@end
