@interface AWEIronManLandingPageCollectionSectionView : UITableViewCell
@property (nonatomic) AWEIronManLandingPageCollectionViewModel viewModel;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) UIButton moreButton;
@property (nonatomic) UIImageView moreButtonImageView;
@property (nonatomic) UIView edgeView;
@property (nonatomic) Q dragingIndex;
@property (nonatomic) UIView dragingView;
@property (nonatomic) AWEIronManLandingPageCommonCollectionCell dragingCell;
@property (nonatomic) AWEIronManLandingPageCommonItemModel dragingItemModel;
@property (nonatomic) AWEIronManLandingPageBottomBarView bottomBar;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)awe_themeDidChange:;
- (id)descLabel;
- (void)setDescLabel:;
- (void)trackMoreButtonClick;
- (void)addBottomBar;
- (id)edgeView;
- (void)setEdgeView:;
- (void)impactFeedback;
- (id)moreButtonImageView;
- (void)setThemeUI;
- (void)dragingBegan:;
- (void)dragingChanged:;
- (void)dragingEnded:;
- (id)getDragingIndexPathWithPoint:;
- (void)setDragingIndex:;
- (void)setDragingCell:;
- (unsigned long long)dragingIndex;
- (void)setDragingItemModel:;
- (id)dragingCell;
- (void)setDragingView:;
- (id)dragingView;
- (void)removeBottomBar;
- (void)restoreDragingView;
- (void)restoreDragingCell;
- (void)trackDragingToDeleteCollectionAtIndex:;
- (id)dragingItemModel;
- (void)trackItemClickAtIndex:;
- (void)trackItemShowAtIndex:;
- (void)moreButtonDidClick:;
- (void)setMoreButtonImageView:;
- (id)collectionView:layout:referenceSizeForFooterInSection:;
- (id)collectionView:layout:referenceSizeForHeaderInSection:;
- (id)collectionView;
- (double)collectionView:layout:minimumInteritemSpacingForSectionAtIndex:;
- (id)initWithViewModel:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setBottomBar:;
- (long long)numberOfSectionsInCollectionView:;
- (id)viewModel;
- (id)containerView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (id)moreButton;
- (void)collectionView:didSelectItemAtIndexPath:;
- (id)bottomBar;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)setMoreButton:;
- (long long)collectionView:numberOfItemsInSection:;
- (void)layoutSubviews;
- (void)longPressGesture:;
- (void)setUpUI;
@end
