@interface AWEIMExchangeCameraUtility : NSObject
@property (nonatomic) NSMutableDictionary quoteTimeDiffDic;
@property (nonatomic) NSMutableDictionary messagesDic;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)exchangeName;
- (BOOL)isSupportExchangeCameraWithConversation:;
- (unsigned long long)exchangeEntranceStrategy;
- (void)routerToExchangeCameraWithContext:;
- (BOOL)isSupportExchangeImageAlbumFullInputQuickSelect:;
- (BOOL)isSupportExchangeImageInputCamera;
- (BOOL)isSupportExchangeImageInputCameraWithConversation:;
- (BOOL)isSupportExchangeImageAlbumFullPhotoPicker:;
- (BOOL)shouldReloadViewModelWithOriginMessage:updateMessage:;
- (id)getExchangeMessageWithMessage:;
- (BOOL)isExchangeRequestFinishWithOriginMessage:updateMessage:;
- (void)trackClickExchangeImageWith:clickFrom:;
- (void)routerToRandomAlbumCamaraConversationId:enterFrom:entrance:enterMethod:;
- (BOOL)isExchangeFinishWithMessage:;
- (BOOL)isSupportExchangeImageFeature;
- (void)clearConversationExchangeIndexInfo:;
- (BOOL)shouldExitReplyExchangeActionBarEntryForMsg:;
- (BOOL)isPeerUserExchangeReverse:;
- (BOOL)shouldShowReplyButtonWithExchangeImageMessage:conversation:;
- (id)getMosaicImageWithImage:messageID:;
- (id)getHintPushDisplayTextWithMessage:displaytype:;
- (BOOL)isSupportExchangeImageChatListCameraWithReplyConversation:completion:;
- (void)setExchangeMsgRecentlySend:uniqueId:;
- (id)getExchangeQuoteTimeDiffWithQuoteServerMsgId:;
- (void)setExchangeQuoteServerMsgId:quoteTimeDiff:;
- (void)setQuoteTimeDiffDic:;
- (void)setMessagesDic:;
- (id)quoteTimeDiffDic;
- (id)messagesDic;
- (void).cxx_destruct;
+ (id)getTitleAttributedStringWithMessage:needExchangeAnimation:isExchangeImageFinish:;
+ (long long)getExchangeIndexWith:;
+ (void)updateConversationExchangeIndexWith:message:completion:;
+ (BOOL)isSupportExchangeImageCameraAlbum;
+ (BOOL)isSupportExchangeImageAlbumRandom;
+ (void)storeExchangeFinishLocalMarkWithServerMsgId:;
+ (id)memoryCacheForNewGlobalIndexWithCon:;
+ (id)diskCacheForNewGlobalIndexWithCon:;
+ (void)writeMemoryCacheForNewGlobalIndex:withCon:;
+ (id)memoryCacheForNewOtherGlobalIndexWithCon:;
+ (id)diskCacheForNewOtherGlobalIndexWithCon:;
+ (void)writeMemoryCacheForNewOtherGlobalIndex:withCon:;
+ (void)routerToExchangeImageCamaraWithMessage:conversationId:enterFrom:entrance:extraInfo:;
+ (void)writeMemoryCacheForIMMessage:withConID:;
+ (id)memoryCacheForIMMessageWithConID:;
+ (long long)newGlobalIndexWithCon:;
+ (long long)newOtherGlobalIndexWithCon:;
+ (void)setNewGlobalIndex:withCon:;
+ (void)setNewOtherGlobalIndex:withCon:;
+ (void)routerToExchangeImageCamaraWithConversationId:enterFrom:entrance:;
+ (id)getGaussianBlurImageWithImage:blurRadius:;
+ (BOOL)isSupportExchangeImageAnimation;
+ (id)getUnlockWithoutExchangeUidsInGroups:;
+ (long long)getOtherExchangeIndexWith:;
+ (void)updateConversationExchangeOtherIndexWith:message:completion:;
+ (void)requestExchangedMessageListWithMessage:completion:;
+ (void)filterExchangeMessageListWithConversationId:messageList:complete:;
+ (id)sharedInstance;
@end
