@interface AWEIMSkyEyeFloatTipInteractor : AWEIMComponentBase
@property (nonatomic) AWEIMSecurityToastConfigModel config;
@property (nonatomic) AWEIMTopSecurityTipView tipView;
@property (nonatomic) <AWEIMSkyEyeFloatTipInteractorDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL showInFloatMode;
@property (nonatomic) @? continueBlock;
@property (nonatomic) @? removeBlock;
@property (nonatomic) BOOL invalid;
@property (nonatomic) Q priorityValue;
- (BOOL)showInFloatMode;
- (void)setShowInFloatMode:;
- (id)removeBlock;
- (void)setRemoveBlock:;
- (void)hideViewIfNeed;
- (void)showViewIfNeed;
- (id)shouldContinueForPriorityObject:;
- (id)shouldRemoveForPriorityObject:;
- (id)vcParent;
- (double)getMessageListVCTop;
- (id)getNoticeTipSize;
- (void)p_showTopView;
- (void)p_dismissTopView:;
- (void)render:context:;
- (void)topSecurityTipView:didClickButtonModel:;
- (void)topSecurityTipViewDidClickCloseButton:;
- (void)topSecurityTipViewDidShowInterrupted:;
- (BOOL)isTopViewShowing;
- (void)setConfig:;
- (void)setTipView:;
- (id)delegate;
- (void)setInvalid:;
- (id)view;
- (id)config;
- (void)dismiss;
- (void).cxx_destruct;
- (void)setDelegate:;
- (BOOL)invalid;
- (id)continueBlock;
- (void)setContinueBlock:;
- (unsigned long long)priorityValue;
- (void)setPriorityValue:;
- (id)tipView;
@end
