@interface AWEIMManagerCustomEmoticonViewController : UIViewController
@property (nonatomic) AWEIMManagerCustomEmoticonNavView navView;
@property (nonatomic) AWEIMEmoticonManagerDeleteView deleteView;
@property (nonatomic) AWEIMEmoticonManagerDeleteView peakView;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) NSMutableArray selectedEmoticonArray;
@property (nonatomic) BOOL isManaging;
@property (nonatomic) UITapGestureRecognizer manageGestureRecognizer;
@property (nonatomic) UITapGestureRecognizer finishGestureRecognizer;
@property (nonatomic) NSArray sourceArray;
@property (nonatomic) BOOL isGroup;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (void)reloadCollectionView;
- (void)closeView;
- (id)deleteView;
- (void)setDeleteView:;
- (id)navView;
- (void)setNavView:;
- (void)successAddCustomSticker;
- (void)didLongPressCell:;
- (void)cell:changeSelectStatus:emoticon:;
- (void)setIsManaging:;
- (void)didLoadMoreData;
- (id)peakView;
- (id)manageGestureRecognizer;
- (id)finishGestureRecognizer;
- (id)selectedEmoticonArray;
- (void)setSelectedEmoticonArray:;
- (void)continueManage;
- (void)openLibrary;
- (void)loadMoreDataIfNeed;
- (void)manageCustomEmoticon;
- (void)finishManage;
- (void)deleteCustomEmoticon;
- (void)peakCustomEmoticon;
- (void)setPeakView:;
- (void)setManageGestureRecognizer:;
- (void)setFinishGestureRecognizer:;
- (id)collectionView;
- (void)setIsGroup:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)viewDidLoad;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (BOOL)isGroup;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (BOOL)isManaging;
- (void)setSourceArray:;
- (id)sourceArray;
@end
