@interface AWEIMMessageFollowViewInteractor : AWEIMComponentBase
@property (nonatomic) AWEIMStrangerFollowView followView;
@property (nonatomic) AWEIMMessageBaseViewController vcParent;
@property (nonatomic) NSString userID;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) BOOL isRequesting;
@property (nonatomic) BOOL isHideWhenMultiSelect;
@property (nonatomic) BOOL didTrackShowFollowButtonBar;
@property (nonatomic) BOOL peerUserIsMyUnFollowFamiliar;
@property (nonatomic) q localFollowStatus;
@property (nonatomic) q localFollowerStatus;
@property (nonatomic) BOOL invokeShowByOptimize;
@property (nonatomic) AWEUserModel fullDetailUser;
@property (nonatomic) RxDeferred fetchFullUserPromise;
@property (nonatomic) RxDeferred firstPageReloadPromise;
@property (nonatomic) BOOL isFollowViewShowOptimize;
@property (nonatomic) BOOL isMangoScene;
@property (nonatomic) AWEUserModel user;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL showInFloatMode;
@property (nonatomic) @? continueBlock;
@property (nonatomic) @? removeBlock;
@property (nonatomic) BOOL invalid;
@property (nonatomic) Q priorityValue;
- (void)didFinishFollowUser:status:error:;
- (void)didFinishUnFollowUser:status:error:;
- (void)didFinishBlockUser:status:;
- (void)didFinishCloseFriendsWithUser:status:;
- (void)setEnterFrom:;
- (id)enterFrom;
- (void)hostVC_viewDidDisappear;
- (BOOL)showInFloatMode;
- (void)setShowInFloatMode:;
- (id)removeBlock;
- (void)setRemoveBlock:;
- (void)hideViewIfNeed;
- (void)showViewIfNeed;
- (id)shouldContinueForPriorityObject:;
- (id)shouldRemoveForPriorityObject:;
- (void)afterInitialComponentAllResolved:;
- (void)hostVC_viewDidLoad;
- (void)componentDidMounted:;
- (void)didFetchFullDetailUser:fullDetailUser:;
- (void)viewDidChangeBackgroundImage:;
- (BOOL)isRequesting;
- (void)setIsRequesting:;
- (id)followView;
- (void)setFollowView:;
- (id)fullDetailUser;
- (void)setFullDetailUser:;
- (id)vcParent;
- (void)didChangeRelationOldStatus:newStatus:;
- (void)completeColdupIncentiveChatDataUpdate;
- (void)incentiveActivityExit;
- (void)messageListBackgroundImageDidUpdated:;
- (void)didFetchFullDetailUser:;
- (BOOL)isFollowTipsViewShowing;
- (double)getMessageListVCTop;
- (void)updateFollowViewFrame;
- (void)dismissFollowView:;
- (void)didFinishReloadFirstPageTableViewFilled:;
- (void)setFetchFullUserPromise:;
- (id)fetchFullUserPromise;
- (void)setIsFollowViewShowOptimize:;
- (void)strangerTransferToFriendInCurrentController;
- (void)setFirstPageReloadPromise:;
- (id)firstPageReloadPromise;
- (void)p_showWithUser:;
- (void)setIsMangoScene:;
- (BOOL)isMangoScene;
- (void)p_recordFilledState:;
- (void)p_tryShowFollowViewImmediately;
- (BOOL)isFollowViewShowOptimize;
- (void)p_recordFollowViewShowingWhenVCDisappear;
- (void)refreshIncentiveChatUIIfNeeded;
- (void)p_refreshFollowUIIfNeeded;
- (void)setInvokeShowByOptimize:;
- (void)p_handleDataWithDetailUser:fullDetailUser:;
- (BOOL)p_shouldCorrectFollowViewWithUser:;
- (long long)localFollowerStatus;
- (void)p_topFollowBtnClicked:;
- (void)p_topCloseBtnClicked:;
- (BOOL)invokeShowByOptimize;
- (BOOL)didTrackShowFollowButtonBar;
- (void)setDidTrackShowFollowButtonBar:;
- (BOOL)peerUserIsMyUnFollowFamiliar;
- (long long)localFollowStatus;
- (BOOL)isHideWhenMultiSelect;
- (void)setPeerUserIsMyUnFollowFamiliar:;
- (BOOL)p_shouldShowFollowTips:;
- (void)p_addFollowView:;
- (void)setLocalFollowStatus:;
- (double)vcParentViewWidth;
- (void)setIsHideWhenMultiSelect:;
- (void)setLocalFollowerStatus:;
- (id)user;
- (void)setUser:;
- (void)show;
- (id)userID;
- (void)dealloc;
- (void)setInvalid:;
- (void).cxx_destruct;
- (BOOL)invalid;
- (void)setUserID:;
- (id)continueBlock;
- (void)setContinueBlock:;
- (unsigned long long)priorityValue;
- (void)setPriorityValue:;
+ (BOOL)canCreateComponentWithContext:;
@end
