@interface AWEIMFacePuzzleRecognizeSenseAnswerGetResponseModel : AWEBaseApiModel
@property (nonatomic) AWEIMFacePuzzlePicModel resultJointPic;
@property (nonatomic) q useTime;
@property (nonatomic) AWEIMFacePuzzlePicModel mainPic;
@property (nonatomic) NSDictionary chooseAnswerMap;
@property (nonatomic) NSString secExerciseUserId;
@property (nonatomic) NSString secExerciseId;
@property (nonatomic) NSString secAnswerUserId;
@property (nonatomic) q recognizeVisitUserType;
@property (nonatomic) NSString answerDataMatchSimpleStr;
@property (nonatomic) NSString answerDataMatchStr;
@property (nonatomic) q exerciseStatus;
@property (nonatomic) q answerStatus;
@property (nonatomic) q exerciseActivityStatus;
@property (nonatomic) NSString secExerciseAnswerId;
@property (nonatomic) NSString conversationId;
- (void)setSecExerciseUserId:;
- (void)setSecExerciseId:;
- (id)mainPic;
- (long long)exerciseActivityStatus;
- (long long)exerciseStatus;
- (void)setUseTime:;
- (long long)answerStatus;
- (id)resultJointPic;
- (void)setSecAnswerUserId:;
- (void)setSecExerciseAnswerId:;
- (id)secExerciseId;
- (id)secExerciseUserId;
- (void)setMainPic:;
- (void)setExerciseActivityStatus:;
- (long long)recognizeVisitUserType;
- (void)setRecognizeVisitUserType:;
- (void)setExerciseStatus:;
- (long long)useTime;
- (void)setResultJointPic:;
- (id)chooseAnswerMap;
- (void)setChooseAnswerMap:;
- (id)secAnswerUserId;
- (id)answerDataMatchSimpleStr;
- (void)setAnswerDataMatchSimpleStr:;
- (id)answerDataMatchStr;
- (void)setAnswerDataMatchStr:;
- (id)secExerciseAnswerId;
- (void)setAnswerStatus:;
- (void).cxx_destruct;
- (id)conversationId;
- (void)setConversationId:;
+ (id)resultJointPicJSONTransformer;
+ (id)mainPicJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
