@interface AWEIMPrivateChatManagementHelperViewController : UIViewController
@property (nonatomic) AWEIMPrivateChatManagementHelperViewModel viewModel;
@property (nonatomic) NSArray chatArr;
@property (nonatomic) Q selectType;
@property (nonatomic) UIView baseView;
@property (nonatomic) UITableView tableView;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) NSString pageIdentifier;
@property (nonatomic) NSDictionary routerParams;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)aweui_emptyPageConfigForState:;
- (id)aweui_emptyPageEdgeInsets;
- (BOOL)configWithRouterParamDict:;
- (id)routerParams;
- (void)setRouterParams:;
- (void)__setupUI;
- (unsigned long long)selectType;
- (void)__showLoadingView;
- (void)__backBtnClicked;
- (void)setSelectType:;
- (void)__addKVO;
- (void)__updateNaviBar;
- (void)__hideLoadingViewIfNeeded;
- (void)setChatArr:;
- (id)chatArr;
- (void)__transferToConversationWithConversationID:;
- (id)tableView:viewForHeaderInSection:;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (id)init;
- (void)setBaseView:;
- (long long)numberOfSectionsInTableView:;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)tableView;
- (id)loadingView;
- (void)setViewModel:;
- (void).cxx_destruct;
- (double)tableView:heightForRowAtIndexPath:;
- (id)title;
- (double)tableView:heightForHeaderInSection:;
- (id)baseView;
- (double)tableView:heightForFooterInSection:;
- (id)tableView:viewForFooterInSection:;
- (id)pageIdentifier;
- (void)setPageIdentifier:;
@end
