@interface AWEIMConfirmView : UIView
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView avatarView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel descLabel;
@property (nonatomic) BDPStyleTextField inputText;
@property (nonatomic) UIView horizontalSep;
@property (nonatomic) UIView verticalSep;
@property (nonatomic) UIButton cancelBtn;
@property (nonatomic) UIButton confirmBtn;
@property (nonatomic) NSLayoutConstraint containerCenterYCons;
@property (nonatomic) NSLayoutConstraint containerBottomCons;
@property (nonatomic) @? onTapCancel;
@property (nonatomic) @? onTapConfirm;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)descLabel;
- (void)setDescLabel:;
- (id)confirmBtn;
- (id)cancelBtn;
- (void)setConfirmBtn:;
- (void)setCancelBtn:;
- (id)horizontalSep;
- (id)verticalSep;
- (void)setContainerCenterYCons:;
- (id)containerCenterYCons;
- (void)setContainerBottomCons:;
- (id)onTapCancel;
- (id)onTapConfirm;
- (id)containerBottomCons;
- (void)updateContainerPosition:noti:;
- (void)onTapBtn:;
- (void)show:withContainer:completion:;
- (void)setOnTapCancel:;
- (void)setOnTapConfirm:;
- (void)setHorizontalSep:;
- (void)setVerticalSep:;
- (void)prepareLayout;
- (void)keyboardWillHide:;
- (void)textFieldDidEndEditing:;
- (void)dealloc;
- (void)setAvatarView:;
- (void)setImage:;
- (id)initWithFrame:;
- (id)containerView;
- (id)avatarView;
- (void)setDesc:;
- (void)setContainerView:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (void)touchesBegan:withEvent:;
- (id)titleLabel;
- (void)keyboardWillShow:;
- (void)setTitle:;
- (id)inputText;
- (void)setInputText:;
- (void)setupUI;
- (void)keyboardWillChange:;
@end
