@interface AWEIMJXMessageListPushGuideComponent : AWEIMComponentBase
@property (nonatomic) q popupViewStatus;
@property (nonatomic) @? popupViewStatusBlock;
@property (nonatomic) BOOL hasNotice;
@property (nonatomic) q noticeGlobalIndex;
@property (nonatomic) NSSet messageGlobalIndexSet;
@property (nonatomic) BOOL hasBanner;
@property (nonatomic) AWEIMPushWithoutInnerPushSheet popUpSheet;
@property (nonatomic) BOOL isFromPopupSheet;
@property (nonatomic) @? onClose;
@property (nonatomic) BOOL isCloseForPushGuideOpen;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)messageDataControllerDidModified;
- (void)hostVC_willDealloc;
- (void)componentDidMounted:;
- (void)showPitayaPushGuide:;
- (void)onPitayaTriggerFailed:;
- (long long)messageListPopupViewStatus;
- (void)messageListPopupViewShow;
- (void)asyncGetMessageListPopupViewStatus:;
- (long long)popupViewStatus;
- (void)setPopupViewStatus:;
- (id)p_lastTimeKey;
- (void)newInsertMessageAtGloabalIndex:;
- (void)reInsertMessageAtGloabalIndex:;
- (void)didPushBannerShow;
- (void)setPopUpSheet:;
- (void)p_outAppNotifyGuideLogWithEventType:;
- (void)p_openReceivePushOnlyFromFrends;
- (id)popUpSheet;
- (BOOL)p_canShowPopupView;
- (void)p_changeSettingWithField:value:completion:;
- (BOOL)isFromPopupSheet;
- (void)setIsFromPopupSheet:;
- (void)p_loadLatestMessageGlobalIndexIfNeeded;
- (id)messageGlobalIndexSet;
- (void)setMessageGlobalIndexSet:;
- (void)setPopupViewStatusBlock:;
- (double)p_lastLogTimeStamp;
- (void)p_invokeFailedShowPopupViewBlock;
- (void)p_setLastLogTime:;
- (id)popupViewStatusBlock;
- (void)setIsCloseForPushGuideOpen:;
- (BOOL)p_hasNotice;
- (void)setHasNotice:;
- (long long)noticeGlobalIndex;
- (void)setNoticeGlobalIndex:;
- (void)setHasBanner:;
- (BOOL)isCloseForPushGuideOpen;
- (void)handleDidBecomeActive:;
- (void).cxx_destruct;
- (BOOL)hasBanner;
- (BOOL)hasNotice;
- (id)onClose;
- (void)setOnClose:;
+ (BOOL)canCreateComponentWithContext:;
+ (BOOL)p_featureEnableInCunrrentContext:;
@end
