@interface AWEIMMessageListMediaComponent : AWEIMComponentBase
@property (nonatomic) AWEIMMessageDetailManager messageDetailManager;
@property (nonatomic) UIView fromView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)componentDidMounted:;
- (void)hostVC_viewDidAppear;
- (id)baseVC;
- (void)showMediaListWithContext:requestScene:completion:;
- (void)showMediaListWithCell:message:extraParams:requestScene:;
- (void)showMediaListWithCell:message:extraParams:requestScene:completion:;
- (void)showSingleMediaWithContext:requestScene:;
- (void)showMessageDetailWithMessage:requestScene:;
- (void)showMessageDetailWithOriginMessage:requestScene:;
- (void)mediaQuickReplyClickedForCell:;
- (void)showMediaListWithCell:message:requestScene:;
- (void)showMediaWithMessage:cell:shouldShowComment:requestScene:;
- (void)showSingleMediaWithCell:targetMessage:requestScene:;
- (id)getMediaEntranceVieWController;
- (id)messageListVC;
- (id)p_getMediaEntranceVieWController;
- (void)p_showSingleMediaWithCell:targetMessage:requestScene:completion:;
- (void)__messageDetailtrackerWithMessage:;
- (id)messageDetailManager;
- (void)messageDetailManager:showImageVideoControllerWithMessages:currentIndex:requestScene:;
- (void)messageDetailManager:willSelectedOriginMessage:requestScene:;
- (void)messageDetailManager:showCardWithWithMessage:requestScene:;
- (void)messageDetailManager:showMediaWithMessage:shouldShowComment:requestScene:;
- (void)messageDetailManager:showMediaWithMessage:shouldShowChapterPanel:requestScene:;
- (void)messageDetailManager:showSpecialMessage:;
- (void)setMessageDetailManager:;
- (void)setFromView:;
- (void).cxx_destruct;
- (id)fromView;
- (id)conversation;
+ (BOOL)canCreateComponentWithContext:;
@end
