@interface AWEIMDSPMusicServiceController : NSObject
@property (nonatomic) <MusicService> musicService;
@property (nonatomic) <MusicService> secondaryMusicService;
@property (nonatomic) <AWEMusicStreamingPlayEventService> eventService;
@property (nonatomic) AWEIMShareDSPMusicMessage playMessage;
@property (nonatomic) AWEIMMessage possibleMatchedQuote;
@property (nonatomic) <AWEMusicShareServiceProtocol> shareDspService;
@property (nonatomic) BOOL isRequstingPlay;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)musicService:playStatusChanged:;
- (id)musicService;
- (void)setMusicService:;
- (void)p_addSelfObserveNotifications;
- (id)playMessage;
- (void)reportMusicMessageClickWithMessage:;
- (void)destroyIfNeeded;
- (void)setIsRequstingPlay:;
- (BOOL)isRequstingPlay;
- (void)setPlayMessage:;
- (void)setPossibleMatchedQuote:;
- (id)finalMusicIdWithMessage:;
- (id)secondaryMusicService;
- (void)setShareDspService:;
- (id)shareDspService;
- (BOOL)p_isRecalledByMyselfWithRecalledMessage:recallingMessage:;
- (void)p_resetMusicMessagePlayStatus;
- (void)p_removeSelfObserveNotifications;
- (id)possibleMatchedQuote;
- (void)p_postPlayStatusChangedNotification;
- (void)p_imAudioPlayWillStartNotified;
- (void)p_imAudioWillRecordNotified;
- (BOOL)hasMoreOfScene:;
- (id)playMessageMusicId;
- (id)playMessageID;
- (void)playWithMusicMessage:;
- (void)pauseWithMusicMessage:;
- (void)playSharedMusicWithMessage:quotingMessage:stopPlayWhenExitDSPPlayer:completed:;
- (void)stopPlayMusicMessageAfterDeleteMessage:;
- (void)stopPlayMusicMessageAfterRecallMessage:recallingMessage:;
- (void)stopMusicWhenHostViewControllerDidDisappear;
- (BOOL)p_isSameQuote:;
- (void)setSecondaryMusicService:;
- (id)init;
- (void)dealloc;
- (void)setEventService:;
- (void).cxx_destruct;
- (id)eventService;
@end
