@interface AWEIMMentionParticipantDataController : NSObject
@property (nonatomic) AWEIMConversationContext conversationContext;
@property (nonatomic) <IESIMBotsDataManagerProtocol> botsDataController;
@property (nonatomic) NSDictionary aiAppendTipsMap;
@property (nonatomic) <IESIMSearchEngineProtocol> searchEngine;
@property (nonatomic) AWEIMMentionParticipantSearchModel atAllModel;
@property (nonatomic) NSArray bots;
@property (nonatomic) NSArray aiClones;
@property (nonatomic) NSArray participants;
@property (nonatomic) AWEIMMentionParticipantSearchModel inviteBotsModel;
@property (nonatomic) BOOL isInSearchMode;
@property (nonatomic) BOOL isFetchingIntimacyData;
@property (nonatomic) AWEIMCollectionListModel listModel;
@property (nonatomic) NSArray groupIntimacyArray;
@property (nonatomic) NSArray sectionTypes;
@property (nonatomic) AWEIMMessageConversation conversation;
@property (nonatomic) <AWEIMMentionParticipantDataControllerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)bots;
- (void)setBots:;
- (void)formatData;
- (void)p_setupSearchEngine;
- (void)setSearchEngine:;
- (void)searchWithKeyword:;
- (id)botsDataController;
- (id)p_displayNameForSortWithImUser:;
- (BOOL)p_isNumberFirst:;
- (void)p_sortedDataArray:fromArray:;
- (void)makeSelectAIAppendTips:;
- (id)initWithConversationContext:;
- (void)iesim_botsDataSourceDidUpdate;
- (void)setBotsDataController:;
- (id)aiClones;
- (void)setAiClones:;
- (void)resetSearchMode;
- (id)aiAppendTipsMap;
- (void)setAiAppendTipsMap:;
- (void)p_formatBotsData;
- (void)p_formatParticipantsData;
- (void)p_updateInviteBots;
- (id)inviteBotsModel;
- (void)setInviteBotsModel:;
- (void)setGroupIntimacyArray:;
- (id)p_sortedPaticipantsFromArray:;
- (id)groupIntimacyArray;
- (id)p_sortedPaticipantsByAtandIntimacy:atDic:intimacyArr:;
- (void)p_getandSaveIntimacyData;
- (BOOL)isFetchingIntimacyData;
- (void)setIsFetchingIntimacyData:;
- (void)setIsInSearchMode:;
- (void)p_updateAtAllAccess;
- (id)p_resultForSearchList:keyword:operation:;
- (id)atAllModel;
- (void)setAtAllModel:;
- (BOOL)isInSearchMode;
- (id)selectAIAppendTipWithUid:;
- (id)participants;
- (id)delegate;
- (void)setParticipants:;
- (void)setListModel:;
- (id)listModel;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)conversation;
- (void)setConversation:;
- (id)conversationContext;
- (void)setConversationContext:;
- (void)refreshData;
- (id)searchEngine;
- (id)sectionTypes;
- (void)setSectionTypes:;
@end
