@interface AWEIMGreetingContentView : UIView
@property (nonatomic) q showedIndex;
@property (nonatomic) UIButton closeButton;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) UILabel greetingLabel;
@property (nonatomic) UIView separatorLineView;
@property (nonatomic) NSArray stickers;
@property (nonatomic) @? closeButtonClickAction;
@property (nonatomic) @? sendSelectEmojiWithGreetingEmoticonBlock;
@property (nonatomic) @? willDisplayEmojiWithGreetingEmoticonBlock;
@property (nonatomic) BOOL needCalculateShowedIndex;
@property (nonatomic) double separatorLineViewTopOffsetOfParentView;
@property (nonatomic) {CGSize=dd} closeButtonSize;
@property (nonatomic) double closeButtonTrailingOffsetOfParentView;
@property (nonatomic) double collectionViewHeight;
@property (nonatomic) double collectionViewTopOffsetOfGreetingLabel;
@property (nonatomic) {CGSize=dd} collectionViewItemSize;
@property (nonatomic) double greetingLabelHeight;
@property (nonatomic) double greetingLabelTopOffsetOfParentView;
@property (nonatomic) double greetingLabelLeadingOffsetOfParentView;
@property (nonatomic) double greetingLabelTrailingOffsetOfParentView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (void)setCloseButtonSize:;
- (void)closeButtonClicked:;
- (id)closeButtonClickAction;
- (void)setCloseButtonClickAction:;
- (void)stopAnimationIfNeed;
- (id)closeButtonSize;
- (id)greetingLabel;
- (void)setGreetingLabelHeight:;
- (void)setNeedCalculateShowedIndex:;
- (void)setSeparatorLineViewTopOffsetOfParentView:;
- (void)setCloseButtonTrailingOffsetOfParentView:;
- (void)setGreetingLabelLeadingOffsetOfParentView:;
- (void)setGreetingLabelTrailingOffsetOfParentView:;
- (void)setCollectionViewItemSize:;
- (void)setCollectionViewTopOffsetOfGreetingLabel:;
- (void)setGreetingLabelTopOffsetOfParentView:;
- (void)setSendSelectEmojiWithGreetingEmoticonBlock:;
- (void)setWillDisplayEmojiWithGreetingEmoticonBlock:;
- (double)greetingLabelTopOffsetOfParentView;
- (double)collectionViewTopOffsetOfGreetingLabel;
- (id)sendSelectEmojiWithGreetingEmoticonBlock;
- (id)willDisplayEmojiWithGreetingEmoticonBlock;
- (BOOL)needCalculateShowedIndex;
- (double)separatorLineViewTopOffsetOfParentView;
- (double)closeButtonTrailingOffsetOfParentView;
- (id)collectionViewItemSize;
- (double)greetingLabelHeight;
- (double)greetingLabelLeadingOffsetOfParentView;
- (double)greetingLabelTrailingOffsetOfParentView;
- (void)p_updateShowedIndex:;
- (id)p_getCurrentTimeFilterTag;
- (long long)showedIndex;
- (void)setShowedIndex:;
- (void)setGreetingLabel:;
- (id)collectionView;
- (id)collectionView:cellForItemAtIndexPath:;
- (long long)numberOfSectionsInCollectionView:;
- (id)initWithFrame:;
- (void)refreshUI;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)scrollViewDidScroll:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)setCloseButton:;
- (id)closeButton;
- (id)stickers;
- (double)collectionViewHeight;
- (void)setCollectionViewHeight:;
- (id)separatorLineView;
- (void)setSeparatorLineView:;
- (void)setStickers:;
@end
