@interface AWEIMGroupNoticeMessage : AWEIMMessage
@property (nonatomic) AWEIMGroupNameAlertView alertView;
@property (nonatomic) BOOL hasBackgroundImage;
@property (nonatomic) q removeUserNoticeType;
@property (nonatomic) NSString innerContent;
@property (nonatomic) BOOL willIngoreCurrentUser;
@property (nonatomic) NSDictionary contentExt;
@property (nonatomic) NSArray templateArray;
@property (nonatomic) AWEIMGroupNoticeAttributedContentContext attributedContentContext;
@property (nonatomic) NSMutableDictionary highlightTapActionMap;
@property (nonatomic) NSArray subjectUsers;
@property (nonatomic) NSArray objectUsers;
@property (nonatomic) AWEIMGroupNoticeBackupTextModel cnBackupText;
@property (nonatomic) AWEIMGroupNoticeBackupTextModel enBackupText;
@property (nonatomic) AWEIMLinkTextUtility linkTextUtility;
@property (nonatomic) NSString content;
@property (nonatomic) BOOL noticeByCreateGroup;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)initWithContentDict:;
- (id)contentComponentName;
- (void)dismissAlertView;
- (BOOL)shouldHideWithCon:;
- (id)getContentDict;
- (BOOL)isUserCellType;
- (id)pluginsComponentsName;
- (BOOL)supportRefactorCell;
- (id)templateArray;
- (BOOL)canShowSpecialEffect;
- (id)calculateAttributedContent;
- (void)prepareForConversationHint;
- (void)setTemplateArray:;
- (id)highlightTapActionMap;
- (id)contentHighlightActionMap;
- (void)setHighlightTapActionMap:;
- (void)setEnBackupText:;
- (void)setCnBackupText:;
- (void)setObjectUsers:;
- (void)setSubjectUsers:;
- (void)setNoticeByCreateGroup:;
- (void)setRemoveUserNoticeType:;
- (void)setContentExt:;
- (id)subjectUsers;
- (id)objectUsers;
- (id)cnBackupText;
- (id)enBackupText;
- (BOOL)noticeByCreateGroup;
- (id)contentExt;
- (void)setInnerContent:;
- (id)p_getObjectNameWithObjectRange:;
- (long long)removeUserNoticeType;
- (id)p_getSubjectNameWithSubjectRange:;
- (id)__tipsModifiedWithBaseText:usersArray:currentUserID:placeholderString:useZH:;
- (id)p_getObjectNameWithObjectRange:ignoreCurrentUser:;
- (void)setWillIngoreCurrentUser:;
- (id)innerContent;
- (id)calculateTips;
- (void)setLinkTextUtility:;
- (id)linkTextUtility;
- (id)calculateAttributeDict;
- (id)__attributedTipsContentContextByAweType;
- (void)setAttributedContentContext:;
- (id)attributedContentContext;
- (void)__savaHighlightTapAction:range:;
- (void)p_addPersonalDetailLinkToAttStr:withNoticeUser:;
- (void)p_addAITagIfNeededToAttStr:withNoticeUser:;
- (BOOL)willIngoreCurrentUser;
- (void)p_changeGroupName;
- (void)__openGroupManager;
- (void)__openGroupAnnounce;
- (void)__transferToSearchResultPage;
- (void)__openEditGroupAvatar;
- (void)p_transferToCreateGroupVC;
- (BOOL)p_shouldAppendHistoryNotice;
- (void)__openGroupSetting;
- (id)content;
- (id)alertView;
- (long long)templateType;
- (void)setAlertView:;
- (void).cxx_destruct;
- (BOOL)hasBackgroundImage;
- (void)setHasBackgroundImage:;
+ (Class)viewModelClass;
+ (BOOL)aweim_shouldGenerateTopGroupNoticeWithFaceToFaceCreate:conversationID:;
+ (BOOL)shouldGenerateTopGroupNoticeWithMessage:;
+ (BOOL)shouldGenerateTopGroupNoticeWithIESMessage:;
@end
