@interface AWEIMCampaignHeaderViewContorller : UIViewController
@property (nonatomic) UILabel releaseTip;
@property (nonatomic) UIButton campaignBtn;
@property (nonatomic) double lastOffset;
@property (nonatomic) BOOL hasPresentedHint;
@property (nonatomic) BOOL hasPresentedVibrate;
@property (nonatomic) UIButton backButton;
@property (nonatomic) double dropDownThresholdPad_12;
@property (nonatomic) double dropDownThresholdPad_27;
@property (nonatomic) double dropDownThresholdPad_45;
@property (nonatomic) UIView<AWEUGActivityNoticeTitleViewProtocol> titleView;
@property (nonatomic) BOOL hasPullAnimation;
@property (nonatomic) UIImageView lableImageView;
@property (nonatomic) UIImageView backgroundImageView;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView fakeNaviImageView;
@property (nonatomic) @? campaignBtnClick;
@property (nonatomic) @? campaignStateDidChangeBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (void)backButtonClicked;
- (id)imageWithView:;
- (void)bindNavigationbar:;
- (double)campaignHeaderOffsetRadio;
- (id)lableImageView;
- (void)updateWithOffset:isAuto:;
- (void)updateWithOffset:;
- (double)campaignHeaderDropDownHeightThreshold;
- (double)campaignGuideHeightWithAnimation;
- (void)setCampaignBtnClick:;
- (void)setCampaignStateDidChangeBlock:;
- (void)showCampaignButton:;
- (void)prepareForScrollDownAutomatically;
- (void)animateScrollDownAutomatically;
- (void)resetToInit;
- (void)onCampginEnableChangeNotification:;
- (id)campaignBtn;
- (id)fakeNaviImageView;
- (id)releaseTip;
- (BOOL)hasPullAnimation;
- (void)setHasPullAnimation:;
- (double)dropDownThresholdPad_45;
- (void)updatePadBackgroundImageViewWithOffset:;
- (void)updatePadLableImageViewCenterWithOffset:;
- (void)updateBackgroundImageViewWithOffset:;
- (void)updateLableImageViewCenterWithOffset:;
- (void)updateTipsWithOffset:;
- (BOOL)hasPresentedVibrate;
- (void)setHasPresentedVibrate:;
- (BOOL)hasPresentedHint;
- (void)setHasPresentedHint:;
- (void)padPrepareForScrollDownAutomatically;
- (void)padAnimateScrollDownAutomatically;
- (id)campaignBtnClick;
- (void)campaignBtnClicked;
- (double)dropDownThresholdPad_12;
- (double)dropDownThresholdPad_27;
- (id)campaignStateDidChangeBlock;
- (void)setLableImageView:;
- (void)setFakeNaviImageView:;
- (void)setReleaseTip:;
- (void)setCampaignBtn:;
- (void)setDropDownThresholdPad_12:;
- (void)setDropDownThresholdPad_27:;
- (void)setDropDownThresholdPad_45:;
- (id)backButton;
- (id)titleView;
- (void)setTitleView:;
- (void)dealloc;
- (void)viewDidLoad;
- (void)setBackButton:;
- (id)containerView;
- (void)setContainerView:;
- (void).cxx_destruct;
- (id)backgroundImageView;
- (double)lastOffset;
- (void)setLastOffset:;
- (void)setBackgroundImageView:;
@end
