@interface AWEIMTaskConversationCardModel : AWEBaseApiModel
@property (nonatomic) NSString sourceName;
@property (nonatomic) NSString attentionContent;
@property (nonatomic) NSString content;
@property (nonatomic) q updateTime;
@property (nonatomic) NSString convTitle;
@property (nonatomic) NSString convIcon;
@property (nonatomic) NSString convId;
@property (nonatomic) q unreadCount;
@property (nonatomic) NSString jumpSchema;
@property (nonatomic) q sourceType;
@property (nonatomic) NSString hintContent;
@property (nonatomic) BOOL mute;
@property (nonatomic) BOOL unreadDemotion;
@property (nonatomic) BOOL noCutIcon;
- (id)jumpSchema;
- (id)convId;
- (void)setConvId:;
- (id)hintContent;
- (void)setJumpSchema:;
- (void)setHintContent:;
- (id)attentionContent;
- (void)setAttentionContent:;
- (id)convTitle;
- (void)setConvTitle:;
- (id)convIcon;
- (void)setConvIcon:;
- (BOOL)unreadDemotion;
- (void)setUnreadDemotion:;
- (BOOL)noCutIcon;
- (void)setNoCutIcon:;
- (void)setSourceName:;
- (long long)unreadCount;
- (void)setSourceType:;
- (long long)sourceType;
- (BOOL)mute;
- (id)sourceName;
- (id)content;
- (void)setUnreadCount:;
- (void)setMute:;
- (long long)updateTime;
- (void)setContent:;
- (void).cxx_destruct;
- (void)setUpdateTime:;
+ (id)JSONKeyPathsByPropertyKey;
@end
