@interface AWEIMCommentViewController : UIViewController
@property (nonatomic) UIView topSafeTipView;
@property (nonatomic) UITableView tableView;
@property (nonatomic) AWEIMNotificationListDataController dataController;
@property (nonatomic) AWENoticeInteractionListControllerViewModel viewModel;
@property (nonatomic) AWEIMCommentFilterController dataFilterManager;
@property (nonatomic) double statusBarHeight;
@property (nonatomic) NSSet lastVisibleChatSet;
@property (nonatomic) NSString ruleId;
@property (nonatomic) AWEUITextLoadingView loadingView;
@property (nonatomic) BOOL hasDeletedPushNotice;
@property (nonatomic) BOOL hasTrackedPushTipsShow;
@property (nonatomic) UIView searchContainerView;
@property (nonatomic) UIView searchMusicContainerView;
@property (nonatomic) MASConstraint commentSearchShow;
@property (nonatomic) MASConstraint commentSearchHide;
@property (nonatomic) MASConstraint commentMusicSearchShow;
@property (nonatomic) MASConstraint commentMusicSearchHide;
@property (nonatomic) BOOL dataSourceChanging;
@property (nonatomic) BOOL hasChangedSelector;
@property (nonatomic) <AWECommentInputViewManagerProtocol> commentInputViewManager;
@property (nonatomic) <AWECommentInputViewManagerProtocol> productCommentInputViewManager;
@property (nonatomic) <AWECommentInputViewContextProtocol> commentContext;
@property (nonatomic) double enterTextStartTimestamp;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) AWECommentModel commentModel;
@property (nonatomic) q commentCount;
@property (nonatomic) NSMutableSet shouldShowLightInteractionButtonNoticeModelIDSet;
@property (nonatomic) BOOL isWillDisappearing;
@property (nonatomic) BOOL isDidDisappearing;
@property (nonatomic) BOOL initRefreshHasFinished;
@property (nonatomic) NSMutableSet relationTrackSet;
@property (nonatomic) NSMutableSet localReadedNoticeIDsSet;
@property (nonatomic) BOOL needClearLocalReadedNoticeIDsSetAfterRefreshFetch;
@property (nonatomic) BOOL isReplyToComment;
@property (nonatomic) BOOL needShowNavigationBar;
@property (nonatomic) BOOL isLoadCache;
@property (nonatomic) AWEInteractNoticeConfigManager noticeConfigManager;
@property (nonatomic) NSMutableArray candidateDataSource;
@property (nonatomic) BOOL isSwitchTab;
@property (nonatomic) AWEIMInteractNoticeBubbleView unreadBubble;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) <AWEIMNoticeSlidingChildControllerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeModel;
- (id)referString;
- (id)aweui_emptyPageConfigForState:;
- (void)aweui_emptyPagePrimaryButtonTapped:;
- (id)aweui_emptyPageEdgeInsets;
- (void)didFinishFollowUser:status:error:;
- (void)didFinishUnFollowUser:status:error:;
- (void)didFinishBlockUser:status:;
- (void)didFinishSetRemarkWithUser:;
- (void)setEnterFrom:;
- (BOOL)configWithRouterParamDict:;
- (id)enterFrom;
- (id)commentModel;
- (void)setCommentModel:;
- (id)aweui_emptyPageBelowView;
- (void)setDataController:;
- (void)coverTappedWithOptions:;
- (void)presentEmoticonBoardAndScrollToVmoticonTab;
- (void)resetUnreadCount;
- (void)showInputViewWithOptions:enterMethod:;
- (BOOL)shouldShowLightInteractionButtonWithOptions:;
- (BOOL)shouldShowQuickReplyButtonWithOptions:;
- (void)showQuickReplyViewWithOptions:;
- (void)sendLightInteractionWithOptions:;
- (void)avatarTappedWithOptions:;
- (id)lightInteractionButtonIconUrl;
- (void)followStatusChanged:atIndexPath:;
- (void)nicknameTappedWithOptions:;
- (void)addLocalReadedNoticeID:;
- (void)interactionNoticePageBeginRefreshData;
- (void)trackFirstCommentGuideShow;
- (void)trackFirstCommentGuideClick:;
- (void)_endRefreshing;
- (void)backBtnClicked:;
- (BOOL)cellShowFullScreen;
- (id)commentContext;
- (void)setCommentContext:;
- (id)commentInputViewManager;
- (BOOL)isSwitchTab;
- (void)setIsSwitchTab:;
- (id)searchContainerView;
- (void)setSearchContainerView:;
- (id)commentSearchHide;
- (void)setCommentSearchHide:;
- (double)enterTextStartTimestamp;
- (void)setEnterTextStartTimestamp:;
- (void)_showEmptyView;
- (void)p_trackInnerMessageNotification;
- (void)setNoticeConfigManager:;
- (id)noticeConfigManager;
- (void)handleDataSourceIfNeed;
- (void)setCandidateDataSource:;
- (void)setIsWillDisappearing:;
- (void)setIsDidDisappearing:;
- (id)shouldShowLightInteractionButtonNoticeModelIDSet;
- (id)unreadBubble;
- (BOOL)needClearLocalReadedNoticeIDsSetAfterRefreshFetch;
- (id)localReadedNoticeIDsSet;
- (BOOL)initRefreshHasFinished;
- (void)setInitRefreshHasFinished:;
- (void)setNeedClearLocalReadedNoticeIDsSetAfterRefreshFetch:;
- (id)candidateDataSource;
- (void)_loadMoreDataForFirstLoad:;
- (void)_updateLastVisibleSet;
- (double)navigationHeight;
- (void)setLastVisibleChatSet:;
- (void)configCellLongPressGestureIfNeeded:;
- (void)p_trackInteractionNotificationClickedWithIndexPath:;
- (id)lastVisibleChatSet;
- (BOOL)isWillDisappearing;
- (BOOL)isDidDisappearing;
- (id)relationTrackSet;
- (id)swipeActionsWithClassType:indexPath:tableView:;
- (void)p_trackSlideCellAtIndexPath:;
- (void)p_showSendMessageSuccessToastForUser:;
- (void)trackAndTransToProfileWithOptions:enterMethod:enterPosition:;
- (void)p_showQuickReplyViewWithOptions:replyModel:panelLevel:needReplyModel:;
- (void)p_sendLightInteractionMessageWithOptions:avatarView:containerView:enterMethod:noticeDefault:panelLevel:;
- (BOOL)p_shouldShowInteractionButtonWithOptions:;
- (void)p_updateUserStatus:status:isBlock:;
- (void)p_updateCellNameLabel:user:;
- (void)afterDeleteNoticeAutoLoadMoreIfNeeded;
- (void)innerTrackEvent:params:;
- (BOOL)hasDeletedPushNotice;
- (void)setHasDeletedPushNotice:;
- (BOOL)hasTrackedPushTipsShow;
- (void)setHasTrackedPushTipsShow:;
- (void)setShouldShowLightInteractionButtonNoticeModelIDSet:;
- (void)setRelationTrackSet:;
- (void)setLocalReadedNoticeIDsSet:;
- (void)setUnreadBubble:;
- (void)slideVCRefreshListData;
- (id)topSafeTipView;
- (void)setTopSafeTipView:;
- (void)commentNoMoreNoticeNotification:;
- (void)p_setupGroups;
- (void)refreshDataWithLoadingView:;
- (BOOL)isLoadCache;
- (void)setIsLoadCache:;
- (void)setHasChangedSelector:;
- (void)refreshDataWithLoadingView:byPullDown:;
- (BOOL)dataSourceChanging;
- (void)setDataSourceChanging:;
- (BOOL)hasChangedSelector;
- (id)p_titleText;
- (id)p_informativeText;
- (void)p_trackerInnerMessageWithAction:indexPath:noticeType:;
- (void)onVisitComment:;
- (void)onVisitForward:;
- (void)setIsReplyToComment:;
- (id)productCommentInputViewManager;
- (void)onVisitPolymericCommentList:;
- (void)handleLongVideoClick:;
- (void)trackPostReplyComment;
- (void)setProductCommentInputViewManager:;
- (id)searchMusicContainerView;
- (void)setSearchMusicContainerView:;
- (id)commentSearchShow;
- (void)setCommentSearchShow:;
- (id)commentMusicSearchShow;
- (void)setCommentMusicSearchShow:;
- (id)commentMusicSearchHide;
- (void)setCommentMusicSearchHide:;
- (BOOL)isReplyToComment;
- (void)setNeedShowNavigationBar:;
- (void)__showTopSafeTipViewIfNeeded;
- (id)dataFilterManager;
- (void)setDataFilterManager:;
- (void)p_dataFilterManagerSelectHandler;
- (void)updateDataControllerUnreadCount;
- (void)_dismissEmptyView;
- (id)noticeTypeForModel:;
- (id)noticeTypeForCell:;
- (id)p_accountTypeForTrackerWithModel:;
- (void)handleCellClicked:isFromCover:;
- (void)setupNavigationBarAndDataController;
- (BOOL)needShowNavigationBar;
- (void)p_showPopoverWithOptions:targetView:avatarView:containerView:replyMode:enterMethod:;
- (BOOL)isCommentPolymericGroup:;
- (void)setCommentInputViewManager:;
- (void)setModel:;
- (BOOL)prefersStatusBarHidden;
- (void)viewWillDisappear:;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (id)filterView;
- (id)init;
- (void)dealloc;
- (id)delegate;
- (long long)numberOfSectionsInTableView:;
- (void)viewWillLayoutSubviews;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)tableView;
- (id)loadingView;
- (void)setStatusBarHeight:;
- (void)viewDidDisappear:;
- (id)model;
- (void)scrollViewWillBeginDragging:;
- (void)viewWillAppear:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (double)tableView:heightForRowAtIndexPath:;
- (void)viewDidAppear:;
- (void)setDelegate:;
- (id)tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:;
- (double)statusBarHeight;
- (BOOL)tableView:canEditRowAtIndexPath:;
- (void)tableView:didEndEditingRowAtIndexPath:;
- (id)tableView:editActionsForRowAtIndexPath:;
- (long long)tableView:editingStyleForRowAtIndexPath:;
- (void)tableView:willBeginEditingRowAtIndexPath:;
- (long long)commentCount;
- (id)dataController;
- (void)setCommentCount:;
- (double)footerInset;
- (void)_setupUI;
- (id)ruleId;
- (void)setRuleId:;
@end
