@interface AWEIMGroupSPConversationTask : NSObject
@property (nonatomic) NSString conversationShortID;
@property (nonatomic) NSString taskID;
@property (nonatomic) q taskType;
@property (nonatomic) NSString taskName;
@property (nonatomic) NSString taskIcon;
@property (nonatomic) q availableTime;
@property (nonatomic) q expiredTime;
@property (nonatomic) q currentProgress;
@property (nonatomic) q totalProgress;
@property (nonatomic) BOOL isForbidden;
@property (nonatomic) q taskVersion;
@property (nonatomic) q taskStatus;
@property (nonatomic) q taskStatusVersion;
@property (nonatomic) q taskUserStatus;
@property (nonatomic) q taskUserStatusVersion;
@property (nonatomic) NSDictionary localExt;
@property (nonatomic) NSNumber exposeTimeForHot;
@property (nonatomic) NSNumber exposeTimeForNew;
@property (nonatomic) BOOL hasClick;
@property (nonatomic) NSDictionary dynamicExt;
@property (nonatomic) NSDictionary userDynamicExt;
@property (nonatomic) NSDictionary solidExt;
@property (nonatomic) NSString actionSchema;
- (id)trackParams;
- (id)localExt;
- (id)conversationShortID;
- (long long)expiredTime;
- (id)actionSchema;
- (long long)taskVersion;
- (BOOL)isForbidden;
- (BOOL)hasClick;
- (void)setHasClick:;
- (id)rewardSchema;
- (long long)rewardSchemaTimestamp;
- (id)rainID;
- (BOOL)isInValidTime;
- (id)decoratedRewardSchema:;
- (long long)timeStatus;
- (id)taskIcon;
- (long long)availableTime;
- (long long)taskStatusVersion;
- (long long)taskUserStatus;
- (long long)taskUserStatusVersion;
- (id)exposeTimeForHot;
- (void)setExposeTimeForHot:;
- (id)exposeTimeForNew;
- (void)setExposeTimeForNew:;
- (id)dynamicExt;
- (id)userDynamicExt;
- (id)solidExt;
- (long long)taskType;
- (long long)totalProgress;
- (long long)currentProgress;
- (id)taskName;
- (void).cxx_destruct;
- (id)taskID;
- (long long)taskStatus;
@end
