@interface AWEIMMixPhotoInitiatePageSheetCollectionViewCell : UICollectionViewCell
@property (nonatomic) UIImageView backgroundImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIVisualEffectView subtitleBackgroundView;
@property (nonatomic) UILabel subtitleLabel;
@property (nonatomic) CAGradientLayer maskViewGradientLayer;
@property (nonatomic) UIView bgMaskView;
@property (nonatomic) UIView selectView;
@property (nonatomic) UIImageView transferOtherAppImageView;
@property (nonatomic) UIVisualEffectView aiTagLabelBackgroundView;
@property (nonatomic) UILabel aiTagLabel;
@property (nonatomic) UIImageView aiTagImageView;
@property (nonatomic) <AWEIMMixPhotoInitiatePageSheetCollectionViewCellDelegate> delegate;
- (void)setSelectView:;
- (id)selectView;
- (id)bgMaskView;
- (void)setBgMaskView:;
- (void)p_createComponents;
- (void)renderWithViewModel:;
- (void)p_layoutComponents;
- (void)p_configComponents;
- (id)subtitleBackgroundView;
- (id)transferOtherAppImageView;
- (void)setAITagHiden:;
- (id)maskViewGradientLayer;
- (id)aiTagLabelBackgroundView;
- (id)aiTagImageView;
- (id)aiTagLabel;
- (void)setSubtitleBackgroundView:;
- (void)setMaskViewGradientLayer:;
- (void)setTransferOtherAppImageView:;
- (void)setAiTagLabelBackgroundView:;
- (void)setAiTagLabel:;
- (void)setAiTagImageView:;
- (id)delegate;
- (id)initWithFrame:;
- (void)setSubtitleLabel:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (void)layoutSubviews;
- (id)subtitleLabel;
- (id)backgroundImageView;
- (void)setBackgroundImageView:;
+ (id)identifier;
@end
