@interface AWEIMLifeServiceChatMenuEditPagePreviewViewContoller : UIViewController
@property (nonatomic) AWEIMLifeServiceChatMenuEditPageViewModel viewModel;
@property (nonatomic) AWEIMLifeServiceChatMenuView menuView;
@property (nonatomic) UIView containerView;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) UIView shadowBackgroundView;
@property (nonatomic) UIView containerNaviView;
@property (nonatomic) UIView containerAvatar;
@property (nonatomic) UIView containerTitleView;
@property (nonatomic) UIView containerSubtitleView;
@property (nonatomic) UIImageView leftArrowView;
@property (nonatomic) UIImageView moreButtonView;
@property (nonatomic) UIImageView audioImageView;
@property (nonatomic) UIImageView videoImageView;
@property (nonatomic) double tranformScale;
- (void)awe_themeReload;
- (id)moreButtonView;
- (void)setMoreButtonView:;
- (id)videoImageView;
- (void)setVideoImageView:;
- (void)__backBtnClicked;
- (void)__updateGradientLayerWiththemeStyle:;
- (id)shadowBackgroundView;
- (void)setContainerNaviView:;
- (id)containerNaviView;
- (id)leftArrowView;
- (id)containerAvatar;
- (id)containerTitleView;
- (id)containerSubtitleView;
- (id)audioImageView;
- (void)setTranformScale:;
- (double)tranformScale;
- (void)__setupContainerShadow:;
- (void)setShadowBackgroundView:;
- (void)setContainerAvatar:;
- (void)setContainerTitleView:;
- (void)setContainerSubtitleView:;
- (void)setLeftArrowView:;
- (void)setAudioImageView:;
- (id)initWithViewModel:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)containerView;
- (void)setContainerView:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (id)gradientLayer;
- (id)menuView;
- (void)setGradientLayer:;
- (void)setMenuView:;
@end
