@interface AWEIMSendAttachmentContext : NSObject
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) NSMutableArray dbModelArray;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) NSMutableArray dbModelArray;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) NSMutableArray dbModelArray;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) @? coverRefreshCompletionBlock;
@property (nonatomic) NSNumber didRefreshCoverFinish;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) BOOL needTranscodeAndUploadSpecialTrack;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) BOOL needTranscodeAndUploadSpecialTrack;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) AWEIMMessageAttachmentUploadDataModel dataModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString conversationID;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEIMSendMessageAttachmentObject sendObj;
@property (nonatomic) BOOL needTranscodeAndUploadSpecialTrack;
- (void)setDbModelArray:;
- (void)setDbModelArray:;
- (void)setDbModelArray:;
- (id)dbModelArray;
- (id)dbModelArray;
- (id)dbModelArray;
- (id)sendObj;
- (void)setSendObj:;
- (void)setCoverRefreshCompletionBlock:;
- (void)setDidRefreshCoverFinish:;
- (id)coverRefreshCompletionBlock;
- (id)didRefreshCoverFinish;
- (BOOL)needTranscodeAndUploadSpecialTrack;
- (void)setNeedTranscodeAndUploadSpecialTrack:;
- (id)conversationID;
- (void).cxx_destruct;
- (id)dataModel;
- (id)dataModel;
- (id)dataModel;
- (id)dataModel;
- (id)dataModel;
- (id)dataModel;
- (id)dataModel;
- (void)setDataModel:;
- (void)setDataModel:;
- (void)setDataModel:;
- (void)setDataModel:;
- (void)setDataModel:;
- (void)setDataModel:;
- (void)setDataModel:;
@end
