@interface AWEIMFileAttachmentDownloaderDownloadingContext : AWEIMFileAttachmentDownloaderContext
@property (nonatomic) <AWEIMFileAttachmentConfigProtocol> configProtocol;
@property (nonatomic) NSString remoteURL;
@property (nonatomic) NSString targetPath;
@property (nonatomic) NSURL filePath;
@property (nonatomic) NSString secretKey;
@property (nonatomic) BOOL chunkSecreted;
@property (nonatomic) NSString key;
@property (nonatomic) AWEIMMessageAttachmentDBModel dbModel;
@property (nonatomic) AWEIMResourceURLModel resModel;
@property (nonatomic) NSString subType;
@property (nonatomic) NSString uniqueID;
@property (nonatomic) NSString bizLineTag;
@property (nonatomic) @? progressBlock;
@property (nonatomic) @? completeBlock;
- (void)setTargetPath:;
- (void)setCompleteBlock:;
- (id)completeBlock;
- (id)resModel;
- (void)setResModel:;
- (void)setChunkSecreted:;
- (void)setBizLineTag:;
- (BOOL)chunkSecreted;
- (id)bizLineTag;
- (id)configProtocol;
- (void)setConfigProtocol:;
- (id)dbModel;
- (void)setDbModel:;
- (id)progressBlock;
- (id)filePath;
- (id)remoteURL;
- (void)setKey:;
- (void)setSecretKey:;
- (id)uniqueID;
- (id)key;
- (void)setUniqueID:;
- (void)setProgressBlock:;
- (id)subType;
- (void)setFilePath:;
- (id)secretKey;
- (void).cxx_destruct;
- (void)setSubType:;
- (void)setRemoteURL:;
- (id)targetPath;
@end
