@interface AWEIMOnlineContactAvatarViewModel : NSObject
@property (nonatomic) NSString identifier;
@property (nonatomic) Q vmType;
@property (nonatomic) AWEIMFriendInfoDataModel friendInfoModel;
@property (nonatomic) AWEIMSkylightVirtualAvatarHost virtualAvatarHostModel;
@property (nonatomic) UIImage image;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) BOOL hasEverPressed;
@property (nonatomic) BOOL canShowRedDot;
@property (nonatomic) NSString pageIdentifier;
@property (nonatomic) <AFDMomentColorRingInfoProtocol> momentColorRingInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (unsigned long long)vmType;
- (void)setVmType:;
- (BOOL)hasEverPressed;
- (void)setHasEverPressed:;
- (BOOL)canShowRedDot;
- (id)momentColorRingInfo;
- (void)setMomentColorRingInfo:;
- (id)friendInfoModel;
- (id)preferredSubtitle;
- (void)configMomentColorRingInfoWithDict:;
- (void)setFriendInfoModel:;
- (id)virtualAvatarHostModel;
- (void)setVirtualAvatarHostModel:;
- (unsigned long long)hash;
- (id)image;
- (void)setIdentifier:;
- (id)subtitle;
- (void)setImage:;
- (void)setSubtitle:;
- (id)identifier;
- (void).cxx_destruct;
- (id)title;
- (BOOL)isEqual:;
- (void)setTitle:;
- (id)pageIdentifier;
- (void)setPageIdentifier:;
+ (id)subtitleDictionary;
+ (id)viewModelWithIdentifier:;
@end
