@interface AWEIMAudioEmojiModel : MTLModel
@property (nonatomic) q identifier;
@property (nonatomic) NSString emojiName;
@property (nonatomic) NSString audioUrl;
@property (nonatomic) NSString audioMd5;
@property (nonatomic) NSString audioFileType;
@property (nonatomic) NSString staticEmojiUrl;
@property (nonatomic) NSString staticEmojiType;
@property (nonatomic) NSInteger width;
@property (nonatomic) NSInteger height;
@property (nonatomic) NSInteger duration;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)audioUrl;
- (void)setAudioUrl:;
- (id)emojiName;
- (void)setEmojiName:;
- (id)audioMd5;
- (void)setAudioMd5:;
- (id)staticEmojiUrl;
- (void)setStaticEmojiUrl:;
- (id)staticEmojiType;
- (void)setStaticEmojiType:;
- (void)setHeight:;
- (void)setIdentifier:;
- (void)setWidth:;
- (void)setDuration:;
- (long long)identifier;
- (void)setAudioFileType:;
- (int)width;
- (void).cxx_destruct;
- (int)duration;
- (int)height;
- (id)audioFileType;
+ (id)modelCustomPropertyMapper;
+ (id)JSONKeyPathsByPropertyKey;
@end
