@interface AWEIMGiphyReplyComponent : AWEIMComponentBase
@property (nonatomic) AWEIMLatestKindOfMessageInConversationComponent latestGiphyComponent;
@property (nonatomic) q lastRequestPullIndex;
@property (nonatomic) q lastShowPullIndex;
@property (nonatomic) <IESIMHttpTask> preTask;
@property (nonatomic) NSString innerRequestID;
@property (nonatomic) AWEIMMessageConversation conversation;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) double itemHeight;
@property (nonatomic) double viewHeight;
@property (nonatomic) {UIEdgeInsets=dddd} insets;
@property (nonatomic) UIView contentView;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) NSMutableSet showedGiphyIDSet;
@property (nonatomic) NSString replyEmojiID;
@property (nonatomic) NSString searchLogID;
@property (nonatomic) AWEIMEmoticonCollectionListModel listModel;
@property (nonatomic) <AWEIMLightInteractionMessageReplyComponent> lightMsgReplyComponent;
@property (nonatomic) BOOL trackParamsOpt;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL showInFloatMode;
@property (nonatomic) @? continueBlock;
@property (nonatomic) @? removeBlock;
@property (nonatomic) BOOL invalid;
@property (nonatomic) Q priorityValue;
- (void)p_setupUI;
- (BOOL)shouldFailFloatGestureRecognizer:;
- (BOOL)showInFloatMode;
- (void)setShowInFloatMode:;
- (id)removeBlock;
- (void)setRemoveBlock:;
- (void)hideViewIfNeed;
- (void)showViewIfNeed;
- (id)shouldContinueForPriorityObject:;
- (id)shouldRemoveForPriorityObject:;
- (void)afterInitialComponentAllResolved:;
- (void)componentDidMounted:;
- (void)inputViewTypeDidChange:oldInputViewType:;
- (id)viewToDisplayInBottomContainer;
- (BOOL)canShowBarWhenInputTypeChangedTo:;
- (void)setViewHeight:;
- (id)searchLogID;
- (void)setSearchLogID:;
- (id)showedGiphyIDSet;
- (void)setShowedGiphyIDSet:;
- (void)demoteWithGlobalIndex:;
- (id)chatEnterFrom;
- (void)p_updateBackgroundColor;
- (void)messageListBackgroundImageDidUpdated:;
- (void)inputViewController:invoke_growingTextView:shouldChangeTextInRange:replacementText:;
- (void)inputViewController:didInsertEmoticonString:;
- (long long)lastRequestPullIndex;
- (id)latestGiphyComponent;
- (void)p_showGiphyReplySelectViewWithPriority:;
- (void)dismissIfNeeded;
- (id)preTask;
- (void)setReplyEmojiID:;
- (void)p_autoLayoutActionBarShow:animated:nestedAnimations:;
- (BOOL)p_isTargetGiphyWithMessage:;
- (id)lightMsgReplyComponent;
- (long long)lastShowPullIndex;
- (void)setLastShowPullIndex:;
- (void)p_preparePlaceholders;
- (void)setInnerRequestID:;
- (void)setLastRequestPullIndex:;
- (id)innerRequestID;
- (void)p_processWithRawData:hasVmoji:;
- (void)setPreTask:;
- (double)bizViewHeight;
- (void)showGiphyReplySelectView;
- (BOOL)canShowRelpyButton:;
- (void)searchGiphyViewWillShow;
- (void)setLatestGiphyComponent:;
- (BOOL)trackParamsOpt;
- (id)replyEmojiID;
- (void)p_trackEmoticonShowWithModel:indexPath:;
- (id)p_viewModelWithInteractiveEmoticonModel:;
- (id)p_viewModelWithEmoticonModel:placeholder:;
- (id)messageViewController;
- (void)swipeDismiss;
- (void)p_showGiphyReplySelectViewAnimated:nestedAnimations:;
- (void)setLightMsgReplyComponent:;
- (void)setTrackParamsOpt:;
- (id)insets;
- (id)collectionView;
- (BOOL)isShowing;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setInvalid:;
- (id)contentView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)setListModel:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (id)listModel;
- (void).cxx_destruct;
- (void)setContentView:;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (BOOL)invalid;
- (void)setInsets:;
- (id)conversation;
- (void)setConversation:;
- (double)viewHeight;
- (double)itemHeight;
- (id)continueBlock;
- (void)setContinueBlock:;
- (void)refreshData;
- (void)setIsShowing:;
- (void)setItemHeight:;
- (unsigned long long)priorityValue;
- (void)setPriorityValue:;
+ (BOOL)canCreateComponentWithContext:;
+ (id)sharedCache;
@end
