@interface AWEIMShareAndForwardPhotoVideoMixedImpl : NSObject
@property (nonatomic) AWEProgressLoadingView loadingView;
@property (nonatomic) AWEUILoadingView twoBallLoadingView;
@property (nonatomic) BOOL shouldShowShareListTips;
@property (nonatomic) BOOL shouldShowSendingToast;
@property (nonatomic) BOOL shouldShowSendingTwoBallLoading;
@property (nonatomic) BOOL shouldShowSendingDetailToast;
@property (nonatomic) BOOL editPageShare;
@property (nonatomic) BOOL createGroup;
@property (nonatomic) NSDictionary extraTrackParams;
@property (nonatomic) BOOL forbidToast;
@property (nonatomic) <IESIMShareContextProtocol> shareContext;
@property (nonatomic) AWEIMMessage forwardMessage;
@property (nonatomic) NSString accessoryText;
@property (nonatomic) NSString createGroupEnterFrom;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setShareContext:;
- (id)extraTrackInfo;
- (id)shareContext;
- (id)forwardMessage;
- (void)setForwardMessage:;
- (BOOL)createGroup;
- (BOOL)forbidToast;
- (void)setForbidToast:;
- (id)createGroupEnterFrom;
- (void)setCreateGroupEnterFrom:;
- (id)businessModelFromIMSetting;
- (void)saveBusinessModelToIMSetting;
- (void)clearBusinessModelFromIMSetting;
- (void)configShareBottomInputViewWithCoverImageView:;
- (void)configShareAlertTopView:withCoverImageView:contentLabel:;
- (id)shareMessage;
- (void)willShareToShareUserList:shareText:;
- (void)didShareToShareUserList:;
- (void)didSendAttachmentWithIndex:total:;
- (void)setCreateGroup:;
- (id)extraTrackParams;
- (void)setExtraTrackParams:;
- (void)p_dismissLoading;
- (void)setShouldShowShareListTips:;
- (void)setShouldShowSendingToast:;
- (void)setEditPageShare:;
- (void)setShouldShowSendingDetailToast:;
- (void)showCustomTipsAfterSendMessagesWithShareUserList:config:;
- (BOOL)shouldShowSendingTwoBallLoading;
- (id)twoBallLoadingView;
- (BOOL)shouldShowSendingToast;
- (BOOL)editPageShare;
- (BOOL)shouldShowShareListTips;
- (BOOL)shouldShowSendingDetailToast;
- (void)toastDetailInfoWithShareModels:;
- (void)setShouldShowSendingTwoBallLoading:;
- (void)setTwoBallLoadingView:;
- (id)init;
- (void)setAccessoryText:;
- (id)accessoryText;
- (void)setLoadingView:;
- (id)loadingView;
- (id)attachments;
- (void).cxx_destruct;
@end
