@interface AWEIMSafeRemindView : AWEIMBasePopupView
@property (nonatomic) UIImageView avatarImgView;
@property (nonatomic) YYLabel titleLabel;
@property (nonatomic) YYLabel contentLabel;
@property (nonatomic) UIStackView checkboxStackView;
@property (nonatomic) UIImageView selectImageView;
@property (nonatomic) UILabel actionTipLabel;
@property (nonatomic) NSTimer timer;
@property (nonatomic) NSMutableArray selectViewArray;
@property (nonatomic) AWEIMSecurityToastConfigModel toastConfig;
@property (nonatomic) UIPanGestureRecognizer pan;
@property (nonatomic) AVAudioPlayer player;
@property (nonatomic) UIView audioBackgroundView;
@property (nonatomic) CAGradientLayer audioBackgroundLayer;
@property (nonatomic) UIButton audioButton;
@property (nonatomic) UIView audioRedDot;
@property (nonatomic) <IESIMSafeRemindViewDelegateProtocol> innerNotificationListerner;
@property (nonatomic) <AWEIMSafeRemindViewDelegate> delegate;
@property (nonatomic) AWEIMMessageConversation conversation;
@property (nonatomic) double longestAudioPlayPercentage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)pauseAudio;
- (BOOL)configWithModel:;
- (void)setSelectImageView:;
- (id)selectImageView;
- (void)handleAudioSessionInterruptionNotification:;
- (id)actionTipLabel;
- (void)addSubviews;
- (id)avatarImgView;
- (void)setAvatarImgView:;
- (BOOL)bringToFront;
- (void)contentViewPanAction:;
- (id)colorInLightTheme:;
- (id)checkboxStackView;
- (double)__checkboxHeight;
- (void)onTapGes:;
- (void)setSelectViewArray:;
- (double)__contentBottom;
- (id)selectViewArray;
- (void)setCheckboxStackView:;
- (void)maskViewTapAction:;
- (void)p_closeAction;
- (BOOL)checkValid;
- (void)panAction:;
- (void)setLabel:withAttributedText:preferredMaxLayoutWidth:;
- (double)textHeightWithPreferredMaxLayoutWidth:AttributedText:;
- (id)toastConfig;
- (id)middleBodyAreaView;
- (void)configBottomView:configModel:;
- (void)setActionTipLabel:;
- (void)observeEvents;
- (void)unobserveEvents;
- (BOOL)p_showModel:onViewController:;
- (void)setToastConfig:;
- (void)__setupUITitle:subTitle:buttons:configModel:;
- (void)__configConfirmButtonModel:;
- (void)configCloseButtonWithModel:;
- (void)configHeaderPictureWithModel:;
- (void)configTitleWithAttributedTitle:;
- (void)configMiddleBodyAreaWithAttributedSubtitle:model:;
- (double)__titleTopMagin;
- (double)audioButtonWidth;
- (id)audioBackgroundView;
- (id)audioBackgroundLayer;
- (id)audioRedDot;
- (double)__titleAndContentMargin;
- (double)audioRedDotWidth;
- (double)__confirmButtonTop;
- (void)setupConfirmButtonWithTitle:enabledState:;
- (BOOL)__buttonEnableByCheckboxState;
- (void)__updateConfirmButtonEnable:;
- (void)__updateConfrimButtonColor;
- (BOOL)__checkboxHasSelected;
- (void)pressAudioBtn:;
- (void)setLongestAudioPlayPercentage:;
- (void)setInnerNotificationListerner:;
- (id)innerNotificationListerner;
- (double)longestAudioPlayPercentage;
- (BOOL)showModel:;
- (BOOL)showModel:onViewController:;
- (void)registerDelegate;
- (void)setAudioBackgroundView:;
- (void)setAudioBackgroundLayer:;
- (void)setAudioRedDot:;
- (void)setTimer:;
- (void)hide;
- (id)pan;
- (void)dealloc;
- (id)timer;
- (id)delegate;
- (id)initWithFrame:;
- (BOOL)hasAudio;
- (void)dismiss;
- (id)player;
- (void)setPlayer:;
- (void)setTitleLabel:;
- (void)willMoveToWindow:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (void)setPan:;
- (id)conversation;
- (void)setConversation:;
- (id)contentLabel;
- (void)setContentLabel:;
- (void)audioPlayerDidFinishPlaying:successfully:;
- (void)setAudioButton:;
- (id)audioButton;
- (BOOL)hasCheckbox;
- (void)appWillResignActive;
+ (BOOL)isShowing;
@end
