@interface AWEIMInputActionBarEntryItem : NSObject
@property (nonatomic) Q type;
@property (nonatomic) BOOL showTitleOnly;
@property (nonatomic) AWEIMEmoticonModel emoticonModel;
@property (nonatomic) AWEIMActionBarButtonConfig buttonConfig;
@property (nonatomic) AWEIMActionBarShowInfo resolvedShowInfo;
@property (nonatomic) NSValue cropValue;
@property (nonatomic) NSDictionary resolvedShowInfoResourceConfigs;
@property (nonatomic) BOOL voip2In1ShowAsVideoVoip;
@property (nonatomic) NSAttributedString emojiTextAttributedString;
@property (nonatomic) AWEIMMessage bindedMessage;
@property (nonatomic) NSValue itemSizeValue;
@property (nonatomic) NSValue attributedTitleSize;
@property (nonatomic) Q routerType;
@property (nonatomic) NSString iconName;
@property (nonatomic) NSString title;
@property (nonatomic) BOOL showIconOnly;
@property (nonatomic) BOOL doNotUseTintColor;
@property (nonatomic) BOOL shouldBeFirst;
@property (nonatomic) BOOL dismissAfterUse;
@property (nonatomic) Q aweType;
@property (nonatomic) NSMutableArray allValidShowInfos;
@property (nonatomic) NSMutableArray unusedValidShowInfos;
@property (nonatomic) BOOL shouldNotAllowClickFrequently;
@property (nonatomic) double lastClickTimestamp;
@property (nonatomic) double minClickTimeInterval;
- (id)emoticonModel;
- (void)setEmoticonModel:;
- (id)darkIconUrl;
- (id)lightIconUrl;
- (unsigned long long)aweType;
- (void)p_setup;
- (double)lastClickTimestamp;
- (void)setLastClickTimestamp:;
- (id)buttonConfig;
- (void)setButtonConfig:;
- (double)countDownTime;
- (void)setAweType:;
- (id)titleColorDark;
- (id)titleColorWithBackgroundImage;
- (id)titleColorDarkWithBackgroundImage;
- (id)backgroundColorWithBackgroundImage;
- (id)backgroundColorDarkWithBackgroundImage;
- (void)setEmojiTextAttributedString:;
- (id)emojiTextAttributedString;
- (BOOL)doNotUseTintColor;
- (id)cropValue;
- (id)itemSizeValue;
- (void)setItemSizeValue:;
- (id)resolvedShowInfo;
- (void)setAllValidShowInfos:;
- (void)setUnusedValidShowInfos:;
- (void)setResolvedShowInfo:;
- (id)unusedValidShowInfos;
- (void)setRouterType:;
- (void)setCropValue:;
- (void)setVoip2In1ShowAsVideoVoip:;
- (unsigned long long)routerType;
- (BOOL)needHideWhenCountDownEnd;
- (BOOL)isCountDownEnd;
- (BOOL)shouldBeFirst;
- (id)bindedMessage;
- (void)setAttributedTitleSize:;
- (BOOL)showTitleOnly;
- (id)resolvedShowInfoResourceConfigs;
- (void)setResolvedShowInfoResourceConfigs:;
- (BOOL)shouldNotAllowClickFrequently;
- (double)minClickTimeInterval;
- (BOOL)dismissAfterUse;
- (id)allValidShowInfos;
- (void)setMinClickTimeInterval:;
- (void)setDoNotUseTintColor:;
- (void)setShouldNotAllowClickFrequently:;
- (BOOL)voip2In1ShowAsVideoVoip;
- (BOOL)isEqualString:stringB:;
- (void)setBindedMessage:;
- (BOOL)isBusinessCustom;
- (void)setShowTitleOnly:;
- (void)setShouldBeFirst:;
- (void)setDismissAfterUse:;
- (id)attributedTitleSize;
- (id)titleColor;
- (id)init;
- (unsigned long long)hash;
- (id)statsType;
- (id)backgroundColorDark;
- (id)iconName;
- (unsigned long long)type;
- (id)backgroundColor;
- (void)setType:;
- (void).cxx_destruct;
- (id)title;
- (id)initWithType:;
- (BOOL)isEqual:;
- (void)setIconName:;
- (id)sortIdentifier;
- (void)setTitle:;
- (void)setShowIconOnly:;
- (BOOL)showIconOnly;
@end
