@interface AWEIMMessageListGalleryEntryComponent : AWEIMComponentBase
@property (nonatomic) AWEIMChatPanelModel plusPanelItem;
@property (nonatomic) AWEIMAssetGalleryPickerController galleryPickerController;
@property (nonatomic) AWEIMAssetGalleryPickerCustomConfig pickerCustomConfig;
@property (nonatomic) NSMutableArray preTranscodeVideoIDList;
@property (nonatomic) AWEIMPhotoPickerToolbarView toolbarViewInPicker;
@property (nonatomic) AWEIMNewPhotoPickerToolbarView toolbarViewV2InPicker;
@property (nonatomic) AWEIMExchangeAndSendImageActionBarView toolbarExchangeImageInPicker;
@property (nonatomic) AWEIMPhotoPickerToolbarViewV2 toolbarViewV3InPicker;
@property (nonatomic) AWEIMPhotoPickerToolbarView toolbarViewInPreview;
@property (nonatomic) AWEIMNewPhotoPickerToolbarView toolbarViewV2InPreview;
@property (nonatomic) AWEIMExchangeAndSendImageActionBarView toolbarExchangeImageInPreview;
@property (nonatomic) AWEIMPhotoPickerToolbarViewV2 toolbarViewV3InPreview;
@property (nonatomic) BOOL disableSendVideo;
@property (nonatomic) BOOL disableSendWatchOnce;
@property (nonatomic) BOOL supportExchangeImage;
@property (nonatomic) BOOL sendAsNormal;
@property (nonatomic) BOOL sendAsWatchOnce;
@property (nonatomic) BOOL sendAsExchange;
@property (nonatomic) double beginSendTimestamp;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)didUpdateFormatRoom:;
- (void)hostVC_viewDidLoad;
- (void)componentDidMounted:;
- (BOOL)canShowInPlusPanelWithContext:;
- (id)plusPanelItemModel;
- (BOOL)canShowDecidedBySettingsWithContext:;
- (void)didSendAssets:withExchangePublishType:;
- (void)p_onItemDidSelectedFromChatPanel;
- (id)plusPanelItem;
- (void)setPlusPanelItem:;
- (void)handlePhotoRecordFinishedNty:;
- (void)handleVideoRecordFinishedNty:;
- (id)pickerCustomConfig;
- (void)setDisableSendVideo:;
- (void)setPickerCustomConfig:;
- (BOOL)disableSendVideo;
- (BOOL)disableSendWatchOnce;
- (void)setDisableSendWatchOnce:;
- (BOOL)supportExchangeImage;
- (void)setSupportExchangeImage:;
- (void)setBeginSendTimestamp:;
- (double)beginSendTimestamp;
- (double)picker:bottomToolHeightWithConfig:;
- (void)picker:didOperateAsset:selected:totalCount:;
- (void)sendAssets:isSendWatchOnce:;
- (id)galleryPickerController;
- (void)setGalleryPickerController:;
- (void)dissmissEditPageWithSelectedCount:;
- (void)setPreTranscodeVideoIDList:;
- (void)previewButtonPressed:animated:;
- (id)toolbarViewV3InPicker;
- (void)sendButtonInPickerPressed:;
- (void)sendButtonInPreviewPressed:;
- (void)finishSelecting;
- (void)p_didSendAssets:isSendWatchOnce:;
- (id)toolbarExchangeImageInPicker;
- (id)toolbarViewV2InPicker;
- (id)toolbarViewInPicker;
- (id)toolbarViewV3InPreview;
- (id)toolbarExchangeImageInPreview;
- (id)toolbarViewV2InPreview;
- (id)toolbarViewInPreview;
- (id)preTranscodeVideoIDList;
- (BOOL)sendAsExchange;
- (void)p_didSendAssets:;
- (BOOL)sendAsWatchOnce;
- (BOOL)sendAsNormal;
- (void)trackSendBtnClickedWithCount:;
- (void)p_resetPickerState;
- (void)setToolbarViewV3InPicker:;
- (void)setToolbarViewV3InPreview:;
- (id)createToolbarExchangeImageWithSceneType:;
- (void)setToolbarExchangeImageInPicker:;
- (void)watchOnceSendButtonInPickerPressed:;
- (void)exchangeImageButtonInPickerPressed:;
- (void)setToolbarExchangeImageInPreview:;
- (void)watchOnceSendButtonInPreviewPressed:;
- (void)exchangeImageButtonInPreviewPressed:;
- (id)createToolbarViewV2;
- (void)setToolbarViewV2InPicker:;
- (void)setToolbarViewV2InPreview:;
- (id)createToolbarViewWithComponents:;
- (void)setToolbarViewInPicker:;
- (void)setToolbarViewInPreview:;
- (void)setSendAsNormal:;
- (void)setSendAsExchange:;
- (void)setSendAsWatchOnce:;
- (void)p_createUI;
- (void)p_presentPhotoGallery;
- (void)openPicker;
- (void)p_requestAuthorizationComplete:;
- (void)p_startImageUploadPreHeat;
- (id)p_filterExchangeMessageInvalidAssets:exchangeImageDataMap:exchangeImageSizeMap:;
- (id)picker:bottomToolViewWithConfig:;
- (id)preview:bottomToolViewWithConfig:;
- (double)preview:bottomToolHeightWithConfig:;
- (void)picker:allAssetLoadComplete:;
- (void)picker:singleAssetLoadComplete:;
- (void)picker:receiveEditResultWithPath:userInfo:associatedAsset:disableVideo:;
- (void)picker:selectOrigin:;
- (void)pickerDidCancelPickAsset:;
- (void)partOfselectAssetLoadResourceFaild:;
- (void)onPickerToolbar:didTappedWithActionType:;
- (id)animationControllerForPresentedController:presentingController:sourceController:;
- (void)dealloc;
- (id)animationControllerForDismissedController:;
- (void).cxx_destruct;
- (double)toolbarHeight;
- (void)editButtonPressed:;
+ (BOOL)canCreateComponentWithContext:;
@end
