@interface AWEIMMessageContentMaskProps : AWEIMUIViewPresenterProps
@property (nonatomic) UIImage mosaicImage;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) NSString iconName;
@property (nonatomic) NSArray urlArray;
@property (nonatomic) UIImage placeholderImage;
@property (nonatomic) <AWEIMImageProtocol> cachedPlaceholderKeyProvider;
@property (nonatomic) double roundCornerRatio;
@property (nonatomic) AWEIMImageTrackerConfig trackerConfig;
@property (nonatomic) NSString iconBackgroundName;
@property (nonatomic) BOOL showDefaultPlayIcon;
@property (nonatomic) double iconWidthHeight;
@property (nonatomic) double iconAndTitleSpacing;
@property (nonatomic) AWEIMMessage message;
@property (nonatomic) double imageRadius;
@property (nonatomic) BOOL needFold;
@property (nonatomic) BOOL iconBackgroundImageViewHidden;
@property (nonatomic) BOOL iconImageViewHidden;
@property (nonatomic) BOOL titleLabelHidden;
@property (nonatomic) BOOL subtitleLabelHidden;
@property (nonatomic) BOOL defaultPlayIconHidden;
@property (nonatomic) BOOL checkDiff;
- (BOOL)needFold;
- (void)setNeedFold:;
- (id)urlArray;
- (id)trackerConfig;
- (void)setTrackerConfig:;
- (void)setUrlArray:;
- (void)setIconWidthHeight:;
- (double)iconWidthHeight;
- (id)mosaicImage;
- (void)setRoundCornerRatio:;
- (void)setMosaicImage:;
- (void)setIconBackgroundName:;
- (id)iconBackgroundName;
- (id)cachedPlaceholderKeyProvider;
- (double)roundCornerRatio;
- (void)setCachedPlaceholderKeyProvider:;
- (double)imageRadius;
- (void)setImageRadius:;
- (void)setShowDefaultPlayIcon:;
- (void)setIconAndTitleSpacing:;
- (void)setCheckDiff:;
- (void)setIconBackgroundImageViewHidden:;
- (BOOL)showDefaultPlayIcon;
- (void)setIconImageViewHidden:;
- (void)setSubtitleLabelHidden:;
- (void)setDefaultPlayIconHidden:;
- (double)iconAndTitleSpacing;
- (BOOL)checkDiff;
- (BOOL)iconImageViewHidden;
- (BOOL)iconBackgroundImageViewHidden;
- (BOOL)subtitleLabelHidden;
- (BOOL)defaultPlayIconHidden;
- (id)placeholderImage;
- (void)setPlaceholderImage:;
- (id)message;
- (id)subtitle;
- (id)iconName;
- (void)setSubtitle:;
- (void).cxx_destruct;
- (id)title;
- (void)setMessage:;
- (void)setIconName:;
- (void)setTitle:;
- (void)setTitleLabelHidden:;
- (BOOL)titleLabelHidden;
@end
