@interface AWEIMNewGroupInviteCardViewController : UIViewController
@property (nonatomic) AWEIMNewGroupInviteCardView cardView;
@property (nonatomic) UIView<IESIMLoadingViewProtocol> loadingView;
@property (nonatomic) BOOL isAnimating;
@property (nonatomic) BOOL dontShowToast;
@property (nonatomic) NSString customizedButtonTitle;
@property (nonatomic) BOOL needTransferToGroup;
@property (nonatomic) NSNumber bizLine;
@property (nonatomic) NSString bizScene;
@property (nonatomic) q invokeChannel;
@property (nonatomic) BOOL isFirstShow;
@property (nonatomic) BOOL isConfigSuccess;
@property (nonatomic) BOOL viewIsAppear;
@property (nonatomic) AWEIMNewGroupInviteCardViewModel viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @? enterGroupBlock;
@property (nonatomic) @? joinGroupFailBlock;
@property (nonatomic) <AWEIMGroupChatPanelControllerDelegate> groupChatPanelDelegate;
@property (nonatomic) NSDictionary groupChatTrackDict;
- (BOOL)configWithRouterParamDict:;
- (BOOL)viewIsAppear;
- (void)setBizScene:;
- (id)bizLine;
- (id)bizScene;
- (void)setBizLine:;
- (long long)invokeChannel;
- (void)setInvokeChannel:;
- (void)setIsFirstShow:;
- (BOOL)isFirstShow;
- (void)handleKeyboardDidShowNotification:;
- (void)createViewModel:;
- (void)setupBinding;
- (void)setViewIsAppear:;
- (id)groupChatPanelDelegate;
- (BOOL)needTransferToGroup;
- (void)showGroupChatPanelOnViewController:;
- (void)setGroupChatPanelDelegate:;
- (id)groupChatTrackDict;
- (void)setGroupChatTrackDict:;
- (void)updateDismissTrackDict:;
- (id)enterGroupBlock;
- (void)setEnterGroupBlock:;
- (id)joinGroupFailBlock;
- (void)setJoinGroupFailBlock:;
- (BOOL)dontShowToast;
- (id)customizedButtonTitle;
- (void)setNeedTransferToGroup:;
- (void)setDontShowToast:;
- (void)setCustomizedButtonTitle:;
- (void)didTapConfirmBtn;
- (void)didTapGroupownerInfo;
- (void)didTapedCellFollowBtn:complition:;
- (void)didTapedCellJoinMembeBtn:complition:;
- (void)transferToSchema:dismiss:;
- (void)setupEnterGroupBlock;
- (void)p_trackGroupOpenCapabilityIfNeed:reason:;
- (void)setIsConfigSuccess:;
- (BOOL)isConfigSuccess;
- (void)__configNewGroupInviteCardConfirmBtnStyleWithStatusCode:;
- (void)p_enterGroupIfNeed;
- (id)setQuestionBtnText;
- (void)show;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (void)dealloc;
- (long long)numberOfSectionsInTableView:;
- (id)initWithModel:;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)loadingView;
- (void)dismiss;
- (void)viewDidDisappear:;
- (BOOL)isAnimating;
- (void)viewWillAppear:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (double)tableView:heightForRowAtIndexPath:;
- (void)setIsAnimating:;
- (void)viewDidAppear:;
- (void)setupUI;
- (id)cardView;
- (void)setCardView:;
- (void)dismissViewControllerWithCompletion:;
- (double)tableViewHeight;
@end
