@interface AWEInTodayAggregateConfig : MTLModel
@property (nonatomic) Q type;
@property (nonatomic) NSDate date;
@property (nonatomic) q pastType;
@property (nonatomic) NSString albumKey;
@property (nonatomic) NSString aggregatedDateRange;
@property (nonatomic) BOOL aggregateVideo;
@property (nonatomic) q maxVideoDuration;
@property (nonatomic) BOOL aggregateImage;
@property (nonatomic) BOOL sortCreateTime;
@property (nonatomic) q maxAssetsCount;
@property (nonatomic) BOOL ascending;
@property (nonatomic) q maxScanPhotoCount;
@property (nonatomic) BOOL isRefresh;
@property (nonatomic) NSArray tagWeightList;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (long long)maxVideoDuration;
- (id)tagWeightList;
- (void)setTagWeightList:;
- (void)setMaxVideoDuration:;
- (void)setPastType:;
- (id)aggregatedDateRange;
- (void)setAggregatedDateRange:;
- (BOOL)aggregateVideo;
- (void)setAggregateVideo:;
- (BOOL)aggregateImage;
- (void)setAggregateImage:;
- (BOOL)sortCreateTime;
- (void)setSortCreateTime:;
- (long long)maxAssetsCount;
- (void)setMaxAssetsCount:;
- (id)albumKey;
- (void)setAlbumKey:;
- (long long)maxScanPhotoCount;
- (void)setMaxScanPhotoCount:;
- (id)timePeriodRangeList;
- (id)timePeriodAlbumKey;
- (BOOL)ascending;
- (void)setDate:;
- (BOOL)isRefresh;
- (unsigned long long)type;
- (void)setType:;
- (void)setAscending:;
- (void).cxx_destruct;
- (id)date;
- (id)copyWithZone:;
- (void)setIsRefresh:;
- (long long)pastType;
+ (id)tagWeightListJSONTransformer;
+ (id)generateWithStrategyConfig:;
+ (id)JSONKeyPathsByPropertyKey;
@end
