@interface AWEIMIncentiveChatContent_group_plugin : AWEIMFlexComponent
@property (nonatomic) AWEIMMessageConversation conversation;
@property (nonatomic) AWEIMIncentiveChatMessage incentiveMessage;
@property (nonatomic) <AWEIMIncentiveChatService> incentiveService;
@property (nonatomic) AWEIMIncentiveChatChatRelation relation;
@property (nonatomic) Q computedStatus;
@property (nonatomic) <AWEUserService> userService;
@property (nonatomic) NSString currentLoginUserID;
@property (nonatomic) NSDictionary cardTextConfig;
@property (nonatomic) BOOL isApproving;
- (void)needUpdateDisplayWithContextOptions:;
- (void)componentDidMounted:;
- (void)cellWillDisplay:;
- (id)userService;
- (void)incentiveChatService:relationUpdateWithRelationID:conversationID:;
- (void)__createPresenter;
- (void)__trackCardClick;
- (id)__cardTypeForTrack;
- (void)__trackCardShow;
- (void)presenter:didUpdateWithView:;
- (id)incentiveService;
- (id)incentiveMessage;
- (unsigned long long)__inviteStatusWithRelation:;
- (unsigned long long)__approveStatusWithRelation:;
- (BOOL)__whetherBtnTapDoNothing;
- (BOOL)__whetherBtnIsCheckRules;
- (BOOL)__whetherSelfIsInRelation;
- (BOOL)__whetherBtnCanAccept;
- (BOOL)isApproving;
- (void)setIsApproving:;
- (void)__updateProps:withStatus:;
- (unsigned long long)computedStatus;
- (void)__updateBtnProps:withInteractionEnabled:isPrimary:;
- (id)cardTextConfig;
- (id)__configDictWithConfigKey:;
- (BOOL)__whetherBtnIsAccept;
- (BOOL)__whetherBtnIsAcceptToo;
- (BOOL)__whetherSelfStillHasQuota;
- (BOOL)__whetherRelationIsOngoing;
- (BOOL)__whetherRelationStillHasQuota;
- (BOOL)__whetherSelfIsInvitorOfTheRelation;
- (BOOL)__whetherAnyoneElseHasJoinedRelation;
- (id)__userPerspective;
- (id)__inviteCardStatusForTrack;
- (id)__inviteCardExpireReasonForTrack;
- (id)__isRelationExitForTrack;
- (id)__clickLocationForTrack;
- (void)dealloc;
- (id)relation;
- (id)conversation;
- (void)didTapButton;
- (id)currentLoginUserID;
+ (BOOL)canCreateComponentWithContext:;
@end
