@interface AWEIMMessageTabDesktopChannelGuideComponent : AWEIMComponentBase
@property (nonatomic) AWEDesktopSystemPopupGuideModel halfScreenAlertModel;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) @? onClose;
@property (nonatomic) <AWEIMMessageTabPopupViewInterface> messageTabPopupViewInterface;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)alertIDForEvent:;
- (long long)alertPriorityForEvent:;
- (BOOL)canShowWithContext:;
- (BOOL)shouldCancelAllOtherPendingAlertsWhenShowedWithContext:;
- (void)showWithCloseCallback:;
- (void)showDesktopChannelGuide:config:guideType:;
- (void)afterInitialComponentAllResolved:;
- (void)setMessageTabPopupViewInterface:;
- (BOOL)canShowPopupView;
- (id)messageTabPopupViewInterface;
- (void)showPopupView;
- (BOOL)isDisplayingCurrentPopupView;
- (id)halfScreenAlertModel;
- (void)setHalfScreenAlertModel:;
- (id)init;
- (BOOL)isShowing;
- (void)dealloc;
- (void).cxx_destruct;
- (void)setIsShowing:;
- (id)onClose;
- (void)setOnClose:;
@end
