@interface AWEIMCustomGiphyUploadHandler : NSObject
@property (nonatomic) UIImage image;
@property (nonatomic) PHAsset asset;
@property (nonatomic) @? completion;
@property (nonatomic) AWEIMNextGenerationUploadFileController uploader;
@property (nonatomic) AWEIMNetworkPerformanceTracker totalTracker;
@property (nonatomic) AWEIMCustomGiphyBatchUploadHandler uploadHandler;
@property (nonatomic) NSString enterScene;
@property (nonatomic) NSString chatType;
@property (nonatomic) NSString toUserID;
@property (nonatomic) NSString conversationID;
@property (nonatomic) NSDictionary bizTrackParams;
@property (nonatomic) NSDictionary convTrackParams;
- (id)toUserID;
- (void)setToUserID:;
- (id)chatType;
- (void)setChatType:;
- (id)uploader;
- (void)setUploader:;
- (id)bizTrackParams;
- (void)setBizTrackParams:;
- (id)enterScene;
- (void)setEnterScene:;
- (void)p_uploadEmoticonStatus:;
- (void)setTotalTracker:;
- (void)p_uploadFavoriteEmojiNew:withAddStatus:emojiID:;
- (void)setUploadHandler:;
- (void)p_createStickerWithParams:isGif:completion:;
- (void)successAddCustomSticker;
- (id)p_getAssetSize;
- (id)totalTracker;
- (id)convTrackParams;
- (void)uploadImage:preferredMD5:completion:;
- (id)p_caculateEmojiSize;
- (void)setConvTrackParams:;
- (id)uploadHandler;
- (id)image;
- (id)completion;
- (void)setImage:;
- (void)setCompletion:;
- (id)conversationID;
- (void).cxx_destruct;
- (void)setAsset:;
- (id)asset;
- (void)setConversationID:;
@end
