@interface AWEIMActiveUserDataCenter : NSObject
@property (nonatomic) NSMutableDictionary userAcquirerDictionary;
@property (nonatomic) NSMutableSet requestingSet;
@property (nonatomic) BOOL enableNetworkSourceObservers;
@property (nonatomic) NSMutableDictionary networkSourceObservers;
@property (nonatomic) NSObject<OS_dispatch_semaphore> lock;
@property (nonatomic) {_opaque_pthread_mutex_t=q[56c]} mutex;
@property (nonatomic) <AWEIMActiveUserUploader> activeUploader;
@property (nonatomic) YYMemoryCache activeCache;
@property (nonatomic) YYMemoryCache nonFriendActiveCache;
@property (nonatomic) YYMemoryCache groupMemberCache;
@property (nonatomic) BOOL revertChangesOnAccessForSyncingData;
@property (nonatomic) NSDictionary userAcquirerMap;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)didFinishLogoutWithUid:;
- (void)cacheDataWithInfos:groupConversationID:;
- (void)syncDataToAcquirersWithInfos:;
- (void)applicationDidEnterBackgroundNoti:;
- (void)setMutex:;
- (void)registNetworkCallback:forSource:;
- (id)activeCacheObjectForKey:;
- (void)setAcquirer:forKey:;
- (id)acquirerForKey:;
- (void)syncDataToAcquirersWithInfos:pageIdentifier:;
- (void)fetchUserActiveStatusWithSource:secUIDList:convIDList:context:completion:;
- (BOOL)revertChangesOnAccessForSyncingData;
- (void)applicationWillEnterForegroundNoti:;
- (void)p_removeCacheData;
- (id)activeUploader;
- (void)setActiveUploader:;
- (id)groupMemberCache;
- (id)nonFriendActiveCache;
- (BOOL)enableNetworkSourceObservers;
- (id)networkSourceObservers;
- (id)p_filterRequestKeysWithKeyList:context:;
- (id)requestingSet;
- (id)p_filterRequestKeysWithKeyList:;
- (void)enumSecUidList:convIdList:countPerGroup:usingBlock:;
- (void)p_processWithInfos:nonFriendInfos:groupConversationID:completion:;
- (void)fetchUserActiveStatusWithConversionID:completion:;
- (void)cacheDataWithInfos:nonFriendInfos:groupConversationID:;
- (void)syncDataToAcquirersWithInfos:nonFriendInfos:;
- (id)userAcquirerMap;
- (void)syncDataToAcquirersWithInfos:nonFriendInfos:pageIdentifier:;
- (void)fetchUserActiveStatusWithSource:secUIDList:convIDList:filterCache:context:completion:;
- (id)userAcquirerDictionary;
- (void)deleteActiveCacheObjectForKey:;
- (id)nonFriendActiveCacheObjectForKey:sourceType:;
- (void)deleteNonFriendActiveCacheObjectForKey:;
- (id)groupMemberCacheModelForKey:;
- (void)removeAcquirerForKey:;
- (void)setUserAcquirerMap:;
- (void)setUserAcquirerDictionary:;
- (void)setRequestingSet:;
- (void)setEnableNetworkSourceObservers:;
- (void)setNetworkSourceObservers:;
- (void)setNonFriendActiveCache:;
- (void)setGroupMemberCache:;
- (void)setRevertChangesOnAccessForSyncingData:;
- (id)init;
- (void)dealloc;
- (void)setLock:;
- (id)lock;
- (void)setActiveCache:;
- (id)activeCache;
- (void).cxx_destruct;
- (id)mutex;
+ (BOOL)enableActivityUserOpt;
+ (id)startIMAsyncConfig;
+ (void)setupUserActiveUploaderWithContext:;
+ (BOOL)checkEnableServerUploadActiveStatus;
+ (double)lastUploadActiveStatusTime;
+ (void)resetUploadTimerWithUpdateTime:context:;
+ (void)lockActiveUploader:;
+ (BOOL)isAvailableSpecificallyForNonFriendActiveWithSource:;
+ (BOOL)isAvailable;
+ (id)sharedInstance;
@end
