@interface AWEInTodayListViewController : UIViewController
@property (nonatomic) UIButton backButton;
@property (nonatomic) UIButton allSelectButton;
@property (nonatomic) UIView navBar;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) UIButton moreButton;
@property (nonatomic) UIButton selectButton;
@property (nonatomic) UILabel selectedCountLabel;
@property (nonatomic) UIButton cancelButton;
@property (nonatomic) NSMutableArray memoriesList;
@property (nonatomic) Q currentIndex;
@property (nonatomic) @? clickAction;
@property (nonatomic) @? publishAction;
@property (nonatomic) BOOL localAlbumHasShowed;
@property (nonatomic) NSObject<AWEMemoriesPlayerDataControllerProtocol> dataController;
@property (nonatomic) AWEMemoriesPlayerEmptyView emptyView;
@property (nonatomic) @? dismissHandler;
@property (nonatomic) BOOL isSelectedState;
@property (nonatomic) NSMutableArray selectedModels;
@property (nonatomic) UIView bottomBar;
@property (nonatomic) ACCButton publishButton;
@property (nonatomic) ACCButton publishDiaryButton;
@property (nonatomic) BOOL selectedStateFromPlayer;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) AWEInTodaySchemaData schemaData;
@property (nonatomic) AWEInTodayAggregateConfig aggregateConfig;
@property (nonatomic) @? shootAction;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)clickAction;
- (void)setDataController:;
- (void)setClickAction:;
- (void)backAction:;
- (void)showEmptyView;
- (id)publishButton;
- (void)setPublishButton:;
- (id)memoriesList;
- (void)bindObserve;
- (id)publishAction;
- (void)cancelButtonAction:;
- (id)selectedModels;
- (void)addCollectionView;
- (void)prepareSelected;
- (void)updateButtonState;
- (BOOL)isSelectedState;
- (void)addSelectedModel:;
- (void)trackClickItemWithModel:manual:;
- (id)publishDiaryButton;
- (void)addBackButton;
- (void)addMoreButton;
- (void)addSelectedCountLabel;
- (void)addSelectButton;
- (void)addBottomBar;
- (void)addAllSelectButton;
- (void)selectedCountChanged;
- (void)updateCollectionViewConstraints;
- (id)allSelectButton;
- (id)selectedCountLabel;
- (void)updateSelectedModelsWhenSourceChanged;
- (void)setMemoriesList:;
- (void)setIsSelectedState:;
- (void)dismissEmptyView;
- (id)getFilteredTypes;
- (id)shootAction;
- (void)setShootAction:;
- (BOOL)localAlbumHasShowed;
- (void)hideLocalAlbum;
- (void)showLocalAlbum;
- (void)refreshVisibleCells;
- (void)setSelectedStateFromPlayer:;
- (void)removeAllSelectedModels;
- (BOOL)hasSelectedAllModels;
- (void)addAllSelectedModels;
- (BOOL)selectedStateFromPlayer;
- (BOOL)beyondLimitedCount;
- (BOOL)didNotSelected;
- (void)updatePublishButton:selected:;
- (void)setLocalAlbumHasShowed:;
- (id)aggregateConfig;
- (BOOL)hasSelectedModel:;
- (unsigned long long)stateWithTileModel:;
- (void)removeSelectedModel:;
- (void)setSelectedModels:;
- (void)moreAction:;
- (void)allSelectButtonAction:;
- (void)publishButtonTtileConfig;
- (void)publishButtonAction:;
- (void)publishDiaryButtonAction:;
- (id)initWithDataController:currentIndex:isSelected:schemaData:aggregateConfig:clickAction:publishAction:shootAction:;
- (void)scrollTargetCellToCenterWithIndex:;
- (id)fetchTargetCellWithIndex:;
- (void)setTargetCellHidden:withIndex:;
- (void)isLoading:;
- (void)dismissHandler:;
- (long long)indexOfSelectedModel:;
- (void)setAllSelectButton:;
- (void)setSelectedCountLabel:;
- (void)setPublishAction:;
- (void)setPublishDiaryButton:;
- (void)setAggregateConfig:;
- (id)backButton;
- (long long)limitCount;
- (id)collectionView;
- (void)setDismissHandler:;
- (BOOL)isLoading;
- (void)setCancelButton:;
- (void)dealloc;
- (id)dismissHandler;
- (void)setCurrentIndex:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setBottomBar:;
- (void)viewDidLoad;
- (void)setBackButton:;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (id)moreButton;
- (void)collectionView:didSelectItemAtIndexPath:;
- (id)bottomBar;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:;
- (id)cancelButton;
- (void).cxx_destruct;
- (void)setMoreButton:;
- (long long)collectionView:numberOfItemsInSection:;
- (void)setIsLoading:;
- (unsigned long long)currentIndex;
- (void)setupUI;
- (id)emptyView;
- (void)setEmptyView:;
- (double)bottomBarHeight;
- (id)selectButton;
- (void)setSelectButton:;
- (void)setupFooter;
- (id)dataController;
- (void)addCancelButton;
- (void)selectButtonAction:;
- (id)navBar;
- (void)setNavBar:;
- (id)schemaData;
- (void)setSchemaData:;
+ (void)useAvatarIfNeed:;
+ (id)cellSize;
+ (double)cellSpacing;
@end
