@interface AWEIMB2CBottomFloatingAndPanelCellViewModel : NSObject
@property (nonatomic) Q scene;
@property (nonatomic) Q source;
@property (nonatomic) Q style;
@property (nonatomic) NSString title;
@property (nonatomic) AWEIMSmartAssistantSuggestMsg suggestMsg;
@property (nonatomic) AWEIMSmartAssistantRecommendQuickReply quickReply;
@property (nonatomic) NSString keyword;
@property (nonatomic) <AWEIMB2CBottomFloatingAndPanelCellViewModelDelegate> delegate;
@property (nonatomic) NSDictionary trackExt;
@property (nonatomic) NSString layerIconLight;
@property (nonatomic) NSString layerIconDark;
@property (nonatomic) NSString panelIconLight;
@property (nonatomic) NSString panelIconDark;
- (id)trackExt;
- (void)setTrackExt:;
- (id)suggestMsg;
- (id)layerIconDark;
- (id)layerIconLight;
- (id)panelIconDark;
- (id)panelIconLight;
- (double)heightOfCellForOpt;
- (double)heightOfCellForOld;
- (double)titleLabelPanelMaxWidth;
- (id)titleLabelPanelTextFont;
- (double)titleLabelMaxWidth;
- (id)titleLabelBottomTextFont;
- (double)panelTitleLabelMaxWidth;
- (double)heightOfCell;
- (double)titleLabelFloatInputMaxWidth;
- (void)didShowCell;
- (void)setSuggestMsg:;
- (void)setLayerIconLight:;
- (void)setLayerIconDark:;
- (void)setPanelIconLight:;
- (void)setPanelIconDark:;
- (void)setScene:;
- (id)delegate;
- (unsigned long long)scene;
- (void)encodeWithCoder:;
- (unsigned long long)style;
- (void)setQuickReply:;
- (void).cxx_destruct;
- (unsigned long long)source;
- (id)title;
- (void)setSource:;
- (void)setDelegate:;
- (void)setTitle:;
- (id)initWithCoder:;
- (void)setStyle:;
- (id)keyword;
- (void)setKeyword:;
- (void)didSelectCell;
- (id)quickReply;
+ (id)sizeForHeader;
+ (double)panelTitleLabelTopBottomPadding;
+ (double)panelTitleLabelTitileToIconPadding;
+ (double)panelTitleLabelLeftRightPadding;
+ (double)minimumLineSpacingForBottomView;
+ (double)lineTopHeight;
+ (double)minimumLineSpacingForPanelView;
+ (double)paddingForHeader;
+ (double)panelBottom;
+ (double)heightForBottomInteractor;
@end
