@interface AWEIMCardMessageAnchorInfo : NSObject
@property (nonatomic) NSArray anchorIDs;
@property (nonatomic) NSString customID;
@property (nonatomic) NSString musicID;
@property (nonatomic) q anchorType;
@property (nonatomic) NSArray icons;
@property (nonatomic) NSString title;
@property (nonatomic) NSString titleTag;
@property (nonatomic) NSString effectSocialData;
@property (nonatomic) BOOL isImageTemplateSticker;
@property (nonatomic) q POIIconType;
@property (nonatomic) AWEIMCardMessageCommerceAnchorInfo commerceAnchorInfo;
- (id)musicID;
- (id)titleTag;
- (void)setMusicID:;
- (id)initWithContentDict:;
- (void)setTitleTag:;
- (id)effectSocialData;
- (void)setEffectSocialData:;
- (BOOL)isImageTemplateSticker;
- (void)setIsImageTemplateSticker:;
- (id)customID;
- (id)getContentDict;
- (id)commerceAnchorInfo;
- (void)setCommerceAnchorInfo:;
- (id)anchorIDs;
- (void)setCustomID:;
- (long long)POIIconType;
- (void)setAnchorIDs:;
- (void)setPOIIconType:;
- (id)icons;
- (void)setIcons:;
- (void).cxx_destruct;
- (long long)anchorType;
- (id)title;
- (void)setTitle:;
- (id)copyWithZone:;
- (void)setAnchorType:;
@end
