@interface AWEInnerNotificationCenter : HTSService
@property (nonatomic) NSMutableArray internalPendingNotificationRequests;
@property (nonatomic) AWEInnerNotificationOperator currentDisplayNotificationOperator;
@property (nonatomic) <AWEInnerNotificationConflictHandler> conflictHandler;
@property (nonatomic) NSObject<OS_dispatch_semaphore> signal;
@property (nonatomic) AWEInnerNotificationSettings settings;
@property (nonatomic) <AWEInnerNotificationCenterBizProtocol> bizImpl;
@property (nonatomic) RxScheduler scheduler;
@property (nonatomic) RxScheduler waittingScheduler;
@property (nonatomic) q notificationIndex;
@property (nonatomic) NSMutableDictionary blockInfos;
@property (nonatomic) NSTimer blockValidateTimer;
@property (nonatomic) AWEInnerPushAlertManager alertManager;
@property (nonatomic) q forceAlertCount;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)onServiceInit;
- (id)currentDisplayNotification;
- (id)removeAllNotificationWithTypes:;
- (id)removeNotificationWithRequestIdentifier:;
- (id)modifyPendingNotificationRequestsWithTypes:modifyBlock:;
- (id)modifyPendingNotificationRequestsWithIdentifier:modifyBlock:;
- (id)blockDisplayBusinessesWithNotificationPriority:;
- (id)blockNotificationLessAndEqualPriority:business:validateBlockCondition:;
- (id)releaseNotificationBlockWithBusiness:;
- (id)removeAllNotificationController;
- (id)resumeNotifcationDisplayIfNeeded;
- (void)__trackEvent:params:;
- (id)blockValidateTimer;
- (BOOL)__shouldUsePopViewManager;
- (void)__handleEnterForegroundNotification:;
- (void)__handleDidBecomeActiveNotification:;
- (id)currentDisplayNotificationOperator;
- (void)setCurrentDisplayNotificationOperator:;
- (id)__showNotificationFromArrayIfNeededNotificationWrapper;
- (id)__showNotificationFromArrayIfNeeded:onlyForcedAlerts:;
- (BOOL)__hasPendingForceAlert;
- (id)internalPendingNotificationRequests;
- (id)__errorWithUserInfo:errorCode:;
- (void)__trackShowNotificationRequest:error:;
- (id)__isEnableDisplayNotificationWithRequest:onlyForcedAlerts:;
- (id)__showNotificationWithRequest:;
- (void)__removePendingRequest:;
- (id)__isBlockedWithRequest:;
- (id)__dismissCurrentNotification;
- (void)__trackShowNotificationRequest:error:extra:;
- (id)__findTheNextNotificationRequestForDisplay:;
- (id)__requestOperatePschedule:;
- (id)bizImpl;
- (id)__loopFindNotificationRequestIsEnableToDisplayAtIndex:onlyForcedAlerts:;
- (BOOL)__validateBlockCondition:;
- (BOOL)__isForceAlert:;
- (id)waittingScheduler;
- (void)__trackExceptionSchedule;
- (void)__validateCurrentBlockInfos;
- (void)setBlockValidateTimer:;
- (void)__releaseBlockValidateTimer;
- (id)__showNotificationFromArrayIfNeeded;
- (void)__removePendingRequestAtIndex:;
- (long long)forceAlertCount;
- (void)setForceAlertCount:;
- (id)__preAddNotificationRequest:;
- (long long)notificationIndex;
- (void)setNotificationIndex:;
- (void)__trackAddRequest:duration:;
- (id)__addNotificationRequest:;
- (void)__trackAddResultRequest:isNew:;
- (id)__pendingRequestsWithTypes:;
- (void)__removePendingRequests:;
- (id)__modifyPendingRequestWithRequestsProvider:modifyBlock:;
- (void)__trackValidateBlockConditionInvalid:;
- (void)__trackBlockPriority:business:;
- (void)__startBlockValidateTimerIfNeeded;
- (void)__trackReleaseBlockWithBusiness:;
- (void)__trackResumeNotificationDisplay;
- (void)notificationOperatorDidDismiss:reason:;
- (void)__trackNotificationRequestDismiss:reason:;
- (id)__highPriorityPushTypes;
- (id)__trackInfoWithRequest:;
- (id)__trackInfoWithError:;
- (void)showPush;
- (void)showForcePush:;
- (void)dismissCurrentPush;
- (void)__trackEnableDisplayCheckResult:request:;
- (void)setBizImpl:;
- (id)signal;
- (id)notificationController;
- (id)addNotificationRequest:;
- (void)dealloc;
- (id)settings;
- (id)alertManager;
- (id)pendingNotificationRequests;
- (id)scheduler;
- (void).cxx_destruct;
- (void)setAlertManager:;
- (id)conflictHandler;
- (id)blockInfos;
@end
