@interface AWELiveSmoothEnterRoomLivePlayerPreloader : NSObject
@property (nonatomic) BOOL enablePreload;
@property (nonatomic) double startTimeInterval;
@property (nonatomic) double preloadDuration;
@property (nonatomic) NSTimer preloaderTimer;
@property (nonatomic) Q tickCount;
@property (nonatomic) Q enterLiveRoomCount;
@property (nonatomic) AWELiveSmoothEnterRoomLivePlayerPreloaderOptions options;
@property (nonatomic) <IESLivePlayerProtocol> livePlayer;
@property (nonatomic) Q preloadStage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)enablePreload;
- (void)setEnablePreload:;
- (void)audienceQuitAllRoomWithSlideVC:player:context:;
- (id)obtainOptions;
- (void)mountLivePlayerPreloadeWithOptions:bizEnable:callTrace:;
- (void)unMountLivePlayerPreloaderWithCallTrace:;
- (void)removeTimerWithCallTrace:;
- (void)enqueuePlayerIfNeededWithCallTrace:targetRoomID:;
- (void)resetPreloaderEnv;
- (void)setPreloadDuration:;
- (void)setEnterLiveRoomCount:;
- (void)configInnerConfigWithSettings:;
- (void)unMountLivePlayerPreloaderWithCallTrace:needTrack:;
- (unsigned long long)preloadStage;
- (void)setPreloadStage:;
- (void)preloadLivePlayerAfterTickCount:;
- (void)setPreloaderTimer:;
- (double)preloadDuration;
- (void)checkNetWorkWithOptions:excecuteBlock:;
- (void)trackPreloaderUnmount:;
- (void)trackEnterRoomWithPlayerIsPreloaded:;
- (unsigned long long)enterLiveRoomCount;
- (id)preloaderTimer;
- (void)preparePlayerAndReloadStream;
- (void)trackPreloaderStart;
- (id)init;
- (void)dealloc;
- (void)setOptions:;
- (id)options;
- (void).cxx_destruct;
- (void)setStartTimeInterval:;
- (double)startTimeInterval;
- (void)setTickCount:;
- (unsigned long long)tickCount;
- (id)livePlayer;
- (void)setLivePlayer:;
@end
