@interface AWELandscapeFeedEntryView : UIView
@property (nonatomic) UIImageView backgroundImageView;
@property (nonatomic) UIView backgroundView;
@property (nonatomic) UIImageView iconImageView;
@property (nonatomic) UILabel contentLabel;
@property (nonatomic) BOOL isMonitoring;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) NSString referString;
@property (nonatomic) @? didUpdateHiddenBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)layoutSubviews;
- (void)setCenter:;
- (id)referString;
- (void)setReferString:;
- (id)didUpdateHiddenBlock;
- (void)setDidUpdateHiddenBlock:;
- (void)updateLayoutWithShowDesc:;
- (void)updateContentLabelAlpha:;
- (void)beginMonitor;
- (void)endMonitor;
- (void)updateUIForStyleFullScreen;
- (void)updatePadGuideTagStyle;
- (void)traceRotateScreen;
- (void)setModel:;
- (void)updateStyle;
- (id)init;
- (void)dealloc;
- (void)setBackgroundView:;
- (void)orientationChanged:;
- (id)backgroundView;
- (id)model;
- (BOOL)isMonitoring;
- (id)iconImageView;
- (void)setHidden:;
- (void).cxx_destruct;
- (void)reset;
- (id)backgroundImageView;
- (void)setIconImageView:;
- (id)contentLabel;
- (void)setContentLabel:;
- (void)setBackgroundImageView:;
- (void)setIsMonitoring:;
- (void)initUI;
@end
