@interface AWELeftSideBarTrackContext : NSObject
@property (nonatomic) NSString referString;
@property (nonatomic) NSString identification;
@property (nonatomic) NSString entranceStatus;
@property (nonatomic) NSString homepageHotScene;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSString awemeID;
@property (nonatomic) q openTimeStamp;
@property (nonatomic) NSString businessId;
@property (nonatomic) NSString schemaId;
@property (nonatomic) NSString captionBubbleComponentId;
@property (nonatomic) q lastLottieTime;
@property (nonatomic) q lastAnimateTime;
@property (nonatomic) q lastBadgeTime;
@property (nonatomic) q entryLastBadgeTime;
@property (nonatomic) NSString entryBadgeComponentID;
@property (nonatomic) NSDictionary bizTrackParams;
@property (nonatomic) NSDictionary exitBadgeTrackParams;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)setEnterMethod:;
- (void)setReferString:;
- (id)enterMethod;
- (void)setAwemeID:;
- (id)awemeID;
- (void)setIdentification:;
- (id)bizTrackParams;
- (void)setBizTrackParams:;
- (id)entranceStatus;
- (void)setEntranceStatus:;
- (id)homepageHotScene;
- (void)setHomepageHotScene:;
- (id)schemaId;
- (void)setSchemaId:;
- (long long)lastLottieTime;
- (void)setLastLottieTime:;
- (long long)lastAnimateTime;
- (void)setLastAnimateTime:;
- (long long)entryLastBadgeTime;
- (void)setLastBadgeTime:;
- (long long)lastBadgeTime;
- (id)entryBadgeComponentID;
- (void)setEntryBadgeComponentID:;
- (id)exitBadgeTrackParams;
- (void)setEntryLastBadgeTime:;
- (long long)openTimeStamp;
- (void)setOpenTimeStamp:;
- (void)setCaptionBubbleComponentId:;
- (void)setExitBadgeTrackParams:;
- (id)captionBubbleComponentId;
- (id)businessId;
- (void).cxx_destruct;
- (void)setBusinessId:;
- (id)identification;
@end
