@interface AWELiveUpdateInnerPushContent : NSObject
@property (nonatomic) AWELiveInnerPushContentModel model;
@property (nonatomic) <AWEIMStreakDisplayManagerProtocol> imStreakDisplayManager;
@property (nonatomic) NSDictionary extra;
@property (nonatomic) AWELiveInappPushView oldView;
@property (nonatomic) AWEInnerPushCommonView currentView;
@property (nonatomic) AWEInnerPushCommonViewModel viewModel;
@property (nonatomic) AWELiveUpdateInnerPushAvatarView customAvatarView;
@property (nonatomic) <AWEInnerNotificationContentOperator> notificationOperator;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setExtra:;
- (id)imStreakDisplayManager;
- (void)setImStreakDisplayManager:;
- (void)renderModel:context:;
- (id)customIMStreakTextPreferTheme;
- (id)customIMStreakTextFont;
- (void)handleTapAction;
- (id)mainContent;
- (id)notificationOperator;
- (void)viewDidDisappearWithReason:;
- (double)dismissTimerInterval;
- (BOOL)disableUseBusinessTypeDeterminDismissTimerInterval;
- (BOOL)tapGestureIsEnable:;
- (id)trackingModelForScene:;
- (BOOL)enableVibrateWhileViewDidAppear;
- (void)setNotificationOperator:;
- (void)updateLeftIcon;
- (void)updateRightActionAreaModel;
- (void)updateTitleAreaItems;
- (void)updateContentAttrString;
- (id)extTag;
- (id)prefixContent;
- (id)oldView;
- (void)setOldView:;
- (BOOL)enablePreview;
- (void)addQueryItems;
- (BOOL)enablePlayerReuseWhenEnterRoom;
- (id)customAvatarView;
- (BOOL)pushPlatformExperiment;
- (id)trackParamsWithPushModel:scene:;
- (void)setCustomAvatarView:;
- (void)setModel:;
- (id)businessType;
- (id)view;
- (id)viewModel;
- (id)extra;
- (id)model;
- (void)setViewModel:;
- (id)buttonText;
- (void).cxx_destruct;
- (id)title;
- (void)viewDidAppear;
- (id)avatar;
- (BOOL)hasAvatar;
- (void)updateProperties;
- (void)setCurrentView:;
- (id)currentView;
@end
