@interface AWELiveAcqCastVideoLikeController : UIViewController
@property (nonatomic) BOOL initialLoadMoreEnabled;
@property (nonatomic) AWELiveAcqCastVideoLikeDataManager dataManager;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) AWEFeedRefreshFooter footer;
@property (nonatomic) UICollectionViewFlowLayout layout;
@property (nonatomic) BOOL selecting;
@property (nonatomic) Q vcState;
@property (nonatomic) AWELiveAcqEmptyView emptyView;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) BOOL showFavoriteList;
@property (nonatomic) <AWEUserProfileTabVCDelegate> delegate;
@property (nonatomic) <AWELiveAcqCastVideoViewModelProtocol> viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setVcState:;
- (unsigned long long)vcState;
- (void)_refreshData;
- (void)_loadMoreData;
- (BOOL)initialLoadMoreEnabled;
- (void)setInitialLoadMoreEnabled:;
- (void)p_endRefreshingWithMore:list:error:;
- (id)aAWEPadRTVAdapter;
- (void)p_updateViewControllerState:;
- (BOOL)p_isCurrentUser;
- (BOOL)p_shouldUseFooterPlaceholderForState:;
- (BOOL)showFavoriteList;
- (void)setShowFavoriteList:;
- (id)collectionView:layout:referenceSizeForFooterInSection:;
- (void)reloadData;
- (id)collectionView:layout:referenceSizeForHeaderInSection:;
- (id)footer;
- (id)collectionView;
- (double)collectionView:layout:minimumLineSpacingForSectionAtIndex:;
- (void)dealloc;
- (id)dataManager;
- (double)collectionView:layout:minimumInteritemSpacingForSectionAtIndex:;
- (id)initWithViewModel:;
- (id)delegate;
- (void)setLayout:;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (id)collectionView:viewForSupplementaryElementOfKind:atIndexPath:;
- (id)collectionView:cellForItemAtIndexPath:;
- (id)layout;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (id)loadingView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)setDataManager:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)setDelegate:;
- (void)setFooter:;
- (BOOL)selecting;
- (void)setSelecting:;
- (id)emptyView;
- (void)setEmptyView:;
- (double)footerInset;
- (void)_setupUI;
+ (Class)aAWEPadRTVAdapterClass;
@end
