@interface AWELiveWorkViewController : UIViewController
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) NSString userID;
@property (nonatomic) NSString secUserID;
@property (nonatomic) AWEUserModel targetUser;
@property (nonatomic) AWELiveWorkDataController dataController;
@property (nonatomic) AWEFeedRefreshFooter footer;
@property (nonatomic) BOOL isCurrentUser;
@property (nonatomic) BOOL isFromUserHomePage;
@property (nonatomic) <AWEUserProfileTabVCDelegate> delegate;
@property (nonatomic) BOOL isInTabContainer;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)secUserID;
- (void)setSecUserID:;
- (id)aweui_emptyPageConfigForState:;
- (id)aweui_emptyPageEdgeInsets;
- (void)setDataController:;
- (BOOL)isFromUserHomePage;
- (void)setIsFromUserHomePage:;
- (double)contentOffsetY;
- (void)adjustContentOffset:animated:;
- (double)contentSizeHeight;
- (void)loadMoreData;
- (void)registerCollectionViewCell;
- (void)setTargetUser:;
- (void)updateLoadingViewFrame;
- (BOOL)isInTabContainer;
- (void)setIsInTabContainer:;
- (void)refreshDataIfNeed;
- (id)initWithUserID:secUserID:targetUser:delegate:;
- (void)onCellDeleteNotification:;
- (double)cellHeight:;
- (void)trackPlayBackEventWithData:;
- (void)trackLiveShowEventWithData:;
- (void)endRefreshingWithData:error:;
- (void)reloadData;
- (id)collectionView:layout:referenceSizeForHeaderInSection:;
- (id)footer;
- (id)userID;
- (id)collectionView;
- (void)dealloc;
- (id)delegate;
- (void)viewWillLayoutSubviews;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setLoadingView:;
- (long long)numberOfSectionsInCollectionView:;
- (void)viewDidLoad;
- (id)contentView;
- (id)loadingView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setCollectionView:;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)scrollViewWillBeginDragging:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)viewDidAppear:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void)setDelegate:;
- (void)setFooter:;
- (void)setUserID:;
- (double)cellWidth;
- (BOOL)isCurrentUser;
- (void)setIsCurrentUser:;
- (void)setupUI;
- (id)dataController;
- (void)refreshData;
- (id)targetUser;
@end
