@interface AWELivePreStreamSocialElement : AWELiveBusinessBaseElement
@property (nonatomic) q isInTeamFight;
@property (nonatomic) BOOL isInGuestBallte;
@property (nonatomic) q isInRoomBallte;
@property (nonatomic) IESLiveModalDialog modalDialog;
@property (nonatomic) BOOL isFetchingInteractList;
@property (nonatomic) AWELiveMultiInteractListModel interactListModel;
@property (nonatomic) IESLiveKTVPreStreamContext ktvPreStreamContext;
@property (nonatomic) RACBehaviorSubject asyncResourceLoaderSubject;
@property (nonatomic) RACDisposable asyncResourceLoaderDisposable;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)initializeElement;
- (void)viewController_viewWillAppear;
- (void)viewController_viewDidAppear;
- (void)prepareForDisPlay;
- (void)onUserEnterLiveRoom:;
- (void)viewController_endDecelerating;
- (void)preloadElement;
- (void)provideEenterLiveRoomParamasWithContext:;
- (id)interactListModel;
- (id)provideCoreDataForEvent:;
- (id)ktvPreStreamContext;
- (void)setKtvPreStreamContext:;
- (id)modalDialog;
- (void)setModalDialog:;
- (void)updateInteractListWithScene:enterFrom:extra:;
- (id)asyncResourceLoaderSubject;
- (id)asyncResourceLoaderDisposable;
- (void)setAsyncResourceLoaderDisposable:;
- (BOOL)isFetchingInteractList;
- (void)setInteractListModel:;
- (void)setIsFetchingInteractList:;
- (long long)p_isInTeamFightForTrack;
- (void)asyncLoadResourceUsingBlock:;
- (long long)isInTeamFight;
- (void)setIsInTeamFight:;
- (BOOL)isInGuestBallte;
- (void)setIsInGuestBallte:;
- (long long)isInRoomBallte;
- (void)setIsInRoomBallte:;
- (void)setAsyncResourceLoaderSubject:;
- (void)setData:;
- (void).cxx_destruct;
@end
