@interface AWELiveVisibleScopeListFragment : IESLiveGuideComponent
@property (nonatomic) CreateInfoResponse_CreateInfo openLiveModel;
@property (nonatomic) NSInteger realCurrentVisibleType;
@property (nonatomic) Q currentVisibleType;
@property (nonatomic) NSArray userList;
@property (nonatomic) AWELiveVisibleTypeModel curPaidSelectModel;
@property (nonatomic) BDXBridgeEventSubscriber vipPanelSubscriber;
@property (nonatomic) NSArray chatGroupList;
@property (nonatomic) NSInteger realVisibleType;
@property (nonatomic) Q currentSelectedVisibleType;
@property (nonatomic) NSArray selectedUserList;
@property (nonatomic) AWELiveVisibleTypeModel paidSelectModel;
@property (nonatomic) NSArray selectedChatGroupList;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)userList;
- (void)componentBindService;
- (void)componentMount;
- (void)componentUnmount;
- (void)setUserList:;
- (void)setSelectedUserList:;
- (id)selectedUserList;
- (void)updateOpenLiveModel:;
- (id)openLiveModel;
- (void)toolbarLoadAllToolBarItemsForLiveType:;
- (void)addSubscribeVIPPanelFinishSettingIfNeed;
- (id)vipPanelSubscriber;
- (void)setVipPanelSubscriber:;
- (id)getVisibleScopeDetailListVC:liveType:DIContext:selectedBlock:;
- (id)getItemAddTextOf:;
- (id)getCreateAPIParamsOf:;
- (id)getTrackStrOf:;
- (void)openTryLiveVisibleScopeDetailVC:;
- (id)getVisiblePanelViewWithType:liveType:DIContext:selectedBlock:;
- (id)getPaidVisiblePanelViewWithVisibleType:selectedUsers:isShowNotPreviewOption:isPaidOpenLiveNow:selectedBlock:;
- (void)setTryLiveVisibleScopeWithDIContext:completedBlock:;
- (int)realVisibleType;
- (void)setRealVisibleType:;
- (unsigned long long)currentSelectedVisibleType;
- (void)setCurrentSelectedVisibleType:;
- (id)paidSelectModel;
- (void)setPaidSelectModel:;
- (id)selectedChatGroupList;
- (void)setSelectedChatGroupList:;
- (void)changeGuidePaidLiveStatus:;
- (void)changePaidVisibleRange:;
- (void)willCancelPaidLiveStateWhenChangeLiveType:;
- (void)appendOpenLiveRequestParams:completion:;
- (void)appendStartLiveTrackParams:room:completion:;
- (void)initSelect;
- (void)setCurrentVisibleType:;
- (void)setRealCurrentVisibleType:;
- (void)setOpenLiveModel:;
- (void)handleSelectType:userList:;
- (int)realCurrentVisibleType;
- (void)handleSchemaChatGroupLiveIfNeed;
- (unsigned long long)currentVisibleType;
- (BOOL)isInPaidSelectionType:;
- (id)curPaidSelectModel;
- (id)userIdStringArray:;
- (void)handleUpdateVisibleScopeResult:userList:;
- (void)addUploadVisibleSelectMonitor:type:userList:updateFailedList:cancelFailedList:;
- (void)setCurPaidSelectModel:;
- (void)setChatGroupList:;
- (id)chatGroupList;
- (id)chatGroupListStr:;
- (void)saveSelectType:realType:source:;
- (void)showToastWithType:;
- (id)parseGroupIDListStr:;
- (void)setChatGroupLiveVisibleScopeWithDataSource:;
- (void).cxx_destruct;
@end
