@interface AWELeftSideBarWatchVideoLaterContainerView : UIView
@property (nonatomic) UIView contentView;
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) AWELSBWatchVideoLaterHeaderView headerView;
@property (nonatomic) <AWELeftSideBarItemContext> context;
@property (nonatomic) AWELeftSideBarWatchVideoLaterContainerUIConfig containerUIConfig;
@property (nonatomic) AWELeftSideBarWatchVideoLaterHeaderUIConfig headerUIConfig;
@property (nonatomic) double maxTitleHeight;
@property (nonatomic) <AWELeftSideBarWatchVideoLaterContainerViewDelegate> delegate;
@property (nonatomic) NSString headerButtonTitle;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setupUIConfig;
- (void)setContainerUIConfig:;
- (void)setHeaderUIConfig:;
- (id)containerUIConfig;
- (id)headerUIConfig;
- (void)handleTapShowAllBtn:;
- (double)calculateContainerHeight;
- (void)reloadContaienerView;
- (void)updateHeaderTextWithUnreadCount:;
- (id)headerButtonTitle;
- (id)collectionView;
- (double)collectionView:layout:minimumLineSpacingForSectionAtIndex:;
- (double)collectionView:layout:minimumInteritemSpacingForSectionAtIndex:;
- (id)delegate;
- (id)collectionView:cellForItemAtIndexPath:;
- (long long)numberOfSectionsInCollectionView:;
- (id)contentView;
- (id)initWithContext:;
- (void)setCollectionView:;
- (id)headerView;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setContentView:;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)setDelegate:;
- (id)context;
- (void)setHeaderView:;
- (void)setupView;
- (double)maxTitleHeight;
- (void)setMaxTitleHeight:;
- (double)containerHeight;
@end
