@interface AWELongVideoAdEpisodeAwardInfo : MTLModel
@property (nonatomic) double watchDuration;
@property (nonatomic) NSString sendUniqId;
@property (nonatomic) NSNumber timestamp;
@property (nonatomic) NSString sign;
@property (nonatomic) NSNumber startTime;
@property (nonatomic) NSNumber endTime;
@property (nonatomic) NSNumber spuId;
@property (nonatomic) NSNumber skuId;
@property (nonatomic) NSString spuIdStr;
@property (nonatomic) NSString skuIdStr;
@property (nonatomic) q bizType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)sign;
- (void)setSign:;
- (long long)bizType;
- (void)setBizType:;
- (id)spuId;
- (id)skuId;
- (void)setSkuId:;
- (void)setSpuId:;
- (id)sendUniqId;
- (void)setSendUniqId:;
- (double)watchDuration;
- (void)setWatchDuration:;
- (id)spuIdStr;
- (void)setSpuIdStr:;
- (id)skuIdStr;
- (void)setSkuIdStr:;
- (id)timestamp;
- (void)setStartTime:;
- (id)endTime;
- (void)setEndTime:;
- (void)setTimestamp:;
- (void).cxx_destruct;
- (id)startTime;
+ (id)spuIdJSONTransformer;
+ (id)skuIdJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
