@interface AWELiveShelfViewController : UIViewController
@property (nonatomic) AWELiveShelfViewModel viewModel;
@property (nonatomic) AWELiveShelfNetErrorView netErrorView;
@property (nonatomic) UIView backgroundContainer;
@property (nonatomic) AWELiveShelfTopBrandView topBrandView;
@property (nonatomic) AWELiveShelfTopBar topBar;
@property (nonatomic) AWELiveShelfBottomView bottomView;
@property (nonatomic) AWELifeShelfResponseModel model;
@property (nonatomic) AWEPOILoadingView loadingView;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) NSArray cardList;
@property (nonatomic) double serverTime;
@property (nonatomic) NSObject<OS_dispatch_source> serverTimeTimer;
@property (nonatomic) Q requestStage;
@property (nonatomic) AWELiveShelfContainerView shelfContainerView;
@property (nonatomic) BOOL isReuse;
@property (nonatomic) BOOL isClosed;
@property (nonatomic) BOOL isShowFromBillOfLading;
@property (nonatomic) NSMutableSet allShowedItems;
@property (nonatomic) NSMutableSet allMPItems;
@property (nonatomic) NSMutableSet allTakeOutItems;
@property (nonatomic) NSMutableSet allMPTakeOutItems;
@property (nonatomic) double stayBegin;
@property (nonatomic) NSString toPostion;
@property (nonatomic) NSDictionary poiSessionData;
@property (nonatomic) BOOL hasConfigCardList;
@property (nonatomic) NSDictionary extraTrackParams;
@property (nonatomic) NSMutableDictionary tab2CardNumMap;
@property (nonatomic) BOOL forceToClose;
@property (nonatomic) AWELiveShelfLynxModuleOperator lynxModuleOperator;
@property (nonatomic) NSString envAddressInfo;
@property (nonatomic) NSMutableSet hasPrefetchItems;
@property (nonatomic) NSString shelfId;
@property (nonatomic) NSObject<OS_dispatch_source> bottomShowDelayTimer;
@property (nonatomic) AWEPOILiveDataCenterShelfSource dataCenterSource;
@property (nonatomic) BOOL hasNewMessage;
@property (nonatomic) BOOL isHandlingMessage;
@property (nonatomic) double handlingTimestamp;
@property (nonatomic) AWELiveShelfRefreshConfig refreshConfig;
@property (nonatomic) NSMutableArray messageList;
@property (nonatomic) NSString shelfCycleUUID;
@property (nonatomic) BOOL isCacheRequesting;
@property (nonatomic) BOOL isBlockingLiveMessage;
@property (nonatomic) BOOL hasBlockedLiveMessage;
@property (nonatomic) @ container;
@property (nonatomic) <AWELiveShelfVCDelegate> delegate;
@property (nonatomic) NSObject<AWELiveShelfCacheManagerProtocol> cacheManager;
@property (nonatomic) NSDictionary commonTrackerParameter;
@property (nonatomic) AWELiveShelfModel shelfModel;
@property (nonatomic) NSDictionary performanceTracker;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)trackParams;
- (id)extraTrackParams;
- (void)setExtraTrackParams:;
- (id)cardList;
- (id)refreshConfig;
- (void)closeVC;
- (unsigned long long)requestStage;
- (void)setRequestStage:;
- (void)registerNotification;
- (void)setServerTime:;
- (void)updateServerTime:;
- (BOOL)isReuse;
- (void)setIsReuse:;
- (void)handleBroadcastNotification:;
- (void)setCardList:;
- (id)aAWEPadBizUIAdapter;
- (void)setupBottomView;
- (void)setupContainerView;
- (void)setRefreshConfig:;
- (void)containerDidShowCompletion:;
- (void)containerDidSwitchTo:;
- (void)containerWillCloseWithCloseType:;
- (BOOL)containerShouldShowMask;
- (void)embedInContainer:;
- (void)setNetErrorView:;
- (id)netErrorView;
- (void)trackADEventWithLabel:refer:adExtraParams:;
- (void)setEnvAddressInfo:;
- (void)disMissSelf;
- (void)messageReceived:messageType:;
- (id)commonTrackerParameter;
- (void)setAddressInfoRequestParams:;
- (id)envAddressInfo;
- (void)setCommonTrackerParameter:;
- (id)shelfModel;
- (void)replayWithTarget:parameter:;
- (void)setShelfModel:;
- (void)updateWithActionType:isReuse:;
- (void)liveLifeShelfShowErrorTrackerWithReason:;
- (void)setupLoadingView;
- (void)initializeWithParameters:;
- (void)setLiveFloatOnTopMuteAction:;
- (BOOL)canAutoCloseContainerWithSource:;
- (void)cleanLynxModuleIfNeeded;
- (void)registerMessageCenter;
- (id)shelfId;
- (void)setShelfId:;
- (id)shelfDataLynxModule;
- (void)tableViewDidSelectRowWithItem:params:liveInfo:isNative:lynxParams:;
- (void)tableViewDidSelectBuyWithItem:params:liveInfo:isNative:lynxParams:;
- (id)aweContext;
- (void)disMissShelfWithParams:;
- (void)trackerWithEvent:paramsBlock:;
- (id)shelfExposeId;
- (void)tableViewScrollBegin;
- (void)tableViewScrollEnd;
- (void)tableViewDidScrollDirection:offset:contentHeight:extraParams:;
- (void)trackerWithEvent:item:paramsBlock:btmInfo:isCreateChain:;
- (void)trackerWithEvent:item:paramsBlock:;
- (void)filterCardListWithTabId:showExplainingItem:;
- (id)prefetchParamsWithCell:;
- (id)poiSessionData;
- (void)setPoiSessionData:;
- (id)serverTimeTimer;
- (void)setServerTimeTimer:;
- (id)lynxModuleOperator;
- (void)setHasConfigCardList:;
- (void)clearTabMap;
- (id)roomDataForLynxModule;
- (id)tab2CardNumMap;
- (void)recordShowedItemsWithItem:;
- (id)allShowedItems;
- (id)allMPItems;
- (id)allTakeOutItems;
- (id)allMPTakeOutItems;
- (void)updateTabMapCurrentCardNum;
- (long long)calculateTotalItems;
- (void)updateShowedItems;
- (id)nativeDataForLynxModuleWithModel:actionType:cacheStatus:;
- (void)setAllShowedItems:;
- (void)setAllMPItems:;
- (void)setAllTakeOutItems:;
- (void)setAllMPTakeOutItems:;
- (void)setTab2CardNumMap:;
- (BOOL)hasConfigCardList;
- (BOOL)isCacheRequesting;
- (void)setIsCacheRequesting:;
- (void)setLynxModuleOperator:;
- (id)eventArrayTrackWithLynx;
- (id)productTrackerWithItem:;
- (void)trackerWithEvent:paramsBlock:btmInfo:isCreateChain:;
- (id)flashStateWithItem:;
- (id)trackerParamWithCardListContainsCouponInfo;
- (void)logShelfShow;
- (void)trackerWithEvent:params:commonKeys:;
- (id)memberSchemaTrackerParameter;
- (void)dataCacheValidTrackerWithCacheModel:realModel:;
- (void)registerBTM;
- (void)updateBTM;
- (void)p_autoCollectCouponTrackWithSourceItem:result:msg:fromPosition:;
- (void)logShelfDismiss;
- (void)sendStayDurationTrackerToPosition:;
- (void)setStayBegin:;
- (void)forceToSelectTab:;
- (void)setDataCenterSource:;
- (id)bottomShowDelayTimer;
- (void)setBottomShowDelayTimer:;
- (void)newFirstFrameTrackerWithProcessDuration:RequestDuration:time:useCache:dataCacheStatus:;
- (void)removeNetErrorView;
- (void)setupTopBrandView;
- (void)setupTopBar;
- (id)topBrandView;
- (void)updateContextShelfIsClosed:;
- (void)setupBackgroundLayer;
- (void)disMissSelfIfCan;
- (void)setIsBlockingLiveMessage:;
- (BOOL)isShowFromBillOfLading;
- (void)setIsShowFromBillOfLading:;
- (void)handleBlockedLiveMessage;
- (BOOL)showTopBrandView;
- (void)setTopBrandView:;
- (void)updateContainerViewBottomInset;
- (void)tracerTopbarFirstFrameDuration:;
- (void)addNetErrorViewWithText:;
- (void)setForceToClose:;
- (void)sendShelfLifeCycleToMessageCenterIsClosed:;
- (void)setShelfCycleUUID:;
- (id)shelfCycleUUID;
- (BOOL)hasBlockedLiveMessage;
- (void)setHasBlockedLiveMessage:;
- (BOOL)isBlockingLiveMessage;
- (void)handleLivePowerSaveClear:;
- (BOOL)containerShouldClosed;
- (void)setPerformanceTracker:;
- (double)stayBegin;
- (id)commonKeys;
- (BOOL)forceToClose;
- (void)childRemoveFromParent:animation:;
- (void)setBottomViewInvisible:;
- (void)autoPickUpCouponWithItem:params:liveInfo:fromPosition:;
- (void)containerWillClose;
- (id)performanceTracker;
- (id)dataCenterSource;
- (id)shelfContainerView;
- (BOOL)useLynxTrack;
- (void)updateWithActionType:isReuse:refreshInfo:;
- (void)adaptMutiTabABWithModel:;
- (void)liveLifeShelfShowTrackerWithCacheStatus:;
- (void)liveLifePerformanceNetRequestWithError:time:duration:useCache:;
- (void)fetchListFinishedWithModel:actionType:errorType:completion:;
- (void)liveLifeSloganShowTracker;
- (void)updateWithCacheModel:requestDuration:;
- (void)registerShelfDetailAPIPrefetch;
- (void)refreshShelf;
- (id)toPostion;
- (void)setShelfContainerView:;
- (void)setToPostion:;
- (void)liveLifeBarHotSpotClickTracker;
- (void)handleFetchListRequestEnd;
- (id)lynxShelfTrackParamer;
- (void)updateShelfDataToItem;
- (void)calculateDepth;
- (void)calculateOriginIndexWithModel:;
- (void)prefetchVisibleCellWithParams:;
- (id)hasPrefetchItems;
- (void)liveLifeShelfDepthTracker;
- (BOOL)isHandlingMessage;
- (void)setIsHandlingMessage:;
- (void)setHandlingTimestamp:;
- (void)handleMessagePostDelayEnd;
- (void)setHasNewMessage:;
- (id)getCachedMessageRefreshInfo;
- (double)handlingTimestamp;
- (BOOL)hasNewMessage;
- (void)handleUpdateWithActionType:isReuse:;
- (void)setHasPrefetchItems:;
- (void)setModel:;
- (void)setContainer:;
- (id)container;
- (BOOL)isClosed;
- (id)init;
- (void)dealloc;
- (id)delegate;
- (void)viewDidLayoutSubviews;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)loadingView;
- (void)retryAction;
- (void)viewDidDisappear:;
- (double)serverTime;
- (id)model;
- (void)viewWillAppear:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)setBackgroundContainer:;
- (id)topBar;
- (void)viewDidAppear:;
- (void)setTopBar:;
- (id)backgroundContainer;
- (void)setDelegate:;
- (id)gradientLayer;
- (id)bottomView;
- (void)setGradientLayer:;
- (void)setIsClosed:;
- (void)setBottomView:;
- (void)updateBackgroundColor:;
- (id)cacheManager;
- (void)setCacheManager:;
- (id)messageList;
- (void)updateFrame;
- (void)setMessageList:;
+ (Class)aAWEPadBizUIAdapterClass;
@end
