@interface AWELiveSoloKTVDetailHeaderInfoDiffableModel : AWELiveSoloKTVDetailDiffableModel
@property (nonatomic) AVPlayer player;
@property (nonatomic) IESLiveKtvSongStruct song;
@property (nonatomic) q sungCount;
@property (nonatomic) q playerStatus;
@property (nonatomic) BOOL isPlayingBeforeInActivity;
@property (nonatomic) IESLiveCombineSubject songInfoChangeSubject;
@property (nonatomic) IESLiveCombineSubject favoriteStateChangeSubject;
@property (nonatomic) @ observerToken;
- (void)clearPlayer;
- (id)favoriteStateChangeSignal;
- (id)songInfoChangeSignal;
- (long long)sungCount;
- (void)updateCollectStateWithCompletion:;
- (void)updatePlayerState;
- (id)favoriteStateChangeSubject;
- (void)setSungCount:;
- (id)songInfoChangeSubject;
- (void)didPlayerPlayFinish;
- (void)didBecomeActivity;
- (void)setIsPlayingBeforeInActivity:;
- (BOOL)isPlayingBeforeInActivity;
- (void)updateWithSong:sungCount:;
- (void)setSongInfoChangeSubject:;
- (void)setFavoriteStateChangeSubject:;
- (void)dealloc;
- (void)play;
- (void)willResignActive;
- (id)player;
- (void)setPlayer:;
- (void)setObserverToken:;
- (void)observeValueForKeyPath:ofObject:change:context:;
- (void).cxx_destruct;
- (void)pause;
- (id)observerToken;
- (void)setSong:;
- (id)song;
- (long long)playerStatus;
- (void)setPlayerStatus:;
- (void)setupPlayer;
@end
