@interface AWELiveShelfHeaderPoiDetailView : UIView
@property (nonatomic) UIButton poiTitle;
@property (nonatomic) UIImageView rankTagIconImageView;
@property (nonatomic) UILabel rankTagTitleLabel;
@property (nonatomic) UIView rankTagBackground;
@property (nonatomic) UIStackView titleStackView;
@property (nonatomic) UIStackView poiDetailView;
@property (nonatomic) UILabel distanceLabel;
@property (nonatomic) UILabel addressLabel;
@property (nonatomic) UIView line;
@property (nonatomic) UILabel rankLabel;
@property (nonatomic) UIView line2;
@property (nonatomic) BOOL isSupportJumpPoiDetail;
@property (nonatomic) @? poiTitleClickedBlock;
- (id)line2;
- (void)setLine2:;
- (id)poiDetailView;
- (void)setPoiDetailView:;
- (void)setIsSupportJumpPoiDetail:;
- (id)poiTitle;
- (id)rankTagBackground;
- (id)rankTagIconImageView;
- (id)rankTagTitleLabel;
- (id)poiTitleClickedBlock;
- (void)poiTitleClicked:;
- (void)setupWithTitle:Distance:address:rank:poiRankTag:isShowPoiRankTag:isSupportJumpPoiDetail:;
- (void)setPoiTitleClickedBlock:;
- (void)setPoiTitle:;
- (void)setRankTagIconImageView:;
- (void)setRankTagTitleLabel:;
- (void)setRankTagBackground:;
- (BOOL)isSupportJumpPoiDetail;
- (id)initWithFrame:;
- (id)line;
- (void).cxx_destruct;
- (id)distanceLabel;
- (void)setDistanceLabel:;
- (void)setLine:;
- (void)setupUI;
- (id)addressLabel;
- (void)setAddressLabel:;
- (void)setTitleStackView:;
- (id)titleStackView;
- (id)rankLabel;
- (void)setRankLabel:;
@end
