@interface AWELivePreStreamEventElement : AWELiveBaseElement
@property (nonatomic) IESLiveRoomMQEventReportApi reportApi;
@property (nonatomic) BOOL needReportNotRender;
@property (nonatomic) BOOL needReportNotRenderV2;
@property (nonatomic) BOOL hasBeginDragging;
@property (nonatomic) q beginDraggingTime;
@property (nonatomic) q endDraggingTime;
@property (nonatomic) {CGPoint=dd} downLocation;
@property (nonatomic) {CGPoint=dd} upLocation;
@property (nonatomic) BOOL showLiveStream;
@property (nonatomic) NSMutableDictionary playerReportParams;
@property (nonatomic) NSDate liveShowDate;
@property (nonatomic) NSDate firstFrameDate;
@property (nonatomic) double deliveryShowTime;
@property (nonatomic) double deliveryEndTime;
@property (nonatomic) double finishShowTime;
@property (nonatomic) double finishEndTime;
@property (nonatomic) BOOL roomEntered;
@property (nonatomic) BOOL hadTrackLiveShowEvent;
@property (nonatomic) BOOL hasTrackedFirstFrameDuration;
@property (nonatomic) BOOL hadTrackedLiveEnd;
@property (nonatomic) BOOL hasTrackedWindowShow;
@property (nonatomic) q last1LiveIndex;
@property (nonatomic) double last1LiveExposureTime;
@property (nonatomic) double last1LiveEndExposureTime;
@property (nonatomic) double last1NoADLiveIndex;
@property (nonatomic) double last1NoADLiveExposureTime;
@property (nonatomic) double last1NoADLiveEndExposureTime;
@property (nonatomic) AWELiveEnterGuideModel enterGuideModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)initializeElement;
- (id)viceViewTypeForTrack;
- (long long)viceViewLayoutType;
- (void)prepareForDisPlay;
- (void)startTimingForTrack;
- (void)trackEventForStayTime;
- (void)setRoomEntered:;
- (BOOL)roomEntered;
- (void)onUserEnterLiveRoom:;
- (void)viewController_willBeginDragging:;
- (void)viewController_willEndDragging:velocity:;
- (void)streamPlayer_startToPlay;
- (void)streamPlayer_firstFrame;
- (void)streamPlayer_stop;
- (void)streamPlayer_finish;
- (void)provideEenterLiveRoomParamasWithContext:;
- (void)setLiveShowDate:;
- (id)aAWELivePreStreamViewModelDOUYINLiteAdapter;
- (void)setFirstFrameDate:;
- (id)liveShowDate;
- (id)firstFrameDate;
- (long long)p_playedDuration;
- (void)iesLiveTrackEvent:params:;
- (BOOL)isFromHomepageLife;
- (void)p_trackLiveShow;
- (id)tagInfoForTrack;
- (id)p_checkParams:withParamsList:;
- (id)p_extraTrackParamsForAggregateModels;
- (id)inviteModeForTrackByBattleSettings:;
- (void)trackLiveCoverShow:;
- (id)reportApi;
- (void)setReportApi:;
- (void)startDeliveyTime;
- (void)recordDeliveryShownTime;
- (void)startFinishTime;
- (void)recordFinishShownTime;
- (void)handlePlayerReportInfo:;
- (void)setEnterGuideModel:;
- (void)handleFeedRefreshCompletion:;
- (void)checkPreviewModelVail;
- (void)setNeedReportNotRender:;
- (void)setNeedReportNotRenderV2:;
- (void)setHasBeginDragging:;
- (void)setBeginDraggingTime:;
- (void)setEndDraggingTime:;
- (void)setShowLiveStream:;
- (void)trackStreamNotRenderLogType:withRoomAlive:;
- (void)trackLiveWindowClick;
- (void)setHadTrackLiveShowEvent:;
- (void)setHasTrackedWindowShow:;
- (BOOL)showLiveStream;
- (void)setHasTrackedFirstFrameDuration:;
- (void)setHadTrackedLiveEnd:;
- (void)setPlayerReportParams:;
- (void)setFinishShowTime:;
- (void)setFinishEndTime:;
- (void)setDeliveryShowTime:;
- (void)setDeliveryEndTime:;
- (void)trackLiveSwipeAwayDurationIfNeeded:;
- (void)trackEventForShowToPlayTime;
- (void)p_startLiveTabFirstFrameTrack;
- (BOOL)hasBeginDragging;
- (void)startPlayedTimingForTrack;
- (void)trackLiveWindowShow;
- (void)trackLiveEndByCheckingService;
- (void)setDownLocation:;
- (BOOL)needReportNotRenderV2;
- (void)trackStreamNotRenderLogForType:;
- (id)downLocation;
- (long long)endDraggingTime;
- (long long)beginDraggingTime;
- (BOOL)hasTrackedFirstFrameDuration;
- (void)trackEnterRoomDurationWithParam:;
- (id)playerReportParams;
- (BOOL)hadTrackLiveShowEvent;
- (double)last1LiveExposureTime;
- (double)last1LiveEndExposureTime;
- (void)setLast1LiveExposureTime:;
- (void)setLast1LiveIndex:;
- (long long)last1LiveIndex;
- (double)last1NoADLiveExposureTime;
- (double)last1NoADLiveEndExposureTime;
- (void)setLast1NoADLiveExposureTime:;
- (void)setLast1NoADLiveIndex:;
- (double)last1NoADLiveIndex;
- (BOOL)enableOptimizePrestream;
- (void)setLast1LiveEndExposureTime:;
- (void)setLast1NoADLiveEndExposureTime:;
- (id)enterGuideModel;
- (BOOL)hasTrackedWindowShow;
- (id)liveTypeForTrack;
- (id)screenRatioForTrack;
- (id)screenAlignmentForTrack;
- (BOOL)hadTrackedLiveEnd;
- (BOOL)needReportNotRender;
- (double)deliveryEndTime;
- (double)finishEndTime;
- (void)didReceivePlayerMonitorStateInfo:;
- (void)iesLiveTrackEvent:;
- (id)upLocation;
- (void)setUpLocation:;
- (double)deliveryShowTime;
- (double)finishShowTime;
- (void)dealloc;
- (id)requestID;
- (void)setData:;
- (void).cxx_destruct;
- (void)reset;
+ (Class)aAWELivePreStreamViewModelDOUYINLiteAdapterClass;
@end
