@interface AWEListenFeedViewController : AWEBaseListViewController
@property (nonatomic) AWEListenFeedPlayModel playModel;
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) NSString referString;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSString enterTabName;
@property (nonatomic) AWEListDataController externalDataController;
@property (nonatomic) BOOL originalHasExternalDataController;
@property (nonatomic) AWEShellViewController<AWEAwemeDetailTableViewControllerProtocol> externalDetailVC;
@property (nonatomic) q initialIndex;
@property (nonatomic) double startTimestamp;
@property (nonatomic) AWEListenFeedContext context;
@property (nonatomic) Q localPlayStyle;
@property (nonatomic) double localSpeed;
@property (nonatomic) AWEButton backButton;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) AWEListenFeedValueAdjustPopupView speedSheet;
@property (nonatomic) DUXBasicSheet sheet;
@property (nonatomic) DUXBasicSheet bgBasicSheet;
@property (nonatomic) UILabel noContentLabel;
@property (nonatomic) UIButton titleButton;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIImageView titleArrowImageView;
@property (nonatomic) AWEListenFeedContentFilterContainerView contentFilterContainerView;
@property (nonatomic) UILabel secondPageTitleLabel;
@property (nonatomic) BOOL shouldShowContentFilterAfterDelay;
@property (nonatomic) BOOL isExiting;
@property (nonatomic) BOOL pannelIsShowing;
@property (nonatomic) BOOL addedStatusIsRequeatOnAir;
@property (nonatomic) BOOL addedToProfileIsRequestOnAir;
@property (nonatomic) NSDictionary paramDictionary;
@property (nonatomic) q dataSourceType;
@property (nonatomic) BOOL hasShowPinchToastForSpecial;
@property (nonatomic) BOOL willShowGestureGuide;
@property (nonatomic) BOOL shouldDisableContentFilterAutoShow;
@property (nonatomic) BOOL haveNoContent;
@property (nonatomic) BOOL alreadyAutoShowContentFilter;
@property (nonatomic) UIView filterAnimationMask;
@property (nonatomic) BOOL isFilterViewSliding;
@property (nonatomic) NSTimer timer;
@property (nonatomic) AWEGradientView emptyGradientView;
@property (nonatomic) @? closePlayList;
@property (nonatomic) q rewindTotalCount;
@property (nonatomic) q rewindCompletionCount;
@property (nonatomic) q forwardTotalCount;
@property (nonatomic) q forwardCompletionCount;
@property (nonatomic) double previousTime;
@property (nonatomic) UIView tempKeepCurrentPlayingView;
@property (nonatomic) double listenFeedBackgroundFilterViewHeight;
@property (nonatomic) <AWEFeedBackgroundPlayManagerProtocol> backgroundPlayManager;
@property (nonatomic) double kLastTime;
@property (nonatomic) BOOL isPlayingInterrupted;
@property (nonatomic) NSIndexPath lastPlayIndex;
@property (nonatomic) BOOL isScrolling;
@property (nonatomic) BOOL isAutoPause;
@property (nonatomic) BOOL isAutoScrollToNextVideo;
@property (nonatomic) NSIndexPath currentPlayIndex;
@property (nonatomic) AWEListenFeedOptimizedInteractionViewController tempKeepCurrentPlayingViewController;
@property (nonatomic) BOOL isUsedForSecondPage;
@property (nonatomic) NSString secondPageName;
@property (nonatomic) NSString scene;
@property (nonatomic) AWEListenFeedFirstEnterTracker firstEnterTracker;
@property (nonatomic) @? updatePlayListPlayModelBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeModel;
- (void)setAwemeModel:;
- (void)initSubviews;
- (id)referString;
- (void)listDidReloadDataWithCollectionView:;
- (void)setEnterMethod:;
- (BOOL)configWithRouterParamDict:;
- (void)sheetDidDismiss:;
- (void)backButtonClicked:;
- (void)setReferString:;
- (id)enterMethod;
- (BOOL)transition_shouldStartInteractiveTranstionForSlideDirection:gestureRecognizer:;
- (void)listWillPerformBatchUpdatesWithCollectionView:;
- (void)listDidPerformBatchUpdatesWithCollectionView:;
- (void)listWillReloadDataWithCollectionView:;
- (BOOL)isSplashShowing;
- (void)customLayoutCollectionView:;
- (id)sectionControllerClassArray;
- (void)dataSourceDidCreateSectionController:forSectionViewModel:;
- (id)emptySectionsPlaceholderView;
- (id)currentPlayIndex;
- (void)didClickFollowButton;
- (BOOL)isSlideEnable;
- (void)backgroundPlay;
- (id)currentPlayModel;
- (void)handleConnectionChanged:;
- (void)setCurrentPlayIndex:;
- (void)addNotifications;
- (void)handleAudioSessionInterruptionNotification:;
- (void)resetNowPlayingInfo;
- (void)setIsPlayingInterrupted:;
- (BOOL)isPlayingInterrupted;
- (void)setupBinding;
- (void)stateOfHeadphones:;
- (void)playIndex:;
- (id)lastPlayIndex;
- (void)setLastPlayIndex:;
- (id)aAWEFeedContainerViewControllerCommonAdapter;
- (void)handleAppWillResignActive:;
- (void)handleFetchDataState:;
- (void)setPlayModel:;
- (id)playModel;
- (void)showLoadingView:;
- (void)splashDidDisappear:;
- (id)aAWEBackgroundPlayAdapter;
- (id)currentPlayerViewController;
- (void)setupRecallRegisters;
- (void)detailDrawBackCellTimeIsOver:;
- (void)handleVideoSafetyCheckNotification:;
- (void)trackEnterPersonalDetail;
- (id)aAWEListenFeedAdapter;
- (void)setFirstEnterTracker:;
- (void)setEnterTabName:;
- (void)setExternalDetailVC:;
- (void)setExternalDataController:;
- (id)externalDataController;
- (void)didClickAuthorName;
- (void)cleanKeepPlaying;
- (id)currentExtendModelArray;
- (void)showContentFilterView:;
- (void)recordPlayTime;
- (void)contentFilterDismissClicked;
- (void)playNextVideo;
- (void)awe_backgroundPlayNext;
- (BOOL)hasNextVideo;
- (void)playerWillLoopPlaying;
- (void)updateUIToPauseState;
- (void)updateProgressUI;
- (void)updateCurrentTime:totalTime:;
- (void)updateLocalSpeed:;
- (unsigned long long)localPlayStyle;
- (double)localSpeed;
- (id)updatePlayListPlayModelBlock;
- (void)interactionViewDidUpdatePlayer;
- (void)trackDescriptionLabelShow;
- (BOOL)supportFilterView;
- (BOOL)isShowingContentFilter;
- (void)hideSpeedSheetIfNeed;
- (void)realShowFilterAnimation:;
- (BOOL)isUsedForSecondPage;
- (id)enterTabName;
- (id)tempKeepCurrentPlayingViewController;
- (void)trackPlayOverWithOverStatus:;
- (void)trackLoadmoreAnimationTimeWithPageType:;
- (id)firstEnterTracker;
- (void)trackFirstEnter;
- (BOOL)enableBackgroundAudioStyle;
- (BOOL)enableTrackPlayTimeInSegments;
- (void)setIsUsedForSecondPage:;
- (void)setSecondPageName:;
- (void)setWithTimer:;
- (double)listenFeedBackgroundFilterViewHeight;
- (void)playControlView:didClickPlayStyleButton:;
- (void)playControlView:didClickSpeedButton:;
- (void)playControlView:didClickPlayButton:;
- (void)playControlView:didClickCommentButton:;
- (void)playControlView:didClickShareButton:;
- (void)playControlView:sliderTouchBegan:;
- (void)playControlView:sliderValueChanged:;
- (void)playControlView:sliderTouchEnded:;
- (void)playControlViewRewind:;
- (void)playControlViewForward:;
- (void)playControlView:fastModeBeganPlaybackRate:;
- (void)playControlView:fastModeEndedPlaybackRate:;
- (void)playControlView:timingDidResetWithSeconds:;
- (void)popupViewDismiss:;
- (void)popupViewValueChosed:;
- (void)scrollToTopWithIndex:;
- (void)playList:didSelectedIndex:;
- (void)playlist:didMoveItem:;
- (void)playlist:didDeleteItem:;
- (void)playListDidClose:;
- (void)playlistDidClickPlayStyle:;
- (id)backgroundPlayManager;
- (id)backgroundPlayManager;
- (BOOL)p_backgroundPlayNextByClick:;
- (id)aweme_currentIndexPathForFullScreenCell;
- (double)kLastTime;
- (BOOL)awe_backgroundScrollToNextVideoByClick:;
- (void)setKLastTime:;
- (void)awe_backgroundPlay;
- (void)trackPlayOverWithOverStatus:cellModel:;
- (void)trackBackgroundPlayClickRight;
- (BOOL)awe_backgroundIsPlaying;
- (void)awe_backgroundPause;
- (void)showCollectGuideAlert;
- (BOOL)backgroundScrollToPreviousVideo;
- (void)trackBackgroundPlayClickLeft;
- (void)trackClickProgressBarWithExtraParams:;
- (void)awe_enableBackgroundPlay;
- (void)awe_disableBackgroundPlay;
- (void)awe_addNotification;
- (void)awe_backgroundPlayAutoNext;
- (id)awe_backgroundCurrentItemID;
- (BOOL)awe_backgroundCanPlayNext;
- (void)awe_backgroundPlayNextByClick:;
- (BOOL)awe_backgroundCanPlayPrevious;
- (void)awe_backgroundPlayPrevious;
- (double)awe_backgroundVideoDuration;
- (double)awe_backgroundCurrentPlaybackTime;
- (void)awe_backgroundPlayerSeekTime:;
- (BOOL)isAutoScrollToNextVideo;
- (void)setIsAutoScrollToNextVideo:;
- (void)playCell:withIndexPath:;
- (BOOL)isAutoPause;
- (void)setIsAutoPause:;
- (void)willDisplayCell:forItemAtIndexPath:;
- (void)didEndDisplayingCell:forItemAtIndexPath:;
- (void)scrollViewDidEndScrollingForPlay;
- (void)autoPlayIfNeeded;
- (void)autoPauseIfNeeded;
- (void)stopCell:withIndexPath:;
- (id)currentBaseParamsWithOtherParams:;
- (id)baseParamsWithOtherParams:;
- (void)trackEnterListenFeedPage;
- (void)trackExitListenFeedPage:;
- (void)trackListenAddGuideShow:;
- (void)trackListenAddGuideClick:position:;
- (void)trackClickChangeSpeedEntrance;
- (void)trackChangeSpeedMode:;
- (void)trackClickPlayStatus:clickPosition:;
- (void)trackClickVideoPlayWithLogExtra:;
- (void)trackVideoPlayPause;
- (void)trackChooseListenListWithIndex:;
- (void)trackListenListClick;
- (void)trackClickProgressSpeedWithMethod:type:;
- (void)awe_trackSecondPageShowIfNeed;
- (void)trackFollow;
- (void)trackClickComment;
- (void)trackDeleteItem:;
- (void)trackMoveItem:;
- (void)trackEnterForegroundWithPlaying:;
- (void)trackEnterBackgroundWithPlaying:;
- (void)setParamDictionary:;
- (void)setListenFeedBackgroundFilterViewHeight:;
- (id)initWithModel:playModel:;
- (void)setOriginalHasExternalDataController:;
- (void)setupDatasoureType;
- (void)updateEntranceGuideKeyAndTrack;
- (void)setLocalPlayStyle:;
- (void)setLocalSpeed:;
- (void)initCollectionFrame;
- (void)setupRegisters;
- (void)showGuideViewIfNeeded;
- (void)recordEnterTimes;
- (void)showCollectGuideViewIfNeededWithMethod:;
- (void)fetchListenFeedAddedStatusWithCompletion:;
- (void)scrollItemToInitialIndexIfNeeded;
- (void)showReversePlayStyleToolTipsIfNeeded;
- (void)setAccessibilityArray;
- (id)emptyGradientView;
- (void)configContext;
- (void)setupBindingSyncViewModel;
- (void)setupTransmissionNodeInfo;
- (BOOL)originalHasExternalDataController;
- (id)contentFilterContainerView;
- (id)titleArrowImageView;
- (id)secondPageTitleLabel;
- (id)secondPageName;
- (BOOL)pannelIsShowing;
- (BOOL)isPresentOrPushOtherViewController;
- (id)filterAnimationMask;
- (void)titleArrowRotateByShow:;
- (void)setIsFilterViewSliding:;
- (void)willExit:;
- (BOOL)shouldPopupBGPlayGuideEntrance;
- (void)popupBackgroundPlayGuideEntrance;
- (void)checkExternalModelCanPlay:;
- (void)appDidGotoBackground;
- (void)setWillShowGestureGuide:;
- (BOOL)addedStatusIsRequeatOnAir;
- (void)setAddedStatusIsRequeatOnAir:;
- (BOOL)addedToProfileIsRequestOnAir;
- (void)setAddedToProfileIsRequestOnAir:;
- (void)setShouldDisableContentFilterAutoShow:;
- (void)postListenFeedAddToProfile;
- (void)showCollectGuideCheckedView;
- (void)setPannelIsShowing:;
- (void)dismissCollectGuideSheet;
- (void)finishScrollItemToInitialIndex;
- (BOOL)hasShowPinchToastForSpecial;
- (BOOL)willShowGestureGuide;
- (void)showRecommendToast;
- (void)updateNoContentHint;
- (void)recallDimissNotNeedView;
- (void)reloadCurrentIndexPath;
- (void)dealRecallMessage:;
- (id)speedSheet;
- (void)backgroundPlayNextByClick:;
- (void)loadMoreIfNeeded;
- (void)preloadCellMixInfoIfNeeded;
- (id)currentCellControlView;
- (void)setSpeedSheet:;
- (BOOL)haveNoContent;
- (void)setHaveNoContent:;
- (void)showContentFilterViewIfNeeded;
- (void)setUpdatePlayListPlayModelBlock:;
- (void)setClosePlayList:;
- (void)keepCurrentPlayingAndReloadToIndex:;
- (id)currentPlaylistViewController;
- (long long)rewindTotalCount;
- (long long)rewindCompletionCount;
- (void)setRewindTotalCount:;
- (void)setRewindCompletionCount:;
- (long long)forwardTotalCount;
- (long long)forwardCompletionCount;
- (void)setForwardTotalCount:;
- (void)setForwardCompletionCount:;
- (id)closePlayList;
- (unsigned long long)nextPlayStyle;
- (void)changePlayStyleTo:withToast:;
- (void)setHasShowPinchToastForSpecial:;
- (BOOL)shouldShowContentFilterAfterDelay;
- (void)setShouldShowContentFilterAfterDelay:;
- (void)syncAwemeModelToFeedVCIfNeeded;
- (void)syncAwemeModelToDetailVCIfNeeded;
- (void)attachPlayerTrackParamsWillExitToVC:;
- (id)externalDetailVC;
- (unsigned long long)totalShowNumBGPlayGuide;
- (void)clickBackgroundPlaySheet;
- (void)setBgBasicSheet:;
- (id)bgBasicSheet;
- (BOOL)reverseTipsFrequencyEnabled;
- (void)updateReverseTipsShowCount;
- (void)setTempKeepCurrentPlayingViewController:;
- (void)setTempKeepCurrentPlayingView:;
- (id)tempKeepCurrentPlayingView;
- (void)showSpeedSelector;
- (BOOL)isFilterViewSliding;
- (void)prepareFilterViewShow:;
- (void)realShowFilterView:;
- (void)finishFilterViewShow:;
- (id)getAnimationMaskView;
- (void)setFilterAnimationMask:;
- (BOOL)shouldDisableContentFilterAutoShow;
- (BOOL)alreadyAutoShowContentFilter;
- (BOOL)filterViewFrequencyEnabled;
- (void)setAlreadyAutoShowContentFilter:;
- (void)updateFilterViewAutoShowCount;
- (void)titleButtonClicked:;
- (void)backgroundPlayAutoNext;
- (id)backgroundCurrentItemID;
- (void)backgroundPause;
- (BOOL)backgroundCanPlayNext;
- (BOOL)backgroundCanPlayPrevious;
- (void)backgroundPlayPrevious;
- (BOOL)backgroundIsPlaying;
- (double)backgroundVideoDuration;
- (double)backgroundCurrentPlaybackTime;
- (void)backgroundPlayerSeekTime:;
- (void)showNoContentHint;
- (void)setTitleArrowImageView:;
- (void)setContentFilterContainerView:;
- (void)setSecondPageTitleLabel:;
- (id)paramDictionary;
- (void)setEmptyGradientView:;
- (void)setBackgroundPlayManager:;
- (id)backButton;
- (double)startTimestamp;
- (void)setIsScrolling:;
- (void)setScene:;
- (void)viewWillDisappear:;
- (void)setTimer:;
- (id)init;
- (void)dealloc;
- (void)play;
- (id)timer;
- (void)didMoveToParentViewController:;
- (id)scene;
- (id)initWithModel:;
- (long long)dataSourceType;
- (void)setLoadingView:;
- (void)viewDidLoad;
- (void)setBackButton:;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (id)loadingView;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)setIsExiting:;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (void)scrollViewWillBeginDragging:;
- (long long)preferredStatusBarStyle;
- (BOOL)isExiting;
- (void)setTitleLabel:;
- (void)scrollViewDidEndDecelerating:;
- (void)appWillEnterForeground:;
- (void)exit;
- (void)setDataSourceType:;
- (void)setContext:;
- (void)viewWillAppear:;
- (void)appDidBecomeActive:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)setStartTimestamp:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (BOOL)isScrolling;
- (void)scrollViewDidEndScrollingAnimation:;
- (id)titleLabel;
- (id)context;
- (void)resetTimer;
- (void)pause;
- (id)noContentLabel;
- (void)scrollToItemAtIndexPath:atScrollPosition:animated:;
- (void)setNoContentLabel:;
- (id)currentModel;
- (void)setupUI;
- (void)initConstraints;
- (id)currentCell;
- (void)setupData;
- (void)fetchFilterData;
- (void)scrollViewDidEndScrolling;
- (id)titleButton;
- (void)setupCollectionView:;
- (void)appWillTerminate:;
- (void)setTitleButton:;
- (id)sheet;
- (double)previousTime;
- (void)setPreviousTime:;
- (void)handleAppDidEnterBackground:;
- (void)handleAppWillEnterForeground:;
- (void)audioSessionDidInterrupt:;
- (void)seekToTime:completion:;
- (long long)initialIndex;
- (void)setInitialIndex:;
- (void)setSheet:;
+ (Class)viewModelClass;
+ (Class)aAWEFeedContainerViewControllerCommonAdapterClass;
+ (Class)aAWEBackgroundPlayAdapterClass;
+ (Class)aAWEListenFeedAdapterClass;
@end
