@interface AWEListenFeedPlayListViewController : AWEBaseListViewController
@property (nonatomic) AWEListenFeedViewModel externalViewModel;
@property (nonatomic) q locatedIndex;
@property (nonatomic) AWEListenFeedPlayModel playModel;
@property (nonatomic) UIView maskView;
@property (nonatomic) UIView bgView;
@property (nonatomic) AWEListenFeedPlayListHeaderView headerView;
@property (nonatomic) BOOL isScrolling;
@property (nonatomic) AWEListenFeedContext context;
@property (nonatomic) AWEListenFeedPlayListCell movingCell;
@property (nonatomic) AWEListenFeedCellViewModel cellModelToDelete;
@property (nonatomic) <AWEListenFeedPlayListViewControllerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)sectionController:didMoveModel:fromIndex:toIndex:finalModelsArray:;
- (void)actionSheet:didClickButtonAtIndex:;
- (void)customLayoutCollectionView:;
- (id)sectionControllerClassArray;
- (void)dataSourceDidCreateSectionController:forSectionViewModel:;
- (BOOL)isSlideEnable;
- (void)containerWillBeginInteractiveMovementAtIndexPath:;
- (id)targetPointForMovementWithOriginalPoint:;
- (void)containerDidEndInteractiveMovement;
- (BOOL)enableInteractiveMovement;
- (void)setPlayModel:;
- (id)playModel;
- (void)updatePlayStyle:;
- (void)setExternalViewModel:;
- (void)setLocatedIndex:;
- (id)externalViewModel;
- (long long)locatedIndex;
- (void)scrollToTopWithIndex:;
- (long long)numberOfCellInVisibleRect;
- (void)closeDidClick;
- (void)setupDefaultDataLoadBehavior;
- (id)normalCollectionViewRect;
- (void)closeIfNeeds;
- (void)setCellModelToDelete:;
- (void)setMovingCell:;
- (id)movingCell;
- (id)cellModelToDelete;
- (void)updateHeaderPlayStyleButton:;
- (void)changePlayStyle;
- (id)initWithViewModel:locatedIndex:playModel:context:;
- (void)updatePlayModel:;
- (void)setIsScrolling:;
- (id)delegate;
- (id)maskView;
- (void)viewDidLoad;
- (BOOL)gestureRecognizerShouldBegin:;
- (id)headerView;
- (void)scrollViewDidScroll:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)scrollViewWillBeginDragging:;
- (void)scrollViewDidEndDecelerating:;
- (void)setContext:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (BOOL)isScrolling;
- (void)scrollViewDidEndScrollingAnimation:;
- (void)setMaskView:;
- (void)setDelegate:;
- (id)context;
- (void)setHeaderView:;
- (id)bgView;
- (void)setBgView:;
- (void)setupUI;
- (double)cellHeight;
- (void)setupCollectionView:;
- (void)deleteModel:;
+ (Class)viewModelClass;
@end
