@interface AWELiveVSTabViewController : UIViewController
@property (nonatomic) UIView naviBarBackgroundView;
@property (nonatomic) UICollectionView listView;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) AWELiveVSTabViewModel viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q type;
@property (nonatomic) NSString referString;
- (BOOL)canRefresh;
- (id)referString;
- (id)aweui_emptyPageConfigForState:;
- (void)aweui_emptyPagePrimaryButtonTapped:;
- (void)pauseWithAnimation;
- (BOOL)currentTabIsTop;
- (void)loadMore;
- (void)animatedRefreshWithCompletion:;
- (id)initWithDataController:;
- (void)showLoading:;
- (id)naviBarBackgroundView;
- (void)setNaviBarBackgroundView:;
- (void)setupListAdapter;
- (void)initLoadData;
- (void)updateViewWithNetworkError:;
- (void)refreshWithComplete:;
- (void)setScrollEnabled:;
- (void)play;
- (void)setLoadingView:;
- (id)viewModel;
- (void)viewDidLoad;
- (id)listView;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (void)reload;
- (id)loadingView;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (void)setListView:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)stop;
- (void)pause;
- (void)setupUI;
@end
