@interface AWELivePodcastRegisterManager : NSObject
@property (nonatomic) AWEUIAlertView alert;
@property (nonatomic) RACDisposable webPageDismissDispose;
@property (nonatomic) Q realNameStatus;
@property (nonatomic) BOOL phoneBinded;
@property (nonatomic) BOOL agreementDone;
@property (nonatomic) BOOL contactAuthorized;
@property (nonatomic) q verifyRiskLevel;
@property (nonatomic) NSString ticket;
@property (nonatomic) UINavigationController nav;
@property (nonatomic) NSString createRoomTypeString;
@property (nonatomic) NSNumber uniqueId;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)enterFrom;
- (void)setNav:;
- (void)setCreateRoomTypeString:;
- (void)setRealNameStatus:;
- (void)setPhoneBinded:;
- (void)setAgreementDone:;
- (long long)verifyRiskLevel;
- (void)setVerifyRiskLevel:;
- (void)checkProcess;
- (BOOL)agreementDone;
- (void)addScertificationStatusOberserve;
- (void)useNewCertCompletionWithCertResult:;
- (BOOL)phoneBinded;
- (unsigned long long)realNameStatus;
- (id)createRoomTypeString;
- (id)getURLString;
- (void)updateRealNameVerifyStatus:;
- (void)showRealNameVerify;
- (void)showAgreementAlert:completion:;
- (void)retryStartLive;
- (void)setWebPageDismissDispose:;
- (BOOL)contactAuthorized;
- (void)setContactAuthorized:;
- (id)aAWELivePodcastRegisterManagerDOUYINAdaper;
- (void)updateRealNameVerifyStatus;
- (id)webPageDismissDispose;
- (id)init;
- (void)showViewController:;
- (void)setupObservers;
- (void)setUniqueId:;
- (id)uniqueId;
- (void).cxx_destruct;
- (void)setAlert:;
- (id)alert;
- (void)setTicket:;
- (id)ticket;
- (id)nav;
+ (Class)aAWELivePodcastRegisterManagerDOUYINAdaperClass;
+ (id)sharedInstance;
@end
