@interface AWELivePreStreamViewController : UIViewController
@property (nonatomic) AWELiveElementConfig elementConfig;
@property (nonatomic) <IESLiveDI> roomDI;
@property (nonatomic) UIView<AWELivePreStreamViewProtocol> streamView;
@property (nonatomic) AWELivePreStreamCenterContainer centerContainer;
@property (nonatomic) AWELivePreStreamLeftContainer leftContainer;
@property (nonatomic) AWELivePreStreamTopContainer topContainer;
@property (nonatomic) AWELivePreStreamAlertContainer businessContainer;
@property (nonatomic) AWELivePreStreamRightContainer rightContainer;
@property (nonatomic) AWELivePreStreamBottomContainer bottomNewContainer;
@property (nonatomic) <AWELivePreStreamBizStatusService> bizStatusService;
@property (nonatomic) <AWELivePreStreamAlertElementService> alertElementService;
@property (nonatomic) <AWELivePreStreamEventService> eventService;
@property (nonatomic) AWELivePreStreamPlayer streamPlayer;
@property (nonatomic) NSObject<AWEAdPromptViewManager> promptViewManager;
@property (nonatomic) @? screenPureModeBlock;
@property (nonatomic) AWELivePreStreamContext pageContext;
@property (nonatomic) AWELivePrestreamElementDispatcher elementDispatcher;
@property (nonatomic) BOOL streamingPreloaded;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) q viewAppearState;
@property (nonatomic) NSTimer cardShowTimer;
@property (nonatomic) NSTimer cardHideTimer;
@property (nonatomic) BOOL roomEntered;
@property (nonatomic) NSDictionary couponDict;
@property (nonatomic) BOOL isLivePlayerClosed;
@property (nonatomic) BOOL isNodeOptimized;
@property (nonatomic) BOOL disableReusePlayerWhenExitRoom;
@property (nonatomic) NSDictionary extendActionParams;
@property (nonatomic) NSNumber clickArea;
@property (nonatomic) NSString adCardClickMethod;
@property (nonatomic) UIView vsWatermarkView;
@property (nonatomic) UIImageView videoPlaceholderView;
@property (nonatomic) AWELivePreStreamSEIManager preSEIManager;
@property (nonatomic) AWELivePreStreamMessageManager messageDispatchManager;
@property (nonatomic) AWELivePreStreamMessageActionCreator messageActionCreator;
@property (nonatomic) UILabel testTime;
@property (nonatomic) AWELivePreStreamEnterRoomManager enterRoomManager;
@property (nonatomic) BOOL enterByPinch;
@property (nonatomic) IESLiveEnterRoomParamModel enterRoomShowParamModel;
@property (nonatomic) UIView playerViceView;
@property (nonatomic) NSString audienceRoomId;
@property (nonatomic) BOOL quitByCloseButton;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} playerFrame;
@property (nonatomic) IESLiveKTVPreStreamContext ktvPreStreamContext;
@property (nonatomic) IESLiveDynamicBackgroundUpdater dynamicBackgroundUpdater;
@property (nonatomic) BOOL enablePlayerEvent;
@property (nonatomic) BOOL isPlayerFirstFrameZero;
@property (nonatomic) BOOL willEnterLiveRoom;
@property (nonatomic) @? enterCompletion;
@property (nonatomic) <AWELiveAudienceViewControllerDelegate> audienceDelegate;
@property (nonatomic) AWELivePreStreamContainerPlugin containerPlugin;
@property (nonatomic) AWELivePreStreamBootLoaderPlugin bootLoaderPlugin;
@property (nonatomic) <IESLivePreviewRoomService> previewRoomService;
@property (nonatomic) BOOL isPKOrMultilinkerScene;
@property (nonatomic) NSTimer demandCheckTimer;
@property (nonatomic) NSString seiUpdateTs;
@property (nonatomic) AWELivePreStreamTrackContextManager trackContext;
@property (nonatomic) IESLiveStreamDispatcherAPI streamDispatcherAPI;
@property (nonatomic) BOOL firstScreenDataHasLoad;
@property (nonatomic) AWEGradientView topGradientView;
@property (nonatomic) <AWEFeedTableViewCellProtocol> cellDelegate;
@property (nonatomic) AWELivePreStreamViewModel viewModel;
@property (nonatomic) <AWEFeedTableViewCellControllerPlayerDelegate> playerDelegate;
@property (nonatomic) <AWELivePreStreamLiveDelegate> liveDelegate;
@property (nonatomic) q indexPath;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) NSString referString;
@property (nonatomic) NSDictionary logExtraDict;
@property (nonatomic) q type;
@property (nonatomic) BOOL showInSearchResult;
@property (nonatomic) NSDictionary extTrackLog;
@property (nonatomic) @? clickBlock;
@property (nonatomic) @? enterBlock;
@property (nonatomic) NSDictionary preStreamLogExtraDict;
@property (nonatomic) NSString tabName;
@property (nonatomic) AWEAwemePageContext feedPageContext;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL enableLivePreMix;
@property (nonatomic) BOOL enablePreBootLoader;
@property (nonatomic) <AWEAwemePlayInteractionPlayDelegate><AWEAwemePlayInteractionPanelDelegate><AWEAwemePlayInteractionCommerceDelegate><AWEAwemePlayInteractionUpdateDelegate><AWEAwemePlayInteractionUIDisplayDelegate><AWEPlayInteractionViewControllerProtocol> interactionController;
@property (nonatomic) UITableViewCell<AWEFeedTableViewCellProtocol> superCell;
@property (nonatomic) UIView view;
- (void)setLogExtraDict:;
- (id)referString;
- (void)addKey:handler:;
- (void)setReferString:;
- (id)logExtraDict;
- (id)trackContext;
- (id)enterFrom;
- (id)playerDelegate;
- (void)setPlayerDelegate:;
- (void)setPureModeBlock:;
- (void)setTrackContext:;
- (void)postForKey:;
- (id)currentRoomID;
- (id)feedPageContext;
- (void)setFeedPageContext:;
- (void)removeKey:handler:;
- (void)preloadWithModel:;
- (void)removeHandlersForKey:;
- (void)setShouldReportAudioFrame:;
- (void)setSupportPictureInPictureMode:;
- (id)enterCompletion;
- (void)setEnterCompletion:;
- (BOOL)isPlayerPlaying;
- (void)setClickBlock:;
- (id)elementConfig;
- (void)setElementConfig:;
- (void)requestReuseLivePlayer:;
- (id)leftContainer;
- (id)rightContainer;
- (id)clickBlock;
- (void)audienceWillEnterLiveRoom:anchorID:;
- (void)audienceQuitByCloseButtonWithSlideVC:;
- (void)audienceDidLeaveLiveRoom:anchorID:;
- (void)audienceWillLeaveLiveRoom:;
- (void)audienceCheckLiveRoomBackOptimizeEnable:;
- (void)reloadWithModel:;
- (void)deceleratingEndToDisplay;
- (void)resetPreload;
- (void)enterLiveRoom:;
- (BOOL)enableLivePreMix;
- (void)setRightContainer:;
- (void)setLeftContainer:;
- (id)createRightContainer;
- (void)setEnterBlock:;
- (id)enterBlock;
- (long long)liveAdType;
- (id)backgroundCoverImage;
- (void)setupBinding;
- (id)promptViewManager;
- (void)setPromptViewManager:;
- (void)audiencePreQuitAllRoomWithSlideVC:player:context:;
- (void)audienceQuitAllRoomWithSlideVC:player:context:;
- (id)clickArea;
- (void)setClickArea:;
- (void)setAllUIElementsHidden:withAnimation:;
- (void)purifySurfaceViews:;
- (void)setBottomContainerOffset:;
- (void)setPreStreamLogExtraDict:;
- (void)setAutoEnterEnable:;
- (void)willBeginDragging:;
- (void)willEndDragging:velocity:;
- (void)preloadStreamABTestAI:preloadPull:interval:ignorePeakTime:;
- (void)preloadStreamABTestAIHotStart:interval:ignorePeakTime:;
- (void)preloadStreamAIStop:;
- (id)extTrackLog;
- (void)setExtTrackLog:;
- (id)topContainer;
- (void)setTopContainer:;
- (void)pauseWithCallTrace:;
- (void)p_handleAppWillResignActive;
- (void)stopWithCallTrace:;
- (void)setShouldMuted:;
- (void)correctMuteStateIfNeeded;
- (void)setShouldHiddenCoverImageView:;
- (void)setShouldHiddenGradientContainerView:;
- (void)setScaleTypeToFit:;
- (void)dislikeLiveStream;
- (void)smoothEnterPlayRemoteRoom:;
- (void)prepareForElementsDisplay;
- (void)setEnterLiveRoomCompletion:;
- (void)setAudienceViewControllerDelegate:;
- (BOOL)liveDidEnd;
- (long long)currentViewAppearState;
- (id)getPreStreamLivePlayer;
- (void)searchLiveWillEnterRoom;
- (BOOL)showInSearchResult;
- (void)setShowInSearchResult:;
- (void)setUpAdCardIfNeeded;
- (id)getLiveStatusTipView;
- (id)getLivePreStreamView;
- (void)bizDowngradeActiveLiveTask;
- (id)vsWatermarkView;
- (void)setVsWatermarkView:;
- (void)setRoomEntered:;
- (BOOL)roomEntered;
- (void)onSyncLiveUserNotification:;
- (void)setAudienceDelegate:;
- (id)streamPlayer;
- (void)setStreamPlayer:;
- (id)streamView;
- (void)startMessageIfNeed;
- (void)setMessageActionCreator:;
- (id)messageActionCreator;
- (void)loadNewMessageActionCreator;
- (void)onStartLeaveRoomAnimation;
- (id)roomDI;
- (id)audienceDelegate;
- (void)stopAndResetMessage;
- (id)bizStatusService;
- (void)setBizStatusService:;
- (id)commonTrackContext;
- (BOOL)enableLandscapeInRoom;
- (void)onMessageReceivce:withDict:;
- (BOOL)isPlayerFirstFrameZero;
- (void)setIsPlayerFirstFrameZero:;
- (void)setIsPKOrMultilinkerScene:;
- (id)aAWELiveModuleServiceDOUYINLiteAdaper;
- (double)bottomContainerBottomOffSet;
- (long long)transToRoomSceneWithRoom:;
- (BOOL)supportScene:;
- (BOOL)isPKOrMultilinkerScene;
- (BOOL)couldDisableLandscapeMission;
- (void)onReceiveSEI:;
- (id)aAWELiveModuleServiceDOUYINAdaper;
- (void)clickEnterLiveRoom:;
- (BOOL)isOldStyle;
- (BOOL)prestreamMuteShow;
- (BOOL)prestreamMuteExpand;
- (BOOL)enablePreLiteInteraction;
- (BOOL)enablePreHorizontalContainer;
- (BOOL)enablePreEnterRoom;
- (void)trackPreviewModuleShow:;
- (void)trackPreviewModuleClick:;
- (void)setupPreviewInteractStatus;
- (BOOL)enablePreBootLoader;
- (id)playerFrame;
- (id)elementDispatcher;
- (void)setWillEnterLiveRoom:;
- (id)bootLoaderPlugin;
- (id)containerPlugin;
- (id)enterRoomManager;
- (void)setStreamView:;
- (void)p_loadEnterRoomServiceIfNeeded;
- (void)p_registerNotificationObservers;
- (void)tryReShowSmoothQuitPlayerWithContext:;
- (void)setDisableReusePlayerWhenExitRoom:;
- (BOOL)disableReusePlayerWhenExitRoom;
- (void)setQuitByCloseButton:;
- (void)setAudienceRoomId:;
- (void)p_hideTopGradientViewIfNeed;
- (long long)viewAppearState;
- (BOOL)p_checkCellPageAppearState;
- (void)setStreamingPreloaded:;
- (void)setIsLivePlayerClosed:;
- (id)audienceRoomId;
- (BOOL)isNodeOptimized;
- (void)setIsNodeOptimized:;
- (BOOL)streamingPreloaded;
- (void)setScreenPureModeBlock:;
- (void)setContainerPlugin:;
- (id)screenPureModeBlock;
- (void)setViewAppearState:;
- (BOOL)willEnterLiveRoom;
- (id)alertElementService;
- (void)setAlertElementService:;
- (void)setEnterRoomManager:;
- (void)setPlayerFrame:;
- (void)p_handleAppWillEnterForeground;
- (void)p_handleAppDidEnterBackground;
- (void)p_handleAppDidBecomeActive;
- (void)p_handleAppWillTerminate;
- (BOOL)isLivePlayerClosed;
- (void)willSetupBootLoaderWithLiveRoom:;
- (void)uninstallBootLoaderByLeavePageTimeOut;
- (id)preStreamLogExtraDict;
- (void)setRoomDI:;
- (void)setElementDispatcher:;
- (void)setBootLoaderPlugin:;
- (id)previewRoomService;
- (void)setPreviewRoomService:;
- (void)addWatermark;
- (void)handleCardDidClickToOpenLiveRoomInStream:;
- (void)p_fetchBalanceToCouponStateIfNeeded:;
- (void)setCouponDict:;
- (void)setAdCardClickMethod:;
- (id)couponDict;
- (id)adCardClickMethod;
- (void)setCardHideTimer:;
- (void)setCardShowTimer:;
- (id)cardShowTimer;
- (id)cardHideTimer;
- (id)videoPlaceholderView;
- (void)setVideoPlaceholderView:;
- (void)removeRoomBackOptimizeIfNeeded;
- (void)showRoomBackOptimizeIfNeeded;
- (BOOL)liveRoomBackOptimizeEnable;
- (BOOL)liveRoomBackShouldShowViceView;
- (void)setPlayerViceView:;
- (BOOL)liveRoomModeEnable;
- (BOOL)quitByCloseButton;
- (void)showPlayerViceViewIfNeeded;
- (void)removePlayerViceView;
- (id)playerViceView;
- (void)refreshExtendInfo;
- (void)setBusinessContainer:;
- (id)businessContainer;
- (void)setBottomNewContainer:;
- (id)bottomNewContainer;
- (void)setEnterByPinch:;
- (void)setExtendActionParams:;
- (void)p_addParams:toLiveLogModelEcomLiveParams:;
- (id)ktvPreStreamContext;
- (void)setKtvPreStreamContext:;
- (void)setSeiUpdateTs:;
- (id)seiUpdateTs;
- (id)preSEIManager;
- (void)loadPreSEIManagerIfNeed;
- (void)loadPreMessageDispatcherManagerIfNeed;
- (void)configMessageIfNeed;
- (void)setPreSEIManager:;
- (id)messageDispatchManager;
- (void)setMessageDispatchManager:;
- (void)p_monitorLayoutOnEnter;
- (void)p_handleDisableTemplateMessage:;
- (void)requestWithRandom:Data:;
- (void)handleControlParams:;
- (int)shuffleTime:upper:;
- (id)pr_convertToDict:;
- (void)sendToPlayerProvider:;
- (id)pr_convertToDict:error:;
- (void)preloadStreamABTestStrategy:;
- (id)demandCheckTimer;
- (void)setDemandCheckTimer:;
- (void)bandWidthOptPreloadStreamIsAiPreload:interval:;
- (void)invalidateDemandCheckTimer;
- (void)pr_dealWithPlayer:;
- (void)closeLivePlayerWithToken:isEnqueuePlayer:;
- (id)testTime;
- (id)dynamicBackgroundUpdater;
- (void)configUserInteractionMonitor:;
- (long long)cellContainerAppearState;
- (void)loadBizStatusServiceIfNeed;
- (void)loadEventServiceIfNeed;
- (void)loadAlertElementServiceIfNeed;
- (BOOL)optimizeEnterOfficialChannelRoom;
- (void)removeVideoPlaceholderView;
- (void)p_prepareForReuse;
- (void)createDynamicBackgroundUpdater;
- (void)recordSelectTimesWithItemID:;
- (id)previewSelectTimesWithItemID:;
- (void)enterLiveRoomEnded;
- (id)createBottomNewContainer;
- (void)deployStreamPlayer;
- (void)initSet;
- (void)preloadStreamWithModel:interval:callTrace:;
- (void)setupVideoPlaceholderView;
- (id)preProcessPlayerBeforeEnterLiveRoom:;
- (id)userFeedbackDataForRoom;
- (id)p_clickExtendArea:;
- (void)enterLiveRoom_new:;
- (void)old_enterLiveRoom:;
- (void)enterRoomInNormalTab:roomID:enterPosition:withPlayer:;
- (id)extendActionParams;
- (BOOL)enterByPinch;
- (id)enterRoomShowParamModel;
- (void)buildParamsForCouponExchange:enterPosition:clickParams:;
- (void)buildParamsForCouponGetUseOptimize:enterPosition:;
- (void)startDynamicBackgroundUpdater;
- (void)setEnablePlayerEvent:;
- (BOOL)enablePlayerEvent;
- (void)loadTestTime:;
- (void)setStreamDispatcherAPI:;
- (void)initContainer;
- (void)dealWithGroupLiveWithMetaInfo:;
- (void)p_handleStreamControlMessage:dict:;
- (id)streamDispatcherAPI;
- (void)showEnterOtherRoomDialog:roomID:enterPosition:withPlayer:;
- (void)enterRoomInFollowTab:enterPosition:withPlayer:;
- (void)setTestTime:;
- (void)setEnterRoomShowParamModel:;
- (BOOL)firstScreenDataHasLoad;
- (void)setFirstScreenDataHasLoad:;
- (void)setModel:;
- (void)viewWillDisappear:;
- (id)interactionView;
- (id)init;
- (BOOL)isShowing;
- (void)dealloc;
- (void)play;
- (void)setVolume:;
- (id)initWithConfig:;
- (void)viewDidLayoutSubviews;
- (long long)indexPath;
- (id)viewModel;
- (void)viewDidLoad;
- (void)prepareForDisplay;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (id)contentView;
- (long long)type;
- (void)setIndexPath:;
- (id)connectionInfo;
- (void)viewDidDisappear:;
- (id)model;
- (void)setType:;
- (void)setEventService:;
- (void)viewWillAppear:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)reset;
- (id)eventService;
- (void)stop;
- (void)pause;
- (id)interactionController;
- (void)setupUI;
- (id)cellDelegate;
- (void)configureWithModel:;
- (void)setCellDelegate:;
- (void)didEndDisplaying;
- (void)setPageContext:;
- (id)pageContext;
- (id)tabName;
- (void)setTabName:;
- (id)topGradientView;
- (void)setTopGradientView:;
- (void)setIsShowing:;
- (id)centerContainer;
- (void)setCenterContainer:;
- (id)liveDelegate;
- (void)setLiveDelegate:;
+ (Class)aAWELiveModuleServiceDOUYINAdaperClass;
+ (Class)aAWELiveModuleServiceDOUYINLiteAdaperClass;
@end
