@interface AWEMVChannelLiveCardCell : AWEMVChannelBaseCell
@property (nonatomic) <AWELiveStreamPlayer> playerController;
@property (nonatomic) AWEMVChannelLiveCardBottomView bottomInfoView;
@property (nonatomic) AWEGradientView livingContainerView;
@property (nonatomic) UILabel livingLabel;
@property (nonatomic) AWEMVChannelLiveCardPaidTagView paidTagView;
@property (nonatomic) AWEMVChannelLiveCardRoomStatsView statsView;
@property (nonatomic) UIButton volumeSwitch;
@property (nonatomic) BOOL isSmoothEnterRoom;
@property (nonatomic) q viewRight;
@property (nonatomic) double startPlayerTime;
@property (nonatomic) <AWELiveVSMessageService> messageService;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL isActive;
@property (nonatomic) AWEMVChannelAutoPlayHandler autoPlayHandler;
- (id)ticketType;
- (void)setupSubViews;
- (void)player:loadStateDidChange:;
- (void)player:playbackStateDidChange:;
- (long long)viewRight;
- (void)setViewRight:;
- (id)autoPlayHandler;
- (void)setAutoPlayHandler:;
- (void)updateVolumeSwitch;
- (void)trialTimeDidChange:;
- (void)viewStatusDidChange:hasShareTickets:;
- (id)customTrialView;
- (id)customTrialContainerView;
- (double)startPlayerTime;
- (void)setStartPlayerTime:;
- (void)configWithAwemeModel:context:;
- (void)installMessageChannel;
- (void)uninstallMessageChannel;
- (id)messageService;
- (void)setMessageService:;
- (void)onMessageReceivce:messageStr:;
- (id)livingContainerView;
- (id)livingLabel;
- (void)setLivingContainerView:;
- (void)setLivingLabel:;
- (void)updatePaidTagType:;
- (BOOL)isPaidLive;
- (BOOL)isVerticalStream;
- (id)livingTagText;
- (id)livingViewGradientColors;
- (id)coverImageURLArray;
- (void)makePlayerControllerLayout;
- (void)trackLiveEvent:extraParams:;
- (void)trackLiveShowReport;
- (long long)currentPaidTagType;
- (BOOL)playerShouldMute;
- (id)liveCommonParams;
- (void)handleResponseClicked;
- (id)paidTagView;
- (id)mediumCommonParams;
- (void)willDisplayWithIndex:;
- (void)setPaidTagView:;
- (id)bottomInfoView;
- (id)statsView;
- (id)volumeSwitch;
- (void)makeSubViewsLayout;
- (void)setIsSmoothEnterRoom:;
- (void)trackLiveSdkDuration;
- (id)playerControllerLogExtraDict;
- (void)handleClickVolumeSwitch;
- (BOOL)isSmoothEnterRoom;
- (void)setBottomInfoView:;
- (void)setStatsView:;
- (void)setVolumeSwitch:;
- (void)didBecomeActive;
- (void)setIsActive:;
- (void)play;
- (void)setPlayerController:;
- (void)prepareForReuse;
- (void)didResignActive;
- (id)initWithFrame:;
- (id)identifier;
- (id)playerController;
- (void).cxx_destruct;
- (BOOL)isActive;
- (void)stop;
- (void)pause;
- (id)activeView;
- (void)resetPlayer;
@end
