@interface AWEMVChannelTracker : NSObject
@property (nonatomic) AWEMVChannelPageContext context;
- (id)aAWEPadModuleAdapter;
- (id)beginToTrackCurrentChannelWithAction:;
- (void)trackPadChannelRefreshWithMonitor:;
- (void)trackStayTime:;
- (void)trackCardAnchorShowWithModel:;
- (id)cardNameWithType:;
- (id)liveRoomStatusWithModel:;
- (BOOL)isVSScene:;
- (id)commonParamsWithModel:;
- (void)trackBackToTabWithEnterFrom:;
- (void)trackMediumvideoClientClickWithModel:cardType:logExtra:;
- (void)trackMediumvideoClientShowWithModel:cardType:index:;
- (void)trackMediumvideoUGShowWithModel:;
- (void)trackMediumvideoClientShowWithModel:cardType:index:extraLog:;
- (void)trackLoadMoreData:result:;
- (void)trackMediumVideoClientHoldPanelShowWithModel:cardType:extraDict:;
- (id)feedCacheParams;
- (void)trackCachePreloadVideo:;
- (void)trackMediumVideoClientGuideWithModel:;
- (void)trackMediumVideoClientCoverPlayWithModel:costTime:;
- (void)trackRefreshDataWithMethod:result:;
- (void)trackFirstScreenStayTime:;
- (void)trackRefreshData:result:;
- (void)trackSlideWithDirection:;
- (void)trackMediumVideoTabSortSuccessWithTabOrder:;
- (void)trackCacheVisibility:;
- (void)trackBannerCloseWithModel:banner:bannerIndex:;
- (id)initWithContext:;
- (void)setContext:;
- (void).cxx_destruct;
- (id)context;
+ (Class)aAWEPadModuleAdapterClass;
+ (id)trackParamsForVideoInflowWithModel:;
+ (id)trackParamsForLiveInflowWithModel:;
+ (long long)followTagWithFollowStatus:;
+ (id)idFromModel:;
+ (id)dataTypeWithModel:;
+ (id)logExtraWithCellClick:viewModel:;
@end
