@interface AWEMusicLunaGuideBubble : UIView
@property (nonatomic) UIImageView lunaImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel subTitleLabel;
@property (nonatomic) UIButton mainBtn;
@property (nonatomic) UIButton closeBtn;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subTitle;
@property (nonatomic) NSString mainBtnName;
@property (nonatomic) @? closeAction;
@property (nonatomic) @? maiBtnTappedAction;
- (id)closeBtn;
- (void)setCloseBtn:;
- (void)closeBtnTapped:;
- (id)lunaImageView;
- (id)mainBtn;
- (void)closeBtnTapped_IMP:;
- (void)mainBtnTapped_IMP:;
- (id)maiBtnTappedAction;
- (void)mainBtnTapped:;
- (void)setMainBtnName:;
- (id)mainBtnName;
- (void)setMaiBtnTappedAction:;
- (void)setLunaImageView:;
- (void)setMainBtn:;
- (void)setCloseAction:;
- (id)initWithFrame:;
- (void)setup;
- (void)setSubTitle:;
- (id)subTitle;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)title;
- (id)titleLabel;
- (id)closeAction;
- (void)setTitle:;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
@end
