@interface AWEMediaDownloadCommonTask : AWEMediaDownloadTask
@property (nonatomic) AWEMediaDownloadLoadingView loadingView;
@property (nonatomic) AWEUILoadingView afdLoadingView;
- (void)downloadStageWillRun:;
- (void)downloadStage:didFinishWithResult:error:;
- (void)updateErrorMessageWithResult:error:;
- (void)tapticWithResult:;
- (void)setupStagesWithType:;
- (void)setupLoadingView;
- (void)handleProgressChange:;
- (void)showToastStartDownloadAdsVideo;
- (void)trackDownloadPopupShow;
- (void)trackDownloadStartTime;
- (void)trackDownloadWaringPopupShow;
- (void)trackDownloadEndTimeWithStageResult:error:;
- (void)trackFinishDownloadWithError:;
- (void)trackNeedWaterMarkAfterDownload;
- (void)trackDownloadNoWatermarkWithError:;
- (void)trackFinishWaterMarkWithError:;
- (void)trackDownloadWarningPopupContinue;
- (void)trackDownloadWaringPopupCancel;
- (BOOL)isNewTrackerSwitchOn;
- (void)_trackDownloadWarningBuilder:;
- (void)trackTaskDoneWithItem:;
- (void)trackTaskFailWithItem:error:;
- (void)trackTaskCancelWithItem:isDownloading:;
- (void)trackFinishDownloadWithStatus:error:;
- (void)trackStageWillRun:;
- (void)trackStageFinish:stageResult:error:;
- (void)_trackMuteDownloadWarningBuilder:;
- (void)trackDownloadFailBannerShow;
- (void)trackTaskFinishWithItem:result:error:;
- (void)insertStage:beforeStage:;
- (void)insertStage:afterStage:;
- (BOOL)p_isCloseFriendsShare;
- (void)setAfdLoadingView:;
- (id)afdLoadingView;
- (void)setLoadingView:;
- (void)finishWithResult:error:;
- (id)loadingView;
- (id)initWithOptions:;
- (void).cxx_destruct;
+ (id)taskWithModel:options:;
@end
