@interface AWEMusicPlayerActionView : UIView
@property (nonatomic) AWEMusicStreamingButton loopButton;
@property (nonatomic) AWEMusicStreamingButton queueButton;
@property (nonatomic) AWEMusicStreamingButton preButton;
@property (nonatomic) AWEMusicStreamingButton nextButton;
@property (nonatomic) AWEMusicStreamingButton playButton;
@property (nonatomic) BOOL isSingle;
@property (nonatomic) BOOL isPlaying;
@property (nonatomic) <AWEMusicPlayerActionViewDelegate> delegate;
@property (nonatomic) BOOL playingStatus;
@property (nonatomic) Q loopMode;
@property (nonatomic) NSString loopModeAccessibilityLabel;
- (void)setPlayStatus:;
- (unsigned long long)loopMode;
- (void)setLoopMode:;
- (void)setLoopStatus:;
- (void)setLoopModeAccessibilityLabel:;
- (void)setPlayingStatus:;
- (BOOL)isPlayingStatus;
- (void)setLoopButton:;
- (id)loopButton;
- (void)setQueueButton:;
- (id)queueButton;
- (void)setPreButton:;
- (id)preButton;
- (void)setButton:imageName:;
- (void)loopButtonTapped:;
- (void)queueButtonTapped:;
- (void)preButtonTapped:;
- (void)setIsSingle:;
- (BOOL)isSingle;
- (void)loopButtonTapped_IMP:;
- (void)preButtonTapped_IMP:;
- (void)nextButtonTapped_IMP:;
- (void)playButtonTapped_IMP:;
- (void)queueButtonTapped_IMP:;
- (id)loopModeAccessibilityLabel;
- (BOOL)isPlaying;
- (id)delegate;
- (id)initWithFrame:;
- (void)setup;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)layoutSubviews;
- (void)setIsPlaying:;
- (id)nextButton;
- (void)setNextButton:;
- (id)playButton;
- (void)nextButtonTapped:;
- (void)setPlayButton:;
- (void)playButtonTapped:;
@end
