@interface AWEMultipleSelectionDislikePanelViewController : UIViewController
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) NSDictionary trackExtra;
@property (nonatomic) UIView videoInfoView;
@property (nonatomic) UIImageView videoThumb;
@property (nonatomic) UILabel tipLabel;
@property (nonatomic) UITableView tableView;
@property (nonatomic) DUXDivider line;
@property (nonatomic) DUXButton submitButton;
@property (nonatomic) DUXButton closeButton;
@property (nonatomic) NSMutableArray selectedInfos;
@property (nonatomic) <AWEMultipleSelectionDislikePanelViewControllerDelegate> selectDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeModel;
- (void)setAwemeModel:;
- (id)dux_sheetShouldRecognizeAsynchronousWithGestures;
- (id)dux_titleForColoseButton;
- (id)trackExtra;
- (void)setTrackExtra:;
- (void)setSelectDelegate:;
- (id)selectDelegate;
- (void)didClickedSubmit;
- (void)hideLine:;
- (void)stateDidChanged:checked:;
- (void)didClickedClose;
- (id)videoThumb;
- (void)setVideoThumb:;
- (id)videoInfoView;
- (void)configVideoImage:;
- (id)getDislikeInfoWithIndexPath:;
- (void)addSelectedInfo:;
- (void)deselectedInfo:;
- (id)selectedInfos;
- (id)initWithData:trackExtra:;
- (void)setVideoInfoView:;
- (void)setSelectedInfos:;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (long long)numberOfSectionsInTableView:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)viewDidLoad;
- (id)tableView;
- (id)line;
- (void).cxx_destruct;
- (double)tableView:heightForRowAtIndexPath:;
- (void)setLine:;
- (void)setTipLabel:;
- (void)tableView:didDeselectRowAtIndexPath:;
- (id)tipLabel;
- (void)setupUI;
- (void)setCloseButton:;
- (id)closeButton;
- (void)setSubmitButton:;
- (id)submitButton;
@end
