@interface AWEMusicStreamingImpl.LunaShareInfoResponse : AWEMusicStreamingImpl.LunaBaseApiResponseModel
@property (nonatomic) NSString shareTitle;
@property (nonatomic) NSString shareDesc;
@property (nonatomic) NSString shareLink;
@property (nonatomic) _TtC21AWEMusicStreamingImpl11LunaURLInfo shareCover;
@property (nonatomic) NSString shareWeiboDesc;
@property (nonatomic) NSString shareLinkDesc;
@property (nonatomic) NSString systemShareLink;
@property (nonatomic) _TtC21AWEMusicStreamingImpl15ShareDouyinInfo shareDouyinInfo;
@property (nonatomic) NSString shareDouyinTitle;
@property (nonatomic) NSString shortShareLink;
@property (nonatomic) NSString commonShareDesc;
- (void)setShareWeiboDesc:;
- (void)setShareDesc:;
- (void)setShareTitle:;
- (void)setShareLinkDesc:;
- (id)shareDesc;
- (id)shareLink;
- (void)setShareLink:;
- (id)shareCover;
- (void)setShareCover:;
- (id)shareWeiboDesc;
- (id)shareLinkDesc;
- (id)systemShareLink;
- (void)setSystemShareLink:;
- (id)shareDouyinInfo;
- (void)setShareDouyinInfo:;
- (id)shareDouyinTitle;
- (void)setShareDouyinTitle:;
- (id)shortShareLink;
- (void)setShortShareLink:;
- (id)commonShareDesc;
- (void)setCommonShareDesc:;
- (id)initWithDictionary:error:;
- (id)init;
- (void).cxx_destruct;
- (id)initWithCoder:;
- (id)shareTitle;
+ (id)shareCoverJSONTransformer;
+ (id)shareDouyinInfoJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
