@interface AWEMiniLunaMyCollectionViewModel : NSObject
@property (nonatomic) NSArray sectionViewModelArray;
@property (nonatomic) AWEMiniLunaPlaylistSectionViewModel createdPlaylistSectionModel;
@property (nonatomic) AWEMiniLunaPlaylistSectionViewModel collectedPlaylistSectionModel;
@property (nonatomic) AWEMiniLunaPlaylistSectionViewModel dailyPlaylistSectionModel;
@property (nonatomic) AWEMusicCollectionLunaBannerSectionViewModel lunaBannerSectionModel;
@property (nonatomic) BOOL isCurrentUser;
@property (nonatomic) NSString createdPlaylistCursor;
@property (nonatomic) NSString collectedPlaylistCursor;
@property (nonatomic) q totalCount;
@property (nonatomic) q requestCount;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) AWEUserModel userModel;
@property (nonatomic) NSMutableArray recommendBackupPool;
@property (nonatomic) q recommendRetryCount;
@property (nonatomic) BOOL hasShownLunaBanner;
@property (nonatomic) AWEMiniLunaPlaylistPagingFetcher fetcher;
@property (nonatomic) AWEMusicStreamingQueueHandler queueHandler;
@property (nonatomic) BOOL hasMoreSong;
@property (nonatomic) NSNumber cursor;
@property (nonatomic) NSString purchId;
@property (nonatomic) <AWEMiniLunaMyCollectionViewModelDelegate> delegate;
@property (nonatomic) BOOL refreshFooterHidden;
@property (nonatomic) BOOL canAutoPlayPlaylist;
@property (nonatomic) NSString secUserID;
@property (nonatomic) NSString userName;
@property (nonatomic) AWECollectDiversionModel collectDiversionInfo;
@property (nonatomic) AWEMusicDSPEventModel eventModel;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) Q highlightPlaylistCategory;
@property (nonatomic) AWEMusicPlayerQueue queue;
@property (nonatomic) AWEMiniLunaPlaylistInfoModel currentAutoPlayingPlaylist;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)secUserID;
- (void)setSecUserID:;
- (void)setEnterFrom:;
- (id)enterFrom;
- (id)sectionViewModelArray;
- (void)setSectionViewModelArray:;
- (BOOL)hasMoreOfScene:;
- (void)loadMoreScene:responseBlock:completion:;
- (id)eventModel;
- (void)setEventModel:;
- (void)playlistModelChangedWithType:changeModels:from:;
- (void)setHighlightPlaylistCategory:;
- (void)setCanAutoPlayPlaylist:;
- (BOOL)canAutoPlayPlaylist;
- (unsigned long long)highlightPlaylistCategory;
- (id)queueHandler;
- (id)pageEventParams;
- (BOOL)hasMoreSong;
- (void)requestPlaylistsWithCompletion:;
- (void)requestAutoPlayInfoWithCompletion:;
- (BOOL)refreshFooterHidden;
- (id)indexPathForlunaLikePlaylistCellInTableView:;
- (id)collectDiversionInfo;
- (id)playlistModelAtIndexPath:;
- (void)deletePlaylistAtIndexPath:completion:;
- (void)deletePlaylist:completion:;
- (id)p_makePlaylistSectionViewModelWithType:;
- (id)createdPlaylistSectionModel;
- (id)collectedPlaylistSectionModel;
- (id)dailyPlaylistSectionModel;
- (void)p_remakeSections;
- (id)lunaBannerSectionModel;
- (void)addPlaylist:toType:;
- (id)deletePlaylist:toType:;
- (void)updatePlaylist:;
- (void)updateCollectionPlaylist:;
- (BOOL)p_isLynxBanner;
- (void)setPurchId:;
- (id)purchId;
- (void)p_trackLunaBannerDidClicked;
- (void)p_trackLunaBannerShown;
- (BOOL)p_canShowBanner;
- (id)p_makeLunaBannerSectionViewModel:;
- (void)setLunaBannerSectionModel:;
- (void)p_handleResponse:error:completion:;
- (id)currentAutoPlayingPlaylist;
- (void)setCurrentAutoPlayingPlaylist:;
- (void)setHasMoreSong:;
- (void)setRefreshFooterHidden:;
- (void)setCollectDiversionInfo:;
- (void)setCreatedPlaylistSectionModel:;
- (void)setCollectedPlaylistSectionModel:;
- (void)setDailyPlaylistSectionModel:;
- (id)createdPlaylistCursor;
- (void)setCreatedPlaylistCursor:;
- (id)collectedPlaylistCursor;
- (void)setCollectedPlaylistCursor:;
- (id)recommendBackupPool;
- (void)setRecommendBackupPool:;
- (long long)recommendRetryCount;
- (void)setRecommendRetryCount:;
- (BOOL)hasShownLunaBanner;
- (void)setHasShownLunaBanner:;
- (id)cursor;
- (void)setRequestCount:;
- (long long)requestCount;
- (id)delegate;
- (long long)totalCount;
- (void)setQueue:;
- (void)setHasMore:;
- (id)userName;
- (BOOL)hasMore;
- (void)setCursor:;
- (BOOL)isEmpty;
- (void)setUserModel:;
- (void).cxx_destruct;
- (id)initWithUserModel:;
- (id)userModel;
- (id)queue;
- (void)setDelegate:;
- (id)fetcher;
- (void)setUserName:;
- (BOOL)tableView:canEditRowAtIndexPath:;
- (BOOL)isCurrentUser;
- (void)setIsCurrentUser:;
- (void)setFetcher:;
- (void)setTotalCount:;
@end
