@interface AWEMixVideoPanelDetailTableViewContainerController : UIViewController
@property (nonatomic) AWEMixVideoPanelDetailTableViewController tableViewController;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q transition_playStateBeforeViewWillDisappear;
@property (nonatomic) UIViewController<AWEAwemeDetailTableViewControllerProtocol> detailTableController;
- (void)transition_didPopDoneTransitionWithContext:;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (BOOL)transition_shouldStartInteractiveTranstionForSlideDirection:gestureRecognizer:;
- (void)transition_didStartTransitionWithContext:;
- (BOOL)transition_gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (id)awe_preferredTransitionProviderClassNameForContext:;
- (id)transition_destinatedViewControllerForSlideDirection:gestureRecognizer:;
- (BOOL)transition_enableCustomActionForSlideDirection:gestureRecognizer:;
- (void)transition_performCustomActionForSlideDirection:gestureRecognizer:;
- (id)transition_directlyPresentingViewController;
- (BOOL)transition_shouldStartInteractiveTranstionToVC:;
- (void)transition_didCancelPercentDrivenTransitionWithContext:;
- (id)initWithDataController:initialIndex:referString:logExtraDict:;
- (id)transition_contextProviderTopLevelView:changeRectBlock:;
- (id)initWithAwemeModel:referString:logExtraDict:;
- (id)detailTableController;
- (id)aAWEPadMixVideoImmersiveAdapter;
- (id)transition_videoController;
- (BOOL)transition_shouldFixPlayerControllerForFromModel:toModel:;
- (void)transition_scrollToPlayerControllerWithFromModel:;
- (id)transition_bottomMoveView;
- (id)transition_alphaViewArray;
- (id)transition_interactionController;
- (void)transition_customAnimateDidFinishWithVideoController:;
- (BOOL)transition_isMoveFromVC;
- (long long)transition_playStateBeforeViewWillDisappear;
- (void)setTransition_playStateBeforeViewWillDisappear:;
- (id)aAWEPadMixVideoRotateAdapter;
- (id)aAWEMixVideoPanelDetailTableViewControllerAdapter;
- (void)viewWillDisappear:;
- (id)init;
- (id)forwardingTargetForSelector:;
- (void)viewDidLoad;
- (BOOL)respondsToSelector:;
- (BOOL)conformsToProtocol:;
- (long long)preferredStatusBarStyle;
- (void).cxx_destruct;
- (void)forwardInvocation:;
- (void)viewDidAppear:;
- (id)methodSignatureForSelector:;
- (void)setTableViewController:;
- (id)tableViewController;
+ (Class)aAWEPadMixVideoImmersiveAdapterClass;
+ (Class)aAWEPadMixVideoRotateAdapterClass;
+ (Class)aAWEMixVideoPanelDetailTableViewControllerAdapterClass;
@end
