@interface AWEModernFeedTagFrame : NSObject
@property (nonatomic) q currentTagType;
@property (nonatomic) BOOL shouldShowPOIEntrance;
@property (nonatomic) BOOL isFromSearch;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} iconFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} titleFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} arrowFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} lineFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} ironManFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} tagFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} poiFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} platformFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} shoppingCartBtnFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} stickerFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} mvFrame;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} goodsSeedingFrame;
@property (nonatomic) UIFont markButtonsFont;
@property (nonatomic) AWEAwemeModel aweme;
@property (nonatomic) AWEFeedVideoSingleCardLayoutAdjuster layoutAdjuster;
@property (nonatomic) AWEFeedVideoCardQualityLayoutAdjuster qualityLayoutAdjuster;
- (id)aweme;
- (void)setAweme:;
- (BOOL)shouldShowShoppingEntrance;
- (BOOL)isUseNativeAnchor;
- (BOOL)shouldShowPoiButton;
- (BOOL)isFromSearch;
- (void)setIsFromSearch:;
- (id)tagFrame;
- (BOOL)shouldShowIronManButton;
- (BOOL)shouldShowStickerButton;
- (BOOL)shouldShowMvButton;
- (BOOL)shouldShowPlatfromButton;
- (BOOL)shouldShowTagView;
- (void)configFrameWithAweme:containerWidth:leftMargin:rightMargin:;
- (void)configFrameWithAweme:containerWidth:leftMargin:rightMargin:showPOIEntrance:;
- (void)setTagFrameWidth:;
- (void)setTagFrame:;
- (void)setShouldShowPOIEntrance:;
- (long long)getCurrentModernFeedTagType;
- (void)setCurrentTagType:;
- (long long)currentTagType;
- (double)feedTagHeight;
- (void)setMvFrame:;
- (void)setPlatformFrame:;
- (void)setPoiFrame:;
- (void)setShoppingCartBtnFrame:;
- (void)setIronManFrame:;
- (void)setStickerFrame:;
- (void)setGoodsSeedingFrame:;
- (id)markButtonsFont;
- (id)shoppingCartBtnFrame;
- (id)ironManFrame;
- (id)platformFrame;
- (id)poiFrame;
- (id)mvFrame;
- (id)stickerFrame;
- (BOOL)canShowIronManButton;
- (BOOL)canShowShoppingEntrance;
- (BOOL)canShowPlatfromButton;
- (BOOL)canShowStickerButton;
- (BOOL)canShowMvButton;
- (BOOL)shouldShowPOIEntrance;
- (BOOL)canShowGoodsSeedingEntrance;
- (void)setIconFrame:;
- (id)arrowFrame;
- (void)setArrowFrame:;
- (id)lineFrame;
- (void)setLineFrame:;
- (id)goodsSeedingFrame;
- (void)setMarkButtonsFont:;
- (void)setQualityLayoutAdjuster:;
- (id)qualityLayoutAdjuster;
- (id)layoutAdjuster;
- (void)setLayoutAdjuster:;
- (BOOL)shouldShowNormalTagView;
- (void)adjusterQualityFrameWithWidth:;
- (double)adjustAnchorButtonWidthWithTextLength:hasVerticalLine:;
- (BOOL)p_showShowTitleTagOfStickerAnchorWithAwemeModel:;
- (id)iconFrame;
- (id)init;
- (void).cxx_destruct;
- (id)titleFrame;
- (void)setTitleFrame:;
@end
