@interface AWEMessageReachPopViewAccessManager : NSObject
@property (nonatomic) <AWEPzEngineProtocol> popViewEngine;
@property (nonatomic) NSMutableArray activatedPopViews;
@property (nonatomic) AWEMRAlertMigrateTracker alertTracker;
@property (nonatomic) NSMapTable didTrackShowRecordMap;
@property (nonatomic) MMKV mmkv;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setMmkv:;
- (id)mmkv;
- (id)interceptorActionBeforeTrackWithContext:;
- (void)interceptorActionAfterCanShowCheck:completion:;
- (void)registerAlertInterceptor;
- (void)triggerAccessForceAlert:forEventItem:completion:;
- (void)initAccessManager;
- (void)trackAlertTerminateIfNeeded;
- (BOOL)enableAccessControl:;
- (void)popViewPizzaComponentVerify:completion:;
- (id)popViewEngine;
- (void)forceAlertTrigger:forEventItem:completion:;
- (id)createPzComponentConfigModel:cTags:;
- (id)activatedPopViews;
- (id)alertTracker;
- (BOOL)isTaskIDValid:;
- (void)removeDidTrackShowRecordForKey:;
- (id)didTrackShowRecordMap;
- (void)storeDidTrackShowRecords;
- (void)alertTaskWillShowWithContext:;
- (void)alertTaskDidShowWithContext:;
- (void)alertTaskDidClickWithContext:clickInfo:;
- (void)alertTaskDidHideWithContext:didShow:;
- (void)forceAlertWillShowWithContext:;
- (void)forceAlertDidShowWithContext:;
- (void)forceAlertDidCloseWithContext:didShow:;
- (id)forceAlertTrackParamsWithContext:;
- (id)getPopViewEngine;
- (BOOL)isAccessIDValid:;
- (void)setDidTrackShowRecordForKey:trackParams:;
- (void)setPopViewEngine:;
- (void)setActivatedPopViews:;
- (void)setAlertTracker:;
- (void)setDidTrackShowRecordMap:;
- (void).cxx_destruct;
+ (id)shareInstance;
@end
