@interface AWEMusicFeedETModel : MTLModel
@property (nonatomic) BOOL isPlaylistScene;
@property (nonatomic) NSString authorId;
@property (nonatomic) NSString musicId;
@property (nonatomic) NSString songGroupId;
@property (nonatomic) NSString playlistID;
@property (nonatomic) BOOL hasLyrics;
@property (nonatomic) BOOL isVideo;
@property (nonatomic) NSString mediaType;
@property (nonatomic) NSString metaSongId;
@property (nonatomic) NSDictionary trackParams;
@property (nonatomic) double playedDuration;
@property (nonatomic) NSString queueName;
@property (nonatomic) NSString queueType;
@property (nonatomic) NSString sceneName;
@property (nonatomic) NSString sourceType;
@property (nonatomic) NSString videoId;
@property (nonatomic) NSString requestId;
@property (nonatomic) NSString groupId;
@property (nonatomic) NSString groupType;
@property (nonatomic) NSString fromGroupId;
@property (nonatomic) NSString fromGroupType;
@property (nonatomic) NSString artistId;
- (id)trackParams;
- (void)setTrackParams:;
- (void)setMusicId:;
- (void)setFromGroupId:;
- (id)musicId;
- (void)setMetaSongId:;
- (void)setArtistId:;
- (void)setPlaylistID:;
- (id)fromGroupId;
- (double)playedDuration;
- (void)setPlayedDuration:;
- (id)metaSongId;
- (void)setFromGroupType:;
- (id)songGroupId;
- (BOOL)isPlaylistScene;
- (void)setIsPlaylistScene:;
- (id)fromGroupType;
- (id)artistId;
- (void)setSongGroupId:;
- (void)setSourceType:;
- (id)sceneName;
- (void)setGroupId:;
- (id)groupId;
- (id)sourceType;
- (BOOL)hasLyrics;
- (void)setGroupType:;
- (void)setMediaType:;
- (id)groupType;
- (BOOL)isVideo;
- (id)mediaType;
- (void)setVideoId:;
- (void).cxx_destruct;
- (void)setRequestId:;
- (id)videoId;
- (id)requestId;
- (id)copyWithZone:;
- (void)setIsVideo:;
- (void)setHasLyrics:;
- (id)playlistID;
- (id)queueType;
- (void)setSceneName:;
- (void)setQueueType:;
- (id)queueName;
- (void)setQueueName:;
- (id)authorId;
- (void)setAuthorId:;
+ (id)encodingBehaviorsByPropertyKey;
@end
