@interface AWEMusicSegmentedControl : UIView
@property (nonatomic) UIStackView stackView;
@property (nonatomic) NSMutableArray itemViews;
@property (nonatomic) NSArray items;
@property (nonatomic) UIView darkSelectedLineView;
@property (nonatomic) UIView lightSelectedLineView;
@property (nonatomic) UIView seperateView;
@property (nonatomic) q playingIndex;
@property (nonatomic) q selectedIndex;
@property (nonatomic) <AWEMusicSegmentedControlDelegate> delegate;
@property (nonatomic) AWESlidingViewController slidingViewController;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)awe_themeReload;
- (void)configSubviews;
- (id)seperateView;
- (void)setSeperateView:;
- (id)slidingViewController;
- (void)setSlidingViewController:;
- (void)setSelectedIndex:animated:tapped:;
- (void)slidingControllerDidScroll:isFigureDragging:;
- (id)initWithItems:defaultSelectedIndex:;
- (void)tabChangedProgress:fromIndex:toIndex:;
- (void)setPlayingIndex:;
- (long long)playingIndex;
- (id)darkSelectedLineView;
- (id)lightSelectedLineView;
- (void)setDarkSelectedLineView:;
- (void)setLightSelectedLineView:;
- (void)updatePlayIndex:currentIndex:isPlaying:;
- (void)tab:changeToSelected:animated:;
- (id)titleFontWithSelected:;
- (id)stackView;
- (void)setSelectedIndex:;
- (void)setStackView:;
- (id)items;
- (id)delegate;
- (void)setItems:;
- (long long)selectedIndex;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)itemViews;
- (void)setItemViews:;
- (void)singleTap:;
- (void)updateAccessibilityLabel;
@end
