@interface AWEModernFeedContentFrame : NSObject
@property (nonatomic) NSString authorName;
@property (nonatomic) double containerWidth;
@property (nonatomic) NSMutableArray rangeArray;
@property (nonatomic) NSMutableArray abstractRangeArray;
@property (nonatomic) YYTextLayout shortAnswerLayout;
@property (nonatomic) double titleFontSize;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} hotSpotTagFrame;
@property (nonatomic) BOOL shouldShowHotSpotTag;
@property (nonatomic) AWEFeedVideoSingleCardLayoutAdjuster layoutAdjuster;
@property (nonatomic) AWEFeedVideoCardQualityLayoutAdjuster qualityLayoutAdjuster;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} descriptionFrame;
@property (nonatomic) YYTextLayout descriptionLayout;
@property (nonatomic) NSArray linkRangeArray;
@property (nonatomic) NSMutableAttributedString displayDescription;
@property (nonatomic) q maxNumberOfRows;
@property (nonatomic) BOOL shouldShowFullTextButton;
@property (nonatomic) q abstractPositionType;
@property (nonatomic) BOOL isShowFullTextButton;
@property (nonatomic) BOOL shouldShowFoldButton;
@property (nonatomic) BOOL isToRed;
@property (nonatomic) @? attachmentDidLoad;
@property (nonatomic) @? didTapOpenPanelBlock;
@property (nonatomic) NSString referString;
@property (nonatomic) AWEAwemeModel aweme;
@property (nonatomic) AWEConcernCardModel concernCardModel;
- (id)referString;
- (id)aweme;
- (void)setReferString:;
- (void)setAweme:;
- (id)hotSpotTagFont;
- (id)hotSpotTagColor;
- (BOOL)shouldShowFoldButton;
- (void)setShouldShowFoldButton:;
- (id)descriptionFrame;
- (void)setShouldShowFullTextButton:;
- (void)setDescriptionFrame:;
- (void)setLinkRangeArray:;
- (void)setDescriptionLayout:;
- (void)setDisplayDescription:;
- (BOOL)shouldShowFullTextButton;
- (BOOL)isAttributedStringTruncated:;
- (id)linkRangeArray;
- (void)appendMixVideoTagIfNeededWithAweme:attributedString:;
- (id)concernCardModel;
- (BOOL)isShowFullTextButton;
- (void)replacePlayTagIfNeeded;
- (void)replaceAdTagIfNeeded;
- (void)replaceGifTagIfNeeded;
- (void)setAttachmentDidLoad:;
- (BOOL)isToRed;
- (void)configFrameWithAweme:containerWidth:leftMargin:rightMargin:showAuthorName:showVideoAbstract:layoutType:;
- (void)configFrameWithAweme:containerWidth:layoutType:;
- (void)setIsToRed:;
- (void)configFrameWithAweme:containerWidth:leftMargin:rightMargin:showAuthorName:layoutType:;
- (BOOL)p_isConfigAttachImageFrameWithAweme:;
- (void)p_configAttachmentImageFrameWithAweme:containerWidth:leftMargin:rightMargin:;
- (id)descriptionStringForAweme:;
- (id)authorFloatingRedTextIfNeed:textExtra:extraLength:;
- (id)authorColor;
- (id)textExtraArrayForAweme:;
- (id)transferRange:withString:;
- (id)authorFont;
- (id)challengeColor;
- (id)challengeFont;
- (void)appendPlayTagPlaceholderIfNeededWithAweme:attributedString:;
- (void)appendAdTagPlaceholderIfNeededWithAweme:attributedString:;
- (void)appendAlbumTagIfNeededWithAweme:attributedString:;
- (id)addJumpTimeTextWithModel:attributes:authorName:;
- (BOOL)shouldShowHotSpotTag;
- (id)hotSpotTagFrame;
- (void)setIsShowFullTextButton:;
- (BOOL)shouldAppendAdTagWithAweme:;
- (id)p_resizeImage:size:;
- (id)attachmentDidLoad;
- (id)formattedJumpTimeForTime:;
- (id)contentFloatingRedTextIfNeed:textExtra:extraLength:attributes:;
- (BOOL)isTrendingPage;
- (void)setConcernCardModel:;
- (void)setQualityLayoutAdjuster:;
- (id)getAbstractAttributedString:attributes:showAuthorName:authorName:containerWidth:leftMargin:rightMargin:paragraphStyle:;
- (id)generateVideoSummaryWith:attributes:authorName:;
- (id)generateVideoSectionAbatrctText:attributes:authorName:width:;
- (id)qualityLayoutAdjuster;
- (BOOL)isShortAnswerNewStyleWithModel:;
- (id)layoutAdjuster;
- (void)setLayoutAdjuster:;
- (BOOL)enableGeneralSearchTextInfoGovern;
- (void)setAbstractPositionType:;
- (id)abstractRangeArray;
- (void)setHotSpotTagFrame:;
- (void)setShouldShowHotSpotTag:;
- (long long)abstractPositionType;
- (void)hotSpotPureTextFoldButtonWithAttributedString:;
- (id)shortAnswerLayoutWithMoldel:leftMargin:rightMargin:containerWidth:;
- (void)setShortAnswerLayout:;
- (void)setAbstractMaxNumberOfRows:containerWidth:leftMargin:rightMargin:emojiStr:;
- (BOOL)hasAiTitleInfo:;
- (void)setAITitleMaxNumberOfRows;
- (id)fetchVideoAITitle:attributes:containerWidth:leftMargin:rightMargin:paragraphStyle:;
- (BOOL)showShortAnswerStyleWithModel:;
- (BOOL)enableAITitleOpt;
- (long long)aITitleMaxNumRows;
- (id)shortAnswerLayout;
- (id)didTapOpenPanelBlock;
- (id)generateShortAnswerText:attributes:width:;
- (id)generateShortAnswerIcon:attributes:width:;
- (BOOL)showPointWithModel:;
- (id)getTextLayoutWith:textFontSize:width:maxLines:;
- (void)udpateAbstractRangeArrayPrefixLength:maxLength:text:;
- (void)replaceVideoAbstractDotIfNeeded;
- (void)replaceVideoAbstractAITag;
- (void)replaceVideoAbstractTag;
- (void)addAbstractHighlight;
- (void)updateDisplayDescriptionIfNeeded;
- (void)setDidTapOpenPanelBlock:;
- (void)setAbstractRangeArray:;
- (double)titleFontSize;
- (id)init;
- (void)setRangeArray:;
- (void)setTitleFontSize:;
- (void).cxx_destruct;
- (id)rangeArray;
- (id)authorName;
- (id)displayDescription;
- (void)setAuthorName:;
- (double)containerWidth;
- (id)descriptionLayout;
- (long long)maxNumberOfRows;
- (void)setContainerWidth:;
- (void)setMaxNumberOfRows:;
+ (BOOL)enableMixVideo:;
+ (BOOL)fixAbstractTransactionMainThread;
@end
