@interface AWEMVChannelPlayVideoViewController : UIViewController
@property (nonatomic) NSString enterFrom;
@property (nonatomic) UIView clipContainerView;
@property (nonatomic) NSTimer beginLoadingTimer;
@property (nonatomic) UIViewController<AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEPlayVideoViewControllerProtocol> playerViewController;
@property (nonatomic) BDImageView coverImgView;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) AWEMVChannelPageContext context;
@property (nonatomic) NSTimer weakenPlayTimer;
@property (nonatomic) q weakenTimerCount;
@property (nonatomic) BOOL isPlayerLoading;
@property (nonatomic) CADisplayLink displayLink;
@property (nonatomic) NSDictionary logExtraDict;
@property (nonatomic) AWEMVChannelPlayerCardInteractionView interactionView;
@property (nonatomic) AWEMVChannelPlayerCardContext interactionContext;
@property (nonatomic) BOOL hasCoverConfig;
@property (nonatomic) BOOL hasInteractionConfig;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSNumber defaultStartPlayTime;
@property (nonatomic) double stopTime;
@property (nonatomic) double currentPlayTime;
@property (nonatomic) @? playButtonClicked;
@property (nonatomic) @? controlViewHandler;
@property (nonatomic) NSString referString;
@property (nonatomic) BOOL shouldPreventShowCoverImage;
@property (nonatomic) BOOL hasPrepareForDisplay;
@property (nonatomic) q state;
@property (nonatomic) AWEMVChannelBaseCell playerCell;
@property (nonatomic) <AWEMVPlayVideoViewDelegate> playVideoDelegate;
@property (nonatomic) <AWEMVChannelPlayerCardPlayerProtocol> cardDelegate;
- (void)setLogExtraDict:;
- (id)referString;
- (void)setEnterFrom:;
- (void)player:playbackFailedWithError:;
- (void)playerDidReadyForDisplay:;
- (void)player:didChangeStallState:;
- (void)playerWillLoopPlaying:;
- (void)player:playbackFailedForURL:error:;
- (void)setReferString:;
- (id)logExtraDict;
- (void)updatePlayerIfNeeded;
- (id)enterFrom;
- (void)player:updatePlayTime:canPlayTime:totalTime:;
- (void)playerWillStartNextLoop:;
- (void)playerWillStartNextLoopFinished:;
- (void)player:didChangePlaybackToAction:;
- (void)updateLogExtraDict:;
- (double)currentPlayTime;
- (BOOL)isPlayerPlaying;
- (void)removeFromParentVC;
- (id)currentCoverImage;
- (id)relatedViewControllerForPrefetch;
- (void)setCurrentPlayTime:;
- (void)configSubviews;
- (void)updatePlayerViewFrame;
- (void)setupBind;
- (BOOL)hasPrepareForDisplay;
- (void)setHasPrepareForDisplay:;
- (BOOL)shouldResponseGestureRecognizer:;
- (void)resetToBeginTime;
- (void)playResumeDisplayLink;
- (void)resetDisplayLink;
- (void)handleResponseLongPressAction:;
- (BOOL)isPlayerUnplayedStatus;
- (id)coverImgView;
- (void)setCoverImgView:;
- (id)playerCell;
- (void)setPlayerCell:;
- (id)cardDelegate;
- (void)setCardDelegate:;
- (void)updateInteractionView;
- (void)bindEvents;
- (long long)userActionPlayState;
- (long long)videoActionState;
- (void)updateState:animated:completion:;
- (void)setupPlayerViewController;
- (id)defaultStartPlayTime;
- (void)setDefaultStartPlayTime:;
- (void)hidePlayerGradienView;
- (void)showPlayerGradienView;
- (void)seekVideoStartToDefault;
- (void)removeVideoViewController;
- (void)playAndStopLoadingAnimation:;
- (void)clearDefaultStartPlayTime;
- (void)updateVideoScalingMode;
- (void)setStopPlayTime:;
- (void)configAfterQuitLandscape:;
- (void)willShowActiveViewInVisibleRange;
- (void)configBeforeEnterLandscape;
- (void)configAfterQuitLandscape;
- (id)initWithMVVideoConfig:context:;
- (void)updateWithModel:logExtraDict:;
- (void)configAfterQuitLandscapeWithModel:;
- (BOOL)playWithMute:;
- (void)showCoverImageView:;
- (void)refreshLogExtraDict:;
- (void)triggerWeakenTimer;
- (void)updateStartLeftTime;
- (void)updateClipContainerViewFrame;
- (void)clipPlayControllerView;
- (double)playerVerticalFrameOffset:;
- (void)prepareBeforeTransition;
- (void)configAfterBackFromTransition;
- (void)configAfterUpdatePlayerControllerInWindowPlayStatus;
- (id)clipContainerView;
- (id)playButtonClicked;
- (void)setPlayButtonClicked:;
- (id)controlViewHandler;
- (void)setControlViewHandler:;
- (BOOL)shouldPreventShowCoverImage;
- (void)setShouldPreventShowCoverImage:;
- (BOOL)isPlayerLoading;
- (void)setPlayVideoDelegate:;
- (void)setHasCoverConfig:;
- (void)setHasInteractionConfig:;
- (void)triggerLoadingTimer:;
- (void)fireWeakenTimer;
- (BOOL)hasCoverConfig;
- (BOOL)hasInteractionConfig;
- (void)updateSmallCardAutoPlayScaleModeIfNeed;
- (id)beginLoadingTimer;
- (void)setBeginLoadingTimer:;
- (long long)weakenTimerCount;
- (void)setWeakenTimerCount:;
- (void)setWeakenPlayTimer:;
- (id)weakenPlayTimer;
- (void)hideRateViewIfNeed;
- (void)updateCoverImageView;
- (void)setIsPlayerLoading:;
- (void)triggerOrFireWeakenTimerWithIsLoading:;
- (id)playVideoDelegate;
- (void)setClipContainerView:;
- (void)updateState:;
- (void)setModel:;
- (id)interactionView;
- (void)dealloc;
- (BOOL)play;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)displayLink;
- (void)prepareForDisplay;
- (long long)state;
- (void)setInteractionView:;
- (void)replay;
- (double)stopTime;
- (id)model;
- (void)setDisplayLink:;
- (void)setContext:;
- (void).cxx_destruct;
- (void)reset;
- (id)context;
- (void)setState:;
- (BOOL)stop;
- (void)setStopTime:;
- (id)playerViewController;
- (BOOL)pause;
- (void)setPlayerViewController:;
- (id)interactionContext;
- (void)setInteractionContext:;
- (void)seekToTime:completion:;
@end
