@interface AWEMusicProfileExtensionAreaCardController : NSObject
@property (nonatomic) UIView<AWEProfileExtensionAreaCardViewProtocol> cardView;
@property (nonatomic) AWEProfileExtensionAreaCommonParamModel commonParamModel;
@property (nonatomic) BOOL isActiveSubtitleOnce;
@property (nonatomic) BOOL isActiveIcon;
@property (nonatomic) AWEMusicCardExtensionModel originalModel;
@property (nonatomic) BOOL isShowing;
@property (nonatomic) NSString currentSubTitle;
@property (nonatomic) BOOL isLunaIcon;
@property (nonatomic) q currentIconShowCount;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)shouldShowCard;
- (void)passCardView:;
- (void)cardDidClicked;
- (void)cardWillAppear;
- (void)cardWillDisappear;
- (void)cardDidDisappear;
- (void)setCommonParamModel:;
- (id)commonParamModel;
- (void)updateCardView;
- (id)p_trackParams;
- (id)p_userWrapperKey:;
- (void)setOriginalModel:;
- (id)originalModel;
- (void)setIsActiveSubtitleOnce:;
- (void)p_extraSubTitleShowedCountPlus:;
- (id)p_subtitleIconClickedWrapperKey:;
- (void)updateCustomDetailViewWithSubtitle:iconURL:;
- (BOOL)isActiveIcon;
- (void)setIsActiveIcon:;
- (BOOL)isActiveSubtitleOnce;
- (BOOL)p_canShowExtraSubTitle;
- (id)p_subtitleIconShowedWrapperKey:;
- (void)setCurrentIconShowCount:;
- (BOOL)p_canShowIconAnimation;
- (void)setIsLunaIcon:;
- (void)setCurrentSubTitle:;
- (long long)currentIconShowCount;
- (id)currentSubTitle;
- (BOOL)isLunaIcon;
- (void)updateSubtitle;
- (BOOL)isShowing;
- (void).cxx_destruct;
- (BOOL)isCurrentUser;
- (id)cardView;
- (void)setCardView:;
- (void)updateIcon;
- (void)setIsShowing:;
+ (id)cardControllerWithCommonParam:;
+ (id)shared;
@end
