@interface AWENewVideoCoverStickerHandler : NSObject
@property (nonatomic) NLELayer_OC currentEditLayer;
@property (nonatomic) AWENewVideoCoverNLELayerView currentEditLayerView;
@property (nonatomic) q stickerViewHierarchyIdCounter;
@property (nonatomic) AWEStoryFontModel currentFontModel;
@property (nonatomic) AWEStoryColor currentColorModel;
@property (nonatomic) q currentAlignment;
@property (nonatomic) Q currentTextStyle;
@property (nonatomic) AWENewVideoCoverCommandStack commandStack;
@property (nonatomic) NSMutableArray recommendTextContent;
@property (nonatomic) AWENewVideoCoverRotateScaleTranslateCommand lastRecordCommand;
@property (nonatomic) NSString videoCoverSource;
@property (nonatomic) AWEVideoPublishViewModel repository;
@property (nonatomic) <AWENewVideoCoverStickerHandlerDelegate> delegate;
@property (nonatomic) <ACCStickerServiceProtocol> stickerService;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)commonTrackParams;
- (id)videoCoverSource;
- (void)setVideoCoverSource:;
- (void)clearCommand;
- (id)stickerContainer;
- (id)stickerService;
- (void)setStickerService:;
- (void)registerInputModule;
- (void)updateLayerViewInStickerContainer:withUpdatedModule:;
- (id)NLEImageService;
- (void)trackEditRecall;
- (id)recommendTextContent;
- (id)addLayerViewWithstickerInfo:;
- (id)getNLEImageWrapper;
- (id)currentTextModel;
- (id)currentFontModel;
- (id)currentColorModel;
- (unsigned long long)currentTextStyle;
- (id)nleLayerForStickerView:;
- (id)realStickerViewForStickerView:;
- (id)textOfLayer:;
- (void)commandStackHasCommand:;
- (id)commandStack;
- (void)setCommandStack:;
- (id)getNleImageAlbumEditor;
- (BOOL)useVideoCoverImageTemplate;
- (void)clearCurrentEditLayer;
- (void)pushCommand:;
- (void)recoverEdit;
- (id)currentEditLayer;
- (long long)nextStickerViewHierarchyId;
- (long long)stickerViewHierarchyIdCounter;
- (void)setStickerViewHierarchyIdCounter:;
- (void)textDidChangeToTextTab;
- (void)setCurrentEditLayer:;
- (void)setCurrentEditLayerView:;
- (void)trackCompleteEditSticker:layerView:;
- (id)stickerViewForNLELayer:;
- (id)addLayerViewWithstickerInfo:lastContent:;
- (void)stickerView:handleTranslate:;
- (void)stickerView:handleRotation:;
- (void)stickerView:handleScale:;
- (void)trackDragCover;
- (BOOL)currentLayerCanEdit;
- (void)textDidStartEdit;
- (void)stickerView:handleEndGesture:;
- (id)getCommandByAddStickerView:config:needRecord:;
- (void)removeStickerViewWithContent:;
- (id)nleLayerOfLayerOrStickerId:;
- (void)trackDeleteSticker:layerView:;
- (void)trackEditSticker:;
- (void)trackAddSticker:;
- (id)lastRecordCommand;
- (void)trackMainLayerCommand:;
- (void)setLastRecordCommand:;
- (id)realStickerViewForContentView:;
- (id)geometryModelForLayer:;
- (void)tryShowEditLayer;
- (id)currentEditLayerView;
- (long long)currentTextAlignStyle;
- (id)addTitleSticker:fontModel:colorModel:aligntStyle:textStyle:showEdit:;
- (void)trackSelectTitleItem:;
- (void)markStickEdit;
- (BOOL)stickerTemplateReplaceFixEnable;
- (BOOL)currentIsTextLayer;
- (BOOL)currentIsTemplateLayer;
- (void)trackFailToAddCoverText:errorCode:titleId:titleSource:textTemplateId:failStage:;
- (id)nleLayerOfSticker:;
- (id)stickerInfoWithLayer:stickerId:;
- (void)updaterLayer:withContent:;
- (void)trackSelectTextTemplate:title:tabName:;
- (void)trackAddCoverText:titleId:titleSource:textTemplateId:;
- (void)trackChangeTextTemplateTab:enterTabType:;
- (void)realClearSticker;
- (void)deleteEditLayer:;
- (void)setCurrentFontModel:;
- (void)updateFont:withLayer:;
- (void)setCurrentColorModel:;
- (void)updateUIColor:withLayer:;
- (void)editDidSelectAlign:withLayer:;
- (void)editDidSelectTextStyle:currentTextModel:withLayer:;
- (void)configLayer:withTextStyle:andTextModel:useCommand:;
- (void)updateCurrentEditLayerContent:;
- (void)updateLayerViewInStickerContainer:withUpdatedLayer:andLayerView:imageWrapper:;
- (id)stickerContentViewForStickerView:;
- (void)setRecommendTextContent:;
- (void)textDidFinishEdit;
- (void)textDidSelectTitleItem:fontModel:colorModel:aligntStyle:textStyle:;
- (void)textDidSelectSticker:atIndex:extraPramas:textTemplateSetParam:tabName:;
- (void)textDidFailToSelectSticker:atIndex:error:;
- (void)textDidDeselectSticker:;
- (void)textDidClearSticker;
- (void)textDidSelectFontStyle:;
- (void)textDidSelectColorStyle:;
- (void)textDidSelectAlignStyle:;
- (void)textDidSelectTextStyle:;
- (void)textTemplateChangedToTab:enterTabType:;
- (id)currentEditLayerContent;
- (id)delegate;
- (id)repository;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)setRepository:;
- (void)setCurrentTextStyle:;
- (long long)currentAlignment;
- (void)setCurrentAlignment:;
+ (id)geometryModelWithLayer:fromNLEImageWrapper:mediaSize:;
+ (id)viewConfigConstrutor;
+ (id)viewConstructor;
@end
