@interface AWENearbyGuideFloatBackModel : MTLModel
@property (nonatomic) q pageTypeId;
@property (nonatomic) q positionScene;
@property (nonatomic) @? attachClickedHandler;
@property (nonatomic) @? attachBeforeClickedHandler;
@property (nonatomic) NSString urlString;
@property (nonatomic) NSString floatBackText;
@property (nonatomic) BOOL backToFeed;
@property (nonatomic) NSString buttonType;
@property (nonatomic) NSNumber singleHiddenCount;
@property (nonatomic) NSNumber doubleHiddenCount;
@property (nonatomic) NSNumber resident;
@property (nonatomic) NSNumber shrinkCount;
@property (nonatomic) q actionType;
@property (nonatomic) q offsetFromBottom;
@property (nonatomic) @? clickedHandler;
@property (nonatomic) q bitmapRefreshPage;
@property (nonatomic) NSDictionary notiParams;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)floatBackText;
- (void)setFloatBackText:;
- (BOOL)backToFeed;
- (void)setBackToFeed:;
- (id)singleHiddenCount;
- (void)setSingleHiddenCount:;
- (id)doubleHiddenCount;
- (void)setDoubleHiddenCount:;
- (id)shrinkCount;
- (void)setShrinkCount:;
- (long long)offsetFromBottom;
- (void)setOffsetFromBottom:;
- (id)clickedHandler;
- (void)setClickedHandler:;
- (long long)bitmapRefreshPage;
- (void)setBitmapRefreshPage:;
- (id)notiParams;
- (void)setNotiParams:;
- (void)setPositionScene:;
- (void)setAttachBeforeClickedHandler:;
- (void)setAttachClickedHandler:;
- (void)setPageTypeId:;
- (long long)positionScene;
- (id)attachBeforeClickedHandler;
- (id)attachClickedHandler;
- (long long)pageTypeId;
- (id)buttonType;
- (id)urlString;
- (long long)actionType;
- (void)setActionType:;
- (void)setUrlString:;
- (void).cxx_destruct;
- (void)setButtonType:;
- (id)resident;
- (void)setResident:;
+ (BOOL)automaticallyDefaultMapping;
+ (id)JSONKeyPathsByPropertyKey;
@end
