@interface AWENoticeImpl.AWENoticeInteractionLeftContainer : AWENoticeInteractionBaseContainer
@property (nonatomic) UIImageView avatarImageView;
@property (nonatomic) UIView avatarContainerView;
@property (nonatomic) UIView multiAvatars;
@property (nonatomic) UIImageView typeIconView;
@property (nonatomic) UIImageView yellowPointView;
@property (nonatomic) <AFDCloseFriendsColorRingDisplayManagerProtocol> colorRingDisplayManager;
- (void)cellWillDisplay;
- (id)colorRingDisplayManager;
- (void)configYellowPoint;
- (id)yellowPointView;
- (void)setYellowPointView:;
- (id)typeIconView;
- (void)setTypeIconView:;
- (id)multiAvatars;
- (void)setMultiAvatars:;
- (void)handleTapAvatarGesWithSender:;
- (void)handleTapMultiAvatasGesWithSender:;
- (id)createYellowPointView;
- (id)createAvatarImageView;
- (id)createTypeIconView;
- (id)createMultiAvatars;
- (id)createColorRingDisplayManager;
- (BOOL)cf_canShowColorRingWithRingStatus:;
- (id)cf_transitionTargetView;
- (void)cf_colorRingViewVisibleStatusChanged;
- (void)setColorRingDisplayManager:;
- (void)configWithCellModel:;
- (void)prepareForReuse;
- (id)initWithFrame:;
- (void).cxx_destruct;
- (id)initWithCoder:;
- (void)setupUI;
- (id)avatarImageView;
- (id)avatarContainerView;
- (void)setAvatarContainerView:;
- (void)setAvatarImageView:;
- (id)createAvatarContainerView;
- (void)configLayout;
+ (id)defaultAvatarImage;
@end
