@interface AWENaviCacheManager : NSObject
@property (nonatomic) double timeInterval;
@property (nonatomic) <AWENaviUserInfoProtocol> loginUser;
@property (nonatomic) double lokiExpiration;
@property (nonatomic) NSRecursiveLock lokiLock;
@property (nonatomic) IESEffectPlatformResponseModel lokiModel;
@property (nonatomic) double limitExpiration;
@property (nonatomic) NSRecursiveLock limitLock;
@property (nonatomic) AWETwoTuple limitModelTuple;
@property (nonatomic) double avatarExpiration;
@property (nonatomic) NSRecursiveLock avatarLock;
@property (nonatomic) AWETwoTuple avatarModelTuple;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)enableMemoryOptimizeWithNunki;
- (void)didReceiveMemeoryDangerLevelTopNotification;
- (void)setLokiLock:;
- (void)setLimitLock:;
- (void)setAvatarLock:;
- (double)getBaseTime:;
- (void)setLokiExpiration:;
- (void)setLimitExpiration:;
- (void)setAvatarExpiration:;
- (void)setLokiModel:;
- (void)setLimitModelTuple:;
- (void)setAvatarModelTuple:;
- (id)responseCacheURL:;
- (id)lokiLock;
- (double)lokiExpiration;
- (id)lokiModel;
- (void)fetchCachedResponseOfClass:fromFileName:completion:;
- (void)baseTimeNeedsUpdate:;
- (void)cacheResponse:toFileName:completion:;
- (id)limitLock;
- (double)limitExpiration;
- (id)limitModelTuple;
- (id)p_limitedCacheFileName;
- (id)avatarLock;
- (double)avatarExpiration;
- (id)avatarModelTuple;
- (id)p_selfAvatarCacheFileName;
- (id)getBaseTimeCacheKey:;
- (id)contentsOfTabPromotion:;
- (void)updatePromotionCache:ofTab:;
- (BOOL)shouldShowPromotionForTab:;
- (id)promotionCacheKey:;
- (void)fetchLokiResponseCompletion:;
- (void)setLokiResponse:;
- (void)fetchLimitResponseCompletion:;
- (void)setLimitResponse:;
- (void)fetchSelfAvatarResponseCompletion:;
- (void)setSelfAvatarResponse:;
- (void)markShowedPromotionForTab:;
- (void)increaceForceLandingCount:;
- (BOOL)shouldForceLandingTab:limit:;
- (void)setLoginUser:;
- (double)timeInterval;
- (id)init;
- (void)dealloc;
- (id)initWithTimeInterval:;
- (void)setTimeInterval:;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning:;
- (id)loginUser;
@end
