@interface AWENaviDuetActionPoseComponent : AWENaviDuetBaseFeatureComponent
@property (nonatomic) AWENaviDuetActionPoseView sceneView;
@property (nonatomic) <AWENaviDuetViewContainerProtocol> viewContainer;
@property (nonatomic) <AWENaviDuetRenderServiceProtocol> renderService;
@property (nonatomic) NSArray originActionPoses;
@property (nonatomic) NSArray actionPoses;
@property (nonatomic) AWENaviDuetActionPoseModel currentActionPose;
@property (nonatomic) NSURL musicPath;
@property (nonatomic) NSArray ownLimitedActionNameArray;
@property (nonatomic) BOOL hasSwitched;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupBinding;
- (void)p_showSceneViewIfNeeded;
- (void)setupActionsData;
- (id)renderService;
- (void)musicPlayNeedsReset:;
- (void)fetchActionsCompletion:;
- (void)setOwnLimitedActionNameArray:;
- (BOOL)isOwnLimitedActionEffect:;
- (BOOL)isNeedsExclusiveAction:;
- (void)setOriginActionPoses:;
- (id)filterActionPoseWithOthers:;
- (void)setActionPoses:;
- (void)setupInitialActionPose;
- (id)actionPoses;
- (id)originActionPoses;
- (id)currentActionPose;
- (void)applyActionScence:;
- (BOOL)hasSwitched;
- (BOOL)isDefaultAction:;
- (void)setHasSwitched:;
- (BOOL)unloadSceneIfNeeded;
- (void)resetMusic:;
- (void)setCurrentActionPose:;
- (void)setMusicPath:;
- (void)p_recoveryMusicIfNeeded;
- (void)needsPauseMusic;
- (id)musicPath;
- (id)ownLimitedActionNameArray;
- (void)didFinishLoadAvatarPlugin;
- (void)didRebuidRecorder;
- (void)componentDidMount;
- (void)componentDidUnmount;
- (void)componentDidAppear;
- (void)componentWillDisappear;
- (unsigned long long)preferredLoadPhase;
- (void)setRenderService:;
- (id)viewModel;
- (void)appWillEnterForeground:;
- (void).cxx_destruct;
- (id)sceneView;
- (id)serviceProvider;
- (void)setServiceProvider:;
- (void)setViewContainer:;
- (id)viewContainer;
- (void)setSceneView:;
- (void)p_registerNotifications;
@end
