@interface AWENearbyC2TransformerViewModel : AWEBaseViewModel
@property (nonatomic) AWENearbySettingsManager settingsMananger;
@property (nonatomic) AWENearbySettingsResponse settingResponse;
@property (nonatomic) BOOL isTransformerShow;
@property (nonatomic) double currentDisplayPct;
@property (nonatomic) Q lastRefreshType;
@property (nonatomic) Q lastDataType;
@property (nonatomic) BOOL needRefreshByOrder;
@property (nonatomic) BOOL needRefreshBySendLaunchSuccess;
@property (nonatomic) BOOL needRefreshByPOICollect;
@property (nonatomic) AWENearbyPageContext pageContext;
@property (nonatomic) <IESLCMessageHandlerProtocol> messageHandler;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)ieslc_messageHandler:didReceiveMsg:;
- (void)configTaskWithModel:;
- (void)__setupObserver;
- (id)initWithPageContext:;
- (BOOL)isTransformerShow;
- (void)setIsTransformerShow:;
- (void)__updateTransformerShowStatus:;
- (void)__didReceiveFavoriteStatusUpdatedNotifications:;
- (long long)transformerSceneTypeWithPageType:;
- (BOOL)needRefreshByPOICollect;
- (void)setNeedRefreshByPOICollect:;
- (unsigned long long)lastRefreshType;
- (double)currentDisplayPct;
- (void)setCurrentDisplayPct:;
- (void)setLastRefreshType:;
- (void)updateTransformerDisplayPct:;
- (id)settingResponse;
- (void)enterToNeabry;
- (void)transformerDidLoad;
- (void)transformerDidAppear;
- (void)transformerDidDisapper;
- (BOOL)refreshTransformerIfNeededWhenTransformerShow;
- (BOOL)refreshTransformerIfNeededWhenDisplayPct90;
- (unsigned long long)lastDataType;
- (id)settingsMananger;
- (void)cardRefreshWithParams:refreshType:completion:;
- (void)updateLynxCardHeight:type:;
- (void)refreshTransformerWithType:completion:;
- (void)refreshTransformerWithType:extraRequestParam:completion:;
- (void)refreshByTransformerToolAreaChangeWithType:;
- (BOOL)needRefreshByOrder;
- (void)setNeedRefreshByOrder:;
- (BOOL)needRefreshBySendLaunchSuccess;
- (void)setNeedRefreshBySendLaunchSuccess:;
- (void)__didReceiveLynxBroadcastNotification:;
- (void)refreshTransformerWithType:;
- (void)handleTransformerRefreshWithScene:;
- (long long)orderLCFrequency;
- (void)__refreshTransformerWithType:sourceType:usePreloadCache:completion:;
- (void)setLastDataType:;
- (void)__refreshTransformerWithType:sourceType:extraRequestParam:usePreloadCache:completion:;
- (void)setSettingResponse:;
- (void)setSettingsMananger:;
- (void).cxx_destruct;
- (void)cancelCurrentRequest;
- (void)setPageContext:;
- (id)pageContext;
@end
