@interface AWENearbyFeedCardMonitor : NSObject
@property (nonatomic) @? fpsCallback;
@property (nonatomic) NSMutableArray fpsRecords;
@property (nonatomic) @? frameDropCallback;
@property (nonatomic) NSMutableArray frameDropRecords;
@property (nonatomic) NSMutableArray cpuRecords;
@property (nonatomic) NSMutableArray memoryRecords;
@property (nonatomic) BOOL fpsMonitorRunning;
@property (nonatomic) BOOL dropMonitorRunning;
@property (nonatomic) NSObject<OS_dispatch_queue> sampleQueue;
@property (nonatomic) NSTimer monitorTimer;
@property (nonatomic) q firstMemory;
@property (nonatomic) double beginTime;
@property (nonatomic) NSString scene;
- (void)setFpsCallback:;
- (id)fpsCallback;
- (void)setSampleQueue:;
- (id)frameDropCallback;
- (id)sampleQueue;
- (void)setFrameDropCallback:;
- (void)startFPSMonitor;
- (void)setFpsRecords:;
- (id)fpsRecords;
- (void)clearMonitorData;
- (void)setFpsMonitorRunning:;
- (void)setDropMonitorRunning:;
- (void)startFrameDropMonitor;
- (void)startUtilsMonitor;
- (void)setFirstMemory:;
- (BOOL)fpsMonitorRunning;
- (BOOL)dropMonitorRunning;
- (id)getNearbyCardFPSMonitorData;
- (id)getNearbyCardUtilsMonitorData;
- (long long)firstMemory;
- (void)setFrameDropRecords:;
- (id)frameDropRecords;
- (void)setCpuRecords:;
- (void)setMemoryRecords:;
- (id)monitorTimer;
- (id)cpuRecords;
- (void)setMonitorTimer:;
- (void)monitorCPUAndMemory;
- (void)setScene:;
- (id)init;
- (void)dealloc;
- (id)scene;
- (void)stopTimer;
- (double)beginTime;
- (id)memoryRecords;
- (void)setBeginTime:;
- (void).cxx_destruct;
- (void)stop;
- (void)start;
@end
