@interface AWENearbyHalfScreenContainerViewController : UIViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWENearbyHalfScreenContainerModel containerModel;
@property (nonatomic) UIView containerView;
@property (nonatomic) CAShapeLayer containerShapeLayer;
@property (nonatomic) UIViewController currentContentVC;
@property (nonatomic) UIButton maskViewButton;
@property (nonatomic) UIPanGestureRecognizer panGesture;
@property (nonatomic) {CGPoint=dd} containerViewPanStartPoint;
@property (nonatomic) BOOL isMaxStatusWhenPanStart;
@property (nonatomic) BOOL isRedirectContent;
@property (nonatomic) @ containerContent;
@property (nonatomic) UIScrollView contentScrollView;
@property (nonatomic) UIView contentView;
@property (nonatomic) NSMutableArray subscribeList;
@property (nonatomic) AWENearbyHalfScreenShowAnimationController showController;
@property (nonatomic) AWENearbyHalfScreenDismissAnimationController dismissController;
@property (nonatomic) AWENearbyHalfScreenAnimation currentShowAnimation;
@property (nonatomic) AWENearbyHalfScreenAnimation currentDismissAnimation;
@property (nonatomic) AWENearbyHalfScreenAnimation currentTargetAnimation;
@property (nonatomic) q originHeightPercent;
@property (nonatomic) q maxHeightPercent;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} angleTargetRect;
@property (nonatomic) double paddingTop;
@property (nonatomic) double containerShowedTimeStamp;
@property (nonatomic) BOOL showCompleted;
@property (nonatomic) UIButton highLightBtn;
@property (nonatomic) BOOL needFrezedContainerHeight;
@property (nonatomic) AWENearbyLifeSwipeUpGuideView swipeUpGuideView;
@property (nonatomic) BOOL didScrollTopTabInGroupon;
@property (nonatomic) NSString arrowColor;
@property (nonatomic) NSArray viewInjectorList;
@property (nonatomic) Q containerViewStyle;
@property (nonatomic) @? dismissCompletion;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q containerViewState;
- (void)containerDidFirstScreen:;
- (void)container:onSetupLynxInfo:bulletInfo:;
- (void)container:onUpdateLynxInfo:bulletInfo:;
- (void)setDismissCompletion:;
- (id)subscribeList;
- (id)containerModel;
- (void)setSubscribeList:;
- (void)xpoolContainerDidFinishLoad:;
- (void)xpoolContainer:didLoadFailedWithError:;
- (void)xpoolContainerDidFirstScreen:;
- (void)setContainerModel:;
- (id)arrowColor;
- (void)setArrowColor:;
- (void)nearbylifeC2PageFetchFinish:resource:refreshContext:isRefresh:;
- (void)hiddenHalfScreenHighLight;
- (void)updateHalfScreenAngleTargetRect:dialogProps:;
- (void)updateHalfScreenCloseAnimationTargetView:;
- (long long)originHeightPercent;
- (void)setOriginHeightPercent:;
- (void)setAngleTargetRect:;
- (id)angleTargetRect;
- (id)swipeUpGuideView;
- (void)setSwipeUpGuideView:;
- (void)addDitoFMPDoneNotificationIfNeeded:;
- (void)recordUserHasScroollTab;
- (id)maskViewButton;
- (void)setupContainerContent:;
- (void)maskViewButtonClicked:;
- (void)setMaskViewButton:;
- (unsigned long long)containerViewState;
- (void)setContainerViewState:;
- (long long)maxHeightPercent;
- (void)setMaxHeightPercent:;
- (id)initWithContent:containerModel:;
- (void)setViewInjectorList:;
- (void)showContentViewWithCompletion:;
- (BOOL)isRedirectContent;
- (double)containerShowedTimeStamp;
- (BOOL)needFrezedContainerHeight;
- (void)handleFullScreenPanGesture:;
- (void)handlePanGestureStateBegan:;
- (void)handlePanGestureStateChanged:;
- (void)handlePanGestureStateEnded:;
- (void)setContainerViewPanStartPoint:;
- (double)containerViewLimitTopY;
- (void)setIsMaxStatusWhenPanStart:;
- (void)publishJSBEvent:params:;
- (double)containerViewLimitBottomY;
- (BOOL)isMaxStatusWhenPanStart;
- (void)dismissHalfScreenWithCloseType:;
- (void)trackNearbyHalfScreenInteractionMonitorWithParams:;
- (void)changeContainerViewPositionWithNewHeight:;
- (void)updateContainerViewState:;
- (BOOL)shouldDisableHalfScreenHorizontalScrollWhileHalfStateOf:;
- (id)findScrollViewInContent;
- (unsigned long long)containerViewStyle;
- (id)containerContent;
- (id)findScrollViewInContentOfBDXViewController:;
- (id)findScrollViewInContentOfUIViewController:;
- (id)__findScrollViewWithParentView:;
- (void)registerRedirectJSEvent;
- (void)registerContentPopJSEvent;
- (void)registerHeightChangeJSEvent;
- (void)registerChangeArrowColorJSEvent;
- (void)registerCloseHalfScreenContianerJSEvent;
- (void)trackNearbyHalfScreenJSBMonitorWithParam:;
- (void)redirectContentWithSchema:;
- (void)setNeedFrezedContainerHeight:;
- (void)halfScreenChangeStatusWithType:;
- (void)updateHalfScreenArrowColor:;
- (void)dismissHalfScreenWithCloseType:showExtraAnimation:;
- (void)registerHalfScreenJSEvent;
- (id)currentDismissAnimation;
- (void)reportHalfScreenCloseAnimationExposeIfNeeded;
- (void)setCurrentShowAnimation:;
- (id)currentShowAnimation;
- (void)setCurrentDismissAnimation:;
- (void)setCurrentTargetAnimation:;
- (id)showAnimationOfType:;
- (id)dismissAnimationOfType:;
- (id)endingAnimationOfType:;
- (unsigned long long)showAnimationType;
- (unsigned long long)dismissAnimationTypeWithShowExtraAnimation:;
- (void)trackNearbyHalfScreenWillClose:;
- (void)trackNearbyHalfScreenCloseAnimationDone:animations:;
- (void)trackNearbyHalfScreenBecomeFull:;
- (void)updateContainerViewStateHalf;
- (void)updateContainerViewStateFull;
- (void)updateContainerViewStateMaxPercent;
- (void)sendHalfScreenInjectedViewEvent:funcBlock:;
- (id)showController;
- (void)postHalfScreenStateChange:params:;
- (void)hideSwipeView;
- (id)containerShapeLayer;
- (void)setShowCompleted:;
- (BOOL)canShowSwipeUpView;
- (void)setSheetLayout;
- (void)setRichArrowAlertLayout;
- (void)setNomalArrowAlertLayout;
- (void)setContainerShapeLayer:;
- (id)highLightBtn;
- (void)setupContentOfViewController:;
- (void)setupContentOfView:;
- (void)setContainerShowedTimeStamp:;
- (id)currentContentVC;
- (void)setCurrentContentVC:;
- (void)transparentAngleTargetRect;
- (void)recordSwipUpViewShow;
- (id)swipeUpShowStorageKey:type:;
- (void)updateAngleTargetRect:;
- (void)updateHalfScreenHeightAndAngleTargetRect;
- (BOOL)showCompleted;
- (void)setDidScrollTopTabInGroupon:;
- (void)highLightButtonClicked:;
- (void)setIsRedirectContent:;
- (void)setContainerContent:;
- (id)viewInjectorList;
- (BOOL)didScrollTopTabInGroupon;
- (void)setContainerViewStyle:;
- (id)containerViewPanStartPoint;
- (void)setShowController:;
- (void)setDismissController:;
- (id)currentTargetAnimation;
- (void)setHighLightBtn:;
- (void)dealloc;
- (double)paddingTop;
- (void)setPaddingTop:;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:;
- (id)contentView;
- (id)containerView;
- (id)contentScrollView;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)viewDidDisappear:;
- (void)setContainerView:;
- (void).cxx_destruct;
- (void)setContentView:;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (void)setupUI;
- (id)panGesture;
- (void)setContentScrollView:;
- (void)setPanGesture:;
- (id)dismissController;
- (void)handlePanGesture:;
- (id)dismissCompletion;
- (void)setupLayout;
@end
