@interface AWENearbyDualLastFMPManager : AWENearbyFMPBaseManager
@property (nonatomic) BOOL feedShow;
@property (nonatomic) BOOL transformerShow;
@property (nonatomic) double feedCost;
@property (nonatomic) double transformerCost;
@property (nonatomic) BOOL isFirstArea;
@property (nonatomic) q areaType;
@property (nonatomic) q interruptedScene;
@property (nonatomic) NSString transformerFMPSdkResult;
@property (nonatomic) BOOL isFeedShow;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)feedRequestFail;
- (void)feedRequestEmpty;
- (void)transformerRequestFail;
- (void)transformerRequestEmpty;
- (void)transformerDidShowParams:renderTime:error:;
- (void)setFeedCost:;
- (void)setTransformerFMPSdkResult:;
- (id)transformerFMPSdkResult;
- (double)feedCost;
- (void)setIsFeedShow:;
- (id)injectCustomParams;
- (BOOL)isFeedShow;
- (id)injectEventName;
- (void)feedStartSetCover;
- (void)setIsFirstArea:;
- (BOOL)isFirstArea;
- (void)feedDidShowParams:;
- (BOOL)transformerShow;
- (void)setFeedShow:;
- (void)setTransformerCost:;
- (BOOL)feedShow;
- (void)setTransformerShow:;
- (double)transformerCost;
- (long long)interruptedScene;
- (void)setInterruptedScene:;
- (id)init;
- (void).cxx_destruct;
- (long long)areaType;
- (void)setAreaType:;
+ (id)sharedInstanceWithPageType:;
@end
