@interface AWEOpenShareService : HTSService
@property (nonatomic) AWEOpenShareManager shareManager;
@property (nonatomic) BDOpenSDKPasteShareData shareData;
@property (nonatomic) double timeDiff;
@property (nonatomic) NSString sendTimeStamp;
@property (nonatomic) BOOL usingClipboard;
@property (nonatomic) NSString creationID;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)shareManager;
- (id)creationID;
- (id)consumerGetReqFromURL:;
- (BOOL)handleConsumerGetReq:withUserInfo:completion:;
- (void)setSendTimeStamp:;
- (id)sendTimeStamp;
- (void)getPasteboardItemsWithCert:completion:;
- (void)setCreationID:;
- (void)handleAwemeShareWithDict:;
- (void)handleAwemeShareFromSystemExtension:;
- (id)popCreationID;
- (void)setUsingClipboard:;
- (BOOL)usingClipboard;
- (void)setTimeDiff:;
- (id)extractedShareDataFromQueryParams:;
- (id)secretPara;
- (id)styleIDWithURL:;
- (double)timeDiff;
- (id)generateCreationID;
- (void)setShareManager:;
- (id)init;
- (void).cxx_destruct;
- (id)shareData;
- (void)setShareData:;
+ (id)consumerGetReqFromURL:;
+ (BOOL)handleConsumerGetReq:withUserInfo:completion:;
+ (id)URLFromProviderGetResp:;
+ (BOOL)ignoreLogin;
+ (void)registerShareServiceWithShareDelegate:;
+ (id)getShareDelegate;
+ (BOOL)requireLoginBeforeStart;
+ (void)getInvokeGameInfoWithSecUid:roomId:gameId:completion:;
+ (void)reportShareWithID:when:params:;
+ (void)addShareTrackInfo:toPublishModel:;
+ (void)startShareWithResp:params:completion:;
+ (void)handleCommonAbilityWithUrlString:;
+ (id)monitorTrackerBuildOpenPlatformParamsWithURL:;
+ (BOOL)shouldUseNewPublishAbilityWithClientKey:params:;
+ (id)handleSDKParams:isUL:;
+ (id)handleH5Params:;
+ (id)handleSystemParams:;
+ (id)sharedInstance;
+ (id)serviceName;
@end
