@interface AWEPublishPrivacyHalfScreenViewController : UIViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) AWEPublishPrivacyOptionViewController optionVC;
@property (nonatomic) UINavigationController innerNavigation;
@property (nonatomic) AFDModalViewHelper helper;
@property (nonatomic) AFDPrivacyPublishParamsModel paramsModel;
@property (nonatomic) BOOL shouldDismissChildVC;
@property (nonatomic) BOOL needMixConfrimAlert;
@property (nonatomic) NSArray disallowedCellTypes;
@property (nonatomic) @? selectPrivacyBlock;
@property (nonatomic) @? willSelectPrivacyBlock;
@property (nonatomic) @? shouldKeepPageWhenSelectPrivacy;
@property (nonatomic) @? dismissBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @? didSelectedAdvanceSettingCellBlock;
- (BOOL)wantsDimmingTransitionBackground;
- (void)transitionBackgroundViewTapped:;
- (void)presentedViewPanFinished;
- (id)awemeID;
- (void)updateContentHeight:;
- (id)aAWEAwemeInteractionManagerDOUYINLiteAdapter;
- (id)paramsModel;
- (void)setParamsModel:;
- (void)dismissHalfScreen;
- (id)initWithParamsModel:;
- (BOOL)isNewFriendsDailyPublishPanelSettingStyleRadicalStatus;
- (id)initWithAweme:previousPage:referString:enterFrom:scene:;
- (void)setDisallowedCellTypes:;
- (id)sceneTypeForTrack;
- (void)dismissHalfScreenWithChildVC;
- (void)setOptionVC:;
- (id)optionVC;
- (void)setupTransitionController;
- (double)p_getContentHeight;
- (void)setInnerNavigation:;
- (id)innerNavigation;
- (void)confirmPrivacySettingAndDismiss:andChildVC:keepPage:;
- (void)trackConfirmEvent:;
- (void)setShouldDismissChildVC:;
- (id)constructPublishOutputParamsModelWithExtraParams:;
- (BOOL)isNewFriendsDailyPublishPanelExperimentStatus;
- (id)willSelectPrivacyBlock;
- (id)selectPrivacyBlock;
- (void)setNeedMixConfrimAlert:;
- (BOOL)needMixConfrimAlert;
- (BOOL)shouldShowLiteChangePrivacyPopupWithPrivacyOption:awemeModel:;
- (void)p_changePrivacyTypeWithParamsModel:fromRedEnvelopePanel:;
- (id)shouldKeepPageWhenSelectPrivacy;
- (id)__fromStatus;
- (void)trackDismissWithType:;
- (void)confirmPrivacySettingAndDismiss:andChildVC:;
- (void)confirmToNormalAndDismiss;
- (long long)duetDownloadSettingScene;
- (id)didSelectedAdvanceSettingCellBlock;
- (void)p_changePrivacyTypeWithContext:fromRedEnvelopePanel:;
- (void)p_changeAwemePrivacy:;
- (BOOL)shouldDismissChildVC;
- (void)p_needMixConfirmAlertAndChangeAwemePrivacyWithContext:;
- (void)confirmToNormalAndDismissWithIs24Story:changePrivacyParams:;
- (void)transferToNotMateCanSeeSetting;
- (void)pushAdvanceSettingMenuAfterPublish;
- (void)pushAdvancedSettingViewController;
- (void)pushSaveSettingViewController;
- (void)pushXiguaPrivacySettingViewController;
- (void)handleQuickFlashRedEnvelopeSetPrivateWithParamsModel:fromRedEnvelopePanel:;
- (void)handleQuickFlashRedEnvelopeSetPrivateWhenEditTitleWithParamsModel:;
- (void)setSelectPrivacyBlock:;
- (void)setWillSelectPrivacyBlock:;
- (void)setShouldKeepPageWhenSelectPrivacy:;
- (void)setDidSelectedAdvanceSettingCellBlock:;
- (id)disallowedCellTypes;
- (void)show;
- (void)viewDidLoad;
- (void)viewWillAppear:;
- (void)setHelper:;
- (void).cxx_destruct;
- (id)helper;
- (id)dismissBlock;
- (void)setDismissBlock:;
+ (Class)aAWEAwemeInteractionManagerDOUYINLiteAdapterClass;
@end
