@interface AWEPostPageGoodsElement : AWEPostPageAnchorCheckCellElement
@property (nonatomic) AWENewPublishGoodsTableCell goodsTableViewCell;
@property (nonatomic) BOOL hasShoppingCartPermission;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSDictionary extras;
- (BOOL)hasShoppingCartPermission;
- (void)setHasShoppingCartPermission:;
- (id)starAtlas;
- (id)poiService;
- (void)elementAppear;
- (void)didSelectAnchorWithType:anchorDismissBlock:enterFromType:;
- (void)addAIAnchorWithType:anchorDismissBlock:;
- (void)setupCell:;
- (void)refreshWithAnchorVM:;
- (void)configPlaceholderUI;
- (BOOL)canHandleAnchorType:;
- (BOOL)hasGoodsSticker;
- (void)refreshAnchorGoodsWith:;
- (void)goodsStickerConflictCheck;
- (void)cleanGoodsCache;
- (void)showReminderIfNeeded;
- (void)removeReminder;
- (id)goodsTableViewCell;
- (void)p_goodsCellClicked;
- (void)p_asyncGoodsEditInfoNotification:;
- (void)updateShoppingCartAnchor:;
- (void)toastIfNeededForDraftID:;
- (void)trackPublishGoodsAnchorClicked;
- (id)commerceOpenShareHelper;
- (void)setGoodsTableViewCell:;
- (void)cleanUp;
- (void)viewDidDisappear:;
- (void)viewWillAppear:;
- (BOOL)isVisible;
- (void)setViewModel:;
- (void).cxx_destruct;
- (BOOL)isEnabled;
- (id)extras;
- (id)cell;
- (void)setupUI;
- (void)addObservers;
- (void)didSelect;
+ (void)_aweLazyRegisterPostPage;
+ (id)type;
@end
