@interface AWEPadModuleAdapter : NSObject
@property (nonatomic) <AWEIpadLongpressService> longPress;
@property (nonatomic) <AWEIpadShareService> share;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)feedAutoPlayService;
- (id)getPadProtocol:;
- (void)addRotateObserverWithRootViewController:observer:;
- (void)removeRotateObserverWithRootViewController:observer:;
- (id)insideSplitScreenService;
- (id)classroomDetailAdapter;
- (id)padSplitScreenAdapter;
- (id)searchEntranceService;
- (id)pushUIService;
- (id)trackAdapter;
- (id)albumUIService;
- (id)panelAdapter;
- (id)rotationTranslationAdapter;
- (id)interactUIService;
- (id)progressUIService;
- (id)padUIAdapter;
- (id)channelService;
- (id)longVideoPlayerService;
- (id)padUtilsInterface;
- (id)iPadPiPService;
- (id)keyboardBindingsService;
- (id)padDanmakuService;
- (id)padSpeedAdapter;
- (id)inviteWatchGuideService;
- (id)videoPlayService;
- (id)playerAdapter;
- (id)systemSplitScreenService;
- (id)longPress;
- (id)share;
- (id)bubble;
- (id)weakTarget;
+ (id)createPadModuleAdapter;
+ (Class)padSplitScreenAdapterClass;
+ (Class)weakTargetClass;
@end
