@interface AWEPOICityDetailOldFeedComponentViewModel : DitoComponentViewModel
@property (nonatomic) AWEAwemeModel aweme;
@property (nonatomic) AWEPOICityDetailOldFeedComponentView cell;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q cellIndex;
@property (nonatomic) BOOL isFirst;
@property (nonatomic) BOOL isLast;
@property (nonatomic) q modelIndex;
@property (nonatomic) q awemeIndex;
@property (nonatomic) BOOL hasRemoved;
@property (nonatomic) BOOL hasTracked;
- (id)getAwemeModel;
- (id)aweme;
- (void)setAweme:;
- (BOOL)hasTracked;
- (void)setHasTracked:;
- (void)canEnterLiveRoom:;
- (void)trackShow;
- (void)setIsFirst:;
- (void)setIsLast:;
- (id)poiDetail;
- (id)zoomTransitionView;
- (long long)awemeIndex;
- (void)setAwemeIndex:;
- (void)setHasRemoved:;
- (BOOL)hasRemoved;
- (void)bindStateAndAction;
- (id)componentSizeWithMaxWidth:;
- (id)constData;
- (id)generalContext;
- (void)componentViewDidCompleteShow;
- (id)syncFeedManager;
- (void)tryEnterLive;
- (void)tryEnterFeed;
- (long long)viewModelIndex;
- (id)biserialCellFrame;
- (void)didTapVideo;
- (id)biserialAwemeSizeWithMaxWidth:;
- (BOOL)hasAweme;
- (id)fullPageFeedExtension;
- (id)initWithNode:;
- (id)store;
- (void).cxx_destruct;
- (long long)cellIndex;
- (BOOL)isFirst;
- (id)cell;
- (BOOL)isLast;
- (void)setCell:;
- (BOOL)hasModel;
- (unsigned long long)indexInGroup;
- (long long)modelIndex;
- (void)setModelIndex:;
- (void)setCellIndex:;
@end
