@interface AWEPublishSaveToAlbumTask : AWEPublishCommonTask
@property (nonatomic) AWEPublishBaseStage mergeStage;
@property (nonatomic) AWEPublishWaterMarkStage waterMarkStage;
@property (nonatomic) NSTimer timer;
@property (nonatomic) Q savePathStyle;
@property (nonatomic) NSNumber saveAlbumFinished;
@property (nonatomic) NSNumber saveCloudAlbumFinished;
@property (nonatomic) NSNumber saveDraftFinished;
@property (nonatomic) NSString saveCloudAlbumFailedText;
@property (nonatomic) AWEVideoPublishViewModel inputModel;
@property (nonatomic) NSError saveError;
@property (nonatomic) BOOL taskFailed;
@property (nonatomic) double startTime;
@property (nonatomic) double expectedSaveDuration;
@property (nonatomic) AWEPublishFlowModel flowModel;
@property (nonatomic) AWEUserModel customerWatermarkAuthorInfo;
@property (nonatomic) BOOL isFeedVideoMergeTask;
@property (nonatomic) BOOL forceIgnoreWatermark;
@property (nonatomic) BOOL isFromSaveAsVideoManager;
@property (nonatomic) AWEVideoDraftTracer tracer;
@property (nonatomic) BOOL silent;
@property (nonatomic) BOOL hasBroken;
@property (nonatomic) BOOL parallelEdit;
@property (nonatomic) @? updateSourceModel;
@property (nonatomic) AWEVideoPublishViewModel sourcePublishModel;
@property (nonatomic) <ACCPublishServiceSaveAlbumDelegate> saveAlbumDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_updateProgress:;
- (BOOL)taskFailed;
- (void)setCurrentStage:;
- (void)p_showSuccessToast;
- (id)editService;
- (void)setEditService:;
- (void)setFlowModel:;
- (id)flowModel;
- (id)sequenceEditService;
- (void)setSequenceEditService:;
- (void)publishStage:didChangeStatus:userInfo:;
- (void)publishStage:updateProgress:;
- (void)stage:didChangeStatus:;
- (void)setParallelEdit:;
- (id)mergeStage;
- (void)setMergeStage:;
- (BOOL)isFeedVideoMergeTask;
- (void)setTaskFailed:;
- (void)saveDraft:;
- (id)customerWatermarkAuthorInfo;
- (void)setCustomerWatermarkAuthorInfo:;
- (BOOL)parallelEdit;
- (id)waterMarkStage;
- (void)setWaterMarkStage:;
- (void)setUpdateSourceModel:;
- (void)setSourcePublishModel:;
- (void)setSaveAlbumDelegate:;
- (void)setIsFeedVideoMergeTask:;
- (void)setForceIgnoreWatermark:;
- (BOOL)forceIgnoreWatermark;
- (void)setIsFromSaveAsVideoManager:;
- (BOOL)isFromSaveAsVideoManager;
- (void)setHasBroken:;
- (id)updateSourceModel;
- (id)sourcePublishModel;
- (void)setExpectedSaveDuration:;
- (void)trackDownloadEventIfNeed;
- (void)p_trackImageAlbumDownloadStatusIfNeedWithIsStart:;
- (void)p_startTimerToUpdateProgress;
- (BOOL)p_shouldSaveAlbumWithWatermarkStage;
- (long long)p_getCurrentSaveStyle;
- (void)p_didFinishWithUserInfo:;
- (void)p_handleProcessImageStageDoneWithUserInfo:;
- (void)syncImageQualityTrackWithURL:;
- (double)expectedSaveDuration;
- (BOOL)p_shouldSaveAlbumWithWatermarkForSourceClip;
- (void)setSavePathStyle:;
- (void)setSaveAlbumFinished:;
- (void)setSaveCloudAlbumFinished:;
- (void)setSaveDraftFinished:;
- (void)p_trackDownload;
- (unsigned long long)savePathStyle;
- (void)p_errorAction:;
- (void)p_checkAllSaveTaskDidFinish;
- (void)p_saveToAlbum:;
- (void)p_saveToCloudAlbumWithInfo:completion:;
- (void)p_clearQuickSaveAlbumInfo;
- (void)p_deleteDraftIfNeeded;
- (id)p_trackExtra;
- (id)p_handleCloudAlbumReourceWithInfo:;
- (void)setSaveCloudAlbumFailedText:;
- (BOOL)hasBroken;
- (id)saveAlbumFinished;
- (id)saveCloudAlbumFinished;
- (id)saveDraftFinished;
- (void)p_trackDownloadStatusWithFailedPathInfo:;
- (id)saveCloudAlbumFailedText;
- (id)saveAlbumDelegate;
- (void)notifyWillAppend;
- (void)failWithError:;
- (void)setTimer:;
- (void)dealloc;
- (id)timer;
- (void)setStartTime:;
- (void)resume;
- (void)execute;
- (id)initWithModel:;
- (void).cxx_destruct;
- (double)startTime;
- (id)inputModel;
- (void)setInputModel:;
- (void)willResignActiveNotification:;
- (void)setTimeTracker:;
- (id)timeTracker;
- (id)tracer;
- (void)setTracer:;
- (id)saveError;
- (void)setSaveError:;
- (void)setSilent:;
- (BOOL)silent;
@end
