@interface AWEPOIDetailFeedUgcRateGradientExpandConfig : NSObject
@property (nonatomic) Q gradientStyle;
@property (nonatomic) NSArray gradientColors;
@property (nonatomic) NSArray gradientLocations;
@property (nonatomic) {CGPoint=dd} gradientStartPoint;
@property (nonatomic) {CGPoint=dd} gradientEndPoint;
@property (nonatomic) double gradientWidth;
@property (nonatomic) NSString text;
@property (nonatomic) UIFont font;
@property (nonatomic) UIColor textColor;
@property (nonatomic) UIColor backgroundColor;
@property (nonatomic) {UIEdgeInsets=dddd} textContainerInset;
@property (nonatomic) {UIEdgeInsets=dddd} margin;
@property (nonatomic) double cornerRadius;
- (void)setGradientLocations:;
- (id)margin;
- (void)setText:;
- (void)setCornerRadius:;
- (id)text;
- (id)gradientColors;
- (void)setTextColor:;
- (id)textContainerInset;
- (void)setMargin:;
- (id)backgroundColor;
- (id)font;
- (void)setBackgroundColor:;
- (void).cxx_destruct;
- (double)cornerRadius;
- (void)setFont:;
- (void)setTextContainerInset:;
- (id)textColor;
- (void)setGradientColors:;
- (id)gradientLocations;
- (unsigned long long)gradientStyle;
- (void)setGradientStyle:;
- (id)gradientEndPoint;
- (id)gradientStartPoint;
- (void)setGradientEndPoint:;
- (void)setGradientStartPoint:;
- (double)gradientWidth;
- (void)setGradientWidth:;
@end
