@interface AWEPrivacyAudioCameraDataCollector : NSObject
@property (nonatomic) AWEPrivacyAudioCameraConfig config;
@property (nonatomic) NSString lastPageName;
@property (nonatomic) NSString lastTopViewBounds;
@property (nonatomic) NSString screenBounds;
@property (nonatomic) double lastTimestamp;
@property (nonatomic) BOOL floatViewState;
@property (nonatomic) BOOL isBackground;
@property (nonatomic) NSInteger index;
@property (nonatomic) NSString audioGraphEventID;
@property (nonatomic) NSString audioUnitEventID;
@property (nonatomic) NSString recordEventID;
@property (nonatomic) NSString cameraEventID;
@property (nonatomic) NSString uuid;
@property (nonatomic) @? workItem;
@property (nonatomic) @? delayRelaseItem;
@property (nonatomic) NSHashTable veRecorderViews;
@property (nonatomic) NSHashTable avPreviewLayers;
@property (nonatomic) NSString veAssociateViewController;
@property (nonatomic) NSString avAssociateViewController;
@property (nonatomic) q videoPreviewStatus;
- (id)workItem;
- (void)setWorkItem:;
- (id)lastPageName;
- (BOOL)enableCollect;
- (void)topviewDidChangeWithName:;
- (void)setVeRecorderViews:;
- (void)setAvPreviewLayers:;
- (id)veRecorderViews;
- (id)controllerNameWhithResponder:;
- (void)setVeAssociateViewController:;
- (id)pageService;
- (void)setLastPageName:;
- (void)setLastTopViewBounds:;
- (void)reportClassName:methodName:videoPreviewStatus:isDelayRelease:;
- (void)setVideoPreviewStatus:;
- (int)videoPreviewNumber;
- (void)delayReleaseDetect:;
- (void)resetUUID;
- (id)avPreviewLayers;
- (void)setAvAssociateViewController:;
- (long long)videoPreviewStatus;
- (id)cameraEventID;
- (void)setDelayRelaseItem:;
- (id)delayRelaseItem;
- (id)audioUnitEventID;
- (id)audioGraphEventID;
- (id)recordEventID;
- (void)setFloatViewState:;
- (BOOL)floatViewState;
- (void)windowDetect;
- (id)veAssociateViewController;
- (id)avAssociateViewController;
- (id)lastTopViewBounds;
- (void)setCameraEventID:;
- (void)setRecordEventID:;
- (void)setAudioUnitEventID:;
- (void)setAudioGraphEventID:;
- (void)addPreview:;
- (void)updateFloatViewState:withName:;
- (void)setIndex:;
- (void)setConfig:;
- (int)index;
- (id)screenBounds;
- (id)init;
- (void)didEnterBackground:;
- (id)uuid;
- (id)tracker;
- (id)config;
- (void)setUuid:;
- (void)setLastTimestamp:;
- (void).cxx_destruct;
- (void)didBecomeActive:;
- (BOOL)isBackground;
- (double)lastTimestamp;
- (void)setIsBackground:;
- (void)handleEvent:;
- (void)setScreenBounds:;
- (void)addPreviewLayer:;
+ (id)sharedInstance;
+ (void)start;
@end
