@interface AWEPOIDetailTableViewLocationCell : AWEPOIDetailTableViewCell
@property (nonatomic) UIImageView mapIcon;
@property (nonatomic) UIImageView navigateIcon;
@property (nonatomic) UILabel locationLabel;
@property (nonatomic) UILabel distanceLabel;
@property (nonatomic) BOOL hasPhoneNumber;
@property (nonatomic) BOOL hasCompanyPage;
@property (nonatomic) BOOL hasDistance;
@property (nonatomic) UIView callAreaContainerView;
@property (nonatomic) UIImageView callIcon;
@property (nonatomic) UIView callAreaSeparator;
@property (nonatomic) UIView companyAreaContainerView;
@property (nonatomic) UIImageView companyIcon;
@property (nonatomic) UIView companyAreaSeparator;
@property (nonatomic) DitoPageContext context;
@property (nonatomic) <AWEPOIDetailTableViewLocationCellDelegate> delegate;
- (void)setMapIcon:;
- (void)p_updateConstraints;
- (void)setHasCompanyPage:;
- (BOOL)hasCompanyPage;
- (void)selfLongTap:;
- (void)p_setupLocationLabel;
- (void)p_setupMapIcon;
- (void)p_setupDistanceLabel;
- (void)p_setupCallArea;
- (void)p_setupCompanyArea;
- (double)p_mapIconOffset;
- (void)setCallAreaContainerView:;
- (void)handleTapOnCallArea:;
- (id)callAreaContainerView;
- (void)setCallIcon:;
- (id)callIcon;
- (BOOL)p_needSetAreaSeparator;
- (void)setCallAreaSeparator:;
- (id)callAreaSeparator;
- (void)setCompanyAreaContainerView:;
- (void)handleTapOnCompanyArea:;
- (id)companyAreaContainerView;
- (void)setCompanyIcon:;
- (id)companyIcon;
- (void)setCompanyAreaSeparator:;
- (id)companyAreaSeparator;
- (id)navigateIcon;
- (void)setAddress:distance:;
- (void)handleTapOnNavigate:;
- (void)hideContentViews;
- (void)setNavigateIcon:;
- (void)setHasDistance:;
- (void)setDistance:;
- (id)delegate;
- (id)systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:;
- (void)setLocation:;
- (id)initWithFrame:;
- (void)setup;
- (void)setContext:;
- (void).cxx_destruct;
- (BOOL)hasDistance;
- (void)setDelegate:;
- (id)context;
- (id)distanceLabel;
- (void)setDistanceLabel:;
- (BOOL)hasPhoneNumber;
- (id)locationLabel;
- (void)setLocationLabel:;
- (id)mapIcon;
- (void)setHasPhoneNumber:;
+ (double)cellHeightForLocation:distance:hasPhoneNumber:hasCompanyPage:;
+ (id)attributedLocationTextForAddress:distance:hasPhoneNumber:hasCompanyPage:;
+ (double)locationLabelWidthForInfoWithPhoneNumber:withCompanyPage:;
@end
