@interface AWEPlayInteractionScreenCastInnerFeedController : AWEPlayInteractionBaseController
@property (nonatomic) UIView<BDByteScreenCastLivePlayerControlViewProtocol> screenCastControlView;
@property (nonatomic) UIView<BDByteScreenCastLivePlayerControlViewProtocol> originalControlView;
@property (nonatomic) UIView blackView;
@property (nonatomic) UIView animationBackGroundView;
@property (nonatomic) double originViewHeight;
@property (nonatomic) BOOL isInShrink;
@property (nonatomic) BOOL hasHide;
@property (nonatomic) AWEScreenCastControlViewConfig awemeCastConfig;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setHide:;
- (void)didDisplay;
- (BOOL)isScreenCasting;
- (void)videoDidShrink;
- (void)videoDidMagnify;
- (BOOL)videoContentIsLandscape;
- (id)screenCastControlView;
- (void)closeButtonClicked:;
- (id)aAWEFeedModuleServiceDOUYINJXAdapter;
- (BOOL)checkIsScreenCastSubView:;
- (void)removeControlViewIfNeeded;
- (void)enterScreenCastStatusIfNeeded;
- (void)removeScreenCastControlView;
- (void)updateScreenCastViewLayout:;
- (void)setScreenCastControlView:;
- (void)updateScreenCastConfig:;
- (void)showControlView:;
- (void)updateControlViewFrame;
- (void)castPlayProgressInfoChanged:;
- (void)castPlayStatusChanged:;
- (void)alreadyCastPlayAllVideos;
- (id)castExtraParams:;
- (double)startScreenCastPlayTime;
- (void)closeCastButtonClicked:;
- (void)didConnectToDevice;
- (void)willVideoDidShrink;
- (void)videoContentFameDidChange;
- (BOOL)hasHide;
- (void)setHasHide:;
- (id)blackView;
- (id)currentProgressInfo;
- (id)animationBackGroundView;
- (void)setIsInShrink:;
- (double)originViewHeight;
- (void)setOriginViewHeight:;
- (BOOL)isInShrink;
- (void)setBlackView:;
- (void)setAnimationBackGroundView:;
- (id)originalControlView;
- (void)showOriginalControlView:;
- (id)awemeCastConfig;
- (void)setAwemeCastConfig:;
- (void)setOriginalControlView:;
- (void)resetControlViewTargetSize;
- (void)closeCastWithReason:;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)containerView;
- (void).cxx_destruct;
- (void)viewDidAppear;
- (void)didEndDisplaying;
- (void)willDisplay;
+ (Class)aAWEFeedModuleServiceDOUYINJXAdapterClass;
@end
