@interface AWEPOIMarkViewUIConfigModel : NSObject
@property (nonatomic) UIImage markImage;
@property (nonatomic) NSNumber markWidthBetweenImageAndText;
@property (nonatomic) NSNumber markLeftMargin;
@property (nonatomic) NSNumber markRightMargin;
@property (nonatomic) NSNumber markCornerRadius;
@property (nonatomic) NSNumber spaceBetweenMarkLabelAndVerticalSeperateLine;
@property (nonatomic) NSNumber spaceBetweenSeperateLineAndAdTag;
@property (nonatomic) double verticalSeperateLineHeight;
@property (nonatomic) UIColor seperateLineBackgroundColor;
@property (nonatomic) UIColor markLabelTextColor;
@property (nonatomic) UIFont markLabelTextFont;
@property (nonatomic) double markLabelTextAlpha;
@property (nonatomic) UIImage markBackgroundImage;
@property (nonatomic) UIColor containerViewBackgroundColor;
@property (nonatomic) NSString adTagText;
@property (nonatomic) UIColor adTagTextColor;
@property (nonatomic) UIFont adTagTextFont;
@property (nonatomic) UIColor tagTextColor;
@property (nonatomic) UIFont tagTextFont;
@property (nonatomic) BOOL needIconDarkBkg;
@property (nonatomic) double labelHeightWhenNotExpanded;
@property (nonatomic) double labelHeightWhenExpanded;
@property (nonatomic) {CGSize=dd} markImageSize;
@property (nonatomic) BOOL hideArrow;
@property (nonatomic) NSNumber markLabelMinWidth;
- (void)setTagTextFont:;
- (void)setTagTextColor:;
- (id)markImageSize;
- (void)setMarkImageSize:;
- (void)setAdTagText:;
- (void)setMarkImage:;
- (void)setMarkCornerRadius:;
- (void)setMarkLeftMargin:;
- (void)setMarkRightMargin:;
- (void)setContainerViewBackgroundColor:;
- (void)setMarkWidthBetweenImageAndText:;
- (void)setMarkLabelTextFont:;
- (void)setMarkLabelTextColor:;
- (void)setSpaceBetweenMarkLabelAndVerticalSeperateLine:;
- (void)setVerticalSeperateLineHeight:;
- (void)setSeperateLineBackgroundColor:;
- (void)setAdTagTextFont:;
- (void)setAdTagTextColor:;
- (void)setSpaceBetweenSeperateLineAndAdTag:;
- (void)setHideArrow:;
- (id)markCornerRadius;
- (id)markLeftMargin;
- (id)markLabelTextColor;
- (id)containerViewBackgroundColor;
- (id)seperateLineBackgroundColor;
- (id)tagTextColor;
- (void)setMarkLabelTextAlpha:;
- (void)setMarkBackgroundImage:;
- (void)setNeedIconDarkBkg:;
- (void)setLabelHeightWhenExpanded:;
- (void)setLabelHeightWhenNotExpanded:;
- (id)adTagTextColor;
- (id)markWidthBetweenImageAndText;
- (id)markRightMargin;
- (id)markImage;
- (id)spaceBetweenMarkLabelAndVerticalSeperateLine;
- (id)spaceBetweenSeperateLineAndAdTag;
- (double)verticalSeperateLineHeight;
- (id)markLabelTextFont;
- (double)markLabelTextAlpha;
- (id)markBackgroundImage;
- (id)adTagText;
- (id)adTagTextFont;
- (id)tagTextFont;
- (BOOL)needIconDarkBkg;
- (double)labelHeightWhenNotExpanded;
- (double)labelHeightWhenExpanded;
- (BOOL)hideArrow;
- (id)markLabelMinWidth;
- (void)setMarkLabelMinWidth:;
- (void).cxx_destruct;
+ (id)model;
@end
