@interface AWEProfileExtensionAreaCardModel : MTLModel
@property (nonatomic) Q cardType;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) NSString originSubtitle;
@property (nonatomic) NSString schema;
@property (nonatomic) NSString originCardData;
@property (nonatomic) NSDictionary originCardDataDict;
@property (nonatomic) NSString category;
@property (nonatomic) NSString eventParams;
@property (nonatomic) AWEURLModel lightIconURLModel;
@property (nonatomic) AWEURLModel darkIconURLModel;
@property (nonatomic) AWEProfileExtensionEditInfoModel editPageInfo;
@property (nonatomic) AWEProfileExtensionAreaDiamondDataInfoModel diamondDataInfoModel;
@property (nonatomic) NSNumber isCurrentUser;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setEventParams:;
- (id)originCardData;
- (id)lightIconURLModel;
- (id)darkIconURLModel;
- (id)diamondDataInfoModel;
- (id)originSubtitle;
- (void)setOriginSubtitle:;
- (BOOL)imFansGroup_shouldShowPrivilegeEscalationGuideWithUid:;
- (id)originCardDataDict;
- (void)setOriginCardData:;
- (id)editPageInfo;
- (void)setLightIconURLModel:;
- (void)setDarkIconURLModel:;
- (void)setEditPageInfo:;
- (void)setDiamondDataInfoModel:;
- (id)schema;
- (id)category;
- (void)setSchema:;
- (id)subtitle;
- (void)setSubtitle:;
- (void)setCategory:;
- (void).cxx_destruct;
- (id)title;
- (void)setTitle:;
- (id)isCurrentUser;
- (void)setIsCurrentUser:;
- (unsigned long long)cardType;
- (void)setCardType:;
- (id)eventParams;
+ (id)lightIconURLModelJSONTransformer;
+ (id)darkIconURLModelJSONTransformer;
+ (id)editPageInfoJSONTransformer;
+ (id)diamondDataInfoModelJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
