@interface AWEPOINearbyHotListDataController : AWEListDataController
@property (nonatomic) q page;
@property (nonatomic) q pageSize;
@property (nonatomic) NSMutableDictionary rawToFiltered;
@property (nonatomic) AWERxProperty isRequesting;
@property (nonatomic) AWERxProperty feedList;
@property (nonatomic) AWERxProperty hasMoreData;
@property (nonatomic) NSString poiId;
@property (nonatomic) double longitude;
@property (nonatomic) double latitude;
@property (nonatomic) AWEPOINearbyHotPrefetcher prefetcher;
- (void)loadMoreWithCompletion:;
- (void)initFetchWithCompletion:;
- (long long)filteredDataSourceIndexFromIndex:;
- (id)isRequesting;
- (void)setIsRequesting:;
- (id)feedList;
- (void)setFeedList:;
- (void)p_handleResponse:error:completion:;
- (void)setRawToFiltered:;
- (id)rawToFiltered;
- (void)setPrefetcher:;
- (id)prefetcher;
- (void)p_fetchData:;
- (id)distanceByLongitude:latitude:longitude:latitude:;
- (long long)page;
- (id)init;
- (void)setLatitude:;
- (double)latitude;
- (void)setLongitude:;
- (double)longitude;
- (void).cxx_destruct;
- (void)refreshWithCompletion:;
- (id)hasMoreData;
- (void)setPage:;
- (id)poiId;
- (void)setPoiId:;
- (long long)pageSize;
- (void)setPageSize:;
- (void)setHasMoreData:;
@end
