@interface AWEPlayInteractionChapterElement : AWEPlayInteractionLeftElement
@property (nonatomic) UIView container;
@property (nonatomic) DUXBaseImageView chapterIcon;
@property (nonatomic) UILabel chapterLabel;
@property (nonatomic) DUXBaseImageView arrowIcon;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)viewController_willDisplay;
- (id)activateInfoWithData:;
- (void)layoutElementView;
- (id)arrowIcon;
- (void)setArrowIcon:;
- (id)aAWEFeedModuleServiceDOUYINJXAdapter;
- (void)handleClickChapterEntrance:;
- (BOOL)enableSmartChapterKeyPoint;
- (void)trackChapterEntranceShow;
- (void)handleShareButtonClicked:;
- (id)chapterIcon;
- (id)chapterLabel;
- (void)trackChapterEntranceClick;
- (void)setChapterIcon:;
- (void)setChapterLabel:;
- (void)setContainer:;
- (id)container;
- (void)dealloc;
- (void)viewDidLoad;
- (void).cxx_destruct;
+ (id)activateInfoWithContext:;
+ (Class)aAWEFeedModuleServiceDOUYINJXAdapterClass;
+ (BOOL)shouldShowChapterEntrance:;
@end
