@interface AWEPOIGoodsDetailNavigationBarNew : DitoComponentView
@property (nonatomic) <DitoComponentViewModel> viewModel;
@property (nonatomic) DUXNavigationBar duxNavigationBar;
@property (nonatomic) DUXNavigationBarImageAction duxLeftAction;
@property (nonatomic) DUXNavigationBarImageAction duxShareAction;
@property (nonatomic) BOOL hasShareButtonShow;
@property (nonatomic) AWEPOIGoodsDetailShareCouponBubbleManager shareCouponBubbleManager;
@property (nonatomic) AWEPOIGoodsDetailNavigationBarNewViewModel navigationBarVM;
@property (nonatomic) AWEGradientView gradientView;
@property (nonatomic) UIImage backWhiteImage;
@property (nonatomic) UIImage backBlackImage;
@property (nonatomic) UIImage closeWhiteImage;
@property (nonatomic) UIImage closeBlackImage;
@property (nonatomic) UIImage shareWhiteImage;
@property (nonatomic) UIImage shareBlackImage;
@property (nonatomic) AWEPOIGoodsDetailNavigationBarUIModel startState;
@property (nonatomic) AWEPOIGoodsDetailNavigationBarUIModel endState;
@property (nonatomic) double startShowElevatorOffset;
@property (nonatomic) double elevatorVisibleOffset;
@property (nonatomic) BOOL isPopup;
@property (nonatomic) BOOL shouldShowTitle;
@property (nonatomic) BOOL shouldShowGradientView;
@property (nonatomic) AWEPOIGoodsDetailElevatorView elevatorView;
@property (nonatomic) NSArray titleTabs;
@property (nonatomic) BOOL shouldShowElevator;
@property (nonatomic) BOOL hasPingbackNavBarShow;
@property (nonatomic) AWEGDNoActionEventHandler noActionEventHandler;
- (id)duxNavigationBar;
- (void)setDuxNavigationBar:;
- (void)updateViewModel:;
- (id)navigationBarVM;
- (void)setNavigationBarVM:;
- (void)backButtonPress;
- (BOOL)isPopup;
- (id)noActionEventHandler;
- (void)setNoActionEventHandler:;
- (void)setTitleTabs:;
- (id)titleTabs;
- (id)elevatorView;
- (double)startShowElevatorOffset;
- (void)setStartShowElevatorOffset:;
- (double)elevatorVisibleOffset;
- (void)setElevatorVisibleOffset:;
- (void)setIsPopup:;
- (id)duxLeftAction;
- (id)duxShareAction;
- (void)setElevatorView:;
- (id)shareCouponBubbleManager;
- (BOOL)hasShareButtonShow;
- (void)setHasShareButtonShow:;
- (id)shareTrackParams;
- (void)openSharePanel;
- (void)shareButtonPress;
- (void)setDuxLeftAction:;
- (void)setDuxShareAction:;
- (void)setShareCouponBubbleManager:;
- (void)setShouldShowTitle:;
- (void)p_bindActionAndState;
- (void)resetUIByCurrentOffset:;
- (void)updateElevatorStyleWithOffsetYValue:;
- (void)updateBackgroundWithAlpha:isElevator:;
- (void)pingbackNavBarShow;
- (BOOL)shouldShowGradientView;
- (void)alphaAnimationWithContext:;
- (void)navigationBarDidShow;
- (BOOL)hasPingbackNavBarShow;
- (void)setHasPingbackNavBarShow:;
- (void)setShouldShowGradientView:;
- (id)closeWhiteImage;
- (id)backWhiteImage;
- (id)closeBlackImage;
- (id)backBlackImage;
- (id)shareWhiteImage;
- (id)shareBlackImage;
- (void)setShouldShowElevator:;
- (void)setupDUXUI;
- (void)initStartStateBackground;
- (void)updateElevatorViewWithForce:;
- (void)setDuxAction:withUrl:defaultImage:;
- (id)leftBlackImage;
- (id)leftWhiteImage;
- (id)elevatorBackgroundColorWithAlpha:;
- (id)normalBackgroundColorWithAlpha:;
- (void)setBackWhiteImage:;
- (void)setBackBlackImage:;
- (void)setCloseWhiteImage:;
- (void)setCloseBlackImage:;
- (void)setShareWhiteImage:;
- (void)setShareBlackImage:;
- (BOOL)shouldShowElevator;
- (id)gradientView;
- (id)startState;
- (id)viewModel;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)setGradientView:;
- (id)endState;
- (void)setEndState:;
- (void)setStartState:;
- (void)updateTitle;
- (BOOL)shouldShowTitle;
- (id)initWithFrame:viewModel:;
@end
