@interface AWEPadSkyLightTopBarViewController : UIViewController
@property (nonatomic) UICollectionView listView;
@property (nonatomic) UIImageView backgroundImage;
@property (nonatomic) UIView sectionContainer;
@property (nonatomic) AWEPadSkyLightCardViewController liveContainerVC;
@property (nonatomic) AWEPadSkyLightCardViewController gameContainerVC;
@property (nonatomic) AWEPadBaseSectionViewModel<AWEPLVSectionViewModelProtocol> liveSectionData;
@property (nonatomic) AWEPadBaseSectionViewModel<AWEPLVSectionViewModelProtocol> gameSectionData;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} lastFrame;
@property (nonatomic) AWEPadSkyLightTopBarViewModel viewModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)initFetch;
- (void)setupListAdapter;
- (void)updatesectionContainerLayout;
- (id)sectionContainer;
- (id)liveContainerVC;
- (id)gameContainerVC;
- (void)setupSectionContainerForHorizontal;
- (id)liveSectionData;
- (id)gameSectionData;
- (void)setLiveSectionData:;
- (void)setGameSectionData:;
- (void)updateSectionDatas:completion:;
- (void)setSectionContainer:;
- (void)setLiveContainerVC:;
- (void)setGameContainerVC:;
- (id)backgroundImage;
- (void)setBackgroundImage:;
- (id)initWithViewModel:;
- (void)viewDidLayoutSubviews;
- (id)viewModel;
- (void)viewDidLoad;
- (id)listView;
- (double)contentHeight;
- (void)setListView:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)setupUI;
- (id)lastFrame;
- (void)setLastFrame:;
@end
