@interface AWEPOIDouDiscountItemCard : MTLModel
@property (nonatomic) q avgPrice;
@property (nonatomic) NSString backendTypeName;
@property (nonatomic) NSString poiName;
@property (nonatomic) NSString buyButtonText;
@property (nonatomic) NSDictionary qualityScoreBigPic;
@property (nonatomic) NSDictionary qualityScoreSmallPic;
@property (nonatomic) NSString rankText;
@property (nonatomic) NSString bizZone;
@property (nonatomic) NSString distanceText;
@property (nonatomic) NSString poiID;
@property (nonatomic) q recommendScore;
@property (nonatomic) NSString lynxCardUrl;
@property (nonatomic) q openTimems;
@property (nonatomic) AWEPOIDouDiscountPOICardConf douDiscountPOICardConf;
@property (nonatomic) AWEURLModel poiHeadImg;
@property (nonatomic) q distance;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)poiID;
- (id)poiName;
- (void)setPoiName:;
- (void)setPoiID:;
- (long long)avgPrice;
- (void)setAvgPrice:;
- (id)backendTypeName;
- (void)setBackendTypeName:;
- (id)buyButtonText;
- (void)setBuyButtonText:;
- (id)qualityScoreBigPic;
- (void)setQualityScoreBigPic:;
- (id)qualityScoreSmallPic;
- (void)setQualityScoreSmallPic:;
- (id)rankText;
- (void)setRankText:;
- (id)bizZone;
- (void)setBizZone:;
- (id)distanceText;
- (void)setDistanceText:;
- (long long)recommendScore;
- (void)setRecommendScore:;
- (id)lynxCardUrl;
- (void)setLynxCardUrl:;
- (long long)openTimems;
- (void)setOpenTimems:;
- (id)douDiscountPOICardConf;
- (void)setDouDiscountPOICardConf:;
- (id)poiHeadImg;
- (void)setPoiHeadImg:;
- (void)setDistance:;
- (long long)distance;
- (void).cxx_destruct;
+ (id)JSONKeyPathsByPropertyKey;
@end
