@interface AWEPOIDetailSummaryView : UIView
@property (nonatomic) UILabel poiNameLabel;
@property (nonatomic) UILabel businessHourLabel;
@property (nonatomic) AWEModernPOIDetailCollectButton collectButton;
@property (nonatomic) AWEPOIDetailRatingContainerView ratingView;
@property (nonatomic) UILabel visitCountLabel;
@property (nonatomic) UILabel subTypeLabel;
@property (nonatomic) NSMutableArray detailViews;
@property (nonatomic) UIView topAnchorView;
@property (nonatomic) q detailViewOptions;
@property (nonatomic) AWEPOIDetailSummaryConfig config;
@property (nonatomic) <AWEPOIDetailSummaryViewDelegate> delegate;
@property (nonatomic) I enableFunctions;
@property (nonatomic) Q collectStyle;
- (id)initWithFrame:config:;
- (id)collectButton;
- (void)setCollectButton:;
- (void)handleShare;
- (void)setPoiNameLabel:;
- (id)poiNameLabel;
- (void)configureWithPOI:;
- (void)handleCollect;
- (void)p_setupUIWithPOIDetail:;
- (unsigned int)enableFunctions;
- (void)setDetailViewOptions:;
- (void)p_setupTopRightCollectButtonWithPOIDetail:;
- (void)p_setupPOINameLabelWithPOIDetail:;
- (void)p_setupPOIBusinessHourLabelWithPOIDetail:;
- (void)p_setupSubTypeViewWithPOIDetail:;
- (void)p_setupVisitCountViewWithPOIDetail:;
- (void)p_setupCostViewWithPOIDetail:;
- (void)p_setupBottomButtonWithPOIDetail:;
- (void)p_addLayoutConstraints;
- (unsigned long long)collectStyle;
- (void)setTopAnchorView:;
- (long long)detailViewOptions;
- (void)setVisitCountLabel:;
- (id)visitCountLabel;
- (void)setSubTypeLabel:;
- (id)subTypeLabel;
- (void)setBusinessHourLabel:;
- (id)businessHourLabel;
- (id)topAnchorView;
- (BOOL)p_needAdjustSubTypeLabelToRight;
- (void)poiNameLabelLongTap:;
- (void)setConfig:;
- (id)delegate;
- (id)config;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)ratingView;
- (void)setRatingView:;
- (void)setDetailViews:;
- (id)detailViews;
+ (double)heightForPOI:config:;
+ (id)p_formattedCostForCost:;
+ (double)poiDetailSummaryCellVerticalSpace;
+ (id)poiAttrTitleWithPoiName:isForDisplay:;
+ (double)poiTitleLabelMaxWidthWithConfig:;
+ (id)poiAttrBusinessHourWithBusinessHour:isForDisplay:;
+ (BOOL)enableBusinessHour:functions:;
+ (long long)p_optionsForDetailViewsToAddForPOIDetail:functions:;
+ (double)poiDetailSummaryDetailViewHeight;
+ (BOOL)enableBottomCollectionWithConfig:;
+ (double)poiDetailSummaryBottomCollectionViewHeight;
+ (BOOL)enableTopRightCollectionWithConfig:;
+ (id)topRightCollectButtonContentSizeOfStyle:isCollected:;
+ (double)maxWidthTopRightCollectButtonContentSizeOfStyle:;
+ (id)detailLabelForText:;
+ (id)p_costStringForPOIDetail:;
+ (id)poiTitleFont;
+ (id)p_detailLabelsTextFont;
+ (double)p_detailLabelWidthForText:;
+ (BOOL)p_hasValidCostForPOI:;
+ (BOOL)p_shouldSetupCollectButton;
+ (BOOL)enableCollectWithFunctions:;
+ (id)poiTitleAttributes:;
+ (id)poiBusinessHourFont;
+ (id)p_lastCharacterFrameWithPoiDetail:config:;
@end
