@interface AWEPOIGoodsDetailRenderPriorityManager : NSObject
@property (nonatomic) BOOL shouldOptimize;
@property (nonatomic) AWEGoodsDetailPageContext context;
@property (nonatomic) <DitoLynxExtensionProtocol> ditoLynxExtension;
@property (nonatomic) Q strategyType;
@property (nonatomic) BOOL isFullScreenStatus;
@property (nonatomic) Q curPriority;
@property (nonatomic) BOOL preRenderFinished;
@property (nonatomic) double curHeight;
@property (nonatomic) Q recursionCount;
@property (nonatomic) NSMutableDictionary tagToHeightMap;
@property (nonatomic) double pageHeight;
- (void)setStrategyType:;
- (unsigned long long)strategyType;
- (BOOL)isFullScreenStatus;
- (void)setIsFullScreenStatus:;
- (void)didEndReload;
- (void)ditoExtension:didReceiveSizeChangeWithViewTag:;
- (void)ditoExtensionDidPreloadLynx:;
- (void)setDitoLynxExtension:;
- (id)ditoLynxExtension;
- (void)optimizeLynxRenderPriority:;
- (id)initWithContext:isFullScreenStatus:lynxExtension:;
- (void)setCurPriority:;
- (void)setPreRenderFinished:;
- (void)setRecursionCount:;
- (void)setTagToHeightMap:;
- (void)setupLynxExtension:;
- (BOOL)shouldOptimize;
- (void)optimizeLynxRenderPriorityDefaultStrategy:;
- (void)optimizeLynxRenderPriorityNewStrategy:;
- (double)curHeight;
- (unsigned long long)recursionCount;
- (unsigned long long)curPriority;
- (BOOL)preRenderFinished;
- (id)tagToHeightMap;
- (void)setCurHeight:;
- (void)setContext:;
- (void).cxx_destruct;
- (id)context;
- (double)pageHeight;
- (void)setPageHeight:;
- (void)updatePriority;
@end
