@interface AWEProfileAvatarPreviewPendantButton : AWEAnimatedButton
@property (nonatomic) NSString enterFrom;
@property (nonatomic) AWEUserModel user;
@property (nonatomic) AWEUserModel currentLoginUser;
@property (nonatomic) BOOL isCurrentLoginUser;
@property (nonatomic) AWEUserAvatarDecotationModel decoration;
@property (nonatomic) UIImageView avatarPendantImageView;
@property (nonatomic) UIImageView avatarPendantBackgroundDropView;
@property (nonatomic) UILabel pendantTitleLabel;
@property (nonatomic) UIImageView atmosphereBackgroundImageView;
@property (nonatomic) UIImageView avatarThumbImageView;
@property (nonatomic) BOOL isButtonClickedAction;
@property (nonatomic) AWEProfileAvatarPreviewPendantManager pandantManager;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setEnterFrom:;
- (id)enterFrom;
- (id)currentLoginUser;
- (id)superView;
- (void)setCurrentLoginUser:;
- (void)setupNormalUI;
- (BOOL)isCurrentLoginUser;
- (void)setIsCurrentLoginUser:;
- (void)setupAtmosphereUI;
- (void)configureContentWithModel:;
- (id)pendantTitleLabel;
- (id)avatarPendantBackgroundDropView;
- (id)avatarPendantImageView;
- (void)setAtmosphereBackgroundImageView:;
- (id)atmosphereBackgroundImageView;
- (id)avatarThumbImageView;
- (id)pandantManager;
- (void)removeAvatarPreviewViewWhenPushingViewController:;
- (void)setPendantTitleLabelFontSize:;
- (id)initWithFrame:user:enterFrom:;
- (void)setAvatarPendantImageView:;
- (void)setAvatarPendantBackgroundDropView:;
- (void)setPendantTitleLabel:;
- (void)setAvatarThumbImageView:;
- (BOOL)isButtonClickedAction;
- (void)setIsButtonClickedAction:;
- (void)setPandantManager:;
- (id)user;
- (void)setUser:;
- (void)setHidden:;
- (void).cxx_destruct;
- (id)decoration;
- (void)setDecoration:;
@end
