@interface AWEPreloginOneLoginDataController : NSObject
@property (nonatomic) @? preLoginCompleteBlock;
@property (nonatomic) @? stopLoadingBlock;
@property (nonatomic) q maskloginDuration;
@property (nonatomic) NSObject<AWEUserLoginUILayoutConfig> layoutConfig;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) q carrierType;
@property (nonatomic) q requestTokenDuration;
@property (nonatomic) double carrierLoginStart;
@property (nonatomic) q tokenloginDuration;
@property (nonatomic) DYRouterModel routerModel;
@property (nonatomic) NSDictionary loginResultMonitorDict;
- (void)setEnterFrom:;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)enterFrom;
- (void)setCarrierType:;
- (long long)carrierType;
- (void)setLayoutConfig:;
- (id)routerModel;
- (void)setRouterModel:;
- (void)trackLoginDurationWithStatus:;
- (id)loginResultMonitorDict;
- (double)carrierLoginStart;
- (long long)requestTokenDuration;
- (void)setCarrierLoginStart:;
- (void)setLoginResultMonitorDict:;
- (void)handleLoginError:ticket:;
- (void)setRequestTokenDuration:;
- (void)requestTokenLogin:withError:;
- (void)requestQuickLoginWithToken:;
- (void)setPreLoginCompleteBlock:;
- (void)setStopLoadingBlock:;
- (void)carrierLoginWithRequest:;
- (void)setMaskloginDuration:;
- (void)trackLoginPhoneLoginFailureWithIsMask:error:;
- (void)preRequestCarrierLoginCarrierType:;
- (void)handleLoginSuccessAccount:ticket:preLogin:callback:;
- (id)preLoginCompleteBlock;
- (long long)maskloginDuration;
- (long long)tokenloginDuration;
- (id)stopLoadingBlock;
- (void)setTokenloginDuration:;
- (void)checkEnableOneLoginWithLastOneLoginUser:Completion:;
- (void)preRequestPrefetchLoginWithPhoneNumber:carrierType:completion:stopLoadingBlock:;
- (void).cxx_destruct;
- (id)layoutConfig;
@end
