@interface AWEPlayVideoPlayerContext : NSObject
@property (nonatomic) BDSimPlayerMediaModel media;
@property (nonatomic) double time;
@property (nonatomic) <AWEPlayVideoDelegate> playerDelegate;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) q playState;
@property (nonatomic) q previousPlayState;
@property (nonatomic) q loopTimes;
@property (nonatomic) double currentPlaybackTime;
@property (nonatomic) double totalPlayTime;
@property (nonatomic) NSNumber videoDuration;
@property (nonatomic) double defaultSeekToTime;
@property (nonatomic) q coverContentMode;
@property (nonatomic) BOOL shouldAdaptFullScreen;
@property (nonatomic) NSString referString;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString reactId;
@property (nonatomic) NSDictionary logExtraDict;
@property (nonatomic) NSDictionary btmInfo;
@property (nonatomic) NSNumber slideType;
@property (nonatomic) NSString adEventName;
@property (nonatomic) NSDictionary adExtraData;
@property (nonatomic) NSString ruleId;
@property (nonatomic) NSNumber clickEnter;
@property (nonatomic) BOOL hasReportClickEnter;
@property (nonatomic) NSDictionary context;
@property (nonatomic) BOOL useNormalCover;
@property (nonatomic) NSTimer bufferingChecktimer;
@property (nonatomic) BOOL previousKeepAlive;
@property (nonatomic) BOOL isPlayFailedShown;
@property (nonatomic) BOOL finishLogged;
@property (nonatomic) BOOL albumFinishLogged;
@property (nonatomic) BOOL isReadyForDisplay;
@property (nonatomic) BOOL isPlayStarted;
@property (nonatomic) BOOL hasBlockBeforeStart;
@property (nonatomic) BOOL isPlaybackFailed;
@property (nonatomic) double playStartTimestamp;
@property (nonatomic) double stallStartTimestamp;
@property (nonatomic) Q fullscreenEnterCnt;
@property (nonatomic) Q fullscreenExitCnt;
@property (nonatomic) BOOL alreadyRecordPlayCompletion;
@property (nonatomic) HTSTimingTracker timingTracker;
@property (nonatomic) NSNumber calcBitrate;
@property (nonatomic) Q stallCount;
@property (nonatomic) double stallTotalDuration;
@property (nonatomic) NSTimer volumeSyncTimer;
@property (nonatomic) double playStartSystemVolumn;
@property (nonatomic) BOOL shouldDiscardReport;
@property (nonatomic) BOOL blockedWithAlertView;
@property (nonatomic) BOOL isPlayerInStall;
@property (nonatomic) BOOL pauseBySingleClick;
@property (nonatomic) NSDictionary avOutsyncInfo;
@property (nonatomic) double outsyncBegin;
@property (nonatomic) BOOL shouldPreventTrackPlayTime;
@property (nonatomic) BOOL isCDNURLExpired;
@property (nonatomic) NSString connectMethod;
@property (nonatomic) NSString enterMethodForTrack;
@property (nonatomic) NSMutableDictionary playIndexDic;
@property (nonatomic) BOOL coverImageLoaded;
@property (nonatomic) Q totalStallCount;
@property (nonatomic) double totalStallTotalDuration;
@property (nonatomic) BOOL earPhone;
@property (nonatomic) NSDictionary firstFrameTimestamp;
@property (nonatomic) NSNumber playbackTimeWhenStop;
@property (nonatomic) NSDictionary contextInfoWhenStop;
@property (nonatomic) NSArray playURLs;
@property (nonatomic) q preloadSize;
@property (nonatomic) NSTimer videoPlayCheckTimer;
@property (nonatomic) q currentVideoCheckCount;
@property (nonatomic) BOOL shouldShowCoverWhenSeekToTime;
@property (nonatomic) BOOL isResourceRecallEnabled;
@property (nonatomic) double lastPlayTimestamp;
@property (nonatomic) NSDictionary playVideoQualityExtraInfo;
@property (nonatomic) NSDictionary videoPlayEndParams;
@property (nonatomic) BOOL enableHDR;
@property (nonatomic) BOOL hasPreCreatedPlayer;
@property (nonatomic) NSString searchVideoMethod;
@property (nonatomic) NSNumber qualityType;
@property (nonatomic) NSTimer videoBufferTimer;
@property (nonatomic) NSString pageType;
@property (nonatomic) NSString cityInfoString;
@property (nonatomic) q playType;
@property (nonatomic) NSString originEntryEnterMethod;
@property (nonatomic) double playVideoDuration;
@property (nonatomic) double currPlaybackTime;
@property (nonatomic) double currPlayableDuration;
@property (nonatomic) q scalingMode;
@property (nonatomic) BOOL repeated;
@property (nonatomic) BOOL mute;
@property (nonatomic) double volume;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setStallCount:;
- (id)reactId;
- (void)setReactId:;
- (id)cityInfoString;
- (void)setCityInfoString:;
- (id)originEntryEnterMethod;
- (void)setOriginEntryEnterMethod:;
- (void)setLogExtraDict:;
- (id)referString;
- (void)setEnterFrom:;
- (void)setReferString:;
- (id)logExtraDict;
- (double)defaultSeekToTime;
- (id)adExtraData;
- (void)setAdExtraData:;
- (id)searchVideoMethod;
- (void)setSearchVideoMethod:;
- (id)btmInfo;
- (void)setBtmInfo:;
- (long long)loopTimes;
- (double)totalPlayTime;
- (double)playStartTimestamp;
- (long long)coverContentMode;
- (void)setCoverContentMode:;
- (BOOL)shouldAdaptFullScreen;
- (void)setShouldAdaptFullScreen:;
- (BOOL)useNormalCover;
- (void)setUseNormalCover:;
- (BOOL)pauseBySingleClick;
- (void)setPauseBySingleClick:;
- (id)clickEnter;
- (void)setClickEnter:;
- (id)slideType;
- (void)setSlideType:;
- (BOOL)hasReportClickEnter;
- (void)setHasReportClickEnter:;
- (id)enterFrom;
- (id)adEventName;
- (void)setAdEventName:;
- (void)setDefaultSeekToTime:;
- (id)playerDelegate;
- (void)setPlayerDelegate:;
- (void)setShouldShowCoverWhenSeekToTime:;
- (unsigned long long)stallCount;
- (double)currPlayableDuration;
- (double)currPlaybackTime;
- (void)setPlayType:;
- (id)playURLs;
- (BOOL)isPlayerInStall;
- (BOOL)isPlayStarted;
- (void)setIsPlayStarted:;
- (long long)preloadSize;
- (void)setPreloadSize:;
- (BOOL)shouldShowCoverWhenSeekToTime;
- (void)setPlayStartTimestamp:;
- (void)setPreviousKeepAlive:;
- (BOOL)isPlayFailedShown;
- (void)setIsPlayFailedShown:;
- (void)setIsPlaybackFailed:;
- (void)setPlayURLs:;
- (BOOL)isPlaybackFailed;
- (BOOL)previousKeepAlive;
- (BOOL)isCDNURLExpired;
- (void)setIsCDNURLExpired:;
- (void)setLoopTimes:;
- (void)setCurrPlaybackTime:;
- (void)setTotalPlayTime:;
- (void)setCurrPlayableDuration:;
- (BOOL)isResourceRecallEnabled;
- (void)setIsResourceRecallEnabled:;
- (void)setStallStartTimestamp:;
- (double)stallStartTimestamp;
- (double)stallTotalDuration;
- (void)setStallTotalDuration:;
- (double)lastPlayTimestamp;
- (void)setLastPlayTimestamp:;
- (void)setTotalStallTotalDuration:;
- (double)totalStallTotalDuration;
- (void)setShouldDiscardReport:;
- (BOOL)finishLogged;
- (void)setFinishLogged:;
- (void)setCoverImageLoaded:;
- (void)setPreviousPlayState:;
- (id)videoBufferTimer;
- (BOOL)shouldDiscardReport;
- (void)setIsPlayerInStall:;
- (BOOL)blockedWithAlertView;
- (id)playIndexDic;
- (id)videoPlayCheckTimer;
- (void)setBlockedWithAlertView:;
- (void)setVideoBufferTimer:;
- (void)setPlayStartSystemVolumn:;
- (void)setCalcBitrate:;
- (void)setCurrentVideoCheckCount:;
- (long long)currentVideoCheckCount;
- (void)setVideoPlayCheckTimer:;
- (long long)previousPlayState;
- (void)setPlayIndexDic:;
- (id)connectMethod;
- (void)setConnectMethod:;
- (double)playStartSystemVolumn;
- (id)calcBitrate;
- (BOOL)coverImageLoaded;
- (BOOL)alreadyRecordPlayCompletion;
- (void)setAlreadyRecordPlayCompletion:;
- (id)bufferingChecktimer;
- (void)setBufferingChecktimer:;
- (BOOL)albumFinishLogged;
- (void)setAlbumFinishLogged:;
- (BOOL)hasBlockBeforeStart;
- (void)setHasBlockBeforeStart:;
- (id)volumeSyncTimer;
- (void)setVolumeSyncTimer:;
- (id)avOutsyncInfo;
- (void)setAvOutsyncInfo:;
- (double)outsyncBegin;
- (void)setOutsyncBegin:;
- (BOOL)shouldPreventTrackPlayTime;
- (void)setShouldPreventTrackPlayTime:;
- (id)enterMethodForTrack;
- (void)setEnterMethodForTrack:;
- (BOOL)earPhone;
- (void)setEarPhone:;
- (id)playbackTimeWhenStop;
- (void)setPlaybackTimeWhenStop:;
- (id)contextInfoWhenStop;
- (void)setContextInfoWhenStop:;
- (id)playVideoQualityExtraInfo;
- (void)setPlayVideoQualityExtraInfo:;
- (id)videoPlayEndParams;
- (void)setVideoPlayEndParams:;
- (BOOL)hasPreCreatedPlayer;
- (void)setHasPreCreatedPlayer:;
- (double)playVideoDuration;
- (void)setPlayVideoDuration:;
- (unsigned long long)fullscreenEnterCnt;
- (void)setFullscreenEnterCnt:;
- (unsigned long long)fullscreenExitCnt;
- (void)setFullscreenExitCnt:;
- (double)time;
- (void)setModel:;
- (BOOL)mute;
- (double)volume;
- (void)setTime:;
- (BOOL)isReadyForDisplay;
- (void)setVolume:;
- (void)setCurrentPlaybackTime:;
- (void)setMute:;
- (void)setPageType:;
- (BOOL)enableHDR;
- (id)model;
- (void)setContext:;
- (void)setTimingTracker:;
- (id)timingTracker;
- (void).cxx_destruct;
- (id)videoDuration;
- (double)currentPlaybackTime;
- (id)media;
- (id)context;
- (id)pageType;
- (void)setEnableHDR:;
- (void)setScalingMode:;
- (long long)scalingMode;
- (void)setMedia:;
- (BOOL)repeated;
- (void)setRepeated:;
- (unsigned long long)totalStallCount;
- (void)setTotalStallCount:;
- (id)qualityType;
- (void)setVideoDuration:;
- (long long)playState;
- (void)setPlayState:;
- (id)ruleId;
- (void)setRuleId:;
- (long long)playType;
- (void)setIsReadyForDisplay:;
- (void)setQualityType:;
- (id)firstFrameTimestamp;
- (void)setFirstFrameTimestamp:;
@end
