@interface AWEPushLoginViewController : UIViewController
@property (nonatomic) DYLastLoginUserModel accountNeedLogin;
@property (nonatomic) NSString loginTitle;
@property (nonatomic) AWEUserContext userContext;
@property (nonatomic) NSObject<AWEUserLoginUILayoutConfig> layoutConfig;
@property (nonatomic) AWELoginBackgroundView containerView;
@property (nonatomic) UIView<AWELastAccountLoginView> oneLoginView;
@property (nonatomic) NSObject<AWEUserLoginUIAmbientConfig> ambientConfig;
@property (nonatomic) DYRouterModel routerModel;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) BOOL isKeyboardShow;
@property (nonatomic) BOOL isRecievedResult;
@property (nonatomic) q clickCount;
@property (nonatomic) BOOL prePageIsHalfScreen;
@property (nonatomic) NSString verifyTicket;
@property (nonatomic) @? completionBlock;
@property (nonatomic) BOOL shouldResetBtn;
@property (nonatomic) NSString token;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (void)setEnterFrom:;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)enterFrom;
- (void)setLayoutConfig:;
- (id)verifyTicket;
- (void)setVerifyTicket:;
- (id)routerModel;
- (void)setRouterModel:;
- (BOOL)isKeyboardShow;
- (void)p_setupNavigationBar;
- (void)setIsKeyboardShow:;
- (id)loginTitle;
- (void)setLoginTitle:;
- (id)ambientConfig;
- (void)setAmbientConfig:;
- (void)handleDeviceOrientationChangeNotification;
- (void)helpAction;
- (id)p_trackInfo;
- (void)otherLoginAction;
- (void)countdownFinish;
- (void)clickLoginWithView:index:;
- (void)clickOtherLoginWithView:;
- (void)setAccountNeedLogin:;
- (id)oneLoginView;
- (id)accountNeedLogin;
- (void)clickHelpWithView:;
- (void)setOneLoginView:;
- (id)aAWEUserModuleConfigCommonAdapter;
- (id)aAWEUserModuleServiceDOUYINAdapter;
- (void)didReceiveLongConnectionNotification:;
- (BOOL)shouldResetBtn;
- (void)setIsRecievedResult:;
- (void)startCheckPushResultWithToken:;
- (void)verifyCompletionWithSuccess:;
- (void)checkPushResultWithToken:;
- (BOOL)isRecievedResult;
- (void)rejectLogin;
- (void)sendPush;
- (id)initWithRouterModel:lastLoginUserModel:;
- (void)setShouldResetBtn:;
- (BOOL)prePageIsHalfScreen;
- (void)setPrePageIsHalfScreen:;
- (void)setUserContext:;
- (id)userContext;
- (void)dealloc;
- (void)setCompletionBlock:;
- (void)viewDidLayoutSubviews;
- (id)completionBlock;
- (void)viewDidLoad;
- (id)containerView;
- (void)setClickCount:;
- (void)setContainerView:;
- (void).cxx_destruct;
- (void)setToken:;
- (void)viewDidAppear:;
- (void)invalidateTimer;
- (id)token;
- (void)closeAction;
- (long long)clickCount;
- (void)deviceOrientationDidChange:;
- (id)layoutConfig;
+ (Class)aAWEUserModuleConfigCommonAdapterClass;
+ (Class)aAWEUserModuleServiceDOUYINAdapterClass;
@end
