@interface AWEPadPMCSeriesHistoryModel : MTLModel
@property (nonatomic) NSString seriesID;
@property (nonatomic) NSString seriesName;
@property (nonatomic) NSArray coverUrl;
@property (nonatomic) NSString watchedItem;
@property (nonatomic) NSNumber wacthedTime;
@property (nonatomic) NSNumber watchedEpisode;
@property (nonatomic) NSString extraInfo;
@property (nonatomic) q calendarGroupID;
@property (nonatomic) NSNumber playVV;
@property (nonatomic) BOOL isExclusive;
@property (nonatomic) NSArray horizontalCoverUrl;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setCoverUrl:;
- (id)coverUrl;
- (id)watchedItem;
- (void)setWatchedItem:;
- (id)watchedEpisode;
- (void)setWatchedEpisode:;
- (id)seriesID;
- (void)setSeriesID:;
- (id)horizontalCoverUrl;
- (id)playVV;
- (void)setHorizontalCoverUrl:;
- (void)setPlayVV:;
- (id)wacthedTime;
- (void)setWacthedTime:;
- (long long)calendarGroupID;
- (void)setCalendarGroupID:;
- (BOOL)isExclusive;
- (void)setSeriesName:;
- (void).cxx_destruct;
- (id)seriesName;
- (id)extraInfo;
- (void)setIsExclusive:;
- (void)setExtraInfo:;
+ (id)JSONKeyPathsByPropertyKey;
@end
