@interface AWEPadSplitDetailWrapViewController : UIViewController
@property (nonatomic) double offsetX;
@property (nonatomic) UIViewController tableViewController;
@property (nonatomic) BOOL canAutorotate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)transition_didPopDoneTransitionWithContext:;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (BOOL)transition_shouldStartInteractiveTranstionForSlideDirection:gestureRecognizer:;
- (void)transition_didStartTransitionWithContext:;
- (BOOL)transition_gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (id)awe_preferredTransitionProviderClassNameForContext:;
- (id)transition_destinatedViewControllerForSlideDirection:gestureRecognizer:;
- (BOOL)transition_enableCustomActionForSlideDirection:gestureRecognizer:;
- (void)transition_performCustomActionForSlideDirection:gestureRecognizer:;
- (id)transition_directlyPresentingViewController;
- (BOOL)transition_shouldStartInteractiveTranstionToVC:;
- (void)transition_didCancelPercentDrivenTransitionWithContext:;
- (BOOL)isFromLocalHotSpot;
- (id)trendingKeyWord;
- (void)appendTrackParamsIfNeeded:;
- (void)hideHotInteractionView:;
- (id)aAWEPadDetailTableAdapter;
- (void)padSplitUpdateViewOffsetX:;
- (void)setCanAutorotate:;
- (BOOL)canAutorotate;
- (void)refreshTableViewFrameIfNeeded;
- (BOOL)isMemberOfClass:;
- (BOOL)prefersStatusBarHidden;
- (BOOL)isKindOfClass:;
- (void)viewDidLayoutSubviews;
- (id)forwardingTargetForSelector:;
- (BOOL)respondsToSelector:;
- (BOOL)conformsToProtocol:;
- (long long)preferredStatusBarStyle;
- (void).cxx_destruct;
- (void)forwardInvocation:;
- (id)methodSignatureForSelector:;
- (void)setTableViewController:;
- (id)tableViewController;
- (double)offsetX;
- (void)setOffsetX:;
+ (Class)aAWEPadDetailTableAdapterClass;
@end
