@interface AWEPublishAdvanceSettingsDuetPermissionCell : UITableViewCell
@property (nonatomic) AWEPublishAdvanceSettingsDuetPermissionItem item;
@property (nonatomic) UIImageView iconImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIView lineView;
@property (nonatomic) UILabel introLabel;
@property (nonatomic) UIImageView arrowImageView;
@property (nonatomic) AFDRoundedView containerView;
@property (nonatomic) Q cornerType;
@property (nonatomic) NSIndexPath indexPath;
@property (nonatomic) <AWEPublishAdvanceSettingsCellDelegate> delegate;
@property (nonatomic) @? onSwitcherToggledBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)awe_themeDidChange:;
- (void)setupCorners;
- (void)showBottomLine:;
- (void)onCellClicked;
- (void)updateViewWithControlEnabled:;
- (id)delegate;
- (void)setHighlighted:animated:;
- (id)indexPath;
- (void)setItem:;
- (id)containerView;
- (id)item;
- (void)setIndexPath:;
- (void)setContainerView:;
- (id)initWithStyle:reuseIdentifier:;
- (void)setTitleLabel:;
- (id)iconImageView;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setDelegate:;
- (void)layoutSubviews;
- (unsigned long long)accessibilityTraits;
- (BOOL)isAccessibilityElement;
- (void)updateWithItem:;
- (id)lineView;
- (void)setIconImageView:;
- (void)setLineView:;
- (void)setupUI;
- (unsigned long long)cornerType;
- (void)setCornerType:;
- (id)introLabel;
- (void)setIntroLabel:;
- (id)arrowImageView;
- (void)setArrowImageView:;
+ (double)cellHeight;
@end
