@interface AWEPOIUGCRateListNGViewController : DitoGeneralContainerViewController
@property (nonatomic) AWEPOIUGCRatePageContext context;
@property (nonatomic) AWEPOIUGCRateAgentHandler agentHandler;
@property (nonatomic) AWEPOIDetailNGAutoPlayUtil autoPlayer;
@property (nonatomic) <AWEPOIDetailNGAutoPlayUtilObjectProtocol> currentPlayingObject;
@property (nonatomic) <AWEPOISyncFeedExtensionProtocol> syncFeedManager;
@property (nonatomic) AWEPOITouchThroughView interactMaskView;
@property (nonatomic) BOOL hasRouteToDefaultUrl;
@property (nonatomic) BOOL didConfigWithRouterParams;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)configWithRouterParamDict:;
- (BOOL)btm_autoManaged;
- (id)btm_pageIdentifier;
- (void)cancelVideoPreload;
- (void)recordStartTime;
- (void)registerExtensions;
- (id)extraBizParams;
- (void)trackStayTime;
- (void)windowDidResignKeyNotification:;
- (void)windowDidBecomeKeyNotification:;
- (id)previewingViewControllerForView:atPoint:;
- (id)previewingSourceRectForView:atPoint:;
- (void)pageDidScroll:;
- (void)trackExit;
- (void)bindStateAndAction;
- (id)DitoPageScene;
- (void)didLoadPageModel:;
- (void)didEndReload;
- (void)pageDidEndDragging:willDecelerate:;
- (void)pageDidEndDecelerating:;
- (void)pageWillBeginDragging:;
- (void)pageDidEndScrollingAnimation:;
- (id)constData;
- (void)loadMoreWithParams:completion:;
- (id)syncFeedManager;
- (void)registerAgents;
- (void)setupBuilder;
- (BOOL)hasMoreWithPageModel:;
- (id)awemeModelWithViewModelTag:;
- (id)zoomTransitionStartViewWithViewModelTag:;
- (id)videoPlayerForSyncFeedExtensionTransition;
- (void)syncFeedExtensionWillReturnToViewModelTag:isScrolled:;
- (void)syncFeedExtensionDidReturnToViewModelTag:;
- (BOOL)shouldSyncFeedExtensionUpdatePlayerWithAwemeModel:fromContext:;
- (id)syncFeedGroupComponentNodeTagList;
- (id)extraPerformanceTrackParams;
- (id)autoPlayer;
- (id)currentPlayingObject;
- (void)autoStopObject:;
- (id)currentPlayingCell;
- (void)setCurrentPlayingObject:;
- (void)autoPlayObject:;
- (id)autoPlayVisibleObjects;
- (void)doVideoPreload;
- (void)setSyncFeedManager:;
- (void)setAutoPlayer:;
- (void)showTopInteractiveMaskView;
- (void)hideTopInteractiveMaskView;
- (void)refreshPageMoniterStartTime;
- (id)extraRequestCostParamsForResponse:;
- (id)agentHandler;
- (BOOL)shouldAppendMainBizParamsToLoadMore;
- (id)ratePageContext;
- (void)setAgentHandler:;
- (BOOL)didConfigWithRouterParams;
- (void)setDidConfigWithRouterParams:;
- (id)interactMaskView;
- (BOOL)hasRouteToDefaultUrl;
- (void)setHasRouteToDefaultUrl:;
- (void)trackUgcRateListPageShow;
- (id)stayTimeKey;
- (id)pageTrackingParams;
- (id)getLogExtraDictionary;
- (void)didReceiveInteraction;
- (id)extraRouterParamsForSchema:currentQuery:;
- (void)setInteractMaskView:;
- (void)viewWillDisappear:;
- (id)init;
- (void)dealloc;
- (void)didMoveToParentViewController:;
- (void)viewDidLoad;
- (id)containerView;
- (id)createContext;
- (void)viewDidDisappear:;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (id)requestPath;
@end
