@interface AWEPostPageGeneralAnchorElement : AWEPostPageAnchorCheckCellElement
@property (nonatomic) AWENewPublishAnchorTableViewCell generalViewTableViewCell;
@property (nonatomic) NSString generalViewEnterFrom;
@property (nonatomic) NSString positionCoverPath;
@property (nonatomic) NSArray suggestionModels;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSDictionary extras;
- (id)publishViewModel;
- (id)starAtlas;
- (void)elementAppear;
- (void)didSelectAnchorWithType:anchorDismissBlock:enterFromType:;
- (void)addAIAnchorWithType:anchorDismissBlock:;
- (void)setupCell:;
- (void)refreshWithAnchorVM:;
- (void)configPlaceholderUI;
- (id)mediaTypeForTrack;
- (long long)anchorRequestPublishItemType;
- (BOOL)canHandleAnchorType:;
- (id)getDidSelectedTags;
- (id)getSuggestionTags;
- (id)tagRecommendService;
- (void)setSuggestionModels:;
- (id)suggestionModels;
- (void)addAnchorGeneralViewObserver;
- (id)generalViewTableViewCell;
- (id)singleGeneralViewPublishModel;
- (void)didClickGeneralViewWithType:completion:;
- (BOOL)isGeneralAnchorType:;
- (void)updateGeneralViewWithJsonString:;
- (void)addGeneralViewAnchorNotification:;
- (void)trackGameCPDeleteAnchor;
- (void)setGeneralViewEnterFrom:;
- (id)generalViewEnterFrom;
- (id)positionCoverPath;
- (void)cancelSelectedGeneralView:;
- (void)prepareWithType:completion:;
- (void)setPositionCoverPath:;
- (void)trackGameCPClickAnchor:;
- (void)setGeneralViewTableViewCell:;
- (void)cleanUp;
- (BOOL)isVisible;
- (void).cxx_destruct;
- (BOOL)isEnabled;
- (id)extras;
- (id)cell;
- (void)setupUI;
- (void)didSelect;
+ (void)_aweLazyRegisterPostPage;
+ (id)type;
@end
