@interface AWEPluginRouteCustomImpl : NSObject
@property (nonatomic) @? closeWebViewBlock;
@property (nonatomic) @? adWebViewLoadFinishBlk;
@property (nonatomic) NSString verifyAppId;
@property (nonatomic) @? verifyBlk;
@property (nonatomic) @? payResultBlk;
@property (nonatomic) BDXBridgeEventSubscriber paySubscriber;
@property (nonatomic) @? payCallback;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)transferToURLString:;
- (BOOL)canOpenURLString:;
- (void)onResp:;
- (BOOL)transferToURLStringWithFormat:;
- (void)adWebViewDidFinishLoadWithWebViewController:;
- (void)adWebViewDidFailLoadWithWebViewController:error:;
- (void)didOpenURL:sourceApplication:annotation:;
- (void)setPayCallback:;
- (id)payCallback;
- (void)registerSubscribes;
- (void)unregisterSubscribers;
- (void)bdp_openSchemaAndCloseGameWithUniqueID:URL:userInfo:completion:;
- (void)viewWillAppear:uniqueID:;
- (void)viewDidDisappear:uniqueID:;
- (void)closeWebViewNotification:;
- (void)syncCertificationStatusHandler:;
- (BOOL)bdp_openSchemaWithURL:userInfo:appID:;
- (BOOL)bdp_openSchemaWithURL:userInfo:appID:error:;
- (void)tryEventIMEnterChat:;
- (void)bdp_openLoadFailedPageForChannel:schema:appID:closeHandler:;
- (void)setCloseWebViewBlock:;
- (BOOL)openAdWebUrlWithParam:appID:;
- (BOOL)openOtherWithParam:appID:;
- (id)bdp_loadFailedPageForChannel:schema:appID:loadFinishBlock:;
- (id)adWebUrlWithParam:;
- (void)setAdWebViewLoadFinishBlk:;
- (void)eventAdWebViewOpenWithParams:;
- (id)otherWebViewUrlWithParam:;
- (void)bdp_openLoadFailedPageForNonODRWithParams:schema:appID:closeHandler:;
- (BOOL)bdp_openCustomerServiceWithWebURLString:extraInfo:appID:;
- (BOOL)bdp_checkSidebarScene;
- (id)closeWebViewBlock;
- (void)bdp_navigateToVideoWithParam:appID:completion:;
- (id)adWebViewLoadFinishBlk;
- (void)setVerifyAppId:;
- (void)setVerifyBlk:;
- (id)verifyAppId;
- (id)verifyBlk;
- (void)setPayResultBlk:;
- (void)__registerPlayletPaymentStatusChange;
- (id)paySubscriber;
- (void)setPaySubscriber:;
- (id)payResultBlk;
- (BOOL)bdp_openSchemaWithURL:userInfo:;
- (BOOL)bdp_canOpenLoadFailedPageForChannel:schema:;
- (void)bdp_openLoadFailedPageForChannel:schema:closeHandler:;
- (id)bdp_loadFailedPageForChannel:schema:loadFinishBlock:;
- (BOOL)bdp_openCustomerServiceWithWebURLString:extraInfo:;
- (void)bdp_navigateToVideoWithParam:completion:;
- (BOOL)bdp_openIMCustomerService:;
- (void)bdp_openAppAndReopenGameWithUniqueID:URL:completion:;
- (void)bdp_openGameDetailInfoWithUniqueID:;
- (void)bdp_navigateToScene:uniqueID:url:completion:;
- (void)bdp_openUrl:params:fromH5:completion:;
- (BOOL)bdp_openUserProfile:appID:;
- (void)bdp_openLoadFailedPageForIndustryWithParams:schema:appID:closeHandler:;
- (void)bdp_navigateToRealNamePageWithParam:appID:completion:;
- (void)bdp_navigateToDPPageWithParam:appID:completion:;
- (id)init;
- (void)dealloc;
- (void).cxx_destruct;
- (void)handleOpenURL:;
+ (id)sharedPlugin;
+ (void)handleViewWillAppear:containerVC:;
+ (void)handleViewDidDisappear:containerVC:;
@end
