@interface AWEPlayInteractionConfigsHelper : NSObject
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) AWEAwemeModel fromModel;
@property (nonatomic) NSString referString;
@property (nonatomic) NSDictionary logExtraDict;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) q mediaType;
@property (nonatomic) AWEAwemeModel registerElementModel;
@property (nonatomic) @ commerceController;
@property (nonatomic) AWEPlayInteractionElementStrategyManager strategyManager;
@property (nonatomic) AWEPlayInteractionMetricsMonitor metricsMonitor;
@property (nonatomic) AWEPlayInteractionViewController viewController;
- (void)setLogExtraDict:;
- (id)referString;
- (void)setEnterFrom:;
- (void)setReferString:;
- (id)logExtraDict;
- (id)fromModel;
- (void)setFromModel:;
- (id)enterFrom;
- (id)registerElementModel;
- (void)setRegisterElementModel:;
- (id)strategyManager;
- (BOOL)shouldShowBulletScreen;
- (BOOL)isRemotePlayLegacyVersion;
- (BOOL)isDouDiscountInnerPage;
- (BOOL)isDouDiscountInnerPageWithV2Experiment;
- (BOOL)shouldAddNowFamiliarInterpretationElementsWithBulletsScreen;
- (BOOL)notSmallDevice;
- (BOOL)isNearbyWaterFall;
- (BOOL)shouldShowRelatedBarElement;
- (BOOL)isInTeenExternalAlbum;
- (BOOL)enableInteractionAlienation;
- (id)commerceController;
- (void)setCommerceController:;
- (void)setStrategyManager:;
- (id)metricsMonitor;
- (void)setMetricsMonitor:;
- (void)setModel:;
- (void)setMediaType:;
- (long long)mediaType;
- (id)viewController;
- (id)model;
- (void).cxx_destruct;
- (void)setViewController:;
@end
