@interface AWEPlayletUserProfileTabCollectionHeaderView : UIView
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView playletCoverView;
@property (nonatomic) UIImageView playletIcon;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel updateCountLabel;
@property (nonatomic) AWEPlayletCardInfoModel playletCardModel;
@property (nonatomic) AWEPaymentBadgeView paymentBadgeView;
@property (nonatomic) NSString fromGroupID;
@property (nonatomic) NSString subEntrance;
@property (nonatomic) @? enterPlayletFeedBlock;
@property (nonatomic) UIButton playletButton;
- (void)configWithModel:;
- (id)fromGroupID;
- (void)setFromGroupID:;
- (id)paymentBadgeView;
- (void)setPaymentBadgeView:;
- (id)updateCountLabel;
- (void)setUpdateCountLabel:;
- (void)enterFeed;
- (id)playletCoverView;
- (id)playletIcon;
- (void)setPlayletCoverView:;
- (void)setPlayletIcon:;
- (id)playletButton;
- (void)enterDetail:;
- (void)setPlayletCardModel:;
- (long long)strategyInformationType;
- (id)playletCardModel;
- (id)subEntrance;
- (id)enterPlayletFeedBlock;
- (id)updateCountLabelFont;
- (id)playletButtonFont;
- (void)setEnterPlayletFeedBlock:;
- (void)setPlayletButton:;
- (void)setSubEntrance:;
- (id)initWithFrame:;
- (id)containerView;
- (void)setContainerView:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (id)titleLabelFont;
- (void)setUpUI;
@end
