@interface AWEQuickShareVideoURLChecker : NSObject
@property (nonatomic) BOOL timeout;
@property (nonatomic) NSObject<OS_dispatch_source> downloadVEFileTimer;
@property (nonatomic) NSURL videoURL;
@property (nonatomic) NSURL permanentValidVideoURL;
@property (nonatomic) VEFileDownloader videoURLDownloader;
@property (nonatomic) VEFileDownloader permanentValidDownloader;
@property (nonatomic) BOOL isCheckedVideoURL;
@property (nonatomic) BOOL isCheckedPermanentValidVideoURL;
@property (nonatomic) NSError videoURLError;
@property (nonatomic) NSError permanentValidVideoURLError;
@property (nonatomic) NSError error;
@property (nonatomic) BOOL isPermanentValidURL;
@property (nonatomic) NSURL downloadVideoURL;
@property (nonatomic) VEFileDownloader downloader;
- (void)cancelTimerIfNeeded;
- (BOOL)isCheckedVideoURL;
- (BOOL)isCheckedPermanentValidVideoURL;
- (id)videoURLDownloader;
- (id)permanentValidDownloader;
- (id)downloadVideoURL;
- (void)downloadWithTimerIfNeeded:enterFrom:playerCacheInfo:storyModel:permanentValidVideoURL:timeoutDuration:completion:;
- (void)setDownloadVEFileTimer:;
- (id)downloadVEFileTimer;
- (void)setPermanentValidVideoURL:;
- (void)setVideoURLError:;
- (void)setIsCheckedVideoURL:;
- (BOOL)isPermanentValidURL;
- (id)downloadWithVideoURL:enterFrom:playerCacheInfo:storyModel:completion:;
- (void)setVideoURLDownloader:;
- (void)setPermanentValidVideoURLError:;
- (void)setIsCheckedPermanentValidVideoURL:;
- (void)setPermanentValidDownloader:;
- (void)resumeTimerWithTimeout:completion:;
- (id)permanentValidVideoURL;
- (id)videoURLError;
- (id)permanentValidVideoURLError;
- (void)setVideoURL:;
- (void)setError:;
- (BOOL)timeout;
- (id)downloader;
- (id)videoURL;
- (id)description;
- (void)setTimeout:;
- (void).cxx_destruct;
- (id)error;
@end
