@interface AWERelationSheetContext : NSObject
@property (nonatomic) AWEUserModel user;
@property (nonatomic) AWEUserRelationContext relationContext;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString previousPage;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSString cardType;
@property (nonatomic) q recommendType;
@property (nonatomic) NSDictionary addFriendExtra;
@property (nonatomic) NSString chatType;
@property (nonatomic) NSString conversationID;
@property (nonatomic) NSString fromCardType;
@property (nonatomic) NSString fromRecReason;
@property (nonatomic) NSNumber fromImprOrder;
@property (nonatomic) NSString contactName;
@property (nonatomic) NSString mateApplyMsg;
@property (nonatomic) NSString groupChatName;
@property (nonatomic) NSString groupChatAlias;
- (void)setEnterFrom:;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)enterFrom;
- (long long)recommendType;
- (id)chatType;
- (void)setChatType:;
- (void)setRecommendType:;
- (void)setRelationContext:;
- (void)setFromRecReason:;
- (void)setAddFriendExtra:;
- (id)relationContext;
- (id)mateApplyMsg;
- (void)setMateApplyMsg:;
- (id)groupChatName;
- (void)setGroupChatName:;
- (id)groupChatAlias;
- (void)setGroupChatAlias:;
- (void)setFromCardType:;
- (void)setFromImprOrder:;
- (id)addFriendExtra;
- (id)fromCardType;
- (id)fromRecReason;
- (id)fromImprOrder;
- (id)user;
- (void)setUser:;
- (id)contactName;
- (id)conversationID;
- (void).cxx_destruct;
- (void)setConversationID:;
- (id)previousPage;
- (void)setPreviousPage:;
- (id)cardType;
- (void)setCardType:;
- (void)setContactName:;
@end
