@interface AWERTVFeedContentViewController : RTVFeedContentViewController
@property (nonatomic) <RxInjector> injector;
@property (nonatomic) <RTVXRControllerInjector> controllerInjector;
@property (nonatomic) UIViewController<AFDPlayRemoteFeedContainerViewControllerProtocol> remotePlayViewController;
@property (nonatomic) AWERTVFeedCastVideoPanelController castVideoPanelController;
@property (nonatomic) <RTVFeedVolumeSettingController> volumeSettingController;
@property (nonatomic) <RTVSettingsManager> settingsManager;
@property (nonatomic) <RTVUserProfileManagerInterface> userProfileManager;
@property (nonatomic) <RTVInteractionSendMessageActionControllerInterface> sendMessageActionController;
@property (nonatomic) RTVFeedSharePauseView pauseView;
@property (nonatomic) <AWERTVFeedContentControllers> feedContentControllers;
@property (nonatomic) <AWERTVLongVideoHistoryControllerProtocol> longVideoHistoryController;
@property (nonatomic) BOOL isLocalFeedActive;
@property (nonatomic) BOOL isRemoteFeedActive;
@property (nonatomic) BOOL isPlayPause;
@property (nonatomic) BOOL isFirstApply;
@property (nonatomic) NSString firstApplyIdentifier;
@property (nonatomic) BOOL hadPreloadFeed;
@property (nonatomic) NSSet preloadReceivedCMDSet;
@property (nonatomic) <RTVFeedSharePlayerProviderInterface> playerProvider;
@property (nonatomic) <RTVFeedRequestSyncCommandControllerInterface> commandRequester;
@property (nonatomic) RxDeferred roomInfoReadyDeferred;
@property (nonatomic) q pureMode;
@property (nonatomic) <RTVStorageArea> storageArea;
@property (nonatomic) AWEAwemeModel lastAwemeModel;
@property (nonatomic) AWERTVFeedImpressionTracker impressionTracker;
@property (nonatomic) <RTVFeedSharePIPControllerProtocol> pipController;
@property (nonatomic) <RTVStateMachineInterface> stateMachine;
@property (nonatomic) <RTVFeedQosMonitorInterface> qosMonitor;
@property (nonatomic) <RTVRoomDistributionGuidePresenterInterface> distributionGuidePresenter;
@property (nonatomic) BOOL isShowingSlidingTip;
@property (nonatomic) <RTVParticipantsObserveController> participantsObserveController;
@property (nonatomic) {CGSize=dd} contentSize;
@property (nonatomic) BOOL isLandscape;
@property (nonatomic) NSMutableArray stateRecorderTokens;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)currentAwemeModel;
- (void)setPureMode:;
- (void)pauseWithAnimation;
- (void)playWithAnimation;
- (void)rtv_awakeFromControllerInjector;
- (long long)pureMode;
- (void)didOccurredInteractionVideoPausedWithAwemeModel:;
- (void)didOccurredInteractionVideoPlayWithAwemeModel:;
- (void)didOccurEnterLandscapeActionWithAwemeModel:;
- (void)playerIsPaused;
- (void)__addObservers;
- (void)__createComponents;
- (BOOL)isPause;
- (void)updateContentSize:;
- (long long)currentAwemeType;
- (long long)feedShareRoomFeatureType;
- (id)userProfileManager;
- (id)storageArea;
- (void)pinQosMonitorType:userInfo:;
- (long long)getSynchronousTime;
- (BOOL)queryFeedSharePIPIsActive;
- (void)logFeedShareInfo:;
- (void)upDataLog:WithContent:WithExtra:;
- (BOOL)willChangeToLayoutType:;
- (void)updateCurrentPlayItemProgress:totalTime:;
- (void)willStartNextLoop;
- (void)videoBeginPlayWithModel:;
- (void)playerStartPlay;
- (BOOL)isEnableGuestSliding;
- (BOOL)isEnableHostSliding;
- (BOOL)isEnableShowSwipeUpGuide;
- (BOOL)queryRTVSafeSettingBoolValueForKey:defaultValue:;
- (id)customWatchTypeForFeed;
- (void)updateHost:dataController:currentID:targetFeedID:feedType:infoDict:completion:;
- (void)canEnterLiveRoom:callback:;
- (void)__log:;
- (id)rtvFeedContentControllers;
- (id)transitionToInterfaceOrientations:;
- (BOOL)currentInterfaceOrientationLayoutIsPortait;
- (void)hidePauseView:;
- (void)pauseWithIcon:;
- (void)playRemoteFeedContaienrViewController:didInvokeWithRoomBizInfo:;
- (BOOL)isSupportScrollForFeedType:;
- (void)updateIsPause:;
- (void)enablePureMode:;
- (void)feedContainer:didScrollToAweme:;
- (void)playRemoteFeedContaienrViewControllerFailToSliding:;
- (void)playRemoteFeedContaienrViewControllerDidSwipeToRight:;
- (unsigned long long)currentVideoLayoutType;
- (void)__configComponents;
- (void)notifyDidChangeActive:;
- (void)notifyChangeToNarrow:;
- (void)notifyDidChangeToNarrow:;
- (void)dismissContentController;
- (BOOL)isWillShowFeedGuide;
- (void)changeToNarrowView;
- (void)viewSizeDidChangeAfterSizeTransition;
- (void)onInteractionControlViewShareButtonClicked;
- (id)aAWEPadRTVAdapter;
- (BOOL)shouldCastFeedType:;
- (BOOL)shouldCastSearchType:;
- (void)insertAndScrollToAwemeModel:;
- (id)feedContentControllers;
- (id)currentTopViewController;
- (id)qosMonitor;
- (void)__bindStateRecorder;
- (id)roomInfoReadyDeferred;
- (id)participantsObserveController;
- (id)stateRecorderTokens;
- (void)setIsLocalFeedActive:;
- (void)setIsRemoteFeedActive:;
- (void)__updatePureMode;
- (void)__updateMultiSpeedEnable;
- (void)renderSession:;
- (id)remotePlayViewController;
- (void)setFirstApplyIdentifier:;
- (void)setIsFirstApply:;
- (id)__remotePlayViewControllerInfoDictionary:;
- (id)castVideoPanelController;
- (BOOL)isLocalFeedActive;
- (id)longVideoHistoryController;
- (id)playerProvider;
- (BOOL)isFirstApply;
- (id)firstApplyIdentifier;
- (unsigned char)__canTrackCoPlayInvite;
- (void)setRoomInfoReadyDeferred:;
- (void)__createCastVideoPanelService;
- (void)__createRemotePlayViewController;
- (void)__createPauseView;
- (void)__createVolumeSettingController;
- (BOOL)hadPreloadFeed;
- (id)commandRequester;
- (BOOL)isSelfSharing;
- (id)preloadReceivedCMDSet;
- (BOOL)__isUseNewReceiveMessageMethod;
- (BOOL)isRemoteFeedActive;
- (id)sendMessageActionController;
- (void)__destoryPIP;
- (id)__currentAwemeModel;
- (id)impressionTracker;
- (id)__applyHostWithNeedRetainCurrentAweme:;
- (void)resumePushAudioMixingStream;
- (id)__currentAwemeMediaTypeString;
- (BOOL)isEnableAutoPlayNext;
- (void)openFeedSharePanel:hasHotTip:;
- (void)pausePushAudioMixingStream:;
- (BOOL)__isSupportMultiSpeed;
- (long long)__rtvAwemeType:;
- (long long)__playRemoteFeedType:;
- (id)volumeSettingController;
- (BOOL)isPlayPause;
- (void)setIsPlayPause:;
- (unsigned long long)__feedShareFeedType:;
- (void)__backToFeedButtonTap;
- (void)autoPlayNextVideoIfNeeded;
- (id)lastAwemeModel;
- (void)setLastAwemeModel:;
- (void)__showCastTipsIfNeeded;
- (BOOL)isShowingSlidingTip;
- (void)setIsShowingSlidingTip:;
- (id)distributionGuidePresenter;
- (long long)__currentAwemeMediaType;
- (void)feedController:didChangeToShareModel:;
- (void)interactionControlViewController:actionTypeTriggered:;
- (void)quitFeedContentController;
- (void)rtvSession:participatorsDidChange:oldParticipators:;
- (void)voipSessionVoipInfoPrepareReady:;
- (void)voipSession:newParticipantJoined:;
- (void)stateMachine:didTransferFrom:to:context:;
- (void)updateContentSizeForPiPUpdate:;
- (void)interactionMessageListViewController:willSendMessage:;
- (void)participantsObserveController:didChangeMultiSpeedFeatureValueFrom:to:;
- (void)feedSession:didReceiveCommand:;
- (void)feedSession:shareWillFinishWithReason:;
- (id)feedSessionTryToShareFeed:;
- (void)insertHotFeedWithModel:;
- (void)showHalfIMPanelOfUserID:;
- (void)enableMiniContainer:;
- (void)__routeToConversationOfType:convID:anotherUserID:floatMode:needRoute:;
- (void)handleBusinessSessionAction:;
- (void)setRemotePlayViewController:;
- (void)setVolumeSettingController:;
- (void)setLongVideoHistoryController:;
- (id)currentContentSize;
- (float)volume;
- (void)setContentSize:;
- (id)pipController;
- (void)dealloc;
- (void)resume;
- (double)totalTime;
- (id)settingsManager;
- (id)contentSize;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (void)setPipController:;
- (id)observers;
- (id).cxx_construct;
- (id)injector;
- (void)loadView;
- (void).cxx_destruct;
- (double)videoDuration;
- (double)currentPlaybackTime;
- (id)stateMachine;
- (void)viewDidAppear:;
- (void)setDelegate:;
- (void)setIsLandscape:;
- (BOOL)isLandscape;
- (long long)playState;
- (void)appDidBecomeActive;
- (id)pauseView;
- (void)setPauseView:;
- (void)playLast;
- (void)playNext;
- (void)appWillResignActive;
- (void)seekToTime:completion:;
+ (Class)aAWEPadRTVAdapterClass;
@end
