@interface AWERadarGroupConfirmViewController : UIViewController
@property (nonatomic) NSString groupCommad;
@property (nonatomic) NSString groupId;
@property (nonatomic) AWENavigationBar navigationBar;
@property (nonatomic) UIView hintView;
@property (nonatomic) UILabel hintLabel;
@property (nonatomic) AWERadarGroupEnterCommandView commandView;
@property (nonatomic) UIViewController<AWERadarNearbyItemListViewControllerProtocol> userListController;
@property (nonatomic) AFDButton enterButton;
@property (nonatomic) BOOL isCommandInvalid;
@property (nonatomic) BOOL willOpenClickCreateGroupButton;
@property (nonatomic) BOOL hasExit;
@property (nonatomic) q radarUserListCount;
@property (nonatomic) NSTimer uploadLocationTimer;
@property (nonatomic) BOOL isExited;
@property (nonatomic) BOOL hasPeople;
@property (nonatomic) <AWEIMFaceToFaceConfigProtocol> materialInfo;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel subTitleLabel;
@property (nonatomic) UIImageView topBackgroundImageView;
@property (nonatomic) BOOL delayLocationRequest;
@property (nonatomic) NSString leavePageEventName;
@property (nonatomic) q enterType;
@property (nonatomic) NSDictionary routerParam;
- (void)p_setupUI;
- (void)awe_onReturnButtonClicked:;
- (id)routerParam;
- (void)setRouterParam:;
- (id)enterButton;
- (void)setEnterButton:;
- (void)p_stopTimer;
- (BOOL)hasExit;
- (void)setHasExit:;
- (id)materialInfo;
- (void)setMaterialInfo:;
- (void)setIsExited:;
- (BOOL)isExited;
- (void)setTopBackgroundImageView:;
- (id)topBackgroundImageView;
- (id)commandView;
- (void)setupCommandView;
- (BOOL)isSpringFestivalActive;
- (id)initWithGroupCommand:andGroupId:;
- (void)__trackAPIEventResCode:duration:apiName:;
- (void)setCommandView:;
- (void)setHasPeople:;
- (BOOL)delayLocationRequest;
- (void)p_removeGroupCommandVC;
- (void)p_updateUserList:withNoticeList:;
- (void)p_startTimer;
- (void)p_dismissEvent;
- (void)p_startHeartBeat:;
- (BOOL)willOpenClickCreateGroupButton;
- (void)p_removeSelfAndActivityCreateGroupVC;
- (void)p_removeSelfVC;
- (id)leavePageEventName;
- (void)trackLeaveViewMethod:;
- (void)p_exitAWERadarBuildGroup;
- (void)p_startHeartBeat;
- (id)userListController;
- (long long)radarUserListCount;
- (id)groupCommad;
- (void)setIsCommandInvalid:;
- (void)setRadarUserListCount:;
- (id)uploadLocationTimer;
- (void)p_setHintViewInvalid;
- (void)p_uploadLocation;
- (void)setUploadLocationTimer:;
- (BOOL)isCommandInvalid;
- (void)trackGroupEnterClick;
- (void)p_trackGroupCreateWithMonitor:response:error:extra:;
- (void)setLeavePageEventName:;
- (void)p_trackAddFaceToFaceGroupWithResponse:error:;
- (void)trackGroupCreateSucces;
- (void)trackCreateGroupWithRespModel:;
- (void)setWillOpenClickCreateGroupButton:;
- (void)trackEnterChat;
- (id)p_getRootVC;
- (void)setGroupCommad:;
- (void)setUserListController:;
- (void)setDelayLocationRequest:;
- (void)setGroupId:;
- (id)groupId;
- (id)navigationBar;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidDisappear:;
- (long long)preferredStatusBarStyle;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (id)titleLabel;
- (void)setNavigationBar:;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
- (id)hintLabel;
- (id)hintView;
- (void)setHintLabel:;
- (void)setHintView:;
- (void)enterGroup;
- (long long)enterType;
- (void)setEnterType:;
- (BOOL)hasPeople;
- (void)p_addObservers;
@end
