@interface AWERelatedRecomendPanelViewController : UIViewController
@property (nonatomic) UIView containerView;
@property (nonatomic) UIView effectView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIButton closeButton;
@property (nonatomic) UIView bottomCollectView;
@property (nonatomic) AWEListDataController dataController;
@property (nonatomic) UIPanGestureRecognizer panGes;
@property (nonatomic) UITapGestureRecognizer tapGes;
@property (nonatomic) {CGPoint=dd} lastLocation;
@property (nonatomic) double baseViewBottomOffset;
@property (nonatomic) MASConstraint baseViewBottom;
@property (nonatomic) AWERelatedRecomendPanelListView listView;
@property (nonatomic) NSString referString;
@property (nonatomic) <AWERelatedRecomendPanelViewDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)referString;
- (void)setReferString:;
- (void)setDataController:;
- (id)panGes;
- (void)setPanGes:;
- (id)tapGes;
- (void)setTapGes:;
- (void)selfPanned:;
- (void)selfTapped:;
- (void)setBaseViewBottomOffset:;
- (void)setBaseViewBottom:;
- (double)baseViewBottomOffset;
- (id)baseViewBottom;
- (void)refreshWithTitle:dataController:currentAwemeModel:;
- (void)panelListDidSelectAtIndex:aweme:;
- (id)bottomCollectView;
- (void)setBottomCollectView:;
- (id)lastLocation;
- (id)delegate;
- (id)effectView;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:;
- (id)listView;
- (id)containerView;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)setEffectView:;
- (void)setListView:;
- (void)setContainerView:;
- (void)setTitleLabel:;
- (void)setLastLocation:;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:shouldRequireFailureOfGestureRecognizer:;
- (id)titleLabel;
- (void)setDelegate:;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (void)setCloseButton:;
- (id)closeButton;
- (void)closeButtonTapped;
- (id)dataController;
@end
