@interface AWERepoKaraokeModel : NSObject
@property (nonatomic) NSDictionary trackParams;
@property (nonatomic) NSMutableDictionary mTrackParams;
@property (nonatomic) BOOL enterWithMusic;
@property (nonatomic) BOOL enableRecordSelectMusic;
@property (nonatomic) NSString enterKaraokeSelectMusicId;
@property (nonatomic) AWEKaraokeLyricsSong lyricsModel;
@property (nonatomic) NSDictionary editJsonInfo;
@property (nonatomic) NSDictionary musicJsonInfo;
@property (nonatomic) NSString midiLocalPath;
@property (nonatomic) AWEKaraokeEditModel editModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <ACCPublishRepository> repoDeprecated;
@property (nonatomic) BOOL isFromAuthorityGuide;
@property (nonatomic) q recordMode;
@property (nonatomic) ACCEditMVModel mvModel;
@property (nonatomic) <ACCMusicKaraokeAudioModelProtocol> originalSongTrack;
@property (nonatomic) <ACCMusicKaraokeAudioModelProtocol> accompanyTrack;
@property (nonatomic) <ACCMusicModelProtocolD> musicModel;
@property (nonatomic) NSNumber shootDuration;
@property (nonatomic) BOOL lightningStyleKaraoke;
@property (nonatomic) NSNumber lyricsStartTime;
@property (nonatomic) BOOL fromRecordExport;
- (id)trackParams;
- (void)setTrackParams:;
- (id)musicModel;
- (void)setShootDuration:;
- (void)setMusicModel:;
- (long long)recordMode;
- (void)setRecordMode:;
- (id)mvModel;
- (void)setMvModel:;
- (id)shootDuration;
- (id)repoDeprecated;
- (void)setRepoDeprecated:;
- (id)acc_publishRequestParams:;
- (id)initWithDraft:;
- (void)saveWithDraft:;
- (id)draftFolder;
- (void)draftWillBeSavedWithID:;
- (void)modelDidRetrievedFromDraftWithID:;
- (id)acc_referExtraParams;
- (id)editModel;
- (void)generateMVFromDraftVideoData:taskId:completion:;
- (double)originalSoundStartTime;
- (double)accompanyStartTime;
- (void)addTrackParamsFromDictionary:;
- (void)setTrackParam:forKey:;
- (BOOL)isFromAuthorityGuide;
- (void)setIsFromAuthorityGuide:;
- (BOOL)enterWithMusic;
- (void)setEnterWithMusic:;
- (BOOL)enableRecordSelectMusic;
- (void)setEnableRecordSelectMusic:;
- (id)enterKaraokeSelectMusicId;
- (void)setEnterKaraokeSelectMusicId:;
- (id)originalSongTrack;
- (void)setOriginalSongTrack:;
- (id)accompanyTrack;
- (void)setAccompanyTrack:;
- (BOOL)lightningStyleKaraoke;
- (void)setLightningStyleKaraoke:;
- (id)lyricsStartTime;
- (void)setLyricsStartTime:;
- (BOOL)fromRecordExport;
- (void)setFromRecordExport:;
- (void)setEditModel:;
- (void)setEditJsonInfo:;
- (void)setMusicJsonInfo:;
- (id)editJsonInfo;
- (id)musicJsonInfo;
- (id)lyricsModel;
- (void)setLyricsModel:;
- (id)midiLocalPath;
- (void)setMidiLocalPath:;
- (id)mTrackParams;
- (void)setMTrackParams:;
- (void)generateDefaultBGMVFromDraft:taskId:completion:;
- (id)init;
- (void).cxx_destruct;
- (id)copyWithZone:;
@end
