@interface AWERLVirtualView : NSObject
@property (nonatomic) UIView renderedView;
@property (nonatomic) NSString reuseIdentifier;
@property (nonatomic) NSMutableArray privateSubviews;
@property (nonatomic) BOOL rl_newAdded;
@property (nonatomic) BOOL rl_layoutCacheValid;
@property (nonatomic) AWERLTransition insertTransition;
@property (nonatomic) AWERLTransition deleteTransition;
@property (nonatomic) BOOL userInteractionEnabled;
@property (nonatomic) UIColor backgroundColor;
@property (nonatomic) double cornerRadius;
@property (nonatomic) BOOL clipsToBounds;
@property (nonatomic) @? singleTapBlock;
@property (nonatomic) BOOL hidden;
@property (nonatomic) double borderWidth;
@property (nonatomic) ^{CGColor=} borderColor;
@property (nonatomic) BOOL masksToBounds;
@property (nonatomic) q contentMode;
@property (nonatomic) double alpha;
@property (nonatomic) ^{CGColor=} shadowColor;
@property (nonatomic) float shadowOpacity;
@property (nonatomic) {CGSize=dd} shadowOffset;
@property (nonatomic) double shadowRadius;
@property (nonatomic) BOOL isAccessibilityElement;
@property (nonatomic) NSString accessibilityLabel;
@property (nonatomic) Q accessibilityTraits;
@property (nonatomic) {CGSize=dd} size;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} frame;
@property (nonatomic) {CGSize=dd} layoutSize;
@property (nonatomic) {CGPoint=dd} layoutPosition;
@property (nonatomic) q layoutStyle;
@property (nonatomic) {UIEdgeInsets=dddd} absoluteLayoutStyle;
@property (nonatomic) {CGSize=dd} rl_cachedConstraintSize;
@property (nonatomic) {CGSize=dd} rl_cachedMeasureSize;
@property (nonatomic) BOOL rl_hitLayoutCacheValid;
@property (nonatomic) NSString debugName;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)debugBuildDescriptions:;
- (void)updateFrameForRenderedView:;
- (id)layoutStyle:;
- (id)absoluteLayoutStyle:;
- (void)setAbsoluteLayoutStyle:;
- (void)setSingleTapBlock:;
- (id)userInteractionEnabled:;
- (void)changeSubviews:;
- (id)layoutThatFits:;
- (id)createViewToRender;
- (void)updateAttributesForRenderedView:;
- (id)borderColor:;
- (id)borderWidth:;
- (id)masksToBounds:;
- (id)cornerRadius:;
- (id)reuseIdentifier:;
- (BOOL)canRenderView;
- (void)setLayoutPosition:;
- (id)layoutPosition;
- (id)singleTapBlock;
- (id)mountWithContext:;
- (void)debugBuildLayoutDescriptions:;
- (BOOL)rl_newAdded;
- (BOOL)rl_layoutCacheValid;
- (BOOL)rl_hitLayoutCacheValid;
- (id)rl_cachedConstraintSize;
- (void)debugHierarchyVirtualViewDescriptions;
- (void)debugHierarchyLayoutDescription;
- (void)setRl_newAdded:;
- (void)setRl_layoutCacheValid:;
- (void)unmount;
- (id)fetchViewToRender;
- (void)onAnimationCompletion;
- (void)setRl_hitLayoutCacheValid:;
- (id)rl_cachedMeasureSize;
- (void)setRl_cachedConstraintSize:;
- (id)absoluteLayoutStyle;
- (void)setRl_cachedMeasureSize:;
- (void)setInsertTransition:;
- (void)setDeleteTransition:;
- (id)clipsToBounds:;
- (id)singleTapBlock:;
- (id)contentMode:;
- (id)alpha:;
- (id)shadowColor:;
- (id)shadowOpacity:;
- (id)shadowOffset:;
- (id)shadowRadius:;
- (id)transition:;
- (id)privateSubviews;
- (void)__updateMountedView:context:;
- (id)insertTransition;
- (id)deleteTransition;
- (void)setPrivateSubviews:;
- (id)layoutSize;
- (id)accessibilityLabel;
- (void)setLayoutStyle:;
- (void)setBorderColor:;
- (void)setBorderWidth:;
- (void)setAlpha:;
- (void)setClipsToBounds:;
- (BOOL)isUserInteractionEnabled;
- (id)init;
- (double)borderWidth;
- (id)borderColor;
- (id)frame;
- (void)setShadowOpacity:;
- (double)shadowRadius;
- (void)addTransition:;
- (id)shadowColor;
- (void)addSubview:;
- (void)setCornerRadius:;
- (void)setDebugName:;
- (void)setFrame:;
- (void)setShadowColor:;
- (id)shadowOffset;
- (void)setAccessibilityLabel:;
- (double)alpha;
- (void)setShadowOffset:;
- (void)setShadowRadius:;
- (long long)layoutStyle;
- (id)initWithSize:;
- (id)backgroundColor;
- (BOOL)clipsToBounds;
- (void)setMasksToBounds:;
- (void)setBackgroundColor:;
- (void)setAccessibilityTraits:;
- (void)setHidden:;
- (id)size;
- (void).cxx_destruct;
- (id)backgroundColor:;
- (void)setSize:;
- (double)cornerRadius;
- (id)debugDescription;
- (id)debugName;
- (void)setUserInteractionEnabled:;
- (BOOL)masksToBounds;
- (float)shadowOpacity;
- (BOOL)hidden;
- (unsigned long long)accessibilityTraits;
- (id)valueForUndefinedKey:;
- (id)reuseIdentifier;
- (long long)contentMode;
- (BOOL)isAccessibilityElement;
- (void)setContentMode:;
- (void)setIsAccessibilityElement:;
- (void)setLayoutSize:;
- (void)setReuseIdentifier:;
- (id)subviews;
- (id)accessibilityLabel:;
- (id)accessibilityTraits:;
- (id)isAccessibilityElement:;
- (id)size:;
- (id)hidden:;
- (id)renderedView;
- (void)setRenderedView:;
+ (void)registerAutoSyncAttributeKeyPathPairs:;
+ (id)autoSyncAttributeKeyPathPairs;
+ (void)unregisterAutoSyncAttributeKeyPath:;
@end
