@interface AWERTVInviteFriendsSegmentController : NSObject
@property (nonatomic) <RxInjector> injector;
@property (nonatomic) RxDeferred searchCompleteDefer;
@property (nonatomic) RxPromise fetchAllFriendsPromise;
@property (nonatomic) RxPromise fetchAllGroupsPromise;
@property (nonatomic) RxScheduler writeScheduler;
@property (nonatomic) <IESIMSearchEngineProtocol> searchEngine;
@property (nonatomic) <RTVUserProfileManagerInterface> profileManager;
@property (nonatomic) <RTVXRStateRecorder> xrStateRecorder;
@property (nonatomic) NSDictionary userActiveInfoMap;
@property (nonatomic) NSMutableDictionary currentUserCellModelMapper;
@property (nonatomic) RTVInviteFriendsDataProviderContext context;
@property (nonatomic) <RTVInviteParticipantDataFetcher> dataFetcher;
@property (nonatomic) NSArray selectedItemIDs;
@property (nonatomic) NSMutableArray selectedResults;
@property (nonatomic) NSMutableOrderedSet searchSelectedUserIDs;
@property (nonatomic) NSMutableArray defaultSelectUserIDs;
@property (nonatomic) BOOL hasChangeSelect;
@property (nonatomic) RxPromise searchEngineReadyPromise;
@property (nonatomic) <RTVVoipConfigureManagerInterface> voipConfiguration;
@property (nonatomic) <RTVSettingsManager> rtvSettingsManager;
@property (nonatomic) <AWERTVInviteFriendsSegmentControllerDelegate> delegate;
@property (nonatomic) <RTVCollectionViewControllerSegmentControllerDelegate> segmentDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)rxAwakeFromPropertyInjection;
- (void)renderModel:context:;
- (id)sectionModels;
- (void)registReusableViewForCollectionView:;
- (id)itemSizeForCollectionView:withCellModel:;
- (id)rtvSettingsManager;
- (id)defaultSelectUserIDs;
- (void)setDefaultSelectUserIDs:;
- (BOOL)__interfaceOrientationLayoutIsPortrait;
- (id)xrStateRecorder;
- (id)__fetchAllFriends;
- (id)__fetchAllGroups;
- (void)__configSearchEngine;
- (id)fetchAllFriendsPromise;
- (id)fetchAllGroupsPromise;
- (void)setSearchEngineReadyPromise:;
- (id)writeScheduler;
- (id)searchCompleteDefer;
- (id)__cellModelsWithItems:;
- (id)__sectionIdentifierWithCategory:;
- (id)selectedResults;
- (id)searchSelectedUserIDs;
- (id)currentUserCellModelMapper;
- (id)segmentDelegate;
- (id)__fetchAllFriendsSectionModels;
- (id)__inviteFriendsCellReuseIdentifier;
- (id)__inviteGroupCellReuseIdentifier;
- (id)__inviteFriendHeaderReuseIdentifier;
- (BOOL)__canSelectCellModel:;
- (void)__changeFriendSelectState:;
- (void)setSearchCompleteDefer:;
- (id)searchEngineReadyPromise;
- (id)__sectionModelsWithItems:category:;
- (void)setUserActiveInfoMap:;
- (unsigned long long)__recentMaxUserCount;
- (id)userActiveInfoMap;
- (id)__sortUsersByNameIndex:;
- (id)__createCellModelWithItem:;
- (id)selectedItemIDs;
- (unsigned long long)__currentSelectCount;
- (BOOL)hasChangeSelect;
- (BOOL)__canSelectItem:;
- (void)setHasChangeSelect:;
- (id)voipConfiguration;
- (id)searchResultWithKey:;
- (void)setSegmentDelegate:;
- (id)supplementarySizeForCollectionView:elementsKind:sectionIdentifier:;
- (void)collectionView:didSelectCellModel:;
- (id)currentSelectedResults;
- (id)defaultSelectedIDs;
- (id)__preferSelectedSort:;
- (void)setCurrentUserCellModelMapper:;
- (void)setDataFetcher:;
- (void)resetSelection;
- (id)delegate;
- (BOOL)isSearching;
- (id)injector;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)context;
- (id)searchEngine;
- (id)profileManager;
- (id)dataFetcher;
@end
