@interface AWERecordBeautyVCContext : NSObject
@property (nonatomic) NSMapTable contentVCs;
@property (nonatomic) NSHashTable subscribers;
@property (nonatomic) AWERecordBeautyContentViewController currentContentVC;
@property (nonatomic) AWERecordBeautyViewController rootVC;
@property (nonatomic) NSString styleNodeId;
@property (nonatomic) NSDictionary styleExtraCellModelsNodeIdInfo;
@property (nonatomic) BOOL isMultipersonStatus;
@property (nonatomic) NSMutableDictionary styleSliderValueInfo;
@property (nonatomic) <AWERecordBeautyVCContextDelegation> delegate;
@property (nonatomic) AWERecordBeautyDataManager dataManager;
@property (nonatomic) BOOL enableBlurViewOpt;
@property (nonatomic) BOOL isAppendStyleNodeBySplitelineNodeStatus;
@property (nonatomic) BOOL isSubPanelViewStatus;
@property (nonatomic) NSString currentSelectStyleItemNodeId;
@property (nonatomic) NSString currentFristPanelSelectStyleItemNodeId;
@property (nonatomic) NSArray exposeChildItemNodeIds;
@property (nonatomic) NSString selectOffNodeId;
@property (nonatomic) @? beautyViewControllerUpdateBeautyAvailabilitiesAction;
@property (nonatomic) @? beautyViewControllerSaveCacheAction;
@property (nonatomic) @? beautyContentDidTrackItemAction;
@property (nonatomic) @? beautyClickStyleItemAction;
@property (nonatomic) @? beautyClickStyleOffNodeItemAction;
@property (nonatomic) @? trackerOffNodeItemAction;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)showToast:;
- (void)setRootVC:;
- (id)rootVC;
- (id)initWithDataManager:;
- (id)currentContentVC;
- (void)setCurrentContentVC:;
- (void)turnOnBeauty;
- (void)turnOffBeauty;
- (id)styleSliderValueInfo;
- (void)setStyleNodeId:;
- (id)styleExtraCellModelsNodeIdInfoWithItemModels:;
- (void)setStyleExtraCellModelsNodeIdInfo:;
- (void)setCurrentSelectStyleItemNodeId:;
- (void)updateStyleMoreItemApplyStatus:;
- (void)updateDetectFaceStatusWithMultipersonStatus:;
- (id)styleNodeId;
- (void)updateCurrentVC;
- (id)styleExtraCellModelsNodeIdInfo;
- (BOOL)hasOriginStyleStatus;
- (BOOL)didSelectStyleEffectItemSelfStatusWithNodeId:;
- (void)resetApplyEffectValueAndStatusWithExcludeNodeId:isNeedResetStyleNodeToDefaultRealValueStatus:;
- (long long)effectCurrentValueWithItemModel:;
- (id)applyAllNodeIdDiffStyleNode;
- (id)styleExtraNodeIds;
- (void)resetApplyStyleEffect;
- (id)selectOffNodeId;
- (void)resetStyleNodePropertyStatus;
- (long long)effectDefaultValueWithItemModel:;
- (void)setIsSubPanelViewStatus:;
- (void)handleSlider:finishSlidingWithValue:realValue:;
- (void)showAlertWithTitle:content:actionButtonTitle:cancelButtonTitle:actionBlock:cancelBlock:;
- (void)setStyleSliderValueInfo:;
- (BOOL)isEnableRecordBeautyAddStyleEffectSwitchStatus;
- (void)setIsMultipersonStatus:;
- (BOOL)isMultipersonStatus;
- (void)updateContentVC:;
- (void)setIsAppendStyleNodeBySplitelineNodeStatus:;
- (BOOL)isSubPanelViewStatus;
- (id)exposeChildItemNodeIds;
- (BOOL)isTurnOffBeauty;
- (BOOL)isAppendStyleNodeBySplitelineNodeStatus;
- (void)beautyEffectContentDidUnDownloadAction;
- (void)collectionView:selectLeafItem:;
- (void)collectionView:selectCollection:;
- (void)didUpdateDefaultStateStatus:;
- (void)didUpdateAllStatus;
- (void)bindCurrentContentVC:;
- (void)addContentVC:withNodeId:;
- (void)removeContentVCWithNodeId:;
- (BOOL)enableBlurViewOpt;
- (void)setEnableBlurViewOpt:;
- (void)p_updateItemVC:;
- (id)cellModelsWithNodeId:;
- (void)p_changeResetButtonStateInVC:isAllInDefaultState:;
- (void)p_updateSliderIfUpdatingCurrentContentVCWithConentVCNodeId:;
- (id)removeStyleNodeIfNeededWithStatusModes:;
- (id)p_generateCellModelWithItemStatusModel:;
- (id)offNodeWithItemStatusModel:cellModel:;
- (id)styleMoreNodeWithItemStatusModel:cellModel:;
- (id)styleChildExtraNodesWithItemStatusModel:cellModel:;
- (void)cellModelsAppendCellModel:itemStatusModel:cellModels:;
- (id)styleOffNodeDefaultSelectIfNeededWithStatusModes:;
- (long long)cellModelsAppendStyleCellModelWithStatusModes:styleNodeIndex:cellModels:;
- (void)cellModelsAppendSplitelineWithIndex:cellModels:;
- (id)cellModelsFindStyleMoreNodeWithStatusModes:;
- (id)styleExtraNodesWithStyleMoreNode:;
- (id)firstAndSecondChildExtraNodeIndexsWithChildExtraNodes:;
- (id)firstAndSecondChildNodeStatusModelWithChildExtraNodes:firstAndSecondChildExtraNodeIndexs:;
- (BOOL)cellModelsAppendFirstAndSecondChildNodeCellModelWithStatusModels:cellModels:;
- (id)currentSelectStyleItemNodeId;
- (void)setExposeChildItemNodeIds:;
- (id)splitlineCellModel;
- (void)setSelectOffNodeId:;
- (id)contentVCs;
- (void)assignRootVC:;
- (void)handleTapResetButton:resetTitle:;
- (void)setContentVCs:;
- (void)beautyEffectContentDidSelectStyleEffectItemActionWithNodeId:styleExtraCellModelsNodeIdInfo:completeHandler:;
- (void)beautyEffectContentDidSelectStyleMoreItemActionWithNodeId:;
- (void)setBeautyViewControllerUpdateBeautyAvailabilitiesAction:;
- (void)setBeautyViewControllerSaveCacheAction:;
- (void)setBeautyContentDidTrackItemAction:;
- (void)setBeautyClickStyleItemAction:;
- (void)setBeautyClickStyleOffNodeItemAction:;
- (void)setTrackerOffNodeItemAction:;
- (void)setupStyleNodeIfNeeded;
- (BOOL)hasContainsStyleNodeStatus;
- (void)recoverUserLastDefineEffect;
- (void)cacheUserLastDefineEffect;
- (void)sliderWithStyleEffectValueDidChange:realValue:itemModel:;
- (void)setCurrentFristPanelSelectStyleItemNodeId:;
- (void)beautyEffectContentDidTrackItemActionWithNodeId:;
- (void)beautyItemCellModelStatusGrayedOutAndDisabledToastAction;
- (void)beautyEffectContentDidResetStyleEffectItemActionWithNodeId:;
- (void)beautyNavigationControllerDidTapBackAction;
- (void)beautyEffectContentDidTrackClickStyleItemActionWithNodeId:;
- (void)beautyEffectContentDidTrackClickStyleOffNodeItemAction;
- (void)handleDidStartSliding:;
- (void)handleSlider:valueDidChange:realValue:;
- (id)currentFristPanelSelectStyleItemNodeId;
- (void)beautyEffectContentDidClickTurnOffBeautyNodeItemAction;
- (id)beautyViewControllerSaveCacheAction;
- (id)trackerOffNodeItemAction;
- (id)beautyViewControllerUpdateBeautyAvailabilitiesAction;
- (void)beautyEffectContentDidSelectLeafNodeItemAction;
- (void)removeFirstPanelSelectStatus;
- (id)sortSelectItems:;
- (id)beautyContentDidTrackItemAction;
- (id)beautyClickStyleItemAction;
- (id)beautyClickStyleOffNodeItemAction;
- (void)beautyEffectContentDidResetEffectItemUIUpdateAction;
- (id)dataManager;
- (id)delegate;
- (id)subscribers;
- (void)setDataManager:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)addSubscriber:;
- (void)removeSubscriber:;
- (void)setSubscribers:;
@end
