@interface AWESearchScanPanelBackgroundView : UIView
@property (nonatomic) UIImageView imageView;
@property (nonatomic) BackgroundCoverView alternateBG;
@property (nonatomic) NSArray rawDetections;
@property (nonatomic) AWESearchScanImageSelectionHandleView activeHandleView;
@property (nonatomic) NSMutableArray selectionHandleViewArray;
@property (nonatomic) NSMutableArray selectionDotViewArray;
@property (nonatomic) NSArray selectionRectArray;
@property (nonatomic) Q selectedIndex;
@property (nonatomic) AWESearchScanImageSelectionHandleView customHandleView;
@property (nonatomic) AWESearchScanImageDotView customDotView;
@property (nonatomic) AWESearchScanDataContext dataContext;
@property (nonatomic) BOOL isScanQuestionMode;
@property (nonatomic) BOOL endCurrentHandlerViewChanged;
@property (nonatomic) AWESearchScanCircleSearchView circleSearchView;
@property (nonatomic) UITapGestureRecognizer clickBorderWithoutCircleGesture;
@property (nonatomic) NSArray hiddenDetections;
@property (nonatomic) <AWESearchScanPanelBackgroundViewDelegate> delegate;
@property (nonatomic) NSArray tabViewModels;
@property (nonatomic) BOOL hasDragPanel;
@property (nonatomic) UIScrollView scrollView;
@property (nonatomic) Q scrollType;
@property (nonatomic) double offsetY;
@property (nonatomic) double panelBaseOffset;
@property (nonatomic) double centerAreaBaseOffset;
@property (nonatomic) Q scrollViewOffsetResetType;
@property (nonatomic) BOOL currentSelectedTabIsScanQuestion;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)dataContext;
- (void)configUI;
- (void)setDataContext:;
- (id)alternateBG;
- (id)rawDetections;
- (void)updateDetectionArray:withSelectionIndex:;
- (void)updateSubviewFrame;
- (id)handleViewAtIndex:;
- (id)selectionHandleViewArray;
- (id)customHandleView;
- (id)selectionDotViewArray;
- (id)customDotView;
- (void)updateSelectionIndex:;
- (id)activeHandleView;
- (void)setCustomHandleView:;
- (void)showDotView:isShow:;
- (id)selectionRectArray;
- (id)createDotView;
- (void)setCustomDotView:;
- (void)updateMaskViewWithHanleViewFrame:;
- (void)setRawDetections:;
- (void)setSelectionRectArray:;
- (id)dotViewAtIndex:;
- (void)closeSelectionIndex:expandIndex:animated:completion:;
- (id)scrollGestureRecognizer;
- (void)handleViewSelectionChanged:;
- (void)handleViewSelectionChangeEnded:;
- (id)tabViewModels;
- (id)createLayerWithPath:;
- (void)showDetectionExpandAnimation:atIndex:completion:;
- (void)setAlternateBG:;
- (void)setSelectionDotViewArray:;
- (void)setScrollType:;
- (void)didSwitchTab;
- (BOOL)isScanQuestionMode;
- (void)setSelectionHandleViewArray:;
- (void)tapGestureDidHandle:;
- (void)touchDidEnd:;
- (void)setIsScanQuestionMode:;
- (void)setCurrentSelectedTabIsScanQuestion:;
- (void)handleViewTouchPoint:event:currentHandleView:;
- (BOOL)currentSelectedTabIsScanQuestion;
- (void)setScrollViewOffsetResetType:;
- (id)circleSearchView;
- (void)addClickBorderGesture;
- (double)panelBaseOffset;
- (double)centerAreaBaseOffset;
- (unsigned long long)scrollViewOffsetResetType;
- (double)getScrollViewContentOffsetWithIndex:;
- (void)updateDetectionArray:withSelectionIndex:reloadLayout:;
- (id)fetachDetectionFrame;
- (id)convertSelectionRectToDetctionDic:;
- (id)convertDetctionDicToDetctionRect:;
- (void)questionModelLevelAdjust;
- (void)shouldResetCurrentHandlerViewChangedFlag;
- (id)createClickableHandleView;
- (void)questionModelPanChangedAlphaAdjust;
- (void)updateQuestionDetections;
- (void)setHiddenDetections:;
- (id)convertSelectionRectWithDetectionDic:;
- (void)hiddenHandleViewAndDotView;
- (void)updateImageViewPositionWithIndex:completion:;
- (void)updateImageViewPositionWithIndex:closeIndex:completion:;
- (void)removeClickBorderGesture;
- (BOOL)endCurrentHandlerViewChanged;
- (void)setEndCurrentHandlerViewChanged:;
- (void)handleClickBorderWithoutCircle:;
- (id)adjustTapPoint:;
- (void)updateClickBorderUIWithHandleView:andBoxRect:;
- (id)clickBorderWithoutCircleGesture;
- (id)hiddenDetections;
- (id)initWithMode:dataContext:currentTabIsScanQuestion:;
- (void)changeSelectionIndex:selectBoxType:;
- (void)updateHiddenDetectionArray:;
- (BOOL)hasDragPanel;
- (void)setHasDragPanel:;
- (void)setPanelBaseOffset:;
- (void)setCenterAreaBaseOffset:;
- (void)setCircleSearchView:;
- (void)setClickBorderWithoutCircleGesture:;
- (void)setScrollView:;
- (void)setSelectedIndex:;
- (id)delegate;
- (id)scrollView;
- (unsigned long long)selectedIndex;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)layoutSubviews;
- (void)setImageView:;
- (id)imageView;
- (unsigned long long)scrollType;
- (id)detections;
- (void)updateImage:;
- (double)offsetY;
- (void)setOffsetY:;
@end
