@interface AWESearchPOIFilterManager : AWESearchFilterBaseManager
@property (nonatomic) NSMutableSet quickFilterItemDataIDs;
@property (nonatomic) NSMutableSet userManualSelectComponentsDataIDs;
@property (nonatomic) NSString strCalendarModelDataID;
@property (nonatomic) NSString addressLocationID;
@property (nonatomic) NSString userAddressID;
@property (nonatomic) NSString addressBizName;
@property (nonatomic) NSString startHintText;
@property (nonatomic) BOOL isMorningRoom;
@property (nonatomic) NSString endHintText;
@property (nonatomic) NSDate startDate;
@property (nonatomic) NSDate endDate;
@property (nonatomic) NSString startDateString;
@property (nonatomic) NSString endDateString;
@property (nonatomic) NSString startDateDispalyText;
@property (nonatomic) NSString endDateDispalyText;
@property (nonatomic) BOOL shouldDisplayDate;
@property (nonatomic) NSString calendarPostDataString;
@property (nonatomic) double startHintWidth;
@property (nonatomic) double endHintWidth;
@property (nonatomic) double startDateWidth;
@property (nonatomic) double endDateWidth;
@property (nonatomic) q searchScene;
@property (nonatomic) <AWESearchPOIFilterManagerDelegate> delegate;
- (long long)searchScene;
- (void)setSearchScene:;
- (void)resetWithQueryModel:;
- (BOOL)selectStateForModel:;
- (void)didUnselectComponentWithDataID:;
- (id)sortParamsWithIsFromSelectBoard:needParent:;
- (id)createFilterSelectTreeNodeWithDataID:;
- (id)userAddressID;
- (void)setUserAddressID:;
- (void)setAddressLocationID:;
- (BOOL)calendarDateChangedWithStartString:andEndString:;
- (void)setCalendarPostDataString:;
- (BOOL)updateCalendarWithStartString:andEndString:isMorningRoom:;
- (id)generateSortParamsWithModel:;
- (id)generateSortParamsWithModelDataID:;
- (void)clearQuickFilterStateWithQueryModel:controllerInfo:;
- (void)getRecursiveSelectChildModelsWithModel:completion:;
- (void)userDidManualSelectTrailComponent:;
- (void)userDidManualUnselectTrailComponent:;
- (id)getAddressModel;
- (id)getCalendarModel;
- (id)addressLocationID;
- (id)addressBizName;
- (id)endDateString;
- (BOOL)shouldDisplayDate;
- (double)startHintWidth;
- (id)startHintText;
- (void)setStartHintWidth:;
- (double)endHintWidth;
- (id)endHintText;
- (void)setEndHintWidth:;
- (double)startDateWidth;
- (id)startDateDispalyText;
- (void)setStartDateWidth:;
- (double)endDateWidth;
- (id)endDateDispalyText;
- (void)setEndDateWidth:;
- (void)setShouldDisplayDate:;
- (id)userManualSelectComponentsDataIDs;
- (void)setUserManualSelectComponentsDataIDs:;
- (void)configDefaultAddressInfo;
- (void)configDefaultCalendarInfo;
- (void)setAddressBizName:;
- (id)standardFormatter;
- (id)displayFormatter;
- (void)setStartDateDispalyText:;
- (void)setEndDateString:;
- (void)setEndDateDispalyText:;
- (void)setStrCalendarModelDataID:;
- (id)strCalendarModelDataID;
- (void)setStartHintText:;
- (void)setEndHintText:;
- (void)didReplaceFilterComponentModelFromQueryModelWithValue:oldValue:;
- (void)recursiveCollectSelectedChildModelsWithModel:selectedModelsCollection:selectedModelDataIdsCollection:;
- (id)calendarPostDataString;
- (void)reloadWithQueryModel:;
- (void)configAllBusinessDefaultInfo;
- (id)quickFilterItemDataIDs;
- (void)didAddFilterComponentModelFromQueryModelWithValue:;
- (BOOL)isMorningRoom;
- (void)setIsMorningRoom:;
- (void)setQuickFilterItemDataIDs:;
- (void)setEndDate:;
- (id)startDate;
- (id)delegate;
- (void)setStartDate:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)endDate;
- (id)startDateString;
- (void)setStartDateString:;
+ (id)filterManagerWithManager:;
+ (unsigned long long)maxTreeWidthForModel:;
+ (void)updateCurrentPOIFilterManager:forKey:;
+ (id)getCurrentPOIFilterManagerForKey:;
+ (void)buildFilterManagerMapIfNeeded;
+ (id)getStandardFormatter;
+ (id)getDisplayFormatter;
@end
