@interface AWESearchCachalotDynamicResourceManager : NSObject
@property (nonatomic) q maxDownloadTimeout;
@property (nonatomic) BOOL enableCardFilter;
@property (nonatomic) NSArray cardFilterWhitelist;
@property (nonatomic) NSString searchType;
@property (nonatomic) AWESearchDynamicResourceChannelManager channelManager;
@property (nonatomic) NSArray cardTemplateDowngradeChannelList;
@property (nonatomic) AWESearchCachalotDataController delegate;
@property (nonatomic) BOOL enable;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setMaxDownloadTimeout:;
- (void)checkSearchChannelStatusWithForce:;
- (void)checkResponseDataList:forceSyncExec:completion:;
- (void)setEnableCardFilter:;
- (void)setCardFilterWhitelist:;
- (void)setCardTemplateDowngradeChannelList:;
- (id)buildSurlRecordFromCardList:;
- (void)willInvokeCompletionBlock:;
- (long long)maxDownloadTimeout;
- (void)trackResultForResourceNode:status:;
- (BOOL)enableCardFilter;
- (void)removeNodesInSurlRecord:;
- (id)cardFilterWhitelist;
- (id)cardTemplateDowngradeChannelList;
- (BOOL)enable;
- (void)setChannelManager:;
- (id)searchType;
- (id)delegate;
- (void)setSearchType:;
- (id)channelManager;
- (void).cxx_destruct;
- (id)initWithScene:;
- (void)setDelegate:;
- (void)setEnable:;
+ (id)findSceneConf:;
+ (BOOL)enableTemplateDowngrade;
+ (id)cardTemplateDowngradeConf;
+ (BOOL)enableSurlSupportInSearchScene:;
+ (id)cardTemplateDowngradeSceneMap;
+ (id)templateExtraInfoInSearchType:;
+ (BOOL)willUseSurl:inSearchScene:channel:;
+ (id)templateExtraInfoInSearchVCName:;
+ (id)conf;
@end
