@interface AWESearchMerchandiseGoodsInfoSingleColView : AWESearchMerchandiseGoodsInfoView
@property (nonatomic) AWESearchGoodsRecommendView recommendView;
@property (nonatomic) AWESearchGoodsSellInfoView sellInfoView;
@property (nonatomic) UIImageView adSpotImageView;
@property (nonatomic) UIImageView addCartImageView;
@property (nonatomic) AWEEcomSearchGoodsDiscountPriceView discountPriceView;
@property (nonatomic) AWEEcomSearchGoodsDiscountInfoLineView discountInfoLineView;
@property (nonatomic) AWEEcomSearchPriceAreaView priceAreaView;
@property (nonatomic) AWEEcomSearchPriceUpperAreaView priceUpperAreaView;
@property (nonatomic) AWEEcomSearchNewUserStrengthPriceView newerStrenghPriceView;
@property (nonatomic) UILabel newerStrenghSaleLabel;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) BOOL isFromPhotoSearch;
@property (nonatomic) <AWESearchWordProtocol> delegate;
- (void)configWithModel:;
- (void)jumpShop;
- (unsigned long long)titleLabelLines;
- (void)iconRecommendAreaShopClick;
- (void)jumpLeaderboard;
- (void)adCouponListViewTapped:;
- (void)jumpComparePrice;
- (void)jumpSearchWord:;
- (BOOL)isFromPhotoSearch;
- (void)configGradientLayerWithModel:;
- (id)adSpotImageView;
- (double)getAdCouponListViewMaxWidth;
- (void)iconRecommendAreaShowTrack;
- (void)setIsFromPhotoSearch:;
- (id)recommendView;
- (void)setRecommendView:;
- (id)sellInfoView;
- (void)setSellInfoView:;
- (void)setAdSpotImageView:;
- (id)addCartImageView;
- (void)setAddCartImageView:;
- (id)discountPriceView;
- (void)setDiscountPriceView:;
- (id)discountInfoLineView;
- (void)setDiscountInfoLineView:;
- (id)priceAreaView;
- (void)setPriceAreaView:;
- (id)priceUpperAreaView;
- (void)setPriceUpperAreaView:;
- (id)newerStrenghPriceView;
- (void)setNewerStrenghPriceView:;
- (id)newerStrenghSaleLabel;
- (void)setNewerStrenghSaleLabel:;
- (id)delegate;
- (id)initWithFrame:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (void)layoutSubviews;
- (id)gradientLayer;
- (void)setGradientLayer:;
+ (double)goodsInfoHeightForModel:containerWidth:;
+ (double)heightForModel:containerWidth:minHeight:;
@end
