@interface AWESocialPromotionPushView : UIView
@property (nonatomic) UIView contentBaseView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel contentLabel;
@property (nonatomic) UIImageView avatarImageView;
@property (nonatomic) UIImageView extAvatarBackground;
@property (nonatomic) UIImageView extAvatarImageView;
@property (nonatomic) UIButton replyButton;
@property (nonatomic) UILabel extTagLabel;
@property (nonatomic) AWESocialPromotionPushViewModel noticePushModel;
@property (nonatomic) <AWEInnerNotificationContentOperator> notificationOperator;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)disablePullIndicatorView;
- (void)renderModel:context:;
- (void)handleTapAction;
- (id)notificationOperator;
- (void)viewDidDisappearWithReason:;
- (BOOL)tapGestureIsEnable:;
- (void)setNotificationOperator:;
- (void)setExtTagLabel:;
- (id)extTagLabel;
- (void)setNoticePushModel:;
- (id)noticePushModel;
- (id)contentBaseView;
- (id)extAvatarImageView;
- (void)setContentBaseView:;
- (void)setExtAvatarImageView:;
- (void)__addSubviews;
- (id)extAvatarBackground;
- (void)updateConfigurablePushView:;
- (void)p_trackAction:extra:;
- (void)configurableLayoutSubViews;
- (void)setExtAvatarBackground:;
- (id)init;
- (id)intrinsicContentSize;
- (id)view;
- (id)initWithFrame:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)layoutSubviews;
- (id)avatarImageView;
- (id)contentLabel;
- (void)setAvatarImageView:;
- (void)setContentLabel:;
- (void)setReplyButton:;
- (id)replyButton;
@end
