@interface AWEShowTheaterPageContext : NSObject
@property (nonatomic) NSString firstAwemeID;
@property (nonatomic) NSString firstAlbumID;
@property (nonatomic) NSString awemeIDList;
@property (nonatomic) NSString albumIDList;
@property (nonatomic) NSString episodeIDList;
@property (nonatomic) NSDictionary logExtraDic;
@property (nonatomic) NSString previousPage;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) NSNumber currentTime;
@property (nonatomic) NSNumber offset;
@property (nonatomic) NSNumber enterScene;
@property (nonatomic) NSDictionary requestParamsDic;
@property (nonatomic) BOOL forbidLoadMore;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)logExtraDic;
- (void)setLogExtraDic:;
- (id)enterScene;
- (void)setEnterScene:;
- (id)firstAwemeID;
- (void)setFirstAwemeID:;
- (id)awemeIDList;
- (void)setAwemeIDList:;
- (id)albumIDList;
- (void)setAlbumIDList:;
- (id)episodeIDList;
- (void)setEpisodeIDList:;
- (id)requestParamsDic;
- (void)setRequestParamsDic:;
- (BOOL)forbidLoadMore;
- (void)setForbidLoadMore:;
- (id)firstAlbumID;
- (void)setFirstAlbumID:;
- (void)setCurrentTime:;
- (id)currentTime;
- (void)setOffset:;
- (id)offset;
- (void).cxx_destruct;
- (id)previousPage;
- (void)setPreviousPage:;
@end
