@interface AWEShareTextToFriendsInputView : UIView
@property (nonatomic) UITextView shareTextView;
@property (nonatomic) UIImageView videoImageView;
@property (nonatomic) UIButton leftButton;
@property (nonatomic) UIButton rightButton;
@property (nonatomic) NSArray buttonTypes;
@property (nonatomic) Q type;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSDictionary config;
@property (nonatomic) BOOL enableEmoticonToolBar;
@property (nonatomic) BOOL enableShareWithTimestamp;
@property (nonatomic) UIView separatorLine;
@property (nonatomic) Q enterFromType;
@property (nonatomic) BOOL isHardAd;
@property (nonatomic) BOOL enableExpandInputViewHotspot;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) <AWEIMShareTextViewDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView<AWEIMShareInputEmoticonToolBarViewProtocol> emoticonToolBar;
@property (nonatomic) UIButton shareButton;
@property (nonatomic) UIView<AWEIMShareTimestampViewProtocol> timestampView;
- (void)setEnterFrom:;
- (id)enterFrom;
- (void)didClickedEmoticonControlButtonToStatus:;
- (void)didClickCheckBox:;
- (BOOL)isHardAd;
- (id)initWithFrame:config:;
- (void)handleKeyboardShowNoti:;
- (void)handleKeyboardHideNoti:;
- (id)videoImageView;
- (void)setVideoImageView:;
- (void)leftButtonClick;
- (void)rightButtonClick;
- (void)setButtonTypes:;
- (id)buttonTypes;
- (id)emoticonToolBar;
- (BOOL)enableEmoticonToolBar;
- (void)setEnableEmoticonToolBar:;
- (id)shareTextView;
- (unsigned long long)enterFromType;
- (void)setEnterFromType:;
- (void)setEmoticonToolBar:;
- (void)setShareTextView:;
- (void)updateShareText:;
- (id)currentShareText;
- (void)updateBottomButtonWithButtonTypes:;
- (BOOL)enableShareWithTimestamp;
- (void)updateVideoImageViewWithShareImpl:;
- (id)timestampView;
- (id)getShareContext;
- (void)p_setupObserver;
- (void)setTimestampView:;
- (BOOL)enableExpandInputViewHotspot;
- (void)respondButtonActionWithCurrentButtonType:;
- (void)sendShareMessage;
- (id)currentSelectedShareList;
- (void)sendMessageWithShareList:shareContext:needCreateGroup:;
- (void)updateButtonTitles:;
- (void)updateButtonLayoutWithButtonTypes:;
- (id)extraAsynchronousGestures;
- (void)showKeyBoardDirectly;
- (void)updateRightButton:;
- (void)setEnableShareWithTimestamp:;
- (void)setIsHardAd:;
- (void)setEnableExpandInputViewHotspot:;
- (void)setModel:;
- (void)setConfig:;
- (void)setLeftButton:;
- (void)setRightButton:;
- (BOOL)textView:shouldInteractWithTextAttachment:inRange:interaction:;
- (id)delegate;
- (id)leftButton;
- (id)config;
- (id)rightButton;
- (unsigned long long)type;
- (id)model;
- (void)setType:;
- (void).cxx_destruct;
- (void)setupConstraints;
- (void)setDelegate:;
- (id)textDraggableView:itemsForDrag:;
- (BOOL)textView:shouldChangeTextInRange:replacementText:;
- (void)textViewDidChange:;
- (id)shareButton;
- (id)separatorLine;
- (void)setSeparatorLine:;
- (void)setUpUI;
- (id)getView;
@end
