@interface AWESearchCorrectView : UICollectionReusableView
@property (nonatomic) AWESearchCorrectModel model;
@property (nonatomic) YYLabel keywordLabel;
@property (nonatomic) UIView lineView;
@property (nonatomic) AWESearchBackgroundView backgroundView;
@property (nonatomic) UIView parentContainer;
@property (nonatomic) @? tapBlock;
@property (nonatomic) Q theme;
@property (nonatomic) BOOL shouldShowDivideLine;
@property (nonatomic) AWESearchCorrectViewUIConfig uiConfig;
@property (nonatomic) BOOL enableAlphaBackground;
- (void)setTapBlock:;
- (id)tapBlock;
- (void)configureUI;
- (id)uiConfig;
- (void)setUiConfig:;
- (id)initWithCorrectModel:;
- (void)setShouldShowDivideLine:;
- (void)configureData;
- (void)configKeyword;
- (double)heightOfKeywordLabel;
- (void)addSearchEntranceForAttributedText:;
- (void)updateImmersiveBackgroundViewFrame;
- (void)attachBackgroundView:container:;
- (void)setEnableAlphaBackground:;
- (BOOL)enableAlphaBackground;
- (BOOL)shouldShowDivideLine;
- (void)updateSearchBackground:hidden:theme:enableAlphaBackground:container:;
- (unsigned long long)theme;
- (void)setModel:;
- (void)setTheme:;
- (void)setBackgroundView:;
- (id)initWithFrame:;
- (id)backgroundView;
- (id)model;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)lineView;
- (void)setLineView:;
- (id)parentContainer;
- (void)setParentContainer:;
- (id)defaultColor;
- (void)updateWithModel:;
- (id)keywordLabel;
- (void)setKeywordLabel:;
- (void)viewTapped;
- (double)maxLabelWidth;
+ (id)identifier;
@end
