@interface AWESearchFakeAnchorManager : NSObject
@property (nonatomic) NSString currentGid;
@property (nonatomic) NSMutableArray commentTopWords;
@property (nonatomic) NSMutableArray commentEntityWords;
@property (nonatomic) NSMutableArray currentRelatedSearchWords;
@property (nonatomic) NSMutableArray nextTimeRelatedSearchWords;
@property (nonatomic) NSMutableArray guideSearchWords;
@property (nonatomic) NSMutableArray clickRecomWords;
@property (nonatomic) NSString searchBarOuterWord;
@property (nonatomic) NSMutableArray descriptionEntityWords;
@property (nonatomic) NSMutableDictionary feedBottomWordsDic;
@property (nonatomic) NSMutableArray guessWords;
@property (nonatomic) NSMutableDictionary impressionExtraInfo;
@property (nonatomic) NSString strNextTimeRelatedSearchWordsUploadToken;
@property (nonatomic) NSString strCurrentRelatedSearchWordsUploadToken;
@property (nonatomic) NSMutableArray generalMaskedRSInfo;
@property (nonatomic) NSMutableArray generalMaskedGSInfo;
@property (nonatomic) NSMutableArray generalMaskedClickRecomInfo;
@property (nonatomic) NSString fromGroupId;
- (void)updateFeedBottomFakeAnchorForModel:gid:;
- (void)updateCommentTopFakeAnchorForModel:gid:;
- (void)updateFakeGuessWordsForWords:gid:;
- (void)updateSearchBarOuterWordForWord:gid:;
- (void)updateClickRecomWordsForWords:gid:;
- (void)updateGuideSearchWordsForWords:gid:;
- (void)updateRelatedSearchWordsForWords:uploadToken:gid:;
- (void)addCommentEntityWord:gid:;
- (void)addDescriptionEntityWord:gid:;
- (void)addImpressionExtraInfo:gid:;
- (id)maskedSearchParamsForGid:relatedSearchWordsUploadToken:;
- (void)removeAllFakeWords;
- (void)updateClickRecomWordsForGeneralMask:searchId:;
- (void)updateGSWordsForGeneralMask:searchId:;
- (void)updateRSWordsForGeneralMask:searchId:;
- (id)generalMaskedSearchParamsForSearchId:;
- (BOOL)hitOldMaskTypeForGid:;
- (void)setFromGroupId:;
- (id)fetchNextTimeRelatedSearchWordsUploadTokenWhenMaskedSearchFinished;
- (id)fromGroupId;
- (id)currentGid;
- (void)setCurrentGid:;
- (id)guessWords;
- (id)impressionExtraInfo;
- (void)setImpressionExtraInfo:;
- (id)feedBottomWordsDic;
- (id)commentTopWords;
- (void)setSearchBarOuterWord:;
- (id)clickRecomWords;
- (id)guideSearchWords;
- (id)strNextTimeRelatedSearchWordsUploadToken;
- (void)setStrCurrentRelatedSearchWordsUploadToken:;
- (void)setStrNextTimeRelatedSearchWordsUploadToken:;
- (void)resetNextTimeRelatedSearchWordsIfNeed;
- (id)nextTimeRelatedSearchWords;
- (id)currentRelatedSearchWords;
- (id)commentEntityWords;
- (id)descriptionEntityWords;
- (id)searchBarOuterWord;
- (id)strCurrentRelatedSearchWordsUploadToken;
- (id)generalMaskedClickRecomInfo;
- (void)p_updateMaskInfoWith:searchId:currentArray:;
- (id)generalMaskedGSInfo;
- (id)generalMaskedRSInfo;
- (id)getInfoBySearchId:infoArray:;
- (void)setCommentTopWords:;
- (void)setCommentEntityWords:;
- (void)setCurrentRelatedSearchWords:;
- (void)setNextTimeRelatedSearchWords:;
- (void)setGuideSearchWords:;
- (void)setClickRecomWords:;
- (void)setDescriptionEntityWords:;
- (void)setFeedBottomWordsDic:;
- (void)setGeneralMaskedRSInfo:;
- (void)setGeneralMaskedGSInfo:;
- (void)setGeneralMaskedClickRecomInfo:;
- (void)setGuessWords:;
- (id)init;
- (void).cxx_destruct;
+ (id)sharedManager;
@end
