@interface AWESmartPhoneConfig : NSObject
@property (nonatomic) NSString adID;
@property (nonatomic) NSString logExtra;
@property (nonatomic) NSString phoneNumber;
@property (nonatomic) NSString creativeID;
@property (nonatomic) NSNumber instanceID;
@property (nonatomic) NSString phoneKey;
@property (nonatomic) NSString positionTag;
@property (nonatomic) NSDictionary gscenario;
@property (nonatomic) NSString mKey;
@property (nonatomic) NSString customField;
@property (nonatomic) Q refer;
@property (nonatomic) NSDictionary extraInfo;
@property (nonatomic) NSString dialogShowEvent;
@property (nonatomic) NSString dialogItemClickEvent;
@property (nonatomic) NSString secretNumDialogUrl;
@property (nonatomic) NSDictionary abArgs;
@property (nonatomic) NSDictionary extraRootParams;
- (void)setLogExtra:;
- (id)logExtra;
- (id)adID;
- (void)setAdID:;
- (void)setCreativeID:;
- (void)setRefer:;
- (unsigned long long)refer;
- (id)phoneKey;
- (id)initWithOriginAdModel:;
- (void)setGscenario:;
- (void)setPositionTag:;
- (id)gscenario;
- (id)positionTag;
- (void)setMKey:;
- (void)setPhoneKey:;
- (void)setCustomField:;
- (id)customField;
- (id)extraRootParams;
- (BOOL)useSecretNumberDialog:;
- (id)secretNumDialogUrl;
- (id)dialogItemClickEvent;
- (id)dialogShowEvent;
- (id)abArgs;
- (id)secretNumberCustomField:;
- (void)setDialogShowEvent:;
- (void)setDialogItemClickEvent:;
- (void)setSecretNumDialogUrl:;
- (void)setAbArgs:;
- (void)setExtraRootParams:;
- (void)setInstanceID:;
- (id)instanceID;
- (id)phoneNumber;
- (void)setPhoneNumber:;
- (void).cxx_destruct;
- (id)extraInfo;
- (id)creativeID;
- (void)setExtraInfo:;
- (id)mKey;
@end
