@interface AWESearchFilmTVEpisodesView : UIView
@property (nonatomic) AWEGeneralSearchModel searchModel;
@property (nonatomic) AWEGeneralFilmTVSourceModel sourceModel;
@property (nonatomic) q buttonCount;
@property (nonatomic) NSMutableArray buttonArray;
@property (nonatomic) NSMutableArray vipLabelArray;
@property (nonatomic) NSArray modelArray;
@property (nonatomic) NSArray cellList;
@property (nonatomic) UIView footerView;
@property (nonatomic) UIView challengeStyleFooterView;
@property (nonatomic) @? buttonClickedBlock;
@property (nonatomic) BOOL fromChallenge;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setModelArray:;
- (id)modelArray;
- (void)setButtonArray:;
- (id)buttonArray;
- (double)viewHeight:ignoreBottomPadding:;
- (void)updateSourceModel:;
- (void)setButtonClickedBlock:;
- (void)setFromChallenge:;
- (id)cellList;
- (BOOL)fromChallenge;
- (id)challengeStyleFooterView;
- (void)setButtonCount:;
- (id)createViewModels:;
- (id)vipLabelArray;
- (void)updatePaymentStatus:withLabel:;
- (void)cellSelected:;
- (id)buttonClickedBlock;
- (void)setVipLabelArray:;
- (void)setCellList:;
- (void)setChallengeStyleFooterView:;
- (void)updateEpisodesModel:;
- (void)buttonTapped:;
- (void)setFooterView:;
- (id)footerView;
- (id)initWithFrame:;
- (void).cxx_destruct;
- (long long)buttonCount;
- (id)sourceModel;
- (void)setSearchModel:;
- (id)searchModel;
- (void)setSourceModel:;
+ (double)viewHeight:ignoreBottomPadding:;
+ (BOOL)enableFixEpisodesCellShowPeriods;
+ (BOOL)enableFixEpisodesCellReuse;
+ (BOOL)doubleColumnExperienceOptimize;
+ (double)viewHeight:;
@end
