@interface AWEShakeShareAwemeManager : NSObject
@property (nonatomic) NSObject<AWEUserLikesDataManagerProtocol> likeDataManager;
@property (nonatomic) NSMutableArray itemList;
@property (nonatomic) NSMutableDictionary sentShareIdMap;
@property (nonatomic) BOOL requestingShare;
@property (nonatomic) NSMutableArray shareInbox;
@property (nonatomic) NSMutableSet proceedShareIds;
@property (nonatomic) AWEShakeShareAwemeReceiveSharingPanel receivePanel;
@property (nonatomic) BOOL replyingShare;
@property (nonatomic) AWEAwemeModel awemeToShare;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)sheetWillStayAfterClickMaskArea;
- (void)sheetDidDismiss:;
- (void)onApplicationWillResignActive;
- (id)shareInbox;
- (void)setSentShareIdMap:;
- (void)setProceedShareIds:;
- (void)setAwemeToShare:;
- (id)likeDataManager;
- (void)updateWithNearbyItemList:;
- (void)updateWithShareInbox:;
- (void)updateShareModelIfNeededWithCurrentUser:newUser:;
- (BOOL)requestingShare;
- (void)trackShareSuccessForRadarUser:;
- (id)sentShareIdMap;
- (id)fetchRadarItemWithShareModelForUser:;
- (void)setRequestingShare:;
- (id)awemeToShare;
- (void)setShareInbox:;
- (id)receivePanel;
- (void)showReceiveSharePanelIfNeeded;
- (void)dismissReceiveSharePanelIfNeeded;
- (id)proceedShareIds;
- (void)replyShareWithShareId:accept:;
- (void)setReceivePanel:;
- (void)setReplyingShare:;
- (void)transToMessageVCIfNeedRetry:retryCount:;
- (void)fetchAwemeWithCurrentAweme:completion:;
- (void)updateWithNearbyItemList:shareInbox:completion:;
- (unsigned long long)shareCardStatusForUser:;
- (void)startShareAweme:toUser:completion:;
- (void)cancelShareAweme:toUser:completion:;
- (void)setLikeDataManager:;
- (BOOL)replyingShare;
- (id)init;
- (void).cxx_destruct;
- (id)itemList;
- (void)setItemList:;
@end
