@interface AWESearchMidDCDataController : AWEListDataController
@property (nonatomic) q doubleColumnFeedType;
@property (nonatomic) q pullType;
@property (nonatomic) q pullTimes;
@property (nonatomic) q retryTimes;
@property (nonatomic) NSMutableSet modelsSet;
@property (nonatomic) q lastOffset;
@property (nonatomic) NSTimer waitPrefetchTimer;
@property (nonatomic) @? optPrefetchResponseBlock;
@property (nonatomic) <AWEDCFeedListResponseProtocol> optPrefetchResponse;
@property (nonatomic) double retryFetchStartTime;
@property (nonatomic) q offset;
@property (nonatomic) NSString pageID;
@property (nonatomic) NSString uniquePageId;
@property (nonatomic) q innerOffset;
@property (nonatomic) q requestCount;
@property (nonatomic) q innerRequestCount;
@property (nonatomic) q innerRequest;
@property (nonatomic) NSString enterInnerDocId;
@property (nonatomic) NSDictionary clientExtra;
@property (nonatomic) NSArray fromModelsArray;
@property (nonatomic) q retryFetchState;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL isPrefetching;
@property (nonatomic) @? prefetchCompletion;
@property (nonatomic) @? prefetchResponseBlock;
@property (nonatomic) NSError prefetchError;
@property (nonatomic) NSArray prefetchDataList;
@property (nonatomic) <AWEDCFeedListResponseProtocol> prefetchResponse;
- (void)loadMoreWithCompletion:;
- (void)initFetchWithCompletion:;
- (void)fetchDataWithRequestParams:args:completion:;
- (void)refreshDataWithRequestParams:args:completion:;
- (void)loadMoreDataWithRequestParams:args:completion:;
- (void)cancelRequestTask;
- (long long)pullType;
- (void)setPullType:;
- (void)setIsPrefetching:;
- (BOOL)isPrefetching;
- (long long)retryTimes;
- (void)setRetryTimes:;
- (id)clientExtra;
- (void)setClientExtra:;
- (id)filterRepeatModel:;
- (id)transferAwemeListIfNeededWithArray:;
- (id)prefetchCompletion;
- (id)prefetchResponseBlock;
- (void)setPrefetchDataList:;
- (void)setPrefetchError:;
- (void)setPrefetchResponse:;
- (void)prefetchWithArgs:params:completion:dcCompletion:;
- (long long)doubleColumnFeedType;
- (void)setDoubleColumnFeedType:;
- (void)initFetchWithConfig:completion:;
- (void)initFetchWithConfig:completion:dcCompletion:;
- (void)initFetchWithConfig:args:completion:dcCompletion:;
- (void)initFetchWithConfig:bodyExtParams:args:completion:dcCompletion:;
- (BOOL)hasPrefetched;
- (void)setPullTimes:;
- (void)updateInnerModelTrackInfoIfNeededWithArray:;
- (void)refreshWithConfig:completion:;
- (void)refreshWithConfig:completion:dcCompletion:;
- (void)refreshWithConfig:args:completion:dcCompletion:;
- (void)refreshWithConfig:bodyExtParams:args:completion:dcCompletion:;
- (void)updatePullTimesIfNeeded;
- (void)setPrefetchCompletion:;
- (void)setPrefetchResponseBlock:;
- (id)prefetchDataList;
- (id)prefetchError;
- (id)prefetchResponse;
- (void)clearPrefetch;
- (void)loadMoreWithCompletion:dcCompletion:;
- (void)loadMoreWithConfig:completion:dcCompletion:;
- (void)loadMoreWithConfig:args:completion:dcCompletion:;
- (void)loadMoreWithConfig:bodyExtParams:args:completion:dcCompletion:;
- (long long)pullTimes;
- (id)modelsSet;
- (void)setModelsSet:;
- (id)uniquePageId;
- (void)setEnterInnerDocId:;
- (long long)innerRequestCount;
- (void)setInnerRequestCount:;
- (id)enterInnerDocId;
- (void)updateOuterRequestCount;
- (void)updateInnerRequestCount;
- (void)initFetchWithConfig:bodyExtParams:args:completion:dcCompletion:originCompletion:;
- (id)waitPrefetchTimer;
- (void)setWaitPrefetchTimer:;
- (void)setRetryFetchStartTime:;
- (void)invalidatePrefetchTimerIfNeeded;
- (id)optPrefetchResponse;
- (void)clearOptPrefetch;
- (void)createWaitPrefetchTimer:;
- (void)setRetryFetchState:;
- (void)trackInitErrorWithDataListIfNeeded:error:;
- (double)retryFetchStartTime;
- (void)setOptPrefetchResponseBlock:;
- (BOOL)optPrefetchIfNeeded:prefetchingBlock:prefetchedBlock:retryFetchBlock:;
- (id)fetchInnerBodyParams;
- (id)fetchOuterBodyParams;
- (void)preloadResource:;
- (void)addRankTagWithArray:;
- (void)addTagWithArray:args:;
- (void)trackFetchErrorWithDataListIfNeeded:error:args:;
- (BOOL)interceptRetryFetchData:error:;
- (void)setUniquePageId:;
- (id)fromModelsArray;
- (void)trackLoadMoreErrorWithDataListIfNeeded:error:;
- (long long)netErrorSceneWithArgs:;
- (void)preloadCoverImage:index:;
- (void)preloadAvatarImage:;
- (BOOL)enableCommonRequestParamsAddFeedFeature;
- (void)prefetchWithArgs:params:completion:dcCompletion:originCompletion:;
- (long long)retryFetchState;
- (id)optPrefetchResponseBlock;
- (void)setOptPrefetchResponse:;
- (BOOL)prefetchSuccessWithData:;
- (long long)innerOffset;
- (void)setInnerOffset:;
- (long long)innerRequest;
- (void)setInnerRequest:;
- (void)setFromModelsArray:;
- (void)setRequestCount:;
- (long long)requestCount;
- (void)setOffset:;
- (long long)offset;
- (void)commonInit;
- (void).cxx_destruct;
- (void)refreshWithCompletion:;
- (void)setPageID:;
- (id)initWithType:;
- (id)pageID;
- (long long)lastOffset;
- (void)setLastOffset:;
@end
