@interface AWEStorageServiceKVHandler : AWEStorageServiceHandler
@property (nonatomic) AWEKVStorageHandlerConfiguration config;
@property (nonatomic) <AWEStorageServiceKVUniversal> defaultStorage;
@property (nonatomic) <AWEStorageServiceKVUniversal> backupStorage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)objectForKey:withOptions:;
- (void)setObject:forKey:withOptions:;
- (void)removeObjectForKey:withOptions:;
- (id)stringForKey:withOptions:;
- (id)arrayForKey:withOptions:;
- (id)dictionaryForKey:withOptions:;
- (id)dataForKey:withOptions:;
- (long long)integerForKey:withOptions:;
- (void)setInteger:forKey:withOptions:;
- (float)floatForKey:withOptions:;
- (void)setFloat:forKey:withOptions:;
- (double)doubleForKey:withOptions:;
- (void)setDouble:forKey:withOptions:;
- (BOOL)boolForKey:withOptions:;
- (void)setBool:forKey:withOptions:;
- (id)URLForKey:withOptions:;
- (void)setURL:forKey:withOptions:;
- (void)setDefaultStorage:;
- (id)initWithDomain:options:;
- (void)storageHandlerConfiguration:;
- (void)setupStorageHandlerStorage:;
- (id)updateKey:withConfig:;
- (void)updateMetaDataIfNeeded:key:type:backup:size:;
- (void)removeMetaDataForKey:;
- (void)bothMemoryAndDiskStorageHandler:;
- (void)diskStorageHandler:;
- (void)memoryStorageHandler:;
- (BOOL)needBackupStorage:;
- (id)backupStorage;
- (void)setBackupStorage:;
- (void)setConfig:;
- (void)setDouble:forKey:;
- (void)setInteger:forKey:;
- (float)floatForKey:;
- (id)arrayForKey:;
- (id)stringForKey:;
- (id)dataForKey:;
- (id)config;
- (void)setBool:forKey:;
- (id)dictionaryForKey:;
- (void)removeObjectForKey:;
- (id)metaDataForKey:;
- (void).cxx_destruct;
- (id)objectForKey:;
- (double)doubleForKey:;
- (void)setFloat:forKey:;
- (id)initWithDomain:;
- (BOOL)boolForKey:;
- (long long)integerForKey:;
- (id)URLForKey:;
- (void)setObject:forKey:;
- (void)setURL:forKey:;
- (id)defaultStorage;
- (BOOL)isValidNumber:;
+ (id)universalStorageHandler;
@end
