@interface AWESearchGeneralSearchDoubleColumnPlayRule : NSObject
@property (nonatomic) BOOL isActive;
@property (nonatomic) double topActiveRedio;
@property (nonatomic) double bottomActiveRedio;
@property (nonatomic) NSArray playQueue;
@property (nonatomic) BOOL disableDoubleColumnCard;
@property (nonatomic) double speedLimit;
@property (nonatomic) UIView<AWESearchAutoPlayCardProtocol> wantToActiveCard;
@property (nonatomic) AWESearchAutoPlayHandler handler;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)p_isCard1:equalToCard2:;
- (id)wantToActiveCard;
- (id)playQueue;
- (void)currentCardPlayEnded;
- (long long)p_cardIndexInPlayQueue:;
- (void)setPlayQueue:;
- (void)setWantToActiveCard:;
- (id)getAutoPlayViewFromViews:inContainer:contentOffset:directionPoint:speedPoint:;
- (void)setDisableDoubleColumnCard:;
- (void)setTopActiveRedio:;
- (void)setBottomActiveRedio:;
- (double)bottomActiveRedio;
- (double)topActiveRedio;
- (BOOL)disableDoubleColumnCard;
- (BOOL)p_playQueue:ContainsCard:;
- (void)becomeActive;
- (void)setHandler:;
- (id)init;
- (void)setIsActive:;
- (double)speedLimit;
- (id)handler;
- (void)setSpeedLimit:;
- (void).cxx_destruct;
- (void)resignActive;
- (BOOL)isActive;
- (unsigned long long)ruleType;
@end
