@interface AWEShareLiveModel : NSObject
@property (nonatomic) <AWEShareLiveRoomModelProtocol> room;
@property (nonatomic) <AWEShareLiveContentModelProtocol> content;
@property (nonatomic) AWELiveRoomModel mappedRoom;
@property (nonatomic) Q posterType;
@property (nonatomic) UIImage tokenAlertTopImage;
@property (nonatomic) AWEShareLiveImageModel shareImageModel;
@property (nonatomic) q sceneType;
@property (nonatomic) BOOL isLiveChaine;
@property (nonatomic) NSString shareType;
- (id)extraParams;
- (id)backgroundImageUrl;
- (id)configID;
- (id)shareScene;
- (id)mappedRoom;
- (void)setMappedRoom:;
- (id)statsDic;
- (id)shareImageModel;
- (id)landscapeImageShareCallback;
- (void)setPosterType:;
- (void)setTokenAlertTopImage:;
- (void)setShareImageModel:;
- (void)setIsLiveChaine:;
- (BOOL)isPreLive;
- (BOOL)isHiddenReposter;
- (id)ugShareInfo;
- (id)tokenAlertTopImageURLs;
- (id)channelShareCallback;
- (BOOL)isLiveChaine;
- (id)tokenAlertTopImage;
- (id)content;
- (void)setContent:;
- (void).cxx_destruct;
- (id)room;
- (long long)sceneType;
- (void)setRoom:;
- (void)setSceneType:;
- (BOOL)isLandscape;
- (void)setShareType:;
- (id)shareType;
- (unsigned long long)posterType;
- (id)activityInfo;
@end
