@interface AWESearchVideoComponentLynxElement : LynxUI
@property (nonatomic) AWESearchLynxAwemeModelIndex awemeModelIndex;
@property (nonatomic) AWEAwemeModel awemeModel;
@property (nonatomic) NSString containerID;
@property (nonatomic) BOOL needUpdateModelFlag;
@property (nonatomic) BOOL showGuideAttribute;
@property (nonatomic) BOOL shouldUpdatePlayer;
@property (nonatomic) double durationCreateView;
@property (nonatomic) BOOL isReuse;
@property (nonatomic) BOOL attachedSessionId;
@property (nonatomic) @? playbackTimeBlock;
@property (nonatomic) NSTimer playbackTimeTimer;
@property (nonatomic) double playbackTime;
@property (nonatomic) NSDate startTimerDate;
@property (nonatomic) NSDate pauseTimerDate;
@property (nonatomic) q prePlayState;
@property (nonatomic) <AWESearchLynxBusinessVideoPlayerComponentProvider> playerComponent;
@property (nonatomic) AWESearchStandardVideoPlayerComponentModel playerModel;
@property (nonatomic) AWESearchPlayerInteractorComponentModel playerInteractorModel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <SearchDynamicElementStatusDelegate> statusDelegate;
@property (nonatomic) q transitionIndex;
- (id)awemeModel;
- (id)currentAwemeModel;
- (void)setAwemeModel:;
- (id)liveTransitionContext;
- (void)setPlaybackTimeBlock:;
- (void)setSign:;
- (void)layoutDidFinished;
- (void)play:withResult:;
- (void)pause:withResult:;
- (void)stop:withResult:;
- (void)playerPlayTime:canPlayTime:totalTime:;
- (void)logExtra:requestReset:;
- (void)poster:requestReset:;
- (void)fitMode:requestReset:;
- (void)didPlayError:;
- (void)didStartStall;
- (void)propsDidUpdate;
- (void)onNodeReady;
- (void)preloadVideoModel:;
- (long long)preferScaleMode;
- (BOOL)updateScaleModeBeforeAnimation;
- (void)setPlayerModel:;
- (id)playerModel;
- (id)componentLogData;
- (BOOL)isReuse;
- (void)setIsReuse:;
- (void)updateAwemeList:;
- (void)seek:withResult:;
- (void)didStartShowing;
- (BOOL)isMediaSourceCard;
- (void)startScroll;
- (void)endScroll;
- (void)repeat:requestReset:;
- (void)didSeekEnd:;
- (void)controlPlayerWithCommand:;
- (void)volume:requestReset:;
- (void)mute:requestReset:;
- (void)didRecallResource;
- (void)didPaymentVideoPreviewEnd;
- (void)didPaymentVideoPaid;
- (void)didRewardAdvertiseVideoPreviewEnd;
- (void)didRewardAdvertiseVideoUnlock;
- (void)setShouldUpdatePlayer:;
- (BOOL)shouldUpdatePlayer;
- (void)registerSearchUserGuide;
- (void)updateModelWithIndex:;
- (void)awemeindex:requestReset:;
- (void)sessionid:requestReset:;
- (void)setAwemeModelIndex:;
- (id)awemeModelIndex;
- (void)sendLoadingEvent;
- (void)setNeedUpdateModelFlag:;
- (BOOL)shouldExitFullScreenWithPlayStatus;
- (void)viewWillDisAppear;
- (void)syncplaystatus:requestReset:;
- (BOOL)shouldEnterFullScreenWithPlayer;
- (BOOL)needUpdateModelFlag;
- (void)addObserverForPaymentVideoIfNeeded;
- (void)updateWithPaidAwemeModel:;
- (id)reportUserInfoOnError;
- (BOOL)openAutoPlayMonitor;
- (void)attachContainerIDAsync:;
- (void)elementDidFinishBind;
- (void)attachContainerID;
- (void)bindContainerID;
- (void)setAttachedSessionId:;
- (BOOL)attachedSessionId;
- (void)btm_info:requestReset:;
- (void)showprogressbar:requestReset:;
- (void)control:requestReset:;
- (void)registerCallback:forReachingPlaybackTime:;
- (id)playbackTimeBlock;
- (void)updateSearchVideoCardName:;
- (BOOL)shouldEnterFullScreenWithPlayStatus;
- (id)getLynxElementType;
- (void)stopPlaybackTimeTimer;
- (void)startPlaybackTimeTimer;
- (void)onTimerAction;
- (id)playbackTimeTimer;
- (void)setPlaybackTimeTimer:;
- (id)playerComponent;
- (id)playerInteractorModel;
- (void)setPlayerComponent:;
- (void)setPlayerInteractorModel:;
- (long long)prePlayState;
- (BOOL)canResumePlaybackTimeTimer;
- (void)resumePlaybackTimeTimer;
- (void)setPrePlayState:;
- (void)pausePlaybackTimeTimer;
- (void)setStartTimerDate:;
- (id)pauseTimerDate;
- (id)startTimerDate;
- (void)setPauseTimerDate:;
- (void)playbackRate:requestReset:;
- (void)setDurationCreateView:;
- (void)setShowGuideAttribute:;
- (double)durationCreateView;
- (BOOL)showGuideAttribute;
- (void)showguide:requestReset:;
- (void)reactheadphoneschange:requestReset:;
- (void)watchedMonitor:requestReset:;
- (void)diggAnimate:withResult:;
- (BOOL)isPaidWithAweme:;
- (id)transformPlayerInteractorModelWithControlData:;
- (void)playerComponentUpdateWithModel:;
- (id)getDefaultPaidTagModelWithAwemeModel:;
- (void)componentdata:requestReset:;
- (id)transformPlayerComponentDataWithControlData:;
- (void)didBecomeActive;
- (void)setStatusDelegate:;
- (id)init;
- (void)setContainerID:;
- (void)play;
- (id)videoView;
- (void)prepareForReuse;
- (void)didResignActive;
- (id)transitionContext;
- (void)didEnd;
- (id)containerID;
- (void).cxx_destruct;
- (id)statusDelegate;
- (void)pause;
- (double)playbackTime;
- (void)setPlaybackTime:;
- (void)didStart;
- (id)createView;
- (void)resetPlayer;
- (void)didStop;
- (void)didPause;
+ (id)__lynx_prop_config__1992;
+ (id)__lynx_prop_config__1730;
+ (id)__lynx_prop_config__1841;
+ (id)__lynx_prop_config__2043;
+ (id)__lynx_prop_config__2134;
+ (id)__lynx_prop_config__2225;
+ (id)__lynx_prop_config__2316;
+ (id)__lynx_prop_config__2367;
+ (id)__lynx_prop_config__2439;
+ (id)__lynx_prop_config__25010;
+ (id)__lynx_prop_config__25511;
+ (id)__lynx_prop_config__26012;
+ (id)__lynx_prop_config__26513;
+ (id)__lynx_prop_config__27014;
+ (id)__lynx_prop_config__27515;
+ (id)__lynx_prop_config__28216;
+ (id)__lynx_prop_config__29017;
+ (id)__lynx_ui_method_config__35618;
+ (id)__lynx_ui_method_config__36019;
+ (id)__lynx_ui_method_config__36420;
+ (id)__lynx_ui_method_config__36821;
+ (id)__lynx_ui_method_config__39522;
@end
