@interface AWESearchListCommodityCollectionCell : SearchListCollectionCell
@property (nonatomic) BOOL needPlayFinishConf;
@property (nonatomic) NSArray awemeListModel;
@property (nonatomic) q playSession;
@property (nonatomic) @? cellVideoPlayFinished;
@property (nonatomic) BOOL needPlayFinish;
@property (nonatomic) double playInterval;
@property (nonatomic) @? playDidFinishBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeModel;
- (id)liveTransitionContext;
- (id)awemeListModel;
- (id)awemeList;
- (void)setAwemeListModel:;
- (void)updateAwemeList:;
- (id)livePlayerView;
- (BOOL)needPlayFinish;
- (double)playInterval;
- (id)playDidFinishBlock;
- (void)setPlayDidFinishBlock:;
- (void)updatePlayDidFinishBlk:;
- (void)didAsyncUpdatedUIFrame:;
- (void)updateSearchElementContext;
- (void)forwardElementMessageWithMesssageType:payload:;
- (long long)playSession;
- (BOOL)needPlayFinishConf;
- (id)cellVideoPlayFinished;
- (void)setNeedPlayFinishConf:;
- (void)setPlaySession:;
- (void)setCellVideoPlayFinished:;
- (void)didBecomeActive;
- (void)didResignActive;
- (id)transitionContext;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)activeView;
- (void)resetPlayer;
- (id)livePlayer;
@end
