@interface AWESearchAIGCCommonDetailDataController : AWESearchVerticalDataController
@property (nonatomic) NSNumber offset;
@property (nonatomic) q dataProcessIndex;
@property (nonatomic) NSString backtrace;
@property (nonatomic) BOOL isDoubleColumnLeft;
@property (nonatomic) NSString initialSearchSource;
@property (nonatomic) NSDictionary clientEngineExtra;
@property (nonatomic) NSString enterFromSecond;
@property (nonatomic) NSString query;
@property (nonatomic) NSString conversationID;
@property (nonatomic) NSString mainBotSearchID;
@property (nonatomic) NSString clientServerExtra;
@property (nonatomic) NSString extraLogData;
@property (nonatomic) NSString hitScene;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setHitScene:;
- (void)setContainerConfig:;
- (id)enterFromSecond;
- (void)setEnterFromSecond:;
- (void)setInitialSearchSource:;
- (id)initialSearchSource;
- (id)clientEngineExtra;
- (void)setClientEngineExtra:;
- (Class)customResponseClass;
- (Class)customRequestParamsClass;
- (void)refreshResponse:;
- (void)loadMoreResponse:;
- (id)customInnerVCModelsFromOuterDataModels:;
- (id)customAwemeModelFromOuterDataModel:;
- (id)p_getValidResponse:;
- (BOOL)isDoubleColumnLeft;
- (void)setIsDoubleColumnLeft:;
- (void)resetRankDataIndex;
- (id)generalDelegate;
- (id)generalCachalotRequestCommonParams;
- (id)clientServerExtra;
- (void)setDataProcessIndex:;
- (long long)dataProcessIndex;
- (id)generalCachalotRequestRefreshParams;
- (id)generalCachalotRequestLoadMoreParams;
- (void)setClientServerExtra:;
- (void)setUpRequestParamsDelegate;
- (void)generateLeafModelsAndCardArrayForResponse:isFromSteam:;
- (void)generateCardArrayForResponse:;
- (id)mainBotSearchID;
- (id)hitScene;
- (void)preGenerateLeafModelsForResponse:isFromSteam:;
- (id)extraLogData;
- (void)setMainBotSearchID:;
- (void)setExtraLogData:;
- (id)backtrace;
- (id)init;
- (void)setOffset:;
- (id)offset;
- (void)setQuery:;
- (id)query;
- (id)conversationID;
- (void).cxx_destruct;
- (void)setConversationID:;
- (void)setBacktrace:;
@end
