@interface AWESearchAIGCQueryContext : NSObject
@property (nonatomic) NSString query;
@property (nonatomic) NSString tosid;
@property (nonatomic) UIImage image;
@property (nonatomic) q imageHeight;
@property (nonatomic) q imageWidth;
@property (nonatomic) NSArray imageUrlList;
@property (nonatomic) NSString originalSearchId;
@property (nonatomic) NSString originalQuery;
@property (nonatomic) NSString videoID;
@property (nonatomic) NSArray videoImageURLList;
@property (nonatomic) q videoImageHeight;
@property (nonatomic) q videoImageWidth;
@property (nonatomic) UIImage videoImage;
@property (nonatomic) NSDictionary appendRequestParams;
@property (nonatomic) NSString searchUniqueID;
@property (nonatomic) BOOL isShowHistoryTips;
- (id)imageUrlList;
- (void)setImageUrlList:;
- (id)videoImage;
- (void)setVideoImage:;
- (id)videoImageURLList;
- (void)setVideoImageURLList:;
- (long long)videoImageHeight;
- (void)setVideoImageHeight:;
- (long long)videoImageWidth;
- (void)setVideoImageWidth:;
- (id)appendRequestParams;
- (void)setAppendRequestParams:;
- (id)tosid;
- (void)setTosid:;
- (id)searchUniqueID;
- (void)setSearchUniqueID:;
- (BOOL)isPicTextSearch;
- (id)initWithBubbleModel:;
- (BOOL)isPurePicSearch;
- (id)originalSearchId;
- (void)setOriginalSearchId:;
- (BOOL)isShowHistoryTips;
- (void)setIsShowHistoryTips:;
- (id)initWithQuery:;
- (id)image;
- (void)setImage:;
- (void)setQuery:;
- (id)query;
- (void).cxx_destruct;
- (long long)imageWidth;
- (long long)imageHeight;
- (id)videoID;
- (void)setVideoID:;
- (id)originalQuery;
- (void)setOriginalQuery:;
- (void)setImageHeight:;
- (void)setImageWidth:;
+ (id)safeQuery:;
@end
