@interface AWESearchHotSpotDiscussTabSelectCard : UIViewController
@property (nonatomic) UIView selectBgView;
@property (nonatomic) UIView splitView;
@property (nonatomic) DUXBaseLabel generalTab;
@property (nonatomic) DUXBaseLabel rencentTab;
@property (nonatomic) DUXBaseLabel tipsLabel;
@property (nonatomic) UIView contentView;
@property (nonatomic) AWESearchCachalotResultContext cachalotContext;
@property (nonatomic) AWESearchTracker tracker;
@property (nonatomic) AWEModernFeedCellModel dataModel;
@property (nonatomic) <AWEModernFeedCellContext> context;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) # cardClass;
- (id)tipsLabel;
- (void)setTipsLabel:;
- (void)trackShow;
- (void)componentClicked;
- (void)componentWillDisplay;
- (void)configUI;
- (void)trackClick;
- (id)splitView;
- (void)setSplitView:;
- (id)cachalotContext;
- (void)setCachalotContext:;
- (id)selectBgView;
- (void)setSelectBgView:;
- (id)generalTab;
- (id)rencentTab;
- (void)p_tabChangedAction:isClicked:;
- (void)generalTabClicked;
- (void)rencentTabClicked;
- (void)switchToCorrespondingTab:;
- (void)setGeneralTab:;
- (void)setRencentTab:;
- (id)init;
- (id)tracker;
- (id)contentView;
- (id)initWithContext:;
- (void)setTracker:;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setContentView:;
- (id)context;
- (id)componentView;
- (id)dataModel;
- (void)setDataModel:;
- (void)updateWithViewModel:;
- (void)updateWithModel:;
+ (double)modernFeedCellPreferedHeightForModel:width:;
+ (id)sizeWithViewModel:width:;
@end
