@interface AWESearchScanCircleSearchHelper : NSObject
@property (nonatomic) BOOL hitWhiteList;
@property (nonatomic) NSString searchFrom;
- (void)setSearchFrom:;
- (BOOL)hitWhiteList;
- (void)setHitWhiteList:;
- (id)searchFrom;
- (void).cxx_destruct;
+ (BOOL)enableDrawCircle;
+ (BOOL)disableBorderAndPoint;
+ (BOOL)impEnableClickBorder;
+ (BOOL)impEnableDrawCircle;
+ (BOOL)impDisableBorderAndPoint;
+ (double)impCircleSearchPathWidth;
+ (id)impCircleSearchPathColor;
+ (double)impCircleSearchPathRadius;
+ (id)impCircleSearchCursorImage;
+ (id)impCircleSearchRectImage;
+ (double)impCircleSearchBorderInnerPadding;
+ (double)impCircleSearchBorderOutterPadding;
+ (id)impCircleSearchBorderColor;
+ (double)impCircleSearchBorderRadius;
+ (double)impCircleSearchBorderMinWidth;
+ (double)impCircleSearchPathAnimationDuration;
+ (double)impCircleSearchRectAnimationDuration;
+ (long long)impCircleSearchGuideTimes;
+ (double)impCircleSearchGuideDuration;
+ (id)impCircleSearchGuideClickText;
+ (id)impCircleSearchGuideCircleText;
+ (id)impCircleSearchGuideCircleAndClickText;
+ (BOOL)impCircleSearchUseCurveBezier;
+ (BOOL)impCircleSearchUseAntialias;
+ (BOOL)isCircleMode;
+ (BOOL)enableClickBorder;
+ (double)clickBorderDefaultWidth;
+ (double)clickBorderMinWidth;
+ (double)circleSearchPathWidth;
+ (id)circleSearchPathColor;
+ (double)circleSearchPathRadius;
+ (id)circleSearchCursorImage;
+ (id)circleSearchRectImage;
+ (double)circleSearchBorderInnerPadding;
+ (double)circleSearchBorderOutterPadding;
+ (id)circleSearchBorderColor;
+ (double)circleSearchBorderRadius;
+ (double)circleSearchBorderMinWidth;
+ (double)circleSearchPathAnimationDuration;
+ (double)circleSearchRectAnimationDuration;
+ (long long)circleSearchGuideTimes;
+ (double)circleSearchGuideDuration;
+ (id)circleSearchGuideClickText;
+ (id)circleSearchGuideCircleText;
+ (id)circleSearchGuideCircleAndClickText;
+ (BOOL)circleSearchUseCurveBezier;
+ (BOOL)circleSearchUseAntialias;
+ (id)sharedInstance;
@end
