@interface AWEShakeShareAwemeCardView : UIView
@property (nonatomic) Q status;
@property (nonatomic) AWEAwemeModel aweme;
@property (nonatomic) AWEUserModel user;
@property (nonatomic) UIImageView coverImageView;
@property (nonatomic) UIStackView titleStackView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) AWEShakeShareAwemeLoadingLabel subTitleLabel;
@property (nonatomic) UIView separatorLine;
@property (nonatomic) UILabel descriptionLabel;
@property (nonatomic) UIButton shareButton;
@property (nonatomic) BOOL isSharingLikedAweme;
@property (nonatomic) @? actionBlock;
- (id)aweme;
- (void)setAweme:;
- (id)coverImageView;
- (void)setCoverImageView:;
- (void)initView;
- (void)configCoverWithStatus:aweme:user:;
- (void)configDescriptionLabelWithStatus:aweme:user:;
- (void)configShareButtonWithStatus:aweme:user:;
- (void)configTitleLabelWithStatus:aweme:user:;
- (void)configSubTitleLabelWithStatus:aweme:user:;
- (void)configItemAlphaWithStatus:aweme:user:;
- (BOOL)isSharingLikedAweme;
- (double)titleMaxWidth;
- (id)truncateStringWithPrefix:middle:postfix:maxWidth:attributes:;
- (void)coverImageViewTapped;
- (void)updateWithStatus:aweme:user:;
- (double)subtitleMaxWidth;
- (void)setIsSharingLikedAweme:;
- (id)user;
- (void)setUser:;
- (void)setDescriptionLabel:;
- (void)setStatus:;
- (id)initWithFrame:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (unsigned long long)status;
- (id)titleLabel;
- (id)descriptionLabel;
- (void)setActionBlock:;
- (id)actionBlock;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
- (void)setTitleStackView:;
- (id)titleStackView;
- (void)setShareButton:;
- (id)shareButton;
- (id)separatorLine;
- (void)setSeparatorLine:;
- (void)setupLayout;
- (void)shareButtonTapped;
@end
