@interface AWESearchVideoCardShortAnswerComponent : AWESearchComponent
@property (nonatomic) UIView contentView;
@property (nonatomic) YYLabel answerText;
@property (nonatomic) UIImageView lineView;
@property (nonatomic) AWESearchVideoCardAnswerThemeView answerThemeView;
@property (nonatomic) AWEGeneralSearchVideoCardModel bindedModel;
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) BOOL currentModelFromSetupModelOnly;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)playerProvider;
- (void)updateWithModel:forceUpdate:;
- (void)trackSearchResultClick;
- (void)setBindedModel:;
- (id)bindedModel;
- (void)setModelOnly:;
- (void)setCurrentModelFromSetupModelOnly:;
- (BOOL)currentModelFromSetupModelOnly;
- (id)descProvider;
- (id)answerThemeView;
- (void)setAnswerThemeView:;
- (void)setModel:;
- (id)init;
- (id)contentView;
- (id)model;
- (void).cxx_destruct;
- (void)setContentView:;
- (id)componentView;
- (id)lineView;
- (void)setLineView:;
- (void)setupUI;
- (id)abstractProvider;
- (id)answerText;
- (void)setAnswerText:;
+ (id)componentSizeForModel:width:;
+ (id)calculateSizeWithModel:Width:;
+ (id)shortAnswerTextWithModel:;
@end
