@interface AWESearchWebTranscodeNovelBussiness : AWESearchWebTranscodeBussiness
@property (nonatomic) BDXWebView webView;
@property (nonatomic) BOOL isDomReady;
@property (nonatomic) BOOL isLoadingEnd;
@property (nonatomic) BOOL isTranscodePageShowing;
@property (nonatomic) BOOL webViewHasReloaded;
@property (nonatomic) NSError latestLoadError;
@property (nonatomic) BOOL webViewRequestTimeOut;
@property (nonatomic) BOOL hitSCC;
@property (nonatomic) BOOL hitBlackList;
@property (nonatomic) NSDictionary novelTranscodingData;
@property (nonatomic) Q transcodeResult;
@property (nonatomic) NSString pageType;
@property (nonatomic) NSDictionary transcodingJson;
@property (nonatomic) NSString transcodingExtra;
@property (nonatomic) AWESearchWebViewTranscodingManager transcodingManager;
@property (nonatomic) NSObject novelMonitorContext;
@property (nonatomic) NSString novelTranscodeEnterMehod;
@property (nonatomic) UIView loadingBackView;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) AWESearchWebViewNovelTranscodingManager novelTranscodingManager;
@property (nonatomic) NSMutableDictionary webExitTrackDict;
@property (nonatomic) double onLoadTime;
@property (nonatomic) double onTranscodeBeginTime;
@property (nonatomic) AWESearchWebPreloadPlugin preloadPlugin;
@property (nonatomic) BOOL isFromCloseTranscode;
@property (nonatomic) AWESearchWebNovelNativeReaderHelper readerHelper;
@property (nonatomic) NSString serverNovelTranscodingData;
- (id)webViewWillDealloc:;
- (id)webView:loadRequest:;
- (id)webView:loadData:MIMEType:characterEncodingName:baseURL:;
- (id)webView:loadHTMLString:baseURL:;
- (void)setHitBlackList:;
- (id)searchParamsBlock;
- (id)loadingBackView;
- (void)setLoadingBackView:;
- (void)refreshActionBlock;
- (unsigned long long)transcodeResult;
- (BOOL)isDomReady;
- (BOOL)hitBlackList;
- (double)onLoadTime;
- (void)setOnLoadTime:;
- (id)transcodingManager;
- (void)setTranscodingManager:;
- (void)backActionBlock;
- (id)currentTranscodingManager;
- (void)copyActionBlock;
- (id)transcodingExtra;
- (void)setTranscodingExtra:;
- (double)onTranscodeBeginTime;
- (void)setOnTranscodeBeginTime:;
- (id)monitorTrackParams:;
- (void)updateWithContainerContext:;
- (void)webViewOnLoad:;
- (void)setIsDomReady:;
- (void)setIsLoadingEnd:;
- (void)setTranscodeResult:;
- (void)setIsTranscodePageShowing:;
- (void)setWebViewHasReloaded:;
- (void)setWebExitTrackDict:;
- (void)setLatestLoadError:;
- (void)setHitSCC:;
- (void)setNovelTranscodeEnterMehod:;
- (void)setNovelMonitorContext:;
- (id)novelMonitorContext;
- (void)hookWKWebViewConsoleLog;
- (void)sccRejected:;
- (BOOL)enableTrackWebReadPercent;
- (void)reportTranscodeResultWithRequestUrl:Code:;
- (id)novelTranscodeEnterMehod;
- (void)setIsFromCloseTranscode:;
- (void)setWebViewRequestTimeOut:;
- (id)webExitTrackDict;
- (BOOL)hitSCC;
- (void)registerWebTranscodeJSBridge;
- (void)trackWebHitBlackList;
- (void)showNovelPreloadTranscodePage;
- (void)requestNovelTranscodeData;
- (BOOL)enableWebInjectDisappearBlock;
- (void)setupWebBlankDetect;
- (BOOL)enableWebInjectDomReady;
- (void)showTranscodingSwitch:;
- (BOOL)isFromCloseTranscode;
- (BOOL)couldRemoveBlankView;
- (void)webViewDidLoadTimeout;
- (void)removeLoadingBGView;
- (void)trackWebLoadFailWithError:;
- (id)preloadPlugin;
- (BOOL)webViewHasReloaded;
- (void)trackWebLoadEnd;
- (void)beginTranscode;
- (void)setTranscodingJson:;
- (BOOL)webViewRequestTimeOut;
- (void)performTranscoding;
- (void)updateDataEngineAndTrackerWithConfig;
- (void)extraCatalogDataWithTranscodeResult:;
- (void)pushTranscodedNovelWithData:source:type:;
- (void)setServerNovelTranscodingData:;
- (id)novelTranscodingManager;
- (id)transcodingJson;
- (void)asyncLoadTranscodingWithCompletion:;
- (void)loadTranscodingScript;
- (void)asyncLoadCommonTranscodingWithCompletion:;
- (void)trackWebTranscodeFinish:;
- (BOOL)shouldReturnTranscoding;
- (id)novelTranscodingData;
- (void)removeUselessWebView:;
- (void)trackWebDomReady;
- (void)removeWebLoadingView;
- (void)webViewDidFinishTranscodingWithCode:;
- (void)setNovelTranscodingData:;
- (id)readerHelper;
- (void)trackStayPage;
- (void)setPreloadPlugin:;
- (void)setReaderHelper:;
- (id)findSuperViewControllerOfWebView;
- (id)serverNovelTranscodingData;
- (void)trackLoadTranscodingScript:isSuccess:resFrom:errorMsg:;
- (void)trackWebPageShowImmediately:;
- (BOOL)enableWebBlankDetect;
- (void)trackWebExitBlankCheck:immediately:;
- (BOOL)isLoadingEnd;
- (id)latestLoadError;
- (BOOL)isTranscodePageShowing;
- (void)setNovelTranscodingManager:;
- (void)searchBarActionBlock;
- (void)turnOnTranscodeBlock;
- (void)turnOffCurrentTranscodeBlock;
- (void)turnOffGlobalTranscodeBlock;
- (BOOL)checkCanAutoTranscode;
- (void)tryShowTranscodingDialogByResonse;
- (void)tryShowTranscodingDialogByFrontEndSpecialEvent;
- (void)tryAddWebNovelLoadingView;
- (void)checkIfCanbeTranscodeWithSuccessCode:WithComplte:;
- (id)webView:didFinishNavigation:;
- (id)webView:didStartProvisionalNavigation:;
- (id)webView:didCommitNavigation:;
- (void)setWebView:;
- (void)setLoadingView:;
- (id)webView:didFailNavigation:withError:;
- (id)webView;
- (id)loadingView;
- (void)setPageType:;
- (id)webView:didFailProvisionalNavigation:withError:;
- (void).cxx_destruct;
- (id)webView:decidePolicyForNavigationAction:decisionHandler:;
- (id)pageType;
- (void)reloadWebView;
@end
