@interface AWETripleColumnPlayletSectionCell : UICollectionViewCell
@property (nonatomic) UIView coverContainerView;
@property (nonatomic) BDImageView coverImageView;
@property (nonatomic) UIImage placeholderImage;
@property (nonatomic) AWEGradientView gradientView;
@property (nonatomic) UIView tagView;
@property (nonatomic) UILabel tagLabel;
@property (nonatomic) UIView playCountView;
@property (nonatomic) BDImageView playCountIcon;
@property (nonatomic) UILabel playCountLabel;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel subTitleLabel;
- (id)coverImageView;
- (void)setCoverImageView:;
- (id)tagLabel;
- (void)setTagLabel:;
- (id)playCountLabel;
- (void)setPlayCountLabel:;
- (id)coverContainerView;
- (void)setCoverContainerView:;
- (void)configWithSectionItem:;
- (double)titleFontForCurrentBreakPoint;
- (id)playCountView;
- (id)playCountIcon;
- (void)setPlayCountView:;
- (void)setPlayCountIcon:;
- (id)placeholderImage;
- (void)setPlaceholderImage:;
- (id)gradientView;
- (void)prepareForReuse;
- (id)initWithFrame:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (void)setGradientView:;
- (id)titleLabel;
- (void)layoutSubviews;
- (void)setupUI;
- (void)setSubTitleLabel:;
- (id)subTitleLabel;
- (void)setupLayout;
- (id)tagView;
- (void)setTagView:;
+ (id)identifier;
@end
