@interface AWETeenLongPressPanelBaseViewModel : NSObject
@property (nonatomic) q actionType;
@property (nonatomic) NSString describeString;
@property (nonatomic) NSString duxIconName;
@property (nonatomic) UIColor duxIconColor;
@property (nonatomic) UIImage iconImage;
@property (nonatomic) AWETeenLongPressPanelContext context;
@property (nonatomic) BOOL showSelected;
@property (nonatomic) NSString describeSelectedString;
@property (nonatomic) NSString duxIconSelectedName;
@property (nonatomic) UIColor duxIconSelectedColor;
@property (nonatomic) @? action;
@property (nonatomic) UIView rightSubview;
@property (nonatomic) {CGSize=dd} rightSubviewSize;
@property (nonatomic) double rightPadding;
@property (nonatomic) @? willAppearBlock;
@property (nonatomic) <AWETeenLongPressPanelDelegate> delegate;
- (void)setDuxIconName:;
- (void)setDescribeString:;
- (id)willAppearBlock;
- (void)setWillAppearBlock:;
- (void)setRightPadding:;
- (id)duxIconColor;
- (id)getCommonSwitch;
- (id)describeString;
- (id)duxIconName;
- (id)getCommonSegmentWithItems:delegate:;
- (id)duxIconSelectedName;
- (void)setDuxIconSelectedName:;
- (void)setDuxIconColor:;
- (id)duxIconSelectedColor;
- (void)setDuxIconSelectedColor:;
- (id)describeSelectedString;
- (void)setDescribeSelectedString:;
- (BOOL)showSelected;
- (void)setShowSelected:;
- (void)dismissPanel;
- (void)setRightSubview:;
- (id)rightSubview;
- (id)rightSubviewSize;
- (void)setRightSubviewSize:;
- (long long)actionType;
- (void)setActionType:;
- (id)iconImage;
- (id)delegate;
- (void)setIconImage:;
- (void)setAction:;
- (id)action;
- (void)setContext:;
- (void).cxx_destruct;
- (void)setDelegate:;
- (id)context;
- (double)rightPadding;
@end
