@interface AWETeenMessageViewController : UIViewController
@property (nonatomic) UITableView tableView;
@property (nonatomic) AWEUILoadingView loadingView;
@property (nonatomic) AWENotificationModelNew actionSheetOperationModel;
@property (nonatomic) AWETeenMessageDataController dataController;
@property (nonatomic) BOOL needRefresh;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString awe_padUITrackerPageEnterFrom;
@property (nonatomic) BOOL awe_padUITrackerIgnoreStayTime;
- (void)p_setupUI;
- (id)aweui_emptyPageConfigForState:;
- (void)aweui_emptyPagePrimaryButtonTapped:;
- (id)aweui_emptyPageEdgeInsets;
- (void)didFinishLogin;
- (BOOL)awe_shouldAutorotate;
- (unsigned long long)awe_supportedInterfaceOrientations;
- (void)setDataController:;
- (void)setNeedRefresh:;
- (void)teenModeDidChange:isLogout:;
- (id)titleForActionSheet;
- (id)awe_padUITrackerPageEnterFrom;
- (void)p_loadMoreData;
- (void)p_refreshData;
- (void)awe_themeDidChange;
- (void)deleteNotice;
- (void)readAllMessage;
- (id)getTitleAction:;
- (void)onSettingClick:;
- (void)onGotoDetailClick:;
- (void)onNoticeTextUnfoldCell:;
- (void)p_addHeaderAndFooter;
- (void)p_initFetchData;
- (void)showActionSheet:;
- (void)setActionSheetOperationModel:;
- (id)actionSheetOperationModel;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (void)dealloc;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (void)setLoadingView:;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (id)tableView;
- (id)loadingView;
- (BOOL)needRefresh;
- (void).cxx_destruct;
- (BOOL)refreshWithCompletion:;
- (void)viewDidAppear:;
- (id)dataController;
@end
