@interface AWETheaterHotLiveContentCell : UICollectionViewCell
@property (nonatomic) UIView containerView;
@property (nonatomic) BDImageView imageView;
@property (nonatomic) UILabel title;
@property (nonatomic) UILabel subTitle;
@property (nonatomic) UILabel timeLabel;
@property (nonatomic) UILabel priceLabel;
@property (nonatomic) <AWELiveShowTagViewProtocol> tagViewModel;
@property (nonatomic) UIView tagView;
@property (nonatomic) UIButton enterLiveButton;
@property (nonatomic) UIButton appointmentButton;
@property (nonatomic) UIButton paidButton;
@property (nonatomic) BDXBridgeEventSubscriber subscriber;
@property (nonatomic) AWETheaterCommonSectionItem sectionItem;
@property (nonatomic) @? handleTicketPackage;
@property (nonatomic) @? handleCardClickTrack;
- (id)enterLiveButton;
- (void)setEnterLiveButton:;
- (void)setUI;
- (void)openPaidPanel;
- (id)getUserSchemaInAppointmentScene;
- (void)subscribeEventBuyTicketSuccess;
- (void)unsubscribeEvent;
- (id)tagViewModel;
- (id)theaterCommonParams;
- (id)paidLiveCommonParams;
- (void)setTagViewModel:;
- (void)tagViewCustomWithItem:;
- (id)appointmentButton;
- (id)paidButton;
- (void)updateTimeLabelFrame;
- (void)showRightBottomButton;
- (void)updateEnterLiveButtonIfNeed;
- (void)updatePaidButtonIfNeed;
- (void)updateAppointmentButtonIfNeed;
- (void)changePaidButtonStatus:;
- (void)trackBuyticketButtonShow;
- (void)trackAppointmentCardShow;
- (void)changeAppointmentStatus:;
- (id)handleCardClickTrack;
- (void)openAppointmentPanel;
- (void)appointmentRequesCompletion:;
- (void)trackAppointmentCardClick:;
- (void)requestForTicket;
- (void)trackAppointmentCardSuccess:;
- (void)showShareTicketWith:;
- (void)trackBuyticketButtonClick;
- (id)handleTicketPackage;
- (void)enterActionClick;
- (void)paidButtonDidClick;
- (id)appointmentCommonParams;
- (id)buyticketButtonCommonParams;
- (void)containerViewClick;
- (void)appointmentButtonDidClick;
- (void)setHandleTicketPackage:;
- (void)setHandleCardClickTrack:;
- (void)setAppointmentButton:;
- (void)setPaidButton:;
- (void)setTimeLabel:;
- (void)prepareForReuse;
- (id)subscriber;
- (void)setSubscriber:;
- (id)initWithFrame:;
- (id)containerView;
- (void)setSubTitle:;
- (id)subTitle;
- (void)setContainerView:;
- (void).cxx_destruct;
- (id)timeLabel;
- (id)title;
- (void)setImageView:;
- (void)setTitle:;
- (id)imageView;
- (id)priceLabel;
- (void)setPriceLabel:;
- (void)setSectionItem:;
- (id)sectionItem;
- (id)tagView;
- (void)setTagView:;
@end
