@interface AWETeenLandscapePlayInteractionView : NSObject
@property (nonatomic) AWEAwemeModel model;
@property (nonatomic) AWEMinorAlbum albumModel;
@property (nonatomic) UIViewController<AWETeenLandscapePlayInteractionViewDelegate> viewController;
@property (nonatomic) AWETeenPlayInteractionContext context;
@property (nonatomic) Q interactionStatus;
@property (nonatomic) AWETeenPlayInteractionProgressHelper progressHelper;
@property (nonatomic) AWETeenModePlayerProgressSlider progressSlider;
@property (nonatomic) AWETeenPlayInteractionMaximumProgressView centerProgressView;
@property (nonatomic) AWETeenPlayInteractionMiniProgressView miniProgressView;
@property (nonatomic) AWEGradientView topMaskView;
@property (nonatomic) AWEGradientView bottomMaskView;
@property (nonatomic) AWETeenLandscapeSpeedPlayView speedPlayContainer;
@property (nonatomic) UIView seekMaskView;
@property (nonatomic) UIImageView previewImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIButton backButton;
@property (nonatomic) UIButton playButton;
@property (nonatomic) UIButton nextEpisodeButton;
@property (nonatomic) UIButton screenCastButton;
@property (nonatomic) AWETeenCastPopover castPopover;
@property (nonatomic) double lastPlayDuration;
@property (nonatomic) NSTimer enterImmersiveTimer;
@property (nonatomic) AWEElementContainer bottomContainer;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) double bottomMargin;
@property (nonatomic) Q playerStatus;
- (void)p_setupUI;
- (void)setHide:;
- (void)videoDidActivity;
- (void)setBottomMaskView:;
- (id)bottomMaskView;
- (id)topMaskView;
- (void)setTopMaskView:;
- (void)p_updateInteractionElementsStatus;
- (void)p_updateDataForContainerElements:;
- (id)aAWEBrandColorAdapter;
- (void)setLastPlayDuration:;
- (double)lastPlayDuration;
- (id)sliderThemeColor;
- (id)screenCastButton;
- (void)setScreenCastButton:;
- (id)albumModel;
- (void)setAlbumModel:;
- (void)updatePlayProgressWithTime:totalDuration:;
- (void)setPlayProgressWithTime:totalDuration:;
- (void)screenCastButtonClicked;
- (void)updateUIAccordingtoModel:;
- (void)setHide:animated:;
- (id)enterImmersiveTimer;
- (void)p_setupEvent;
- (id)nextEpisodeButton;
- (id)miniProgressView;
- (void)p_startEnterImmersiveTimer;
- (void)p_stopEnterImmersiveTimer;
- (void)setCastPopover:;
- (id)progressHelper;
- (id)castPopover;
- (id)aAWETeenModeSettingsViewModelCommonAdapter;
- (void)setInteractionStatus:;
- (id)speedPlayContainer;
- (void)playerSeekingBegin;
- (void)playerSeekingEnd;
- (void)updateProgressSliderWithPlayableTime:totalDuration:;
- (void)changeImmersiveStatus:;
- (id)seekMaskView;
- (id)centerProgressView;
- (void)p_setupScreenCastEntrance;
- (void)p_setupRightBottomButtons;
- (unsigned long long)interactionStatus;
- (void)setEnterImmersiveTimer:;
- (id)bottomContainerElements;
- (void)exitLandscapeClicked;
- (void)nextEpisodeButtonClicked;
- (void)progressTapSeek;
- (void)progressPanSeekBegin;
- (void)progressPanSeekChanged:previewImage:;
- (void)progressPanSeekEnd;
- (void)closePlaybackRatePanel;
- (void)setProgressHelper:;
- (void)setCenterProgressView:;
- (void)setMiniProgressView:;
- (void)setSpeedPlayContainer:;
- (void)setSeekMaskView:;
- (void)setNextEpisodeButton:;
- (id)backButton;
- (void)setModel:;
- (void)dealloc;
- (void)resume;
- (id)view;
- (void)viewDidLoad;
- (void)setBackButton:;
- (void)prepareForDisplay;
- (id)viewController;
- (id)model;
- (void)setTitleLabel:;
- (void)setData:;
- (void)viewWillAppear;
- (void)setContext:;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)reset;
- (void)viewDidAppear;
- (id)context;
- (void)pause;
- (void)setViewController:;
- (id)previewImageView;
- (void)setPreviewImageView:;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)didEndDisplaying;
- (id)playButton;
- (unsigned long long)playerStatus;
- (void)setPlayButton:;
- (void)setPlayerStatus:;
- (id)progressSlider;
- (void)setProgressSlider:;
- (void)willDisplay;
- (id)initWithContext:viewController:;
- (id)bottomContainer;
- (void)setBottomContainer:;
+ (Class)aAWEBrandColorAdapterClass;
+ (Class)aAWETeenModeSettingsViewModelCommonAdapterClass;
@end
