@interface AWETemplateListTemplateInfoResponseModel : MTLModel
@property (nonatomic) NSString templateID;
@property (nonatomic) q appID;
@property (nonatomic) NSString regionKey;
@property (nonatomic) q templateType;
@property (nonatomic) NSString mediaID;
@property (nonatomic) NSString title;
@property (nonatomic) NSString templateDescription;
@property (nonatomic) q width;
@property (nonatomic) q height;
@property (nonatomic) NSString md5;
@property (nonatomic) NSString templateUri;
@property (nonatomic) NSDictionary templateCoverModel;
@property (nonatomic) NSArray tags;
@property (nonatomic) NSString extra;
@property (nonatomic) AWEImageTemplateExtraInfoModel imageTemplateExt;
@property (nonatomic) AWEVideoTemplateExtraInfoModel videoTemplateExt;
@property (nonatomic) q provider;
@property (nonatomic) BOOL isDownloaded;
@property (nonatomic) NSDictionary resourcesCache;
@property (nonatomic) NSString unzipPath;
@property (nonatomic) BOOL unzipPathCacheExist;
@property (nonatomic) BOOL resourcesCacheCacheExist;
@property (nonatomic) NSDictionary dictionaryValue;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setExtra:;
- (id)regionKey;
- (void)setRegionKey:;
- (id)imageTemplateExt;
- (id)templateCoverModel;
- (id)videoTemplateExt;
- (void)setImageTemplateExt:;
- (void)setVideoTemplateExt:;
- (void)setUnzipPath:;
- (void)setTemplateDescription:;
- (void)setTemplateUri:;
- (void)setTemplateCoverModel:;
- (id)templateCoverURLs;
- (id)templateUri;
- (id)templateDescription;
- (id)generatenNleResourceManager;
- (BOOL)unzipPathCacheExist;
- (BOOL)resourcesCacheCacheExist;
- (id)resourcesCache;
- (void)setResourcesCache:;
- (void)setUnzipPathCacheExist:;
- (void)setResourcesCacheCacheExist:;
- (id)tags;
- (void)setProvider:;
- (void)setHeight:;
- (void)setWidth:;
- (id)templateID;
- (id)extra;
- (void)setTemplateID:;
- (void)setTags:;
- (long long)appID;
- (long long)templateType;
- (long long)width;
- (void)setAppID:;
- (void).cxx_destruct;
- (id)title;
- (long long)height;
- (void)setTemplateType:;
- (long long)provider;
- (void)setTitle:;
- (BOOL)isHorizontal;
- (void)setMd5:;
- (id)md5;
- (BOOL)isDownloaded;
- (id)mediaID;
- (void)setMediaID:;
- (id)unzipPath;
- (void)setIsDownloaded:;
+ (id)imageTemplateExtJSONTransformer;
+ (id)videoTemplateExtJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
