@interface AWETheaterBannerSectionCell : UICollectionViewCell
@property (nonatomic) AWETheaterIndentBannerView bannerView;
@property (nonatomic) AWETheaterSectionModel sectionModel;
@property (nonatomic) AWETheaterPageContext context;
@property (nonatomic) @? nextLoopHandler;
@property (nonatomic) @? resetHandler;
@property (nonatomic) @? clickAction;
@property (nonatomic) @? tapVolumeButtonBlock;
@property (nonatomic) @? showVolumeButtonBlock;
@property (nonatomic) @? logExtraDict;
@property (nonatomic) @? lvideoLogExtraDict;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setLogExtraDict:;
- (void)duxGrid_viewDidChangeBreakPointFrom:toBreakPoint:;
- (id)logExtraDict;
- (id)clickAction;
- (void)setClickAction:;
- (long long)currentShowIndex;
- (void)updateCellPaymentWithModel:;
- (void)stopLiveBanner;
- (id)showVolumeButtonBlock;
- (id)tapVolumeButtonBlock;
- (void)trackCellWillDisappear;
- (void)setTapVolumeButtonBlock:;
- (void)setShowVolumeButtonBlock:;
- (id)currentSectionItem;
- (BOOL)currentShowIsVideo;
- (id)nextLoopHandler;
- (BOOL)isInCenterVisibleCell:;
- (long long)getCurrentStyle;
- (long long)duxIndentBannerNumberOfItem;
- (id)duxIndentBannerCell:cellForItemAtIndex:;
- (void)duxIndentBannerCell:didEndDisplayingCellAtIndex:;
- (void)duxIndentBannerCell:willDisplayCellAtIndex:;
- (void)configWithSectionModel:context:;
- (id)lvideoLogExtraDict;
- (void)setLvideoLogExtraDict:;
- (void)setNextLoopHandler:;
- (id)sectionModel;
- (void)play;
- (id)initWithFrame:;
- (void)setContext:;
- (void).cxx_destruct;
- (id)resetHandler;
- (void)setSectionModel:;
- (id)context;
- (void)stop;
- (void)pause;
- (void)setResetHandler:;
- (void)configureSubviews;
- (id)bannerView;
- (void)setBannerView:;
- (void)configureConstraints;
@end
