@interface AWETransformerGroupElement : AWETransformerBaseElement
@property (nonatomic) Q overflow;
@property (nonatomic) double scrollerVerticalSize;
@property (nonatomic) double scrollerHorizontalSize;
@property (nonatomic) Q flexDirection;
@property (nonatomic) Q justifyContent;
@property (nonatomic) Q alignItems;
@property (nonatomic) NSString gridTemplateColumns;
@property (nonatomic) NSString gridTemplateRows;
@property (nonatomic) NSString gridColumnGap;
@property (nonatomic) NSString gridRowGap;
@property (nonatomic) Q maxShowNum;
@property (nonatomic) double maxShowItemVisibleSpace;
@property (nonatomic) AWETransformerLayoutFlexAttributes flexLayoutAttribues;
@property (nonatomic) AWETransformerLayoutGridAttributes gridLayoutAttribues;
@property (nonatomic) AWETransformerLayoutCommonAttributes groupCommonLayoutAttributes;
@property (nonatomic) NSArray childElements;
@property (nonatomic) double timeFromParseToCreateElementTree;
- (void)setFlexDirection:;
- (void)setAlignItems:;
- (void)setJustifyContent:;
- (unsigned long long)maxShowNum;
- (void)setMaxShowNum:;
- (id)subElements;
- (unsigned long long)flexDirection;
- (id)commonLayoutAttribue;
- (void)renderElement;
- (id)flexLayoutAttribues;
- (id)gridLayoutAttribues;
- (void)clearLayoutInfo;
- (id)groupCommonLayoutAttributes;
- (void)setGroupCommonLayoutAttributes:;
- (void)setFlexLayoutAttribues:;
- (void)setGridLayoutAttribues:;
- (void)setChildElements:;
- (unsigned long long)alignItems;
- (BOOL)containerLynxElementWithCardType:;
- (double)scrollerHorizontalSize;
- (void)setScrollerHorizontalSize:;
- (double)scrollerVerticalSize;
- (void)setScrollerVerticalSize:;
- (unsigned long long)justifyContent;
- (id)gridRowGap;
- (void)setGridRowGap:;
- (id)gridColumnGap;
- (void)setGridColumnGap:;
- (id)gridTemplateRows;
- (void)setGridTemplateRows:;
- (id)gridTemplateColumns;
- (void)setGridTemplateColumns:;
- (double)maxShowItemVisibleSpace;
- (void)setMaxShowItemVisibleSpace:;
- (double)timeFromParseToCreateElementTree;
- (void)setTimeFromParseToCreateElementTree:;
- (void)layout;
- (id)childElements;
- (void)loadView;
- (void)updateLayout;
- (void).cxx_destruct;
- (unsigned long long)overflow;
- (void)setOverflow:;
+ (id)elementType;
@end
