@interface AWETeenFoldingLabel : YYLabel
@property (nonatomic) NSAttributedString originString;
@property (nonatomic) UIButton unfoldButton;
@property (nonatomic) UIButton foldButton;
@property (nonatomic) {CGSize=dd} layoutSize;
@property (nonatomic) double lineHeight;
@property (nonatomic) Q maxFoldLines;
@property (nonatomic) BOOL foldButtonWrap;
@property (nonatomic) @? didClickTail;
- (id)foldButton;
- (void)setFoldButton:;
- (id)didClickTail;
- (void)setMaxFoldLines:;
- (void)setFoldButtonWrap:;
- (void)setDidClickTail:;
- (id)unfoldButton;
- (void)setUnfoldButton:;
- (id)originString;
- (void)p_formatAttributedString:;
- (unsigned long long)maxFoldLines;
- (id)p_lastLineSizeForAttributeString:constraintSize:;
- (BOOL)foldButtonWrap;
- (void)p_unfoldIfNeeded;
- (void)p_foldIfNeeded;
- (void)setOriginString:;
- (void)clickUnfoldButton;
- (void)clickFoldButton;
- (id)layoutSize;
- (id)init;
- (id)attributedText;
- (void)setText:;
- (void)setPreferredMaxLayoutWidth:;
- (id)text;
- (void)setNumberOfLines:;
- (void)setAttributedText:;
- (void).cxx_destruct;
- (id)hitTest:withEvent:;
- (double)lineHeight;
- (void)setLayoutSize:;
- (void)setLineHeight:;
@end
