@interface AWETextEditViewController : UIViewController
@property (nonatomic) UITextView contentTextView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UITextView contentCalculateHeightTextView;
@property (nonatomic) AWEAnimatedButton idCopyButton;
@property (nonatomic) BOOL hasShownKeyboard;
@property (nonatomic) Q style;
@property (nonatomic) NSString preTitle;
@property (nonatomic) NSString contentText;
@property (nonatomic) NSString numberText;
@property (nonatomic) NSString tipText;
@property (nonatomic) NSString placeholder;
@property (nonatomic) BOOL emptyIsChanged;
@property (nonatomic) BOOL shouldSaveChange;
@property (nonatomic) @? exitBlock;
@property (nonatomic) UITextField contentTextField;
@property (nonatomic) UIView sepView;
@property (nonatomic) UILabel numberLabel;
@property (nonatomic) UILabel tipLabel;
@property (nonatomic) UITextView contentTextView;
@property (nonatomic) UIButton saveButton;
@property (nonatomic) UILabel preTitleLabel;
@property (nonatomic) UIButton deleteButton;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)deleteButtonClicked;
- (void)setStatusBarBackgroundColor:;
- (id)sepView;
- (void)setSepView:;
- (void)setContentTextView:;
- (id)contentTextView;
- (id)exitBlock;
- (void)setExitBlock:;
- (id)tipText;
- (void)setTipText:;
- (id)preTitle;
- (void)setPreTitle:;
- (void)setShouldSaveChange:;
- (id)preTitleLabel;
- (void)updateEditStyleWithShowKeyboard:;
- (BOOL)hasShownKeyboard;
- (void)setHasShownKeyboard:;
- (id)contentTextField;
- (BOOL)isSettingEnable;
- (id)idCopyButton;
- (void)p_finishEditing;
- (void)p_saveButtonClicked;
- (void)setEmptyIsChanged:;
- (void)setTipLabelForContentTextView;
- (BOOL)shouldSaveChange;
- (void)saveButtonClicked;
- (BOOL)emptyIsChanged;
- (void)updateEmptyNumberText;
- (void)editTextFieldDidChange:;
- (BOOL)isTextOverHeightLimit:;
- (void)editTextViewDidChange:;
- (id)contentCalculateHeightTextView;
- (void)idCopyButtonClicked;
- (void)p_deleteButtonClicked;
- (void)configWithStyle:preTitle:contentText:numberText:tipText:placeholder:emptyIsChanged:;
- (void)updateEditStyle;
- (void)updateCopyButtonIfNeeded;
- (void)setContentTextField:;
- (void)setPreTitleLabel:;
- (void)setContentCalculateHeightTextView:;
- (void)setIdCopyButton:;
- (BOOL)prefersStatusBarHidden;
- (void)viewWillDisappear:;
- (id)init;
- (void)textFieldDidEndEditing:;
- (void)setDeleteButton:;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)setPlaceholder:;
- (unsigned long long)style;
- (void)viewWillAppear:;
- (id)placeholder;
- (id)deleteButton;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)textFieldDidBeginEditing:;
- (void)setStyle:;
- (double)layoutManager:lineSpacingAfterGlyphAtIndex:withProposedLineFragmentRect:;
- (void)setTipLabel:;
- (BOOL)textView:shouldChangeTextInRange:replacementText:;
- (void)textViewDidBeginEditing:;
- (void)textViewDidChange:;
- (void)textViewDidEndEditing:;
- (id)tipLabel;
- (void)textFieldDidChange:;
- (void)setContentText:;
- (id)contentText;
- (void)_setupNavbar;
- (id)saveButton;
- (void)setSaveButton:;
- (void)setNumberLabel:;
- (void)_setUpUI;
- (id)numberLabel;
- (id)numberText;
- (void)setNumberText:;
@end
