@interface AWEUserLoginSMSStep1ViewController : AWEUserLoginBaseViewController
@property (nonatomic) AWEUserLoginSMSViewModel viewModel;
@property (nonatomic) UIView navigationBar;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIView bottomView;
@property (nonatomic) UIView protocolView;
@property (nonatomic) UIView phoneNumberInputView;
@property (nonatomic) AWEUserLoginErrorInfoLabel errorLabel;
@property (nonatomic) YYLabel passwordLoginButton;
- (id)pageBtm;
- (void)setupContainerView;
- (id)protocolView;
- (void)setProtocolView:;
- (id)phoneNumberInputView;
- (void)setPhoneNumberInputView:;
- (void)handleKeyboardWillChange:;
- (void)passwordLoginAction:;
- (id)passwordLoginButton;
- (void)setPasswordLoginButton:;
- (void)cursorFocusWhenAppear;
- (void)setupBgViewIfNeed;
- (void)setupLoginComponentView;
- (void)startBind;
- (void)updateBottomViewLayoutKeyboardShow:;
- (void)updatePasswordLoginButtonLayout;
- (id)navigationBar;
- (id)init;
- (id)viewModel;
- (void)viewDidLoad;
- (id)containerView;
- (void)viewDidDisappear:;
- (void)setContainerView:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)setNavigationBar:;
- (id)bottomView;
- (void)setupUI;
- (void)setBottomView:;
- (void)showError:;
- (void)hideError;
- (void)setupNavigationBar;
- (id)errorLabel;
- (void)setErrorLabel:;
@end
