@interface AWEUserProfileLocalNumManager : NSObject
@property (nonatomic) NSNumber likeNum;
@property (nonatomic) NSNumber postNum;
@property (nonatomic) NSNumber privateNum;
@property (nonatomic) NSNumber drafts;
@property (nonatomic) NSNumber forwardNum;
@property (nonatomic) NSNumber recycledWorksNum;
@property (nonatomic) NSNumber hasSoftDeleteForLaunchNum;
@property (nonatomic) NSDate lockLikeNumExpiryDate;
- (id)currentUserPrivateNum;
- (void)didChangeVideoPrivacy:;
- (void)didDeleteAweme:;
- (void)didPostAweme:;
- (BOOL)hasDraft;
- (id)currentUserLikeNum;
- (BOOL)isLockLikeNumUpdate;
- (void)updateUserLikeNum:;
- (void)lockLikeNum:;
- (void)resetAllNum;
- (id)lockLikeNumExpiryDate;
- (id)likeNum;
- (void)setLikeNum:;
- (void)setLockLikeNumExpiryDate:;
- (void)increaseUserLikeNum;
- (void)decreaseUserLikeNum;
- (id)currentUserPostNum;
- (void)increaseUserPostNum;
- (void)updateUserPostNum:;
- (void)decreaseUserForwardNum;
- (void)decreaseUserPostNum;
- (void)increaseDraft;
- (void)decreaseDraft;
- (void)updateUserDraftNum:;
- (void)increaseUserPostNumBy:;
- (id)cloudAlbumNum;
- (void)updateRecycledWorksNum:;
- (void)updateUserPrivateNum:shouldShowMixEntrance:;
- (void)updateCloudAlbumNum:;
- (void)updateUserPrivateNum:;
- (id)privateNum;
- (id)recycledWorksNum;
- (BOOL)hasRecycledWorks;
- (BOOL)hasSoftDeleteForLaunch;
- (void)updateUserForwardNum:;
- (void)increaseUserForwardNum;
- (void)increaseUserPrivateNum;
- (void)increaseRecycledWorksNum;
- (void)decreaseUserPrivateNum;
- (void)setPostNum:;
- (void)setDrafts:;
- (void)setForwardNum:;
- (id)postNum;
- (id)forwardNum;
- (id)drafts;
- (void)setPrivateNum:;
- (id)cloudAlbumStorageKey;
- (id)hasSoftDeleteForLaunchNum;
- (void)setRecycledWorksNum:;
- (void)setHasSoftDeleteForLaunchNum:;
- (id)currentUserPostAndDraftNum;
- (id)currentUserForwardNum;
- (id)init;
- (void).cxx_destruct;
+ (id)sharedInstance;
@end
