@interface AWEUserProfileTabModel : NSObject
@property (nonatomic) q profileTabType;
@property (nonatomic) NSString title;
@property (nonatomic) NSString selectedTitle;
@property (nonatomic) NSString backupTitle;
@property (nonatomic) BOOL lockIconVisible;
@property (nonatomic) BOOL shouldShowRedDot;
@property (nonatomic) NSString redDotContentString;
@property (nonatomic) NSString name;
@property (nonatomic) NSString nameEn;
@property (nonatomic) NSString url;
@property (nonatomic) NSNumber displayCount;
@property (nonatomic) NSString tabComponentType;
- (long long)profileTabType;
- (void)setShouldShowRedDot:;
- (BOOL)shouldShowRedDot;
- (id)nameEn;
- (void)setNameEn:;
- (void)setProfileTabType:;
- (id)tabComponentType;
- (void)setTabComponentType:;
- (BOOL)lockIconVisible;
- (void)setLockIconVisible:;
- (id)backupTitle;
- (void)setBackupTitle:;
- (id)redDotContentString;
- (void)setRedDotContentString:;
- (void)setDisplayCount:;
- (void)setUrl:;
- (void).cxx_destruct;
- (id)title;
- (id)displayCount;
- (void)setName:;
- (id)name;
- (id)url;
- (void)setTitle:;
- (id)selectedTitle;
- (void)setSelectedTitle:;
@end
