@interface AWEUserRecommendTableViewManager : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UITableView tableView;
@property (nonatomic) <AWEUserRecommendTableSectionProviderProtocol> sectionProvider;
@property (nonatomic) q recommendSection;
@property (nonatomic) AWEUserRecommendRefreshFooter footer;
@property (nonatomic) <AWEUserRecommendTableViewManagerDataSource> dataSource;
@property (nonatomic) <UITableViewDataSource> tableViewDataSource;
@property (nonatomic) <UITableViewDelegate> tableViewDelegate;
@property (nonatomic) AWERefreshFooter managedFooter;
@property (nonatomic) BOOL managedFooterHidden;
@property (nonatomic) double managedFooterInsetB;
@property (nonatomic) double recommendFooterInsetB;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)sectionProvider;
- (void)setSectionProvider:;
- (void)setTableViewDelegate:;
- (id)tableViewDelegate;
- (id)indexesForVisibleCellsForRecommendSectionProvider:;
- (id)visibleCellsForRecommendSectionProvider:;
- (id)cellForRecommendSectionProvider:atIndex:;
- (id)headerViewForRecommendSectionProvider:;
- (id)footerViewForRecommendSectionProvider:;
- (id)recommendSectionProvider:dequeueReusableCellWithIdentifier:;
- (id)recommendSectionProvider:dequeueReusableHeaderFooterViewWithIdentifier:;
- (void)recommendSectionProvider:insertRowsAtIndexes:animated:;
- (void)recommendSectionProvider:deleteRowsAtIndexes:animated:;
- (void)recommendSectionProvider:performBatchUpdates:completion:;
- (void)reloadRecommendSectionProvider:;
- (void)recommendSectionProviderWillBecomeEmpty:;
- (void)recommendSectionProviderDidBecomeEmpty:;
- (void)recommendSectionProviderDidBecomeNonEmpty:;
- (long long)recommendSection;
- (void)setManagedFooterHidden:;
- (id)managedFooter;
- (void)setManagedFooterInsetB:;
- (void)setRecommendFooterInsetB:;
- (id)initWithTableView:contextBuilder:;
- (id)initWithTableView:viewModel:;
- (BOOL)shouldHideManagedFooter;
- (double)recommendFooterInsetB;
- (double)managedFooterInsetB;
- (id)initWithTableView:sectionProvider:;
- (void)setRecommendSection:;
- (void)p_updateMJFooterIfNeeded;
- (BOOL)managedFooterHidden;
- (id)tableView:viewForHeaderInSection:;
- (id)footer;
- (id)tableView:cellForRowAtIndexPath:;
- (long long)tableView:numberOfRowsInSection:;
- (long long)numberOfSectionsInTableView:;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void)setTableView:;
- (id)tableView;
- (void)scrollViewDidScroll:;
- (void)scrollViewWillBeginDragging:;
- (void).cxx_destruct;
- (id)sectionIndexTitlesForTableView:;
- (double)tableView:heightForRowAtIndexPath:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void)setDataSource:;
- (double)tableView:heightForHeaderInSection:;
- (void)tableView:didEndDisplayingCell:forRowAtIndexPath:;
- (id)tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:;
- (id)dataSource;
- (void)setFooter:;
- (long long)tableView:sectionForSectionIndexTitle:atIndex:;
- (BOOL)tableView:canEditRowAtIndexPath:;
- (BOOL)tableView:canMoveRowAtIndexPath:;
- (void)tableView:commitEditingStyle:forRowAtIndexPath:;
- (void)tableView:didDeselectRowAtIndexPath:;
- (void)tableView:didEndDisplayingFooterView:forSection:;
- (void)tableView:didEndDisplayingHeaderView:forSection:;
- (void)tableView:didEndEditingRowAtIndexPath:;
- (id)tableView:editActionsForRowAtIndexPath:;
- (double)tableView:heightForFooterInSection:;
- (id)tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:;
- (void)tableView:moveRowAtIndexPath:toIndexPath:;
- (id)tableView:viewForFooterInSection:;
- (void)tableView:willBeginEditingRowAtIndexPath:;
- (void)tableView:willDisplayFooterView:forSection:;
- (void)tableView:willDisplayHeaderView:forSection:;
- (void)setTableViewDataSource:;
- (id)tableViewDataSource;
@end
