@interface AWEUserRecommendEmptyRecommendViewController : UIViewController
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView tipIconView;
@property (nonatomic) UILabel tipTitleLabel;
@property (nonatomic) UILabel tipSubstileLabel;
@property (nonatomic) NSString userID;
@property (nonatomic) q type;
@property (nonatomic) BOOL isPlayingAnimation;
@property (nonatomic) UIViewController<AWEUserRecommendViewControllerProtocol> userRecommendVC;
@property (nonatomic) UIView recommendView;
@property (nonatomic) NSDictionary extraDict;
@property (nonatomic) AWEUserModel user;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (id)extraDict;
- (void)setExtraDict:;
- (id)enterFromString;
- (id)recommendView;
- (void)setRecommendView:;
- (id)tipIconView;
- (void)setTipIconView:;
- (BOOL)hasRecommendData;
- (id)iconImageForEmptyType;
- (id)titleForEmptyType;
- (id)descriptionForEmptyType;
- (void)setIsPlayingAnimation:;
- (BOOL)isPlayingAnimation;
- (id)userRecommendVC;
- (id)p_recommendContext;
- (void)setUserRecommendVC:;
- (id)tipTitleLabel;
- (id)tipSubstileLabel;
- (BOOL)enableEmptyStyleOpt;
- (void)playRecommendViewAnimation:;
- (id)initWithUserID:type:extraDict:;
- (void)setTipTitleLabel:;
- (void)setTipSubstileLabel:;
- (id)user;
- (void)setUser:;
- (id)userID;
- (void)viewDidLoad;
- (id)containerView;
- (double)contentHeight;
- (long long)type;
- (void)setContainerView:;
- (void)setType:;
- (void).cxx_destruct;
- (void)setUserID:;
@end
