@interface AWEUserRecommendBigCardContainerView : UIView
@property (nonatomic) AWEUserRecommendBigCardViewModel viewModel;
@property (nonatomic) AWEUserRecommendBigCardView cardView;
@property (nonatomic) AWEUserRecommendBigCardFooterView footerView;
@property (nonatomic) AWEBinding currentModelBinding;
@property (nonatomic) AWEBinding preloadModelBinding;
@property (nonatomic) AWEBinding followStatusObserver;
@property (nonatomic) UIImageView animationImageView;
@property (nonatomic) UIView fadeContainerView;
@property (nonatomic) UIView gradientBGView;
@property (nonatomic) UIImageView defaultBGView;
@property (nonatomic) CAGradientLayer gradientBGLayer;
@property (nonatomic) CAGradientLayer shadowBGLayer;
@property (nonatomic) UIView slideUpHintView;
@property (nonatomic) BOOL isCardDisplaying;
@property (nonatomic) q lastSelectedAwemeCellIndex;
@property (nonatomic) UILongPressGestureRecognizer longPressGestureRecognizer;
@property (nonatomic) UIViewController<AWEAwemeLongPressModalViewControllerProtocol> longPressViewController;
@property (nonatomic) <AWEUserRecommendBigCardContainerViewDelegate> delegate;
@property (nonatomic) BOOL showsSlideUpHint;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)zoomTransitionStartViewForOffset:;
- (id)aAWEPadModuleAdapter;
- (void)configWithViewModel:;
- (id)aAWELiteUGSocialModuleAdapter;
- (void)setIsCardDisplaying:;
- (BOOL)isCardDisplaying;
- (id)longPressViewController;
- (void)setLongPressViewController:;
- (void)p_applicationDidBecomeActiveNotification:;
- (BOOL)showsSlideUpHint;
- (void)p_animateSlideUpHintView;
- (id)slideUpHintView;
- (void)setShowsSlideUpHint:;
- (void)p_longPress:;
- (BOOL)p_enableNewPressPanel;
- (void)setSlideUpHintView:;
- (double)p_footerViewBottomPadding;
- (void)setLastSelectedAwemeCellIndex:;
- (long long)lastSelectedAwemeCellIndex;
- (void)setFadeContainerView:;
- (id)fadeContainerView;
- (id)gradientBGView;
- (id)defaultBGView;
- (void)configAndDisplayCell;
- (id)currentModelBinding;
- (void)setCurrentModelBinding:;
- (id)followStatusObserver;
- (void)setFollowStatusObserver:;
- (id)gradientBGLayer;
- (id)shadowBGLayer;
- (void)setGradientBGView:;
- (void)setDefaultBGView:;
- (void)setGradientBGLayer:;
- (void)setShadowBGLayer:;
- (double)bottomUnsafeAreaHeight;
- (id)preloadModelBinding;
- (void)setPreloadModelBinding:;
- (void)p_updateFootView;
- (id)aAWEUserRecommendBigCardContainerViewCommonAdapter;
- (void)updateFollowButtonTextWithUser:;
- (void)animationDidStop:finished:;
- (void)play;
- (void)setFooterView:;
- (id)delegate;
- (id)footerView;
- (id)viewModel;
- (id)initWithFrame:;
- (void)setLongPressGestureRecognizer:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (id)longPressGestureRecognizer;
- (void)reset;
- (void)setDelegate:;
- (void)viewDidAppear;
- (void)pause;
- (id)cardView;
- (void)setCardView:;
- (void)viewDidDisappear;
- (void)didEndDisplaying;
- (void)willDisplay;
- (id)animationImageView;
- (void)setAnimationImageView:;
+ (Class)aAWEPadModuleAdapterClass;
+ (Class)aAWELiteUGSocialModuleAdapterClass;
+ (Class)aAWEUserRecommendBigCardContainerViewCommonAdapterClass;
@end
