@interface AWEVideoIntelligentChapterLogParam : MTLModel
@property (nonatomic) double totalCost;
@property (nonatomic) double clientCost;
@property (nonatomic) double getTokenCost;
@property (nonatomic) double extractAudioCost;
@property (nonatomic) double extractFrameCost;
@property (nonatomic) double uploadAudioTosCost;
@property (nonatomic) double uploadFrameTosCost;
@property (nonatomic) double uploadAudioTosUriCost;
@property (nonatomic) double uploadFrameTosUriCost;
@property (nonatomic) double pullingCost;
@property (nonatomic) q videoDuration;
@property (nonatomic) q retryType;
@property (nonatomic) q resultType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setRetryType:;
- (void)setExtractFrameCost:;
- (void)setExtractAudioCost:;
- (void)setUploadFrameTosCost:;
- (void)setUploadAudioTosCost:;
- (void)setPullingCost:;
- (void)setGetTokenCost:;
- (void)setUploadFrameTosUriCost:;
- (void)setUploadAudioTosUriCost:;
- (void)setClientCost:;
- (double)clientCost;
- (double)getTokenCost;
- (double)extractAudioCost;
- (double)extractFrameCost;
- (double)uploadAudioTosCost;
- (double)uploadFrameTosCost;
- (double)uploadAudioTosUriCost;
- (double)uploadFrameTosUriCost;
- (double)pullingCost;
- (long long)retryType;
- (void)setResultType:;
- (long long)resultType;
- (long long)videoDuration;
- (void)setVideoDuration:;
- (void)setTotalCost:;
- (double)totalCost;
+ (id)JSONKeyPathsByPropertyKey;
@end
