@interface AWEVSFormatTabLatestModel : NSObject
@property (nonatomic) NSString episodeID;
@property (nonatomic) NSString currentPeriod;
@property (nonatomic) NSString watchedPeriodText;
@property (nonatomic) double watchDuration;
@property (nonatomic) double watchRatio;
@property (nonatomic) NSString seasonID;
@property (nonatomic) NSString itemID;
@property (nonatomic) NSString roomID;
@property (nonatomic) NSString vsEpisodeType;
@property (nonatomic) NSString vsEpisodeSubType;
@property (nonatomic) NSString authorID;
@property (nonatomic) Q directionType;
- (void)setDirectionType:;
- (void)setEpisodeID:;
- (double)watchDuration;
- (void)setWatchDuration:;
- (double)watchRatio;
- (void)setWatchedPeriodText:;
- (void)setWatchRatio:;
- (void)setSeasonID:;
- (void)setVsEpisodeType:;
- (void)setVsEpisodeSubType:;
- (id)seasonID;
- (id)vsEpisodeType;
- (id)vsEpisodeSubType;
- (id)watchedPeriodText;
- (id)itemID;
- (void)setItemID:;
- (id)roomID;
- (void).cxx_destruct;
- (void)setRoomID:;
- (id)currentPeriod;
- (void)setCurrentPeriod:;
- (id)authorID;
- (void)setAuthorID:;
- (id)episodeID;
- (unsigned long long)directionType;
@end
