@interface AWEVisionPhotoTools : NSObject
@property (nonatomic) ACCScanPhotoServiceImp scanImp;
@property (nonatomic) @? scanResultCompleted;
@property (nonatomic) @? qrCodeScanResultCompleted;
@property (nonatomic) @? scanAnythingResultCompleted;
@property (nonatomic) UIView<ACCTextLoadingViewProtcol> loadingView;
@property (nonatomic) BOOL handleCancelLoading;
@property (nonatomic) BOOL alreadyJump;
@property (nonatomic) double begainScanPictureInterval;
@property (nonatomic) UIImage scanImage;
@property (nonatomic) Q scanImageType;
@property (nonatomic) AWEVisionCameraGlobalDataModel globalData;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) BOOL isMultiCodeAlgorithm;
@property (nonatomic) ACCPhotoScanQRCodePerformanceTimestamp scanQRCodePerformanceTimestamp;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setEnterFrom:;
- (void)setEnterMethod:;
- (id)enterMethod;
- (id)enterFrom;
- (id)globalData;
- (void)setGlobalData:;
- (void)setIsMultiCodeAlgorithm:;
- (id)startQrCodeScanWithImage:supportMulti:showLoading:;
- (void)startQrCodeScanWithImage:showLoading:completed:;
- (BOOL)handleCancelLoading;
- (void)setHandleCancelLoading:;
- (id)scanQRCodePerformanceTimestamp;
- (void)setScanQRCodePerformanceTimestamp:;
- (void)setAlreadyJump:;
- (id)scanImp;
- (void)setScanImageType:;
- (void)setScanImage:;
- (void)setBegainScanPictureInterval:;
- (void)setScanResultCompleted:;
- (void)setScanAnythingResultCompleted:;
- (void)setQrCodeScanResultCompleted:;
- (unsigned long long)scanImageType;
- (void)pictureQrcodeScanMonitor:;
- (double)begainScanPictureInterval;
- (id)scanImage;
- (BOOL)isMultiCodeAlgorithm;
- (BOOL)alreadyJump;
- (id)qrCodeScanResultCompleted;
- (id)scanResultCompleted;
- (id)scanAnythingResultCompleted;
- (void)setScanImp:;
- (void)dealloc;
- (void)setLoadingView:;
- (id)loadingView;
- (void).cxx_destruct;
+ (id)scaledImageToMax1080WithImage:;
@end
