@interface AWEVideoCoverImageTemplateListContentView : UIView
@property (nonatomic) UICollectionView templateCollectionView;
@property (nonatomic) UICollectionViewFlowLayout flowLayout;
@property (nonatomic) AWENewVideoCoverEditTemplateViewModel viewModel;
@property (nonatomic) NSDictionary showModelHastracked;
@property (nonatomic) NSString currentEnterType;
@property (nonatomic) <AWEVideoCoverImageTemplateListContentViewDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_setupUI;
- (void)p_setupConstraint;
- (void)scrollToIndexPath:animated:;
- (void)setCurrentEnterType:;
- (id)currentEnterType;
- (void)p_trackVisibleTemplateCell;
- (void)templateApplyTemplateSuccessForIndexPath:;
- (void)setShowModelHastracked:;
- (void)p_updateTabSelection:;
- (void)p_viewStopScrolling:;
- (id)visibleTemplateCellIndexPaths;
- (id)showModelHastracked;
- (BOOL)needTemplateHistory;
- (void)cellShowComplianceNotificationAndAuthorInfoAndClearBtnStatusWith:;
- (void)cell:didSelectForIndexPath:model:;
- (void)setTemplateCollectionView:;
- (id)templateCollectionView;
- (void)historyCellShowComplianceNotificationAndAuthorInfoAndClearBtnStatusWith:;
- (void)historyCell:didEndDisplayAtIndexPath:model:;
- (void)historyCell:didSelectForIndexPath:model:;
- (void)historyCellForNextAction:;
- (void)cell:didEndDisplayAtIndexPath:model:;
- (void)cellForNextAction:;
- (void)p_trackTemplateWhenShowsWithIndexPath:;
- (void)templateImageDoSelectForIndexPath:isHistory:;
- (void)p_trackTemplateShowWith:model:;
- (void)trackVisibleTemplateCell;
- (void)markEnterType:atIndex:;
- (void)reloadData;
- (id)collectionView:layout:referenceSizeForHeaderInSection:;
- (id)delegate;
- (id)collectionView:cellForItemAtIndexPath:;
- (long long)numberOfSectionsInCollectionView:;
- (id)viewModel;
- (void)scrollViewDidScroll:;
- (void)scrollViewDidEndDecelerating:;
- (void)setViewModel:;
- (void).cxx_destruct;
- (long long)collectionView:numberOfItemsInSection:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void)scrollViewDidEndScrollingAnimation:;
- (void)setDelegate:;
- (id)flowLayout;
- (void)setFlowLayout:;
- (id)initWithFrame:viewModel:;
@end
