@interface AALocalContactInfo : NSObject
@property (nonatomic) NSString handle;
@property (nonatomic) NSString fullName;
@property (nonatomic) NSString firstName;
@property (nonatomic) NSString lastName;
@property (nonatomic) NSNumber familyDSID;
@property (nonatomic) NSString familyMemberType;
@property (nonatomic) BOOL isChild;
@property (nonatomic) NSData imageData;
@property (nonatomic) q contactType;
@property (nonatomic) NSUUID custodianID;
@property (nonatomic) q trustedContactStatus;
@property (nonatomic) <AAInheritanceContactInfo> inheritanceContactInfo;
- (id)fullName;
- (void)setImageData:;
- (id)imageData;
- (id)handle;
- (id)firstName;
- (id)lastName;
- (id)initWithCoder:;
- (id)displayName;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (BOOL)isEqual:;
- (BOOL)isChild;
- (id)copyWithZone:;
- (void)setContactType:;
- (long long)contactType;
- (id)custodianID;
- (void)setCustodianID:;
- (id)initWithHandle:contact:;
- (id)initWithFamilyDSID:firstName:lastName:fullName:appleID:familyMemberType:isChild:;
- (id)detailsText;
- (BOOL)isFamilyMember;
- (id)_fullNameFromFirstName:lastName:;
- (BOOL)_isEqualToLocalContact:;
- (id)_detailsTextForContactType;
- (id)familyDSID;
- (id)familyMemberType;
- (long long)trustedContactStatus;
- (void)setTrustedContactStatus:;
- (id)inheritanceContactInfo;
- (void)setInheritanceContactInfo:;
+ (BOOL)supportsSecureCoding;
@end
