@interface ABBufferQueryCursor : NSObject
@property (nonatomic) NSMutableData mutableData;
@property (nonatomic) NSMutableSet contactIdentifiers;
@property (nonatomic) NSMutableDictionary matchInfo;
@property (nonatomic) ^{sqlite3_blob=} incompleteBlob;
@property (nonatomic) Q blobBytesWritten;
@property (nonatomic) Q blobLength;
@property (nonatomic) q currentMultivalue;
@property (nonatomic) BOOL hasFoundAnyImageDataForCurrentContact;
@property (nonatomic) q resumeToken;
@property (nonatomic) NSInteger currentMultivalueIdentifier;
@property (nonatomic) NSInteger currentPropertyID;
@property (nonatomic) NSInteger currentRecordID;
@property (nonatomic) NSData currentRecordIndividualUniqueIDAuditData;
@property (nonatomic) NSData currentRecordLinkedUniqueIDAuditData;
@property (nonatomic) Q maxBufferSize;
@property (nonatomic) Q maxContactsPerBatch;
@property (nonatomic) Q countOfContactsInBuffer;
@property (nonatomic) ABBufferQuery query;
@property (nonatomic) CNManagedConfiguration managedConfiguration;
@property (nonatomic) NSInteger multivaluePropertyIDColumn;
@property (nonatomic) NSInteger multivalueIdentifierColumn;
@property (nonatomic) NSInteger multivalueUUIDColumn;
@property (nonatomic) NSInteger multivalueValueColumn;
@property (nonatomic) NSInteger multivalueLabelColumn;
@property (nonatomic) NSInteger multivalueEntryKeyColumn;
@property (nonatomic) NSInteger multivalueEntryValueColumn;
@property (nonatomic) NSInteger contactLinkUUIDColumn;
@property (nonatomic) NSInteger contactPreferredForImageColumn;
@property (nonatomic) NSInteger personLinkColumn;
- (id)contactIdentifiers;
- (id)currentRecordLinkedUniqueIDAuditData;
- (id)managedConfiguration;
- (void)setMultivalueLabelColumn:;
- (unsigned long long)blobBytesWritten;
- (void)setMutableData:;
- (int)multivalueEntryValueColumn;
- (void)setContactLinkUUIDColumn:;
- (void)dealloc;
- (id)mutableData;
- (int)multivalueUUIDColumn;
- (int)multivalueValueColumn;
- (void)setManagedConfiguration:;
- (long long)resumeToken;
- (void)setContactPreferredForImageColumn:;
- (void)setMatchInfo:;
- (void)setMultivalueEntryValueColumn:;
- (void)setHasFoundAnyImageDataForCurrentContact:;
- (void)setMultivalueValueColumn:;
- (int)multivalueIdentifierColumn;
- (void)setCurrentMultivalue:;
- (long long)currentMultivalue;
- (id)query;
- (unsigned long long)maxContactsPerBatch;
- (void)setMultivaluePropertyIDColumn:;
- (unsigned long long)maxBufferSize;
- (id)incompleteBlob;
- (void)setResumeToken:;
- (int)contactLinkUUIDColumn;
- (unsigned long long)blobLength;
- (void)setCountOfContactsInBuffer:;
- (id)initWithQuery:batchSize:;
- (void)setMultivalueIdentifierColumn:;
- (int)currentPropertyID;
- (void)setCurrentMultivalueIdentifier:;
- (void)setBlobLength:;
- (void)setMultivalueEntryKeyColumn:;
- (void)setMaxContactsPerBatch:;
- (int)personLinkColumn;
- (void)setMaxBufferSize:;
- (BOOL)hasFoundAnyImageDataForCurrentContact;
- (void)setCurrentPropertyID:;
- (int)contactPreferredForImageColumn;
- (int)multivaluePropertyIDColumn;
- (id)matchInfo;
- (void)fetchNextBatchWithReply:;
- (id)currentRecordIndividualUniqueIDAuditData;
- (int)multivalueEntryKeyColumn;
- (int)currentMultivalueIdentifier;
- (void)setBlobBytesWritten:;
- (id)initWithAddressBook:predicate:propertyIdentifierSet:includeLinkedContacts:sortOrder:suggestedContactsPerBatch:managedConfiguration:identifierAuditMode:;
- (void)setCurrentRecordIndividualUniqueIDAuditData:;
- (void)setCurrentRecordID:;
- (void)setCurrentRecordLinkedUniqueIDAuditData:;
- (void)setIncompleteBlob:;
- (int)currentRecordID;
- (void)setContactIdentifiers:;
- (void)setPersonLinkColumn:;
- (void)setMultivalueUUIDColumn:;
- (unsigned long long)countOfContactsInBuffer;
- (int)multivalueLabelColumn;
@end
