@interface ABNewPersonViewController : UIViewController
@property (nonatomic) CNContactViewController cnContactViewController;
@property (nonatomic) ^v parentSource;
@property (nonatomic) CNContact mergeContact;
@property (nonatomic) BOOL showsCancelButton;
@property (nonatomic) <ABNewPersonViewControllerDelegate> newPersonViewDelegate;
@property (nonatomic) r^v addressBook;
@property (nonatomic) r^v displayedPerson;
@property (nonatomic) r^v parentGroup;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)showsCancelButton;
- (id)init;
- (void)dealloc;
- (void)setEditing:animated:;
- (void)setShowsCancelButton:;
- (void)save:;
- (id)addressBook;
- (void)viewDidAppear:;
- (void)setAddressBook:;
- (void)loadView;
- (id)preferredContentSize;
- (void)contactViewController:didCompleteWithContact:;
- (id)initWithStyle:;
- (id)parentGroup;
- (void)setParentGroup:;
- (id)initWithNibName:bundle:style:;
- (id)newPersonViewDelegate;
- (void)setNewPersonViewDelegate:;
- (id)displayedPerson;
- (void)setDisplayedPerson:;
- (void)loadContactViewController;
- (void)setSavesNewContactOnSuspend:;
- (BOOL)savesNewContactOnSuspend;
- (id)cnContactViewController;
- (void)setCnContactViewController:;
- (id)parentSource;
- (void)setParentSource:;
- (id)mergeContact;
- (void)setMergeContact:;
@end
