@interface ABUAdSDKManager : NSObject
@property (nonatomic) ABUUserConfig userConfig;
@property (nonatomic) NSString appID;
@property (nonatomic) ABUUserInfoForSegment userInfoForSegment;
@property (nonatomic) I logLevel;
@property (nonatomic) NSDictionary userDefineInfoForSegment;
@property (nonatomic) NSDictionary userCustomInfoForSegment;
@property (nonatomic) NSString userCustomInfoStringForSegment;
@property (nonatomic) @? userSetCompletionHandler;
@property (nonatomic) NSString startAppID;
@property (nonatomic) double sdkInitTimestamp;
@property (nonatomic) double initTimestamp;
@property (nonatomic) q initStartTime;
@property (nonatomic) double initStartTimeForDuration;
- (void)configLoadForLocalDidSuccess_V2;
- (void)setupAdnSDKWithConfig:complete:;
- (void)setupUserConfig;
- (void)_configLoadDidFailedWithError_V2:;
- (void)_configLoadDidSuccessViaLocal:;
- (void)_configLoadDidSuccess_V2;
- (void)_giveSDKInitFailWithError:;
- (void)_setupAdnSDKsWithConfigs:complete:;
- (void)_trackSDKInit;
- (void)_trackSDKInitEndWithLocal:andAdnInitInfo:;
- (void)_tryGiveSDKInitSuccess;
- (void)_tryGiveSDKInitSuccess_V2;
- (void)_updatePC:;
- (void)_updateRulesWithConfig:;
- (long long)archiveSDKInitTimestamp;
- (void)configDidInitialize;
- (void)configLoadDidFailedWithError:;
- (void)configLoadDidSuccess;
- (void)configLoadForLocalDidFailed_V2;
- (void)configLoadForServerDidFailed_V2WithError:;
- (void)configLoadForServerDidSuccess_V2;
- (void)delayReportSDKInit;
- (long long)initStartTime;
- (double)initStartTimeForDuration;
- (double)initTimestamp;
- (void)registerAppID:;
- (double)sdkInitTimestamp;
- (void)setInitStartTime:;
- (void)setInitStartTimeForDuration:;
- (void)setInitTimestamp:;
- (void)setSdkInitTimestamp:;
- (void)setStartAppID:;
- (void)setUserConfig:;
- (void)setUserCustomInfoForSegment:;
- (void)setUserCustomInfoStringForSegment:;
- (void)setUserDefineInfoForSegment:;
- (void)setUserInfoForSegment:;
- (void)setUserSetCompletionHandler:;
- (void)setupAPMConfig;
- (void)setupAdActionManager;
- (void)setupAdnDetectManager;
- (BOOL)setupAdnSDKWithConfigSYNC:;
- (void)setupApplogConfig;
- (void)setupLogConfigViaConfig;
- (void)setupModuleControl;
- (void)setupPangleSDK;
- (void)setupRewardAgainShowCount;
- (void)setupSDKConfig;
- (void)setupTNCConfig;
- (void)setupTrackerConfig;
- (void)setupUpperDetectManager;
- (id)startAppID;
- (void)trackSDKInit;
- (void)trackSDKInitEndWithLocal:andAdnInitInfo:;
- (long long)unarchiveSDKInitTimestamp;
- (id)userConfig;
- (id)userCustomInfoForSegment;
- (id)userCustomInfoStringForSegment;
- (id)userDefineInfoForSegment;
- (id)userInfoForSegment;
- (id)userSetCompletionHandler;
- (id)init;
- (void)setLogLevel:;
- (void)setAppID:;
- (id)_serviceName;
- (unsigned int)logLevel;
- (id)appID;
- (void).cxx_destruct;
- (void)_setup;
- (id)sdkVersion;
- (void)_appWillEnterForeground:;
- (void)setupNotifications;
+ (void)reportBackStageWithDuration:;
+ (id)getCustomUserInfoJsonForSegment;
+ (void)setThemeStatus:;
+ (id)ssAppID;
+ (void)_cannotCallConfigMethodAfterSetupCheck:;
+ (id)_configObservers;
+ (void)abTest_ifUseNewSdkinitWithOldA:newB:;
+ (void)addConfigLoadSuccessObserver:withAction:;
+ (BOOL)configDidLoad;
+ (id)extraDeviceMap;
+ (long long)getAdTypeWithRitId:;
+ (id)getCustomUserInfoDicForSegment;
+ (id)getGMSDKExtraInfo;
+ (long long)getSDKInitTimestamp;
+ (id)getUserInfoDicForSegment;
+ (void)initSDKWithAppId:config:;
+ (void)initSDKWithAppId:config:asyncCompletionHandler:;
+ (BOOL)isValidRitId:;
+ (id)msdkSessionID;
+ (void)notifyConfigObservers;
+ (void)preloadAdsWithInfos:andInterval:andConcurrent:;
+ (void)setCustomIDFA:;
+ (void)setExtDeviceData:;
+ (void)setLoglevel:language:;
+ (void)setUserInfoForSegment:;
+ (long long)themeStatus;
+ (void)updateExtraDeviceMap:;
+ (id)sharedInstance;
+ (id)SDKVersion;
+ (void)setAppID:;
+ (void)setup;
+ (id)appID;
@end
