@interface ABUBaseAd : NSObject
@property (nonatomic) double mediationFillTimestamp;
@property (nonatomic) Q controlStatus;
@property (nonatomic) ABUUValueRule uvalueRule;
@property (nonatomic) NSMutableDictionary policyResult;
@property (nonatomic) BOOL needHandleCacheTimeout;
@property (nonatomic) NSArray reuseIdentifierFactors;
@property (nonatomic) UIViewController viewController;
@property (nonatomic) @? completeCallback;
@property (nonatomic) BOOL preloadCacheMode;
@property (nonatomic) NSString linkID;
@property (nonatomic) NSMutableDictionary params;
@property (nonatomic) BOOL isPreloadWhenShow;
@property (nonatomic) NSDictionary preloadInfo;
@property (nonatomic) NSString rit;
@property (nonatomic) NSString scenarioID;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) BOOL bidNotify;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q requestType;
@property (nonatomic) Q expectAdCount;
- (void)adViewDidClick:;
- (void)adViewWillShow:;
- (void)configLoadForLocalDidSuccess_V2;
- (id)getShowEcpmInfo;
- (void)setPreloadInfo:;
- (void)updateWhenClick;
- (void)adViewDidClose:;
- (id)resultForPolicy;
- (id)rit;
- (void)_adLoadDidSuccess;
- (id)_adReuseIdentifier;
- (void)_dealBaseActionWhenAdShowCalling:;
- (void)_dealBaseActionWhenAdShowListenCalling:;
- (BOOL)_enablePreloadCacheWithType:andAd:;
- (BOOL)_enablePreloadWithAd:enablePreloadCache:;
- (void)_removeFromHandleLoadPool;
- (void)_trackBiddingAdmCacheWithMediaSlotConfig:package:;
- (void)_trackGetConfigError:backup:;
- (void)_trackMediaCacheSuccessWithMediaSlotConfig:package:isMock:;
- (void)_trackMediaClickListenWithMediaSlotConfig:andPackage:;
- (void)_trackMediaShowFailListenWithAdPackage:andAdState:andError:;
- (void)_trackMediaShowFailWithInfo:andError:carousel:;
- (void)_trackMediaShowIsReadyWithAllLoadedAdInfo:andReadyShowAd:withError:;
- (void)_trackMediaShowListenWithMediaSlotConfig:andPackage:isMock:;
- (void)_trackMediaShowWithMediaSlotConfig:andPackage:isMock:;
- (void)_trackMediaWillShow:;
- (void)_trackMediationRequestWithError:andNextLinkID:;
- (void)_trackTotalLoadFail:andNextLinkID:;
- (void)adCustomTokensInfoDidCollected:andResumeHandler:;
- (void)adLoadDidFailedWithError:;
- (void)adLoadDidSuccess;
- (id)adPackageWithAdapter:;
- (void)adViewCallAdnShow:;
- (void)adViewCallAdnShowFailListenWithAd:andAdState:andError:;
- (void)adViewDidDownloadVideoWithAdPackage:;
- (void)adViewDidShow:;
- (void)adViewShowFailWithInfo:andError:;
- (void)adViewShowFailWithInfo:andError:carousel:;
- (void)addParam:withKey:;
- (void)addToHandleLoadPool;
- (void)addToHandleShowPoolForView:;
- (void)adnAdDidFinishLoad:error:;
- (BOOL)allowAdapterCallbackShow;
- (BOOL)bidNotify;
- (id)cacheRitList;
- (id)canShowForMediationControl;
- (id)checkPreloadCacheExistWithWaterfall:errorType:;
- (id)completeCallback;
- (void)configLoadForLocalDidFailed_V2;
- (void)configPreviewAdInfos:;
- (id)createWaterfallFailedWithLoadConfig:;
- (void)detectAdDelegate;
- (BOOL)didFinishAdnPreload;
- (BOOL)didFinishPreloadCache;
- (BOOL)enableCurrentAdnPreload;
- (BOOL)enablePreloadCache;
- (BOOL)enablePreloadExtra;
- (BOOL)enableReload;
- (BOOL)enableSetCountForPlatform;
- (void)ex_loadAdData;
- (unsigned long long)expectAdCount;
- (id)extraDataWithPackage:;
- (id)getAdLoadInfoList;
- (id)getAdNetworkPlatformName;
- (id)getAdNetworkRitId;
- (id)getCBE;
- (id)getCurrentBestEcpmInfo;
- (id)getMediaExtraInfo;
- (id)getPreEcpm;
- (id)initWithMediationRit:;
- (BOOL)isAdnPreloadWithAd:;
- (BOOL)isLoadViaMediation;
- (BOOL)isPreloadWhenShow;
- (long long)isRepeatClickWithAd:;
- (long long)isRepeatShowWithAd:;
- (void)loadAdData;
- (void)loadAdDataWithConfig:;
- (void)loadAdDataWithMediaSlotConfigIDs:sign:;
- (id)loadPriceOfTargetPackage:;
- (double)mediationFillTimestamp;
- (unsigned long long)mediationReqTypeWithError:;
- (unsigned long long)moduleControl;
- (id)multiBiddingEcpmInfos;
- (BOOL)needHandleCacheTimeout;
- (id)policyResult;
- (id)preloadAdWithType:;
- (void)preloadByUser;
- (BOOL)preloadCacheMode;
- (id)preloadInfo;
- (void)removeFromHandleLoadPool;
- (void)removeFromHandleShowPool;
- (long long)requestStateFromType:;
- (id)reuseIdentifierFactors;
- (void)setBidNotify:;
- (void)setCompleteCallback:;
- (void)setDidFinishAdnPreload:;
- (void)setDidFinishPreloadCache:;
- (void)setExpectAdCount:;
- (void)setIsPreloadWhenShow:;
- (void)setMediationFillTimestamp:;
- (void)setPolicyResult:;
- (void)setScenarioID:;
- (void)setUvalueRule:;
- (BOOL)shouldStartLoadAd:;
- (id)targetPackage;
- (void)trackMediaCacheSuccessWithPackage:isMock:;
- (void)trackMediaShowIsReadyWithAllLoadedAdInfo:andReadyShowAd:withError:;
- (void)updatePerformWithAd:andType:;
- (void)updateWhenCloseWithAd:;
- (void)updateWhenShow;
- (id)uvalueRule;
- (void)videoCacheDidTimeout;
- (id)viewControllerForPresentingModalView;
- (void)waterfall:didCollectedAdsTokens:andResumeHandler:;
- (void)waterfall:didLoadMediaAd:withAdapter:;
- (void)waterfall:loadFailedMediaAdWithError:;
- (void)waterfall:loadFailedWithError:;
- (void)waterfall:willStartLoadWithParams:error:;
- (void)waterfallDidLoadSuccess:;
- (id)waterfallFillFailMessages;
- (long long)requestType;
- (BOOL)isLoading;
- (void)setRequestType:;
- (id)init;
- (void)dealloc;
- (void)setViewController:;
- (int)logType;
- (long long)adType;
- (id)scenarioID;
- (id)viewController;
- (void).cxx_destruct;
- (id)params;
- (id)linkID;
- (void)setControlStatus:;
- (unsigned long long)controlStatus;
- (void)setParams:;
+ (id)adHandleLoadPool;
+ (id)adHandleShowPool;
+ (void)removeFromHandleShowPoolForView:;
@end
