@interface ABUCsjRewardedVideoAdapter : NSObject
@property (nonatomic) BUNativeExpressRewardedVideoAd expressRvAd;
@property (nonatomic) BOOL hasVideoDownLoad;
@property (nonatomic) RewardVideoAgainDelegate rewardVideoAgainDelegate;
@property (nonatomic) NSMutableDictionary pangleExtroInfoMap;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <BUMCustomRewardedVideoAdapterBridge> bridge;
@property (nonatomic) NSDictionary extroInfoMap;
@property (nonatomic) BOOL isCustomAdapter;
@property (nonatomic) <BUMCustomConfigAdapter> configAdapter;
- (void)_fillInfo:rewardedVideoModel:;
- (void)_setupWithWithSlotID:andParameter:;
- (id)_transitionMediaExt:;
- (BOOL)enablePreloadWhenCurrentIsDisplay;
- (id)expressRvAd;
- (id)extroInfoMap;
- (id)getAdCreativeToken;
- (double)getExpireTimestamp;
- (BOOL)hasVideoDownLoad;
- (void)loadRewardedVideoAdWithSlotID:andParameter:;
- (BOOL)materialMetaIsFromPreload;
- (id)mediatedAdStatus;
- (void)nativeExpressRewardedVideoAd:didFailWithError:;
- (void)nativeExpressRewardedVideoAdCallback:withType:;
- (void)nativeExpressRewardedVideoAdDidClick:;
- (void)nativeExpressRewardedVideoAdDidClickSkip:;
- (void)nativeExpressRewardedVideoAdDidClose:;
- (void)nativeExpressRewardedVideoAdDidCloseOtherController:interactionType:;
- (void)nativeExpressRewardedVideoAdDidDownLoadVideo:;
- (void)nativeExpressRewardedVideoAdDidLoad:;
- (void)nativeExpressRewardedVideoAdDidPlayFinish:didFailWithError:;
- (void)nativeExpressRewardedVideoAdDidVisible:;
- (void)nativeExpressRewardedVideoAdServerRewardDidSucceed:verify:;
- (void)nativeExpressRewardedVideoAdViewRenderFail:error:;
- (void)nativeExpressRewardedVideoAdViewRenderSuccess:;
- (void)nativeExpressRewardedVideoAdWillClose:;
- (void)nativeExpressRewardedVideoAdWillVisible:;
- (id)pangleExtroInfoMap;
- (id)rewardVideoAgainDelegate;
- (id)serverBiddingTokenWithParams:error:;
- (void)setHasVideoDownLoad:;
- (void)setPangleExtroInfoMap:;
- (void)setRewardVideoAgainDelegate:;
- (BOOL)showAdFromRootViewController:parameter:;
- (void).cxx_destruct;
@end
