@interface ABUInterstitialProAd : ABUBaseAd
@property (nonatomic) {CGSize=dd} sizeForInterstitial;
@property (nonatomic) BOOL hasShown;
@property (nonatomic) BOOL didDealVideoCache;
@property (nonatomic) BOOL didDealLoad;
@property (nonatomic) ABUInterstitialProCarouselManager carouselManager;
@property (nonatomic) <ABUInterstitialProAdDelegate> delegate;
@property (nonatomic) ABURewardedVideoModel rewardModel;
@property (nonatomic) BOOL mutedIfCan;
@property (nonatomic) BOOL isReady;
@property (nonatomic) BOOL materialMetaIsFromPreload;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)getShowEcpmInfo;
- (void)setDidDealLoad:;
- (id)carouselManager;
- (void)fullscreenVideoAdRenderSuccess:;
- (void)setRewardModel:;
- (void)_handleAdClick;
- (void)_handleAdClickSkip;
- (void)_handleAdClose;
- (void)_handleAdDidShowFailed:;
- (void)_handleAdDidVisible;
- (void)_handleAdDidWillPresentFullscreenModal;
- (void)_handleVideoAdPlayFinished:;
- (void)_handleVideoCache2OutWithAd;
- (void)_handleVideoCacheActionWithAd:;
- (BOOL)_realShowAd:withRootViewController:extraInfos:;
- (void)adLoadDidFailedWithError:;
- (void)adLoadDidSuccess;
- (BOOL)carouselAdDidRequestShowAd:withRootViewController:extraInfos:;
- (void)carouselAdDidShowFailedWithError:;
- (void)carouselAdDidShowFinish;
- (BOOL)didDealLoad;
- (BOOL)didDealVideoCache;
- (BOOL)enablePreloadCache;
- (void)fullscreenVideoAd:didPlayFinishWithError:;
- (void)fullscreenVideoAdDidClick:;
- (void)fullscreenVideoAdDidClickSkip:;
- (void)fullscreenVideoAdDidClose:;
- (void)fullscreenVideoAdDidShowFailed:error:;
- (void)fullscreenVideoAdDidVisible:;
- (void)fullscreenVideoAdVideoDidLoad:;
- (void)fullscreenVideoAdWillClose:;
- (void)fullscreenVideoAdWillDismissFullScreenModel:interactionType:;
- (void)fullscreenVideoAdWillPresentFullscreenModal:;
- (void)fullscreenVideoAdWillVisible:;
- (id)getAdCreativeToken;
- (id)getAdNetworkPlatformName;
- (id)getAdNetworkRitId;
- (double)getExpireTimestamp;
- (id)getMediaExtraInfo;
- (id)getPreEcpm;
- (id)initWithAdUnitID:sizeForInterstitial:;
- (void)interstitialAd:renderFailedWithError:;
- (void)interstitialAdDidClick:;
- (void)interstitialAdDidClose:;
- (void)interstitialAdDidShowFailed:error:;
- (void)interstitialAdDidVisible:;
- (void)interstitialAdRenderSuccess:;
- (void)interstitialAdWillDismissFullScreenModal:;
- (void)interstitialAdWillPresentFullScreenModal:;
- (BOOL)isReadyCallByApi:error:;
- (BOOL)materialMetaIsFromPreload;
- (unsigned long long)moduleControl;
- (BOOL)mutedIfCan;
- (BOOL)needHandleCacheTimeout;
- (id)preloadAdWithType:;
- (void)preloaderDidSuccessLoadWithTargetAd:andType:;
- (id)reuseIdentifierFactors;
- (id)rewardModel;
- (void)rewardedVideoAd:didServerRewardSuccessWithInfo:;
- (void)setCarouselManager:;
- (void)setDidDealVideoCache:;
- (void)setMutedIfCan:;
- (void)setSizeForInterstitial:;
- (BOOL)showAdFromRootViewController:extraInfos:;
- (id)sizeForInterstitial;
- (void)videoCacheDidTimeout;
- (void)waterfall:didLoadMediaAd:withAdapter:;
- (void)setDelegate:;
- (long long)adType;
- (BOOL)isReady;
- (id)delegate;
- (void).cxx_destruct;
- (id)extraData;
- (void)setHasShown:;
- (BOOL)hasShown;
@end
