@interface ABURewardManager : NSObject
@property (nonatomic) ABURewardManagerConfig config;
@property (nonatomic) double lastRequestTime;
@property (nonatomic) BOOL canceled;
@property (nonatomic) ABUAdapterRewardAdInfo reward;
@property (nonatomic) @? complete;
@property (nonatomic) NSObject<OS_dispatch_queue> queue;
@property (nonatomic) BOOL allowCallback;
@property (nonatomic) q startTime;
@property (nonatomic) NSString transID;
- (id)initWithConfigBuilder:complete:;
- (double)lastRequestTime;
- (id)transID;
- (void)__requestRewardIfNeededByCallback:;
- (void)_backupRewardInNeeded;
- (void)_dealCallback:;
- (void)_requestReward;
- (void)_requestRewardIfNeededByAdnVerify;
- (void)_requestRewardIfNeededByRetryWithTimes:;
- (void)_requestRewardIfNeededByTimer;
- (void)_requestRewardIfNeededByVideoComplete;
- (BOOL)allowCallback;
- (void)requestRewardIfNeededWithReward:by:;
- (id)reward;
- (void)setAllowCallback:;
- (void)setLastRequestTime:;
- (void)setReward:;
- (void)setTransID:;
- (id)complete;
- (long long)tag;
- (id)init;
- (void)cancel;
- (void)setConfig:;
- (void)setStartTime:;
- (long long)startTime;
- (void).cxx_destruct;
- (void)setQueue:;
- (void)setComplete:;
- (id)config;
- (void)setCanceled:;
- (id)queue;
- (BOOL)canceled;
@end
