@interface ACCredentialItem : NSObject
@property (nonatomic) NSString accountIdentifier;
@property (nonatomic) NSDate expirationDate;
@property (nonatomic) BOOL expired;
@property (nonatomic) NSString serviceName;
@property (nonatomic) BOOL persistent;
@property (nonatomic) NSURL objectID;
@property (nonatomic) ACAccountStore accountStore;
@property (nonatomic) BOOL dirty;
@property (nonatomic) NSSet dirtyProperties;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)_initWithProtobuf:;
- (void)setAccountStore:;
- (void)markAllPropertiesDirty;
- (void)_markPropertyDirty:;
- (id)objectID;
- (void)setObjectID:;
- (BOOL)isPersistent;
- (id)accountStore;
- (id)dirtyProperties;
- (id)_initWithProtobufData:;
- (id)fullDescription;
- (void)setAccountIdentifier:;
- (id)_encodeProtobufData;
- (id)accountIdentifier;
- (BOOL)isDirty;
- (BOOL)isExpired;
- (id)initWithAccountIdentifier:serviceName:;
- (void)setServiceName:;
- (void)setExpirationDate:;
- (id)serviceName;
- (id)initWithCoder:;
- (id)expirationDate;
- (void)encodeWithCoder:;
- (BOOL)isPropertyDirty:;
- (id)initWithManagedCredentialItem:;
- (id)_encodeProtobuf;
- (void).cxx_destruct;
- (id)description;
- (id)initWithManagedCredentialItem:accountStore:;
- (void)setPersistent:;
- (void)clearDirtyProperties;
- (id)copyWithZone:;
+ (BOOL)supportsSecureCoding;
@end
