@interface AFHomeAccessorySiriDataSharingChangeLogEvent : NSObject
@property (nonatomic) NSDate date;
@property (nonatomic) q previousOptInStatus;
@property (nonatomic) q newOptInStatus;
@property (nonatomic) q changeSource;
@property (nonatomic) NSString changeReason;
@property (nonatomic) NSString buildVersion;
@property (nonatomic) NSString productVersion;
@property (nonatomic) NSString schemaVersion;
@property (nonatomic) NSString logEventIdentifier;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)buildVersion;
- (id)productVersion;
- (id)init;
- (long long)changeSource;
- (id)buildDictionaryRepresentation;
- (id)mutatedCopyWithMutator:;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (id)initWithDictionaryRepresentation:;
- (id)_descriptionWithIndent:;
- (id)date;
- (id)initWithBuilder:;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (id)description;
- (id)schemaVersion;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)initWithDate:previousOptInStatus:newOptInStatus:changeSource:changeReason:buildVersion:productVersion:schemaVersion:logEventIdentifier:;
- (long long)previousOptInStatus;
- (long long)newOptInStatus;
- (id)changeReason;
- (id)logEventIdentifier;
+ (id)newWithBuilder:;
+ (BOOL)supportsSecureCoding;
@end
