@interface AKAuthorizationPresentationContext : NSObject
@property (nonatomic) NSString bundleID;
@property (nonatomic) BOOL signInAllowsPCSKeyAccess;
@property (nonatomic) NSString localizedAppName;
@property (nonatomic) NSString informativeText;
@property (nonatomic) NSString iconName;
@property (nonatomic) NSData iconData;
@property (nonatomic) NSNumber iconScale;
@property (nonatomic) AKCredentialRequestContext credentialRequestContext;
@property (nonatomic) AKUserInformation userInformation;
@property (nonatomic) NSArray loginChoices;
- (id)informativeText;
- (id)iconScale;
- (id)initWithCoder:;
- (id)iconName;
- (void)encodeWithCoder:;
- (id)localizedAppName;
- (void).cxx_destruct;
- (id)description;
- (id)bundleID;
- (id)copyWithZone:;
- (void)setBundleID:;
- (void)setLocalizedAppName:;
- (id)iconData;
- (id)userInformation;
- (void)setUserInformation:;
- (id)initWithContext:client:;
- (id)initWithContext:bundleID:;
- (id)initWithUsername:;
- (void)_addPresenterParameters;
- (void)_addPresentationParametersForContext:;
- (BOOL)signInAllowsPCSKeyAccess;
- (void)setSignInAllowsPCSKeyAccess:;
- (id)credentialRequestContext;
- (void)setCredentialRequestContext:;
- (id)loginChoices;
- (void)setLoginChoices:;
+ (BOOL)supportsSecureCoding;
+ (id)presentationContextForRequestContext:client:;
@end
