@interface AlipaySDK : NSObject
@property (nonatomic) NSString schemeStr;
@property (nonatomic) NSString executingOrderStr;
@property (nonatomic) @? completionBlock;
@property (nonatomic) APayRoute route;
@property (nonatomic) APayProcessor processor;
@property (nonatomic) NSDictionary alertOkAction;
@property (nonatomic) NSDictionary alertCancelAction;
@property (nonatomic) NSCondition tidCondition;
@property (nonatomic) BOOL stopPayIn2S;
@property (nonatomic) BOOL stopAuthIn2S;
@property (nonatomic) BOOL stopFetchConfig;
@property (nonatomic) Q areaType;
@property (nonatomic) APayAlertView alertView;
@property (nonatomic) UIWindow targetWindow;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)stopFetchConfig;
- (id)fetchTradeToken;
- (id)queryTidFactor:;
- (void)setStopPayIn2S:;
- (void)afterCallAlipay:callSuccess:withBlock:;
- (id)alertCancelAction;
- (id)alertOkAction;
- (unsigned long long)area4OrderStr:;
- (void)authWithInfo:callback:;
- (void)auth_V2WithInfo:fromScheme:callback:;
- (id)buildQueryStrWithOrder:andExtraInfo:;
- (BOOL)callAlipayBySchemes:orderStr:;
- (void)callAlipayByUL:withBlock:;
- (void)callAlipayWithOrderStr:dynamicLaunch:withBlock:;
- (void)callback:withMemo:andResultStatus:;
- (void)callbackWithResult:;
- (BOOL)checkValidityWithOrderStr:callback:;
- (void)cleanInfoWhenGoPortal:;
- (id)dictionaryFromRegular:pattern:;
- (id)executingOrderStr;
- (id)fetchOrderInfoFromH5PayUrl:;
- (void)fetchSdkConfigWithBlock:;
- (void)handleRouteConfig:withBlock:;
- (BOOL)isLogined;
- (BOOL)isNewModelResult:;
- (BOOL)isShouldInterceptorDomain:;
- (void)onAdapterFinished;
- (BOOL)payInterceptorWithUrl:fromScheme:callback:;
- (void)payOrder:dynamicLaunch:fromScheme:callback:;
- (void)payOrder:fromScheme:callback:;
- (void)payUrlOrder:fromScheme:callback:;
- (void)payWithType:orderStr:schemeStr:dynamicLaunch:callback:;
- (void)processAuthResult:standbyCallback:;
- (void)processAuth_V2Result:standbyCallback:;
- (void)processOrderWithPaymentResult:standbyCallback:;
- (void)processResultUrl:callback:;
- (id)processTradeToken:;
- (void)queryTid;
- (void)removeAlipayObserver;
- (long long)routeTypeWithConfig:;
- (id)schemeStr;
- (void)setAlertCancelAction:;
- (void)setAlertOkAction:;
- (void)setExecutingOrderStr:;
- (void)setSchemeStr:;
- (void)setStopAuthIn2S:;
- (void)setStopFetchConfig:;
- (void)setTidCondition:;
- (BOOL)stopAuthIn2S;
- (BOOL)stopPayIn2S;
- (id)tidCondition;
- (id)valueFromResult:withKey:isNewModel:;
- (id)init;
- (id)route;
- (void)setCompletionBlock:;
- (id)currentVersion;
- (void)setUrl:;
- (void)setAlertView:;
- (void).cxx_destruct;
- (id)alertView;
- (id)completionBlock;
- (void)alertView:clickedButtonAtIndex:;
- (id)targetWindow;
- (id)processor;
- (unsigned long long)areaType;
- (void)setAreaType:;
- (void)setTargetWindow:;
- (void)cleanData;
+ (void)stopLog;
+ (void)startLogWithBlock:;
+ (id)defaultService;
@end
