@interface AMSLogConfig : NSObject
@property (nonatomic) NSString category;
@property (nonatomic) NSString subsystem;
@property (nonatomic) NSObject<OS_os_log> OSLogObject;
@property (nonatomic) BOOL debugLogsEnabled;
- (BOOL)debugLogsEnabled;
- (id)subsystem;
- (id)initWithCategory:backingLog:;
- (void)setOSLogObject:;
- (unsigned long long)hash;
- (void)setCategory:;
- (void).cxx_destruct;
- (id)description;
- (id)OSLogObject;
- (id)mutableCopyWithZone:;
- (BOOL)isEqual:;
- (void)setSubsystem:;
- (id)category;
- (id)copyWithZone:;
+ (id)sharedAccountsDaemonConfig;
+ (id)sharedWebUIConfig;
+ (id)sharedBagConfig;
+ (id)sharedConfigOversize;
+ (id)sharedPromiseConfig;
+ (id)sharedMediaServiceOwnerConfig;
+ (id)sharedAccountsMultiUserConfig;
+ (BOOL)_debugLogsEnabled:;
+ (id)sharedAccountsConfig;
+ (id)sharedAccountsOversizeConfig;
+ (id)sharedUserNotificationConfig;
+ (id)sharedAccountsCookiesConfig;
+ (id)sharedConfig;
+ (id)sharedPurchaseConfig;
+ (id)sharedFollowUpConfig;
+ (id)sharedEngagementConfig;
+ (id)sharedKeychainConfig;
+ (id)sharedAccountsAuthenticationPluginConfig;
+ (id)sharedServerDataCacheConfig;
+ (id)sharedRatingsProviderConfig;
+ (id)sharedAccountsStorefrontConfig;
+ (id)sharedAccountsLogoutConfig;
+ (id)sharedPushNotificationConfig;
+ (id)sharedAccountsMigrationConfigOversize;
+ (id)sharedAccountsMigrationConfig;
+ (id)sharedAccountsNotificationPluginConfig;
+ (id)sharedDeviceOffersConfig;
+ (id)sharedAccountsSyncPluginConfig;
+ (id)sharedMediaConfig;
+ (id)sharedDataMigrationConfig;
+ (id)sharedAttestationConfig;
+ (id)sharedBagCacheConfig;
+ (id)sharedAnisetteConfig;
+ (id)sharedMarketingItemConfig;
+ (id)sharedPrivacyConfig;
@end
