@interface AMSSnapshotBag : NSObject
@property (nonatomic) AMSBagFrozenDataSource dataSource;
@property (nonatomic) {optional<AMSCore::Bag>=(?=c{Bag=^^?{shared_ptr<AMSCore::IBagDataSource>=^{IBagDataSource}^{__shared_weak_count}}})B} underlyingBag;
@property (nonatomic) NSDate creationDate;
@property (nonatomic) BOOL expired;
@property (nonatomic) NSDate expirationDate;
@property (nonatomic) NSString profile;
@property (nonatomic) NSString profileVersion;
@property (nonatomic) AMSProcessInfo processInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setDataSource:;
- (id)init;
- (id)URLForKey:;
- (BOOL)isExpired;
- (id)_initWithDataSource:;
- (id)initWithBag:;
- (id)boolForKey:;
- (id)stringForKey:;
- (id)initWithCoder:;
- (id)profile;
- (id)compile;
- (id)_initWithSnapshotBag:;
- (id)URLForKey:account:;
- (id)expirationDate;
- (void)encodeWithCoder:;
- (id)arrayForKey:;
- (id)dataSource;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)isLoaded;
- (id)doubleForKey:;
- (void)setUnderlyingBag:;
- (id)profileVersion;
- (void)createSnapshotWithCompletion:;
- (id)underlyingBag;
- (id)integerForKey:;
- (id).cxx_construct;
- (id)dictionaryForKey:;
- (id)creationDate;
+ (BOOL)supportsSecureCoding;
@end
