@interface ARFLSpring : NSObject
@property (nonatomic) double retargetResponseFraction;
@property (nonatomic) double projectionDeceleration;
@property (nonatomic) double value;
@property (nonatomic) double target;
@property (nonatomic) double velocity;
@property (nonatomic) double projectedTarget;
@property (nonatomic) {ARFLSpringParameters=dddd} parameters;
@property (nonatomic) {ARFLSpringParameters=dddd} trackingParameters;
@property (nonatomic) BOOL tracking;
@property (nonatomic) double minimumTarget;
@property (nonatomic) double maximumTarget;
@property (nonatomic) double rubberbandRange;
@property (nonatomic) double rubberbandFactor;
- (double)velocity;
- (BOOL)isTracking;
- (id)init;
- (void)setVelocity:;
- (void)setTracking:;
- (void)setTarget:;
- (id)parameters;
- (void)setValue:;
- (void)step:;
- (double)target;
- (double)value;
- (void)setParameters:;
- (id)initWithValue:;
- (double)projectedTarget;
- (double)_projectedTargetForVelocity:;
- (void)resetImmediatelyToValue:;
- (void)setTrackingParameters:;
- (BOOL)usesDampingRatioResponseForSmoothing;
- (void)setUsesDampingRatioResponseForSmoothing:;
- (id)_effectiveParameters;
- (void)_updateForEffectiveParameters;
- (id)trackingParameters;
- (double)minimumTarget;
- (void)setMinimumTarget:;
- (double)maximumTarget;
- (void)setMaximumTarget:;
- (double)rubberbandRange;
- (void)setRubberbandRange:;
- (double)rubberbandFactor;
- (void)setRubberbandFactor:;
- (double)retargetResponseFraction;
- (void)setRetargetResponseFraction:;
- (double)projectionDeceleration;
- (void)setProjectionDeceleration:;
+ (id)springWithValue:;
@end
