@interface ARMLImageDownScalingTechnique : ARImageBasedTechnique
@property (nonatomic) BOOL centerCropImage;
@property (nonatomic) {CGSize=dd} imageSize;
@property (nonatomic) BOOL resizeUltraWideImage;
@property (nonatomic) BOOL saveIntermediateScaleResultData;
@property (nonatomic) BOOL shouldOperateOnHighResolutionImages;
@property (nonatomic) @? wideRotationStrategy;
@property (nonatomic) @? ultrawideRotationStrategy;
- (void)dealloc;
- (id)initWithSize:;
- (id)imageSize;
- (id)processData:;
- (void).cxx_destruct;
- (id)_fullDescription;
- (BOOL)isEqual:;
- (void)prepare:;
- (void)requestResultDataAtTimestamp:context:;
- (double)requiredTimeInterval;
- (id)resultDataClasses;
- (BOOL)shouldOperateOnHighResolutionImages;
- (void)setShouldOperateOnHighResolutionImages:;
- (long long)getDeviceOrientationFromImageData:;
- (id)initWithSize:requiredTimeInterval:;
- (void)lockOrientation:;
- (void)_processImageDataInBackground:;
- (id)defaultRotationStrategy;
- (id)_twoPassDownscaledResultDataFromImageData:croppedRect:;
- (id)_scaleImageDataForNeuralNetwork:scaledSize:;
- (id)_rotateImageDataForNeuralNetwork:deviceOrientation:pRegionOfInterest:pRotationOfResultTensor:;
- (id)_fastPassDownscaledResultDataFromImageData:croppedRect:fastPassScaler:;
- (BOOL)centerCropImage;
- (void)setCenterCropImage:;
- (BOOL)resizeUltraWideImage;
- (void)setResizeUltraWideImage:;
- (BOOL)saveIntermediateScaleResultData;
- (void)setSaveIntermediateScaleResultData:;
- (id)wideRotationStrategy;
- (void)setWideRotationStrategy:;
- (id)ultrawideRotationStrategy;
- (void)setUltrawideRotationStrategy:;
@end
