@interface ARRecordingTechniquePublic : ARTechnique
@property (nonatomic) Q state;
@property (nonatomic) NSURL outputFileURL;
@property (nonatomic) BOOL expectDepthData;
@property (nonatomic) BOOL expectAudioData;
@property (nonatomic) BOOL expectCustomData;
@property (nonatomic) BOOL shouldSaveVideoInPhotosLibrary;
@property (nonatomic) <ARRecordingTechniqueDelegate> recordingTechniqueDelegate;
@property (nonatomic) Q recordingSensorDataTypes;
@property (nonatomic) ARParentImageSensorSettings parentImageSensorSettings;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)_subscribeToBackgroundNotifications;
- (void)_saveVideoInPhotosLibrary:;
- (void)copyVideoToPhotoLibrary:;
- (id)init;
- (void)dealloc;
- (BOOL)finished;
- (void)setState:;
- (id)processData:;
- (unsigned long long)state;
- (void)startRecording;
- (void).cxx_destruct;
- (void)_finish:;
- (void)didFailWithError:;
- (BOOL)isEqual:;
- (id)outputFileURL;
- (unsigned long long)requiredSensorDataTypes;
- (id)parentImageSensorSettings;
- (void)isReadyToRecord;
- (void)didFinishRecording;
- (id)initWithFileURL:sensorDataTypes:;
- (id)initWithFileURL:recordingSensorDataTypes:;
- (id)initWithFileURL:recordingSensorDataTypes:startImmediately:recordCollaborationData:;
- (void)recordCustomData:forTimestamp:;
- (void)recordCollaborationData:localSession:;
- (void)recordAddedAnchor:;
- (void)recordRemovedAnchor:;
- (void)finishRecording;
- (void)abortRecording;
- (BOOL)expectDepthData;
- (void)setExpectDepthData:;
- (BOOL)expectAudioData;
- (void)setExpectAudioData:;
- (BOOL)expectCustomData;
- (void)setExpectCustomData:;
- (BOOL)shouldSaveVideoInPhotosLibrary;
- (void)setShouldSaveVideoInPhotosLibrary:;
- (id)recordingTechniqueDelegate;
- (void)setRecordingTechniqueDelegate:;
- (unsigned long long)recordingSensorDataTypes;
- (void)setParentImageSensorSettings:;
- (BOOL)allowedToWrite;
- (void)removeTemporaryVideoFile;
- (void)_fail:;
- (void)_startRecording;
- (void)setupSensorTracks;
- (void)setupCustomTrack;
- (id)createFileMetadata;
- (void)writeTimeOfFlightData:;
- (void)writeSensorData:;
- (void)writeImageData:;
- (void)writePearlDepthData:withTimestamp:fromCaptureDevice:;
- (void)writeAudioData:;
- (void)writeResultData:withTimestamp:;
- (void)processTimeSensitiveNSCoderObject:withTimestamp:metadataID:;
- (void)_finishRecording;
+ (BOOL)isSupported;
@end
