@interface AUParameterTree : AUParameterGroup
@property (nonatomic) {vector<AddressToParameter addrToParamIndex;
@property (nonatomic) NSInteger _autoCreatedForV2AU;
@property (nonatomic) NSObject<OS_dispatch_queue> observationQueue;
@property (nonatomic) NSObject<OS_dispatch_queue> valueAccessQueue;
@property (nonatomic) AUAudioUnit_XH _auXH;
@property (nonatomic) NSInteger numRecorders;
@property (nonatomic) ^{AURemoteParameterObserver=} remoteObserverToken;
@property (nonatomic) ^{AURemoteParameterObserver=} remoteRecorderToken;
@property (nonatomic) NSXPCConnection remoteParameterSynchronizerXPCConnection;
- (id)parameterWithAddress:;
- (id)initWithChildren:;
- (void)dealloc;
- (id)remoteParameterSynchronizerXPCConnection;
- (id)observerController;
- (id)valueAccessQueue;
- (int)numRecorders;
- (void)_init2;
- (id)remoteObserverToken;
- (id)initWithCoder:;
- (void)set_autoCreatedForV2AU:;
- (void)encodeWithCoder:;
- (id)addrToParamIndex;
- (void)set_auXH:;
- (void)setAddrToParamIndex:;
- (void).cxx_destruct;
- (id)_auXH;
- (id)parameterWithID:scope:element:;
- (void)setRemoteRecorderToken:;
- (id)observationQueue;
- (void)setRemoteParameterSynchronizerXPCConnection:;
- (void)setNumRecorders:;
- (void)remoteSyncParameter:value:extOriginator:hostTime:eventType:;
- (id).cxx_construct;
- (id)remoteRecorderToken;
- (void)_checkInitTreeObservation;
- (int)_autoCreatedForV2AU;
- (void)setRemoteObserverToken:;
+ (id)createGroupTemplate:;
+ (BOOL)supportsSecureCoding;
+ (id)createParameterWithIdentifier:name:address:min:max:unit:unitName:flags:valueStrings:dependentParameters:;
+ (id)createGroupWithIdentifier:name:children:;
+ (id)createGroupFromTemplate:identifier:name:addressOffset:;
+ (id)createTreeWithChildren:;
@end
