@interface AVAudioDeviceTestSequence : NSObject
@property (nonatomic) BOOL processSequenceAsynchronously;
@property (nonatomic) q outputID;
@property (nonatomic) float volume;
@property (nonatomic) NSURL stimulusURL;
@property (nonatomic) AVAudioDeviceTestProcessingChain inputProcessingChain;
@property (nonatomic) AVAudioDeviceTestProcessingChain outputProcessingChain;
@property (nonatomic) q outputMode;
@property (nonatomic) q priority;
@property (nonatomic) NSString mode;
@property (nonatomic) BOOL calculateCrossCorrelationPeak;
@property (nonatomic) BOOL parallelCrossCorrelationCalculation;
@property (nonatomic) q numberOfChannels;
@property (nonatomic) NSArray micBufferNumbers;
@property (nonatomic) BOOL requiresBluetoothOutput;
@property (nonatomic) NSString microphone;
- (id)init;
- (float)volume;
- (void)setPriority:;
- (void)setVolume:;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (id)mode;
- (void)setMode:;
- (long long)priority;
- (void)setOutputMode:;
- (long long)outputMode;
- (long long)numberOfChannels;
- (BOOL)processSequenceAsynchronously;
- (void)setProcessSequenceAsynchronously:;
- (long long)outputID;
- (void)setOutputID:;
- (id)stimulusURL;
- (void)setStimulusURL:;
- (id)inputProcessingChain;
- (void)setInputProcessingChain:;
- (id)outputProcessingChain;
- (void)setOutputProcessingChain:;
- (BOOL)calculateCrossCorrelationPeak;
- (void)setCalculateCrossCorrelationPeak:;
- (BOOL)parallelCrossCorrelationCalculation;
- (void)setParallelCrossCorrelationCalculation:;
- (void)setNumberOfChannels:;
- (id)micBufferNumbers;
- (void)setMicBufferNumbers:;
- (BOOL)requiresBluetoothOutput;
- (void)setRequiresBluetoothOutput:;
- (id)microphone;
- (void)setMicrophone:;
+ (BOOL)supportsSecureCoding;
@end
