@interface AVHapticSequence : NSObject
@property (nonatomic) AVHapticPlayer player;
@property (nonatomic) Q seqID;
@property (nonatomic) double duration;
@property (nonatomic) double lastStartTime;
@property (nonatomic) Q activeChannel;
@property (nonatomic) Q eventBehavior;
@property (nonatomic) BOOL loopingEnabled;
@property (nonatomic) float playbackRate;
@property (nonatomic) Q channelCount;
@property (nonatomic) @? completionHandler;
- (float)playbackRate;
- (void)setActiveChannel:;
- (id)init;
- (void)dealloc;
- (unsigned long long)eventBehavior;
- (void)setPlaybackRate:;
- (void)setCompletionHandler:;
- (unsigned long long)activeChannel;
- (void)setDuration:;
- (unsigned long long)channelCount;
- (id)player;
- (void).cxx_destruct;
- (void)setPlayer:;
- (double)duration;
- (id)completionHandler;
- (BOOL)stopAtTime:error:;
- (void)setLoopingEnabled:;
- (BOOL)activateChannelByIndex:atTime:error:;
- (BOOL)setVolume:atTime:error:;
- (BOOL)loopingEnabled;
- (BOOL)earlyUnduckAudioAtTime:error:;
- (BOOL)cancelAndReturnError:;
- (BOOL)pauseAtTime:error:;
- (BOOL)resumeAtTime:error:;
- (void)setEventBehavior:;
- (BOOL)resetAtTime:error:;
- (id)initWithData:player:error:;
- (id)initWithEvents:player:error:;
- (id)initWithDictionary:player:error:;
- (BOOL)setLoopingEnabled:error:;
- (unsigned long long)getChannelCount;
- (BOOL)setLoopLength:error:;
- (BOOL)prepareToPlayAndReturnError:;
- (BOOL)playAtTime:offset:error:;
- (BOOL)seekToTime:error:;
- (BOOL)setParameter:value:channel:atTime:error:;
- (unsigned long long)seqID;
- (void)setSeqID:;
- (double)lastStartTime;
- (void)setLastStartTime:;
@end
