@interface AVMutableMovieTrack : AVMovieTrack
@property (nonatomic) NSArray formatDescriptions;
@property (nonatomic) NSArray metadata;
@property (nonatomic) AVMediaDataStorage mediaDataStorage;
@property (nonatomic) NSURL sampleReferenceBaseURL;
@property (nonatomic) BOOL enabled;
@property (nonatomic) q alternateGroupID;
@property (nonatomic) BOOL modified;
@property (nonatomic) BOOL hasProtectedContent;
@property (nonatomic) NSInteger timescale;
- (id)dimensions;
- (void)setPreferredMediaChunkDuration:;
- (void)setLayer:;
- (void)setPreferredMediaChunkAlignment:;
- (id)metadataForFormat:;
- (void)setPreferredTransform:;
- (id)naturalSize;
- (id)extendedLanguageTag;
- (void)dealloc;
- (void)setLanguageCode:;
- (long long)preferredMediaChunkSize;
- (void)setExtendedLanguageTag:;
- (void)setPreferredMediaChunkSize:;
- (id)languageCode;
- (id)formatDescriptions;
- (void)setAlternateGroupID:;
- (void)setSampleReferenceBaseURL:;
- (void)setNaturalSize:;
- (id)availableMetadataFormats;
- (BOOL)hasProtectedContent;
- (id)metadata;
- (long long)layer;
- (void)setPreferredVolume:;
- (id)_figAssetTrack;
- (id)mediaPresentationTimeRange;
- (id)locale;
- (id)mediaDecodeTimeRange;
- (void)setModified:;
- (void)removeTimeRange:;
- (void)insertEmptyTimeRange:;
- (BOOL)isModified;
- (void)setMetadata:;
- (id)sampleReferenceBaseURL;
- (id)_figMutableMovie;
- (void)scaleTimeRange:toDuration:;
- (void)_signalMetadataUpdated;
- (void)loadValuesAsynchronouslyForKeys:completionHandler:;
- (void)setEnabled:;
- (void).cxx_destruct;
- (long long)statusOfValueForKey:error:;
- (int)trackID;
- (float)preferredVolume;
- (id)description;
- (id)preferredMediaChunkDuration;
- (long long)preferredMediaChunkAlignment;
- (void)setTimescale:;
- (int)timescale;
- (long long)alternateGroupID;
- (id)preferredTransform;
- (BOOL)isEnabled;
- (void)addTrackAssociationToTrack:type:;
- (void)removeTrackAssociationToTrack:type:;
- (void)replaceFormatDescription:withFormatDescription:;
- (id)mediaDataStorage;
- (id)initWithTrackID:forMovie:;
- (void)_addFigAssetTrackNotifications;
- (void)_removeFigAssetTrackNotifications;
- (id)cleanApertureDimensions;
- (id)productionApertureDimensions;
- (id)encodedPixelsDimensions;
- (id)_sizeForProperty:;
- (void)_setSize:forProperty:;
- (id)_stringForProperty:;
- (void)_setString:forProperty:;
- (void)setMediaDataStorage:;
- (void)setCleanApertureDimensions:;
- (void)setProductionApertureDimensions:;
- (void)setEncodedPixelsDimensions:;
- (BOOL)isCompatibleWithFormatDescription:;
- (BOOL)insertTimeRange:ofTrack:atTime:copySampleData:error:;
- (BOOL)appendSampleBuffer:decodeTime:presentationTime:error:;
- (BOOL)insertMediaTimeRange:intoTimeRange:;
- (BOOL)appendMediaData:dataOffset:;
+ (BOOL)expectsPropertyRevisedNotifications;
+ (id)trackWithTrackID:forMovie:;
@end
