@interface AWDCoreRoutineMagicMomentsSuggestionInstance : PBCodable
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) Q timestamp;
@property (nonatomic) BOOL hasSuggestionId;
@property (nonatomic) NSString suggestionId;
@property (nonatomic) BOOL hasConfidence;
@property (nonatomic) NSInteger confidence;
@property (nonatomic) NSMutableArray suggestions;
@property (nonatomic) BOOL hasReposponceTime;
@property (nonatomic) NSInteger reposponceTime;
@property (nonatomic) BOOL hasDurationSinceLastSuggestion;
@property (nonatomic) NSInteger durationSinceLastSuggestion;
- (void)setSuggestions:;
- (void)clearSuggestions;
- (int)confidence;
- (void)setConfidence:;
- (void)dealloc;
- (id)suggestionsAtIndex:;
- (id)suggestionId;
- (unsigned long long)suggestionsCount;
- (void)writeTo:;
- (id)suggestions;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (BOOL)hasTimestamp;
- (void)setSuggestionId:;
- (void)setTimestamp:;
- (BOOL)readFrom:;
- (unsigned long long)timestamp;
- (id)description;
- (id)dictionaryRepresentation;
- (void)addSuggestions:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setHasConfidence:;
- (BOOL)hasConfidence;
- (BOOL)hasSuggestionId;
- (void)setReposponceTime:;
- (void)setHasReposponceTime:;
- (BOOL)hasReposponceTime;
- (void)setDurationSinceLastSuggestion:;
- (void)setHasDurationSinceLastSuggestion:;
- (BOOL)hasDurationSinceLastSuggestion;
- (int)reposponceTime;
- (int)durationSinceLastSuggestion;
+ (Class)suggestionsType;
@end
