@interface AWDIDSAppDeliveryReceipt : PBCodable
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) Q timestamp;
@property (nonatomic) BOOL hasService;
@property (nonatomic) NSString service;
@property (nonatomic) BOOL hasIsToDefaultPairedDevice;
@property (nonatomic) Q isToDefaultPairedDevice;
@property (nonatomic) BOOL hasMessageSize;
@property (nonatomic) Q messageSize;
@property (nonatomic) BOOL hasRTT;
@property (nonatomic) Q rTT;
@property (nonatomic) BOOL hasPriority;
@property (nonatomic) Q priority;
- (void)setService:;
- (void)setPriority:;
- (void)dealloc;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)setHasPriority:;
- (void)setMessageSize:;
- (id)service;
- (void)copyTo:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (BOOL)hasTimestamp;
- (void)setTimestamp:;
- (BOOL)readFrom:;
- (unsigned long long)timestamp;
- (id)description;
- (BOOL)hasPriority;
- (unsigned long long)messageSize;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (unsigned long long)priority;
- (BOOL)hasService;
- (void)setIsToDefaultPairedDevice:;
- (unsigned long long)isToDefaultPairedDevice;
- (void)setHasIsToDefaultPairedDevice:;
- (BOOL)hasIsToDefaultPairedDevice;
- (void)setHasMessageSize:;
- (BOOL)hasMessageSize;
- (void)setRTT:;
- (void)setHasRTT:;
- (BOOL)hasRTT;
- (unsigned long long)rTT;
@end
