@interface AWDIDSRegistrationCompleted : PBCodable
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) Q timestamp;
@property (nonatomic) BOOL hasRegistrationType;
@property (nonatomic) NSInteger registrationType;
@property (nonatomic) BOOL hasServiceIdentifier;
@property (nonatomic) NSString serviceIdentifier;
@property (nonatomic) BOOL hasWasSuccessful;
@property (nonatomic) I wasSuccessful;
@property (nonatomic) BOOL hasRegistrationError;
@property (nonatomic) NSInteger registrationError;
@property (nonatomic) BOOL hasCircleStatus;
@property (nonatomic) NSInteger circleStatus;
- (int)registrationType;
- (BOOL)hasRegistrationError;
- (void)setRegistrationError:;
- (void)setHasRegistrationError:;
- (void)setServiceIdentifier:;
- (BOOL)hasServiceIdentifier;
- (void)setRegistrationType:;
- (void)dealloc;
- (int)registrationError;
- (void)setWasSuccessful:;
- (unsigned int)wasSuccessful;
- (void)setCircleStatus:;
- (void)writeTo:;
- (id)serviceIdentifier;
- (void)setHasRegistrationType:;
- (unsigned long long)hash;
- (void)setHasWasSuccessful:;
- (void)copyTo:;
- (void)setHasCircleStatus:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (BOOL)hasWasSuccessful;
- (BOOL)hasTimestamp;
- (BOOL)hasCircleStatus;
- (void)setTimestamp:;
- (BOOL)hasRegistrationType;
- (int)circleStatus;
- (BOOL)readFrom:;
- (unsigned long long)timestamp;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
@end
