@interface AWDMailUserEngagement : PBCodable
@property (nonatomic) BOOL hasType;
@property (nonatomic) NSInteger type;
@property (nonatomic) BOOL hasMessageAgeInWeeks;
@property (nonatomic) q messageAgeInWeeks;
@property (nonatomic) BOOL hasMailboxType;
@property (nonatomic) NSInteger mailboxType;
@property (nonatomic) BOOL hasIsTopHitMessage;
@property (nonatomic) BOOL isTopHitMessage;
@property (nonatomic) BOOL hasTopHitIndexInTopHitsList;
@property (nonatomic) q topHitIndexInTopHitsList;
@property (nonatomic) BOOL hasTopHitIndexInSpotlightList;
@property (nonatomic) q topHitIndexInSpotlightList;
- (int)StringAsType:;
- (void)setType:;
- (void)writeTo:;
- (void)setHasType:;
- (BOOL)hasType;
- (unsigned long long)hash;
- (void)copyTo:;
- (id)typeAsString:;
- (void)mergeFrom:;
- (int)type;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (int)mailboxType;
- (void)setMailboxType:;
- (void)setHasMailboxType:;
- (BOOL)hasMailboxType;
- (id)mailboxTypeAsString:;
- (int)StringAsMailboxType:;
- (id)initWithEngagmentType:receivedDate:mailboxType:isTopHit:messageListIndex:spotlightListIndex:;
- (id)initWithEngagmentType:message:isTopHit:messageListIndex:spotlightListIndex:;
- (id)initWithEngagmentType:isTopHit:;
- (id)initWithEngagmentType:;
- (void)setMessageAgeInWeeks:;
- (void)setHasMessageAgeInWeeks:;
- (BOOL)hasMessageAgeInWeeks;
- (void)setIsTopHitMessage:;
- (void)setHasIsTopHitMessage:;
- (BOOL)hasIsTopHitMessage;
- (void)setTopHitIndexInTopHitsList:;
- (void)setHasTopHitIndexInTopHitsList:;
- (BOOL)hasTopHitIndexInTopHitsList;
- (void)setTopHitIndexInSpotlightList:;
- (void)setHasTopHitIndexInSpotlightList:;
- (BOOL)hasTopHitIndexInSpotlightList;
- (long long)messageAgeInWeeks;
- (BOOL)isTopHitMessage;
- (long long)topHitIndexInTopHitsList;
- (long long)topHitIndexInSpotlightList;
@end
