@interface AWDNanoPhoneIncomingCallConnected : PBCodable
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) Q timestamp;
@property (nonatomic) BOOL hasConnectingMs;
@property (nonatomic) Q connectingMs;
@property (nonatomic) BOOL hasCallProviderIdentifier;
@property (nonatomic) NSString callProviderIdentifier;
@property (nonatomic) BOOL hasIsVideo;
@property (nonatomic) BOOL isVideo;
@property (nonatomic) BOOL hasIsHosted;
@property (nonatomic) BOOL isHosted;
- (BOOL)isVideo;
- (void)dealloc;
- (BOOL)isHosted;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (BOOL)hasTimestamp;
- (void)setTimestamp:;
- (BOOL)readFrom:;
- (unsigned long long)timestamp;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setIsVideo:;
- (id)callProviderIdentifier;
- (void)setHasIsVideo:;
- (BOOL)hasIsVideo;
- (void)setConnectingMs:;
- (void)setHasConnectingMs:;
- (BOOL)hasConnectingMs;
- (BOOL)hasCallProviderIdentifier;
- (void)setIsHosted:;
- (void)setHasIsHosted:;
- (BOOL)hasIsHosted;
- (unsigned long long)connectingMs;
- (void)setCallProviderIdentifier:;
@end
