@interface AWDWiFiMetricsManagerChipCounters : PBCodable
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) Q timestamp;
@property (nonatomic) BOOL hasFrameCounters;
@property (nonatomic) AWDWiFiMetricsManagerFrameCounterStats frameCounters;
@property (nonatomic) BOOL hasTxGeneralStats;
@property (nonatomic) AWDChipCountersTx txGeneralStats;
@property (nonatomic) BOOL hasTxErrorStats;
@property (nonatomic) AWDChipErrorCountersTx txErrorStats;
@property (nonatomic) BOOL hasRxGeneralStats;
@property (nonatomic) AWDChipCountersRx rxGeneralStats;
@property (nonatomic) BOOL hasRxMACErrorStats;
@property (nonatomic) AWDMacCountersRxErrors rxMACErrorStats;
@property (nonatomic) BOOL hasRxMACCounterStats;
@property (nonatomic) AWDMacCountersRx rxMACCounterStats;
@property (nonatomic) BOOL hasRxPhyErrors;
@property (nonatomic) AWDRxPhyErrors rxPhyErrors;
@property (nonatomic) BOOL hasUcastWPA2Counters;
@property (nonatomic) AWDWPA2Counters ucastWPA2Counters;
@property (nonatomic) BOOL hasMcastWPA2Counters;
@property (nonatomic) AWDWPA2Counters mcastWPA2Counters;
@property (nonatomic) NSMutableArray frameCounterPerInterfaces;
- (void)dealloc;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (BOOL)hasTimestamp;
- (void)setTimestamp:;
- (BOOL)readFrom:;
- (unsigned long long)timestamp;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasFrameCounters;
- (BOOL)hasTxGeneralStats;
- (BOOL)hasTxErrorStats;
- (BOOL)hasRxGeneralStats;
- (BOOL)hasRxMACErrorStats;
- (BOOL)hasRxMACCounterStats;
- (BOOL)hasRxPhyErrors;
- (BOOL)hasUcastWPA2Counters;
- (BOOL)hasMcastWPA2Counters;
- (void)clearFrameCounterPerInterfaces;
- (void)addFrameCounterPerInterface:;
- (unsigned long long)frameCounterPerInterfacesCount;
- (id)frameCounterPerInterfaceAtIndex:;
- (id)frameCounters;
- (void)setFrameCounters:;
- (id)txGeneralStats;
- (void)setTxGeneralStats:;
- (id)txErrorStats;
- (void)setTxErrorStats:;
- (id)rxGeneralStats;
- (void)setRxGeneralStats:;
- (id)rxMACErrorStats;
- (void)setRxMACErrorStats:;
- (id)rxMACCounterStats;
- (void)setRxMACCounterStats:;
- (id)rxPhyErrors;
- (void)setRxPhyErrors:;
- (id)ucastWPA2Counters;
- (void)setUcastWPA2Counters:;
- (id)mcastWPA2Counters;
- (void)setMcastWPA2Counters:;
- (id)frameCounterPerInterfaces;
- (void)setFrameCounterPerInterfaces:;
+ (Class)frameCounterPerInterfaceType;
@end
