@interface AWEBubble : UIView
@property (nonatomic) UITapGestureRecognizer tapGesture;
@property (nonatomic) BOOL tapToDismiss;
@property (nonatomic) UILabel textLabel;
@property (nonatomic) UIView<AWEBubbleAnchor> bubbleView;
@property (nonatomic) Q direction;
@property (nonatomic) {UIEdgeInsets=dddd} edgeInsets;
@property (nonatomic) BOOL attributedBubble;
@property (nonatomic) {CGSize=dd} fixedSize;
@property (nonatomic) {CGPoint=dd} contentOffset;
@property (nonatomic) BOOL needFixedWidth;
@property (nonatomic) UIView iconView;
@property (nonatomic) {UIEdgeInsets=dddd} iconViewEdgeInsets;
@property (nonatomic) BOOL useContainerToAdjustBodyFrame;
@property (nonatomic) UIView anchorView;
@property (nonatomic) {CGPoint=dd} anchorPoint;
@property (nonatomic) BOOL useAdjustmentAsOffset;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)currentTextSize;
- (void)adjustBodyFrame;
- (id)anchorPositionRelatedToLeftTop;
- (BOOL)attributedBubble;
- (double)bubbleAnimationAnchorOffset;
- (void)drawStrokeIfNeeded;
- (id)iconViewEdgeInsets;
- (void)initWithAttributedContent:direction:anchorAdjustment:bubbleImage:image9ScaleInsets:edgeInsets:fixedSize:needFixedWidth:;
- (void)initWithContent:direction:anchorAdjustment:bubbleImage:image9ScaleInsets:edgeInsets:font:color:fixedSize:;
- (void)initWithContent:direction:anchorAdjustment:cornerAdjustment:fixedSize:isDarkBackGround:;
- (void)initWithContent:direction:anchorAdjustment:isDarkBackGround:;
- (void)initWithContent:direction:bubbleView:edgeInsets:font:color:fixedSize:;
- (void)initWithContent:direction:isDarkBackGround:;
- (void)initWithContent:withIconView:iconViewInsets:direction:anchorAdjustment:cornerAdjustment:fixedSize:isDarkBackGround:;
- (void)initWithCustomView:direction:edgeInsets:anchorAdjustment:cornerAdjustment:isDarkBackGround:;
- (void)initWithCustomView:direction:edgeInsets:anchorAdjustment:isDarkBackGround:;
- (void)initWithLabel:direction:bubbleView:edgeInsets:fixedSize:needFixedWidth:;
- (BOOL)needFixedWidth;
- (void)redoLayout;
- (void)redrawStrokeIfNeeded;
- (void)runDefaultDismissAnimationWithCompletion:;
- (void)setAttributedBubble:;
- (void)setBackgroundTransparent;
- (void)setIconViewEdgeInsets:;
- (void)setNeedFixedWidth:;
- (void)setTapToDismiss:;
- (void)setUseAdjustmentAsOffset:;
- (void)setUseContainerToAdjustBodyFrame:;
- (void)syncStatusWithAnchor;
- (BOOL)tapToDismiss;
- (void)tapToDismissAction;
- (BOOL)useAdjustmentAsOffset;
- (BOOL)useContainerToAdjustBodyFrame;
- (id)contentOffset;
- (void)setEdgeInsets:;
- (unsigned long long)direction;
- (id)textLabel;
- (void)setContentOffset:;
- (void)setDirection:;
- (void)dealloc;
- (void)layoutSubviews;
- (id)iconView;
- (void)setIconView:;
- (void)observeValueForKeyPath:ofObject:change:context:;
- (void)setFixedSize:;
- (id)anchorPoint;
- (id)edgeInsets;
- (id)sizeThatFits:;
- (void).cxx_destruct;
- (id)tapGesture;
- (void)setNumberOfLines:;
- (void)setTextAlignment:;
- (id)fixedSize;
- (void)setAnchorPoint:;
- (id)anchorView;
- (void)setAnchorView:;
- (void)setTextLabel:;
- (id)bubbleView;
- (void)setBubbleView:;
- (void)setTapGesture:;
- (id)bubbleImageView;
+ (id)bubbleWithAttributedContent:direction:anchorAdjustment:bubbleImage:image9ScaleInsets:edgeInsets:fixedSize:needFixedWidth:;
+ (id)bubbleWithContent:direction:anchorAdjustment:bubbleImage:image9ScaleInsets:edgeInsets:font:color:fixedSize:;
+ (id)bubbleWithContent:direction:anchorAdjustment:cornerAdjustment:fixedSize:isDarkBackGround:;
+ (id)bubbleWithContent:direction:anchorAdjustment:isDarkBackGround:;
+ (id)bubbleWithContent:direction:isDarkBackGround:;
+ (id)bubbleWithContent:withIconView:iconViewInsets:direction:anchorAdjustment:cornerAdjustment:fixedSize:isDarkBackGround:;
+ (id)bubbleWithCustomView:direction:edgeInsets:anchorAdjustment:cornerAdjustment:isDarkBackGround:;
+ (id)bubbleWithCustomView:direction:edgeInsets:anchorAdjustment:isDarkBackGround:;
@end
