@interface AWEIMConversationPuller : NSObject
@property (nonatomic) q nextCursor;
@property (nonatomic) q createNextCursor;
@property (nonatomic) q joinNextCursor;
@property (nonatomic) NSArray shareModelList;
@property (nonatomic) NSArray createShareModelList;
@property (nonatomic) NSArray joinShareModelList;
@property (nonatomic) NSMutableSet conversationIdSetM;
@property (nonatomic) NSMutableSet createConversationIdSetM;
@property (nonatomic) NSMutableSet joinConversationIdSetM;
@property (nonatomic) NSArray conversationList;
@property (nonatomic) BOOL hasMoreCreate;
@property (nonatomic) @? fetchCreateAndJoinGroupsCompletion;
@property (nonatomic) BOOL hasMoreConvList;
- (id)chatDataManager;
- (BOOL)hasMoreConvList;
- (id)conversationIdSetM;
- (id)createConversationIdSetM;
- (long long)createNextCursor;
- (id)createShareModelList;
- (void)fetchAllGroupShareModelWithCompletion:;
- (id)fetchCreateAndJoinGroupsCompletion;
- (void)fetchGroupShareModelWithFetchCount:completion:;
- (void)fetchMyCreateGroupsAndJoinGroupsWithCompletion:;
- (void)fetchMyCreateGroupsWithCompletion:;
- (void)fetchMyJoinGroupsWithCompletion:;
- (void)fetchTopFortyGroup:;
- (BOOL)hasMoreCreate;
- (id)joinConversationIdSetM;
- (long long)joinNextCursor;
- (id)joinShareModelList;
- (long long)nextCursor;
- (void)setConversationIdSetM:;
- (void)setConversationList:;
- (void)setCreateConversationIdSetM:;
- (void)setCreateNextCursor:;
- (void)setCreateShareModelList:;
- (void)setFetchCreateAndJoinGroupsCompletion:;
- (void)setHasMoreConvList:;
- (void)setHasMoreCreate:;
- (void)setJoinConversationIdSetM:;
- (void)setJoinNextCursor:;
- (void)setJoinShareModelList:;
- (void)setNextCursor:;
- (void)setShareModelList:;
- (id)shareModelList;
- (id)init;
- (void).cxx_destruct;
- (id)conversationList;
@end
