@interface AWEIMSharePanelExtension : NSObject
@property (nonatomic) AWEShareContext context;
@property (nonatomic) UIViewController<AWESharePanel> sharePanel;
@property (nonatomic) AWEIMTranspondListViewController transpondVC;
@property (nonatomic) AWEIMShareMutiselectViewController mutiselectVC;
@property (nonatomic) NSArray shareModels;
@property (nonatomic) BOOL authorSharingNonpublicAweme;
@property (nonatomic) NSString multiselectShareText;
@property (nonatomic) BOOL animatingMultiselectVC;
@property (nonatomic) BOOL isFetchingIronManShareInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)mutiselectVCconfirmToBindPhone:;
- (void)setAuthorSharingNonpublicAweme:;
- (void)transpondListViewShareFinished:;
- (void)setShareModels:;
- (void)setTranspondVC:;
- (void)transpondListViewDidSelectMore:;
- (void)dismissWithMultiselectAnimated:completion:;
- (BOOL)isAnimatingMultiselectVC;
- (BOOL)isAuthorSharingNonpublicAweme;
- (BOOL)isFetchingIronManShareInfo;
- (id)multiselectShareText;
- (void)multiselectVCRequestDismissal:completion:;
- (id)mutiselectVC;
- (void)mutiselectVCIsHidden:hasSentMessage:shareList:;
- (id)p_adjustedDataListIfNeeded:aweModel:;
- (void)p_transpondListView:didSelectedShareModel:hasMore:;
- (void)setAnimatingMultiselectVC:;
- (void)setIsFetchingIronManShareInfo:;
- (void)setMultiselectShareText:;
- (void)setMutiselectVC:;
- (void)setSharePanel:;
- (id)shareModels;
- (id)sharePanel;
- (void)sharePanelDidDisappear:;
- (void)sharePanelWillAppear:;
- (void)sharePanelWillDisappear:;
- (void)showMultiselectWithShareModel:transpondListView:hasMore:;
- (void)showMultiselectWithShareModel:transpondListView:hasMore:completion:;
- (void)showTranspondWithModels:hasMore:;
- (void)startFetchingTranspondModels;
- (void)transpondListView:didSelectedShareModel:hasMore:;
- (void)transpondListViewRequestDismissal:completion:;
- (id)transpondVC;
- (id)context;
- (void).cxx_destruct;
- (void)setContext:;
+ (id)extensionWithContext:;
@end
