@interface AWEIMProjectXConfig : IESIMBaseApiModel
@property (nonatomic) AWEIMBannerIconConfig im_x_profile_send_msg_btn_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_profile_more_send_msg_btn_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_contact_send_msg_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_chat_no_unread_msg_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_chat_list_banner_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_chat_list_banner_bg_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_story_detail_input_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_share_board_im_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_publish_board_im_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_share_board_im_red_envelope_icon_config;
@property (nonatomic) AWEIMBannerIconConfig im_x_story_response_my_story_icon_config;
@property (nonatomic) NSString im_x_profile_send_msg_btn_icon;
@property (nonatomic) NSString im_x_profile_more_send_msg_btn_icon;
@property (nonatomic) NSString im_x_contact_send_msg_icon;
@property (nonatomic) NSString im_x_alert_install_profile_title;
@property (nonatomic) NSString im_x_alert_install_transfer_title;
@property (nonatomic) NSString im_x_story_detail_input_icon;
@property (nonatomic) NSString im_x_share_board_im_icon;
@property (nonatomic) NSString im_x_share_board_im_title;
@property (nonatomic) NSString im_x_publish_board_im_icon;
@property (nonatomic) NSString im_x_chat_no_unread_msg_title;
@property (nonatomic) Q im_x_chat_subtitle_style;
@property (nonatomic) NSString im_x_chat_msg_subtitle;
@property (nonatomic) NSString im_x_chat_no_unread_msg_icon;
@property (nonatomic) NSString im_x_chat_installed_button_title;
@property (nonatomic) NSString im_x_chat_no_installed_button_title;
@property (nonatomic) Q im_x_chat_list_style;
@property (nonatomic) NSString im_x_story_detail_input_placeholder;
@property (nonatomic) NSString im_x_chat_list_banner_icon;
@property (nonatomic) NSString im_x_chat_list_banner_bg;
@property (nonatomic) NSString im_x_share_board_im_red_envelope_icon;
@property (nonatomic) NSString im_x_videoRedEnvelopeMessage;
@property (nonatomic) NSString im_x_redEnvelopeMessage;
@property (nonatomic) NSString im_x_tail_install_title;
@property (nonatomic) NSString im_x_story_response_my_story_icon;
- (id)im_x_share_board_im_icon_config;
- (id)im_x_chat_list_banner_bg_config;
- (id)im_x_alert_install_profile_title;
- (id)im_x_alert_install_transfer_title;
- (id)im_x_chat_installed_button_title;
- (id)im_x_chat_list_banner_bg;
- (id)im_x_chat_list_banner_icon;
- (id)im_x_chat_list_banner_icon_config;
- (unsigned long long)im_x_chat_list_style;
- (id)im_x_chat_msg_subtitle;
- (id)im_x_chat_no_installed_button_title;
- (id)im_x_chat_no_unread_msg_icon;
- (id)im_x_chat_no_unread_msg_icon_config;
- (id)im_x_chat_no_unread_msg_title;
- (unsigned long long)im_x_chat_subtitle_style;
- (id)im_x_contact_send_msg_icon;
- (id)im_x_contact_send_msg_icon_config;
- (id)im_x_profile_more_send_msg_btn_icon;
- (id)im_x_profile_more_send_msg_btn_icon_config;
- (id)im_x_profile_send_msg_btn_icon;
- (id)im_x_profile_send_msg_btn_icon_config;
- (id)im_x_publish_board_im_icon;
- (id)im_x_publish_board_im_icon_config;
- (id)im_x_redEnvelopeMessage;
- (id)im_x_share_board_im_icon;
- (id)im_x_share_board_im_red_envelope_icon;
- (id)im_x_share_board_im_red_envelope_icon_config;
- (id)im_x_share_board_im_title;
- (id)im_x_story_detail_input_icon;
- (id)im_x_story_detail_input_icon_config;
- (id)im_x_story_detail_input_placeholder;
- (id)im_x_story_response_my_story_icon;
- (id)im_x_story_response_my_story_icon_config;
- (id)im_x_tail_install_title;
- (id)im_x_videoRedEnvelopeMessage;
- (void)setIm_x_alert_install_profile_title:;
- (void)setIm_x_alert_install_transfer_title:;
- (void)setIm_x_chat_installed_button_title:;
- (void)setIm_x_chat_list_banner_bg_config:;
- (void)setIm_x_chat_list_banner_icon_config:;
- (void)setIm_x_chat_list_style:;
- (void)setIm_x_chat_msg_subtitle:;
- (void)setIm_x_chat_no_installed_button_title:;
- (void)setIm_x_chat_no_unread_msg_icon_config:;
- (void)setIm_x_chat_no_unread_msg_title:;
- (void)setIm_x_chat_subtitle_style:;
- (void)setIm_x_contact_send_msg_icon_config:;
- (void)setIm_x_profile_more_send_msg_btn_icon_config:;
- (void)setIm_x_profile_send_msg_btn_icon_config:;
- (void)setIm_x_publish_board_im_icon_config:;
- (void)setIm_x_share_board_im_icon_config:;
- (void)setIm_x_share_board_im_red_envelope_icon_config:;
- (void)setIm_x_story_detail_input_icon_config:;
- (void)setIm_x_story_detail_input_placeholder:;
- (void)setIm_x_story_response_my_story_icon_config:;
- (void).cxx_destruct;
+ (id)im_x_chat_list_banner_bg_configJSONTransformer;
+ (id)im_x_chat_list_banner_icon_configJSONTransformer;
+ (id)im_x_chat_no_unread_msg_icon_configJSONTransformer;
+ (id)im_x_contact_send_msg_icon_configJSONTransformer;
+ (id)im_x_profile_more_send_msg_icon_configJSONTransformer;
+ (id)im_x_profile_send_msg_btn_icon_configJSONTransformer;
+ (id)im_x_publish_board_im_icon_configJSONTransformer;
+ (id)im_x_share_board_im_icon_configJSONTransformer;
+ (id)im_x_share_board_im_red_envelope_icon_configJSONTransformer;
+ (id)im_x_story_detail_input_icon_configJSONTransformer;
+ (id)im_x_story_response_my_story_icon_configJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
