@interface AWEIMNewAwemeMessageTableViewCell : AWEIMSystemMessageTableViewCell
@property (nonatomic) UIView bubbleView;
@property (nonatomic) UIImageView awemePlayIconImageView;
@property (nonatomic) UIImageView awemeCoverImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UILabel detailLabel;
@property (nonatomic) IESIMUILoadingView loadingView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)awemeID;
- (id)awemeCoverImageView;
- (id)awemePlayIconImageView;
- (void)configWithMessage:;
- (id)displayBubbleView;
- (id)displayImageView;
- (void)endAnimationForLoadingAwemeModel;
- (id)menuTargetView;
- (void)p_updateUIWithNewAwemeMessage:;
- (void)setAwemeCoverImageView:;
- (void)setAwemePlayIconImageView:;
- (void)startAnimationForLoadingAwemeModel;
- (void)tapOnCell:;
- (void)setTitleLabel:;
- (void).cxx_destruct;
- (id)menuItems;
- (id)titleLabel;
- (void)setupUI;
- (id)detailLabel;
- (void)setDetailLabel:;
- (id)bubbleView;
- (void)setBubbleView:;
- (id)loadingView;
- (void)setLoadingView:;
- (id)playerContainerView;
+ (id)contentSizeWithMesasge:;
+ (id)identifier;
@end
