@interface AWENetTaskConfig : NSObject
@property (nonatomic) BOOL dispatchEnabled;
@property (nonatomic) double maxDurationForWaitngFeed;
@property (nonatomic) double sparseDelayTime;
@property (nonatomic) double feedReadyTaskInterval;
@property (nonatomic) double sparseTaskInterval;
@property (nonatomic) double idleTaskInterval;
@property (nonatomic) NSArray droppedTasks;
@property (nonatomic) NSArray immediatelyTasks;
@property (nonatomic) NSArray feedReadyTasks;
@property (nonatomic) NSArray sparseTasks;
@property (nonatomic) NSArray idleTasks;
@property (nonatomic) NSArray allowAfterFeedReadyTasks;
- (BOOL)dispatchEnabled;
- (void)setSparseTasks:;
- (double)sparseDelayTime;
- (id)allowAfterFeedReadyTasks;
- (id)droppedTasks;
- (double)feedReadyTaskInterval;
- (id)feedReadyTasks;
- (double)idleTaskInterval;
- (id)idleTasks;
- (id)immediatelyTasks;
- (double)maxDurationForWaitngFeed;
- (void)setAllowAfterFeedReadyTasks:;
- (void)setDispatchEnabled:;
- (void)setDroppedTasks:;
- (void)setFeedReadyTaskInterval:;
- (void)setFeedReadyTasks:;
- (void)setIdleTaskInterval:;
- (void)setIdleTasks:;
- (void)setImmediatelyTasks:;
- (void)setMaxDurationForWaitngFeed:;
- (void)setSparseDelayTime:;
- (void)setSparseTaskInterval:;
- (double)sparseTaskInterval;
- (id)sparseTasks;
- (id)init;
- (void).cxx_destruct;
+ (id)config;
@end
