@interface BDARVAppletBanner : BDARVBanner
@property (nonatomic) UIImageView avatar;
@property (nonatomic) UIButton actionButton;
@property (nonatomic) UILabel sourceLabel;
@property (nonatomic) UILabel adLabel;
@property (nonatomic) UILabel avatarLabel;
@property (nonatomic) UIView topBorder;
@property (nonatomic) UIView bottomBorder;
@property (nonatomic) BOOL is4dy;
- (void)actionBtnClick:;
- (id)adLabel;
- (void)setSourceLabel:;
- (void)sendBannerEventWithLabel:refer:;
- (void)setAvatarLabel:;
- (id)avatarLabel;
- (void)clickTimeMonitor;
- (id)getDefaultAvatarImage;
- (id)initWithFrame:source:;
- (BOOL)is4dy;
- (void)layoutComponents4DY;
- (id)referString:;
- (void)resizeLayout;
- (void)sendBannerEventWithLabel:;
- (void)setAdLabel:;
- (void)setIs4dy:;
- (void)tapAction:forEvent:;
- (void)useCustomAdLabel;
- (void)traitCollectionDidChange:;
- (void).cxx_destruct;
- (id)avatar;
- (void)setAvatar:;
- (id)actionButton;
- (void)setActionButton:;
- (id)sourceLabel;
- (id)topBorder;
- (id)bottomBorder;
- (void)setTopBorder:;
- (void)setBottomBorder:;
- (void)updateUI:;
@end
