@interface BDARVCardViewContainer : UIView
@property (nonatomic) NSArray feedAdModels;
@property (nonatomic) BDARVSourceModel sourceModel;
@property (nonatomic) BDARVFeedADModel feedAdModel;
@property (nonatomic) q adType;
@property (nonatomic) Q loadState;
@property (nonatomic) Q cardViewAdType;
@property (nonatomic) BDARVPatchADModel patchAdModel;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} layoutFrame;
@property (nonatomic) BOOL isVideoMute;
@property (nonatomic) UIColor btnHighlightColor;
@property (nonatomic) UIColor btnNormalColor;
@property (nonatomic) BDARVCardView innerCardView;
@property (nonatomic) NSDictionary playerConfig;
@property (nonatomic) <BDARVCardViewContainerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)isVerticalVideo;
- (void)setIsVideoMute:;
- (void)setLayoutFrame:;
- (void)cardViewCloseAd;
- (void)cardViewDidClickBannerWithInfo:;
- (void)setFeedAdModel:;
- (id)btnHighlightColor;
- (id)btnNormalColor;
- (unsigned long long)cardViewAdType;
- (void)cardViewDidClickCardViewButtonWithInfo:;
- (void)cardViewDidClickCardViewWithInfo:;
- (void)cardViewDidClickCloseWithInfo:;
- (void)cardViewDidClickFullScreen:completed:;
- (void)cardViewDidClickVideoWithInfo:;
- (void)cardViewDidContentResize:info:;
- (void)cardViewDidLoadFailWithError:;
- (void)cardViewDidLoadSuccess;
- (void)cardViewLoadVideoError;
- (void)cardViewMuteBtnClick:;
- (void)cardViewPreloadFormWithInfo:;
- (void)cardViewPreloadMPWithInfo:;
- (void)cardViewRenderVideoStart;
- (void)cardViewReportAction:adModel:;
- (void)cardViewVideoAdDidFinish;
- (void)cardViewWillStartLoad;
- (id)feedAdModel;
- (id)feedAdModels;
- (BOOL)handleAppstoreClosedLoopWith:;
- (void)hideCloseBtn;
- (id)innerCardView;
- (void)innerLoadContent;
- (void)innerLoadPatchContent;
- (BOOL)isVideoMute;
- (void)layoutWithFrame:;
- (void)layoutWithOrigin:;
- (void)layoutWithWidth:;
- (id)loadAdModuleFromLocal;
- (id)loadModuleWithAdType:;
- (id)loadNovelAdModuleFromLocal:;
- (id)loadPatchAdModuleFromLocal:;
- (id)patchAdModel;
- (id)playerConfig;
- (void)sendCardViewEventWithLabel:;
- (void)sendCardViewEventWithTag:label:refer:;
- (void)sendCardViewEventWithTag:label:refer:extra:;
- (void)sendShowEvent;
- (void)sendShowOverEvent:;
- (void)setBtnHighlightColor:;
- (void)setBtnNormalColor:;
- (void)setCardViewAdType:;
- (void)setFeedAdModels:;
- (void)setInnerCardView:;
- (void)setPatchAdModel:;
- (void)setPlayerConfig:;
- (void)dealloc;
- (unsigned long long)loadState;
- (void)play;
- (void)hide;
- (void)setDelegate:;
- (void)stop;
- (long long)adType;
- (BOOL)hasVideo;
- (void)close;
- (void)show;
- (void)resume;
- (id)delegate;
- (void).cxx_destruct;
- (void)pause;
- (id)layoutFrame;
- (BOOL)hasType:;
- (id)sourceModel;
- (void)enterFullScreen;
- (void)exitFullScreen;
- (void)loadContent;
- (void)setAdType:;
- (void)setSourceModel:;
- (void)setLoadState:;
+ (void)bannerPreloadSuccessWithSource:adType:duration:;
+ (long long)cacheAdCount:;
+ (long long)cacheAdCountAdFrom:;
+ (void)clearCacheAdFrom:;
+ (id)getBDARVCardViewContainer:feedAdModels:delegate:;
+ (id)getBDARVNovelCardViewContainer:source:delegate:;
+ (id)getBDARVPatchCardViewContainer:source:delegate:;
+ (id)innerGetBDARVCardViewContainer:feedAdModels:delegate:;
+ (id)innerGetBDARVNovelCardViewContainer:source:delegate:;
+ (id)innerGetBDARVPatchCardViewContainer:source:delegate:;
+ (void)loadAds:source:completed:;
+ (void)loadPatchAds:source:completed:;
+ (long long)patchCacheAdCountCreatorID:;
+ (void)startPreload:;
@end
