@interface BDARVVideoAlertView : UIView
@property (nonatomic) UIButton sureAlertButton;
@property (nonatomic) UIButton cancelAlertButton;
@property (nonatomic) UIButton closeAlertButton;
@property (nonatomic) UILabel titleAlertLabel;
@property (nonatomic) UIImageView alertImageView;
@property (nonatomic) UIView alertView;
@property (nonatomic) @? cancelBlock;
@property (nonatomic) @? closeAlertBlock;
@property (nonatomic) Q status;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)closeAlertBlock;
- (id)sureAlertButton;
- (id)titleAlertLabel;
- (id)alertImageView;
- (id)cancelAlertButton;
- (void)cancelClose:;
- (id)closeAlertButton;
- (void)confirmClose:;
- (void)dismissFromTopViewController;
- (id)initWithAlertInfo:quitTitle:cancelComplete:closeComplete:;
- (void)refreshAlertFrame;
- (void)refreshUIWithAlertInfo:quitTitle:;
- (void)setAlertImageView:;
- (void)setCancelAlertButton:;
- (void)setCloseAlertBlock:;
- (void)setCloseAlertButton:;
- (void)setSureAlertButton:;
- (void)setTitleAlertLabel:;
- (void)showWithTopVC:topView:;
- (void)setStatus:;
- (unsigned long long)statusCode;
- (void)setCancelBlock:;
- (BOOL)prefersStatusBarHidden;
- (void)setAlertView:;
- (id)cancelBlock;
- (void).cxx_destruct;
- (unsigned long long)status;
- (id)alertView;
@end
