@interface BDDispatcherBase : NSObject
@property (nonatomic) NSURL commandURL;
@property (nonatomic) NSString scheme;
@property (nonatomic) NSString module;
@property (nonatomic) NSString action;
@property (nonatomic) NSString next;
@property (nonatomic) NSString delayTime;
@property (nonatomic) NSString backup;
@property (nonatomic) BDDispatcherBase backupDispatcher;
@property (nonatomic) double startTimeStamp;
@property (nonatomic) NSDictionary queryDict;
@property (nonatomic) NSDictionary paramDict;
@property (nonatomic) NSString oauthType;
@property (nonatomic) NSDictionary userInfo;
@property (nonatomic) @ sourceApplication;
@property (nonatomic) @ sourceWebView;
@property (nonatomic) NSURL sourceURL;
@property (nonatomic) NSString jsCallback;
@property (nonatomic) @? nativeCallback;
- (id)trimParaWithURLString:paraName:;
- (id)backup;
- (id)backupDispatcher;
- (id)commandURL;
- (id)jsCallback;
- (id)nativeCallback;
- (id)paramDict;
- (BOOL)parseCommandURL:;
- (id)parseQuery:;
- (id)parseSeniorScheme:;
- (id)queryDict;
- (void)setBackup:;
- (void)setBackupDispatcher:;
- (void)setCommandURL:;
- (void)setJsCallback:;
- (void)setNativeCallback:;
- (void)setParamDict:;
- (void)setQueryDict:;
- (void)setStartTimeStamp:;
- (id)next;
- (void)setNext:;
- (id)module;
- (id)initWithURL:;
- (void)setScheme:;
- (void)setSourceURL:;
- (id)userInfo;
- (id)scheme;
- (id)sourceURL;
- (void)setDelayTime:;
- (id)action;
- (id)debugDescription;
- (void)setAction:;
- (id)sourceApplication;
- (void)setUserInfo:;
- (void).cxx_destruct;
- (id)description;
- (void)setModule:;
- (id)delayTime;
- (void)setSourceApplication:;
- (id)sourceWebView;
- (void)setSourceWebView:;
- (id)parsePath:;
- (double)startTimeStamp;
- (id)oauthType;
+ (id)codeInfoWithStatus:;
+ (id)dispatcherWithString:;
+ (id)messageInfoWithStatus:;
+ (id)reponseWithStatus:data:;
+ (BOOL)accessInstanceVariablesDirectly;
@end
