@interface BDImageLargeSizeMonitor : NSObject
@property (nonatomic) BOOL monitorEnable;
@property (nonatomic) Q fileSizeLimit;
@property (nonatomic) Q memoryLimit;
@property (nonatomic) double viewResolutionScaleLimit;
@property (nonatomic) BOOL loadSuccess;
@property (nonatomic) NSURL imageURL;
@property (nonatomic) double fileSize;
@property (nonatomic) UIView requestView;
@property (nonatomic) UIImage requestImage;
@property (nonatomic) NSString bizTag;
@property (nonatomic) NSString sceneTag;
@property (nonatomic) NSString pageTag;
@property (nonatomic) @ userInfo;
- (void)setLoadSuccess:;
- (void)setRequestView:;
- (id)bd_getViewPath:;
- (id)bizTag;
- (unsigned long long)fileSizeLimit;
- (BOOL)monitorEnable;
- (id)pathIndexOfSameClass:child:;
- (id)requestImage;
- (id)requestView;
- (id)sceneTag;
- (void)setBizTag:;
- (void)setFileSizeLimit:;
- (void)setMonitorEnable:;
- (void)setPageTag:;
- (void)setRequestImage:;
- (void)setSceneTag:;
- (void)setViewResolutionScaleLimit:;
- (void)trackLargeImageMonitor;
- (double)viewResolutionScaleLimit;
- (double)fileSize;
- (id)init;
- (id)userInfo;
- (void)setFileSize:;
- (void)setUserInfo:;
- (void).cxx_destruct;
- (void)setMemoryLimit:;
- (void)setImageURL:;
- (unsigned long long)memoryLimit;
- (id)imageURL;
- (id)pageTag;
- (BOOL)loadSuccess;
@end
