@interface BDImageView : UIImageView
@property (nonatomic) BDAnimatedImagePlayer player;
@property (nonatomic) BDImage animateImage;
@property (nonatomic) BOOL settingImageByApp;
@property (nonatomic) NSMutableDictionary bdSetImageDelay;
@property (nonatomic) Q pauseForAutoAnimationControlOptions;
@property (nonatomic) BOOL isNotFirstAutoPlayAnimatedImage;
@property (nonatomic) BOOL infinityLoop;
@property (nonatomic) Q customLoop;
@property (nonatomic) BOOL animateEnable;
@property (nonatomic) BOOL frameCacheAutomatically;
@property (nonatomic) BOOL cacheAllFrame;
@property (nonatomic) Q currentAnimatedImageIndex;
@property (nonatomic) BOOL autoPlayAnimatedImage;
@property (nonatomic) BOOL hightAnimationControl;
@property (nonatomic) BOOL moveToWindowAnimationControl;
@property (nonatomic) Q singleAutoAnimationControlType;
@property (nonatomic) @? loopCompletionBlock;
@property (nonatomic) @? customLoopCompletionBlock;
@property (nonatomic) @? firstFramePlayBlock;
@property (nonatomic) @? delayFramePlayBlock;
@property (nonatomic) NSString animateRunLoopMode;
@property (nonatomic) BDAnimatedPreferredFrameRateRange animatedPreferredFrameRateRange;
@property (nonatomic) Q animationType;
@property (nonatomic) BOOL enableWaterLevel;
@property (nonatomic) double waterLevelDuration;
@property (nonatomic) BOOL bd_isOpenDownsample_delay;
@property (nonatomic) Q animationDelayType;
@property (nonatomic) Q animationDelayState;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)cj_loadGifAndOnceLoop:duration:;
- (BOOL)isAnimateEnable;
- (id)animatedPreferredFrameRateRange;
- (id)bdSetImageDelay;
- (BOOL)isNotFirstAutoPlayAnimatedImage;
- (void)_autoAnimationControlForStart:autoPlay:option:;
- (BOOL)_canPauseForAutoAnimationControl;
- (BOOL)_needAutoAnimationControl;
- (void)_tryPlayAnimateImage;
- (id)animateImage;
- (id)animateRunLoopMode;
- (unsigned long long)animationDelayState;
- (unsigned long long)animationDelayType;
- (BOOL)autoPlayAnimatedImage;
- (id)bd_baseImage;
- (BOOL)bd_isOpenDownsample_delay;
- (id)bd_setImageWithURL:alternativeURLs:placeholder:options:config:blocks:;
- (BOOL)cacheAllFrame;
- (void)cj_loadGifAndInfinityLoop:duration:;
- (void)cj_loadGifAndInfinityLoopWithURL:duration:;
- (void)cj_loadGifAndOnceLoopWithURL:duration:;
- (void)clearImageBuffer;
- (unsigned long long)currentAnimatedImageIndex;
- (unsigned long long)customLoop;
- (id)customLoopCompletionBlock;
- (id)delayFramePlayBlock;
- (BOOL)enableWaterLevel;
- (id)firstFramePlayBlock;
- (BOOL)frameCacheAutomatically;
- (BOOL)hightAnimationControl;
- (void)imagePlayer:didUpdateImage:index:;
- (void)imagePlayerDelayPlay:index:animationDelayType:animationDelayState:;
- (void)imagePlayerDidReachAllLoopEnd:;
- (void)imagePlayerDidReachEnd:;
- (void)imagePlayerStartPlay:;
- (BOOL)infinityLoop;
- (BOOL)isSettingImageByApp;
- (id)loopCompletionBlock;
- (BOOL)moveToWindowAnimationControl;
- (void)p_baseLoadGif:;
- (void)p_baseLoadGifWithURL:;
- (unsigned long long)pauseForAutoAnimationControlOptions;
- (void)setAnimateEnable:;
- (void)setAnimateImage:;
- (void)setAnimateRunLoopMode:;
- (void)setAnimatedPreferredFrameRateRange:;
- (void)setAnimationDelayState:;
- (void)setAnimationDelayType:;
- (void)setAutoPlayAnimatedImage:;
- (void)setBdSetImageDelay:;
- (void)setBd_isOpenDownsample_delay:;
- (void)setCacheAllFrame:;
- (void)setCurrentAnimatedImageIndex:;
- (void)setCustomLoop:;
- (void)setCustomLoopCompletionBlock:;
- (void)setDelayFramePlayBlock:;
- (void)setEnableWaterLevel:;
- (void)setFirstFramePlayBlock:;
- (void)setFrameCacheAutomatically:;
- (void)setHightAnimationControl:;
- (void)setImage:new:;
- (void)setInfinityLoop:;
- (void)setIsNotFirstAutoPlayAnimatedImage:;
- (void)setLoopCompletionBlock:;
- (void)setMoveToWindowAnimationControl:;
- (void)setPauseForAutoAnimationControlOptions:;
- (void)setSingleAutoAnimationControlType:;
- (void)setWaterLevelDuration:;
- (unsigned long long)singleAutoAnimationControlType;
- (double)waterLevelDuration;
- (unsigned long long)animationType;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setImage:;
- (id)initWithCoder:;
- (void)setAnimationType:;
- (void)startAnimating;
- (id)initWithFrame:;
- (void)stopAnimating;
- (void)startAnimation;
- (id)player;
- (void).cxx_destruct;
- (void)didMoveToWindow;
- (void)setPlayer:;
- (void)setHighlighted:;
- (void)setHidden:;
- (id)description;
- (void)pauseAnimation;
- (id)image;
- (void)stopAnimation;
+ (BOOL)autoAnimationControl;
+ (void)setAutoAnimationControl:;
+ (id)layerClass;
@end
