@interface BDLynxView : UIView
@property (nonatomic) BDLynxViewClient clientDelegate;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} lynxViewFrame;
@property (nonatomic) LynxConfig lynxConfig;
@property (nonatomic) BDLynxProvider lynxProvdier;
@property (nonatomic) NSString channel;
@property (nonatomic) NSString sessionID;
@property (nonatomic) @? lynxBuilderBlock;
@property (nonatomic) NSData data;
@property (nonatomic) NSData prefetchData;
@property (nonatomic) <BDLynxClientViewDelegate> lynxDelegate;
@property (nonatomic) NSString containerID;
@property (nonatomic) LynxView lynxView;
@property (nonatomic) <BDLImageLoaderProtocol> imageLoader;
@property (nonatomic) <LynxDynamicComponentFetcher> dynamicComponentFetcher;
@property (nonatomic) BDLynxViewBaseParams params;
@property (nonatomic) q widthMode;
@property (nonatomic) q heightMode;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)viewDidLoadFailedWithUrl:error:;
- (void)bdlynxViewLoadUrlFailed:;
- (void)bdlynxViewloadTemplateWithUrl:onComplete:;
- (id)dynamicComponentFetcher;
- (id)findViewWithName:;
- (long long)heightMode;
- (id)initWithFrame:builderBlock:;
- (id)loadCanvasImageWithURL:contextInfo:completion:;
- (id)loadImageWithURL:size:contextInfo:completion:;
- (void)loadLynxBaseParams:;
- (void)loadLynxWithParams:;
- (void)loadLynxWithParamsRender:render:;
- (void)loadParamsUsingRender:render:;
- (id)loadResourceWithURL:type:completion:;
- (id)lynxBuilderBlock;
- (id)lynxConfig;
- (id)lynxDelegate;
- (id)lynxProvdier;
- (id)lynxView;
- (id)lynxViewFrame;
- (void)p_loadParams:;
- (id)redirectURL:;
- (void)registerHandler:forMethod:;
- (void)registerModule:param:;
- (void)registerShadowNode:withName:;
- (void)registerUI:withName:;
- (void)reloadWithBaseParams:;
- (void)reloadWithBaseParams:data:;
- (void)setDynamicComponentFetcher:;
- (void)setHeightMode:;
- (void)setLynxBuilderBlock:;
- (void)setLynxConfig:;
- (void)setLynxDelegate:;
- (void)setLynxProvdier:;
- (void)setLynxView:;
- (void)setLynxViewFrame:;
- (void)setWidthAndHeightMode:;
- (void)setWidthMode:;
- (void)toastErrorMessage:forDuration:;
- (void)updateModuleData:;
- (void)viewDidChangeIntrinsicContentSize:;
- (void)viewDidConstructJSRuntime;
- (void)viewDidFinishLoadWithURL:;
- (void)viewDidFirstScreen;
- (void)viewDidPageUpdate;
- (void)viewDidRecieveError:;
- (void)viewDidStartLoading;
- (void)viewDidUpdate;
- (id)viewWithName:;
- (long long)widthMode;
- (void)setSessionID:;
- (void)reload;
- (void)setChannel:;
- (id)sessionID;
- (id)clientDelegate;
- (id)imageLoader;
- (id)channel;
- (id)containerID;
- (id)data;
- (void)setContainerID:;
- (id)prefetchData;
- (id)hitTest:withEvent:;
- (id)initWithFrame:;
- (void)updateData:;
- (void).cxx_destruct;
- (void)setData:;
- (void)registerModule:;
- (void)setClientDelegate:;
- (void)setImageLoader:;
- (id)params;
- (void)setParams:;
- (void)setPrefetchData:;
+ (id)defaultGroup;
@end
