@interface BDUGLuckyPrefetchManager : NSObject
@property (nonatomic) NSString loaderBiz;
@property (nonatomic) BOOL isH5Prefetch;
@property (nonatomic) <IESPrefetchLoaderProtocol> prefetchLoader;
@property (nonatomic) BDUGLuckyPrefetchCache storage;
@property (nonatomic) IESPrefetchThreadSafeDictionary requestDic;
@property (nonatomic) BOOL isPrefetching;
@property (nonatomic) NSHashTable delegates;
@property (nonatomic) NSString accessKey;
@property (nonatomic) NSArray channels;
@property (nonatomic) # capability;
@property (nonatomic) BDUGLuckyPrefetchConfig config;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)customConfigForProject:version:;
- (void)loader:logInfo:;
- (void)bindGeckoAccessKey:channels:;
- (void)cache:didSaveObjectForKey:;
- (id)currentPrefetchScript;
- (id)customCacheStorage;
- (id)initWithLoaderBiz:;
- (BOOL)isH5Prefetch;
- (BOOL)isPrefetching;
- (void)loader:didFinishFetchData:withStatus:error:;
- (void)loader:didFinishLoadConfig:withError:;
- (void)loader:didFinishPrefetchApi:withCacheStatus:;
- (void)loader:didFinishPrefetchOccasion:withError:;
- (void)loader:didFinishPrefetchSchema:withError:;
- (id)loaderBiz;
- (void)networkForRequest:completion:;
- (BOOL)paramValid:;
- (void)prefetchDataWithWebUrl:;
- (BOOL)prefetchEnable;
- (id)prefetchLoader;
- (void)requestDataWithParam:completion:;
- (id)requestDic;
- (void)setIsH5Prefetch:;
- (void)setIsPrefetching:;
- (void)setLoaderBiz:;
- (void)setPrefetchLoader:;
- (void)setRequestDic:;
- (void)addDelegate:;
- (id)channels;
- (id)init;
- (id)delegates;
- (void)setDelegates:;
- (void)dealloc;
- (void)setConfig:;
- (void)setStorage:;
- (id)storage;
- (void).cxx_destruct;
- (void)setChannels:;
- (id)config;
- (id)accessKey;
- (void)setAccessKey:;
- (Class)capability;
- (void)setCapability:;
+ (id)prefetchManagerForContainer:;
+ (id)prefetchStatusString:;
+ (id)sharedInstance;
@end
