@interface BDUGLuckyActivityTaskModel : BDUGLuckyJSONModel
@property (nonatomic) NSString taskType;
@property (nonatomic) NSString globalTaskId;
@property (nonatomic) NSString taskId;
@property (nonatomic) NSString activityId;
@property (nonatomic) NSString taskToken;
@property (nonatomic) NSString extra;
@property (nonatomic) NSString targetPage;
@property (nonatomic) NSDate lastPersistenceTime;
@property (nonatomic) NSDate taskStartDate;
@property (nonatomic) double expireTimeMs;
@property (nonatomic) NSString uniqueType;
@property (nonatomic) NSDictionary extraParams;
- (void)setExtraParams:;
- (double)expireTimeMs;
- (id)extraParams;
- (id)globalTaskId;
- (id)lastPersistenceTime;
- (void)setExpireTimeMs:;
- (void)setExtra:;
- (void)setGlobalTaskId:;
- (void)setLastPersistenceTime:;
- (void)setTaskStartDate:;
- (void)setTaskToken:;
- (void)setUniqueType:;
- (id)taskStartDate;
- (id)taskToken;
- (id)uniqueType;
- (id)extra;
- (id)taskType;
- (id)taskId;
- (void).cxx_destruct;
- (void)setTaskType:;
- (id)targetPage;
- (void)setTargetPage:;
- (id)activityId;
- (void)setActivityId:;
- (void)setTaskId:;
@end
