@interface BDUGLuckyStaticCommonInfo : BDUGLuckyBDModel
@property (nonatomic) BDUGLuckyShakeData shakeData;
@property (nonatomic) BDUGLuckyCancelData cancelData;
@property (nonatomic) BDUGLuckyLowUpdate lowUpdate;
@property (nonatomic) BDUGLuckyGlobalGecko gecko;
@property (nonatomic) BDUGLuckyDomain domain;
@property (nonatomic) BDUGLuckyFeRules feRules;
@property (nonatomic) NSDictionary pageDependency;
@property (nonatomic) NSArray<BDUGLuckySceneTimeInfo> sceneTimeInfos;
@property (nonatomic) BDUGLuckyCooling cooling;
@property (nonatomic) BDUGLuckyNotificationConfig notificationConfig;
@property (nonatomic) BDUGLuckyPreCongfig preConfig;
@property (nonatomic) NSDictionary extra;
- (id)feRules;
- (id)cooling;
- (id)cancelData;
- (id)gecko;
- (id)lowUpdate;
- (BOOL)modelCustomTransformFromDictionary:;
- (id)notificationConfig;
- (id)pageDependency;
- (id)preConfig;
- (id)sceneTimeInfos;
- (void)setCancelData:;
- (void)setCooling:;
- (void)setExtra:;
- (void)setFeRules:;
- (void)setGecko:;
- (void)setLowUpdate:;
- (void)setNotificationConfig:;
- (void)setPageDependency:;
- (void)setPreConfig:;
- (void)setSceneTimeInfos:;
- (void)setShakeData:;
- (id)shakeData;
- (id)extra;
- (id)initWithDictionary:error:;
- (void).cxx_destruct;
- (id)domain;
- (void)setDomain:;
+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@end
