@interface BDUGSyncCore : NSObject
@property (nonatomic) NSObject<OS_dispatch_source> pollTimer;
@property (nonatomic) NSObject<OS_dispatch_source> httpPollTimer;
@property (nonatomic) BOOL isRollback;
- (id)_buildPollData;
- (void)_dealWithACKPackets:did:uid:;
- (void)_dealWithCtrlProtocol;
- (void)_dealWithData:channel:;
- (void)_dealWithDataPackets:did:uid:channel:;
- (void)_dealWithSyncPackets:did:uid:;
- (id)_deliverSyncDataWithSynclogs:bucketMap:;
- (void)_monitorReceiveDataWithDataPackets:channel:;
- (void)_monitorSync;
- (void)_monitorSyncRetry;
- (void)_sendHttpMessage:;
- (void)_sendMessage:completion:;
- (void)_sendReportLogs:;
- (void)_startHttpSyncWithMessage:;
- (BOOL)_storageHistorySynclogs:;
- (void)deliverSyncLogWithBusinessID:callback:;
- (void)httpPollData;
- (id)httpPollTimer;
- (BOOL)isRollback;
- (void)onPushManagerConnectionStateChanged:;
- (void)onReceivedFrontierMessage:;
- (void)reportBusinessSyncLog;
- (void)setHttpPollTimer:;
- (void)setIsRollback:;
- (void)startHttpPoll;
- (void)startPoll;
- (void)startSyncData;
- (id)init;
- (void)dealloc;
- (void).cxx_destruct;
- (void)_sendMessage:;
- (id)pollTimer;
- (void)setPollTimer:;
+ (id)sharedCore;
@end
