@interface BDXBridgeAuthResult : NSObject
@property (nonatomic) BOOL isAuthorized;
@property (nonatomic) q reasonType;
@property (nonatomic) q methodAuthType;
@property (nonatomic) q groupAuthType;
@property (nonatomic) BDXBridgeAuthModelContentV2BizConfig bizConfig;
@property (nonatomic) BOOL hasMatchedRule;
@property (nonatomic) BOOL inIncludeMethods;
@property (nonatomic) q authProcessStage;
@property (nonatomic) NSString feId;
@property (nonatomic) q feAuthConfigSource;
@property (nonatomic) NSNumber packageVersion;
@property (nonatomic) NSDictionary requestTrackings;
- (long long)authProcessStage;
- (id)bizConfig;
- (long long)feAuthConfigSource;
- (id)feId;
- (long long)groupAuthType;
- (BOOL)hasMatchedRule;
- (BOOL)inIncludeMethods;
- (long long)methodAuthType;
- (id)packageVersion;
- (id)requestTrackings;
- (void)setAuthProcessStage:;
- (void)setBizConfig:;
- (void)setFeAuthConfigSource:;
- (void)setFeId:;
- (void)setGroupAuthType:;
- (void)setHasMatchedRule:;
- (void)setInIncludeMethods:;
- (void)setMethodAuthType:;
- (void)setPackageVersion:;
- (void)setRequestTrackings:;
- (void)setReasonType:;
- (id)init;
- (long long)reasonType;
- (BOOL)isAuthorized;
- (void)setIsAuthorized:;
- (void).cxx_destruct;
- (id)description;
+ (id)authResultReasonDescriptionForAuthMode:;
+ (id)authResultReasonDescriptionForAuthResultReasonType:;
@end
