@interface BDXBridgeCallMessage : NSObject
@property (nonatomic) WKWebView wkWebView;
@property (nonatomic) NSString methodName;
@property (nonatomic) NSString methodNamespace;
@property (nonatomic) NSString methodType;
@property (nonatomic) NSDictionary params;
@property (nonatomic) NSString callbackID;
@property (nonatomic) NSString JSSDKVersion;
@property (nonatomic) NSString protocolVersion;
@property (nonatomic) NSString iframeURLString;
@property (nonatomic) NSURL invokeURL;
@property (nonatomic) NSNumber isMainFrame;
@property (nonatomic) NSString frameURL;
@property (nonatomic) NSString containerType;
@property (nonatomic) NSString aid;
@property (nonatomic) NSNumber authStatus;
@property (nonatomic) NSDictionary rawData;
@property (nonatomic) NSNumber sendTimeStamp;
@property (nonatomic) NSNumber receivedTimeStamp;
@property (nonatomic) NSNumber requestDecodeDuration;
@property (nonatomic) NSString messageUUID;
@property (nonatomic) NSString appID;
@property (nonatomic) BOOL backgroundThreadCall;
- (id)JSSDKVersion;
- (id)iframeURLString;
- (id)methodNamespace;
- (void)setIsMainFrame:;
- (BOOL)backgroundThreadCall;
- (id)callbackID;
- (id)invokeURL;
- (id)methodType;
- (id)receivedTimeStamp;
- (id)requestDecodeDuration;
- (id)sendTimeStamp;
- (void)setBackgroundThreadCall:;
- (void)setCallbackID:;
- (void)setFrameURL:;
- (void)setIframeURLString:;
- (void)setInvokeURL:;
- (void)setJSSDKVersion:;
- (void)setMethodNamespace:;
- (void)setMethodType:;
- (void)setReceivedTimeStamp:;
- (void)setRequestDecodeDuration:;
- (void)setSendTimeStamp:;
- (void)setWkWebView:;
- (id)wkWebView;
- (id)protocolVersion;
- (void)setProtocolVersion:;
- (id)isMainFrame;
- (void)setRawData:;
- (id)messageUUID;
- (void)setAppID:;
- (id)appID;
- (void).cxx_destruct;
- (id)rawData;
- (id)params;
- (id)containerType;
- (void)setContainerType:;
- (void)setMessageUUID:;
- (void)setParams:;
- (id)frameURL;
- (id)methodName;
- (void)setAid:;
- (id)aid;
- (id)authStatus;
- (void)setAuthStatus:;
- (void)setMethodName:;
+ (id)recevieMessageFromWebViewWithCallData:;
@end
