@interface BDXBridgeAppShareMethodParamModel : BDXBridgeModel
@property (nonatomic) NSString share_title;
@property (nonatomic) NSString share_desc;
@property (nonatomic) NSString share_link;
@property (nonatomic) NSString share_weibo_desc;
@property (nonatomic) NSString share_link_desc;
@property (nonatomic) NSString system_share_link;
@property (nonatomic) NSString share_douyin_title;
@property (nonatomic) NSString data_URL;
@property (nonatomic) NSString activity_name;
@property (nonatomic) NSString douyin_share_id;
@property (nonatomic) BDXBridgeAppShareShareCover share_cover;
@property (nonatomic) NSArray platforms;
@property (nonatomic) NSArray douyin_publish_hash_tags;
@property (nonatomic) q content_type;
- (id)douyin_share_id;
- (void)setShare_title:;
- (void)setShare_cover:;
- (id)share_link_desc;
- (id)activity_name;
- (id)data_URL;
- (id)douyin_publish_hash_tags;
- (void)setActivity_name:;
- (void)setData_URL:;
- (void)setDouyin_publish_hash_tags:;
- (void)setDouyin_share_id:;
- (void)setPlatforms:;
- (void)setShare_desc:;
- (void)setShare_douyin_title:;
- (void)setShare_link:;
- (void)setShare_link_desc:;
- (void)setShare_weibo_desc:;
- (void)setSystem_share_link:;
- (id)share_cover;
- (id)share_desc;
- (id)share_douyin_title;
- (id)share_link;
- (id)share_title;
- (id)share_weibo_desc;
- (id)system_share_link;
- (void).cxx_destruct;
- (long long)content_type;
- (void)setContent_type:;
- (id)platforms;
+ (id)requiredKeyPaths;
+ (id)share_coverJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
