@interface BDXContext : NSObject
@property (nonatomic) BDXMonitor lifeCycleMonitor;
@property (nonatomic) NSNumber kitFrameWidth;
@property (nonatomic) NSNumber kitFrameHeight;
@property (nonatomic) BOOL openFromXRouter;
@property (nonatomic) q viewType;
@property (nonatomic) NSNumber bdxLogPid;
@property (nonatomic) {CGSize=dd} preferMetrixScreenSize;
@property (nonatomic) NSMapTable weakObjHolder;
@property (nonatomic) NSMapTable strongObjHolder;
@property (nonatomic) NSMapTable dupObjHolder;
@property (nonatomic) BOOL freezeFlag;
@property (nonatomic) NSString sessionID;
@property (nonatomic) BDXUIContext uiContext;
@property (nonatomic) BDXContainerContext containerContext;
@property (nonatomic) BDXLynxOnlyContext lynxOnlyContext;
@property (nonatomic) BDXWebOnlyContext webOnlyContext;
@property (nonatomic) BDXSchemeContext schemeContext;
@property (nonatomic) BDXResourceLoaderContext resourceLoaderContext;
@property (nonatomic) BDXHybridMonitorContext hybridMonitorContext;
@property (nonatomic) @ globalProps;
@property (nonatomic) NSString accessKey;
@property (nonatomic) NSString aid;
@property (nonatomic) NSString bid;
@property (nonatomic) NSString sdkVersion;
@property (nonatomic) NSDictionary monitorCommonParams;
@property (nonatomic) NSString originURL;
@property (nonatomic) NSDictionary extraInfo;
@property (nonatomic) @? getGlobalPropsBlock;
@property (nonatomic) NSString appThemeReloadKey;
@property (nonatomic) NSNumber forceHttps;
@property (nonatomic) NSArray hostAllowList;
@property (nonatomic) BOOL shouldUseAnniePro;
@property (nonatomic) NSString apAppId;
@property (nonatomic) NSString prefetchBusiness;
@property (nonatomic) NSDictionary prefetchInitData;
@property (nonatomic) NSArray preloadPathsForForceNetwork;
@property (nonatomic) NSArray preloadPathsForForbiddenRouter;
@property (nonatomic) NSDictionary preloadResources;
@property (nonatomic) BDXResourceLoaderProcessorConfig processorConfig;
@property (nonatomic) BDXSeperateRenderContext seperateRenderContext;
@property (nonatomic) NSNumber useSingletonResourceLoader;
@property (nonatomic) NSArray imageCacheSharedDomainList;
@property (nonatomic) BDXResourceLoaderConfig loaderConfig;
@property (nonatomic) <BDXPoolProtocol> xpool;
@property (nonatomic) BDXPreCreateTemplateRenderContext preCreateTemplateRenderContext;
@property (nonatomic) <BDXPerfMonitorProtocol> perfMonitor;
@property (nonatomic) BDXTracertMonitor tracertMonitor;
@property (nonatomic) NSNumber trackFrequency;
@property (nonatomic) NSNumber enableMonitor;
@property (nonatomic) @? localInitDataBlock;
@property (nonatomic) <BDXContainerLifecycleProtocol> containerLifecycleDelegate;
@property (nonatomic) <BDXHostNavigationProtocol> hostNavigationDelegate;
@property (nonatomic) NSString containerName;
@property (nonatomic) @? hasAgreedPrivacy;
@property (nonatomic) <BDXPolicyProtocol> policyService;
@property (nonatomic) BOOL falconSchemeHandlerEnable;
@property (nonatomic) BOOL falconEnable;
@property (nonatomic) # pageClazz;
@property (nonatomic) # schemeParamClazz;
@property (nonatomic) # bridgeClass;
@property (nonatomic) NSArray bridgeProviderClasses;
@property (nonatomic) <BDXBridgeProviderProtocol> bridgeProvider;
@property (nonatomic) NSArray xBridgeMethods;
@property (nonatomic) NSArray xBridgeMethodInstances;
@property (nonatomic) <BDXBridgeNetworkServiceProtocol> networkService;
@property (nonatomic) NSArray bridgesDispatchDirectly;
@property (nonatomic) NSDictionary additionalRequestParams;
@property (nonatomic) BOOL enableWebContentPreloadOffline;
@property (nonatomic) NSData templateData;
@property (nonatomic) NSDictionary initialData;
@property (nonatomic) NSArray customUIElements;
@property (nonatomic) NSString initialDataMarkState;
@property (nonatomic) NSNumber disableAutoExpose;
@property (nonatomic) NSNumber enableRadonCompatible;
@property (nonatomic) @? rawViewBuilderBlock;
@property (nonatomic) BOOL enableSSR;
@property (nonatomic) @ monitorSettingModel;
@property (nonatomic) BDXWebSecureLinkConfig secureLinkConfig;
@property (nonatomic) NSDictionary additionalRequestHeaderFields;
@property (nonatomic) NSArray appendCommonParamsHostAllowList;
@property (nonatomic) @? searchBlock;
@property (nonatomic) NSArray enableAdBlockAllowList;
@property (nonatomic) @? networkCommonParamsBlock;
@property (nonatomic) @? saveWebImage;
@property (nonatomic) NSString customUA;
@property (nonatomic) NSArray webInstancePlugins;
@property (nonatomic) WKWebViewConfiguration webViewConfig;
@property (nonatomic) BOOL enableADBlock;
@property (nonatomic) NSNumber widthMode;
@property (nonatomic) NSNumber heightMode;
@property (nonatomic) double fontScale;
@property (nonatomic) double viewZoom;
@property (nonatomic) double containerFontScale;
@property (nonatomic) UIView<BDXLoadingViewProtocol> loadingView;
@property (nonatomic) @? loadingViewBuilder;
@property (nonatomic) UIView<BDXLoadErrorViewProtocol> loadFailedView;
@property (nonatomic) @? failedViewBuilder;
@property (nonatomic) UIView<BDXNavigationBarProtocol> navBar;
@property (nonatomic) @? navBarReportHandle;
@property (nonatomic) @? navBarShareHandle;
@property (nonatomic) UIColor containerBackgroundColor;
@property (nonatomic) NSNumber containerStatusBarStyle;
@property (nonatomic) UIColor titleColor;
@property (nonatomic) UIColor lineColor;
@property (nonatomic) UIColor progressTintColor;
@property (nonatomic) @? appThemeBlock;
@property (nonatomic) NSString defaultPageTitle;
@property (nonatomic) NSNumber shouldAutorotate;
@property (nonatomic) NSNumber orientationMask;
@property (nonatomic) @? appFontScaleBlock;
@property (nonatomic) @? appViewZoomBlock;
@property (nonatomic) BDXSchemaParam schemaParams;
@property (nonatomic) NSArray schemaInterceptors;
@property (nonatomic) BOOL ignoreSchemaBid;
- (id)appendCommonParamsHostAllowList;
- (BOOL)ignoreSchemaBid;
- (id)lynxOnlyContext;
- (id)orientationMask;
- (void)setBid:;
- (void)setGlobalProps:;
- (void)setInitialData:;
- (id)strongObjHolder;
- (id)apAppId;
- (id)bid;
- (void)freeze:;
- (BOOL)openFromXRouter;
- (void)setBridgeClass:;
- (void)setPerfMonitor:;
- (void)setPreloadPathsForForceNetwork:;
- (void)setSearchBlock:;
- (void)setupSubContext;
- (id)__getPropertyWithKey:;
- (BOOL)__updatePropertyWithKey:value:;
- (id)additionalRequestHeaderFields;
- (id)appFontScaleBlock;
- (id)appThemeBlock;
- (id)appThemeReloadKey;
- (id)appViewZoomBlock;
- (void)attachSettings;
- (id)bdxLogPid;
- (Class)bridgeClass;
- (id)bridgeProvider;
- (id)bridgeProviderClasses;
- (id)bridgesDispatchDirectly;
- (double)containerFontScale;
- (id)containerLifecycleDelegate;
- (id)containerStatusBarStyle;
- (id)customUA;
- (id)customUIElements;
- (id)defaultPageTitle;
- (id)disableAutoExpose;
- (id)dupObjHolder;
- (BOOL)enableADBlock;
- (id)enableAdBlockAllowList;
- (id)enableMonitor;
- (id)enableRadonCompatible;
- (BOOL)enableSSR;
- (BOOL)enableWebContentPreloadOffline;
- (id)failedViewBuilder;
- (BOOL)falconEnable;
- (BOOL)falconSchemeHandlerEnable;
- (id)forceHttps;
- (BOOL)freezeFlag;
- (id)getGlobalPropsBlock;
- (id)getObjForKey:;
- (id)getObjForType:;
- (id)globalProps;
- (id)hasAgreedPrivacy;
- (id)heightMode;
- (id)hostAllowList;
- (id)hostNavigationDelegate;
- (id)hybridMonitorContext;
- (id)imageCacheSharedDomainList;
- (id)initialData;
- (id)initialDataMarkState;
- (BOOL)isMonitorEnabled;
- (BOOL)isWeakObjForKey:;
- (id)kitFrameHeight;
- (id)kitFrameWidth;
- (id)lifeCycleMonitor;
- (id)loadFailedView;
- (id)loaderConfig;
- (id)loadingViewBuilder;
- (id)localInitDataBlock;
- (void)mergeContext:;
- (void)mergeContext:shouldOverride:;
- (void)mergeGlobalCtxWithBid:;
- (id)monitorCommonParams;
- (id)monitorSettingModel;
- (id)navBarReportHandle;
- (id)navBarShareHandle;
- (id)networkCommonParamsBlock;
- (Class)pageClazz;
- (id)perfMonitor;
- (id)policyService;
- (id)preCreateTemplateRenderContext;
- (id)preferMetrixScreenSize;
- (id)prefetchBusiness;
- (id)prefetchInitData;
- (id)preloadPathsForForbiddenRouter;
- (id)preloadPathsForForceNetwork;
- (id)rawViewBuilderBlock;
- (void)registerCopyObj:forKey:;
- (void)registerCopyObj:forType:;
- (void)registerStrongObj:forKey:;
- (void)registerStrongObj:forType:;
- (void)registerWeakObj:forKey:;
- (void)registerWeakObj:forType:;
- (id)resourceLoaderContext;
- (id)saveWebImage;
- (id)schemaInterceptors;
- (id)schemaParams;
- (id)schemeContext;
- (Class)schemeParamClazz;
- (id)searchBlock;
- (id)secureLinkConfig;
- (id)seperateRenderContext;
- (void)setAdditionalRequestHeaderFields:;
- (void)setApAppId:;
- (void)setAppFontScaleBlock:;
- (void)setAppThemeBlock:;
- (void)setAppThemeReloadKey:;
- (void)setAppViewZoomBlock:;
- (void)setAppendCommonParamsHostAllowList:;
- (void)setBdxLogPid:;
- (void)setBridgeProvider:;
- (void)setBridgeProviderClasses:;
- (void)setBridgesDispatchDirectly:;
- (void)setContainerFontScale:;
- (void)setContainerLifecycleDelegate:;
- (void)setContainerStatusBarStyle:;
- (void)setCustomUA:;
- (void)setCustomUIElements:;
- (void)setDefaultPageTitle:;
- (void)setDisableAutoExpose:;
- (void)setDupObjHolder:;
- (void)setEnableADBlock:;
- (void)setEnableAdBlockAllowList:;
- (void)setEnableMonitor:;
- (void)setEnableRadonCompatible:;
- (void)setEnableSSR:;
- (void)setEnableWebContentPreloadOffline:;
- (void)setExtraInfo:;
- (void)setFailedViewBuilder:;
- (void)setFalconEnable:;
- (void)setFalconSchemeHandlerEnable:;
- (void)setForceHttps:;
- (void)setFreezeFlag:;
- (void)setGetGlobalPropsBlock:;
- (void)setHasAgreedPrivacy:;
- (void)setHeightMode:;
- (void)setHostAllowList:;
- (void)setHostNavigationDelegate:;
- (void)setHybridMonitorContext:;
- (void)setIgnoreSchemaBid:;
- (void)setImageCacheSharedDomainList:;
- (void)setInitialDataMarkState:;
- (void)setKitFrameHeight:;
- (void)setKitFrameWidth:;
- (void)setLifeCycleMonitor:;
- (void)setLoadFailedView:;
- (void)setLoaderConfig:;
- (void)setLoadingViewBuilder:;
- (void)setLocalInitDataBlock:;
- (void)setLynxOnlyContext:;
- (void)setMonitorCommonParams:;
- (void)setMonitorSettingModel:;
- (void)setNavBarReportHandle:;
- (void)setNavBarShareHandle:;
- (void)setNetworkCommonParamsBlock:;
- (void)setOpenFromXRouter:;
- (void)setOrientationMask:;
- (void)setPageClazz:;
- (void)setPolicyService:;
- (void)setPreCreateTemplateRenderContext:;
- (void)setPreferMetrixScreenSize:;
- (void)setPrefetchBusiness:;
- (void)setPrefetchInitData:;
- (void)setPreloadPathsForForbiddenRouter:;
- (void)setPreloadResources:;
- (void)setRawViewBuilderBlock:;
- (void)setResourceLoaderContext:;
- (void)setSaveWebImage:;
- (void)setSchemaInterceptors:;
- (void)setSchemaParams:;
- (void)setSchemeContext:;
- (void)setSchemeParamClazz:;
- (void)setSecureLinkConfig:;
- (void)setSeperateRenderContext:;
- (void)setShouldAutorotate:;
- (void)setShouldUseAnniePro:;
- (void)setStrongObjHolder:;
- (void)setTemplateData:;
- (void)setTracertMonitor:;
- (void)setTrackFrequency:;
- (void)setUiContext:;
- (void)setUseSingletonResourceLoader:;
- (void)setViewZoom:;
- (void)setWeakObjHolder:;
- (void)setWebInstancePlugins:;
- (void)setWebOnlyContext:;
- (void)setWebViewConfig:;
- (void)setWidthMode:;
- (void)setXBridgeMethodInstances:;
- (void)setXBridgeMethods:;
- (void)setXpool:;
- (BOOL)shouldUseAnniePro;
- (id)templateData;
- (id)tracertMonitor;
- (id)trackFrequency;
- (id)uiContext;
- (id)useSingletonResourceLoader;
- (double)viewZoom;
- (id)weakObjHolder;
- (id)webInstancePlugins;
- (id)webOnlyContext;
- (id)webViewConfig;
- (id)widthMode;
- (id)xBridgeMethodInstances;
- (id)xBridgeMethods;
- (id)xpool;
- (void)setSessionID:;
- (id)shouldAutorotate;
- (id)sessionID;
- (id)containerName;
- (id)init;
- (long long)viewType;
- (void)dealloc;
- (void)setContainerName:;
- (void)setProgressTintColor:;
- (id)lineColor;
- (void)setNetworkService:;
- (void)setTitleColor:;
- (id)titleColor;
- (void).cxx_destruct;
- (id)progressTintColor;
- (void)setLineColor:;
- (id)networkService;
- (id)copyWithZone:;
- (id)sdkVersion;
- (id)containerBackgroundColor;
- (id)accessKey;
- (void)setAccessKey:;
- (id)containerContext;
- (void)setContainerContext:;
- (double)fontScale;
- (void)setFontScale:;
- (id)originURL;
- (void)setOriginURL:;
- (id)processorConfig;
- (void)setProcessorConfig:;
- (id)preloadResources;
- (id)loadingView;
- (void)setLoadingView:;
- (void)setViewType:;
- (id)extraInfo;
- (void)setAid:;
- (id)aid;
- (void)setSdkVersion:;
- (void)setAdditionalRequestParams:;
- (id)additionalRequestParams;
- (void)setContainerBackgroundColor:;
- (id)navBar;
- (void)setNavBar:;
+ (id)mergeArray:to:override:;
+ (id)mergeDict:to:override:;
+ (id)mergeProp:to:override:;
+ (id)mergeTable:to:override:;
@end
