@interface BDXLynxVideoView : LynxUI
@property (nonatomic) NSDictionary paramsDict;
@property (nonatomic) BDXVideoPlayerVideoModel videoModel;
@property (nonatomic) NSMutableArray childrenView;
@property (nonatomic) BOOL hidden;
@property (nonatomic) double seekTime;
@property (nonatomic) BOOL needReplay;
@property (nonatomic) BOOL autoPlay;
@property (nonatomic) BOOL mute;
@property (nonatomic) BOOL isLoop;
@property (nonatomic) BOOL useSinglePlayer;
@property (nonatomic) BOOL needPreload;
@property (nonatomic) BOOL autoLifecycle;
@property (nonatomic) BOOL listenDeviceChange;
@property (nonatomic) NSNumber startTime;
@property (nonatomic) NSNumber volume;
@property (nonatomic) NSNumber rate;
@property (nonatomic) NSString posterURL;
@property (nonatomic) NSString fitMode;
@property (nonatomic) NSString control;
@property (nonatomic) NSDictionary logExtraDict;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)didBufferChange;
- (id)fitMode;
- (void)didStateChange:;
- (void)setNeedPreload:;
- (BOOL)useSinglePlayer;
- (void)__controlPlayerWithCommand:;
- (id)__resolveSrcAsJSON:;
- (id)__resolveSrcAsSchema:;
- (id)__resolveSrcAsUrl:;
- (void)__setupVideoModel:;
- (BOOL)autoLifecycle;
- (void)autoLifecycle:requestReset:;
- (void)autoPlay:requestReset:;
- (id)childrenView;
- (void)control:requestReset:;
- (void)didBufferChangeWithInfo:;
- (void)didDeviceChange:;
- (void)didError:;
- (void)didFullscreenChange:;
- (void)didSeek:;
- (void)didTimeUpdate:;
- (void)fetchByResourceManager:completionHandler:;
- (void)fitMode:requestReset:;
- (id)formatLogExtraDict:;
- (void)getDuration:withResult:;
- (void)layoutDidFinished;
- (BOOL)listenDeviceChange;
- (void)listenDeviceChange:requestReset:;
- (id)logExtraDict;
- (void)logExtraDict:requestReset:;
- (void)mute:requestReset:;
- (BOOL)needPreload;
- (BOOL)needReplay;
- (void)onListCellAppear:withList:;
- (void)onListCellDisappear:exist:withList:;
- (void)onListCellPrepareForReuse:withList:;
- (id)paramsDict;
- (id)posterURL;
- (void)posterURL:requestReset:;
- (void)preload:requestReset:;
- (void)rate:requestReset:;
- (void)schema:requestReset:;
- (void)setAutoLifecycle:;
- (void)setChildrenView:;
- (void)setFitMode:;
- (void)setIsLoop:;
- (void)setListenDeviceChange:;
- (void)setLogExtraDict:;
- (void)setNeedReplay:;
- (void)setParamsDict:;
- (void)setPosterURL:;
- (void)setRepeat:requestReset:;
- (void)setUseSinglePlayer:;
- (void)setVideoModel:;
- (void)startTime:requestReset:;
- (void)useSinglePlayer:requestReset:;
- (id)videoModel;
- (void)volume:requestReset:;
- (BOOL)mute;
- (void)setRate:;
- (id)init;
- (id)volume;
- (void)setVolume:;
- (id)rate;
- (void)setStartTime:;
- (id)startTime;
- (BOOL)hidden;
- (void)setMute:;
- (void).cxx_destruct;
- (BOOL)isLoop;
- (void)setHidden:;
- (void)setSeekTime:;
- (void)didEnd;
- (double)seekTime;
- (id)control;
- (void)setControl:;
- (void)didError;
- (BOOL)autoPlay;
- (void)setAutoPlay:;
- (id)createView;
- (BOOL)hasCustomLayout;
- (void)didPause;
- (void)didPlay;
+ (id)__lynx_prop_config__1051;
+ (id)__lynx_prop_config__1212;
+ (id)__lynx_prop_config__1573;
+ (id)__lynx_prop_config__1634;
+ (id)__lynx_prop_config__1695;
+ (id)__lynx_prop_config__1756;
+ (id)__lynx_prop_config__1817;
+ (id)__lynx_prop_config__1878;
+ (id)__lynx_prop_config__1989;
+ (id)__lynx_prop_config__20410;
+ (id)__lynx_prop_config__21011;
+ (id)__lynx_prop_config__21812;
+ (id)__lynx_prop_config__22413;
+ (id)__lynx_prop_config__23014;
+ (id)__lynx_prop_config__23515;
+ (id)__lynx_ui_method_config__24416;
+ (Class)fullScreenPlayerClz;
+ (void)lynxLazyLoad;
+ (Class)videoCorePlayerClazz;
+ (Class)videoModelConverterClz;
@end
