@interface BDXLynxLottieView : LynxUI
@property (nonatomic) BOOL loop;
@property (nonatomic) BOOL autoReverse;
@property (nonatomic) BOOL autoplay;
@property (nonatomic) float speed;
@property (nonatomic) q loopCount;
@property (nonatomic) BOOL layoutReady;
@property (nonatomic) BOOL resourceReady;
@property (nonatomic) BOOL playWhenAllReady;
@property (nonatomic) BOOL onlyLocal;
@property (nonatomic) NSString currentSource;
@property (nonatomic) NSString srcFormat;
@property (nonatomic) NSDictionary srcPolyfill;
@property (nonatomic) NSDictionary currentSrcPolyfill;
@property (nonatomic) NSNumber startFrame;
@property (nonatomic) NSNumber endFrame;
@property (nonatomic) Q loopIndex;
@property (nonatomic) NSNumber lastFrame;
@property (nonatomic) NSString animationID;
@property (nonatomic) LOTCompositionContainer compContainer;
@property (nonatomic) NSMutableDictionary subscribedFrames;
@property (nonatomic) NSMutableDictionary reportContext;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setAutoReverse:;
- (id)updateURLQuery:;
- (void)setLayoutReady:;
- (void)setSrcPolyfill:;
- (void)animationView:didLoadResourcesWithError:;
- (void)animationView:fetchResourceWithURL:completionHandler:;
- (void)animationView:isDisplayingFrame:;
- (void)animationViewDidStart:;
- (BOOL)autoReverse;
- (void)autoReverse:requestReset:;
- (void)autoplay:requestReset:;
- (id)compContainer;
- (id)currentSrcPolyfill;
- (void)endFrame:requestReset:;
- (void)getCurrentFrame:withResult:;
- (void)getDuration:withResult:;
- (void)isAnimating:withResult:;
- (void)json:requestReset:;
- (void)layoutDidFinished;
- (BOOL)layoutReady;
- (void)loop:requestReset:;
- (void)objectfit:requestReset:;
- (BOOL)onlyLocal;
- (void)onlyLocal:requestReset:;
- (void)pause:withResult:;
- (void)play:withResult:;
- (void)playIfReady;
- (BOOL)playWhenAllReady;
- (void)progress:requestReset:;
- (void)refreshAnimationID;
- (void)repeatCount:requestReset:;
- (void)reportCost:resourceURL:;
- (void)reportErrorCode:message:resourceURL:;
- (BOOL)resourceReady;
- (void)resume:withResult:;
- (void)seek:withResult:;
- (void)sendErrorEventWithCode:resourceURL:message:;
- (void)sendEventNamed:extraDetail:;
- (void)setCompContainer:;
- (void)setCurrentSource:;
- (void)setCurrentSrcPolyfill:;
- (void)setLoopIndex:;
- (void)setOnlyLocal:;
- (void)setPlayWhenAllReady:;
- (void)setResourceReady:;
- (void)setSrcFormat:;
- (void)setSubscribedFrames:;
- (id)shouldFallbackBlock;
- (void)speed:requestReset:;
- (void)src:requestReset:;
- (id)srcFormat;
- (void)srcFormat:requestReset:;
- (id)srcPolyfill;
- (void)srcPolyfill:requestReset:;
- (void)startFrame:requestReset:;
- (void)stop:withResult:;
- (void)subscribeUpdateEvent:withResult:;
- (id)subscribedFrames;
- (void)unsubscribeUpdateEvent:withResult:;
- (void)updateAnimationProperties;
- (void)updateCompositionIfNeeded:;
- (void)updateSource:formatWithPolyfill:;
- (void)updateSourceIfNeeded;
- (id)init;
- (void)setSpeed:;
- (float)speed;
- (id)currentSource;
- (id)endFrame;
- (void).cxx_destruct;
- (void)setEndFrame:;
- (void)setAnimationID:;
- (id)animationID;
- (void)setStartFrame:;
- (id)startFrame;
- (BOOL)loop;
- (long long)loopCount;
- (void)setReportContext:;
- (id)reportContext;
- (void)setLastFrame:;
- (id)lastFrame;
- (id)createView;
- (void)setLoop:;
- (BOOL)autoplay;
- (void)setAutoplay:;
- (unsigned long long)loopIndex;
- (void)setLoopCount:;
+ (id)__lynx_prop_config__1101;
+ (id)__lynx_prop_config__1192;
+ (id)__lynx_prop_config__1293;
+ (id)__lynx_prop_config__1394;
+ (id)__lynx_prop_config__1645;
+ (id)__lynx_prop_config__1746;
+ (id)__lynx_prop_config__1837;
+ (id)__lynx_prop_config__1928;
+ (id)__lynx_prop_config__1989;
+ (id)__lynx_prop_config__20710;
+ (id)__lynx_prop_config__22111;
+ (id)__lynx_prop_config__23612;
+ (id)__lynx_prop_config__24413;
+ (id)__lynx_prop_config__25414;
+ (id)__lynx_ui_method_config__25915;
+ (id)__lynx_ui_method_config__26516;
+ (id)__lynx_ui_method_config__27017;
+ (id)__lynx_ui_method_config__27518;
+ (id)__lynx_ui_method_config__28019;
+ (id)__lynx_ui_method_config__28420;
+ (id)__lynx_ui_method_config__28821;
+ (id)__lynx_ui_method_config__30022;
+ (id)__lynx_ui_method_config__31023;
+ (id)__lynx_ui_method_config__32024;
+ (void)lynxLazyLoad;
@end
