@interface BDXResourceProvider : NSObject
@property (nonatomic) NSString res_accessKey;
@property (nonatomic) NSString res_channelName;
@property (nonatomic) NSString res_bundleName;
@property (nonatomic) Q res_version;
@property (nonatomic) NSData res_Data;
@property (nonatomic) q res_sourceFrom;
@property (nonatomic) NSString res_originSourceURL;
@property (nonatomic) NSString res_sourceURL;
@property (nonatomic) NSString res_localPath;
@property (nonatomic) NSString res_cdnUrl;
@property (nonatomic) NSDate expireDate;
@property (nonatomic) NSString res_lineFlagString;
@property (nonatomic) BDXResourceLoaderMetricModel metricInfo;
@property (nonatomic) BOOL isGeckoUpdate;
@property (nonatomic) double downloadResourceStart;
@property (nonatomic) double downloadResourceEnd;
@property (nonatomic) double readTemplateLocalStart;
@property (nonatomic) double readTemplateLocalEnd;
@property (nonatomic) NSString resFrom;
@property (nonatomic) UIImage resourceImage;
@property (nonatomic) BOOL isFromMemory;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)res_channelName;
- (id)originSourceURL;
- (id)resFrom;
- (void)setRes_version:;
- (id)cdnUrl;
- (double)downloadResourceEnd;
- (double)downloadResourceStart;
- (BOOL)isFromMemory;
- (BOOL)isGeckoUpdate;
- (double)readTemplateLocalEnd;
- (double)readTemplateLocalStart;
- (id)res_Data;
- (id)res_accessKey;
- (id)res_bundleName;
- (id)res_cdnUrl;
- (id)res_lineFlagString;
- (id)res_localPath;
- (id)res_originSourceURL;
- (long long)res_sourceFrom;
- (id)res_sourceURL;
- (unsigned long long)res_version;
- (id)resourceFrom;
- (void)setDownloadResourceEnd:;
- (void)setDownloadResourceStart:;
- (void)setIsFromMemory:;
- (void)setIsGeckoUpdate:;
- (void)setReadTemplateLocalEnd:;
- (void)setReadTemplateLocalStart:;
- (void)setResFrom:;
- (void)setRes_Data:;
- (void)setRes_accessKey:;
- (void)setRes_bundleName:;
- (void)setRes_cdnUrl:;
- (void)setRes_channelName:;
- (void)setRes_lineFlagString:;
- (void)setRes_localPath:;
- (void)setRes_originSourceURL:;
- (void)setRes_sourceFrom:;
- (void)setRes_sourceURL:;
- (id)init;
- (id)channel;
- (unsigned long long)version;
- (long long)resourceType;
- (id)expireDate;
- (void)setMetricInfo:;
- (id)bundle;
- (void).cxx_destruct;
- (void)setExpireDate:;
- (id)resourceData;
- (id)metricInfo;
- (id)sourceUrl;
- (id)accessKey;
- (id)absolutePath;
- (void)setResourceImage:;
- (id)resourceImage;
+ (void)doTrackLoadEventWithProvider:container:;
+ (void)trackLoadEventWithProvider:container:;
+ (id)resourceWithURL:;
@end
