@interface BDXTabbarView : UIView
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) NSLayoutConstraint collectionViewHeightConstraint;
@property (nonatomic) Q selectedIndex;
@property (nonatomic) BOOL hasFirstTimeAutoSelected;
@property (nonatomic) NSArray tabbarItems;
@property (nonatomic) VernierView vernier;
@property (nonatomic) UIView bottomBorder;
@property (nonatomic) NSLayoutConstraint bottomBorderWidthConstraint;
@property (nonatomic) NSLayoutConstraint bottomBorderHeightConstraint;
@property (nonatomic) NSLayoutConstraint bottomBorderBottomConstraint;
@property (nonatomic) <BDXTabbarViewEventDelegate> lynxEventDelegate;
@property (nonatomic) <BDXTabbarViewDelegate> delegate;
@property (nonatomic) UIColor tabIndicatorColor;
@property (nonatomic) double tabInterSpace;
@property (nonatomic) double tabIndicatorWidth;
@property (nonatomic) double tabIndicatorHeight;
@property (nonatomic) double tabIndicatorTop;
@property (nonatomic) q tabLayoutGravity;
@property (nonatomic) double borderHeight;
@property (nonatomic) double borderWidth;
@property (nonatomic) double borderDistanceToBottom;
@property (nonatomic) UIColor borderColor;
@property (nonatomic) double leftMargin;
@property (nonatomic) double rightMargin;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (double)tabIndicatorTop;
- (void)setBottomBorderWidthConstraint:;
- (void)setTabbarItems:;
- (id)vernier;
- (double)borderDistanceToBottom;
- (double)borderHeight;
- (id)bottomBorderBottomConstraint;
- (id)bottomBorderHeightConstraint;
- (id)bottomBorderWidthConstraint;
- (BOOL)directSetSelectedIndex:;
- (id)getCell:;
- (BOOL)hasFirstTimeAutoSelected;
- (id)lynxEventDelegate;
- (void)reselectSelectedIndex;
- (void)scrollToTargetIndex:sourceIndex:percent:;
- (void)setBorderDistanceToBottom:;
- (void)setBorderHeight:;
- (void)setBottomBorderBottomConstraint:;
- (void)setBottomBorderHeightConstraint:;
- (void)setHasFirstTimeAutoSelected:;
- (void)setLynxEventDelegate:;
- (void)setTabIndicatorColor:;
- (void)setTabIndicatorHeight:;
- (void)setTabIndicatorTop:;
- (void)setTabIndicatorWidth:;
- (void)setTabInterSpace:;
- (void)setTabLayoutGravity:;
- (void)setVernier:;
- (id)tabIndicatorColor;
- (double)tabIndicatorHeight;
- (double)tabIndicatorWidth;
- (double)tabInterSpace;
- (long long)tabLayoutGravity;
- (id)tabbarItems;
- (double)tabsOffsetToCenter;
- (double)tabsOriginTotalWidth;
- (id)collectionView:layout:insetForSectionAtIndex:;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)setBorderColor:;
- (double)collectionView:layout:minimumLineSpacingForSectionAtIndex:;
- (double)collectionView:layout:minimumInteritemSpacingForSectionAtIndex:;
- (id)borderColor;
- (id)init;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setLeftMargin:;
- (double)leftMargin;
- (long long)collectionView:numberOfItemsInSection:;
- (unsigned long long)selectedIndex;
- (void)setDelegate:;
- (id)collectionView:cellForItemAtIndexPath:;
- (double)borderWidth;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setBorderWidth:;
- (void)setCollectionView:;
- (id)delegate;
- (double)rightMargin;
- (void).cxx_destruct;
- (id)collectionView;
- (void)setSelectedIndex:;
- (void)setRightMargin:;
- (void)setupUI;
- (id)collectionViewHeightConstraint;
- (void)setCollectionViewHeightConstraint:;
- (id)bottomBorder;
- (void)setBottomBorder:;
@end
