@interface BKSAssertion : NSObject
@property (nonatomic) NSString name;
@property (nonatomic) BOOL valid;
@property (nonatomic) @? invalidationHandler;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)_setAttributes:;
- (id)_attributes;
- (void)_lock_setName:;
- (unsigned long long)_bksErrorForRBSAssertionError:;
- (void)_lock_setAttributes:;
- (void)assertion:didInvalidateWithError:;
- (id)_internalAssertion;
- (id)_lock_attributes;
- (id)init;
- (void)_lock:;
- (void)_lock_reaquireAssertion;
- (id)_lock_internalAssertion;
- (void)dealloc;
- (BOOL)valid;
- (void)setName:;
- (id)_initWithName:handler:;
- (void)assertionWillInvalidate:;
- (void)_setTarget:;
- (id)_target;
- (id)_lock_acquisitionHandler;
- (id)_acquisitionHandler;
- (BOOL)acquire;
- (void)_acquireAsynchronously;
- (void)_invalidateSynchronously:;
- (id)_lock_name;
- (void)_lock_setInternalAssertion:;
- (void).cxx_destruct;
- (id)invalidationHandler;
- (void)setInvalidationHandler:;
- (id)name;
- (void)invalidate;
@end
