@interface BKSAlternateSystemApp : NSObject
@property (nonatomic) NSString bundleId;
@property (nonatomic) NSXPCConnection connection;
@property (nonatomic) NSObject<OS_dispatch_queue> queue;
@property (nonatomic) q state;
@property (nonatomic) BOOL stateChangeWaiter;
@property (nonatomic) NSObject<OS_dispatch_semaphore> stateChangeSemaphore;
@property (nonatomic) <BKSAlternateSystemAppDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)terminate;
- (void)_queue_invalidate;
- (void)dealloc;
- (void)_handleInterruptedConnection;
- (id)initWithBundleId:;
- (void)setState:;
- (id)bundleId;
- (void)setDelegate:;
- (void)_queue_ensureConnection;
- (long long)state;
- (id)delegate;
- (id)connection;
- (void).cxx_destruct;
- (void)setConnection:;
- (void)setQueue:;
- (void)setBundleId:;
- (id)queue;
- (void)activate;
- (void)didBlockSystemAppForAlternateSystemApp;
- (void)didUnblockSystemAppForAlternateSystemApp;
- (void)alternateSystemAppWithBundleID:failedToOpenWithResult:;
- (void)alternateSystemAppWithBundleID:didExitWithContext:;
- (void)alternateSystemAppWithBundleIDDidOpen:;
- (void)alternateSystemAppWithBundleIDDidTerminate:;
- (void)_queue_changeState:;
- (void)_waitForState:;
- (void)_handleInvalidatedConnection;
- (BOOL)stateChangeWaiter;
- (void)setStateChangeWaiter:;
- (id)stateChangeSemaphore;
- (void)setStateChangeSemaphore:;
@end
