@interface BMPBHomeKitClientMediaAccessoryControlEvent : PBCodable
@property (nonatomic) BOOL hasBase;
@property (nonatomic) BMPBHomeKitClientBase base;
@property (nonatomic) BOOL hasAccessoryUniqueIdentifier;
@property (nonatomic) NSString accessoryUniqueIdentifier;
@property (nonatomic) NSMutableArray accessoryStates;
@property (nonatomic) BOOL hasAccessoryMediaRouteIdentifier;
@property (nonatomic) NSString accessoryMediaRouteIdentifier;
@property (nonatomic) NSMutableArray zoneUniqueIdentifiers;
@property (nonatomic) BOOL hasRoomUniqueIdentifier;
@property (nonatomic) NSString roomUniqueIdentifier;
@property (nonatomic) BOOL hasAccessoryName;
@property (nonatomic) NSString accessoryName;
@property (nonatomic) BOOL hasRoomName;
@property (nonatomic) NSString roomName;
@property (nonatomic) NSMutableArray zoneNames;
@property (nonatomic) BOOL hasHomeName;
@property (nonatomic) NSString homeName;
- (id)accessoryName;
- (id)zoneNames;
- (void)setBase:;
- (void)writeTo:;
- (id)base;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setAccessoryStates:;
- (void)mergeFrom:;
- (BOOL)hasBase;
- (void)setRoomName:;
- (void).cxx_destruct;
- (id)accessoryStates;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (id)roomName;
- (void)setZoneNames:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)clearZoneNames;
- (void)addZoneNames:;
- (id)zoneNamesAtIndex:;
- (id)homeName;
- (void)setHomeName:;
- (BOOL)hasHomeName;
- (unsigned long long)zoneNamesCount;
- (BOOL)hasAccessoryUniqueIdentifier;
- (void)clearZoneUniqueIdentifiers;
- (void)addZoneUniqueIdentifiers:;
- (unsigned long long)zoneUniqueIdentifiersCount;
- (id)zoneUniqueIdentifiersAtIndex:;
- (BOOL)hasRoomUniqueIdentifier;
- (BOOL)hasAccessoryName;
- (BOOL)hasRoomName;
- (id)accessoryUniqueIdentifier;
- (void)setAccessoryUniqueIdentifier:;
- (id)zoneUniqueIdentifiers;
- (void)setZoneUniqueIdentifiers:;
- (id)roomUniqueIdentifier;
- (void)setRoomUniqueIdentifier:;
- (void)setAccessoryName:;
- (void)clearAccessoryStates;
- (void)addAccessoryState:;
- (unsigned long long)accessoryStatesCount;
- (id)accessoryStateAtIndex:;
- (BOOL)hasAccessoryMediaRouteIdentifier;
- (id)accessoryMediaRouteIdentifier;
- (void)setAccessoryMediaRouteIdentifier:;
+ (Class)zoneNamesType;
+ (Class)zoneUniqueIdentifiersType;
+ (Class)accessoryStateType;
@end
