@interface BMPostSiriEngagementEvent : BMEventBase
@property (nonatomic) NSString UISessionID;
@property (nonatomic) NSString taskID;
@property (nonatomic) NSString taskType;
@property (nonatomic) NSString conversationPath;
@property (nonatomic) BOOL hasTaskSuccess;
@property (nonatomic) NSInteger taskSuccess;
@property (nonatomic) BOOL hasIsUserAbandoned;
@property (nonatomic) BOOL isUserAbandoned;
@property (nonatomic) BOOL hasIsUserCancelled;
@property (nonatomic) BOOL isUserCancelled;
@property (nonatomic) NSArray pseEvents;
@property (nonatomic) I dataVersion;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)taskType;
- (void)writeTo:;
- (unsigned int)dataVersion;
- (id)initByReadFrom:;
- (void).cxx_destruct;
- (id)description;
- (id)taskID;
- (id)serialize;
- (BOOL)isEqual:;
- (id)initWithUISessionID:taskID:taskType:conversationPath:taskSuccess:isUserAbandoned:isUserCancelled:pseEvents:;
- (id)initWithUISessionId:domain:action:isPostSiriEngagement:pseDeltaDuration:pseDeltaSinceUIStart:pseDeltaSinceUIEnd:pseContents:;
- (id)UISessionID;
- (id)conversationPath;
- (BOOL)hasTaskSuccess;
- (void)setHasTaskSuccess:;
- (int)taskSuccess;
- (BOOL)hasIsUserAbandoned;
- (void)setHasIsUserAbandoned:;
- (BOOL)isUserAbandoned;
- (BOOL)hasIsUserCancelled;
- (void)setHasIsUserCancelled:;
- (BOOL)isUserCancelled;
- (id)pseEvents;
+ (id)eventWithData:dataVersion:;
@end
