@interface BMThirdPartyAppContentEvent : NSObject
@property (nonatomic) NSString uniqueId;
@property (nonatomic) NSString domainId;
@property (nonatomic) NSString bundleId;
@property (nonatomic) double absoluteTimestamp;
@property (nonatomic) NSString title;
@property (nonatomic) NSString desc;
@property (nonatomic) NSString comment;
@property (nonatomic) NSString content;
@property (nonatomic) NSString contentProtection;
@property (nonatomic) I dataVersion;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)content;
- (id)initWithProtoData:;
- (id)init;
- (id)uniqueId;
- (id)comment;
- (id)proto;
- (id)desc;
- (id)json;
- (id)bundleId;
- (id)encodeAsProto;
- (double)absoluteTimestamp;
- (id)initWithCoder:;
- (unsigned int)dataVersion;
- (unsigned long long)hash;
- (BOOL)isCompleteWithContext:error:;
- (void)encodeWithCoder:;
- (id)initWithProto:;
- (id)title;
- (id)domainId;
- (void).cxx_destruct;
- (id)contentProtection;
- (BOOL)isValidWithContext:error:;
- (id)serialize;
- (id)jsonDict;
- (BOOL)isEqual:;
- (id)initWithUniqueId:domainId:bundleId:absoluteTimestamp:title:desc:comment:content:contentProtection:;
- (id)initWithUniqueId:domainId:bundleId:absoluteTimestamp:title:desc:comment:content:;
+ (id)eventWithData:dataVersion:;
+ (BOOL)supportsSecureCoding;
@end
