@interface BWZoomCommandHandler : NSObject
@property (nonatomic) float requestedZoomFactor;
@property (nonatomic) float requestedZoomFactorWithoutFudge;
@property (nonatomic) float appliedZoomFactor;
@property (nonatomic) float appliedZoomFactorWithoutFudge;
@property (nonatomic) float rampTargetZoomFactor;
@property (nonatomic) float earlySwitchOverScaleFactorForZoomIn;
@property (nonatomic) float allowableMinimumDigitalZoomFactorDuringZoomOut;
@property (nonatomic) NSInteger rampTuning;
@property (nonatomic) float rampZoomFactorOfInterest;
@property (nonatomic) <BWZoomCompletionDelegate> zoomCompletionDelegate;
@property (nonatomic) <BWZoomCompletionDelegate> zoomCompletionDelegateForStereoAudio;
- (void)setRequestedZoomFactor:;
- (id)init;
- (void)dealloc;
- (float)requestedZoomFactor;
- (void)updateAppliedZoomFactorForDelayedISPAppliedZoomFactor:;
- (id)zoomCompletionDelegateForStereoAudio;
- (void)resetZoomDelayBuffer;
- (int)rampTuning;
- (void)rampToVideoZoomFactor:usingSpringWithTension:friction:snapFraction:rampTuning:earlySwitchOverScaleFactorForZoomIn:allowableMinimumDigitalZoomFactorDuringZoomOut:rampStartFrameDelayAt30fps:commandID:;
- (id)zoomCompletionDelegate;
- (void)setFudgedZoomRanges:;
- (void)setZoomCompletionDelegateForStereoAudio:;
- (float)appliedZoomFactor;
- (void)rampToVideoZoomFactor:withRampType:rate:duration:snapToTargetZoomFactorWithinRampFraction:rampTuning:earlySwitchOverScaleFactorForZoomIn:allowableMinimumDigitalZoomFactorDuringZoomOut:commandID:;
- (float)allowableMinimumDigitalZoomFactorDuringZoomOut;
- (void)setZoomCompletionDelegate:;
- (long long)timeForLastRequestedZoomFactor;
- (float)rampTargetZoomFactor;
- (void)resetZoomFactorOfInterest;
- (float)updateZoomModelAndAppliedZoomFactorForNextFrameWithPTS:ptsTolerance:delayedISPAppliedZoomFactor:zoomFactorChangedOut:;
- (float)updateZoomModelForNextFrameWithPTS:;
- (float)predictRampZoomFactorAfterNumberOfFrames:settingZoomFactorOfInterest:;
- (BOOL)haveUpdatedZoomModelForPTS:;
- (void)setTypicalISPZoomDelay:clientCanCompensateForDelay:;
- (float)applyFudgeToZoomFactor:;
- (float)rampZoomFactorOfInterest;
- (float)requestedZoomFactorWithoutFudge;
- (float)appliedZoomFactorWithoutFudge;
- (float)earlySwitchOverScaleFactorForZoomIn;
@end
