@interface ByteRTCMediaPlayer : NSObject
@property (nonatomic) @ audioFrameObserverDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @ customSourceProviderDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (int)getTotalDuration;
- (int)pushExternalAudioFrame:;
- (int)registerAudioFrameObserver:;
- (int)getAudioTrackCount;
- (id)audioFrameObserverDelegate;
- (void)onFrame:audioFrame:;
- (void)setAudioFrameObserverDelegate:;
- (id)customSourceProviderDelegate;
- (int)onReadData:bufferSize:;
- (long long)onSeek:whence:;
- (void)setCustomSourceProviderDelegate:;
- (id)initWithMediaPlayer:;
- (int)open:config:;
- (int)openWithCustomSource:config:;
- (int)setVolume:type:;
- (int)getPlaybackDuration;
- (int)setAudioPitch:;
- (int)setAudioDualMonoMode:;
- (int)selectAudioTrack:;
- (int)setPosition:;
- (void)dealloc;
- (int)start;
- (int)stop;
- (int)setEventHandler:;
- (int)resume;
- (void).cxx_destruct;
- (int)pause;
- (id).cxx_construct;
- (int)setPlaybackSpeed:;
- (int)setProgressInterval:;
- (int)setLoudness:;
- (int)getPosition;
- (int)getVolume:;
@end
