@interface C2MPNetworkEvent : PBCodable
@property (nonatomic) BOOL hasTriggers;
@property (nonatomic) Q triggers;
@property (nonatomic) BOOL hasReportFrequency;
@property (nonatomic) Q reportFrequency;
@property (nonatomic) BOOL hasReportFrequencyBase;
@property (nonatomic) Q reportFrequencyBase;
@property (nonatomic) BOOL hasNetworkTaskDescription;
@property (nonatomic) NSString networkTaskDescription;
@property (nonatomic) BOOL hasNetworkHostname;
@property (nonatomic) NSString networkHostname;
@property (nonatomic) BOOL hasNetworkRemoteAddresssAndPort;
@property (nonatomic) NSString networkRemoteAddresssAndPort;
@property (nonatomic) BOOL hasNetworkConnectionUuid;
@property (nonatomic) NSString networkConnectionUuid;
@property (nonatomic) BOOL hasNetworkConnectionReused;
@property (nonatomic) BOOL networkConnectionReused;
@property (nonatomic) BOOL hasNetworkInterfaceIdentifier;
@property (nonatomic) NSString networkInterfaceIdentifier;
@property (nonatomic) BOOL hasNetworkProtocolName;
@property (nonatomic) NSString networkProtocolName;
@property (nonatomic) BOOL hasNetworkRequestHeaderSize;
@property (nonatomic) I networkRequestHeaderSize;
@property (nonatomic) BOOL hasNetworkRequestBodyBytesSent;
@property (nonatomic) Q networkRequestBodyBytesSent;
@property (nonatomic) BOOL hasNetworkResponseHeaderSize;
@property (nonatomic) I networkResponseHeaderSize;
@property (nonatomic) BOOL hasNetworkResponseBodyBytesReceived;
@property (nonatomic) Q networkResponseBodyBytesReceived;
@property (nonatomic) BOOL hasNetworkPreviousAttemptCount;
@property (nonatomic) I networkPreviousAttemptCount;
@property (nonatomic) BOOL hasNetworkFatalError;
@property (nonatomic) C2MPError networkFatalError;
@property (nonatomic) BOOL hasNetworkStatusCode;
@property (nonatomic) Q networkStatusCode;
@property (nonatomic) BOOL hasNetworkRequestUri;
@property (nonatomic) NSString networkRequestUri;
@property (nonatomic) BOOL hasNetworkIsDiscretionary;
@property (nonatomic) BOOL networkIsDiscretionary;
@property (nonatomic) BOOL hasNetworkNegotiatedTlsProtocolVersion;
@property (nonatomic) NSString networkNegotiatedTlsProtocolVersion;
@property (nonatomic) NSMutableArray networkPathInfos;
@property (nonatomic) BOOL hasTimestampC2Init;
@property (nonatomic) Q timestampC2Init;
@property (nonatomic) BOOL hasTimestampC2Start;
@property (nonatomic) Q timestampC2Start;
@property (nonatomic) BOOL hasTimestampC2Now;
@property (nonatomic) Q timestampC2Now;
@property (nonatomic) BOOL hasTimestampDnsStart;
@property (nonatomic) Q timestampDnsStart;
@property (nonatomic) BOOL hasTimestampDnsEnd;
@property (nonatomic) Q timestampDnsEnd;
@property (nonatomic) BOOL hasTimestampTcpStart;
@property (nonatomic) Q timestampTcpStart;
@property (nonatomic) BOOL hasTimestampTcpEnd;
@property (nonatomic) Q timestampTcpEnd;
@property (nonatomic) BOOL hasTimestampSslStart;
@property (nonatomic) Q timestampSslStart;
@property (nonatomic) BOOL hasTimestampRequestStart;
@property (nonatomic) Q timestampRequestStart;
@property (nonatomic) BOOL hasTimestampRequestEnd;
@property (nonatomic) Q timestampRequestEnd;
@property (nonatomic) BOOL hasTimestampResponseStart;
@property (nonatomic) Q timestampResponseStart;
@property (nonatomic) BOOL hasTimestampResponseEnd;
@property (nonatomic) Q timestampResponseEnd;
@property (nonatomic) BOOL hasOptionsQualityOfService;
@property (nonatomic) NSString optionsQualityOfService;
@property (nonatomic) BOOL hasOptionsOutOfProcess;
@property (nonatomic) BOOL optionsOutOfProcess;
@property (nonatomic) BOOL hasOptionsOutOfProcessForceDiscretionary;
@property (nonatomic) BOOL optionsOutOfProcessForceDiscretionary;
@property (nonatomic) BOOL hasOptionsAllowExpensiveAccess;
@property (nonatomic) BOOL optionsAllowExpensiveAccess;
@property (nonatomic) BOOL hasOptionsAllowPowerNapScheduling;
@property (nonatomic) BOOL optionsAllowPowerNapScheduling;
@property (nonatomic) BOOL hasOptionsTimeoutIntervalForRequest;
@property (nonatomic) I optionsTimeoutIntervalForRequest;
@property (nonatomic) BOOL hasOptionsTimeoutIntervalForResource;
@property (nonatomic) I optionsTimeoutIntervalForResource;
@property (nonatomic) BOOL hasOptionsSourceApplicationBundleIdentifier;
@property (nonatomic) NSString optionsSourceApplicationBundleIdentifier;
@property (nonatomic) BOOL hasOptionsSourceApplicationSecondaryIdentifier;
@property (nonatomic) NSString optionsSourceApplicationSecondaryIdentifier;
@property (nonatomic) BOOL hasOptionsAppleIdContext;
@property (nonatomic) BOOL optionsAppleIdContext;
@property (nonatomic) BOOL hasOptionsTlsPinningRequired;
@property (nonatomic) BOOL optionsTlsPinningRequired;
@property (nonatomic) BOOL hasOptionsDiscretionaryNetworkBehavior;
@property (nonatomic) NSString optionsDiscretionaryNetworkBehavior;
@property (nonatomic) BOOL hasOptionsDuetPreClearedMode;
@property (nonatomic) NSString optionsDuetPreClearedMode;
@property (nonatomic) BOOL hasOptionsAllowCellularAccess;
@property (nonatomic) BOOL optionsAllowCellularAccess;
- (void)setHasTriggers:;
- (BOOL)hasReportFrequencyBase;
- (unsigned long long)reportFrequencyBase;
- (void)setReportFrequency:;
- (void)setReportFrequencyBase:;
- (BOOL)hasTriggers;
- (void)setTriggers:;
- (unsigned long long)reportFrequency;
- (void)setHasTimestampSslStart:;
- (unsigned long long)triggers;
- (unsigned long long)timestampTcpEnd;
- (id)networkFatalError;
- (unsigned int)optionsTimeoutIntervalForResource;
- (void)setHasReportFrequencyBase:;
- (void)setHasNetworkRequestBodyBytesSent:;
- (void)setNetworkProtocolName:;
- (BOOL)optionsOutOfProcess;
- (id)networkProtocolName;
- (BOOL)hasOptionsAllowPowerNapScheduling;
- (unsigned long long)networkResponseBodyBytesReceived;
- (void)setOptionsSourceApplicationBundleIdentifier:;
- (void)setTimestampC2Now:;
- (void)setNetworkResponseHeaderSize:;
- (BOOL)networkConnectionReused;
- (void)setNetworkNegotiatedTlsProtocolVersion:;
- (unsigned int)optionsTimeoutIntervalForRequest;
- (BOOL)hasOptionsDuetPreClearedMode;
- (void)setHasTimestampC2Now:;
- (void)setHasOptionsTlsPinningRequired:;
- (void)setOptionsDuetPreClearedMode:;
- (BOOL)hasNetworkStatusCode;
- (void)setHasNetworkRequestHeaderSize:;
- (BOOL)hasOptionsOutOfProcessForceDiscretionary;
- (void)addNetworkPathInfo:;
- (void)setHasTimestampC2Start:;
- (BOOL)hasNetworkResponseBodyBytesReceived;
- (BOOL)hasOptionsTlsPinningRequired;
- (BOOL)hasNetworkHostname;
- (void)setHasTimestampRequestStart:;
- (unsigned long long)timestampRequestEnd;
- (BOOL)hasNetworkProtocolName;
- (BOOL)hasTimestampDnsStart;
- (void)writeTo:;
- (void)setNetworkHostname:;
- (void)setOptionsAllowExpensiveAccess:;
- (void)clearNetworkPathInfos;
- (void)setHasOptionsAppleIdContext:;
- (unsigned long long)timestampC2Start;
- (void)setHasTimestampTcpStart:;
- (void)setTimestampResponseEnd:;
- (void)setOptionsDiscretionaryNetworkBehavior:;
- (void)setNetworkTaskDescription:;
- (void)setHasNetworkPreviousAttemptCount:;
- (void)setOptionsOutOfProcess:;
- (id)networkNegotiatedTlsProtocolVersion;
- (id)networkConnectionUuid;
- (BOOL)hasNetworkPreviousAttemptCount;
- (void)setOptionsAllowCellularAccess:;
- (void)setTimestampRequestEnd:;
- (BOOL)hasNetworkRequestBodyBytesSent;
- (BOOL)optionsAllowExpensiveAccess;
- (id)networkTaskDescription;
- (BOOL)hasNetworkConnectionUuid;
- (void)setOptionsAllowPowerNapScheduling:;
- (unsigned long long)hash;
- (BOOL)hasNetworkIsDiscretionary;
- (BOOL)hasTimestampC2Init;
- (unsigned long long)timestampRequestStart;
- (BOOL)hasNetworkTaskDescription;
- (void)setNetworkInterfaceIdentifier:;
- (id)optionsSourceApplicationBundleIdentifier;
- (void)setOptionsTimeoutIntervalForResource:;
- (void)setNetworkPreviousAttemptCount:;
- (void)setHasTimestampResponseStart:;
- (void)setOptionsSourceApplicationSecondaryIdentifier:;
- (BOOL)hasOptionsAllowExpensiveAccess;
- (unsigned long long)timestampDnsEnd;
- (void)copyTo:;
- (void)setNetworkRequestUri:;
- (void)setOptionsOutOfProcessForceDiscretionary:;
- (BOOL)hasNetworkConnectionReused;
- (unsigned int)networkPreviousAttemptCount;
- (unsigned long long)timestampDnsStart;
- (void)setNetworkPathInfos:;
- (BOOL)hasTimestampRequestEnd;
- (void)mergeFrom:;
- (void)setNetworkRequestBodyBytesSent:;
- (void)setTimestampDnsStart:;
- (unsigned long long)timestampC2Init;
- (void)setNetworkResponseBodyBytesReceived:;
- (BOOL)hasTimestampC2Now;
- (void)setHasOptionsTimeoutIntervalForRequest:;
- (void)setTimestampTcpEnd:;
- (BOOL)hasTimestampResponseEnd;
- (id)optionsDiscretionaryNetworkBehavior;
- (unsigned long long)timestampTcpStart;
- (BOOL)hasReportFrequency;
- (void)setOptionsTlsPinningRequired:;
- (void)setHasOptionsTimeoutIntervalForResource:;
- (BOOL)hasOptionsAllowCellularAccess;
- (void)setNetworkConnectionReused:;
- (BOOL)hasOptionsTimeoutIntervalForRequest;
- (unsigned int)networkRequestHeaderSize;
- (BOOL)hasNetworkInterfaceIdentifier;
- (BOOL)hasNetworkResponseHeaderSize;
- (void)setTimestampDnsEnd:;
- (unsigned long long)networkStatusCode;
- (BOOL)hasTimestampSslStart;
- (void)setTimestampC2Start:;
- (BOOL)hasOptionsAppleIdContext;
- (void)setHasNetworkResponseBodyBytesReceived:;
- (BOOL)hasNetworkFatalError;
- (void)setHasOptionsOutOfProcess:;
- (void)setHasOptionsAllowCellularAccess:;
- (void)setHasOptionsAllowExpensiveAccess:;
- (BOOL)optionsAllowCellularAccess;
- (void)setTimestampC2Init:;
- (void).cxx_destruct;
- (id)optionsQualityOfService;
- (id)networkRequestUri;
- (id)networkPathInfoAtIndex:;
- (void)setHasNetworkConnectionReused:;
- (unsigned long long)timestampC2Now;
- (void)setHasTimestampResponseEnd:;
- (BOOL)optionsAllowPowerNapScheduling;
- (BOOL)readFrom:;
- (void)setTimestampSslStart:;
- (void)setTimestampResponseStart:;
- (void)setNetworkStatusCode:;
- (BOOL)hasOptionsOutOfProcess;
- (void)setTimestampTcpStart:;
- (id)description;
- (BOOL)hasTimestampTcpEnd;
- (void)setOptionsTimeoutIntervalForRequest:;
- (void)setHasNetworkIsDiscretionary:;
- (unsigned long long)timestampSslStart;
- (BOOL)optionsAppleIdContext;
- (void)setTimestampRequestStart:;
- (BOOL)hasTimestampTcpStart;
- (id)optionsDuetPreClearedMode;
- (void)setOptionsQualityOfService:;
- (BOOL)hasOptionsQualityOfService;
- (BOOL)hasNetworkRequestHeaderSize;
- (void)setHasTimestampDnsEnd:;
- (void)setHasTimestampDnsStart:;
- (BOOL)hasNetworkRequestUri;
- (void)setHasTimestampRequestEnd:;
- (id)networkHostname;
- (id)dictionaryRepresentation;
- (void)setNetworkIsDiscretionary:;
- (void)setHasTimestampTcpEnd:;
- (id)optionsSourceApplicationSecondaryIdentifier;
- (id)networkPathInfos;
- (BOOL)optionsOutOfProcessForceDiscretionary;
- (BOOL)optionsTlsPinningRequired;
- (BOOL)hasTimestampC2Start;
- (BOOL)hasOptionsSourceApplicationSecondaryIdentifier;
- (void)setNetworkConnectionUuid:;
- (BOOL)hasTimestampResponseStart;
- (unsigned long long)timestampResponseStart;
- (BOOL)hasNetworkRemoteAddresssAndPort;
- (void)setHasOptionsOutOfProcessForceDiscretionary:;
- (void)setOptionsAppleIdContext:;
- (unsigned int)networkResponseHeaderSize;
- (unsigned long long)networkRequestBodyBytesSent;
- (BOOL)hasOptionsTimeoutIntervalForResource;
- (void)setHasReportFrequency:;
- (void)setNetworkRequestHeaderSize:;
- (id)networkRemoteAddresssAndPort;
- (BOOL)hasTimestampRequestStart;
- (BOOL)hasNetworkNegotiatedTlsProtocolVersion;
- (void)setNetworkRemoteAddresssAndPort:;
- (unsigned long long)timestampResponseEnd;
- (BOOL)isEqual:;
- (void)setHasTimestampC2Init:;
- (void)setHasOptionsAllowPowerNapScheduling:;
- (id)networkInterfaceIdentifier;
- (BOOL)networkIsDiscretionary;
- (void)setHasNetworkStatusCode:;
- (void)setHasNetworkResponseHeaderSize:;
- (BOOL)hasOptionsDiscretionaryNetworkBehavior;
- (void)setNetworkFatalError:;
- (unsigned long long)networkPathInfosCount;
- (BOOL)hasOptionsSourceApplicationBundleIdentifier;
- (id)copyWithZone:;
- (BOOL)hasTimestampDnsEnd;
+ (Class)networkPathInfoType;
@end
