@interface CAMetalLayer : CALayer
@property (nonatomic) BOOL fenceEnabled;
@property (nonatomic) BOOL serverSyncEnabled;
@property (nonatomic) BOOL lowLatency;
@property (nonatomic) BOOL exclusiveMode;
@property (nonatomic) double inputTime;
@property (nonatomic) BOOL nonDefaultColorspace;
@property (nonatomic) double drawableTimeoutSeconds;
@property (nonatomic) Q protectionOptions;
@property (nonatomic) Q displayCompositingInternalStatus;
@property (nonatomic) <MTLDevice> device;
@property (nonatomic) <MTLDevice> preferredDevice;
@property (nonatomic) Q pixelFormat;
@property (nonatomic) BOOL framebufferOnly;
@property (nonatomic) {CGSize=dd} drawableSize;
@property (nonatomic) Q maximumDrawableCount;
@property (nonatomic) BOOL presentsWithTransaction;
@property (nonatomic) ^{CGColorSpace=} colorspace;
@property (nonatomic) BOOL wantsExtendedDynamicRangeContent;
@property (nonatomic) CAEDRMetadata EDRMetadata;
@property (nonatomic) BOOL allowsNextDrawableTimeout;
@property (nonatomic) NSDictionary developerHUDProperties;
- (void)setColorspace:;
- (BOOL)shouldArchiveValueForKey:;
- (id)init;
- (void)dealloc;
- (BOOL)presentsWithTransaction;
- (void)setPixelFormat:;
- (BOOL)lowLatency;
- (void)setDevice:;
- (BOOL)exclusiveMode;
- (BOOL)displaySyncEnabled;
- (double)inputTime;
- (void)setAllowsNextDrawableTimeout:;
- (void)setDrawableSize:;
- (void)setPresentsWithTransaction:;
- (void)didChangeValueForKey:;
- (BOOL)framebufferOnly;
- (void)setDrawableTimeoutSeconds:;
- (BOOL)nonDefaultColorspace;
- (unsigned long long)maximumDrawableCount;
- (BOOL)allowsNextDrawableTimeout;
- (void)setServerSyncEnabled:;
- (void)_didCommitLayer:;
- (void)setFramebufferOnly:;
- (unsigned long long)protectionOptions;
- (void)setNonDefaultColorspace:;
- (void)setDisplaySyncEnabled:;
- (BOOL)serverSyncEnabled;
- (void)layerDidBecomeVisible:;
- (void)setContents:;
- (id)nextDrawable;
- (void)_display;
- (void)setLowLatency:;
- (void)discardContents;
- (void)setInputTime:;
- (unsigned long long)displayCompositingInternalStatus;
- (BOOL)fenceEnabled;
- (id)newDrawable;
- (void)setDeveloperHUDProperties:;
- (unsigned long long)pixelFormat;
- (id)EDRMetadata;
- (void)setMaximumDrawableCount:;
- (id)colorspace;
- (void)setProtectionOptions:;
- (void)setColorspace:nonDefault:;
- (void)setEDRMetadata:;
- (double)drawableTimeoutSeconds;
- (BOOL)isDrawableAvailable;
- (void)setExclusiveMode:;
- (id)drawableSize;
- (id)device;
- (id)developerHUDProperties;
- (void)removeBackBuffers;
- (void)setFenceEnabled:;
- (id)preferredDevice;
+ (id)defaultValueForKey:;
+ (BOOL)CA_automaticallyNotifiesObservers:;
@end
