@interface CAReporter : NSObject
@property (nonatomic) NSMutableDictionary internalConfiguration;
@property (nonatomic) NSDate startDate;
@property (nonatomic) S serviceType;
@property (nonatomic) BOOL started;
@property (nonatomic) BOOL removedByClient;
@property (nonatomic) BOOL connected;
@property (nonatomic) CAReportingPerformanceObject perfObject;
@property (nonatomic) Q signpostID;
@property (nonatomic) q reporterID;
@property (nonatomic) NSDictionary configuration;
- (void)setStarted:;
- (void)setConnected:;
- (id)startDate;
- (BOOL)connected;
- (unsigned long long)signpostID;
- (void)sendMessage:category:type:;
- (void)dealloc;
- (BOOL)started;
- (void)setStartDate:;
- (void)start;
- (long long)reporterID;
- (unsigned short)serviceType;
- (id)initWithReporterID:serviceType:;
- (void)stop;
- (BOOL)removedByClient;
- (void)setServiceType:;
- (void)setConfiguration:;
- (void)setPerfObject:;
- (void)setRemovedByClient:;
- (id)initWithNewReporterID;
- (id)perfObject;
- (void)updateWithReporterID:;
- (id)initWithSessionID:serviceType:;
- (id)configuration;
- (void).cxx_destruct;
- (void)cacheServiceType:;
- (id)internalConfiguration;
- (void)setInternalConfiguration:;
+ (void)sendSingleMessage:category:type:;
@end
