@interface CARScreenInfo : NSObject
@property (nonatomic) Q systemAvailableInteractionModels;
@property (nonatomic) Q systemPrimaryInteractionModel;
@property (nonatomic) Q currentViewAreaTransitionControlType;
@property (nonatomic) BOOL wantsCornerMasks;
@property (nonatomic) BOOL initialFocusOwner;
@property (nonatomic) BOOL supportsAppearanceMode;
@property (nonatomic) BOOL supportsPerDisplayNightMode;
@property (nonatomic) BOOL supportsMapAppearanceMode;
@property (nonatomic) NSDictionary screenInfoResponse;
@property (nonatomic) BOOL supportsLayerTracking;
@property (nonatomic) CARDisplayInfo physicalDisplay;
@property (nonatomic) NSString identifier;
@property (nonatomic) Q screenType;
@property (nonatomic) BOOL limitedUI;
@property (nonatomic) Q limitedUIElements;
@property (nonatomic) BOOL nightMode;
@property (nonatomic) Q availableInteractionModels;
@property (nonatomic) Q primaryInteractionModel;
@property (nonatomic) BOOL supportsHighFidelityTouch;
@property (nonatomic) Q maxFramesPerSecond;
@property (nonatomic) {CGSize=dd} physicalSize;
@property (nonatomic) {CGSize=dd} pixelSize;
@property (nonatomic) {CGSize=dd} squaredPixelSize;
@property (nonatomic) NSArray viewAreas;
@property (nonatomic) CARScreenViewArea currentViewArea;
@property (nonatomic) CARScreenViewArea adjacentViewArea;
@property (nonatomic) NSURL initialURL;
- (id)pixelSize;
- (unsigned long long)screenType;
- (id)identifier;
- (id)physicalSize;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)availableInteractionModels;
- (BOOL)supportsHighFidelityTouch;
- (unsigned long long)primaryInteractionModel;
- (unsigned long long)limitedUIElements;
- (id)initialURL;
- (id)initWithPropertySupplier:screenType:;
- (id)initWithPropertySupplier:screenType:additionalInsets:displayDictionary:;
- (id)descriptionForAvailableInteractionModels;
- (id)descriptionForPrimaryInteractionModel;
- (id)_descriptionForInteractionModel:;
- (BOOL)_currentProcessHasEntitlement;
- (void)nightModeChanged:;
- (void)limitedUIChanged:;
- (void)setPhysicalDisplay:;
- (id)originInDisplay;
- (id)displayPixelSize;
- (BOOL)isLimitedUI;
- (BOOL)isNightMode;
- (unsigned long long)maxFramesPerSecond;
- (id)squaredPixelSize;
- (id)viewAreas;
- (id)currentViewArea;
- (void)setCurrentViewArea:;
- (id)adjacentViewArea;
- (void)setAdjacentViewArea:;
- (unsigned long long)currentViewAreaTransitionControlType;
- (void)setCurrentViewAreaTransitionControlType:;
- (unsigned long long)systemAvailableInteractionModels;
- (void)setSystemAvailableInteractionModels:;
- (unsigned long long)systemPrimaryInteractionModel;
- (void)setSystemPrimaryInteractionModel:;
- (BOOL)wantsCornerMasks;
- (void)setWantsCornerMasks:;
- (BOOL)initialFocusOwner;
- (void)setInitialFocusOwner:;
- (BOOL)supportsAppearanceMode;
- (void)setSupportsAppearanceMode:;
- (BOOL)supportsPerDisplayNightMode;
- (void)setSupportsPerDisplayNightMode:;
- (BOOL)supportsMapAppearanceMode;
- (void)setSupportsMapAppearanceMode:;
- (id)screenInfoResponse;
- (BOOL)supportsLayerTracking;
- (void)setSupportsLayerTracking:;
- (id)physicalDisplay;
@end
