@interface CATTaskProgress : NSObject
@property (nonatomic) NSUUID UUID;
@property (nonatomic) Q phase;
@property (nonatomic) @ resultObject;
@property (nonatomic) NSError error;
@property (nonatomic) NSDictionary userInfo;
@property (nonatomic) BOOL isCancelable;
@property (nonatomic) BOOL isCanceled;
@property (nonatomic) q completedUnitCount;
@property (nonatomic) q totalUnitCount;
@property (nonatomic) NSString requestClassName;
@property (nonatomic) Q state;
- (BOOL)isCanceled;
- (id)initWithOperation:;
- (unsigned long long)phase;
- (void)setPhase:;
- (id)requestClassName;
- (id)init;
- (void)setRequestClassName:;
- (void)setResultObject:;
- (id)userInfo;
- (void)setUUID:;
- (void)setError:;
- (void)setProgress:;
- (void)setCompletedUnitCount:;
- (id)error;
- (id)initWithCoder:;
- (id)debugDescription;
- (id)progressStateDescription;
- (void)encodeWithCoder:;
- (unsigned long long)state;
- (void)setUserInfo:;
- (BOOL)isCancelable;
- (void)setIsCanceled:;
- (void).cxx_destruct;
- (void)setIsCancelable:;
- (void)setTotalUnitCount:;
- (id)description;
- (long long)totalUnitCount;
- (id)mutableCopyWithZone:;
- (id)UUID;
- (long long)completedUnitCount;
- (id)resultObject;
- (id)initWithOperationUUID:;
- (id)copyWithZone:;
+ (BOOL)supportsSecureCoding;
+ (void)assertResultObject:isValidForRequestClassName:;
+ (id)progressForOperation:;
+ (Class)classForResultObjectWithRequestClassName:;
@end
