@interface CBAODTransitionController : CBModule
@property (nonatomic) BOOL liveUpdatesOverride;
@property (nonatomic) float nitsOverride;
@property (nonatomic) float currentDisplayNits;
@property (nonatomic) float brightnessFactor;
@property (nonatomic) BOOL displayON;
@property (nonatomic) float remainingTransitionLength;
@property (nonatomic) BOOL liveUpdates;
- (void)dealloc;
- (void)colorRampRoutine:;
- (void)setInitialState:;
- (void)checkBootArgsConfiguration;
- (void).cxx_destruct;
- (BOOL)cancelTransition;
- (void)sendNotificationForKey:andValue:;
- (id).cxx_construct;
- (id)initWithCBBrtControl:andQueue:;
- (float)getFloatValueFrom:key:;
- (float)getFloatValueFrom:key:subkey:;
- (id)initWithCBBrtControl:andThresholdModule:andQueue:;
- (BOOL)initAPEndpoint;
- (float)currentDisplayNits;
- (void)setDurationOfEDRRamp:;
- (void)setDisplayON:;
- (BOOL)startTransition:length:forceUpdate:rampDoneCallback:rampCanceledCallback:;
- (BOOL)startTransition:transitionParameters:rampDoneCallback:rampCanceledCallback:;
- (id)copyColourRampStatsWithLength:frequency:origin:target:;
- (id)copyRampStatsWithLength:frequency:origin:target:;
- (void)releaseCallbacks;
- (void)clockUpdateHandler:;
- (void)rampsDoneCallback:;
- (void)releaseLastUpdateSwappedTimer;
- (void)activateLastUpdateSwappedTimerWithTimeout:;
- (BOOL)applyPendingUpdates;
- (BOOL)commitBrightness:force:;
- (void)updateSDRBrightness:;
- (void)updateBrightnessLimit:;
- (void)updateAAPFactor:rampDuration:;
- (void)updateLowAmbientAdaptationScaler:;
- (void)updateAmbient:;
- (float)sdrBrightnessProgressCallback:rampContext:;
- (float)sdrBrightnessProgressCallback:rampContext:profile:;
- (float)brightnessLimitProgressCallback:rampContext:;
- (BOOL)requestTransitionStopForIdentifier:;
- (void)initColorEffects;
- (void)updateColorRamp:;
- (BOOL)requestColorRampTransitionStop;
- (void)processInitialColorMatrixFromState:;
- (void)colorMatrix:fromState:;
- (id)chromaticityForMatrix:;
- (BOOL)shallUpdateWhitepointFrom:target:;
- (void)updateEDRHeadroom:;
- (void)setUpFlipBookHeaderWithLength:frequency:lux:;
- (void)updateFlipBookEntryWithBrightness:;
- (void)updateFlipBookEntryWithBrightnessLimit:;
- (void)updateFlipBookEntryWithAAPFactor:;
- (void)addFlipBookEntry:;
- (BOOL)sendCurrentFlipBook;
- (void)constructFlipBookData:size:;
- (BOOL)flipBookEntryForID:entry:;
- (BOOL)liveUpdates;
- (void)setLiveUpdates:;
- (BOOL)cancelDCPTransition;
- (void)enableDCPFlipBookUpdates:;
- (int)currentTransitionUpdateID;
- (float)transitionDurationFromCurrent:toTarget:;
- (id)copyContext;
- (void)logTransitionParameters:;
- (float)calculateSpringProgressForLinearProgress:;
- (float)calculateSigmoidProgressForLinearProgress:;
- (float)sigmoidFunction:;
- (BOOL)liveUpdatesOverride;
- (void)setLiveUpdatesOverride:;
- (float)nitsOverride;
- (void)setNitsOverride:;
- (void)setCurrentDisplayNits:;
- (float)brightnessFactor;
- (void)setBrightnessFactor:;
- (BOOL)displayON;
- (float)remainingTransitionLength;
- (void)setRemainingTransitionLength:;
@end
