@interface CBControllerInfo : NSObject
@property (nonatomic) NSArray audioLinkQualityArray;
@property (nonatomic) q bluetoothState;
@property (nonatomic) NSString chipsetID;
@property (nonatomic) NSInteger discoverableState;
@property (nonatomic) NSString firmwareName;
@property (nonatomic) NSString firmwareVersion;
@property (nonatomic) NSData hardwareAddressData;
@property (nonatomic) c hciTransportType;
@property (nonatomic) NSInteger inquiryState;
@property (nonatomic) C lmpVersion;
@property (nonatomic) I productID;
@property (nonatomic) I supportedServices;
@property (nonatomic) S vendorID;
@property (nonatomic) C vendorIDSource;
@property (nonatomic) NSError lastChipsetInitError;
- (unsigned int)productID;
- (void)setVendorID:;
- (id)firmwareVersion;
- (void)setSupportedServices:;
- (unsigned short)vendorID;
- (void)setHardwareAddressData:;
- (unsigned char)vendorIDSource;
- (void)encodeWithXPCObject:;
- (id)descriptionWithLevel:;
- (void)setAudioLinkQualityArray:;
- (void)setProductID:;
- (void)setVendorIDSource:;
- (void)setBluetoothState:;
- (char)hciTransportType;
- (id)lastChipsetInitError;
- (id)initWithXPCObject:error:;
- (int)discoverableState;
- (unsigned int)supportedServices;
- (long long)bluetoothState;
- (void)setLastChipsetInitError:;
- (int)inquiryState;
- (void)setInquiryState:;
- (id)hardwareAddressData;
- (void)setFirmwareName:;
- (void).cxx_destruct;
- (void)setFirmwareVersion:;
- (id)description;
- (id)chipsetID;
- (void)setHciTransportType:;
- (void)setDiscoverableState:;
- (id)firmwareName;
- (unsigned char)lmpVersion;
- (id)audioLinkQualityArray;
- (void)setChipsetID:;
- (void)setLmpVersion:;
@end
