@interface CEKLightingCubeMutableAppearance : CEKLightingCubeAppearance
@property (nonatomic) ^{CGGradient=} background;
@property (nonatomic) ^{CGColor=} topFill;
@property (nonatomic) ^{CGGradient=} topGlow;
@property (nonatomic) ^{CGGradient=} topMask;
@property (nonatomic) ^{CGColor=} bottomFill;
@property (nonatomic) ^{CGGradient=} bottomInnerGlow;
@property (nonatomic) ^{CGGradient=} bottomOuterGlow;
@property (nonatomic) ^{CGGradient=} bottomMask;
@property (nonatomic) ^{CGColor=} verticalFillColor;
@property (nonatomic) double verticalFillBackIntensity;
@property (nonatomic) double verticalFillFrontIntensity;
@property (nonatomic) ^{CGGradient=} topOver;
@property (nonatomic) ^{CGColor=} stroke;
- (id)background;
- (void)setBackground:;
- (void)setStroke:;
- (id)stroke;
- (id)topMask;
- (void)setTopMask:;
- (id)bottomMask;
- (void)setBottomMask:;
- (id)topFill;
- (id)topGlow;
- (id)bottomFill;
- (id)bottomInnerGlow;
- (id)bottomOuterGlow;
- (id)verticalFillColor;
- (double)verticalFillBackIntensity;
- (double)verticalFillFrontIntensity;
- (id)topOver;
- (void)setTopFill:;
- (void)setTopGlow:;
- (void)setBottomFill:;
- (void)setBottomInnerGlow:;
- (void)setBottomOuterGlow:;
- (void)setTopOver:;
- (void)setVerticalFillColor:;
- (void)setVerticalFillFrontIntensity:;
- (void)setVerticalFillBackIntensity:;
@end
