@interface CEMNetworkDNSProxyDeclaration : CEMConfigurationBase
@property (nonatomic) NSString payloadAppBundleIdentifier;
@property (nonatomic) NSString payloadProviderBundleIdentifier;
@property (nonatomic) CEMAnyPayload payloadProviderConfiguration;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void).cxx_destruct;
- (id)copyWithZone:;
- (BOOL)multipleAllowed;
- (BOOL)mustBeSupervised;
- (int)activationLevel;
- (id)assetReferences;
- (BOOL)loadPayload:error:;
- (id)serializePayloadWithAssetProviders:;
- (id)payloadAppBundleIdentifier;
- (void)setPayloadAppBundleIdentifier:;
- (id)payloadProviderBundleIdentifier;
- (void)setPayloadProviderBundleIdentifier:;
- (id)payloadProviderConfiguration;
- (void)setPayloadProviderConfiguration:;
+ (id)profileType;
+ (id)registeredClassName;
+ (id)registeredIdentifier;
+ (id)allowedPayloadKeys;
+ (id)restrictionPayloadKeys;
+ (id)buildWithIdentifier:withAppBundleIdentifier:withProviderBundleIdentifier:withProviderConfiguration:;
+ (id)buildRequiredOnlyWithIdentifier:withAppBundleIdentifier:;
@end
