@interface CHNonTextCandidateStroke : NSObject
@property (nonatomic) q classificationAsNonText;
@property (nonatomic) q substrokesCount;
@property (nonatomic) NSDictionary supportByStrokeIdentifier;
@property (nonatomic) double lineError;
@property (nonatomic) double containerScore;
@property (nonatomic) double lineOrientationAngle;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} bounds;
@property (nonatomic) double boundsDiagonal;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} enlargedBounds;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} rotatedBounds;
@property (nonatomic) CHEncodedStrokeIdentifier strokeIdentifier;
@property (nonatomic) q effectiveClassification;
@property (nonatomic) double support;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (id)bounds;
- (id)mutableCopyWithZone:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (double)support;
- (id)strokeIdentifier;
- (id)initWithStroke:consistingOfSubstrokes:classificationAsNonText:lineOrientation:lineError:containerScore:;
- (id)initWithStrokeIdentifier:substrokesCount:classificationAsNonText:lineOrientation:lineError:containerScore:bounds:boundsDiagonal:enlargedBounds:rotatedBounds:supportByStrokeIdentifier:support:;
- (long long)effectiveClassification;
- (BOOL)isEqualToNonTextCandidateStroke:;
- (long long)classificationAsNonText;
- (long long)substrokesCount;
- (id)supportByStrokeIdentifier;
- (double)lineError;
- (double)containerScore;
- (double)lineOrientationAngle;
- (double)boundsDiagonal;
- (id)enlargedBounds;
- (id)rotatedBounds;
+ (BOOL)supportsSecureCoding;
@end
