@interface CHRecognitionSessionTask : NSObject
@property (nonatomic) CHRecognitionSessionResult outputResult;
@property (nonatomic) q status;
@property (nonatomic) NSObject<OS_dispatch_queue> _recognizersQueue;
@property (nonatomic) CHStrokeClassificationModel strokeClassificationModel;
@property (nonatomic) NSArray subjectStrokeIdentifiers;
@property (nonatomic) BOOL cancelled;
@property (nonatomic) @? partialResultBlock;
@property (nonatomic) CHRecognitionSessionResult inputResult;
@property (nonatomic) <CHRecognitionSessionTaskDelegate> delegate;
@property (nonatomic) NSArray recognitionLocales;
@property (nonatomic) NSArray preferredLocales;
@property (nonatomic) <CHStrokeProvider> strokeProvider;
@property (nonatomic) q recognitionEnvironment;
@property (nonatomic) q strokeGroupingRequirement;
@property (nonatomic) BOOL isHighResponsivenessTask;
@property (nonatomic) BOOL saveInputDrawings;
@property (nonatomic) NSSet forceRecognitionStrokeGroupIdentifiers;
@property (nonatomic) BOOL strokeGroupingOnly;
- (BOOL)cancelled;
- (void)setCancelled:;
- (id)init;
- (void)cancel;
- (void)setDelegate:;
- (void)main;
- (id)delegate;
- (void).cxx_destruct;
- (void)_setStatus:;
- (long long)status;
- (id)preferredLocales;
- (id)strokeProvider;
- (id)clutterFilter;
- (long long)recognitionEnvironment;
- (id)initWithLocales:preferredLocales:strokeProvider:inputResult:recognitionQOSClass:recognitionEnvironment:;
- (id)recognitionResultsForGroupingResult:groupingManager:;
- (id)textCorrectionResultsForGroupingResult:groupingManager:;
- (id)newStrokeClassifier;
- (id)newGroupingManager;
- (id)initWithLocales:preferredLocales:strokeProvider:inputResult:recognitionQOSClass:recognitionEnvironment:isHighResponsivenessTask:strokeClassificationModel:strokeGroupingRequirement:partialResultBlock:;
- (id)initWithLocales:preferredLocales:strokeProvider:inputResult:recognitionQOSClass:recognitionEnvironment:isHighResponsivenessTask:strokeClassificationModel:strokeGroupingRequirement:subjectStrokeIdentifiers:partialResultBlock:;
- (BOOL)_isTransitionValidFromStatus:toStatus:;
- (void)_logResultsIfAppropriateWithStrokeProvider:;
- (id)_textRecognitionResultsForTextStrokeGroup:groupingManager:;
- (id)_tokenizedTextResultForDrawing:usingRecognizer:isRemoteRecognizer:locale:strokeLimit:recognitionError:;
- (id)_recognitionResultsForNonTextStrokeGroup:groupingManager:;
- (id)inputResult;
- (id)recognitionLocales;
- (id)outputResult;
- (void)_setOutputResult:;
- (long long)strokeGroupingRequirement;
- (BOOL)isHighResponsivenessTask;
- (BOOL)saveInputDrawings;
- (void)setSaveInputDrawings:;
- (id)forceRecognitionStrokeGroupIdentifiers;
- (void)setForceRecognitionStrokeGroupIdentifiers:;
- (BOOL)strokeGroupingOnly;
- (void)setStrokeGroupingOnly:;
- (id)_recognizersQueue;
- (id)strokeClassificationModel;
- (id)subjectStrokeIdentifiers;
- (id)partialResultBlock;
- (void)setPartialResultBlock:;
@end
