@interface CJPayNewIAPManager : NSObject
@property (nonatomic) CJPayIAPMonitor monitor;
@property (nonatomic) BOOL enableSK2;
@property (nonatomic) BOOL enableSK1Observer;
@property (nonatomic) BOOL needPendingReturnFail;
@property (nonatomic) NSDictionary bizParams;
@property (nonatomic) @ product;
@property (nonatomic) CJPayIAPRetainUtil retainUtil;
@property (nonatomic) NSString tradeNo;
@property (nonatomic) NSString lastTradeNo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)isSupportNewIAP;
- (BOOL)shouldUseNewIAP;
- (id)tradeNo;
- (void)setLastTradeNo:;
- (id)bizParams;
- (void)configIAPSettings;
- (void)createTradeOrderWithAppID:params:exts:completion:;
- (void)didFinishProductOrder:isBackground:resultType:error:;
- (void)disableIESStoreObserver;
- (BOOL)enableSK1Observer;
- (BOOL)enableSK2;
- (void)event:params:;
- (BOOL)isEnableSK1Observer;
- (BOOL)isEnableSK2;
- (BOOL)isNeedPendingReturnFail;
- (void)keyChainSafeSave:forkey:;
- (id)keyChainStringValueForkey:;
- (id)lastTradeNo;
- (void)monitorWithStage:categoryDic:extralDic:;
- (BOOL)needPendingReturnFail;
- (void)p_didFinishProductOrder:isBackground:resultType:error:;
- (id)p_merchantKey;
- (void)paymentQueue:shouldAddStorePayment:for:;
- (void)prefetchProductsWithIdentifiers:completion:;
- (void)requestSK1ProductsWithIdentifiers:completion:;
- (void)restoreWithUid:callBack:;
- (id)retainUtil;
- (void)setBizParams:;
- (void)setEnableSK1Observer:;
- (void)setEnableSK2:;
- (void)setNeedPendingReturnFail:;
- (void)setRetainUtil:;
- (void)setTradeNo:;
- (void)sk1ConfirmWithCommonParams:bizContentParams:completion:;
- (void)sk2ConfirmWithCommonParams:bizContentParams:completion:;
- (void)startIAPWithParams:product:;
- (void)startupService;
- (id)init;
- (void)setMonitor:;
- (void).cxx_destruct;
- (id)monitor;
- (id)product;
- (void)setProduct:;
- (void)presentCodeRedemptionSheet;
+ (id)shareInstance;
@end
