@interface CJPayDouyinLoadingView : UIView
@property (nonatomic) UIView hudView;
@property (nonatomic) UIImageView logoImageView;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIView showView;
@property (nonatomic) UIStackView dotStackView;
@property (nonatomic) NSMutableArray dotViews;
@property (nonatomic) UILabel subTitleLabel;
@property (nonatomic) BOOL isLoading;
- (void)allowUserInteraction:;
- (id)dotStackView;
- (void)p_dismissWithAnimated:;
- (void)p_setupUI;
- (void)p_showLoadingOnView:;
- (void)p_showLoadingOnView:title:animated:;
- (void)p_showLoadingOnView:title:icon:animated:;
- (void)p_showLoadingOnView:title:subTitle:icon:animated:;
- (void)setDotStackView:;
- (void)setShowView:;
- (id)showView;
- (BOOL)isLoading;
- (id)init;
- (void)setTitleLabel:;
- (void)setIsLoading:;
- (id)containerView;
- (void)setContainerView:;
- (void)setTitle:;
- (void)startAnimating;
- (id)initWithFrame:;
- (void)stopAnimating;
- (void)setIcon:;
- (void).cxx_destruct;
- (void)setSubTitle:;
- (id)titleLabel;
- (id)subTitleLabel;
- (void)setSubTitleLabel:;
- (id)dotViews;
- (void)setDotViews:;
- (id)logoImageView;
- (void)setLogoImageView:;
- (id)hudView;
- (void)setHudView:;
+ (void)dismissWithAnimated:;
+ (id)sharedView;
+ (id)showLoadingOnView:title:animated:afterDelay:;
+ (id)showLoadingOnView:title:icon:animated:afterDelay:;
+ (id)showLoadingOnView:title:subTitle:icon:animated:afterDelay:;
+ (id)showLoadingWithView:onView:;
+ (id)showMessageWithTitle:subTitle:;
+ (id)showWindowLoadingWithTitle:animated:afterDelay:;
@end
