@interface CJPayOPHomePageViewController : CJPayHomePageViewController
@property (nonatomic) CJPayOPHomeContentView outerPayHomeContentView;
@property (nonatomic) CJPayCombinationPaymentViewController combinePayViewController;
@property (nonatomic) CJPayBizChoosePayMethodViewController choosePayMethodVC;
@property (nonatomic) CJPayDefaultChannelShowConfig currentPayConfig;
@property (nonatomic) BOOL isSendToCombinePaymentVC;
@property (nonatomic) NSMutableArray notSufficientFundIdsInCombinePay;
@property (nonatomic) double lastTimestamp;
@property (nonatomic) BOOL isColdLaunch;
- (void)changePayMethodTo:;
- (id)choosePayMethodVC;
- (id)combinePayViewController;
- (void)combinePayWithType:;
- (id)currentPayConfig;
- (void)didClickBannerWithType:;
- (void)didSelectAtIndex:;
- (id)getCurrentContentView;
- (BOOL)isColdLaunch;
- (BOOL)isSecondaryCellView:;
- (BOOL)isSendToCombinePaymentVC;
- (id)notSufficientFundIdsInCombinePay;
- (void)notifyNotsufficient:;
- (void)onConfirmPayAction;
- (id)outerPayHomeContentView;
- (void)p_bindCardSuccess;
- (void)p_checkAuthStatusAndPay;
- (void)p_gotoCombinationPaymentType:;
- (void)p_notifyHomeVCAndChooseVCNotSufficientWithResponse:error:bankCardId:;
- (void)p_showAuthAlertWithAuthUrl:completion:;
- (void)p_tryInsertChooseViewControllerWithNotSufficientID:;
- (void)setChoosePayMethodVC:;
- (void)setCombinePayViewController:;
- (void)setCurrentPayConfig:;
- (void)setIsColdLaunch:;
- (void)setNotSufficientFundIdsInCombinePay:;
- (void)setOuterPayHomeContentView:;
- (void)setupNavigatinBar;
- (void)showState:;
- (void)updateOrderResponse:;
- (void)updatePayTypeView;
- (void)stopLoading;
- (void)setLastTimestamp:;
- (void)startLoading;
- (void).cxx_destruct;
- (double)lastTimestamp;
- (void)viewDidLoad;
- (void)back;
@end
