@interface CJPayIntegratedCashierProcessManager : NSObject
@property (nonatomic) CJPayOrderResultResponse resResponse;
@property (nonatomic) NSDictionary createOrderParams;
@property (nonatomic) CJPayDefaultChannelShowConfig curSelectConfig;
@property (nonatomic) q queryTimes;
@property (nonatomic) <CJPayBizDYPayPlugin> dypayController;
@property (nonatomic) CJPayHalfPageBaseViewController<CJPayIntegratedCashierHomeVCProtocol> homeVC;
@property (nonatomic) UIViewController backVC;
@property (nonatomic) CJPayCreateOrderResponse orderResponse;
@property (nonatomic) @? completionBlock;
@property (nonatomic) NSDictionary lynxRetainTrackerParams;
@property (nonatomic) BOOL orderIsInvalid;
@property (nonatomic) BOOL isPaymentForOuterApp;
@property (nonatomic) NSString combineType;
@property (nonatomic) <CJPayAPIDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)curSelectConfig;
- (void)setCombineType:;
- (void)setResResponse:;
- (id)QRCodeParams:;
- (id)dypayController;
- (id)p_trackerParams;
- (id)backVC;
- (id)buildCommonTrackDic:;
- (void)confirmPayWithConfig:;
- (id)createOrderParams;
- (void)handleComfirmResponse:;
- (void)handleQueryResult:;
- (id)homeVC;
- (id)initWith:bizParams:;
- (BOOL)isPaymentForOuterApp;
- (id)lynxRetainTrackerParams;
- (BOOL)orderIsInvalid;
- (id)orderResponse;
- (id)p_buildConfirmRequestParams;
- (BOOL)p_buttonInfoHandler:;
- (void)p_callCompletionBlock:orderStatus:;
- (BOOL)p_checkNoNetwrok:;
- (BOOL)p_checkOrderValidation;
- (void)p_dypayWithResponse:defaultShowConfig:;
- (unsigned long long)p_getChannelWith:tradeType:;
- (void)p_handleChannelResult:resultType:;
- (void)p_handleClose:;
- (void)p_handleUnistallCase:;
- (BOOL)p_needInvokeLoginAndReturn:;
- (void)p_payWithChannel:response:;
- (void)p_queryOrderResult:;
- (void)p_queryResult:withResultType:completion:;
- (void)p_resultPageLynx:;
- (void)p_resultPageLynxCard:;
- (void)p_resultPageNative:;
- (id)p_resultmodelwithResponse:;
- (void)p_submitConfirmRequest;
- (void)p_updateCreateOrderResponse;
- (void)queryQROrderResult:;
- (long long)queryTimes;
- (void)requestCreateOrderWithBizParams:completion:;
- (void)requestQueryOrderResultWithTradeNo:processInfo:completion:;
- (id)resResponse;
- (void)setBackVC:;
- (void)setCreateOrderParams:;
- (void)setCurSelectConfig:;
- (void)setDypayController:;
- (void)setHomeVC:;
- (void)setIsPaymentForOuterApp:;
- (void)setLynxRetainTrackerParams:;
- (void)setOrderIsInvalid:;
- (void)setOrderResponse:;
- (void)setQueryTimes:;
- (void)trackWithName:params:;
- (void)updateCreateOrderResponseWithCompletionBlock:;
- (void)dealloc;
- (void)setDelegate:;
- (void)setCompletionBlock:;
- (id)delegate;
- (void).cxx_destruct;
- (id)completionBlock;
- (id)combineType;
- (void)pushViewController:;
@end
