@interface CKDPRecordFieldValueEncryptedValue : PBCodable
@property (nonatomic) BOOL hasSignedValue;
@property (nonatomic) q signedValue;
@property (nonatomic) BOOL hasDoubleValue;
@property (nonatomic) double doubleValue;
@property (nonatomic) BOOL hasDateValue;
@property (nonatomic) CKDPDate dateValue;
@property (nonatomic) BOOL hasStringValue;
@property (nonatomic) NSString stringValue;
@property (nonatomic) BOOL hasLocationValue;
@property (nonatomic) CKDPLocationCoordinate locationValue;
@property (nonatomic) BOOL hasReferenceValue;
@property (nonatomic) CKDPRecordReference referenceValue;
@property (nonatomic) Q signedListValuesCount;
@property (nonatomic) ^q signedListValues;
@property (nonatomic) Q doubleListValuesCount;
@property (nonatomic) ^d doubleListValues;
@property (nonatomic) NSMutableArray dateListValues;
@property (nonatomic) NSMutableArray stringListValues;
@property (nonatomic) NSMutableArray locationListValues;
- (void)setHasSignedValue:;
- (BOOL)hasReferenceValue;
- (id)locationValue;
- (void)setSignedValue:;
- (void)setLocationValue:;
- (void)setReferenceValue:;
- (BOOL)hasLocationValue;
- (id)referenceValue;
- (void)addDoubleListValue:;
- (BOOL)hasSignedValue;
- (long long)signedValue;
- (void)setDoubleValue:;
- (id)dateListValues;
- (long long)signedListValueAtIndex:;
- (id)dateValue;
- (void)dealloc;
- (void)addDateListValue:;
- (id)doubleListValues;
- (void)clearDoubleListValues;
- (void)clearSignedListValues;
- (void)setSignedListValues:count:;
- (double)doubleValue;
- (unsigned long long)locationListValuesCount;
- (void)writeTo:;
- (void)clearStringListValues;
- (id)stringListValueAtIndex:;
- (id)dateListValueAtIndex:;
- (BOOL)hasDateValue;
- (id)stringListValues;
- (unsigned long long)hash;
- (void)setDoubleListValues:count:;
- (void)setStringListValues:;
- (void)copyTo:;
- (void)setStringValue:;
- (void)mergeFrom:;
- (void)addLocationListValue:;
- (void)setDateValue:;
- (unsigned long long)dateListValuesCount;
- (unsigned long long)doubleListValuesCount;
- (void)setLocationListValues:;
- (void)clearLocationListValues;
- (id)stringValue;
- (void).cxx_destruct;
- (unsigned long long)signedListValuesCount;
- (BOOL)hasDoubleValue;
- (BOOL)readFrom:;
- (void)addSignedListValue:;
- (id)description;
- (id)locationListValues;
- (void)setHasDoubleValue:;
- (void)setDateListValues:;
- (id)dictionaryRepresentation;
- (double)doubleListValueAtIndex:;
- (id)signedListValues;
- (void)clearDateListValues;
- (unsigned long long)stringListValuesCount;
- (void)addStringListValue:;
- (BOOL)isEqual:;
- (BOOL)hasStringValue;
- (id)locationListValueAtIndex:;
- (id)copyWithZone:;
+ (Class)dateListValueType;
+ (Class)stringListValueType;
+ (Class)locationListValueType;
@end
