@interface CKShareParticipant : NSObject
@property (nonatomic) BOOL wantsNewInvitationToken;
@property (nonatomic) BOOL isCurrentUser;
@property (nonatomic) BOOL isOrgAdminUser;
@property (nonatomic) q mutableInvitationTokenStatus;
@property (nonatomic) CKRecordID shareRecordID;
@property (nonatomic) NSString inviterID;
@property (nonatomic) q originalParticipantRole;
@property (nonatomic) q originalAcceptanceStatus;
@property (nonatomic) q originalPermission;
@property (nonatomic) BOOL createdInProcess;
@property (nonatomic) BOOL acceptedInProcess;
@property (nonatomic) NSData protectionInfo;
@property (nonatomic) NSData protectionInfoPublicKey;
@property (nonatomic) NSData encryptedPersonalInfo;
@property (nonatomic) BOOL isAnonymousInvitedParticipant;
@property (nonatomic) BOOL forceSendPublicKeyForAnonymousParticipants;
@property (nonatomic) NSString participantID;
@property (nonatomic) q acceptanceStatus;
@property (nonatomic) CKUserIdentity userIdentity;
@property (nonatomic) CKDeviceToDeviceShareInvitationToken invitationToken;
@property (nonatomic) q role;
@property (nonatomic) q type;
@property (nonatomic) q permission;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)safari_contact;
- (long long)permission;
- (id)protectionInfo;
- (void)CKDescribePropertiesUsing:;
- (void)setProtectionInfo:;
- (void)setPermission:;
- (id)_initWithUserIdentity:;
- (id)redactedDescription;
- (void)setType:;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (id)debugDescription;
- (void)encodeWithCoder:;
- (void)setRole:;
- (id)userIdentity;
- (long long)type;
- (void).cxx_destruct;
- (void)setUserIdentity:;
- (long long)role;
- (id)description;
- (id)_init;
- (id)participantID;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setParticipantID:;
- (id)encryptedPersonalInfo;
- (void)setEncryptedPersonalInfo:;
- (void)_stripPersonalInfo;
- (long long)invitationTokenStatus;
- (id)unifiedContactsInStore:keysToFetch:error:;
- (long long)acceptanceStatus;
- (void)setAcceptanceStatus:;
- (BOOL)wantsNewInvitationToken;
- (void)setWantsNewInvitationToken:;
- (BOOL)isCurrentUser;
- (void)setIsCurrentUser:;
- (BOOL)isOrgAdminUser;
- (void)setIsOrgAdminUser:;
- (long long)mutableInvitationTokenStatus;
- (void)setMutableInvitationTokenStatus:;
- (id)shareRecordID;
- (void)setShareRecordID:;
- (id)inviterID;
- (void)setInviterID:;
- (long long)originalParticipantRole;
- (void)setOriginalParticipantRole:;
- (long long)originalAcceptanceStatus;
- (void)setOriginalAcceptanceStatus:;
- (long long)originalPermission;
- (void)setOriginalPermission:;
- (BOOL)createdInProcess;
- (void)setCreatedInProcess:;
- (BOOL)acceptedInProcess;
- (void)setAcceptedInProcess:;
- (id)protectionInfoPublicKey;
- (void)setProtectionInfoPublicKey:;
- (BOOL)isAnonymousInvitedParticipant;
- (void)setIsAnonymousInvitedParticipant:;
- (BOOL)forceSendPublicKeyForAnonymousParticipants;
- (void)setForceSendPublicKeyForAnonymousParticipants:;
- (id)invitationToken;
- (void)setInvitationToken:;
+ (BOOL)supportsSecureCoding;
@end
