@interface CKSyncEngineFetchChangesOperation : NSOperation
@property (nonatomic) NSError error;
@property (nonatomic) NSOperationQueue operationQueue;
@property (nonatomic) CKDatabase database;
@property (nonatomic) CKServerChangeToken previousDatabaseServerChangeToken;
@property (nonatomic) CKOperationGroup group;
@property (nonatomic) BOOL shouldFetchDatabaseChanges;
@property (nonatomic) @? networkAttributionBundleIDOverrideBlock;
@property (nonatomic) NSSet zoneIDs;
@property (nonatomic) @? recordZoneWithIDChangedBlock;
@property (nonatomic) @? recordZoneWithIDWasDeletedBlock;
@property (nonatomic) @? recordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock;
@property (nonatomic) @? recordZoneWithIDWasPurgedBlock;
@property (nonatomic) @? databaseChangeTokenUpdatedBlock;
@property (nonatomic) @? fetchDatabaseChangesCompletionBlock;
@property (nonatomic) @? willBeginFetchingChangesForZoneIDsBlock;
@property (nonatomic) @? recordZoneChangesConfigurationBlock;
@property (nonatomic) @? recordWasChangedBlock;
@property (nonatomic) @? recordWithIDWasDeletedBlock;
@property (nonatomic) @? recordZoneChangeTokensUpdatedBlock;
@property (nonatomic) @? recordZoneFetchCompletionBlock;
@property (nonatomic) @? willEnqueueOperationBlock;
@property (nonatomic) @? fetchChangesCompletionBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)transitionToExecuting;
- (id)initWithDatabase:;
- (id)recordZoneWithIDWasDeletedBlock;
- (void)CKDescribePropertiesUsing:;
- (void)setRecordZoneChangeTokensUpdatedBlock:;
- (id)init;
- (void)cancel;
- (void)setWillEnqueueOperationBlock:;
- (void)setRecordZoneWithIDWasPurgedBlock:;
- (void)setRecordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock:;
- (void)setFetchDatabaseChangesCompletionBlock:;
- (void)setRecordWithIDWasDeletedBlock:;
- (id)willEnqueueOperationBlock;
- (void)start;
- (id)recordWithIDWasDeletedBlock;
- (id)redactedDescription;
- (void)setError:;
- (id)recordZoneChangeTokensUpdatedBlock;
- (BOOL)isExecuting;
- (id)operationQueue;
- (id)error;
- (id)fetchDatabaseChangesCompletionBlock;
- (void)setRecordZoneWithIDChangedBlock:;
- (void)setRecordWasChangedBlock:;
- (void)setGroup:;
- (void)setRecordZoneFetchCompletionBlock:;
- (void)setNetworkAttributionBundleIDOverrideBlock:;
- (void)setZoneIDs:;
- (BOOL)isAsynchronous;
- (id)group;
- (id)cancelledError;
- (BOOL)isFinished;
- (id)recordZoneWithIDWasPurgedBlock;
- (id)recordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock;
- (void)fetchRecordZoneChanges;
- (id)recordZoneFetchCompletionBlock;
- (void).cxx_destruct;
- (id)networkAttributionBundleIDOverrideBlock;
- (void)finishWithError:;
- (id)description;
- (void)transitionToFinished;
- (id)recordWasChangedBlock;
- (id)database;
- (id)zoneIDs;
- (id)recordZoneWithIDChangedBlock;
- (void)setRecordZoneWithIDWasDeletedBlock:;
- (void)setOperationQueue:;
- (void)fetchDatabaseChangesThenRecordZoneChanges;
- (id)previousDatabaseServerChangeToken;
- (void)setPreviousDatabaseServerChangeToken:;
- (BOOL)shouldFetchDatabaseChanges;
- (void)setShouldFetchDatabaseChanges:;
- (id)databaseChangeTokenUpdatedBlock;
- (void)setDatabaseChangeTokenUpdatedBlock:;
- (id)willBeginFetchingChangesForZoneIDsBlock;
- (void)setWillBeginFetchingChangesForZoneIDsBlock:;
- (id)recordZoneChangesConfigurationBlock;
- (void)setRecordZoneChangesConfigurationBlock:;
- (id)fetchChangesCompletionBlock;
- (void)setFetchChangesCompletionBlock:;
+ (BOOL)_removesDependenciesAfterFinish;
+ (void)setMaxZonesPerOperation:;
+ (unsigned long long)maxZonesPerOperation;
@end
