@interface CKUploadRequestPersistentStore : NSObject
@property (nonatomic) NSURL databaseURL;
@property (nonatomic) BOOL firstInvocation;
@property (nonatomic) NSObject<OS_dispatch_queue> stateQueue;
- (id)stateQueue;
- (id)databaseURL;
- (void)setCurrentUser:;
- (id)sortedDelayedSyncRecordsForDatabase:;
- (id)metadataForRecordName:;
- (void)setStateQueue:;
- (id)delayedSyncDateForRecord:;
- (id)delayedSyncRecordNamesBeforeAndIncludingDate:;
- (void)readWriteDatabase:async:withCompletionHandler:;
- (void)deleteDatabase;
- (void)readDatabase:async:withCompletionHandler:;
- (long long)delayedSyncCountForRecordName:;
- (id)unarchivedObjectOfClass:fromData:error:;
- (void)clearDatabase;
- (id)delayedSyncRecordNamesAfterDate:;
- (BOOL)firstInvocation;
- (void)setDatabaseURL:;
- (void).cxx_destruct;
- (void)deleteDelayedSyncForRecordName:;
- (void)clearDelayedSyncRecords;
- (id)lastFetchDate;
- (void)persistDelayedSyncForRecordName:withDate:increasingCount:;
- (void)markRecordNameUnrecoverable:;
- (id)currentUser;
- (void)persistSyncEngineMetadata:;
- (id)assetRepairMetadata;
- (id)packageRepairMetadata;
- (id)earliestDelayedSyncDateAfterDate:;
- (void)clearRepairRecords;
- (void)setFirstInvocation:;
- (id)initWithDatabaseURL:;
- (id)allData;
- (id)syncEngineMetadata;
- (void)persistRepairRecord:;
- (void)deleteRepairRecord:;
- (void)setLastFetchDate:;
+ (id)repairRecordToMetadata:;
@end
