@interface CLSActivityReport : CLSReportItem
@property (nonatomic) q contextType;
@property (nonatomic) NSString contextTopic;
@property (nonatomic) NSString contextTitle;
@property (nonatomic) NSString contextAppBundleIdentifier;
@property (nonatomic) NSString contextID;
@property (nonatomic) CLSAggregatedValue time;
@property (nonatomic) CLSAggregatedValue progress;
@property (nonatomic) CLSActivityReportItem primaryReportItem;
@property (nonatomic) NSArray additionalReportItems;
@property (nonatomic) NSString contextStableObjectID;
@property (nonatomic) NSInteger handoutAttachmentType;
@property (nonatomic) NSString handoutAuthorizedObjectID;
- (void)add:;
- (void)setTime:;
- (id)time;
- (long long)contextType;
- (void)setProgress:;
- (id)contextID;
- (void)setContextType:;
- (void)setContextID:;
- (id)initWithCoder:;
- (id)progress;
- (void)encodeWithCoder:;
- (long long)compare:;
- (void).cxx_destruct;
- (id)description;
- (id)dictionaryRepresentation;
- (id)copyWithZone:;
- (id)contextTitle;
- (void)setContextTitle:;
- (void)scalarMultiply:;
- (int)handoutAttachmentType;
- (void)setHandoutAttachmentType:;
- (id)handoutAuthorizedObjectID;
- (void)setHandoutAuthorizedObjectID:;
- (id)contextTopic;
- (void)setContextTopic:;
- (id)contextAppBundleIdentifier;
- (void)setContextAppBundleIdentifier:;
- (id)primaryReportItem;
- (void)setPrimaryReportItem:;
- (id)additionalReportItems;
- (void)setAdditionalReportItems:;
- (id)contextStableObjectID;
- (void)setContextStableObjectID:;
+ (BOOL)supportsSecureCoding;
@end
