@interface CLSCurrentUser : NSObject
@property (nonatomic) NSInteger devMode;
@property (nonatomic) CLSPerson person;
@property (nonatomic) NSString accountIdentifier;
@property (nonatomic) NSString accountPersonaUniqueIdentifier;
@property (nonatomic) NSString clientPersonaUniqueIdentifier;
@property (nonatomic) BOOL hasDataSeparatedAccount;
@property (nonatomic) BOOL requiresPersonaMatch;
@property (nonatomic) BOOL hasMatchingPersona;
@property (nonatomic) Q roles;
@property (nonatomic) NSDictionary locationIDsByAXMRoleType;
@property (nonatomic) BOOL hasManagedAccount;
@property (nonatomic) BOOL hasEDUAccount;
@property (nonatomic) NSString organizationName;
@property (nonatomic) BOOL organizationProgressTrackingAllowed;
@property (nonatomic) BOOL organizationMaidAnalyticsEnabled;
@property (nonatomic) BOOL personMaidAnalyticsEnabled;
@property (nonatomic) q catalogEnvironment;
@property (nonatomic) NSInteger rosterServiceAuthenticationState;
@property (nonatomic) NSInteger handoutServiceAuthenticationState;
@property (nonatomic) NSInteger iCloudDriveAuthenticationState;
@property (nonatomic) BOOL hasUbiquityEnabled;
@property (nonatomic) NSURL schoolworkUbiquitousContainerURL;
@property (nonatomic) NSError schoolworkUbiquitousContainerError;
@property (nonatomic) NSData schoolworkUbiquitousContainerURLSandboxExtension;
@property (nonatomic) CKRecordID orgAdminUserRecordID;
@property (nonatomic) NSError orgAdminUserFetchError;
@property (nonatomic) CKRecordID userRecordID;
@property (nonatomic) NSError userFetchError;
@property (nonatomic) NSURL multimediaCacheDirectoryURL;
@property (nonatomic) NSError multimediaCacheDirectoryURLError;
@property (nonatomic) NSData multimediaCacheDirectoryURLSandboxExtension;
@property (nonatomic) NSString personaUniqueString;
@property (nonatomic) NSString clientPersonaUniqueString;
@property (nonatomic) BOOL isAdministrator;
@property (nonatomic) BOOL isInstructor;
@property (nonatomic) BOOL isStudent;
- (id)personaUniqueString;
- (void)setSchoolworkUbiquitousContainerURL:;
- (void)setOrgAdminUserFetchError:;
- (void)setRoles:;
- (void)setHasDataSeparatedAccount:;
- (BOOL)_hasRole:;
- (int)devMode;
- (void)dealloc;
- (void)setAccountIdentifier:;
- (void)setSchoolworkUbiquitousContainerURLSandboxExtension:;
- (id)accountIdentifier;
- (int)rosterServiceAuthenticationState;
- (unsigned long long)roles;
- (id)multimediaCacheDirectoryURLSandboxExtension;
- (BOOL)isAdministrator;
- (id)clientPersonaUniqueIdentifier;
- (id)accountPersonaUniqueIdentifier;
- (id)orgAdminUserRecordID;
- (id)schoolworkUbiquitousContainerError;
- (void)setMultimediaCacheDirectoryURLError:;
- (id)userFetchError;
- (void)setOrganizationMaidAnalyticsEnabled:;
- (id)initWithCoder:;
- (void)setHasManagedAccount:;
- (id)clientPersonaUniqueString;
- (BOOL)hasDataSeparatedAccount;
- (BOOL)hasEDUAccount;
- (void)setMultimediaCacheDirectoryURLSandboxExtension:;
- (void)setMultimediaCacheDirectoryURL:;
- (BOOL)personMaidAnalyticsEnabled;
- (void)setLocationIDsByAXMRoleType:;
- (void)setOrganizationName:;
- (void)setOrgAdminUserRecordID:;
- (void)encodeWithCoder:;
- (void)setHasEDUAccount:;
- (void)setAccountPersonaUniqueIdentifier:;
- (void)setPersonMaidAnalyticsEnabled:;
- (BOOL)hasRole:;
- (void)setHasMatchingPersona:;
- (BOOL)isInstructor;
- (void)setCatalogEnvironment:;
- (id)multimediaCacheDirectoryURLError;
- (void)setClientPersonaUniqueIdentifier:;
- (void)setSchoolworkUbiquitousContainerError:;
- (void).cxx_destruct;
- (id)userRecordID;
- (BOOL)hasMatchingPersona;
- (id)schoolworkUbiquitousContainerURLSandboxExtension;
- (void)setPerson:;
- (BOOL)requiresPersonaMatch;
- (void)setUserRecordID:;
- (int)handoutServiceAuthenticationState;
- (id)locationIDsByAXMRoleType;
- (void)setRosterServiceAuthenticationState:;
- (id)orgAdminUserFetchError;
- (id)person;
- (unsigned long long)_useRoles;
- (id)description;
- (id)schoolworkUbiquitousContainerURL;
- (void)setHandoutServiceAuthenticationState:;
- (BOOL)hasManagedAccount;
- (id)_init;
- (void)setHasUbiquityEnabled:;
- (BOOL)hasUbiquityEnabled;
- (id)organizationName;
- (void)setOrganizationProgressTrackingAllowed:;
- (BOOL)organizationMaidAnalyticsEnabled;
- (id)multimediaCacheDirectoryURL;
- (void)setRequiresPersonaMatch:;
- (void)setICloudDriveAuthenticationState:;
- (long long)catalogEnvironment;
- (int)iCloudDriveAuthenticationState;
- (void)setDevMode:;
- (BOOL)organizationProgressTrackingAllowed;
- (BOOL)isStudent;
- (void)setUserFetchError:;
- (id)copyWithZone:;
+ (BOOL)supportsSecureCoding;
+ (unsigned long long)userRolesFromUserLocationIDsByAXMRoleType:;
+ (id)magicValue;
@end
