@interface CNCapabilitiesManager : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)isFaceTimeAppAvailable;
- (void)dealloc;
- (BOOL)isMailAppAvailable;
- (BOOL)hasPreviouslyConferencedWithID:;
- (BOOL)_isAppAvailable:;
- (BOOL)hasSiriCapability;
- (id)conferenceURLForPhoneNumber:;
- (BOOL)hasCellularDataCapability;
- (BOOL)isConferencingAvailable;
- (BOOL)hasSMSCapability;
- (BOOL)isPhoneAppAvailable;
- (BOOL)isMMSConfigured;
- (BOOL)isMadridConfigured;
- (void)idStatusUpdatedForDestinations:service:;
- (BOOL)isEmailConfigured;
- (BOOL)areFavoritesAvailable;
- (BOOL)hasForceTouchCapability;
- (void)_startListeningToIDSServiceAvailabilityIfNecessary;
- (BOOL)isSensitiveUIAllowed;
- (BOOL)isFaceTimeAudioAvailable;
- (id)conferenceURLForDestinationID:;
- (void).cxx_destruct;
- (void)addIDSServiceAvailabilityListener:selector:;
- (BOOL)isConferencingEverGonnaBeAvailable;
- (BOOL)hasAdditionalTextTones;
- (void)removeIDSServiceAvailabilityListener:;
- (BOOL)hasCameraCapability;
- (BOOL)hasVibratorCapability;
- (BOOL)hasCellularTelephonyCapability;
- (BOOL)isMessagesAppAvailable;
- (BOOL)hasTelephonyCapability;
- (BOOL)hasCellularTelephonyHardwareCapability;
- (BOOL)isWeiboServiceAvailable;
- (void)_startListeningToIDSIDQueryControllerIfNecessary;
+ (id)defaultCapabilitiesManager;
+ (void)_setDefaultCapabilitiesManager:;
@end
