@interface CNCardPropertyGroup : CNCardGroup
@property (nonatomic) NSArray editingItems;
@property (nonatomic) NSArray deletedItems;
@property (nonatomic) NSString property;
@property (nonatomic) NSArray propertyItems;
@property (nonatomic) CNPolicy policy;
@property (nonatomic) NSDictionary linkedPolicies;
@property (nonatomic) CNContactStore contactStore;
@property (nonatomic) BOOL showActionsWhenEmpty;
@property (nonatomic) BOOL allowsDisplayModePickerActions;
@property (nonatomic) BOOL multiValue;
@property (nonatomic) BOOL fixedValue;
@property (nonatomic) BOOL multiLine;
@property (nonatomic) BOOL allowsAdding;
@property (nonatomic) BOOL modified;
@property (nonatomic) BOOL isAdded;
- (BOOL)modified;
- (id)property;
- (id)policy;
- (BOOL)isRequired;
- (void).cxx_destruct;
- (id)contactStore;
- (id)description;
- (id)displayItems;
- (Class)propertyGroupItemClass;
- (id)editingItems;
- (void)setAllowsDisplayModePickerActions:;
- (BOOL)allowsDisplayModePickerActions;
- (void)reloadDataPreservingChanges:;
- (void)saveChanges;
- (id)initWithProperty:contact:store:policy:linkedPolicies:;
- (BOOL)allowsAdding;
- (BOOL)isMultiValue;
- (BOOL)isFixedValue;
- (BOOL)isMultiLine;
- (id)nextAvailableLabel;
- (BOOL)addEditingItem;
- (void)removeEditingItem:;
- (id)lastEditingItem;
- (void)setEditingItems:;
- (id)_loadPropertyItems;
- (id)_mergeItems:forEditing:;
- (id)_itemToBeMergedWith:fromItems:forEditing:;
- (BOOL)_shouldShowGroupWhenEditing:;
- (BOOL)labelsAreUnique;
- (BOOL)canAddEditingItem;
- (BOOL)_arrayContainsMaxAllowedItems:;
- (void)_updateNameValuesForItems:;
- (id)policyForItem:;
- (void)saveChangesForItems:;
- (id)labelsForItem:options:;
- (id)labelsInUseByGroup;
- (id)itemsUsingLabel:;
- (id)_availableLabelsInLabels:forItem:withValueSelector:usedLabelsCount:;
- (id)_nextAvailableLabelInLabels:withValueSelector:;
- (id)_nextAvailableLabel;
- (id)_nextAvailableInstantMessageService;
- (id)_nextAvailableSocialService;
- (id)propertyItems;
- (id)linkedPolicies;
- (BOOL)showActionsWhenEmpty;
- (void)setShowActionsWhenEmpty:;
- (BOOL)isAdded;
- (void)setIsAdded:;
- (id)deletedItems;
- (void)setDeletedItems:;
+ (id)groupForProperty:contact:store:policy:linkedPolicies:;
@end
