@interface CNContactGridCell : UICollectionViewCell
@property (nonatomic) CNAvatarView avatarView;
@property (nonatomic) CNContactGridClippingView actionsClippingView;
@property (nonatomic) UIView actionsContainerView;
@property (nonatomic) CNQuickActionsView actionsView;
@property (nonatomic) UILabel nameLabel;
@property (nonatomic) CNContact contact;
@property (nonatomic) CNContactFormatter contactFormatter;
@property (nonatomic) <CNAvatarViewDelegate><CNQuickActionsViewDelegate> delegate;
@property (nonatomic) {CGSize=dd} avatarSize;
@property (nonatomic) {UIEdgeInsets=dddd} avatarMargins;
@property (nonatomic) NSDictionary nameTextAttributes;
@property (nonatomic) BOOL showsContactOnTap;
@property (nonatomic) NSArray actionCategories;
@property (nonatomic) CNQuickActionsManager actionsManager;
@property (nonatomic) double maximumActionsWidth;
- (void)setShowsContactOnTap:;
- (void)setActionCategories:;
- (id)actionCategories;
- (id)contactFormatter;
- (id)avatarView;
- (id)contact;
- (id)preferredLayoutAttributesFittingAttributes:;
- (void)setContact:;
- (void)setDelegate:;
- (void)setAvatarView:;
- (void)setContactFormatter:;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)showsContactOnTap;
- (void)updateConstraints;
- (id)nameLabel;
- (void)setNameLabel:;
- (void)setNameTextAttributes:;
- (id)nameTextAttributes;
- (id)actionsView;
- (void)setActionsView:;
- (id)actionsContainerView;
- (void)setActionsContainerView:;
- (id)actionsManager;
- (void)setActionsManager:;
- (id)avatarSize;
- (void)setAvatarSize:;
- (id)avatarMargins;
- (void)setAvatarMargins:;
- (void)_createViewsIfNeeded;
- (id)animationBlockForPreparingToShowActions;
- (id)completionBlockForHidingActions;
- (void)_updateActionsMask;
- (double)maximumActionsWidth;
- (id)actionsClippingView;
- (void)setActionsClippingView:;
+ (double)actionsLeftMargin;
@end
