@interface CNDuplicateContactsController : NSObject
@property (nonatomic) _TtC10ContactsUI18DuplicatesUIHelper duplicatesUIHelper;
@property (nonatomic) CNContactFormatter contactFormatter;
@property (nonatomic) CNUIContactsEnvironment environment;
@property (nonatomic) q newDuplicatesCount;
@property (nonatomic) q allDuplicatesCount;
@property (nonatomic) BOOL isAlreadyFindingDuplicates;
@property (nonatomic) BOOL isPerformingMerge;
@property (nonatomic) double mergeCompletedAt;
@property (nonatomic) q lastIgnoredNewDuplicatesCount;
@property (nonatomic) NSObject<CNContactDataSource> dataSource;
@property (nonatomic) <CNDuplicateContactsControllerDelegate> delegate;
@property (nonatomic) CNContactStore contactStore;
- (void)setLastIgnoredNewDuplicatesCount:;
- (long long)lastIgnoredNewDuplicatesCount;
- (void)setDataSource:;
- (void)willPerformDuplicatesMerge;
- (void)setNewDuplicatesCount:;
- (id)initWithDataSource:environment:delegate:;
- (void)setEnvironment:;
- (BOOL)isPerformingMerge;
- (id)contactFormatter;
- (void)setDuplicatesUIHelper:;
- (void)ignoreNewDuplicatesBanner;
- (void)didSelectUnignoreDuplicate:;
- (void)setIsAlreadyFindingDuplicates:;
- (void)decorateBannerViewCell:;
- (void)refreshManagedDuplicatesWithCompletionBlock:;
- (void)setDelegate:;
- (BOOL)isBusy;
- (void)setAllDuplicatesCount:;
- (double)mergeCompletedAt;
- (void)didSelectMergeAllDuplicates:signaturesToMerge:;
- (void)duplicatesDidChange;
- (void)updateDuplicatesCounts;
- (void)didPerformDuplicatesMerge;
- (void)findDuplicates;
- (id)environment;
- (void)presentSheetBasedMergeForController:showsIgnored:;
- (BOOL)isInMergeCooldown:;
- (void)presentDuplicatesUIFailureAlertForController:;
- (id)duplicatesUIHelper;
- (void)setContactFormatter:;
- (BOOL)isAlreadyFindingDuplicates;
- (id)dataSource;
- (id)delegate;
- (void)setIsPerformingMerge:;
- (void).cxx_destruct;
- (id)contactStore;
- (BOOL)wantsToDisplayNewDuplicatesBanner:;
- (long long)newDuplicatesCount;
- (void)setMergeCompletedAt:;
- (BOOL)hasNewDuplicates;
- (long long)allDuplicatesCount;
- (BOOL)canMergeDuplicates;
- (void)refreshManagedDuplicates;
- (void)performMerge:;
- (void)performIgnoreAll;
- (void)didSelectIgnoreAllDuplicates:signaturesIgnored:;
- (void)resetDuplicates;
+ (id)os_log;
+ (id)defaultContactFormatter;
+ (id)defaultContactFormatterForDataSource:;
@end
