@interface CNEnvironment : CNEnvironmentBase
@property (nonatomic) <CNMetricsReporter> metricsReporter;
@property (nonatomic) <CNAPeopleSuggesterFacade> peopleSuggester;
@property (nonatomic) <CNACDPeopleSuggesterFacade> cdPeopleSuggester;
@property (nonatomic) <CNAutocompleteSuggestedResultPrioritization> suggestedResultPrioritization;
@property (nonatomic) <CNACTStewieFacade> stewie;
@property (nonatomic) DADConnection dataAccessConnection;
@property (nonatomic) <CNFileManager> fileManager;
@property (nonatomic) CNUserDefaults userDefaults;
@property (nonatomic) <CNSchedulerProvider> schedulerProvider;
@property (nonatomic) <CNTimeProvider> timeProvider;
@property (nonatomic) NSNotificationCenter notificationCenter;
@property (nonatomic) <CNEntitlementVerification> entitlementVerifier;
@property (nonatomic) <CNAuthorizationContext> authorizationContext;
@property (nonatomic) <CNLocalizationServices> localizationServices;
@property (nonatomic) NSString mainBundleIdentifier;
@property (nonatomic) NSString defaultCountryCode;
@property (nonatomic) BOOL internalBuild;
@property (nonatomic) BOOL commLimitsEnabled;
- (id)metricsReporter;
- (id)peopleSuggester;
- (id)stewie;
- (id)cdPeopleSuggester;
- (id)suggestedResultPrioritization;
- (id)dataAccessConnection;
- (id)fileManager;
- (BOOL)isInternalBuild;
- (id)init;
- (void)setValue:forKey:;
- (id)timeProvider;
- (id)notificationCenter;
- (id)authorizationContext;
- (id)schedulerProvider;
- (id)mainBundleIdentifier;
- (id)userDefaults;
- (void).cxx_destruct;
- (id)entitlementVerifier;
- (id)defaultCountryCode;
- (id)getDefaultCountryCode;
- (BOOL)isCommLimitsEnabled;
- (BOOL)isCommLimitsEnabledImpl;
- (id)valueForKey:onCacheMiss:;
- (id)localizationServices;
+ (id)defaultEnvironment;
+ (char *)environmentStackKey;
@end
