@interface CNMeCardSharingAvatarViewController : UIViewController
@property (nonatomic) BOOL hasImage;
@property (nonatomic) UIView avatarContainerView;
@property (nonatomic) CAShapeLayer circularLayer;
@property (nonatomic) UIImageView imageView;
@property (nonatomic) UILabel addPhotoLabel;
@property (nonatomic) <CNMeCardSharingAvatarProvider> avatarProvider;
@property (nonatomic) <CNAvatarImageProvider> fallbackImageProvider;
@property (nonatomic) CNAvatarViewController avatarViewController;
@property (nonatomic) UITapGestureRecognizer tapGestureRecognizer;
@property (nonatomic) <CNMeCardSharingAvatarViewControllerDelegate> delegate;
- (void)reload;
- (void)setTapGestureRecognizer:;
- (void)setDelegate:;
- (id)tapGestureRecognizer;
- (BOOL)hasImage;
- (void)viewWillLayoutSubviews;
- (id)delegate;
- (void).cxx_destruct;
- (id)imageView;
- (void)loadView;
- (void)setImageView:;
- (void)viewDidLoad;
- (id)avatarViewController;
- (void)setAvatarViewController:;
- (id)avatarProvider;
- (void)setAvatarProvider:;
- (id)initWithAvatarProvider:;
- (void)updateWithAvatarProvider:;
- (void)didTapAvatarView:;
- (void)updateForChangedImageAnimated:;
- (void)setHasImage:;
- (id)avatarContainerView;
- (void)setAvatarContainerView:;
- (id)circularLayer;
- (void)setCircularLayer:;
- (id)addPhotoLabel;
- (void)setAddPhotoLabel:;
- (id)fallbackImageProvider;
- (void)setFallbackImageProvider:;
@end
