@interface CRTextSequenceRecognizerModelEspresso : CRTextSequenceRecognizerModel
@property (nonatomic) CRNeuralRecognizerConfiguration recognizerConfiguration;
@property (nonatomic) ^v context;
@property (nonatomic) ^v plan;
@property (nonatomic) {?=^vi} network;
@property (nonatomic) NSInteger engine;
@property (nonatomic) NSInteger precision;
@property (nonatomic) {vector<const char * names;
@property (nonatomic) NSString currentConfigurationHash;
@property (nonatomic) NSObject<OS_dispatch_queue> predictionQueue;
@property (nonatomic) NSObject<OS_dispatch_group> predictionGroup;
@property (nonatomic) NSObject<OS_dispatch_semaphore> submissionSemaphore;
@property (nonatomic) NSArray outputNames;
- (void)setPrecision:;
- (void)setPlan:;
- (id)plan;
- (int)engine;
- (void)setEngine:;
- (void)setNetwork:;
- (id)network;
- (void)dealloc;
- (int)precision;
- (id)modelFilePath;
- (id)context;
- (void)setNames:;
- (id)initWithConfiguration:error:;
- (id)names;
- (id)configuration;
- (void).cxx_destruct;
- (void)setContext:;
- (id).cxx_construct;
- (BOOL)preheatWithError:;
- (id)outputNames;
- (id)predictFromInputs:error:;
- (id)inputBatchFromTextFeatures:image:featureWidth:configuration:;
- (id)outputFromOutputBuffers:featureInfo:;
- (id)_modelConfigurationNameForInput:;
- (id)_configurationHashForInput:;
- (id)_configurationHashForInput:batchSize:;
- (BOOL)_setupContextAndPlanForConfiguration:error:;
- (id)_createContextForEngine:configuration:;
- (id)_createBufferWithWidth:height:channels:batchSize:sequenceLength:;
- (BOOL)_shouldReconfigurePlanForInput:;
- (BOOL)_configurePlanForInput:error:;
- (void)_resetEspressoState;
- (void)releaseIntermediateBuffers;
- (id)recognizerConfiguration;
- (void)setRecognizerConfiguration:;
- (id)currentConfigurationHash;
- (void)setCurrentConfigurationHash:;
- (id)predictionQueue;
- (void)setPredictionQueue:;
- (id)predictionGroup;
- (void)setPredictionGroup:;
- (id)submissionSemaphore;
- (void)setSubmissionSemaphore:;
@end
