@interface CSAttributeEvaluator : NSObject
@property (nonatomic) Q options;
@property (nonatomic) BOOL fuzzyMatching;
@property (nonatomic) Q matcherCount;
@property (nonatomic) r^^v matchers;
@property (nonatomic) Q queryTermCount;
@property (nonatomic) Q matchersPerTerm;
@property (nonatomic) ^v tokenizer;
@property (nonatomic) NSMutableArray tokenizedQueryTerms;
@property (nonatomic) NSString language;
@property (nonatomic) NSArray queryTerms;
@property (nonatomic) NSString queryString;
@property (nonatomic) BOOL matchOncePerTerm;
- (void)setOptions:;
- (void)dealloc;
- (id)matchers;
- (void)setLanguage:;
- (id)language;
- (void)setTokenizer:;
- (unsigned long long)options;
- (id)tokenizer;
- (void).cxx_destruct;
- (void)setMatchers:;
- (id)queryString;
- (id)initWithQuery:language:fuzzyThreshold:options:;
- (void)processTranscriptionTokens:;
- (BOOL)processPropertyToken:length:tokenType:range:index:evaluationHandler:;
- (id)queryTerms;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:withHandler:;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:skipTranscriptions:withHandler:;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:skipTranscriptions:withFuzzyHandler:;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:strongCompounds:withHandler:;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:strongCompounds:skipTranscriptions:withHandler:;
- (unsigned long long)evaluateAttribute:ignoreSubtokens:strongCompounds:skipTranscriptions:withFuzzyHandler:;
- (BOOL)matchOncePerTerm;
- (void)setMatchOncePerTerm:;
- (BOOL)fuzzyMatching;
- (void)setFuzzyMatching:;
- (unsigned long long)matcherCount;
- (void)setMatcherCount:;
- (unsigned long long)queryTermCount;
- (void)setQueryTermCount:;
- (unsigned long long)matchersPerTerm;
- (void)setMatchersPerTerm:;
- (id)tokenizedQueryTerms;
- (void)setTokenizedQueryTerms:;
+ (void)enumerateTokensForString:locale:options:withHandler:;
@end
