@interface CSJEcomCouponModel : NSObject
@property (nonatomic) q user_id;
@property (nonatomic) NSString coupon_meta_id;
@property (nonatomic) NSString unique_id;
@property (nonatomic) q device_id;
@property (nonatomic) BOOL has_coupon;
@property (nonatomic) q coupon_scene;
@property (nonatomic) q type;
@property (nonatomic) q threshold;
@property (nonatomic) NSString scene_key;
@property (nonatomic) q activity_id;
@property (nonatomic) q amount;
@property (nonatomic) q action;
@property (nonatomic) q style;
@property (nonatomic) NSString start_time;
@property (nonatomic) NSString expire_time;
@property (nonatomic) NSString button_text;
@property (nonatomic) NSString extra;
@property (nonatomic) NSString toast;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setButton_text:;
- (void)setExpire_time:;
- (void)setActivity_id:;
- (long long)activity_id;
- (id)button_text;
- (BOOL)canApplyCoupon;
- (BOOL)canShowToast;
- (id)coupon_meta_id;
- (long long)coupon_scene;
- (id)expire_time;
- (BOOL)has_coupon;
- (id)scene_key;
- (void)setCoupon_meta_id:;
- (void)setCoupon_scene:;
- (void)setExtra:;
- (void)setHas_coupon:;
- (void)setScene_key:;
- (void)setStart_time:;
- (void)setUser_id:;
- (long long)threshold;
- (id)extra;
- (id)toDictionary;
- (void)setType:;
- (void)setStyle:;
- (long long)action;
- (id)initWithCoder:;
- (void)setAction:;
- (long long)device_id;
- (void)encodeWithCoder:;
- (long long)type;
- (void).cxx_destruct;
- (long long)style;
- (void)setDevice_id:;
- (void)setThreshold:;
- (id)unique_id;
- (id)start_time;
- (void)setUnique_id:;
- (long long)amount;
- (void)setAmount:;
- (void)setToast:;
- (id)toast;
- (long long)user_id;
+ (id)modelCustomPropertyMapper;
+ (id)fromDictionary:;
@end
