@interface CSJNativeExpressRewardDrawDisplayViewController : UIViewController
@property (nonatomic) NSArray expressAdViews;
@property (nonatomic) UIViewController parentVC;
@property (nonatomic) CSJAdSlot slot;
@property (nonatomic) UITableView tableView;
@property (nonatomic) CSJRewardedVideoTopBarView topBarView;
@property (nonatomic) CSJNativeExpressRewardDrawUpSwipArrowView guideView;
@property (nonatomic) CSJNativeExpressRewardUpSwipBottomView swipBottomView;
@property (nonatomic) CSJMaterialMeta firstMaterialMeta;
@property (nonatomic) CSJURitSettingModel ritModel;
@property (nonatomic) Q curIndex;
@property (nonatomic) Q oldIndex;
@property (nonatomic) CSJNativeExpressRewardDrawAdView curDrawAdView;
@property (nonatomic) CSJMaterialMeta curMaterialMeta;
@property (nonatomic) BOOL isMute;
@property (nonatomic) NSString playStartTimestamp;
@property (nonatomic) BOOL isShowAlert;
@property (nonatomic) BUTimer rewardCountDownTimer;
@property (nonatomic) q rewardCountDownSecond;
@property (nonatomic) BUTimer skipCountDownTimer;
@property (nonatomic) q skipCountDownSecond;
@property (nonatomic) BUTimer residentTimer;
@property (nonatomic) CSJNativeExpressRewardDrawRewardSender rewardSender;
@property (nonatomic) CSJNativeExpressRewardDrawEndcardTransfer endcardTransfer;
@property (nonatomic) BOOL didCallbackPlayError;
@property (nonatomic) q residentCount;
@property (nonatomic) <CSJNativeExpressVideoAdDelegate> rewardedVideoAd;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)endcardTransfer;
- (id)curMaterialMeta;
- (id)rewardedVideoAd;
- (void)setIsShowAlert:;
- (void)videoTopBarDislikeButtonTapped:;
- (void)addGuideImageView;
- (void)addTableView;
- (void)addTopBarView;
- (id)curDrawAdView;
- (unsigned long long)curIndex;
- (BOOL)didCallbackPlayError;
- (id)expressAdViews;
- (id)firstMaterialMeta;
- (void)hiddenSwipBottomView;
- (id)initWithExpressAdViews:parentVC:slot:;
- (BOOL)isShowAlert;
- (unsigned long long)oldIndex;
- (id)playStartTimestamp;
- (void)preloadEndcard;
- (void)receiveWillResignActiveNotification:;
- (void)receivedidBecomeActiveNotification:;
- (void)refreshTopBarAndReward;
- (void)regsiterNotification;
- (void)removeGuideImageView;
- (void)reportScrollEvent;
- (id)residentTimer;
- (void)residentTimerAction:;
- (long long)rewardCountDownSecond;
- (id)rewardCountDownTimer;
- (void)rewardDrawAdView:player:stateDidChanged:;
- (void)rewardDrawAdViewDidPlayFinish:player:error:;
- (void)rewardDrawAdViewDimissCurrentVC:;
- (void)rewardDrawAdViewEnableScroll:;
- (long long)rewardDrawAdViewGetRewardLeftTime;
- (void)rewardDrawAdViewInteractSkipDuration:;
- (void)rewardDrawAdViewIsShowAlert:adView:;
- (id)rewardDrawAdViewReportGetAdExtraDic;
- (void)rewardDrawAdViewShowNextAd;
- (void)rewardDrawAdViewSwitchToEndcard:;
- (unsigned long long)rewardPlayTime;
- (id)rewardSender;
- (id)ritModel;
- (void)sendReward;
- (void)setCurIndex:;
- (void)setDidCallbackPlayError:;
- (void)setEndcardTransfer:;
- (void)setExpressAdViews:;
- (void)setFirstMaterialMeta:;
- (void)setIsMute:;
- (void)setOldIndex:;
- (void)setPlayStartTimestamp:;
- (void)setResidentTimer:;
- (void)setRewardCountDownSecond:;
- (void)setRewardCountDownTimer:;
- (void)setRewardSender:;
- (void)setRewardedVideoAd:;
- (void)setRitModel:;
- (void)setSkipCountDownSecond:;
- (void)setSkipCountDownTimer:;
- (void)setSwipBottomView:;
- (void)showGuideImageView;
- (void)showSwipBottomView;
- (long long)skipCountDownSecond;
- (id)skipCountDownTimer;
- (void)startResidentTimer;
- (void)startRewardCountDownTimer;
- (void)startSkipCountDownTimer;
- (void)stopResidentTimer;
- (void)stopRewardCountDownTimer;
- (void)stopSkipCountDownTimer;
- (void)storeKitDidClose:;
- (void)storeKitWillOpen:;
- (id)swipBottomView;
- (void)updateRewardLeftSeconds:;
- (void)updateSkipLeftSeconds:;
- (void)videoTopBarCloseButtonTapped:;
- (void)videoTopBarSilentButtonTapped:;
- (void)scrollViewDidEndDecelerating:;
- (BOOL)shouldAutorotate;
- (long long)preferredInterfaceOrientationForPresentation;
- (id)slot;
- (void)dealloc;
- (long long)residentCount;
- (BOOL)prefersStatusBarHidden;
- (id)tableView:cellForRowAtIndexPath:;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (void)setSlot:;
- (double)tableView:heightForRowAtIndexPath:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)setTableView:;
- (void)tableView:didEndDisplayingCell:forRowAtIndexPath:;
- (unsigned long long)supportedInterfaceOrientations;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (id)tableView;
- (long long)tableView:numberOfRowsInSection:;
- (void)viewDidLoad;
- (void)setResidentCount:;
- (id)topBarView;
- (void)setTopBarView:;
- (void)initData;
- (BOOL)isMute;
- (id)parentVC;
- (void)setParentVC:;
- (void)setGuideView:;
- (id)guideView;
@end
