@interface CSJSDWebImageDownloaderOperation : NSOperation
@property (nonatomic) NSMutableArray callbackTokens;
@property (nonatomic) Q options;
@property (nonatomic) NSDictionary context;
@property (nonatomic) BOOL executing;
@property (nonatomic) BOOL finished;
@property (nonatomic) NSMutableData imageData;
@property (nonatomic) NSData cachedData;
@property (nonatomic) Q expectedSize;
@property (nonatomic) Q receivedSize;
@property (nonatomic) NSURLResponse response;
@property (nonatomic) NSError responseError;
@property (nonatomic) double previousProgress;
@property (nonatomic) BOOL downloadCompleted;
@property (nonatomic) <CSJSDWebImageDownloaderResponseModifier> responseModifier;
@property (nonatomic) <CSJSDWebImageDownloaderDecryptor> decryptor;
@property (nonatomic) NSURLSession unownedSession;
@property (nonatomic) NSURLSession ownedSession;
@property (nonatomic) NSURLSessionTask dataTask;
@property (nonatomic) NSURLSessionTaskMetrics metrics;
@property (nonatomic) NSOperationQueue coderQueue;
@property (nonatomic) NSMapTable imageMap;
@property (nonatomic) Q backgroundTaskId;
@property (nonatomic) NSURLRequest request;
@property (nonatomic) NSURLCredential credential;
@property (nonatomic) double minimumProgressInterval;
@property (nonatomic) NSIndexSet acceptableStatusCodes;
@property (nonatomic) NSSet acceptableContentTypes;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)acceptableContentTypes;
- (id)acceptableStatusCodes;
- (id)addHandlersForProgress:completed:;
- (id)addHandlersForProgress:completed:decodeOptions:;
- (unsigned long long)backgroundTaskId;
- (void)callCompletionBlockWithToken:image:imageData:error:finished:;
- (void)callCompletionBlocksWithError:;
- (void)callCompletionBlocksWithImage:imageData:error:finished:;
- (void)cancelInternal;
- (void)checkDoneWithImageData:finishedTokens:;
- (id)coderQueue;
- (id)imageMap;
- (id)initWithRequest:inSession:options:;
- (id)initWithRequest:inSession:options:context:;
- (BOOL)isDownloadCompleted;
- (double)minimumProgressInterval;
- (id)ownedSession;
- (unsigned long long)receivedSize;
- (id)responseModifier;
- (void)setAcceptableContentTypes:;
- (void)setAcceptableStatusCodes:;
- (void)setBackgroundTaskId:;
- (void)setCallbackTokens:;
- (void)setCoderQueue:;
- (void)setDecryptor:;
- (void)setDownloadCompleted:;
- (void)setExpectedSize:;
- (void)setImageMap:;
- (void)setMinimumProgressInterval:;
- (void)setOwnedSession:;
- (void)setReceivedSize:;
- (void)setResponseModifier:;
- (void)setUnownedSession:;
- (BOOL)shouldContinueWhenAppEntersBackground;
- (void)startCoderOperationWithImageData:pendingTokens:finishedTokens:;
- (id)unownedSession;
- (void)URLSession:dataTask:didReceiveData:;
- (void)setOptions:;
- (id)responseError;
- (void)setFinished:;
- (void)setResponseError:;
- (void)URLSession:task:didReceiveChallenge:completionHandler:;
- (void)setDataTask:;
- (id)init;
- (void)cancel;
- (void)setImageData:;
- (id)cachedData;
- (void)setMetrics:;
- (id)context;
- (id)metrics;
- (id)dataTask;
- (BOOL)cancel:;
- (void)URLSession:task:didCompleteWithError:;
- (id)imageData;
- (void)start;
- (void)URLSession:task:didFinishCollectingMetrics:;
- (void)URLSession:dataTask:didReceiveResponse:completionHandler:;
- (BOOL)isExecuting;
- (void)URLSession:dataTask:willCacheResponse:completionHandler:;
- (id)request;
- (id)credential;
- (BOOL)isAsynchronous;
- (BOOL)isFinished;
- (unsigned long long)options;
- (id)response;
- (void).cxx_destruct;
- (void)reset;
- (void)setResponse:;
- (void)setContext:;
- (void)setExecuting:;
- (void)done;
- (void)setCachedData:;
- (double)previousProgress;
- (void)setPreviousProgress:;
- (void)setCredential:;
- (id)callbackTokens;
- (unsigned long long)expectedSize;
- (id)decryptor;
+ (unsigned long long)imageOptionsFromDownloaderOptions:;
@end
