@interface CSJToastConfig : NSObject
@property (nonatomic) q postion;
@property (nonatomic) UIFont textFont;
@property (nonatomic) UIColor textColor;
@property (nonatomic) UIColor backgroundColor;
@property (nonatomic) float duration;
@property (nonatomic) double cornerRadius;
@property (nonatomic) {UIEdgeInsets=dddd} insets;
@property (nonatomic) NSString message;
@property (nonatomic) q alignment;
@property (nonatomic) {CGSize=dd} superViewSize;
@property (nonatomic) {CGPoint=dd} location;
@property (nonatomic) @? showCompletion;
@property (nonatomic) @? dismissCompletion;
- (long long)postion;
- (id)dismissCompletion;
- (void)setDismissCompletion:;
- (void)setPostion:;
- (void)setShowCompletion:;
- (void)setSuperViewSize:;
- (id)showCompletion;
- (id)superViewSize;
- (id)init;
- (void)setBackgroundColor:;
- (void)setAlignment:;
- (void)setMessage:;
- (id)backgroundColor;
- (void)setInsets:;
- (id)textFont;
- (id)insets;
- (id)location;
- (void)setDuration:;
- (void)setTextColor:;
- (void)setCornerRadius:;
- (void)setLocation:;
- (id)message;
- (void).cxx_destruct;
- (id)textColor;
- (double)cornerRadius;
- (long long)alignment;
- (float)duration;
- (void)setTextFont:;
@end
