@interface CSJUgenAggregationEcommerecAdapter : CSJUgenAggregationAdapter
@property (nonatomic) CSJRewardVideoAdCountDownWidgetView countDownView;
@property (nonatomic) BOOL isShowingLoadMoreAlert;
@property (nonatomic) NSDate dismissLoadMoreAlertDate;
@property (nonatomic) BOOL showOnceEcommerec;
- (void)ecommerecOnTapHandlerWithEvent:;
- (void)resumeCountDown;
- (void)ugenAggregationContentViewClose;
- (void)aggregationAlertCancleAction;
- (void)aggregationAlertSureAction;
- (id)countDownView;
- (id)dismissLoadMoreAlertDate;
- (void)ecommerecOnDismissHandlerWithEvent:;
- (void)ecommerecOnExposureHandlerWithEvent:;
- (void)ecommerecOnScrollHandlerWithEvent:;
- (void)ecommerecOnSlideHandlerWithEvent:;
- (void)invalidateCountDown;
- (BOOL)isShowingLoadMoreAlert;
- (BOOL)isValidCountDown;
- (void)p_loadDataTimesReachedLimit;
- (void)pauseCountDown;
- (long long)pbu_ecommerecRewardTime;
- (BOOL)pbu_shouldShowUgenAggregationAlert;
- (void)scheduleCountDown;
- (void)setCountDownView:;
- (void)setDismissLoadMoreAlertDate:;
- (void)setIsShowingLoadMoreAlert:;
- (void)setShowOnceEcommerec:;
- (BOOL)shouldShowUgenAggregationAlert;
- (BOOL)showOnceEcommerec;
- (void)ugenAggregationContentViewRender;
- (void)ugenAggregationCountDownWidgetRender;
- (void)ugenAggregationSendReward;
- (void)ugenAggregationTopBarRender;
- (long long)ugenAggregationTopBarStyle;
- (void)ugenContentView:event:;
- (void)ugenContentView:loadFailWithInfo:error:;
- (void)ugenContentView:loadFinishWithInfo:;
- (void)ugenContentView:loadStartWithInfo:;
- (void)ugenRecylerLayoutWidget:didEndDecelerating:;
- (void)ugenRecylerLayoutWidget:didEndDragging:willDecelerate:;
- (double)ugenRewardPayCountDown;
- (void)vmAggregationLoadData;
- (void)vmAggregationViewDidAppear;
- (void)vmAggregationViewDidDisappear;
- (void)vmAggregationViewDidLoad;
- (void).cxx_destruct;
@end
