@interface CSJUnionRequestModel : CSJRequestModel
@property (nonatomic) NSString requestID;
@property (nonatomic) NSString adSDKVersion;
@property (nonatomic) NSString userID;
@property (nonatomic) NSString did;
@property (nonatomic) CSJUser user;
@property (nonatomic) NSString sourceType;
@property (nonatomic) CSJApp app;
@property (nonatomic) CSJDevice device;
@property (nonatomic) NSString ua;
@property (nonatomic) NSString ip;
@property (nonatomic) NSString ipv4;
@property (nonatomic) NSString ipv6;
@property (nonatomic) NSMutableArray adslotsAry;
@property (nonatomic) NSNumber req_type;
@property (nonatomic) NSNumber ts;
@property (nonatomic) NSString req_sign;
@property (nonatomic) NSArray source_temai_product_ids;
@property (nonatomic) CSJABTest abTest;
@property (nonatomic) NSArray network_id_list;
@property (nonatomic) CSJAdSlot slot;
@property (nonatomic) NSNumber code_group_id;
@property (nonatomic) NSString extra_data;
@property (nonatomic) NSString material_keys;
@property (nonatomic) q rawReqbodyLength;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)network_id_list;
- (void)setDid:;
- (id)did;
- (id)_mergedJSONStringWithJSONString:coverJSONString:;
- (id)abTest;
- (id)adSDKVersion;
- (id)adslotsAry;
- (id)code_group_id;
- (id)csj_dictionaryValue;
- (id)extra_data;
- (id)material_keys;
- (long long)rawReqbodyLength;
- (id)req_sign;
- (id)req_type;
- (void)setAbTest:;
- (void)setAdSDKVersion:;
- (void)setAdslotsAry:;
- (void)setCode_group_id:;
- (void)setExtra_data:;
- (void)setMaterial_keys:;
- (void)setNetwork_id_list:;
- (void)setRawReqbodyLength:;
- (void)setReq_sign:;
- (void)setReq_type:;
- (void)setSource_temai_product_ids:;
- (void)setUa:;
- (id)source_temai_product_ids;
- (id)ua;
- (void)setUser:;
- (id)slot;
- (id)app;
- (id)userID;
- (id)init;
- (void)setApp:;
- (id)sourceType;
- (id)ts;
- (void)setDevice:;
- (void)setSourceType:;
- (id)dictionaryValue;
- (void)setSlot:;
- (id)user;
- (id)requestID;
- (void).cxx_destruct;
- (void)setUserID:;
- (void)setTs:;
- (id)device;
- (void)setRequestID:;
- (void)setIpv4:;
- (void)setIpv6:;
- (id)ipv4;
- (id)ipv6;
- (void)setIp:;
- (id)ip;
+ (id)unionRequestModel:slotParams:reqType:;
@end
