@interface CVAPRDevice : NSObject
@property (nonatomic) q referenceFrame;
@property (nonatomic) CVAPRRangeMeasurement range;
@property (nonatomic) CVAPRAngleMeasurement azimuth;
@property (nonatomic) CVAPRAngleMeasurement elevation;
@property (nonatomic) NSUUID UUID;
@property (nonatomic) NSNumber sessionID;
@property (nonatomic) q measurementNumber;
@property (nonatomic) double measurementTimestamp;
@property (nonatomic) double timestamp;
@property (nonatomic) double mach_continuous_time;
@property (nonatomic) double utc_time;
- (void)setReferenceFrame:;
- (void)setSessionID:;
- (id)sessionID;
- (id)init;
- (void)setRange:;
- (void)setUUID:;
- (id)azimuth;
- (id)initWithCoder:;
- (long long)referenceFrame;
- (id)range;
- (void)encodeWithCoder:;
- (void)setTimestamp:;
- (void).cxx_destruct;
- (double)timestamp;
- (id)UUID;
- (void)setAzimuth:;
- (id)elevation;
- (void)setElevation:;
- (void)addTimes;
- (long long)measurementNumber;
- (void)setMeasurementNumber:;
- (double)measurementTimestamp;
- (void)setMeasurementTimestamp:;
- (double)mach_continuous_time;
- (void)setMach_continuous_time:;
- (double)utc_time;
- (void)setUtc_time:;
+ (BOOL)supportsSecureCoding;
+ (id)classes;
@end
