@interface CXCallControllerHostConnection : NSObject
@property (nonatomic) NSObject<OS_dispatch_queue> serialQueue;
@property (nonatomic) NSXPCConnection connection;
@property (nonatomic) BOOL hasPushToTalkBackgroundMode;
@property (nonatomic) BOOL hasVoIPBackgroundMode;
@property (nonatomic) NSString applicationIdentifier;
@property (nonatomic) NSURL bundleURL;
@property (nonatomic) NSSet capabilities;
@property (nonatomic) <CXCallControllerVendorProtocol> remoteObjectProxy;
@property (nonatomic) BOOL entitledForPublicAPI;
@property (nonatomic) BOOL entitledForPrivateAPI;
@property (nonatomic) BOOL callTransactionRequestPermitted;
@property (nonatomic) BOOL channelTransactionRequestPermitted;
@property (nonatomic) <CXCallControllerHostConnectionDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)applicationIdentifier;
- (void)setCapabilities:;
- (id)init;
- (void)dealloc;
- (id)bundleURL;
- (id)capabilities;
- (void)setApplicationIdentifier:;
- (void)setBundleURL:;
- (void)setDelegate:;
- (id)remoteObjectProxy;
- (id)serialQueue;
- (BOOL)hasVoIPBackgroundMode;
- (id)removeCall:;
- (BOOL)isPermittedToUsePrivateAPI;
- (id)delegate;
- (id)connection;
- (void).cxx_destruct;
- (BOOL)isPermittedToUsePublicAPI;
- (void)setConnection:;
- (id)description;
- (void)setSerialQueue:;
- (id)addOrUpdateCall:;
- (id)requestCalls:;
- (id)requestTransaction:reply:;
- (id)initWithConnection:serialQueue:;
- (BOOL)isCallTransactionRequestPermitted;
- (BOOL)isChannelTransactionRequestPermitted;
- (BOOL)hasPushToTalkBackgroundMode;
- (void)setHasPushToTalkBackgroundMode:;
- (void)setHasVoIPBackgroundMode:;
@end
