@interface DJTableViewVMOptionsController : UIViewController
@property (nonatomic) UITableView tableView;
@property (nonatomic) DJTableViewVM tableViewVM;
@property (nonatomic) BOOL multipleChoice;
@property (nonatomic) NSString originalValue;
@property (nonatomic) NSArray optionsArray;
@property (nonatomic) @? completionHandler;
@property (nonatomic) NSString rightButtonTitle;
@property (nonatomic) @? rightButtonClickHandler;
@property (nonatomic) NSString separateCharater;
@property (nonatomic) q tableViewStyle;
- (void)setTableViewVM:;
- (void)checkCellWithValue:;
- (void)configTable;
- (id)initWithRow:options:multipleChoice:completionHandler:;
- (void)multipleCheckCellWithValue:;
- (BOOL)multipleChoice;
- (void)onTouchRightButton;
- (id)readCurrentValue;
- (id)rightButtonClickHandler;
- (id)rightButtonTitle;
- (id)separateCharater;
- (void)setMultipleChoice:;
- (void)setOptionsArray:;
- (void)setRightButtonClickHandler:;
- (void)setRightButtonTitle:;
- (void)setSeparateCharater:;
- (id)tableViewVM;
- (void)setCompletionHandler:;
- (void).cxx_destruct;
- (void)setTableView:;
- (id)optionsArray;
- (id)tableView;
- (void)viewDidLoad;
- (id)completionHandler;
- (long long)tableViewStyle;
- (void)setTableViewStyle:;
- (id)originalValue;
- (void)setOriginalValue:;
@end
