@interface DOCConfiguration : NSObject
@property (nonatomic) NSArray documentContentTypes;
@property (nonatomic) NSArray urls;
@property (nonatomic) DOCConcreteLocation defaultLocation;
@property (nonatomic) Q interactionMode;
@property (nonatomic) BOOL shouldIgnoreInteractionMode;
@property (nonatomic) BOOL inProcess;
@property (nonatomic) NSDictionary allowedConversions;
@property (nonatomic) BOOL shouldConvert;
@property (nonatomic) NSArray excludedDocumentContentTypes;
@property (nonatomic) NSArray recentDocumentsContentTypes;
@property (nonatomic) NSString hostIdentifier;
@property (nonatomic) NSString hostBundleTitle;
@property (nonatomic) BOOL forBrowsingInApp;
@property (nonatomic) BOOL forPickingDocuments;
@property (nonatomic) BOOL forPickingFolders;
@property (nonatomic) BOOL forMovingDocuments;
@property (nonatomic) BOOL forSavingDocuments;
@property (nonatomic) BOOL isPickerUI;
@property (nonatomic) BOOL supportsRemovableFileProviders;
@property (nonatomic) BOOL forPickingDownloadsFolder;
@property (nonatomic) BOOL supportsRelatedFilesInPicker;
@property (nonatomic) BOOL isContentManaged;
@property (nonatomic) BOOL neverCreateBookmarkForOpenInPlace;
@property (nonatomic) BOOL pickingItemsShouldBumpLastOpenDate;
@property (nonatomic) BOOL suppressBlackCallout;
@property (nonatomic) BOOL preferLastUsedDate;
@property (nonatomic) BOOL isFilesApp;
@property (nonatomic) BOOL isPopover;
@property (nonatomic) BOOL isWidget;
@property (nonatomic) BOOL isPopoverOrWidget;
@property (nonatomic) BOOL shouldOpenInApp;
@property (nonatomic) NSArray hiddenSourcesIdentifiers;
@property (nonatomic) BOOL restoreLastVisitedLocation;
@property (nonatomic) BOOL saveLastVisitedLocation;
@property (nonatomic) BOOL collectionSupportsDragAndDrop;
@property (nonatomic) q maximumNumberOfItemsToFetch;
@property (nonatomic) q maximumNumberOfRows;
@property (nonatomic) BOOL skipDownload;
@property (nonatomic) BOOL presentingMakesCollectionFirstResponder;
@property (nonatomic) BOOL showCollectionControls;
@property (nonatomic) BOOL supportsColumnView;
@property (nonatomic) BOOL supportsNavigationTitleMenus;
@property (nonatomic) BOOL shouldAdjustContentInset;
@property (nonatomic) BOOL useSharedQuickLook;
@property (nonatomic) BOOL useExpandedSourceList;
@property (nonatomic) Q browserViewContext;
@property (nonatomic) NSString roleIdentifier;
@property (nonatomic) NSString stateIdentifier;
@property (nonatomic) NSString sceneIdentifier;
@property (nonatomic) NSArray forbiddenActionIdentifiers;
@property (nonatomic) double thumbnailFetchingTimeOut;
- (id)init;
- (id)urls;
- (BOOL)isContentManaged;
- (void)setIsContentManaged:;
- (id)sceneIdentifier;
- (id)initWithCoder:;
- (void)setSceneIdentifier:;
- (void)setUrls:;
- (id)defaultLocation;
- (void)encodeWithCoder:;
- (BOOL)isEqualToConfiguration:;
- (void).cxx_destruct;
- (id)hostIdentifier;
- (void)setHostIdentifier:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setForPickingDocuments:;
- (void)setForPickingDownloadsFolder:;
- (BOOL)forPickingDownloadsFolder;
- (unsigned long long)interactionMode;
- (long long)maximumNumberOfRows;
- (id)stateIdentifier;
- (void)setStateIdentifier:;
- (BOOL)isWidget;
- (BOOL)shouldOpenInApp;
- (void)setInteractionMode:;
- (BOOL)shouldConvert;
- (void)setRecentDocumentsContentTypes:;
- (id)hostBundleTitle;
- (BOOL)isPickerUI;
- (BOOL)isFilesApp;
- (id)allowedConversions;
- (BOOL)forSavingDocuments;
- (BOOL)forPickingFolders;
- (BOOL)forPickingDocuments;
- (void)setSupportsRemovableFileProviders:;
- (unsigned long long)interactionModeForPreparing;
- (BOOL)inProcess;
- (id)roleIdentifier;
- (BOOL)shouldIgnoreInteractionMode;
- (id)recentDocumentsContentTypes;
- (id)documentContentTypes;
- (void)setDocumentContentTypes:;
- (BOOL)isPopover;
- (BOOL)forBrowsingInApp;
- (BOOL)isPopoverOrWidget;
- (void)setDefaultLocation:;
- (void)setShouldIgnoreInteractionMode:;
- (void)setInProcess:;
- (void)setAllowedConversions:;
- (void)setShouldConvert:;
- (id)excludedDocumentContentTypes;
- (void)setExcludedDocumentContentTypes:;
- (void)setHostBundleTitle:;
- (void)setForPickingFolders:;
- (BOOL)forMovingDocuments;
- (void)setForMovingDocuments:;
- (BOOL)supportsRemovableFileProviders;
- (BOOL)supportsRelatedFilesInPicker;
- (void)setSupportsRelatedFilesInPicker:;
- (BOOL)neverCreateBookmarkForOpenInPlace;
- (void)setNeverCreateBookmarkForOpenInPlace:;
- (BOOL)pickingItemsShouldBumpLastOpenDate;
- (void)setPickingItemsShouldBumpLastOpenDate:;
- (BOOL)suppressBlackCallout;
- (void)setSuppressBlackCallout:;
- (BOOL)preferLastUsedDate;
- (void)setPreferLastUsedDate:;
- (void)setShouldOpenInApp:;
- (id)hiddenSourcesIdentifiers;
- (void)setHiddenSourcesIdentifiers:;
- (BOOL)restoreLastVisitedLocation;
- (void)setRestoreLastVisitedLocation:;
- (BOOL)saveLastVisitedLocation;
- (void)setSaveLastVisitedLocation:;
- (BOOL)collectionSupportsDragAndDrop;
- (void)setCollectionSupportsDragAndDrop:;
- (long long)maximumNumberOfItemsToFetch;
- (void)setMaximumNumberOfItemsToFetch:;
- (void)setMaximumNumberOfRows:;
- (BOOL)skipDownload;
- (void)setSkipDownload:;
- (BOOL)presentingMakesCollectionFirstResponder;
- (void)setPresentingMakesCollectionFirstResponder:;
- (BOOL)showCollectionControls;
- (void)setShowCollectionControls:;
- (BOOL)supportsColumnView;
- (void)setSupportsColumnView:;
- (BOOL)supportsNavigationTitleMenus;
- (void)setSupportsNavigationTitleMenus:;
- (BOOL)shouldAdjustContentInset;
- (void)setShouldAdjustContentInset:;
- (BOOL)useSharedQuickLook;
- (void)setUseSharedQuickLook:;
- (BOOL)useExpandedSourceList;
- (void)setUseExpandedSourceList:;
- (unsigned long long)browserViewContext;
- (void)setBrowserViewContext:;
- (void)setRoleIdentifier:;
- (id)forbiddenActionIdentifiers;
- (void)setForbiddenActionIdentifiers:;
- (double)thumbnailFetchingTimeOut;
- (void)setThumbnailFetchingTimeOut:;
+ (BOOL)supportsSecureCoding;
+ (id)configurationForImportingDocumentsWithConversionRules:;
+ (id)configurationForImportingDocumentsWithContentTypes:mode:;
+ (id)configurationForFolderPicking;
+ (id)configurationForExportingDocumentsToURLs:mode:;
+ (id)configurationForOpeningDocumentsOfApplicationWithBundleIdentifier:;
+ (id)configurationForImportingDocumentContentTypes:mode:;
+ (id)pickableContentTypesFromAllowedConversions:;
@end
