@interface DOMHTMLTableCellElement : DOMHTMLElement
@property (nonatomic) NSInteger cellIndex;
@property (nonatomic) NSString align;
@property (nonatomic) NSString axis;
@property (nonatomic) NSString bgColor;
@property (nonatomic) NSString ch;
@property (nonatomic) NSString chOff;
@property (nonatomic) NSInteger colSpan;
@property (nonatomic) NSInteger rowSpan;
@property (nonatomic) NSString headers;
@property (nonatomic) NSString height;
@property (nonatomic) BOOL noWrap;
@property (nonatomic) NSString vAlign;
@property (nonatomic) NSString width;
@property (nonatomic) NSString abbr;
@property (nonatomic) NSString scope;
- (void)setScope:;
- (void)setAxis:;
- (id)scope;
- (void)setWidth:;
- (void)setHeaders:;
- (id)height;
- (id)width;
- (void)setHeight:;
- (id)axis;
- (id)headers;
- (int)rowSpan;
- (int)colSpan;
- (id)bgColor;
- (void)setBgColor:;
- (int)cellIndex;
- (id)_cellAbove;
- (id)align;
- (void)setAlign:;
- (id)ch;
- (void)setCh:;
- (id)chOff;
- (void)setChOff:;
- (void)setColSpan:;
- (void)setRowSpan:;
- (BOOL)noWrap;
- (void)setNoWrap:;
- (id)vAlign;
- (void)setVAlign:;
- (id)abbr;
- (void)setAbbr:;
@end
