@interface DOMHTMLSelectElement : DOMHTMLElement
@property (nonatomic) BOOL autofocus;
@property (nonatomic) BOOL disabled;
@property (nonatomic) DOMHTMLFormElement form;
@property (nonatomic) BOOL multiple;
@property (nonatomic) NSString name;
@property (nonatomic) NSInteger size;
@property (nonatomic) NSString type;
@property (nonatomic) DOMHTMLOptionsCollection options;
@property (nonatomic) NSInteger length;
@property (nonatomic) NSInteger selectedIndex;
@property (nonatomic) NSString value;
@property (nonatomic) BOOL willValidate;
- (id)createPeripheral;
- (void)_startAssistingDocumentView:;
- (void)_stopAssistingDocumentView:;
- (BOOL)_requiresAccessoryView;
- (BOOL)_requiresInputView;
- (BOOL)_supportsAutoFill;
- (BOOL)nodeCanBecomeFirstResponder;
- (void)setDisabled:;
- (void)setName:;
- (int)selectedIndex;
- (void)remove:;
- (BOOL)disabled;
- (void)setValue:;
- (id)options;
- (id)type;
- (id)value;
- (int)length;
- (id)name;
- (void)setSize:;
- (int)size;
- (void)setSelectedIndex:;
- (id)listItemAtIndex:;
- (void)_activateItemAtIndex:allowMultipleSelection:;
- (void)_activateItemAtIndex:;
- (id)form;
- (id)item:;
- (BOOL)multiple;
- (unsigned int)completeLength;
- (BOOL)autofocus;
- (void)setAutofocus:;
- (BOOL)willValidate;
- (id)namedItem:;
- (void)setMultiple:;
- (void)add:before:;
- (void)add::;
- (int)structuralComplexityContribution;
@end
