@interface DYOpenDBStorage : NSObject
@property (nonatomic) NSString name;
@property (nonatomic) FMDatabaseQueue dbQueue;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (long long)getInt64ForKey:;
- (id)KVItemForKey:;
- (BOOL)_createDBTableWithName:dbQueue:;
- (int)getInt32ForKey:;
- (id)jsonItemForKey:;
- (id)_getObjectOfClass:forKey:;
- (BOOL)dropStorage;
- (void)enumerateKeys:;
- (double)getDoubleForKey:;
- (id)getObjectOfClass:forKey:;
- (id)initWithStorageID:dbQueue:;
- (id)initWithStorageID:rootPath:;
- (int)limitSize;
- (int)storageSizeInBytes;
- (BOOL)updateStorageSize:;
- (BOOL)containsKey:;
- (BOOL)_removeObjectForKey:;
- (void)_close;
- (BOOL)_setObject:forKey:;
- (BOOL)setObject:forKey:;
- (void)setName:;
- (BOOL)setDouble:forKey:;
- (BOOL)setBool:forKey:;
- (id)allKeys;
- (BOOL)setInt32:forKey:;
- (void)close;
- (BOOL)removeAllObjects;
- (unsigned long long)type;
- (void).cxx_destruct;
- (id)name;
- (BOOL)removeObjectForKey:;
- (BOOL)setInt64:forKey:;
- (id)dbQueue;
- (unsigned long long)getCount;
- (BOOL)getBoolForKey:;
- (void)setDbQueue:;
+ (id)shareInstance;
@end
