@interface EDSearchableIndexRichLinkItem : NSObject
@property (nonatomic) NSString richLinkPersistentID;
@property (nonatomic) NSString messagePersistentID;
@property (nonatomic) EDSearchableIndexRichLinkItemMetadatum metadatum;
@property (nonatomic) BOOL requiresPreprocessing;
@property (nonatomic) NSString richLinkItemIdentifier;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString identifier;
@property (nonatomic) NSString domainIdentifier;
@property (nonatomic) q indexingType;
@property (nonatomic) NSDate dateReceived;
@property (nonatomic) Q itemInstantiationTime;
@property (nonatomic) Q estimatedSizeInBytes;
@property (nonatomic) NSData underlyingData;
@property (nonatomic) BOOL hasCompleteData;
@property (nonatomic) BOOL alwaysMarkAsIndexed;
@property (nonatomic) BOOL shouldExcludeFromIndex;
- (id)domainIdentifier;
- (id)identifier;
- (id)searchableItem;
- (long long)compare:;
- (void).cxx_destruct;
- (id)dateReceived;
- (void)preprocess;
- (id)underlyingData;
- (void)setIndexingType:;
- (long long)indexingType;
- (id)messagePersistentID;
- (BOOL)shouldExcludeFromIndex;
- (void)setNeedsAllAttributesIndexingType;
- (void)setNeedsAllAttributesIncludingDataDetectionResultsIndexingType;
- (id)fetchIndexableAttachments;
- (void)setMessagePersistentID:;
- (unsigned long long)itemInstantiationTime;
- (unsigned long long)estimatedSizeInBytes;
- (void)setUnderlyingData:;
- (BOOL)hasCompleteData;
- (BOOL)alwaysMarkAsIndexed;
- (BOOL)requiresPreprocessing;
- (id)metadatum;
- (void)setMetadatum:;
- (void)setRequiresPreprocessing:;
- (id)richLinkItemIdentifier;
- (id)initWithRichLinkItemIdentifier:messagePersistentID:metadatum:;
- (id)richLinkPersistentID;
- (void)setRichLinkPersistentID:;
+ (id)log;
+ (id)richLinkItemIdentifierFromSearchableItemIdentifier:;
+ (id)messageIDandRichLinkIDFromRichLinkIdentifier:;
+ (id)completeSearchableIndexRichLinkItemIdentifierFromID:;
@end
