@interface EKCalendarNotification : NSObject
@property (nonatomic) q type;
@property (nonatomic) NSString uniqueIdentifier;
@property (nonatomic) NSString title;
@property (nonatomic) NSString name;
@property (nonatomic) NSString firstName;
@property (nonatomic) NSString lastName;
@property (nonatomic) NSString emailAddress;
@property (nonatomic) NSString phoneNumber;
@property (nonatomic) NSURL URL;
@property (nonatomic) NSString recipientName;
@property (nonatomic) EKObjectID objectID;
@property (nonatomic) ^{CGColor=} dotColor;
@property (nonatomic) BOOL hiddenFromNotificationCenter;
@property (nonatomic) BOOL alerted;
@property (nonatomic) BOOL needsAlert;
@property (nonatomic) BOOL couldBeJunk;
@property (nonatomic) EKSource source;
@property (nonatomic) EKCalendar calendar;
@property (nonatomic) EKEvent event;
@property (nonatomic) BOOL isCurrentUserForSharing;
@property (nonatomic) BOOL isCurrentUserForScheduling;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)emailAddress;
- (void)setLastName:;
- (void)setCalendar:;
- (id)objectID;
- (void)setObjectID:;
- (void)setEvent:;
- (id)calendar;
- (void)dealloc;
- (id)event;
- (void)setName:;
- (id)phoneNumber;
- (id)uniqueIdentifier;
- (void)setEmailAddress:;
- (void)setFirstName:;
- (void)setPhoneNumber:;
- (void)setType:;
- (id)firstName;
- (id)lastName;
- (void)setTitle:;
- (long long)type;
- (id)title;
- (void).cxx_destruct;
- (id)source;
- (id)name;
- (void)setSource:;
- (void)setURL:;
- (id)URL;
- (id)initWithType:;
- (id)recipientName;
- (void)setRecipientName:;
- (BOOL)alerted;
- (BOOL)isSharedCalendarInvitation;
- (void)setDotColor:;
- (BOOL)needsAlert;
- (BOOL)isInvitation;
- (BOOL)acknowledgeWithEventStore:error:;
- (BOOL)isProposedNewTime;
- (BOOL)proposedStartDateIsInFutureForAttendee:;
- (id)dotColor;
- (BOOL)hiddenFromNotificationCenter;
- (void)setHiddenFromNotificationCenter:;
- (void)setAlerted:;
- (BOOL)couldBeJunk;
- (void)setCouldBeJunk:;
@end
