@interface EMCollection : EMRepositoryObject
@property (nonatomic) <EFCancelable> cancelationToken;
@property (nonatomic) NSHashTable changeObservers;
@property (nonatomic) <EFScheduler> queryScheduler;
@property (nonatomic) <EFScheduler> observerScheduler;
@property (nonatomic) EFQuery query;
@property (nonatomic) EFFuture allItemIDs;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q signpostID;
- (void)refresh;
- (unsigned long long)signpostID;
- (void)dealloc;
- (void)enumerateObserversWithBlock:;
- (id)query;
- (id)observerScheduler;
- (void)setChangeObservers:;
- (id)initWithObjectID:query:;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (id)cancelationToken;
- (void).cxx_destruct;
- (void)stopObserving:;
- (id)changeObservers;
- (void)setCancelationToken:;
- (void)_cancelQuery;
- (id)initWithQuery:repository:;
- (void)beginObserving:;
- (void)_commonInitWithQuery:;
- (id)queryScheduler;
- (id)objectIDForItemID:;
- (id)itemIDForObjectID:;
- (BOOL)objectIDBelongsToCollection:;
- (void)insertItemIDs:before:;
- (void)insertItemIDs:after:;
- (id)removeItemIDs:;
- (BOOL)containsItemID:includeRecovery:;
- (id)firstExistingItemIDAfterItemID:;
- (id)firstExistingItemIDBeforeItemID:;
- (id)_firstExistingItemIDForItemID:inReverse:;
- (id)iterateItemIDsStartingAtItemID:inReverse:withBlock:;
- (id)_iterateItemIDsStartingAtItemID:inReverse:includeStartingItem:withBlock:;
- (void)notifyChangeObserversAboutAddedItemIDs:before:extraInfo:;
- (void)notifyChangeObserversAboutAddedItemIDs:after:extraInfo:;
- (void)notifyChangeObserversAboutChangesByItemIDs:;
- (void)notifyChangeObserver:stockedItemIDs:;
- (id)allItemIDs;
- (void)_performQuery;
- (void)_performQueryIfNeeded;
- (void)_cancelQueryIfNeeded;
- (BOOL)isRecovering;
- (void)finishRecovery;
- (void)queryDidStartRecovery;
- (void)queryMatchedAddedObjectIDs:before:extraInfo:;
- (void)queryMatchedAddedObjectIDs:after:extraInfo:;
- (void)queryMatchedMovedObjectIDs:before:;
- (void)queryMatchedMovedObjectIDs:after:;
- (void)queryMatchedChangesByObjectIDs:;
- (void)queryAnticipatesDeletedObjectIDs:;
- (void)queryMatchedDeletedObjectIDs:;
- (void)queryDidFinishInitialLoad;
- (void)queryDidFinishRemoteSearch;
- (id)_itemIDsForObjectIDs:;
- (void)_filterAndTransformObjectIDs:before:existingObjectID:batchBlock:;
- (BOOL)observerContainsObjectID:;
- (void)queryReplacedObjectID:withNewObjectID:;
- (void)notifyChangeObserverAboutStockedItemIDs:;
+ (id)log;
+ (BOOL)supportsSecureCoding;
+ (id)signpostLog;
@end
