@interface EMVIPManager : NSObject
@property (nonatomic) EMRemoteConnection connection;
@property (nonatomic) EFPromise vipsByIdentifierPromise;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSSet allVIPWaitForResult;
@property (nonatomic) NSSet allVIPs;
@property (nonatomic) EAEmailAddressSet allVIPEmailAddresses;
@property (nonatomic) BOOL hasVIPs;
- (void)_reset;
- (id)init;
- (void)dealloc;
- (void)getAllVIPsWithCompletion:;
- (void)removeVIPsWithEmailAddresses:;
- (id)initWithRemoteConnection:;
- (BOOL)isVIPAddress:;
- (id)connection;
- (void).cxx_destruct;
- (void)setConnection:;
- (id)allVIPs;
- (id)allVIPEmailAddresses;
- (id)allVIPWaitForResult;
- (BOOL)hasVIPs;
- (void)saveVIPs:;
- (void)removeVIPsWithIdentifiers:;
- (id)vipWithIdentifier:;
- (void)didFinishBlockingMainThreadForFuture:;
- (void)didStartBlockingMainThreadForFuture:;
- (void)observer:gotVIPs:;
- (void)observer:updatedVIPs:removedVIPs:;
- (void)_startObservingVIPChangesIfNecessary;
- (id)_vipsByIdentifierFuture;
- (id)_vipsByIdentifier;
- (id)vipsByIdentifierPromise;
- (void)setVipsByIdentifierPromise:;
+ (id)log;
+ (id)remoteInterface;
@end
