@interface FigCaptureCameraParameters : NSObject
@property (nonatomic) NSInteger meteorHeadroomProcessingType;
@property (nonatomic) NSDictionary cameraParameters;
@property (nonatomic) NSDictionary cameraTuningParameters;
@property (nonatomic) NSDictionary motionAttachmentsParameters;
@property (nonatomic) NSDictionary videoStabilizationParameters;
@property (nonatomic) NSDictionary videoStabilizationSTFParameters;
@property (nonatomic) NSDictionary stereoDisparityParameters;
@property (nonatomic) NSDictionary commonNRFParameters;
@property (nonatomic) NSInteger nrfVersion;
@property (nonatomic) NSInteger distortionCorrectionVersion;
@property (nonatomic) NSDictionary commonVideoGreenGhostMitigationParameters;
@property (nonatomic) NSInteger videoGreenGhostMitigationVersion;
@property (nonatomic) NSDictionary photoEncoderParameters;
@property (nonatomic) NSInteger deepZoomVersion;
- (id)videoStabilizationSTFParameters;
- (BOOL)portraitPreviewForegroundBlurEnabledForPortType:sensorIDString:zoomFactor:;
- (id)init;
- (id)landmarksVersionForInferenceType:;
- (BOOL)chromaticDefringingEnabledForSlomoForPortType:sensorIDString:;
- (void)dealloc;
- (id)sensorIDDictionaryForStream:;
- (id)quadraSubPixelSwitchingParametersForPortType:sensorIDString:;
- (int)disparityVersionForPortType:sensorIDString:;
- (id)stereoDisparityParameters;
- (int)deepZoomVersion;
- (id)portraitSceneMonitoringParametersForPortType:sensorIDString:zoomFactor:;
- (int)depthProcessorVersion;
- (int)focusPixelDisparityVersionForPortType:sensorIDString:;
- (int)disparityRefinementTypeForPortType:sensorIDString:zoomFactor:;
- (BOOL)chromaticDefringingEnabledForVideoForPortType:sensorIDString:;
- (int)videoGreenGhostMitigationVersion;
- (BOOL)panoramaRequiresLTMLockingForPortType:sensorIDString:;
- (int)distortionCorrectionVersion;
- (id)commonNRFParameters;
- (id)commonVideoGreenGhostMitigationParameters;
- (id)initWithContentsOfFile:;
- (BOOL)complementMatteSuppressionDecisionWithISPDetectedFaces;
- (int)learnedMattingVersion;
- (int)fsdNetStereoImagesAlignmentForPortType:sensorIDString:;
- (id)actionCameraSceneMonitoringParametersForPortType:sensorIDString:;
- (int)mattingVersionForPortType:sensorIDString:;
- (int)videoStabilizationProcessorVersion;
- (id)videoStabilizationParameters;
- (int)sdofRenderingVersionForPortType:sensorIDString:zoomFactor:;
- (id)focalLengthCharacterizationForStream:;
- (id)photoEncoderParameters;
- (id)sensorIDDictionaryForPortType:sensorIDString:;
- (int)disparityVersion;
- (id)chromaticDefringingParametersForPortType:sensorIDString:;
- (int)portraitSceneMonitorVersionForPortType:sensorIDString:zoomFactor:;
- (int)nrfVersion;
- (id)cameraParameters;
- (id)initWithModelSpecificName:;
- (int)meteorHeadroomProcessingType;
- (unsigned int)landmarksConstellationPointCountForInferenceType:;
- (int)personSemanticsVersion;
- (id)motionAttachmentsParameters;
- (int)coreImagePortraitFilterVersion;
- (id)cameraTuningParameters;
+ (id)sharedInstance;
+ (id)sensorIDStringFromModuleInfo:;
+ (int)movieFileMaxLossyCompressionLevelForPixelFormat:;
+ (int)stillImageMaxLossyCompressionLevel;
+ (unsigned int)sensorIDFromSensorIDString:;
+ (int)previewMaxLossyCompressionLevel;
+ (id)sdofTuningParametersForSensorIDDictionary:zoomFactor:;
+ (int)videoDataMaxLossyCompressionLevel;
+ (id)sensorIDStringFromMetadata:;
@end
