@interface FLEXProtocol : NSObject
@property (nonatomic) NSString name;
@property (nonatomic) @ tag;
@property (nonatomic) FLEXObjectExplorerDefaults defaults;
@property (nonatomic) BOOL isEditable;
@property (nonatomic) BOOL isCallable;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Protocol objc_protocol;
@property (nonatomic) NSString name;
@property (nonatomic) NSArray requiredMethods;
@property (nonatomic) NSArray optionalMethods;
@property (nonatomic) NSArray protocols;
@property (nonatomic) NSString imagePath;
@property (nonatomic) NSArray properties;
@property (nonatomic) NSArray requiredProperties;
@property (nonatomic) NSArray optionalProperties;
@property (nonatomic) @ tag;
- (id)defaults;
- (void)setDefaults:;
- (BOOL)isEditable;
- (BOOL)isCallable;
- (id)currentValueWithTarget:;
- (id)previewWithTarget:;
- (id)viewerWithTarget:;
- (id)editorWithTarget:section:;
- (long long)suggestedAccessoryTypeWithTarget:;
- (id)reuseIdentifierWithTarget:;
- (id)additionalActionsWithTarget:sender:;
- (id)copiableMetadataWithTarget:;
- (id)contextualSubtitleWithTarget:;
- (long long)compare:;
- (id)initWithProtocol:;
- (id)description;
- (id)debugDescription;
- (void)examine;
- (BOOL)conformsTo:;
- (id)objc_protocol;
- (id)name;
- (id)requiredMethods;
- (id)optionalMethods;
- (id)protocols;
- (id)imagePath;
- (id)properties;
- (id)requiredProperties;
- (id)optionalProperties;
- (id)tag;
- (void)setTag:;
- (void).cxx_destruct;
+ (id)allProtocols;
+ (id)protocol:;
@end
