@interface FLOWSchemaFLOWDomainContext : SISchemaInstrumentationMessage
@property (nonatomic) FLOWSchemaFLOWVoiceShortcutContext voiceShortcutContext;
@property (nonatomic) BOOL hasVoiceShortcutContext;
@property (nonatomic) FLOWSchemaFLOWHomeAutomationContext homeAutomationContext;
@property (nonatomic) BOOL hasHomeAutomationContext;
@property (nonatomic) FLOWSchemaFLOWPhoneCallContext phoneCallContext;
@property (nonatomic) BOOL hasPhoneCallContext;
@property (nonatomic) FLOWSchemaFLOWSmsContext smsContext;
@property (nonatomic) BOOL hasSmsContext;
@property (nonatomic) FLOWSchemaFLOWMediaPlayerContext mediaPlayerContext;
@property (nonatomic) BOOL hasMediaPlayerContext;
@property (nonatomic) FLOWSchemaFLOWIdentityContext identityContext;
@property (nonatomic) BOOL hasIdentityContext;
@property (nonatomic) FLOWSchemaFLOWBriefingContext briefingContext;
@property (nonatomic) BOOL hasBriefingContext;
@property (nonatomic) FLOWSchemaFLOWPegasusContext pegasusContext;
@property (nonatomic) BOOL hasPegasusContext;
@property (nonatomic) FLOWSchemaFLOWInformationPluginContext informationPluginContext;
@property (nonatomic) BOOL hasInformationPluginContext;
@property (nonatomic) FLOWSchemaFLOWHomeCommunicationContext homeCommunicationContext;
@property (nonatomic) BOOL hasHomeCommunicationContext;
@property (nonatomic) NSData jsonData;
@property (nonatomic) Q whichDomaincontext;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (void)setVoiceShortcutContext:;
- (id)voiceShortcutContext;
- (void)deleteVoiceShortcutContext;
- (void)setHomeAutomationContext:;
- (id)homeAutomationContext;
- (void)deleteHomeAutomationContext;
- (void)setPhoneCallContext:;
- (id)phoneCallContext;
- (void)deletePhoneCallContext;
- (void)setSmsContext:;
- (id)smsContext;
- (void)deleteSmsContext;
- (void)setMediaPlayerContext:;
- (id)mediaPlayerContext;
- (void)deleteMediaPlayerContext;
- (void)setIdentityContext:;
- (id)identityContext;
- (void)deleteIdentityContext;
- (void)setBriefingContext:;
- (id)briefingContext;
- (void)deleteBriefingContext;
- (void)setPegasusContext:;
- (id)pegasusContext;
- (void)deletePegasusContext;
- (void)setInformationPluginContext:;
- (id)informationPluginContext;
- (void)deleteInformationPluginContext;
- (void)setHomeCommunicationContext:;
- (id)homeCommunicationContext;
- (void)deleteHomeCommunicationContext;
- (unsigned long long)whichDomaincontext;
- (BOOL)hasVoiceShortcutContext;
- (void)setHasVoiceShortcutContext:;
- (BOOL)hasHomeAutomationContext;
- (void)setHasHomeAutomationContext:;
- (BOOL)hasPhoneCallContext;
- (void)setHasPhoneCallContext:;
- (BOOL)hasSmsContext;
- (void)setHasSmsContext:;
- (BOOL)hasMediaPlayerContext;
- (void)setHasMediaPlayerContext:;
- (BOOL)hasIdentityContext;
- (void)setHasIdentityContext:;
- (BOOL)hasBriefingContext;
- (void)setHasBriefingContext:;
- (BOOL)hasPegasusContext;
- (void)setHasPegasusContext:;
- (BOOL)hasInformationPluginContext;
- (void)setHasInformationPluginContext:;
- (BOOL)hasHomeCommunicationContext;
- (void)setHasHomeCommunicationContext:;
@end
