@interface FLOWSchemaFLOWSmsTextContentMetadata : SISchemaInstrumentationMessage
@property (nonatomic) I messageCharLength;
@property (nonatomic) BOOL hasMessageCharLength;
@property (nonatomic) I messageWordLength;
@property (nonatomic) BOOL hasMessageWordLength;
@property (nonatomic) FLOWSchemaFLOWKeyboardUsageMetadata flowKeyboardUsageMetadata;
@property (nonatomic) BOOL hasFlowKeyboardUsageMetadata;
@property (nonatomic) BOOL isPunctuationUsed;
@property (nonatomic) BOOL hasIsPunctuationUsed;
@property (nonatomic) BOOL isPayloadMultilingual;
@property (nonatomic) BOOL hasIsPayloadMultilingual;
@property (nonatomic) NSData jsonData;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (void)setMessageCharLength:;
- (BOOL)hasMessageCharLength;
- (void)setHasMessageCharLength:;
- (void)deleteMessageCharLength;
- (void)setMessageWordLength:;
- (BOOL)hasMessageWordLength;
- (void)setHasMessageWordLength:;
- (void)deleteMessageWordLength;
- (BOOL)hasFlowKeyboardUsageMetadata;
- (void)deleteFlowKeyboardUsageMetadata;
- (void)setIsPunctuationUsed:;
- (BOOL)hasIsPunctuationUsed;
- (void)setHasIsPunctuationUsed:;
- (void)deleteIsPunctuationUsed;
- (void)setIsPayloadMultilingual:;
- (BOOL)hasIsPayloadMultilingual;
- (void)setHasIsPayloadMultilingual:;
- (void)deleteIsPayloadMultilingual;
- (unsigned int)messageCharLength;
- (unsigned int)messageWordLength;
- (id)flowKeyboardUsageMetadata;
- (void)setFlowKeyboardUsageMetadata:;
- (BOOL)isPunctuationUsed;
- (BOOL)isPayloadMultilingual;
- (void)setHasFlowKeyboardUsageMetadata:;
@end
