@interface FTUserConfiguration : NSObject
@property (nonatomic) ^{__CTServerConnection=} ctServerConnection;
@property (nonatomic) NSMutableDictionary nonBTAllowedCache;
@property (nonatomic) BOOL shouldCacheCTConnection;
@property (nonatomic) BOOL _nonWifiFaceTimeEntitled;
@property (nonatomic) BOOL cellularFaceTimeEnabled;
@property (nonatomic) BOOL allowAnyNetwork;
@property (nonatomic) NSArray selectedPhoneNumberRegistrationSubscriptionLabels;
@property (nonatomic) NSNumber selectedPhoneNumberRegistrationSubscriptionNumber;
@property (nonatomic) BOOL isDeviceInDualPhoneIdentityMode;
@property (nonatomic) BOOL isDeviceInManualPhoneSelectionMode;
- (id)init;
- (id)ctServerConnection;
- (void)dealloc;
- (void)setCellularFaceTimeEnabled:;
- (id)nonBTAllowedCache;
- (BOOL)_getNonBluetoothDataAllowedForBundleID:;
- (BOOL)cellularFaceTimeEnabled;
- (void)_clearCaches;
- (BOOL)allowAnyNetwork;
- (void)setIsDeviceInDualPhoneIdentityMode:;
- (id)selectedPhoneNumberRegistrationSubscriptionNumber;
- (void)setAllowAnyNetwork:;
- (BOOL)_getCellularDataEnabledForBundleID:;
- (BOOL)wifiAllowedForBundleId:;
- (void)setShouldCacheCTConnection:;
- (void)setIsDeviceInManualPhoneSelectionMode:;
- (id)selectedPhoneNumberRegistrationSubscriptionLabels;
- (BOOL)_adequateInternalOrCarrierInstall;
- (BOOL)nonBluetoothAllowedForBundleId:;
- (void)setNonBTAllowedCache:;
- (void)_setupUsageHandlerIfNeeded;
- (BOOL)isDeviceInDualPhoneIdentityMode;
- (BOOL)isDeviceInManualPhoneSelectionMode;
- (BOOL)shouldCacheCTConnection;
- (void).cxx_destruct;
- (BOOL)_nonWifiFaceTimeEntitled;
- (BOOL)_getWifiDataAllowedForBundleID:;
- (void)_setAppCellularDataEnabled:;
- (void)silentlySetSelectedPhoneNumberRegistrationSubscriptionLabels:;
- (BOOL)cellularDataEnabledForBundleId:;
- (void)setSelectedPhoneNumberRegistrationSubscriptionLabels:;
- (void)setCtServerConnection:;
+ (id)sharedInstance;
@end
