@interface GEOComposedRouteSegment : NSObject
@property (nonatomic) GEOComposedRoute composedRoute;
@property (nonatomic) q type;
@property (nonatomic) NSInteger transportType;
@property (nonatomic) double expectedTime;
@property (nonatomic) {_NSRange=QQ} pointRange;
@property (nonatomic) I startPointIndex;
@property (nonatomic) {?=If} startRouteCoordinate;
@property (nonatomic) I endPointIndex;
@property (nonatomic) {?=If} endRouteCoordinate;
@property (nonatomic) Q pointCount;
@property (nonatomic) {_NSRange=QQ} stepRange;
@property (nonatomic) Q startStepIndex;
@property (nonatomic) Q endStepIndex;
@property (nonatomic) Q stepCount;
@property (nonatomic) NSArray steps;
@property (nonatomic) {_NSRange=QQ} transitStepRange;
@property (nonatomic) Q numberOfTransitStops;
@property (nonatomic) GEOPBTransitStop startingTransitStop;
@property (nonatomic) GEOPBTransitStop endingTransitStop;
- (id)steps;
- (int)transportType;
- (unsigned long long)stepCount;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (long long)type;
- (void).cxx_destruct;
- (id)description;
- (BOOL)contains:;
- (id)initWithComposedRoute:routeSegmentType:stepRange:pointRange:;
- (id)startingTransitStop;
- (id)endingTransitStop;
- (id)transitStepRange;
- (unsigned long long)numberOfTransitStops;
- (unsigned long long)pointCount;
- (id)endRouteCoordinate;
- (double)expectedTime;
- (id)startRouteCoordinate;
- (unsigned int)startPointIndex;
- (unsigned int)endPointIndex;
- (unsigned long long)startStepIndex;
- (unsigned long long)endStepIndex;
- (id)pointRange;
- (id)stepRange;
- (double)remainingDistanceAlongSegmentFromStepIndex:currentStepRemainingDistance:;
- (double)remainingTimeAlongSegmentFromStepIndex:currentStepRemainingDistance:;
- (id)composedRoute;
- (void)setComposedRoute:;
+ (BOOL)supportsSecureCoding;
@end
