@interface GEODataSessionTask : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString entityTag;
@property (nonatomic) NSData receivedData;
@property (nonatomic) Q receivedDataLength;
@property (nonatomic) NSError error;
@property (nonatomic) Q incomingPayloadSize;
@property (nonatomic) q responseSource;
@property (nonatomic) BOOL protocolBufferHasPreamble;
@property (nonatomic) NSURL originalRequestURL;
@property (nonatomic) double elapsedTime;
@property (nonatomic) double loadTime;
@property (nonatomic) NSObject<OS_dispatch_queue> sessionIsolation;
@property (nonatomic) <GEODataSessionTaskDelegate> delegate;
@property (nonatomic) GEODataSession session;
@property (nonatomic) NSObject<OS_dispatch_queue> delegateQueue;
@property (nonatomic) GEODataURLSessionTask urlTask;
@property (nonatomic) <GEODataSessionTask> completedSubtask;
@property (nonatomic) NSObject<OS_os_activity> activity;
@property (nonatomic) {?=i(?=iii)} requestKind;
@property (nonatomic) float priority;
@property (nonatomic) NSData receivedData;
@property (nonatomic) NSURL downloadedFileURL;
@property (nonatomic) Q receivedDataLength;
@property (nonatomic) NSError error;
@property (nonatomic) NSString remoteAddressAndPort;
@property (nonatomic) BOOL protocolBufferHasPreamble;
@property (nonatomic) Q outgoingPayloadSize;
@property (nonatomic) Q incomingPayloadSize;
@property (nonatomic) BOOL failedDueToCancel;
@property (nonatomic) <GEORequestCounterTicket> requestCounterTicket;
@property (nonatomic) GEOClientMetrics clientMetrics;
@property (nonatomic) <NSObject> parsedResponse;
@property (nonatomic) Q requestedMultipathServiceType;
@property (nonatomic) BOOL mptcpNegotiated;
@property (nonatomic) BOOL receivedRNFNotification;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)dataSession:shouldConvertDataTask:toDownloadTaskForEstimatedResponseSize:completionHandler:;
- (void)setSession:;
- (void)cancel;
- (void)setPriority:;
- (void)dataSession:didCompleteTask:;
- (void)start;
- (long long)responseSource;
- (void)setDelegate:;
- (double)elapsedTime;
- (id)sessionIsolation;
- (BOOL)mptcpNegotiated;
- (BOOL)receivedRNFNotification;
- (id)error;
- (BOOL)didValidateEntityTagForData:entityTag:;
- (void)setCompletedSubtask:;
- (id)debugDescription;
- (id)delegateQueue;
- (id)remoteAddressAndPort;
- (id)activity;
- (id)receivedData;
- (id)delegate;
- (id)urlTask;
- (id)session;
- (id)originalRequestURL;
- (void).cxx_destruct;
- (BOOL)failedDueToCancel;
- (id)requestKind;
- (BOOL)validateTileResponse:error:;
- (unsigned long long)incomingPayloadSize;
- (id)description;
- (id)entityTag;
- (double)loadTimeIncludingTask:;
- (id)parsedResponse;
- (void)_didCompleteSubtask:;
- (id)completedSubtask;
- (BOOL)getHeaderValue:forField:;
- (unsigned long long)requestedMultipathServiceType;
- (double)loadTime;
- (unsigned long long)outgoingPayloadSize;
- (BOOL)protocolBufferHasPreamble;
- (id)initWithSession:delegate:delegateQueue:requestKind:requestCounterTicket:;
- (id)downloadedFileURL;
- (unsigned long long)receivedDataLength;
- (void)dataSession:willSendRequest:forTask:completionHandler:;
- (id)requestCounterTicket;
- (id)clientMetrics;
- (void)setUrlTask:;
- (BOOL)validateTransportWithError:;
- (float)priority;
@end
