@interface GEODailyUseSummaryUseEvent : PBCodable
@property (nonatomic) BOOL hasEventType;
@property (nonatomic) NSInteger eventType;
@property (nonatomic) BOOL hasAppType;
@property (nonatomic) NSInteger appType;
@property (nonatomic) BOOL hasCount;
@property (nonatomic) I count;
@property (nonatomic) BOOL hasUsageBool;
@property (nonatomic) BOOL usageBool;
@property (nonatomic) BOOL hasUsageString;
@property (nonatomic) NSString usageString;
- (void)setCount:;
- (void)readAll:;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (int)StringAsEventType:;
- (int)appType;
- (id)initWithDictionary:;
- (void)writeTo:;
- (void)setUsageBool:;
- (int)eventType;
- (void)setEventType:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (void)setUsageString:;
- (void)setHasEventType:;
- (BOOL)usageBool;
- (void).cxx_destruct;
- (BOOL)hasEventType;
- (BOOL)readFrom:;
- (void)setAppType:;
- (id)description;
- (id)usageString;
- (id)dictionaryRepresentation;
- (BOOL)hasAppType;
- (id)eventTypeAsString:;
- (unsigned int)count;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setHasCount:;
- (BOOL)hasCount;
- (void)setHasAppType:;
- (id)appTypeAsString:;
- (int)StringAsAppType:;
- (void)setHasUsageBool:;
- (BOOL)hasUsageBool;
- (BOOL)hasUsageString;
+ (BOOL)isValid:;
@end
