@interface GEOETARequest : PBRequest
@property (nonatomic) BOOL hasTransportType;
@property (nonatomic) NSInteger transportType;
@property (nonatomic) BOOL hasTimepoint;
@property (nonatomic) {GEOTimepoint=ddi{?=b1b1b1}} timepoint;
@property (nonatomic) BOOL hasOrigin;
@property (nonatomic) GEOWaypoint origin;
@property (nonatomic) NSMutableArray destinations;
@property (nonatomic) BOOL hasIncludeHistoricTravelTime;
@property (nonatomic) BOOL includeHistoricTravelTime;
@property (nonatomic) BOOL hasAllowPartialResults;
@property (nonatomic) BOOL allowPartialResults;
@property (nonatomic) BOOL hasIncludeDistance;
@property (nonatomic) BOOL includeDistance;
@property (nonatomic) BOOL hasSessionID;
@property (nonatomic) {GEOSessionID=QQ} sessionID;
@property (nonatomic) BOOL hasSessionRelativeTimestamp;
@property (nonatomic) double sessionRelativeTimestamp;
@property (nonatomic) BOOL hasWalkingLimitMeters;
@property (nonatomic) I walkingLimitMeters;
@property (nonatomic) BOOL hasAdditionalEnabledMarkets;
@property (nonatomic) GEOAdditionalEnabledMarkets additionalEnabledMarkets;
@property (nonatomic) BOOL hasOriginWaypointTyped;
@property (nonatomic) GEOWaypointTyped originWaypointTyped;
@property (nonatomic) NSMutableArray destinationWaypointTypeds;
@property (nonatomic) NSMutableArray intermediateWaypointTypeds;
@property (nonatomic) BOOL hasAutomobileOptions;
@property (nonatomic) GEOAutomobileOptions automobileOptions;
@property (nonatomic) BOOL hasCyclingOptions;
@property (nonatomic) GEOCyclingOptions cyclingOptions;
@property (nonatomic) BOOL hasTransitOptions;
@property (nonatomic) GEOTransitOptions transitOptions;
@property (nonatomic) BOOL hasWalkingOptions;
@property (nonatomic) GEOWalkingOptions walkingOptions;
@property (nonatomic) BOOL hasIsFromAPI;
@property (nonatomic) BOOL isFromAPI;
@property (nonatomic) BOOL hasCommonOptions;
@property (nonatomic) GEOCommonOptions commonOptions;
@property (nonatomic) BOOL hasSessionState;
@property (nonatomic) NSData sessionState;
@property (nonatomic) BOOL hasOriginalRouteID;
@property (nonatomic) NSData originalRouteID;
@property (nonatomic) NSMutableArray originalRouteZilchPoints;
@property (nonatomic) BOOL hasOriginalWaypointRoute;
@property (nonatomic) GEOOriginalWaypointRoute originalWaypointRoute;
@property (nonatomic) NSMutableArray deviceHistoricalLocations;
@property (nonatomic) BOOL hasClientCapabilities;
@property (nonatomic) GEOClientCapabilities clientCapabilities;
@property (nonatomic) BOOL hasLastKnownRoadLocation;
@property (nonatomic) GEOLocation lastKnownRoadLocation;
@property (nonatomic) BOOL hasAbClientMetadata;
@property (nonatomic) GEOPDABClientDatasetMetadata abClientMetadata;
@property (nonatomic) BOOL hasIncludeRouteTrafficDetail;
@property (nonatomic) BOOL includeRouteTrafficDetail;
@property (nonatomic) BOOL hasIncludeShortTrafficSummary;
@property (nonatomic) BOOL includeShortTrafficSummary;
@property (nonatomic) BOOL hasPhoneticLocaleIdentifier;
@property (nonatomic) NSString phoneticLocaleIdentifier;
@property (nonatomic) BOOL hasRequestingAppId;
@property (nonatomic) NSString requestingAppId;
@property (nonatomic) BOOL hasIncludeEtaRouteIncidents;
@property (nonatomic) BOOL includeEtaRouteIncidents;
@property (nonatomic) BOOL hasRecentLocationHistory;
@property (nonatomic) GEORecentLocationHistory recentLocationHistory;
@property (nonatomic) BOOL hasPrivacyMetadata;
@property (nonatomic) GEOPrivacyMetadata privacyMetadata;
@property (nonatomic) BOOL hasPathComputationOptions;
@property (nonatomic) GEOPathComputationOptions pathComputationOptions;
@property (nonatomic) NSMutableArray serviceTags;
@property (nonatomic) NSMutableArray trafficApiResponses;
@property (nonatomic) NSMutableArray trafficSnapshotIds;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)setSessionID:;
- (void)readAll:;
- (void)setAutomobileOptions:;
- (int)StringAsTransportType:;
- (id)privacyMetadata;
- (id)sessionID;
- (id)unknownFields;
- (BOOL)hasGreenTeaWithValue:;
- (id)automobileOptions;
- (void)setTransportType:;
- (id)init;
- (void)clearSensitiveFields:;
- (BOOL)hasAdditionalEnabledMarkets;
- (id)destinations;
- (void)setOrigin:;
- (BOOL)hasTransitOptions;
- (BOOL)hasWalkingOptions;
- (id)initWithJSON:;
- (id)transitOptions;
- (id)serviceTagAtIndex:;
- (id)jsonRepresentation;
- (Class)responseClass;
- (BOOL)includeHistoricTravelTime;
- (BOOL)hasAbClientMetadata;
- (void)setSessionState:;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (void)setHasIncludeHistoricTravelTime:;
- (int)transportType;
- (id)phoneticLocaleIdentifier;
- (void)addServiceTag:;
- (BOOL)hasPrivacyMetadata;
- (unsigned long long)hash;
- (id)sessionState;
- (unsigned long long)deviceHistoricalLocationsCount;
- (void)setIncludeHistoricTravelTime:;
- (void)setAdditionalEnabledMarkets:;
- (id)origin;
- (id)deviceHistoricalLocationAtIndex:;
- (id)serviceTags;
- (void)copyTo:;
- (id)clientCapabilities;
- (BOOL)hasTransportType;
- (void)mergeFrom:;
- (void)setPrivacyMetadata:;
- (void)addDestination:;
- (void)setAbClientMetadata:;
- (void)clearServiceTags;
- (id)deviceHistoricalLocations;
- (BOOL)hasCyclingOptions;
- (void)setTransitOptions:;
- (BOOL)hasSessionRelativeTimestamp;
- (BOOL)hasAutomobileOptions;
- (id)initWithData:;
- (void).cxx_destruct;
- (id)transportTypeAsString:;
- (void)setDestinations:;
- (id)additionalEnabledMarkets;
- (void)clearDeviceHistoricalLocations;
- (void)setCyclingOptions:;
- (BOOL)readFrom:;
- (void)setWalkingOptions:;
- (void)setDeviceHistoricalLocations:;
- (id)description;
- (void)setServiceTags:;
- (void)setHasTransportType:;
- (id)dictionaryRepresentation;
- (void)setClientCapabilities:;
- (void)setSessionRelativeTimestamp:;
- (BOOL)hasOrigin;
- (unsigned int)requestTypeCode;
- (BOOL)hasIncludeHistoricTravelTime;
- (id)walkingOptions;
- (unsigned long long)serviceTagsCount;
- (void)setHasSessionRelativeTimestamp:;
- (id)abClientMetadata;
- (void)addDeviceHistoricalLocation:;
- (double)sessionRelativeTimestamp;
- (BOOL)isEqual:;
- (id)cyclingOptions;
- (id)copyWithZone:;
- (BOOL)hasRequestingAppId;
- (id)requestingAppId;
- (void)setRequestingAppId:;
- (BOOL)hasLastKnownRoadLocation;
- (id)lastKnownRoadLocation;
- (void)setLastKnownRoadLocation:;
- (BOOL)hasClientCapabilities;
- (BOOL)hasOriginalRouteID;
- (id)originalRouteID;
- (void)setOriginalRouteID:;
- (BOOL)hasPhoneticLocaleIdentifier;
- (void)setPhoneticLocaleIdentifier:;
- (id)timepoint;
- (void)setTimepoint:;
- (void)setHasTimepoint:;
- (BOOL)hasTimepoint;
- (unsigned int)walkingLimitMeters;
- (void)setWalkingLimitMeters:;
- (void)setHasWalkingLimitMeters:;
- (BOOL)hasWalkingLimitMeters;
- (BOOL)isFromAPI;
- (void)setIsFromAPI:;
- (void)setHasIsFromAPI:;
- (BOOL)hasIsFromAPI;
- (BOOL)hasSessionState;
- (BOOL)includeDistance;
- (id)commonOptions;
- (void)setCommonOptions:;
- (id)recentLocationHistory;
- (void)setRecentLocationHistory:;
- (id)initWithQuickETARequest:;
- (id)originalRouteZilchPoints;
- (void)setOriginalRouteZilchPoints:;
- (void)clearOriginalRouteZilchPoints;
- (void)addOriginalRouteZilchPoints:;
- (unsigned long long)originalRouteZilchPointsCount;
- (id)originalRouteZilchPointsAtIndex:;
- (BOOL)hasOriginalWaypointRoute;
- (id)originalWaypointRoute;
- (void)setOriginalWaypointRoute:;
- (void)setHasSessionID:;
- (BOOL)hasSessionID;
- (BOOL)hasCommonOptions;
- (BOOL)hasRecentLocationHistory;
- (id)trafficApiResponses;
- (void)setTrafficApiResponses:;
- (void)clearTrafficApiResponses;
- (void)addTrafficApiResponses:;
- (unsigned long long)trafficApiResponsesCount;
- (id)trafficApiResponsesAtIndex:;
- (id)trafficSnapshotIds;
- (void)setTrafficSnapshotIds:;
- (void)clearTrafficSnapshotIds;
- (void)addTrafficSnapshotIds:;
- (unsigned long long)trafficSnapshotIdsCount;
- (id)trafficSnapshotIdsAtIndex:;
- (void)clearDestinations;
- (unsigned long long)destinationsCount;
- (id)destinationAtIndex:;
- (BOOL)allowPartialResults;
- (void)setAllowPartialResults:;
- (void)setHasAllowPartialResults:;
- (BOOL)hasAllowPartialResults;
- (void)setIncludeDistance:;
- (void)setHasIncludeDistance:;
- (BOOL)hasIncludeDistance;
- (BOOL)hasOriginWaypointTyped;
- (id)originWaypointTyped;
- (void)setOriginWaypointTyped:;
- (id)destinationWaypointTypeds;
- (void)setDestinationWaypointTypeds:;
- (void)clearDestinationWaypointTypeds;
- (void)addDestinationWaypointTyped:;
- (unsigned long long)destinationWaypointTypedsCount;
- (id)destinationWaypointTypedAtIndex:;
- (id)intermediateWaypointTypeds;
- (void)setIntermediateWaypointTypeds:;
- (void)clearIntermediateWaypointTypeds;
- (void)addIntermediateWaypointTyped:;
- (unsigned long long)intermediateWaypointTypedsCount;
- (id)intermediateWaypointTypedAtIndex:;
- (BOOL)includeRouteTrafficDetail;
- (void)setIncludeRouteTrafficDetail:;
- (void)setHasIncludeRouteTrafficDetail:;
- (BOOL)hasIncludeRouteTrafficDetail;
- (BOOL)includeShortTrafficSummary;
- (void)setIncludeShortTrafficSummary:;
- (void)setHasIncludeShortTrafficSummary:;
- (BOOL)hasIncludeShortTrafficSummary;
- (BOOL)includeEtaRouteIncidents;
- (void)setIncludeEtaRouteIncidents:;
- (void)setHasIncludeEtaRouteIncidents:;
- (BOOL)hasIncludeEtaRouteIncidents;
- (BOOL)hasPathComputationOptions;
- (id)pathComputationOptions;
- (void)setPathComputationOptions:;
+ (BOOL)isValid:;
+ (Class)deviceHistoricalLocationType;
+ (Class)serviceTagType;
+ (Class)destinationType;
+ (Class)originalRouteZilchPointsType;
+ (Class)trafficApiResponsesType;
+ (Class)trafficSnapshotIdsType;
+ (Class)destinationWaypointTypedType;
+ (Class)intermediateWaypointTypedType;
@end
