@interface GEOFormatArgument : PBCodable
@property (nonatomic) q type;
@property (nonatomic) NSString token;
@property (nonatomic) I value1;
@property (nonatomic) I value2;
@property (nonatomic) NSArray value3s;
@property (nonatomic) NSString stringValue;
@property (nonatomic) float percentageValue;
@property (nonatomic) BOOL shouldScaleUnits;
@property (nonatomic) NSString accessibilityLabel;
@property (nonatomic) <GEOServerFormatTokenPriceValue> priceValue;
@property (nonatomic) <GEOTransitArtworkDataSource> artworkValue;
@property (nonatomic) NSArray timeStampValues;
@property (nonatomic) <GEOServerFormatTokenCountdownValue> countdownValue;
@property (nonatomic) <GEOServerFormatTokenUrlValue> urlValue;
@property (nonatomic) <GEOServerFormatTokenManeuverValue> maneuverValue;
@property (nonatomic) <GEOServerFormatTokenNumberData> numberData;
@property (nonatomic) GEOGenericCombinations genericCombinations;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL hasToken;
@property (nonatomic) NSString token;
@property (nonatomic) BOOL hasValInt1;
@property (nonatomic) I valInt1;
@property (nonatomic) BOOL hasValInt2;
@property (nonatomic) I valInt2;
@property (nonatomic) Q valInt3sCount;
@property (nonatomic) ^I valInt3s;
@property (nonatomic) BOOL hasValString;
@property (nonatomic) NSString valString;
@property (nonatomic) BOOL hasPrice;
@property (nonatomic) GEOPrice price;
@property (nonatomic) BOOL hasArtwork;
@property (nonatomic) GEOPBTransitArtwork artwork;
@property (nonatomic) NSMutableArray timestampDatas;
@property (nonatomic) BOOL hasCountdownData;
@property (nonatomic) GEOCountdownData countdownData;
@property (nonatomic) BOOL hasNumberData;
@property (nonatomic) GEONumberData numberData;
@property (nonatomic) BOOL hasMeasurementData;
@property (nonatomic) GEOMeasurementData measurementData;
@property (nonatomic) BOOL hasUrlData;
@property (nonatomic) GEOURLData urlData;
@property (nonatomic) BOOL hasManeuverData;
@property (nonatomic) GEOManeuverData maneuverData;
@property (nonatomic) BOOL hasStringSubstituteData;
@property (nonatomic) GEOGenericStringData stringSubstituteData;
@property (nonatomic) BOOL hasGenericCombinations;
@property (nonatomic) GEOGenericCombinations genericCombinations;
@property (nonatomic) BOOL hasFormat;
@property (nonatomic) NSInteger format;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)setFormat:;
- (void)readAll:;
- (id)unknownFields;
- (id)artwork;
- (id)init;
- (void)dealloc;
- (int)format;
- (id)initWithJSON:;
- (id)token;
- (id)jsonRepresentation;
- (id)accessibilityLabel;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (void)setToken:;
- (long long)type;
- (id)stringValue;
- (BOOL)hasToken;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (void)setArtwork:;
- (id)dictionaryRepresentation;
- (id)price;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasArtwork;
- (BOOL)hasPrice;
- (void)setPrice:;
- (unsigned int)valInt1;
- (void)setValInt1:;
- (void)setHasValInt1:;
- (BOOL)hasValInt1;
- (unsigned int)valInt2;
- (void)setValInt2:;
- (void)setHasValInt2:;
- (BOOL)hasValInt2;
- (unsigned long long)valInt3sCount;
- (id)valInt3s;
- (void)clearValInt3s;
- (void)addValInt3:;
- (unsigned int)valInt3AtIndex:;
- (void)setValInt3s:count:;
- (BOOL)hasValString;
- (id)valString;
- (void)setValString:;
- (id)timestampDatas;
- (void)setTimestampDatas:;
- (void)clearTimestampDatas;
- (void)addTimestampData:;
- (unsigned long long)timestampDatasCount;
- (id)timestampDataAtIndex:;
- (BOOL)hasCountdownData;
- (id)countdownData;
- (void)setCountdownData:;
- (BOOL)hasNumberData;
- (id)numberData;
- (void)setNumberData:;
- (BOOL)hasMeasurementData;
- (id)measurementData;
- (void)setMeasurementData:;
- (BOOL)hasUrlData;
- (id)urlData;
- (void)setUrlData:;
- (BOOL)hasManeuverData;
- (id)maneuverData;
- (void)setManeuverData:;
- (BOOL)hasStringSubstituteData;
- (id)stringSubstituteData;
- (void)setStringSubstituteData:;
- (BOOL)hasGenericCombinations;
- (id)genericCombinations;
- (void)setGenericCombinations:;
- (void)setHasFormat:;
- (BOOL)hasFormat;
- (id)formatAsString:;
- (int)StringAsFormat:;
- (id)urlValue;
- (unsigned int)value1;
- (unsigned int)value2;
- (id)value3s;
- (id)priceValue;
- (float)percentageValue;
- (id)artworkValue;
- (id)timeStampValues;
- (id)countdownValue;
- (BOOL)shouldScaleUnits;
- (id)maneuverValue;
- (id)stringWithDefaultValues;
- (double)_secondsRoundedUpToNearestMinute:;
- (id)_stringForDurationSeconds:unitsStyle:;
- (id)_formatterForDurationString;
- (id)_stringForPower:unit:;
+ (BOOL)isValid:;
+ (Class)timestampDataType;
@end
