@interface GEOGuidanceEventFeedback : PBCodable
@property (nonatomic) BOOL hasRouteID;
@property (nonatomic) NSData routeID;
@property (nonatomic) BOOL hasStepID;
@property (nonatomic) I stepID;
@property (nonatomic) BOOL hasEnrouteNoticeIndex;
@property (nonatomic) I enrouteNoticeIndex;
@property (nonatomic) BOOL hasEventIndex;
@property (nonatomic) I eventIndex;
@property (nonatomic) BOOL hasDistanceToManeuver;
@property (nonatomic) float distanceToManeuver;
@property (nonatomic) BOOL hasTimeToManeuver;
@property (nonatomic) float timeToManeuver;
@property (nonatomic) BOOL hasVehicleSpeed;
@property (nonatomic) float vehicleSpeed;
@property (nonatomic) BOOL hasTrafficSpeed;
@property (nonatomic) NSInteger trafficSpeed;
@property (nonatomic) BOOL hasDuration;
@property (nonatomic) float duration;
@property (nonatomic) BOOL hasSignGuidanceFeedback;
@property (nonatomic) GEOSignGuidanceFeedback signGuidanceFeedback;
@property (nonatomic) BOOL hasSpokenGuidanceFeedback;
@property (nonatomic) GEOSpokenGuidanceFeedback spokenGuidanceFeedback;
@property (nonatomic) BOOL hasJunctionViewGuidanceFeedback;
@property (nonatomic) GEOJunctionViewGuidanceFeedback junctionViewGuidanceFeedback;
@property (nonatomic) BOOL hasTrafficCameraGuidanceFeedback;
@property (nonatomic) GEOTrafficCameraInformation trafficCameraGuidanceFeedback;
- (void)readAll:;
- (id)routeID;
- (id)init;
- (BOOL)hasDuration;
- (id)initWithJSON:;
- (void)setVehicleSpeed:;
- (void)setHasDuration:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setDuration:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (float)duration;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasRouteID;
- (void)setRouteID:;
- (unsigned int)stepID;
- (void)setStepID:;
- (void)setHasStepID:;
- (BOOL)hasStepID;
- (float)distanceToManeuver;
- (void)setDistanceToManeuver:;
- (void)setHasDistanceToManeuver:;
- (BOOL)hasDistanceToManeuver;
- (unsigned int)enrouteNoticeIndex;
- (void)setEnrouteNoticeIndex:;
- (void)setHasEnrouteNoticeIndex:;
- (BOOL)hasEnrouteNoticeIndex;
- (unsigned int)eventIndex;
- (void)setEventIndex:;
- (void)setHasEventIndex:;
- (BOOL)hasEventIndex;
- (float)timeToManeuver;
- (void)setTimeToManeuver:;
- (void)setHasTimeToManeuver:;
- (BOOL)hasTimeToManeuver;
- (float)vehicleSpeed;
- (void)setHasVehicleSpeed:;
- (BOOL)hasVehicleSpeed;
- (int)trafficSpeed;
- (void)setTrafficSpeed:;
- (void)setHasTrafficSpeed:;
- (BOOL)hasTrafficSpeed;
- (id)trafficSpeedAsString:;
- (int)StringAsTrafficSpeed:;
- (BOOL)hasSignGuidanceFeedback;
- (id)signGuidanceFeedback;
- (void)setSignGuidanceFeedback:;
- (BOOL)hasSpokenGuidanceFeedback;
- (id)spokenGuidanceFeedback;
- (void)setSpokenGuidanceFeedback:;
- (BOOL)hasJunctionViewGuidanceFeedback;
- (id)junctionViewGuidanceFeedback;
- (void)setJunctionViewGuidanceFeedback:;
- (BOOL)hasTrafficCameraGuidanceFeedback;
- (id)trafficCameraGuidanceFeedback;
- (void)setTrafficCameraGuidanceFeedback:;
+ (BOOL)isValid:;
@end
