@interface GEOLogMsgEventTransitAppLaunch : PBCodable
@property (nonatomic) BOOL hasBundleIdentifier;
@property (nonatomic) NSString bundleIdentifier;
@property (nonatomic) BOOL hasSource;
@property (nonatomic) GEOLatLng source;
@property (nonatomic) BOOL hasDestination;
@property (nonatomic) GEOLatLng destination;
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) double timestamp;
- (void)readAll:;
- (void)setDestination:;
- (BOOL)hasGreenTeaWithValue:;
- (id)init;
- (id)bundleIdentifier;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)destination;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setHasTimestamp:;
- (void)mergeFrom:;
- (void)setBundleIdentifier:;
- (BOOL)hasTimestamp;
- (void)setTimestamp:;
- (id)initWithData:;
- (void).cxx_destruct;
- (id)source;
- (BOOL)readFrom:;
- (double)timestamp;
- (id)description;
- (BOOL)hasSource;
- (id)dictionaryRepresentation;
- (BOOL)hasBundleIdentifier;
- (void)setSource:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasDestination;
+ (BOOL)isValid:;
@end
