@interface GEOLPRLPRMapRule : PBCodable
@property (nonatomic) BOOL hasMrLicensePlateStructure;
@property (nonatomic) GEOLPRLicensePlateStructure mrLicensePlateStructure;
@property (nonatomic) Q plateTypeIndexesCount;
@property (nonatomic) ^I plateTypeIndexes;
@property (nonatomic) NSMutableArray targetChars;
@property (nonatomic) NSMutableArray valueMappings;
- (void)readAll:;
- (id)init;
- (void)dealloc;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (unsigned long long)plateTypeIndexesCount;
- (id)plateTypeIndexes;
- (void)clearPlateTypeIndexes;
- (void)addPlateTypeIndexes:;
- (unsigned int)plateTypeIndexesAtIndex:;
- (void)setPlateTypeIndexes:count:;
- (id)targetChars;
- (void)setTargetChars:;
- (void)clearTargetChars;
- (void)addTargetChar:;
- (unsigned long long)targetCharsCount;
- (id)targetCharAtIndex:;
- (id)valueMappings;
- (void)setValueMappings:;
- (void)clearValueMappings;
- (void)addValueMapping:;
- (unsigned long long)valueMappingsCount;
- (id)valueMappingAtIndex:;
- (BOOL)hasMrLicensePlateStructure;
- (id)mrLicensePlateStructure;
- (void)setMrLicensePlateStructure:;
+ (BOOL)isValid:;
+ (Class)targetCharType;
+ (Class)valueMappingType;
@end
