@interface GEOLogMsgStateMapUIShown : PBCodable
@property (nonatomic) BOOL hasIsAirQualityShown;
@property (nonatomic) BOOL isAirQualityShown;
@property (nonatomic) BOOL hasIsWeatherShown;
@property (nonatomic) BOOL isWeatherShown;
@property (nonatomic) BOOL hasIsVenueExperienceShown;
@property (nonatomic) BOOL isVenueExperienceShown;
@property (nonatomic) BOOL hasIsLookAroundEntryIconShown;
@property (nonatomic) BOOL isLookAroundEntryIconShown;
@property (nonatomic) BOOL hasActiveNavMode;
@property (nonatomic) NSInteger activeNavMode;
- (void)readAll:;
- (BOOL)isVenueExperienceShown;
- (void)setActiveNavMode:;
- (BOOL)isWeatherShown;
- (void)setIsAirQualityShown:;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (BOOL)hasIsAirQualityShown;
- (id)initWithDictionary:;
- (void)writeTo:;
- (void)setIsVenueExperienceShown:;
- (unsigned long long)hash;
- (BOOL)hasActiveNavMode;
- (void)copyTo:;
- (int)activeNavMode;
- (void)mergeFrom:;
- (BOOL)isLookAroundEntryIconShown;
- (BOOL)hasIsLookAroundEntryIconShown;
- (id)activeNavModeAsString:;
- (void)setHasIsVenueExperienceShown:;
- (void)setHasActiveNavMode:;
- (void)setIsLookAroundEntryIconShown:;
- (void)setHasIsAirQualityShown:;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (void)setIsWeatherShown:;
- (BOOL)isAirQualityShown;
- (BOOL)hasIsVenueExperienceShown;
- (int)StringAsActiveNavMode:;
- (BOOL)hasIsWeatherShown;
- (void)setHasIsLookAroundEntryIconShown:;
- (BOOL)isEqual:;
- (void)setHasIsWeatherShown:;
- (id)copyWithZone:;
+ (BOOL)isValid:;
@end
