@interface GEOMapItemRoutineAttributes : PBCodable
@property (nonatomic) NSUUID loiIdentifier;
@property (nonatomic) BOOL hasLoiType;
@property (nonatomic) NSInteger loiType;
@property (nonatomic) BOOL hasEventName;
@property (nonatomic) NSString eventName;
@property (nonatomic) BOOL hasEventDate;
@property (nonatomic) double eventDate;
@property (nonatomic) BOOL hasIsEventAllDay;
@property (nonatomic) BOOL isEventAllDay;
@property (nonatomic) BOOL hasLoiIdentifierString;
@property (nonatomic) NSString loiIdentifierString;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)readAll:;
- (int)loiType;
- (double)eventDate;
- (id)unknownFields;
- (id)init;
- (BOOL)isEventAllDay;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)loiIdentifier;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)eventName;
- (void)setEventName:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (BOOL)hasLoiType;
- (void)setHasLoiType:;
- (void)setLoiType:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setLoiIdentifier:;
- (id)loiTypeAsString:;
- (int)StringAsLoiType:;
- (BOOL)hasEventName;
- (void)setEventDate:;
- (void)setHasEventDate:;
- (BOOL)hasEventDate;
- (void)setIsEventAllDay:;
- (void)setHasIsEventAllDay:;
- (BOOL)hasIsEventAllDay;
- (BOOL)hasLoiIdentifierString;
- (id)loiIdentifierString;
- (void)setLoiIdentifierString:;
+ (BOOL)isValid:;
@end
