@interface GEOMapFeatureAccess : NSObject
@property (nonatomic) BOOL joinAllRoadsByMuid;
@property (nonatomic) BOOL allowNetworkTileLoad;
@property (nonatomic) BOOL flipNegativeTravelDirectionRoads;
@property (nonatomic) BOOL visitDoubleTravelDirectionRoadsTwice;
@property (nonatomic) BOOL allowStaleData;
- (id)findRoadsToPreviousIntersectionOf:handler:completionHandler:;
- (id)init;
- (id)findRoadsFromPreviousIntersectionOf:handler:completionHandler:;
- (void)preloadTransitTilesNear:radius:preloadToDiskOnly:completionHandler:;
- (id)findTransitAccessPointsForStation:handler:completionHandler:;
- (void)setAllowNetworkTileLoad:;
- (id)findTransitStationForHall:handler:completionHandler:;
- (id)initWithQueue:memoryCacheCountLimit:memoryCacheCostLimit:;
- (id)findTransitStationsNear:radius:handler:completionHandler:;
- (void)setFlipNegativeTravelDirectionRoads:;
- (id)findRoadsFromJunction:handler:completionHandler:;
- (void)clearTransitTiles;
- (id)findTransitHallsNear:radius:handler:completionHandler:;
- (id)findRoadWithMuid:nearCoordinate:handler:completionHandler:;
- (id)findTransitPointWithID:near:pointHandler:completionHandler:;
- (id)synchronousFindRoadsToNextIntersectionOf:;
- (id)_findParentOfTransitPoint:handler:completionHandler:;
- (id)findTransitHallForStop:handler:completionHandler:;
- (id)findRoadsFromNextIntersectionOf:handler:completionHandler:;
- (id)findRoadsToJunction:handler:completionHandler:;
- (id)findRoadsNear:radius:handler:completionHandler:;
- (id)findTransitStopsNear:radius:handler:completionHandler:;
- (id)findAllRoadsAtPreviousIntersectionOf:handler:completionHandler:;
- (id)_findTransitPointsOfType:nearCoordinate:radius:handler:completionHandler:;
- (id)_synchronousFindWithHandler:;
- (BOOL)allowStaleData;
- (void)clearBuildingTiles;
- (void)preloadRoadTilesNear:radius:preloadToDiskOnly:completionHandler:;
- (id)synchronousFindRoadWithID:;
- (void)preloadTransitTilesNear:radius:completionHandler:;
- (void)preloadBuildingTilesNear:radius:completionHandler:;
- (id)_findChildrenOfTransitPoint:handler:completionHandler:;
- (void)clearAllTiles;
- (id)synchronousFindRoadsNear:radius:;
- (id)findTransitHallsForStation:handler:completionHandler:;
- (void).cxx_destruct;
- (void)preloadRoadTilesNear:radius:completionHandler:;
- (id)findRoadsToNextIntersectionOf:handler:completionHandler:;
- (id)roadTileKeysNear:radius:;
- (id)findRoadWithID:handler:completionHandler:;
- (void)preloadBuildingTilesNear:radius:preloadToDiskOnly:completionHandler:;
- (void)preloadBuildingTilesNear:radius:tileSetStyle:preloadToDiskOnly:completionHandler:;
- (BOOL)flipNegativeTravelDirectionRoads;
- (id)synchronousFindRoadsFromPreviousIntersectionOf:;
- (id)findTransitLinksNear:radius:handler:completionHandler:;
- (void)_clearStandardTilesWithType:;
- (id)initWithQueue:;
- (id)findAllRoadsAtNextIntersectionOf:handler:completionHandler:;
- (void)setAllowStaleData:;
- (void)clearRoadTiles;
- (BOOL)visitDoubleTravelDirectionRoadsTwice;
- (id)findTransitGeometryForPoint:completionHandler:;
- (id)findBuildingsNear:radius:tileSetStyle:handler:completionHandler:;
- (id)synchronousFindRoadsFromNextIntersectionOf:;
- (void)_preloadTilesNear:radius:preloadToDiskOnly:tileSetStyle:tileScale:completionHandler:;
- (id)synchronousFindRoadWithMuid:nearCoordinate:;
- (BOOL)joinAllRoadsByMuid;
- (id)findBuildingsNear:radius:handler:completionHandler:;
- (id)_openTileLoaderWithCompletionHandler:;
- (id)synchronousFindRoadsToPreviousIntersectionOf:;
- (void)setVisitDoubleTravelDirectionRoadsTwice:;
- (id)findTransitStopsForHall:handler:completionHandler:;
- (void)setJoinAllRoadsByMuid:;
- (BOOL)allowNetworkTileLoad;
+ (id)tileSetInfoForStyle:scale:;
@end
