@interface GEOPDEvChargingPort : PBCodable
@property (nonatomic) BOOL hasPower;
@property (nonatomic) I power;
@property (nonatomic) BOOL hasChargingConnectorType;
@property (nonatomic) NSInteger chargingConnectorType;
@property (nonatomic) BOOL hasChargingLevel;
@property (nonatomic) NSInteger chargingLevel;
@property (nonatomic) PBUnknownFields unknownFields;
- (unsigned int)power;
- (void)readAll:;
- (id)unknownFields;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (void)setPower:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setHasPower:;
- (BOOL)hasPower;
- (int)chargingConnectorType;
- (void)setChargingConnectorType:;
- (void)setHasChargingConnectorType:;
- (BOOL)hasChargingConnectorType;
- (id)chargingConnectorTypeAsString:;
- (int)StringAsChargingConnectorType:;
- (int)chargingLevel;
- (void)setChargingLevel:;
- (void)setHasChargingLevel:;
- (BOOL)hasChargingLevel;
- (id)chargingLevelAsString:;
- (int)StringAsChargingLevel:;
+ (BOOL)isValid:;
@end
