@interface GEOPBTransitSystem : PBCodable
@property (nonatomic) BOOL hasMuid;
@property (nonatomic) Q muid;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL hasSystemIndex;
@property (nonatomic) I systemIndex;
@property (nonatomic) BOOL hasMuid;
@property (nonatomic) Q muid;
@property (nonatomic) BOOL hasWebsite;
@property (nonatomic) NSString website;
@property (nonatomic) BOOL hasStyleAttributes;
@property (nonatomic) GEOStyleAttributes styleAttributes;
@property (nonatomic) BOOL hasArtwork;
@property (nonatomic) GEOPBTransitArtwork artwork;
@property (nonatomic) BOOL hasNameDisplayString;
@property (nonatomic) NSString nameDisplayString;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)setHasMuid:;
- (BOOL)hasMuid;
- (void)setMuid:;
- (void)readAll:;
- (id)unknownFields;
- (id)artwork;
- (id)init;
- (id)bestName;
- (id)initWithJSON:;
- (void)setWebsite:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (id)identifier;
- (id)website;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (unsigned int)systemIndex;
- (unsigned long long)muid;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (BOOL)hasStyleAttributes;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (void)setArtwork:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)styleAttributes;
- (void)setStyleAttributes:;
- (id)copyWithZone:;
- (BOOL)hasArtwork;
- (BOOL)hasNameDisplayString;
- (id)nameDisplayString;
- (void)setNameDisplayString:;
- (void)setSystemIndex:;
- (void)setHasSystemIndex:;
- (BOOL)hasSystemIndex;
- (BOOL)hasWebsite;
- (id)geoTransitSystem;
+ (BOOL)isValid:;
@end
