@interface GEOPDAutocompleteEntryAddress : PBCodable
@property (nonatomic) BOOL hasCenter;
@property (nonatomic) GEOLatLng center;
@property (nonatomic) BOOL hasOpaqueGeoId;
@property (nonatomic) Q opaqueGeoId;
@property (nonatomic) BOOL hasDistance;
@property (nonatomic) double distance;
@property (nonatomic) BOOL hasPlaceType;
@property (nonatomic) NSInteger placeType;
@property (nonatomic) BOOL hasDisambiguationRadiusMeters;
@property (nonatomic) double disambiguationRadiusMeters;
@property (nonatomic) BOOL hasMapsId;
@property (nonatomic) GEOPDMapsIdentifier mapsId;
@property (nonatomic) BOOL hasShouldCallPlacesForClientization;
@property (nonatomic) BOOL shouldCallPlacesForClientization;
@property (nonatomic) PBUnknownFields unknownFields;
- (double)distance;
- (id)center;
- (int)placeType;
- (void)readAll:;
- (id)mapsId;
- (id)unknownFields;
- (BOOL)hasGreenTeaWithValue:;
- (id)init;
- (void)setCenter:;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (void)setDistance:;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (BOOL)hasCenter;
- (id)placeTypeAsString:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)setMapsId:;
- (void)mergeFrom:;
- (void)setPlaceType:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)hasDistance;
- (BOOL)readFrom:;
- (id)description;
- (BOOL)hasMapsId;
- (id)dictionaryRepresentation;
- (void)setHasPlaceType:;
- (BOOL)hasPlaceType;
- (int)StringAsPlaceType:;
- (BOOL)isEqual:;
- (void)setHasDistance:;
- (id)copyWithZone:;
- (unsigned long long)opaqueGeoId;
- (void)setOpaqueGeoId:;
- (void)setHasOpaqueGeoId:;
- (BOOL)hasOpaqueGeoId;
- (double)disambiguationRadiusMeters;
- (void)setDisambiguationRadiusMeters:;
- (void)setHasDisambiguationRadiusMeters:;
- (BOOL)hasDisambiguationRadiusMeters;
- (BOOL)shouldCallPlacesForClientization;
- (void)setShouldCallPlacesForClientization:;
- (void)setHasShouldCallPlacesForClientization:;
- (BOOL)hasShouldCallPlacesForClientization;
+ (BOOL)isValid:;
@end
