@interface GEORPFeedbackUserInfo : PBCodable
@property (nonatomic) BOOL hasUserCredentials;
@property (nonatomic) GEORPUserCredentials userCredentials;
@property (nonatomic) BOOL hasDevicePushToken;
@property (nonatomic) NSData devicePushToken;
@property (nonatomic) BOOL hasUserEmail;
@property (nonatomic) NSString userEmail;
@property (nonatomic) BOOL hasPreferredEmail;
@property (nonatomic) NSString preferredEmail;
@property (nonatomic) BOOL hasUgcUserId;
@property (nonatomic) NSString ugcUserId;
@property (nonatomic) BOOL hasAnonUserInfo;
@property (nonatomic) GEORPAppAttestInfo anonUserInfo;
@property (nonatomic) BOOL hasRolloverInfo;
@property (nonatomic) GEORPAppAttestInfo rolloverInfo;
@property (nonatomic) BOOL hasTdmUserInfo;
@property (nonatomic) GEORPTdmInfo tdmUserInfo;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)readAll:;
- (id)unknownFields;
- (id)init;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasUserCredentials;
- (id)userCredentials;
- (void)setUserCredentials:;
- (BOOL)hasDevicePushToken;
- (id)devicePushToken;
- (void)setDevicePushToken:;
- (BOOL)hasUserEmail;
- (id)userEmail;
- (void)setUserEmail:;
- (BOOL)hasPreferredEmail;
- (id)preferredEmail;
- (void)setPreferredEmail:;
- (BOOL)hasUgcUserId;
- (id)ugcUserId;
- (void)setUgcUserId:;
- (BOOL)hasAnonUserInfo;
- (id)anonUserInfo;
- (void)setAnonUserInfo:;
- (BOOL)hasRolloverInfo;
- (id)rolloverInfo;
- (void)setRolloverInfo:;
- (BOOL)hasTdmUserInfo;
- (id)tdmUserInfo;
- (void)setTdmUserInfo:;
+ (BOOL)isValid:;
@end
