@interface GEORPIncidentAnnotationDetails : PBCodable
@property (nonatomic) BOOL hasUserLocation;
@property (nonatomic) GEORPUserLocationDetails userLocation;
@property (nonatomic) BOOL hasIncidentId;
@property (nonatomic) NSString incidentId;
@property (nonatomic) BOOL hasAnnotationType;
@property (nonatomic) NSInteger annotationType;
@property (nonatomic) BOOL hasIncidentType;
@property (nonatomic) NSInteger incidentType;
@property (nonatomic) BOOL hasIncidentLocation;
@property (nonatomic) GEOLatLng incidentLocation;
- (void)readAll:;
- (BOOL)hasGreenTeaWithValue:;
- (id)init;
- (void)clearSensitiveFields:;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasUserLocation;
- (id)userLocation;
- (void)setUserLocation:;
- (BOOL)hasIncidentId;
- (id)incidentId;
- (void)setIncidentId:;
- (int)annotationType;
- (void)setAnnotationType:;
- (void)setHasAnnotationType:;
- (BOOL)hasAnnotationType;
- (id)annotationTypeAsString:;
- (int)StringAsAnnotationType:;
- (int)incidentType;
- (void)setIncidentType:;
- (void)setHasIncidentType:;
- (BOOL)hasIncidentType;
- (id)incidentTypeAsString:;
- (int)StringAsIncidentType:;
- (BOOL)hasIncidentLocation;
- (id)incidentLocation;
- (void)setIncidentLocation:;
+ (BOOL)isValid:;
@end
