@interface GEOResource : PBCodable
@property (nonatomic) BOOL hasResourceType;
@property (nonatomic) NSInteger resourceType;
@property (nonatomic) BOOL hasFilename;
@property (nonatomic) NSString filename;
@property (nonatomic) BOOL hasChecksum;
@property (nonatomic) NSData checksum;
@property (nonatomic) Q regionsCount;
@property (nonatomic) ^{GEOTileSetRegion=IIIIII} regions;
@property (nonatomic) NSMutableArray filters;
@property (nonatomic) BOOL hasConnectionType;
@property (nonatomic) NSInteger connectionType;
@property (nonatomic) BOOL hasPreferWiFiAllowedStaleThreshold;
@property (nonatomic) I preferWiFiAllowedStaleThreshold;
@property (nonatomic) BOOL hasValidationMethod;
@property (nonatomic) NSInteger validationMethod;
@property (nonatomic) BOOL hasAlternateResourceURLIndex;
@property (nonatomic) I alternateResourceURLIndex;
@property (nonatomic) BOOL hasUpdateMethod;
@property (nonatomic) NSInteger updateMethod;
@property (nonatomic) BOOL hasTimeToLiveSeconds;
@property (nonatomic) I timeToLiveSeconds;
@property (nonatomic) PBUnknownFields unknownFields;
- (int)connectionType;
- (BOOL)hasConnectionType;
- (id)connectionTypeAsString:;
- (void)readAll:;
- (void)setHasValidationMethod:;
- (void)setConnectionType:;
- (id)filename;
- (id)filters;
- (void)setHasConnectionType:;
- (void)setRegions:count:;
- (id)unknownFields;
- (id)init;
- (int)validationMethod;
- (void)dealloc;
- (id)regions;
- (id)initWithJSON:;
- (id)resourceTypeAsString:;
- (void)addRegion:;
- (unsigned long long)filtersCount;
- (id)jsonRepresentation;
- (unsigned int)preferWiFiAllowedStaleThreshold;
- (void)clearRegions;
- (void)setPreferWiFiAllowedStaleThreshold:;
- (id)regionAtIndex:;
- (BOOL)hasTimeToLiveSeconds;
- (int)resourceType;
- (id)updateMethodAsString:;
- (void)addFilter:;
- (void)clearFilters;
- (id)initWithDictionary:;
- (void)clearUnknownFields:;
- (void)setTimeToLiveSeconds:;
- (void)setResourceType:;
- (BOOL)hasUpdateMethod;
- (BOOL)hasPreferWiFiAllowedStaleThreshold;
- (void)writeTo:;
- (unsigned long long)regionsCount;
- (unsigned int)timeToLiveSeconds;
- (void)setHasTimeToLiveSeconds:;
- (void)setHasResourceType:;
- (void)setFilters:;
- (int)StringAsResourceType:;
- (unsigned long long)hash;
- (void)setFilename:;
- (void)setUpdateMethod:;
- (id)validationMethodAsString:;
- (BOOL)_geo_isRelevantForScales:scenarios:;
- (int)StringAsConnectionType:;
- (void)copyTo:;
- (void)setAlternateResourceURLIndex:;
- (void)mergeFrom:;
- (BOOL)hasValidationMethod;
- (BOOL)hasFilename;
- (BOOL)hasResourceType;
- (id)initWithData:;
- (int)updateMethod;
- (id)filterAtIndex:;
- (void).cxx_destruct;
- (unsigned int)alternateResourceURLIndex;
- (void)setChecksum:;
- (BOOL)readFrom:;
- (BOOL)hasChecksum;
- (id)description;
- (int)StringAsUpdateMethod:;
- (void)setHasUpdateMethod:;
- (int)StringAsValidationMethod:;
- (id)dictionaryRepresentation;
- (BOOL)hasAlternateResourceURLIndex;
- (void)setHasPreferWiFiAllowedStaleThreshold:;
- (BOOL)isEqual:;
- (void)setValidationMethod:;
- (void)setHasAlternateResourceURLIndex:;
- (id)copyWithZone:;
- (id)checksum;
+ (BOOL)isValid:;
+ (Class)filterType;
@end
