@interface GEORPTransitLineTileInfo : PBCodable
@property (nonatomic) BOOL hasTransitLineMuid;
@property (nonatomic) Q transitLineMuid;
@property (nonatomic) BOOL hasTransitLineName;
@property (nonatomic) NSString transitLineName;
@property (nonatomic) BOOL hasTransitSystemName;
@property (nonatomic) NSString transitSystemName;
- (void)readAll:;
- (id)init;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasTransitLineMuid;
- (unsigned long long)transitLineMuid;
- (void)setTransitLineMuid:;
- (BOOL)hasTransitSystemName;
- (id)transitSystemName;
- (void)setTransitSystemName:;
- (BOOL)hasTransitLineName;
- (id)transitLineName;
- (void)setTransitLineName:;
- (void)setHasTransitLineMuid:;
+ (BOOL)isValid:;
@end
