@interface GEOTileSet : PBCodable
@property (nonatomic) BOOL hasBaseURL;
@property (nonatomic) NSString baseURL;
@property (nonatomic) BOOL hasMultiTileURL;
@property (nonatomic) NSString multiTileURL;
@property (nonatomic) NSInteger style;
@property (nonatomic) NSMutableArray validVersions;
@property (nonatomic) NSInteger scale;
@property (nonatomic) NSInteger size;
@property (nonatomic) BOOL hasLocalizationURL;
@property (nonatomic) NSString localizationURL;
@property (nonatomic) NSMutableArray supportedLanguages;
@property (nonatomic) BOOL hasMultiTileURLUsesStatusCodes;
@property (nonatomic) BOOL multiTileURLUsesStatusCodes;
@property (nonatomic) BOOL hasUpdateBehavior;
@property (nonatomic) NSInteger updateBehavior;
@property (nonatomic) NSMutableArray countryRegionAllowlists;
@property (nonatomic) BOOL hasChecksumType;
@property (nonatomic) NSInteger checksumType;
@property (nonatomic) BOOL hasDataSet;
@property (nonatomic) I dataSet;
@property (nonatomic) BOOL hasRequestStyle;
@property (nonatomic) NSInteger requestStyle;
@property (nonatomic) BOOL hasUseAuthProxy;
@property (nonatomic) BOOL useAuthProxy;
@property (nonatomic) BOOL hasSupportsMultipathTCP;
@property (nonatomic) BOOL supportsMultipathTCP;
@property (nonatomic) BOOL hasAlternativeMultipathTCPPort;
@property (nonatomic) I alternativeMultipathTCPPort;
@property (nonatomic) NSMutableArray deviceSKUAllowlists;
@property (nonatomic) PBUnknownFields unknownFields;
- (int)StringAsSize:;
- (id)scaleAsString:;
- (int)requestStyle;
- (void)readAll:;
- (int)StringAsRequestStyle:;
- (id)unknownFields;
- (id)countryRegionAllowlistAtIndex:;
- (id)init;
- (id)supportedLanguages;
- (int)StringAsChecksumType:;
- (void)setHasRequestStyle:;
- (void)setHasChecksumType:;
- (void)setDataSet:;
- (BOOL)hasDataSet;
- (void)setSupportsMultipathTCP:;
- (void)addValidVersion:;
- (id)initWithJSON:;
- (int)StringAsUpdateBehavior:;
- (void)setBaseURL:;
- (BOOL)supportsMultipathTCP;
- (unsigned long long)supportedLanguagesCount;
- (void)setAlternativeMultipathTCPPort:;
- (BOOL)useAuthProxy;
- (id)baseURL;
- (BOOL)hasMultiTileURL;
- (BOOL)hasSupportsMultipathTCP;
- (void)setScale:;
- (BOOL)hasBaseURL;
- (id)jsonRepresentation;
- (id)styleAsString:;
- (void)setHasUpdateBehavior:;
- (BOOL)hasUseAuthProxy;
- (void)setUpdateBehavior:;
- (id)deviceSKUAllowlistAtIndex:;
- (id)updateBehaviorAsString:;
- (void)setValidVersions:;
- (int)StringAsStyle:;
- (void)addSupportedLanguage:;
- (id)initWithDictionary:;
- (void)setHasUseAuthProxy:;
- (void)setHasSupportsMultipathTCP:;
- (void)clearUnknownFields:;
- (void)setChecksumType:;
- (id)validVersions;
- (id)sizeAsString:;
- (void)writeTo:;
- (id)deviceSKUAllowlists;
- (BOOL)multiTileURLUsesStatusCodes;
- (void)setStyle:;
- (void)setHasAlternativeMultipathTCPPort:;
- (id)supportedLanguageAtIndex:;
- (void)setRequestStyle:;
- (void)setHasDataSet:;
- (void)setUseAuthProxy:;
- (unsigned int)alternativeMultipathTCPPort;
- (unsigned int)dataSet;
- (id)validVersionAtIndex:;
- (id)localizationURL;
- (BOOL)hasAlternativeMultipathTCPPort;
- (unsigned long long)deviceSKUAllowlistsCount;
- (id)checksumTypeAsString:;
- (unsigned long long)countryRegionAllowlistsCount;
- (BOOL)hasUpdateBehavior;
- (int)StringAsScale:;
- (unsigned long long)hash;
- (void)clearCountryRegionAllowlists;
- (void)copyTo:;
- (void)mergeFrom:;
- (BOOL)hasMultiTileURLUsesStatusCodes;
- (unsigned long long)validVersionsCount;
- (int)checksumType;
- (void)setCountryRegionAllowlists:;
- (void)addDeviceSKUAllowlist:;
- (id)requestStyleAsString:;
- (id)initWithData:;
- (BOOL)hasLocalizationURL;
- (BOOL)hasRequestStyle;
- (BOOL)hasChecksumType;
- (void).cxx_destruct;
- (int)updateBehavior;
- (BOOL)readFrom:;
- (id)multiTileURL;
- (void)setHasMultiTileURLUsesStatusCodes:;
- (void)setMultiTileURL:;
- (id)description;
- (void)setDeviceSKUAllowlists:;
- (void)setLocalizationURL:;
- (void)setSupportedLanguages:;
- (id)dictionaryRepresentation;
- (void)addCountryRegionAllowlist:;
- (void)clearSupportedLanguages;
- (id)countryRegionAllowlists;
- (int)scale;
- (int)style;
- (void)clearDeviceSKUAllowlists;
- (void)setSize:;
- (BOOL)isEqual:;
- (void)clearValidVersions;
- (void)setMultiTileURLUsesStatusCodes:;
- (id)copyWithZone:;
- (int)size;
+ (BOOL)isValid:;
+ (Class)supportedLanguageType;
+ (Class)countryRegionAllowlistType;
+ (Class)deviceSKUAllowlistType;
+ (Class)validVersionType;
@end
