@interface GEOTrafficCamera : PBCodable
@property (nonatomic) BOOL hasIdentifier;
@property (nonatomic) NSString identifier;
@property (nonatomic) BOOL hasType;
@property (nonatomic) NSInteger type;
@property (nonatomic) BOOL hasPosition;
@property (nonatomic) GEOLatLng position;
@property (nonatomic) BOOL hasHighlightDistance;
@property (nonatomic) I highlightDistance;
@property (nonatomic) BOOL hasInfoCard;
@property (nonatomic) GEOMiniCard infoCard;
@property (nonatomic) BOOL hasSpeedLimitText;
@property (nonatomic) NSString speedLimitText;
@property (nonatomic) BOOL hasSpeedThreshold;
@property (nonatomic) double speedThreshold;
@property (nonatomic) BOOL hasSpeedingCard;
@property (nonatomic) GEOMiniCard speedingCard;
@property (nonatomic) BOOL hasCameraPriority;
@property (nonatomic) I cameraPriority;
@property (nonatomic) BOOL hasCountryCodeStyleId;
@property (nonatomic) I countryCodeStyleId;
@property (nonatomic) PBUnknownFields unknownFields;
- (void)setPosition:;
- (void)readAll:;
- (id)position;
- (id)unknownFields;
- (BOOL)hasGreenTeaWithValue:;
- (id)init;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (int)StringAsType:;
- (id)initWithDictionary:;
- (id)identifier;
- (void)clearUnknownFields:;
- (void)setType:;
- (void)writeTo:;
- (void)setHasType:;
- (BOOL)hasType;
- (unsigned long long)hash;
- (BOOL)hasIdentifier;
- (void)copyTo:;
- (id)typeAsString:;
- (void)mergeFrom:;
- (int)type;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (void)setIdentifier:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasHighlightDistance;
- (unsigned int)highlightDistance;
- (BOOL)hasSpeedLimitText;
- (id)speedLimitText;
- (BOOL)hasSpeedThreshold;
- (double)speedThreshold;
- (BOOL)hasCameraPriority;
- (unsigned int)cameraPriority;
- (void)setHighlightDistance:;
- (void)setHasHighlightDistance:;
- (BOOL)hasInfoCard;
- (id)infoCard;
- (void)setInfoCard:;
- (BOOL)hasPosition;
- (void)setSpeedLimitText:;
- (void)setSpeedThreshold:;
- (void)setHasSpeedThreshold:;
- (BOOL)hasSpeedingCard;
- (id)speedingCard;
- (void)setSpeedingCard:;
- (void)setCameraPriority:;
- (void)setHasCameraPriority:;
- (unsigned int)countryCodeStyleId;
- (void)setCountryCodeStyleId:;
- (void)setHasCountryCodeStyleId:;
- (BOOL)hasCountryCodeStyleId;
+ (BOOL)isValid:;
@end
