@interface GEOVLFSuccessDetails : PBCodable
@property (nonatomic) BOOL hasCorrection;
@property (nonatomic) GEOVLFCorrection correction;
@property (nonatomic) BOOL hasPoseConfidence;
@property (nonatomic) double poseConfidence;
@property (nonatomic) Q inlierSuccessIndicesCount;
@property (nonatomic) ^I inlierSuccessIndices;
- (void)readAll:;
- (id)init;
- (void)dealloc;
- (id)initWithJSON:;
- (id)jsonRepresentation;
- (id)initWithDictionary:;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (id)initWithData:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)correction;
- (BOOL)hasCorrection;
- (void)setCorrection:;
- (double)poseConfidence;
- (void)setPoseConfidence:;
- (void)setHasPoseConfidence:;
- (BOOL)hasPoseConfidence;
- (unsigned long long)inlierSuccessIndicesCount;
- (id)inlierSuccessIndices;
- (void)clearInlierSuccessIndices;
- (void)addInlierSuccessIndices:;
- (unsigned int)inlierSuccessIndicesAtIndex:;
- (void)setInlierSuccessIndices:count:;
+ (BOOL)isValid:;
@end
