@interface GEOVoltaireAddressCorrectionProvider : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) GEOProtobufSession protobufSession;
@property (nonatomic) GEOProtobufSessionTask initializationTask;
@property (nonatomic) GEOProtobufSessionTask updateTask;
@property (nonatomic) @? initFinishedHandler;
@property (nonatomic) @? initErrorHandler;
@property (nonatomic) @? updateFinishedHandler;
@property (nonatomic) @? updateErrorHandler;
- (id)init;
- (void)cancelRequest;
- (void).cxx_destruct;
- (void)protobufSession:didCompleteTask:;
- (id)protobufSession;
- (id)cancelError;
- (void)startInitRequest:finished:error:;
- (void)startUpdateRequest:finished:error:;
- (id)initializationTask;
- (void)setInitializationTask:;
- (id)updateTask;
- (void)setUpdateTask:;
- (id)initFinishedHandler;
- (void)setInitFinishedHandler:;
- (id)initErrorHandler;
- (void)setInitErrorHandler:;
- (id)updateFinishedHandler;
- (void)setUpdateFinishedHandler:;
- (id)updateErrorHandler;
- (void)setUpdateErrorHandler:;
- (void)didCompleteInitTask;
- (void)didCompleteUpdateTask;
+ (id)acInitURL;
+ (BOOL)acInitNeedsProxy;
+ (id)acUpdateURL;
+ (BOOL)acUpdateNeedsProxy;
@end
