@interface GMNativeExpressBannerView : UIView
@property (nonatomic) ABUBannerAd gmAd;
@property (nonatomic) UIView realBannerView;
@property (nonatomic) <BUMNativeExpressBannerViewDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)bannerAd:didLoadFailWithError:;
- (void)bannerAdDidBecomeVisible:bannerView:;
- (void)bannerAdDidClick:bannerView:;
- (void)bannerAdDidClosed:bannerView:dislikeWithReason:;
- (void)bannerAdDidLoad:bannerView:;
- (void)bannerAdNeedLayoutUI:canvasView:;
- (void)bannerAdWillDismissFullScreenModal:bannerView:;
- (void)bannerAdWillPresentFullScreenModal:bannerView:;
- (id)biddingToken;
- (id)getABUxxxAd;
- (id)getAdCreativeToken;
- (id)gmAd;
- (id)initWithSlot:rootViewController:adSize:;
- (id)initWithSlot:rootViewController:adSize:interval:;
- (id)initWithSlotID:rootViewController:adSize:;
- (id)initWithSlotID:rootViewController:adSize:IsSupportDeepLink:;
- (id)initWithSlotID:rootViewController:adSize:IsSupportDeepLink:interval:;
- (id)initWithSlotID:rootViewController:adSize:interval:;
- (void)loadAdData;
- (void)loadAdDataWithMediaSlotConfigIDs:sign:;
- (void)loss:lossReason:winBidder:;
- (id)mediaExt;
- (id)mediation;
- (id)realBannerView;
- (void)setAdMarkup:;
- (void)setGmAd:;
- (void)setMopubAdMarkUp:;
- (void)setRealBannerView:;
- (void)win:;
- (void)layoutSubviews;
- (BOOL)isMemberOfClass:;
- (void)setDelegate:;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)isKindOfClass:;
- (long long)interval;
- (void)setPrice:;
@end
