@interface GRRSchemaGRRFeature : SISchemaInstrumentationMessage
@property (nonatomic) GRRSchemaGRRStringList applicationsInForeground;
@property (nonatomic) BOOL hasApplicationsInForeground;
@property (nonatomic) I asrRank;
@property (nonatomic) BOOL hasAsrRank;
@property (nonatomic) BOOL canResolveContactByRelationship;
@property (nonatomic) BOOL hasCanResolveContactByRelationship;
@property (nonatomic) NSString configuredSiriLanguage;
@property (nonatomic) BOOL hasConfiguredSiriLanguage;
@property (nonatomic) BOOL contactHasRequestedAddressDetail;
@property (nonatomic) BOOL hasContactHasRequestedAddressDetail;
@property (nonatomic) double contactMatchConfidence;
@property (nonatomic) BOOL hasContactMatchConfidence;
@property (nonatomic) BOOL deviceIsPlayingAudio;
@property (nonatomic) BOOL hasDeviceIsPlayingAudio;
@property (nonatomic) NSString inputOrigin;
@property (nonatomic) BOOL hasInputOrigin;
@property (nonatomic) BOOL isActiveAlarmPresent;
@property (nonatomic) BOOL hasIsActiveAlarmPresent;
@property (nonatomic) BOOL isActiveAppointmentPresent;
@property (nonatomic) BOOL hasIsActiveAppointmentPresent;
@property (nonatomic) BOOL isAnnounceEnabled;
@property (nonatomic) BOOL hasIsAnnounceEnabled;
@property (nonatomic) BOOL isAudioPlaying;
@property (nonatomic) BOOL hasIsAudioPlaying;
@property (nonatomic) BOOL isAppInstalled;
@property (nonatomic) BOOL hasIsAppInstalled;
@property (nonatomic) BOOL isAppMatchPresent;
@property (nonatomic) BOOL hasIsAppMatchPresent;
@property (nonatomic) BOOL isAppRunning;
@property (nonatomic) BOOL hasIsAppRunning;
@property (nonatomic) BOOL isArtistPresent;
@property (nonatomic) BOOL hasIsArtistPresent;
@property (nonatomic) BOOL isContactNameResolved;
@property (nonatomic) BOOL hasIsContactNameResolved;
@property (nonatomic) BOOL isEmailAvailable;
@property (nonatomic) BOOL hasIsEmailAvailable;
@property (nonatomic) BOOL isFollowUp;
@property (nonatomic) BOOL hasIsFollowUp;
@property (nonatomic) BOOL isMediaItemEntityPresent;
@property (nonatomic) BOOL hasIsMediaItemEntityPresent;
@property (nonatomic) BOOL isMessagingPossible;
@property (nonatomic) BOOL hasIsMessagingPossible;
@property (nonatomic) BOOL isMessagingPossibleForSendMessageIntent;
@property (nonatomic) BOOL hasIsMessagingPossibleForSendMessageIntent;
@property (nonatomic) BOOL isPhoneCallPossible;
@property (nonatomic) BOOL hasIsPhoneCallPossible;
@property (nonatomic) BOOL isPhoneCallPossibleForPhoneCallIntent;
@property (nonatomic) BOOL hasIsPhoneCallPossibleForPhoneCallIntent;
@property (nonatomic) BOOL isPhoneNumberAvailable;
@property (nonatomic) BOOL hasIsPhoneNumberAvailable;
@property (nonatomic) BOOL isPhoneNumberContactResolvable;
@property (nonatomic) BOOL hasIsPhoneNumberContactResolvable;
@property (nonatomic) BOOL isPreviousTurnSendEmptyMessage;
@property (nonatomic) BOOL hasIsPreviousTurnSendEmptyMessage;
@property (nonatomic) BOOL isSettingOn;
@property (nonatomic) BOOL hasIsSettingOn;
@property (nonatomic) BOOL isTimerActive;
@property (nonatomic) BOOL hasIsTimerActive;
@property (nonatomic) BOOL isVideoPlaying;
@property (nonatomic) BOOL hasIsVideoPlaying;
@property (nonatomic) I numberOfContactsResolved;
@property (nonatomic) BOOL hasNumberOfContactsResolved;
@property (nonatomic) NSString previousFlowDomain;
@property (nonatomic) BOOL hasPreviousFlowDomain;
@property (nonatomic) Q requestTimeBeginMs;
@property (nonatomic) BOOL hasRequestTimeBeginMs;
@property (nonatomic) BOOL sharingAppActive;
@property (nonatomic) BOOL hasSharingAppActive;
@property (nonatomic) BOOL sharingEntityPresent;
@property (nonatomic) BOOL hasSharingEntityPresent;
@property (nonatomic) BOOL sharingRecipientPresent;
@property (nonatomic) BOOL hasSharingRecipientPresent;
@property (nonatomic) BOOL smsAttachmentExists;
@property (nonatomic) BOOL hasSmsAttachmentExists;
@property (nonatomic) BOOL smsAttributeRecipientExists;
@property (nonatomic) BOOL hasSmsAttributeRecipientExists;
@property (nonatomic) BOOL smsAttributeSenderExists;
@property (nonatomic) BOOL hasSmsAttributeSenderExists;
@property (nonatomic) BOOL smsPhoneNumberMentioned;
@property (nonatomic) BOOL hasSmsPhoneNumberMentioned;
@property (nonatomic) BOOL smsTextPayloadExists;
@property (nonatomic) BOOL hasSmsTextPayloadExists;
@property (nonatomic) Q timeSinceLastValidRequestMs;
@property (nonatomic) BOOL hasTimeSinceLastValidRequestMs;
@property (nonatomic) GRRSchemaGRRStringList topTopics;
@property (nonatomic) BOOL hasTopTopics;
@property (nonatomic) NSData jsonData;
@property (nonatomic) Q whichFeature;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (BOOL)isTimerActive;
- (BOOL)isAnnounceEnabled;
- (BOOL)isAppInstalled;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)inputOrigin;
- (void)setInputOrigin:;
- (BOOL)isFollowUp;
- (BOOL)isVideoPlaying;
- (void)setApplicationsInForeground:;
- (id)applicationsInForeground;
- (void)deleteApplicationsInForeground;
- (void)setAsrRank:;
- (unsigned int)asrRank;
- (void)deleteAsrRank;
- (void)setCanResolveContactByRelationship:;
- (BOOL)canResolveContactByRelationship;
- (void)deleteCanResolveContactByRelationship;
- (void)setConfiguredSiriLanguage:;
- (id)configuredSiriLanguage;
- (void)deleteConfiguredSiriLanguage;
- (void)setContactHasRequestedAddressDetail:;
- (BOOL)contactHasRequestedAddressDetail;
- (void)deleteContactHasRequestedAddressDetail;
- (void)setContactMatchConfidence:;
- (double)contactMatchConfidence;
- (void)deleteContactMatchConfidence;
- (void)setDeviceIsPlayingAudio:;
- (BOOL)deviceIsPlayingAudio;
- (void)deleteDeviceIsPlayingAudio;
- (void)deleteInputOrigin;
- (void)setIsActiveAlarmPresent:;
- (BOOL)isActiveAlarmPresent;
- (void)deleteIsActiveAlarmPresent;
- (void)setIsActiveAppointmentPresent:;
- (BOOL)isActiveAppointmentPresent;
- (void)deleteIsActiveAppointmentPresent;
- (void)setIsAnnounceEnabled:;
- (void)deleteIsAnnounceEnabled;
- (void)setIsAudioPlaying:;
- (BOOL)isAudioPlaying;
- (void)deleteIsAudioPlaying;
- (void)setIsAppInstalled:;
- (void)deleteIsAppInstalled;
- (void)setIsAppMatchPresent:;
- (BOOL)isAppMatchPresent;
- (void)deleteIsAppMatchPresent;
- (void)setIsAppRunning:;
- (BOOL)isAppRunning;
- (void)deleteIsAppRunning;
- (void)setIsArtistPresent:;
- (BOOL)isArtistPresent;
- (void)deleteIsArtistPresent;
- (void)setIsContactNameResolved:;
- (BOOL)isContactNameResolved;
- (void)deleteIsContactNameResolved;
- (void)setIsEmailAvailable:;
- (BOOL)isEmailAvailable;
- (void)deleteIsEmailAvailable;
- (void)setIsFollowUp:;
- (void)deleteIsFollowUp;
- (void)setIsMediaItemEntityPresent:;
- (BOOL)isMediaItemEntityPresent;
- (void)deleteIsMediaItemEntityPresent;
- (void)setIsMessagingPossible:;
- (BOOL)isMessagingPossible;
- (void)deleteIsMessagingPossible;
- (void)setIsMessagingPossibleForSendMessageIntent:;
- (BOOL)isMessagingPossibleForSendMessageIntent;
- (void)deleteIsMessagingPossibleForSendMessageIntent;
- (void)setIsPhoneCallPossible:;
- (BOOL)isPhoneCallPossible;
- (void)deleteIsPhoneCallPossible;
- (void)setIsPhoneCallPossibleForPhoneCallIntent:;
- (BOOL)isPhoneCallPossibleForPhoneCallIntent;
- (void)deleteIsPhoneCallPossibleForPhoneCallIntent;
- (void)setIsPhoneNumberAvailable:;
- (BOOL)isPhoneNumberAvailable;
- (void)deleteIsPhoneNumberAvailable;
- (void)setIsPhoneNumberContactResolvable:;
- (BOOL)isPhoneNumberContactResolvable;
- (void)deleteIsPhoneNumberContactResolvable;
- (void)setIsPreviousTurnSendEmptyMessage:;
- (BOOL)isPreviousTurnSendEmptyMessage;
- (void)deleteIsPreviousTurnSendEmptyMessage;
- (void)setIsSettingOn:;
- (BOOL)isSettingOn;
- (void)deleteIsSettingOn;
- (void)setIsTimerActive:;
- (void)deleteIsTimerActive;
- (void)setIsVideoPlaying:;
- (void)deleteIsVideoPlaying;
- (void)setNumberOfContactsResolved:;
- (unsigned int)numberOfContactsResolved;
- (void)deleteNumberOfContactsResolved;
- (void)setPreviousFlowDomain:;
- (id)previousFlowDomain;
- (void)deletePreviousFlowDomain;
- (void)setRequestTimeBeginMs:;
- (unsigned long long)requestTimeBeginMs;
- (void)deleteRequestTimeBeginMs;
- (void)setSharingAppActive:;
- (BOOL)sharingAppActive;
- (void)deleteSharingAppActive;
- (void)setSharingEntityPresent:;
- (BOOL)sharingEntityPresent;
- (void)deleteSharingEntityPresent;
- (void)setSharingRecipientPresent:;
- (BOOL)sharingRecipientPresent;
- (void)deleteSharingRecipientPresent;
- (void)setSmsAttachmentExists:;
- (BOOL)smsAttachmentExists;
- (void)deleteSmsAttachmentExists;
- (void)setSmsAttributeRecipientExists:;
- (BOOL)smsAttributeRecipientExists;
- (void)deleteSmsAttributeRecipientExists;
- (void)setSmsAttributeSenderExists:;
- (BOOL)smsAttributeSenderExists;
- (void)deleteSmsAttributeSenderExists;
- (void)setSmsPhoneNumberMentioned:;
- (BOOL)smsPhoneNumberMentioned;
- (void)deleteSmsPhoneNumberMentioned;
- (void)setSmsTextPayloadExists:;
- (BOOL)smsTextPayloadExists;
- (void)deleteSmsTextPayloadExists;
- (void)setTimeSinceLastValidRequestMs:;
- (unsigned long long)timeSinceLastValidRequestMs;
- (void)deleteTimeSinceLastValidRequestMs;
- (void)setTopTopics:;
- (id)topTopics;
- (void)deleteTopTopics;
- (unsigned long long)whichFeature;
- (BOOL)hasApplicationsInForeground;
- (void)setHasApplicationsInForeground:;
- (BOOL)hasAsrRank;
- (void)setHasAsrRank:;
- (BOOL)hasCanResolveContactByRelationship;
- (void)setHasCanResolveContactByRelationship:;
- (BOOL)hasConfiguredSiriLanguage;
- (void)setHasConfiguredSiriLanguage:;
- (BOOL)hasContactHasRequestedAddressDetail;
- (void)setHasContactHasRequestedAddressDetail:;
- (BOOL)hasContactMatchConfidence;
- (void)setHasContactMatchConfidence:;
- (BOOL)hasDeviceIsPlayingAudio;
- (void)setHasDeviceIsPlayingAudio:;
- (BOOL)hasInputOrigin;
- (void)setHasInputOrigin:;
- (BOOL)hasIsActiveAlarmPresent;
- (void)setHasIsActiveAlarmPresent:;
- (BOOL)hasIsActiveAppointmentPresent;
- (void)setHasIsActiveAppointmentPresent:;
- (BOOL)hasIsAnnounceEnabled;
- (void)setHasIsAnnounceEnabled:;
- (BOOL)hasIsAudioPlaying;
- (void)setHasIsAudioPlaying:;
- (BOOL)hasIsAppInstalled;
- (void)setHasIsAppInstalled:;
- (BOOL)hasIsAppMatchPresent;
- (void)setHasIsAppMatchPresent:;
- (BOOL)hasIsAppRunning;
- (void)setHasIsAppRunning:;
- (BOOL)hasIsArtistPresent;
- (void)setHasIsArtistPresent:;
- (BOOL)hasIsContactNameResolved;
- (void)setHasIsContactNameResolved:;
- (BOOL)hasIsEmailAvailable;
- (void)setHasIsEmailAvailable:;
- (BOOL)hasIsFollowUp;
- (void)setHasIsFollowUp:;
- (BOOL)hasIsMediaItemEntityPresent;
- (void)setHasIsMediaItemEntityPresent:;
- (BOOL)hasIsMessagingPossible;
- (void)setHasIsMessagingPossible:;
- (BOOL)hasIsMessagingPossibleForSendMessageIntent;
- (void)setHasIsMessagingPossibleForSendMessageIntent:;
- (BOOL)hasIsPhoneCallPossible;
- (void)setHasIsPhoneCallPossible:;
- (BOOL)hasIsPhoneCallPossibleForPhoneCallIntent;
- (void)setHasIsPhoneCallPossibleForPhoneCallIntent:;
- (BOOL)hasIsPhoneNumberAvailable;
- (void)setHasIsPhoneNumberAvailable:;
- (BOOL)hasIsPhoneNumberContactResolvable;
- (void)setHasIsPhoneNumberContactResolvable:;
- (BOOL)hasIsPreviousTurnSendEmptyMessage;
- (void)setHasIsPreviousTurnSendEmptyMessage:;
- (BOOL)hasIsSettingOn;
- (void)setHasIsSettingOn:;
- (BOOL)hasIsTimerActive;
- (void)setHasIsTimerActive:;
- (BOOL)hasIsVideoPlaying;
- (void)setHasIsVideoPlaying:;
- (BOOL)hasNumberOfContactsResolved;
- (void)setHasNumberOfContactsResolved:;
- (BOOL)hasPreviousFlowDomain;
- (void)setHasPreviousFlowDomain:;
- (BOOL)hasRequestTimeBeginMs;
- (void)setHasRequestTimeBeginMs:;
- (BOOL)hasSharingAppActive;
- (void)setHasSharingAppActive:;
- (BOOL)hasSharingEntityPresent;
- (void)setHasSharingEntityPresent:;
- (BOOL)hasSharingRecipientPresent;
- (void)setHasSharingRecipientPresent:;
- (BOOL)hasSmsAttachmentExists;
- (void)setHasSmsAttachmentExists:;
- (BOOL)hasSmsAttributeRecipientExists;
- (void)setHasSmsAttributeRecipientExists:;
- (BOOL)hasSmsAttributeSenderExists;
- (void)setHasSmsAttributeSenderExists:;
- (BOOL)hasSmsPhoneNumberMentioned;
- (void)setHasSmsPhoneNumberMentioned:;
- (BOOL)hasSmsTextPayloadExists;
- (void)setHasSmsTextPayloadExists:;
- (BOOL)hasTimeSinceLastValidRequestMs;
- (void)setHasTimeSinceLastValidRequestMs:;
- (BOOL)hasTopTopics;
- (void)setHasTopTopics:;
@end
