@interface HMDCPUExceptionV2Record : NSObject
@property (nonatomic) BOOL isLowPowerModel;
@property (nonatomic) BOOL isBackground;
@property (nonatomic) q thermalState;
@property (nonatomic) q threadCount;
@property (nonatomic) q sampleCount;
@property (nonatomic) q processorCount;
@property (nonatomic) q startTime;
@property (nonatomic) q endTime;
@property (nonatomic) float peakUsage;
@property (nonatomic) float averageUsage;
@property (nonatomic) float configUsage;
@property (nonatomic) Q localID;
@property (nonatomic) Q sequenceCode;
@property (nonatomic) double timestamp;
@property (nonatomic) double inAppTime;
@property (nonatomic) Q isReported;
@property (nonatomic) NSString scene;
@property (nonatomic) NSString customScene;
@property (nonatomic) NSString possibleScene;
@property (nonatomic) NSString lastScene;
@property (nonatomic) NSString uuid;
@property (nonatomic) NSString osVersion;
@property (nonatomic) NSString bundleId;
@property (nonatomic) NSString updateVersionCode;
@property (nonatomic) NSString appVersion;
@property (nonatomic) NSString sessionID;
@property (nonatomic) NSArray appStates;
@property (nonatomic) NSDictionary binaryImages;
@property (nonatomic) NSMutableArray threadsInfo;
- (void)setConfigUsage:;
- (void)setThreadCount:;
- (BOOL)isLowPowerModel;
- (void)setCustomScene:;
- (void)setThreadsInfo:;
- (id)appStates;
- (float)averageUsage;
- (float)configUsage;
- (id)customScene;
- (double)inAppTime;
- (unsigned long long)infoSize;
- (float)peakUsage;
- (id)possibleScene;
- (unsigned long long)sequenceCode;
- (void)setAppStates:;
- (void)setAverageUsage:;
- (void)setBinaryImages:;
- (void)setInAppTime:;
- (void)setIsLowPowerModel:;
- (void)setIsReported:;
- (void)setLastScene:;
- (void)setPeakUsage:;
- (void)setPossibleScene:;
- (void)setSequenceCode:;
- (void)setUpdateVersionCode:;
- (id)threadInfoReportDict;
- (id)threadsInfo;
- (id)updateVersionCode;
- (void)setSessionID:;
- (void)setAppVersion:;
- (long long)sampleCount;
- (id)sessionID;
- (id)appVersion;
- (BOOL)isBackground;
- (void)setSampleCount:;
- (id)osVersion;
- (id)binaryImages;
- (void)setScene:;
- (id)uuid;
- (id)bundleId;
- (void)setStartTime:;
- (void)setUuid:;
- (void)setEndTime:;
- (long long)startTime;
- (id)scene;
- (long long)threadCount;
- (long long)endTime;
- (void)setIsBackground:;
- (void)setOsVersion:;
- (void)setTimestamp:;
- (void).cxx_destruct;
- (unsigned long long)isReported;
- (id)lastScene;
- (double)timestamp;
- (void)setBundleId:;
- (unsigned long long)localID;
- (long long)processorCount;
- (long long)thermalState;
- (void)setThermalState:;
- (void)setProcessorCount:;
- (id)reportDictionary;
- (void)setLocalID:;
+ (id)tableName;
+ (id)record;
@end
