@interface HMDFolderInfo : NSObject
@property (nonatomic) NSMutableDictionary customFolderMap;
@property (nonatomic) HMDFolderInfoModel rootFolder;
@property (nonatomic) NSMutableDictionary customConfigDict;
@property (nonatomic) NSMutableSet customRegConfigSet;
@property (nonatomic) NSMutableDictionary documentsAndDataSizeDict;
@property (nonatomic) Q libraryCacheSize;
@property (nonatomic) NSObject<OS_dispatch_queue> operationQueue;
@property (nonatomic) NSDictionary customDepthInfo;
@property (nonatomic) BOOL allowCustomLevel;
@property (nonatomic) Q fileMaxRecursionDepth;
@property (nonatomic) q collectMinSize;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)customDepthInfo;
- (id)customFolderMap;
- (void)addCustomSearchDepathConfig:;
- (BOOL)allowCustomLevel;
- (BOOL)checkCustomPathWithPath:size:isFolder:;
- (long long)collectMinSize;
- (id)customConfigDict;
- (void)customPathWithConfigDict:;
- (id)customRegConfigSet;
- (id)documentsAndDataSizeDict;
- (unsigned long long)fileMaxRecursionDepth;
- (id)folderInfosDictWithAppFolderSize:folderInfo:;
- (id)folderInfosDictWithAppFolderSize:folderInfo:compliancePaths:matchedPrefix:;
- (id)formatPathWithOriginPath:;
- (id)getAPPHomeDirectory;
- (id)infoModelWithPath:size:isFolder:isUserCustomPath:level:;
- (unsigned long long)libraryCacheSize;
- (BOOL)needAddToReportFolderInfo:depthLevel:;
- (void)recordFolderInfoWithRelativePath:size:deepLevel:isFolder:;
- (id)reportDiskFolderInfoWithAppFolderSize:;
- (id)reportDiskFolderInfoWithAppFolderSize:compliancePaths:;
- (id)resolutionCustomDepthDict:;
- (void)setAllowCustomLevel:;
- (void)setCollectMinSize:;
- (void)setCustomConfigDict:;
- (void)setCustomDepthInfo:;
- (void)setCustomFolderMap:;
- (void)setCustomRegConfigSet:;
- (void)setDocumentsAndDataSizeDict:;
- (void)setFileMaxRecursionDepth:;
- (void)setLibraryCacheSize:;
- (long long)sizeOfDocumentsAndData;
- (id)translateAbsolutePathToRelative:;
- (void)visitDirectory:size:deepLevel:;
- (void)visitFile:size:lastAccessDate:deepLevel:;
- (id)init;
- (id)operationQueue;
- (void).cxx_destruct;
- (void)setRootFolder:;
- (id)rootFolder;
- (void)clearData;
- (void)setOperationQueue:;
- (void)setupData;
@end
