@interface HMDOOMCrashRecord : HMDTrackerRecord
@property (nonatomic) NSString internalStorageSession;
@property (nonatomic) double appUsedMemory;
@property (nonatomic) double deviceFreeMemory;
@property (nonatomic) double freeDiskSpace;
@property (nonatomic) double freeDiskBlockSize;
@property (nonatomic) NSString business;
@property (nonatomic) NSString lastScene;
@property (nonatomic) NSDictionary customParams;
@property (nonatomic) NSDictionary filters;
@property (nonatomic) NSDictionary operationTrace;
@property (nonatomic) NSString binaryInfo;
@property (nonatomic) NSString loginfo;
- (id)loginfo;
- (double)appUsedMemory;
- (id)binaryInfo;
- (id)customParams;
- (double)deviceFreeMemory;
- (double)freeDiskBlockSize;
- (double)freeDiskSpace;
- (id)internalStorageSession;
- (id)operationTrace;
- (void)setAppUsedMemory:;
- (void)setBinaryInfo:;
- (void)setCustomParams:;
- (void)setDeviceFreeMemory:;
- (void)setFreeDiskBlockSize:;
- (void)setFreeDiskSpace:;
- (void)setInternalStorageSession:;
- (void)setLastScene:;
- (void)setLoginfo:;
- (void)setOperationTrace:;
- (id)filters;
- (void)setFilters:;
- (void).cxx_destruct;
- (id)lastScene;
- (id)business;
- (void)setBusiness:;
- (id)reportDictionary;
+ (id)aggregateDataForRecords:;
+ (id)reportDataForRecords:;
+ (id)tableName;
+ (id)newRecord;
@end
