@interface HTSDUnscathed : NSObject
@property (nonatomic) NSArray channelList;
@property (nonatomic) NSArray appVersionList;
@property (nonatomic) NSArray lazyLoadDlibList;
@property (nonatomic) NSDictionary exportSymbols;
@property (nonatomic) NSDictionary osVersionRange;
@property (nonatomic) NSString loadEnable;
@property (nonatomic) BOOL racEnable;
@property (nonatomic) BOOL encrypted;
@property (nonatomic) NSInteger hookType;
@property (nonatomic) BOOL enableCallFuncLog;
@property (nonatomic) BOOL enableLoadIntime;
@property (nonatomic) BOOL enableModInitLog;
@property (nonatomic) BOOL enablePrintLog;
@property (nonatomic) BOOL enableInstExecLog;
@property (nonatomic) BOOL enableInstCallFrameLog;
@property (nonatomic) BOOL serializeNativeSymbolLookup;
@property (nonatomic) q bindSymbolMaxConcurrentOperationCount;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setChannelList:;
- (void)setSerializeNativeSymbolLookup:;
- (id)appVersionList;
- (long long)bindSymbolMaxConcurrentOperationCount;
- (id)channelList;
- (BOOL)enableCallFuncLog;
- (BOOL)enableInstCallFrameLog;
- (BOOL)enableInstExecLog;
- (BOOL)enableLoadIntime;
- (BOOL)enableModInitLog;
- (BOOL)enablePrintLog;
- (id)exportSymbols;
- (int)hookType;
- (id)lazyLoadDlibList;
- (id)loadEnable;
- (BOOL)racEnable;
- (BOOL)serializeNativeSymbolLookup;
- (void)setAppVersionList:;
- (void)setBindSymbolMaxConcurrentOperationCount:;
- (void)setEnableCallFuncLog:;
- (void)setEnableInstCallFrameLog:;
- (void)setEnableInstExecLog:;
- (void)setEnableLoadIntime:;
- (void)setEnableModInitLog:;
- (void)setEnablePrintLog:;
- (void)setExportSymbols:;
- (void)setHookType:;
- (void)setLazyLoadDlibList:;
- (void)setLoadEnable:;
- (void)setRacEnable:;
- (void)setEncrypted:;
- (BOOL)encrypted;
- (void).cxx_destruct;
- (id)osVersionRange;
- (void)setOsVersionRange:;
@end
