@interface HTSLiveSmallCameraPreviewView : UIView
@property (nonatomic) <IESLiveRecoderFactory> recoderFactory;
@property (nonatomic) <IESLiveEffectProcessLifyCycle> videoEffectLifeCycle;
@property (nonatomic) <IESLiveVideoEffectProcessing> videoProcesser;
@property (nonatomic) <IESLiveEffectProcessServiceAdapter> effectProcesser;
@property (nonatomic) <IESLiveEffectModuleBeautyForAudienceService> beautyEffectConfig;
@property (nonatomic) NSArray beautyItems;
@property (nonatomic) BOOL isUsedBeautyEffect;
@property (nonatomic) <IESLiveRecoder> camera;
@property (nonatomic) BOOL inPreviewMode;
@property (nonatomic) BOOL openGesture;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setBeautyItems:;
- (id)effectProcesser;
- (void)setOpenGesture:;
- (void)useBeautyEffectWithBeautyItems:;
- (id)beautyEffectConfig;
- (id)beautyItems;
- (id)cameraPreview;
- (void)didSetAttachingDIContext;
- (BOOL)isFirstConnect;
- (BOOL)isUsedBeautyEffect;
- (void)loadBeautyResource;
- (void)loadCamera;
- (BOOL)openGesture;
- (id)recoderFactory;
- (void)setBeautyEffectConfig:;
- (void)setEffectProcesser:;
- (void)setIsUsedBeautyEffect:;
- (void)setRecoderFactory:;
- (void)setUpEffectEnvironment;
- (void)setVideoEffectLifeCycle:;
- (void)setVideoProcesser:;
- (void)switchCameraSource;
- (id)videoEffectLifeCycle;
- (id)videoProcesser;
- (id)camera;
- (id)init;
- (void)dealloc;
- (void)setCamera:;
- (long long)cameraPosition;
- (void).cxx_destruct;
- (void)startPreview;
- (void)stopPreview;
- (BOOL)inPreviewMode;
- (void)clearCamera;
@end
