@interface HTSLiveSaaSFollowGuidePopupView : UIView
@property (nonatomic) IESLiveSaaSLiveRoomModel liveRoom;
@property (nonatomic) UIView backgroundView;
@property (nonatomic) UIView headShadowView;
@property (nonatomic) UIView headImageView;
@property (nonatomic) UIView nameLabel;
@property (nonatomic) UIView hintLabel;
@property (nonatomic) UIView followButton;
@property (nonatomic) UIView nameContainer;
@property (nonatomic) UIImageView anchorLevelImageView;
@property (nonatomic) @? onFollow;
@property (nonatomic) @? onClose;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)anchorLevelImageView;
- (void)applyLandscapeLayout;
- (void)applyPortraitLayout;
- (id)followButton;
- (void)hasFollowed;
- (id)headImageView;
- (id)headShadowView;
- (id)initWithLiveRoom:;
- (id)liveRoom;
- (id)nameContainer;
- (id)onFollow;
- (void)pr_follow:;
- (void)setAnchorLevelImageView:;
- (void)setFollowButton:;
- (void)setHeadImageView:;
- (void)setHeadShadowView:;
- (void)setLiveRoom:;
- (void)setNameContainer:;
- (void)setOnFollow:;
- (id)backgroundView;
- (void)close;
- (void).cxx_destruct;
- (void)setBackgroundView:;
- (id)nameLabel;
- (void)setNameLabel:;
- (id)hintLabel;
- (void)setHintLabel:;
- (id)onClose;
- (void)setOnClose:;
@end
