@interface HTSLivePreviewExposeData_PreviewExtendArea : IESLivePBBaseMessage
@property (nonatomic) HTSLiveImage extendIcon;
@property (nonatomic) BOOL hasExtendIcon;
@property (nonatomic) NSString extendPreText;
@property (nonatomic) NSString extendText;
@property (nonatomic) NSInteger extendType;
@property (nonatomic) NSString extra;
@property (nonatomic) NSInteger useMarquee;
@property (nonatomic) NSInteger iconType;
@property (nonatomic) NSMutableArray rightPartArray;
@property (nonatomic) Q rightPartArray_Count;
@property (nonatomic) NSString buttonPart;
@property (nonatomic) NSMutableArray midPartArray;
@property (nonatomic) Q midPartArray_Count;
@property (nonatomic) BOOL needDelimiter;
@property (nonatomic) NSMutableArray bottomPartArray;
@property (nonatomic) Q bottomPartArray_Count;
@property (nonatomic) NSInteger uiType;
@property (nonatomic) NSInteger version;
@property (nonatomic) HTSLivePreviewExposeData_PreviewExtendArea_ActionConfig actionCfg;
@property (nonatomic) BOOL hasActionCfg;
@property (nonatomic) BOOL usePassThroughExtraJson;
@property (nonatomic) NSString passThroughExtraJson;
@property (nonatomic) NSMutableDictionary extraEnterRoom;
@property (nonatomic) Q extraEnterRoom_Count;
@property (nonatomic) NSString extraBusiness;
@property (nonatomic) BOOL noNeedPoll;
+ (id)descriptor;
@end
