@interface HybridResourceSchemaParam : NSObject
@property (nonatomic) NSDictionary paramDict;
@property (nonatomic) NSString accessKey;
@property (nonatomic) NSString channel;
@property (nonatomic) NSString bundle;
@property (nonatomic) NSNumber disableGecko;
@property (nonatomic) NSNumber disableBuiltin;
@property (nonatomic) NSNumber disableCDN;
@property (nonatomic) NSNumber enableMemoryCache;
@property (nonatomic) NSNumber onlyLocal;
@property (nonatomic) NSNumber waitGeckoUpdate;
@property (nonatomic) NSNumber disableGeckoUpdate;
@property (nonatomic) NSNumber disableCDNCache;
@property (nonatomic) BOOL lockResource;
@property (nonatomic) NSString sessionId;
@property (nonatomic) NSString sourceUrl;
@property (nonatomic) NSNumber useForest;
@property (nonatomic) NSNumber dynamic;
@property (nonatomic) BOOL parallelFetchResource;
@property (nonatomic) BOOL cdnRegionRedirect;
@property (nonatomic) NSArray redirectRegions;
- (id)redirectRegions;
- (id)waitGeckoUpdate;
- (id)disableCDNCache;
- (BOOL)cdnRegionRedirect;
- (id)disableBuiltin;
- (id)disableCDN;
- (id)disableGecko;
- (id)disableGeckoUpdate;
- (id)enableMemoryCache;
- (id)extractAccessKey;
- (id)extractBundle;
- (id)extractChannel;
- (id)extractDisableBuiltin;
- (id)extractDisableCDN;
- (id)extractDisableCDNCache;
- (id)extractDisableGecko;
- (id)extractDisableGeckoUpdate;
- (id)extractDynamic;
- (id)extractEnableMemoryCache;
- (BOOL)extractLockResource;
- (id)extractOnlyLocal;
- (id)extractSessionId;
- (id)extractURL;
- (id)extractUseForest;
- (id)extractWaitGeckoUpdate;
- (id)getWaitGeckoUpdateFromDynamic:;
- (id)initWithExtra:;
- (BOOL)lockResource;
- (id)onlyLocal;
- (BOOL)parallelFetchResource;
- (id)paramDict;
- (id)resolvedTaskConfig:;
- (id)resolvedTaskConfigForLynxView:;
- (id)resolvedTaskConfigForWebView:;
- (void)setCdnRegionRedirect:;
- (void)setDisableBuiltin:;
- (void)setDisableCDN:;
- (void)setDisableCDNCache:;
- (void)setDisableGecko:;
- (void)setDisableGeckoUpdate:;
- (void)setEnableMemoryCache:;
- (void)setLockResource:;
- (void)setOnlyLocal:;
- (void)setParallelFetchResource:;
- (void)setParamDict:;
- (void)setRedirectRegions:;
- (void)setUseForest:;
- (void)setWaitGeckoUpdate:;
- (id)useForest;
- (void)setSessionId:;
- (void)setChannel:;
- (id)sessionId;
- (id)channel;
- (id)bundle;
- (void).cxx_destruct;
- (void)setBundle:;
- (id)dynamic;
- (void)setDynamic:;
- (id)sourceUrl;
- (void)setSourceUrl:;
- (id)accessKey;
- (void)setAccessKey:;
@end
