@interface ICDocCamThumbnailCollectionViewController : UICollectionViewController
@property (nonatomic) <ICDocCamThumbnailViewDelegate> delegate;
@property (nonatomic) ICDocCamThumbnailCollectionViewLayout layout;
@property (nonatomic) BOOL isPerformingBatchUpdates;
@property (nonatomic) BOOL needReloadAfterBatchUpdates;
@property (nonatomic) NSMutableArray documentInfoArray;
@property (nonatomic) ICDocCamImageCache imageCache;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)shouldAutorotate;
- (id)imageCache;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)didReceiveMemoryWarning;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (long long)collectionView:numberOfItemsInSection:;
- (void)setDelegate:;
- (void)setLayout:;
- (id)collectionView:cellForItemAtIndexPath:;
- (BOOL)_canShowWhileLocked;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)setImageCache:;
- (id)layout;
- (id)delegate;
- (void).cxx_destruct;
- (void)update;
- (id)initWithDelegate:;
- (long long)numberOfSectionsInCollectionView:;
- (unsigned long long)supportedInterfaceOrientations;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)viewDidLoad;
- (id)rootView;
- (id)collectionView:imageSizeAtIndex:;
- (id)targetViewRect;
- (void)setImageWithUUID:forCell:useResizedImage:;
- (void)reloadDataForCollectionView;
- (void)addNewDocument:completionBlock:;
- (void)animateLayoutChange;
- (id)documentInfoArray;
- (void)setDocumentInfoArray:;
- (BOOL)isPerformingBatchUpdates;
- (void)setIsPerformingBatchUpdates:;
- (BOOL)needReloadAfterBatchUpdates;
- (void)setNeedReloadAfterBatchUpdates:;
@end
