@interface ICMutableMusicSubscriptionStatus : ICMusicSubscriptionStatus
@property (nonatomic) BOOL minorAccountHolder;
@property (nonatomic) BOOL hasFamily;
@property (nonatomic) BOOL hasFamilyGreaterThanOneMember;
@property (nonatomic) BOOL headOfHousehold;
@property (nonatomic) BOOL matchEnabled;
@property (nonatomic) NSDate expirationDate;
@property (nonatomic) BOOL hasOfflineSlots;
@property (nonatomic) BOOL inFreeTrial;
@property (nonatomic) BOOL eligibleForFreeTrial;
@property (nonatomic) BOOL purchaser;
@property (nonatomic) q carrierBundlingStatusType;
@property (nonatomic) q reasonType;
@property (nonatomic) q sourceType;
@property (nonatomic) q statusType;
@property (nonatomic) BOOL administrator;
@property (nonatomic) BOOL discoveryModeEligible;
@property (nonatomic) q statusCode;
@property (nonatomic) NSArray termsStatusList;
@property (nonatomic) NSString phoneNumber;
@property (nonatomic) NSString cellularOperatorName;
@property (nonatomic) NSString sessionIdentifier;
@property (nonatomic) q carrierBundlingErrorCode;
@property (nonatomic) BOOL partOfBundle;
@property (nonatomic) BOOL bundleOwner;
@property (nonatomic) NSArray eligibleOffers;
@property (nonatomic) BOOL inGlidePreview;
- (void)setStatusCode:;
- (void)setDiscoveryModeEligible:;
- (void)setReasonType:;
- (long long)statusCode;
- (void)setPhoneNumber:;
- (void)setHasFamily:;
- (void)setMinorAccountHolder:;
- (void)setSourceType:;
- (void)setExpirationDate:;
- (void)setCarrierBundlingErrorCode:;
- (void)setHasFamilyGreaterThanOneMember:;
- (void)setEligibleOffers:;
- (void)setSessionIdentifier:;
- (void)setCarrierBundlingStatusType:;
- (void)setHasOfflineSlots:;
- (void)setTermsStatusList:;
- (void)setPartOfBundle:;
- (void)setInFreeTrial:;
- (void)setAdministrator:;
- (void)setCellularOperatorName:;
- (void)setHeadOfHousehold:;
- (void)setMatchEnabled:;
- (void)setEligibleForFreeTrial:;
- (void)setInGlidePreview:;
- (void)setBundleOwner:;
- (void)setPurchaser:;
- (void)setStatusType:;
- (id)copyWithZone:;
@end
