@interface ICSTodo : ICSCalendarItem
@property (nonatomic) NSArray attach;
@property (nonatomic) NSArray attendee;
@property (nonatomic) NSInteger classification;
@property (nonatomic) ICSDate completed;
@property (nonatomic) q percentComplete;
@property (nonatomic) ICSDate created;
@property (nonatomic) NSString description;
@property (nonatomic) ICSDate dtstamp;
@property (nonatomic) ICSDate dtstart;
@property (nonatomic) ICSDate due;
@property (nonatomic) ICSDuration duration;
@property (nonatomic) NSArray exdate;
@property (nonatomic) NSArray exrule;
@property (nonatomic) ICSDate last_modified;
@property (nonatomic) NSString location;
@property (nonatomic) ICSUserAddress organizer;
@property (nonatomic) Q priority;
@property (nonatomic) NSArray rdate;
@property (nonatomic) ICSDate recurrence_id;
@property (nonatomic) NSArray rrule;
@property (nonatomic) Q sequence;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSString summary;
@property (nonatomic) NSString uid;
@property (nonatomic) NSURL url;
@property (nonatomic) NSString x_apple_ews_changekey;
@property (nonatomic) NSString x_apple_ews_itemid;
@property (nonatomic) BOOL x_apple_ews_needsserverconfirmation;
@property (nonatomic) NSString x_apple_ews_permission;
@property (nonatomic) Q x_apple_sort_order;
@property (nonatomic) ICSStructuredLocation x_apple_structured_location;
@property (nonatomic) NSArray conferences;
@property (nonatomic) NSArray x_apple_activity;
@property (nonatomic) NSData x_apple_appLinkData;
- (long long)percentComplete;
- (BOOL)validate:;
- (void)setCompleted:;
- (void)setPercentComplete:;
- (id)completed;
- (void)setX_apple_sort_order:;
- (id)x_apple_activity;
- (void)setX_apple_appLinkData:;
- (void)setX_apple_activity:;
- (id)due;
- (void)setDue:;
- (unsigned long long)x_apple_sort_order;
- (id)x_apple_appLinkData;
- (id)propertiesToIncludeForChecksumVersion:;
- (void)fixComponent;
+ (id)name;
@end
