@interface ICURLPerformanceMetrics : NSObject
@property (nonatomic) double connectionStartTime;
@property (nonatomic) double connectionEndTime;
@property (nonatomic) double domainLookupStartTime;
@property (nonatomic) double domainLookupEndTime;
@property (nonatomic) double fetchStartTime;
@property (nonatomic) double requestStartTime;
@property (nonatomic) double responseStartTime;
@property (nonatomic) double responseEndTime;
@property (nonatomic) double secureConnectionStartTime;
@property (nonatomic) BOOL cachedResponse;
@property (nonatomic) BOOL connectionReused;
@property (nonatomic) NSString appleTimingApp;
@property (nonatomic) NSString connectionType;
@property (nonatomic) NSString edgeNodeCacheStatus;
@property (nonatomic) NSString environmentDataCenter;
@property (nonatomic) NSString responseDate;
@property (nonatomic) Q statusCode;
@property (nonatomic) Q redirectCount;
@property (nonatomic) Q requestMessageSize;
@property (nonatomic) NSString requestUrl;
@property (nonatomic) NSString resolvedIPAddress;
@property (nonatomic) Q responseMessageSize;
- (id)environmentDataCenter;
- (id)connectionType;
- (id)edgeNodeCacheStatus;
- (id)appleTimingApp;
- (double)connectionStartTime;
- (double)connectionEndTime;
- (id)responseDate;
- (double)responseEndTime;
- (double)fetchStartTime;
- (id)resolvedIPAddress;
- (double)requestStartTime;
- (double)domainLookupEndTime;
- (BOOL)connectionReused;
- (unsigned long long)responseMessageSize;
- (unsigned long long)requestMessageSize;
- (double)domainLookupStartTime;
- (double)responseStartTime;
- (double)secureConnectionStartTime;
- (BOOL)cachedResponse;
- (unsigned long long)statusCode;
- (unsigned long long)redirectCount;
- (id)initWithTransactionMetrics:request:;
- (id)requestUrl;
- (void).cxx_destruct;
+ (double)networkingTimeFromMetrics:;
@end
