@interface IDSQRProtoSessionInfoIndication : PBCodable
@property (nonatomic) NSMutableArray peerPublishedStreams;
@property (nonatomic) Q peerSubscribedStreamIdsCount;
@property (nonatomic) ^I peerSubscribedStreamIds;
@property (nonatomic) Q lightweightParticipantIdListsCount;
@property (nonatomic) ^Q lightweightParticipantIdLists;
@property (nonatomic) BOOL hasTxnId;
@property (nonatomic) Q txnId;
@property (nonatomic) BOOL hasGenerationCounter;
@property (nonatomic) I generationCounter;
- (void)dealloc;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (unsigned int)generationCounter;
- (void)setGenerationCounter:;
- (void)setTxnId:;
- (void)setHasTxnId:;
- (BOOL)hasTxnId;
- (unsigned long long)txnId;
- (void)setHasGenerationCounter:;
- (BOOL)hasGenerationCounter;
- (void)clearPeerPublishedStreams;
- (void)addPeerPublishedStreams:;
- (unsigned long long)peerPublishedStreamsCount;
- (id)peerPublishedStreamsAtIndex:;
- (unsigned long long)peerSubscribedStreamIdsCount;
- (id)peerSubscribedStreamIds;
- (void)clearPeerSubscribedStreamIds;
- (void)addPeerSubscribedStreamIds:;
- (unsigned int)peerSubscribedStreamIdsAtIndex:;
- (void)setPeerSubscribedStreamIds:count:;
- (unsigned long long)lightweightParticipantIdListsCount;
- (id)lightweightParticipantIdLists;
- (void)clearLightweightParticipantIdLists;
- (void)addLightweightParticipantIdList:;
- (unsigned long long)lightweightParticipantIdListAtIndex:;
- (void)setLightweightParticipantIdLists:count:;
- (id)peerPublishedStreams;
- (void)setPeerPublishedStreams:;
+ (Class)peerPublishedStreamsType;
@end
