@interface IDSRegistrationAccountStatusMetric : NSObject
@property (nonatomic) NSString name;
@property (nonatomic) S rtcType;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) NSInteger accountType;
@property (nonatomic) NSString serviceIdentifier;
@property (nonatomic) BOOL doesExist;
@property (nonatomic) BOOL isEnabled;
@property (nonatomic) BOOL isUserDisabled;
@property (nonatomic) BOOL doesMatchiCloudAccount;
@property (nonatomic) BOOL isiCloudSignedIn;
@property (nonatomic) BOOL isiTunesSignedIn;
@property (nonatomic) q registrationError;
@property (nonatomic) NSInteger registrationErrorReason;
@property (nonatomic) q registrationStatus;
@property (nonatomic) NSInteger accountRegistrationStatus;
@property (nonatomic) q lastRegistrationFailureError;
@property (nonatomic) BOOL hasEverRegistered;
@property (nonatomic) double timeIntervalSinceLastRegistrationFailure;
@property (nonatomic) double timeIntervalSinceLastRegistrationSuccess;
@property (nonatomic) q accountSecurityLevel;
@property (nonatomic) BOOL areAllAliasesSelected;
@property (nonatomic) BOOL areAllSelectedAliasesRegistered;
@property (nonatomic) BOOL isProdEnvironment;
@property (nonatomic) q numberOfSelected;
@property (nonatomic) q numberOfVetted;
@property (nonatomic) q numberOfUnselectReasonUnknown;
@property (nonatomic) q numberOfUnselectReasonAlertDenial;
@property (nonatomic) q numberOfUnselectReasonClientCall;
@property (nonatomic) q numberOfUnselectReasonBadAlias;
@property (nonatomic) q numberOfUnselectReasonUpdateInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) I awdIdentifier;
@property (nonatomic) PBCodable<NSCopying> awdRepresentation;
- (int)accountType;
- (BOOL)doesExist;
- (unsigned short)rtcType;
- (long long)registrationError;
- (long long)registrationStatus;
- (id)serviceIdentifier;
- (id)awdRepresentation;
- (void).cxx_destruct;
- (unsigned int)awdIdentifier;
- (id)description;
- (BOOL)isUserDisabled;
- (id)name;
- (id)dictionaryRepresentation;
- (BOOL)isEnabled;
- (id)initWithAccountType:serviceIdentifier:doesExist:isEnabled:isUserDisabled:isiCloudSignedIn:doesMatchiCloudAccount:isiTunesSignedIn:registrationError:registrationErrorReason:registrationStatus:accountRegistrationStatus:hasEverRegistered:lastRegistrationFailureError:timeIntervalSinceLastRegistrationFailure:timeIntervalSinceLastRegistrationSuccess:accountSecurityLevel:areAllAliasesSelected:areAllSelectedAliasesRegistered:numberOfSelected:numberOfVetted:numberOfUnselectReasonUnknown:numberOfUnselectReasonAlertDenial:numberOfUnselectReasonClientCall:numberOfUnselectReasonBadAlias:numberOfUnselectReasonUpdateInfo:isProdEnvironment:;
- (BOOL)doesMatchiCloudAccount;
- (BOOL)isiCloudSignedIn;
- (BOOL)isiTunesSignedIn;
- (int)registrationErrorReason;
- (int)accountRegistrationStatus;
- (long long)lastRegistrationFailureError;
- (BOOL)hasEverRegistered;
- (double)timeIntervalSinceLastRegistrationFailure;
- (double)timeIntervalSinceLastRegistrationSuccess;
- (long long)accountSecurityLevel;
- (BOOL)areAllAliasesSelected;
- (BOOL)areAllSelectedAliasesRegistered;
- (BOOL)isProdEnvironment;
- (long long)numberOfSelected;
- (long long)numberOfVetted;
- (long long)numberOfUnselectReasonUnknown;
- (long long)numberOfUnselectReasonAlertDenial;
- (long long)numberOfUnselectReasonClientCall;
- (long long)numberOfUnselectReasonBadAlias;
- (long long)numberOfUnselectReasonUpdateInfo;
@end
