@interface IDSStunCandidate : NSObject
@property (nonatomic) BOOL active;
@property (nonatomic) Q type;
@property (nonatomic) Q priority;
@property (nonatomic) q transport;
@property (nonatomic) NSInteger index;
@property (nonatomic) r^{sockaddr=CC[14c]} address;
@property (nonatomic) ^{sockaddr=CC[14c]} external;
@property (nonatomic) ^{?=i[12C]} prefix;
@property (nonatomic) I radioAccessTechnology;
@property (nonatomic) I mtu;
@property (nonatomic) double extIPDetectionStartTime;
@property (nonatomic) S linkFlags;
@property (nonatomic) I dataSoMask;
@property (nonatomic) NSString allocbindDataBlob;
- (unsigned int)mtu;
- (BOOL)active;
- (id)external;
- (long long)transport;
- (unsigned int)radioAccessTechnology;
- (void)dealloc;
- (int)index;
- (unsigned long long)type;
- (void)setPrefix:;
- (id)prefix;
- (void).cxx_destruct;
- (id)description;
- (id)address;
- (void)setLocalPort:;
- (void)setActive:;
- (BOOL)isEqual:;
- (unsigned long long)priority;
- (void)setMtu:;
- (id)initWithType:transport:radioAccessTechnology:mtu:index:address:external:;
- (void)setExternal:;
- (void)setAddress:external:;
- (void)setExternalAddress:;
- (void)updateTransport:;
- (BOOL)isCompatibleWithStunCandidate:;
- (BOOL)isSameNetworkType:;
- (BOOL)isServerReflexiveStunCandidate;
- (BOOL)isRelayStunCandidate;
- (BOOL)isCellularStunCandidate;
- (BOOL)isLinkLocalStunCandidate;
- (BOOL)hasNATIPv4Address;
- (BOOL)hasNATIPv4External;
- (void)setRadioAccessTechnology:;
- (double)extIPDetectionStartTime;
- (void)setExtIPDetectionStartTime:;
- (unsigned int)dataSoMask;
- (void)setDataSoMask:;
- (id)allocbindDataBlob;
- (void)setAllocbindDataBlob:;
- (unsigned short)linkFlags;
- (void)setLinkFlags:;
+ (id)candidateWithType:transport:radioAccessTechnology:mtu:index:address:external:;
@end
