@interface IESECLiveGoodsModel : MTLModel
@property (nonatomic) BOOL unrecEvent;
@property (nonatomic) NSString couponType;
@property (nonatomic) IESECLiveGoodsRitTagModel basePickTag;
@property (nonatomic) BOOL isSaaSCampaign;
@property (nonatomic) NSDictionary statusImageMap;
@property (nonatomic) IESECLiveGoodsPriceBuilder priceInfoBuilder;
@property (nonatomic) IESECLiveGoodsStatusBuilder statusInfoBuilder;
@property (nonatomic) IESECLiveGoodsStateModel state;
@property (nonatomic) q tag;
@property (nonatomic) BOOL canBePicked;
@property (nonatomic) NSNumber soldCount;
@property (nonatomic) NSString goodsID;
@property (nonatomic) NSString promotionID;
@property (nonatomic) q channelID;
@property (nonatomic) q channelType;
@property (nonatomic) NSString title;
@property (nonatomic) NSURL cover;
@property (nonatomic) IESECLiveImageURLModel coverForDetail;
@property (nonatomic) NSString priceHeader;
@property (nonatomic) NSNumber minPrice;
@property (nonatomic) NSNumber maxPrice;
@property (nonatomic) NSString minPriceStr;
@property (nonatomic) NSNumber marketPrice;
@property (nonatomic) IESECLiveGoodsPriceDescriptionModel priceDescription;
@property (nonatomic) BOOL showSKUBanner;
@property (nonatomic) BOOL everSKUBannerShowed;
@property (nonatomic) NSArray skuInfos;
@property (nonatomic) NSNumber skuInfosMaxCount;
@property (nonatomic) IESECLiveSubsetGoodsModel subsetGoodsModel;
@property (nonatomic) IESECLiveGoodsCarouselInfoModel carouselInfo;
@property (nonatomic) IESECLiveGoodsCarouselInfoModel recommendInfo;
@property (nonatomic) IESECLiveGoodsCampaignModel campaign;
@property (nonatomic) BOOL isCampaign;
@property (nonatomic) IESECLiveGoodsJumpDestination jumpDestination;
@property (nonatomic) NSString detailURL;
@property (nonatomic) NSString orderURL;
@property (nonatomic) NSString directlyJumpURL;
@property (nonatomic) q ultimateBuyAB;
@property (nonatomic) NSArray couponTags;
@property (nonatomic) NSDictionary skuCouponPanelParams;
@property (nonatomic) NSNumber applyCoupon;
@property (nonatomic) BOOL needAutoApplyCoupon;
@property (nonatomic) NSDictionary ritTags;
@property (nonatomic) NSString findGoodsTagURLString;
@property (nonatomic) IESECLiveImageURLModel atmosphereTag;
@property (nonatomic) IESECLiveImageURLModel tagImageURL;
@property (nonatomic) NSString statusImageURLStr;
@property (nonatomic) q flashType;
@property (nonatomic) BOOL isFlashSale;
@property (nonatomic) NSURL icon;
@property (nonatomic) NSString countString;
@property (nonatomic) NSNumber count;
@property (nonatomic) q explainStatus;
@property (nonatomic) BOOL isSupportCart;
@property (nonatomic) BOOL hideShopCart;
@property (nonatomic) BOOL hasCommentaryVideo;
@property (nonatomic) NSString replayCardStatus;
@property (nonatomic) NSString fragmentID;
@property (nonatomic) NSDictionary activity;
@property (nonatomic) NSNumber itemType;
@property (nonatomic) NSDictionary event;
@property (nonatomic) NSDictionary trackParams;
@property (nonatomic) IESECLiveGoodsStandardTrackModel standardEventTrack;
@property (nonatomic) NSDictionary listPassthroughTrackDic;
@property (nonatomic) BOOL isIntroducingBanner;
@property (nonatomic) q localNum;
@property (nonatomic) BOOL currentScreenLandscape;
@property (nonatomic) NSString labelNameLiveTotal;
@property (nonatomic) NSNumber inventoryStatus;
@property (nonatomic) NSString couponUserTagForTrack;
@property (nonatomic) Q goodsListCombinationType;
@property (nonatomic) BOOL priceSceneChanged;
@property (nonatomic) BOOL isRetryGetBack;
@property (nonatomic) BOOL hasPriceModule;
@property (nonatomic) NSString soldHint;
@property (nonatomic) BOOL lottery;
@property (nonatomic) IESECLiveGoodsLotteryInfo lotteryInfo;
@property (nonatomic) IESECLiveGoodsHotSaleModel hotSaleInfo;
@property (nonatomic) IESECLiveGoodsFlickerImageModel flickerImageModel;
@property (nonatomic) BOOL flickerImageShowed;
@property (nonatomic) BOOL flickerImageEnableTrackByShow;
@property (nonatomic) IESECLiveEntranceViewModel entranceModel;
@property (nonatomic) IESECLiveBottomBannerModel bottomBanner;
@property (nonatomic) IESECLiveGoodsExtraModel extra;
@property (nonatomic) IESECLiveGoodsPurchaseStepperModel purchaseStepper;
@property (nonatomic) NSString buttonLabel;
@property (nonatomic) NSNumber index;
@property (nonatomic) NSNumber realIndex;
@property (nonatomic) NSNumber shopID;
@property (nonatomic) BOOL isSingleSKU;
@property (nonatomic) q goodsSymbol;
@property (nonatomic) NSMutableDictionary updatedTime;
@property (nonatomic) IESECLiveGoodsAskExplainInfoModel askExplainInfo;
@property (nonatomic) IESECLiveGoodsCardModel narrowCardModel;
@property (nonatomic) BOOL depositPreSale;
@property (nonatomic) IESECLiveGoodsReservationModel reservationInfo;
@property (nonatomic) IESECLiveComboBuyModel comboBuyModel;
@property (nonatomic) IESECLiveGoodsCombinationModel combinationModel;
@property (nonatomic) BOOL showCombinationView;
@property (nonatomic) NSString leafCategory;
@property (nonatomic) IESECLiveDynamicRegionModel goodsHeaderAtmosphere;
@property (nonatomic) IESECLiveGoodsCategoryInfoModel categoryInfoModel;
@property (nonatomic) IESECLiveDynamicRegionModel promotionBottom;
@property (nonatomic) BOOL showLongPressBackground;
@property (nonatomic) BOOL showLongPressGuide;
@property (nonatomic) NSDictionary longPressGuideInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q status;
@property (nonatomic) BOOL hasStock;
@property (nonatomic) NSNumber canSold;
- (id)directlyJumpURL;
- (id)goodsID;
- (id)liveEventParams;
- (BOOL)lottery;
- (id)narrowCardModel;
- (id)purchaseStepper;
- (void)setApplyCoupon:;
- (void)setBasePickTag:;
- (void)setHotSaleInfo:;
- (void)setIsSingleSKU:;
- (void)setLotteryInfo:;
- (void)setMarketPrice:;
- (void)setPriceHeader:;
- (void)setTagImageURL:;
- (void)setTrackParams:;
- (BOOL)updateWithProductUpdateMessage:;
- (id)canSold;
- (id)inventoryStatus;
- (id)jumpDestination;
- (id)promotionBottom;
- (id)ritTags;
- (void)setGoodsSymbol:;
- (void)setMinPriceStr:;
- (void)setPromotionID:;
- (void)setUpdatedTime:;
- (void)addBaseverifiedToParams:;
- (id)applyCoupon;
- (id)askExplainInfo;
- (id)atmosphereTag;
- (id)basePickTag;
- (id)bottomBanner;
- (id)campaign;
- (BOOL)canBePicked;
- (id)carouselInfo;
- (id)categoryInfoModel;
- (BOOL)checkProductRefreshMessageIfNeeded:;
- (id)combinationModel;
- (id)comboBuyModel;
- (id)couponTags;
- (id)couponType;
- (id)couponUserTagForTrack;
- (id)cover;
- (id)coverForDetail;
- (id)createLiveGoodsModelBySelf;
- (BOOL)currentScreenLandscape;
- (BOOL)depositPreSale;
- (id)depositReservationDic;
- (id)detailURL;
- (id)entranceModel;
- (BOOL)everSKUBannerShowed;
- (long long)explainStatus;
- (id)findGoodsTagURLString;
- (long long)flashType;
- (BOOL)flickerImageEnableTrackByShow;
- (id)flickerImageModel;
- (BOOL)flickerImageShowed;
- (id)fragmentID;
- (id)getPitayaCategoryInfo;
- (id)goodsHeaderAtmosphere;
- (unsigned long long)goodsListCombinationType;
- (long long)goodsSymbol;
- (BOOL)hasCommentaryVideo;
- (BOOL)hasPriceModule;
- (BOOL)hasStock;
- (BOOL)hideShopCart;
- (id)hotSaleInfo;
- (void)initBasePickBanner;
- (BOOL)isCampaign;
- (BOOL)isFlashSale;
- (BOOL)isIntroducingBanner;
- (BOOL)isRetryGetBack;
- (BOOL)isSaaSCampaign;
- (BOOL)isSingleSKU;
- (BOOL)isSupportCart;
- (id)labelNameLiveTotal;
- (id)leafCategory;
- (id)listPassthroughTrackDic;
- (long long)localNum;
- (id)longPressGuideInfo;
- (id)lotteryInfo;
- (id)marketPrice;
- (id)maxPrice;
- (id)minPrice;
- (id)minPriceStr;
- (BOOL)needAutoApplyCoupon;
- (void)p_didRefreshMessage:;
- (void)p_didUpdateMessage:;
- (id)p_listPassthroughParams;
- (id)p_serverEventParams;
- (void)p_setKey:withValue:toMtlDic:;
- (BOOL)p_shouldRefreshMessage:;
- (BOOL)p_shouldUpdateMessage:;
- (void)p_updateAuction:;
- (void)p_updateLottery:;
- (BOOL)p_updateProductWithMessage:;
- (id)priceHeader;
- (id)priceInfoBuilder;
- (BOOL)priceSceneChanged;
- (id)promotionID;
- (id)rawGoodsData;
- (id)realIndex;
- (id)recommendInfo;
- (id)replayCardStatus;
- (void)setAskExplainInfo:;
- (void)setAtmosphereTag:;
- (void)setBottomBanner:;
- (void)setCampaign:;
- (void)setCanSold:;
- (void)setCarouselInfo:;
- (void)setCategoryInfoModel:;
- (void)setCombinationModel:;
- (void)setComboBuyModel:;
- (void)setCouponTags:;
- (void)setCover:;
- (void)setCoverForDetail:;
- (void)setCurrentScreenLandscape:;
- (void)setDepositPreSale:;
- (void)setDetailURL:;
- (void)setDirectlyJumpURL:;
- (void)setEntranceModel:;
- (void)setEverSKUBannerShowed:;
- (void)setExplainStatus:;
- (void)setExtra:;
- (void)setFindGoodsTagURLString:;
- (void)setFlashType:;
- (void)setFlickerImageEnableTrackByShow:;
- (void)setFlickerImageModel:;
- (void)setFlickerImageShowed:;
- (void)setFragmentID:;
- (void)setGoodsHeaderAtmosphere:;
- (void)setGoodsID:;
- (void)setGoodsListCombinationType:;
- (void)setHasCommentaryVideo:;
- (void)setHasPriceModule:;
- (void)setHasStock:;
- (void)setHideShopCart:;
- (void)setInventoryStatus:;
- (void)setIsCampaign:;
- (void)setIsIntroducingBanner:;
- (void)setIsRetryGetBack:;
- (void)setIsSaaSCampaign:;
- (void)setIsSupportCart:;
- (void)setJumpDestination:;
- (void)setLabelNameLiveTotal:;
- (void)setLeafCategory:;
- (void)setListPassthroughTrackDic:;
- (void)setLocalNum:;
- (void)setLongPressGuideInfo:;
- (void)setLottery:;
- (void)setMaxPrice:;
- (void)setMinPrice:;
- (void)setNarrowCardModel:;
- (void)setNeedAutoApplyCoupon:;
- (void)setPriceDescription:;
- (void)setPriceInfoBuilder:;
- (void)setPriceSceneChanged:;
- (void)setPromotionBottom:;
- (void)setPurchaseStepper:;
- (void)setRealIndex:;
- (void)setRecommendInfo:;
- (void)setReplayCardStatus:;
- (void)setReservatedState;
- (void)setRitTags:;
- (void)setShopID:;
- (void)setShowCombinationView:;
- (void)setShowLongPressBackground:;
- (void)setShowLongPressGuide:;
- (void)setShowSKUBanner:;
- (void)setSkuCouponPanelParams:;
- (void)setSkuInfos:;
- (void)setSkuInfosMaxCount:;
- (void)setSoldCount:;
- (void)setSoldHint:;
- (void)setStandardEventTrack:;
- (void)setStatusImageMap:;
- (void)setStatusImageURLStr:;
- (void)setStatusInfoBuilder:;
- (void)setSubsetGoodsModel:;
- (void)setUltimateBuyAB:;
- (id)shopID;
- (BOOL)showCombinationView;
- (BOOL)showLongPressBackground;
- (BOOL)showLongPressGuide;
- (BOOL)showSKUBanner;
- (id)skuCouponPanelParams;
- (id)skuCouponTags;
- (id)skuInfos;
- (id)skuInfosMaxCount;
- (id)soldCount;
- (id)soldHint;
- (id)standardEventTrack;
- (id)statusImageMap;
- (id)statusImageURLStr;
- (id)statusInfoBuilder;
- (id)subsetGoodsModel;
- (id)tagImageURL;
- (id)toADTrackParamsDictionary;
- (id)trackParams;
- (void)transferBusinessParamsToModel:;
- (id)transformComboBuyModelToCombinationModel;
- (long long)ultimateBuyAB;
- (BOOL)unrecEvent;
- (void)updateHotAtmosphere:;
- (void)updatePriceWithGoods:;
- (BOOL)updateWithMarketingMessage:;
- (void)updateWithProductRefreshMessage:;
- (id)updatedTime;
- (void)setCount:;
- (void)setChannelID:;
- (void)setStatus:;
- (void)setItemType:;
- (long long)tag;
- (id)extra;
- (void)setEvent:;
- (id)event;
- (void)setState:;
- (void)setActivity:;
- (id)initWithDictionary:error:;
- (id)icon;
- (void)setTitle:;
- (id)itemType;
- (id)index;
- (id)activity;
- (void)setTag:;
- (id)title;
- (id)state;
- (void)setIcon:;
- (void)setIndex:;
- (void).cxx_destruct;
- (id)buttonLabel;
- (long long)status;
- (id)count;
- (long long)channelID;
- (long long)channelType;
- (BOOL)isEqual:;
- (id)priceDescription;
- (void)setButtonLabel:;
- (id)orderURL;
- (void)setOrderURL:;
- (id)reservationInfo;
- (void)setReservationInfo:;
- (id)countString;
- (void)setChannelType:;
+ (id)combinationModelJSONTransformer;
+ (id)comboBuyModelJSONTransformer;
+ (id)couponTagsJSONTransformer;
+ (id)extraJSONTransformer;
+ (id)reservationInfoJSONTransformer;
+ (id)ritTagsJSONTransformer;
+ (id)skuInfosJSONTransformer;
+ (id)stateJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
