@interface IESECGoodsInternalFeedDataSource : NSObject
@property (nonatomic) IESECGoodsDetailParameters goodsDetailParameter;
@property (nonatomic) IESECFeedRecommendDataController recommendFeedsController;
@property (nonatomic) IESECGoodsFeedPitayaManager pitayaManager;
@property (nonatomic) NSMutableDictionary objectsToCarouselIndexMap;
@property (nonatomic) NSMutableArray mViewModels;
@property (nonatomic) q goodsCardCount;
@property (nonatomic) BOOL useNewCell;
@property (nonatomic) NSMutableDictionary pitayaInfoDict;
@property (nonatomic) BOOL hasShowLongPress;
@property (nonatomic) NSMutableArray<IESECGoodsFeedControllerProtocol> controllerInstanceArray;
@property (nonatomic) double heightOfSecondSectionHeader;
@property (nonatomic) BOOL hasMoreToLoad;
@property (nonatomic) BOOL hasNoRecommendation;
@property (nonatomic) NSArray viewModels;
@property (nonatomic) NSArray models;
@property (nonatomic) NSArray rawRecommendItems;
@property (nonatomic) q firstResourceCardNumber;
@property (nonatomic) Q listStyle;
@property (nonatomic) IESECGoodsFeedContext context;
@property (nonatomic) IESECFeedRecommendItemModel rankingItem;
@property (nonatomic) NSArray resourceItems;
@property (nonatomic) NSMutableArray tagsHaveBeenDisplayed;
@property (nonatomic) <IESECGoodsFeedListDelegate> containerDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)controllerArray;
- (void)setMViewModels:;
- (void)configBaseViewModel:withParams:;
- (void)saveHasShowLongPressInstruction;
- (void)appendSectionViewModels:animated:completion:;
- (void)cancelLatestRequest;
- (id)cardViewModelsWithParams:;
- (long long)carouselIndexForSection:;
- (id)classNameArray;
- (id)controllerArrayBySelector:;
- (id)controllerByProtocol:;
- (id)controllerInstanceArray;
- (id)controllersByProtocol:;
- (void)deduplicateFromIndex:;
- (id)detailParametersFromProductModel:;
- (id)detailParametersListFromRankingItem:;
- (void)enterDetailAtIndex:;
- (id)favoriteFeedViewModelWithObjects:;
- (id)firstCardViewModelWithParams:;
- (long long)firstResourceCardNumber;
- (long long)goodsCardCount;
- (id)goodsDetailParameter;
- (BOOL)hasMoreToLoad;
- (BOOL)hasNoRecommendation;
- (BOOL)hasShowLongPress;
- (double)heightOfSecondSectionHeader;
- (id)initWithGoodsDetailParameters:;
- (id)initWithGoodsDetailParameters:useNewCell:context:;
- (void)insertCompareDealsResourceCardViewIfNeed:;
- (void)insertResourceItem:atIndex:;
- (void)insertSectionViewModels:atIndex:animated:completion:;
- (void)insertSectionViewModels:atIndexes:animated:completion:;
- (id)largeCardViewModelWithParams:isFirstCard:;
- (void)loadCompareDealsModelWithScene:productList:completion:;
- (void)loadControllersWithContainer:rootView:withContext:;
- (void)loadFavoriteItemCompareDealsCardIfNeed:;
- (void)loadMoreRecommendGoods;
- (void)loadMoreWithCompletionHandler:;
- (void)loadMoreWithFilterString:completionHandler:;
- (void)loadResourceCardsPromotionProductWithCompletionHandler:;
- (void)loadResourceCardsWithCompletionHandler:;
- (void)loadSearchModelWithProduct:completion:;
- (id)mViewModels;
- (id)objectsToCarouselIndexMap;
- (id)old_baseViewModelWithParams:isFirstCard:;
- (id)old_cardViewModelsWithParams:;
- (id)old_favoriteFeedViewModelWithObjects:;
- (id)old_firstCardViewModelWithParams:;
- (id)pitayaDict;
- (id)pitayaInfoDict;
- (id)pitayaManager;
- (void)productCardUpdated;
- (unsigned long long)productModelsCount;
- (id)rawRecommendItems;
- (id)recommendFeedsController;
- (void)removeAllControllers;
- (void)removeResourceCardModels;
- (void)removeSectionViewModels:animated:completion:;
- (void)removeSectionViewModelsAtIndexes:;
- (void)replaceSectionViewModels:atIndex:animated:completion:;
- (id)resourceItems;
- (id)resourceLynxViewModelWithParams:item:;
- (id)resourceViewModelWithParams:;
- (void)scrollToSectionViewModel:supplementaryKinds:scrollDirection:scrollPosition:animated:;
- (id)searchViewModelWithParams:;
- (void)setCarouselIndex:forSection:;
- (void)setControllerInstanceArray:;
- (void)setFirstResourceCardNumber:;
- (void)setGoodsCardCount:;
- (void)setGoodsDetailParameter:;
- (void)setHasShowLongPress:;
- (void)setObjectsToCarouselIndexMap:;
- (void)setPitayaInfoDict:;
- (void)setPitayaManager:;
- (void)setRecommendFeedsController:;
- (void)setResourceItems:;
- (void)setTagsHaveBeenDisplayed:;
- (void)setUseNewCell:;
- (id)tagsHaveBeenDisplayed;
- (id)tagsViewModelWithParams:;
- (void)updateCompareDealsBarWithModel:completion:;
- (void)updateDataSourceModels:;
- (void)updateFirstCardViewModelWithMsgAlpha:;
- (void)updateFirstCardViewModelWithParams:;
- (void)updateRecommendItemsForPreload:error:;
- (void)updateSectionViewModels:animated:completion:;
- (void)updateStateForCompareDealsWithDict:;
- (BOOL)useNewCell;
- (void)initialized;
- (void)addController:;
- (void)removeController:;
- (id)context;
- (id)models;
- (void)removeElementsInRange:;
- (void).cxx_destruct;
- (void)viewWillAppear;
- (void)setContext:;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)viewModels;
- (unsigned long long)listStyle;
- (void)setListStyle:;
- (id)rankingItem;
- (id)containerDelegate;
- (void)setContainerDelegate:;
@end
