@interface IESECLiveGoodsHotSaleModel : MTLModel
@property (nonatomic) NSString saleNumStr;
@property (nonatomic) q UIType;
@property (nonatomic) q dataType;
@property (nonatomic) NSString imageURLStr;
@property (nonatomic) NSString prefixStr;
@property (nonatomic) NSString suffixStr;
@property (nonatomic) NSNumber saleNum;
@property (nonatomic) NSString topImageURL;
@property (nonatomic) NSArray bgColors;
@property (nonatomic) NSArray borderColors;
@property (nonatomic) double bgLeftMargin;
@property (nonatomic) BOOL sameContentSize;
@property (nonatomic) BOOL showEnhancedDesign;
@property (nonatomic) NSNumber dismissInterval;
@property (nonatomic) BOOL shouldShow;
@property (nonatomic) q lastTrackType;
@property (nonatomic) NSString hotsaleType;
@property (nonatomic) q state;
@property (nonatomic) NSMutableArray followUpItems;
@property (nonatomic) double vibeLeftMargin;
@property (nonatomic) BOOL circularVibe;
@property (nonatomic) BOOL priceFormatStyle;
@property (nonatomic) BOOL shouldCheckNum;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)isStock;
- (void)setHotsaleType:;
- (id)dismissInterval;
- (id)saleNum;
- (BOOL)sameContentSize;
- (void)setTopImageURL:;
- (long long)UIType;
- (id)bgColors;
- (double)bgLeftMargin;
- (id)borderColors;
- (BOOL)circularVibe;
- (id)followUpItems;
- (id)hotsaleType;
- (BOOL)isHotsale;
- (BOOL)isRank;
- (long long)lastTrackType;
- (id)prefixStr;
- (BOOL)priceFormatStyle;
- (id)saleNumStr;
- (void)setBgColors:;
- (void)setBgLeftMargin:;
- (void)setBorderColors:;
- (void)setCircularVibe:;
- (void)setDismissInterval:;
- (void)setFollowUpItems:;
- (void)setLastTrackType:;
- (void)setPrefixStr:;
- (void)setPriceFormatStyle:;
- (void)setSaleNum:;
- (void)setSaleNumStr:;
- (void)setSameContentSize:;
- (void)setShouldCheckNum:;
- (void)setShowEnhancedDesign:;
- (void)setSuffixStr:;
- (void)setUIType:;
- (void)setVibeLeftMargin:;
- (BOOL)shouldCheckNum;
- (BOOL)showEnhancedDesign;
- (id)suffixStr;
- (id)topImageURL;
- (void)updateWithMsgHotSaleInfoMessage:;
- (double)vibeLeftMargin;
- (void)setDataType:;
- (void)setState:;
- (long long)dataType;
- (long long)state;
- (void).cxx_destruct;
- (BOOL)shouldShow;
- (void)setShouldShow:;
- (id)imageURLStr;
- (void)setImageURLStr:;
- (BOOL)isComment;
+ (id)JSONKeyPathsByPropertyKey;
@end
