@interface IESEffectPlatformResponseModel : MTLModel
@property (nonatomic) NSString version;
@property (nonatomic) NSString defaultFrontFilterID;
@property (nonatomic) NSString defaultRearFilterID;
@property (nonatomic) NSArray collection;
@property (nonatomic) NSArray effects;
@property (nonatomic) NSArray categories;
@property (nonatomic) IESPlatformPanelModel panel;
@property (nonatomic) NSMutableDictionary effectsMap;
@property (nonatomic) BOOL needReprocessEffects;
@property (nonatomic) NSArray downloadedEffects;
@property (nonatomic) NSArray urlPrefix;
@property (nonatomic) NSString requestID;
@property (nonatomic) NSString recId;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)defaultFrontFilterID;
- (id)defaultRearFilterID;
- (id)downloadedEffects;
- (id)effectsMap;
- (BOOL)needReprocessEffects;
- (void)preProcessEffects;
- (id)recId;
- (void)setDefaultFrontFilterID:;
- (void)setDefaultRearFilterID:;
- (void)setEffectsMap:;
- (void)setNeedReprocessEffects:;
- (void)setRecId:;
- (id)collection;
- (void)setCollection:;
- (void)setCategories:;
- (id)effects;
- (void)setVersion:;
- (id)version;
- (id)requestID;
- (void).cxx_destruct;
- (id)categories;
- (void)setRequestID:;
- (id)copyWithZone:;
- (void)setEffects:;
- (id)panel;
- (void)setPanelName:;
- (void)setPanel:;
- (id)urlPrefix;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)JSONTransformerForKey:;
@end
