@interface IESECShopMomentsViewController : IESECBaseShopTabViewController
@property (nonatomic) FBKVOController kvoController;
@property (nonatomic) IESECShopMomentsViewModel viewModel;
@property (nonatomic) IESECShopMomentsStatusView statusView;
@property (nonatomic) IESECListKitBFFViewController listVC;
@property (nonatomic) UIView<IESECAwemeVideoViewProtocol> player;
@property (nonatomic) UICollectionViewCell<IESECShopMomentsVideoCardProtocol> currentVideoCard;
@property (nonatomic) double constructTime;
@property (nonatomic) double pageInitTime;
@property (nonatomic) double pageReadyTime;
@property (nonatomic) @? scrollCallBack;
@property (nonatomic) IESECListKitCardPreloader lynxCardPreloader;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView rootView;
@property (nonatomic) IESECStorePageContext pageContext;
@property (nonatomic) <IESECStoreContainerProtocol> container;
- (id)p_findVideoCard;
- (void)tabScrollViewDidScrollCallback:;
- (void)tryToStopVideo:;
- (void)UIApplicationDidBecomeActiveNotification;
- (void)UIApplicationWillResignActiveNotification;
- (double)constructTime;
- (void)currentCardsWriteAlogMethodName:paramModel:result:context:;
- (id)currentVideoCard;
- (void)initFetchShopMomentsData;
- (id)initWithPageContext:;
- (id)kvoController;
- (id)listVC;
- (id)lynxCardPreloader;
- (void)muteVideo:;
- (BOOL)p_cardCanPlay:withVisiblePercent:;
- (void)p_footerEndRefreshingWithHasMore:;
- (void)p_loadMoreShopMomentsData;
- (void)p_playInCard:withPlayer:;
- (void)p_reloadShopMomentsData;
- (void)p_reportWithError:;
- (void)p_setupInfinitelyRefreshFooter;
- (void)p_stopInCard:withPlayer:;
- (double)pageInitTime;
- (double)pageReadyTime;
- (void)preloadLynxTemplates;
- (void)registerTabScrollViewDidEndDeceleratingCallback:;
- (void)registerTabScrollViewDidEndDraggingCallback:;
- (void)registerTabScrollViewWillBeginDraggingCallback:;
- (void)removeBackgroundColorIfNeeded;
- (id)scrollCallBack;
- (void)setConstructTime:;
- (void)setCurrentVideoCard:;
- (void)setKvoController:;
- (void)setListVC:;
- (void)setLynxCardPreloader:;
- (void)setPageInitTime:;
- (void)setPageReadyTime:;
- (void)setScrollCallBack:;
- (void)setupBinding;
- (void)setupRegister;
- (id)tabScrollViews;
- (void)trackStayWithEventName:duration:;
- (void)tryToPlayVideo;
- (void)updateWithPreloadTabModel:;
- (BOOL)videoShouldPause;
- (void)scrollViewDidEndDecelerating:;
- (void)setContainer:;
- (id)viewModel;
- (id)container;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (void)scrollViewWillBeginDragging:;
- (id)player;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void).cxx_destruct;
- (void)setPlayer:;
- (void)viewDidAppear:;
- (void)viewWillAppear:;
- (void)collectionView:didEndDisplayingCell:forItemAtIndexPath:;
- (void)setViewModel:;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)rootView;
- (void)setRootView:;
- (void)setupViews;
- (id)pageContext;
- (void)setPageContext:;
- (id)statusView;
- (void)setStatusView:;
@end
