@interface IESECFullReturnBannerView : UIView
@property (nonatomic) NSString fullReturnText;
@property (nonatomic) NSString hasBuy;
@property (nonatomic) NSString needBuy;
@property (nonatomic) IESECURLModel backgroundImageURL;
@property (nonatomic) IESECURLModel fullReturnIconURL;
@property (nonatomic) IESECGoodsFullReturnModel fullReturnInfo;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView backgroundImage;
@property (nonatomic) UIImageView fullReturnIcon;
@property (nonatomic) UILabel fullReturnLabel;
@property (nonatomic) UILabel progressLabel;
@property (nonatomic) UIImageView moreIcon;
@property (nonatomic) q viewStyle;
- (id)fullReturnLabel;
- (id)needBuy;
- (id)fullReturnIcon;
- (id)fullReturnIconURL;
- (id)fullReturnInfo;
- (id)fullReturnText;
- (id)hasBuy;
- (id)initWithParameters:style:;
- (id)moreIcon;
- (void)setFullReturnIcon:;
- (void)setFullReturnIconURL:;
- (void)setFullReturnInfo:;
- (void)setFullReturnLabel:;
- (void)setFullReturnText:;
- (void)setHasBuy:;
- (void)setMoreIcon:;
- (void)setNeedBuy:;
- (void)setupProgressLabel;
- (void)updateWithParameters:;
- (id)containerView;
- (void)setContainerView:;
- (void)setBackgroundImage:;
- (long long)viewStyle;
- (id)backgroundImage;
- (void).cxx_destruct;
- (void)setViewStyle:;
- (void)setupUI;
- (id)progressLabel;
- (void)setProgressLabel:;
- (id)backgroundImageURL;
- (void)setBackgroundImageURL:;
- (void)updateUI:;
@end
