@interface IESECShopActivityController : IESECShopControllerV2
@property (nonatomic) IESECUserTrackerPageContext eggPageContext;
@property (nonatomic) IESECShopGoldCoinTaskScrollingFilter goldCoinTaskScrollingFilter;
@property (nonatomic) UIView<IESECShopMarqueeProtocol> marqueeView;
@property (nonatomic) CADisplayLink displayLink;
@property (nonatomic) BOOL isNeedPostRequest;
@property (nonatomic) double stayDuration;
@property (nonatomic) IESECServiceProxy<IESECShopDataService> dataService;
@property (nonatomic) IESECServiceProxy<IESECShopStateService> stateService;
@property (nonatomic) IESECServiceProxy<IESECShopLayoutService> layoutService;
@property (nonatomic) IESECServiceProxy<IESECShopForwardCoService> forwardCoService;
@property (nonatomic) NSMutableDictionary redPackInterceptionConfig;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)iesecshop_screenStateDidChange:;
- (void)setDataService:;
- (void)handleFeTopTabs;
- (void)setGoldCoinTaskScrollingFilter:;
- (void)controllerDidAppear:;
- (void)controllerDidDisappear:;
- (void)controllerDidLoad;
- (void)controllerWillAppear:;
- (void)controllerWillDisappear:;
- (long long)currentPageContentMode;
- (id)dataService;
- (void)didSetControllerManagerV2:;
- (void)dismissMarqueeView;
- (void)displayLinkDidTrigger:;
- (id)eggPageContext;
- (void)enableDisplayCycleIfNeeded;
- (id)forwardCoService;
- (id)goldCoinTaskScrollingFilter;
- (void)handleExtraSchemaIfNeeded;
- (void)hostInjectionDidOpenPage;
- (void)hostInjectionDidPageScroll:;
- (void)hostInjectionDidPageSwitchMode;
- (void)hostInjectionPageWillAppearAgain;
- (void)hostInjectionViewWillDisappear;
- (void)hostInjectionWillClosePage;
- (void)hostInjectionWillOpenNextPage;
- (void)iesecshop_containerDidMoveToParentViewController:;
- (void)iesecshop_didFinishExtensionAreaAnimation;
- (void)iesecshop_didTapAtBottomTabItem:;
- (void)iesecshop_pagerView:didMoveToTab:;
- (void)iesecshop_pagerView:mainScrollViewDidScroll:;
- (void)iesecshop_pagerView:mainScrollViewWillBeginDragging:;
- (void)iesecshop_pagerView:tabScrollViewDidScroll:;
- (BOOL)isNeedPostRequest;
- (id)layoutService;
- (void)p_didEndScrolling;
- (BOOL)p_exceedMarqueeViewShowLimit;
- (id)pageDisplayExtraDict;
- (id)redPackInterceptionConfig;
- (void)requestWhenStayStorePageIfNeed;
- (void)setEggPageContext:;
- (void)setForwardCoService:;
- (void)setIsNeedPostRequest:;
- (void)setLayoutService:;
- (void)setRedPackInterceptionConfig:;
- (void)setStateService:;
- (void)setStayDuration:;
- (void)setupBinding;
- (void)startDisplayLink;
- (id)stateService;
- (double)stayDuration;
- (void)subscribePendantCloseEvent;
- (void)subscribeXBridgeEvents;
- (void)unsubscribeXBridgeEvents;
- (void)updateInterceptionConfigIfNeed;
- (id)displayLink;
- (void)setDisplayLink:;
- (id)init;
- (void)stopDisplayLink;
- (id)fromViewController;
- (id)marqueeView;
- (void).cxx_destruct;
- (void)setMarqueeView:;
@end
