@interface IESECWinLynxSectionController : IGListSectionController
@property (nonatomic) IESECWinLynxCardDiffableModel object;
@property (nonatomic) IESECWinContext context;
@property (nonatomic) IESECServiceProxy<IESECWinLynxCardService> lynxCardService;
@property (nonatomic) IESECServiceProxy<IESECWinLynxPreloadService> preloadService;
@property (nonatomic) IESECServiceProxy<IESECWinSplitService> splitService;
@property (nonatomic) IESECServiceProxy<IESECWinTabService> tabService;
@property (nonatomic) IESECServiceProxy<IESECWinOpportunityService> opportunityService;
@property (nonatomic) FBKVOController kvoCtrl;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)kvoCtrl;
- (id)lynxCardService;
- (BOOL)pageDidAppeared;
- (id)cellForItemAtIndex:;
- (id)currentListContextIdForCards;
- (void)didUpdateToObject:;
- (void)listAdapter:didEndDisplayingSectionController:;
- (void)listAdapter:didEndDisplayingSectionController:cell:atIndex:;
- (void)listAdapter:willDisplaySectionController:;
- (void)listAdapter:willDisplaySectionController:cell:atIndex:;
- (void)lynxCard:didLoadFail:;
- (void)lynxCard:didUpdateDataWithLynxViewFromType:perfDict:;
- (void)lynxCard:setupPerf:;
- (void)lynxCard:sizeDidChanged:;
- (void)lynxCard:updatePerf:;
- (id)opportunityService;
- (id)preloadService;
- (void)puzzleHybridPopControllerDismissedWithObject:;
- (void)removeSelf;
- (void)setKvoCtrl:;
- (void)setLynxCardService:;
- (void)setOpportunityService:;
- (void)setPreloadService:;
- (void)setSplitService:;
- (void)setTabService:;
- (id)splitService;
- (id)tabService;
- (void)tabViewController_viewWillAppear:;
- (void)tabViewController_viewWillDisappear:;
- (void)setObject:;
- (long long)numberOfItems;
- (void)dealloc;
- (id)context;
- (id)initWithContext:;
- (void).cxx_destruct;
- (id)object;
- (void)addObserver;
- (void)setContext:;
- (id)sizeForItemAtIndex:;
@end
