@interface IESECCommentMediaViewController : UIViewController
@property (nonatomic) NSArray mediaItems;
@property (nonatomic) IESECCommentMediaInteractorView interactorView;
@property (nonatomic) CAGradientLayer gradientLayer;
@property (nonatomic) CAGradientLayer bottomGradientLayer;
@property (nonatomic) UIViewController mediaVC;
@property (nonatomic) BOOL shouldHideMultiplyButton;
@property (nonatomic) IESECImagePreviewInteractiveTransition transition;
@property (nonatomic) IESECGoodsCommentContext context;
@property (nonatomic) <IESECCommentMediaDelegate> delegate;
@property (nonatomic) @? clickLikeButtonBlock;
@property (nonatomic) UIView animateTargetView;
@property (nonatomic) UIPanGestureRecognizer panToDismiss;
@property (nonatomic) double imageContainerAlpha;
@property (nonatomic) Q index;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)mediaVC;
- (void)setupInteractorView:mediaIndex:;
- (id)animateTargetView;
- (id)bottomGradientLayer;
- (id)clickLikeButtonBlock;
- (id)commentModuleWithDataType:;
- (void)dismiss:isCurrentVideoTab:;
- (double)imageContainerAlpha;
- (id)initWithMediaModels:mediaIndex:context:shouldHideMultiplyButton:;
- (id)interactorView;
- (id)mediaArrayWithModels:;
- (void)mediaPreviewController:didDismissWithIndex:isCurrentVideoTab:;
- (void)mediaPreviewController:didSwipeToIndex:previousIndex:;
- (id)panToDismiss;
- (void)progressIsSliding:;
- (void)pushMultypleMedias:;
- (void)setAnimateTargetView:;
- (void)setBottomGradientLayer:;
- (void)setClickLikeButtonBlock:;
- (void)setImageContainerAlpha:;
- (void)setInteractorView:;
- (void)setMediaVC:;
- (void)setPanToDismiss:;
- (void)setShouldHideMultiplyButton:;
- (void)setupImageGradientLayer;
- (void)setupMediaView:mediaIndex:;
- (void)setupNewImageGradientLayer:;
- (BOOL)shouldHideMultiplyButton;
- (void)showMultypleMediaButtonTrack;
- (id)targetViewForImagePreviewController:atIndex:;
- (void)updateInteractorViewData:mediaIndex:;
- (void)updateMediaModels:;
- (void)dismiss;
- (void)setTransition:;
- (id)transition;
- (id)currentImageView;
- (id)context;
- (id)gradientLayer;
- (void)setDelegate:;
- (unsigned long long)index;
- (id)delegate;
- (void)setIndex:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)viewWillAppear:;
- (void)setContext:;
- (void)viewDidLoad;
- (void)setGradientLayer:;
- (id)mediaItems;
- (void)setMediaItems:;
@end
