@interface IESECLiveGoodsListClickContext : NSObject
@property (nonatomic) q autoApplyCouponType;
@property (nonatomic) IESECLiveGoodsListParams params;
@property (nonatomic) BOOL isInitial;
@property (nonatomic) BOOL shouldTrackInitialInfo;
@property (nonatomic) BOOL shouldTrackInitialInfoV2;
@property (nonatomic) BOOL shouldTrackInitialSmartProduct;
@property (nonatomic) BOOL monitorTracked;
@property (nonatomic) double listViewReallyShowTime;
@property (nonatomic) NSDictionary temporaryTrackParams;
@property (nonatomic) NSMutableSet trackedIds;
@property (nonatomic) BOOL shouldTrackNow;
@property (nonatomic) NSMutableSet trackedTabIDs;
@property (nonatomic) BOOL hasLocatedGoods;
@property (nonatomic) BOOL hasShowRelatedLabel;
@property (nonatomic) BOOL everTrackedScroll;
@property (nonatomic) BOOL hasScrolledToBottom;
@property (nonatomic) BOOL bottomLabelShowed;
- (BOOL)hasLocatedGoods;
- (long long)autoApplyCouponType;
- (BOOL)bottomLabelShowed;
- (id)couponInfo;
- (BOOL)everTrackedScroll;
- (id)fetchParams;
- (BOOL)hasScrolledToBottom;
- (BOOL)hasShowRelatedLabel;
- (double)listViewReallyShowTime;
- (BOOL)monitorTracked;
- (void)setAutoApplyCouponType:;
- (void)setBottomLabelShowed:;
- (void)setEverTrackedScroll:;
- (void)setHasLocatedGoods:;
- (void)setHasScrolledToBottom:;
- (void)setHasShowRelatedLabel:;
- (void)setIsInitial:;
- (void)setListViewReallyShowTime:;
- (void)setMonitorTracked:;
- (void)setShouldTrackInitialInfo:;
- (void)setShouldTrackInitialInfoV2:;
- (void)setShouldTrackInitialSmartProduct:;
- (void)setShouldTrackNow:;
- (void)setTemporaryTrackParams:;
- (void)setTrackedIds:;
- (void)setTrackedTabIDs:;
- (BOOL)shouldTrackInitialInfo;
- (BOOL)shouldTrackInitialInfoV2;
- (BOOL)shouldTrackInitialSmartProduct;
- (BOOL)shouldTrackNow;
- (id)temporaryTrackParams;
- (id)trackedIds;
- (id)trackedTabIDs;
- (id)initWithParams:;
- (BOOL)isInitial;
- (void).cxx_destruct;
- (id)params;
+ (id)entranceForm;
@end
