@interface IESECPanoramaImage : LynxUI
@property (nonatomic) UIView contentView;
@property (nonatomic) BDImageView imageView;
@property (nonatomic) CMMotionManager motionManager;
@property (nonatomic) BOOL isStaticImage;
@property (nonatomic) {CGPoint=dd} originOffect;
@property (nonatomic) {CGVector=dd} rotateAngle;
@property (nonatomic) double maxRotateAngle;
@property (nonatomic) double lastTimeStamp;
@property (nonatomic) double imageWidthScale;
@property (nonatomic) double imageHeightScale;
@property (nonatomic) BOOL autoDetect;
@property (nonatomic) double updateInterval;
@property (nonatomic) double sensitive;
@property (nonatomic) double animationDuration;
@property (nonatomic) IESECTracker tracker;
- (void)animationDuration:requestReset:;
- (double)imageWidthScale;
- (void)didMotionUpdate;
- (void)setRotateAngle:;
- (BOOL)autoDetect;
- (void)autoDetect:requestReset:;
- (void)didReady;
- (double)imageHeightScale;
- (void)imageHeightScale:requestReset:;
- (void)imageWidthScale:requestReset:;
- (BOOL)isStaticImage;
- (double)lastTimeStamp;
- (double)maxRotateAngle;
- (id)originOffect;
- (void)pause:withResult:;
- (void)play:withResult:;
- (void)reload:withResult:;
- (id)rotateAngle;
- (void)sensitive:requestReset:;
- (void)setAutoDetect:;
- (void)setImageHeightScale:;
- (void)setImageWidthScale:;
- (void)setIsStaticImage:;
- (void)setLastTimeStamp:;
- (void)setMaxRotateAngle:;
- (void)setOriginOffect:;
- (void)src:requestReset:;
- (void)startMonitorMotion;
- (void)stop:withResult:;
- (void)stopMonitorMotion;
- (void)transformImage;
- (void)updateInterval:requestReset:;
- (void)setTracker:;
- (id)contentView;
- (void)dealloc;
- (id)tracker;
- (double)animationDuration;
- (double)updateInterval;
- (void)setUpdateInterval:;
- (void)setAnimationDuration:;
- (void).cxx_destruct;
- (id)imageView;
- (void)setContentView:;
- (void)setImageView:;
- (void)setSensitive:;
- (double)sensitive;
- (id)motionManager;
- (id)createView;
- (void)setMotionManager:;
- (void)updateImageSize;
+ (id)__lynx_prop_config__480;
+ (id)__lynx_prop_config__551;
+ (id)__lynx_prop_config__623;
+ (id)__lynx_prop_config__695;
+ (id)__lynx_prop_config__756;
+ (id)__lynx_prop_config__817;
+ (id)__lynx_prop_config__8810;
+ (id)__lynx_ui_method_config__10112;
+ (id)__lynx_ui_method_config__10713;
+ (id)__lynx_ui_method_config__11314;
+ (id)__lynx_ui_method_config__9511;
+ (void)registerPanoramaImage;
@end
