@interface IESECLiveAnchorCouponBindView : IESECLiveAnchorNavigationBaseView
@property (nonatomic) UITextField textField;
@property (nonatomic) UIButton clearButton;
@property (nonatomic) UIButton confirmButton;
@property (nonatomic) UILabel hintLabel;
@property (nonatomic) IESECLiveAnchorCouponCard couponCard;
@property (nonatomic) UIButton bindButton;
@property (nonatomic) UIView lineView;
@property (nonatomic) UILabel indicatorLabel;
@property (nonatomic) UIImageView hintImageView;
@property (nonatomic) NSString noticeText;
@property (nonatomic) BOOL hasBindAtLeastOneCoupon;
@property (nonatomic) Q previousTextLength;
@property (nonatomic) IESECLiveApi api;
@property (nonatomic) IESECLiveRoomContext roomContext;
@property (nonatomic) NSString roomID;
@property (nonatomic) @? completionHandler;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setRoomContext:;
- (void)_refreshUIWithInput:;
- (id)addWhitespceForText:;
- (id)bindButton;
- (void)clearButtonFired:;
- (id)confirmButtonDisableColor;
- (void)confirmButtonFired:;
- (void)confirmButtonShouldShow:;
- (id)confirmButtonTextColor;
- (id)couponCard;
- (void)grantCoupon:;
- (BOOL)hasBindAtLeastOneCoupon;
- (id)initWithFrame:roomID:roomContext:shouldShowMaskView:;
- (unsigned long long)previousTextLength;
- (void)setBindButton:;
- (void)setBindNoticeText:;
- (void)setCouponCard:;
- (void)setHasBindAtLeastOneCoupon:;
- (void)setIndicatorLabel:;
- (void)setInputNoticeText:;
- (void)setPreviousTextLength:;
- (void)setupCouponBindUI;
- (void)pop;
- (BOOL)textFieldShouldReturn:;
- (id)textField;
- (void)setCompletionHandler:;
- (void)setTextField:;
- (id)clearButton;
- (void)textFieldDidBeginEditing:;
- (BOOL)textFieldShouldEndEditing:;
- (void).cxx_destruct;
- (void)viewDidAppear;
- (BOOL)textField:shouldChangeCharactersInRange:replacementString:;
- (id)completionHandler;
- (id)lineView;
- (void)setLineView:;
- (id)noticeText;
- (void)setNoticeText:;
- (id)confirmButton;
- (void)setConfirmButton:;
- (id)hintLabel;
- (void)setHintLabel:;
- (id)hintImageView;
- (void)setHintImageView:;
- (id)roomID;
- (void)setRoomID:;
- (void)viewDidDisappear;
- (id)api;
- (id)roomContext;
- (id)indicatorLabel;
- (void)setClearButton:;
- (void)setHintText:;
- (void)setApi:;
@end
