@interface IESECStoreSearchViewController : UIViewController
@property (nonatomic) IESECRelationSearchContext searchContext;
@property (nonatomic) IESECShopSearchNavView navView;
@property (nonatomic) IESECStoreSearchGuideViewController guideViewController;
@property (nonatomic) IESECStoreSearchResultViewController resultViewController;
@property (nonatomic) IESECSearchSuggestViewController suggestViewController;
@property (nonatomic) IESECSearchSuggestManager suggestManager;
@property (nonatomic) IESECTracker tracker;
@property (nonatomic) NSDictionary searchTrackDic;
@property (nonatomic) NSDictionary enterSearchBTMInfo;
@property (nonatomic) q productTabStyle;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)backToGuideView;
- (id)p_topSearchWord;
- (id)navView;
- (long long)productTabStyle;
- (void)adTracker;
- (id)enterSearchBTMInfo;
- (void)fetchHotWords;
- (void)fetchSearchSuggestWordsWithKeyWord:;
- (id)guideViewController;
- (id)initWithSearchContext:;
- (id)resultViewController;
- (void)searchGoodsByKey:isDefault:;
- (void)searchGuideViewController:didReloadHotWordArray:;
- (void)searchGuideViewController:didSelectSearchWord:atIndex:searchType:;
- (void)searchKeywordFromRouter;
- (void)searchNav:textDidChange:;
- (void)searchNavTextDidBeginEditing:;
- (void)searchSuggestViewController:didDisplaySuggestion:atIndex:;
- (void)searchSuggestViewController:didPopulateSuggestion:atIndex:;
- (void)searchSuggestViewController:didSelectSuggestion:atIndex:;
- (void)searchSuggestViewControllerDidScroll:;
- (id)searchTrackDic;
- (void)setEnterSearchBTMInfo:;
- (void)setGuideViewController:;
- (void)setNavView:;
- (void)setProductTabStyle:;
- (void)setResultViewController:;
- (void)setSearchTrackDic:;
- (void)setSuggestManager:;
- (void)setSuggestViewController:;
- (id)suggestManager;
- (id)suggestViewController;
- (void)switchChildViewController:;
- (BOOL)ttHideNavigationBar;
- (void)updateSearchSuggestionsWithKeyWord:;
- (void)setTracker:;
- (BOOL)shouldAutorotate;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)setSearchContext:;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (long long)preferredStatusBarStyle;
- (id)tracker;
- (void)searchForWord:;
- (void)setPlaceholder:;
- (void)viewDidDisappear:;
- (void)viewWillDisappear:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)viewWillAppear:;
- (id)searchContext;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)setupUI;
- (void)backButtonTapped;
@end
