@interface IESECDisclaimerPopupCustomView : UIView
@property (nonatomic) {UIEdgeInsets=dddd} textViewEdgeInsets;
@property (nonatomic) NSDictionary extraParams;
@property (nonatomic) NSDictionary config;
@property (nonatomic) @? actionBlock;
@property (nonatomic) @? cancelBlock;
@property (nonatomic) UILabel mainTitleLabel;
@property (nonatomic) UITextView contentTextView;
@property (nonatomic) UITextView textView;
@property (nonatomic) UIImageView agreeImgV;
@property (nonatomic) BOOL isAgreed;
@property (nonatomic) IESECHighlightButton confirmButton;
@property (nonatomic) IESECHighlightButton closeButton;
@property (nonatomic) UIView contentView;
@property (nonatomic) IESECPopupView popup;
@property (nonatomic) IESECDisclaimerPopupUIConfiguration UIConfiguration;
@property (nonatomic) NSDictionary agreeImgConf;
@property (nonatomic) BOOL openWithSaaS;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setExtraParams:;
- (id)UIConfiguration;
- (id)contentTextView;
- (id)agreeImgConf;
- (id)agreeImgV;
- (void)agreeViewClick;
- (id)contentTextViewEdgeInsets;
- (void)dismissWhenCompleted:;
- (id)extraParams;
- (id)initWithExtraParams:actionBlock:cancelBlock:;
- (BOOL)isAgreed;
- (id)mainTitleLabel;
- (BOOL)openWithSaaS;
- (void)setAgreeImgConf:;
- (void)setAgreeImgV:;
- (void)setContentTextView:;
- (void)setIsAgreed:;
- (void)setMainTitleLabel:;
- (void)setOpenWithSaaS:;
- (void)setUIConfiguration:;
- (id)textViewEdgeInsets;
- (id)trackEventName;
- (void)dismiss;
- (id)textView;
- (id)contentView;
- (void)setCancelBlock:;
- (id)actionBlock;
- (void)setConfig:;
- (void)close;
- (void)setTextView:;
- (void)setup;
- (BOOL)textView:shouldInteractWithURL:inRange:interaction:;
- (id)cancelBlock;
- (void).cxx_destruct;
- (void)setContentView:;
- (id)config;
- (void)showInView:;
- (BOOL)textView:shouldInteractWithURL:inRange:;
- (void)setActionBlock:;
- (void)confirm;
- (id)confirmButton;
- (void)setConfirmButton:;
- (id)closeButton;
- (void)setCloseButton:;
- (id)popup;
- (void)setPopup:;
@end
