@interface IESECLiveGoodsListModel : IESECLiveApiBaseModel
@property (nonatomic) IESECLiveReplayFlow replayFlow;
@property (nonatomic) IESECLivePickedGoodsListExtraModel extra;
@property (nonatomic) BOOL commentaryVideoAuth;
@property (nonatomic) q anchorTransDataSetting;
@property (nonatomic) IESECLiveGoodsListAskExplainPopInfoModel askExplainPopInfo;
@property (nonatomic) BOOL askExplainAuth;
@property (nonatomic) IESECLiveAnchorOrderLimitModel anchorOrderLimitInfo;
@property (nonatomic) IESECLiveAnchorBubbleInfoModel bubbleInfo;
@property (nonatomic) NSNumber serverTime;
@property (nonatomic) q roomType;
@property (nonatomic) q hourBuyShopMatchStatus;
@property (nonatomic) NSString hourBuyShopID;
@property (nonatomic) IESECLiveListThemeModel liveTheme;
@property (nonatomic) q liteListStyle;
@property (nonatomic) NSDictionary liveThemeColorDic;
@property (nonatomic) NSDictionary liveThemeFileDic;
@property (nonatomic) NSDictionary liveThemeFontSizeDic;
@property (nonatomic) NSDictionary liveThemeRadiusDic;
@property (nonatomic) q cartAddEnhanceStyle;
@property (nonatomic) IESECLiveGoodsListApplyResp applyResp;
@property (nonatomic) NSString bottomTitle;
@property (nonatomic) NSString bottomEndTitle;
@property (nonatomic) IESECLiveListBottomGuideModel bottomGuideInfo;
@property (nonatomic) NSNumber expireTime;
@property (nonatomic) NSArray tabModels;
@property (nonatomic) Q tabValidMinGoodsCount;
@property (nonatomic) NSString currentPromotionId;
@property (nonatomic) IESECLiveListVibeModel topVibe;
@property (nonatomic) IESECLiveListHeaderModel header;
@property (nonatomic) IESECLiveGoodsListHeaderPromotionModel headerPromotion;
@property (nonatomic) NSArray entries;
@property (nonatomic) IESECLiveGoodsListBannerModel bannerModel;
@property (nonatomic) IESECLiveGoodsListAuthorReputationModel authorReputation;
@property (nonatomic) IESECLiveGoodsListAuthorShopInfo shopInfo;
@property (nonatomic) IESECLiveGoodsListAuthorShopWindowInfo shopWindowInfo;
@property (nonatomic) NSDictionary ritTags;
@property (nonatomic) BOOL showCart;
@property (nonatomic) IESECLiveRoomCart roomCart;
@property (nonatomic) q searchButtonStyle;
@property (nonatomic) NSString searchSchema;
@property (nonatomic) NSString biz_title;
@property (nonatomic) q totalGoodsCount;
@property (nonatomic) NSArray goodsList;
@property (nonatomic) q showAuthorConnect;
- (id)bottomGuideInfo;
- (id)headerPromotion;
- (id)topVibe;
- (id)ritTags;
- (void)setBannerModel:;
- (long long)totalGoodsCount;
- (id)anchorOrderLimitInfo;
- (long long)anchorTransDataSetting;
- (id)applyResp;
- (BOOL)askExplainAuth;
- (id)askExplainPopInfo;
- (id)authorReputation;
- (id)bannerModel;
- (id)biz_title;
- (id)bottomEndTitle;
- (id)bubbleInfo;
- (long long)cartAddEnhanceStyle;
- (BOOL)commentaryVideoAuth;
- (id)currentPromotionId;
- (id)generateThemeKey;
- (id)getLiteListThemeKey:;
- (id)goodsList;
- (id)hourBuyShopID;
- (long long)hourBuyShopMatchStatus;
- (long long)liteListStyle;
- (id)liveTheme;
- (id)liveThemeColorDic;
- (id)liveThemeFileDic;
- (id)liveThemeFontSizeDic;
- (id)liveThemeRadiusDic;
- (id)replayFlow;
- (id)roomCart;
- (long long)roomType;
- (long long)searchButtonStyle;
- (id)searchSchema;
- (void)setAnchorOrderLimitInfo:;
- (void)setAnchorTransDataSetting:;
- (void)setApplyResp:;
- (void)setAskExplainAuth:;
- (void)setAskExplainPopInfo:;
- (void)setAuthorReputation:;
- (void)setBiz_title:;
- (void)setBottomEndTitle:;
- (void)setBottomGuideInfo:;
- (void)setBubbleInfo:;
- (void)setCartAddEnhanceStyle:;
- (void)setCommentaryVideoAuth:;
- (void)setCurrentPromotionId:;
- (void)setExtra:;
- (void)setGoodsList:;
- (void)setHeaderPromotion:;
- (void)setHourBuyShopID:;
- (void)setHourBuyShopMatchStatus:;
- (void)setLiteListStyle:;
- (void)setLiveTheme:;
- (void)setLiveThemeColorDic:;
- (void)setLiveThemeFileDic:;
- (void)setLiveThemeFontSizeDic:;
- (void)setLiveThemeRadiusDic:;
- (void)setReplayFlow:;
- (void)setRitTags:;
- (void)setRoomCart:;
- (void)setRoomType:;
- (void)setSearchButtonStyle:;
- (void)setSearchSchema:;
- (void)setServerTime:;
- (void)setShopInfo:;
- (void)setShopWindowInfo:;
- (void)setShowAuthorConnect:;
- (void)setShowCart:;
- (void)setTabModels:;
- (void)setTabValidMinGoodsCount:;
- (void)setTopVibe:;
- (void)setTotalGoodsCount:;
- (id)shopInfo;
- (id)shopWindowInfo;
- (long long)showAuthorConnect;
- (BOOL)showCart;
- (id)tabModels;
- (unsigned long long)tabValidMinGoodsCount;
- (void)setHeader:;
- (void)setEntries:;
- (id)extra;
- (void).cxx_destruct;
- (id)entries;
- (id)serverTime;
- (id)header;
- (id)expireTime;
- (void)setExpireTime:;
- (id)bottomTitle;
- (void)setBottomTitle:;
+ (id)applyRespJSONTransformer;
+ (id)entriesJSONTransformer;
+ (id)goodsListJSONTransformer;
+ (id)ritTagsJSONTransformer;
+ (id)tabModelsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@end
