@interface IESECWinListKitNativeCell : UICollectionViewCell
@property (nonatomic) IESECLynxCard lynxCard;
@property (nonatomic) IESECLynxCardModel lynxCardModel;
@property (nonatomic) UIView nativeContentView;
@property (nonatomic) double nativeContentHeight;
@property (nonatomic) @? nativeCellClick;
@property (nonatomic) double lynxCardMarginTop;
@property (nonatomic) NSString currentEnvIdentifier;
@property (nonatomic) NSDictionary globalPropsExtra;
@property (nonatomic) NSDictionary rootGlobalPropsExtra;
@property (nonatomic) NSArray bridges;
@property (nonatomic) <IESECWinListKitNativeCellLynxCardDelegate> lynxCardDelegate;
@property (nonatomic) IESECWinLynxCardResponse lynxCardResp;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)bridges;
- (id)configLynxData:;
- (id)nativeCellClick;
- (void)removeLynxCard:;
- (void)currentCardsWriteAlogMethodName:paramModel:result:context:;
- (id)currentEnvIdentifier;
- (id)currentListContextIdForCards;
- (id)globalPropsExtra;
- (id)lynxCard;
- (void)lynxCard:didLoadFail:;
- (void)lynxCard:sizeDidChanged:;
- (id)lynxCardDelegate;
- (double)lynxCardMarginTop;
- (id)lynxCardModel;
- (id)lynxCardResp;
- (void)nativeCellDidClick;
- (double)nativeContentHeight;
- (id)nativeContentView;
- (id)rootGlobalPropsExtra;
- (void)setBridges:;
- (void)setCurrentEnvIdentifier:;
- (void)setGlobalPropsExtra:;
- (void)setLynxCard:;
- (void)setLynxCardDelegate:;
- (void)setLynxCardMarginTop:;
- (void)setLynxCardModel:;
- (void)setNativeCellClick:;
- (void)setNativeContentHeight:;
- (void)setRootGlobalPropsExtra:;
- (void)updateListLayoutWithLynxCard:;
- (void)updateLynxCardHeight:;
- (void)updateWithLynxCardResp:;
- (void).cxx_destruct;
@end
