@interface IESGurdBaseDownloadOperation : NSOperation
@property (nonatomic) BOOL isPatch;
@property (nonatomic) IESGurdResourceModel config;
@property (nonatomic) @? downloadCompletion;
@property (nonatomic) q downloadPriority;
@property (nonatomic) IESGurdDownloadPackageInfo downloadPackageInfo;
@property (nonatomic) BOOL executing;
@property (nonatomic) BOOL finished;
@property (nonatomic) IESGurdDownloadInfoModel downloadInfoModel;
@property (nonatomic) NSString accessKey;
@property (nonatomic) NSString channel;
@property (nonatomic) BOOL retryDownload;
- (void)sendUpdateStats;
- (void)callDownloadCompletion:error:;
- (BOOL)checkNeedDownload;
- (id)downloadInfoModel;
- (void)downloadOdr;
- (id)downloadPackageInfo;
- (id)getResourceModel;
- (id)getUpdateStageMode:;
- (void)handleBusinessFailedWithType:;
- (void)handleDownloadResult:downloadInfo:error:;
- (void)handleDownloadResultWithDownloadInfo:succeed:error:;
- (void)handleOperationCancel;
- (void)innerFinishDownload:error:;
- (BOOL)isResourceActiveWithMeta:;
- (void)log:hasError:;
- (void)onCheckError:msg:;
- (void)setDownloadInfoModel:;
- (void)setDownloadPackageInfo:;
- (void)setRetryDownload:;
- (void)updateDownloadPriority:;
- (void)setFinished:;
- (void)setChannel:;
- (void)cancel;
- (id)channel;
- (void)start;
- (BOOL)isConcurrent;
- (void)setConfig:;
- (long long)downloadPriority;
- (BOOL)isExecuting;
- (BOOL)isFinished;
- (BOOL)isPatch;
- (void)setIsPatch:;
- (void).cxx_destruct;
- (void)setDownloadPriority:;
- (id)config;
- (void)setExecuting:;
- (id)downloadCompletion;
- (id)accessKey;
- (void)setAccessKey:;
- (BOOL)retryDownload;
- (void)setDownloadCompletion:;
- (void)operationDidStart;
+ (id)operationWithConfig:isPatch:downloadCompletion:;
@end
