@interface IESLiveBigGiftComboView : UIView
@property (nonatomic) IESLiveUnifiedGiftComboView comboViewContainer;
@property (nonatomic) IESLiveBigGiftComboActivityViewModel activityViewModel;
@property (nonatomic) IESLiveGiveGiftTransaction giftTransaction;
@property (nonatomic) HTSLiveGiftItem giftItem;
@property (nonatomic) ComboHint originComboHint;
@property (nonatomic) NSMutableArray giftComboInfos;
@property (nonatomic) NSArray comboHints;
@property (nonatomic) NSArray normalComboHintArray;
@property (nonatomic) NSArray classicComboHintArray;
@property (nonatomic) HTSLiveComboHintData firstTimeComboHint;
@property (nonatomic) NSInteger firstTimeComboScene;
@property (nonatomic) NSDictionary rocketMaxLimitMap;
@property (nonatomic) q pendingCount;
@property (nonatomic) q currentSection;
@property (nonatomic) q currentCount;
@property (nonatomic) q currentHintSection;
@property (nonatomic) q currentSendTogetherHintSection;
@property (nonatomic) q currentClassicHintSection;
@property (nonatomic) q trackClassicHintSection;
@property (nonatomic) BOOL hasDisplayedClassicFirstTime;
@property (nonatomic) BOOL enableClickTrack;
@property (nonatomic) BOOL enableClassicClickTrack;
@property (nonatomic) HTSLiveComboHintData comboHintTrackData;
@property (nonatomic) HTSLiveComboHintData classicComboHintTrackData;
@property (nonatomic) IESLiveGiveGiftDynamicParams dynamicParams;
@property (nonatomic) NSMutableDictionary sendTogetherImact;
@property (nonatomic) BOOL pressing;
@property (nonatomic) IESLiveCountTimer timer;
@property (nonatomic) double buffer;
@property (nonatomic) double currentVerlocity;
@property (nonatomic) double verlocityLimit;
@property (nonatomic) q gradient;
@property (nonatomic) q pressingTimes;
@property (nonatomic) <IESLiveRebornGiftAnimationRouter> giftAnimationRouter;
@property (nonatomic) BOOL isDismissing;
@property (nonatomic) HTSLiveUser currentLoginUser;
@property (nonatomic) BOOL seriesGiftForbidComboHint;
@property (nonatomic) BOOL enableAfterSendSchema;
@property (nonatomic) IESLiveGiftPanelViewModel panelViewModel;
@property (nonatomic) @? handleSendGiftError;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)dismissNormally;
- (id)giftTransaction;
- (void)increaseSection;
- (id)originComboHint;
- (id)activityViewModel;
- (void)allAnimationPlayFinished;
- (void)banMontageGiftIfNeeded:;
- (id)classicComboHintArray;
- (id)classicComboHintTrackData;
- (id)comboHintTrackData;
- (id)comboHints;
- (id)comboViewContainer;
- (long long)currentClassicHintSection;
- (long long)currentComboCount;
- (long long)currentHintSection;
- (id)currentLoginUser;
- (long long)currentSendTogetherHintSection;
- (double)currentVerlocity;
- (void)didGiveGiftFailed:error:;
- (void)didSetAttachingDIContext;
- (void)disableClassicClickTrack;
- (void)disableClickTrack;
- (BOOL)enableAfterSendSchema;
- (BOOL)enableClassicClickTrack;
- (BOOL)enableClickTrack;
- (id)firstTimeComboHint;
- (int)firstTimeComboScene;
- (id)giftAnimationRouter;
- (id)giftComboInfos;
- (id)handleSendGiftError;
- (BOOL)hasDisplayedClassicFirstTime;
- (void)impact;
- (void)increaseCount;
- (void)increaseLongPressed;
- (id)initWithTransaction:dynamicParams:giftItem:baseCount:;
- (BOOL)isBigGift;
- (void)launchActivityViewModelIfNeed;
- (id)normalComboHintArray;
- (void)onclickBuffGiftIcon;
- (id)panelViewModel;
- (BOOL)pressing;
- (long long)pressingTimes;
- (void)regenerateSendTogetherComboHintArray:;
- (id)rocketMaxLimitMap;
- (void)sendGift;
- (void)sendGiftSuccess:;
- (id)sendTogetherImact;
- (BOOL)seriesGiftForbidComboHint;
- (void)setActivityViewModel:;
- (void)setClassicComboHintArray:;
- (void)setClassicComboHintTrackData:;
- (void)setComboHintTrackData:;
- (void)setComboHints:;
- (void)setComboViewContainer:;
- (void)setCurrentClassicHintSection:;
- (void)setCurrentHintSection:;
- (void)setCurrentLoginUser:;
- (void)setCurrentSendTogetherHintSection:;
- (void)setCurrentVerlocity:;
- (void)setDynamicParams:;
- (void)setEnableAfterSendSchema:;
- (void)setEnableClassicClickTrack:;
- (void)setEnableClickTrack:;
- (void)setFirstTimeComboHint:;
- (void)setFirstTimeComboScene:;
- (void)setGiftAnimationRouter:;
- (void)setGiftComboInfos:;
- (void)setGiftTransaction:;
- (void)setHandleSendGiftError:;
- (void)setHasDisplayedClassicFirstTime:;
- (void)setNormalComboHintArray:;
- (void)setOriginComboHint:;
- (void)setPanelViewModel:;
- (void)setPressing:;
- (void)setPressingTimes:;
- (void)setRocketMaxLimitMap:;
- (void)setSendTogetherImact:;
- (void)setSeriesGiftForbidComboHint:;
- (void)setTrackClassicHintSection:;
- (void)setVerlocityLimit:;
- (void)showClassicComboHint;
- (void)showClassicFirstTimeComboHint;
- (void)showHintHugeText;
- (void)showHugeText;
- (void)showSendTogetherComboHint;
- (void)showSendTogetherFirstTimeComboHint;
- (long long)trackClassicHintSection;
- (void)trackForComboShow;
- (void)trackForShowClassicClick;
- (void)trackForShowClassicHintText;
- (void)trackForShowGiftComboClick;
- (void)trackForShowHintText;
- (void)trackForShowSendTogetherClick;
- (void)trackForShowSendTogetherHintText;
- (void)updateActivityView:;
- (void)updateComboInfosWithHint:;
- (double)verlocityLimit;
- (void)setBuffer:;
- (long long)currentCount;
- (void)dismiss;
- (void)removeFromSuperview;
- (void)setGradient:;
- (void)dealloc;
- (double)buffer;
- (void)didMoveToSuperview;
- (long long)gradient;
- (void)longPress:;
- (void)tap:;
- (void)setTimer:;
- (void)startAnimation;
- (void).cxx_destruct;
- (id)timer;
- (BOOL)isDismissing;
- (void)loop;
- (void)setupUI;
- (void)setIsDismissing:;
- (long long)pendingCount;
- (void)setCurrentCount:;
- (void)setPendingCount:;
- (long long)currentSection;
- (void)setCurrentSection:;
- (id)giftItem;
- (void)setGiftItem:;
- (id)dynamicParams;
@end
