@interface IESLivePKScoreBar : UIView
@property (nonatomic) double ratio;
@property (nonatomic) double instantKillRatio;
@property (nonatomic) q leftNum;
@property (nonatomic) q rightNum;
@property (nonatomic) NSString leftNumStr;
@property (nonatomic) NSString rightNumStr;
@property (nonatomic) NSString currentAddScoreStr;
@property (nonatomic) NSString relativeStr;
@property (nonatomic) UIFont scoreTextFont;
@property (nonatomic) BOOL isShowRelative;
@property (nonatomic) UIView contentView;
@property (nonatomic) UIView leftNumView;
@property (nonatomic) UIView rightNumView;
@property (nonatomic) UILabel leftLabel;
@property (nonatomic) UILabel rightLabel;
@property (nonatomic) IESLiveOutsideStrokeLabel currentAddScoreLabel;
@property (nonatomic) IESLivePKScoreBarUsersView currentUsersView;
@property (nonatomic) NSString currentAnimationResource;
@property (nonatomic) IESLiveAnimatedImageView animatedImageView;
@property (nonatomic) IESLiveAnimatedImageView waveAnimatedView;
@property (nonatomic) IESLiveAnimatedImageView currentParticleAnimatedView;
@property (nonatomic) UIImageView currentParticleImageView;
@property (nonatomic) UIImageView instantKillImageView;
@property (nonatomic) NSString currentInstantKillImageName;
@property (nonatomic) NSMutableDictionary animationDataCache;
@property (nonatomic) IESLivePKScoreBarEffectInfoContainer effectInfoContainer;
@property (nonatomic) BOOL isShowRelativeForceUpdate;
@property (nonatomic) double animateOffSetX;
@property (nonatomic) double animateOffSetY;
@property (nonatomic) double currentAddScoreLabelWidth;
@property (nonatomic) <IESLiveCompoundSubscription> disposable;
@property (nonatomic) BOOL needReward;
@property (nonatomic) BOOL isLoadedRewardUI;
@property (nonatomic) BOOL isStealTower;
@property (nonatomic) BOOL isSelfRewarding;
@property (nonatomic) BOOL isOppoRewarding;
@property (nonatomic) BOOL isTeamTaskAnimating;
@property (nonatomic) BOOL isTeamTaskAnimatingRefreshLayout;
@property (nonatomic) BOOL didUpdateLeftNum;
@property (nonatomic) UILabel leftTeamTaskRewardLabel;
@property (nonatomic) UIImageView oppoTeamTaskRewardImageView;
@property (nonatomic) UIImageView teamTaskLightingImageView;
@property (nonatomic) IESLiveCountTimer doubleTaskShownTimer;
@property (nonatomic) <IESLiveRevenueInteractPlayModel> playModel;
@property (nonatomic) IESLivePKScoreBarConfig config;
@property (nonatomic) double scoreBarLeftHeight;
@property (nonatomic) double scoreBarRightHeight;
@property (nonatomic) double scoreBarLeftY;
@property (nonatomic) double scoreBarRightY;
@property (nonatomic) BOOL isRecover;
@property (nonatomic) BOOL isSyncUpdateImage;
- (void)setCurrentInstantKillImageName:;
- (void)updateLeftLabel;
- (void)updateWithContainerFrameChanged;
- (BOOL)isEffectInfoFog;
- (BOOL)isOppoRewarding;
- (BOOL)isSelfRewarding;
- (long long)leftNum;
- (void)setAtmosphereAnimationImageUrl:;
- (void)setCurrentParticleAnimatedView:;
- (void)setLeftNumView:;
- (void)setOppoTeamTaskRewardImageView:;
- (void)setRelativeStr:;
- (void)setRightNumStr:;
- (void)updateScoreLabelIsShowRelative:;
- (double)animateOffSetX;
- (double)animateOffSetY;
- (id)animatedImageView;
- (id)animationDataCache;
- (id)animationDataForImageName:;
- (void)cleanScoreBarInstantKillLine;
- (void)clearAtmosphereAnimationImage;
- (id)currentAddScoreLabel;
- (double)currentAddScoreLabelWidth;
- (id)currentAddScoreStr;
- (id)currentAnimationResource;
- (id)currentInstantKillImageName;
- (id)currentParticleAnimatedView;
- (id)currentParticleImageView;
- (id)currentUsersView;
- (BOOL)didUpdateLeftNum;
- (id)disposable;
- (id)doubleTaskShownTimer;
- (id)effectInfoContainer;
- (double)effectInfoRatio:;
- (double)effectInfoScoreBarLeftHeight;
- (double)effectInfoScoreBarLeftY;
- (void)endOppoTeamTaskReward;
- (void)endSelfTeamTaskReward:;
- (void)initSubviews;
- (id)initWithDIContext:config:;
- (id)instantKillImageView;
- (double)instantKillRatio;
- (BOOL)isInitialScore;
- (BOOL)isLoadedRewardUI;
- (BOOL)isNeedHiddenAnimatedImageView;
- (BOOL)isRecover;
- (BOOL)isRightEffectInfoFog;
- (BOOL)isShowLeftEffectInfo;
- (BOOL)isShowRelative;
- (BOOL)isShowRelativeForceUpdate;
- (BOOL)isShowRightEffectInfo;
- (BOOL)isShowingEffectInfoContainer;
- (BOOL)isStealTower;
- (BOOL)isSyncUpdateImage;
- (BOOL)isTeamTaskAnimating;
- (BOOL)isTeamTaskAnimatingRefreshLayout;
- (id)leftAttributedString;
- (id)leftNumStr;
- (id)leftNumView;
- (id)leftTeamTaskRewardLabel;
- (void)loadWaveAnimationViewWithImageName:loopCount:complete:;
- (BOOL)needReward;
- (BOOL)needShowOppoTeamTaskAdditionInfo;
- (id)oppoTeamTaskRewardImageView;
- (id)playModel;
- (BOOL)refreshEffectInfoContainer;
- (void)refreshEffectInfoContainerWithScoreStr:;
- (void)refreshEffectInfoMidAnimatedView;
- (id)relativeStr;
- (void)removeCurrentAddScoreLabel;
- (id)rightAttributedString;
- (long long)rightNum;
- (id)rightNumStr;
- (id)rightNumView;
- (double)scoreBarLeftHeight;
- (double)scoreBarLeftY;
- (double)scoreBarRightHeight;
- (double)scoreBarRightY;
- (id)scoreTextFont;
- (void)setAnimateOffSetX:;
- (void)setAnimateOffSetY:;
- (void)setAnimatedImageView:;
- (void)setAnimationDataCache:;
- (void)setAtmosphereAnimationImage:withFrame:;
- (void)setAtmosphereAnimationImageUrlAlpha:isChangeAlpha:;
- (void)setAtmosphereScoreStrLabel:duration:;
- (void)setAtmosphereUsersView:isMyGift:;
- (void)setCurrentAddScoreLabel:;
- (void)setCurrentAddScoreLabelStyle;
- (void)setCurrentAddScoreLabelWidth:;
- (void)setCurrentAddScoreStr:;
- (void)setCurrentAnimationResource:;
- (void)setCurrentParticleAnimatedImageUrl:;
- (void)setCurrentParticleImageView:;
- (void)setCurrentUsersView:;
- (void)setDidUpdateLeftNum:;
- (void)setDisposable:;
- (void)setDoubleTaskShownTimer:;
- (void)setEffectInfoContainer:;
- (void)setInstantKillImageView:;
- (void)setInstantKillRatio:;
- (void)setIsLoadedRewardUI:;
- (void)setIsOppoRewarding:;
- (void)setIsRecover:;
- (void)setIsSelfRewarding:;
- (void)setIsShowRelative:;
- (void)setIsShowRelativeForceUpdate:;
- (void)setIsStealTower:;
- (void)setIsSyncUpdateImage:;
- (void)setIsTeamTaskAnimating:;
- (void)setIsTeamTaskAnimatingRefreshLayout:;
- (void)setLeftNum:;
- (void)setLeftNumStr:;
- (void)setLeftScore:scoreStr:;
- (void)setLeftTeamTaskRewardLabel:;
- (void)setNeedReward:;
- (void)setPlayModel:;
- (void)setRightNum:;
- (void)setRightNumView:;
- (void)setRightScore:scoreStr:;
- (void)setScoreBarInstantKillLine:;
- (void)setScoreBarLeftHeight:;
- (void)setScoreBarLeftY:;
- (void)setScoreBarRightHeight:;
- (void)setScoreBarRightY:;
- (void)setScoreTextFont:;
- (void)setTeamTaskLightingImageView:;
- (void)setWaveAnimatedView:;
- (void)showWaveAnimationView;
- (void)startOppoTeamTaskReward;
- (void)startSelfTeamTaskReward:;
- (void)startStealTower:;
- (id)teamTaskLightingImageView;
- (void)updateRightLabel;
- (void)updateScoreBarInstantKillLine:;
- (void)updateScoreBarLayoutIsReward:;
- (void)updateTeamTaskRewardLeftScore:isDoubleTask:;
- (void)updateViewAnimated:;
- (void)updateViewAnimated:showWaveAnimation:isDoubleTask:;
- (id)waveAnimatedView;
- (id)contentView;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setConfig:;
- (id)hitTest:withEvent:;
- (void).cxx_destruct;
- (void)setContentView:;
- (id)config;
- (id)leftLabel;
- (id)rightLabel;
- (void)updateCornerRadius;
- (double)ratio;
- (void)setRatio:;
- (void)setLeftLabel:;
- (void)setRelativeScore:;
- (void)setRightLabel:;
- (void)clean;
@end
