@interface IESLiveSaaSMSequenceAnchorFragment : IESLiveRoomComponent
@property (nonatomic) IESLiveSaaSLiveRoomModel room;
@property (nonatomic) IESLiveSaaSMSeqAnchorRecordView recordView;
@property (nonatomic) IESLiveSaaSMSeqCountdownView countDownView;
@property (nonatomic) IESLiveSaaSMSeqAnchorStore store;
@property (nonatomic) IESLiveSaaSCountTimer timer;
@property (nonatomic) BOOL isOnMSequenceRoom;
@property (nonatomic) BOOL isOnMSequenceWillStart;
@property (nonatomic) BOOL isOnMSequenceWillEnd;
@property (nonatomic) BOOL anchorInteractiveEnabled;
@property (nonatomic) q alertBeforeEnd;
@property (nonatomic) q forbidBeforeEnd;
@property (nonatomic) <IESLiveSaaSRootRouter> containerRouter;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)containerRouter;
- (long long)forbidBeforeEnd;
- (long long)alertBeforeEnd;
- (BOOL)anchorInteractiveEnabled;
- (void)componentDidMount;
- (void)componentWillUnmount;
- (id)countDownView;
- (unsigned long long)currentMseqLayout;
- (void)didSetAttachingDIContext;
- (void)disableInteractiveBeforeStart:text:;
- (void)enableInteractive;
- (void)enterMseqAtFirst;
- (void)forceOpenIntimateChat;
- (BOOL)getCurrentRoomIsInOfficialChannel;
- (void)hideComponent;
- (BOOL)isAnchorMSeqRoomWillStart;
- (BOOL)isMSeqBackupRoom;
- (BOOL)isMSeqRoomWillEnd;
- (BOOL)isOnMSequenceRoom;
- (BOOL)isOnMSequenceWillEnd;
- (BOOL)isOnMSequenceWillStart;
- (double)mSeqCountDownTipHeight;
- (id)recordView;
- (void)setAlertBeforeEnd:;
- (void)setAnchorInteractiveEnabled:;
- (void)setContainerRouter:;
- (void)setCountDownView:;
- (void)setForbidBeforeEnd:;
- (void)setIsOnMSequenceRoom:;
- (void)setIsOnMSequenceWillEnd:;
- (void)setIsOnMSequenceWillStart:;
- (void)setRecordView:;
- (void)showComponent;
- (void)showCountDownTipView;
- (void)startCountDownGuide;
- (void)startEnterMSeqCountDown:onMSeqTime:;
- (void)startLeaveMSeqCountDown:;
- (id)toastStringBeforeEnd;
- (void)stopTimer;
- (id)init;
- (void)dealloc;
- (void)setStore:;
- (void)startTimer;
- (void)setTimer:;
- (void).cxx_destruct;
- (id)timer;
- (id)store;
+ (id)componentWithRoom:trackContext:componentContext:;
@end
