@interface IESLiveRevenueInteractPlayInstance : NSObject
@property (nonatomic) IESLiveRevenueInteractPlayModel model;
@property (nonatomic) IESLiveRevenueInteractPlayBuilder builder;
@property (nonatomic) <IESLiveRevenueInteractProvider> provider;
@property (nonatomic) IESLiveRevenueInteractPlayAPI api;
@property (nonatomic) <IESLiveCompoundSubscription> disposable;
@property (nonatomic) IESLiveRevenueInteractApi revenueInteractApi;
@property (nonatomic) IESLiveRevenueInteractDurationTrackHelper durationTrackHelper;
@property (nonatomic) HTSEventForwardingView battlePlaygroundView;
@property (nonatomic) NSMutableDictionary battleViewDic;
@property (nonatomic) IESLiveRevenueInteractPlayComponentManager componentManager;
@property (nonatomic) IESLiveCountTimer battleTimer;
@property (nonatomic) IESLiveCountTimer punishTimer;
@property (nonatomic) IESLiveCountTimer finishTimeOutTimer;
@property (nonatomic) BOOL isDestroying;
@property (nonatomic) BOOL hasTrackPKEnd;
@property (nonatomic) BOOL hasLoadLynxControlComponents;
@property (nonatomic) double lynxVideoLayoutOffset;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)logEvent:extra:;
- (void)setPunishTimer:;
- (void)trackPKLivePlay;
- (void)handleNativeComponents:byEvent:;
- (void)onBattleTimeOut;
- (void)onPunishTimeOut;
- (void)setBattleTimer:;
- (void)stopBattleTimer;
- (void)stopPunishTimer;
- (id)battlePlaygroundView;
- (id)battleTimer;
- (id)battleViewDic;
- (void)bindAction;
- (void)clearBattleViews;
- (void)clearGridView;
- (void)didChangeStateFrom:to:;
- (void)didChangeStateToPlayingFrom:;
- (void)didChangeStateToResultFrom:;
- (void)didLayoutModelChanged;
- (id)disposable;
- (id)durationTrackHelper;
- (id)finishTimeOutTimer;
- (void)handleClearNotification:;
- (BOOL)hasLoadLynxControlComponents;
- (BOOL)hasTrackPKEnd;
- (id)initWithDIContext:builder:;
- (BOOL)isDestroying;
- (BOOL)isPlaygroundHandleStreamAndLocalLayout;
- (BOOL)isVaildPlayTimeToStart;
- (void)layoutBattleViews;
- (void)layoutPlaygroundGridViewWithFrame:userId:;
- (double)lynxVideoLayoutOffset;
- (void)modifyStreamTopOffest:;
- (void)notifyLynxEvent:extraParams:;
- (void)onBattleEffectContainerMessageReceived:;
- (void)onBattleMessageReceived:;
- (void)onBattleStateSyncMessageReceived:;
- (void)onBattleTeamTaskMessageReceived:;
- (void)onBattleTimeInvalid;
- (void)onBattleToastMessageReceived:;
- (void)onFinishMessageReceived:;
- (void)onInstanceDestroy;
- (void)onInstanceStartWithData:;
- (void)onPlayStartWithData:;
- (void)onScoreMessageReceived:;
- (void)onStartListResponseReceived:;
- (id)punishTimer;
- (void)pveHandleBattleBg:topImage:bottomImage:;
- (void)requestBattleFinish:;
- (void)requestBattleOnceMoreReplyWithInviterId:inviteType:toMultiPKMode:isAccept:;
- (void)requestLinkmicListToResult;
- (void)requestPlayStateTransition:stage:;
- (BOOL)resolveBattleTimeForValid;
- (BOOL)resolvePunishTimeForValid;
- (id)revenueInteractApi;
- (void)setBattlePlaygroundView:;
- (void)setBattleViewDic:;
- (void)setComponentManager:;
- (void)setDisposable:;
- (void)setDurationTrackHelper:;
- (void)setFinishTimeOutTimer:;
- (void)setHasLoadLynxControlComponents:;
- (void)setHasTrackPKEnd:;
- (void)setIsDestroying:;
- (void)setLynxVideoLayoutOffset:;
- (void)setRevenueInteractApi:;
- (void)setupGridView:;
- (id)sortedSession;
- (void)startBattleFinishTimeOutTimer;
- (void)startBattleTimerWithDuration:;
- (void)startPunishTimerWithDuration:;
- (void)stopBattleFinishTimeOutTimer;
- (void)trackPKEndWithReason:isInterruptPlaying:isInitiator:;
- (void)trackPKWatchDurationByChangeMode:;
- (void)updateBattleViewWithClearMessage:;
- (void)updateBattleViewsHidden;
- (void)updateMedalIcon:;
- (void)updatePluginLayoutIfNeeded;
- (void)updateVideoLayoutIfNeeded;
- (double)videoLayoutOffset;
- (void)setProvider:;
- (id)model;
- (void)setModel:;
- (BOOL)isAnchor;
- (id)builder;
- (id)provider;
- (id)adapter;
- (void).cxx_destruct;
- (void)messageReceived:;
- (id)api;
- (void)setBuilder:;
- (void)setApi:;
- (id)componentManager;
@end
