@interface IESLiveSaaSEnterRoomParamsModel : BDDynamicModel
@property (nonatomic) NSDictionary originalParameter;
@property (nonatomic) NSNumber roomID;
@property (nonatomic) NSNumber replayId;
@property (nonatomic) NSNumber xtabSelectTabId;
@property (nonatomic) BOOL enableReplay;
@property (nonatomic) NSString ownerID;
@property (nonatomic) NSString secOwnerID;
@property (nonatomic) NSString enterFrom;
@property (nonatomic) NSString enterMethod;
@property (nonatomic) BOOL enableFeedDrawer;
@property (nonatomic) BOOL isFromNearbyTV;
@property (nonatomic) NSString fromUID;
@property (nonatomic) NSArray idArr;
@property (nonatomic) NSString innerFeedURL;
@property (nonatomic) NSString isEffectAd;
@property (nonatomic) NSDictionary effectAdDic;
@property (nonatomic) NSString videoID;
@property (nonatomic) NSString logPb;
@property (nonatomic) NSString requestID;
@property (nonatomic) NSString requestPage;
@property (nonatomic) NSString anchorType;
@property (nonatomic) NSString pushTypeString;
@property (nonatomic) NSString toMultiSegue;
@property (nonatomic) NSString liveReason;
@property (nonatomic) NSDictionary extraParmas;
@property (nonatomic) NSString searchID;
@property (nonatomic) NSString searchType;
@property (nonatomic) NSNumber giftID;
@property (nonatomic) NSString creativeID;
@property (nonatomic) NSNumber isFromAD;
@property (nonatomic) NSDictionary IESLiveEffectAdTrackExtraServiceKey;
@property (nonatomic) NSString isOtherChannel;
@property (nonatomic) NSString logExtra;
@property (nonatomic) NSString ecomLiveParams;
@property (nonatomic) NSString roomEnterScheme;
@property (nonatomic) NSNumber multitabSelectTabid;
@property (nonatomic) NSString logParams;
@property (nonatomic) NSNumber collectionId;
@property (nonatomic) NSDictionary schemaParams;
@property (nonatomic) NSString passThroughLogData;
@property (nonatomic) BOOL toSingleRoom;
@property (nonatomic) NSNumber seekTime;
@property (nonatomic) NSString matchId;
@property (nonatomic) NSString sharePlatform;
@property (nonatomic) NSString defaultResolution;
@property (nonatomic) BOOL enterMultiRoomForDefault;
@property (nonatomic) NSString schemeExtraParams;
@property (nonatomic) NSDictionary feedExtraParams;
@property (nonatomic) BOOL needToTrackAllParams;
@property (nonatomic) NSDictionary clickParams;
@property (nonatomic) BOOL closeCurrentRoom;
@property (nonatomic) NSString roomFinishedNotice;
@property (nonatomic) NSString originalRoomInfo;
@property (nonatomic) BOOL usePre;
@property (nonatomic) NSString pullStreamData;
@property (nonatomic) BOOL isReenter;
@property (nonatomic) BOOL fromOutside;
@property (nonatomic) NSString cameraID;
@property (nonatomic) BOOL showLoading;
- (id)matchId;
- (id)roomEnterScheme;
- (void)setEnterMethod:;
- (id)attachingDIContext;
- (id)ecomLiveParams;
- (id)enterFrom;
- (id)enterMethod;
- (id)initWithParameter:;
- (BOOL)isReenter;
- (id)logParams;
- (id)multitabSelectTabid;
- (BOOL)p_enableNearbyTVDrawerOfEnterFrom:enterMethod:;
- (void)p_parseParameter;
- (id)schemaParamsWithOriginalParameter:;
- (void)setCameraID:;
- (void)setEcomLiveParams:;
- (void)setEnterFrom:;
- (void)setIsReenter:;
- (void)setLogParams:;
- (void)setMatchId:;
- (void)setMultitabSelectTabid:;
- (void)setRoomEnterScheme:;
- (void)setSharePlatform:;
- (void)setToSingleRoom:;
- (void)setUsePre:;
- (id)sharePlatform;
- (BOOL)toSingleRoom;
- (BOOL)usePre;
- (void).cxx_destruct;
- (void)setSeekTime:;
- (id)seekTime;
- (id)collectionId;
- (void)setCollectionId:;
- (id)cameraID;
@end
