@interface IESLiveSaaSAvatarRotatingCircleView : UIView
@property (nonatomic) double angle;
@property (nonatomic) double radian;
@property (nonatomic) double arcPeriod;
@property (nonatomic) double realArcPeriod;
@property (nonatomic) double circlePeriod;
@property (nonatomic) CAShapeLayer dashCircle;
@property (nonatomic) CAShapeLayer solidArc;
@property (nonatomic) CADisplayLink displayLink;
@property (nonatomic) double lastTimestamp;
@property (nonatomic) double timeOffsetCircle;
@property (nonatomic) double timeOffsetArc;
@property (nonatomic) BOOL animating;
@property (nonatomic) UIColor circleColor;
@property (nonatomic) NSArray dashPattern;
- (id)arcPath;
- (void)setCircleColor:;
- (double)arcPeriod;
- (id)arcWithStartAngle:endAngle:;
- (id)circleColor;
- (id)circlePath;
- (double)circlePeriod;
- (id)dashCircle;
- (id)initWithFrame:angle:arcPeriod:circlePeriod:;
- (BOOL)isSamePointWithFirst:second:;
- (double)radTime:;
- (double)radian;
- (double)realArcPeriod;
- (void)setArcPeriod:;
- (void)setCirclePeriod:;
- (void)setDashCircle:;
- (void)setRadian:;
- (void)setRealArcPeriod:;
- (void)setSolidArc:;
- (void)setTimeOffsetArc:;
- (void)setTimeOffsetCircle:;
- (id)solidArc;
- (void)startOrStop:;
- (double)timeOffsetArc;
- (double)timeOffsetCircle;
- (id)displayLink;
- (void)setAnimating:;
- (void)setDisplayLink:;
- (BOOL)isAnimating;
- (void)setLastTimestamp:;
- (void)handleDisplayLink:;
- (void)startAnimating;
- (void)stopAnimating;
- (void).cxx_destruct;
- (double)lastTimestamp;
- (double)angle;
- (void)setAngle:;
- (double)normalize:;
- (id)dashPattern;
- (void)setDashPattern:;
@end
