@interface IESLiveSaaSAuthCouponAlertViewModel : IESLiveSaaSAuthAlertViewModel
@property (nonatomic) NSString couponAuthAlertTitleString;
@property (nonatomic) NSString couponAuthAlertContentString;
@property (nonatomic) NSString couponAuthAlertButtonString;
@property (nonatomic) NSString couponScene;
@property (nonatomic) NSString couponValidTime;
@property (nonatomic) NSString couponUsesLimitAmount;
@property (nonatomic) NSString couponTitleString;
@property (nonatomic) IESLiveSaaSCouponPopupModel popupModel;
@property (nonatomic) IESLiveSaaSCouponPopupCouponModel couponModel;
@property (nonatomic) Q couponAmount;
@property (nonatomic) Q couponThreshold;
@property (nonatomic) q authType;
@property (nonatomic) BOOL enableAuthNewStyle;
@property (nonatomic) IESLiveSaaSCouponPopupRoomContext roomContext;
- (unsigned long long)couponThreshold;
- (id)couponValidTime;
- (void)setCouponAuthAlertButtonString:;
- (void)setCouponModel:;
- (void)setCouponScene:;
- (void)setRoomContext:;
- (void)clickCancel;
- (void)clickLogin;
- (unsigned long long)couponAmount;
- (id)couponAuthAlertButtonString;
- (id)couponAuthAlertContentString;
- (id)couponAuthAlertTitleString;
- (id)couponModel;
- (id)couponScene;
- (id)couponTitleString;
- (id)couponUsesLimitAmount;
- (BOOL)enableAuthNewStyle;
- (id)formatCouponAmountStr;
- (id)formatCouponThresholdStr;
- (id)formatFloat:;
- (id)initWithCouponPopupModel:;
- (BOOL)isDiscountCoupon;
- (void)setCouponAuthAlertContentString:;
- (void)setCouponAuthAlertTitleString:;
- (void)setCouponTitleString:;
- (void)setCouponUsesLimitAmount:;
- (void)setCouponValidTime:;
- (void)setEnableAuthNewStyle:;
- (void)trackCancel;
- (void)trackLoginButtonClick;
- (void)trackPopupClick:;
- (void)trackPopupShow;
- (id)userAuthType;
- (void)setAuthType:;
- (long long)authType;
- (void).cxx_destruct;
- (id)roomContext;
- (id)popupModel;
- (void)setPopupModel:;
@end
