@interface IESLiveMultiLinkerInstance : NSObject
@property (nonatomic) IESLiveInteractiveMediaService mediaService;
@property (nonatomic) IESLiveMultiLinkerLocalLayout localLayout;
@property (nonatomic) IESLiveMultiLinkerStreamLayout streamLayout;
@property (nonatomic) <IESLiveMultiLinkerProvider> provider;
@property (nonatomic) HTSLiveInteractiveAPIV2 interactiveAPI;
@property (nonatomic) <IESLiveCompoundSubscription> disposable;
@property (nonatomic) IESLiveCountTimer timeoutTimer;
@property (nonatomic) IESLiveCountTimer multiChannelBackupTimer;
@property (nonatomic) IESLiveCountTimer interactDurationTimer;
@property (nonatomic) IESLiveCountTimer randomTeamMockGridsTimer;
@property (nonatomic) IESLiveCountTimer lessFrameCheckTimer;
@property (nonatomic) IESLiveCountTimer moreFrameNotInDataTimer;
@property (nonatomic) IESLiveCountTimer moreFrameNotLinkedTimer;
@property (nonatomic) IESLiveMultiLinkerModel mLinkerModel;
@property (nonatomic) q buildSource;
@property (nonatomic) <IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) q interactStartTime;
@property (nonatomic) double timeBeforeJoinChannel;
@property (nonatomic) NSMutableArray linkedUsersWhenJoin;
@property (nonatomic) NSString currentBusinessId;
@property (nonatomic) NSString currentQId;
@property (nonatomic) NSString operatorId;
@property (nonatomic) IESLiveRevenueInteractLynxComponentManager lynxComponentManager;
@property (nonatomic) IESLiveMultiLinkerStreamBackgroundManager backgroundManager;
@property (nonatomic) UIImageView backgroundImage;
@property (nonatomic) BOOL didJoinChannel;
@property (nonatomic) BOOL hasCompletedPrepare;
@property (nonatomic) BOOL didLoadInteractiveService;
@property (nonatomic) BOOL needCheckSubscribeStatus;
@property (nonatomic) BOOL isChorusOpenInMultilinker;
@property (nonatomic) BOOL hasClosedBigParty;
@property (nonatomic) UIButton singleViewHint;
@property (nonatomic) UIButton singleViewSwitchBtn;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)checkMoreFrame:;
- (void)interactiveMediaServiceWillEnd:;
- (void)onReceivedInteractScoreMessage:;
- (void)setLocalLayout:;
- (void)stopMultiChannelInfoBackupTimer;
- (void)switchMediaParamsWithUserCount:;
- (void)handleNativeComponents:byEvent:;
- (void)loadLocalLayout;
- (void)onRTCStatusInit;
- (void)p_switchMixType;
- (void)setBuildSource:;
- (void)addBackgroundImage;
- (void)addConnectionOverTrackParamsFromPlay:;
- (id)backgroundManager;
- (void)bindAction;
- (long long)buildSource;
- (void)businessJoinChannel;
- (void)calculateSingleViewOptimizationCropRegionForUILayout:completion:;
- (void)changeIntoMultiLinkerMultiMatchIfNeed;
- (void)changeRandomTeamSceneIfTeamChange;
- (id)checkConnectSuccess:;
- (void)checkIfNeedMoreTimerOnInteracting;
- (void)checkMultiChannelInfoWithSource:;
- (void)checkShowLastResultIfNeeded;
- (void)checkUnexpectLessPushWithFirstFrameID:;
- (BOOL)checkVideoStatusAndUpdateAudioVolume:;
- (void)cleanOtherSceneForBusinessReady:;
- (void)cleanOtherSceneForRTCReady:;
- (void)closeChorus;
- (id)currentBusinessId;
- (id)currentQId;
- (void)didChangePerfWarningLevelTo:;
- (void)didChorusEnd:;
- (void)didChorusStarted:;
- (BOOL)didJoinChannel;
- (BOOL)didLoadInteractiveService;
- (void)didRevenueInteractPlayEnd;
- (void)didRevenueInteractPlayStart:;
- (void)didSetAttachingDIContext;
- (void)disableSingleView;
- (id)disposable;
- (BOOL)enableCheckUnexpectLessPush;
- (BOOL)enableCheckUnexpectMorePush;
- (void)enableSingleView;
- (BOOL)enableSingleViewOptimizationDebug;
- (id)extraMonitorDict:connectModel:;
- (BOOL)hasClosedBigParty;
- (BOOL)hasCompletedPrepare;
- (id)initWithContext:mediaService:;
- (id)interactDurationTimer;
- (long long)interactStartTime;
- (id)interactiveAPI;
- (void)interactiveMediaService:didOfflineOfUid:sessions:reason:;
- (void)interactiveMediaService:firstFrameRenderCallback:;
- (void)interactiveMediaService:firstRemoteVideoWithLinkmicUid:;
- (void)interactiveMediaService:onUserJoined:extraInfo:;
- (void)interactiveMediaService:receivesError:;
- (void)interactiveMediaServiceDidStart:;
- (BOOL)isChorusOpenInMultilinker;
- (BOOL)isMultiLinkmicAutoMatchForMatchType:;
- (BOOL)isSameBattleConfig:;
- (BOOL)isStatusRefactor;
- (BOOL)isValidModeInfo:;
- (void)joinChannelSuccess;
- (id)layoutFramesOfLinkdersCount:;
- (id)leaveToastStringInPlay:;
- (id)lessFrameCheckTimer;
- (id)linkedUsersWhenJoin;
- (void)loadContainerView;
- (void)loadInteractiveLayout;
- (void)loadMediaService;
- (void)loadStreamLayout;
- (id)localLayout;
- (id)lynxComponentManager;
- (id)mLinkerModel;
- (void)monitorJoinChannelResponse:;
- (id)moreFrameNotInDataTimer;
- (id)moreFrameNotLinkedTimer;
- (id)multiChannelBackupTimer;
- (void)multiLinkerUserService:didInteractiveListUpdated:;
- (void)multiLinkerUserService:didListDataUpdated:;
- (void)multiLinkerUserService:user:useBackupStream:;
- (void)muteRemoteStreamIfNeeded;
- (BOOL)needCheckSubscribeStatus;
- (BOOL)needReportConnectionSuccess;
- (void)onInteractionEnd;
- (void)onInteractionStarted;
- (void)onLayoutModelChanged;
- (void)onRTCInfoModelChanged;
- (void)onRTCStatusConnecting;
- (void)onRTCStatusJoinedChannel;
- (void)onRTCStatusMixStream;
- (void)onRTCStatusStart;
- (void)onReceivedLinkLeaveMessage:;
- (void)onReceivedLinkMultiBattleTeamChangedMessage:;
- (void)onReceivedLinkUpdateAnchorInteractConfigMessage:;
- (void)onReceivedLinkUpdateAnchorInteractLayoutMessage:;
- (void)onReceivedMediaInfoChangedMessage:;
- (void)onRegionCountChanged;
- (void)onStatusBusinessJoinedChannel;
- (void)onStatusBusinessPrepare;
- (void)onStatusInteracting;
- (void)p_showRenderArea;
- (id)randomTeamMockGridsTimer;
- (void)resumeLayout;
- (id)roomModel;
- (void)sendMultiLinkerEvent:withParams:;
- (void)setBackgroundManager:;
- (void)setCameraCornerHidden:;
- (void)setCurrentBusinessId:;
- (void)setCurrentQId:;
- (void)setDidJoinChannel:;
- (void)setDidLoadInteractiveService:;
- (void)setDisposable:;
- (void)setHasClosedBigParty:;
- (void)setHasCompletedPrepare:;
- (void)setInteractDurationTimer:;
- (void)setInteractStartTime:;
- (void)setInteractiveAPI:;
- (void)setIsChorusOpenInMultilinker:;
- (void)setLessFrameCheckTimer:;
- (void)setLinkedUsersWhenJoin:;
- (void)setLynxComponentManager:;
- (void)setMLinkerModel:;
- (void)setMoreFrameNotInDataTimer:;
- (void)setMoreFrameNotLinkedTimer:;
- (void)setMultiChannelBackupTimer:;
- (void)setNeedCheckSubscribeStatus:;
- (void)setOperatorId:;
- (void)setRandomTeamMockGridsTimer:;
- (void)setRoomModel:;
- (void)setSingleViewHint:;
- (void)setSingleViewSwitchBtn:;
- (void)setStreamLayout:;
- (void)setTimeBeforeJoinChannel:;
- (void)setupConnectModel;
- (void)setupReadyMadeMediaService:;
- (void)setupSingleViewEnv;
- (BOOL)shouldCheckUnexpectMorePush;
- (id)singleViewHint;
- (id)singleViewSwitchBtn;
- (id)sortedLinkedUsers;
- (void)startConnectTimer;
- (void)startInteractDurationTimer;
- (void)startLessFrameCheckTimer;
- (void)startMoreFrameNotInDataTimer;
- (void)startMoreFrameNotLinkedTimer;
- (void)startMultiChannelInfoBackupTimerIfEnable;
- (void)startRandomTeamMockGridsTimer;
- (void)stopInteractDurationTimer;
- (id)streamLayout;
- (double)timeBeforeJoinChannel;
- (void)trackChorusEnd:isMultilinkerEnd:isActiveClose:;
- (void)trackConnectionSuccess;
- (void)trackLayoutShowWithOperateId:isManual:;
- (id)trackParamsForConnectionOver;
- (void)unmuteLinkedUsersIfNeeded;
- (void)updateBuildSource;
- (void)updateInteractScore:;
- (void)updateInteractScoreWithAnchorInfoDict:;
- (void)updateLastResultShow:;
- (void)updateMediaParamsWithRTCRegionCount;
- (void)updateSingleViewConfigIfNeeded;
- (void)updateSubscribeStatusFor:useBackupStream:;
- (void)willChorusEnd:;
- (void)willChorusStart:;
- (void)willRevenueInteractPlayEnd:;
- (void)willRevenueInteractPlayStart;
- (void)setProvider:;
- (void)dealloc;
- (void)setBackgroundImage:;
- (id)backgroundImage;
- (id)provider;
- (void).cxx_destruct;
- (id)timeoutTimer;
- (void)setTimeoutTimer:;
- (id)mediaService;
- (void)setMediaService:;
- (id)operatorId;
@end
