@interface IESLiveMessageListActionSheetFragment : IESLiveRoomComponent
@property (nonatomic) NSMutableDictionary items;
@property (nonatomic) NSMutableArray showItems;
@property (nonatomic) NSMutableArray syncUpdateItems;
@property (nonatomic) BOOL messageOperateEnable;
@property (nonatomic) BOOL commentReplyLinkEnable;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)showActionSheetWithNode:atCell:;
- (id)syncUpdateItems;
- (void)componentCreate;
- (void)addActionSheetItem:;
- (void)addItemType:withNode:toSheet:;
- (void)addItemsToSheet:withNode:;
- (void)addOpenUserCardActionSheetItem;
- (void)addReplyActionSheetItem;
- (BOOL)commentReplyLinkEnable;
- (void)componentBindService;
- (void)componentMount;
- (void)directActionWithNode:;
- (BOOL)messageOperateEnable;
- (void)removeActionSheetItemWithType:;
- (void)replyComment:;
- (void)setCommentReplyLinkEnable:;
- (void)setMessageOperateEnable:;
- (void)setShowItems:;
- (void)setSyncUpdateItems:;
- (void)showActionSheetVCWithNode:;
- (id)showItems;
- (void)trackClickCommentWithNode:onActionSheet:;
- (void)updateShowItemsWithNode:;
- (id)items;
- (void)setItems:;
- (void).cxx_destruct;
+ (BOOL)isMixed;
+ (BOOL)componentShouldActive:;
@end
