@interface IESLivePosterMakerPanel : UIView
@property (nonatomic) IESLiveVSPosterStore store;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIButton closeBtn;
@property (nonatomic) UIView authInfoView;
@property (nonatomic) IESLiveNormalActionView leftAction;
@property (nonatomic) IESLiveNormalActionView rightAction;
@property (nonatomic) IESLiveWebpLoadingView loadingView;
@property (nonatomic) UIView templatesView;
@property (nonatomic) UIView preView;
@property (nonatomic) UICollectionView templatesCollectionView;
@property (nonatomic) NSIndexPath selectedIndex;
@property (nonatomic) BOOL hasSet;
@property (nonatomic) UILabel authLabel;
@property (nonatomic) IESLiveImageView authIcon;
@property (nonatomic) IESLiveImageView posterPreView;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} originFrame;
@property (nonatomic) Q status;
@property (nonatomic) @? closeBlock;
@property (nonatomic) @? leftBlock;
@property (nonatomic) @? rightBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_autoSelectCellWithScrollView:;
- (id)preView;
- (void)setOriginFrame:;
- (id)authIcon;
- (id)authInfoView;
- (id)authLabel;
- (id)closeBlock;
- (id)closeBtn;
- (void)closePanel;
- (id)createAuthInfoView;
- (void)layoutBGView;
- (void)layoutPreviewStatus;
- (void)layoutTemplateSelectStatus;
- (id)leftAction;
- (id)leftBlock;
- (id)originFrame;
- (id)posterPreView;
- (id)rightBlock;
- (void)setAuthIcon:;
- (void)setAuthInfoView:;
- (void)setAuthLabel:;
- (void)setCloseBlock:;
- (void)setCloseBtn:;
- (void)setLeftAction:;
- (void)setLeftBlock:;
- (void)setPosterPreView:;
- (void)setPreView:;
- (void)setRightBlock:;
- (void)setTemplatesCollectionView:;
- (void)setTemplatesView:;
- (void)setupSubViews;
- (void)showPreView;
- (void)tapPreView;
- (id)templatesCollectionView;
- (id)templatesView;
- (void)updateAuthorName:;
- (void)updatePreViewImage;
- (void)updateWithStatus;
- (void)scrollViewDidEndDecelerating:;
- (void)setStatus:;
- (void)collectionView:willDisplayCell:forItemAtIndexPath:;
- (void)setStore:;
- (id)initWithStore:;
- (void)setTitleLabel:;
- (long long)collectionView:numberOfItemsInSection:;
- (id)selectedIndex;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)scrollViewDidScroll:;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)scrollViewDidEndDragging:willDecelerate:;
- (void).cxx_destruct;
- (unsigned long long)status;
- (void)scrollViewDidEndScrollingAnimation:;
- (id)store;
- (id)titleLabel;
- (void)setSelectedIndex:;
- (id)cellSize;
- (BOOL)hasSet;
- (void)setHasSet:;
- (id)loadingView;
- (void)setLoadingView:;
- (id)rightAction;
- (void)setRightAction:;
@end
