@interface IESLiveIMPaaSWorker : NSObject
@property (nonatomic) <IESLiveDataSyncService> wrdsManager;
@property (nonatomic) <IESLiveIMMessageReciever> messageFirstReceiver;
@property (nonatomic) q bizUniqueToken;
@property (nonatomic) double totalDecodedTS;
@property (nonatomic) q totalPacketCount;
@property (nonatomic) <IESLiveIMPaaSClient> client;
@property (nonatomic) <IESLiveIMMessageDispatchProvider> dispatcher;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setWrdsManager:;
- (long long)bizUniqueToken;
- (void)collectDataDecodingTime:;
- (void)didRecievePacket:;
- (id)initWith:wrdsManager:dispatcher:;
- (void)logEvent:params:;
- (id)messageFirstReceiver;
- (void)registerWith:;
- (void)setBizUniqueToken:;
- (void)setMessageFirstReceiver:;
- (void)setTotalDecodedTS:;
- (void)setTotalPacketCount:;
- (void)startDispatch;
- (void)startReplay;
- (void)stopDispatch;
- (void)stopReplay;
- (double)totalDecodedTS;
- (long long)totalPacketCount;
- (void)trackDataDecodingTime;
- (void)trackEvent:params:;
- (id)wrdsManager;
- (void)setDispatcher:;
- (id)dispatcher;
- (void)start;
- (void)stop;
- (void)setClient:;
- (void)reconnect;
- (id)client;
- (void).cxx_destruct;
- (id)initWith:;
- (void)unregisterWith:;
@end
