@interface IESLivePublicScreenChatAuthAttachment : NSObject
@property (nonatomic) q filterTimesWhenEnterRoomChatClosed;
@property (nonatomic) NSMutableString filterMessagesIdWhenEnterRoomChatClosed;
@property (nonatomic) BOOL didCommittedData;
@property (nonatomic) BOOL chatEnable;
@property (nonatomic) BOOL didReceivedMsg;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) IESLivePublicScreenView publicScreenView;
@property (nonatomic) IESLivePublicScreenContext publicScreenContext;
@property (nonatomic) HTSEventContext trackContext;
@property (nonatomic) @? didAttach;
@property (nonatomic) @? didDetach;
- (id)abilityProtocol;
- (void)chatAuthEnable:;
- (BOOL)canShowWhenChatClosed:;
- (BOOL)chatEnable;
- (void)checkMessagelistHiddenStatus;
- (void)delayHideMessageListView;
- (id)didAttach;
- (BOOL)didCommittedData;
- (id)didDetach;
- (BOOL)didReceivedMsg;
- (void)fakeRoomMessageWhenRoomAuthChatChanged:;
- (void)filterMessageNodesIfRoomAuthChatClosed:;
- (id)filterMessagesIdWhenEnterRoomChatClosed;
- (long long)filterTimesWhenEnterRoomChatClosed;
- (void)handleRoomVerifyMessage:;
- (id)publicScreenContext;
- (void)publicScreenMessageProcessed:;
- (id)publicScreenView;
- (void)setChatEnable:;
- (void)setDidAttach:;
- (void)setDidCommittedData:;
- (void)setDidDetach:;
- (void)setDidReceivedMsg:;
- (void)setFilterMessagesIdWhenEnterRoomChatClosed:;
- (void)setFilterTimesWhenEnterRoomChatClosed:;
- (void)setPublicScreenContext:;
- (void)setPublicScreenView:;
- (void)setTrackContext:;
- (BOOL)shouldActive;
- (id)trackContext;
- (void)detach;
- (void)dealloc;
- (void)attach;
- (id)type;
- (void).cxx_destruct;
@end
