@interface IESLiveSaaSWKWebView : IESWKWebView
@property (nonatomic) IESLiveSaaSWKWebViewDelegateWrapper delegateWrapper;
@property (nonatomic) NSMutableSet bridgeHandlers;
@property (nonatomic) <IESLiveSaaSWebViewService> webViewService;
@property (nonatomic) <IESLiveSaaSDebugService> debugService;
@property (nonatomic) UIScreenEdgePanGestureRecognizer backNavigationGesture;
@property (nonatomic) UIScreenEdgePanGestureRecognizer forwardNavigationGesture;
@property (nonatomic) BOOL allowBackNavigationGesture;
@property (nonatomic) BOOL allowForwardNavigationGesture;
@property (nonatomic) BOOL enableBackGesture;
@property (nonatomic) <IESLivePiperProtocol> liveBridge;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL canGoBack;
@property (nonatomic) BOOL canGoForward;
@property (nonatomic) BOOL loading;
@property (nonatomic) UIScrollView scrollView;
@property (nonatomic) NSString containerID;
@property (nonatomic) UIView rawView;
@property (nonatomic) PuzzleContext context;
@property (nonatomic) <PuzzleHybridStateCenterProtocol> stateCenter;
@property (nonatomic) Q kernalType;
@property (nonatomic) <IESHYHybridViewLifecycleProtocol> lifecycleDelegate;
@property (nonatomic) NSString liveBusiness;
@property (nonatomic) NSDictionary initialMethodsMap;
@property (nonatomic) BDXThreadSafeDictionary lazyCreateMethodsMap;
@property (nonatomic) <IESLiveHybridContainerDelegate> liveHybridContainerDelegate;
- (id)rawView;
- (void)setLiveHybridContainerDelegate:;
- (void)addPiperHandler:;
- (void)addXBridgeMethods;
- (BOOL)allowBackNavigationGesture;
- (BOOL)allowForwardNavigationGesture;
- (id)backNavigationGesture;
- (id)bridgeHandlers;
- (id)currentRequestURL;
- (id)currentWebViewScene;
- (id)debugService;
- (BOOL)enableBackGesture;
- (id)forwardNavigationGesture;
- (id)ies_namespace;
- (id)initWithFrame:bridgeClass:;
- (id)initWithFrame:bridgeClass:settings:;
- (unsigned long long)kernalType;
- (id)lifecycleDelegate;
- (id)liveBridge;
- (id)liveBusiness;
- (id)liveHybridContainerDelegate;
- (void)panScreenEdgeLeft;
- (void)secureGoBackWithReachEndBlock:;
- (void)sendEvent:params:;
- (void)setAllowBackNavigationGesture:;
- (void)setAllowForwardNavigationGesture:;
- (void)setBackNavigationGesture:;
- (void)setBridgeHandlers:;
- (void)setDebugService:;
- (void)setEnableBackGesture:;
- (void)setForwardNavigationGesture:;
- (void)setLifecycleDelegate:;
- (void)setLiveBridge:;
- (void)setLiveBusiness:;
- (void)setTimeStampOfWebPageWithDict:;
- (void)setWebViewService:;
- (void)setupDelegateWrapper:;
- (void)triggerLayout;
- (id)webViewService;
- (void)setDelegateWrapper:;
- (void)dealloc;
- (id)context;
- (void)addGestureRecognizer:;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (BOOL)gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:;
- (id)delegateWrapper;
- (id)initWithFrame:;
- (void)updateData:;
- (void).cxx_destruct;
- (void)setContext:;
- (BOOL)gestureRecognizer:shouldRequireFailureOfGestureRecognizer:;
- (void)loadData;
- (void)loadWithURL:;
- (void)scaleToFit;
- (void)loadURLRequest:;
@end
