@interface IESLiveDanmakuVariousViewModel : NSObject
@property (nonatomic) NSArray avatarURLs;
@property (nonatomic) UIImage avatarImage;
@property (nonatomic) BOOL showAvatar;
@property (nonatomic) double avatarLeadingOffset;
@property (nonatomic) double officialAvatarSize;
@property (nonatomic) {CGSize=dd} avatarSize;
@property (nonatomic) double avatarBadgeSize;
@property (nonatomic) BOOL showAvatarBadge;
@property (nonatomic) HTSLiveImage avatarBadge;
@property (nonatomic) NSArray backgroundColors;
@property (nonatomic) UIImage backgroundSkin;
@property (nonatomic) BOOL showContentBorder;
@property (nonatomic) NSArray borderColors;
@property (nonatomic) NSAttributedString content;
@property (nonatomic) NSArray contentTextColors;
@property (nonatomic) NSArray contentOuterStrokeColors;
@property (nonatomic) double outerStrokeWidth;
@property (nonatomic) double horizontalSpacing;
@property (nonatomic) HTSLiveImage badgeIcon;
@property (nonatomic) q atmosphereCols;
@property (nonatomic) NSAttributedString atmosphereContent;
@property (nonatomic) double atmosphereSpacingMax;
@property (nonatomic) double atmosphereSpacingMin;
@property (nonatomic) double atmosphereContentHeight;
@property (nonatomic) double mainContentHeight;
@property (nonatomic) double danmakuHeight;
@property (nonatomic) BOOL pinModeRequired;
- (double)avatarBadgeSize;
- (BOOL)pinModeRequired;
- (void)setAvatarBadge:;
- (BOOL)showAvatarBadge;
- (long long)atmosphereCols;
- (id)atmosphereContent;
- (double)atmosphereContentHeight;
- (double)atmosphereSpacingMax;
- (double)atmosphereSpacingMin;
- (id)avatarBadge;
- (double)avatarLeadingOffset;
- (id)avatarURLs;
- (id)backgroundSkin;
- (id)badgeIcon;
- (id)borderColors;
- (id)contentOuterStrokeColors;
- (id)contentTextColors;
- (double)danmakuHeight;
- (double)mainContentHeight;
- (double)officialAvatarSize;
- (double)outerStrokeWidth;
- (void)setAtmosphereCols:;
- (void)setAtmosphereContent:;
- (void)setAtmosphereContentHeight:;
- (void)setAtmosphereSpacingMax:;
- (void)setAtmosphereSpacingMin:;
- (void)setAvatarBadgeSize:;
- (void)setAvatarLeadingOffset:;
- (void)setAvatarURLs:;
- (void)setBackgroundSkin:;
- (void)setBadgeIcon:;
- (void)setBorderColors:;
- (void)setContentOuterStrokeColors:;
- (void)setContentTextColors:;
- (void)setDanmakuHeight:;
- (void)setMainContentHeight:;
- (void)setOfficialAvatarSize:;
- (void)setOuterStrokeWidth:;
- (void)setPinModeRequired:;
- (void)setShowAvatar:;
- (void)setShowAvatarBadge:;
- (void)setShowContentBorder:;
- (BOOL)showAvatar;
- (BOOL)showContentBorder;
- (id)content;
- (void)setContent:;
- (id)backgroundColors;
- (void).cxx_destruct;
- (void)setAvatarImage:;
- (id)avatarImage;
- (id)avatarSize;
- (void)setAvatarSize:;
- (void)setBackgroundColors:;
- (double)horizontalSpacing;
- (void)setHorizontalSpacing:;
@end
