@interface IESLiveSaaSVideoPlayer : NSObject
@property (nonatomic) IESLiveVideoPlayerController player;
@property (nonatomic) UIView view;
@property (nonatomic) Q loadState;
@property (nonatomic) Q playbackState;
@property (nonatomic) double progress;
@property (nonatomic) double cacheProgress;
@property (nonatomic) double duration;
@property (nonatomic) <IESLiveSaaSVideoPlayerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString vid;
- (void)seekToProgress:;
- (id)vid;
- (void)_loadPlayerIfNeed;
- (double)cacheProgress;
- (void)changePlayerContentFrame;
- (void)didSetAttachingDIContext;
- (void)playerController:loadStateDidChange:;
- (void)playerController:playbackStateDidChange:;
- (void)playerController:playerDidFinishError:;
- (void)playerController:updateCacheProgress:;
- (void)playerController:updateProgress:duration:;
- (void)playerController:userStop:;
- (void)reloadVideoId:;
- (void)renderOnView:;
- (void)setCacheProgress:;
- (void)videoReadyToDisPlayOfPlayerController:;
- (id)init;
- (unsigned long long)playbackState;
- (unsigned long long)loadState;
- (void)setPlaybackState:;
- (void)play;
- (void)hide;
- (void)setStartTime:;
- (void)setDelegate:;
- (void)setProgress:;
- (void)commonInit;
- (void)stop;
- (void)prepareForReuse;
- (void)close;
- (void)show;
- (void)setDuration:;
- (double)progress;
- (id)view;
- (id)player;
- (id)delegate;
- (void).cxx_destruct;
- (void)setPlayer:;
- (void)pause;
- (void)setView:;
- (double)duration;
- (id)videoSize;
- (void)setLoop:;
- (void)setLoadState:;
@end
