@interface IESLiveUserCardPOIDetailView : UIView
@property (nonatomic) IESLiveUserProfile targetUser;
@property (nonatomic) UIView backgroundContainer;
@property (nonatomic) UIImageView locationImageView;
@property (nonatomic) UIImageView actionIconView;
@property (nonatomic) UILabel contentLabel;
@property (nonatomic) NSNumber scene;
@property (nonatomic) BOOL isShowWhite;
@property (nonatomic) NSString cityInfo;
@property (nonatomic) IESLiveUserCardStore store;
@property (nonatomic) NSString detailInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setIsShowWhite:;
- (id)actionIconView;
- (id)cityInfo;
- (void)configWithScene:;
- (void)configWithStore:;
- (void)configWithTag:isShowWhite:;
- (void)configWithUserModel:;
- (id)detailInfo;
- (BOOL)isShowWhite;
- (void)onTapped:;
- (void)setActionIconView:;
- (void)setCityInfo:;
- (void)setDetailInfo:;
- (void)setTargetUser:;
- (void)trackPOILabelShow;
- (id)init;
- (void)setScene:;
- (void)setStore:;
- (id)scene;
- (id)backgroundContainer;
- (void)setup;
- (void).cxx_destruct;
- (id)store;
- (void)setBackgroundContainer:;
- (BOOL)shouldShow;
- (id)contentLabel;
- (void)setContentLabel:;
- (id)locationImageView;
- (void)setLocationImageView:;
- (id)targetUser;
@end
