@interface IESLiveSaaSLayoutBaseContainer : NSObject
@property (nonatomic) IESLiveSaaSLayoutContainerItem item;
@property (nonatomic) IESLiveSaaSStackView view;
@property (nonatomic) IESLiveSaaSLayoutRulesController rule;
@property (nonatomic) NSMutableArray subContainers;
@property (nonatomic) NSString viewType;
@property (nonatomic) NSString containerType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)addContainer:insets:size:;
- (void)addCustomContainer:;
- (void)addPluginview:;
- (void)addSubview:viewType:;
- (void)addSubview:viewType:insets:;
- (void)addSubview:viewType:insets:size:;
- (void)addSubview:viewType:size:;
- (BOOL)canInsertType:;
- (void)containerOrientationChanged:;
- (void)didAutoRoateToOrientation:;
- (void)didMoveToParentContainer:;
- (id)itemForView:viewType:size:insets:;
- (id)ruleForType:;
- (void)setSubContainers:;
- (id)subContainers;
- (id)viewForType:;
- (void)willMoveToParentContainer:;
- (id)rule;
- (id)item;
- (id)init;
- (id)viewType;
- (id)view;
- (void)setItem:;
- (void).cxx_destruct;
- (void)loadView;
- (void)setRule:;
- (void)setView:;
- (void)viewDidLoad;
- (void)addContainer:;
- (void)removeContainer:;
- (id)itemForType:;
- (void)setViewType:;
- (BOOL)containsType:;
- (void)removeType:;
@end
