@interface IESLivePKRecommendTabView : UIView
@property (nonatomic) IESLivePKNormalPanelViewModel viewModel;
@property (nonatomic) UICollectionView tabCollectionView;
@property (nonatomic) UIScrollView tabScrollView;
@property (nonatomic) IESLivePKRecommendPanelView recommendPanelView;
@property (nonatomic) IESLivePKFollowPanelView followPanelView;
@property (nonatomic) NSMutableDictionary flexActivityViews;
@property (nonatomic) NSMutableArray tabViews;
@property (nonatomic) NSMutableArray subTabs;
@property (nonatomic) NSMutableDictionary unloadedFlexActivityIds;
@property (nonatomic) NSMutableDictionary loadedFlexActivityIds;
@property (nonatomic) UIView sliderView;
@property (nonatomic) BOOL hasFlexActivityTab;
@property (nonatomic) BOOL isNotTap;
@property (nonatomic) BOOL isDragging;
@property (nonatomic) BOOL needTrackDefault;
@property (nonatomic) q tabCount;
@property (nonatomic) q currentTab;
@property (nonatomic) q recommendTabIdx;
@property (nonatomic) q followTabIdx;
@property (nonatomic) {CGPoint=dd} sliderOriginPoint;
@property (nonatomic) <IESLivePKRecommendTabViewDelegate> recommendTabViewDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (long long)recommendTabIdx;
- (void)selectFollowTab;
- (BOOL)showFollowPanel;
- (id)followPanelView;
- (id)subTabs;
- (void)addTabViews;
- (BOOL)didSubTabLoaded:;
- (void)didUpdatePanelScrollViewOffset:deltaY:;
- (id)flexActivityViews;
- (long long)followTabIdx;
- (BOOL)hasFlexActivityTab;
- (id)initWithDIContext:viewModel:;
- (BOOL)isListOpt;
- (BOOL)isNotTap;
- (id)loadedFlexActivityIds;
- (BOOL)needTrackDefault;
- (void)panelView:registerFlexActivityWithID:;
- (id)recommendPanelView;
- (id)recommendTabViewDelegate;
- (void)reloadDatas;
- (void)selectRecommendTab;
- (void)selectTabWithIdx:;
- (void)setFlexActivityViews:;
- (void)setFollowPanelView:;
- (void)setFollowTabIdx:;
- (void)setHasFlexActivityTab:;
- (void)setIsNotTap:;
- (void)setLoadedFlexActivityIds:;
- (void)setNeedTrackDefault:;
- (void)setRecommendPanelView:;
- (void)setRecommendTabIdx:;
- (void)setRecommendTabViewDelegate:;
- (void)setSliderOriginPoint:;
- (void)setSubTabs:;
- (void)setTabCollectionView:;
- (void)setTabScrollView:;
- (void)setTabViews:;
- (void)setUnloadedFlexActivityIds:;
- (void)setupFlexActivityTab;
- (void)setupSubview;
- (id)sliderOriginPoint;
- (id)tabScrollView;
- (id)tabViews;
- (void)trackFlexActivityPanelCells:;
- (void)trackPKSubTabShow:;
- (id)unloadedFlexActivityIds;
- (void)updateFlexActivityPanelWithId:;
- (void)updateSubTabLayout;
- (void)willPanelScrollViewBeginDragging;
- (void)willPanelScrollViewEndDragging;
- (id)collectionView:layout:sizeForItemAtIndexPath:;
- (void)scrollViewDidEndDecelerating:;
- (id)viewModel;
- (void)layoutSubviews;
- (long long)collectionView:numberOfItemsInSection:;
- (id)tabCollectionView;
- (void)setSliderView:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)scrollViewDidScroll:;
- (id)sliderView;
- (void)collectionView:didSelectItemAtIndexPath:;
- (void)scrollViewWillBeginDragging:;
- (void).cxx_destruct;
- (long long)numberOfSectionsInCollectionView:;
- (BOOL)isDragging;
- (void)setViewModel:;
- (void)setIsDragging:;
- (long long)currentTab;
- (void)setCurrentTab:;
- (long long)tabCount;
- (void)setTabCount:;
@end
