@interface IESLiveListView : UIView
@property (nonatomic) UITableView tableView;
@property (nonatomic) IESLiveEmptyView emptyView;
@property (nonatomic) IESLiveWebpLoadingView loadingIndicator;
@property (nonatomic) NSArray sectionArray;
@property (nonatomic) IESLiveEmptyViewConfig emptyViewConfig;
@property (nonatomic) UIColor baseColor;
@property (nonatomic) double lastContentOffsetY;
@property (nonatomic) <IESLiveListViewDelegate> delegate;
@property (nonatomic) BOOL isLoading;
@property (nonatomic) BOOL isFavoriteButtonHidden;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) PlaylistTab category;
@property (nonatomic) NSString identifiyTitle;
@property (nonatomic) <UIScrollViewDelegate> scrollDelegate;
@property (nonatomic) BOOL redundantReload;
@property (nonatomic) BOOL visibleCellIndexPathNoUpdatedAfterFetchFlag;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)emptyViewConfig;
- (BOOL)redundantReload;
- (void)addLoadMoreBlock:;
- (void)addRefreshBlock:;
- (id)identifiyTitle;
- (BOOL)isFavoriteButtonHidden;
- (double)lastContentOffsetY;
- (void)loadDataWithSections:;
- (void)loadMoreDone:;
- (id)sectionArray;
- (void)setEmptyViewConfig:;
- (void)setIdentifiyTitle:;
- (void)setIsFavoriteButtonHidden:;
- (void)setLastContentOffsetY:;
- (void)setRedundantReload:;
- (void)setSectionArray:;
- (void)setVisibleCellIndexPathNoUpdatedAfterFetchFlag:;
- (void)startLoading:;
- (void)updateEmptyConfig:;
- (void)updateLoadingResultStatus;
- (BOOL)visibleCellIndexPathNoUpdatedAfterFetchFlag;
- (BOOL)isLoading;
- (void)stopLoading;
- (void)startLoading;
- (void)setIsLoading:;
- (id)tableView:cellForRowAtIndexPath:;
- (void)setDelegate:;
- (void)setHasMore:;
- (void)setScrollDelegate:;
- (id)initWithFrame:style:;
- (void)scrollViewDidScroll:;
- (double)tableView:heightForRowAtIndexPath:;
- (id)tableView:viewForHeaderInSection:;
- (id)delegate;
- (void)setCategory:;
- (void).cxx_destruct;
- (BOOL)hasMore;
- (void)setTableView:;
- (void)tableView:didEndDisplayingCell:forRowAtIndexPath:;
- (double)tableView:heightForHeaderInSection:;
- (id)scrollDelegate;
- (void)scrollViewDidScrollToTop:;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (id)tableView;
- (long long)tableView:numberOfRowsInSection:;
- (id)category;
- (long long)numberOfSectionsInTableView:;
- (double)tableView:heightForFooterInSection:;
- (id)tableView:viewForFooterInSection:;
- (id)baseColor;
- (id)emptyView;
- (void)setEmptyView:;
- (id)loadingIndicator;
- (void)setLoadingIndicator:;
- (void)setBaseColor:;
- (void)cleanData;
@end
