@interface IESLiveLinkLiveRtcExtInfo : NSObject
@property (nonatomic) NSString liveRtcAppId;
@property (nonatomic) NSString liveRtcAppSign;
@property (nonatomic) NSString liveRtcToken;
@property (nonatomic) NSString liveRtcRoomId;
@property (nonatomic) NSString liveRtcUserId;
@property (nonatomic) NSString liveRtcVendorName;
@property (nonatomic) q liveRtcVendorType;
@property (nonatomic) NSString liveRtcbusinessID;
@property (nonatomic) q liveMixType;
@property (nonatomic) q liveRtcMixBitrateKbps;
@property (nonatomic) q liveRtcMixServerVideoWidth;
@property (nonatomic) q liveRtcMixServerVideoHeight;
@property (nonatomic) q liveRtcMixServerVideoFps;
@property (nonatomic) q liveRtcMixServerVideoBitRateKbps;
@property (nonatomic) q liveRtcParamMode;
@property (nonatomic) ByteRTCVideoEncoderConfig liveRtcVideoInputParam;
@property (nonatomic) ByteRTCVideoEncoderConfig liveRtcPerformanceLowVideoParam;
- (id)liveRtcPerformanceLowVideoParam;
- (void)setLiveMixType:;
- (void)setLiveRtcMixServerVideoHeight:;
- (long long)liveMixType;
- (id)liveRtcAppId;
- (id)liveRtcAppSign;
- (long long)liveRtcMixBitrateKbps;
- (long long)liveRtcMixServerVideoBitRateKbps;
- (long long)liveRtcMixServerVideoFps;
- (long long)liveRtcMixServerVideoHeight;
- (long long)liveRtcMixServerVideoWidth;
- (long long)liveRtcParamMode;
- (id)liveRtcRoomId;
- (id)liveRtcToken;
- (id)liveRtcUserId;
- (id)liveRtcVendorName;
- (long long)liveRtcVendorType;
- (id)liveRtcVideoInputParam;
- (id)liveRtcbusinessID;
- (void)setLiveRtcAppId:;
- (void)setLiveRtcAppSign:;
- (void)setLiveRtcMixBitrateKbps:;
- (void)setLiveRtcMixServerVideoBitRateKbps:;
- (void)setLiveRtcMixServerVideoFps:;
- (void)setLiveRtcMixServerVideoWidth:;
- (void)setLiveRtcParamMode:;
- (void)setLiveRtcPerformanceLowVideoParam:;
- (void)setLiveRtcRoomId:;
- (void)setLiveRtcToken:;
- (void)setLiveRtcUserId:;
- (void)setLiveRtcVendorName:;
- (void)setLiveRtcVendorType:;
- (void)setLiveRtcVideoInputParam:;
- (void)setLiveRtcbusinessID:;
- (id)init;
- (void).cxx_destruct;
@end
