@interface IESLiveAudienceInteractiveSettingPanel : IESLiveInteractionPopupViewController
@property (nonatomic) BOOL hasMasterSwitch;
@property (nonatomic) @? didUpdateMasterSwitch;
@property (nonatomic) NSArray configurations;
@property (nonatomic) NSArray sectionItems;
@property (nonatomic) NSString titleForLabel;
@property (nonatomic) HTSEventContext eventContext;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UITableView tableView;
@property (nonatomic) UIView seperatorLineView;
@property (nonatomic) UIView masterSwitchContainerView;
@property (nonatomic) UILabel masterSwitchTitleLabel;
@property (nonatomic) UILabel masterSwitchSubTitleLabel;
@property (nonatomic) UISwitch masterSwitch;
@property (nonatomic) UIView userInteractMasterSwitch;
@property (nonatomic) BOOL didTrackForGuestGift;
@property (nonatomic) double tableViewHeight;
@property (nonatomic) BOOL oddTimeToRefreshSettingPanel;
@property (nonatomic) <IESLiveAudienceInteractiveSettingsAction> actionDelegate;
@property (nonatomic) BOOL hasTrackPlayModeExposure;
@property (nonatomic) BOOL isFromPK;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} navFrameBeforeEnterAdminVc;
@property (nonatomic) UIViewController adminVc;
@property (nonatomic) NSMutableDictionary latestSettings;
@property (nonatomic) double startTime;
@property (nonatomic) BOOL hasFirstFetch;
@property (nonatomic) NSNumber fixedPanelHeight;
@property (nonatomic) IESLivePresentNavController nav;
@property (nonatomic) BOOL isPanelShow;
@property (nonatomic) BOOL didFetchSetting;
@property (nonatomic) BOOL isRoot;
@property (nonatomic) @? onSettingOpen;
@property (nonatomic) @? clickItemFeedback;
@property (nonatomic) @? heightDidChanged;
@property (nonatomic) NSNumber fromSeatPosition;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)adminVc;
- (BOOL)didFetchSetting;
- (BOOL)hasMasterSwitch;
- (void)setNav:;
- (id)generateStrongReminderViewModel;
- (void)setIsPanelShow:;
- (id)addAlphaMaskParameterToUrl:;
- (id)applySettingTypes;
- (id)audienceInteractiveSettingsAction;
- (id)authorityItemsWithSettings:;
- (id)buildTrackParamsForMoreDetail;
- (id)clickItemFeedback;
- (id)commonTrackParams;
- (void)currentFlattenSceneDidChangedFrom:to:;
- (id)currentFunctionType;
- (id)descForApplySettingType:;
- (id)descForStrongReminderType:;
- (void)didSetAttachingDIContext;
- (BOOL)didTrackForGuestGift;
- (id)didUpdateMasterSwitch;
- (void)didUpdatedSettingsSucceed;
- (void)didUpdatedSettingsSucceedWithData:;
- (void)fetchLocalAudienceInteractiveSettingsWithCompletion:;
- (id)fixedPanelHeight;
- (id)fromSeatPosition;
- (id)generateAudioAndVideoViewModelWithSettings:;
- (id)generateAuthorityViewModelWithSettings:;
- (BOOL)hasFirstFetch;
- (BOOL)hasTrackPlayModeExposure;
- (id)heightDidChanged;
- (id)indicatorHintFromPaidApplyReasonValue:;
- (id)initWithFrame:title:actionDelegate:eventContext:;
- (id)initWithFrame:title:actionDelegate:eventContext:isFromPK:;
- (BOOL)isFromPK;
- (BOOL)isPanelShow;
- (id)latestSettings;
- (void)loadDataAndRefresh;
- (id)makeSwitchItemWithTitle:initialValue:;
- (id)masterSwitch;
- (id)masterSwitchContainerView;
- (id)masterSwitchSubTitleLabel;
- (id)masterSwitchTitleLabel;
- (id)navFrameBeforeEnterAdminVc;
- (BOOL)oddTimeToRefreshSettingPanel;
- (id)onSettingOpen;
- (void)onSetupNavBar:;
- (void)p_addObserver;
- (void)p_changeMasterSwitchValue;
- (void)p_trackPlayModeExposureWithConfiguration:;
- (void)p_trakcFunctionPanelProgramShowItemWithEvent:source:;
- (void)paidLinkmicOpenStatusChanged:;
- (void)panelDidPopupAndShow;
- (id)seperatorLineView;
- (void)setAdminVc:;
- (void)setClickItemFeedback:;
- (void)setDidFetchSetting:;
- (void)setDidTrackForGuestGift:;
- (void)setDidUpdateMasterSwitch:;
- (void)setEventContext:;
- (void)setFixedPanelHeight:;
- (void)setFromSeatPosition:;
- (void)setHasFirstFetch:;
- (void)setHasMasterSwitch:;
- (void)setHasTrackPlayModeExposure:;
- (void)setHeightDidChanged:;
- (void)setIsFromPK:;
- (void)setLatestSettings:;
- (void)setMasterSwitch:;
- (void)setMasterSwitchContainerView:;
- (void)setMasterSwitchSubTitleLabel:;
- (void)setMasterSwitchTitleLabel:;
- (void)setNavFrameBeforeEnterAdminVc:;
- (void)setOddTimeToRefreshSettingPanel:;
- (void)setOnSettingOpen:;
- (void)setSeperatorLineView:;
- (void)setTitleForLabel:;
- (void)setUserInteractMasterSwitch:;
- (void)setupMasterSwitch:title:subTitle:try2Switch:;
- (void)showAudioAndVideoAuthority:settings:;
- (void)showHistoryPaidListView;
- (void)showLinkAcceptAuthority:settings:;
- (void)showPaidApplyReasonPanel;
- (void)showPaidLinkmicEvaluationView;
- (void)showPaidOptimizeLinkmicView:;
- (void)showStrongReminderView:;
- (void)showSwitchChatroomAndKTV:;
- (void)showThirdLevelPanelWithPopupItemConfigBlock:viewModelBlock:didShowBlock:;
- (id)strongReminderTypes;
- (id)titleForLabel;
- (void)trackDiff;
- (void)updateListWithSettings:;
- (void)updatePanelScrollEnabled:;
- (id)userInteractMasterSwitch;
- (void)setupConstraints;
- (void)setTitleLabel:;
- (id)tableView:cellForRowAtIndexPath:;
- (void)record;
- (void)setStartTime:;
- (BOOL)isRoot;
- (unsigned long long)currentScene;
- (void)setConfigurations:;
- (void)setSectionItems:;
- (id)actionDelegate;
- (double)startTime;
- (double)tableView:heightForRowAtIndexPath:;
- (id)tableView:viewForHeaderInSection:;
- (void)viewWillDisappear:;
- (void).cxx_destruct;
- (void)viewWillAppear:;
- (id)configurations;
- (void)setTableView:;
- (double)tableView:heightForHeaderInSection:;
- (id)sectionItems;
- (id)eventContext;
- (id)titleLabel;
- (void)tableView:willDisplayCell:forRowAtIndexPath:;
- (id)tableView;
- (long long)tableView:numberOfRowsInSection:;
- (void)viewDidLoad;
- (long long)numberOfSectionsInTableView:;
- (void)setIsRoot:;
- (void)setActionDelegate:;
- (void)setupViews;
- (double)tableViewHeight;
- (void)setTableViewHeight:;
- (double)contentViewHeight;
- (id)nav;
@end
