@interface IESLiveVSBigGiftComboView : UIView
@property (nonatomic) CADisplayLink displayLink;
@property (nonatomic) Q originCountdown;
@property (nonatomic) double currentCountdownRotate;
@property (nonatomic) UIView comboAnimationContentView;
@property (nonatomic) UIImageView comboBcakgroundImageView;
@property (nonatomic) UIImageView comboTextImageView;
@property (nonatomic) UIButton comboButton;
@property (nonatomic) BOOL isCountdowning;
@property (nonatomic) IESLiveVSSendGiftCommandQueue sendCommandQueue;
@property (nonatomic) IESLiveVSGiftItem giftItem;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (unsigned long long)originCountdown;
- (void)setComboButton:;
- (id)p_createCommand;
- (id)comboAnimationContentView;
- (id)comboBcakgroundImageView;
- (id)comboButton;
- (id)comboTextImageView;
- (void)commandDidExecute:command:error:;
- (double)currentCountdownRotate;
- (void)destroyTimer;
- (void)didComboButtonClicked:;
- (id)initWithGiftItem:;
- (BOOL)isCountdowning;
- (void)loadComboSubviews;
- (void)p_dismissWithInterrupt:;
- (id)sendCommandQueue;
- (void)setComboAnimationContentView:;
- (void)setComboBcakgroundImageView:;
- (void)setComboTextImageView:;
- (void)setCurrentCountdownRotate:;
- (void)setIsCountdowning:;
- (void)setOriginCountdown:;
- (void)setSendCommandQueue:;
- (void)tapEmpty;
- (id)displayLink;
- (void)setDisplayLink:;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)startAnimation;
- (void).cxx_destruct;
- (id)giftItem;
- (void)setGiftItem:;
@end
