@interface IESLivePolicyEngineService : IESLiveGeneralBaseService
@property (nonatomic) IESLivePEStrategyDataManager dataManager;
@property (nonatomic) IESLivePEStrategyDataParser dataParser;
@property (nonatomic) NSMutableDictionary factorDic;
@property (nonatomic) NSMutableDictionary subscriberDic;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)addRoomStrategyWith:;
- (void)addSubscriber:forStrategy:withDefaultFactor:;
- (void)addSubscriberForPublicScreenHistoryMessageStrategy:;
- (void)characterDidChange:withCharacterKey:;
- (void)checkStrategy:withDefaultDic:;
- (id)dataParser;
- (void)executeStrategyWithStrategyModels:;
- (id)factorDic;
- (BOOL)factorDidChangeWithFactorKey:currentValue:;
- (id)factorValueWithKey:;
- (id)historyMessageDynamicLoadStrategy;
- (void)liveRoomWatchMinitTick:;
- (id)publicScreenHistoryCommentLoadStrategyDefaultFactor;
- (void)registerStrategyWithJSONDictionary:;
- (id)relatedFactorsWithStrategyModel:;
- (void)removeSubscriber:forStrategy:;
- (void)serviceDidLaunch;
- (void)serviceUninstall;
- (void)setDataParser:;
- (void)setFactorDic:;
- (void)setSubscriberDic:;
- (void)setupDecisionEnv;
- (void)strategyFactorChange:withFactorKey:;
- (void)strategyFactorsChange:;
- (void)subscribeStrategyFromBackEndData;
- (id)subscriberDic;
- (void)setDataManager:;
- (id)dataManager;
- (void).cxx_destruct;
+ (void)ieslivekit_register_generalServiceAction;
+ (id)serviceProtocolsWithParam:;
+ (BOOL)serviceShouldActive:;
@end
