@interface IESLivePKGuestApplyListCell : UITableViewCell
@property (nonatomic) Q scene;
@property (nonatomic) @? permitUserBlock;
@property (nonatomic) UIImageView avatarView;
@property (nonatomic) UIImageView genderIcon;
@property (nonatomic) UILabel nicknameLabel;
@property (nonatomic) UILabel rankLabel;
@property (nonatomic) UILabel applyTimeLabel;
@property (nonatomic) IESLiveWaitingListUser userModel;
@property (nonatomic) NSNumber now;
@property (nonatomic) UIStackView tagContainer;
@property (nonatomic) BOOL enableShowGender;
- (id)permitUserBlock;
- (id)applyTimeLabel;
- (BOOL)enableShowGender;
- (id)genderIcon;
- (void)removeAllTagViews;
- (void)setApplyTimeLabel:;
- (void)setEnableShowGender:;
- (void)setGenderIcon:;
- (void)setPermitUserBlock:;
- (void)setTagContainer:;
- (id)tagContainer;
- (void)updateWithModel:now:permitUserBlock:scene:showPermit:rank:sortByTime:;
- (id)now;
- (id)initWithStyle:reuseIdentifier:;
- (void)setNow:;
- (void)setScene:;
- (id)avatarView;
- (void)setUserModel:;
- (void)setAvatarView:;
- (id)userModel;
- (void)prepareForReuse;
- (unsigned long long)scene;
- (void).cxx_destruct;
- (id)rankLabel;
- (void)setRankLabel:;
- (id)nicknameLabel;
- (void)setNicknameLabel:;
- (void)layoutUI;
+ (id)waitingDesString:nowTime:;
@end
