@interface IESLiveSaaSRoomInnerFeedContainerStore : NSObject
@property (nonatomic) NSNumber hasMoreRoom;
@property (nonatomic) <IESLiveSaaSMotionGuideCoordinator> guideCoordinator;
@property (nonatomic) <IESLiveSaaSFeedDrawerProvider> feedDrawerProvider;
@property (nonatomic) NSMutableArray roomList;
@property (nonatomic) NSNumber maxTime;
@property (nonatomic) NSString requestFrom;
@property (nonatomic) NSString innerFeedURL;
@property (nonatomic) HTSEventContext eventContext;
@property (nonatomic) BOOL alreadyRequest;
@property (nonatomic) BOOL enableScroll;
@property (nonatomic) IESLiveSaaSMultiRoomSegue originRoomSegue;
@property (nonatomic) q maxReadIndex;
@property (nonatomic) q loadMoreFirstIndex;
@property (nonatomic) NSString frontUnreadExtra;
@property (nonatomic) NSString lastUnreadExtra;
@property (nonatomic) NSNumber adOffset;
@property (nonatomic) NSMutableSet adRoomIDs;
@property (nonatomic) NSMutableDictionary adExtraStrings;
@property (nonatomic) NSDictionary feedExtraParams;
@property (nonatomic) NSNumber searchOffset;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <HTSLiveSaaSRoomCollectionDataObserver> dataObserver;
- (id)feedExtraParams;
- (void)setHasMoreRoom:;
- (id)lastUnreadExtra;
- (id)originRoomSegue;
- (void)setRequestFrom:;
- (void)_addRoomList:mappingError:;
- (void)_clearData;
- (BOOL)_enablePostUnreadRoom;
- (id)_getClientParamsForRecommend;
- (id)_getParams:;
- (id)_innerUrlConfigs;
- (BOOL)_isCurrentRoomListContainOfRoomID:;
- (void)_loadMore:;
- (void)_postUnreadRoomList;
- (void)_praseJsonData:finish:;
- (id)adExtraStringWithRoomID:;
- (id)adExtraStrings;
- (id)adOffset;
- (id)adRoomIDs;
- (BOOL)alreadyRequest;
- (BOOL)alreadyRequestFinish;
- (BOOL)canLoadMore;
- (BOOL)canRefresh;
- (BOOL)canSwipeRoomLeft;
- (BOOL)canSwipeRoomVertical;
- (void)changeToIndex:;
- (BOOL)containInnerUrlConfigForEnterFrom:enterMethod:;
- (BOOL)deleteRoom:;
- (void)didCloseRoom:;
- (BOOL)enableReTab;
- (BOOL)enableScroll;
- (id)feedDrawerProvider;
- (id)frontUnreadExtra;
- (id)guideCoordinator;
- (id)hasMoreRoom;
- (id)innerFeedRequestFrom;
- (id)innerFeedURL;
- (id)innerUrlConfigForEnterFrom:enterMethod:;
- (BOOL)isADRoomWithRoomID:;
- (void)loadMore;
- (long long)loadMoreFirstIndex;
- (long long)maxReadIndex;
- (id)requestFrom;
- (id)roomList;
- (id)searchOffset;
- (void)setAdExtraStrings:;
- (void)setAdOffset:;
- (void)setAdRoomIDs:;
- (void)setAlreadyRequest:;
- (void)setEnableScroll:;
- (void)setEventContext:;
- (void)setFeedDrawerProvider:;
- (void)setFeedExtraParams:;
- (void)setFrontUnreadExtra:;
- (void)setGuideCoordinator:;
- (void)setInnerFeedURL:;
- (void)setLastUnreadExtra:;
- (void)setLoadMoreFirstIndex:;
- (void)setMaxReadIndex:;
- (void)setOriginRoom:segue:;
- (void)setOriginRoomSegue:;
- (void)setRoomList:;
- (void)setRoomList:segue:;
- (void)setSearchOffset:;
- (void)storeEnableScroll:;
- (void)updateInnerFeedURLIfNeededWithSegue:;
- (void)refresh;
- (id)maxTime;
- (void)setDataObserver:;
- (void)setMaxTime:;
- (void)_refresh:;
- (id)channelName;
- (void).cxx_destruct;
- (BOOL)hasMore;
- (id)dataObserver;
- (id)eventContext;
@end
