@interface IESLiveLinkmicMediaService : NSObject
@property (nonatomic) IESLiveLinkmicMonitor linkmicMonitor;
@property (nonatomic) BOOL isJoinChannel;
@property (nonatomic) IESLiveInteractiveMediaService mediaService;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <IESLiveLinkmicMediaServiceDelegate> delegate;
@property (nonatomic) <IESLiveLinkmicMediaServiceInfoUpdatable> mediaInfo;
@property (nonatomic) <IESLiveLinkmicMediaServiceAudio> audio;
@property (nonatomic) <IESLiveLinkmicMediaServiceVideo> video;
@property (nonatomic) <IESLiveLinkmicMediaServiceSessions> sessions;
@property (nonatomic) <IESLiveLinkmicMediaServiceSignal> signal;
@property (nonatomic) <IESLiveLinkmicMediaServiceCrossRoom> crossRoom;
@property (nonatomic) <IESLiveLinkmicMediaServiceKTV> ktv;
@property (nonatomic) <IESLiveLinkmicMediaServiceExtra> extra;
- (void)interactiveMediaServiceWillEnd:;
- (id)ktv;
- (id)crossRoom;
- (void)didSetAttachingDIContext;
- (void)enterLinkmic;
- (void)exitLinkmic;
- (void)interactiveMediaService:anchorDidChangeToBackupSession:linkmicID:backupLinkmicID:;
- (void)interactiveMediaService:audioSessionInterrupt:;
- (id)interactiveMediaService:captureSizeWithUserService:outputSize:;
- (void)interactiveMediaService:didOfflineOfUid:sessions:reason:;
- (void)interactiveMediaService:didPublishStreamOfUser:;
- (void)interactiveMediaService:didUpdatedSessionsLocalLayout:;
- (void)interactiveMediaService:didVideoMuted:byUid:;
- (void)interactiveMediaService:firstFrameRenderCallback:;
- (void)interactiveMediaService:firstRemoteAudioFrameWithLinkmicUid:;
- (void)interactiveMediaService:firstRemoteVideoWithLinkmicUid:;
- (void)interactiveMediaService:localSmallWindowSessionCreated:;
- (void)interactiveMediaService:newSessionCreated:local:;
- (void)interactiveMediaService:onDeviceLoopDelayReceived:;
- (void)interactiveMediaService:onNetworkQuality:remoteQualities:;
- (void)interactiveMediaService:onRTMLinkMessageReceived:;
- (void)interactiveMediaService:onStreamSyncInfoReceived:streamType:data:;
- (void)interactiveMediaService:onSubtitleMessageReceived:;
- (void)interactiveMediaService:onSubtitleStateChanged:;
- (void)interactiveMediaService:onSwitchMixTypeResult:isMixOnClient:;
- (void)interactiveMediaService:onUserJoined:extraInfo:;
- (void)interactiveMediaService:receivesError:;
- (void)interactiveMediaService:startPlayPublicStreamResult:needVideoCanvas:;
- (void)interactiveMediaService:stopPlayPublicStreamResult:;
- (void)interactiveMediaService:videoSizeChangedOfUid:size:;
- (void)interactiveMediaServiceAppDidActive;
- (void)interactiveMediaServiceAppResignActive;
- (void)interactiveMediaServiceDidEnd:;
- (void)interactiveMediaServiceDidStart:;
- (void)interactiveMediaServiceSomeoneTalkingStateDidChanged:;
- (void)interactiveMeidaServiceLostConnection:;
- (BOOL)isEnterLinkmic;
- (BOOL)isInteractRunning;
- (BOOL)isJoinChannel;
- (id)linkmicMonitor;
- (void)setIsJoinChannel:;
- (void)setLinkmicMonitor:;
- (void)setupWithConfig:;
- (void)setupWithMediaService:;
- (void)startInteract;
- (void)stopInteract;
- (void)updateLinkmicMonitor:;
- (id)signal;
- (id)extra;
- (id)sessions;
- (void)setDelegate:;
- (id)delegate;
- (void).cxx_destruct;
- (id)video;
- (id)audio;
- (id)mediaService;
- (void)setMediaService:;
- (id)mediaInfo;
@end
