@interface IESLiveAlphaVideoPlayer : NSObject
@property (nonatomic) <IESLiveRoomServiceAdapter> room;
@property (nonatomic) HTSEventContext trackContext;
@property (nonatomic) IESLiveVideoGiftController giftController;
@property (nonatomic) HTSLiveEffectPlayerStringPiece stringPiece;
@property (nonatomic) IESLiveAlphaVideoPlayerConfiguration configuration;
@property (nonatomic) IESLiveAlphaVideoPlayerButtonView buttonView;
@property (nonatomic) <IESLiveRoomRealStreamingServiceAdapter> realStreamingService;
@property (nonatomic) BOOL hasMannualOpenAEC;
@property (nonatomic) BOOL liveAlphaVideoPlayerEnableAuxStreamAudioFile;
@property (nonatomic) NSDictionary soundGiftVolumeConfigs;
@property (nonatomic) BOOL giftSoundVolumeDynamicAdjust;
@property (nonatomic) BOOL liveAudioGiftDisableAec;
@property (nonatomic) double liveAudioGiftAECDelayTime;
@property (nonatomic) q liveAudioGiftAECRetryTime;
@property (nonatomic) BOOL bpeaAudioCertEnable;
@property (nonatomic) NSString bpeaAudioCertToken;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <IESLiveAlphaVideoPlayerCallbackDelegate> playerCallbackDelegate;
@property (nonatomic) <IESLiveAlphaVideoPlayerActionDelegate> playerActionDelegate;
- (void)setStringPiece:;
- (BOOL)shouldDelayPlayIfAudioResouces:;
- (void)updateVibrateButton:completion:;
- (float)audioPlayVolume;
- (void)monitorWithConfiguration:error:;
- (void)setEnableSound:;
- (float)_getAudioPlayVolumeFromPlayerStreamSound;
- (void)adjustPlayerViewLevelWithConfiguration:;
- (void)asyncPlayWithCheckAECState:;
- (BOOL)bpeaAudioCertEnable;
- (id)bpeaAudioCertToken;
- (void)closeEchoCancellation;
- (void)destroyButtonView;
- (void)didClickSoundButton;
- (void)didClickVibrateAndSoundButton;
- (void)didClickVibrateButton;
- (void)didFinishPlayingWithError:;
- (void)didSetAttachingDIContext;
- (BOOL)enableSound;
- (BOOL)enableVibrate;
- (void)execActionSafely:;
- (void)frameCallBack:;
- (id)giftController;
- (BOOL)giftSoundVolumeDynamicAdjust;
- (BOOL)hasMannualOpenAEC;
- (id)initWithRoom:trackContext:;
- (BOOL)isHeadsetPluggedIn;
- (BOOL)liveAlphaVideoPlayerEnableAuxStreamAudioFile;
- (double)liveAudioGiftAECDelayTime;
- (long long)liveAudioGiftAECRetryTime;
- (BOOL)liveAudioGiftDisableAec;
- (void)loadButtonView:metalFrame:withAction:;
- (void)openEchoCancellation;
- (id)playerActionDelegate;
- (id)playerCallbackDelegate;
- (id)realStreamingService;
- (void)removeStringPiece;
- (void)setBpeaAudioCertEnable:;
- (void)setBpeaAudioCertToken:;
- (void)setEnableVibrate:;
- (void)setGiftController:;
- (void)setGiftSoundVolumeDynamicAdjust:;
- (void)setHasMannualOpenAEC:;
- (void)setLiveAlphaVideoPlayerEnableAuxStreamAudioFile:;
- (void)setLiveAudioGiftAECDelayTime:;
- (void)setLiveAudioGiftAECRetryTime:;
- (void)setLiveAudioGiftDisableAec:;
- (void)setPlayerActionDelegate:;
- (void)setPlayerCallbackDelegate:;
- (void)setRealStreamingService:;
- (void)setSoundButtonDidShow:;
- (void)setSoundGiftVolumeConfigs:;
- (void)setTrackContext:;
- (void)setVibrateButtonDidShow:;
- (void)showSoundButton:metalFrame:;
- (void)showStringPiece:videoRatio:needCircle:;
- (void)showVibrateAndSoundButton:metalFrame:;
- (void)showVibrateButton:metalFrame:;
- (BOOL)soundButtonDidShow;
- (id)soundGiftVolumeConfigs;
- (void)startPlayWithConfiguration:;
- (void)stopPlayingWithError:;
- (id)stringPiece;
- (void)successParseConfigResourceModel:;
- (id)trackContext;
- (void)updateSoundButton:completion:;
- (void)updateVibrateAndSoundButton:completion:;
- (BOOL)vibrateButtonDidShow;
- (BOOL)videoControllerShouldDelayPlayIfAudioResouces:;
- (void)videoGiftController:didSetMetalViewFrame:;
- (id)videoGiftController:externalAudioPlayer:resource:error:;
- (void)videoGiftController:sceneError:scene:;
- (void)videoGiftController:willPlayFrame:;
- (void)setButtonView:;
- (BOOL)isPlaying;
- (void)setConfiguration:;
- (id)configuration;
- (void).cxx_destruct;
- (id)buttonView;
- (void)stopPlaying;
- (id)room;
- (void)setRoom:;
- (void)stopEngine;
@end
