@interface IESLiveInteractionEmojiPanelViewModel : NSObject
@property (nonatomic) BOOL isMute;
@property (nonatomic) BOOL isFollow;
@property (nonatomic) BOOL isHost;
@property (nonatomic) <IESLiveInteractUserModel> interactGuestUser;
@property (nonatomic) IESLiveInteractionEmojiAPI api;
@property (nonatomic) IESLiveInteractionEmojiPanelConfig config;
@property (nonatomic) Q emojiLines;
@property (nonatomic) NSArray renderItems;
@property (nonatomic) NSArray honorInfoArray;
@property (nonatomic) NSArray adventureItems;
@property (nonatomic) NSArray panelItems;
@property (nonatomic) NSArray modeItems;
@property (nonatomic) NSArray activityItems;
@property (nonatomic) NSString requestPage;
@property (nonatomic) q loadingStatus;
@property (nonatomic) NSArray emojiPages;
@property (nonatomic) IESLiveInteractionEmojiStore store;
@property (nonatomic) IESLivePopupItem popupItem;
@property (nonatomic) NSString addSeatNameTitle;
- (void)setRenderItems:;
- (void)setRequestPage:;
- (BOOL)showDressUpIcon;
- (void)didSelectEmoji:;
- (BOOL)showCenterTitle;
- (BOOL)showCompetitionGameSetPerformer;
- (BOOL)showEnlargeIcon;
- (void)showMultiAudioKTVSingModePicker;
- (id)addSeatNameTitle;
- (id)adventureItems;
- (long long)avatarAuditStatus;
- (id)buildXplayOperationItem:;
- (int)currentConnectMode;
- (void)didClickAddSeatNameButton;
- (void)didClickAvatarCloseButton;
- (void)didClickConnectionButton;
- (void)didClickContributionListButton;
- (void)didClickFastMatchButton;
- (void)didClickFollowButton;
- (void)didClickGuestHonorIcons;
- (void)didClickHostButton;
- (void)didClickMuteButton:;
- (void)didClickRecognizeButton;
- (void)didClickSendGiftButton;
- (void)didClickSettingBtn;
- (void)didClickUserInfoButton;
- (void)didShowEmoji:;
- (unsigned long long)emojiLines;
- (unsigned long long)emojiLinesWithPages:;
- (id)emojiPages;
- (void)enlargeGuest:;
- (BOOL)hasSeatName;
- (void)hidePanel;
- (id)honorInfoArray;
- (id)initWithStore:config:;
- (unsigned long long)initialEmojiLines;
- (id)interactGuestUser;
- (BOOL)isCurrentSceneSupportPaidLimitLink;
- (BOOL)isFollow;
- (BOOL)isOnlyAvatarEmojiForAnchor;
- (BOOL)isOthersPanel;
- (BOOL)isSingleLineEmojiList;
- (BOOL)isTopRightAddSeatName;
- (BOOL)isTopRightDisconnect;
- (BOOL)isXplayExitOperationExist;
- (BOOL)isXplayOperationExist;
- (id)itemInfoForType:;
- (id)makePanelItemWithType:;
- (id)modeItems;
- (void)modifyOtherRoomStatus:;
- (id)othersPanelItemTypes;
- (BOOL)p_isAnonymous;
- (id)panelItems;
- (id)panelTitle;
- (id)popupItem;
- (id)pr_reformEmojiPageFromList:withMaxLines:;
- (BOOL)precheckOthersConnection;
- (id)reformEmojiPageFromList:;
- (id)renderConnectModeItems;
- (id)renderItems;
- (void)renderSkinInActivityItem:;
- (unsigned long long)requestEmojiCategory;
- (id)requestPage;
- (id)selfConnectModeTypes;
- (id)selfPanelItemTypes;
- (void)setAdventureItems:;
- (void)setEmojiLines:;
- (void)setEmojiPages:;
- (void)setHonorInfoArray:;
- (void)setInteractGuestUser:;
- (void)setIsFollow:;
- (void)setIsHost:;
- (void)setIsMute:;
- (void)setModeItems:;
- (void)setPanelItems:;
- (void)setPopupItem:;
- (BOOL)showAudioModeIcon;
- (BOOL)showAvatarModeIcon;
- (BOOL)showBeautyIcon;
- (BOOL)showCameraOption;
- (BOOL)showCancelEnlargeIcon;
- (BOOL)showCompetitionGameUnsetPerformer;
- (BOOL)showConnectionIcon;
- (BOOL)showContributionList;
- (BOOL)showFastMatchIcon;
- (BOOL)showHostIcon;
- (BOOL)showIncreasePaidLimitLinkTime;
- (BOOL)showInviteKtvChatGroup;
- (BOOL)showMuteIcon;
- (BOOL)showMuteOherRoomIcon;
- (BOOL)showOpenContainerEntrance;
- (void)showQuickInteractPanel:;
- (BOOL)showRecognizeModeIcon;
- (BOOL)showTeamFightSetBlue;
- (BOOL)showTeamFightSetBlueDisable;
- (BOOL)showTeamFightSetRed;
- (BOOL)showTeamFightSetRedDisable;
- (BOOL)showVideoModeIcon;
- (id)statusTrackStringForToast:;
- (BOOL)topRightShowSettingEntrance;
- (void)trackActivityItemClick:;
- (void)trackActivityItemShow:;
- (void)updatePanelItemWithType:;
- (long long)loadingStatus;
- (void)setLoadingStatus:;
- (void)setStore:;
- (void)setConfig:;
- (BOOL)isAnchor;
- (void).cxx_destruct;
- (id)currentUser;
- (id)config;
- (id)store;
- (void)fetchData;
- (id)activityItems;
- (BOOL)isHost;
- (void)setActivityItems:;
- (id)api;
- (BOOL)isMute;
- (void)setApi:;
@end
