@interface IESLiveHTTPClientWrapper : NSObject
@property (nonatomic) <IESLiveLanguageService> languageService;
@property (nonatomic) <IESLiveCertifyCenter> certifyCenter;
@property (nonatomic) <IESLiveLocationService> locationService;
@property (nonatomic) <IESLiveNetworkQualityInfoService> networkQualityInfoService;
@property (nonatomic) <IESLiveCustomConfig> customConfig;
@property (nonatomic) <IESLiveAppInfo> appInfo;
@property (nonatomic) NSString domain;
@property (nonatomic) NSMutableDictionary injectdCommonParams;
@property (nonatomic) BOOL enableNetflowTag;
@property (nonatomic) NSMutableDictionary commonHeaders;
@property (nonatomic) @? pathMapBlock;
@property (nonatomic) <IESLiveHTTPClient> client;
@property (nonatomic) BOOL teenMode;
@property (nonatomic) NSDictionary mainThreadParams;
@property (nonatomic) @ certifyService;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)languageService;
- (id)locationService;
- (id)URLString:appendCommonParams:;
- (id)URLStringByAppendingCompletePath:;
- (id)URLStringByAppendingPath:;
- (void)_checkApprovedWithURL:;
- (void)_checkIfAPIPathEndsWithSlash:;
- (id)baseHostURL;
- (id)buildSafeCommonParamsWithUrlString:withoutL0:;
- (id)certifyCenter;
- (id)certifyService;
- (id)commonHeaders;
- (id)commonParameters;
- (id)commonParametersWithUrlString:;
- (id)commonParametersWithoutL0;
- (id)commonPath;
- (id)configDomain;
- (BOOL)containsCookie:forCookies:;
- (id)customConfig;
- (BOOL)enableNetflowTag;
- (id)extensionUserDefaultsSuitName;
- (id)get:parameters:headerFields:completion:;
- (void)handleAccessTokenError:requestModel:;
- (id)handleError:withResponseObj:;
- (id)initWithClient:commonParams:;
- (id)injectdCommonParams;
- (BOOL)isTeenMode;
- (BOOL)isUseAuthV2;
- (id)logIDForResponseObj:;
- (id)mainThreadParams;
- (BOOL)netflowTag;
- (id)networkQualityInfoService;
- (id)pathMapBlock;
- (id)post:parameters:headerFields:completion:;
- (id)postForBinary:parameters:completion:;
- (id)postForJSON:parameters:headerFields:completion:;
- (void)recordCommonParams;
- (void)requestCallbackWithResponseCallback:requestError:finishModel:;
- (void)requestCallbackWithResponseCallback:requestError:finishModel:;
- (id)requestIdForResponseObj:;
- (id)requestWithParamsModel:;
- (void)setCertifyCenter:;
- (void)setCertifyService:;
- (void)setCommonHeaders:;
- (void)setCustomConfig:;
- (void)setEnableNetflowTag:;
- (void)setInjectdCommonParams:;
- (void)setLanguageService:;
- (void)setLocationService:;
- (void)setMainThreadParams:;
- (void)setNetflowTag:;
- (void)setNetworkQualityInfoService:;
- (void)setPathMapBlock:;
- (void)setTeenMode:;
- (BOOL)shouldUpdateSharedCookie;
- (void)updateSharedCookieForURL:;
- (id)uploadFileData:URLString:progress:parameters:completionHandler:fileType:;
- (id)initWithClient:;
- (void)dealloc;
- (id)baseURL;
- (void)setClient:;
- (id)appInfo;
- (void)setValue:forHTTPHeaderField:;
- (id)client;
- (void).cxx_destruct;
- (id)domain;
- (void)setDomain:;
- (void)setAppInfo:;
+ (id)getCurrentHostURL;
@end
