@interface IESLiveMultiAudioAudienceFragment : IESLiveRoomComponent
@property (nonatomic) IESLiveMultiAudioAudienceStore store;
@property (nonatomic) <IESLiveInteractiveInviteService> inviteFriendsService;
@property (nonatomic) HTSGroupedLiveMessageHandler messageHandler;
@property (nonatomic) IESLiveAudienceInteractiveRootPanel adminInteractiveRootPanel;
@property (nonatomic) IESLiveAudienceInteractiveInviteInterestedListPanel inviteInterestedListPanel;
@property (nonatomic) NSDate lastGuideAnimationPlayTime;
@property (nonatomic) BOOL clickGuideBubble;
@property (nonatomic) <IESLiveMultiAudioSceneControllerProtocol> sceneController;
@property (nonatomic) IESLiveCountTimer invitationGuideTimer;
@property (nonatomic) BOOL invitationGuideHasShown;
@property (nonatomic) NSNumber clickPosition;
@property (nonatomic) NSNumber applyType;
@property (nonatomic) IESLiveInteractionConfirmPanel confirmPanel;
@property (nonatomic) IESLiveInteractiveEditSeatPanelViewModel adminEditViewModel;
@property (nonatomic) IESliveAudienceInteractPanelManager panelManager;
@property (nonatomic) <IESLiveInteractionLinkerService> linkerService;
@property (nonatomic) <IESLiveInteractionSettingsRouter> interactionSettings;
@property (nonatomic) <IESLiveMultiAudioAudienceLinkmicInnerService> audienceLinkmicInnerService;
@property (nonatomic) NSArray multiAudioAudienceProtocols;
@property (nonatomic) BOOL isInBackground;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)adminModeEnable;
- (void)audienceInteractiveRootPanel:permitApplicationOfUser:extraInfo:;
- (id)frameOfSlotView;
- (void)setAudienceLinkmicInnerService:;
- (void)setMultiAudioAudienceProtocols:;
- (id)supportedScenes;
- (id)trackContextForSceneController:;
- (void)componentCreate;
- (void)currentLayoutDidChangedFrom:to:;
- (BOOL)isInPaidLinkmic;
- (BOOL)sceneControllerValidWithLayout:;
- (void)acceptConnectionWithUserID:requestPage:;
- (void)acceptConnectionWithWaitingListUser:params:;
- (id)activedList;
- (void)activedListObserver;
- (id)adminEditViewModel;
- (id)adminInteractiveRootPanel;
- (id)adminInteractiveRootPanelViewModel;
- (void)adminKickOutUserID:secUserID:requestSource:completion:;
- (void)adminPermitWithUser:requestSource:extraInfo:;
- (BOOL)adminRightEnable;
- (id)allMembersList;
- (id)allSeatProviderViews;
- (void)anchorInteractUserObserver;
- (id)anchorPermitConnectionParamsWithUser:;
- (id)appDataForSceneController:;
- (void)appDataObserver:;
- (void)applyConnectionWithParams:;
- (void)askForStopApplyFromAdminPanel:;
- (void)askForStopConnectionAction:;
- (void)audienceInteractiveRootPanel:inviteWithUserID:secUserID:sourcePage:;
- (void)audienceInteractiveRootPanel:inviteWithUserID:secUserID:sourcePage:params:;
- (void)audienceInteractiveRootPanelAdminApply:;
- (void)audienceInteractiveRootPanelNeedToResetWaitingApplications:;
- (id)audienceLinkmicInnerService;
- (void)authenticationNofity:;
- (void)cancelApplication;
- (void)checkApplyPermission:;
- (void)checkAuthorizationPermission:;
- (BOOL)clickGuideBubble;
- (id)clickPosition;
- (void)clickSelfUserViewFrom:guest:;
- (void)componentBindService;
- (id)componentContextForSceneController:;
- (void)componentDidAppear;
- (void)componentMount;
- (void)componentOrientationChanged:;
- (void)componentUnmount;
- (void)componentWillAppear;
- (id)confirmPanel;
- (id)coreTrackModel;
- (unsigned long long)correctCurrentScene:;
- (id)createRootPanelViewModelConfigWithSource:;
- (void)currentLayoutUIDidUpdateFrom:to:;
- (id)currentStreamLayout;
- (void)didClickAudienceInteractionEntranceButton;
- (void)didClickInviteView;
- (void)didClickPreLinkWithPosition:;
- (void)didClickSelfWithPosition:requestSource:;
- (BOOL)didConnectToAnchor;
- (void)didSwitchLayoutFrom:to:;
- (void)didTapSlotViewWithPosition:sceneController:;
- (id)emojiContainerForUserID:isInteractiveEmoji:;
- (id)emojiSeatAnimationViewsForUserID:;
- (BOOL)enablePushStreamInBackground;
- (BOOL)enableShowOthersPanel;
- (id)enlargeGuestUserId;
- (void)enlargeGuestWithIsEnlarge:guestID:;
- (BOOL)enterRoomByFastMatch;
- (void)fetchGuestGiftSetting;
- (int)getListUserRoleWithUserID:;
- (id)guestBattleUIAdaptor;
- (id)guestInfoList;
- (id)guestListViewFrame;
- (void)handleFlattenSceneDidChangedFrom:to:;
- (BOOL)hasEmptySeat;
- (void)hideAdminPanel;
- (id)interactUserList;
- (void)interactionDidUpdateAllSeats:;
- (void)interactionLinkerService:didCancelWaitingWithContext:;
- (void)interactionLinkerService:didCloseWithContext:;
- (void)interactionLinkerService:didDisconnectWithContext:;
- (void)interactionLinkerService:didJoinChannelWithContext:;
- (void)interactionLinkerService:onReceivedInvite:;
- (void)interactionLinkerService:startWaitingWithContext:;
- (void)interactionLinkerServiceInteractDidEnd:;
- (void)interactionLinkerServiceInteractDidStart:;
- (void)interactionLinkerServiceInteractPrepareWillReady:;
- (void)interactionLinkerServiceInteractWillEnd:;
- (void)interactionLinkerServiceInteractWillStart:;
- (void)interactionLinkerServiceUserAlreadyLinked:;
- (BOOL)invitationGuideHasShown;
- (id)invitationGuideTimer;
- (id)inviteFriendsService;
- (id)inviteInterestedListPanel;
- (void)inviteUserWithSecID:userID:sourcePage:;
- (void)inviteUserWithSecID:userID:sourcePage:params:;
- (BOOL)isApplyingToJoinChannel;
- (BOOL)isAudioCaptureThisTime;
- (BOOL)isEnlargeGuest;
- (BOOL)isInAnonymousPaidLinkmicWithUserID:;
- (BOOL)isInWaitingList:;
- (BOOL)isInteractionRuning;
- (BOOL)isJoinChannelAfterFollow;
- (BOOL)isPaidLinkmicJoinChannel;
- (BOOL)isSelfLinked;
- (BOOL)isSelfWaiting;
- (BOOL)isValidWithLayout:;
- (BOOL)isValidWithScene:;
- (long long)joinPayCount;
- (id)lastGuideAnimationPlayTime;
- (void)leave:directly:completed:;
- (long long)linkMicStatus;
- (id)linkerService;
- (id)linkmicHost;
- (void)loadMessageHandlers;
- (long long)maxMcNum;
- (void)multiAudioApplyConnectionWithParams:;
- (id)multiAudioAudienceProtocols;
- (void)muteAllRemoteAudioStreams:reason:;
- (void)muteGuest:;
- (void)muteOrUnMuteSelf;
- (void)muteOtherRoom:;
- (void)muteSelf:;
- (void)muteSelf:withState:;
- (void)muteSelfForKTVSing:;
- (void)onAppDidEnterBackground;
- (void)onAppDidEnterForeground;
- (id)onlineUserWrapper:;
- (void)openEmojiPanelForUser:requestPage:;
- (id)othersMembersList;
- (void)p_guestOperation:sourcePage:fromPanel:;
- (BOOL)p_isInMseqRoom;
- (void)p_showLinkPanelForOtherLinkerGuest:;
- (void)p_trackGuestConnectAction:muteUser:;
- (void)paidLinkmicDidReceiveAddPriceMessage:;
- (void)paidLinkmicExplainCardClick;
- (void)paidLinkmicOpenStatusChanged:;
- (void)paidLinkmicWaitingUserLeaveWithToast:;
- (id)panelManager;
- (id)playModesArray;
- (void)popupUsingAlertStyle;
- (id)pr_buildTrackFollow;
- (void)pr_didClickSelfWithPosition:requestSource:;
- (void)pr_trackClickOnSeat:;
- (void)pr_updateLinkMicFanticketView;
- (void)prepareForStartWithSource:shouldApply:mute:shouldBanVideo:;
- (BOOL)processingMultiAudio;
- (void)registerObservers;
- (void)removeAWEBridgeSyncCertificationObserver;
- (void)removeAdminUI;
- (void)replyWithFromSecUid:;
- (id)roleForLog;
- (id)roomForSceneController:;
- (id)rootPanelDelegateInstance;
- (id)sceneConfigurationsInSettingPanel;
- (void)sceneController:didClickSeatAtIndex:seatInfo:;
- (void)sceneController:didClickSeatAtIndex:viewIndex:seatInfo:;
- (void)sceneController:didSelectGuest:enableDisconnect:;
- (void)sceneController:didSwitchLayoutWithInteractionLayout:;
- (void)sceneController:doingSwitchLayoutWithInteractionLayout:;
- (void)sceneController:muteSelf:;
- (void)sceneController:processWithAppData:;
- (void)sceneController:willSwitchLayoutWithInteractionLayout:;
- (void)sceneControllerDidClickAdminApply:;
- (void)sceneControllerDidClickAnchorProfile:;
- (void)sceneControllerDidShowGuideBubble:;
- (id)sceneControllerWithLayout:;
- (BOOL)selectedFeedback;
- (void)sendAWEBridgeSyncCertificationStatus;
- (void)setAdminEditViewModel:;
- (void)setAdminInteractiveRootPanel:;
- (void)setClickGuideBubble:;
- (void)setClickPosition:;
- (void)setConfirmPanel:;
- (void)setInvitationGuideHasShown:;
- (void)setInvitationGuideTimer:;
- (void)setInviteFriendsService:;
- (void)setInviteInterestedListPanel:;
- (void)setIsInBackground:;
- (void)setLastGuideAnimationPlayTime:;
- (void)setLinkerService:;
- (void)setPanelManager:;
- (void)setupStore;
- (BOOL)shouldFetchWaitingUserAfterApply;
- (void)showAdminOperationPanelForGuest:;
- (void)showAdminPanelWithSource:;
- (void)showAnimationWithCueThreshold:animationData:;
- (void)showApplyDetailPanelWithWaitingResponse:;
- (void)showCancelApplicationSheetWithTitle:;
- (void)showChangeTeamToastWithPosition:;
- (void)showClickEmptySeatActionSheetWithPosition:sceneController:;
- (void)showInviteInterestedListPanelWithSource:;
- (void)showInvitePanelWithView:showCompletion:hideCompletion:;
- (void)showLoginPanel;
- (void)showReceivingPanelObserver:;
- (void)showUserPreView:trackerLabel:;
- (void)showWaitingApplicationNumTip:;
- (id)stageWithLayout:;
- (void)startInvitationGuideTimerIfNeeded;
- (void)stopConnectionWithRequestSource:;
- (void)stopConnectionWithRequestSource:extra:completion:;
- (void)stopConnectionWithUserID:secUserID:requestSource:;
- (void)stopInvitationGuideTimer;
- (id)teamFightDelegate;
- (id)toastForDisconnect:;
- (void)toastObserver:;
- (unsigned long long)tryToShowInvitePanelWithIsTask:activityName:;
- (unsigned long long)tryToStartApplyProcessingWithIsTask:activityName:applyType:applySource:;
- (void)unMuteGuest:;
- (void)unMuteOtherRoom:;
- (void)unloadMessageHandlers;
- (void)unregisterObservers;
- (void)updateSeatInfosIfNeeded;
- (id)userByUserId:;
- (BOOL)userInActiveList:;
- (BOOL)userInActiveOrWaitingList:;
- (void)userProfileWillAppear;
- (id)waitingList;
- (void)waitingOffsetObserver;
- (void)showToast:;
- (void)dealloc;
- (void)setStore:;
- (unsigned long long)currentScene;
- (BOOL)isMuted;
- (BOOL)isInBackground;
- (id)messageHandler;
- (void).cxx_destruct;
- (id)store;
- (void)setMessageHandler:;
- (void)messageReceived:;
- (id)interactionSettings;
- (id)applyType;
- (void)setApplyType:;
- (void)setInteractionSettings:;
- (id)sceneController;
- (void)setSceneController:;
+ (BOOL)isMixed;
+ (BOOL)componentShouldActive:;
@end
