@interface IESLivePKEffectInfoManager : NSObject
@property (nonatomic) BattleEffectInfo battleEffectInfo;
@property (nonatomic) NSString rawBattleEffectInfo;
@property (nonatomic) BOOL resolveFromMessage;
@property (nonatomic) AnchorEffect_EffectInfo lastPropEffectInfoSendByCurrentLoginUser;
@property (nonatomic) q lastReportEffectInfoStartTime;
@property (nonatomic) NSDictionary fontSizeDict;
@property (nonatomic) <IESLiveRevenueInteractProvider> interactProvider;
@property (nonatomic) <IESLiveCompoundSubscription> disposable;
@property (nonatomic) NSNumber isOverlay;
@property (nonatomic) BOOL isNewPropEffectInfoSendByCurrentLoginUser;
- (id)activePropEffectInfoForUserId:;
- (id)anchorEffectForUserId:;
- (id)battleEffectInfo;
- (void)cleanInvalidEffectInfo;
- (void)clearBattleEffectInfo;
- (double)currentServerTimestampInMS;
- (id)disposable;
- (id)executePropsMakeBorrowedAnimationWithCenterPoint:;
- (id)executePropsMakeEffectAnimationFromStart:toTarget:;
- (id)executePropsMakeEffectBreathAnimationWithTimeOffset:;
- (id)executePropsMakeEffectQueueAnimationFromStart:toTarget:;
- (id)executePropsMakeFierceAnimationWithCenterPoint:;
- (id)firstActivePropEffectInfoForUserId:;
- (id)fontSizeDict;
- (double)fontSizeForBuffScoreRatio:;
- (BOOL)hasEffectInfo;
- (id)initWithDIContext:;
- (id)interactProvider;
- (BOOL)isNewPropEffectInfoSendByCurrentLoginUser;
- (id)lastPropEffectInfoSendByCurrentLoginUser;
- (long long)lastReportEffectInfoStartTime;
- (long long)longestRemainSecondsFor:;
- (id)newSentPropEffectInfoFor:;
- (long long)numberOfSameKindForEffectInfo:inAnchorEffect:;
- (void)openDescPageForEffectInfo:source:;
- (void)openPropCardDetailWithSource:scene:userId:;
- (id)rawBattleEffectInfo;
- (long long)remainSecondsFor:;
- (void)reportEffectInfo:userId:checkLast:;
- (void)resetIsOverlayIfNeed;
- (void)resetLastPropEffectInfoSendByCurrentLoginUserWithBattleEffectInfo:;
- (void)resolveBattleEffectContainerMessage:;
- (BOOL)resolveFromMessage;
- (void)resolveRawBattleEffectInfo:battleId:;
- (void)setBattleEffectInfo:;
- (void)setDisposable:;
- (void)setFontSizeDict:;
- (void)setInteractProvider:;
- (void)setIsNewPropEffectInfoSendByCurrentLoginUser:;
- (void)setLastPropEffectInfoSendByCurrentLoginUser:;
- (void)setLastReportEffectInfoStartTime:;
- (void)setRawBattleEffectInfo:;
- (void)setResolveFromMessage:;
- (BOOL)useLocalUpdateBattleEffectInfoIfExpired:;
- (id)isOverlay;
- (void).cxx_destruct;
- (void)setIsOverlay:;
- (void)clean;
+ (BOOL)isPropEffectType:;
+ (id)schemaForEffectType:;
+ (BOOL)shouldLoadEffectInfoForInteractProvider:;
@end
