@interface IESLivePKAudienceBuilder : NSObject
@property (nonatomic) HTSLivePKApi pkApi;
@property (nonatomic) HTSLiveInteractiveAPIV2 interactApi;
@property (nonatomic) HTSLiveLinkMicPKMessageHandler messageHandler;
@property (nonatomic) IESLiveInteractiveLinkService linkService;
@property (nonatomic) <IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) NSNumber currentChannelID;
@property (nonatomic) IESLiveCountTimer timeoutTimer;
@property (nonatomic) IESLiveCountTimer seiInteractModeBackUpTimer;
@property (nonatomic) BOOL seiOnInteractMode;
@property (nonatomic) BOOL realSEIInteractMode;
@property (nonatomic) BOOL isCountingDown;
@property (nonatomic) BOOL isFirstSEI;
@property (nonatomic) BOOL fetchPKDataSuccess;
@property (nonatomic) BOOL isRequestingPKDataApi;
@property (nonatomic) float backupCountdownInterval;
@property (nonatomic) IESLivePKModel pkmodel;
@property (nonatomic) <IESLiveRevenueInteractPlayModel> playModel;
@property (nonatomic) RACCompoundDisposable disposable;
@property (nonatomic) q requestMaxCount;
@property (nonatomic) q requestCurrentCount;
@property (nonatomic) IESLiveLinkMicSEIParserResult seiResult;
@property (nonatomic) IESLiveLinkMicSEIParserResult lastSEI;
@property (nonatomic) BOOL revenueInteractStart;
@property (nonatomic) BOOL multiNormalSwitchPKFlag;
@property (nonatomic) BOOL hasDisableVR;
@property (nonatomic) BOOL hasComponentUnmount;
@property (nonatomic) <IESLivePKProvider> pkProvider;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)lastSEI;
- (void)setInteractApi:;
- (unsigned long long)supportSeiTypes;
- (BOOL)isPKSEI;
- (id)pkmodel;
- (long long)requestMaxCount;
- (void)setLinkService:;
- (void)startSEIInteractModeBackUpTimer;
- (void)updatePKStatus:;
- (float)backupCountdownInterval;
- (void)bindAction;
- (void)cancelBackupTimer;
- (void)checkPKChannelStatusWithForceChangePKStatus:source:channelID:;
- (void)didSetAttachingDIContext;
- (void)didUpdateRoom:timeStamp:;
- (id)disposable;
- (void)endLinkMicExternalSceneHandle;
- (BOOL)fetchPKDataSuccess;
- (BOOL)hasComponentUnmount;
- (BOOL)hasDisableVR;
- (id)initWithDIContext:;
- (id)interactApi;
- (BOOL)isCountingDown;
- (BOOL)isCropLiveStreaming;
- (BOOL)isFirstSEI;
- (BOOL)isMultiLinkerSEI:;
- (BOOL)isRequestingPKDataApi;
- (BOOL)isSubOrientationVerticalRoom;
- (id)linkService;
- (BOOL)multiNormalSwitchPKFlag;
- (void)onComponentUnmount;
- (void)onDestoryPK;
- (void)onParseredWithSEIResult:;
- (void)onPreparePKWithListResult:;
- (void)onReceivePKSetting:;
- (void)onReceivedLinkBanMessage:;
- (void)onReceivedLinkCloseMessage:;
- (void)onReceivedLinkEnterMessage:;
- (void)onReceivedRevenueInteractEnabledMessage:;
- (id)pkApi;
- (id)pkProvider;
- (id)playModel;
- (BOOL)realSEIInteractMode;
- (void)receivePKDataFromMessage:;
- (void)requestBattleDataWithForceChangePKStatus:source:channelID:;
- (long long)requestCurrentCount;
- (void)requestListWithForceChangePKStatus:source:channelID:;
- (unsigned long long)requestSourceByBattleStatsSource:;
- (BOOL)revenueInteractStart;
- (id)roomModel;
- (id)seiInteractModeBackUpTimer;
- (BOOL)seiOnInteractMode;
- (id)seiResult;
- (void)setBackupCountdownInterval:;
- (void)setCurrentChannelID:;
- (void)setDisposable:;
- (void)setFetchPKDataSuccess:;
- (void)setHasComponentUnmount:;
- (void)setHasDisableVR:;
- (void)setIsCountingDown:;
- (void)setIsFirstSEI:;
- (void)setIsRequestingPKDataApi:;
- (void)setLastSEI:;
- (void)setMultiNormalSwitchPKFlag:;
- (void)setPkApi:;
- (void)setPkProvider:;
- (void)setPkmodel:;
- (void)setPlayModel:;
- (void)setRealSEIInteractMode:;
- (void)setRequestCurrentCount:;
- (void)setRequestMaxCount:;
- (void)setRevenueInteractStart:;
- (void)setRoomModel:;
- (void)setSeiInteractModeBackUpTimer:;
- (void)setSeiOnInteractMode:;
- (void)setSeiResult:;
- (void)startBackupTimer;
- (void)startLinkMicExternalSceneHandleWithForceChangePKStatus:source:channelID:;
- (void)stopSEIInteractModeBackUpTimer;
- (void)subscribedSyncDataUpdatedWithValue:oldVersion:newVersion:;
- (void)subscribedSyncDataWithValue:version:;
- (void)trackConnectionWatchDuration;
- (void)transfromBigPartyToPK;
- (void)transfromNormalToPK:;
- (void)transfromPKToNormal;
- (unsigned long long)typeToCheckIfLaterThanWhenReuseSEI;
- (void)dealloc;
- (id)messageHandler;
- (void).cxx_destruct;
- (void)setMessageHandler:;
- (id)timeoutTimer;
- (void)setTimeoutTimer:;
- (id)currentChannelID;
@end
