@interface IESLiveMultiCameraStore : NSObject
@property (nonatomic) <IESLiveRoomServiceAdapter> room;
@property (nonatomic) HTSLiveEpisodeExtraInfo extraInfo;
@property (nonatomic) IESLiveRelatedLiveEntryItem cameraEntryItem;
@property (nonatomic) IESLiveRelatedLivePanelTabModel cameraTabModel;
@property (nonatomic) IESLiveMultiCameraListView cameraListView;
@property (nonatomic) UILabel paidTagLabel;
@property (nonatomic) BOOL hasTrackPortraitShow;
@property (nonatomic) BOOL hasTrackLandscapeShow;
@property (nonatomic) BOOL hasChangeCamera;
@property (nonatomic) HTSEventContext trackContext;
@property (nonatomic) @? autoOpenTabPanelCallBack;
@property (nonatomic) @? userInteractAction;
@property (nonatomic) @? updateVisibleCallBack;
@property (nonatomic) @? openTabPanelCallBack;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)cameraEntryItem;
- (BOOL)hasChangeCamera;
- (id)autoOpenTabPanelCallBack;
- (id)cameraListView;
- (id)cameraListViewWithType:;
- (id)cameraTabModel;
- (BOOL)checkEnableShowPaidTag;
- (BOOL)didConnectToAnchor;
- (void)didSetAttachingDIContext;
- (BOOL)enableAutoOpenMultiCameraListPanel;
- (BOOL)hasTrackLandscapeShow;
- (BOOL)hasTrackPortraitShow;
- (void)hiddenPaidTag:;
- (BOOL)needRequestFullData:;
- (void)notifyMainCameraTitleChanged;
- (void)onCameraWillChangeTo:source:;
- (void)openMultiCameraListPanelIfNeed;
- (id)openTabPanelCallBack;
- (void)p_validCurCamera;
- (void)paidStreamDidChangePaidStatusForOtherCamera:scene:;
- (void)paidStreamTrialDidPaid:;
- (id)paidTagLabel;
- (id)paidTagShowedKey;
- (id)panelAutoShowedKey;
- (void)selectCameraOutside:;
- (void)setAutoOpenTabPanelCallBack:;
- (void)setCameraEntryItem:;
- (void)setCameraListView:;
- (void)setCameraTabModel:;
- (void)setExtraInfo:;
- (void)setHasChangeCamera:;
- (void)setHasTrackLandscapeShow:;
- (void)setHasTrackPortraitShow:;
- (void)setOpenTabPanelCallBack:;
- (void)setPaidTagLabel:;
- (void)setTrackContext:;
- (void)setUpdateVisibleCallBack:;
- (void)setUserInteractAction:;
- (void)streamPlayerDidReadyToRender;
- (id)trackContext;
- (void)trackEnterViewClick;
- (void)trackEnterViewShow;
- (void)trackMultiCameraPanelShow;
- (void)trackMultiCameraUpdateWithParams:;
- (void)trackerVSSubCameraPullStreamFirstFrame:;
- (void)tryOpenRelatedLivePanel;
- (void)updateEntryVisible;
- (void)updateListViewIfNeed;
- (void)updateMultiCameraInfoNeedTrack:trackParameters:completion:;
- (id)updateMultiCameraInfoWithEpisodeExtra:;
- (void)updateMultiCameraMessage:;
- (void)updatePaidCameraStatus;
- (id)updateVisibleCallBack;
- (id)userInteractAction;
- (void).cxx_destruct;
- (id)room;
- (void)setRoom:;
- (void)messageReceived:;
- (id)extraInfo;
- (id)initWithRoom:;
- (void)mount;
@end
