@interface IESLiveFeedAudioMultiKTVStageView : UIView
@property (nonatomic) @ latestMessage;
@property (nonatomic) <IESLivePlayerProtocol> player;
@property (nonatomic) IESLiveLinkmicRoomEnterTracker roomEnterTracker;
@property (nonatomic) IESLiveLinkmicPreviewLoadTracker previewLoadTracker;
@property (nonatomic) HTSLiveUser roomOwner;
@property (nonatomic) <IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) IESLiveFeedAudioStageViewExtraModel extraModel;
@property (nonatomic) BOOL smallMode;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)allSeatProviderViews;
- (void)configWithListModel:;
- (id)currentKTVContainerView;
- (id)currentKTVStageView;
- (BOOL)enableUGCMV;
- (id)extraModel;
- (id)guestListViewFrame;
- (void)handleSEIData:;
- (void)handleSEIParseResult:;
- (id)initWithFrame:roomOwner:roomModel:extra:;
- (id)ktvPreStreamContext;
- (id)latestMessage;
- (void)loadStageView;
- (void)onMessageReceivedFromPrestream:withDict:;
- (id)previewLoadTracker;
- (id)roomEnterTracker;
- (id)roomModel;
- (void)setExtraModel:;
- (void)setLatestMessage:;
- (void)setPreviewLoadTracker:;
- (void)setRoomEnterTracker:;
- (void)setRoomModel:;
- (void)setSmallMode:;
- (BOOL)smallMode;
- (void)smoothEnterRoomFromPreview;
- (void)smoothExitRoomToPreview;
- (id)stageInsetsForAdapterSize:;
- (void)updateAnchorUser:;
- (void)updateStageMessageIfNeed;
- (id)player;
- (void).cxx_destruct;
- (void)setPlayer:;
- (id)roomOwner;
- (void)setRoomOwner:;
@end
