@interface IESLiveVoiceCommonPanelView : IESLiveCommentExpandDetailView
@property (nonatomic) IESLiveVoicePanelViewModel viewModel;
@property (nonatomic) double recordBtnSize;
@property (nonatomic) double recordBtnStaticBgSize;
@property (nonatomic) double recordTopOffset;
@property (nonatomic) IESLiveVoicePanelButton recordButton;
@property (nonatomic) UIView recordBtnAnimationBackground;
@property (nonatomic) UIView recordBtnStaticBackground;
@property (nonatomic) UILabel tipLabel;
@property (nonatomic) IESLiveVoiceMsgSendTipView tipView;
@property (nonatomic) BOOL currentLongpressInside;
@property (nonatomic) NSString tipLabelText;
@property (nonatomic) NSString buttonImageName;
@property (nonatomic) NSString buttonBackgroundColor;
- (id)buttonImageName;
- (void)recordBtnCancel;
- (double)recordTopOffset;
- (void)addBackgroundAnimation;
- (void)animationChangeOpacity:hide:;
- (void)changeGroupOpacityIsEnd:;
- (BOOL)currentLongpressInside;
- (void)longPressRecordBtn:;
- (id)recordBtnAnimationBackground;
- (void)recordBtnDown;
- (void)recordBtnMoveInside;
- (void)recordBtnMoveOutside;
- (double)recordBtnSize;
- (id)recordBtnStaticBackground;
- (double)recordBtnStaticBgSize;
- (void)recordBtnUpInside;
- (void)recordBtnUpOutside;
- (void)removeBackgroundAnimation;
- (void)setButtonImageName:;
- (void)setCurrentLongpressInside:;
- (void)setRecordBtnAnimationBackground:;
- (void)setRecordBtnSize:;
- (void)setRecordBtnStaticBackground:;
- (void)setRecordBtnStaticBgSize:;
- (void)setRecordTopOffset:;
- (void)setTipLabelText:;
- (void)setupGesture;
- (id)tipLabelText;
- (id)viewModel;
- (id)initWithViewModel:;
- (void).cxx_destruct;
- (void)setViewModel:;
- (id)tipLabel;
- (void)setTipLabel:;
- (void)setupUI;
- (id)buttonBackgroundColor;
- (void)setButtonBackgroundColor:;
- (id)tipView;
- (void)setTipView:;
- (id)recordButton;
- (void)setRecordButton:;
@end
