@interface IESLiveVSGiftListManager : NSObject
@property (nonatomic) <IESLiveVSGiftListAPI> api;
@property (nonatomic) IESLiveComponentContext componentContext;
@property (nonatomic) GiftListResponse_Data cachedGiftListModel;
@property (nonatomic) IESLiveVSFetchNewGiftTaskThrottle taskThrottle;
@property (nonatomic) BOOL isFetchingNewGift;
@property (nonatomic) NSMutableArray giftListUpdatedBlocks;
@property (nonatomic) NSMutableArray giftsInfoUpdatedBlocks;
@property (nonatomic) NSString cachedGiftListLogID;
@property (nonatomic) <IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) HTSLiveEpisode itemRoom;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)giftWithGiftID:;
- (void)p_loadLocalData;
- (id)cachedGiftListLogID;
- (id)cachedGiftListModel;
- (id)componentContext;
- (id)currentGiftListLogID;
- (id)currentGiftListModel;
- (id)currentGiftsInfo;
- (void)fetchGiftListFromScene:completion:;
- (void)fetchGiftListFromScene:secGuestID:completion:;
- (id)giftListUpdatedBlocks;
- (id)giftsInfoUpdatedBlocks;
- (id)initWithVSComponentContext:;
- (BOOL)isFetchingNewGift;
- (id)itemRoom;
- (id)p_giftList;
- (id)p_giftWithGiftID:;
- (id)p_giftsInfo;
- (void)p_loadLocalGiftListModelWithCompletion:;
- (void)p_receivedNewGift:completion:;
- (void)prefetchGiftList;
- (void)receivedNewGift:completion:;
- (void)registerGiftListUpdatedBlock:;
- (void)registerGiftsInfoUpdatedBlock:shouldSkipFirst:;
- (id)roomModel;
- (void)scheduleFetchNewGiftTask:;
- (void)scheduleUnionTask:;
- (void)setCachedGiftListLogID:;
- (void)setCachedGiftListModel:;
- (void)setComponentContext:;
- (void)setGiftListUpdatedBlocks:;
- (void)setGiftsInfoUpdatedBlocks:;
- (void)setIsFetchingNewGift:;
- (void)setItemRoom:;
- (void)setRoomModel:;
- (void)setTaskThrottle:;
- (id)taskThrottle;
- (void)ts_fetchGiftListWithParams:duration:error:;
- (void)dealloc;
- (void).cxx_destruct;
- (id)api;
- (void)setApi:;
@end
