@interface IESLiveSaaSLotteryFragment : IESLiveRoomComponent
@property (nonatomic) IESLiveSaaSLotteryStore store;
@property (nonatomic) IESLiveSaaSLotteryFloatingView lotteryFloatingView;
@property (nonatomic) <IESLiveSaaSLotteryActions> actionCreator;
@property (nonatomic) <IESLiveSaaSInternalRouter> internalRouter;
@property (nonatomic) <IESLiveSaaSURLSchemaHandler> schemaURLHandler;
@property (nonatomic) <IESLiveSaaSAuthorizationService> authService;
@property (nonatomic) BOOL lotteryPannelViewShowing;
@property (nonatomic) BOOL shouldForbidInteract;
@property (nonatomic) NSString fobidInteractToast;
@property (nonatomic) HTSLiveToolbarItem anchorLotteryItem;
@property (nonatomic) q lastRejectedlotteryId;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)p_handleTrackContextLotteryInfo;
- (BOOL)p_enableLottery;
- (void)setAuthService:;
- (id)actionCreator;
- (id)anchorLotteryItem;
- (id)authService;
- (void)componentDidMount;
- (void)componentOrientationChanged:;
- (void)componentWillUnmount;
- (void)didSetAttachingDIContext;
- (id)fobidInteractToast;
- (id)internalRouter;
- (BOOL)isLotteryModeEnabled;
- (long long)lastRejectedlotteryId;
- (id)lotteryFloatingView;
- (void)lotteryFloatingViewClicked:;
- (void)lotteryItemClick;
- (void)lotteryItemDidClick;
- (BOOL)lotteryPannelViewShowing;
- (void)monitorLotteryOpenEventWithResultType:lotteryStatus:;
- (void)p_checkAuthorizationAndShowLotteryPanelWithParams:;
- (void)p_createLotteryFloatingViewIfNeedNew;
- (void)p_dismissLottery;
- (void)p_loadLotterButtonIfNeed;
- (void)p_loadLotteryToolbarItem;
- (void)p_realOpenLotteryPanelWithParams:;
- (void)p_setInteraciveDisabled:;
- (void)p_setInteraciveEnabled;
- (void)p_setItemDisabled:;
- (void)p_showLotteryResultView;
- (void)prepareStartLotteryMode;
- (void)receivedLotteryEndForResult:;
- (void)receivedLotteryNotApprovedWithRule:failureReason:message:;
- (void)receivedLotteryStart;
- (void)refreshPermission;
- (id)schemaURLHandler;
- (void)setActionCreator:;
- (void)setAnchorLotteryItem:;
- (void)setFobidInteractToast:;
- (void)setInternalRouter:;
- (void)setLastRejectedlotteryId:;
- (void)setLotteryFloatingView:;
- (void)setLotteryPannelViewShowing:;
- (void)setSchemaURLHandler:;
- (void)setShouldForbidInteract:;
- (BOOL)shouldForbidInteract;
- (BOOL)shouldShowFirstRedDot;
- (BOOL)shouldWGameXInviteLottery;
- (void)tr_clickLotteryIconEvent;
- (void)tr_showLotteryFloatEvent;
- (void)dealloc;
- (void)setStore:;
- (id)initWithStore:;
- (void).cxx_destruct;
- (id)store;
+ (id)componentWithRoom:trackContext:componentContext:;
+ (long long)preferredLoadPhase;
@end
