@interface IESLiveGuestBattleResourceManager : IESLiveMultiBaseResourceManager
@property (nonatomic) NSArray guestBattleEffects;
@property (nonatomic) NSMutableDictionary winnerStickerMap;
@property (nonatomic) IESEffectModel loserSticker;
@property (nonatomic) q winnerLevel;
@property (nonatomic) @? winnerBlock;
@property (nonatomic) @? loserBlock;
- (id)heartbrokenName;
- (id)hot_battle_anim;
- (void)setWinnerBlock:;
- (void)setWinnerLevel:;
- (void)cleanGuestBattleEffectComplete;
- (id)crown_icon:;
- (id)crown_upgrade_anim:;
- (void)downloadGuestBattleEffects;
- (void)downloadGuestBattleStickerIfNeeded:;
- (id)getBeautyEffectIdWithRole:level:;
- (id)guestBattleEffects;
- (void)heartbrokenEffect:;
- (id)heartbroken_anim;
- (id)heartbroken_appear;
- (id)heartbroken_icon;
- (id)loserBlock;
- (id)loserSticker;
- (id)loser_larger_anim;
- (void)monitorDownloadResultEffect:error:;
- (void)monitorDressConfigErrorWithStatus:error:;
- (id)normal_icon;
- (id)panel_rule_img;
- (id)resourceURLWithKey:resourceName:;
- (void)setGuestBattleEffects:;
- (void)setLoserBlock:;
- (void)setLoserSticker:;
- (void)setWinnerStickerMap:;
- (id)settle_anim;
- (id)sprint_battle_anim;
- (id)start_anim;
- (id)themeConfig;
- (void)tryInsertDressSticker:;
- (void)tryInsertLevelSticker:;
- (id)winnerBlock;
- (void)winnerEffect:complete:;
- (long long)winnerLevel;
- (id)winnerStickerMap;
- (id)winner_appear;
- (id)winner_larger_anim:;
- (id)winner_victory_anim;
- (id)background;
- (id)init;
- (void).cxx_destruct;
@end
