@interface IESLivePKAndMutliLinkSettingPanel : IESLiveRevenueInteractPopupViewController
@property (nonatomic) q settingType;
@property (nonatomic) NSArray pkItemInfos;
@property (nonatomic) NSArray multiLinkItemInfos;
@property (nonatomic) UITableView settingListView;
@property (nonatomic) HTSLivePKApi pkApi;
@property (nonatomic) HTSLiveInteractiveAPIV2 interactAPI;
@property (nonatomic) NSMutableArray pkSettingItems;
@property (nonatomic) NSArray multiLinkerSettingItems;
@property (nonatomic) NSMutableArray pkInviteSettingChildrenIndexList;
@property (nonatomic) BOOL linkEnabled;
@property (nonatomic) BOOL multiLinkEnabled;
@property (nonatomic) BOOL defaultLargeLayoutEnabled;
@property (nonatomic) BOOL noFollowAuth;
@property (nonatomic) BOOL sendGiftToOthers;
@property (nonatomic) q multiLinkerSubItemsCount;
@property (nonatomic) NSString inviteRejectTemporaryText;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setPkItemInfos:;
- (void)setInteractAPI:;
- (void)setSettingType:;
- (id)settingListView;
- (id)cellWithIndex:section:;
- (BOOL)defaultLargeLayoutEnabled;
- (BOOL)followingFollowedLinkEnabled;
- (BOOL)hourlyRankLinkEnabled;
- (id)initWithSettingType:;
- (id)interactAPI;
- (id)inviteRejectTemporaryText;
- (BOOL)multiLinkEnabled;
- (id)multiLinkItemInfos;
- (id)multiLinkerSettingItems;
- (long long)multiLinkerSubItemsCount;
- (BOOL)noFollowAuth;
- (void)onSetupNavBar:;
- (void)p_animationUpdateWithValue:index:;
- (void)p_builSettingView;
- (void)p_buildMultiLinkSettingDataSource;
- (void)p_buildPKSettingDataSource;
- (id)p_makeSwitchItemWithTitle:initialValue:style:;
- (id)p_pkSettingCellFromItemInfo:;
- (void)p_reload;
- (void)p_showChangeTimeVC;
- (void)p_showSubPanelWithItem:;
- (void)p_showVolumeUpVC;
- (void)p_trackAntionWithItem:;
- (void)p_updateBlockListDataSource;
- (void)p_updateSetting:completion:;
- (void)p_updateSetting:withValue:completion:;
- (id)pkApi;
- (id)pkInviteSettingChildrenIndexList;
- (id)pkItemInfos;
- (id)pkSettingItems;
- (BOOL)popularityRankLinkEnabled;
- (BOOL)searchLinkEnabled;
- (BOOL)sendGiftToOthers;
- (void)setDefaultLargeLayoutEnabled:;
- (void)setFollowingFollowedLinkEnabled:;
- (void)setHourlyRankLinkEnabled:;
- (void)setInviteRejectTemporaryText:;
- (void)setMultiLinkEnabled:;
- (void)setMultiLinkItemInfos:;
- (void)setMultiLinkerSettingItems:;
- (void)setMultiLinkerSubItemsCount:;
- (void)setNoFollowAuth:;
- (void)setPKSwitchSettingFromSettings:itemInfo:;
- (void)setPkApi:;
- (void)setPkInviteSettingChildrenIndexList:;
- (void)setPkSettingItems:;
- (void)setPopularityRankLinkEnabled:;
- (void)setSearchLinkEnabled:;
- (void)setSendGiftToOthers:;
- (void)setSettingListView:;
- (void)showPKTermDetailView;
- (void)trackActionWithItem:isOn:partition:;
- (void)trackDefualtLargeLayoutSettingClicked:;
- (void)trackDefualtLargeLayoutSettingShow;
- (void)dismiss;
- (id)tableView:cellForRowAtIndexPath:;
- (void)setLinkEnabled:;
- (id)tableView:viewForHeaderInSection:;
- (void)tableView:didSelectRowAtIndexPath:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (double)tableView:heightForHeaderInSection:;
- (long long)tableView:numberOfRowsInSection:;
- (void)viewDidLoad;
- (long long)numberOfSectionsInTableView:;
- (double)tableView:heightForFooterInSection:;
- (id)tableView:viewForFooterInSection:;
- (long long)settingType;
- (BOOL)linkEnabled;
@end
