@interface IESLiveRoomBattleTrackHandler : NSObject
@property (nonatomic) <IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) HTSEventContext trackContext;
@property (nonatomic) <IESLiveRoomBattleProvider> roomBattleProvider;
@property (nonatomic) IESLiveInteractionBattleFullLinkMonitor monitor;
@property (nonatomic) NSMutableDictionary startLoadTimestampDict;
@property (nonatomic) BOOL isStartHandler;
@property (nonatomic) q guestCntBeforeSwitchScene;
@property (nonatomic) q guestCntAfterSwitchScene;
@property (nonatomic) NSString requestPage;
- (void)setRequestPage:;
- (id)anchorTypeStr;
- (id)appendCommonExtra:;
- (long long)guestCntAfterSwitchScene;
- (long long)guestCntBeforeSwitchScene;
- (id)initWithTrackContext:room:DIContext:;
- (id)invitePageStr;
- (BOOL)isStartHandler;
- (id)keyStrWithkey:;
- (void)monitorIMWithName:message:extra:;
- (void)monitorStartRoomBattleLoadDurationIfNeed;
- (void)monitorWithAPIPath:requestTimestamp:error:response:extra:;
- (void)monitorWithName:extra:eventType:;
- (void)monitorWithName:extra:eventType:metric:;
- (id)playStageWithStatus:;
- (void)recordTimestampWithKey:;
- (void)recordTimestampWithKey:timestamp:;
- (id)requestPage;
- (id)roomBattleProvider;
- (id)roomBattleTrackExtra;
- (id)roomModel;
- (void)setGuestCntAfterSwitchScene:;
- (void)setGuestCntBeforeSwitchScene:;
- (void)setIsStartHandler:;
- (void)setRoomBattleProvider:;
- (void)setRoomModel:;
- (void)setStartLoadTimestampDict:;
- (void)setTrackContext:;
- (id)startLoadTimestampDict;
- (id)trackContext;
- (void)trackWithEvent:extra:;
- (id)userTypeStr;
- (void)setMonitor:;
- (void).cxx_destruct;
- (id)monitor;
@end
