@interface IESLiveBigPartyCameraPreviewViewWrapper : NSObject
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} originFrame;
@property (nonatomic) UIView cameraPreview;
@property (nonatomic) IESLiveInteractionLayout layout;
@property (nonatomic) BOOL isInAnimation;
@property (nonatomic) @? insertingBlock;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setOriginFrame:;
- (void)addCameraPreviewToOriginViewStackIfNeeded;
- (id)anchorCameraTargetFrameWithLayout:;
- (id)cameraEffectProvider;
- (id)cameraPreview;
- (id)insertingBlock;
- (BOOL)isInAnimation;
- (void)layoutTouchableViewWithRect:;
- (void)onAnchorPreviewInsertToSlotUsingBlock:;
- (id)originFrame;
- (void)regenerateCameraPreview;
- (void)removeCameraPreview;
- (void)resetOriginFrame;
- (void)resumeOrigin;
- (void)setCameraCornerHidden:;
- (void)setCameraPreview:;
- (void)setInsertingBlock:;
- (void)setIsInAnimation:;
- (void)singleViewOptimizationDidDisableWithConfig:;
- (void)singleViewOptimizationDidEnableWithConfig:;
- (void)singleViewOptimizationDidUpdateCropRegion:config:;
- (void)startWithLayout:;
- (void)updateWithCurrentLayout;
- (void)setLayout:;
- (id)layout;
- (void)setup;
- (void).cxx_destruct;
- (void)clean;
@end
