@interface IESLiveBigPartyAnchorFragment : IESLiveRoomComponent
@property (nonatomic) IESLiveBigPartyAnchorStore store;
@property (nonatomic) <IESLiveCompoundSubscription> disposable;
@property (nonatomic) RACDisposable videoCaptureLevelDisposable;
@property (nonatomic) IESLiveAudienceInteractFinishPopupView finishPopupView;
@property (nonatomic) NSArray readedApplications;
@property (nonatomic) BOOL didLayout;
@property (nonatomic) <IESLiveBigPartyAnchorAction> actionCreator;
@property (nonatomic) <IESLiveShareServiceAdapter> shareService;
@property (nonatomic) BOOL invitationGuideHasShown;
@property (nonatomic) BOOL hasStartedLive;
@property (nonatomic) BOOL needResumeChatroom;
@property (nonatomic) BOOL directStartChatRoom;
@property (nonatomic) BOOL previousChangeToFullInteractOnlySelf;
@property (nonatomic) IESLiveInteractionConfirmPanel confirmPanel;
@property (nonatomic) <IESLivePerfSampler> perfSampler;
@property (nonatomic) BOOL isClosingLiveRoom;
@property (nonatomic) IESLiveBigPartyAnchorMuteView anchorMuteView;
@property (nonatomic) BOOL isEnterBackground;
@property (nonatomic) IESLiveBigPartyTransferRouterImpl bigPartyTransferRouter;
@property (nonatomic) IESLiveBigPartyMSequenceAnchorManager mSeqManager;
@property (nonatomic) IESliveAudienceInteractPanelManager panelManager;
@property (nonatomic) <IESLiveInteractionSettingsRouter> interactionSettings;
@property (nonatomic) <IESLiveInteractionLinkerService> linker;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)audienceInteractiveRootPanel:permitApplicationOfUser:extraInfo:;
- (void)bigPartyLayoutDidChangeFrom:to:;
- (id)bizView;
- (id)finishPopupView;
- (BOOL)isInvitingUser:;
- (void)setMSeqManager:;
- (void)setPerfSampler:;
- (BOOL)startByAutoOpen;
- (void)cleanDataSource;
- (void)componentCreate;
- (BOOL)isInPaidLinkmic;
- (void)setVideoCaptureLevelDisposable:;
- (void)showBigPartyPanelWithSeatIndex:;
- (void)acceptConnnectionWithUserID:requestPage:;
- (void)acceptStrongReminderRequestWithUser:requestPage:;
- (id)actionCreator;
- (id)activedList;
- (id)allInteractUserList;
- (id)allSeatProviderViews;
- (id)anchorContainerFrame;
- (id)anchorMuteView;
- (void)applyConnectionWithParams:;
- (void)audienceInteractiveRootPanel:fetchInvitableFriendsListWithCount:completion:;
- (void)audienceInteractiveRootPanel:inviteWithUserID:secUserID:sourcePage:;
- (void)audienceInteractiveRootPanel:inviteWithUserID:secUserID:sourcePage:params:;
- (void)audienceInteractiveRootPanel:onTabShowWithType:;
- (void)audienceInteractiveRootPanel:shareWithClickScene:shareScene:;
- (void)audienceInteractiveRootPanelEndInteract:;
- (void)audienceInteractiveRootPanelNeedToResetWaitingApplications:;
- (void)audienceInteractiveRootPanelOnGuestAutoLinkMic:completion:;
- (BOOL)bigPartyAdminModeEnable;
- (BOOL)bigPartyAdminRightEnable;
- (void)bigPartyDidEnd;
- (void)bigPartyLayoutDidStarted:;
- (BOOL)bigPartyModeEnable;
- (id)bigPartyPanel;
- (id)bigPartyPanelViewModel;
- (id)bigPartyTransferRouter;
- (id)cameraPreview;
- (void)closeBigPartyWithSourceType:confirmAction:;
- (void)componentBindService;
- (void)componentDidAppear;
- (void)componentDidDisappear;
- (void)componentMount;
- (void)componentOrientationChanged:;
- (void)componentUnmount;
- (id)confirmPanel;
- (id)convertActivedToGuest:;
- (unsigned long long)correctCurrentScene;
- (BOOL)couldUnmountComponent;
- (void)currentLayoutUIDidUpdateFrom:to:;
- (BOOL)didConnectToAnchor;
- (void)didCreateTreamFight:;
- (void)didEndKTVWithPlayMode:;
- (void)didStartKTVWithPlayMode:;
- (void)didStartRoomBattle;
- (BOOL)directStartChatRoom;
- (void)directStartIfNeeded;
- (void)directStartWithLayout:;
- (void)directStopWithLayout:;
- (void)directSwitchToLayout:;
- (id)disposable;
- (id)emojiContainerForUserID:isInteractiveEmoji:;
- (BOOL)enableAudienceLinkMic;
- (BOOL)enableCameraRemoteControl;
- (BOOL)enableEditSeatName;
- (double)giftOffsetHeight;
- (id)guestBattleUIAdaptor;
- (id)guestInfoList;
- (id)guestListViewFrame;
- (id)guestsListView;
- (void)handlePauseAction;
- (BOOL)hasDealWithFirstSEI;
- (BOOL)hasStartedLive;
- (id)interactUserList;
- (void)interactionLinkerService:didCloseWithContext:;
- (void)interactionLinkerService:interactListDidChangeFrom:to:;
- (void)interactionLinkerService:linkerOccurError:;
- (void)interactionLinkerService:localSmallWindowSessionCreated:;
- (void)interactionLinkerService:muteStateDidChange:reason:;
- (void)interactionLinkerService:onSwitchMixTypeResult:isMixOnClient:;
- (void)interactionLinkerServiceAppDidActive:;
- (void)interactionLinkerServiceAppResignActive:;
- (void)interactionLinkerServiceInteractDidEnd:;
- (void)interactionLinkerServiceInteractDidStart:;
- (void)interactionLinkerServiceInteractPrepareWillReady:;
- (void)interactionLinkerServiceInteractWillStart:;
- (void)interactionPlaymodeDidEnd:;
- (void)interactionPlaymodeDidStart:;
- (id)interactiveEmojiEndPointAnimationContainerForUserID:;
- (BOOL)invitationGuideHasShown;
- (void)inviteWithUserID:secUserID:sourcePage:;
- (BOOL)isApplyingToJoinChannel;
- (BOOL)isAudioCaptureThisTime;
- (BOOL)isClosingLiveRoom;
- (BOOL)isEnlargeGuestLayout;
- (BOOL)isEnlargeGuestLayoutStyle;
- (BOOL)isEnterBackground;
- (BOOL)isEqualStyle;
- (BOOL)isInAnonymousPaidLinkmicWithUserID:;
- (BOOL)isInAudienceLinkmic;
- (BOOL)isInPaidLinkmicNormal;
- (BOOL)isLiveViewVisiable;
- (BOOL)isMiniAppScreenCastRunning;
- (id)linker;
- (id)linkmicHost;
- (id)mSeqManager;
- (void)mountDidFinishForLevel:;
- (void)muteSelf:;
- (void)muteSelfDirectly:;
- (void)muteSelfForKTVSing:;
- (BOOL)needResumeChatroom;
- (double)offsetYOfAnchorInteractiveEmojiEndPointAnimationContainer;
- (void)onAnchorClickSelf:;
- (void)onClickInteractEntranceItem;
- (id)onlineUserWrapper:;
- (void)openPaidLimitLinkTimeSettingPanelWithGuest:;
- (id)ownEmojiContainerForUserID:;
- (void)p_addLinkSettingToolBarItem;
- (BOOL)p_enabledPaidLinkmicAddPrice;
- (void)p_hideAnchorMuteView;
- (unsigned long long)p_normalizeSocialScene:;
- (void)p_resumeBigPartyLayout;
- (void)p_showAnchorMuteView;
- (void)p_showAnchorOperationActionSheetForOtherLinkerGuest:;
- (void)p_showSettingGuidePanel;
- (void)p_trackAdminLinkSettingChangeShow;
- (void)p_trackAdminLinkSettingChangeSuccess;
- (void)p_trackAnchorNewConnectionPanelShow;
- (void)p_trackFeedbackConfirmClick;
- (void)p_trackFeedbackUploaded;
- (void)p_trackFeedbackViewShow;
- (void)p_trackGuestConnectAction:;
- (void)p_triggerInvitationGuideIfNeeded;
- (void)paidLinkmicDidReceiveAddPriceMessage:;
- (void)paidLinkmicOpenStatusChanged:;
- (id)panelManager;
- (void)pauseAnchorLiveWithType:;
- (id)perfSampler;
- (id)pkAudienceLinkmicMediaService;
- (BOOL)playerBeInBigPartyLayoutStyle;
- (id)playerFrameWithOriginFrame:;
- (void)prepareAnchorLive;
- (BOOL)previousChangeToFullInteractOnlySelf;
- (unsigned long long)previousScene;
- (id)readedApplications;
- (id)rootPanelTopRightItemWithPosition:;
- (void)setActionCreator:;
- (void)setAnchorMuteView:;
- (void)setBigPartyTransferRouter:;
- (void)setConfirmPanel:;
- (void)setDidLayout:;
- (void)setDirectStartChatRoom:;
- (void)setDisposable:;
- (void)setFinishPopupView:;
- (void)setHasStartedLive:;
- (void)setInvitationGuideHasShown:;
- (void)setIsClosingLiveRoom:;
- (void)setIsEnterBackground:;
- (void)setLinker:;
- (void)setNeedResumeChatroom:;
- (void)setPanelManager:;
- (void)setPreviousChangeToFullInteractOnlySelf:;
- (void)setReadedApplications:;
- (void)setShareService:;
- (void)shareLiveRoomWithScene:;
- (id)shareService;
- (BOOL)shouldSendBackgroundSignalWhenAppActiveStateChange;
- (BOOL)shouldSendBackgroundSignalWhenComponentDidDisappear;
- (void)showAdminInteractivePanel;
- (void)showAnchorOperationPanelForGuest:;
- (void)showAnchorOperationPanelForGuest:requestPage:;
- (void)showBigPartyPanelWithSeatIndex:enterFrom:;
- (void)showLinkPanel:source:;
- (void)showThemeCompetitionPanelWithSource:;
- (void)showUserPreView:trackerLabel:;
- (void)startAudienceLinkmic:;
- (void)startLive;
- (void)stopBigPartyInteract;
- (id)targetGuestListView;
- (id)topRightItem;
- (void)trackSeatClickedEventWithExtra:seatIndex:;
- (void)trackSeatHeadClickedWithUser:;
- (unsigned long long)tryToShowInvitePanelWithIsTask:activityName:;
- (unsigned long long)tryToStartApplyProcessingWithIsTask:activityName:applyType:applySource:;
- (int)uilayout;
- (void)updateWithLiveCoreExtInfo:rtcExtInfo:;
- (BOOL)userInActiveList:;
- (BOOL)userInActiveOrWaitingList:;
- (void)userProfileWillAppear;
- (id)videoCaptureLevelDisposable;
- (id)waitingList;
- (void)willFinishedTreamFight:;
- (void)willStopAnchorLive;
- (BOOL)isDynamic;
- (void)setStore:;
- (BOOL)didLayout;
- (unsigned long long)currentScene;
- (void).cxx_destruct;
- (id)store;
- (id)interactionSettings;
- (void)setInteractionSettings:;
- (BOOL)isMute;
+ (BOOL)isMixed;
@end
