@interface IESLiveSaaSPluginLayoutMachine : NSObject
@property (nonatomic) NSArray subScenes;
@property (nonatomic) NSMapTable viewTable;
@property (nonatomic) UIView containerView;
@property (nonatomic) BOOL isAnchor;
@property (nonatomic) BOOL isGiftPanelShow;
@property (nonatomic) BOOL neededLayout;
@property (nonatomic) IESLiveSaaSLayoutRoomContainer roomContainer;
@property (nonatomic) <IESLiveSaaSLayoutContainer> entranceContainer;
@property (nonatomic) <IESLiveSaaSLayoutContainer> operationContainer;
@property (nonatomic) <HTSLiveSaaSLayoutSceneProtocol> layoutScene;
@property (nonatomic) <HTSLiveSmallGiftAction> smallGiftDispatcher;
@property (nonatomic) <HTSLiveSaaSUserEnterAction> userEnterDispatcher;
@property (nonatomic) <IESLiveSaaSLayoutSceneActions> sceneActions;
@property (nonatomic) IESLiveSaaSRightBottomManager rightBottomManager;
@property (nonatomic) IESLiveCombineSubject rightBottomItemSubject;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)removeSubScene:;
- (void)setLayoutScene:;
- (BOOL)isGiftPanelShow;
- (void)addSubScene:;
- (void)addView:withLayoutType:;
- (BOOL)containSubScene:;
- (id)currentRightBottomCombineSubject;
- (id)currentRightBottomItem;
- (void)didAutoRoateToOrientation:;
- (void)didForceUpdateToOrientation:;
- (void)didSetAttachingDIContext;
- (BOOL)enableSetNeedsLayout;
- (id)entranceContainer;
- (BOOL)getGiftPanelShow;
- (void)hideCurrentRightBottomItem;
- (void)hideRightBottomViewWithItem:processResult:;
- (id)initWithContainer:isAnchor:diContext:;
- (void)layoutMessageListToTop:;
- (void)layoutPluginIfNeed;
- (id)layoutScene;
- (BOOL)neededLayout;
- (id)operationContainer;
- (void)registerBottomItemSubject;
- (void)registerContainer:;
- (void)registerContainers;
- (void)registerRunloopObserver;
- (void)removeContainers;
- (void)removeViewWithType:;
- (id)rightBottomItemSubject;
- (id)rightBottomManager;
- (id)roomContainer;
- (void)setEntranceContainer:;
- (void)setGiftPanelShow:;
- (void)setIsAnchor:;
- (void)setIsGiftPanelShow:;
- (void)setNeededLayout:;
- (void)setOperationContainer:;
- (void)setRightBottomItemSubject:;
- (void)setRightBottomManager:;
- (void)setRoomContainer:;
- (void)setSmallGiftDispatcher:;
- (void)setSubScenes:;
- (void)setUserEnterDispatcher:;
- (void)setViewTable:;
- (void)showNextRightBottomItemInQueue;
- (void)showRightBottomViewWithItem:processResult:;
- (id)smallGiftDispatcher;
- (id)subScenes;
- (void)updateMessageListLayout;
- (id)userEnterDispatcher;
- (id)viewOfType:;
- (id)viewTable;
- (id)visibleViewsOfTypes:;
- (void)layoutIfNeeded;
- (void)setScene:;
- (void)addView:;
- (id)containerView;
- (void)setContainerView:;
- (void)removeView:;
- (BOOL)isAnchor;
- (void)setNeedsLayout;
- (void).cxx_destruct;
- (id)sceneActions;
- (void)setSceneActions:;
- (unsigned long long)getScene;
+ (void)ieslivekit_xstone_binding_template;
@end
