@interface IESLiveRoomServiceAdapterImpl : NSObject
@property (nonatomic) IESLiveSaaSLiveRoomModel saasRoom;
@property (nonatomic) HTSLiveRoom mixedRoom;
@property (nonatomic) <IESLiveSaaSRoomService> roomService;
@property (nonatomic) HTSLiveRoomUserInfoModel userInfoModel;
@property (nonatomic) HTSEventContext trackContext;
@property (nonatomic) NSDictionary dictionaryValue;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q startTime;
@property (nonatomic) NSNumber roomID;
@property (nonatomic) BOOL isAnchor;
@property (nonatomic) NSString ownerUserID;
@property (nonatomic) HTSLiveUser owner;
@property (nonatomic) NSString livetypeFromScence;
@property (nonatomic) HTSLiveRoom roomModel;
@property (nonatomic) NSDictionary anchorABMap;
@property (nonatomic) NSMutableDictionary anchorAbmap;
@property (nonatomic) HTSLiveRoomAuthStatus roomAuth;
@property (nonatomic) NSString itemExplicitInfo;
@property (nonatomic) BOOL vSRoom;
@property (nonatomic) q liveTime;
@property (nonatomic) HTSLiveToolBarData toolbarData;
@property (nonatomic) BOOL hasRoomCart;
@property (nonatomic) BOOL hasCommerceGoods;
@property (nonatomic) BOOL isCommerceWhenEnter;
@property (nonatomic) BOOL mSequenceRoom;
@property (nonatomic) BOOL pseudoLiving;
@property (nonatomic) BOOL officialChannelRoom;
@property (nonatomic) HTSLiveOfficialChannelInfo officialChannel;
@property (nonatomic) NSString enterFromAdType;
@property (nonatomic) HTSLiveVSCameraInfo roomSubCamera;
@property (nonatomic) BOOL hasMultiCameraData;
@property (nonatomic) BOOL isMainCamera;
@property (nonatomic) NSString currentCameraID;
@property (nonatomic) HTSLiveVSCameraInfo currentCamera;
@property (nonatomic) NSArray allCameraInfosArray;
@property (nonatomic) NSNumber currentContentID;
@property (nonatomic) NSString cameraTypeTrackStr;
@property (nonatomic) BOOL hasPaidCameraData;
@property (nonatomic) NSInteger currentCameraType;
@property (nonatomic) NSNumber currentMainCameraContentID;
@property (nonatomic) NSString requestId;
@property (nonatomic) NSString logpb;
@property (nonatomic) q groupId;
@property (nonatomic) HTSLiveLifeGrouponInfo lifeGrouponInfo;
@property (nonatomic) HTSLiveMemberMessage selfMemberMsg;
@property (nonatomic) q ntpDiffTime;
@property (nonatomic) BOOL liveTypeThirdParty;
@property (nonatomic) BOOL liveTypeScreenshot;
@property (nonatomic) BOOL liveTypeOfficial;
@property (nonatomic) HTSLiveStreamUrl streamURL;
@property (nonatomic) BOOL hasStreamURL;
@property (nonatomic) q createTime;
@property (nonatomic) BOOL isLandscape;
@property (nonatomic) q osType;
@property (nonatomic) HTSLiveHotRoomInfo hotRoomInfo;
@property (nonatomic) BOOL liveTypeSandbox;
@property (nonatomic) BOOL liveTypeAudio;
@property (nonatomic) HTSLiveRoomIMInfo imInfo;
@property (nonatomic) q liveRoomMode;
@property (nonatomic) NSDictionary rawAdParams;
@property (nonatomic) BOOL isAd;
@property (nonatomic) BOOL hasBonus;
@property (nonatomic) NSNumber currentGameID;
@property (nonatomic) NSInteger mainFeedLabelType;
@property (nonatomic) NSInteger feedLabelType;
@property (nonatomic) NSString cityName;
@property (nonatomic) q autoCover;
@property (nonatomic) HTSLiveRoomSpecificSceneTypeInfo sceneTypeInfo;
@property (nonatomic) HTSLiveDesireInfo desireInfo;
@property (nonatomic) BOOL unDeliveriedUserInPayRoom;
@property (nonatomic) HTSLivePaidLiveData paidLiveData;
@property (nonatomic) HTSLiveGameExtra gameExtra;
@property (nonatomic) HTSLiveEpisodeExtraInfo episodeExtra;
@property (nonatomic) BOOL isVSRoom_Live;
@property (nonatomic) BOOL isVSRoom_FirstPlay;
@property (nonatomic) IESLiveChannelInviteModel channelInviteModel;
@property (nonatomic) NSString currentMainCameraMatchID;
@property (nonatomic) GPBInt64Array currentMainCameraEventIds;
@property (nonatomic) BOOL isVSStreamVertical;
@property (nonatomic) HTSLiveImage cover;
@property (nonatomic) BOOL hasCover;
@property (nonatomic) BOOL withLinkmic;
@property (nonatomic) HTSLiveLinkMic linkMic;
@property (nonatomic) BOOL hasLinkMic;
@property (nonatomic) GPBStringInt64Dictionary linkerMap;
@property (nonatomic) Q linkerMap_Count;
@property (nonatomic) HTSLiveRoomUserAttr livingRoomAttrs;
@property (nonatomic) BOOL hasLivingRoomAttrs;
@property (nonatomic) HTSLiveRoomOthersData others;
@property (nonatomic) BOOL templateRoom;
@property (nonatomic) q templateID;
@property (nonatomic) BOOL isVSOrMediaMixRoom;
@property (nonatomic) HTSLiveRoomInteractData interact;
@property (nonatomic) NSNumber enterTimestamp;
@property (nonatomic) HTSLiveRoomCart roomCart;
@property (nonatomic) HTSLiveActivityRoomSkinInfo activityRoomSkinInfo;
@property (nonatomic) BOOL hasActivityRoomSkinInfo;
@property (nonatomic) HTSLiveLinkerDetail linkerDetail;
@property (nonatomic) q giftMsgStyle;
@property (nonatomic) q fansclubMsgStyle;
@property (nonatomic) q followMsgStyle;
@property (nonatomic) q shareMsgStyle;
@property (nonatomic) q userCount;
@property (nonatomic) NSNumber currentGroupID;
@property (nonatomic) <IESLiveDIContext> attachingDIContext;
@property (nonatomic) HTSLiveEpisodeExtraInfo vsComponentExtraInfo;
@property (nonatomic) RoomPublicScreenInfo publicScreenPlatformInfo;
@property (nonatomic) HTSLiveRoomPlatformComponentsData platformComponentsData;
@property (nonatomic) BOOL isTemplateVerticalStream;
@property (nonatomic) HTSLiveRoomExtra extra;
@property (nonatomic) HTSLiveCastScreenData castScreenData;
@property (nonatomic) NSNumber vsRoomType;
@property (nonatomic) q hasPromotionGames;
@property (nonatomic) HTSLiveRoomGameData gameData;
@property (nonatomic) GPBInt64Array fansGroupAdminUserIdsArray;
@property (nonatomic) HTSLiveAudioBGData audioRoomBgimage;
@property (nonatomic) BOOL hasAudioRoomBgimage;
@property (nonatomic) HTSLiveImage background;
@property (nonatomic) BOOL hasBackground;
@property (nonatomic) HTSLiveAppearance appearance;
@property (nonatomic) BOOL hasAppearance;
@property (nonatomic) NSString idStr;
@property (nonatomic) q webcastSdkVersion;
@property (nonatomic) NSString livePlatformSource;
@property (nonatomic) NSString stamps;
@property (nonatomic) HTSLiveEcomData ecomData;
@property (nonatomic) NSString sharePlatform;
@property (nonatomic) HTSLiveLiveStatusInfo liveStatusInfo;
@property (nonatomic) BOOL isUnionCustom;
@property (nonatomic) NSNumber customUserID;
@property (nonatomic) NSString logID;
@property (nonatomic) NSNumber portalID;
@property (nonatomic) HTSLiveCommentaryRoomInfo commentaryRoomInfo;
@property (nonatomic) NSString recommendMethod;
@property (nonatomic) NSString gameName;
@property (nonatomic) BOOL withKtv;
@property (nonatomic) BOOL withDrawSomething;
@property (nonatomic) NSString originatingRoomID;
@property (nonatomic) HTSLiveImage operationLabel;
@property (nonatomic) NSNumber linkUserID;
@property (nonatomic) NSNumber linkAnchorID;
@property (nonatomic) BOOL hasLinkerDetail;
@property (nonatomic) HTSLiveClientComponent clientComponentData;
@property (nonatomic) NSString insertTaskId;
@property (nonatomic) BOOL withAggregateColumn;
@property (nonatomic) HTSLiveRoomReqUserData reqUser;
@property (nonatomic) BOOL hasReqUser;
@property (nonatomic) NSString roomLiveReason;
@property (nonatomic) q appId;
@property (nonatomic) NSString streamIdStr;
@property (nonatomic) HTSLiveRoomBasisData basis;
@property (nonatomic) BOOL hasBasis;
@property (nonatomic) NSString shareURL;
@property (nonatomic) IOSClientComponent iosClientComponentData;
@property (nonatomic) @ audioModel;
@property (nonatomic) BOOL isMediaPreview;
@property (nonatomic) HTSLiveRoomAnchorData anchorData;
@property (nonatomic) HTSLiveMatchRoomData match;
@property (nonatomic) BOOL replay;
@property (nonatomic) NSString vid;
@property (nonatomic) HTSLivePublicScreenBottomInfo publicScreenBottomInfo;
@property (nonatomic) BOOL hasPublicScreenBottomInfo;
- (void)setRoomService:;
- (id)enterFromAdType;
- (id)anchorAbmap;
- (id)audioRoomBgimage;
- (id)channelInviteModel;
- (void)clearRoom;
- (BOOL)didSetPlaceHolderBg;
- (id)didSetPlaceHolderBgKey;
- (void)didUpdateRoom:;
- (id)enterTimestamp;
- (id)hostAvatarThumbUrlList;
- (BOOL)isCommerceWhenEnter;
- (BOOL)isDouyinMediaRoom;
- (BOOL)isExplainRoom;
- (BOOL)isPaidStream;
- (BOOL)isPaiedUserInPayRoom;
- (BOOL)isPseudoLiving;
- (BOOL)isVRCamera;
- (BOOL)isVRRoom;
- (BOOL)isValidRoom;
- (BOOL)liveTypeAudio;
- (id)livetypeFromScence;
- (id)logpb;
- (id)mixedRoom;
- (id)rawAdParams;
- (id)roomModel;
- (id)roomService;
- (id)roomWithSaaSRoom:;
- (id)saasRoom;
- (id)selfMemberMsg;
- (void)setChannelInviteModel:;
- (void)setDidSetPlaceHolderBg:;
- (void)setDidSetPlaceHolderBgKey:;
- (void)setEnterFromAdType:;
- (void)setMixedRoom:;
- (void)setSaasRoom:;
- (void)setUserInfoModel:;
- (BOOL)shouldShowViceView;
- (id)trackContext;
- (BOOL)useHostInfo;
- (id)userInfoModel;
- (id)viceViewTypeForTrack;
- (id)vrType;
- (id)requestId;
- (long long)scene;
- (BOOL)isAnchor;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:;
- (void)doesNotRecognizeSelector:;
- (BOOL)isAd;
- (id)currentCamera;
- (id)ownerUserID;
@end
