@interface IESLiveSaaSConsumeFollowGuideFragment : IESLiveRoomComponent
@property (nonatomic) IESLiveSaaSConsumeFollowGuideStore store;
@property (nonatomic) NSMutableSet observerSet;
@property (nonatomic) BOOL keyboardShow;
@property (nonatomic) BOOL hasShowFollowGuide;
@property (nonatomic) BOOL mySpecialGiftShow;
@property (nonatomic) BOOL commerceListShow;
@property (nonatomic) IESLiveSaaSConsumeFollowGuidePopupView guidePopup;
@property (nonatomic) NSObject<OS_dispatch_source> loopShowTimer;
@property (nonatomic) NSObject<OS_dispatch_queue> loopShowQueue;
@property (nonatomic) <HTSLiveSaaSFollowGuideActions> guideActionDispatcher;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)pr_isInMseqRoom;
- (void)showConsumeFollowGuidePopupView;
- (void)setObserverSet:;
- (void)bindStore;
- (BOOL)commerceListShow;
- (void)componentDidMount;
- (void)componentDidUnmount;
- (id)guideActionDispatcher;
- (id)guidePopup;
- (BOOL)hasShowFollowGuide;
- (BOOL)keyboardShow;
- (id)loopShowQueue;
- (id)loopShowTimer;
- (void)loopToShowConsumeFollowGuidePopupView;
- (BOOL)mySpecialGiftShow;
- (void)setCommerceListShow:;
- (void)setGuideActionDispatcher:;
- (void)setGuidePopup:;
- (void)setHasShowFollowGuide:;
- (void)setKeyboardShow:;
- (void)setLoopShowQueue:;
- (void)setLoopShowTimer:;
- (void)setMySpecialGiftShow:;
- (void)setStore:;
- (id)observerSet;
- (void).cxx_destruct;
- (id)store;
+ (id)componentWithRoom:trackContext:componentContext:;
@end
