@interface IESLivePrivilegeEntranceProfileView : UIView
@property (nonatomic) IESLiveImageView container;
@property (nonatomic) IESLiveButton fansclubButton;
@property (nonatomic) UILabel fansclubLevelLabel;
@property (nonatomic) UIImage activeFansBgImage;
@property (nonatomic) UIImage inActiveFansBgImage;
@property (nonatomic) BOOL isFirstShow;
@property (nonatomic) IESLivePrivilegeEntranceProfileViewModel viewModel;
@property (nonatomic) <IESLivePrivilegeEntranceProfileViewEventHandler> delegate;
@property (nonatomic) IESLivePrivilegeEntranceProfileAnimationFactory animationFactory;
@property (nonatomic) NSString lastFansclubState;
@property (nonatomic) NSString lastVipState;
@property (nonatomic) NSNumber isShowing;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setIsFirstShow:;
- (id)activeFansBgImage;
- (void)bindState;
- (id)buttonBgImageWithColorArray:;
- (id)fansclubButton;
- (id)fansclubLevelLabel;
- (id)inActiveFansBgImage;
- (BOOL)isFirstShow;
- (id)lastFansclubState;
- (id)lastVipState;
- (void)playFansclubActiveAnimation;
- (void)playFansclubGuideAnimationIfNeeded;
- (void)playShowAnimationIfNeeded;
- (void)setActiveFansBgImage:;
- (void)setFansclubButton:;
- (void)setFansclubLevelLabel:;
- (void)setInActiveFansBgImage:;
- (void)setIsShowing:;
- (void)setLastFansclubState:;
- (void)setLastVipState:;
- (void)tapFansclubButton;
- (void)updateFansclubLevel:;
- (void)updateStateEnableAnimation:;
- (void)viewDidHideFromContainer:;
- (void)viewDidShowOnContainer:;
- (void)setContainer:;
- (id)viewModel;
- (id)isShowing;
- (void)setAnimationFactory:;
- (id)animationFactory;
- (void)setDelegate:;
- (id)container;
- (id)viewSize;
- (id)delegate;
- (void).cxx_destruct;
- (void)setViewModel:;
- (void)setupUI;
- (id)initWithFrame:viewModel:;
@end
