@interface IESLiveVSMessageBoardFragment : IESLiveRoomComponent
@property (nonatomic) HTSLiveToolbarItem toolbarItem;
@property (nonatomic) IESLiveVSMessageBoardApi api;
@property (nonatomic) NSMutableDictionary thumbup_list;
@property (nonatomic) IESLiveVSMessageBoardInputPanelView inputPanelView;
@property (nonatomic) IESLiveVSMessageBoardStore store;
@property (nonatomic) @? openInputPanelJSB;
@property (nonatomic) HTSLiveCommentsSyncData commentDataCache;
@property (nonatomic) NSString thumbupListDataStr;
@property (nonatomic) NSString uiConfig;
@property (nonatomic) q boardItemStatus;
@property (nonatomic) BOOL firstFetchVSMessageBoard;
@property (nonatomic) HTSLiveImage iconImage;
@property (nonatomic) NSString toolbarDataJsonStr;
@property (nonatomic) NSString toolbarDataSchemaURL;
@property (nonatomic) NSString dressInfoForWeb;
@property (nonatomic) InteractDressInfoResponse_DressInfo dressUpModel;
@property (nonatomic) NSMutableArray entityIdArray;
@property (nonatomic) NSString paySchema;
@property (nonatomic) q gradientType;
@property (nonatomic) BOOL hasShowPortrait;
@property (nonatomic) BOOL hasShowLandscape;
@property (nonatomic) BOOL hasOpenMessageBoard;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)dressInfoForWeb;
- (BOOL)hasShowPortrait;
- (void)trackForDressUp;
- (void)trackVSMessageBoardToolbarShow:;
- (long long)boardItemStatus;
- (void)appearDidFinishForLevel:;
- (void)clearInputPanelWithClearDraft:;
- (id)commentDataCache;
- (void)componentBindService;
- (void)componentMount;
- (void)componentOrientationChanged:;
- (long long)dressUpExclusiveMedalRecord:;
- (id)dressUpModel;
- (long long)dressUpThemeSkinRecord:;
- (id)entityIdArray;
- (void)fetchVSMessageBoardDressUpList;
- (BOOL)firstFetchVSMessageBoard;
- (void)getEntityIdArray;
- (void)getVSMessageBoardCommentCacheDataWithKeys:requestFrom:completion:;
- (BOOL)hasOpenMessageBoard;
- (BOOL)hasShowLandscape;
- (void)initFetchVSMessageBoard;
- (void)initVSMessageBoardToolbar;
- (void)inputPanel:commentDidChange:;
- (void)inputPanelDidClickSend:;
- (void)inputPanelDismiss:isSendClicked:;
- (id)inputPanelView;
- (id)openInputPanelJSB;
- (void)openInputView;
- (void)openVSMessageBoardInputPanelWithParameters:completion:;
- (void)openVSMessageBoardViewWithSource:isUserClick:;
- (id)paySchema;
- (void)setBoardItemStatus:;
- (void)setCommentDataCache:;
- (void)setDressInfoForWeb:;
- (void)setDressUpModel:;
- (void)setEntityIdArray:;
- (void)setFirstFetchVSMessageBoard:;
- (void)setHasOpenMessageBoard:;
- (void)setHasShowLandscape:;
- (void)setHasShowPortrait:;
- (void)setInputPanelView:;
- (void)setOpenInputPanelJSB:;
- (void)setPaySchema:;
- (void)setThumbupListDataStr:;
- (void)setThumbup_list:;
- (void)setToolbarDataJsonStr:;
- (void)setToolbarDataSchemaURL:;
- (void)setUiConfig:;
- (void)setVSMessageBoardCommentCacheDataWithKey:value:;
- (BOOL)shouldShowRedDotRecord:;
- (void)subscribedSyncDataUpdatedWithValue:oldVersion:newVersion:;
- (void)subscribedSyncDataWithValue:version:;
- (id)thumbupListDataStr;
- (id)thumbup_list;
- (void)toolbarComponentRemovedReason:extra:;
- (id)toolbarDataJsonStr;
- (id)toolbarDataSchemaURL;
- (void)toolbarReceiveComponent:completion:;
- (id)uiConfig;
- (void)willAutoRotateToOrientation:size:;
- (void)setStore:;
- (void)setIconImage:;
- (void).cxx_destruct;
- (id)store;
- (id)iconImage;
- (id)toolbarItem;
- (void)messageReceived:;
- (void)setToolbarItem:;
- (id)api;
- (long long)gradientType;
- (void)setGradientType:;
- (void)setApi:;
+ (BOOL)isMixed;
+ (BOOL)componentShouldActive:;
@end
