@interface IESLiveSmallAudienceRequestView : UIView
@property (nonatomic) BOOL isAudioModeOn;
@property (nonatomic) <HTSLivePixelBufferCapturer> capturer;
@property (nonatomic) @? onClose;
@property (nonatomic) BOOL waitingForConnect;
@property (nonatomic) <IESLiveRecoder> camera;
@property (nonatomic) UIView controlContainer;
@property (nonatomic) <IESLiveSmallAudienceRequestViewDelegate> delegate;
@property (nonatomic) IESLiveInteractiveAudioView audioBackView;
@property (nonatomic) IESLiveInteractionGuestPreviewView cameraPreview;
@property (nonatomic) double previewCornerRadius;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)addCameraPreview:;
- (id)audioBackView;
- (id)cameraPreview;
- (id)capturer;
- (id)controlContainer;
- (void)didSetAttachingDIContext;
- (BOOL)isAudioModeOn;
- (void)loadBeautyResource;
- (id)removeCameraPreview;
- (void)setAudioBackView:;
- (void)setCameraPreview:;
- (void)setCapturer:;
- (void)setControlContainer:;
- (void)setIsAudioModeOn:;
- (void)setPreviewCornerRadius:;
- (void)setWaitingForConnect:;
- (void)setupViewsOnisAudio:;
- (void)stopAndHidePreView;
- (void)switchCameraSource;
- (void)switchConnectMode;
- (void)updateAudioAnimation:;
- (void)updateAvatarURLList:;
- (void)updateVoiceWaveWithMicDress:userID:;
- (BOOL)waitingForConnect;
- (id)camera;
- (id)init;
- (void)stopCapture;
- (void)dealloc;
- (void)setDelegate:;
- (long long)cameraPosition;
- (id)delegate;
- (void).cxx_destruct;
- (void)willMoveToSuperview:;
- (id)previewSize;
- (void)startPreview;
- (void)stopPreview;
- (void)appDidEnterBackground;
- (void)appDidBecomeActive;
- (double)previewCornerRadius;
- (id)onClose;
- (void)setOnClose:;
- (void)showCameraPreview;
- (unsigned long long)previewFrameRate;
@end
