@interface IESLiveSaaSFeedSquDoubleView : UIView
@property (nonatomic) UIImageView coverImageView;
@property (nonatomic) IESLiveSaaSGradientView maskView;
@property (nonatomic) UIImageView platformImageView;
@property (nonatomic) UIView containerView;
@property (nonatomic) UIImageView avatarImageView;
@property (nonatomic) UIImageView benefitImageView;
@property (nonatomic) double platformImageWidth;
@property (nonatomic) double benefitImageWidth;
@property (nonatomic) UILabel title;
@property (nonatomic) UILabel extraLabel;
@property (nonatomic) UILabel nickNameLabel;
@property (nonatomic) IESLiveSaaSFeedWatermarkView watermarkView;
@property (nonatomic) NSDictionary trackParams;
@property (nonatomic) NSString customEnterMethod;
@property (nonatomic) NSNumber previewBeginTime;
@property (nonatomic) <IESLiveSaaSFeedCardViewDelegate> delegate;
@property (nonatomic) <IESLiveSaaSFeedStreamResolutionDelegate> resolutionDelegate;
@property (nonatomic) BOOL isPreviewing;
@property (nonatomic) UIView coverView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setTrackParams:;
- (id)benefitImageView;
- (double)benefitImageWidth;
- (void)cleanForReuse;
- (id)coverImageView;
- (id)customEnterMethod;
- (id)extraLabel;
- (void)generateLabelImageView:complection:;
- (void)generateLabelWithImage:complection:;
- (id)nickNameLabel;
- (id)platformImageView;
- (double)platformImageWidth;
- (id)previewBeginTime;
- (void)setBenefitImageView:;
- (void)setBenefitImageWidth:;
- (void)setCoverImageView:;
- (void)setCustomEnterMethod:;
- (void)setExtraLabel:;
- (void)setNickNameLabel:;
- (void)setPlatformImageView:;
- (void)setPlatformImageWidth:;
- (void)setPreviewBeginTime:;
- (void)setWatermarkView:;
- (id)trackParams;
- (void)updateData:model:;
- (id)watermarkView;
- (id)maskView;
- (id)containerView;
- (void)setContainerView:;
- (void)setTitle:;
- (id)initWithFrame:;
- (id)title;
- (void).cxx_destruct;
- (void)setMaskView:;
- (id)avatarImageView;
- (void)setAvatarImageView:;
- (void)buildView;
@end
