@interface IESLiveSaaSIMBaseActionCreator : NSObject
@property (nonatomic) <IESLiveMonitor> monitor;
@property (nonatomic) <IESLiveSaaSMessageConfig> messageConfig;
@property (nonatomic) IESLiveSaaSIMBaseDispatcher imDispatcher;
@property (nonatomic) IESLiveSaaSMessageExtraProcessor extraProcessor;
@property (nonatomic) IESLiveSaaSIMBaseClient imClient;
@property (nonatomic) Q scene;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)addSubscriber:forMessageNames:;
- (unsigned long long)decodeScene;
- (void)didRecievePacket:;
- (id)extraProcessor;
- (id)httpParams:;
- (id)imClient;
- (id)imDispatcher;
- (id)initWithDIContext:config:;
- (void)logEvent:params:;
- (id)messageConfig;
- (void)remoteRoomDataReady:;
- (void)setExtraProcessor:;
- (void)setImClient:;
- (void)setImDispatcher:;
- (void)setMessageConfig:;
- (void)setSeiTimestamp:;
- (void)setupWithMessageConfig:;
- (void)startMessageDispatch;
- (void)stopMessageDispatch;
- (void)trackWith:extra:;
- (void)userDidLogin:;
- (void)userDidLogout;
- (void)userDidUpdate:;
- (id)websocketHeaders:;
- (id)websocketParams:;
- (id)websocketUrl;
- (void)setScene:;
- (void)start;
- (void)stop;
- (id)httpUrl;
- (unsigned long long)scene;
- (void)setMonitor:;
- (void).cxx_destruct;
- (id)monitor;
- (long long)defaultTimeout;
@end
