@interface IESLiveBigPartyEqualGuestListView : UIView
@property (nonatomic) IESLiveBigPartyEqualGuestListViewModel viewModel;
@property (nonatomic) <IESLiveInteractionLayoutCanvas> canvas;
@property (nonatomic) NSMutableArray guestInfoViews;
@property (nonatomic) NSMutableArray slotSeperatorsLine;
@property (nonatomic) IESLiveInteractSeatAnimationManager seatAnimationManager;
@property (nonatomic) IESLiveBigPartyGuestInfoView showingView;
@property (nonatomic) <IESLiveInteractiveInviteService> inviteFriendsService;
@property (nonatomic) BOOL isTeamFightMode;
@property (nonatomic) HTSLiveLayerCapturer layerCapture;
@property (nonatomic) BOOL isFirstSlotRender;
@property (nonatomic) NSArray saveOldConfigs;
@property (nonatomic) NSArray saveNewConfigs;
@property (nonatomic) ^{__CFRunLoopObserver=} observer;
@property (nonatomic) q guestListViewNumber;
@property (nonatomic) UIView<IESLiveInteractiveViewAboveListView> viewAboveListView;
@property (nonatomic) NSObject<OS_dispatch_queue> renderSerialQueue;
@property (nonatomic) UIImage originalMeidaCoverImage;
@property (nonatomic) NSArray renderCutSlots;
@property (nonatomic) BOOL isProcessingMeidaCoverImage;
@property (nonatomic) IESLiveTeamFightBorderView borderView;
@property (nonatomic) IESLiveChatRoomInviteGuideHelper inviteGuideHelper;
@property (nonatomic) BOOL isAllGuestInfoViewHidden;
@property (nonatomic) <IESLiveInteractXplayGameInterface> xplayGameInterface;
@property (nonatomic) <IESLiveBigPartyEqualGuestListViewBackgroundUpdator> backgroundUpdator;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) <IESLiveBigPartyEqualGuestsListViewDelegate> delegate;
@property (nonatomic) NSMutableDictionary infoViewPixelBuffers;
@property (nonatomic) @? updatedInfoViewPixel;
@property (nonatomic) @? inviteFriendBlock;
- (void)asyncRenderImage:inImageView:cutSlots:slotContainer:completion:;
- (id)frameOfSlotView;
- (void)punishTeamFight;
- (void)finishTeamFight;
- (long long)hiddenSeatCount;
- (BOOL)isInPaidLinkmic;
- (BOOL)isTeamFightMode;
- (void)setIsProcessingMeidaCoverImage:;
- (void)setShowingView:;
- (void)triggerInvitationGuideAnimation;
- (id)allSeatProviderViews;
- (id)aspectFillRecWithImage:targetSize:;
- (void)asyncRenderImage:targetFrame:cutRects:completion:;
- (id)backgroundUpdator;
- (void)bindCanvas:;
- (void)bindGuestInfoViewsWithCanvas:;
- (void)bindViewModel;
- (BOOL)checkHasEmptySeat;
- (void)cleanSnapchatBuffers;
- (void)didClickApplyView:;
- (void)didClickGuestInviteView:;
- (void)didClickInfoView:;
- (void)didClickInviteWithUser:andInRoom:;
- (void)didClickUserInfo:guestInviteView:;
- (void)didClickUserInvite:guestInviteView:;
- (void)didHideGuestInviteView:;
- (void)didSetAttachingDIContext;
- (void)didUpdateTeamFightInfo;
- (id)emojiContainerForUserID:;
- (BOOL)enablePictureMixer;
- (id)fanTicketViewMap;
- (long long)findEmptySeatIndex;
- (id)findTheEmptyView;
- (id)frameOfSlotViewWithContainer:;
- (id)generateGuestInfoViewWithViewModel:totalCount:index:;
- (id)guestBattleInfoViewMap;
- (id)guestBattleScoreViewMap;
- (id)guestInfoViewMap;
- (id)guestInfoViews;
- (long long)guestListViewNumber;
- (BOOL)handleLayoutOperationView;
- (void)hideEmptyInfoViewIfNeeded;
- (void)infoViewHiddenDidChange:isHidden:;
- (id)infoViewPixelBuffers;
- (id)inviteFriendBlock;
- (id)inviteFriendsService;
- (id)inviteGuideHelper;
- (void)inviteGuideViewWillHiding;
- (void)inviteGuideViewWillShowing;
- (BOOL)isAllGuestInfoViewHidden;
- (BOOL)isFirstSlotRender;
- (BOOL)isInPaidLinkmicNormal;
- (BOOL)isProcessingMeidaCoverImage;
- (id)layerCapture;
- (void)notifyUpdateClearScreenState:;
- (void)onFanticketDidSelected:;
- (void)onGuestBattleFinish;
- (void)onGuestBattleSettle;
- (void)onGuestBattleStart;
- (void)onGuestInfoViewTapAcceptLink:;
- (void)onMainGuestInfoViewMediaCoverChanged:;
- (void)onUpdateSnapchatWithInfoView:;
- (id)originalMeidaCoverImage;
- (void)p_handleGuestInfoViewInvitedView;
- (void)p_removeGuestInfoViewInvitedView;
- (void)p_updateBackGroundViewCutInfo;
- (void)p_updateWithFullActiveList:;
- (void)paidLinkmicOpenStatusChanged:;
- (id)pathWithTargetSize:cutRects:;
- (void)prepareTeamFight;
- (void)processMeidaCoverImageIfNeededWithOriginalImage:;
- (void)registerRunloopObserver;
- (void)removeAllInfoViews;
- (void)removeRunloopObserver;
- (void)removeTeamFightBoarder;
- (void)removeViewAboveListViewIfNeed;
- (id)renderCutSlots;
- (id)renderSerialQueue;
- (unsigned long long)representCountWithTotalCount:index:;
- (id)saveNewConfigs;
- (id)saveOldConfigs;
- (id)searchEmptySeatView;
- (id)seatAnimationManager;
- (void)setBackgroundUpdator:;
- (void)setGuestInfoViews:;
- (void)setGuestListViewNumber:;
- (void)setInfoViewPixelBuffers:;
- (void)setInviteFriendBlock:;
- (void)setInviteFriendsService:;
- (void)setInviteGuideHelper:;
- (void)setIsAllGuestInfoViewHidden:;
- (void)setIsFirstSlotRender:;
- (void)setIsTeamFightMode:;
- (void)setLayerCapture:;
- (void)setOriginalMeidaCoverImage:;
- (void)setRenderCutSlots:;
- (void)setRenderSerialQueue:;
- (void)setSaveNewConfigs:;
- (void)setSaveOldConfigs:;
- (void)setSeatAnimationManager:;
- (void)setSlotSeperatorsLine:;
- (void)setUpdatedInfoViewPixel:;
- (void)setViewAboveListView:;
- (void)setXplayGameInterface:;
- (void)setupGuestInfoViewsWithCanvas:;
- (void)setupGuideHelper;
- (void)setupTeamFightGuestBackground;
- (void)setupViewStepByStep;
- (BOOL)shouldProcessMediaCoverImage;
- (void)showResultTeamFight;
- (void)showSelfDisciplineLikeAnimationByUserId:;
- (void)showTeamFightGuestBg;
- (id)showingView;
- (id)slotSeperatorsLine;
- (BOOL)slotsIsEqual:toSlots:;
- (void)snapchatInfoViewsImmediately;
- (void)startTeamFight;
- (void)updateAnchorSeatName:;
- (void)updateCurrentSinger:;
- (void)updateRoomThemeData:;
- (void)updateRoomThemeWithIconMics:iconMicLock:micBgcolorValue:colorMicLine:colorMicText:;
- (void)updateSeat;
- (void)updateSeatInfos:;
- (void)updateSeparatorGuestViewBg:;
- (void)updateSinger:;
- (void)updateSnapchatWithInfoView:;
- (void)updateWithActiveList:;
- (id)updatedInfoViewPixel;
- (id)viewAboveListView;
- (id)viewWithIndex:;
- (id)viewWithLinkMicID:;
- (id)xplayGameInterface;
- (id)canvas;
- (void)setCanvas:;
- (BOOL)isAdminUser;
- (void)dealloc;
- (id)viewModel;
- (void)setDelegate:;
- (BOOL)isPreview;
- (id)initWithCoder:;
- (BOOL)isAnchor;
- (id)initWithFrame:;
- (id)dataSource;
- (id)delegate;
- (void)setObserver:;
- (void).cxx_destruct;
- (void)setupManager;
- (void)setViewModel:;
- (id)observer;
- (id)borderView;
- (void)setBorderView:;
- (id)initWithFrame:viewModel:;
- (id)slots;
@end
