@interface IESSaaSTIMConversationCoreInfoORM : IESSaaSTIMBaseORM
@property (nonatomic) NSString belongingConversationIdentifier;
@property (nonatomic) q infoVersion;
@property (nonatomic) NSString name;
@property (nonatomic) NSString desc;
@property (nonatomic) NSString icon;
@property (nonatomic) NSString notice;
@property (nonatomic) q ownerID;
@property (nonatomic) NSInteger mode;
@property (nonatomic) NSString ext;
@property (nonatomic) q creatorUid;
@property (nonatomic) NSDictionary extDictionary;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)belongingConversationIdentifier;
- (void)setExt:;
- (void)setInfoVersion:;
- (long long)creatorUid;
- (id)extDictionary;
- (long long)infoVersion;
- (void)setBelongingConversationIdentifier:;
- (void)setCreatorUid:;
- (void)setExtDictionary:;
- (void)setName:;
- (id)desc;
- (id)icon;
- (void)setDesc:;
- (void)setIcon:;
- (void).cxx_destruct;
- (id)name;
- (int)mode;
- (void)setMode:;
- (id)notice;
- (void)setNotice:;
- (long long)ownerID;
- (void)setOwnerID:;
- (id)ext;
+ (id)belongingConversationIdentifier;
+ (id)AllProperties;
+ (id)AnyProperty;
+ (id)PropertyNamed;
+ (id)creatorUid;
+ (id)infoVersion;
+ (id)objectRelationalMappingForWCDB;
+ (id)desc;
+ (id)icon;
+ (id)name;
+ (id)mode;
+ (id)notice;
+ (id)ownerID;
+ (id)ext;
@end
