@interface IMFeatureFlags : NSObject
@property (nonatomic) BOOL conversationPinningMultiDragEnabled;
@property (nonatomic) BOOL conversationPinningTouchdownDimEnabled;
@property (nonatomic) BOOL conversationPinningUsesLastNameForDuplicatesEnabled;
@property (nonatomic) BOOL avatarViewAllowsStaleRendering;
@property (nonatomic) BOOL showAllInstalledMessageApps;
@property (nonatomic) BOOL mentionsKeyboardSuggestionsEnabled;
@property (nonatomic) BOOL macToolbarEnabled;
@property (nonatomic) BOOL macApplicationMetricsGatheringEnabled;
@property (nonatomic) BOOL messageSyncP2Enabled;
@property (nonatomic) BOOL fullTranscriptLoggingEnabled;
@property (nonatomic) BOOL chatCacheEnabled;
@property (nonatomic) BOOL micGroupPhotoEnabled;
@property (nonatomic) BOOL commSafetyUIEnabled;
@property (nonatomic) BOOL commSafetyInternalEnabled;
@property (nonatomic) BOOL businessGreeting;
@property (nonatomic) BOOL threeColumnLayoutEnabled;
@property (nonatomic) BOOL stewieEnabled;
@property (nonatomic) BOOL supplementalLexiconMentionsEnabled;
@property (nonatomic) BOOL uiConsistencyEnabled;
@property (nonatomic) BOOL systemImageAdoptionEnabled;
@property (nonatomic) BOOL isExpanseEnabled;
@property (nonatomic) BOOL improvedPriorityInversionFixEnabled;
@property (nonatomic) BOOL threeAttachmentStackEnabled;
@property (nonatomic) BOOL unitTestableFeatureEnabled;
@property (nonatomic) BOOL unitTestableFeatureForNewPlatformEnabled;
@property (nonatomic) BOOL modernXPCEnabled;
@property (nonatomic) BOOL focusFilteringInConversationListEnabled;
@property (nonatomic) BOOL markUnreadEnabled;
@property (nonatomic) BOOL siriLinkEnabled;
@property (nonatomic) BOOL recentlyDeletedEnabled;
@property (nonatomic) BOOL gelatoCoreEnabled;
@property (nonatomic) BOOL gelatoNoticesEnabled;
@property (nonatomic) BOOL newAudioMessageFlowEnabled;
@property (nonatomic) BOOL messageRetractionEnabled;
@property (nonatomic) BOOL messageRetractionDemoModeEnabled;
@property (nonatomic) BOOL backgroundAudioEnabled;
@property (nonatomic) BOOL messageEditingEnabled;
@property (nonatomic) BOOL messageEditingHistoryViewingEnabled;
@property (nonatomic) BOOL messageEditingBackwardCompatabilityEnabled;
@property (nonatomic) BOOL transcriptSharingEnabled;
@property (nonatomic) BOOL smsSubClassification;
@property (nonatomic) BOOL simBasedFiltering;
@property (nonatomic) BOOL smsFilterForUS;
@property (nonatomic) BOOL smsFilterForUK;
@property (nonatomic) BOOL messagesIniCloudVersion2;
@property (nonatomic) BOOL carrierReportJunk;
@property (nonatomic) BOOL AVLessSharePlayEnabled;
@property (nonatomic) BOOL reducedChatCacheSizeEnabled;
@property (nonatomic) BOOL notificationActionsEnabled;
@property (nonatomic) BOOL templateCapabilityFallbackEnabled;
@property (nonatomic) BOOL tapbackInferenceEnabled;
@property (nonatomic) BOOL SWYAttachmentsEnabled;
@property (nonatomic) BOOL arePreResolvedSiriMatchesEnabled;
- (BOOL)fixIMDPersistenceAgentPriorityInversion;
- (BOOL)isUnknownGroupSendersEnabled;
- (BOOL)isTemplateCapabilityFallbackEnabled;
- (BOOL)isTranscriptSharingEnabled;
- (BOOL)conversationPinningMultiDragEnabled;
- (BOOL)isUnitTestableFeatureForNewPlatformEnabled;
- (BOOL)commSafetyUIEnabled;
- (BOOL)isMessageEditingHistoryViewingEnabled;
- (BOOL)conversationPinningTouchdownDimEnabled;
- (BOOL)isSMSFilterEnabledForUK;
- (BOOL)isCarrierReportJunkEnabled;
- (BOOL)isMessageEditingBackwardCompatabilityEnabled;
- (BOOL)isFocusFilteringInConversationListEnabled;
- (BOOL)isFocusFilteringInConversationListEnabledForMessages;
- (BOOL)isGelatoCoreEnabled;
- (BOOL)isRecentlyDeletedEnabled;
- (BOOL)isSiriLinkEnabled;
- (BOOL)macToolbarEnabled;
- (BOOL)macApplicationMetricsGatheringEnabled;
- (BOOL)avatarViewAllowsStaleRendering;
- (BOOL)isMessagesIniCloudVersion2;
- (BOOL)threeAttachmentStackEnabled;
- (BOOL)threeColumnLayoutEnabled;
- (BOOL)messageSyncP2Enabled;
- (BOOL)isNewAudioMessageFlowEnabled;
- (BOOL)loadAllChatsProgressivelyEnabled;
- (BOOL)improvedPriorityInversionFixEnabled;
- (BOOL)isCKScreenshotTestFeatureFlagMember:withDomain:;
- (BOOL)isSMSFilterEnabledForUS;
- (BOOL)businessGreeting;
- (BOOL)supplementalLexiconMentionsEnabled;
- (BOOL)manuallyAckMessagesEnabled;
- (BOOL)allCallOptionsInNavBarButtonEnabled;
- (BOOL)isBackgroundAudioEnabled;
- (BOOL)certifiedDeliveryEnabled;
- (BOOL)isExpanseEnabled;
- (BOOL)fixIMTranscoderAgentPriorityInversion;
- (BOOL)showAllInstalledMessageApps;
- (BOOL)isSMSSubClassificationEnabled;
- (BOOL)uiConsistencyEnabled;
- (id)CKScreenshotTestFeatureFlagMembers;
- (BOOL)isGreenfieldEnabled;
- (BOOL)isAVLessSharePlayEnabled;
- (BOOL)fullTranscriptLoggingEnabled;
- (BOOL)systemImageAdoptionEnabled;
- (BOOL)mentionsKeyboardSuggestionsEnabled;
- (BOOL)photoAnalysisInSpotlightEnabled;
- (BOOL)isTapbackInferenceEnabled;
- (BOOL)isMessageRetractionDemoModeEnabled;
- (BOOL)isModernXPCEnabled;
- (BOOL)micGroupPhotoEnabled;
- (BOOL)isMessageEditingEnabled;
- (BOOL)isNotificationActionsEnabled;
- (BOOL)messageAppFreezerEnabled;
- (BOOL)arePreResolvedSiriMatchesEnabled;
- (BOOL)isSIMBasedFilteringEnabled;
- (BOOL)stewieEnabled;
- (BOOL)commSafetyInternalEnabled;
- (BOOL)isMarkUnreadEnabled;
- (BOOL)CKScreenshotTestFeatureFlagValue;
- (BOOL)isGelatoNoticesEnabled;
- (BOOL)isReducedChatCacheSizeEnabled;
- (BOOL)chatCacheEnabled;
- (BOOL)fixImagentPriorityInversion;
- (BOOL)isSWYAttachmentsEnabled;
- (BOOL)conversationPinningUsesLastNameForDuplicatesEnabled;
- (BOOL)modernAppPresentationEnabled;
- (BOOL)isMessageRetractionEnabled;
- (BOOL)isUnitTestableFeatureEnabled;
+ (void)testWithFeature:block:;
+ (id)sharedInstance;
+ (id)sharedFeatureFlags;
+ (void)testWithFeature:enabled:block:;
@end
