@interface IMMessagePartSyndicationRange : NSObject
@property (nonatomic) NSString serializedString;
@property (nonatomic) Q serializedVersion;
@property (nonatomic) q syndicationType;
@property (nonatomic) q syndicationStatus;
@property (nonatomic) {_NSRange=QQ} messagePartRange;
@property (nonatomic) NSDate syndicationStartDate;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (id)syndicationStartDate;
- (id)description;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setSyndicationStatus:;
- (long long)syndicationStatus;
- (long long)syndicationType;
- (id)messagePartRange;
- (id)initWithSyndicationType:messagePartRange:syndicationStartDate:;
- (id)initWithSyndicationType:messagePartRange:syndicationStartDate:syndicationStatus:;
- (id)initWithSyndicationAction:;
- (id)serializedString;
- (unsigned long long)serializedVersion;
- (BOOL)_canBeReplacedByRange:;
+ (BOOL)supportsSecureCoding;
+ (id)unarchiveClasses;
+ (id)_stringFromSyndicationType:;
+ (id)_stringFromSyndicationStatus:;
+ (id)serializedStringFromArray:;
+ (id)messageRangeFromTokens_v1:;
+ (id)deserializeSyndicationRangeFromString:;
+ (unsigned long long)serializationVersion;
+ (void)setSerializationVersion:;
+ (id)rangesFromSerializedString:;
+ (id)updateMessagesRanges:withMessagePartSyndicationRanges:didUpdate:;
+ (id)messagePartSyndicationRangeForRange:inRangesArray:;
+ (id)findChangesFromRangeArray:comparedToRangeArray:;
+ (id)minStartDateForRanges:;
+ (id)maxStartDateForRanges:;
@end
