@interface IMUserDefaults : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setClearStateOnLaunch:;
- (BOOL)clearStateOnLaunch;
- (BOOL)appBoolByHostForKey:;
- (void)setAppBool:byHostForKey:;
- (id)appValueForKey:;
- (void)setAppValue:forKey:;
- (void)removeAppValueForKey:;
- (BOOL)appBoolForKey:;
- (void)setAppBool:forKey:;
- (void)setValue:forKey:appID:;
- (void)setMultiple:remove:appID:;
- (void)synchronizeAppID:;
- (id)copyKeyListForAppID:;
- (id)copyMultipleForCurrentKeys:appID:;
- (id)copyValueForKey:appID:;
- (void)setValue:forKey:applicationID:userName:hostName:;
- (void)setMultiple:remove:applicationID:userName:hostName:;
- (void)synchronizeApplicationID:userName:hostName:;
- (id)copyKeyListForApplicationID:userName:hostName:;
- (id)copyMultipleForCurrentKeys:applicationID:userName:hostName:;
- (id)copyValueForKey:applicationID:userName:hostName:;
+ (BOOL)__im_isEngramEnabledForGroups;
+ (id)sharedDefaults;
+ (BOOL)isEngramEnabled;
+ (void)setEnableEngram:;
+ (void)setPhoneNumberValidationMode:;
+ (long long)phoneNumberValidationMode;
+ (void)setPhoneNumberValidationPreflightTestData:;
+ (id)phoneNumberValidationPreflightTestData;
+ (void)setEnableLiveDeliveryWarmUp:;
+ (BOOL)isLiveDeliveryWarmUpEnabled;
+ (BOOL)trustAnyCredential;
+ (BOOL)isWritePushPayloadsToDiskEnabled;
+ (id)writePushPayloadsToDiskPath;
@end
