@interface INCodableAttribute : NSObject
@property (nonatomic) NSNumber displayPriorityRank;
@property (nonatomic) NSArray promptDialogs;
@property (nonatomic) NSArray unsupportedReasons;
@property (nonatomic) NSString _typeString;
@property (nonatomic) NSString _attributeTagKey;
@property (nonatomic) NSString _attributeDisplayPriorityKey;
@property (nonatomic) INCodableDescription _codableDescription;
@property (nonatomic) # _unsafeObjectClass;
@property (nonatomic) # _relationshipValueTransformerClass;
@property (nonatomic) q modifier;
@property (nonatomic) BOOL fixedSizeArray;
@property (nonatomic) NSString propertyName;
@property (nonatomic) NSString displayName;
@property (nonatomic) NSString displayNameID;
@property (nonatomic) BOOL defaultAttribute;
@property (nonatomic) BOOL configurable;
@property (nonatomic) BOOL supportsResolution;
@property (nonatomic) BOOL supportsDynamicEnumeration;
@property (nonatomic) BOOL supportsSearch;
@property (nonatomic) INCodableAttributeMetadata metadata;
@property (nonatomic) INCodableAttributeRelationship relationship;
@property (nonatomic) : getter;
@property (nonatomic) : setter;
@property (nonatomic) q valueType;
@property (nonatomic) # objectClass;
@property (nonatomic) # resolutionResultClass;
@property (nonatomic) NSString entityKeypath;
@property (nonatomic) NSString localizedDisplayName;
@property (nonatomic) q windowSize;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)_codableDescription;
- (long long)windowSize;
- (void)setWindowSize:;
- (void)updateWithDictionary:;
- (id)dictionaryRepresentationWithLocalizer:;
- (long long)modifier;
- (Class)objectClass;
- (id)propertyName;
- (id)__INCodableDescriptionTypeKey;
- (id)relationship;
- (void)_setCodableDescription:;
- (void)setRelationship:;
- (id)metadata;
- (id)__INTypeCodableDescriptionTypeKey;
- (Class)resolutionResultClass;
- (id)__INIntentResponseCodableDescriptionTypeKey;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (void)setDisplayName:;
- (id)displayName;
- (void)setMetadata:;
- (void)encodeWithCoder:;
- (id)localizedDisplayName;
- (id)descriptionAtIndent:;
- (void)setModifier:;
- (void).cxx_destruct;
- (id)__INCodableDescriptionNameKey;
- (id)description;
- (id)localizedDisplayNameWithLocalizer:;
- (id)displayNameID;
- (id)dictionaryRepresentation;
- (long long)valueType;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)_typeString;
- (SEL)setter;
- (BOOL)isConfigurable;
- (void)setConfigurable:;
- (Class)_relationshipValueTransformerClass;
- (id)__INCodableDescriptionEnumTypeKey;
- (id)__INIntentResponseCodableDescriptionEnumTypeKey;
- (id)__INTypeCodableDescriptionEnumTypeKey;
- (id)__INCodableDescriptionTagKey;
- (id)__INIntentResponseCodableDescriptionTagKey;
- (id)__INTypeCodableDescriptionTagKey;
- (id)__INIntentResponseCodableDescriptionNameKey;
- (id)__INTypeCodableDescriptionNameKey;
- (id)__INCodableDescriptionDisplayNameKey;
- (id)__INIntentResponseCodableDescriptionDisplayNameKey;
- (id)__INTypeCodableDescriptionDisplayNameKey;
- (id)__INCodableDescriptionDisplayNameIDKey;
- (id)__INIntentResponseCodableDescriptionDisplayNameIDKey;
- (id)__INTypeCodableDescriptionDisplayNameIDKey;
- (id)__INCodableDescriptionDisplayPriorityKey;
- (id)__INIntentResponseCodableDescriptionDisplayPriorityKey;
- (id)__INTypeCodableDescriptionDisplayPriorityKey;
- (id)__INCodableDescriptionDefaultKey;
- (id)__INIntentResponseCodableDescriptionDefaultKey;
- (id)__INTypeCodableDescriptionDefaultKey;
- (id)__INCodableDescriptionSupportsResolutionKey;
- (id)__INIntentResponseCodableDescriptionSupportsResolutionKey;
- (id)__INTypeCodableDescriptionSupportsResolutionKey;
- (id)__INCodableDescriptionSupportsDynamicEnumerationKey;
- (id)__INIntentResponseCodableDescriptionSupportsDynamicEnumerationKey;
- (id)__INTypeCodableDescriptionSupportsDynamicEnumerationKey;
- (id)__INCodableDescriptionSupportsSearchKey;
- (id)__INIntentResponseCodableDescriptionSupportsSearchKey;
- (id)__INTypeCodableDescriptionSupportsSearchKey;
- (id)__INCodableDescriptionConfigurableKey;
- (id)__INIntentResponseCodableDescriptionConfigurableKey;
- (id)__INTypeCodableDescriptionConfigurableKey;
- (id)__INCodableDescriptionWindowSizeKey;
- (id)__INIntentResponseCodableDescriptionWindowSizeKey;
- (id)__INTypeCodableDescriptionWindowSizeKey;
- (id)__INCodableDescriptionSupportsMultipleValuesKey;
- (id)__INIntentResponseCodableDescriptionSupportsMultipleValuesKey;
- (id)__INTypeCodableDescriptionSupportsMultipleValuesKey;
- (id)__INCodableDescriptionFixedSizeArrayKey;
- (id)__INIntentResponseCodableDescriptionFixedSizeArrayKey;
- (id)__INTypeCodableDescriptionFixedSizeArrayKey;
- (id)__INCodableDescriptionPromptDialogsKey;
- (id)__INIntentResponseCodableDescriptionPromptDialogsKey;
- (id)__INTypeCodableDescriptionPromptDialogsKey;
- (id)__INCodableDescriptionArraySizesKey;
- (id)__INIntentResponseCodableDescriptionArraySizesKey;
- (id)__INTypeCodableDescriptionArraySizesKey;
- (id)__INCodableDescriptionArraySizeSizeKey;
- (id)__INIntentResponseCodableDescriptionArraySizeSizeKey;
- (id)__INTypeCodableDescriptionArraySizeSizeKey;
- (id)__INCodableDescriptionArraySizeSizeClassKey;
- (id)__INIntentResponseCodableDescriptionArraySizeSizeClassKey;
- (id)__INTypeCodableDescriptionArraySizeSizeClassKey;
- (id)__INCodableDescriptionUnsupportedReasonsKey;
- (id)__INIntentResponseCodableDescriptionUnsupportedReasonsKey;
- (id)__INTypeCodableDescriptionUnsupportedReasonsKey;
- (id)__INCodableDescriptionMetadataKey;
- (id)__INIntentResponseCodableDescriptionMetadataKey;
- (id)__INTypeCodableDescriptionMetadataKey;
- (id)__INCodableDescriptionRelationshipKey;
- (id)__INIntentResponseCodableDescriptionRelationshipKey;
- (id)__INTypeCodableDescriptionRelationshipKey;
- (id)__INCodableDescriptionEntityKeypathKey;
- (id)__INIntentResponseCodableDescriptionEntityKeypathKey;
- (id)__INTypeCodableDescriptionEntityKeypathKey;
- (SEL)getter;
- (Class)_unsafeObjectClass;
- (id)unsupportedReasonWithIndex:;
- (unsigned long long)indexForUnsupportedReason:;
- (long long)arraySizeForSizeClass:;
- (id)promptDialogWithType:;
- (id)_attributeTagKey;
- (id)_attributeDisplayPriorityKey;
- (void)_setTypeString:;
- (BOOL)isFixedSizeArray;
- (void)setFixedSizeArray:;
- (void)setPropertyName:;
- (void)setDisplayNameID:;
- (BOOL)isDefaultAttribute;
- (void)setDefaultAttribute:;
- (BOOL)supportsResolution;
- (void)setSupportsResolution:;
- (BOOL)supportsDynamicEnumeration;
- (void)setSupportsDynamicEnumeration:;
- (BOOL)supportsSearch;
- (void)setSupportsSearch:;
- (id)unsupportedReasons;
- (void)_setUnsupportedReasons:;
- (id)entityKeypath;
- (void)setEntityKeypath:;
- (id)promptDialogs;
- (void)_setPromptDialogs:;
- (id)displayPriorityRank;
- (void)setDisplayPriorityRank:;
+ (BOOL)supportsSecureCoding;
@end
