@interface INFERENCESchemaINFERENCEContactHandleSignalSet : SISchemaInstrumentationMessage
@property (nonatomic) BOOL isSuggestedHandle;
@property (nonatomic) BOOL hasIsSuggestedHandle;
@property (nonatomic) BOOL isFavorite;
@property (nonatomic) BOOL hasIsFavorite;
@property (nonatomic) BOOL isQueryExactMatch;
@property (nonatomic) BOOL hasIsQueryExactMatch;
@property (nonatomic) BOOL isQueryMatch;
@property (nonatomic) BOOL hasIsQueryMatch;
@property (nonatomic) BOOL isPartialQueryValueMatch;
@property (nonatomic) BOOL hasIsPartialQueryValueMatch;
@property (nonatomic) INFERENCESchemaINFERENCEPrivatizedHistoryStats historyStats;
@property (nonatomic) BOOL hasHistoryStats;
@property (nonatomic) BOOL isRecentInAnyGroup;
@property (nonatomic) BOOL hasIsRecentInAnyGroup;
@property (nonatomic) BOOL isRecentInSameGroup;
@property (nonatomic) BOOL hasIsRecentInSameGroup;
@property (nonatomic) BOOL isPreferredType;
@property (nonatomic) BOOL hasIsPreferredType;
@property (nonatomic) BOOL isAllowedType;
@property (nonatomic) BOOL hasIsAllowedType;
@property (nonatomic) BOOL isFaceTimeable;
@property (nonatomic) BOOL hasIsFaceTimeable;
@property (nonatomic) BOOL isNotFaceTimeable;
@property (nonatomic) BOOL hasIsNotFaceTimeable;
@property (nonatomic) NSData jsonData;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (BOOL)isFavorite;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (void)setIsFavorite:;
- (void)setHasIsFavorite:;
- (BOOL)hasIsFavorite;
- (void)deleteIsFavorite;
- (void)setIsSuggestedHandle:;
- (BOOL)hasIsSuggestedHandle;
- (void)setHasIsSuggestedHandle:;
- (void)deleteIsSuggestedHandle;
- (void)setIsQueryExactMatch:;
- (BOOL)hasIsQueryExactMatch;
- (void)setHasIsQueryExactMatch:;
- (void)deleteIsQueryExactMatch;
- (void)setIsQueryMatch:;
- (BOOL)hasIsQueryMatch;
- (void)setHasIsQueryMatch:;
- (void)deleteIsQueryMatch;
- (void)setIsPartialQueryValueMatch:;
- (BOOL)hasIsPartialQueryValueMatch;
- (void)setHasIsPartialQueryValueMatch:;
- (void)deleteIsPartialQueryValueMatch;
- (BOOL)hasHistoryStats;
- (void)deleteHistoryStats;
- (void)setIsRecentInAnyGroup:;
- (BOOL)hasIsRecentInAnyGroup;
- (void)setHasIsRecentInAnyGroup:;
- (void)deleteIsRecentInAnyGroup;
- (void)setIsRecentInSameGroup:;
- (BOOL)hasIsRecentInSameGroup;
- (void)setHasIsRecentInSameGroup:;
- (void)deleteIsRecentInSameGroup;
- (void)setIsPreferredType:;
- (BOOL)hasIsPreferredType;
- (void)setHasIsPreferredType:;
- (void)deleteIsPreferredType;
- (void)setIsAllowedType:;
- (BOOL)hasIsAllowedType;
- (void)setHasIsAllowedType:;
- (void)deleteIsAllowedType;
- (void)setIsFaceTimeable:;
- (BOOL)hasIsFaceTimeable;
- (void)setHasIsFaceTimeable:;
- (void)deleteIsFaceTimeable;
- (void)setIsNotFaceTimeable:;
- (BOOL)hasIsNotFaceTimeable;
- (void)setHasIsNotFaceTimeable:;
- (void)deleteIsNotFaceTimeable;
- (BOOL)isSuggestedHandle;
- (BOOL)isQueryExactMatch;
- (BOOL)isQueryMatch;
- (BOOL)isPartialQueryValueMatch;
- (id)historyStats;
- (void)setHistoryStats:;
- (BOOL)isRecentInAnyGroup;
- (BOOL)isRecentInSameGroup;
- (BOOL)isPreferredType;
- (BOOL)isAllowedType;
- (BOOL)isFaceTimeable;
- (BOOL)isNotFaceTimeable;
- (void)setHasHistoryStats:;
@end
