@interface INShortcut : NSObject
@property (nonatomic) Q wf_shortcutAvailability;
@property (nonatomic) INImage _keyImage;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSArray writableTypeIdentifiersForItemProvider;
@property (nonatomic) NSData activityData;
@property (nonatomic) INImage activityImage;
@property (nonatomic) NSString activitySubtitle;
@property (nonatomic) NSString activityBundleIdentifier;
@property (nonatomic) NSString _title;
@property (nonatomic) NSString _subtitle;
@property (nonatomic) NSString _associatedAppBundleIdentifier;
@property (nonatomic) INIntent intent;
@property (nonatomic) NSUserActivity userActivity;
- (unsigned long long)wf_shortcutAvailability;
- (id)intent;
- (id)_title;
- (void)_injectProxiesForImages:completion:;
- (id)initWithUserActivity:;
- (id)_subtitle;
- (id)activitySubtitle;
- (id)initWithCoder:;
- (long long)_compareSubProducerOne:subProducerTwo:;
- (id)_keyImage;
- (void)encodeWithCoder:;
- (void).cxx_destruct;
- (id)userActivity;
- (id)description;
- (id)loadDataWithTypeIdentifier:forItemProviderCompletionHandler:;
- (id)initWithIntent:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)_initWithIntent:;
- (id)initWithUserActivity:bundleIdentifier:;
- (id)initWithActivityData:activityImage:activitySubtitle:activityBundleIdentifier:;
- (id)shortcutWithActivityImage:;
- (id)shortcutWithActivityBundleIdentifier:;
- (id)activityData;
- (id)_associatedAppBundleIdentifier;
- (id)activityImage;
- (id)activityBundleIdentifier;
+ (BOOL)supportsSecureCoding;
+ (id)writableTypeIdentifiersForItemProvider;
+ (id)readableTypeIdentifiersForItemProvider;
+ (id)objectWithItemProviderData:typeIdentifier:error:;
+ (long long)itemProviderVisibilityForRepresentationWithTypeIdentifier:;
@end
