@interface LAUIAuthenticationCore : NSObject
@property (nonatomic) Q enabledMechanisms;
@property (nonatomic) Q activeMechanisms;
@property (nonatomic) BOOL applicationActive;
@property (nonatomic) BOOL keyWindow;
@property (nonatomic) BOOL uiActive;
@property (nonatomic) LAContext context;
@property (nonatomic) NSDictionary faceIdResult;
@property (nonatomic) NSObject<LAUIAuthenticationCoreDelegate> delegate;
@property (nonatomic) UIView view;
@property (nonatomic) q biometryType;
- (BOOL)isApplicationActive;
- (id)context;
- (void)setDelegate:;
- (id)view;
- (long long)biometryType;
- (id)delegate;
- (void).cxx_destruct;
- (void)setApplicationActive:;
- (void)setView:;
- (id)notificationNames;
- (void)setContext:;
- (void)setKeyWindow:;
- (BOOL)isKeyWindow;
- (void)_notification:;
- (void)event:params:reply:;
- (void)checkView;
- (BOOL)enableMechanism:error:;
- (BOOL)disableMechanism:error:;
- (BOOL)isMechanismEnabled:;
- (id)initWithMechanisms:;
- (id)initWithMechanisms:context:;
- (BOOL)isMechanismAvailable:error:;
- (BOOL)isMechanismActive:;
- (void)_setupMechanisms:;
- (void)_enableAvailableMechanisms:;
- (void)_setupNotifications:;
- (BOOL)_mechanism:enable:error:;
- (void)setEnabledMechanisms:;
- (void)setActiveMechanisms:;
- (void)startOrStopBackgroundMechanisms;
- (long long)_policyForBackgroundMechanisms;
- (void)_startBackgroundMechanisms;
- (id)_optionsForBackgroundMechanism;
- (void)_handleBackgroundMechanismsResult:error:context:;
- (void)_stopBackgroundMechanisms;
- (void)_processActivityChangeForNotification:block:;
- (BOOL)_simpleStatusInParams:touchId:faceId:;
- (void)_biometryState:;
- (void)_biometricNoMatch;
- (unsigned long long)enabledMechanisms;
- (unsigned long long)activeMechanisms;
- (BOOL)isUiActive;
- (void)setUiActive:;
- (id)faceIdResult;
+ (void)performBlockOnMainThread:;
@end
