@interface LCStreamingDisplayInfo : NSObject
@property (nonatomic) q audioCaptureType;
@property (nonatomic) BOOL videoMixOnClient;
@property (nonatomic) q videobps;
@property (nonatomic) q videofps;
@property (nonatomic) NSString streamingProtocol;
@property (nonatomic) NSString streamingName;
@property (nonatomic) NSString streamingEncodeQuality;
@property (nonatomic) q networkQuality;
@property (nonatomic) q audiobps;
@property (nonatomic) NSString audioEncode;
@property (nonatomic) q audioStreamingSample;
@property (nonatomic) q audioStreamingChannel;
@property (nonatomic) BOOL denoiseEnable;
@property (nonatomic) BOOL aecEnable;
@property (nonatomic) BOOL agcEnable;
@property (nonatomic) BOOL earMonitorEnable;
@property (nonatomic) NSString videoCaptureImageResolution;
@property (nonatomic) NSString previewImageResolution;
@property (nonatomic) NSString videoStreamingImageResolution;
@property (nonatomic) NSString rtcDownVideoFrameImageReolution;
- (id)rtcDownVideoFrameImageReolution;
- (void)setVideoCaptureImageResolution:;
- (void)setAudioEncode:;
- (BOOL)aecEnable;
- (BOOL)agcEnable;
- (long long)audioCaptureType;
- (id)audioEncode;
- (long long)audioStreamingChannel;
- (long long)audioStreamingSample;
- (long long)audiobps;
- (BOOL)denoiseEnable;
- (BOOL)earMonitorEnable;
- (id)previewImageResolution;
- (void)setAecEnable:;
- (void)setAgcEnable:;
- (void)setAudioCaptureType:;
- (void)setAudioStreamingChannel:;
- (void)setAudioStreamingSample:;
- (void)setAudiobps:;
- (void)setDenoiseEnable:;
- (void)setEarMonitorEnable:;
- (void)setNetworkQuality:;
- (void)setPreviewImageResolution:;
- (void)setRtcDownVideoFrameImageReolution:;
- (void)setStreamingEncodeQuality:;
- (void)setStreamingName:;
- (void)setStreamingProtocol:;
- (void)setVideoMixOnClient:;
- (void)setVideoStreamingImageResolution:;
- (void)setVideobps:;
- (void)setVideofps:;
- (id)streamingEncodeQuality;
- (id)streamingName;
- (id)streamingProtocol;
- (id)videoCaptureImageResolution;
- (BOOL)videoMixOnClient;
- (id)videoStreamingImageResolution;
- (long long)videobps;
- (long long)videofps;
- (void).cxx_destruct;
- (long long)networkQuality;
+ (BOOL)isStreamingDisplayInfoEnable;
+ (void)setisStreamingDisplayInfoEnable:;
+ (id)showInteractDisplayInfo;
+ (id)showStreamingDisplayInfo;
+ (void)updateBoolStatusFromInputDict:;
+ (void)updateImageResolutionFromVideoGraph:;
+ (void)updateInteractDisplayInfo:;
+ (void)updateStreamingDisplayInfo:;
+ (id)sharedInstance;
@end
