@interface MailAccount : MFAccount
@property (nonatomic) BOOL cacheHasBeenRead;
@property (nonatomic) <EFScheduler> mailboxCacheWriteScheduler;
@property (nonatomic) MFLocalActionReplayHandler replayHandler;
@property (nonatomic) <MFTaskManager> taskManager;
@property (nonatomic) NSDate lastEmailAliasesSyncDate;
@property (nonatomic) NSString lastEmailAliasesSyncEntityTag;
@property (nonatomic) BOOL shouldArchiveByDefault;
@property (nonatomic) BOOL sourceIsManaged;
@property (nonatomic) NSString defaultPath;
@property (nonatomic) BOOL moveSupported;
@property (nonatomic) MFMailboxUid rootMailbox;
@property (nonatomic) MFMailboxUid rootMailboxUid;
@property (nonatomic) NSString mailboxPathExtension;
@property (nonatomic) BOOL supportsRemoteAppend;
@property (nonatomic) BOOL supportsFastRemoteBodySearch;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL isManaged;
@property (nonatomic) NSArray emailAddresses;
@property (nonatomic) NSString smtpIdentifier;
@property (nonatomic) BOOL isLocalAccount;
@property (nonatomic) NSString identifier;
@property (nonatomic) NSString altDSID;
@property (nonatomic) ACAccount systemAccount;
@property (nonatomic) NSString statisticsKind;
@property (nonatomic) BOOL primaryiCloudAccount;
@property (nonatomic) BOOL isActive;
@property (nonatomic) NSString displayName;
@property (nonatomic) NSString username;
@property (nonatomic) NSArray emailAddressStrings;
@property (nonatomic) NSString hostname;
@property (nonatomic) NSString password;
@property (nonatomic) BOOL managed;
@property (nonatomic) ECAccount baseAccount;
- (id)path;
- (id)stateCaptureTitle;
- (void)systemWillSleep;
- (id)emailAddresses;
- (void)dealloc;
- (id)URLString;
- (void)setHostname:;
- (void)setPath:;
- (void)setLibrary:;
- (void)setUsername:;
- (void)saveState;
- (void)startListeningForNotifications;
- (BOOL)renameMailbox:newName:;
- (void)newActionsAdded;
- (id)displayName;
- (void)systemDidWake;
- (id)connectionError;
- (id)defaultPath;
- (void)setDefaultEmailAddress:;
- (id)library;
- (void)setConnectionError:;
- (BOOL)_setPath:;
- (void).cxx_destruct;
- (id)initWithPath:;
- (void)setEmailAddresses:;
- (id)description;
- (id)defaultEmailAddress;
- (BOOL)isLocalAccount;
- (void)setPortNumber:;
- (id)loggingIdentifier;
- (void)setActive:;
- (BOOL)deleteMailbox:;
- (void)invalidate;
- (void)test_tearDown;
- (BOOL)isActive;
- (void)addNewAction:;
- (id)taskManager;
- (id)URL;
- (id)replayAction:;
- (id)fullUserName;
- (BOOL)sourceIsManaged;
- (void)_didBecomeActive:;
- (id)emailAddressStrings;
- (BOOL)canAuthenticateWithCurrentCredentials;
- (id)statisticsKind;
- (id)initWithPersistentAccount:;
- (void)persistentAccountDidChange:previousAccount:;
- (void)_setAccountProperties:;
- (void)setValueInAccountProperties:forKey:;
- (BOOL)supportsMailDrop;
- (void)releaseAllConnections;
- (void)releaseAllForcedConnections;
- (id)deliveryAccount;
- (void)setDeliveryAccount:;
- (id)_defaultSpecialMailboxNameForType:;
- (id)iconString;
- (BOOL)derivesDeliveryAccountInfoFromMailAccount;
- (id)URLForMessage:;
- (id)_deliveryAccountCreateIfNeeded:;
- (id)initWithLibrary:persistentAccount:;
- (BOOL)canReceiveNewMailNotifications;
- (id)firstEmailAddress;
- (BOOL)shouldFetchRemoteLinksWithDateReceived:;
- (BOOL)isEquivalentTo:hostname:username:;
- (id)uniqueIdForPersistentConnection;
- (id)displayUsername;
- (id)emailAddressesAndAliasesList;
- (id)fromEmailAddresses;
- (id)fromEmailAddressesIncludingDisabled;
- (void)setEnabled:forEmailAddress:;
- (void)invalidateEmailAliases;
- (void)updateEmailAliasesIfNeeded;
- (void)pushUpdateForAliasData;
- (BOOL)supportsArchiving;
- (id)allMailboxUids;
- (void)resetSpecialMailboxes;
- (int)emptyFrequencyForMailboxType:;
- (id)_copyMailboxUidWithParent:name:attributes:existingMailboxUid:dictionary:;
- (id)_newMailboxWithParent:name:attributes:dictionary:withCreationOption:;
- (BOOL)_renameMailbox:newName:parent:;
- (BOOL)newMailboxNameIsAcceptable:reasonForFailure:;
- (id)primaryMailboxUid;
- (id)_URLScheme;
- (id)URLStringFromLegacyURLString:;
- (BOOL)mustArchiveSentMessages;
- (BOOL)canArchiveSentMessages;
- (id)allMailMailboxUid;
- (void)fetchMailboxList;
- (Class)storeClass;
- (id)_copyMailboxWithParent:name:attributes:dictionary:;
- (void)_synchronouslyLoadListingForParent:;
- (BOOL)renameMailbox:newName:parent:;
- (BOOL)_deleteMailbox:reflectToServer:;
- (id)mailboxPathExtension;
- (BOOL)supportsRemoteAppend;
- (BOOL)supportsMailboxEditing;
- (id)_infoForMatchingURL:;
- (id)mailboxUidForInfo:;
- (id)_specialMailboxUidWithType:create:;
- (BOOL)isMailboxLocalForType:;
- (BOOL)supportsMessageFlagging;
- (BOOL)supportsThreadOperations;
- (BOOL)shouldArchiveByDefault;
- (BOOL)shouldFetchAgainWithError:foregroundRequest:;
- (id)uniqueServerIdForMessage:;
- (BOOL)reconstituteOrphanedMeetingInMessage:;
- (id)unactionableInvitationICSRepresentationInMessage:summary:;
- (id)meetingStorePersistentID;
- (void)stopListeningForNotifications;
- (BOOL)shouldRestoreMessagesAfterFailedDelete;
- (BOOL)supportsUserPushedMailboxes;
- (id)pushedMailboxUids;
- (void)changePushedMailboxUidsAdded:deleted:;
- (id)signingIdentityPersistentReferenceForAddress:;
- (void)setSigningIdentityPersistentReference:forAddress:;
- (id)encryptionIdentityPersistentReferenceForAddress:;
- (void)setEncryptionIdentityPersistentReference:forAddress:;
- (BOOL)perMessageEncryptionEnabledForAddress:;
- (int)secureCompositionSigningPolicyForAddress:;
- (int)secureCompositionEncryptionPolicyForAddress:;
- (id)copyDataForRemoteEncryptionCertificatesForAddresses:errors:;
- (id)copyDataForRemoteEncryptionCertificatesForAddress:error:;
- (BOOL)restrictedFromTransferingMessagesToOtherAccounts;
- (BOOL)restrictedFromSendingExternally;
- (BOOL)restrictedFromSyncingRecents;
- (id)fetchLimits;
- (id)unsupportedHandoffTypes;
- (BOOL)moveSupported;
- (BOOL)hasEnoughInformationForEasySetup;
- (int)archiveDestinationForMailbox:;
- (id)displayNameUsingSpecialNamesForMailboxUid:;
- (id)_childOfMailbox:withComponentName:;
- (void)_deleteHook;
- (BOOL)supportsFastRemoteBodySearch;
- (id)persistentNameForMailbox:;
- (id)saveSentFolder;
- (void)_readCustomInfoFromMailboxCache:;
- (void)_writeCustomInfoToMailboxCache:;
- (void)test_setTaskManager:;
- (void)_setSpecialMailbox:forType:;
- (BOOL)isSpecialMailbox:;
- (void)_mailboxesWereRemovedFromTree:withFileSystemPaths:;
- (BOOL)canMailboxBeDeleted:;
- (void)deleteMessagesFromMailboxUid:olderThanNumberOfDays:;
- (id)mailboxUidForRelativePath:create:;
- (BOOL)canFetch;
- (BOOL)deleteInPlaceForAllMailboxes;
- (BOOL)deleteInPlaceForMailbox:;
- (id)lastKnownCapabilities;
- (void)resetMailboxTimer;
- (id)_pathComponentForUidName:;
- (id)_uidNameForPathComponent:;
- (id)_mailboxPathPrefix;
- (BOOL)supportsAppend;
- (BOOL)_registerPushNotificationPrefix:forMailboxNames:;
- (void)transferNotificationSessionToAccount:;
- (BOOL)_setChildren:forMailboxUid:;
- (id)mailboxUidForRelativePath:create:withOption:;
- (id)legacySQLExpressionToMatchAllMailboxes;
- (BOOL)_shouldConfigureMailboxCache;
- (BOOL)supportsPurge;
- (id)storeForMailboxUid:;
- (void)deliveryAccountWillBeRemoved:;
- (id)mailboxForType:;
- (BOOL)containsMailboxWithURL:;
- (id)smtpIdentifier;
- (id)rootMailbox;
- (BOOL)cacheHasBeenRead;
- (void)setCacheHasBeenRead:;
- (BOOL)isUsernameEquivalentTo:;
- (void)_invalidateCachedMailboxen;
- (id)initWithLibrary:path:;
- (void)setFullUserName:;
- (BOOL)isPrimaryDeliveryAccountDisabled;
- (void)setPrimaryDeliveryAccountDisabled:;
- (id)deliveryAccountAlternates;
- (void)setDeliveryAccountAlternates:;
- (BOOL)canUseDeliveryAccount:;
- (void)setCanUseCarrierDeliveryFallback:;
- (BOOL)canUseCarrierDeliveryFallback;
- (id)emailAddressesDictionary;
- (id)receiveEmailAliasAddresses;
- (void)setReceiveEmailAliasAddresses:;
- (id)lastEmailAliasesSyncDate;
- (void)setLastEmailAliasesSyncDate:;
- (id)lastEmailAliasesSyncEntityTag;
- (void)setLastEmailAliasesSyncEntityTag:;
- (id)emailAddressesAndAliases;
- (id)copyReceivingEmailAddresses;
- (void)_invalidateAndDeleteAccountData:;
- (void)_asynchronouslyInvalidateAndDeleteAccountData:;
- (void)invalidateAndDelete;
- (void)_synchronizeMailboxListWithFileSystem;
- (void)forceFetchMailboxList;
- (id)rootMailboxUid;
- (void)deleteDeliveryAccountIfNeeded;
- (BOOL)deliveryAccountInUseByOtherAccounts:;
- (id)mailboxUidOfType:createIfNeeded:;
- (id)specialMailboxNameForType:;
- (id)allMailboxesFilteringNotes:;
- (id)mailboxesForSuggestionsLostMessageSearchPriorToTime:;
- (id)transferDisabledMailboxUids;
- (void)setMailboxUid:forMailboxType:;
- (void)_setEmptyFrequency:forKey:;
- (void)setEmptyFrequency:forMailboxType:;
- (BOOL)_resetSpecialMailboxes;
- (BOOL)canCreateNewMailboxes;
- (BOOL)canMailboxBeRenamed:;
- (BOOL)moveMailbox:intoParent:;
- (BOOL)deleteMailbox:reflectToServer:;
- (void)_resetAllMailboxURLs:;
- (void)resetMailboxURLs;
- (BOOL)isHostnameEquivalentTo:;
- (BOOL)isAccountClassEquivalentTo:;
- (Class)storeClassForMailbox:;
- (id)mailboxUidForURL:;
- (BOOL)ownsMailboxUidWithURL:;
- (void)emptyTrash;
- (void)setupLibrary;
- (BOOL)supportsSyncingReadState;
- (BOOL)willPerformActionForChokePoint:coalescePoint:result:;
- (void)didFinishActionForChokePoint:coalescePoint:withResult:;
- (BOOL)isActiveWithPersistentAccount:;
- (int)_emptyFrequencyForKey:defaultValue:;
- (BOOL)_loadMailboxListingIntoCache:attributes:children:parent:;
- (id)mailboxCachePath;
- (void)setMailboxCachePath:;
- (void)resetMailboxCache;
- (void)_loadEntriesFromFileSystemPath:parent:;
- (void)_writeMailboxCacheWithPrejudice:;
- (void)_writeMailboxCacheWithPrejudice:completionHandler:;
- (void)_incrementCacheDirtyCount;
- (id)powerAssertionIdentifierWithPrefix:;
- (id)_cachedSpecialMailboxOfType:;
- (BOOL)_assignSpecialMailboxToAppropriateIvar:forType:;
- (void)_setSpecialMailboxName:forType:;
- (BOOL)_canEmptyMessagesFromMailboxUid:;
- (BOOL)_shouldLogDeleteActivity;
- (id)_URLForInfo:;
- (BOOL)_cleanInboxDuplication:;
- (id)newMailboxWithParent:name:;
- (id)_localMailboxNameForType:usingDisplayName:;
- (id)allLocalMailboxUids;
- (id)valueInAccountLookAsidePropertiesForKey:;
- (void)setValueInAccountLookAsideProperties:forKey:;
- (void)_setValueInAccountLookAsideProperties:forKey:subKey:;
- (id)customSignature;
- (void)setCustomSignature:;
- (BOOL)preventArchiveForMailbox:;
- (BOOL)canArchiveForMailbox:;
- (BOOL)supportsHandoffType:;
- (void)_registerStateCaptureHandler;
- (id)debugAccountState;
- (id)mailboxCacheWriteScheduler;
- (void)setMailboxCacheWriteScheduler:;
- (id)replayHandler;
- (void)setReplayHandler:;
+ (void)reloadAccounts;
+ (id)activeAccounts;
+ (id)log;
+ (id)lock;
+ (id)mailAccounts;
+ (void)test_tearDown;
+ (id)defaultMailAccountForDelivery;
+ (id)newAccountWithDictionary:;
+ (id)existingAccountForUniqueID:;
+ (BOOL)isPredefinedAccountType;
+ (id)predefinedValueForKey:;
+ (BOOL)usernameIsEmailAddress;
+ (BOOL)primaryDeliveryAccountIsDynamic;
+ (id)allMailboxUids;
+ (id)legacyPathForAccountIdentifier:withHostname:username:;
+ (id)csAccountTypeString;
+ (id)accountWithUniqueId:;
+ (id)legacyPathNameForAccountWithHostname:username:;
+ (BOOL)mailboxListingNotificationsAreEnabled;
+ (void)disableMailboxListingNotifications;
+ (void)enableMailboxListingNotifications:;
+ (void)_addAccountToSortedPaths:;
+ (void)_setupSortedPathsForAccounts:;
+ (id)existingDAMailAccountForDAAccount:;
+ (id)_loadAllAccountsWithError:;
+ (id)_loadDataAccessAccountsWithError:;
+ (id)mailAccountsWithError:;
+ (id)lastMailAccountsReloadDate;
+ (void)setMailAccounts:;
+ (void)setMailAccounts:saveIfChanged:;
+ (void)_setMailAccounts:saveIfChanged:alreadyLocked:;
+ (void)_removeAccountFromSortedPaths:;
+ (id)activeNonLocalAccounts;
+ (id)activeAccountsWithError:;
+ (id)purgeableAccounts;
+ (void)notifyOfAccountsAdded:accountsRemoved:changedAccounts:;
+ (id)existingAccountWithType:hostname:username:;
+ (void)resetMailboxTimers;
+ (id)_accountContainingEmailAddress:matchingAddress:fullUserName:includingInactive:;
+ (id)accountContainingEmailAddress:includingInactive:;
+ (id)accountContainingEmailAddress:;
+ (id)accountForHeaders:message:includingInactive:;
+ (id)accountThatMessageIsFrom:includingInactive:;
+ (id)accountThatMessageIsFrom:;
+ (id)addressesThatReceivedMessage:;
+ (id)outboxMailboxUid;
+ (id)outboxMessageStore:;
+ (id)allPurgeableMailboxUids;
+ (id)allMailboxUidsForAccounts:;
+ (id)allActivePrimaryMailboxUids;
+ (id)accountWithPath:;
+ (id)newAccountWithPath:;
+ (id)defaultAccountDirectory;
+ (id)defaultMailAccountForDeliveryExcludingRestricted;
+ (id)_defaultMailAccountForDeliveryIncludingRestricted:;
+ (id)defaultDeliveryAccount;
+ (void)saveStateForAllAccounts;
+ (id)mailboxUidForFileSystemPath:create:;
+ (id)accountWithURL:;
+ (id)infoForURL:;
+ (id)URLForInfo:;
+ (id)accountWithURLString:;
+ (id)mailboxUidFromActiveAccountsForURL:;
+ (void)updateEmailAliasesForActiveAccounts;
+ (id)standardAccountClass:valueForKey:;
+ (BOOL)getConfigurationFromServerForEmail:;
+ (id)_accountWithPath:;
+ (void)_setOutboxMailboxUid:;
+ (BOOL)canMoveMessagesFromAccount:toAccount:;
+ (BOOL)canMoveMessagesFromAccount:toAccount:profileConnection:;
+ (void)_removeLookAsideValuesNotInAccountList:;
@end
