@interface MCEASAccountPayload : MCEmailAccountPayloadBase
@property (nonatomic) NSNumber syncDefaultFoldersOnlyNum;
@property (nonatomic) NSString accountDescription;
@property (nonatomic) NSString hostname;
@property (nonatomic) NSString username;
@property (nonatomic) NSString password;
@property (nonatomic) NSString emailAddress;
@property (nonatomic) NSNumber useSSL;
@property (nonatomic) NSNumber useOAuth;
@property (nonatomic) NSString OAuthSignInURL;
@property (nonatomic) NSString OAuthTokenRequestURL;
@property (nonatomic) NSNumber mailNumberOfPastDaysToSync;
@property (nonatomic) NSData embeddedCertificate;
@property (nonatomic) NSString embeddedCertificateName;
@property (nonatomic) NSString embeddedCertificatePassword;
@property (nonatomic) NSString certificateUUID;
@property (nonatomic) BOOL hasCertificate;
@property (nonatomic) NSDictionary communicationServiceRules;
@property (nonatomic) BOOL enableMail;
@property (nonatomic) BOOL enableContacts;
@property (nonatomic) BOOL enableCalendars;
@property (nonatomic) BOOL enableReminders;
@property (nonatomic) BOOL enableNotes;
@property (nonatomic) BOOL enableMailUserOverridable;
@property (nonatomic) BOOL enableContactsUserOverridable;
@property (nonatomic) BOOL enableCalendarsUserOverridable;
@property (nonatomic) BOOL enableRemindersUserOverridable;
@property (nonatomic) BOOL enableNotesUserOverridable;
@property (nonatomic) NSString acAccountIdentifier;
@property (nonatomic) BOOL overridePreviousPassword;
@property (nonatomic) BOOL mustNotUseSynchronizableCredential;
@property (nonatomic) NSString accountPersistentUUID;
@property (nonatomic) NSData certificatePersistentID;
@property (nonatomic) BOOL syncDefaultFoldersOnly;
- (id)emailAddress;
- (id)hostname;
- (void)setPassword:;
- (id)username;
- (id)password;
- (void)setEmailAddress:;
- (void)setUsername:;
- (void).cxx_destruct;
- (id)accountDescription;
- (id)verboseDescription;
- (id)restrictions;
- (id)mailAccountIdentifiers;
- (id)calendarAccountIdentifiers;
- (id)contactsAccountIdentifiers;
- (id)initWithDictionary:profile:outError:;
- (id)stubDictionary;
- (id)payloadDescriptionKeyValueSections;
- (id)subtitle1Label;
- (id)subtitle1Description;
- (BOOL)containsSensitiveUserInformation;
- (id)subtitle2Label;
- (id)subtitle2Description;
- (id)certificatePersistentID;
- (void)setCertificatePersistentID:;
- (id)acAccountIdentifier;
- (void)setAcAccountIdentifier:;
- (id)communicationServiceRules;
- (id)certificateUUID;
- (id)useSSL;
- (id)accountPersistentUUID;
- (void)setAccountPersistentUUID:;
- (BOOL)hasCertificate;
- (BOOL)enableMail;
- (BOOL)enableContacts;
- (BOOL)enableCalendars;
- (BOOL)enableReminders;
- (BOOL)enableNotes;
- (BOOL)enableMailUserOverridable;
- (BOOL)enableContactsUserOverridable;
- (BOOL)enableCalendarsUserOverridable;
- (BOOL)enableRemindersUserOverridable;
- (BOOL)enableNotesUserOverridable;
- (BOOL)mustNotUseSynchronizableCredential;
- (id)mailNumberOfPastDaysToSync;
- (id)embeddedCertificate;
- (id)embeddedCertificateName;
- (id)embeddedCertificatePassword;
- (void)setEmbeddedCertificatePassword:;
- (BOOL)syncDefaultFoldersOnly;
- (void)setSyncDefaultFoldersOnly:;
- (void)setUseSSL:;
- (id)useOAuth;
- (void)setUseOAuth:;
- (id)OAuthSignInURL;
- (void)setOAuthSignInURL:;
- (id)OAuthTokenRequestURL;
- (void)setOAuthTokenRequestURL:;
- (BOOL)overridePreviousPassword;
- (id)syncDefaultFoldersOnlyNum;
+ (id)typeStrings;
+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
@end
