@interface MFComposeSubjectView : MFMailComposeHeaderView
@property (nonatomic) MFConfirmationButton notifyButton;
@property (nonatomic) UITextView textView;
@property (nonatomic) NSString text;
@property (nonatomic) double trailingButtonMidlineInsetFromLayoutMargin;
@property (nonatomic) BOOL notifyOptionSelected;
@property (nonatomic) BOOL allowsNotifyOption;
@property (nonatomic) <MFComposeSubjectViewDelegate> delegate;
@property (nonatomic) BOOL enabled;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)layoutManager:didCompleteLayoutForTextContainer:atEnd:;
- (id)textView;
- (BOOL)keyboardInput:shouldInsertText:isMarkedText:;
- (void)dealloc;
- (BOOL)_canBecomeFirstResponder;
- (BOOL)enabled;
- (void)setFrame:;
- (void)layoutSubviews;
- (void)setText:;
- (void)setDelegate:;
- (id)initWithFrame:;
- (void)traitCollectionDidChange:;
- (BOOL)becomeFirstResponder;
- (void)setEnabled:;
- (void).cxx_destruct;
- (BOOL)endEditing:;
- (id)text;
- (void)textViewDidBeginEditing:;
- (void)textViewDidEndEditing:;
- (void)textViewDidChange:;
- (BOOL)textView:shouldChangeTextInRange:replacementText:;
- (void)refreshPreferredContentSize;
- (void)_textInputDidChange:;
- (void)displayMetricsDidChange;
- (void)_showNotifyButtonIfNeeded;
- (id)notifyButton;
- (void)_configureNotifyGlyphs;
- (void)setAllowsNotifyOption:;
- (BOOL)isNotifyOptionSelected;
- (void)setNotifyOptionSelected:;
- (void)setTrailingButtonMidlineInsetFromLayoutMargin:;
- (void)setNeedsExclusionPathUpdate;
- (void)_updateExclusionPathsIfNeeded;
- (void)_updateTextContainerInsets;
- (id)_textContainerExclusionPathsWithNotifyButton:;
- (BOOL)isEndEditingText:;
- (BOOL)allowsNotifyOption;
- (double)trailingButtonMidlineInsetFromLayoutMargin;
@end
