@interface MFMailCompositionValues : NSObject
@property (nonatomic) q composeType;
@property (nonatomic) NSURL mailtoURL;
@property (nonatomic) NSString autosaveIdentifier;
@property (nonatomic) NSData serializedMessageObjectID;
@property (nonatomic) NSData serializedMailboxObjectID;
@property (nonatomic) NSString preferredSendingEmailAddress;
@property (nonatomic) NSString subject;
@property (nonatomic) NSString hideMyEmailFrom;
@property (nonatomic) NSString from;
@property (nonatomic) NSArray toRecipients;
@property (nonatomic) NSArray ccRecipients;
@property (nonatomic) NSArray bccRecipients;
@property (nonatomic) NSString messageBody;
@property (nonatomic) BOOL isHTML;
@property (nonatomic) NSArray originalContent;
@property (nonatomic) BOOL includeAttachments;
@property (nonatomic) NSInteger sourceAccountManagement;
@property (nonatomic) BOOL isUsingDefaultAccount;
@property (nonatomic) BOOL showKeyboardImmediately;
@property (nonatomic) BOOL showContentImmediately;
@property (nonatomic) BOOL prefersFirstLineSelection;
@property (nonatomic) Q caretPosition;
@property (nonatomic) NSMutableArray contentVariations;
@property (nonatomic) q defaultContentVariationIndex;
@property (nonatomic) NSMutableArray deferredAttachments;
@property (nonatomic) NSDate sendLaterDate;
@property (nonatomic) Q sendLaterContext;
@property (nonatomic) CKShare ckShare;
@property (nonatomic) CKContainerSetupInfo ckContainerSetupInfo;
@property (nonatomic) q ckSharePermissionType;
@property (nonatomic) BOOL ckShareAllowOthersToInvite;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSArray UTITypes;
@property (nonatomic) NSArray photoIDs;
@property (nonatomic) NSArray cloudPhotoIDs;
@property (nonatomic) NSArray contentText;
@property (nonatomic) NSArray contentURLs;
@property (nonatomic) NSString shareSheetSessionID;
- (id)init;
- (id)subject;
- (void)setSubject:;
- (id)bccRecipients;
- (id)messageBody;
- (id)initWithCoder:;
- (id)initWithDictionaryRepresentation:;
- (void)encodeWithCoder:;
- (id)ccRecipients;
- (id)toRecipients;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)setCkShare:;
- (id)ckShare;
- (id)from;
- (void)setFrom:;
- (id)contentText;
- (void)setContentText:;
- (id)UTITypes;
- (void)setContentURLs:;
- (void)setPhotoIDs:;
- (void)setCloudPhotoIDs:;
- (void)setShareSheetSessionID:;
- (id)contentURLs;
- (id)photoIDs;
- (id)cloudPhotoIDs;
- (id)shareSheetSessionID;
- (void)setUTITypes:;
- (void)setToRecipients:;
- (void)setMessageBody:;
- (id)autosaveIdentifier;
- (void)setAutosaveIdentifier:;
- (void)setSourceAccountManagement:;
- (BOOL)isHTML;
- (id)sendLaterDate;
- (void)setSendLaterDate:;
- (void)setCcRecipients:;
- (void)setBccRecipients:;
- (void)setCaretPosition:;
- (long long)composeType;
- (int)sourceAccountManagement;
- (void)setHideMyEmailFrom:;
- (void)setPreferredSendingEmailAddress:;
- (void)setShowKeyboardImmediately:;
- (id)addContentVariationWithName:;
- (void)setComposeType:;
- (id)mailtoURL;
- (void)setMailtoURL:;
- (id)serializedMessageObjectID;
- (void)setSerializedMessageObjectID:;
- (id)serializedMailboxObjectID;
- (void)setSerializedMailboxObjectID:;
- (id)preferredSendingEmailAddress;
- (id)hideMyEmailFrom;
- (void)setIsHTML:;
- (id)originalContent;
- (void)setOriginalContent:;
- (BOOL)includeAttachments;
- (void)setIncludeAttachments:;
- (BOOL)isUsingDefaultAccount;
- (void)setIsUsingDefaultAccount:;
- (BOOL)showKeyboardImmediately;
- (BOOL)showContentImmediately;
- (void)setShowContentImmediately:;
- (BOOL)prefersFirstLineSelection;
- (void)setPrefersFirstLineSelection:;
- (unsigned long long)caretPosition;
- (id)contentVariations;
- (void)setContentVariations:;
- (long long)defaultContentVariationIndex;
- (void)setDefaultContentVariationIndex:;
- (id)deferredAttachments;
- (void)setDeferredAttachments:;
- (unsigned long long)sendLaterContext;
- (void)setSendLaterContext:;
- (id)ckContainerSetupInfo;
- (void)setCkContainerSetupInfo:;
- (long long)ckSharePermissionType;
- (void)setCkSharePermissionType:;
- (BOOL)ckShareAllowOthersToInvite;
- (void)setCkShareAllowOthersToInvite:;
- (void)_processDictionaryRepresentation:;
+ (BOOL)supportsSecureCoding;
@end
