@interface MFNetworkController : NSObject
@property (nonatomic) BOOL isDataAvailable;
@property (nonatomic) BOOL isNetworkUp;
@property (nonatomic) BOOL isFatPipe;
@property (nonatomic) BOOL isOnWWAN;
@property (nonatomic) BOOL inAirplaneMode;
@property (nonatomic) BOOL is3GConnection;
@property (nonatomic) BOOL is4GConnection;
@property (nonatomic) NSInteger dataIndicator;
@property (nonatomic) q transportType;
@property (nonatomic) EFObservable networkObservable;
@property (nonatomic) EFObservable wifiObservable;
@property (nonatomic) AWDMailNetworkDiagnosticsReport awdNetworkDiagnosticReport;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)preferredDataSimChanged:;
- (int)dataStatus;
- (void)dataStatus:dataStatusInfo:;
- (id)init;
- (unsigned long long)signpostID;
- (void)dealloc;
- (int)dataIndicator;
- (void)airplaneModeChanged;
- (long long)transportType;
- (BOOL)isNetworkUp;
- (BOOL)inAirplaneMode;
- (void).cxx_destruct;
- (void)callObserver:callChanged:;
- (void)connectionActivationError:connection:error:;
- (void)simStatusDidChange:status:;
- (void)_registerStateCaptureHandler;
- (void)_resetDataStatusInitialized;
- (void)_initializeDataStatus;
- (void)_setupSymptoms;
- (BOOL)_simulationOverrideForType:actualValue:;
- (void)_setDataStatus_nts:;
- (BOOL)isDataAvailable;
- (BOOL)_isNetworkUp_nts;
- (BOOL)isFatPipe;
- (BOOL)isOnWWAN;
- (BOOL)is3GConnection;
- (BOOL)is4GConnection;
- (void)_setFlags:forReachability:;
- (void)_checkKeys:forStore:;
- (void)_handleWiFiNotification:;
- (id)_networkAssertionWithIdentifier:;
- (id)copyCarrierBundleValue:;
- (id)networkObservable;
- (id)wifiObservable;
- (void)_carrierBundleDidChange;
- (void)_updateActiveCalls;
- (id)awdNetworkDiagnosticReport;
+ (id)sharedInstance;
+ (id)signpostLog;
+ (id)observers;
+ (void)performExecuteOnObservers;
+ (id)networkAssertionWithIdentifier:;
+ (id)addNetworkObserverBlock:queue:;
+ (void)removeNetworkObserver:;
@end
