@interface MKPlaceInlineMapViewController : UIViewController
@property (nonatomic) BOOL useWindowTrait;
@property (nonatomic) MKMapCamera mapCamera;
@property (nonatomic) NSArray visibleMapItems;
@property (nonatomic) MKMapItem mapItem;
@property (nonatomic) BOOL bottomHairlineHidden;
@property (nonatomic) _MKPlaceViewController owner;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)mapItem;
- (void)setOwner:;
- (id)owner;
- (void)setMapItem:;
- (BOOL)_canShowWhileLocked;
- (long long)preferredUserInterfaceStyle;
- (void).cxx_destruct;
- (id)snapshot;
- (void)loadView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)_updateMap;
- (void)_handleTapOnMap;
- (id)initWithMKMapItem:;
- (void)setBottomHairlineHidden:;
- (id)visibleMapItems;
- (void)_updateMapIfNeeded;
- (void)updateInlineMapWithRefinedMapItems;
- (void)_updateInlineMapWithRefinedMapItems;
- (void)cancelSnapshotRequestIfNeeded;
- (id)_mapSize;
- (void)_updateSnapshotImage:;
- (void)_launchMaps;
- (id)traitCollectionForSnapshot;
- (BOOL)isBottomHairlineHidden;
- (BOOL)useWindowTrait;
- (void)setUseWindowTrait:;
- (id)mapCamera;
- (void)setMapCamera:;
+ (id)inlineMapWithMapItem:options:;
@end
