@interface MKPointAnnotation : MKShape
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) q representation;
@property (nonatomic) {CLLocationCoordinate2D=dd} coordinate;
@property (nonatomic) BOOL showsBalloonCallout;
@property (nonatomic) double course;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) CLLocation location;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
- (id)annotation;
- (id)feature;
- (id)initWithCoordinate:;
- (id)reuseIdentifier;
- (id)init;
- (BOOL)isPersistent;
- (void)prepareForReuse;
- (id)_initWithGeoJSONObject:error:;
- (id)location;
- (void)setLocation:;
- (void).cxx_destruct;
- (id)coordinate;
- (void)setCoordinate:;
- (long long)representation;
- (BOOL)_shouldDeselectWhenDragged;
- (id)viewRepresentation;
- (void)_setHiddenForOffscreen:;
- (void)_invalidateCachedCoordinate;
- (BOOL)_isPendingSelectionAnimated;
- (BOOL)showsBalloonCallout;
- (id)initWithCoordinate:title:subtitle:;
- (void)setShowsBalloonCallout:;
- (BOOL)shouldRepresentSelf;
- (void)setRepresentation:;
@end
