@interface MKTileOverlay : NSObject
@property (nonatomic) I providerID;
@property (nonatomic) {CGSize=dd} tileSize;
@property (nonatomic) BOOL geometryFlipped;
@property (nonatomic) q minimumZ;
@property (nonatomic) q maximumZ;
@property (nonatomic) NSString URLTemplate;
@property (nonatomic) BOOL canReplaceMapContent;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) {CLLocationCoordinate2D=dd} coordinate;
@property (nonatomic) {?={?=dd}{?=dd}} boundingMapRect;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
- (void)_receivedMemoryNotification;
- (id)init;
- (void)dealloc;
- (id)boundingMapRect;
- (id)tileSize;
- (void)setTileSize:;
- (void).cxx_destruct;
- (id)coordinate;
- (BOOL)isGeometryFlipped;
- (void)setGeometryFlipped:;
- (unsigned int)_providerID;
- (BOOL)canReplaceMapContent;
- (void)loadTileAtPath:result:;
- (void)_cancelLoadingTileAtPath:;
- (long long)minimumZ;
- (void)setMinimumZ:;
- (long long)maximumZ;
- (void)setMaximumZ:;
- (void)_assignProviderID;
- (id)initWithURLTemplate:;
- (id)URLForTilePath:;
- (id)_keyForPath:;
- (void)_loadTile:result:;
- (void)_scheduleMinLifetimeCacheCleanupIfNecessary;
- (void)_minLifetimeCacheCleanupFired;
- (int)_zoomLevelForScale:;
- (id)_tilesInMapRect:zoomScale:contentScale:;
- (void)_flushCaches;
- (id)URLTemplate;
- (void)setCanReplaceMapContent:;
@end
