@interface MLCOptimizer : NSObject
@property (nonatomic) MLCDevice device;
@property (nonatomic) NSArray deviceOps;
@property (nonatomic) Q numOptimizerDataBuffers;
@property (nonatomic) NSMutableArray oneStepOptimizerBuffers;
@property (nonatomic) float learningRate;
@property (nonatomic) float gradientRescale;
@property (nonatomic) BOOL appliesGradientClipping;
@property (nonatomic) float gradientClipMax;
@property (nonatomic) float gradientClipMin;
@property (nonatomic) float regularizationScale;
@property (nonatomic) NSInteger regularizationType;
@property (nonatomic) NSInteger gradientClippingType;
@property (nonatomic) float maximumClippingNorm;
@property (nonatomic) float customGlobalNorm;
- (id)initWithDescriptor:;
- (void)setDevice:;
- (void).cxx_destruct;
- (id)description;
- (float)learningRate;
- (id)device;
- (id)copyWithZone:;
- (void)setLearningRate:;
- (float)gradientClipMin;
- (float)gradientClipMax;
- (void)setDeviceOps:;
- (id)deviceOps;
- (void)bindDevice:deviceOps:;
- (void)setNumOptimizerDataBuffers:;
- (float)gradientRescale;
- (BOOL)appliesGradientClipping;
- (float)regularizationScale;
- (int)regularizationType;
- (int)gradientClippingType;
- (float)maximumClippingNorm;
- (float)customGlobalNorm;
- (unsigned long long)numOptimizerDataBuffers;
- (id)initWithLearningRate:gradientRescale:applyGradientClipping:gradientClipMax:gradientClipMin:regularizationScale:regularizationType:gradientClippingType:maximumClippingNorm:customGlobalNorm:;
- (id)initWithLearningRate:gradientRescale:applyGradientClipping:gradientClipMax:gradientClipMin:regularizationScale:regularizationType:;
- (void)setAppliesGradientClipping:;
- (id)oneStepOptimizerBuffers;
- (void)setOneStepOptimizerBuffers:;
@end
