@interface MPAVRoutingViewItem : NSObject
@property (nonatomic) q type;
@property (nonatomic) MPAVRoute mainRoute;
@property (nonatomic) NSArray routes;
@property (nonatomic) MPAVRoute leader;
@property (nonatomic) NSString localizedTitle;
@property (nonatomic) NSString localizedSubtitle;
@property (nonatomic) BOOL enabled;
@property (nonatomic) UIImage image;
@property (nonatomic) NSString actionIdentifier;
@property (nonatomic) BOOL nearby;
@property (nonatomic) NSString vendorSpecificCustomRowIdentifier;
@property (nonatomic) BOOL expandable;
@property (nonatomic) BOOL expanded;
@property (nonatomic) BOOL pickable;
@property (nonatomic) Q nestedLevel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)isExpanded;
- (id)routes;
- (BOOL)isPickable;
- (BOOL)enabled;
- (id)_stateDumpObject;
- (id)localizedSubtitle;
- (id)leader;
- (void)setExpanded:;
- (id)mainRoute;
- (unsigned long long)hash;
- (void)setNearby:;
- (long long)type;
- (BOOL)isExpandable;
- (id)actionIdentifier;
- (BOOL)isNearby;
- (void).cxx_destruct;
- (id)localizedTitle;
- (unsigned long long)nestedLevel;
- (id)vendorSpecificCustomRowIdentifier;
- (BOOL)isEqual:;
- (id)image;
+ (id)itemWithVendorSpecificRoute:;
+ (id)itemWithVendorSpecificCustomRowTitle:icon:identifier:;
+ (id)itemWithLeader:members:;
+ (id)itemWithActionTitle:subtitle:enabled:identifier:image:;
+ (id)itemWithRoute:;
@end
