@interface MPRouteLabel : UIView
@property (nonatomic) BSUIEmojiLabelView contentView;
@property (nonatomic) q minimumEndCharacterCount;
@property (nonatomic) NSString text;
@property (nonatomic) q truncationMode;
@property (nonatomic) BOOL forcesUppercaseText;
@property (nonatomic) BOOL displayAsSiriSuggestion;
@property (nonatomic) MPAVRoute route;
@property (nonatomic) UILabel titleLabel;
@property (nonatomic) UIColor textColor;
@property (nonatomic) UIFont font;
@property (nonatomic) double _baselineOffsetFromBottom;
@property (nonatomic) q textAlignment;
@property (nonatomic) BOOL _textColorFollowsTintColor;
- (void)removeRouteNamesFromArray:;
- (void)removeRouteName:;
- (BOOL)_labelFitsText:withSize:;
- (id)contentView;
- (id)_routeNamesSortedAlphanumeric:;
- (void)setMinimumEndCharacterCount:;
- (void)setRoute:;
- (id)_truncateText:by:;
- (long long)truncationMode;
- (id)intrinsicContentSize;
- (void)layoutSubviews;
- (id)_marketingNames;
- (id)route;
- (void)setDisplayAsSiriSuggestion:;
- (void)addRouteNamesFromArray:;
- (void)setFont:;
- (BOOL)displayAsSiriSuggestion;
- (void)_updateTitleIfNeeded;
- (double)_baselineOffsetFromBottom;
- (id)_routeNamesSortedLength:;
- (void)_setTextColorFollowsTintColor:;
- (BOOL)forcesUppercaseText;
- (long long)minimumEndCharacterCount;
- (id)initWithFrame:;
- (void)_updateRouteLabel;
- (void)setTextColor:;
- (void)setTruncationMode:;
- (BOOL)_textColorFollowsTintColor;
- (id)sizeThatFits:;
- (id)_formattedRouteNameForDesignatedGroupLeaderNameText:routeNamesText:;
- (void).cxx_destruct;
- (id)font;
- (id)textColor;
- (long long)textAlignment;
- (long long)_compareLength:with:;
- (void)setContentView:;
- (void)setTextAlignment:;
- (id)_labelSizeForText:;
- (void)addRouteName:;
- (void)setForcesUppercaseText:;
- (id)_bestStringThatFitsSize:;
- (id)text;
- (id)_plusSeparatedRouteNames:;
- (id)titleLabel;
- (void)_routeDidChangeNotification:;
@end
