@interface MPServerObjectDatabase : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)removeObserver:;
- (BOOL)shouldRenewPlaybackAuthorizationTokenForEntityMatchingIdentifierSet:trustID:;
- (void)addObserver:;
- (id)assetsWithMiniSINFsMatchingIdentifierSet:;
- (id)relatedIdentifierSetsForParentIdentifierSet:parentVersionHash:childKey:;
- (id)payloadDataForIdentifierSet:outError:;
- (id)payloadForRelatedEntityWithIdentifierSet:;
- (id)importObjectsFromRequest:options:trustID:playActivityFeatureName:error:;
- (id)_assetsMatchingIdentifierSet:query:;
- (id)modelObjectMatchingIdentifierSet:propertySet:trustID:;
- (void)purgeGlideSubscriptionDataForHashedAccoundID:;
- (id)importObjectsFromRequest:options:error:;
- (id)modelObjectMatchingIdentifierSet:propertySet:;
- (id)_hlsAssetMatchingIdentifierSet:query:;
- (id)playbackAuthorizationTokenForEntityMatchingIdentifierSet:trustID:;
- (id)modelGenericObjectFromObject:playbackAuthorizationToken:;
- (id)_payloadForIdentifierSet:outError:;
- (void).cxx_destruct;
- (id)relatedIdentifierSetsForParentIdentifierSet:childKey:;
- (BOOL)importAssetsFromRequest:error:;
- (void)enumerateAssetsMissingSINFsForHashedPersonID:usingBlock:;
- (void)removePlaybackAuthorizationTokensForTrust:;
- (id)hlsAssetMatchingIdentifierSet:;
- (id)_modelObjectMatchingIdentifierSet:propertySet:;
- (id)assetsMatchingIdentifierSet:;
- (void)unregisterObserver:;
- (void)registerObserver:;
- (id)_initWithDatabaseCreationBlock:;
- (id)importObjectsFromRequest:options:trustID:error:;
- (BOOL)_createDatabaseSchema;
+ (BOOL)prefersInMemoryDatabase;
+ (id)sharedServerObjectDatabase;
+ (void)setPrefersInMemoryDatabase:;
@end
