@interface MPStoreItemMetadataRequest : NSObject
@property (nonatomic) ICClientInfo clientInfo;
@property (nonatomic) ICUserIdentity delegatedUserIdentity;
@property (nonatomic) ICUserIdentity userIdentity;
@property (nonatomic) ICUserIdentityStore userIdentityStore;
@property (nonatomic) ICStorePlatformRequest storePlatformRequest;
@property (nonatomic) BOOL allowLocalEquivalencies;
@property (nonatomic) Q reason;
@property (nonatomic) NSArray itemIdentifiers;
@property (nonatomic) NSNumber timeoutInterval;
@property (nonatomic) NSString platform;
@property (nonatomic) double retryDelay;
@property (nonatomic) BOOL shouldIgnoreCache;
@property (nonatomic) BOOL shouldIgnoreExpiration;
@property (nonatomic) BOOL shouldRequireCachedResults;
@property (nonatomic) NSString clientIdentifier;
@property (nonatomic) NSString requestingBundleIdentifier;
@property (nonatomic) NSString requestingBundleVersion;
@property (nonatomic) BOOL personalized;
@property (nonatomic) q personalizationStyle;
- (long long)personalizationStyle;
- (void)setClientInfo:;
- (id)itemIdentifiers;
- (id)init;
- (void)setPlatform:;
- (void)setDelegatedUserIdentity:;
- (void)setShouldIgnoreExpiration:;
- (void)setRequestingBundleIdentifier:;
- (id)userIdentityStore;
- (id)clientInfo;
- (BOOL)shouldIgnoreExpiration;
- (void)setUserIdentityStore:;
- (BOOL)shouldIgnoreCache;
- (unsigned long long)reason;
- (double)retryDelay;
- (void)setReason:;
- (void)setRequestingBundleVersion:;
- (BOOL)allowLocalEquivalencies;
- (void)setShouldRequireCachedResults:;
- (BOOL)shouldRequireCachedResults;
- (id)timeoutInterval;
- (id)userIdentity;
- (id)delegatedUserIdentity;
- (id)requestingBundleIdentifier;
- (id)platform;
- (id)storePlatformRequest;
- (void).cxx_destruct;
- (void)setItemIdentifiers:;
- (void)setUserIdentity:;
- (BOOL)isPersonalized;
- (void)setClientIdentifier:;
- (id)requestingBundleVersion;
- (void)setTimeoutInterval:;
- (void)setPersonalizationStyle:;
- (id)clientIdentifier;
- (void)setAllowLocalEquivalencies:;
- (void)setRetryDelay:;
- (void)setShouldIgnoreCache:;
@end
