@interface MRAirPlayTransportConnection : MRExternalDeviceTransportConnection
@property (nonatomic) BOOL channelClosed;
@property (nonatomic) NSDate dateCreated;
@property (nonatomic) NSDate mostRecentMessageSentDate;
@property (nonatomic) Q totalMessagesSentCount;
@property (nonatomic) Q totalBytesSentCount;
@property (nonatomic) NSDate mostRecentMessageReceivedDate;
@property (nonatomic) Q totalMessagesReceivedCount;
@property (nonatomic) Q totalBytesReceivedCount;
@property (nonatomic) MROSTransaction transaction;
@property (nonatomic) @ effectiveChannel;
@property (nonatomic) APReceiverMediaRemoteCommunicationChannel apCommunicationChannel;
@property (nonatomic) AVOutputContextCommunicationChannel outputContextCommunicationChannel;
@property (nonatomic) AVOutputDeviceCommunicationChannel outputDeviceCommunicationChannel;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setTransaction:;
- (id)transaction;
- (void)closeWithError:;
- (id)debugDescription;
- (BOOL)isValid;
- (id)dateCreated;
- (void).cxx_destruct;
- (id)description;
- (id)_init;
- (void)setDateCreated:;
- (void)communicationChannel:didReceiveData:;
- (void)communicationChannelDidClose:;
- (unsigned long long)sendTransportData:options:;
- (void)ingestData:;
- (id)initWithAPCommunicationChannel:;
- (id)initWithOutputContextCommunicationChannel:outputContext:;
- (id)initWithOutputDeviceCommunicationChannel:;
- (unsigned long long)_sendTransportData:;
- (id)effectiveChannel;
- (id)apCommunicationChannel;
- (id)outputContextCommunicationChannel;
- (id)outputDeviceCommunicationChannel;
- (BOOL)channelClosed;
- (void)setChannelClosed:;
- (id)mostRecentMessageSentDate;
- (void)setMostRecentMessageSentDate:;
- (unsigned long long)totalMessagesSentCount;
- (void)setTotalMessagesSentCount:;
- (unsigned long long)totalBytesSentCount;
- (void)setTotalBytesSentCount:;
- (id)mostRecentMessageReceivedDate;
- (void)setMostRecentMessageReceivedDate:;
- (unsigned long long)totalMessagesReceivedCount;
- (void)setTotalMessagesReceivedCount:;
- (unsigned long long)totalBytesReceivedCount;
- (void)setTotalBytesReceivedCount:;
@end
