@interface MRContentItem : NSObject
@property (nonatomic) _MRContentItemProtobuf protobuf;
@property (nonatomic) NSString identifier;
@property (nonatomic) MRContentItemMetadata metadata;
@property (nonatomic) NSString info;
@property (nonatomic) NSArray availableLanguageOptions;
@property (nonatomic) NSArray currentLanguageOptions;
@property (nonatomic) NSArray sections;
@property (nonatomic) NSString parentIdentifier;
@property (nonatomic) NSString ancestorIdentifier;
@property (nonatomic) NSString associatedParticipantIdentifier;
@property (nonatomic) NSString queueIdentifier;
@property (nonatomic) NSString requestIdentifier;
@property (nonatomic) MRArtwork artwork;
@property (nonatomic) MRContentItem skeleton;
@property (nonatomic) NSData data;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) NSDictionary nowPlayingInfo;
- (id)sections;
- (id)skeleton;
- (id)requestIdentifier;
- (id)queueIdentifier;
- (id)parentIdentifier;
- (id)artwork;
- (void)setParentIdentifier:;
- (id)initWithProtobuf:;
- (id)initWithNowPlayingInfo:;
- (id)availableLanguageOptions;
- (void)setAssociatedParticipantIdentifier:;
- (id)data;
- (id)protobuf;
- (id)metadata;
- (void)setInfo:;
- (id)identifier;
- (id)associatedParticipantIdentifier;
- (void)setAncestorIdentifier:;
- (void)setNowPlayingInfo:policy:request:;
- (id)nowPlayingInfo;
- (BOOL)isEffectivelyEqual:;
- (void)setMetadata:;
- (void)mergeFrom:;
- (void)setRequestIdentifier:;
- (void)setAvailableLanguageOptions:;
- (id)currentLanguageOptions;
- (id)initWithData:;
- (void)setCurrentLanguageOptions:;
- (void).cxx_destruct;
- (void)setSections:;
- (id)description;
- (id)info;
- (void)setArtwork:;
- (id)ancestorIdentifier;
- (id)dictionaryRepresentation;
- (id)initWithIdentifier:;
- (void)setQueueIdentifier:;
- (void)setIdentifier:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
+ (id)extractedIdentifierFromNowPlayingInfo:;
+ (id)mergeContentItems:;
@end
