@interface MSCMSSignerInfo : NSObject
@property (nonatomic) ^{__SecKey={__CFRuntimeBase=QAQ}^{__SecKeyDescriptor}^v} signerPrivKey;
@property (nonatomic) ^{SignerInfo=i{heim_base_data=Q^v}{AlgorithmIdentifier={heim_oid=Q^I}^{heim_base_data}}^{heim_base_data}{AlgorithmIdentifier={heim_oid=Q^I}^{heim_base_data}}{heim_base_data=Q^v}^{heim_base_data}} encodedSignerInfo;
@property (nonatomic) NSData signature;
@property (nonatomic) ^{__SecCertificate=} signerCertificate;
@property (nonatomic) MSAlgorithmIdentifier signatureAlgorithm;
@property (nonatomic) NSData signedAttrsData;
@property (nonatomic) {heim_base_data=Q^v} signedAttrsSet;
@property (nonatomic) NSData unsignedAttrsData;
@property (nonatomic) {heim_base_data=Q^v} unsignedAttrsSet;
@property (nonatomic) NSData identifierData;
@property (nonatomic) NSNumber version;
@property (nonatomic) MSCMSSignedData containingSignedData;
@property (nonatomic) MSAlgorithmIdentifier digestAlgorithm;
@property (nonatomic) MSCMSMutableAttributeArray protectedAttributes;
@property (nonatomic) MSCMSMutableAttributeArray unprotectedAttributes;
@property (nonatomic) NSData LAContext;
- (void)setSignature:;
- (id)signature;
- (void)dealloc;
- (void)setVersion:;
- (id)version;
- (void)setLAContext:;
- (void)setIdentifierData:;
- (id)signatureAlgorithm;
- (void).cxx_destruct;
- (id)LAContext;
- (id)identifierData;
- (void)setSignatureAlgorithm:;
- (id)unprotectedAttributes;
- (id)protectedAttributes;
- (id)createTrustObjectWithPolicies:error:;
- (id)getAttributesWithType:;
- (id)signerCertificate;
- (id)initWithIdentity:error:;
- (BOOL)verifyTimestamps:;
- (id)digestAlgorithm;
- (void)setUnprotectedAttributes:;
- (id)initWithCertificate:error:;
- (id)initWithEmail:LAContext:error:;
- (id)initWithCertificate:signatureAlgorithm:error:;
- (id)initWithIdentity:signatureAlgorithm:error:;
- (id)initWithEmail:signatureAlgorithm:LAContext:error:;
- (id)initWithCertificate:recipientsAlgorithmCapabilities:error:;
- (id)initWithIdentity:recipientsAlgorithmCapabilities:error:;
- (id)initWithEmail:recipientsAlgorithmCapabilities:LAContext:error:;
- (id)calculateSignedAttributesDigest:;
- (BOOL)verifyContentTypeAttribute:;
- (BOOL)verifyMessageDigestAttribute:error:;
- (id)calculateSignerInfoDigest:;
- (BOOL)verifySignature:;
- (id)verifyTime:;
- (BOOL)verifySignatureAndSignerWithPolicies:verifyTime:error:;
- (BOOL)verifyCountersignatures:;
- (BOOL)verifyCountersignaturesAndCountersignersWithPolicies:verifyTime:error:;
- (BOOL)sign:;
- (BOOL)encodeSignerInfo:error:;
- (void)setSignerCertificate:;
- (void)setProtectedAttributes:;
- (id)signerPrivKey;
- (void)setSignerPrivKey:;
- (id)encodedSignerInfo;
- (void)setEncodedSignerInfo:;
- (id)signedAttrsData;
- (void)setSignedAttrsData:;
- (id)signedAttrsSet;
- (void)setSignedAttrsSet:;
- (id)unsignedAttrsData;
- (void)setUnsignedAttrsData:;
- (id)unsignedAttrsSet;
- (void)setUnsignedAttrsSet:;
- (id)containingSignedData;
- (void)setContainingSignedData:;
- (void)setDigestAlgorithm:;
+ (id)decodeSignerInfo:certificates:LAContext:error:;
@end
