@interface MTVisualStylingProvider : NSObject
@property (nonatomic) MTCoreMaterialVisualStylingProvider coreMaterialVisualStylingProvider;
@property (nonatomic) MTCoreMaterialVisualStylingProvider coreMaterialVisualStylingProvider;
@property (nonatomic) NSMutableDictionary styleNamesToVisualStylings;
@property (nonatomic) NSMapTable viewsAndLayersToCoreMaterialVisualStyles;
@property (nonatomic) NSMapTable viewsAndLayersToObserverBlocks;
@property (nonatomic) NSPointerArray privateObservers;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)_removeObserver:;
- (void)providedStylesDidChangeForProvider:;
- (void)_addObserver:;
- (void).cxx_destruct;
- (id)description;
- (void)automaticallyUpdateView:withStyle:;
- (id)_visualStylingForStyle:;
- (void)stopAutomaticallyUpdatingView:;
- (id)_styleNamesToVisualStylings;
- (BOOL)isAutomaticallyUpdatingView:;
- (void)automaticallyUpdateView:withStyle:andObserverBlock:;
- (id)newAutomaticallyUpdatingViewWithStyle:;
- (void)_automaticallyUpdateView:withStyleNamed:andObserverBlock:;
- (id)_visualStylingForStyleNamed:;
- (void)automaticallyUpdateLayer:withStyle:andObserverBlock:;
- (id)_visualStylingForContinuallyUpdatedView:;
- (void)automaticallyUpdateLayer:withStyle:;
- (void)stopAutomaticallyUpdatingLayer:;
- (BOOL)isAutomaticallyUpdatingLayer:;
- (void)_automaticallyUpdateViewOrLayer:withStyleNamed:andObserverBlock:;
- (void)_stopAutomaticallyUpdatingViewOrLayer:;
- (BOOL)_isAutomaticallyUpdatingViewOrLayer:;
- (void)_updateVisualStyleOfViewOrLayer:;
- (id)_coreMaterialVisualStylingProvider;
- (void)setCoreMaterialVisualStylingProvider:;
- (void)setStyleNamesToVisualStylings:;
- (id)_viewsAndLayersToCoreMaterialVisualStyles;
- (void)setViewsAndLayersToCoreMaterialVisualStyles:;
- (id)_viewsAndLayersToObserverBlocks;
- (void)setViewsAndLayersToObserverBlocks:;
- (id)_privateObservers;
- (void)setPrivateObservers:;
- (id)initWithCoreMaterialVisualStylingProvider:;
+ (id)_visualStylingProviderForRecipe:category:andUserInterfaceStyle:;
+ (Class)_visualStylingClass;
+ (id)_visualStylingProviderForStyleSetNamed:inBundle:;
+ (id)_visualStylingProviderForRecipeNamed:andCategory:;
+ (id)_visualStylingProviderForRecipe:andCategory:;
@end
