@interface NEProfileIngestion : NSObject
@property (nonatomic) NSString clientName;
@property (nonatomic) NSString payloadType;
@property (nonatomic) NEConfigurationManager manager;
@property (nonatomic) NSMutableArray currentConfigurations;
@property (nonatomic) NEConfiguration ingestedConfiguration;
- (id)clientName;
- (void)dealloc;
- (BOOL)removeConfigurationWithIdentifier:;
- (id)initWithName:;
- (id)manager;
- (BOOL)removeConfiguration:;
- (void).cxx_destruct;
- (id)payloadType;
- (id)initWithNameAndType:payloadType:;
- (BOOL)loadConfigurationsForceReloadFromDisk;
- (id)findConfigurationByName:;
- (id)findConfigurationByPayloadUUID:;
- (id)findConfigurationByConfigurationID:;
- (BOOL)createConfigurationFromPayload:payloadType:;
- (id)ingestedConfiguration;
- (BOOL)saveIngestedConfiguration;
- (BOOL)saveIngestedConfiguration:;
- (BOOL)removeIngestedConfiguration;
- (id)setAsideConfigurationName:unsetAside:;
- (BOOL)isInstalled:;
- (BOOL)lockConfigurations;
- (void)unlockConfigurations;
- (void)enableDefaultService;
- (BOOL)enableAlwaysOnVpn;
- (BOOL)updateDefaultAfterAddingConfiguration;
- (BOOL)updateDefaultAfterDeletingConfiguration;
- (id)copyManagedConfigurationIDs;
- (BOOL)updateAppLayerVPNMappingRules:;
- (BOOL)updatePerAppMappingRules:;
- (BOOL)updateManagedAppRules:;
- (BOOL)updateAccountIdentifiers:;
- (id)getCertificatesForConfigurationWithIdentifier:;
- (void)removeAllConfigurationsWithPayload:profile:;
- (id)currentConfigurations;
- (void)setCurrentConfigurations:;
- (void)setIngestedConfiguration:;
+ (id)getServiceIDForPayload:;
+ (void)profileMigrationComplete;
@end
