@interface NEVPNProtocol : NSObject
@property (nonatomic) NSUUID identifier;
@property (nonatomic) q type;
@property (nonatomic) BOOL disconnectOnWake;
@property (nonatomic) NSInteger disconnectOnWakeTimeout;
@property (nonatomic) NEKeychainItem passwordKeychainItem;
@property (nonatomic) NSString passwordEncryption;
@property (nonatomic) NSData identityReferenceInternal;
@property (nonatomic) NSData identityDataInternal;
@property (nonatomic) BOOL identityDataImported;
@property (nonatomic) NSData identityDataHash;
@property (nonatomic) NEKeychainItem identityDataPasswordKeychainItem;
@property (nonatomic) NEDNSSettings DNSSettings;
@property (nonatomic) NSString extensibleSSOProvider;
@property (nonatomic) BOOL disconnectOnIdle;
@property (nonatomic) NSInteger disconnectOnIdleTimeout;
@property (nonatomic) BOOL disconnectOnUserSwitch;
@property (nonatomic) BOOL disconnectOnLogout;
@property (nonatomic) NSString serverAddress;
@property (nonatomic) NSString username;
@property (nonatomic) NSData passwordReference;
@property (nonatomic) NSData identityReference;
@property (nonatomic) NSData identityData;
@property (nonatomic) NSString identityDataPassword;
@property (nonatomic) BOOL disconnectOnSleep;
@property (nonatomic) NEProxySettings proxySettings;
@property (nonatomic) BOOL includeAllNetworks;
@property (nonatomic) BOOL excludeLocalNetworks;
@property (nonatomic) BOOL enforceRoutes;
- (BOOL)checkValidityAndCollectErrors:;
- (id)identityData;
- (id)initFromLegacyDictionary:;
- (id)username;
- (id)descriptionWithIndent:options:;
- (id)copyLegacyDictionary;
- (void)setUsername:;
- (id)identifier;
- (id)initWithCoder:;
- (id)proxySettings;
- (void)encodeWithCoder:;
- (long long)type;
- (void).cxx_destruct;
- (id)description;
- (void)setIdentifier:;
- (id)initWithType:;
- (id)copyWithZone:;
- (void)setIdentityData:;
- (id)serverAddress;
- (void)setServerAddress:;
- (id)identityReference;
- (void)setIdentityReference:;
- (id)passwordReference;
- (void)setPasswordReference:;
- (id)DNSSettings;
- (void)setDNSSettings:;
- (void)setProxySettings:;
- (BOOL)setServiceProtocolsInService:;
- (BOOL)updateWithServiceProtocolsFromService:;
- (void)copyPasswordsFromKeychainInDomain:;
- (void)removeKeychainItemsInDomain:keepIdentity:;
- (void)syncWithKeychainInDomain:configuration:suffix:;
- (id)createInterface;
- (id)initWithProtocolIdentifier:;
- (void)addDisconnectOptions:;
- (void)initDisconnectOptions:;
- (void)setIdentityReferenceInternal:;
- (id)identityReferenceInternal;
- (void)syncWithKeychainInDomainCommon:;
- (BOOL)needToUpdateKeychain;
- (void)migratePasswordsFromPreferences:;
- (id)identityDataPassword;
- (void)setIdentityDataPassword:;
- (BOOL)disconnectOnSleep;
- (void)setDisconnectOnSleep:;
- (BOOL)includeAllNetworks;
- (void)setIncludeAllNetworks:;
- (BOOL)excludeLocalNetworks;
- (void)setExcludeLocalNetworks:;
- (BOOL)enforceRoutes;
- (void)setEnforceRoutes:;
- (BOOL)disconnectOnWake;
- (void)setDisconnectOnWake:;
- (int)disconnectOnWakeTimeout;
- (void)setDisconnectOnWakeTimeout:;
- (id)passwordKeychainItem;
- (void)setPasswordKeychainItem:;
- (id)passwordEncryption;
- (void)setPasswordEncryption:;
- (id)identityDataInternal;
- (void)setIdentityDataInternal:;
- (BOOL)identityDataImported;
- (void)setIdentityDataImported:;
- (id)identityDataHash;
- (void)setIdentityDataHash:;
- (id)identityDataPasswordKeychainItem;
- (void)setIdentityDataPasswordKeychainItem:;
- (id)extensibleSSOProvider;
- (void)setExtensibleSSOProvider:;
- (BOOL)disconnectOnIdle;
- (void)setDisconnectOnIdle:;
- (int)disconnectOnIdleTimeout;
- (void)setDisconnectOnIdleTimeout:;
- (BOOL)disconnectOnUserSwitch;
- (void)setDisconnectOnUserSwitch:;
- (BOOL)disconnectOnLogout;
- (void)setDisconnectOnLogout:;
+ (BOOL)supportsSecureCoding;
@end
