@interface NLXSchemaNLXClientEventMetadata : SISchemaInstrumentationMessage
@property (nonatomic) SISchemaUUID nlId;
@property (nonatomic) BOOL hasNlId;
@property (nonatomic) NSString resultCandidateId;
@property (nonatomic) BOOL hasResultCandidateId;
@property (nonatomic) NSInteger componentInvocationSource;
@property (nonatomic) BOOL hasComponentInvocationSource;
@property (nonatomic) SISchemaUUID requestId;
@property (nonatomic) BOOL hasRequestId;
@property (nonatomic) NSData jsonData;
- (id)requestId;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)resultCandidateId;
- (void)setRequestId:;
- (void)setHasRequestId:;
- (BOOL)hasRequestId;
- (void)setResultCandidateId:;
- (void)deleteRequestId;
- (BOOL)hasResultCandidateId;
- (void)deleteResultCandidateId;
- (void)setHasResultCandidateId:;
- (BOOL)hasNlId;
- (void)deleteNlId;
- (void)setComponentInvocationSource:;
- (BOOL)hasComponentInvocationSource;
- (void)setHasComponentInvocationSource:;
- (void)deleteComponentInvocationSource;
- (id)nlId;
- (void)setNlId:;
- (int)componentInvocationSource;
- (void)setHasNlId:;
@end
