@interface NLXSchemaCDMUserDialogAct : SISchemaInstrumentationMessage
@property (nonatomic) USOSchemaUSOUtteranceAlignment alignment;
@property (nonatomic) BOOL hasAlignment;
@property (nonatomic) USOSchemaUSOGraph reference;
@property (nonatomic) BOOL hasReference;
@property (nonatomic) NLXSchemaCDMUserAccepted accepted;
@property (nonatomic) BOOL hasAccepted;
@property (nonatomic) NLXSchemaCDMUserRejected rejected;
@property (nonatomic) BOOL hasRejected;
@property (nonatomic) NLXSchemaCDMUserCancelled cancelled;
@property (nonatomic) BOOL hasCancelled;
@property (nonatomic) NLXSchemaCDMUserWantedToRepeat wantedToRepeat;
@property (nonatomic) BOOL hasWantedToRepeat;
@property (nonatomic) NLXSchemaCDMUserAcknowledged acknowledged;
@property (nonatomic) BOOL hasAcknowledged;
@property (nonatomic) NLXSchemaCDMUserWantedToProceed wantedToProceed;
@property (nonatomic) BOOL hasWantedToProceed;
@property (nonatomic) NLXSchemaCDMUserWantedToPause wantedToPause;
@property (nonatomic) BOOL hasWantedToPause;
@property (nonatomic) NLXSchemaCDMDelegatedUserDialogAct delegated;
@property (nonatomic) BOOL hasDelegated;
@property (nonatomic) NLXSchemaCDMUserStatedTask userStatedTask;
@property (nonatomic) BOOL hasUserStatedTask;
@property (nonatomic) NSData jsonData;
@property (nonatomic) Q whichUserdialogacttype;
- (id)cancelled;
- (id)reference;
- (void)setCancelled:;
- (void)setReference:;
- (void)setAlignment:;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void)setAcknowledged:;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)hasReference;
- (BOOL)readFrom:;
- (id)acknowledged;
- (id)dictionaryRepresentation;
- (id)alignment;
- (void)setDelegated:;
- (BOOL)isEqual:;
- (id)delegated;
- (void)setHasDelegated:;
- (BOOL)hasDelegated;
- (id)accepted;
- (void)setAccepted:;
- (void)setHasAlignment:;
- (BOOL)hasAlignment;
- (void)setHasCancelled:;
- (BOOL)hasCancelled;
- (void)setHasReference:;
- (id)rejected;
- (BOOL)hasRejected;
- (void)setRejected:;
- (void)deleteCancelled;
- (void)deleteAlignment;
- (void)deleteReference;
- (void)deleteAccepted;
- (void)deleteRejected;
- (void)setWantedToRepeat:;
- (id)wantedToRepeat;
- (void)deleteWantedToRepeat;
- (void)deleteAcknowledged;
- (void)setWantedToProceed:;
- (id)wantedToProceed;
- (void)deleteWantedToProceed;
- (void)setWantedToPause:;
- (id)wantedToPause;
- (void)deleteWantedToPause;
- (void)deleteDelegated;
- (void)setUserStatedTask:;
- (id)userStatedTask;
- (void)deleteUserStatedTask;
- (unsigned long long)whichUserdialogacttype;
- (BOOL)hasAccepted;
- (void)setHasAccepted:;
- (void)setHasRejected:;
- (BOOL)hasWantedToRepeat;
- (void)setHasWantedToRepeat:;
- (BOOL)hasAcknowledged;
- (void)setHasAcknowledged:;
- (BOOL)hasWantedToProceed;
- (void)setHasWantedToProceed:;
- (BOOL)hasWantedToPause;
- (void)setHasWantedToPause:;
- (BOOL)hasUserStatedTask;
- (void)setHasUserStatedTask:;
@end
