@interface NSMetadataQuery : NSObject
@property (nonatomic) <NSMetadataQueryDelegate> delegate;
@property (nonatomic) NSPredicate predicate;
@property (nonatomic) NSArray sortDescriptors;
@property (nonatomic) NSArray valueListAttributes;
@property (nonatomic) NSArray groupingAttributes;
@property (nonatomic) double notificationBatchingInterval;
@property (nonatomic) NSArray searchScopes;
@property (nonatomic) NSArray searchItems;
@property (nonatomic) NSOperationQueue operationQueue;
@property (nonatomic) BOOL started;
@property (nonatomic) BOOL gathering;
@property (nonatomic) BOOL stopped;
@property (nonatomic) Q resultCount;
@property (nonatomic) NSArray results;
@property (nonatomic) NSDictionary valueLists;
@property (nonatomic) NSArray groupedResults;
- (void)br_setupForMonitoringChildrenOfFolderAtURL:searchScopes:;
- (void)br_setupForMonitoringChildrenOfFolderAtURL:;
- (BOOL)br_setupForMonitoringItemAtURL:searchScopes:;
- (BOOL)br_setupForMonitoringItemAtURL:;
- (BOOL)br_setupForMonitoringChildrenOfItemAtURL:searchScopes:;
- (BOOL)br_setupForMonitoringChildrenOfItemAtURL:;
- (void)removeObserver:forKeyPath:;
- (void)setSortDescriptors:;
- (BOOL)isStarted;
- (id)sortDescriptors;
- (void)_update;
- (id)init;
- (void)dealloc;
- (void)setDelegate:;
- (unsigned long long)indexOfResult:;
- (id)operationQueue;
- (unsigned long long)resultCount;
- (id)predicate;
- (id)searchItems;
- (id)results;
- (id)delegate;
- (void)setPredicate:;
- (id)_queryString;
- (void)setSearchItems:;
- (void)stopQuery;
- (BOOL)isStopped;
- (void)setOperationQueue:;
- (id)_pendingChangeNotificationsArrayForKey:create:;
- (id)_externalDocumentsBundleIdentifier;
- (void)_noteNote1:;
- (void)_noteNote2:;
- (void)_noteNote3:;
- (void)_noteNote4:;
- (void)_noteNote5:;
- (BOOL)_canModifyQueryOrObserversInCurrentContext;
- (void)_validateInvocationContext;
- (void)_validatePredicate:withScopes:;
- (id)valueListAttributes;
- (void)setValueListAttributes:;
- (id)groupingAttributes;
- (void)setGroupingAttributes:;
- (id)_sortingAttributes;
- (id)_allAttributes;
- (double)notificationBatchingInterval;
- (void)setNotificationBatchingInterval:;
- (id)searchScopes;
- (void)setSearchScopes:;
- (id)searchItemURLs;
- (void)setSearchItemURLs:;
- (void)_setExternalDocumentsBundleIdentifier:;
- (void)_setBatchingParams;
- (void)_postNotificationName:userInfo:;
- (void)_resetQueryState;
- (void)_recreateQuery;
- (BOOL)startQuery;
- (void)_inOriginalContextInvokeBlock:;
- (BOOL)isGathering;
- (void)disableUpdates;
- (void)enableUpdates;
- (void)_disableAutoUpdates;
- (void)_enableAutoUpdates;
- (id)resultAtIndex:;
- (void)enumerateResultsUsingBlock:;
- (void)enumerateResultsWithOptions:usingBlock:;
- (void)_zapResultArrayIfIdenticalTo:;
- (id)valueLists;
- (id)groupedResults;
- (id)valueOfAttribute:forResultAtIndex:;
- (BOOL)_isMDQuery;
+ (BOOL)automaticallyNotifiesObserversForKey:;
+ (id)willBeginPossibleCreationOfItemAtURL:;
+ (id)willBeginPossibleDeletionOfItemAtURL:;
+ (Class)_stitchingClass;
+ (void)didEndPossibleFileOperation:;
+ (id)keyPathsForValuesAffectingValueForKey:;
+ (id)willBeginPossibleMoveOfItemAtURL:toURL:;
@end
