@interface NSPredicate : NSObject
@property (nonatomic) BOOL ef_matchesEverything;
@property (nonatomic) BOOL ef_matchesNothing;
@property (nonatomic) NSPredicate ef_simplifiedPredicate;
@property (nonatomic) NSString ef_publicDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSString predicateFormat;
- (id)minimalFormInContext:;
- (id)_keypathsForDerivedPropertyValidation:;
- (void)cn_triageWithLog:serialNumber:;
- (void)_cn_acceptVisitor:;
- (void)ab_bindWhereClauseComponentOfStatement:withBindingOffset:predicateIdentifier:;
- (id)ab_metadataForMatchingRow:columnOffset:;
- (void)ab_bindJoinClauseComponentOfStatement:withBindingOffset:predicateIdentifier:;
- (void)ab_runPredicateWithSortOrder:ranked:inAddressBook:withDelegate:;
- (void)ab_addCallbackContextToArray:;
- (BOOL)ab_hasCallback;
- (void)ab_bindSelectClauseComponentOfStatement:withBindingOffset:predicateIdentifier:;
- (id)ab_newQueryWithSortOrder:ranked:addressBook:propertyIndices:;
- (id)cls_normalizedPredicate:error:;
- (id)br_watchedURL;
- (id)br_urlWithWatchedChildren;
- (id)br_fileObjectIDWithWatchedChildren;
- (id)br_watchedFileObjectID;
- (BOOL)_isContentTypeFolderComparisonPredicate;
- (BOOL)isFolderOnlyPredicate;
- (id)extractSearchTermFromPredicate;
- (id)em_searchableIndexQueryGenerator;
- (id)ef_publicDescription;
- (BOOL)ef_matchesEverything;
- (BOOL)ef_matchesNothing;
- (id)ef_simplifiedPredicate;
- (BOOL)ef_containsKeyPath:;
- (BOOL)ef_containsSubpredicate:;
- (id)_ef_parenthesizedPublicDescription;
- (id)predicateNodeFromPropertyMapper:;
- (void)acceptVisitor:flags:;
- (BOOL)evaluateWithObject:;
- (id)predicateFormat;
- (BOOL)_allowsEvaluation;
- (void)allowEvaluation;
- (id)initWithCoder:;
- (BOOL)evaluateWithObject:substitutionVariables:;
- (id)predicateWithSubstitutionVariables:;
- (void)encodeWithCoder:;
- (id)description;
- (id)copyWithZone:;
- (void)_validateForMetadataQueryScopes:;
- (id)generateMetadataDescription;
+ (id)predicateForAssetsInAssetCollectionWithID:;
+ (id)predicateForCloudInvitationsInAssetCollection:;
+ (id)predicateForCommentsInAsset:;
+ (id)predicateForLikesInAsset:;
+ (id)vcp_imagesPredicate:;
+ (id)vcp_stillImagesPredicate:;
+ (id)vcp_livePhotosPredicate:;
+ (id)vcp_nonPanoPredicate:;
+ (id)vcp_moviesPredicate:;
+ (id)vcp_fullAnalysisPredatesVersionInternalPredicate:;
+ (float)_peopleThreshold;
+ (id)mad_prioritizedAssetsForFaceDetectionInternalPredicate;
+ (id)mad_nonPrioritizedAssetsForFaceDetectionInternalPredicate;
+ (id)mad_internalPredicateForTaskID:;
+ (id)mad_internalPredicateWithPriority:forTaskID:;
+ (id)mad_internalPredicateNeedsProcessingForTaskID:;
+ (id)tu_predicateForConversationLinkDescriptorsWithActivated:;
+ (id)tu_predicateForConversationLinkDescriptorsWithCreationDate:;
+ (id)tu_predicateForConversationLinkDescriptorsWithExpirationDate:;
+ (id)tu_predicateForConversationLinkDescriptorsWithExpirationDateAfter:;
+ (id)tu_predicateForConversationLinkDescriptorsWithGroupUUID:;
+ (id)tu_predicateForConversationLinkDescriptorsWithInvitedHandle:;
+ (id)tu_predicateForConversationLinkDescriptorsWithInvitedHandleNormalizedValue:;
+ (id)tu_predicateForConversationLinkDescriptorsWithInvitedHandleType:;
+ (id)tu_predicateForConversationLinkDescriptorsWithInvitedHandleValue:;
+ (id)tu_predicateForConversationLinkDescriptorsWithOriginatorHandle:;
+ (id)tu_predicateForConversationLinkDescriptorsWithOriginatorHandleNormalizedValue:;
+ (id)tu_predicateForConversationLinkDescriptorsWithOriginatorHandleType:;
+ (id)tu_predicateForConversationLinkDescriptorsWithOriginatorHandleValue:;
+ (id)tu_predicateForConversationLinkDescriptorsWithPseudonym:;
+ (id)tu_predicateForConversationLinkDescriptorsWithPublicKey:;
+ (id)tu_predicateForConversationLinkDescriptorsWithPrivateKey:;
+ (id)ef_matchEverythingPredicate;
+ (id)ef_matchNothingPredicate;
+ (id)ef_andCompoundPredicateForOptionalPredicate:second:;
+ (BOOL)supportsSecureCoding;
+ (id)newStringFrom:usingUnicodeTransforms:;
+ (id)retainedLocale;
+ (id)predicateWithFormat:arguments:;
+ (id)predicateWithFormat:argumentArray:;
+ (id)predicateWithFormat:;
+ (id)predicateWithValue:;
+ (id)predicateWithBlock:;
@end
