@interface NWAWDLibnetcoreTCPECNInterfaceStatsReport : PBCodable
@property (nonatomic) BOOL hasInterfaceType;
@property (nonatomic) Q interfaceType;
@property (nonatomic) BOOL hasIpProtocol;
@property (nonatomic) Q ipProtocol;
@property (nonatomic) BOOL hasTcpECNIntClientSetup;
@property (nonatomic) Q tcpECNIntClientSetup;
@property (nonatomic) BOOL hasTcpECNIntServerSetup;
@property (nonatomic) Q tcpECNIntServerSetup;
@property (nonatomic) BOOL hasTcpECNIntClientSuccess;
@property (nonatomic) Q tcpECNIntClientSuccess;
@property (nonatomic) BOOL hasTcpECNIntServerSuccess;
@property (nonatomic) Q tcpECNIntServerSuccess;
@property (nonatomic) BOOL hasTcpECNIntNotSupportedPeer;
@property (nonatomic) Q tcpECNIntNotSupportedPeer;
@property (nonatomic) BOOL hasTcpECNIntSynLost;
@property (nonatomic) Q tcpECNIntSynLost;
@property (nonatomic) BOOL hasTcpECNIntSynAckLost;
@property (nonatomic) Q tcpECNIntSynAckLost;
@property (nonatomic) BOOL hasTcpECNIntRecvCE;
@property (nonatomic) Q tcpECNIntRecvCE;
@property (nonatomic) BOOL hasTcpECNIntRecvECE;
@property (nonatomic) Q tcpECNIntRecvECE;
@property (nonatomic) BOOL hasTcpECNIntSentECE;
@property (nonatomic) Q tcpECNIntSentECE;
@property (nonatomic) BOOL hasTcpECNIntConnRecvCE;
@property (nonatomic) Q tcpECNIntConnRecvCE;
@property (nonatomic) BOOL hasTcpECNIntConnRecvECE;
@property (nonatomic) Q tcpECNIntConnRecvECE;
@property (nonatomic) BOOL hasTcpECNIntConnPLNoCE;
@property (nonatomic) Q tcpECNIntConnPLNoCE;
@property (nonatomic) BOOL hasTcpECNIntConnPLCE;
@property (nonatomic) Q tcpECNIntConnPLCE;
@property (nonatomic) BOOL hasTcpECNIntConnNoPLCE;
@property (nonatomic) Q tcpECNIntConnNoPLCE;
@property (nonatomic) BOOL hasTcpECNIntFallbackSynLoss;
@property (nonatomic) Q tcpECNIntFallbackSynLoss;
@property (nonatomic) BOOL hasTcpECNIntFallbackReorder;
@property (nonatomic) Q tcpECNIntFallbackReorder;
@property (nonatomic) BOOL hasTcpECNIntFallbackCE;
@property (nonatomic) Q tcpECNIntFallbackCE;
@property (nonatomic) BOOL hasTcpECNIntOnAvgRTT;
@property (nonatomic) Q tcpECNIntOnAvgRTT;
@property (nonatomic) BOOL hasTcpECNIntOnRTTVar;
@property (nonatomic) Q tcpECNIntOnRTTVar;
@property (nonatomic) BOOL hasTcpECNIntOnOOBPer;
@property (nonatomic) Q tcpECNIntOnOOBPer;
@property (nonatomic) BOOL hasTcpECNIntOnSACKE;
@property (nonatomic) Q tcpECNIntOnSACKE;
@property (nonatomic) BOOL hasTcpECNIntOnReorderPer;
@property (nonatomic) Q tcpECNIntOnReorderPer;
@property (nonatomic) BOOL hasTcpECNIntRxmtPer;
@property (nonatomic) Q tcpECNIntRxmtPer;
@property (nonatomic) BOOL hasTcpECNIntOffAvgRTT;
@property (nonatomic) Q tcpECNIntOffAvgRTT;
@property (nonatomic) BOOL hasTcpECNIntOffRTTVar;
@property (nonatomic) Q tcpECNIntOffRTTVar;
@property (nonatomic) BOOL hasTcpECNIntOffOOBPer;
@property (nonatomic) Q tcpECNIntOffOOBPer;
@property (nonatomic) BOOL hasTcpECNIntOffSACKE;
@property (nonatomic) Q tcpECNIntOffSACKE;
@property (nonatomic) BOOL hasTcpECNIntOffReorderPer;
@property (nonatomic) Q tcpECNIntOffReorderPer;
@property (nonatomic) BOOL hasTcpECNIntOffRxmtPer;
@property (nonatomic) Q tcpECNIntOffRxmtPer;
@property (nonatomic) BOOL hasTcpECNIntOnTotalTxPkts;
@property (nonatomic) Q tcpECNIntOnTotalTxPkts;
@property (nonatomic) BOOL hasTcpECNIntOnTotalRxmtPkts;
@property (nonatomic) Q tcpECNIntOnTotalRxmtPkts;
@property (nonatomic) BOOL hasTcpECNIntOnTotalRxPkts;
@property (nonatomic) Q tcpECNIntOnTotalRxPkts;
@property (nonatomic) BOOL hasTcpECNIntOnTotalOOPkts;
@property (nonatomic) Q tcpECNIntOnTotalOOPkts;
@property (nonatomic) BOOL hasTcpECNIntOnDropRst;
@property (nonatomic) Q tcpECNIntOnDropRst;
@property (nonatomic) BOOL hasTcpECNIntOnDropRxmt;
@property (nonatomic) Q tcpECNIntOnDropRxmt;
@property (nonatomic) BOOL hasTcpECNIntOffTotalTxPkts;
@property (nonatomic) Q tcpECNIntOffTotalTxPkts;
@property (nonatomic) BOOL hasTcpECNIntOffTotalRxmtPkts;
@property (nonatomic) Q tcpECNIntOffTotalRxmtPkts;
@property (nonatomic) BOOL hasTcpECNIntOffTotalRxPkts;
@property (nonatomic) Q tcpECNIntOffTotalRxPkts;
@property (nonatomic) BOOL hasTcpECNIntOffTotalOOPkts;
@property (nonatomic) Q tcpECNIntOffTotalOOPkts;
@property (nonatomic) BOOL hasTcpECNIntOffDropRst;
@property (nonatomic) Q tcpECNIntOffDropRst;
@property (nonatomic) BOOL hasTcpECNIntOffDropRxmt;
@property (nonatomic) Q tcpECNIntOffDropRxmt;
@property (nonatomic) BOOL hasTcpECNIntTotalConnections;
@property (nonatomic) Q tcpECNIntTotalConnections;
@property (nonatomic) BOOL hasTcpUnsentDataAtSleepCnt;
@property (nonatomic) Q tcpUnsentDataAtSleepCnt;
@property (nonatomic) BOOL hasTcpECNIntFallbackDropRst;
@property (nonatomic) Q tcpECNIntFallbackDropRst;
@property (nonatomic) BOOL hasTcpECNIntFallbackDropRxmt;
@property (nonatomic) Q tcpECNIntFallbackDropRxmt;
@property (nonatomic) BOOL hasTcpECNIntFallbackSYNRst;
@property (nonatomic) Q tcpECNIntFallbackSYNRst;
- (void)setInterfaceType:;
- (unsigned long long)interfaceType;
- (void)writeTo:;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (BOOL)hasInterfaceType;
- (unsigned long long)ipProtocol;
- (BOOL)readFrom:;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (void)setHasInterfaceType:;
- (void)setIpProtocol:;
- (void)setHasIpProtocol:;
- (BOOL)hasIpProtocol;
- (void)setTcpECNIntClientSetup:;
- (void)setHasTcpECNIntClientSetup:;
- (BOOL)hasTcpECNIntClientSetup;
- (void)setTcpECNIntServerSetup:;
- (void)setHasTcpECNIntServerSetup:;
- (BOOL)hasTcpECNIntServerSetup;
- (void)setTcpECNIntClientSuccess:;
- (void)setHasTcpECNIntClientSuccess:;
- (BOOL)hasTcpECNIntClientSuccess;
- (void)setTcpECNIntServerSuccess:;
- (void)setHasTcpECNIntServerSuccess:;
- (BOOL)hasTcpECNIntServerSuccess;
- (void)setTcpECNIntNotSupportedPeer:;
- (void)setHasTcpECNIntNotSupportedPeer:;
- (BOOL)hasTcpECNIntNotSupportedPeer;
- (void)setTcpECNIntSynLost:;
- (void)setHasTcpECNIntSynLost:;
- (BOOL)hasTcpECNIntSynLost;
- (void)setTcpECNIntSynAckLost:;
- (void)setHasTcpECNIntSynAckLost:;
- (BOOL)hasTcpECNIntSynAckLost;
- (void)setTcpECNIntRecvCE:;
- (void)setHasTcpECNIntRecvCE:;
- (BOOL)hasTcpECNIntRecvCE;
- (void)setTcpECNIntRecvECE:;
- (void)setHasTcpECNIntRecvECE:;
- (BOOL)hasTcpECNIntRecvECE;
- (void)setTcpECNIntSentECE:;
- (void)setHasTcpECNIntSentECE:;
- (BOOL)hasTcpECNIntSentECE;
- (void)setTcpECNIntConnRecvCE:;
- (void)setHasTcpECNIntConnRecvCE:;
- (BOOL)hasTcpECNIntConnRecvCE;
- (void)setTcpECNIntConnRecvECE:;
- (void)setHasTcpECNIntConnRecvECE:;
- (BOOL)hasTcpECNIntConnRecvECE;
- (void)setTcpECNIntConnPLNoCE:;
- (void)setHasTcpECNIntConnPLNoCE:;
- (BOOL)hasTcpECNIntConnPLNoCE;
- (void)setTcpECNIntConnPLCE:;
- (void)setHasTcpECNIntConnPLCE:;
- (BOOL)hasTcpECNIntConnPLCE;
- (void)setTcpECNIntConnNoPLCE:;
- (void)setHasTcpECNIntConnNoPLCE:;
- (BOOL)hasTcpECNIntConnNoPLCE;
- (void)setTcpECNIntFallbackSynLoss:;
- (void)setHasTcpECNIntFallbackSynLoss:;
- (BOOL)hasTcpECNIntFallbackSynLoss;
- (void)setTcpECNIntFallbackReorder:;
- (void)setHasTcpECNIntFallbackReorder:;
- (BOOL)hasTcpECNIntFallbackReorder;
- (void)setTcpECNIntFallbackCE:;
- (void)setHasTcpECNIntFallbackCE:;
- (BOOL)hasTcpECNIntFallbackCE;
- (void)setTcpECNIntOnAvgRTT:;
- (void)setHasTcpECNIntOnAvgRTT:;
- (BOOL)hasTcpECNIntOnAvgRTT;
- (void)setTcpECNIntOnRTTVar:;
- (void)setHasTcpECNIntOnRTTVar:;
- (BOOL)hasTcpECNIntOnRTTVar;
- (void)setTcpECNIntOnOOBPer:;
- (void)setHasTcpECNIntOnOOBPer:;
- (BOOL)hasTcpECNIntOnOOBPer;
- (void)setTcpECNIntOnSACKE:;
- (void)setHasTcpECNIntOnSACKE:;
- (BOOL)hasTcpECNIntOnSACKE;
- (void)setTcpECNIntOnReorderPer:;
- (void)setHasTcpECNIntOnReorderPer:;
- (BOOL)hasTcpECNIntOnReorderPer;
- (void)setTcpECNIntRxmtPer:;
- (void)setHasTcpECNIntRxmtPer:;
- (BOOL)hasTcpECNIntRxmtPer;
- (void)setTcpECNIntOffAvgRTT:;
- (void)setHasTcpECNIntOffAvgRTT:;
- (BOOL)hasTcpECNIntOffAvgRTT;
- (void)setTcpECNIntOffRTTVar:;
- (void)setHasTcpECNIntOffRTTVar:;
- (BOOL)hasTcpECNIntOffRTTVar;
- (void)setTcpECNIntOffOOBPer:;
- (void)setHasTcpECNIntOffOOBPer:;
- (BOOL)hasTcpECNIntOffOOBPer;
- (void)setTcpECNIntOffSACKE:;
- (void)setHasTcpECNIntOffSACKE:;
- (BOOL)hasTcpECNIntOffSACKE;
- (void)setTcpECNIntOffReorderPer:;
- (void)setHasTcpECNIntOffReorderPer:;
- (BOOL)hasTcpECNIntOffReorderPer;
- (void)setTcpECNIntOffRxmtPer:;
- (void)setHasTcpECNIntOffRxmtPer:;
- (BOOL)hasTcpECNIntOffRxmtPer;
- (void)setTcpECNIntOnTotalTxPkts:;
- (void)setHasTcpECNIntOnTotalTxPkts:;
- (BOOL)hasTcpECNIntOnTotalTxPkts;
- (void)setTcpECNIntOnTotalRxmtPkts:;
- (void)setHasTcpECNIntOnTotalRxmtPkts:;
- (BOOL)hasTcpECNIntOnTotalRxmtPkts;
- (void)setTcpECNIntOnTotalRxPkts:;
- (void)setHasTcpECNIntOnTotalRxPkts:;
- (BOOL)hasTcpECNIntOnTotalRxPkts;
- (void)setTcpECNIntOnTotalOOPkts:;
- (void)setHasTcpECNIntOnTotalOOPkts:;
- (BOOL)hasTcpECNIntOnTotalOOPkts;
- (void)setTcpECNIntOnDropRst:;
- (void)setHasTcpECNIntOnDropRst:;
- (BOOL)hasTcpECNIntOnDropRst;
- (void)setTcpECNIntOnDropRxmt:;
- (void)setHasTcpECNIntOnDropRxmt:;
- (BOOL)hasTcpECNIntOnDropRxmt;
- (void)setTcpECNIntOffTotalTxPkts:;
- (void)setHasTcpECNIntOffTotalTxPkts:;
- (BOOL)hasTcpECNIntOffTotalTxPkts;
- (void)setTcpECNIntOffTotalRxmtPkts:;
- (void)setHasTcpECNIntOffTotalRxmtPkts:;
- (BOOL)hasTcpECNIntOffTotalRxmtPkts;
- (void)setTcpECNIntOffTotalRxPkts:;
- (void)setHasTcpECNIntOffTotalRxPkts:;
- (BOOL)hasTcpECNIntOffTotalRxPkts;
- (void)setTcpECNIntOffTotalOOPkts:;
- (void)setHasTcpECNIntOffTotalOOPkts:;
- (BOOL)hasTcpECNIntOffTotalOOPkts;
- (void)setTcpECNIntOffDropRst:;
- (void)setHasTcpECNIntOffDropRst:;
- (BOOL)hasTcpECNIntOffDropRst;
- (void)setTcpECNIntOffDropRxmt:;
- (void)setHasTcpECNIntOffDropRxmt:;
- (BOOL)hasTcpECNIntOffDropRxmt;
- (void)setTcpECNIntTotalConnections:;
- (void)setHasTcpECNIntTotalConnections:;
- (BOOL)hasTcpECNIntTotalConnections;
- (void)setTcpUnsentDataAtSleepCnt:;
- (void)setHasTcpUnsentDataAtSleepCnt:;
- (BOOL)hasTcpUnsentDataAtSleepCnt;
- (void)setTcpECNIntFallbackDropRst:;
- (void)setHasTcpECNIntFallbackDropRst:;
- (BOOL)hasTcpECNIntFallbackDropRst;
- (void)setTcpECNIntFallbackDropRxmt:;
- (void)setHasTcpECNIntFallbackDropRxmt:;
- (BOOL)hasTcpECNIntFallbackDropRxmt;
- (void)setTcpECNIntFallbackSYNRst:;
- (void)setHasTcpECNIntFallbackSYNRst:;
- (BOOL)hasTcpECNIntFallbackSYNRst;
- (unsigned long long)tcpECNIntClientSetup;
- (unsigned long long)tcpECNIntServerSetup;
- (unsigned long long)tcpECNIntClientSuccess;
- (unsigned long long)tcpECNIntServerSuccess;
- (unsigned long long)tcpECNIntNotSupportedPeer;
- (unsigned long long)tcpECNIntSynLost;
- (unsigned long long)tcpECNIntSynAckLost;
- (unsigned long long)tcpECNIntRecvCE;
- (unsigned long long)tcpECNIntRecvECE;
- (unsigned long long)tcpECNIntSentECE;
- (unsigned long long)tcpECNIntConnRecvCE;
- (unsigned long long)tcpECNIntConnRecvECE;
- (unsigned long long)tcpECNIntConnPLNoCE;
- (unsigned long long)tcpECNIntConnPLCE;
- (unsigned long long)tcpECNIntConnNoPLCE;
- (unsigned long long)tcpECNIntFallbackSynLoss;
- (unsigned long long)tcpECNIntFallbackReorder;
- (unsigned long long)tcpECNIntFallbackCE;
- (unsigned long long)tcpECNIntOnAvgRTT;
- (unsigned long long)tcpECNIntOnRTTVar;
- (unsigned long long)tcpECNIntOnOOBPer;
- (unsigned long long)tcpECNIntOnSACKE;
- (unsigned long long)tcpECNIntOnReorderPer;
- (unsigned long long)tcpECNIntRxmtPer;
- (unsigned long long)tcpECNIntOffAvgRTT;
- (unsigned long long)tcpECNIntOffRTTVar;
- (unsigned long long)tcpECNIntOffOOBPer;
- (unsigned long long)tcpECNIntOffSACKE;
- (unsigned long long)tcpECNIntOffReorderPer;
- (unsigned long long)tcpECNIntOffRxmtPer;
- (unsigned long long)tcpECNIntOnTotalTxPkts;
- (unsigned long long)tcpECNIntOnTotalRxmtPkts;
- (unsigned long long)tcpECNIntOnTotalRxPkts;
- (unsigned long long)tcpECNIntOnTotalOOPkts;
- (unsigned long long)tcpECNIntOnDropRst;
- (unsigned long long)tcpECNIntOnDropRxmt;
- (unsigned long long)tcpECNIntOffTotalTxPkts;
- (unsigned long long)tcpECNIntOffTotalRxmtPkts;
- (unsigned long long)tcpECNIntOffTotalRxPkts;
- (unsigned long long)tcpECNIntOffTotalOOPkts;
- (unsigned long long)tcpECNIntOffDropRst;
- (unsigned long long)tcpECNIntOffDropRxmt;
- (unsigned long long)tcpECNIntTotalConnections;
- (unsigned long long)tcpUnsentDataAtSleepCnt;
- (unsigned long long)tcpECNIntFallbackDropRst;
- (unsigned long long)tcpECNIntFallbackDropRxmt;
- (unsigned long long)tcpECNIntFallbackSYNRst;
@end
