@interface OPTTSTextToSpeechRequest : NSObject
@property (nonatomic) NSString speech_id;
@property (nonatomic) NSString session_id;
@property (nonatomic) NSString language;
@property (nonatomic) NSString gender;
@property (nonatomic) NSString text;
@property (nonatomic) q audio_type;
@property (nonatomic) BOOL enable_word_timing_info;
@property (nonatomic) NSString voice_name;
@property (nonatomic) NSArray context_info;
@property (nonatomic) q preferred_voice_type;
@property (nonatomic) OPTTSTextToSpeechRequestMeta meta_info;
@property (nonatomic) OPTTSTextToSpeechRequestContext context;
@property (nonatomic) OPTTSTextToSpeechRequestExperiment experiment;
@property (nonatomic) OPTTSTTSRequestFeatureFlags feature_flags;
@property (nonatomic) OPTTSTextToSpeechRequestDebug debug;
@property (nonatomic) OPTTSTextToSpeechUserProfile profile;
@property (nonatomic) OPTTSTextToSpeechRequestDevConfig dev_config;
@property (nonatomic) OPTTSTextToSpeechRequestProsodyTransferConfig prosody_config;
@property (nonatomic) OPTTSTextToSpeechRequestProsodyControlConfig prosody_control_config;
- (id)gender;
- (id)debug;
- (id)language;
- (id)context;
- (id)profile;
- (void).cxx_destruct;
- (id)experiment;
- (id)text;
- (id)copyWithZone:;
- (id)context_info;
- (id)speech_id;
- (id)session_id;
- (long long)audio_type;
- (BOOL)enable_word_timing_info;
- (id)voice_name;
- (long long)preferred_voice_type;
- (id)meta_info;
- (id)feature_flags;
- (id)dev_config;
- (id)prosody_config;
- (id)prosody_control_config;
- (id)flatbuffData;
- (id)initWithFlatbuffData:;
- (id)initAndVerifyWithFlatbuffData:;
- (id)initWithFlatbuffData:root:;
- (id)initWithFlatbuffData:root:verify:;
- (id)addObjectToBuffer:;
- (id)context_info_objectAtIndex:;
- (unsigned long long)context_info_count;
- (void)context_info_enumerateObjectsUsingBlock:;
@end
