@interface OspreyRequest : NSObject
@property (nonatomic) NSString methodName;
@property (nonatomic) NSData data;
@property (nonatomic) NSDictionary headers;
@property (nonatomic) BOOL enableDeviceAuthentication;
@property (nonatomic) NSData signedDeviceAuthenticationData;
@property (nonatomic) NSNumber deviceAuthenticationVersion;
@property (nonatomic) BOOL useCompression;
@property (nonatomic) BOOL forceHTTPv2;
@property (nonatomic) NSString clientTraceId;
@property (nonatomic) NSString userAgent;
@property (nonatomic) BOOL allowsCellularAccess;
@property (nonatomic) BOOL requireAbsintheAuthentication;
- (BOOL)allowsCellularAccess;
- (id)userAgent;
- (void)setAllowsCellularAccess:;
- (id)data;
- (void)setHeaders:;
- (void).cxx_destruct;
- (void)setData:;
- (id)headers;
- (void)setUseCompression:;
- (id)deviceAuthenticationVersion;
- (void)setDeviceAuthenticationVersion:;
- (id)initWithMethodName:;
- (id)grpcRequestWithBaseURL:;
- (BOOL)requireAbsintheAuthentication;
- (void)setRequireAbsintheAuthentication:;
- (id)methodName;
- (BOOL)enableDeviceAuthentication;
- (void)setEnableDeviceAuthentication:;
- (id)signedDeviceAuthenticationData;
- (void)setSignedDeviceAuthenticationData:;
- (BOOL)useCompression;
- (BOOL)forceHTTPv2;
- (void)setForceHTTPv2:;
- (id)clientTraceId;
- (void)setClientTraceId:;
+ (id)requestWithMethodName:;
@end
