@interface PDAggregateMeasurement : NSObject
@property (nonatomic) PDContainer container;
@property (nonatomic) NSString metric;
@property (nonatomic) NSString unitString;
@property (nonatomic) NSMutableDictionary variables;
@property (nonatomic) NSMutableDictionary labels;
@property (nonatomic) ^{running_mean=ddQ} values_mean;
@property (nonatomic) ^{pooled_mean={sum=dd}{sum=dd}QQ} stats_mean;
@property (nonatomic) BOOL validMin;
@property (nonatomic) double min;
@property (nonatomic) BOOL validMax;
@property (nonatomic) double max;
@property (nonatomic) Q samples;
@property (nonatomic) PDMeasurement measurement;
- (unsigned long long)samples;
- (void)setContainer:;
- (void)dealloc;
- (void)setSamples:;
- (id)container;
- (double)min;
- (id)unitString;
- (id)labels;
- (double)max;
- (void).cxx_destruct;
- (id)measurement;
- (void)setMax:;
- (void)setMetric:;
- (id)metric;
- (void)setMin:;
- (void)setLabels:;
- (id)variables;
- (void)setUnitString:;
- (id)initWithContainer:metric:unitString:;
- (void)updateWithMeasurement:;
- (void)setVariables:;
- (id)values_mean;
- (void)setValues_mean:;
- (id)stats_mean;
- (void)setStats_mean:;
- (BOOL)validMin;
- (void)setValidMin:;
- (BOOL)validMax;
- (void)setValidMax:;
@end
