@interface PGPlaybackState : NSObject
@property (nonatomic) BOOL supportsFaceTimeActions;
@property (nonatomic) BOOL cameraActive;
@property (nonatomic) BOOL canSwitchCamera;
@property (nonatomic) BOOL microphoneMuted;
@property (nonatomic) BOOL disablesLayerCloning;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL cameraHasMicrophone;
@property (nonatomic) BOOL disablesLayerCloning;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSMutableDictionary mutableDictionary;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) BOOL supportsMicroPIP;
@property (nonatomic) q contentType;
@property (nonatomic) double elapsedTime;
@property (nonatomic) double contentDuration;
@property (nonatomic) q timeControlStatus;
@property (nonatomic) double playbackRate;
@property (nonatomic) BOOL muted;
@property (nonatomic) BOOL requiresLinearPlayback;
@property (nonatomic) BOOL hasInvalidTiming;
@property (nonatomic) BOOL routingVideoToHostedWindow;
@property (nonatomic) PGPlaybackStatePrerollAttributes prerollAttributes;
@property (nonatomic) double normalizedProgress;
@property (nonatomic) q backgroundAudioPolicy;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)_setBool:forKey:;
- (void)setContentType:;
- (void)_setInteger:forKey:;
- (double)playbackRate;
- (void)setRequiresLinearPlayback:;
- (void)setPrerollAttributes:;
- (BOOL)isRoutingVideoToHostedWindow;
- (double)contentDuration;
- (id)prerollAttributes;
- (long long)contentType;
- (id)initWithDictionary:;
- (long long)timeControlStatus;
- (void)setMuted:;
- (double)elapsedTime;
- (BOOL)isMuted;
- (id)_stringForKey:;
- (id)succinctDescriptionBuilder;
- (void)setRoutingVideoToHostedWindow:;
- (BOOL)requiresLinearPlayback;
- (void).cxx_destruct;
- (id)succinctDescription;
- (id)description;
- (id)dictionaryRepresentation;
- (id)descriptionBuilderWithMultilinePrefix:;
- (BOOL)isEqual:;
- (id)descriptionWithMultilinePrefix:;
- (id)copyWithZone:;
- (id)mutableDictionary;
- (BOOL)_boolForKey:;
- (id)_numberForKey:;
- (id)_dictionaryForKey:;
- (void)setContentDuration:;
- (void)setBackgroundAudioPolicy:;
- (void)setPlaybackRate:elapsedTime:timeControlStatus:;
- (void)appendDescriptionForKey:value:toBuilder:;
- (void)updatePlaybackStateWithDiff:;
- (BOOL)supportsMicroPIP;
- (long long)backgroundAudioPolicy;
- (BOOL)isEquivalentToPlaybackState:;
- (id)diffFromPlaybackState:;
- (double)normalizedProgress;
- (double)anchorContentTime;
- (double)anchorWallTime;
- (BOOL)hasInvalidTiming;
- (long long)_integerForKey:;
- (double)_doubleForKey:;
- (void)_setDouble:forKey:;
- (void)_setStateValue:forKey:;
- (void)_setDictionaryOrNotFound:forKey:;
- (void)_ensureMutableDictionary;
- (BOOL)supportsFaceTimeActions;
- (void)setSupportsFaceTimeActions:;
- (BOOL)isCameraActive;
- (void)setCameraActive:;
- (BOOL)canSwitchCamera;
- (void)setCanSwitchCamera:;
- (BOOL)isMicrophoneMuted;
- (void)setMicrophoneMuted:;
- (BOOL)disablesLayerCloning;
- (void)setDisablesLayerCloning:;
- (BOOL)cameraHasMicrophone;
- (void)setCameraHasMicrophone:;
+ (id)defaultValueForKey:;
+ (id)keysForEqualityOfNumberValues;
@end
