@interface PHCollectionList : PHCollection
@property (nonatomic) NSArray collections;
@property (nonatomic) PHQuery query;
@property (nonatomic) @? childCollectionsSortingComparator;
@property (nonatomic) Q unreadAssetCollectionsCount;
@property (nonatomic) Q estimatedChildCollectionCount;
@property (nonatomic) BOOL keyCollectionsAtEnd;
@property (nonatomic) NSString cloudGUID;
@property (nonatomic) NSString transientIdentifier;
@property (nonatomic) q collectionListType;
@property (nonatomic) q collectionListSubtype;
@property (nonatomic) NSDate startDate;
@property (nonatomic) NSDate endDate;
@property (nonatomic) NSArray localizedLocationNames;
- (id)startDate;
- (id)collections;
- (BOOL)canPerformEditOperation:;
- (long long)collectionListType;
- (id)query;
- (id)objectReference;
- (long long)collectionListSubtype;
- (id)endDate;
- (id)cloudGUID;
- (void).cxx_destruct;
- (id)localizedTitle;
- (id)description;
- (id)transientIdentifier;
- (BOOL)hasLocationInfo;
- (BOOL)canContainCollections;
- (id)localizedLocationNames;
- (id)initWithFetchDictionary:propertyHint:photoLibrary:;
- (BOOL)collectionHasFixedOrder;
- (Class)changeRequestClass;
- (unsigned long long)collectionFixedOrderPriority;
- (id)parentFolderID;
- (id)effectiveCustomSortKey;
- (BOOL)keyCollectionsAtEnd;
- (id)initTransientWithCollections:orQuery:title:identifier:photoLibrary:;
- (id)childCollectionsSortingComparator;
- (unsigned long long)unreadAssetCollectionsCount;
- (unsigned long long)estimatedChildCollectionCount;
- (id)pl_assetContainerList;
+ (id)fetchTopLevelUserCollectionsWithOptions:;
+ (id)tm_hook_album_fetchTopLevelUserCollectionsWithOptions:;
+ (void)tm_hook_album_preload;
+ (id)tspk_album_fetchTopLevelUserCollectionsWithOptions:;
+ (void)tspk_album_preload;
+ (id)identifierCode;
+ (id)fetchType;
+ (id)managedEntityName;
+ (BOOL)managedObjectSupportsTrashedState;
+ (id)fetchPredicateFromComparisonPredicate:options:;
+ (id)entityKeyMap;
+ (id)propertiesToFetchWithHint:;
+ (id)fetchCollectionListsContainingCollection:options:;
+ (id)fetchCollectionListsWithLocalIdentifiers:options:;
+ (id)fetchCollectionListsWithType:subtype:options:;
+ (id)fetchRootAlbumCollectionListWithOptions:;
+ (id)fetchRootProjectCollectionListWithOptions:;
+ (id)fetchMomentListsWithSubtype:containingMoment:options:;
+ (id)fetchMomentListsWithSubtype:options:;
+ (id)transientCollectionListWithCollections:title:identifier:photoLibrary:;
+ (id)transientCollectionListWithCollections:title:;
+ (id)transientCollectionListWithCollectionsFetchResult:title:;
+ (id)transientCollectionListWithCollections:title:identifier:;
+ (id)transientCollectionListWithCollectionsFetchResult:title:identifier:;
+ (id)transientCollectionListWithAssetCollections:title:;
+ (id)transientCollectionListWithAssetCollectionsFetchResult:title:;
+ (id)transientCollectionListWithAssetCollections:title:identifier:;
+ (id)transientCollectionListWithAssetCollectionsFetchResult:title:identifier:;
+ (id)fetchCollectionListsForReferences:photoLibrary:;
@end
