@interface PHFaceChangeRequest : PHChangeRequest
@property (nonatomic) BOOL shouldClearFaceCropGenerationState;
@property (nonatomic) NSURL associatedPersonLibraryURL;
@property (nonatomic) PHObjectPlaceholder placeholderForCreatedFace;
@property (nonatomic) double size;
@property (nonatomic) double centerX;
@property (nonatomic) double centerY;
@property (nonatomic) double bodyCenterX;
@property (nonatomic) double bodyCenterY;
@property (nonatomic) double bodyWidth;
@property (nonatomic) double bodyHeight;
@property (nonatomic) s detectionType;
@property (nonatomic) q sourceWidth;
@property (nonatomic) q sourceHeight;
@property (nonatomic) double roll;
@property (nonatomic) BOOL isInVIPModel;
@property (nonatomic) BOOL hidden;
@property (nonatomic) BOOL inTrash;
@property (nonatomic) BOOL manual;
@property (nonatomic) BOOL hasSmile;
@property (nonatomic) double blurScore;
@property (nonatomic) BOOL leftEyeClosed;
@property (nonatomic) BOOL rightEyeClosed;
@property (nonatomic) @ adjustmentVersion;
@property (nonatomic) q nameSource;
@property (nonatomic) q faceAlgorithmVersion;
@property (nonatomic) double poseYaw;
@property (nonatomic) PHFaceprint faceprint;
@property (nonatomic) q clusterSequenceNumber;
@property (nonatomic) q qualityMeasure;
@property (nonatomic) double quality;
@property (nonatomic) S ageType;
@property (nonatomic) S sexType;
@property (nonatomic) S eyesState;
@property (nonatomic) S smileType;
@property (nonatomic) S facialHairType;
@property (nonatomic) S hairColorType;
@property (nonatomic) S glassesType;
@property (nonatomic) S eyeMakeupType;
@property (nonatomic) S lipMakeupType;
@property (nonatomic) S faceExpressionType;
@property (nonatomic) S headgearType;
@property (nonatomic) S hairType;
@property (nonatomic) S poseType;
@property (nonatomic) S skintoneType;
@property (nonatomic) S ethnicityType;
@property (nonatomic) BOOL hasFaceMask;
@property (nonatomic) S gazeType;
@property (nonatomic) double gazeCenterX;
@property (nonatomic) double gazeCenterY;
@property (nonatomic) NSString groupingIdentifier;
@property (nonatomic) BOOL isNewRequest;
@property (nonatomic) BOOL shouldPerformConcurrentWork;
@property (nonatomic) BOOL mutated;
@property (nonatomic) NSString managedEntityName;
@property (nonatomic) NSManagedObjectID objectID;
@property (nonatomic) BOOL clientEntitled;
@property (nonatomic) NSString clientName;
@property (nonatomic) q accessScopeOptionsRequirement;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)groupingIdentifier;
- (double)quality;
- (void)setQuality:;
- (id)adjustmentVersion;
- (id)managedEntityName;
- (double)roll;
- (void)setGroupingIdentifier:;
- (void).cxx_destruct;
- (void)setHidden:;
- (BOOL)isHidden;
- (void)setSize:;
- (double)size;
- (BOOL)manual;
- (void)setRoll:;
- (double)centerX;
- (double)centerY;
- (long long)sourceWidth;
- (long long)sourceHeight;
- (BOOL)hasSmile;
- (BOOL)isInTrash;
- (id)initWithUUID:objectID:;
- (void)encodeToXPCDict:;
- (id)initWithXPCDict:request:clientAuthorization:;
- (BOOL)applyMutationsToManagedObject:photoLibrary:error:;
- (id)initForNewObject;
- (id)createManagedObjectForInsertIntoPhotoLibrary:error:;
- (id)placeholderForCreatedFace;
- (void)setCenterX:;
- (void)setCenterY:;
- (double)bodyCenterX;
- (void)setBodyCenterX:;
- (double)bodyCenterY;
- (void)setBodyCenterY:;
- (double)bodyWidth;
- (void)setBodyWidth:;
- (double)bodyHeight;
- (void)setBodyHeight:;
- (short)detectionType;
- (void)setDetectionType:;
- (void)setSourceWidth:;
- (void)setSourceHeight:;
- (BOOL)isInVIPModel;
- (void)setIsInVIPModel:;
- (void)setInTrash:;
- (void)setManual:;
- (void)setHasSmile:;
- (double)blurScore;
- (void)setBlurScore:;
- (BOOL)isLeftEyeClosed;
- (void)setLeftEyeClosed:;
- (BOOL)isRightEyeClosed;
- (void)setRightEyeClosed:;
- (long long)nameSource;
- (void)setNameSource:;
- (double)poseYaw;
- (void)setPoseYaw:;
- (long long)faceAlgorithmVersion;
- (void)setFaceAlgorithmVersion:;
- (long long)clusterSequenceNumber;
- (void)setClusterSequenceNumber:;
- (long long)qualityMeasure;
- (void)setQualityMeasure:;
- (unsigned short)ageType;
- (void)setAgeType:;
- (unsigned short)sexType;
- (void)setSexType:;
- (unsigned short)eyesState;
- (void)setEyesState:;
- (unsigned short)smileType;
- (void)setSmileType:;
- (unsigned short)facialHairType;
- (void)setFacialHairType:;
- (unsigned short)hairColorType;
- (void)setHairColorType:;
- (unsigned short)glassesType;
- (void)setGlassesType:;
- (unsigned short)eyeMakeupType;
- (void)setEyeMakeupType:;
- (unsigned short)lipMakeupType;
- (void)setLipMakeupType:;
- (unsigned short)faceExpressionType;
- (void)setFaceExpressionType:;
- (unsigned short)headgearType;
- (void)setHeadgearType:;
- (unsigned short)hairType;
- (void)setHairType:;
- (unsigned short)poseType;
- (void)setPoseType:;
- (unsigned short)skintoneType;
- (void)setSkintoneType:;
- (unsigned short)ethnicityType;
- (void)setEthnicityType:;
- (BOOL)hasFaceMask;
- (void)setHasFaceMask:;
- (unsigned short)gazeType;
- (void)setGazeType:;
- (double)gazeCenterX;
- (void)setGazeCenterX:;
- (double)gazeCenterY;
- (void)setGazeCenterY:;
- (void)setAdjustmentVersion:;
- (void)setFaceprint:;
- (id)faceprint;
- (void)setDetectionTraits:;
- (void)associateFaceWithPersonUUID:;
- (BOOL)_associateFace:withPersonInPhotoLibrary:error:;
- (id)_copyPersonWithPersonUUID:toLibrary:error:;
- (void)setShouldClearFaceCropGenerationState:;
- (BOOL)shouldClearFaceCropGenerationState;
- (id)associatedPersonLibraryURL;
- (void)setAssociatedPersonLibraryURL:;
+ (void)deleteFaces:;
+ (id)creationRequestForFace;
+ (id)changeRequestForFace:;
@end
