@interface PHLibraryScopeChangeRequest : PHChangeRequest
@property (nonatomic) PHShareRelationshipChangeRequestHelper participantsHelper;
@property (nonatomic) PHLibraryScope originalLibraryScope;
@property (nonatomic) NSString title;
@property (nonatomic) NSDate creationDate;
@property (nonatomic) s participantCloudUpdateState;
@property (nonatomic) BOOL runningAsUnitTest;
@property (nonatomic) NSArray assetUUIDsManuallyAddedToLibraryScope;
@property (nonatomic) NSArray assetUUIDsManuallyRemovedFromLibraryScope;
@property (nonatomic) NSArray assetUUIDsPhotosSuggestedAddedToLibraryScope;
@property (nonatomic) NSArray assetUUIDsPhotosSuggestedRemovedFromLibraryScope;
@property (nonatomic) NSArray assetUUIDsPhotosSuggestedRejectedFromLibraryScope;
@property (nonatomic) NSArray assetUUIDsPhotosSuggestedUnRejectedFromLibraryScope;
@property (nonatomic) NSArray assetUUIDsAssetsMarkedRejectedByPhotosSuggesterFromLibraryScope;
@property (nonatomic) NSArray participantsAddedToLibraryScope;
@property (nonatomic) NSArray participantsRemovedFromLibraryScope;
@property (nonatomic) PHObjectPlaceholder placeholderForCreatedLibraryScope;
@property (nonatomic) s autoSharePolicy;
@property (nonatomic) BOOL isNewRequest;
@property (nonatomic) BOOL shouldPerformConcurrentWork;
@property (nonatomic) BOOL mutated;
@property (nonatomic) NSString managedEntityName;
@property (nonatomic) NSManagedObjectID objectID;
@property (nonatomic) BOOL clientEntitled;
@property (nonatomic) NSString clientName;
@property (nonatomic) q accessScopeOptionsRequirement;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setStatus:;
- (id)trashedDate;
- (id)scopeIdentifier;
- (void)setTrashedDate:;
- (void)setCreationDate:;
- (id)managedEntityName;
- (void)setTitle:;
- (short)previewState;
- (void)addParticipants:;
- (id)title;
- (long long)scopeType;
- (void).cxx_destruct;
- (short)status;
- (short)exitState;
- (id)creationDate;
- (void)setScopeIdentifier:;
- (void)setScopeType:;
- (void)removeParticipants:;
- (id)initWithUUID:objectID:;
- (void)encodeToXPCDict:;
- (id)initWithXPCDict:request:clientAuthorization:;
- (BOOL)allowMutationToManagedObject:propertyKey:error:;
- (BOOL)applyMutationsToManagedObject:photoLibrary:error:;
- (id)initForNewObject;
- (BOOL)validateInsertIntoPhotoLibrary:error:;
- (id)createManagedObjectForInsertIntoPhotoLibrary:error:;
- (id)placeholderForCreatedLibraryScope;
- (id)rulesData;
- (void)setRulesData:;
- (id)lastParticipantAssetTrashNotificationDate;
- (void)setLastParticipantAssetTrashNotificationDate:;
- (short)participantCloudUpdateState;
- (void)setParticipantCloudUpdateState:;
- (void)setPreviewState:;
- (short)scopeSyncingState;
- (void)setScopeSyncingState:;
- (short)localPublishState;
- (void)setLocalPublishState:;
- (void)setExitState:;
- (void)setPendingLibraryScopeInvitationToPreviewState;
- (short)autoSharePolicy;
- (void)setAutoSharePolicy:;
- (void)moveToSharedLibrary:;
- (void)moveToPersonalLibrary:;
- (void)addPreviewAssetsSuggestedByPhotos:;
- (void)removePreviewAssetsSuggestedByPhotos:;
- (void)rejectPreviewAssetsSuggestedByPhotos:;
- (void)unRejectPreviewAssetsSuggestedByPhotos:;
- (void)markAssetsAsRejectedByPhotosSuggester:;
- (void)_updateParticipantCloudUpdateStateIfNecessary;
- (void)updateWithCustomRules:;
- (id)participantsHelper;
- (id)originalLibraryScope;
- (void)setOriginalLibraryScope:;
- (BOOL)runningAsUnitTest;
- (void)setRunningAsUnitTest:;
- (id)assetUUIDsManuallyAddedToLibraryScope;
- (void)setAssetUUIDsManuallyAddedToLibraryScope:;
- (id)assetUUIDsManuallyRemovedFromLibraryScope;
- (void)setAssetUUIDsManuallyRemovedFromLibraryScope:;
- (id)assetUUIDsPhotosSuggestedAddedToLibraryScope;
- (void)setAssetUUIDsPhotosSuggestedAddedToLibraryScope:;
- (id)assetUUIDsPhotosSuggestedRemovedFromLibraryScope;
- (void)setAssetUUIDsPhotosSuggestedRemovedFromLibraryScope:;
- (id)assetUUIDsPhotosSuggestedRejectedFromLibraryScope;
- (void)setAssetUUIDsPhotosSuggestedRejectedFromLibraryScope:;
- (id)assetUUIDsPhotosSuggestedUnRejectedFromLibraryScope;
- (void)setAssetUUIDsPhotosSuggestedUnRejectedFromLibraryScope:;
- (id)assetUUIDsAssetsMarkedRejectedByPhotosSuggesterFromLibraryScope;
- (void)setAssetUUIDsAssetsMarkedRejectedByPhotosSuggesterFromLibraryScope:;
- (id)participantsAddedToLibraryScope;
- (void)setParticipantsAddedToLibraryScope:;
- (id)participantsRemovedFromLibraryScope;
- (void)setParticipantsRemovedFromLibraryScope:;
+ (id)changeRequestForLibraryScope:;
+ (id)creationRequestForOwnedLibraryScopeInPreviewStateWithTitle:;
+ (void)trashLibraryScopes:;
+ (void)untrashLibraryScopes:;
+ (void)expungeLibraryScopes:;
+ (void)_expungeLibraryScopes:ignorePhotosctlExpungeOverride:;
@end
