@interface PKDaemonClient : NSObject
@property (nonatomic) NSObject<OS_xpc_object> pkd;
@property (nonatomic) NSObject<OS_dispatch_queue> replyQueue;
@property (nonatomic) q protocolVersion;
- (long long)protocolVersion;
- (void)setProtocolVersion:;
- (void)findPlugInByUUID:reply:;
- (void)accessPlugIns:synchronously:flags:reply:;
- (void)copyReceipt:;
- (void)set:plugins:;
- (id)request:;
- (void)matchPlugIns:flags:uuid:reply:;
- (void)sendSynchronously:request:retry:reply:;
- (id)errorInReply:;
- (void)set:uuids:;
- (void)releaseHold:flags:reply:;
- (void)addPlugIns:reply:;
- (void)setPkd:;
- (void)bulkSetPluginAnnotations:reply:;
- (void)setPluginAnnotations:annotations:reply:;
- (void)readyPlugIns:synchronously:flags:environment:languages:persona:sandbox:reply:;
- (void)holdPlugins:extensionPointName:platforms:flags:reply:;
- (void)setReplyQueue:;
- (void)bulkPlugins:reply:;
- (void).cxx_destruct;
- (id)initWithConnection:queue:user:;
- (id)initWithServiceName:user:;
- (id)convertFromXPC:;
- (id)rawConnection;
- (void)findPlugInByPathURL:reply:;
- (id)initWithServiceName:;
- (id)replyQueue;
- (void)removePlugIns:reply:;
- (id)request:paths:;
- (id)pkd;
- (void)sendSynchronously:request:reply:;
- (void)send:reply:;
+ (id)convertToXPC:version:;
@end
