@interface PLGenericAlbum : _PLGenericAlbum
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) NSDate searchableStartDate;
@property (nonatomic) NSDate searchableEndDate;
@property (nonatomic) Q assetsCountPrivate;
@property (nonatomic) Q assetsCountShared;
@property (nonatomic) NSString keyAssetUUIDPrivate;
@property (nonatomic) NSDate keyAssetCreationDatePrivate;
@property (nonatomic) NSString keyAssetUUIDShared;
@property (nonatomic) NSDate keyAssetCreationDateShared;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) @ localID;
@property (nonatomic) s cloudLocalState;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) PLPhotoLibrary photoLibrary;
@property (nonatomic) s trashedState;
@property (nonatomic) NSDate trashedDate;
@property (nonatomic) NSDate startDate;
@property (nonatomic) NSDate endDate;
@property (nonatomic) NSDate creationDate;
@property (nonatomic) NSString uuid;
@property (nonatomic) NSInteger kindValue;
@property (nonatomic) NSString title;
@property (nonatomic) NSString cloudGUID;
@property (nonatomic) NSString importedByBundleIdentifier;
@property (nonatomic) BOOL isPinned;
@property (nonatomic) BOOL isPrototype;
@property (nonatomic) s privacyState;
@property (nonatomic) s cloudLocalState;
@property (nonatomic) s cloudDeleteState;
@property (nonatomic) NSData userQueryData;
@property (nonatomic) BOOL isLibrary;
@property (nonatomic) BOOL isCameraAlbum;
@property (nonatomic) BOOL isSmartAlbum;
@property (nonatomic) BOOL isUserCreated;
@property (nonatomic) BOOL isOwnPhotoStreamAlbum;
@property (nonatomic) BOOL isProjectAlbumRootFolder;
@property (nonatomic) BOOL isRegularRootFolder;
@property (nonatomic) BOOL isRecentlyAddedAlbum;
@property (nonatomic) BOOL isUserLibraryAlbum;
@property (nonatomic) BOOL isProjectAlbum;
@property (nonatomic) BOOL isDuplicateAlbum;
@property (nonatomic) BOOL shouldDeleteWhenEmpty;
@property (nonatomic) BOOL isRegisteredForChanges;
@property (nonatomic) BOOL didRegisteredWithUserInterfaceContext;
@property (nonatomic) NSMutableOrderedSet mutableAssets;
@property (nonatomic) NSNumber kind;
@property (nonatomic) BOOL hasUnseenContentBoolValue;
@property (nonatomic) NSString name;
@property (nonatomic) NSObject posterImage;
@property (nonatomic) BOOL isPanoramasAlbum;
@property (nonatomic) BOOL isPhotoStreamAlbum;
@property (nonatomic) BOOL isCloudSharedAlbum;
@property (nonatomic) BOOL isPendingPhotoStreamAlbum;
@property (nonatomic) BOOL isStandInAlbum;
@property (nonatomic) BOOL isFolder;
@property (nonatomic) BOOL isInTrash;
@property (nonatomic) BOOL isOwnedCloudSharedAlbum;
@property (nonatomic) BOOL isFamilyCloudSharedAlbum;
@property (nonatomic) BOOL isMultipleContributorCloudSharedAlbum;
@property (nonatomic) BOOL canContributeToCloudSharedAlbum;
@property (nonatomic) NSString importSessionID;
@property (nonatomic) NSURL groupURL;
@property (nonatomic) @? sortingComparator;
@property (nonatomic) NSInteger pendingItemsCount;
@property (nonatomic) NSInteger pendingItemsType;
@property (nonatomic) Q batchSize;
@property (nonatomic) NSString localizedTitle;
@property (nonatomic) NSOrderedSet assets;
@property (nonatomic) Q approximateCount;
@property (nonatomic) Q assetsCount;
@property (nonatomic) Q photosCount;
@property (nonatomic) Q videosCount;
@property (nonatomic) BOOL isEmpty;
@property (nonatomic) PLManagedAsset keyAsset;
@property (nonatomic) PLManagedAsset secondaryKeyAsset;
@property (nonatomic) PLManagedAsset tertiaryKeyAsset;
@property (nonatomic) BOOL canShowComments;
@property (nonatomic) BOOL canShowAvalancheStacks;
@property (nonatomic) NSArray localizedLocationNames;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)awakeFromFetch;
- (id)photoLibrary;
- (id)payloadID;
- (unsigned long long)videosCount;
- (BOOL)isRegisteredForChanges;
- (id)childKeyForOrdering;
- (void)delete;
- (void)setIsRegisteredForChanges:;
- (BOOL)isSyncableChange;
- (BOOL)_isGoldilocksEnabled;
- (id)payloadIDForTombstone:;
- (void)willTurnIntoFault;
- (unsigned long long)assetsCountPrivate;
- (BOOL)isEmpty;
- (unsigned long long)assetsCountShared;
- (void)didSave;
- (unsigned long long)photosCount;
- (void)dealloc;
- (void)willSave;
- (BOOL)hasUnseenContentBoolValue;
- (void)registerForChanges;
- (id)payloadForChangedKeys:;
- (BOOL)canPerformEditOperation:;
- (void)awakeFromInsert;
- (void)unregisterForChanges;
- (void)_appendLibraryScopeToCollection:;
- (BOOL)shouldDeleteWhenEmpty;
- (id)posterImage;
- (unsigned long long)approximateCount;
- (id)cplFullRecord;
- (BOOL)isFolder;
- (BOOL)isCloudSharedAlbum;
- (BOOL)didRegisteredWithUserInterfaceContext;
- (unsigned long long)assetsCount;
- (BOOL)supportsCloudUpload;
- (BOOL)isEligibleForSearchIndexing;
- (void)setHasUnseenContentBoolValue:;
- (void)unregisterAllDerivedAlbums;
- (void)enumerateDerivedIndexMappers:;
- (void).cxx_destruct;
- (BOOL)hasDerivedIndexMappers;
- (id)localizedTitle;
- (BOOL)isFamilyCloudSharedAlbum;
- (BOOL)canContributeToCloudSharedAlbum;
- (unsigned long long)countForAssetsOfKind:;
- (id)description;
- (BOOL)isOwnedCloudSharedAlbum;
- (id)subtitle;
- (id)_prettyDescription;
- (BOOL)isMultipleContributorCloudSharedAlbum;
- (id)name;
- (id)sortingComparator;
- (void)setDidRegisteredWithUserInterfaceContext:;
- (unsigned long long)count;
- (id)localID;
- (id)groupURL;
- (BOOL)isUserCreated;
- (id)localizedLocationNames;
- (BOOL)isSmartAlbum;
- (void)setUserQueryData:;
- (BOOL)isInTrash;
- (BOOL)canShowAvalancheStacks;
- (BOOL)canShowComments;
- (BOOL)isPendingPhotoStreamAlbum;
- (BOOL)isLibrary;
- (void)reducePendingItemsCountBy:;
- (void)batchFetchAssets:;
- (int)kindValue;
- (BOOL)isCameraAlbum;
- (BOOL)isPanoramasAlbum;
- (BOOL)isPhotoStreamAlbum;
- (BOOL)isStandInAlbum;
- (BOOL)isRecentlyAddedAlbum;
- (BOOL)isUserLibraryAlbum;
- (BOOL)isProjectAlbum;
- (id)keyAssetUUIDPrivate;
- (id)keyAssetUUIDShared;
- (BOOL)canMoveToTrash;
- (BOOL)validForPersistenceChangedForChangedKeys:;
- (id)keyAssetUUID;
- (id)_kindDescription;
- (id)_compactDebugDescription;
- (void)registerDerivedAlbum:;
- (void)enumerateDerivedAlbums:;
- (id)childManagedObject;
- (void)_applyTrashedState:date::cascade:;
- (void)applyTrashedState:cascade:;
- (void)repairUuidAndTitleWithRecoveryReason:;
- (void)_repairTitleIfEmpty;
- (void)setKindValue:;
- (BOOL)isOwnPhotoStreamAlbum;
- (BOOL)isDuplicateAlbum;
- (BOOL)isProjectAlbumRootFolder;
- (BOOL)isRegularRootFolder;
- (id)assetsByObjectIDAtIndexes:;
- (void)updateAlbumFolderRelation:inLibrary:;
- (id)searchableStartDate;
- (id)searchableEndDate;
- (id)_searchableExtremityDateFromStart:;
- (id)keyAssetCreationDate;
- (id)keyAssetCreationDatePrivate;
- (id)keyAssetCreationDateShared;
- (id)searchIndexContents;
- (void)addSearchIndexContentsToCollection:;
- (id)_scopedIdentifier;
- (id)cplAlbumChangeInPhotoLibrary:;
- (void)applyPropertiesFromAlbumChange:;
- (BOOL)isProjectAlbumSupportingCloudUpload;
+ (id)childKeyForOrdering;
+ (void)addSingletonObjectsToContext:;
+ (id)localizedRecoveredTitle;
+ (id)baseSearchIndexPredicate;
+ (id)isEligibleForSearchIndexingPredicate;
+ (id)localizedTitleForAlbumKind:cplEnabled:;
+ (id)uuidFromGroupURL:;
+ (id)defaultAlbumKindsForFetchingWithCPLEnabled:;
+ (id)albumWithObjectID:inLibrary:;
+ (id)insertNewAlbumIntoLibrary:;
+ (id)insertNewCloudSharedAlbumWithTitle:lastInterestingDate:intoLibrary:;
+ (id)insertNewSmartAlbumIntoLibrary:;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingKindValue;
+ (BOOL)isSmartAlbumForKind:;
+ (BOOL)isUserCreatedForKind:;
+ (BOOL)isFolder:;
+ (id)_singletonFetchingAlbumWithKind:library:;
+ (id)_singletonManagedAlbumWithKind:library:;
+ (id)rootFolderInLibrary:;
+ (id)projectAlbumRootFolderInLibrary:;
+ (id)userLibraryAlbumInLibrary:;
+ (id)allAssetsAlbumInLibrary:;
+ (id)allPanoramasAlbumInLibrary:;
+ (id)allVerticalPanoramasAlbumInLibrary:;
+ (id)allHorizontalPanoramasAlbumInLibrary:;
+ (id)allVideosAlbumInLibrary:;
+ (id)allFavoritesAlbumInLibrary:;
+ (id)allPhotoStreamAssetsAlbumInLibrary:;
+ (id)iTunesLibraryAlbumInLibrary:;
+ (id)trashBinAlbumInLibrary:;
+ (id)unableToUploadAlbumInLibrary:;
+ (id)syncProgressAlbumInLibrary:;
+ (id)otaRestoreProgressAlbumInLibrary:;
+ (id)filesystemImportProgressAlbumInLibrary:;
+ (id)allAlbumsInLibrary:;
+ (id)albumWithUUID:inLibrary:;
+ (id)albumWithName:inLibrary:;
+ (id)albumsForStreamID:inLibrary:;
+ (id)_unpushedParentsOfAlbums:;
+ (id)includeUnpushedParentsForAlbums:limit:;
+ (id)albumsToUploadInitiallyInLibrary:limit:;
+ (void)resetAlbumStateForCloudInLibrary:;
+ (void)_removeAlbumsAndFolders:inManagedObjectContext:;
+ (void)removeAllUserAlbumsAndFoldersInLibrary:;
+ (void)removeEmptyAlbumsAndFoldersForCloudResetInManagedObjectContext:;
+ (void)removeTrashedAlbumsAndFoldersForCloudResetInManagedObjectContext:;
+ (void)removeInvalidAlbumsAndFoldersInManagedObjectContext:;
+ (id)albumsMatchingPredicate:expectedResultCount:inLibrary:;
+ (id)_insertNewAlbumWithKind:title:lastInterestingDate:intoLibrary:;
+ (id)insertNewAlbumWithKind:title:intoLibrary:;
+ (id)insertNewAlbumWithTitle:intoLibrary:;
+ (id)insertNewProjectAlbumWithTitle:documentType:intoLibrary:;
+ (id)insertNewSyncedEventWithTitle:intoLibrary:;
+ (id)insertNewSyncedEventIntoLibrary:;
+ (id)insertNewLegacyFaceAlbumIntoLibrary:;
+ (id)albumFromGroupURL:photoLibrary:;
+ (id)allAlbumsInManagedObjectContext:;
+ (id)allSyncedAlbumsInManagedObjectContext:;
+ (id)allAlbumsRegisteredWithManagedObjectContext:;
+ (id)albumsWithKind:inManagedObjectContext:;
+ (id)eventsWithName:andImportSessionIdentifier:inManagedObjectContext:;
+ (id)insertAlbumWithKind:title:uuid:inManagedObjectContext:;
+ (id)albumWithKind:inManagedObjectContext:;
+ (id)_albumsMatchingPredicate:expectedResultCount:inManagedObjectContext:;
+ (BOOL)is1WaySyncKind:;
+ (id)searchIndexAllowedPredicate;
+ (id)_predicateForSupportedAlbumTypes;
+ (id)albumWithCloudGUID:inLibrary:;
+ (id)albumsWithCloudGUIDs:inLibrary:;
+ (id)needsSearchIndexingForRebuildPredicate:;
@end
