@interface PLPhotoLibraryBundle : NSObject
@property (nonatomic) NSURL libraryURL;
@property (nonatomic) BOOL isShuttingDown;
@property (nonatomic) NSError shutdownReason;
@property (nonatomic) PLPhotoLibraryPathManager pathManager;
@property (nonatomic) PLIndicatorFileCoordinator indicatorFileCoordinator;
@property (nonatomic) PLPersistentContainer persistentContainer;
@property (nonatomic) q connectionType;
@property (nonatomic) PLChangeHandlingContainer changeHandlingContainer;
@property (nonatomic) PLPhotoKitVariationCache variationCache;
@property (nonatomic) PLPersonInfoManager personInfoManager;
@property (nonatomic) PLEmailAddressManager emailAddressManager;
@property (nonatomic) PLPhotoLibraryBundleController bundleController;
@property (nonatomic) PLPhotoAnalysisServiceClient photoAnalysisServiceClient;
@property (nonatomic) PLConstraintsDirector constraintsDirector;
@property (nonatomic) PFTimeZoneLookup timeZoneLookup;
@property (nonatomic) PLClientSandboxExtensionCache clientSandboxExtensionCache;
@property (nonatomic) PLAssetsdClient assetsdClient;
@property (nonatomic) PLLibraryServicesManager libraryServicesManager;
@property (nonatomic) NSArray boundAssetsdServices;
- (id)libraryServicesManager;
- (long long)connectionType;
- (id)pathManager;
- (id)assetsdClient;
- (id)libraryURL;
- (id)indicatorFileCoordinator;
- (void)setCloudPhotoLibraryEnabled:;
- (void)dealloc;
- (void)_invalidateClientSandboxExtensionCache;
- (void)distributeChangesSinceLastCheckpoint;
- (void)touch;
- (id)personInfoManager;
- (id)transferPersons:toBundle:options:completion:;
- (id)photoAnalysisServiceClient;
- (id)newChangePublisher;
- (id)boundAssetsdServicesTable;
- (void)close;
- (BOOL)bindAssetsdService:error:;
- (id)timeZoneLookup;
- (void)beginObservingChanges;
- (void)volumeWillUnmount:;
- (id)shutdownReason;
- (BOOL)sqliteErrorIndicatorFileExists;
- (id)persistentContainer;
- (void)_invalidatePhotoAnalysisServiceClient;
- (id)bundleController;
- (void)unbindAssetsdService:;
- (void)endObservingChanges;
- (id)variationCache;
- (id)clientSandboxExtensionCache;
- (id)transferAssets:toBundle:options:completion:;
- (void)setPhotoStreamEnabled:;
- (id)changeHandlingContainer;
- (BOOL)isSystemPhotoLibrary;
- (id)boundAssetsdServices;
- (void)initializeChangeHandling;
- (void).cxx_destruct;
- (id)newAssetsdClient;
- (id)description;
- (BOOL)registerPLPhotoLibrary:;
- (void)_invalidateChangeHandlingContainer;
- (void)setSharedAlbumEnabled:;
- (id)newLibraryServicesManager;
- (id)initWithLibraryURL:bundleController:;
- (id)makeChangeHandlingNotificationObserverWithLowPriorityThrottleInterval:;
- (BOOL)isShuttingDown;
- (id)constraintsDirector;
- (id)emailAddressManager;
- (void)_invalidatePersistentContainer;
- (void)shutdownWithReason:;
- (void)resetClientSandboxExtensionCache;
- (id)newBoundAssetsdServicesTable;
- (id)newChangeHandlingContainer;
@end
