@interface PQLResultSet : NSObject
@property (nonatomic) NSError error;
@property (nonatomic) Q rowNumber;
@property (nonatomic) Q columns;
@property (nonatomic) PQLConnection db;
@property (nonatomic) ^{sqlite3_stmt=} stmt;
@property (nonatomic) NSSet defaultUnarchivingAllowedClasses;
- (unsigned long long)columns;
- (BOOL)next;
- (id)db;
- (id)nextObject;
- (void)dealloc;
- (int)intAtIndex:;
- (unsigned long long)countByEnumeratingWithState:objects:count:;
- (id)objectAtIndexedSubscript:;
- (id)error;
- (void)close;
- (id)dataAtIndex:;
- (id)stmt;
- (id)stringAtIndex:;
- (id)columnNameAtIndex:;
- (BOOL)boolAtIndex:;
- (id)objectAtIndex:;
- (void).cxx_destruct;
- (double)doubleAtIndex:;
- (id)description;
- (long long)integerAtIndex:;
- (unsigned long long)rowNumber;
- (id)numberAtIndex:;
- (BOOL)_next:;
- (unsigned long long)unsignedIntegerAtIndex:;
- (unsigned long long)unsignedLongLongAtIndex:;
- (id)enumerateObjectsOfClass:;
- (id)dateAtIndex:;
- (id)object:;
- (id)enumerateObjects:;
- (id)objectOfClass:;
- (float)floatAtIndex:;
- (id)unarchivedObjectOfClass:atIndex:;
- (id)unarchivedObjectOfClasses:atIndex:;
- (unsigned int)unsignedIntAtIndex:;
- (unsigned long long)unsignedLongAtIndex:;
- (id)objectOfClass:atIndex:;
- (char)charAtIndex:;
- (long long)longAtIndex:;
- (long long)longLongAtIndex:;
- (id)uuidAtIndex:;
- (id)initWithStatement:usingDatabase:;
- (id)onlyObjectOfClass:initializer:;
- (id)onlyObjectOfClass:;
- (id)onlyObject:;
- (id)objectOfClass:initializer:;
- (unsigned char)unsignedCharAtIndex:;
- (short)shortAtIndex:;
- (unsigned short)unsignedShortAtIndex:;
- (id)UTF8StringAtIndex:;
- (BOOL)isNullAtIndex:;
- (id)dataAtIndex:noCopy:;
- (id)plistAtIndex:;
- (id)defaultUnarchivingAllowedClasses;
- (id)archivedObjectOfClass:atIndex:;
- (id)archivedObjectOfClasses:atIndex:;
- (id)enumerateObjectsOfClass:initializer:;
- (void)setDefaultUnarchivingAllowedClasses:;
@end
