@interface PSESchemaPSEClientEvent : SISchemaTopLevelUnionType
@property (nonatomic) SISchemaInstrumentationMessage innerEvent;
@property (nonatomic) PSESchemaPSEClientEventMetadata eventMetadata;
@property (nonatomic) BOOL hasEventMetadata;
@property (nonatomic) PSESchemaPSEGenericSignalGenerated genericSignalGenerated;
@property (nonatomic) BOOL hasGenericSignalGenerated;
@property (nonatomic) PSESchemaPSECallSignalGenerated callSignalGenerated;
@property (nonatomic) BOOL hasCallSignalGenerated;
@property (nonatomic) NSData jsonData;
@property (nonatomic) Q whichEvent_Type;
- (int)componentName;
- (id)qualifiedMessageName;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (int)getAnyEventType;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (unsigned long long)whichEvent_Type;
- (id)eventMetadata;
- (void)setEventMetadata:;
- (BOOL)hasEventMetadata;
- (int)clockIsolationLevel;
- (id)innerEvent;
- (id)getComponentId;
- (void)deleteEventMetadata;
- (void)setHasEventMetadata:;
- (void)setGenericSignalGenerated:;
- (id)genericSignalGenerated;
- (void)deleteGenericSignalGenerated;
- (void)setCallSignalGenerated:;
- (id)callSignalGenerated;
- (void)deleteCallSignalGenerated;
- (BOOL)hasGenericSignalGenerated;
- (void)setHasGenericSignalGenerated:;
- (BOOL)hasCallSignalGenerated;
- (void)setHasCallSignalGenerated:;
+ (int)joinability;
@end
