@interface PSSearchModel : NSObject
@property (nonatomic) NSString currentQuery;
@property (nonatomic) PSSearchOperation activeSearchOperation;
@property (nonatomic) BOOL showSectionInDetailText;
@property (nonatomic) NSArray rootEntries;
@property (nonatomic) <PSSearchModelDataSource> dataSource;
@property (nonatomic) PSSearchResults currentResults;
@property (nonatomic) BOOL loadingResults;
@property (nonatomic) BOOL indexing;
@property (nonatomic) BOOL hasCompletedIndexing;
@property (nonatomic) BOOL waitUntilFinished;
@property (nonatomic) q observerType;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)addDelegate:;
- (void)setDataSource:;
- (id)init;
- (void)dealloc;
- (id)recursiveDescription;
- (void)removeDelegate:;
- (id)currentQuery;
- (void)preheat;
- (BOOL)waitUntilFinished;
- (BOOL)isIndexing;
- (id)dataSource;
- (void).cxx_destruct;
- (void)setCurrentQuery:;
- (id)currentResults;
- (void)dataSource:performUpdates:;
- (void)invalidateSpecifiersForDataSource:;
- (long long)observerType;
- (void)searchIndexOperation:didFindSpecifierDataSource:;
- (void)searchIndexOperationDidFinish:searchEntries:;
- (void)searchIndexOperationDidCancel:;
- (void)searchOperationDidBegin:;
- (id)searchOperation:filteredEntriesForEntries:;
- (void)searchOperation:configureSearchResults:;
- (void)searchOperationDidFinish:withResults:;
- (void)searchOperationDidCancel:;
- (id)_rootSpecifiers;
- (void)_enumerateDelegatesUsingBlock:;
- (id)_searchEntriesForSpecifierDataSource:;
- (void)_addSpecifierDataSource:forSearchEntry:;
- (void)addRootSpecifier:;
- (void)reloadRootSpecifier:;
- (void)removeRootSpecifier:;
- (void)_addSearchEntries:parent:usingBlock:;
- (void)_removeSearchEntries:usingBlock:;
- (void)_removeSearchEntries:usingBlock:forReload:;
- (void)_reloadSearchEntries:;
- (void)_performDeferredUpdatesForEntry:;
- (BOOL)hasCompletedIndexing;
- (void)_beginIndexingIfNecessary;
- (void)_loadChildrenForEntry:;
- (void)_updatedEntry:withChildren:;
- (void)_finishedIndexingEntry:;
- (BOOL)isLoadingResults;
- (void)searchForQuery:;
- (id)_defaultSearchResultsSectionComparator;
- (void)_cancelAllSearchOperations;
- (void)_beginSearchingEntriesForCurrentQuery:newSearch:;
- (void)_updateWithNewSearchResults:forQuery:newSearch:;
- (void)_performSpecifierUpdates:forSearchEntries:;
- (void)setWaitUntilFinished:;
- (id)activeSearchOperation;
- (void)setActiveSearchOperation:;
- (BOOL)showSectionInDetailText;
- (void)setShowSectionInDetailText:;
- (id)rootEntries;
+ (id)sharedInstance;
@end
