@interface PSSoftwareUpdateTitleCell : PSTableCell
@property (nonatomic) NSLayoutConstraint updateStatusLabelVerticalConstraint;
@property (nonatomic) UIImage gearBackgroundImage;
@property (nonatomic) UIImageView gearBackgroundImageView;
@property (nonatomic) UIProgressView progressBar;
@property (nonatomic) NSInteger progressDisplayStyle;
@property (nonatomic) UILabel updateStatusLabel;
@property (nonatomic) PSWebContainerView releaseNotesSummaryView;
- (void)layoutSubviews;
- (void)animationDidStop:finished:;
- (void)setProgress:;
- (id)initWithStyle:reuseIdentifier:specifier:;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)setupViews;
- (void)configureImageView;
- (id)progressBar;
- (void)setStatusMessage:;
- (double)preferredHeightWithTable:;
- (void)configureAnimatedGearViewFromImageSize:;
- (void)createGearIconConstraints;
- (void)configureUpdateNameLabel:;
- (void)configurePublisherLabel:;
- (void)configureUpdateStatusLabel:;
- (void)configureReleaseNotesSummaryView:;
- (void)configureProgressBar:;
- (void)updateProgressTintColor;
- (void)setProgressDisplayStyle:;
- (int)progressDisplayStyle;
- (id)newSoftwareUpdateAnimatedIconWithFrame:;
- (void)setReleaseNotesSummary:;
- (void)setUpdateName:;
- (void)setPublisherText:;
- (void)setAnimatingGearView:;
- (id)gearBackgroundImage;
- (id)newGearBackgroundImageView;
- (id)newProgressBar;
- (id)newUpdateStatusLabel;
- (id)gearBackgroundImageView;
- (void)setGearBackgroundImageView:;
- (id)updateStatusLabel;
- (id)releaseNotesSummaryView;
- (id)updateStatusLabelVerticalConstraint;
- (void)setUpdateStatusLabelVerticalConstraint:;
+ (long long)cellStyle;
@end
