@interface PuzzleHybridViewController : UIViewController
@property (nonatomic) UIButton backBtn;
@property (nonatomic) UIButton shareBtn;
@property (nonatomic) UIButton closeBtn;
@property (nonatomic) PuzzleSecureBannerView secureBanner;
@property (nonatomic) BOOL showingKeyboard;
@property (nonatomic) BOOL originNaviBarHidden;
@property (nonatomic) BOOL originNaviBarIsHidden;
@property (nonatomic) double topPadding;
@property (nonatomic) double containerViewWidth;
@property (nonatomic) @ keyboardShowObserver;
@property (nonatomic) @ keyboardHideObserver;
@property (nonatomic) PuzzleContext context;
@property (nonatomic) NSString titleString;
@property (nonatomic) BOOL isPageHadShown;
@property (nonatomic) BOOL disableNativeClose;
@property (nonatomic) BOOL triggerBackByBackBtn;
@property (nonatomic) NSDictionary shareInfo;
@property (nonatomic) UIScreenEdgePanGestureRecognizer screenEdgeBackGesture;
@property (nonatomic) {CGPoint=dd} panStartPoint;
@property (nonatomic) BOOL appearFirstTime;
@property (nonatomic) BOOL appearZeroTimes;
@property (nonatomic) BOOL isHybridViewDidLoad;
@property (nonatomic) UIButton errorPageBackBtn;
@property (nonatomic) PuzzleHybridContainer hybridContainer;
@property (nonatomic) UIView statusBarBackgroundView;
@property (nonatomic) q statusBarStyle;
@property (nonatomic) BOOL hideStatusBar;
@property (nonatomic) UIColor originStatusBarBackgroundColor;
@property (nonatomic) q originStatusBarStyle;
@property (nonatomic) UIView<PuzzleNavigationBarProtocol> navigationBar;
@property (nonatomic) BOOL originNavigationBarHidden;
@property (nonatomic) BOOL originNavigationBarIsHidden;
@property (nonatomic) BOOL originControllerPopGestureRecongnizerEnabled;
@property (nonatomic) @ cachedPopGestureRecognizerDelegate;
@property (nonatomic) PuzzleFullScreenControllerUIConfig config;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView<IESHYHybridViewProtocol> kitView;
@property (nonatomic) <IESHYControllerDelegate> delegate;
- (void)__setupShareBtn;
- (BOOL)appearFirstTime;
- (id)backBtn;
- (void)viewDidLoadFailedWithUrl:error:;
- (void)__setupCloseBtn;
- (BOOL)appearZeroTimes;
- (void)dismissWithAnimated:completion:;
- (id)hybridContainer;
- (id)kitView;
- (void)removeSecBanner;
- (void)setOriginNavigationBarIsHidden:;
- (void)updateStatusBarBackgroundColor:;
- (void)viewDidCreated:;
- (void)__addScreenEdgeBackGesture;
- (void)__configUIAppearance;
- (void)__registerJSB;
- (void)__resetStatusBarStyle;
- (void)__setupBackBtn;
- (id)__setupContext;
- (void)__setupHybridContainer;
- (void)__setupNavigationView;
- (void)_doPopActionWithAnimated:completion:;
- (void)addKeyboardObserver;
- (void)addScreenshotObserver;
- (void)cachePopGestureRecognizer;
- (id)cachedPopGestureRecognizerDelegate;
- (void)calculateContainerWidth;
- (void)cancelLoadingAnimation;
- (void)clickBackBtn;
- (void)clickCloseBtn;
- (void)clickShareBtn;
- (id)closeBtn;
- (void)closeHybridWithCompletion:;
- (void)closeLastContainerIfNeeded:;
- (void)closeViewIfNeeded;
- (id)commonTrackerParam;
- (double)containerViewWidth;
- (BOOL)disableNativeClose;
- (void)dismissKeyboard:;
- (void)dismissWithAnimated:animator:closeType:completion:;
- (void)dismissWithAnimated:animator:completion:;
- (BOOL)enableResetNaviBarHidden;
- (id)errorPageBackBtn;
- (BOOL)fixSystemPopTransitionEnable;
- (void)handlePageVisiablityChange:source:;
- (void)handleScreenEdgePan:;
- (void)hideFloatLiveWindow;
- (id)hmdPageExtension;
- (id)initWithConfig:context:delegate:;
- (void)injectShareInfo:;
- (BOOL)interceptCloseAndSendEventWithType:;
- (BOOL)isHybridViewDidLoad;
- (BOOL)isInLightAdapterAllowList;
- (BOOL)isPadAdaptionMode;
- (BOOL)isPageHadShown;
- (id)keyboardHideObserver;
- (id)keyboardShowObserver;
- (BOOL)originControllerPopGestureRecongnizerEnabled;
- (BOOL)originNaviBarHidden;
- (BOOL)originNaviBarIsHidden;
- (BOOL)originNavigationBarHidden;
- (BOOL)originNavigationBarIsHidden;
- (id)originStatusBarBackgroundColor;
- (long long)originStatusBarStyle;
- (void)p_BtnActionWithBtnType:;
- (void)p_showTracker;
- (id)panStartPoint;
- (void)resumePopGestureRecognizer;
- (id)screenEdgeBackGesture;
- (id)secureBanner;
- (void)sendScreenshotEvent;
- (void)setAppearFirstTime:;
- (void)setAppearZeroTimes:;
- (void)setBackBtn:;
- (void)setCachedPopGestureRecognizerDelegate:;
- (void)setCloseBtn:;
- (void)setContainerViewWidth:;
- (void)setDisableNativeClose:;
- (void)setErrorPageBackBtn:;
- (void)setHybridContainer:;
- (void)setIsHybridViewDidLoad:;
- (void)setIsPageHadShown:;
- (void)setKeyboardHideObserver:;
- (void)setKeyboardShowObserver:;
- (void)setNavigationRightButtonType:;
- (void)setNavigationSwipeBackEnable:;
- (void)setOriginControllerPopGestureRecongnizerEnabled:;
- (void)setOriginNaviBarHidden:;
- (void)setOriginNaviBarIsHidden:;
- (void)setOriginNavigationBarHidden:;
- (void)setOriginStatusBarBackgroundColor:;
- (void)setOriginStatusBarStyle:;
- (void)setPanStartPoint:;
- (void)setScreenEdgeBackGesture:;
- (void)setSecureBanner:;
- (void)setShareBtn:;
- (void)setStatusBarBackgroundColor:;
- (void)setTopLevelEnable:;
- (void)setTriggerBackByBackBtn:;
- (void)setWebViewBounceEnable:;
- (void)setupNavigationPopGestureRecognizerEnable:;
- (id)shareBtn;
- (void)showFloatLiveWindow;
- (void)showSecBanner:;
- (void)showWithAnimated:animator:completion:;
- (long long)statusBarStyleForNormalMode;
- (long long)targetUIMode;
- (double)topBtnMargin;
- (id)topLevelEnable;
- (BOOL)triggerBackByBackBtn;
- (void)updateAutoShowNavBarButtonAlpha:;
- (void)updateHybridViewLayout;
- (void)updateNavigationBarColor:;
- (void)updateStatusBarStyle:;
- (void)updateSystemPopTransitionEnable:fullscreenPopTransitionEnable:;
- (void)updateTitleColor:;
- (void)viewDidBackForward;
- (void)viewDidFinishLoadWithURL:;
- (void)viewDidReceiveSecureRisk:;
- (void)viewDidStartLoading;
- (double)topPadding;
- (BOOL)shouldAutorotate;
- (void)setNavigationBar:;
- (long long)preferredStatusBarStyle;
- (void)dealloc;
- (long long)statusBarStyle;
- (id)context;
- (void)goBack;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (BOOL)prefersStatusBarHidden;
- (void)setConfig:;
- (void)setDelegate:;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (id)navigationBar;
- (void)addChildViewController:;
- (void)setStatusBarBackgroundView:;
- (void)setStatusBarHidden:;
- (id)statusBarBackgroundView;
- (void)viewWillDisappear:;
- (id)shareInfo;
- (BOOL)showingKeyboard;
- (void)setShowingKeyboard:;
- (id)delegate;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)viewWillAppear:;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)setShareInfo:;
- (id)config;
- (void)setStatusBarStyle:;
- (unsigned long long)supportedInterfaceOrientations;
- (void)setContext:;
- (void)viewDidLoad;
- (id)titleString;
- (void)setTitleString:;
- (BOOL)hideStatusBar;
- (void)setTopPadding:;
- (void)setHideStatusBar:;
- (void)updateTitle:;
@end
