@interface PuzzleHybridPopupController : UIViewController
@property (nonatomic) IESLiveSaaSPuzzleOrientationHandler orientationHandler;
@property (nonatomic) PuzzleContext context;
@property (nonatomic) UIView statusBarBackgroundView;
@property (nonatomic) MASConstraint hybridViewBottomOffset;
@property (nonatomic) BOOL tapMaskToClose;
@property (nonatomic) UIView containerView;
@property (nonatomic) double animationDuration;
@property (nonatomic) UIView closeIndicator;
@property (nonatomic) UIButton backBtn;
@property (nonatomic) UIButton closeBtn;
@property (nonatomic) BOOL triggerBackByBackBtn;
@property (nonatomic) BOOL showingKeyboard;
@property (nonatomic) BOOL disableNativeClose;
@property (nonatomic) {CGPoint=dd} lastLocation;
@property (nonatomic) {CGPoint=dd} originLocation;
@property (nonatomic) BOOL triggerPullDownClose;
@property (nonatomic) UIPanGestureRecognizer pullDownCloseGesture;
@property (nonatomic) double containerViewHeight;
@property (nonatomic) double containerViewWidth;
@property (nonatomic) double appearTime;
@property (nonatomic) UIPanGestureRecognizer halfToFullScreenGesture;
@property (nonatomic) double halfToFullScreenOriginalY;
@property (nonatomic) Q halfScreenState;
@property (nonatomic) UIView halfScreenContainerView;
@property (nonatomic) UIButton halfScreenCloseButon;
@property (nonatomic) UIView<PuzzleNavigationBarProtocol> navigationBar;
@property (nonatomic) BOOL enableFull;
@property (nonatomic) BOOL enableHalf;
@property (nonatomic) @ keyboardShowObserver;
@property (nonatomic) @ keyboardHideObserver;
@property (nonatomic) NSDictionary shareInfo;
@property (nonatomic) UIButton shareBtn;
@property (nonatomic) NSMutableArray wkObserverKeys;
@property (nonatomic) BOOL webShouldUseKVO;
@property (nonatomic) BOOL keyboardNotiShouldUseFrame;
@property (nonatomic) BOOL appearFirstTime;
@property (nonatomic) PuzzleHybridContainer hybridView;
@property (nonatomic) PuzzlePopupControllerUIConfig popupConfig;
@property (nonatomic) UIView maskBgView;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) UIView<IESHYHybridViewProtocol> kitView;
@property (nonatomic) <IESHYControllerDelegate> delegate;
- (BOOL)appearFirstTime;
- (id)backBtn;
- (double)hybridViewRightConstraintOffset;
- (void)setPopupConfig:;
- (void)viewDidLoadFailedWithUrl:error:;
- (void)closeBtnClicked;
- (void)dismissWithAnimated:completion:;
- (unsigned long long)halfScreenState;
- (id)kitView;
- (void)shareBtnClicked;
- (void)viewDidCreated:;
- (BOOL)webShouldUseKVO;
- (void)UIInit;
- (void)addBottomUI;
- (void)addCenterUI;
- (void)addCloseIndicator;
- (void)addContainerView;
- (void)addHalfToFullScreenPanGesture;
- (void)addHybirdView;
- (void)addHybirdViewCorners;
- (void)addInteractivePopGesture;
- (void)addKeyboardObserver;
- (void)addMaskView;
- (void)addNavigationBarShareButton;
- (void)addPullDownCloseGesture;
- (void)addScreenshotObserver;
- (void)addShareButton;
- (void)addStatusBarContainerView;
- (void)addUpNavigationBar;
- (void)addUpToFullScreenCloseBtn;
- (void)addWKObserver;
- (double)appearTime;
- (void)backBtnClicked;
- (void)calculateWidthAndHeight;
- (void)cancelLoadingAnimation;
- (void)changeHalfScreenViewsAlpha:ignoreHalfCloseBtn:;
- (id)closeBtn;
- (void)closeHybridWithCompletion:;
- (id)closeIndicator;
- (void)closeLastContainerIfNeeded:;
- (void)closeViewIfNeeded;
- (id)commonTrackerParam;
- (double)containerViewHeight;
- (double)containerViewWidth;
- (void)dealWithAccessibility;
- (void)didHalfToFullScreenGesture:;
- (void)didPanHotArea:;
- (BOOL)disableNativeClose;
- (void)dismissWithAnimated:animator:closeType:completion:;
- (void)dismissWithAnimated:animator:completion:;
- (BOOL)enableFull;
- (BOOL)enableHalf;
- (void)executePopupAnimationBlockWhenDisappear;
- (void)halfCloseBtnClicked;
- (id)halfScreenCloseButon;
- (id)halfScreenContainerView;
- (id)halfToFullScreenGesture;
- (double)halfToFullScreenOriginalY;
- (BOOL)hasRightOrBottomMargin;
- (void)hideFloatLiveWindow;
- (id)hmdPageExtension;
- (double)homeIndicatorHeight;
- (void)hybirdViewUIConfig;
- (id)hybridView;
- (double)hybridViewBottomConstraintOffset;
- (id)hybridViewBottomOffset;
- (id)initWithConfig:context:delegate:;
- (void)injectShareInfo:;
- (BOOL)interceptCloseAndSendEventWithType:;
- (BOOL)isBottomHalfPopup;
- (BOOL)isBottomPopup;
- (BOOL)isIpadPortraitMode;
- (BOOL)isLightMode;
- (BOOL)isLynxHybrid;
- (id)keyboardHideObserver;
- (BOOL)keyboardNotiShouldUseFrame;
- (id)keyboardShowObserver;
- (id)maskBgView;
- (void)maskTapClose;
- (id)orientationHandler;
- (void)p_BtnActionWithBtnType:;
- (void)p_checkAndPostOpenNextPage;
- (void)p_dismissWithType:completion:;
- (void)p_postWillOpenNextPageNotification;
- (void)p_postWillShowNotificaion:;
- (void)p_showTracker;
- (double)parseHeight;
- (double)parseWidth;
- (id)popupConfig;
- (id)pullDownCloseGesture;
- (void)reLayoutContainerView;
- (void)registerBridge;
- (void)removeWKObserver;
- (void)resetHeight:;
- (void)resetWidth:;
- (void)sendScreenshotEvent;
- (void)setAppearFirstTime:;
- (void)setAppearTime:;
- (void)setBackBtn:;
- (void)setCloseBtn:;
- (void)setCloseByClickMaskEnable:;
- (void)setCloseByGestureEnbale:;
- (void)setCloseIndicator:;
- (void)setContainerLayoutWithSize:cornerRadius:margin:tapMaskToClose:orientation:;
- (void)setContainerViewHeight:;
- (void)setContainerViewWidth:;
- (void)setDisableNativeClose:;
- (void)setEnableFull:;
- (void)setEnableHalf:;
- (void)setEnableToFull:;
- (void)setEnableToHalf:;
- (void)setHalfScreenCloseButon:;
- (void)setHalfScreenContainerView:;
- (void)setHalfScreenState:;
- (void)setHalfToFullScreenGesture:;
- (void)setHalfToFullScreenOriginalY:;
- (void)setHybridView:;
- (void)setHybridViewBottomOffset:;
- (void)setKeyboardHideObserver:;
- (void)setKeyboardNotiShouldUseFrame:;
- (void)setKeyboardShowObserver:;
- (void)setMaskBgView:;
- (void)setOrientationHandler:;
- (void)setOriginLocation:;
- (void)setPullDownCloseGesture:;
- (void)setPullDownHeight:;
- (void)setShareBtn:;
- (void)setSwitchCloseButtonToggle:;
- (void)setTapMaskToClose:;
- (void)setTopLevelEnable:;
- (void)setTriggerBackByBackBtn:;
- (void)setTriggerPullDownClose:;
- (void)setWebShouldUseKVO:;
- (void)setWebViewBounceEnable:;
- (void)setWkObserverKeys:;
- (void)setupGrayIfNeeded;
- (id)shareBtn;
- (BOOL)shouldIgnoreHalfCloseBtnAlpha;
- (BOOL)shouldUseLandscapeSize;
- (void)showFloatLiveWindow;
- (void)showWithAnimated:animator:completion:;
- (BOOL)tapMaskToClose;
- (long long)targetUIMode;
- (id)topLevelEnable;
- (BOOL)triggerBackByBackBtn;
- (BOOL)triggerPullDownClose;
- (double)upStatusBarHeight;
- (void)updateBackBtn;
- (void)updateFullScreenBtnAlpha:;
- (void)updateHalfScreenButtonsTopOffset;
- (void)updateNavigatioinBarLeftButton;
- (void)updateNavigationBarOnFinish;
- (void)updateUpHalfScreenCloseBtnIcon;
- (void)viewDidBackForward;
- (void)viewDidFinishLoadWithURL:;
- (void)viewDidStartLoading;
- (id)wkObserverKeys;
- (void)setLastLocation:;
- (void)setNavigationBar:;
- (id)lastLocation;
- (void)dealloc;
- (id)context;
- (double)animationDuration;
- (id)containerView;
- (BOOL)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:;
- (void)setContainerView:;
- (void)setDelegate:;
- (BOOL)isLandscape;
- (void)observeValueForKeyPath:ofObject:change:context:;
- (void)viewDidDisappear:;
- (void)scrollViewDidScroll:;
- (id)navigationBar;
- (void)addChildViewController:;
- (void)setStatusBarBackgroundView:;
- (id)statusBarBackgroundView;
- (void)viewWillDisappear:;
- (id)shareInfo;
- (BOOL)showingKeyboard;
- (void)setShowingKeyboard:;
- (id)delegate;
- (void)setAnimationDuration:;
- (void).cxx_destruct;
- (void)viewDidAppear:;
- (void)viewWillAppear:;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)setShareInfo:;
- (void)setContext:;
- (double)defaultHeight;
- (void)viewDidLoad;
- (double)defaultWidth;
- (id)setupContext;
- (void)loadRequest;
- (void)didPan:;
- (id)originLocation;
@end
