@interface QLPreviewController : UIViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSMutableDictionary previewKeyCommands;
@property (nonatomic) BOOL canChangeCurrentPage;
@property (nonatomic) BOOL overlayHidden;
@property (nonatomic) BOOL fullScreen;
@property (nonatomic) BOOL isInteractivePopEnabled;
@property (nonatomic) BOOL previousStatusBarHidden;
@property (nonatomic) q numberOfPreviewItems;
@property (nonatomic) QLItem internalCurrentPreviewItem;
@property (nonatomic) UIViewController<QLPreviewCollectionProtocol> previewCollection;
@property (nonatomic) <QLPrintingProtocol> printer;
@property (nonatomic) NSArray previewToolbarButtons;
@property (nonatomic) NSArray excludedToolbarButtonIdentifiers;
@property (nonatomic) UIAlertController doneButtonAlertController;
@property (nonatomic) QLNavigationState previousNavigationVCState;
@property (nonatomic) UINavigationController internalNavigationController;
@property (nonatomic) BOOL willTransitionToInternalView;
@property (nonatomic) BOOL didTransitionFromInternalView;
@property (nonatomic) BOOL allowInteractiveTransitions;
@property (nonatomic) QLToolbarController toolbarController;
@property (nonatomic) QLPreviewItemStore previewItemStore;
@property (nonatomic) QLActivityItemProvider currentItemProvider;
@property (nonatomic) QLCustomURLSharingProxyDelegate customURLSharingProxyDelegate;
@property (nonatomic) UIDocumentInteractionController sharingInteractionController;
@property (nonatomic) <QLRemotePopoverTracker> shareSheetPopoverTracker;
@property (nonatomic) @? shareSheetDismissCompletion;
@property (nonatomic) NSURL accessedUrlForSharingController;
@property (nonatomic) NSArray originalLeftBarButtonItems;
@property (nonatomic) NSArray originalRightBarButtonItems;
@property (nonatomic) NSString currentTitleFromItemViewController;
@property (nonatomic) <QLPreviewControllerDelegate> strongDelegate;
@property (nonatomic) UIPanGestureRecognizer slideGesture;
@property (nonatomic) UIPinchGestureRecognizer pinchGesture;
@property (nonatomic) UIRotationGestureRecognizer rotationGesture;
@property (nonatomic) QLSwipeDownTracker swipeDownTracker;
@property (nonatomic) QLPinchRotationTracker pinchRotationTracker;
@property (nonatomic) QLStateManager stateManager;
@property (nonatomic) QLTransitionController currentAnimator;
@property (nonatomic) BOOL canShowToolbar;
@property (nonatomic) BOOL canShowNavBar;
@property (nonatomic) BOOL forceDismissActionsPresentation;
@property (nonatomic) BOOL currentPreviewHasRemoteUnsavedEdits;
@property (nonatomic) BOOL isObtainingEditsFromServiceBeforeDismissing;
@property (nonatomic) BOOL isTopPreviewController;
@property (nonatomic) Q quickLookVisibility;
@property (nonatomic) Q appearanceActions;
@property (nonatomic) BOOL isContentManaged;
@property (nonatomic) NSString personaUniqueString;
@property (nonatomic) BOOL useCustomActionButton;
@property (nonatomic) BOOL alwaysDisplayPreviewItemTitle;
@property (nonatomic) BOOL showActionAsDefaultButton;
@property (nonatomic) BOOL forceModalPresentation;
@property (nonatomic) NSArray additionalLeftBarButtonItems;
@property (nonatomic) NSArray additionalRightBarButtonItems;
@property (nonatomic) Q presentationStyle;
@property (nonatomic) UIColor toolbarTintColor;
@property (nonatomic) UIColor navigationBarTintColor;
@property (nonatomic) UIColor backgroundColor;
@property (nonatomic) UIColor fullscreenBackgroundColor;
@property (nonatomic) Q presentationMode;
@property (nonatomic) Q forcedSupportedInterfaceOrientations;
@property (nonatomic) NSString overrideParentApplicationDisplayIdentifier;
@property (nonatomic) <QLPreviewControllerDataSource> dataSource;
@property (nonatomic) q currentPreviewItemIndex;
@property (nonatomic) <QLPreviewItem> currentPreviewItem;
@property (nonatomic) <QLPreviewControllerDelegate> delegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)animationControllerForPresentedController:presentingController:sourceController:;
- (id)printer;
- (void)reloadData;
- (id)personaUniqueString;
- (id)_doneButton;
- (void)setDataSource:;
- (void)willTransitionToTraitCollection:withTransitionCoordinator:;
- (void)_updateBackgroundColor;
- (id)pinchGesture;
- (void)setBackgroundColor:;
- (void)dealloc;
- (BOOL)isContentManaged;
- (unsigned long long)presentationStyle;
- (long long)preferredStatusBarUpdateAnimation;
- (void)setIsContentManaged:;
- (void)setPinchGesture:;
- (id)interactionControllerForPresentation:;
- (void)viewWillTransitionToSize:withTransitionCoordinator:;
- (void)setNavigationBarTintColor:;
- (id)backgroundColor;
- (BOOL)prefersStatusBarHidden;
- (long long)_preferredModalPresentationStyle;
- (void)setDelegate:;
- (id)activityItemsConfiguration;
- (void)setStrongDelegate:;
- (id)animationControllerForDismissedController:;
- (void)beginInteractiveTransition;
- (void)applicationDidBecomeActive:;
- (void)applicationDidEnterBackground:;
- (void)viewDidDisappear:;
- (id)interactionControllerForDismissal:;
- (id)currentTracker;
- (id)currentItem;
- (void)traitCollectionDidChange:;
- (id)keyCommands;
- (void)setAccessoryViewVisible:;
- (void)viewWillDisappear:;
- (unsigned long long)presentationMode;
- (id)dataSource;
- (id)delegate;
- (void)setFullScreen:;
- (id)childViewControllerForStatusBarHidden;
- (BOOL)prefersHomeIndicatorAutoHidden;
- (void)navigationController:willShowViewController:animated:;
- (void)willMoveToParentViewController:;
- (void).cxx_destruct;
- (id)userActivity;
- (void)setPresentationStyle:;
- (void)viewDidAppear:;
- (void)setPrinter:;
- (void)viewWillAppear:;
- (void)setPersonaUniqueString:;
- (void)loadView;
- (int)mode;
- (unsigned long long)supportedInterfaceOrientations;
- (void)setOverrideParentApplicationDisplayIdentifier:;
- (void)screenshotService:generatePDFRepresentationWithCompletion:;
- (id)strongDelegate;
- (id)stateManager;
- (id)overrideParentApplicationDisplayIdentifier;
- (id)initWithNibName:bundle:;
- (void)viewDidLoad;
- (BOOL)sourceIsManaged;
- (BOOL)accessibilityPerformEscape;
- (void)setToolbarTintColor:;
- (void)_reloadDataIfNeeded;
- (id)_preferredBackgroundColor;
- (long long)_preferredWhitePointAdaptivityStyle;
- (id)_childViewControllerForWhitePointAdaptivityStyle;
- (void)setUserActivity:;
- (void)documentPickerWasCancelled:;
- (void)documentPicker:didPickDocumentsAtURLs:;
- (BOOL)fullScreen;
- (id)_actionButton;
- (void)_actionButtonTapped:;
- (id)initWithPreviewItems:;
- (void)setLoadingTextForMissingFiles:;
- (void)refreshCurrentPreviewItem;
- (void)_prepareDelayedAppearance;
- (long long)currentPreviewItemIndex;
- (void)setCurrentOrbMode:;
- (void)setCurrentPreviewItemIndex:;
- (void)setAdditionalLeftBarButtonItems:;
- (void)setAdditionalRightBarButtonItems:;
- (void)_doneButtonTapped:;
- (id)toolbarController;
- (id)currentPreviewItem;
- (id)frameForAdditionalButtonWithActionName:;
- (void)setAppearanceActions:;
- (void)presentPreviewItem:onViewController:withDelegate:animated:;
- (void)documentInteractionControllerDidDismissOptionsMenu:;
- (id)excludedActivityTypesForDocumentInteractionController:;
- (id)additionalActivitiesForDocumentInteractionController:;
- (id)activityItemForDocumentInteractionController:;
- (id)printInfoForDocumentInteractionController:;
- (id)editedItems;
- (id)swipeDownTracker;
- (void)setSwipeDownTracker:;
- (id)navigationBarTintColor;
- (void)setOverlayHidden:;
- (BOOL)overlayHidden;
- (void)setForcedSupportedInterfaceOrientations:;
- (void)_updateAppearance:;
- (void)updatePreferredContentSize:;
- (void)prepareForActionSheetPresentationWithCompletionHandler:;
- (void)dismissQuickLook;
- (BOOL)canShowNavBar;
- (id)fullscreenBackgroundColor;
- (id)internalNavigationController;
- (void)sceneWillDeactivate:;
- (id)flexibleSpace;
- (id)_topNavigationItem;
- (void)updateTitleMenuAndDocumentProperties;
- (void)updateTitleMenuWithItem:;
- (void)createDocumentPropertiesWithItem:shareableURL:;
- (void)updateDocumentPropertiesActivityProviderWithShareableURL:;
- (void)updateDocumentPropertiesDragItemsProviderWithItem:shareableURL:;
- (void)updateDocumentPropertiesMetadataForItem:withShareableURL:;
- (id)titleMenuElementsForItem:atURL:withSuggestedActions:;
- (void)presentError:forAction:;
- (void)handleShortcutsActionOutputFile:forAction:;
- (id)saveToFilesActionForItem:atURL:;
- (id)exportActionForItem:atURL:;
- (id)printActionForItem:atURL:;
- (id)activityControllerForURL:;
- (id)lockPDFActionForItem:atURL:;
- (id)saveToPhotosActionForItem:atURL:;
- (void)presentSaveToPhotoError:forItem:;
- (id)itemProviderForItem:shareableURL:;
- (id)excludedActivityTypesForCurrentPreviewItem;
- (void)setStateManager:;
- (void)setScreenEdgePanWidth:;
- (void)_previousPreview;
- (void)_nextPreview;
- (void)_dismissQuickLookFromKeyboardCommand;
- (void)_keyCommandWasPerformed:;
- (BOOL)itemStore:canShareItem:;
- (BOOL)itemStore:canEditItem:;
- (BOOL)itemStore:canHandleEditedCopyOfPreviewItem:;
- (unsigned long long)itemStore:editedFileBehaviorForItem:;
- (long long)itemStore:editingModeForPreviewItem:;
- (void)previewItemAtIndex:withCompletionHandler:;
- (void)setFullscreenBackgroundColor:;
- (void)previewCollectionUpdatePreviewItem:;
- (void)setToolbarCanBeVisible:;
- (void)setNavBarCanBeVisible:;
- (void)updateOverlayButtons:;
- (void)updateKeyCommands;
- (void)openURLIfAllowed:;
- (void)showShareSheet;
- (void)showShareSheetWithPopoverTracker:customSharedURL:dismissCompletion:;
- (void)triggerQuickLookDismissal;
- (void)getStateRestorationUserInfo:;
- (void)updateStateRestorationWithUserInfo:;
- (void)setCanChangeCurrentPage:;
- (void)currentPreviewItemViewControllerHasUnsavedEdits:;
- (void)forwardMessage:toItemAtIndex:withUUID:completionHandler:;
- (void)setPreviewItemDisplayState:onItemAtIndex:;
- (id)previewItemDisplayStateForItem:;
- (void)expandContentOfItemAtIndex:withUUID:unarchivedItemsURLWrapper:;
- (void)presentAlertControllerForScenario:;
- (void)updatePreviewItemAtIndex:editedCopy:completionHandler:;
- (void)updateTitle:;
- (void)remoteViewControllerWasInvalidated;
- (void)_updateNavigationBarBehaviorStyle;
- (BOOL)_isBeingFullyDismissed;
- (BOOL)_basePreviewControllerIsBeingFullyDismissed;
- (void)_registerForApplicationStateChangesNotifications;
- (void)_unregisterForApplicationStateChangesNotifications;
- (void)_presentPreviewCollection;
- (void)_presentLoadedPreviewCollection:;
- (void)_invalidatePreviewCollectionIfNeeded;
- (void)_invalidatePreviewCollectionIfNeededNow;
- (void)_notifyFirstAppearanceIfNeeded;
- (void)_configurePreviewCollectionIfNeeded;
- (void)_showPreviewCollection;
- (void)_removePreviewCollectionFromViewHierarchy;
- (id)viewForAdditionalButtonWithActionName:;
- (void)waitForPreviewCollectionWithCompletionHandler:;
- (void)_setCurrentPreviewItemIndex:updatePreview:animated:;
- (void)setCurrentPreviewItemIndex:animated:;
- (id)internalCurrentPreviewItem;
- (void)_setFullScreen:animated:force:;
- (void)setOverlayHidden:animated:;
- (void)_setPresentationMode:;
- (void)_updateViewHierarchyPresentation;
- (void)_updateToolbarSuperview;
- (id)previewItemAtIndex:;
- (long long)numberOfPreviewItems;
- (void)setAllowInteractiveTransitions:;
- (void)setUseCustomActionButton:;
- (void)setShowActionAsDefaultButton:;
- (BOOL)hasItemsToPreview;
- (void)setQuickLookVisibility:;
- (void)setQuickLookVisibility:animated:;
- (void)_updateBarTintColors;
- (void)previewCollectionPrefersWhitePointAdaptivityStyle:;
- (void)_updateOverlayButtonsForTraitCollection:animated:;
- (void)_promptUserAndOpenURLIfNeeded:;
- (void)setCurrentPreviewHasRemoteUnsavedEdits:;
- (BOOL)currentPreviewHasUnsavedEdits;
- (void)_updateAllowInteractiveTransitionsIfNeeded;
- (BOOL)_shouldAllowInteractiveTransitions;
- (void)previewItemAtIndex:wasUpdatedWithLifecycleState:withError:;
- (BOOL)isTopPreviewController;
- (id)_topPreviewController;
- (id)_topViewController;
- (BOOL)_topViewControllerBelongsToHierarchy:;
- (BOOL)_quickLookWillBecomeVisible;
- (BOOL)_isQuickLookVisible;
- (void)_savePreviousNavigationVCState;
- (BOOL)parentIsNavigationController;
- (void)showNoDataViewIfNeeded;
- (void)hideNoDataView;
- (BOOL)hasEditedItems;
- (void)_refreshCurrentPreviewItemAnimated:;
- (void)applyPreviewItemDisplayState:toItem:;
- (void)_setPreferredWhitePointAdaptivityStyle:;
- (BOOL)_adoptPersona:andPerformBlock:;
- (id)previewKeyCommands;
- (void)setPreviewKeyCommands:;
- (BOOL)canChangeCurrentPage;
- (BOOL)isInteractivePopEnabled;
- (void)setIsInteractivePopEnabled:;
- (BOOL)previousStatusBarHidden;
- (void)setPreviousStatusBarHidden:;
- (id)previewCollection;
- (id)previewToolbarButtons;
- (id)excludedToolbarButtonIdentifiers;
- (id)doneButtonAlertController;
- (void)setDoneButtonAlertController:;
- (id)previousNavigationVCState;
- (void)setInternalNavigationController:;
- (BOOL)willTransitionToInternalView;
- (void)setWillTransitionToInternalView:;
- (BOOL)didTransitionFromInternalView;
- (void)setDidTransitionFromInternalView:;
- (BOOL)allowInteractiveTransitions;
- (id)previewItemStore;
- (id)currentItemProvider;
- (void)setCurrentItemProvider:;
- (id)customURLSharingProxyDelegate;
- (void)setCustomURLSharingProxyDelegate:;
- (id)sharingInteractionController;
- (void)setSharingInteractionController:;
- (id)shareSheetPopoverTracker;
- (void)setShareSheetPopoverTracker:;
- (id)shareSheetDismissCompletion;
- (void)setShareSheetDismissCompletion:;
- (id)accessedUrlForSharingController;
- (void)setAccessedUrlForSharingController:;
- (id)originalLeftBarButtonItems;
- (void)setOriginalLeftBarButtonItems:;
- (id)originalRightBarButtonItems;
- (void)setOriginalRightBarButtonItems:;
- (id)currentTitleFromItemViewController;
- (void)setCurrentTitleFromItemViewController:;
- (id)slideGesture;
- (void)setSlideGesture:;
- (id)rotationGesture;
- (void)setRotationGesture:;
- (id)pinchRotationTracker;
- (void)setPinchRotationTracker:;
- (id)currentAnimator;
- (void)setCurrentAnimator:;
- (BOOL)canShowToolbar;
- (void)setCanShowToolbar:;
- (void)setCanShowNavBar:;
- (BOOL)forceDismissActionsPresentation;
- (void)setForceDismissActionsPresentation:;
- (BOOL)currentPreviewHasRemoteUnsavedEdits;
- (BOOL)isObtainingEditsFromServiceBeforeDismissing;
- (void)setIsObtainingEditsFromServiceBeforeDismissing:;
- (unsigned long long)quickLookVisibility;
- (unsigned long long)appearanceActions;
- (BOOL)useCustomActionButton;
- (BOOL)alwaysDisplayPreviewItemTitle;
- (void)setAlwaysDisplayPreviewItemTitle:;
- (BOOL)showActionAsDefaultButton;
- (BOOL)forceModalPresentation;
- (void)setForceModalPresentation:;
- (id)additionalLeftBarButtonItems;
- (id)additionalRightBarButtonItems;
- (id)toolbarTintColor;
- (unsigned long long)forcedSupportedInterfaceOrientations;
- (id)_listButton;
- (BOOL)_isInPickMode;
- (unsigned long long)_computePresentationMode;
- (void)registerForScreenshotService;
- (void)unregisterFromScreenshotService;
- (void)didEditCopyOfPreviewItemAtIndex:editedCopy:completionHandler:;
- (void)didEditCopyOfPreviewItemAtIndex:editedCopy:;
- (void)_didEditCopyOfPreviewItemAtIndex:editedCopy:synchronously:completionHandler:;
- (void)_updatePreviewItem:editedCopy:completionHandler:;
- (void)_handleEditedPreviewItem:editedCopy:synchronously:completionHandler:;
- (void)_synchronouslyUpdateContentsOfPreviewItem:editedCopy:completionHandler:;
- (void)_asynchronouslyUpdateContentsOfPreviewItem:editedCopy:completionHandler:;
- (void)shareableURLForCurrentPreviewItem:;
- (void)obtainAndUpdateEditedCopyOfCurrentPreviewItem:;
- (void)presentSaveToFilesForEditedItems:;
- (void)_openInButtonTapped:;
- (void)_copyToButtonTapped:;
- (void)_listButtonTapped:;
- (void)_toolbarButtonPressed:;
- (void)updateOverlayAnimated:forceRefresh:;
- (void)updateOverlayAnimated:forceRefresh:withTraitCollection:;
- (void)updateOverlayAnimated:animatedButtons:forceRefresh:withTraitCollection:;
- (void)_updateOverlayButtonsIfNeededWithTraitCollection:animated:updatedToolbarButtons:;
- (BOOL)_barButtonItemArray:isEqualToArray:;
- (unsigned long long)_numberOfButtonsExcludingSpacersInButtons:disappearingOnTap:;
- (void)updateStatusBarAnimated:;
- (void)updateRemoteOverlayIfNeeded;
- (id)_buttonWithAccessibilityIdentifierPointer:inButtons:;
- (void)_updateCurrentPopoverButtonIfNeeded:newNavigationLeftButtons:;
- (void)updateNavigationTitle;
- (BOOL)_canDisplayOpenInButtonForItem:;
- (BOOL)_shouldDisplayOpenInInChromeIfAvailable;
- (id)_openInButton;
- (id)_additionalLeftButtonItems;
- (id)_additionalRightButtonItems;
- (id)_toolBarButtonsWithTraitCollection:;
- (id)_navigationBarRightButtonsWithTraitCollection:;
- (id)_navigationBarLeftButtonsWithTraitCollection:;
- (id)_openInTitleForOpenInType:claimBinding:;
- (void)_performOpenInWithFileURL:claimBinding:additionalLaunchServicesOptions:completion:;
- (void)showShareSheetFromBarButton:;
- (void)_showShareSheetFromBarButton:;
- (void)showShareSheetFromRemoteViewWithPopoverTracker:customSharedURL:dismissCompletion:;
- (void)_setupDocumentInteractionControllerForPresentation:;
- (void)_setupDocumentInteractionControllerForPresentationWithURL:isCustomURL:completionHandler:;
- (void)_stopAccessingUrlForSharingController;
- (void)_obtainEditsFromServiceAndNotifyPreviewCollectionOfDoneButtonTappedWithSender:;
- (void)_saveEditsIfNecessary:;
- (void)_notifyPreviewCollectionOfDoneButtonTapWithSender:;
- (BOOL)_displayDismissActionsForEditedPreviewItemsIfNeeded:fromBarButtonItem:;
- (void)_performQuickLookDismissalAnimated:;
- (BOOL)_canPerformBarButtonAction;
- (void)_willStartObtainingEditsFromService;
- (void)_didObtainEditsFromService;
- (void)_triggerOverlayUpdateAfterDelay;
- (void)shareSheetDidDismiss;
- (void)didSelectPreviewItem:;
- (id)_editedItemsForDoneActionControllerWithItems:;
- (BOOL)_needsListButton;
- (BOOL)_isToolbarVisibleForTraitCollection:;
- (id)_copyBarButtons:;
- (id)_displayedButtonWithAccessibilityIdentifier:;
- (unsigned long long)currentOrbMode;
- (id)animatorForShowing:previewController:presentingController:;
+ (BOOL)canPreviewItem:;
+ (void)presentPreviewItem:onViewController:withDelegate:animated:;
+ (id)controllerWithItemStore:;
+ (id)printPageRendererForItem:;
+ (void)logDeprecatedMessageForMethodName:;
+ (void)logDeprecatedMessageForSelector:;
+ (id)contentTypeForPreviewItem:;
+ (id)titleForPreviewItem:;
+ (BOOL)copyPreviewItemToPasteboard:;
+ (BOOL)canPreviewDocumentType:;
+ (BOOL)canPreviewMIMEType:;
@end
