@interface RBSProcessHandle : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) RBSProcessInstance instance;
@property (nonatomic) I euid;
@property (nonatomic) BOOL reported;
@property (nonatomic) BOOL lifecycleManaged;
@property (nonatomic) NSString beforeTranslocationBundlePath;
@property (nonatomic) NSString executablePath;
@property (nonatomic) NSInteger pid;
@property (nonatomic) {?=[8I]} auditToken;
@property (nonatomic) NSString name;
@property (nonatomic) RBSProcessIdentity identity;
@property (nonatomic) RBSProcessBundle bundle;
@property (nonatomic) NSInteger platform;
@property (nonatomic) RBSProcessState currentState;
@property (nonatomic) RBSProcessExitContext lastExitContext;
@property (nonatomic) RBSProcessLimitations activeLimitations;
@property (nonatomic) BOOL daemon;
@property (nonatomic) NSString daemonJobLabel;
@property (nonatomic) BOOL consistentLaunchdJob;
@property (nonatomic) NSString consistentJobLabel;
@property (nonatomic) BOOL XPCService;
@property (nonatomic) NSString xpcServiceIdentifier;
@property (nonatomic) NSUUID uuid;
@property (nonatomic) RBSProcessHandle hostProcess;
@property (nonatomic) BOOL application;
@property (nonatomic) BOOL valid;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)fbs_sceneClientIdentity;
- (BOOL)fb_canTaskSuspend;
- (id)hostProcess;
- (BOOL)isDaemon;
- (id)executablePath;
- (id)instance;
- (unsigned int)euid;
- (id)daemonJobLabel;
- (id)init;
- (id)lastExitContext;
- (id)identity;
- (id)beforeTranslocationBundlePath;
- (void)dealloc;
- (BOOL)isLifecycleManaged;
- (BOOL)isApplication;
- (id)currentState;
- (id)initWithRBSXPCCoder:;
- (void)encodeWithRBSXPCCoder:;
- (id)uuid;
- (int)rbs_pid;
- (id)processPredicate;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (id)debugDescription;
- (BOOL)isXPCService;
- (id)auditToken;
- (BOOL)matchesProcess:;
- (id)bundle;
- (void)encodeWithCoder:;
- (BOOL)isManaged;
- (id)xpcServiceIdentifier;
- (int)pid;
- (BOOL)isValid;
- (int)platform;
- (id)initWithIdentity:;
- (void).cxx_destruct;
- (BOOL)isReported;
- (id)description;
- (id)name;
- (BOOL)hasConsistentLaunchdJob;
- (BOOL)isEqual:;
- (id)activeLimitations;
- (void)monitorForDeath:;
- (void)intendToExitWith:;
- (id)initWithInstance:auditToken:bundleData:manageFlags:beforeTranslocationBundlePath:executablePath:cache:;
- (id)initWithLaunchContext:;
- (id)currentStateMatchingDescriptor:;
- (void)fullEncode:forKey:;
- (id)legacyHandle;
- (double)elapsedCPUTimeForFrontBoard;
- (id)consistentJobLabel;
+ (BOOL)supportsRBSXPCSecureCoding;
+ (id)handleForLegacyHandle:error:;
+ (BOOL)supportsSecureCoding;
+ (id)handleForPredicate:error:;
+ (id)currentProcess;
+ (id)observeForImminentAssertionsExpiration:;
+ (id)handleForKey:fetchIfNeeded:;
+ (id)handleForIdentifier:error:;
@end
