@interface RPFileTransferProgress : NSObject
@property (nonatomic) double bytesPerSecond;
@property (nonatomic) double remainingSeconds;
@property (nonatomic) double compressionRate;
@property (nonatomic) NSString currentFilename;
@property (nonatomic) NSError error;
@property (nonatomic) NSInteger linkType;
@property (nonatomic) q transferredByteCount;
@property (nonatomic) q totalByteCount;
@property (nonatomic) q transferredFileCount;
@property (nonatomic) q totalFileCount;
@property (nonatomic) NSInteger type;
- (id)init;
- (id)descriptionWithLevel:;
- (void)setError:;
- (void)setType:;
- (void)setLinkType:;
- (id)error;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (int)type;
- (void).cxx_destruct;
- (id)description;
- (int)linkType;
- (double)bytesPerSecond;
- (void)setBytesPerSecond:;
- (double)remainingSeconds;
- (void)setRemainingSeconds:;
- (double)compressionRate;
- (void)setCompressionRate:;
- (id)currentFilename;
- (void)setCurrentFilename:;
- (long long)transferredByteCount;
- (void)setTransferredByteCount:;
- (long long)totalByteCount;
- (void)setTotalByteCount:;
- (long long)transferredFileCount;
- (void)setTransferredFileCount:;
- (long long)totalFileCount;
- (void)setTotalFileCount:;
+ (BOOL)supportsSecureCoding;
@end
