@interface RTCReportingAgent : NSObject
@property (nonatomic) VCAggregator aggregator;
@property (nonatomic) RTCReporting reportingObject;
@property (nonatomic) NSObject<OS_dispatch_queue> reportingQueue;
@property (nonatomic) NSArray backends;
@property (nonatomic) NSInteger clientType;
@property (nonatomic) NSInteger nextUnassignedReportingModuleID;
@property (nonatomic) NSMutableDictionary userInfoMap;
@property (nonatomic) BOOL forceDisableABC;
@property (nonatomic) NSNumber subSessionId;
@property (nonatomic) NSString serviceName;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (int)clientType;
- (void)dealloc;
- (id)aggregator;
- (id)initWithConfig:;
- (void)setServiceName:;
- (BOOL)sendMessageWithCategory:type:payload:error:;
- (id)serviceName;
- (id)reportingQueue;
- (void)setClientType:;
- (void)didSendMessageForReportingClient:event:;
- (int)learntBitrateForSegment:defaultValue:;
- (void)initAdaptiveLearningWithParameters:;
- (void)sendMessageWithCategory:type:payload:;
- (void)report:segmentDirection:;
- (void)reportQR:;
- (int)nextUnassignedReportingModuleID;
- (id)deriveFromParentHierarchyToken:;
- (id)getUserInfoFromReportingConfiguration:;
- (void)reportingAgentGetAlgosScores:newAlgosScore:;
- (id)newAggregatorForClientType:nwActivity:;
- (void)setAggregatorForClientType:;
- (void)finalizeAggregation;
- (void)reportingSetNetworkActivityReportingEnabled:;
- (unsigned short)reportingSegmentMethodForClientType:;
- (void)releaseReportingObject;
- (unsigned short)reportingCallMethodForClientType:;
- (void)sendAggregatedCallReport;
- (unsigned short)reportingSessionMethodForClientType:;
- (unsigned short)reportingSessionTypeForClientType:;
- (void)sendAggregatedSessionReport;
- (void)reportingSymptom:withOptionalDict:;
- (void)reportingSetReportCallback:withContext:;
- (id)reportingObject;
- (id)backends;
- (void)setBackends:;
- (id)userInfoMap;
- (BOOL)isABCForceDisabled;
- (void)setForceDisableABC:;
- (id)subSessionId;
- (void)setSubSessionId:;
@end
