@interface RTIDocumentTraits : NSObject
@property (nonatomic) NSInteger processId;
@property (nonatomic) NSString appId;
@property (nonatomic) NSString bundleId;
@property (nonatomic) NSString appName;
@property (nonatomic) NSString localizedAppName;
@property (nonatomic) NSArray associatedDomains;
@property (nonatomic) NSObject<NSCopying><NSSecureCoding> responderId;
@property (nonatomic) NSString sceneID;
@property (nonatomic) I contextID;
@property (nonatomic) Q layerID;
@property (nonatomic) Q delegateConformanceType;
@property (nonatomic) BOOL disableAutomaticKeyboardUI;
@property (nonatomic) NSString title;
@property (nonatomic) NSString prompt;
@property (nonatomic) RTIInputViewInfo inputViewInfo;
@property (nonatomic) RTIInputViewInfo assistantViewInfo;
@property (nonatomic) RTIAssistantItem assistantItem;
@property (nonatomic) TITextInputTraits textInputTraits;
@property (nonatomic) NSString textInputContextIdentifier;
@property (nonatomic) NSIndexSet PINEntrySeparatorIndexes;
@property (nonatomic) {_NSRange=QQ} validTextRange;
@property (nonatomic) Q autofillMode;
@property (nonatomic) Q autofillSubMode;
@property (nonatomic) NSDictionary autofillContext;
@property (nonatomic) BOOL shouldLoadAutofillSignUp;
@property (nonatomic) NSString passwordRules;
@property (nonatomic) NSString recipientId;
@property (nonatomic) NSString responseContext;
@property (nonatomic) TIInputContextHistory inputContextHistory;
@property (nonatomic) NSArray enabledSupplementalLexiconIdentifiers;
@property (nonatomic) NSArray supportedPayloadIds;
@property (nonatomic) BOOL supportsImagePaste;
@property (nonatomic) BOOL devicePasscodeEntry;
@property (nonatomic) BOOL disableInputBars;
@property (nonatomic) NSDictionary userInfo;
@property (nonatomic) BOOL disablePrediction;
@property (nonatomic) BOOL hidePrediction;
@property (nonatomic) CAFenceHandle fenceHandle;
@property (nonatomic) NSData textInputModeData;
@property (nonatomic) NSArray additionalLocaleIdentifiers;
- (void)setSceneID:;
- (BOOL)disableInputBars;
- (BOOL)disablePrediction;
- (id)init;
- (BOOL)supportsImagePaste;
- (id)associatedDomains;
- (void)setValidTextRange:;
- (void)setDisableInputBars:;
- (void)dealloc;
- (int)processId;
- (id)textInputTraits;
- (id)appId;
- (id)userInfo;
- (id)sceneID;
- (unsigned long long)delegateConformanceType;
- (void)setDisablePrediction:;
- (id)bundleId;
- (unsigned int)contextID;
- (id)autofillContext;
- (unsigned long long)autofillSubMode;
- (void)setContextID:;
- (void)setTitle:;
- (void)setAppId:;
- (id)initWithCoder:;
- (void)setAppName:;
- (void)setProcessId:;
- (id)PINEntrySeparatorIndexes;
- (void)setPrompt:;
- (id)appName;
- (void)setPasswordRules:;
- (void)encodeWithCoder:;
- (void)setDevicePasscodeEntry:;
- (void)setTextInputTraits:;
- (id)title;
- (void)setSupportedPayloadIds:;
- (void)setUserInfo:;
- (id)localizedAppName;
- (void)setHidePrediction:;
- (void).cxx_destruct;
- (id)responseContext;
- (id)inputContextHistory;
- (id)validTextRange;
- (void)setAutofillContext:;
- (id)prompt;
- (void)setAutofillSubMode:;
- (id)description;
- (unsigned long long)autofillMode;
- (id)supportedPayloadIds;
- (void)setPINEntrySeparatorIndexes:;
- (void)setBundleId:;
- (void)setAssociatedDomains:;
- (void)setResponseContext:;
- (id)passwordRules;
- (BOOL)isEqual:;
- (void)setAutofillMode:;
- (void)setInputContextHistory:;
- (BOOL)hidePrediction;
- (id)copyWithZone:;
- (void)setAssistantViewInfo:;
- (void)setAssistantItem:;
- (void)setInputViewInfo:;
- (void)setShouldLoadAutofillSignUp:;
- (void)setAdditionalLocaleIdentifiers:;
- (void)setFenceHandle:;
- (void)setRecipientId:;
- (BOOL)shouldLoadAutofillSignUp;
- (void)setEnabledSupplementalLexiconIdentifiers:;
- (id)fenceHandle;
- (void)setDelegateConformanceType:;
- (id)enabledSupplementalLexiconIdentifiers;
- (id)assistantItem;
- (void)setTextInputModeData:;
- (void)setTextInputContextIdentifier:;
- (void)setLayerID:;
- (void)setSupportsImagePaste:;
- (id)recipientId;
- (BOOL)devicePasscodeEntry;
- (id)assistantViewInfo;
- (id)inputViewInfo;
- (id)textInputContextIdentifier;
- (void)setDisableAutomaticKeyboardUI:;
- (void)setLocalizedAppName:;
- (BOOL)disableAutomaticKeyboardUI;
- (void)copyContextualPropertiesFromDocumentTraits:;
- (id)responderId;
- (void)setResponderId:;
- (unsigned long long)layerID;
- (id)textInputModeData;
- (id)additionalLocaleIdentifiers;
+ (BOOL)supportsSecureCoding;
@end
