@interface RxCollectionViewOrthogonalScrollerSectionController : NSObject
@property (nonatomic) UICollectionView collectionView;
@property (nonatomic) NSMapTable scrollViewFromSectionMap;
@property (nonatomic) NSMapTable scrollViewToSectionMap;
@property (nonatomic) NSHashTable frontMostElements;
@property (nonatomic) NSIndexSet currentOrthogonalSectionIndexes;
@property (nonatomic) UICollectionView scrollViewCurrentlyBeingConfigured;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)__collectionViewDelegateDidChanged:;
- (void)__collectionViewDidChanged:;
- (id)__contentOffsetForScrollingToItemAtIndexPath:atScrollPosition:itemFrame:containingScrollView:;
- (void)_configureScrollView:forSection:baseContentInsets:;
- (id)_contentSizeForSection:layout:;
- (void)_forceElementsOnTopAsNeeded;
- (long long)_sectionForSectionScrollView:;
- (id)addCollectionViewForIndexPath:;
- (id)addCollectionViewForSection:;
- (void)addElementIfNeeded:;
- (id)collectionViewForIndexPath:;
- (id)collectionViewForSection:;
- (void)reconfigureOrthogonalSectionsForUpdate:;
- (void)restoreLayoutContentOffsetsFromEmbeddedScrollViews;
- (void)synchronizeDelegates;
- (BOOL)respondsToSelector:;
- (id)scrollViewCurrentlyBeingConfigured;
- (void)adjustElementHierarchyOrderingForOrthogonalElementIfNeeded:layoutAttributes:;
- (void)scrollToItemAtIndexPath:atScrollPosition:animated:;
- (void)setScrollViewCurrentlyBeingConfigured:;
- (long long)collectionView:numberOfItemsInSection:;
- (void)setScrollViewFromSectionMap:;
- (BOOL)isIndexPathInOrthogonalScrollingSection:;
- (id)_sectionScrollViewForSection:;
- (id)collectionView:cellForItemAtIndexPath:;
- (void)setScrollViewToSectionMap:;
- (id)_managedScrollViews;
- (void)scrollViewDidScroll:;
- (id)initWithCollectionView:;
- (void)setCurrentOrthogonalSectionIndexes:;
- (id)_sectionScrollViewForIndexPath:;
- (BOOL)isElementInOrthogonalScrollingSection:;
- (id)currentOrthogonalSectionIndexes;
- (void).cxx_destruct;
- (id)_addSectionScrollViewForIndexPath:;
- (void)scrollViewWillEndDragging:withVelocity:targetContentOffset:;
- (id)scrollViewFromSectionMap;
- (id)frontMostElements;
- (id)collectionView:viewForSupplementaryElementOfKind:atIndexPath:;
- (long long)numberOfSectionsInCollectionView:;
- (void)performLayout;
- (id)scrollViewToSectionMap;
- (void)forwardInvocation:;
- (id)collectionView;
- (void)_scrollToItemAtIndexPath:atScrollPosition:animated:;
- (id)_addSectionScrollViewForSection:;
- (id)compositionalLayout;
@end
