@interface RxPromise : NSObject
@property (nonatomic) @ value;
@property (nonatomic) NSError error;
@property (nonatomic) BOOL fulfilled;
@property (nonatomic) BOOL rejected;
@property (nonatomic) BOOL cancelled;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)then:scheduler:;
- (void)addCancellable:;
- (BOOL)isRunningOrResolved;
- (void)joinedPromiseFulfilled:scheduler:;
- (id)performWhenFinished:;
- (id)performWhenFinished:scheduler:;
- (void)rejectWithError:scheduler:;
- (void)resolveWithValue:scheduler:;
- (id)then:error:;
- (id)then:error:scheduler:;
- (id)waitForValue;
- (id)waitForValueWithTimeout:;
- (BOOL)cancelled;
- (id)init;
- (void)cancel;
- (void)dealloc;
- (id)initWithScheduler:;
- (BOOL)isCancelled;
- (void)finish;
- (id)then:;
- (id)error;
- (BOOL)isRunning;
- (void).cxx_destruct;
- (id)description;
- (id)value;
- (BOOL)fulfilled;
- (BOOL)completed;
- (id).cxx_construct;
- (BOOL)rejected;
+ (void)__resolve:value:scheduler:;
+ (id)promise:;
+ (id)promise:scheduler:;
+ (id)reject:scheduler:;
+ (id)resolve:scheduler:;
+ (id)when:;
+ (id)resolve:;
+ (id)reject:;
+ (id)join:;
@end
