@interface SADPDeviceDetail : SADomainObject
@property (nonatomic) BOOL canPlaySound;
@property (nonatomic) NSString deviceClass;
@property (nonatomic) NSString deviceId;
@property (nonatomic) NSString deviceLocality;
@property (nonatomic) NSString deviceName;
@property (nonatomic) NSString emoji;
@property (nonatomic) BOOL foundNearby;
@property (nonatomic) SAPerson owner;
@property (nonatomic) NSString productName;
@property (nonatomic) NSArray productTypes;
@property (nonatomic) BOOL thisDevice;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setProductName:;
- (id)productName;
- (id)deviceClass;
- (id)deviceId;
- (void)setDeviceId:;
- (void)setDeviceName:;
- (void)setDeviceClass:;
- (id)groupIdentifier;
- (id)deviceName;
- (void)setOwner:;
- (BOOL)canPlaySound;
- (id)owner;
- (void)setCanPlaySound:;
- (id)encodedClassName;
- (id)emoji;
- (void)setEmoji:;
- (void)setThisDevice:;
- (id)deviceLocality;
- (void)setDeviceLocality:;
- (BOOL)foundNearby;
- (void)setFoundNearby:;
- (id)productTypes;
- (void)setProductTypes:;
- (BOOL)thisDevice;
+ (id)deviceDetail;
+ (id)deviceDetailWithDictionary:context:;
@end
