@interface SAPerson : SADomainObject
@property (nonatomic) NSArray addresses;
@property (nonatomic) NSDate birthday;
@property (nonatomic) NSString company;
@property (nonatomic) NSString companyPhonetic;
@property (nonatomic) NSArray emails;
@property (nonatomic) NSString firstName;
@property (nonatomic) NSDictionary firstNameAPGs;
@property (nonatomic) NSString firstNamePhonetic;
@property (nonatomic) NSString fullName;
@property (nonatomic) NSString internalGUID;
@property (nonatomic) NSNumber isBlocked;
@property (nonatomic) NSString lastName;
@property (nonatomic) NSDictionary lastNameAPGs;
@property (nonatomic) NSString lastNamePhonetic;
@property (nonatomic) NSNumber me;
@property (nonatomic) NSString middleName;
@property (nonatomic) NSString nickName;
@property (nonatomic) NSDictionary nickNameAPGs;
@property (nonatomic) NSString phonemeData;
@property (nonatomic) NSArray phones;
@property (nonatomic) NSString prefix;
@property (nonatomic) NSNumber pseudo;
@property (nonatomic) NSArray relatedNames;
@property (nonatomic) NSArray socialProfiles;
@property (nonatomic) NSString suffix;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setLastName:;
- (id)fullName;
- (void)setMe:;
- (void)setBirthday:;
- (id)groupIdentifier;
- (void)setPhonemeData:;
- (id)me;
- (void)setFirstName:;
- (id)birthday;
- (id)socialProfiles;
- (id)phonemeData;
- (id)firstName;
- (id)middleName;
- (id)lastName;
- (id)suffix;
- (void)setSocialProfiles:;
- (void)setFullName:;
- (void)setPrefix:;
- (id)prefix;
- (id)encodedClassName;
- (id)nickName;
- (id)isBlocked;
- (void)setSuffix:;
- (id)emails;
- (void)setRelatedNames:;
- (id)relatedNames;
- (void)setMiddleName:;
- (void)setNickName:;
- (id)addresses;
- (void)setIsBlocked:;
- (id)phones;
- (void)setAddresses:;
- (void)setEmails:;
- (void)setPhones:;
- (id)internalGUID;
- (void)setInternalGUID:;
- (id)company;
- (void)setCompany:;
- (id)pseudo;
- (void)setPseudo:;
- (id)companyPhonetic;
- (void)setCompanyPhonetic:;
- (id)firstNameAPGs;
- (void)setFirstNameAPGs:;
- (id)firstNamePhonetic;
- (void)setFirstNamePhonetic:;
- (id)lastNameAPGs;
- (void)setLastNameAPGs:;
- (id)lastNamePhonetic;
- (void)setLastNamePhonetic:;
- (id)nickNameAPGs;
- (void)setNickNameAPGs:;
+ (id)person;
+ (id)personWithDictionary:context:;
@end
