@interface SASportsAthlete : SASportsEntity
@property (nonatomic) SASportsTeam activeTeam;
@property (nonatomic) NSArray athleteMetadata;
@property (nonatomic) NSArray careerStatistics;
@property (nonatomic) NSString firstName;
@property (nonatomic) NSArray formattedMetadata;
@property (nonatomic) NSArray formattedMetadataTypes;
@property (nonatomic) NSString gender;
@property (nonatomic) NSString height;
@property (nonatomic) NSNumber injured;
@property (nonatomic) NSString jerseyNumber;
@property (nonatomic) NSArray lastGameStatistics;
@property (nonatomic) NSString lastName;
@property (nonatomic) NSString nickname;
@property (nonatomic) NSString position;
@property (nonatomic) NSArray previousTeams;
@property (nonatomic) NSArray statistics;
@property (nonatomic) NSString weight;
- (void)setPosition:;
- (void)setLastName:;
- (id)position;
- (id)groupIdentifier;
- (id)gender;
- (id)weight;
- (void)setFirstName:;
- (void)setGender:;
- (id)firstName;
- (void)setWeight:;
- (id)lastName;
- (id)nickname;
- (id)height;
- (id)encodedClassName;
- (void)setHeight:;
- (void)setStatistics:;
- (id)statistics;
- (void)setNickname:;
- (id)activeTeam;
- (void)setActiveTeam:;
- (id)athleteMetadata;
- (void)setAthleteMetadata:;
- (id)careerStatistics;
- (void)setCareerStatistics:;
- (id)formattedMetadata;
- (void)setFormattedMetadata:;
- (id)formattedMetadataTypes;
- (void)setFormattedMetadataTypes:;
- (id)injured;
- (void)setInjured:;
- (id)jerseyNumber;
- (void)setJerseyNumber:;
- (id)lastGameStatistics;
- (void)setLastGameStatistics:;
- (id)previousTeams;
- (void)setPreviousTeams:;
+ (id)athlete;
+ (id)athleteWithDictionary:context:;
@end
