@interface SAWeatherCurrentConditions : AceObject
@property (nonatomic) SAWeatherBarometricPressure barometricPressure;
@property (nonatomic) SAWeatherCondition condition;
@property (nonatomic) NSNumber dayOfWeek;
@property (nonatomic) NSString dewPoint;
@property (nonatomic) NSString heatIndex;
@property (nonatomic) NSString moonPhase;
@property (nonatomic) NSString percentHumidity;
@property (nonatomic) NSNumber percentOfMoonFaceVisible;
@property (nonatomic) NSString sunrise;
@property (nonatomic) NSString sunset;
@property (nonatomic) NSString temperature;
@property (nonatomic) NSString timeOfObservation;
@property (nonatomic) NSString timeZone;
@property (nonatomic) NSString totalDailyPrecipitation;
@property (nonatomic) NSNumber uvIndex;
@property (nonatomic) NSString visibility;
@property (nonatomic) NSString windChill;
@property (nonatomic) SAWeatherWindSpeed windSpeed;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)condition;
- (void)setTimeZone:;
- (void)setCondition:;
- (id)groupIdentifier;
- (void)setVisibility:;
- (id)visibility;
- (void)setTemperature:;
- (id)dayOfWeek;
- (id)sunrise;
- (id)sunset;
- (void)setDayOfWeek:;
- (id)encodedClassName;
- (id)timeZone;
- (id)temperature;
- (id)barometricPressure;
- (void)setBarometricPressure:;
- (id)dewPoint;
- (void)setDewPoint:;
- (id)heatIndex;
- (void)setHeatIndex:;
- (id)moonPhase;
- (void)setMoonPhase:;
- (id)percentHumidity;
- (void)setPercentHumidity:;
- (id)percentOfMoonFaceVisible;
- (void)setPercentOfMoonFaceVisible:;
- (void)setSunrise:;
- (void)setSunset:;
- (id)timeOfObservation;
- (void)setTimeOfObservation:;
- (id)totalDailyPrecipitation;
- (void)setTotalDailyPrecipitation:;
- (id)uvIndex;
- (void)setUvIndex:;
- (id)windChill;
- (void)setWindChill:;
- (id)windSpeed;
- (void)setWindSpeed:;
+ (id)currentConditions;
+ (id)currentConditionsWithDictionary:context:;
@end
