@interface SBSRemoteAlertActivationContext : NSObject
@property (nonatomic) NSUUID activityContinuationIdentifier;
@property (nonatomic) NSDictionary legacyAlertOptions;
@property (nonatomic) BOOL shouldInvalidateWhenDeactivated;
@property (nonatomic) BOOL switcherEligible;
@property (nonatomic) NSString reason;
@property (nonatomic) BOOL activatingForSiri;
@property (nonatomic) BOOL shouldDismissPresentedBanners;
@property (nonatomic) BOOL shouldStashPictureInPictureIfNeeded;
@property (nonatomic) NSSet actions;
@property (nonatomic) NSDictionary userInfo;
@property (nonatomic) SBSRemoteAlertPresentationTarget presentationTarget;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)init;
- (void)encodeWithXPCDictionary:;
- (void)setActions:;
- (id)userInfo;
- (id)reason;
- (id)succinctDescriptionBuilder;
- (id)initWithCoder:;
- (void)setReason:;
- (void)encodeWithCoder:;
- (id)initWithXPCDictionary:;
- (id)actions;
- (void)setUserInfo:;
- (void).cxx_destruct;
- (id)succinctDescription;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:;
- (id)descriptionWithMultilinePrefix:;
- (id)initWithActions:;
- (void)setPresentationTarget:;
- (id)initWithActions:presentationTarget:;
- (id)initWithActions:presentationTarget:userInfo:;
- (void)setLegacyAlertOptions:;
- (BOOL)isActivatingForSiri;
- (void)setActivatingForSiri:;
- (BOOL)shouldDismissPresentedBanners;
- (void)setShouldDismissPresentedBanners:;
- (BOOL)shouldStashPictureInPictureIfNeeded;
- (void)setShouldStashPictureInPictureIfNeeded:;
- (id)presentationTarget;
- (id)activityContinuationIdentifier;
- (void)setActivityContinuationIdentifier:;
- (id)legacyAlertOptions;
- (BOOL)shouldInvalidateWhenDeactivated;
- (void)setShouldInvalidateWhenDeactivated:;
- (BOOL)isSwitcherEligible;
- (void)setSwitcherEligible:;
+ (BOOL)supportsSecureCoding;
+ (id)activationContextWithLegacyAlertOptions:;
@end
