@interface SCLAlertView : UIViewController
@property (nonatomic) NSMutableArray inputs;
@property (nonatomic) NSMutableArray customViews;
@property (nonatomic) NSMutableArray buttons;
@property (nonatomic) UIImageView circleIconImageView;
@property (nonatomic) UIView circleView;
@property (nonatomic) UIView circleViewBackground;
@property (nonatomic) UIView contentView;
@property (nonatomic) UIImageView backgroundView;
@property (nonatomic) UITapGestureRecognizer gestureRecognizer;
@property (nonatomic) NSString titleFontFamily;
@property (nonatomic) NSString bodyTextFontFamily;
@property (nonatomic) NSString buttonsFontFamily;
@property (nonatomic) UIWindow previousWindow;
@property (nonatomic) UIWindow SCLAlertWindow;
@property (nonatomic) @? dismissBlock;
@property (nonatomic) @? dismissAnimationCompletionBlock;
@property (nonatomic) @? showAnimationCompletionBlock;
@property (nonatomic) UIViewController rootViewController;
@property (nonatomic) <UIGestureRecognizerDelegate> restoreInteractivePopGestureDelegate;
@property (nonatomic) I soundID;
@property (nonatomic) BOOL canAddObservers;
@property (nonatomic) BOOL keyboardIsVisible;
@property (nonatomic) BOOL usingNewWindow;
@property (nonatomic) BOOL restoreInteractivePopGestureEnabled;
@property (nonatomic) double backgroundOpacity;
@property (nonatomic) double titleFontSize;
@property (nonatomic) double bodyFontSize;
@property (nonatomic) double buttonsFontSize;
@property (nonatomic) double windowHeight;
@property (nonatomic) double windowWidth;
@property (nonatomic) double titleHeight;
@property (nonatomic) double subTitleHeight;
@property (nonatomic) double subTitleY;
@property (nonatomic) double cornerRadius;
@property (nonatomic) BOOL tintTopCircle;
@property (nonatomic) BOOL useLargerIcon;
@property (nonatomic) UILabel labelTitle;
@property (nonatomic) UITextView viewText;
@property (nonatomic) UIActivityIndicatorView activityIndicatorView;
@property (nonatomic) BOOL shouldDismissOnTapOutside;
@property (nonatomic) NSURL soundURL;
@property (nonatomic) @? attributedFormatBlock;
@property (nonatomic) @? completeButtonFormatBlock;
@property (nonatomic) @? buttonFormatBlock;
@property (nonatomic) @? forceHideBlock;
@property (nonatomic) q hideAnimationType;
@property (nonatomic) q showAnimationType;
@property (nonatomic) q backgroundType;
@property (nonatomic) UIColor customViewColor;
@property (nonatomic) UIColor backgroundViewColor;
@property (nonatomic) UIColor iconTintColor;
@property (nonatomic) double circleIconHeight;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} extensionBounds;
@property (nonatomic) BOOL statusBarHidden;
@property (nonatomic) q statusBarStyle;
@property (nonatomic) BOOL horizontalButtons;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)initWithCoder:;
- (id)init;
- (id)initWithWindowWidth:;
- (id)initWithNewWindow;
- (id)initWithNewWindowWidth:;
- (void)dealloc;
- (void)addObservers;
- (void)removeObservers;
- (void)setupViewWindowWidth:;
- (void)setupNewWindow;
- (BOOL)isModal;
- (void)viewWillLayoutSubviews;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)handleTap:;
- (void)setShouldDismissOnTapOutside:;
- (void)disableInteractivePopGesture;
- (void)restoreInteractivePopGesture;
- (void)setTitleFontFamily:withSize:;
- (void)setBodyTextFontFamily:withSize:;
- (void)setButtonsTextFontFamily:withSize:;
- (void)setBackgroundViewColor:;
- (void)setSoundURL:;
- (void)setSubTitleHeight:;
- (void)addActivityIndicatorView;
- (id)addCustomView:;
- (id)addSwitchViewWithLabel:;
- (id)addTextField:setDefaultText:;
- (void)addCustomTextField:;
- (BOOL)textFieldShouldReturn:;
- (void)keyboardWillShow:;
- (void)keyboardWillHide:;
- (id)addButton:;
- (id)addDoneButtonWithTitle:;
- (id)addButton:actionBlock:;
- (id)addButton:validationBlock:actionBlock:;
- (id)addButton:target:selector:;
- (void)buttonTapped:;
- (void)addTimerToButtonIndex:reverse:;
- (id)showTitle:image:color:title:subTitle:duration:completeText:style:;
- (void)showSuccess:title:subTitle:closeButtonTitle:duration:;
- (void)showError:title:subTitle:closeButtonTitle:duration:;
- (void)showNotice:title:subTitle:closeButtonTitle:duration:;
- (void)showWarning:title:subTitle:closeButtonTitle:duration:;
- (void)showInfo:title:subTitle:closeButtonTitle:duration:;
- (void)showEdit:title:subTitle:closeButtonTitle:duration:;
- (void)showTitle:title:subTitle:style:closeButtonTitle:duration:;
- (void)showCustom:image:color:title:subTitle:closeButtonTitle:duration:;
- (void)showWaiting:title:subTitle:closeButtonTitle:duration:;
- (void)showQuestion:title:subTitle:closeButtonTitle:duration:;
- (void)showSuccess:subTitle:closeButtonTitle:duration:;
- (void)showError:subTitle:closeButtonTitle:duration:;
- (void)showNotice:subTitle:closeButtonTitle:duration:;
- (void)showWarning:subTitle:closeButtonTitle:duration:;
- (void)showInfo:subTitle:closeButtonTitle:duration:;
- (void)showEdit:subTitle:closeButtonTitle:duration:;
- (void)showTitle:subTitle:style:closeButtonTitle:duration:;
- (void)showCustom:color:title:subTitle:closeButtonTitle:duration:;
- (void)showWaiting:subTitle:closeButtonTitle:duration:;
- (void)showQuestion:subTitle:closeButtonTitle:duration:;
- (void)removeTopCircle;
- (BOOL)isVisible;
- (void)alertIsDismissed:;
- (void)alertDismissAnimationIsCompleted:;
- (void)alertShowAnimationIsCompleted:;
- (id)forceHideBlock:;
- (id)mainScreenFrame;
- (BOOL)isAppExtension;
- (void)makeShadowBackground;
- (void)makeBlurBackground;
- (void)makeTransparentBackground;
- (void)setBackground;
- (void)showView;
- (void)hideView;
- (void)fadeOut;
- (void)fadeOutWithDuration:;
- (void)slideOutToBottom;
- (void)slideOutToTop;
- (void)slideOutToLeft;
- (void)slideOutToRight;
- (void)slideOutToCenter;
- (void)slideOutFromCenter;
- (void)simplyDisappear;
- (void)fadeIn;
- (void)slideInFromTop;
- (void)slideInFromBottom;
- (void)slideInFromLeft;
- (void)slideInFromRight;
- (void)slideInFromCenter;
- (void)slideInToCenter;
- (void)simplyAppear;
- (double)cornerRadius;
- (void)setCornerRadius:;
- (BOOL)tintTopCircle;
- (void)setTintTopCircle:;
- (BOOL)useLargerIcon;
- (void)setUseLargerIcon:;
- (id)labelTitle;
- (void)setLabelTitle:;
- (id)viewText;
- (void)setViewText:;
- (id)activityIndicatorView;
- (void)setActivityIndicatorView:;
- (BOOL)shouldDismissOnTapOutside;
- (id)soundURL;
- (id)attributedFormatBlock;
- (void)setAttributedFormatBlock:;
- (id)completeButtonFormatBlock;
- (void)setCompleteButtonFormatBlock:;
- (id)buttonFormatBlock;
- (void)setButtonFormatBlock:;
- (id)forceHideBlock;
- (void)setForceHideBlock:;
- (long long)hideAnimationType;
- (void)setHideAnimationType:;
- (long long)showAnimationType;
- (void)setShowAnimationType:;
- (long long)backgroundType;
- (void)setBackgroundType:;
- (id)customViewColor;
- (void)setCustomViewColor:;
- (id)backgroundViewColor;
- (id)iconTintColor;
- (void)setIconTintColor:;
- (double)circleIconHeight;
- (void)setCircleIconHeight:;
- (id)extensionBounds;
- (void)setExtensionBounds:;
- (BOOL)statusBarHidden;
- (void)setStatusBarHidden:;
- (long long)statusBarStyle;
- (void)setStatusBarStyle:;
- (BOOL)horizontalButtons;
- (void)setHorizontalButtons:;
- (id)inputs;
- (void)setInputs:;
- (id)customViews;
- (void)setCustomViews:;
- (id)buttons;
- (void)setButtons:;
- (id)circleIconImageView;
- (void)setCircleIconImageView:;
- (id)circleView;
- (void)setCircleView:;
- (id)circleViewBackground;
- (void)setCircleViewBackground:;
- (id)contentView;
- (void)setContentView:;
- (id)backgroundView;
- (void)setBackgroundView:;
- (id)gestureRecognizer;
- (void)setGestureRecognizer:;
- (id)titleFontFamily;
- (void)setTitleFontFamily:;
- (id)bodyTextFontFamily;
- (void)setBodyTextFontFamily:;
- (id)buttonsFontFamily;
- (void)setButtonsFontFamily:;
- (id)previousWindow;
- (void)setPreviousWindow:;
- (id)SCLAlertWindow;
- (void)setSCLAlertWindow:;
- (id)dismissBlock;
- (void)setDismissBlock:;
- (id)dismissAnimationCompletionBlock;
- (void)setDismissAnimationCompletionBlock:;
- (id)showAnimationCompletionBlock;
- (void)setShowAnimationCompletionBlock:;
- (id)rootViewController;
- (void)setRootViewController:;
- (id)restoreInteractivePopGestureDelegate;
- (void)setRestoreInteractivePopGestureDelegate:;
- (unsigned int)soundID;
- (void)setSoundID:;
- (BOOL)canAddObservers;
- (void)setCanAddObservers:;
- (BOOL)keyboardIsVisible;
- (void)setKeyboardIsVisible:;
- (BOOL)usingNewWindow;
- (void)setUsingNewWindow:;
- (BOOL)restoreInteractivePopGestureEnabled;
- (void)setRestoreInteractivePopGestureEnabled:;
- (double)backgroundOpacity;
- (void)setBackgroundOpacity:;
- (double)titleFontSize;
- (void)setTitleFontSize:;
- (double)bodyFontSize;
- (void)setBodyFontSize:;
- (double)buttonsFontSize;
- (void)setButtonsFontSize:;
- (double)windowHeight;
- (void)setWindowHeight:;
- (double)windowWidth;
- (void)setWindowWidth:;
- (double)titleHeight;
- (void)setTitleHeight:;
- (double)subTitleHeight;
- (double)subTitleY;
- (void)setSubTitleY:;
- (void).cxx_destruct;
@end
