@interface SCNShape : SCNGeometry
@property (nonatomic) UIBezierPath path;
@property (nonatomic) double extrusionDepth;
@property (nonatomic) q chamferMode;
@property (nonatomic) double chamferRadius;
@property (nonatomic) UIBezierPath chamferProfile;
- (id)path;
- (id)init;
- (void)dealloc;
- (id)copy;
- (void)setPath:;
- (id)initWithCoder:;
- (void)encodeWithCoder:;
- (id)description;
- (id)params;
- (id)copyWithZone:;
- (long long)primitiveType;
- (void)setPrimitiveType:;
- (void)setChamferRadius:;
- (BOOL)getBoundingBoxMin:max:;
- (BOOL)getBoundingSphereCenter:radius:;
- (id)copyAnimationChannelForKeyPath:animation:;
- (id)__createCFObject;
- (id)presentationGeometry;
- (void)_syncObjCModel:;
- (double)chamferRadius;
- (double)extrusionDepth;
- (void)setExtrusionDepth:;
- (long long)chamferMode;
- (void)setChamferMode:;
- (id)chamferProfile;
- (void)setChamferProfile:;
- (double)discretizedStraightLineMaxLength;
- (void)setDiscretizedStraightLineMaxLength:;
- (id)initWithShapeGeometryRef:;
- (id)initPresentationShapeGeometryWithShapeGeometryRef:;
- (void)_customDecodingOfSCNShape:;
- (void)_customEncodingOfSCNShape:;
+ (id)shapeWithPath:materialDiffuse:;
+ (id)nameHeader:frame:corners:;
+ (BOOL)supportsSecureCoding;
+ (id)shapeWithPath:extrusionDepth:;
@end
