@interface SFMediaInfoCardSection : SFCardSection
@property (nonatomic) NSArray punchoutOptions;
@property (nonatomic) NSString punchoutPickerTitle;
@property (nonatomic) NSString punchoutPickerDismissText;
@property (nonatomic) BOOL canBeHidden;
@property (nonatomic) BOOL hasTopPadding;
@property (nonatomic) BOOL hasBottomPadding;
@property (nonatomic) NSString type;
@property (nonatomic) NSInteger separatorStyle;
@property (nonatomic) SFColor backgroundColor;
@property (nonatomic) SFMediaItem mediaItem;
@property (nonatomic) NSArray details;
@property (nonatomic) SFActionItem playAction;
@property (nonatomic) NSArray offers;
@property (nonatomic) NSString watchListIdentifier;
@property (nonatomic) NSString watchListButtonLabel;
@property (nonatomic) NSString watchListContinuationText;
@property (nonatomic) NSString watchListConfirmationText;
@property (nonatomic) BOOL isMediaContainer;
@property (nonatomic) SFRichText specialOfferButtonLabel;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) NSData jsonData;
@property (nonatomic) BOOL hideDivider;
@property (nonatomic) SFCard nextCard;
@property (nonatomic) NSArray commands;
@property (nonatomic) NSArray parameterKeyPaths;
@property (nonatomic) NSString cardSectionId;
@property (nonatomic) NSString resultIdentifier;
@property (nonatomic) SFUserReportRequest userReportRequest;
@property (nonatomic) SFCommand command;
@property (nonatomic) SFCommand previewCommand;
@property (nonatomic) NSArray previewButtonItems;
@property (nonatomic) NSString commandDetail;
@property (nonatomic) NSString cardSectionDetail;
@property (nonatomic) NSString previewButtonItemsTitle;
@property (nonatomic) NSArray embeddedCards;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setDetails:;
- (void)setBackgroundColor:;
- (id)initWithProtobuf:;
- (id)backgroundColor;
- (void)setType:;
- (id)offers;
- (id)initWithCoder:;
- (id)jsonData;
- (unsigned long long)hash;
- (void)encodeWithCoder:;
- (id)type;
- (void).cxx_destruct;
- (int)separatorStyle;
- (void)setOffers:;
- (id)dictionaryRepresentation;
- (void)setSeparatorStyle:;
- (id)details;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)punchoutOptions;
- (id)mediaItem;
- (void)setMediaItem:;
- (void)setPunchoutOptions:;
- (void)setPunchoutPickerDismissText:;
- (void)setPunchoutPickerTitle:;
- (void)setCanBeHidden:;
- (void)setWatchListButtonLabel:;
- (void)setWatchListConfirmationText:;
- (void)setWatchListContinuationText:;
- (void)setWatchListIdentifier:;
- (void)setSpecialOfferButtonLabel:;
- (void)setPlayAction:;
- (void)setHasTopPadding:;
- (void)setIsMediaContainer:;
- (id)punchoutPickerTitle;
- (id)punchoutPickerDismissText;
- (BOOL)canBeHidden;
- (BOOL)hasTopPadding;
- (BOOL)hasBottomPadding;
- (void)setHasBottomPadding:;
- (BOOL)hasCanBeHidden;
- (BOOL)hasHasTopPadding;
- (BOOL)hasHasBottomPadding;
- (BOOL)hasSeparatorStyle;
- (id)playAction;
- (id)watchListIdentifier;
- (id)watchListButtonLabel;
- (id)watchListContinuationText;
- (id)watchListConfirmationText;
- (BOOL)isMediaContainer;
- (id)specialOfferButtonLabel;
- (BOOL)hasIsMediaContainer;
+ (BOOL)supportsSecureCoding;
@end
