@interface SFPasswordSharingSession : NSObject
@property (nonatomic) NSObject<OS_dispatch_queue> dispatchQueue;
@property (nonatomic) NSString deviceName;
@property (nonatomic) NSString hashedEmail;
@property (nonatomic) NSString hashedPhone;
@property (nonatomic) NSString hotspotPSK;
@property (nonatomic) SFDevice peerDevice;
@property (nonatomic) @? progressHandler;
@property (nonatomic) @? promptForPINHandler;
- (void)_cleanup;
- (void)setProgressHandler:;
- (id)progressHandler;
- (void)setPromptForPINHandler:;
- (id)init;
- (void)setDeviceName:;
- (id)promptForPINHandler;
- (void)_run;
- (void)dealloc;
- (id)deviceName;
- (id)dispatchQueue;
- (void)setDispatchQueue:;
- (id)peerDevice;
- (void)setPeerDevice:;
- (void)tryPIN:;
- (void).cxx_destruct;
- (void)invalidate;
- (void)activate;
- (void)_completedWithError:;
- (int)_runSFSessionStart;
- (int)_runPair;
- (int)_runPasswordShare;
- (void)_runPasswordShareSendInfo;
- (void)_runPasswordShareReceiveResponse:;
- (void)_receivedObject:flags:;
- (id)hashedEmail;
- (void)setHashedEmail:;
- (id)hashedPhone;
- (void)setHashedPhone:;
- (id)hotspotPSK;
- (void)setHotspotPSK:;
@end
