@interface SFPasswordSavingServiceViewController : SFPasswordServiceViewController
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void).cxx_destruct;
- (void)_dismiss;
- (id)initWithNibName:bundle:;
- (void)credentialsSubmittedForWebsiteURL:user:password:passwordIsAutoGenerated:completionHandler:;
- (void)_initiateUpgradeToSignInWithApple;
- (void)_initiateChangeToStrongPassword;
- (void)showPromptWithToken:style:;
- (void)_checkIfWarningStoreAlreadyContainsCredentialWithCompletionHandler:;
- (void)_configureSecurityPromptActionsWithCompletionHandler:;
- (void)_saveCredential:;
- (void)_updateCredential:;
- (void)_removeCredential:;
- (void)_showAccountModificationPrompt;
- (void)_addUpgradeToSignInWithAppleActionToPrompt;
- (void)_addChangeToStrongPasswordActionToPrompt;
- (void)_addChangePasswordOnWebsiteActionToPrompt;
- (id)_titleStringForAccountModificationPrompt;
- (id)_messageStringForAccountModificationPrompt;
- (void)_openPasswordManagerToChangePasswordOnWebsite;
+ (id)_exportedInterface;
@end
