@interface SFRichTitleCardSection : SFTitleCardSection
@property (nonatomic) NSArray punchoutOptions;
@property (nonatomic) NSString punchoutPickerTitle;
@property (nonatomic) NSString punchoutPickerDismissText;
@property (nonatomic) BOOL canBeHidden;
@property (nonatomic) BOOL hasTopPadding;
@property (nonatomic) BOOL hasBottomPadding;
@property (nonatomic) NSString type;
@property (nonatomic) NSInteger separatorStyle;
@property (nonatomic) SFColor backgroundColor;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) NSString contentAdvisory;
@property (nonatomic) SFImage titleImage;
@property (nonatomic) BOOL isCentered;
@property (nonatomic) NSString descriptionText;
@property (nonatomic) NSNumber rating;
@property (nonatomic) NSString ratingText;
@property (nonatomic) SFImage reviewGlyph;
@property (nonatomic) NSString reviewText;
@property (nonatomic) BOOL reviewNewLine;
@property (nonatomic) NSArray moreGlyphs;
@property (nonatomic) NSString auxiliaryTopText;
@property (nonatomic) NSString auxiliaryMiddleText;
@property (nonatomic) NSString auxiliaryBottomText;
@property (nonatomic) NSInteger auxiliaryBottomTextColor;
@property (nonatomic) NSNumber auxiliaryAlignment;
@property (nonatomic) BOOL hideVerticalDivider;
@property (nonatomic) NSInteger titleAlign;
@property (nonatomic) NSNumber titleWeight;
@property (nonatomic) BOOL titleNoWrap;
@property (nonatomic) BOOL thumbnailCropCircle;
@property (nonatomic) SFImage imageOverlay;
@property (nonatomic) SFActionItem playAction;
@property (nonatomic) NSInteger playActionAlign;
@property (nonatomic) NSArray offers;
@property (nonatomic) NSString footnote;
@property (nonatomic) SFRichText richSubtitle;
@property (nonatomic) BOOL subtitleIsEmphasized;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) NSData jsonData;
@property (nonatomic) BOOL hideDivider;
@property (nonatomic) SFCard nextCard;
@property (nonatomic) NSArray commands;
@property (nonatomic) NSArray parameterKeyPaths;
@property (nonatomic) NSString cardSectionId;
@property (nonatomic) NSString resultIdentifier;
@property (nonatomic) SFUserReportRequest userReportRequest;
@property (nonatomic) SFCommand command;
@property (nonatomic) SFCommand previewCommand;
@property (nonatomic) NSArray previewButtonItems;
@property (nonatomic) NSString commandDetail;
@property (nonatomic) NSString cardSectionDetail;
@property (nonatomic) NSString previewButtonItemsTitle;
@property (nonatomic) NSArray embeddedCards;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setBackgroundColor:;
- (id)rating;
- (id)descriptionText;
- (id)initWithProtobuf:;
- (id)backgroundColor;
- (void)setType:;
- (id)offers;
- (void)setSubtitle:;
- (void)setTitle:;
- (id)initWithCoder:;
- (id)jsonData;
- (void)encodeWithCoder:;
- (id)type;
- (id)title;
- (void).cxx_destruct;
- (void)setDescriptionText:;
- (id)subtitle;
- (int)separatorStyle;
- (void)setOffers:;
- (id)dictionaryRepresentation;
- (void)setSeparatorStyle:;
- (id)copyWithZone:;
- (id)punchoutOptions;
- (id)reviewText;
- (void)setRating:;
- (void)setFootnote:;
- (id)footnote;
- (BOOL)isCentered;
- (void)setTitleImage:;
- (void)setTitleNoWrap:;
- (void)setHideVerticalDivider:;
- (void)setTitleWeight:;
- (void)setPunchoutOptions:;
- (void)setPunchoutPickerDismissText:;
- (void)setPunchoutPickerTitle:;
- (void)setCanBeHidden:;
- (void)setMoreGlyphs:;
- (void)setImageOverlay:;
- (void)setReviewGlyph:;
- (void)setRatingText:;
- (void)setReviewNewLine:;
- (void)setReviewText:;
- (void)setContentAdvisory:;
- (void)setPlayAction:;
- (void)setPlayActionAlign:;
- (void)setAuxiliaryAlignment:;
- (void)setThumbnailCropCircle:;
- (void)setHasTopPadding:;
- (void)setTitleAlign:;
- (void)setIsCentered:;
- (id)auxiliaryTopText;
- (void)setAuxiliaryTopText:;
- (id)auxiliaryMiddleText;
- (void)setAuxiliaryMiddleText:;
- (id)auxiliaryBottomText;
- (void)setAuxiliaryBottomText:;
- (int)auxiliaryBottomTextColor;
- (void)setAuxiliaryBottomTextColor:;
- (id)titleImage;
- (id)punchoutPickerTitle;
- (id)punchoutPickerDismissText;
- (BOOL)canBeHidden;
- (BOOL)hasTopPadding;
- (BOOL)hasBottomPadding;
- (void)setHasBottomPadding:;
- (BOOL)hasCanBeHidden;
- (BOOL)hasHasTopPadding;
- (BOOL)hasHasBottomPadding;
- (BOOL)hasSeparatorStyle;
- (BOOL)titleNoWrap;
- (id)titleWeight;
- (BOOL)hasTitleNoWrap;
- (id)contentAdvisory;
- (id)playAction;
- (id)reviewGlyph;
- (BOOL)hasIsCentered;
- (id)ratingText;
- (BOOL)reviewNewLine;
- (id)moreGlyphs;
- (id)auxiliaryAlignment;
- (BOOL)hideVerticalDivider;
- (int)titleAlign;
- (BOOL)thumbnailCropCircle;
- (id)imageOverlay;
- (int)playActionAlign;
- (id)richSubtitle;
- (void)setRichSubtitle:;
- (BOOL)subtitleIsEmphasized;
- (void)setSubtitleIsEmphasized:;
- (BOOL)hasReviewNewLine;
- (BOOL)hasAuxiliaryBottomTextColor;
- (BOOL)hasHideVerticalDivider;
- (BOOL)hasTitleAlign;
- (BOOL)hasThumbnailCropCircle;
- (BOOL)hasPlayActionAlign;
- (BOOL)hasSubtitleIsEmphasized;
+ (BOOL)supportsSecureCoding;
@end
