@interface SFScoreboardCardSection : SFTitleCardSection
@property (nonatomic) NSArray punchoutOptions;
@property (nonatomic) NSString punchoutPickerTitle;
@property (nonatomic) NSString punchoutPickerDismissText;
@property (nonatomic) BOOL canBeHidden;
@property (nonatomic) BOOL hasTopPadding;
@property (nonatomic) BOOL hasBottomPadding;
@property (nonatomic) NSString type;
@property (nonatomic) NSInteger separatorStyle;
@property (nonatomic) SFColor backgroundColor;
@property (nonatomic) NSString title;
@property (nonatomic) NSString subtitle;
@property (nonatomic) SFSportsTeam team1;
@property (nonatomic) SFSportsTeam team2;
@property (nonatomic) NSString accessibilityDescription;
@property (nonatomic) NSString eventStatus;
@property (nonatomic) NSDictionary dictionaryRepresentation;
@property (nonatomic) NSData jsonData;
@property (nonatomic) BOOL isCentered;
@property (nonatomic) BOOL hideDivider;
@property (nonatomic) SFCard nextCard;
@property (nonatomic) NSArray commands;
@property (nonatomic) NSArray parameterKeyPaths;
@property (nonatomic) NSString cardSectionId;
@property (nonatomic) NSString resultIdentifier;
@property (nonatomic) SFUserReportRequest userReportRequest;
@property (nonatomic) SFCommand command;
@property (nonatomic) SFCommand previewCommand;
@property (nonatomic) NSArray previewButtonItems;
@property (nonatomic) NSString commandDetail;
@property (nonatomic) NSString cardSectionDetail;
@property (nonatomic) NSString previewButtonItemsTitle;
@property (nonatomic) NSArray embeddedCards;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setBackgroundColor:;
- (id)initWithProtobuf:;
- (id)backgroundColor;
- (id)accessibilityDescription;
- (void)setType:;
- (void)setSubtitle:;
- (void)setTitle:;
- (id)initWithCoder:;
- (id)jsonData;
- (void)encodeWithCoder:;
- (id)type;
- (id)title;
- (void).cxx_destruct;
- (id)subtitle;
- (int)separatorStyle;
- (id)dictionaryRepresentation;
- (void)setSeparatorStyle:;
- (id)copyWithZone:;
- (id)punchoutOptions;
- (void)setAccessibilityDescription:;
- (void)setPunchoutOptions:;
- (void)setPunchoutPickerDismissText:;
- (void)setPunchoutPickerTitle:;
- (void)setEventStatus:;
- (void)setCanBeHidden:;
- (void)setTeam1:;
- (void)setTeam2:;
- (void)setHasTopPadding:;
- (id)punchoutPickerTitle;
- (id)punchoutPickerDismissText;
- (BOOL)canBeHidden;
- (BOOL)hasTopPadding;
- (BOOL)hasBottomPadding;
- (void)setHasBottomPadding:;
- (BOOL)hasCanBeHidden;
- (BOOL)hasHasTopPadding;
- (BOOL)hasHasBottomPadding;
- (BOOL)hasSeparatorStyle;
- (id)team1;
- (id)team2;
- (id)eventStatus;
+ (BOOL)supportsSecureCoding;
@end
