@interface SFSectionModel : NSObject
@property (nonatomic) Q effectiveItemIdentifiersCount;
@property (nonatomic) q itemType;
@property (nonatomic) SFBannerModel contentBanner;
@property (nonatomic) @? siteIconConfigurationProvider;
@property (nonatomic) @? siteCardConfigurationProvider;
@property (nonatomic) @? richLinkConfigurationProvider;
@property (nonatomic) @? siteRowConfigurationProvider;
@property (nonatomic) @ identifier;
@property (nonatomic) NSString title;
@property (nonatomic) NSArray actions;
@property (nonatomic) UIAction supplementaryAction;
@property (nonatomic) SFBannerModel banner;
@property (nonatomic) NSArray itemIdentifiers;
@property (nonatomic) q numberOfRowsVisibleWhenCollapsed;
@property (nonatomic) q numberOfRowsVisibleWhenCollapsedInCompactWidth;
@property (nonatomic) UIMenu titleMenu;
@property (nonatomic) BOOL usesLargeTitle;
@property (nonatomic) BOOL showsTopSeparator;
@property (nonatomic) BOOL expandsModally;
@property (nonatomic) @? contextMenuProvider;
@property (nonatomic) @? contextMenuCommitHandler;
@property (nonatomic) @? contextMenuDismissHandler;
@property (nonatomic) @? dragItemProvider;
@property (nonatomic) @? dropOperationProvider;
@property (nonatomic) @? dropHandler;
- (id)banner;
- (BOOL)showsTopSeparator;
- (id)itemIdentifiers;
- (id)contextMenuProvider;
- (void)setDropHandler:;
- (void)setNumberOfRowsVisibleWhenCollapsed:;
- (void)setContextMenuDismissHandler:;
- (id)identifier;
- (id)dropOperationProvider;
- (long long)numberOfRowsVisibleWhenCollapsedInCompactWidth;
- (void)setExpandsModally:;
- (void)setShowsTopSeparator:;
- (id)richLinkConfigurationProvider;
- (unsigned long long)hash;
- (id)contextMenuCommitHandler;
- (long long)itemType;
- (void)setUsesLargeTitle:;
- (id)initWithIdentifier:title:actions:banner:itemType:itemIdentifiers:configurationProvider:;
- (id)contentBanner;
- (void)setContextMenuProvider:;
- (id)supplementaryAction;
- (id)dropHandler;
- (id)dragItemProvider;
- (id)title;
- (void)setTitleMenu:;
- (id)actions;
- (id)siteRowConfigurationProvider;
- (BOOL)usesLargeTitle;
- (id)effectiveItemIdentifiersWithMaximumCount:;
- (void).cxx_destruct;
- (id)siteCardConfigurationProvider;
- (void)setDropOperationProvider:;
- (void)setDragItemProvider:;
- (id)description;
- (long long)numberOfRowsVisibleWhenCollapsed;
- (id)siteIconConfigurationProvider;
- (id)titleMenu;
- (void)setContextMenuCommitHandler:;
- (unsigned long long)effectiveItemIdentifiersCount;
- (void)setNumberOfRowsVisibleWhenCollapsedInCompactWidth:;
- (BOOL)isEqual:;
- (BOOL)expandsModally;
- (id)contextMenuDismissHandler;
+ (id)siteCardSectionWithIdentifier:title:actions:banner:identifiers:configurationProvider:;
+ (id)siteCardSectionWithIdentifier:actions:banner:identifiers:configurationProvider:;
+ (id)siteRowSectionWithIdentifier:title:actions:banner:identifiers:configurationProvider:;
+ (id)toggleExpandedAction;
+ (id)actionSectionWithIdentifier:actions:;
+ (id)siteIconSectionWithIdentifier:title:actions:banner:supplementaryAction:identifiers:configurationProvider:;
+ (id)footerSectionWithIdentifier:action:;
+ (id)bannerSectionWithIdentifier:title:banner:;
+ (id)siteRowSectionWithIdentifier:actions:banner:identifiers:configurationProvider:;
+ (id)separatorSectionWithIdentifier:;
+ (id)richLinkSectionWithIdentifier:title:actions:banner:identifiers:configurationProvider:;
+ (id)richLinkSectionWithIdentifier:actions:banner:identifiers:configurationProvider:;
+ (id)bannerSectionWithIdentifier:banner:;
+ (id)siteIconSectionWithIdentifier:actions:banner:supplementaryAction:identifiers:configurationProvider:;
+ (id)headingSectionWithIdentifier:title:;
@end
