@interface SFUnifiedBarItem : NSObject
@property (nonatomic) q activeAnimationCount;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL hidden;
@property (nonatomic) BOOL pinned;
@property (nonatomic) BOOL dragging;
@property (nonatomic) BOOL dropping;
@property (nonatomic) BOOL isPlaceholder;
@property (nonatomic) SFUnifiedBarItem secondaryItem;
@property (nonatomic) Q spacingOptions;
@property (nonatomic) SFUnifiedBarItemView view;
@property (nonatomic) SFUnifiedBarItemView reusableView;
@property (nonatomic) SFUnifiedBarItemView reusablePreviewView;
@property (nonatomic) NSString viewReuseIdentifier;
- (void)setPinned:;
- (BOOL)isPlaceholder;
- (BOOL)isDropping;
- (void)setIsPlaceholder:;
- (id)menuElementRepresentationWithSelectionHandler:;
- (id)view;
- (id)secondaryItem;
- (BOOL)isPinned;
- (void)setEnabled:;
- (void).cxx_destruct;
- (void)setHidden:;
- (BOOL)isDragging;
- (BOOL)isHidden;
- (BOOL)isEnabled;
- (void)setReusableView:;
- (void)configureItemView:isPreview:;
- (void)setActiveAnimationCount:;
- (unsigned long long)spacingOptions;
- (void)setSpacingOptions:;
- (id)reusableView;
- (id)reusablePreviewView;
- (void)setReusablePreviewView:;
- (id)viewReuseIdentifier;
- (void)setViewReuseIdentifier:;
- (long long)activeAnimationCount;
@end
