@interface SignpostSupportObjectExtractor : NSObject
@property (nonatomic) SignpostSupportSubsystemCategoryFilter metalSubsystemCategoryFilter;
@property (nonatomic) SignpostIntervalBuilder intervalBuilder;
@property (nonatomic) Q processedEventCount;
@property (nonatomic) BOOL buildAnimationCompositeIntervalTimelines;
@property (nonatomic) @? timedOutBeginEventProcessingBlock;
@property (nonatomic) BOOL _shouldStopProcessing;
@property (nonatomic) NSObject<OS_dispatch_semaphore> completionSemaphore;
@property (nonatomic) NSObject<OS_dispatch_semaphore> syncSem;
@property (nonatomic) NSUUID currentBootUUID;
@property (nonatomic) Q _notificationTimeout;
@property (nonatomic) NSObject<OS_dispatch_queue> notificationProcessingQueue;
@property (nonatomic) OSLogEventLiveStream _liveStream;
@property (nonatomic) @? _stopProcessingBlock;
@property (nonatomic) @? _intervalEndHandler;
@property (nonatomic) BOOL skipAnimationStateTrackingOptimization;
@property (nonatomic) SignpostSupportSubsystemCategoryFilter subsystemCategoryFilter;
@property (nonatomic) SignpostSupportExactProcessNameFilter processNameFilter;
@property (nonatomic) SignpostSupportPIDFilter pidFilter;
@property (nonatomic) SignpostSupportUniquePIDFilter uniquePidFilter;
@property (nonatomic) SignpostSupportObjectFilter objectFilter;
@property (nonatomic) BOOL includeMetalAnalysis;
@property (nonatomic) @? beginEventProcessingBlock;
@property (nonatomic) @? endEventProcessingBlock;
@property (nonatomic) @? repeatedBeginEventProcessingBlock;
@property (nonatomic) @? unmatchedEndEventProcessingBlock;
@property (nonatomic) @? emitEventProcessingBlock;
@property (nonatomic) @? intervalCompletionProcessingBlock;
@property (nonatomic) @? animationIntervalCompletionProcessingBlock;
@property (nonatomic) @? logMessageProcessingBlock;
@property (nonatomic) @? deviceRebootProcessingBlock;
@property (nonatomic) @? processingCompletionBlock;
@property (nonatomic) SignpostSupportAnimationGraceTimeController animationFirstFrameGraceTimeController;
- (id)init;
- (void)dealloc;
- (BOOL)buildAnimationCompositeIntervalTimelines;
- (void)setBuildAnimationCompositeIntervalTimelines:;
- (void).cxx_destruct;
- (void)setSubsystemCategoryFilter:;
- (void)setIntervalCompletionProcessingBlock:;
- (void)setBeginEventProcessingBlock:;
- (void)setEndEventProcessingBlock:;
- (BOOL)processSerializedObjectsFromData:errorOut:;
- (void)finishProcessingSerializedData;
- (BOOL)processSerializedObjectsFromSignpostFile:errorOut:;
- (BOOL)_hasProcessingBlock;
- (BOOL)_hasSignpostProcessingBlock;
- (BOOL)_isTrackingIntervals;
- (BOOL)_hasNonObjectFilters;
- (BOOL)_eventPassesWithPid:uniquePid:processName:subsystem:category:;
- (BOOL)_eventPassesFilters:;
- (BOOL)_shouldProcessEvent:shouldReport:;
- (BOOL)_shouldBuildEventWithPid:uniquePid:processName:subsystem:category:shouldReport:;
- (BOOL)_generateIntervalFromEnd:shouldReport:;
- (BOOL)_processSignpostSupportLogMessage:;
- (BOOL)_processSignpostEvent:shouldReport:;
- (void)stopProcessing;
- (void)_processingCompleted:;
- (id)_loggingSupportStreamPredicateFromFiltersWithForLiveStreaming:;
- (id)subsystemCategoryFilter;
- (id)processNameFilter;
- (void)setProcessNameFilter:;
- (id)pidFilter;
- (void)setPidFilter:;
- (id)uniquePidFilter;
- (void)setUniquePidFilter:;
- (id)objectFilter;
- (void)setObjectFilter:;
- (BOOL)includeMetalAnalysis;
- (void)setIncludeMetalAnalysis:;
- (id)beginEventProcessingBlock;
- (id)endEventProcessingBlock;
- (id)repeatedBeginEventProcessingBlock;
- (void)setRepeatedBeginEventProcessingBlock:;
- (id)unmatchedEndEventProcessingBlock;
- (void)setUnmatchedEndEventProcessingBlock:;
- (id)emitEventProcessingBlock;
- (void)setEmitEventProcessingBlock:;
- (id)intervalCompletionProcessingBlock;
- (id)animationIntervalCompletionProcessingBlock;
- (void)setAnimationIntervalCompletionProcessingBlock:;
- (id)logMessageProcessingBlock;
- (void)setLogMessageProcessingBlock:;
- (id)deviceRebootProcessingBlock;
- (void)setDeviceRebootProcessingBlock:;
- (id)processingCompletionBlock;
- (void)setProcessingCompletionBlock:;
- (id)animationFirstFrameGraceTimeController;
- (id)metalSubsystemCategoryFilter;
- (void)setMetalSubsystemCategoryFilter:;
- (id)intervalBuilder;
- (unsigned long long)processedEventCount;
- (void)setProcessedEventCount:;
- (id)timedOutBeginEventProcessingBlock;
- (void)setTimedOutBeginEventProcessingBlock:;
- (BOOL)_shouldStopProcessing;
- (void)set_shouldStopProcessing:;
- (id)completionSemaphore;
- (id)syncSem;
- (id)currentBootUUID;
- (void)setCurrentBootUUID:;
- (unsigned long long)_notificationTimeout;
- (void)set_notificationTimeout:;
- (id)notificationProcessingQueue;
- (void)setNotificationProcessingQueue:;
- (id)_liveStream;
- (void)set_liveStream:;
- (id)_stopProcessingBlock;
- (void)set_stopProcessingBlock:;
- (id)_intervalEndHandler;
- (void)set_intervalEndHandler:;
- (BOOL)skipAnimationStateTrackingOptimization;
- (void)setSkipAnimationStateTrackingOptimization:;
@end
