@interface SISchemaVoiceTriggerMetrics : SISchemaInstrumentationMessage
@property (nonatomic) NSInteger implicitUtterances;
@property (nonatomic) BOOL hasImplicitUtterances;
@property (nonatomic) NSInteger explicitUtterances;
@property (nonatomic) BOOL hasExplicitUtterances;
@property (nonatomic) NSInteger firstPassTriggers;
@property (nonatomic) BOOL hasFirstPassTriggers;
@property (nonatomic) NSArray firstPassStatistics;
@property (nonatomic) MHSchemaMHVoiceTriggerFirstPassDailyMetadata firstPassMetadata;
@property (nonatomic) BOOL hasFirstPassMetadata;
@property (nonatomic) NSData jsonData;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (void)setImplicitUtterances:;
- (BOOL)hasImplicitUtterances;
- (void)setHasImplicitUtterances:;
- (void)deleteImplicitUtterances;
- (void)setExplicitUtterances:;
- (BOOL)hasExplicitUtterances;
- (void)setHasExplicitUtterances:;
- (void)deleteExplicitUtterances;
- (void)setFirstPassTriggers:;
- (BOOL)hasFirstPassTriggers;
- (void)setHasFirstPassTriggers:;
- (void)deleteFirstPassTriggers;
- (void)clearFirstPassStatistics;
- (void)deleteFirstPassStatistics;
- (void)addFirstPassStatistics:;
- (unsigned long long)firstPassStatisticsCount;
- (id)firstPassStatisticsAtIndex:;
- (BOOL)hasFirstPassMetadata;
- (void)deleteFirstPassMetadata;
- (int)implicitUtterances;
- (int)explicitUtterances;
- (int)firstPassTriggers;
- (id)firstPassStatistics;
- (void)setFirstPassStatistics:;
- (id)firstPassMetadata;
- (void)setFirstPassMetadata:;
- (void)setHasFirstPassMetadata:;
@end
