@interface SKClientBroker : NSObject
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)init;
- (void)_checkStorefrontChangedNotify:;
- (void)dealloc;
- (void)registerMessageListener:;
- (void)downloadAdded:;
- (void)handleEngagementRequest:resultHandler:;
- (void)receivedTransactions:;
- (void)handleAuthenticateRequest:resultHandler:;
- (void)removedEntitlementsForProductIdentifiers:;
- (void)_handleUnfinishedTransactionsNotification;
- (void)downloadStatusChanged:;
- (BOOL)hasTransactionListener;
- (void)unregisterClientWithIdentifier:;
- (void)registerSubscriptionStatusListener:;
- (void)_storefrontObserverAdded;
- (void)unregisterStorefrontListener:;
- (void)receivedStatuses:;
- (void)hasAnyMessageListenersWithReply:;
- (void)storefrontChanged:;
- (void)_storefrontObserverRemoved;
- (void)registerTransactionListener:;
- (void)removedTransactions:;
- (void).cxx_destruct;
- (void)registerStorefrontListener:;
- (void)downloadRemoved:;
- (void)registerClient:withIdentifier:;
- (void)unregisterSubscriptionStatusListener:;
- (void)unregisterMessageListener:;
- (void)unregisterTransactionListener:;
- (void)handleDialogRequest:resultHandler:;
- (void)askToShowMessageWithReplyBlock:;
- (void)updatedTransactions:;
- (id)_unfinishedTransactionsNotificationName;
- (void)pendingMessages:;
- (void)_cancelNotifyTokenIfValid:;
+ (id)defaultBroker;
@end
