@interface SKEngagementRemoteViewTask : NSObject
@property (nonatomic) NSObject<OS_dispatch_group> dispatchGroup;
@property (nonatomic) NSError error;
@property (nonatomic) SKRemoteEngagementPresenterViewController remoteViewController;
@property (nonatomic) NSData requestData;
@property (nonatomic) NSData resultData;
@property (nonatomic) NSDictionary result;
@property (nonatomic) UIViewController viewController;
@property (nonatomic) NSObject<OS_dispatch_queue> workQueue;
@property (nonatomic) UIWindowScene scene;
@property (nonatomic) NSString clientBundleID;
@property (nonatomic) @? completion;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)completion;
- (id)result;
- (id)remoteViewController;
- (void)setCompletion:;
- (void)setScene:;
- (void)setViewController:;
- (id)requestData;
- (id)workQueue;
- (void)setError:;
- (void)_presentViewController:;
- (id)error;
- (id)resultData;
- (void)setClientBundleID:;
- (id)scene;
- (id)clientBundleID;
- (void)setDispatchGroup:;
- (id)viewController;
- (void).cxx_destruct;
- (void)setRemoteViewController:;
- (id)dispatchGroup;
- (void)setRequestData:;
- (void)setResult:;
- (void)presentEngagement;
- (void)setResultData:;
- (void)engagementTaskDidFinishWithResult:resultData:error:completion:;
- (void)preferredContentSizeDidChange:;
- (id)initWithRequestData:presentingViewController:windowScene:;
- (void)_unblock;
@end
