@interface SSPaymentSheet : NSObject
@property (nonatomic) NSString accountHeader;
@property (nonatomic) NSString accountName;
@property (nonatomic) NSArray attributedList;
@property (nonatomic) NSString buyParams;
@property (nonatomic) q confirmationTitleType;
@property (nonatomic) NSString countryCode;
@property (nonatomic) NSString currencyCode;
@property (nonatomic) NSNumber designVersion;
@property (nonatomic) NSString dialogId;
@property (nonatomic) NSString displayPrice;
@property (nonatomic) NSAttributedString displayPriceLabel;
@property (nonatomic) NSString explanation;
@property (nonatomic) NSArray flexList;
@property (nonatomic) NSArray inlineImages;
@property (nonatomic) BOOL applePayClassic;
@property (nonatomic) NSDictionary merchantSession;
@property (nonatomic) NSString message;
@property (nonatomic) q payeeType;
@property (nonatomic) NSString paymentSummary;
@property (nonatomic) NSString presentingSceneIdentifier;
@property (nonatomic) NSNumber price;
@property (nonatomic) NSArray priceSectionItems;
@property (nonatomic) NSString ratingHeader;
@property (nonatomic) NSString ratingValue;
@property (nonatomic) q salableIconType;
@property (nonatomic) NSURL salableIconURL;
@property (nonatomic) NSString salableIconURLString;
@property (nonatomic) NSArray salableInfo;
@property (nonatomic) NSAttributedString salableInfoLabel;
@property (nonatomic) BOOL shouldShowCardPicker;
@property (nonatomic) BOOL shouldSuppressPrice;
@property (nonatomic) BOOL shouldUppercaseText;
@property (nonatomic) NSString storeName;
@property (nonatomic) NSArray styles;
@property (nonatomic) NSString title;
@property (nonatomic) q titleType;
- (void)_lock;
- (void)_unlock;
- (id)initWithXPCEncoding:;
- (id)explanation;
- (long long)titleType;
- (void)setCountryCode:;
- (id)styles;
- (id)countryCode;
- (id)init;
- (id)copyXPCEncoding;
- (void)setMessage:;
- (void)setTitle:;
- (void)setAccountName:;
- (id)dialogId;
- (id)presentingSceneIdentifier;
- (id)currencyCode;
- (id)storeName;
- (id)title;
- (void)setPresentingSceneIdentifier:;
- (id)message;
- (void)setStoreName:;
- (void).cxx_destruct;
- (void)setExplanation:;
- (void)setApplePayClassic:;
- (void)_init;
- (id)price;
- (void)setTitleType:;
- (void)setDialogId:;
- (id)accountName;
- (id)initWithServerResponse:;
- (id)copyWithZone:;
- (void)setStyles:;
- (void)setCurrencyCode:;
- (void)setPrice:;
- (id)_greyAttributedStringForAttributedString:range:;
- (id)buyParams;
- (id)accountHeader;
- (void)setAccountHeader:;
- (BOOL)isApplePayClassic;
- (id)attributedList;
- (id)designVersion;
- (void)setDesignVersion:;
- (id)displayPrice;
- (void)setDisplayPrice:;
- (id)flexList;
- (id)inlineImages;
- (id)merchantSession;
- (void)setMerchantSession:;
- (id)paymentSummary;
- (void)setPaymentSummary:;
- (id)priceSectionItems;
- (void)setPriceSectionItems:;
- (id)ratingHeader;
- (void)setRatingHeader:;
- (id)ratingValue;
- (void)setRatingValue:;
- (id)salableIconURL;
- (id)salableInfo;
- (void)setSalableInfo:;
- (id)salableInfoLabel;
- (BOOL)shouldUppercaseText;
- (void)setShouldUppercaseText:;
- (id)_replaceBreakingSpaceMarkupForMutableAttributedString:;
- (id)_replaceMarkupForMutableAttributedString:markupType:;
- (id)defaultAuthKitAuthenticationContext;
- (id)authKitAuthenticationContextForAccount:;
- (id)initWithServerResponse:buyParams:;
- (id)displayPriceLabel;
- (id)salableIconURLString;
- (void)setSalableIconURLString:;
- (id)_attributedStringForAttributedArray:;
- (id)_attributedStringForAttributedDictionary:;
- (id)_attributedStringForSalableInfoStringArray:;
- (id)_attributedStringForString:;
- (id)_attributedStringForStringArray:useGrey:;
- (long long)_confirmationTitleTypeForStringValue:;
- (id)_displayPriceLabelForDisplayPrice:;
- (long long)_inferSalableIconTypeWithBuyParams:;
- (void)_parseResponse:;
- (id)_attributedListForFlexList:;
- (long long)_payeeTypeForRequestorValue:;
- (long long)_payeeTypeInferredFromEnumeratedTitle;
- (long long)_salableIconTypeForString:;
- (void)_salableInfoItemsToUppercase;
- (void)_stringValuesToUppercase;
- (BOOL)shouldShowCardPicker;
- (void)setShouldShowCardPicker:;
- (long long)confirmationTitleType;
- (void)setConfirmationTitleType:;
- (long long)payeeType;
- (void)setPayeeType:;
- (long long)salableIconType;
- (void)setSalableIconType:;
- (BOOL)shouldSuppressPrice;
- (void)setShouldSuppressPrice:;
+ (id)_styleDictionaryWithName:styles:;
+ (id)_attributedStringWithString:styles:;
+ (id)stringWithFormattedUsernameForString:username:;
@end
