@interface SSPromise : NSObject
@property (nonatomic) SSPromiseCompletionBlocks completionBlocks;
@property (nonatomic) SSPromiseResult promiseResult;
@property (nonatomic) NSConditionLock stateLock;
@property (nonatomic) BOOL cancelled;
@property (nonatomic) BOOL finished;
- (id)errorOnlyCompletionHandlerAdapter;
- (id)completionHandlerAdapter;
- (id)completionBlocks;
- (id)init;
- (id)boolCompletionHandlerAdapter;
- (BOOL)cancel;
- (id)stateLock;
- (void)_addBlock:orCallWithResult:;
- (BOOL)isCancelled;
- (id)resultWithError:;
- (BOOL)_isFinished;
- (BOOL)finishWithResult:;
- (void)setCompletionBlocks:;
- (void)setStateLock:;
- (void)addFinishBlock:;
- (BOOL)isFinished;
- (void)waitUntilFinished;
- (id)catchWithBlock:;
- (void)addSuccessBlock:;
- (void).cxx_destruct;
- (BOOL)finishWithError:;
- (void)setPromiseResult:;
- (id)thenWithBlock:;
- (id)promiseResult;
- (id)resultBeforeDate:error:;
- (id)resultWithTimeout:error:;
- (void)waitUntilFinishedWithTimeout:;
- (BOOL)finishWithResult:error:;
- (void)addErrorBlock:;
- (id)nilValueCompletionHandlerAdapter;
+ (void)_configureAnyPromise:withPomises:currentPromiseIndex:;
+ (id)_globalPromiseStorageAccessQueue;
+ (id)_globalPromiseStorage;
+ (id)promiseWithResult:;
+ (void)_configureAllPromise:withResults:promises:currentPromiseIndex:;
+ (id)promiseWithError:;
+ (BOOL)_errorIsCanceledError:;
+ (void)_finishPromise:withPromise:;
+ (id)promiseWithAll:;
+ (id)promiseWithAny:;
@end
