@interface SSPurchaseRequest : SSRequest
@property (nonatomic) BOOL createsDownloads;
@property (nonatomic) BOOL createsJobs;
@property (nonatomic) BOOL playbackRequest;
@property (nonatomic) BOOL shouldValidatePurchases;
@property (nonatomic) <SSPurchaseRequestDelegate> delegate;
@property (nonatomic) NSArray purchases;
@property (nonatomic) BOOL backgroundRequest;
@property (nonatomic) BOOL needsAuthentication;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)needsAuthentication;
- (id)initWithXPCEncoding:;
- (id)init;
- (void)cancel;
- (void)dealloc;
- (id)copyXPCEncoding;
- (BOOL)start;
- (void)startWithCompletionBlock:;
- (void)setNeedsAuthentication:;
- (void)purchaseManager:didFinishPurchasesWithResponses:;
- (id)purchases;
- (BOOL)createsJobs;
- (void)setCreatesJobs:;
- (id)initWithPurchases:;
- (BOOL)isPlaybackRequest;
- (void)setPlaybackRequest:;
- (void)startWithPurchaseBlock:completionBlock:;
- (void)startWithPurchaseResponseBlock:completionBlock:;
- (void)_addPurchasesToManager;
- (void)_finishPurchasesWithResponses:;
- (id)_purchaseForUniqueIdentifier:;
- (BOOL)isBackgroundRequest;
- (void)setBackgroundRequest:;
- (BOOL)createsDownloads;
- (void)setCreatesDownloads:;
- (BOOL)shouldValidatePurchases;
- (void)setShouldValidatePurchases:;
@end
