@interface SSVPBPlayActivityEnqueuerProperties : PBCodable
@property (nonatomic) BOOL hasBuildVersion;
@property (nonatomic) NSString buildVersion;
@property (nonatomic) BOOL hasDeviceGUID;
@property (nonatomic) NSString deviceGUID;
@property (nonatomic) BOOL hasDeviceName;
@property (nonatomic) NSString deviceName;
@property (nonatomic) BOOL hasTimeZoneName;
@property (nonatomic) NSString timeZoneName;
@property (nonatomic) BOOL hasSystemReleaseType;
@property (nonatomic) NSInteger systemReleaseType;
@property (nonatomic) BOOL hasSBEnabled;
@property (nonatomic) BOOL sBEnabled;
@property (nonatomic) BOOL hasStoreAccountID;
@property (nonatomic) Q storeAccountID;
@property (nonatomic) BOOL hasStoreFrontID;
@property (nonatomic) NSString storeFrontID;
@property (nonatomic) BOOL hasPrivateListeningEnabled;
@property (nonatomic) BOOL privateListeningEnabled;
- (void)setBuildVersion:;
- (id)buildVersion;
- (void)setDeviceName:;
- (id)deviceName;
- (void)writeTo:;
- (BOOL)privateListeningEnabled;
- (id)deviceGUID;
- (unsigned long long)hash;
- (void)copyTo:;
- (void)mergeFrom:;
- (void)setPrivateListeningEnabled:;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (int)systemReleaseType;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)hasTimeZoneName;
- (id)timeZoneName;
- (void)setTimeZoneName:;
- (BOOL)hasDeviceName;
- (id)storeFrontID;
- (unsigned long long)storeAccountID;
- (void)setStoreAccountID:;
- (BOOL)hasBuildVersion;
- (void)setDeviceGUID:;
- (void)setSBEnabled:;
- (void)setStoreFrontID:;
- (void)setSystemReleaseType:;
- (BOOL)hasDeviceGUID;
- (void)setHasSystemReleaseType:;
- (BOOL)hasSystemReleaseType;
- (id)systemReleaseTypeAsString:;
- (int)StringAsSystemReleaseType:;
- (void)setHasSBEnabled:;
- (BOOL)hasSBEnabled;
- (void)setHasStoreAccountID:;
- (BOOL)hasStoreAccountID;
- (BOOL)hasStoreFrontID;
- (void)setHasPrivateListeningEnabled:;
- (BOOL)hasPrivateListeningEnabled;
- (BOOL)sBEnabled;
@end
