@interface STCoreUsersController : NSObject
@property (nonatomic) NSManagedObjectContext managedObjectContext;
@property (nonatomic) NSFetchedResultsController localUserController;
@property (nonatomic) NSFetchedResultsController childUserController;
@property (nonatomic) NSFetchedResultsController settingsController;
@property (nonatomic) STCoreUser selectedUser;
@property (nonatomic) NSArray users;
@property (nonatomic) STCoreUser localUser;
@property (nonatomic) Q selectedIndex;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)users;
- (id)managedObjectContext;
- (void)refresh;
- (unsigned long long)selectedIndex;
- (void)controllerWillChangeContent:;
- (void).cxx_destruct;
- (id)initWithManagedObjectContext:;
- (void)controllerDidChangeContent:;
- (void)setSelectedIndex:;
- (void)setUsers:;
- (id)settingsController;
- (void)setSettingsController:;
- (id)localUser;
- (id)localUserController;
- (id)childUserController;
- (id)selectedUser;
- (BOOL)updateSelectedIndexForDSID:;
- (BOOL)updateSelectedIndexForChildDSID:;
- (BOOL)_updateSelectedIndexForDSID:isManaged:;
- (void)notifyServerOfScreenTimeEnabled:forUser:;
- (void)setLocalUserController:;
- (void)setChildUserController:;
- (void)setSelectedUser:;
+ (id)keyPathsForValuesAffectingLocalUser;
+ (id)keyPathsForValuesAffectingUsers;
+ (id)keyPathsForValuesAffectingSelectedUser;
@end
