@interface STTelephonyStatusDomainData : NSObject
@property (nonatomic) STTelephonyStatusDomainSIMInfo SIMOneInfo;
@property (nonatomic) STTelephonyStatusDomainSIMInfo SIMTwoInfo;
@property (nonatomic) BOOL cellularRadioCapabilityEnabled;
@property (nonatomic) BOOL dualSIMEnabled;
@property (nonatomic) BOOL radioModuleDead;
@property (nonatomic) BOOL usingStewieForSOS;
@property (nonatomic) BOOL inactiveSOSEnabled;
@property (nonatomic) STTelephonyStatusDomainSIMInfo primarySIMInfo;
@property (nonatomic) STTelephonyStatusDomainSIMInfo secondarySIMInfo;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)init;
- (BOOL)isUsingStewieForSOS;
- (id)primarySIMInfo;
- (id)dataByApplyingDiff:;
- (id)succinctDescriptionBuilder;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (id)SIMOneInfo;
- (id)diffFromData:;
- (void)encodeWithCoder:;
- (BOOL)isInactiveSOSEnabled;
- (id)SIMTwoInfo;
- (BOOL)isCellularRadioCapabilityEnabled;
- (void).cxx_destruct;
- (BOOL)isRadioModuleDead;
- (id)succinctDescription;
- (id)description;
- (id)secondarySIMInfo;
- (id)mutableCopyWithZone:;
- (id)descriptionBuilderWithMultilinePrefix:;
- (BOOL)isEqual:;
- (id)descriptionWithMultilinePrefix:;
- (BOOL)isDualSIMEnabled;
- (id)copyWithZone:;
+ (BOOL)supportsSecureCoding;
@end
