@interface TLKGridLayoutManager : NSObject
@property (nonatomic) NSDictionary itemsForIndex;
@property (nonatomic) NSArray itemsForRows;
@property (nonatomic) NSMapTable itemToRowMapping;
@property (nonatomic) NUIGridArrangement gridArrangement;
@property (nonatomic) {CGSize=dd} cachedFittingSize;
@property (nonatomic) {CGSize=dd} cachedGridSize;
@property (nonatomic) q indexForFirstTrailingColumn;
@property (nonatomic) q totalEqualColumns;
@property (nonatomic) NSArray spacings;
@property (nonatomic) double widthOfEqualFillColumns;
@property (nonatomic) NSArray alignments;
@property (nonatomic) NSArray verticalRowAlignments;
@property (nonatomic) BOOL tableContainsRowHeaders;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (long long)numberOfColumns;
- (void).cxx_destruct;
- (id)description;
- (long long)effectiveUserInterfaceLayoutDirection;
- (id)alignments;
- (void)setAlignments:;
- (long long)numberOfItemsInGridArrangement:;
- (id)gridArrangement:itemAtIndex:columns:rows:horizontalAlignment:verticalAlignment:;
- (id)contentLayoutSizeFittingSize:forArrangedSubview:;
- (id)layoutFrameForArrangedSubview:withProposedContentFrame:;
- (double)gridArrangement:widthOfColumnAtIndex:spacingAfter:;
- (id)initWithWithAlignments:rows:;
- (id)sizeForFittingSize:forRow:;
- (void)placeViewsForSize:forRow:completion:;
- (id)addItemsToDictionary:forSection:row:truncationPriorities:;
- (id)spacingsForAlignments:firstValidDataRow:;
- (BOOL)allEqualColumns;
- (double)trailingSectionSpacingBasedOnTotalViewsInSection:;
- (BOOL)hasManyTrailingColumns;
- (id)itemsForIndex;
- (void)setItemsForIndex:;
- (id)itemsForRows;
- (void)setItemsForRows:;
- (id)itemToRowMapping;
- (void)setItemToRowMapping:;
- (id)gridArrangement;
- (void)setGridArrangement:;
- (id)cachedFittingSize;
- (void)setCachedFittingSize:;
- (id)cachedGridSize;
- (void)setCachedGridSize:;
- (long long)indexForFirstTrailingColumn;
- (void)setIndexForFirstTrailingColumn:;
- (long long)totalEqualColumns;
- (void)setTotalEqualColumns:;
- (id)spacings;
- (void)setSpacings:;
- (double)widthOfEqualFillColumns;
- (void)setWidthOfEqualFillColumns:;
- (id)verticalRowAlignments;
- (void)setVerticalRowAlignments:;
- (BOOL)tableContainsRowHeaders;
- (void)setTableContainsRowHeaders:;
+ (id)font;
+ (id)gridManagerWithAlignments:rows:;
+ (id)verticalAlignmentsForItems:;
+ (id)arrayOfItemsForSection:;
+ (double)leadingSectionSpacingForView:view2:index:alignmentSchema:allEqual:;
+ (id)computeTruncationForAlignments:indexForFirstTrailingColumn:totalEqualColumns:;
@end
