@interface TRIClient : NSObject
@property (nonatomic) TRITrackingId trackingId;
@property (nonatomic) TRILogger logger;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)logger;
- (id)trackingId;
- (void)refresh;
- (id)initWithClientIdentifier:paths:unit:staleFactorsUsageGracePeriod:logger:;
- (BOOL)registerNamespaceName:compatibilityVersion:defaultsFileURL:applicationGroup:cloudKitContainerId:error:;
- (void)_registerUpdateHandlerForNamespaceName:notificationCallback:clientMethodNameForLogging:callingFunctionReturnAddressForLogging:;
- (void)dealloc;
- (id)addUpdateHandlerForNamespaceName:usingBlock:;
- (BOOL)deregisterNamespaceName:error:;
- (id)purgeabilityLevelsForFactorsWithNamespaceName:;
- (void)_lazyInit;
- (void)dispose;
- (id)experimentIdWithNamespace:;
- (id)treatmentIdWithNamespaceName:;
- (void)removeLevelsForFactorsImmediately:withNamespace:queue:completion:;
- (id)rolloutIdWithNamespaceName:;
- (id)experimentIdWithNamespaceName:;
- (id)experimentIdentifiersWithNamespaceName:;
- (id)newTrackingId;
- (void)setLogger:;
- (void)_invalidateFactors;
- (void)_checkEntitlements;
- (void)_setupExcessiveStaleFactorsUsageTimerWithGuardedData:namespace:clientMethodNameForLogging:callingFunctionReturnAddressForLogging:;
- (void)downloadNamespaceWithName:options:completion:;
- (BOOL)setFactorsProvisionalForNamespace:error:;
- (id)addUpdateHandlerForNamespaceId:queue:usingBlock:;
- (id)initWithNonLoggingClientIdentifier:paths:;
- (id)initWithClientIdentifier:paths:unit:factorsState:staleFactorsUsageGracePeriod:logger:;
- (void)downloadNamespaceWithName:options:progress:completion:;
- (id)_refresh:;
- (unsigned int)compatibilityVersionWithNamespaceName:;
- (id)rolloutIdentifiersWithNamespaceName:;
- (id)sizesForFactors:withNamespaceName:forMetric:error:;
- (id)newTrackingIdWithTreatmentRefresh:;
- (id)levelForFactor:withNamespaceName:;
- (BOOL)immediateDownloadForNamespaceNames:allowExpensiveNetworking:error:;
- (id)treatmentIdWithNamespace:;
- (BOOL)trialIdentifiersWithNamespaceName:experimentId:deploymentId:treatmentId:;
- (id)addUpdateHandlerForNamespaceId:usingBlock:;
- (void).cxx_destruct;
- (BOOL)hasDownloadedNamespaceWithName:;
- (id)addUpdateHandlerForNamespaceName:queue:usingBlock:;
- (id)factorLevelsWithNamespace:;
- (void)removeDownloadStatusHandlersWithToken:;
- (void)removeUpdateHandlerForToken:;
- (BOOL)promoteFactorsForNamespace:error:;
- (BOOL)setPurgeabilityLevelsForFactors:withNamespaceName:;
- (id)levelForFactor:withNamespace:;
- (BOOL)_hasAppropriatePermissionsForNamespaceName:;
- (long long)_appContainerType:;
- (unsigned long long)statusOfDownloadForFactors:withNamespace:token:queue:progress:completion:;
- (id)_rampIdForRolloutDeployment:;
- (void)downloadLevelsForFactors:withNamespace:queue:options:progress:completion:;
- (void)removeLevelsForFactors:withNamespace:queue:completion:;
- (BOOL)hasRegisteredNamespaceWithName:;
- (id)factorLevelsWithNamespaceName:;
+ (BOOL)isPlatformBinary;
+ (id)printedRolloutInformation:;
+ (id)clientWithProjectId:factorsState:;
+ (id)clientWithIdentifier:;
+ (id)printedExperimentInformation:;
+ (id)printedNCVInformation;
+ (BOOL)requiresLogging;
+ (id)activeExperimentInformation:;
+ (id)sysdiagnoseInfoWithError:;
+ (id)activeRolloutInformation:;
+ (BOOL)requiresTrialDataVaultAccess;
+ (id)clientWithIdentifier:unit:;
@end
