@interface TRINamespaceDescriptor : NSObject
@property (nonatomic) NSString namespaceName;
@property (nonatomic) I downloadNCV;
@property (nonatomic) NSURL factorsURL;
@property (nonatomic) TRIAppContainer appContainer;
@property (nonatomic) NSSet upgradeNCVs;
@property (nonatomic) NSInteger cloudKitContainerId;
@property (nonatomic) NSString resourceAttributionIdentifier;
@property (nonatomic) BOOL expensiveNetworkingAllowed;
@property (nonatomic) BOOL enableFetchDuringSetupAssistant;
@property (nonatomic) NSInteger purgeabilityLevel;
- (id)dictionary;
- (id)namespaceName;
- (id)upgradeNCVs;
- (BOOL)_upgradeNCVsArePositiveIntegers:;
- (BOOL)expensiveNetworkingAllowed;
- (id)initWithDictionary:;
- (BOOL)_upgradeNCVsIsValid:;
- (unsigned long long)hash;
- (BOOL)removeFromDirectory:;
- (BOOL)enableFetchDuringSetupAssistant;
- (BOOL)saveToDirectory:;
- (unsigned int)downloadNCV;
- (id)factorsAbsolutePathAsOwner:;
- (BOOL)writeToFile:;
- (int)purgeabilityLevel;
- (id)initWithNamespaceName:downloadNCV:optionalParams:;
- (id)factorsURL;
- (int)cloudKitContainerId;
- (void).cxx_destruct;
- (id)resourceAttributionIdentifier;
- (id)appContainer;
- (BOOL)_isEqualToNamespaceDescriptor:;
- (BOOL)isEqual:;
+ (id)loadWithNamespaceName:fromDirectory:;
+ (id)descriptorPathForNamespaceName:fromDirectory:;
+ (void)enumerateDescriptorsInDirectory:block:;
+ (BOOL)removeDescriptorWithNamespaceName:fromDirectory:;
+ (id)loadFromFile:;
+ (id)descriptorsForDirectory:filterBlock:;
@end
