@interface TTAccountUserAuditEntity : TTAccountBaseEntity
@property (nonatomic) NSString name;
@property (nonatomic) NSString userDescription;
@property (nonatomic) NSString avatarURL;
@property (nonatomic) NSString backgroundURL;
@property (nonatomic) NSNumber gender;
@property (nonatomic) NSString birthday;
@property (nonatomic) NSString industry;
@property (nonatomic) NSString area;
@property (nonatomic) NSDictionary bgInfo;
@property (nonatomic) NSDictionary live_info;
@property (nonatomic) NSDictionary pgc_edit_info;
@property (nonatomic) NSDictionary common_edit_info;
@property (nonatomic) NSDictionary rp_edit_info;
@property (nonatomic) TTAccountEditUserProfilePendantInfo pendantInfo;
- (void)setPendantInfo:;
- (id)avatarURL;
- (id)backgroundURL;
- (id)bgInfo;
- (id)common_edit_info;
- (id)industry;
- (id)initWithAuditModel:;
- (id)live_info;
- (id)pendantInfo;
- (id)pgc_edit_info;
- (id)rp_edit_info;
- (void)setAvatarURL:;
- (void)setBackgroundURL:;
- (void)setBgInfo:;
- (void)setCommon_edit_info:;
- (void)setIndustry:;
- (void)setLive_info:;
- (void)setPgc_edit_info:;
- (void)setRp_edit_info:;
- (void)setBirthday:;
- (void)setName:;
- (id)gender;
- (id)birthday;
- (void)setGender:;
- (id)initWithDictionary:;
- (void).cxx_destruct;
- (id)name;
- (id)area;
- (void)setArea:;
- (id)userDescription;
- (void)setUserDescription:;
@end
