@interface TTAccountAuthDouYin : NSObject
@property (nonatomic) BOOL isWaitingDouYinCallback;
@property (nonatomic) NSString appId;
@property (nonatomic) NSString scope;
@property (nonatomic) NSDictionary customUserInfo;
@property (nonatomic) NSString code;
@property (nonatomic) @? willLoginHandler;
@property (nonatomic) @? loginCompletedHandler;
@property (nonatomic) TTAccountAuthRequest authRequest;
@property (nonatomic) NSError hostMobileOneAuthTicketError;
@property (nonatomic) BOOL newPlatform;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)setNewPlatform:;
- (void)__laziedRegisterSDKIfNeeded__;
- (void)authorizeDidFinishWithErrCode:error:code:state:;
- (void)authorizeInCustomWebView:withCustomUserInfo:;
- (id)customUserInfo;
- (void)customWapAuthorize;
- (BOOL)handleOpenURL:sourceApplication:annotation:;
- (id)hostMobileOneAuthTicketError;
- (BOOL)isNewPlatform;
- (BOOL)isWaitingDouYinCallback;
- (id)loginCompletedHandler;
- (void)loginDidFinishWithUser:error:response:;
- (void)registerApp:;
- (void)requestAuthInfoByCustomWebView:completion:;
- (void)requestAuthWithRequest:willLogin:completion:;
- (void)requestLoginByCustomWebView:completion:;
- (void)requestLoginByCustomWebView:requestAuthReason:willLogin:completion:;
- (void)requestLoginByCustomWebView:willLogin:completion:;
- (void)requestLoginCallbackWithAuthResponse:;
- (void)requestLoginOnlyWithwillLogin:completion:;
- (void)requestLogout:;
- (void)sdkAuthorize;
- (void)sdkAuthorizeWithTicket:maskMobile:;
- (void)setCustomUserInfo:;
- (void)setHostMobileOneAuthTicketError:;
- (void)setIsWaitingDouYinCallback:;
- (void)setLoginCompletedHandler:;
- (void)setWillLoginHandler:;
- (id)thirdPartAuthParams:;
- (void)tryCancelAuthWhenAppDidBeActive:;
- (id)willLoginHandler;
- (id)init;
- (void)dealloc;
- (void)setScope:;
- (id)appId;
- (void)appDidEnterBackground:;
- (id)scope;
- (id)code;
- (void)setAppId:;
- (void).cxx_destruct;
- (void)reset;
- (void)setCode:;
- (id)authRequest;
- (void)setAuthRequest:;
+ (id)defaultUserInfo;
+ (BOOL)isSupportWebSSO;
+ (id)additionalPermissions;
+ (BOOL)continueUserActivity:restorationHandler:;
+ (id)defaultPermissions;
+ (BOOL)didFinishLaunchingWithOptions:;
+ (id)getAppInstallUrl;
+ (BOOL)handleOpenURL:options:;
+ (BOOL)handleOpenURL:sourceApplication:annotation:;
+ (BOOL)isAppAvailable;
+ (BOOL)isSupportCustomWebSSO;
+ (BOOL)isSupportSSO;
+ (BOOL)isSupportSSOWithIgnoreScheme:;
+ (id)openTokenInfoURLString;
+ (id)platformAppID;
+ (void)registerApp:;
+ (id)sharedInstance;
+ (id)currentVersion;
+ (id)permissions;
+ (id)displayName;
+ (BOOL)isAppInstalled;
+ (id)stateString;
+ (id)platformName;
+ (long long)platformType;
+ (id)scopeString;
+ (id)extraInfo;
+ (BOOL)handleOpenURL:;
@end
