@interface TTTopSignature : NSObject
@property (nonatomic) NSString currDateString;
@property (nonatomic) NSString secretKey;
@property (nonatomic) NSString accessKey;
@property (nonatomic) NSString regionName;
@property (nonatomic) NSString serviceName;
@property (nonatomic) q httpMethod;
@property (nonatomic) NSString canonicalURI;
@property (nonatomic) NSDictionary requestParameters;
@property (nonatomic) NSDictionary requestParametersArrary;
@property (nonatomic) NSDictionary requestHeaders;
@property (nonatomic) NSString payload;
- (id)canonicalURI;
- (id)currDateString;
- (id)getSignedHeadersString:;
- (id)getV4DerivedKey:date:region:service:;
- (id)requestParametersArrary;
- (void)setCanonicalURI:;
- (void)setCurrDateString:;
- (void)setRequestParametersArrary:;
- (id)signerHeaders;
- (id)tsa_calculateSignature:;
- (id)tsa_getCanonicalizedHeaderString:;
- (id)tsa_prepareCanonicalRequest;
- (id)tsa_prepareStringToSign:dateStamp:;
- (id)payload;
- (void)setRequestParameters:;
- (id)init;
- (void)setSecretKey:;
- (void)setPayload:;
- (long long)httpMethod;
- (void)setServiceName:;
- (void)setHttpMethod:;
- (id)serviceName;
- (id)requestParameters;
- (void).cxx_destruct;
- (id)secretKey;
- (id)accessKey;
- (void)setAccessKey:;
- (id)regionName;
- (void)setRegionName:;
- (id)requestHeaders;
- (void)setRequestHeaders:;
@end
