@interface TTVideoEngineMetricImpl : TTVideoEngineMetric
@property (nonatomic) q ability;
@property (nonatomic) q duration;
@property (nonatomic) q enableDiagnose;
@property (nonatomic) double lastMetricTime;
@property (nonatomic) double curDuration;
@property (nonatomic) TTVideoEngineMetricDiagnose metricDiagnose;
@property (nonatomic) TTVideoEngineBatteryMonitor batteryMonitor;
@property (nonatomic) TTVideoEngineMetricKit metricKit;
@property (nonatomic) NSObject<OS_dispatch_queue> metricQueue;
@property (nonatomic) NSMutableDictionary seprateCpuDic;
- (void)setCurDuration:;
- (void)setMetricQueue:;
- (long long)ability;
- (id)backtraceWithThreads:;
- (id)batteryMonitor;
- (void)beginMetric;
- (void)clearSysInfo;
- (double)curDuration;
- (void)diagnoseMetricInfo;
- (long long)enableDiagnose;
- (float)getCpuInfoWithTheadInfo:threadRecord:;
- (id)getMetricCalInfo;
- (id)getMetricSysInfo;
- (id)isPlayThread:;
- (double)lastMetricTime;
- (id)metricDiagnose;
- (id)metricKit;
- (id)metricQueue;
- (id)seprateCpuDic;
- (void)setAbility:;
- (void)setBatteryMonitor:;
- (void)setEnableDiagnose:;
- (void)setLastMetricTime:;
- (void)setMetricDiagnose:;
- (void)setMetricKit:;
- (void)setSeprateCpuDic:;
- (void)setupAbility:;
- (void)setupInterval:;
- (void)stopMetric;
- (id)init;
- (void)setDuration:;
- (void).cxx_destruct;
- (long long)duration;
+ (id)threadArray;
+ (id)sharedInstance;
@end
