@interface TTVideoEngineEventBase : NSObject
@property (nonatomic) <TTVideoEngineEventLoggerDelegate> delegate;
@property (nonatomic) NSMutableDictionary videoInfo;
@property (nonatomic) NSString session_id;
@property (nonatomic) NSString device_id;
@property (nonatomic) NSString sv;
@property (nonatomic) NSString pv;
@property (nonatomic) NSString pc;
@property (nonatomic) NSString sdk_version;
@property (nonatomic) NSString vid;
@property (nonatomic) NSString source_type;
@property (nonatomic) NSString tag;
@property (nonatomic) NSString subtag;
@property (nonatomic) NSString lastResolution;
@property (nonatomic) NSString currentResolution;
@property (nonatomic) q beginSwitchResolutionCurPos;
@property (nonatomic) Q beginSwitchResolutionTime;
@property (nonatomic) NSString initialQualityDesc;
@property (nonatomic) NSString currentQualityDesc;
@property (nonatomic) NSString initial_ip;
@property (nonatomic) NSString initial_resolution;
@property (nonatomic) NSString curURL;
@property (nonatomic) NSString initialURL;
@property (nonatomic) NSString internal_ip;
@property (nonatomic) q drm_type;
@property (nonatomic) NSString drm_token_url;
@property (nonatomic) q play_type;
@property (nonatomic) q audio_codec_nameId;
@property (nonatomic) q video_codec_nameId;
@property (nonatomic) q format_type;
@property (nonatomic) BOOL hw;
@property (nonatomic) BOOL hw_user;
@property (nonatomic) double playSpeed;
@property (nonatomic) q reuse_socket;
@property (nonatomic) NSDictionary abr_info;
@property (nonatomic) BOOL isEnableABR;
@property (nonatomic) NSString vtype;
@property (nonatomic) q video_stream_duration;
@property (nonatomic) q audio_stream_duration;
@property (nonatomic) Q lastForebackSwitchTime;
@property (nonatomic) Q lastAVSwitchTime;
@property (nonatomic) Q lastResSwitchTime;
@property (nonatomic) Q lastHeadsetSwithTime;
@property (nonatomic) q isInBackground;
@property (nonatomic) q radioMode;
@property (nonatomic) q curHeadset;
@property (nonatomic) q blueTooth;
@property (nonatomic) NSDictionary r_stage_errcs;
@property (nonatomic) BOOL has_get_preload_traceid;
@property (nonatomic) BOOL hasAudioTrackInfo;
@property (nonatomic) q mdl_cur_req_pos;
@property (nonatomic) q mdl_cur_end_pos;
@property (nonatomic) q mdl_cur_cache_pos;
@property (nonatomic) q mdl_cache_type;
@property (nonatomic) NSString mdl_cur_ip;
@property (nonatomic) NSString mdl_cur_host;
@property (nonatomic) NSString mdl_cur_url;
@property (nonatomic) q mdl_reply_size;
@property (nonatomic) q mdl_down_pos;
@property (nonatomic) q mdl_player_wait_time;
@property (nonatomic) q mdl_player_wait_num;
@property (nonatomic) q mdl_stage;
@property (nonatomic) q mdl_error_code;
@property (nonatomic) q mdl_sub_error_code;
@property (nonatomic) q mdl_cur_task_num;
@property (nonatomic) NSInteger mdl_conc_count;
@property (nonatomic) q mdl_speed;
@property (nonatomic) NSString mdl_file_key;
@property (nonatomic) q mdl_is_socrf;
@property (nonatomic) q mdl_req_num;
@property (nonatomic) q mdl_url_index;
@property (nonatomic) NSString mdl_re_url;
@property (nonatomic) q mdl_cur_soure;
@property (nonatomic) NSString mdl_extra_info;
@property (nonatomic) q mdl_http_code;
@property (nonatomic) q mdl_req_t;
@property (nonatomic) q mdl_end_t;
@property (nonatomic) q mdl_dns_t;
@property (nonatomic) q mdl_tcp_start_t;
@property (nonatomic) q mdl_tcp_end_t;
@property (nonatomic) q mdl_ttfp;
@property (nonatomic) q mdl_httpfb;
@property (nonatomic) q mdl_http_open_end_t;
@property (nonatomic) q mdl_fs;
@property (nonatomic) q mdl_pcdn_full_speed;
@property (nonatomic) q mdl_tbs;
@property (nonatomic) q mdl_lbs;
@property (nonatomic) q mdl_res_err;
@property (nonatomic) q mdl_read_src;
@property (nonatomic) q mdl_seek_num;
@property (nonatomic) NSString mdl_last_msg;
@property (nonatomic) NSString mdl_server_timing;
@property (nonatomic) q mdl_v_lt;
@property (nonatomic) q mdl_v_p2p_ier;
@property (nonatomic) NSString mdl_ip_list;
@property (nonatomic) NSString mdl_blocked_ips;
@property (nonatomic) NSString mdl_response_cinfo;
@property (nonatomic) NSString mdl_response_cache;
@property (nonatomic) NSString mdl_dns_type;
@property (nonatomic) q mdl_p2p_loader;
@property (nonatomic) NSDictionary mdl_features;
@property (nonatomic) TTVideoEngineMDLTrackInfo mdlAudioInfo;
@property (nonatomic) TTVideoEngineMDLTrackInfo mdlVideoInfo;
- (long long)mdl_cur_req_pos;
- (long long)mdl_lbs;
- (long long)mdl_tcp_start_t;
- (void)setBeginSwitchResolutionCurPos:;
- (void)setInternal_ip:;
- (void)setIsEnableABR:;
- (void)setMdl_ip_list:;
- (void)setMdl_res_err:;
- (void)setSdk_version:;
- (void)setVid:;
- (id)vid;
- (BOOL)hw_user;
- (id)mdl_blocked_ips;
- (long long)mdl_cur_end_pos;
- (long long)mdl_tbs;
- (void)setFormat_type:;
- (void)setMdl_cur_url:;
- (void)setMdl_req_num:;
- (void)setSource_type:;
- (id)abr_info;
- (long long)audio_codec_nameId;
- (long long)audio_stream_duration;
- (long long)beginSwitchResolutionCurPos;
- (unsigned long long)beginSwitchResolutionTime;
- (void)beginToPlay:;
- (long long)blueTooth;
- (long long)curHeadset;
- (id)curURL;
- (id)currentQualityDesc;
- (id)drm_token_url;
- (long long)drm_type;
- (long long)format_type;
- (id)generateTraceID:;
- (id)getNetworkType;
- (BOOL)hasAudioTrackInfo;
- (BOOL)has_get_preload_traceid;
- (BOOL)hw;
- (void)initPlay:traceId:;
- (id)initialQualityDesc;
- (id)initial_ip;
- (id)initial_resolution;
- (id)internal_ip;
- (BOOL)isEnableABR;
- (unsigned long long)lastAVSwitchTime;
- (unsigned long long)lastForebackSwitchTime;
- (unsigned long long)lastHeadsetSwithTime;
- (unsigned long long)lastResSwitchTime;
- (id)lastResolution;
- (id)mdlAudioInfo;
- (id)mdlVideoInfo;
- (long long)mdl_cache_type;
- (int)mdl_conc_count;
- (long long)mdl_cur_cache_pos;
- (id)mdl_cur_host;
- (id)mdl_cur_ip;
- (long long)mdl_cur_soure;
- (long long)mdl_cur_task_num;
- (id)mdl_cur_url;
- (long long)mdl_dns_t;
- (id)mdl_dns_type;
- (long long)mdl_down_pos;
- (long long)mdl_end_t;
- (long long)mdl_error_code;
- (id)mdl_extra_info;
- (id)mdl_features;
- (id)mdl_file_key;
- (long long)mdl_fs;
- (long long)mdl_http_code;
- (long long)mdl_http_open_end_t;
- (long long)mdl_httpfb;
- (id)mdl_ip_list;
- (long long)mdl_is_socrf;
- (id)mdl_last_msg;
- (long long)mdl_p2p_loader;
- (long long)mdl_pcdn_full_speed;
- (long long)mdl_player_wait_num;
- (long long)mdl_player_wait_time;
- (id)mdl_re_url;
- (long long)mdl_read_src;
- (long long)mdl_reply_size;
- (long long)mdl_req_num;
- (long long)mdl_req_t;
- (long long)mdl_res_err;
- (id)mdl_response_cache;
- (id)mdl_response_cinfo;
- (long long)mdl_seek_num;
- (id)mdl_server_timing;
- (long long)mdl_speed;
- (long long)mdl_stage;
- (long long)mdl_sub_error_code;
- (long long)mdl_tcp_end_t;
- (long long)mdl_ttfp;
- (long long)mdl_url_index;
- (long long)mdl_v_lt;
- (long long)mdl_v_p2p_ier;
- (id)pc;
- (double)playSpeed;
- (long long)play_type;
- (id)pv;
- (id)r_stage_errcs;
- (long long)radioMode;
- (long long)reuse_socket;
- (id)sdk_version;
- (void)setAbr_info:;
- (void)setAudio_codec_nameId:;
- (void)setAudio_stream_duration:;
- (void)setBeginSwitchResolutionTime:;
- (void)setBlueTooth:;
- (void)setCurHeadset:;
- (void)setCurURL:;
- (void)setCurrentQualityDesc:;
- (void)setDrm_token_url:;
- (void)setDrm_type:;
- (void)setHasAudioTrackInfo:;
- (void)setHas_get_preload_traceid:;
- (void)setHw:;
- (void)setHw_user:;
- (void)setInitialQualityDesc:;
- (void)setInitial_ip:;
- (void)setInitial_resolution:;
- (void)setIsInBackground:;
- (void)setLastAVSwitchTime:;
- (void)setLastForebackSwitchTime:;
- (void)setLastHeadsetSwithTime:;
- (void)setLastResSwitchTime:;
- (void)setLastResolution:;
- (void)setMdlAudioInfo:;
- (void)setMdlVideoInfo:;
- (void)setMdl_blocked_ips:;
- (void)setMdl_cache_type:;
- (void)setMdl_conc_count:;
- (void)setMdl_cur_cache_pos:;
- (void)setMdl_cur_end_pos:;
- (void)setMdl_cur_host:;
- (void)setMdl_cur_ip:;
- (void)setMdl_cur_req_pos:;
- (void)setMdl_cur_soure:;
- (void)setMdl_cur_task_num:;
- (void)setMdl_dns_t:;
- (void)setMdl_dns_type:;
- (void)setMdl_down_pos:;
- (void)setMdl_end_t:;
- (void)setMdl_error_code:;
- (void)setMdl_extra_info:;
- (void)setMdl_features:;
- (void)setMdl_file_key:;
- (void)setMdl_fs:;
- (void)setMdl_http_code:;
- (void)setMdl_http_open_end_t:;
- (void)setMdl_httpfb:;
- (void)setMdl_is_socrf:;
- (void)setMdl_last_msg:;
- (void)setMdl_lbs:;
- (void)setMdl_p2p_loader:;
- (void)setMdl_pcdn_full_speed:;
- (void)setMdl_player_wait_num:;
- (void)setMdl_player_wait_time:;
- (void)setMdl_re_url:;
- (void)setMdl_read_src:;
- (void)setMdl_reply_size:;
- (void)setMdl_req_t:;
- (void)setMdl_response_cache:;
- (void)setMdl_response_cinfo:;
- (void)setMdl_seek_num:;
- (void)setMdl_server_timing:;
- (void)setMdl_speed:;
- (void)setMdl_stage:;
- (void)setMdl_sub_error_code:;
- (void)setMdl_tbs:;
- (void)setMdl_tcp_end_t:;
- (void)setMdl_tcp_start_t:;
- (void)setMdl_ttfp:;
- (void)setMdl_url_index:;
- (void)setMdl_v_lt:;
- (void)setMdl_v_p2p_ier:;
- (void)setPc:;
- (void)setPlaySpeed:;
- (void)setPlay_type:;
- (void)setPv:;
- (void)setR_stage_errcs:;
- (void)setRadioMode:;
- (void)setReuse_socket:;
- (void)setSubtag:;
- (void)setSv:;
- (void)setVideoInfo:;
- (void)setVideo_codec_nameId:;
- (void)setVideo_stream_duration:;
- (void)setVtype:;
- (id)source_type;
- (id)subtag;
- (id)sv;
- (void)updateMDLInfo;
- (void)updateMdlFeatures:;
- (void)updateVersionInfo;
- (id)videoInfo;
- (long long)video_codec_nameId;
- (long long)video_stream_duration;
- (id)vtype;
- (id)tag;
- (id)init;
- (void)setDelegate:;
- (long long)isInBackground;
- (id)device_id;
- (void)setTag:;
- (id)delegate;
- (void).cxx_destruct;
- (void)setDevice_id:;
- (id)initialURL;
- (id)session_id;
- (void)setSession_id:;
- (id)currentResolution;
- (void)setCurrentResolution:;
- (void)setInitialURL:;
+ (id)generateSessionID:;
@end
