@interface TUCallCapabilitiesXPCClient : NSObject
@property (nonatomic) NSObject<OS_dispatch_queue> queue;
@property (nonatomic) NSXPCConnection xpcConnection;
@property (nonatomic) NSInteger token;
@property (nonatomic) NSMapTable delegateToQueue;
@property (nonatomic) TUCallCapabilitiesState state;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)handleServerDisconnect;
- (id)invalidateAndRefreshWiFiCallingProvisioningURLForSenderIdentityWithUUID:;
- (id)init;
- (id)setWiFiCallingEnabled:forSenderIdentityWithUUID:;
- (id)setThumperCallingAllowed:onSecondaryDeviceWithID:forSenderIdentityWithUUID:;
- (void)dealloc;
- (int)token;
- (void)setState:;
- (void)removeDelegate:;
- (id)synchronousServerWithErrorHandler:;
- (void)_retrieveState;
- (void)setXpcConnection:;
- (id)setRelayCallingEnabled:;
- (id)setVoLTECallingEnabled:forSenderIdentityWithUUID:;
- (id)capabilityStateUpdated:;
- (id)setThumperCallingAllowedOnDefaultPairedDevice:forSenderIdentityWithUUID:;
- (id)endEmergencyCallbackMode;
- (id)asynchronousServerWithErrorHandler:;
- (id)state;
- (void)addDelegate:queue:;
- (id)xpcConnection;
- (void).cxx_destruct;
- (id)setWiFiCallingRoamingEnabled:forSenderIdentityWithUUID:;
- (id)setRelayCallingEnabled:forDeviceWithID:;
- (id)delegateToQueue;
- (id)requestPinFromPrimaryDevice;
- (id)cancelPinRequestFromPrimaryDevice;
- (id)invalidateAndRefreshThumperCallingProvisioningURLForSenderIdentityWithUUID:;
- (void)_updateState:;
- (id)setThumperCallingEnabled:forSenderIdentityWithUUID:;
- (id)queue;
- (void)invalidate;
- (id)asynchronousServer;
- (void)performDelegateCallbackBlock:;
+ (id)callCapabilitiesServerXPCInterface;
+ (void)setSynchronousServer:;
+ (void)setAsynchronousServer:;
+ (id)callCapabilitiesClientXPCInterface;
+ (id)asynchronousServer;
+ (id)synchronousServer;
@end
