@interface TVLPlayerItemAccessLogObservedData : NSObject
@property (nonatomic) q timestamp;
@property (nonatomic) q playedSizeInBytes;
@property (nonatomic) q playPosition;
@property (nonatomic) NSMutableArray stallEvents;
@property (nonatomic) NSMutableArray renderStallEvents;
@property (nonatomic) NSMutableArray avOutSyncEvents;
@property (nonatomic) q durationOfStalls;
@property (nonatomic) q durationOfStallsInPreview;
@property (nonatomic) q stallCountInPreview;
@property (nonatomic) NSDate startPreviewDate;
@property (nonatomic) q playTimePreview;
@property (nonatomic) q playSpeedChangeCount;
@property (nonatomic) NSMutableString playSpeedChangeInfo;
- (void)setStallEvents:;
- (id)avOutSyncEvents;
- (long long)playTimePreview;
- (id)renderStallInfo;
- (void)appendAVOutSyncEvent:;
- (id)avOutSyncInfo;
- (long long)durationOfStalls;
- (long long)durationOfStallsInPreview;
- (void)endPreview;
- (long long)getPlayPreviewTime;
- (void)handlePreview:;
- (long long)playSpeedChangeCount;
- (id)playSpeedChangeInfo;
- (long long)playedSizeInBytes;
- (void)recordPlaySpeedChange:;
- (id)renderStallEvents;
- (void)setAvOutSyncEvents:;
- (void)setPlayPosition:;
- (void)setPlayTimePreview:;
- (void)setPlayedSizeInBytes:;
- (void)setReadOnlyVariable:playSppedChangeCount:playSpeedChangeInfo:;
- (void)setRenderStallEvents:;
- (void)setStartPreviewDate:;
- (long long)stallCountInPreview;
- (id)stallEvents;
- (id)startPreviewDate;
- (id)init;
- (void).cxx_destruct;
- (long long)timestamp;
- (id)copyWithZone:;
- (long long)playPosition;
@end
