@interface UAHTTPOperation : NSOperation
@property (nonatomic) UASocket socket;
@property (nonatomic) NSURLRequest request;
@property (nonatomic) NSHTTPURLResponse response;
@property (nonatomic) NSError error;
@property (nonatomic) NSData body;
@property (nonatomic) @ responseSerializer;
@property (nonatomic) float systemVersion;
@property (nonatomic) NSDictionary schemeInfo;
@property (nonatomic) BOOL wifiwwanNetwork;
@property (nonatomic) BOOL useCellular;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) NSData certData;
@property (nonatomic) @? completion;
- (void)socket:didConnectThroughIPType:;
- (BOOL)wifiwwanNetwork;
- (void)createConnectionToHost:port:ssl:;
- (void)dechunkedData:;
- (id)responseSerializer;
- (id)schemeInfo;
- (void)serializeHTTPResponseMessage;
- (void)setResponseSerializer:;
- (void)setSchemeInfo:;
- (void)setWifiwwanNetwork:;
- (void)socket:didOccurError:;
- (void)socket:didReadData:;
- (void)socket:shouldVerifyServerTrust:authResult:;
- (void)socketDidWriteComplete:;
- (id)completion;
- (void)setFinished:;
- (id)initWithRequest:;
- (void)setCompletion:;
- (BOOL)useCellular;
- (void)cancel;
- (void)dealloc;
- (id)requestData;
- (id)body;
- (void)socketDidClose:;
- (void)setError:;
- (void)startRequest;
- (id)error;
- (id)request;
- (id)socket;
- (void)setSocket:;
- (BOOL)isFinished;
- (void)main;
- (void)setBody:;
- (id)response;
- (void).cxx_destruct;
- (float)systemVersion;
- (void)setRequest:;
- (void)setResponse:;
- (void)finishTask;
- (id)certData;
- (void)setSystemVersion:;
- (void)setCertData:;
- (void)setUseCellular:;
+ (Class)socketClass;
@end
