@interface UgenV3ButtonWidget : UgenWidget
@property (nonatomic) NSString text;
@property (nonatomic) NSString textColor;
@property (nonatomic) NSString textSize;
@property (nonatomic) NSString textStyle;
@property (nonatomic) q lines;
@property (nonatomic) q maxLines;
@property (nonatomic) NSString ellipsize;
@property (nonatomic) NSString textDecoration;
@property (nonatomic) NSString lineHeight;
@property (nonatomic) NSString image;
@property (nonatomic) NSString direction;
@property (nonatomic) NSString highlightImage;
@property (nonatomic) NSString highlightBackgroundImage;
@property (nonatomic) NSString highlightBackgroundColor;
@property (nonatomic) NSString highlightTextColor;
@property (nonatomic) NSString highlightedTextColor;
@property (nonatomic) UIButton button;
- (id)ellipsize;
- (id)highlightBackgroundImage;
- (id)pbu_font;
- (void)setEllipsize:;
- (void)setHighlightBackgroundImage:;
- (void)setHighlightImage:;
- (void)subRender_image_info;
- (void)subRender_text_info;
- (id)ugenView;
- (void)setMaxLines:;
- (void)setHighlightedTextColor:;
- (id)direction;
- (id)init;
- (void)setDirection:;
- (id)textStyle;
- (id)highlightedTextColor;
- (void)setText:;
- (long long)maxLines;
- (void)setImage:;
- (void)setTextStyle:;
- (void)setTextColor:;
- (id)button;
- (void).cxx_destruct;
- (id)textColor;
- (long long)lines;
- (void)setButton:;
- (id)text;
- (id)image;
- (id)highlightImage;
- (id)lineHeight;
- (void)setLineHeight:;
- (id)textSize;
- (void)setLines:;
- (id)highlightBackgroundColor;
- (void)setHighlightBackgroundColor:;
- (id)highlightTextColor;
- (void)setHighlightTextColor:;
- (id)textDecoration;
- (void)setTextDecoration:;
- (void)setTextSize:;
@end
