@interface UIBezierPath : NSObject
@property (nonatomic) r^{CGPath=} vk_CGPath;
@property (nonatomic) NSMutableArray vk_allPoints;
@property (nonatomic) {CGPoint=dd} vk_centroid;
@property (nonatomic) double vk_lengthIgnoringCurves;
@property (nonatomic) r^{CGPath=} CGPath;
@property (nonatomic) BOOL empty;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} bounds;
@property (nonatomic) {CGPoint=dd} currentPoint;
@property (nonatomic) double lineWidth;
@property (nonatomic) NSInteger lineCapStyle;
@property (nonatomic) NSInteger lineJoinStyle;
@property (nonatomic) double miterLimit;
@property (nonatomic) double flatness;
@property (nonatomic) BOOL usesEvenOddFillRule;
- (id)PK_CGPath;
- (id)debugQuickLookObject;
- (id)vk_CGPath;
- (void)vk_addLineToPoint:;
- (void)vk_addCurveToPoint:controlPoint1:controlPoint2:;
- (void)vk_appendBezierPath:;
- (id)vk_centroid;
- (double)vk_lengthIgnoringCurves;
- (id)vk_allPoints;
- (void)vk_applyTransform:;
- (id)vk_pathFromFlippingInRect:;
- (id)vk_subpathArray;
- (id)vk_unionAndFlattenWithPath:;
- (id)vk_intersectAndFlattenWithPath:;
- (id)_vk_flattenWithPath:clipType:;
- (id)vk_expandWithOffset:;
- (void)setLineWidth:;
- (id)init;
- (BOOL)isEmpty;
- (double)lineWidth;
- (void)dealloc;
- (id)initWithCoder:;
- (double)_cornerRadius;
- (void)encodeWithCoder:;
- (id)currentPoint;
- (id)description;
- (id)bounds;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (BOOL)containsPoint:;
- (double)miterLimit;
- (void)setMiterLimit:;
- (unsigned long long)_cornerMask;
- (id)_initWithCGMutablePath:;
- (void)moveToPoint:;
- (void)addLineToPoint:;
- (void)addCurveToPoint:controlPoint1:controlPoint2:;
- (void)addQuadCurveToPoint:controlPoint:;
- (void)addArcWithCenter:radius:startAngle:endAngle:clockwise:;
- (void)appendPath:;
- (void)applyTransform:;
- (void)closePath;
- (void)removeAllPoints;
- (void)_invalidatePathMetadata;
- (id)bezierPathByReversingPath;
- (id)CGPath;
- (void)setCGPath:;
- (void)setLineDash:count:phase:;
- (void)getLineDash:count:phase:;
- (void)fill;
- (void)stroke;
- (void)fillWithBlendMode:alpha:;
- (void)strokeWithBlendMode:alpha:;
- (void)addClip;
- (id)_mutablePath;
- (id)_createMutablePathByDecodingData:;
- (void)_addRoundedCornerWithTrueCorner:radius:corner:clockwise:;
- (void)_addRoundedCornerWithTrueCorner:radius:corner:clockwise:leadInIsContinuous:leadOutIsContinuous:;
- (id)_objcCodeDescription;
- (id)_pathRef;
- (void)lineToPoint:;
- (void)clip;
- (void)appendBezierPath:;
- (void)appendBezierPathWithRect:;
- (void)appendBezierPathWithOvalInRect:;
- (void)appendBezierPathWithOvalInRect:transform:;
- (void)appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:;
- (id)_bezierPathConvertedFromCoordinateSpace:toCoordinateSpace:;
- (BOOL)_isRoundedRect;
- (BOOL)_hasContinuousCorners;
- (int)lineCapStyle;
- (void)setLineCapStyle:;
- (int)lineJoinStyle;
- (void)setLineJoinStyle:;
- (double)flatness;
- (void)setFlatness:;
- (BOOL)usesEvenOddFillRule;
- (void)setUsesEvenOddFillRule:;
+ (id)vk_allPointsFromCGPath:;
+ (id)vk_pathFromCGPath:;
+ (id)vk_subpathArrayFromCGPath:;
+ (id)vk_groupAndRoundPaths:radius:offset:;
+ (BOOL)vk_cgPathcontainsAnyCurveToPoints:;
+ (id)_cgPathFromClipperPath:;
+ (id)vk_newRoundedPathWithRadius:points:;
+ (void)_processPointsForNarrowAngles:;
+ (void)_processPointsForRounding:withRadius:;
+ (id)vk_shiftLinePerpendicularlyFromPoint:to:radius:;
+ (double)vk_clampedRadius:p1:p2:p3:;
+ (double)vk_signForRadiusWithVectorStart:end:otherPoint:;
+ (id)vk_calculateCenterForPoints:p2:p3:radius:;
+ (id)vk_projectPoint:lineStart:lineEnd:;
+ (id)vk_roundAndGroupNormalizedQuadsForHighlight:aspectRatio:expansionScale:radiusToAvgHeightRatio:;
+ (double)radiusForQuads:radiusRatio:;
+ (id)mapPaths:toQuads:;
+ (BOOL)supportsSecureCoding;
+ (id)bezierPath;
+ (id)bezierPathWithRect:;
+ (id)bezierPathWithOvalInRect:;
+ (id)bezierPathWithRoundedRect:cornerRadius:;
+ (id)_bezierPathWithArcRoundedRect:cornerRadius:;
+ (id)bezierPathWithRoundedRect:byRoundingCorners:cornerRadii:;
+ (id)bezierPathWithArcCenter:radius:startAngle:endAngle:clockwise:;
+ (id)bezierPathWithCGPath:;
+ (id)roundedRectBezierPath:withTopCornerRadius:withBottomCornerRadius:;
+ (id)_bezierPathWithRoundedRect:byRoundingCorners:cornerRadius:;
+ (id)roundedRectBezierPath:withRoundedEdges:;
+ (id)roundedRectBezierPath:withRoundedCorners:withCornerRadius:;
+ (id)roundedRectBezierPath:withRoundedCorners:withCornerRadii:;
+ (id)_roundedRectBezierPath:withRoundedCorners:cornerRadius:segments:;
+ (id)_roundedRectBezierPath:withRoundedCorners:cornerRadius:segments:legacyCorners:;
+ (id)_bezierPathWithPillRect:cornerRadius:;
+ (id)_continuousRoundedRectBezierPath:withRoundedCorners:cornerRadius:segments:;
+ (id)_continuousRoundedRectBezierPath:withRoundedCorners:cornerRadii:segments:smoothPillShapes:;
+ (id)shadowBezierPath:withRoundedEdges:;
@end
