@interface UIFontPickerViewController : UIViewController
@property (nonatomic) NSExtension extension;
@property (nonatomic) <NSCopying> extensionRequestIdentifier;
@property (nonatomic) UIFontPickerViewControllerConfiguration configuration;
@property (nonatomic) <UIFontPickerViewControllerDelegate> delegate;
@property (nonatomic) UIFontDescriptor selectedFontDescriptor;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) _UIRemoteViewController _containedRemoteViewController;
- (id)initWithMode:;
- (id)remoteViewController;
- (id)init;
- (void)setExtension:;
- (void)dealloc;
- (void)setDelegate:;
- (id)extension;
- (id)initWithCoder:;
- (BOOL)_canShowWhileLocked;
- (void)encodeWithCoder:;
- (id)configuration;
- (id)delegate;
- (void).cxx_destruct;
- (void)viewWillAppear:;
- (void)dismissViewControllerWithTransition:completion:;
- (void)invalidate;
- (id)initWithConfiguration:;
- (id)_containedRemoteViewController;
- (void)_setChildViewController:;
- (id)extensionRequestIdentifier;
- (void)setExtensionRequestIdentifier:;
- (void)_viewControllerPresentationDidInitiate;
- (void)_commonInitWithCompletion:;
- (void)_pickerDidSelectFont:;
- (void)_pickerDidCancel;
- (id)selectedFontDescriptor;
- (void)setSelectedFontDescriptor:;
- (id)initWithSelectedFont:inMode:;
- (id)_initWithMode:hideSearchBar:tintColor:;
- (id)_initWithCompletion:;
@end
