@interface UIInputSwitcherItem : NSObject
@property (nonatomic) NSString identifier;
@property (nonatomic) NSString localizedTitle;
@property (nonatomic) NSString localizedSubtitle;
@property (nonatomic) UIFont titleFont;
@property (nonatomic) UIFont subtitleFont;
@property (nonatomic) BOOL usesDeviceLanguage;
@property (nonatomic) UISwitch switchControl;
@property (nonatomic) @? switchIsOnBlock;
@property (nonatomic) @? switchToggleBlock;
@property (nonatomic) BOOL isSegmentedItem;
@property (nonatomic) q selectedSegmentIndex;
@property (nonatomic) NSArray segmentTitles;
@property (nonatomic) NSArray segmentImages;
@property (nonatomic) @? persistentSelectedIndex;
- (id)subtitleFont;
- (id)titleFont;
- (void)setSubtitleFont:;
- (void)setSwitchControl:;
- (void)dealloc;
- (void)setTitleFont:;
- (id)localizedSubtitle;
- (void)setLocalizedSubtitle:;
- (id)identifier;
- (void).cxx_destruct;
- (id)localizedTitle;
- (void)setLocalizedTitle:;
- (id)initWithIdentifier:;
- (void)setIdentifier:;
- (long long)selectedSegmentIndex;
- (void)setSelectedSegmentIndex:;
- (id)switchControl;
- (void)setSegmentTitles:;
- (void)setSegmentImages:;
- (id)segmentTitles;
- (id)segmentImages;
- (BOOL)isSegmentedItem;
- (BOOL)usesDeviceLanguage;
- (void)setUsesDeviceLanguage:;
- (id)switchIsOnBlock;
- (void)setSwitchIsOnBlock:;
- (id)switchToggleBlock;
- (void)setSwitchToggleBlock:;
- (id)persistentSelectedIndex;
- (void)setPersistentSelectedIndex:;
+ (id)switcherItemWithIdentifier:;
@end
