@interface UIKBScreenTraits : NSObject
@property (nonatomic) q preferredEmojiScrollingDirection;
@property (nonatomic) UIScreen screen;
@property (nonatomic) q idiom;
@property (nonatomic) BOOL knobInput;
@property (nonatomic) BOOL touchInput;
@property (nonatomic) BOOL touchpadInput;
@property (nonatomic) q orientation;
@property (nonatomic) double keyboardWidth;
@property (nonatomic) double assistantViewWidth;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} bounds;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} assistantViewWindowBounds;
@property (nonatomic) BOOL isKeyboardMinorEdgeWidth;
@property (nonatomic) double keyboardBarHeight;
@property (nonatomic) BOOL isInPopover;
@property (nonatomic) BOOL isFloating;
@property (nonatomic) BOOL isSplit;
@property (nonatomic) BOOL supportsSplit;
@property (nonatomic) BOOL centerFilled;
@property (nonatomic) {CGSize=dd} keyboardScreenReferenceSize;
@property (nonatomic) {CGSize=dd} stretchFactor;
@property (nonatomic) BOOL isLinear;
@property (nonatomic) BOOL isEmojiScrollingDirectionVertical;
- (BOOL)isSplit;
- (BOOL)centerFilled;
- (double)keyboardBarHeight;
- (void)setSupportsSplit:;
- (void)updateForLinearLayout:;
- (BOOL)isFloating;
- (void)setIsSplit:;
- (void)setAssistantViewWidth:;
- (id)keyboardScreenReferenceSize;
- (double)keyboardWidth;
- (BOOL)knobInput;
- (id)assistantViewWindowBounds;
- (BOOL)isKeyboardMinorEdgeWidth;
- (id)stretchFactor;
- (id)initWithScreen:orientation:allowFloating:ignoreRemoteKeyboard:;
- (BOOL)touchpadInput;
- (BOOL)supportsSplit;
- (long long)orientation;
- (void)setAssistantViewWindowBounds:;
- (id)screen;
- (void)setCenterFilled:;
- (long long)idiom;
- (long long)preferredEmojiScrollingDirection;
- (BOOL)isLinear;
- (void)setBounds:;
- (void)setKeyboardBarHeight:;
- (void)setStretchFactor:;
- (void).cxx_destruct;
- (void)updateForTextInputTraits:supportedInteractionModel:;
- (id)description;
- (BOOL)isEmojiScrollingDirectionVertical;
- (void)setPreferredEmojiScrollingDirection:;
- (id)bounds;
- (double)assistantViewWidth;
- (void)setKeyboardWidth:;
- (void)setOrientation:;
- (BOOL)isInPopover;
- (BOOL)touchInput;
- (id)initForInputModeWithScreen:;
+ (id)traitsForPopoverEmulatingWidth:minorEdge:orientation:idiom:;
+ (id)traitsWithScreen:orientation:;
+ (id)traitsWithScreen:orientation:ignoreRemoteKeyboard:;
+ (void)setMockIdiom:;
+ (id)traitsForInputModeWithScreen:;
+ (id)_activeUCBWindowForScreen:;
+ (id)fullScreenTraitsWithScreen:orientation:;
+ (id)_activeKeyboardWindowForScreen:;
@end
