@interface UIKBUndoStyling : NSObject
@property (nonatomic) UIBlurEffect backgroundBlurEffect;
@property (nonatomic) UIVibrancyEffect backgroundVibrancyEffect;
@property (nonatomic) UIColor HUDbackgroundColor;
@property (nonatomic) UIColor HUDShadowColor;
@property (nonatomic) UIColor buttonGlyphColorEnabled;
@property (nonatomic) UIColor buttonGlyphColorPressed;
@property (nonatomic) UIColor buttonGlyphColorDisabled;
@property (nonatomic) UIColor elementBackgroundColor;
@property (nonatomic) UIColor elementCoverColor;
@property (nonatomic) BOOL undoRedoIconOnly;
@property (nonatomic) BOOL cutCopyPasteIconOnly;
@property (nonatomic) BOOL tooSmallForInstructionalText;
@property (nonatomic) BOOL isRTL;
@property (nonatomic) double undoControlMinWidth;
@property (nonatomic) double cutControlMinWidth;
@property (nonatomic) q appearance;
@property (nonatomic) UIFont undoInteractiveControlLabelFont;
@property (nonatomic) UIFont undoStateControlLabelFont;
@property (nonatomic) UIFont undoStateControlUnavailableLabelFont;
- (void)setAppearance:;
- (long long)appearance;
- (void).cxx_destruct;
- (void)setBackgroundBlurEffect:;
- (BOOL)isRTL;
- (id)backgroundBlurEffect;
- (void)setIsRTL:;
- (id)initWithKeyboardAppearance:isRTL:;
- (id)vibrancyEffectForBlur:;
- (void)createDynamicColors;
- (id)undoInteractiveControlLabelFont;
- (id)undoStateControlLabelFont;
- (id)undoStateControlUnavailableLabelFont;
- (id)backgroundVibrancyEffect;
- (void)setBackgroundVibrancyEffect:;
- (id)HUDbackgroundColor;
- (void)setHUDbackgroundColor:;
- (id)HUDShadowColor;
- (void)setHUDShadowColor:;
- (id)buttonGlyphColorEnabled;
- (void)setButtonGlyphColorEnabled:;
- (id)buttonGlyphColorPressed;
- (void)setButtonGlyphColorPressed:;
- (id)buttonGlyphColorDisabled;
- (void)setButtonGlyphColorDisabled:;
- (id)elementBackgroundColor;
- (void)setElementBackgroundColor:;
- (id)elementCoverColor;
- (void)setElementCoverColor:;
- (BOOL)undoRedoIconOnly;
- (void)setUndoRedoIconOnly:;
- (double)undoControlMinWidth;
- (void)setUndoControlMinWidth:;
- (double)cutControlMinWidth;
- (void)setCutControlMinWidth:;
- (BOOL)cutCopyPasteIconOnly;
- (void)setCutCopyPasteIconOnly:;
- (BOOL)tooSmallForInstructionalText;
- (void)setTooSmallForInstructionalText:;
@end
