@interface UIKBGeometry : NSObject
@property (nonatomic) NSString name;
@property (nonatomic) {?=di} x;
@property (nonatomic) {?=di} y;
@property (nonatomic) {?=di} w;
@property (nonatomic) {?=di} h;
@property (nonatomic) {?=di} paddingTop;
@property (nonatomic) {?=di} paddingLeft;
@property (nonatomic) {?=di} paddingBottom;
@property (nonatomic) {?=di} paddingRight;
@property (nonatomic) BOOL explicitlySpecified;
@property (nonatomic) BOOL isTemplate;
- (id)h;
- (BOOL)isTemplate;
- (id)w;
- (id)init;
- (id)shortDescription;
- (void)setName:;
- (void)setX:;
- (id)paddedFrameWithContainingFrame:;
- (id)paddedFrameWithResolvedFrame:;
- (void)setY:;
- (id)paddingBottom;
- (id)paddingRight;
- (id)y;
- (id)paddingTop;
- (BOOL)usesAutomaticMetrics;
- (BOOL)usesPercentages;
- (id)initWithCoder:;
- (unsigned long long)hash;
- (id)overrideGeometry:;
- (id)x;
- (void)setPaddingRight:;
- (id)frame;
- (void)setPaddingBottom:;
- (void)encodeWithCoder:;
- (id)initWithName:rect:padding:;
- (void)setPaddingLeft:;
- (void).cxx_destruct;
- (void)setIsTemplate:;
- (void)setW:;
- (id)initTemplateWithName:rect:padding:;
- (void)setExplicitlySpecified:;
- (void)setPaddingTop:;
- (id)description;
- (id)name;
- (id)frameWithContainingFrame:;
- (id)paddingLeft;
- (void)setH:;
- (BOOL)explicitlySpecified;
- (BOOL)isEqual:;
- (id)copyWithZone:;
+ (id)geometry;
+ (id)geometryWithRect:;
+ (id)geometryWithOriginValue:sizeValue:;
+ (id)codeStringForValue:;
+ (void)performOperations:withScale:;
@end
