@interface UIPrintPreviewPageFetcher : NSObject
@property (nonatomic) NSURL pdfURL;
@property (nonatomic) NSMutableArray cachedInRangeIndexes;
@property (nonatomic) q cachedTotalPageCount;
@property (nonatomic) q cachedSheetNumber;
@property (nonatomic) q numNUpColumns;
@property (nonatomic) q numNUpRows;
@property (nonatomic) {CGSize=dd} pageSize;
@property (nonatomic) {CGSize=dd} previewSize;
@property (nonatomic) BOOL showingPageLayout;
@property (nonatomic) UIPrintPreviewInfo previewInfo;
@property (nonatomic) {CGSize=dd} paperSize;
@property (nonatomic) q cachedTotalSheetCount;
@property (nonatomic) NSMutableDictionary cachedSheetImages;
@property (nonatomic) {CGSize=dd} pageItemSize;
@property (nonatomic) NSArray pageSizes;
@property (nonatomic) double minPageWith;
@property (nonatomic) NSURL quickLookPDFURL;
- (id)init;
- (void)dealloc;
- (void).cxx_destruct;
- (id)previewSize;
- (void)setPreviewSize:;
- (id)pageSize;
- (void)setPaperSize:;
- (id)paperSize;
- (void)setPageSize:;
- (long long)numNUpRows;
- (long long)numNUpColumns;
- (double)_paperAspectRatio;
- (id)quickLookPDFURL;
- (void)setQuickLookPDFURL:;
- (id)previewInfo;
- (void)setPreviewInfo:;
- (id)pdfURL;
- (void)setPdfURL:;
- (void)fetchImageInBackground:completion:;
- (long long)fetchNumberOfItems;
- (long long)sheetIndexToPrintForItemAt:;
- (id)sheetImageForItemAt:;
- (void)resetAllPageImages;
- (void)_resetPageNUp:;
- (long long)_caculateSheetNumber:;
- (void)_resetPagesIndexsInRange;
- (BOOL)_pageIndexIsInRange:printInfo:;
- (BOOL)needDrawPageWithLayout;
- (id)_drawPageContextIntoImage:;
- (id)_drawPageWithLayoutIntoImage:previewInfo:;
- (BOOL)_reversePageOrientation:;
- (BOOL)_mirrorHorizontal:;
- (long long)_pageOffsetForRow:column:printInfo:;
- (id)_pagesLayout:;
- (id)_paperSize:;
- (void)_drawBorderOfType:withScaleFactor:context:pageRect:;
- (void)updatePdfURL:options:completion:;
- (void)resetAllPages:;
- (id)imageSizeAtPageIndex:;
- (id)itemSizeAtPageIndex:flowlayout:;
- (id)sheetSizeAtPageIndex:flowlayout:;
- (id)pageSizeAtPageIndex:flowlayout:;
- (double)caculateHeaderWidth:;
- (double)caculateFooterWidth:;
- (id)quicklookPageThumbnailAtIndex:;
- (void)redrawQuicklookPDF:;
- (void)_removeQuickLookPDFURL;
- (BOOL)showingPageLayout;
- (void)setShowingPageLayout:;
- (long long)cachedTotalSheetCount;
- (void)setCachedTotalSheetCount:;
- (id)cachedSheetImages;
- (void)setCachedSheetImages:;
- (id)pageItemSize;
- (void)setPageItemSize:;
- (id)pageSizes;
- (void)setPageSizes:;
- (double)minPageWith;
- (void)setMinPageWith:;
- (id)cachedInRangeIndexes;
- (void)setCachedInRangeIndexes:;
- (long long)cachedTotalPageCount;
- (void)setCachedTotalPageCount:;
- (long long)cachedSheetNumber;
- (void)setCachedSheetNumber:;
- (void)setNumNUpColumns:;
- (void)setNumNUpRows:;
@end
