@interface UIRepeatedAction : NSObject
@property (nonatomic) NSInvocation invocation;
@property (nonatomic) @ invocationArgument;
@property (nonatomic) NSTimer timer;
@property (nonatomic) double preInvocationDelay;
@property (nonatomic) double invocationDelay;
@property (nonatomic) double repeatedDelay;
@property (nonatomic) BOOL disableRepeat;
@property (nonatomic) BOOL skipInitialFire;
@property (nonatomic) NSObject<UIRepeatedActionDelegate> delegate;
- (id)invocation;
- (id)initWithInvocation:;
- (void)setInvocation:;
- (void)dealloc;
- (void)setDelegate:;
- (BOOL)invoke;
- (void)setTimer:;
- (void)schedule;
- (void)_resetInternalState;
- (id)delegate;
- (void).cxx_destruct;
- (void)reset;
- (id)timer;
- (id)initWithTarget:selector:object:;
- (void)invalidate;
- (void)_repeatedTimerFire;
- (void)_invocationTimerFire;
- (void)_preInvocationTimerFire;
- (void)scheduleWithTarget:selector:object:;
- (void)_adjustInvocationForPhase:;
- (BOOL)_shouldInvokeRepeatedActionForPhase:;
- (void)setPreInvocationDelay:;
- (void)setInvocationDelay:;
- (void)setRepeatedDelay:;
- (double)preInvocationDelay;
- (double)invocationDelay;
- (double)repeatedDelay;
- (BOOL)disableRepeat;
- (void)setDisableRepeat:;
- (BOOL)skipInitialFire;
- (void)setSkipInitialFire:;
- (id)invocationArgument;
- (void)setInvocationArgument:;
+ (id)_invocationForTarget:selector:object:;
+ (id)actionWithTarget:selector:object:;
@end
