@interface UISearchTextField : UITextField
@property (nonatomic) NSValue _searchTextOffsetValue;
@property (nonatomic) BOOL _preventSelectionViewActivation;
@property (nonatomic) BOOL _ignoresDynamicType;
@property (nonatomic) BOOL _needsDelayedSearchControllerPresentation;
@property (nonatomic) UISearchBar _searchBar;
@property (nonatomic) _UISearchSuggestionControllerIOS _suggestionController;
@property (nonatomic) NSArray _dci_searchSuggestions;
@property (nonatomic) NSArray _dci_suggestionsMenuDismissalPassthroughViews;
@property (nonatomic) BOOL _alwaysShowsClearButtonWhenEmpty;
@property (nonatomic) BOOL _alwaysHidesMagnifyingGlassForAccessibilityContentSizeCategory;
@property (nonatomic) NSArray tokens;
@property (nonatomic) UITextRange textualRange;
@property (nonatomic) UIColor tokenBackgroundColor;
@property (nonatomic) BOOL allowsDeletingTokens;
@property (nonatomic) BOOL allowsCopyingTokens;
@property (nonatomic) NSArray searchSuggestions;
@property (nonatomic) UITextField searchTextField;
@property (nonatomic) UIColor searchTextColor;
@property (nonatomic) UIColor searchPlaceholderColor;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)_bookmarkViewRectForBounds:;
- (BOOL)_needsDelayedSearchControllerPresentation;
- (void)didAddTextAttachmentViews:;
- (id)_rangeForSetText;
- (id)_rangeForClearButton;
- (BOOL)_alwaysHidesMagnifyingGlassForAccessibilityContentSizeCategory;
- (id)_clearButtonImageForState:;
- (id)_dci_searchSuggestions;
- (unsigned long long)_characterIndexForTokenTapGestureRecognizer;
- (void)insertAttributedText:;
- (BOOL)allowsCopyingTokens;
- (void)_notifyDidBeginEditing;
- (void)_setPreventSelectionViewActivation:;
- (id)textInputTraits;
- (id)_offsetValueForIcon:;
- (void)_setDeferredSearchSuggestions:;
- (void)_setBottomEffectBackgroundVisible:;
- (BOOL)_shouldIgnoreBaseWritingDirectionChanges;
- (BOOL)canBecomeFocused;
- (BOOL)_alwaysShowsClearButtonWhenEmpty;
- (BOOL)_delegateShouldEndEditing;
- (id)intrinsicContentSize;
- (void)layoutSubviews;
- (id)_rangeOfCustomDraggableObjectsInRange:;
- (void)_setAlwaysHidesMagnifyingGlassForAccessibilityContentSizeCategory:;
- (void)_resetNeedsDelayedSearchControllerPresentation;
- (void)replaceRangeWithTextWithoutClosingTyping:replacementText:;
- (void)_setSuggestionController:;
- (void)_dci_setSearchSuggestions:;
- (void)setText:;
- (id)_createEffectsBackgroundViewWithStyle:applyFilter:;
- (BOOL)_shouldOverrideEditingFont;
- (id)_dci_suggestionsMenuDismissalPassthroughViews;
- (BOOL)_hasContent;
- (void)setDelegate:;
- (id)leftViewRectForBounds:;
- (id)_searchIconViewRectForBounds:;
- (BOOL)_delegateShouldScrollToVisibleWhenBecomingFirstResponder;
- (BOOL)_delegateShouldClear;
- (void)_willAddTokenLayoutView:;
- (void)replaceTextualPortionOfRange:withToken:atIndex:;
- (id)_searchBar;
- (void)replaceRange:withAttributedText:;
- (void)deleteBackward;
- (BOOL)_delegateShouldBeginEditing;
- (void)setTokenBackgroundColor:;
- (id)selectedTokens;
- (void)_setEnabled:animated:;
- (double)_placeholderLabelAlphaForForegroundViewsAlpha:;
- (BOOL)_hasCustomClearButtonImage;
- (BOOL)canResignFirstResponder;
- (BOOL)_textShouldFillFieldEditorHeight;
- (Class)_placeholderLabelClass;
- (BOOL)_becomeFirstResponderWhenPossible;
- (id)initWithCoder:;
- (void)removeTokenAtIndex:;
- (BOOL)_shouldResignOnEditingDidEndOnExit;
- (void)_updateAlphaForMagnifyingGlass;
- (void)setAttributedMarkedText:selectedRange:;
- (void)_updateHelpMessageOverrideWithMessage:;
- (void)_setClearButtonImage:forState:;
- (id)textualRange;
- (void)_highlightedDidChangeAnimated:;
- (void)_applyHighlightedAnimated:;
- (void)tintColorDidChange;
- (void)_setIgnoresDynamicType:;
- (BOOL)_shouldCenterPlaceholder;
- (id)_textRangeForTextStorageRange:;
- (void)_tokenTapGestureRecognized;
- (void)setTokens:;
- (void)insertTextSuggestion:;
- (void)_dci_setSuggestionsMenuDismissalPassthroughViews:;
- (void)_redirectSelectionToAvoidClobberingTokens;
- (void)_didSetFont:;
- (void)_setAlwaysShowsClearButtonWhenEmpty:;
- (id)_placeholderColor;
- (id)_clearButtonSize;
- (BOOL)_shouldDetermineInterfaceStyleTextColor;
- (void)setAllowsDeletingTokens:;
- (void)encodeWithCoder:;
- (id)searchSuggestions;
- (void)_setMagnifyingGlassImage:;
- (void)_copySelectionPopulatingActuallyCopiedTokenCharacterIndexes:;
- (void)_updateDefaultLeftViewForFont:;
- (void)_becomeFirstResponder;
- (id)attributedTextInRange:;
- (BOOL)_delegateShouldChangeCharactersInTextStorageRange:replacementString:delegateCares:;
- (void)didRemoveTextAttachmentViews:;
- (BOOL)canBecomeFirstResponder;
- (BOOL)_supportsDynamicType;
- (void)_defaultInsertTextSuggestion:;
- (void)updateForBackdropStyle:;
- (void)_updateBackgroundViewsAnimated:;
- (void)cut:;
- (id)_availableTextRectForBounds:forEditing:;
- (void)insertText:;
- (void)_setSearchBar:;
- (BOOL)_shouldSuppressSelectionHandles;
- (id)_searchTextOffsetValue;
- (id)editingRectForBounds:;
- (void)copy:;
- (void).cxx_destruct;
- (BOOL)allowsDraggingAttachments;
- (void)searchSuggestionController:didSelectSuggestion:atIndexPath:;
- (void)fieldEditorDidChangeSelection:;
- (void)paste:;
- (void)_hoverGestureChanged:;
- (BOOL)canPerformAction:withSender:;
- (void)_updateBackgroundView:withStyle:filter:;
- (BOOL)_ignoresDynamicType;
- (id)tokenBackgroundColor;
- (void)_suggestionsMenuInteractionWillEndWithAnimator:;
- (void)fieldEditorDidChange:;
- (void)_setBackgroundViewsAlpha:;
- (id)positionOfTokenAtIndex:;
- (void)_setOffsetValue:forIcon:;
- (void)_observeScrollViewDidScroll:;
- (void)_setSearchTextOffetValue:;
- (id)textRectForBounds:;
- (void)_pasteSessionDidFinish:;
- (id)_suggestionController;
- (void)setAllowsCopyingTokens:;
- (BOOL)_isEditingOrHasContent;
- (void)_didRemoveTokenLayoutView:;
- (BOOL)_scalesMagnifyingGlassForDynamicTypeWithFont:;
- (long long)_blurEffectStyle;
- (id)placeholderRectForBounds:;
- (id)insertFilteredText:;
- (id)_initWithFrame:textLayoutManagerEnabled:;
- (void)insertToken:atIndex:;
- (BOOL)gestureRecognizerShouldBegin:;
- (void)_setAnimatesBackgroundCornerRadius:;
- (Class)_canvasViewClass;
- (void)didLayoutTextAttachmentView:inFragmentRect:;
- (BOOL)_shouldSendContentChangedNotificationsIfOnlyMarkedTextChanged;
- (id)clearButtonRectForBounds:;
- (long long)_preferredRenderingModeForPlaceholder;
- (void)_removeEffectsBackgroundViews;
- (id)_newAttributedStringWithToken:;
- (void)setMarkedText:selectedRange:;
- (BOOL)_preventSelectionViewActivation;
- (id)_initWithDeferredSearchIconImageConfiguration;
- (double)_maximumAlphaForLeadingView;
- (long long)_suffixLabelTextAlignment;
- (double)_clearButtonMarginX;
- (id)rightViewRectForBounds:;
- (id)tokensInRange:;
- (id)textInRange:;
- (id)attributedText;
- (void)_updateLeftViewForMagnifyingGlassImage;
- (BOOL)allowsDeletingTokens;
- (BOOL)_shouldHideMagnifyingGlassWhenEditingOrHasContent;
- (id)text;
- (void)_activateSelectionView;
- (void)_animateForFirstResponderChangeWithAnimations:completion:;
- (id)_suffixFrame;
- (void)setSearchSuggestions:;
- (void)__highlightedDidChangeAnimated:;
- (void)_updateAtomViewSelection:;
- (id)_adjustedTextOrEditingRect:forBounds:;
- (void)_clearBackgroundViews;
- (id)_initWithFrame:textLayoutManagerEnabled:defersSearchImageConfiguration:;
- (id)tokens;
- (BOOL)resignFirstResponder;
- (id)_adjustmentsForSearchIconViewRectForBounds:;
- (id)_deferredSearchSuggestions;
- (id)_customDraggableObjectsForRange:;
- (void)replaceRange:withText:;
- (void)_animateForFirstResponderChangeWithAnimations:;
- (void)_notifyDidEndEditing;
+ (id)visualStyleRegistryIdentity;
+ (Class)_fieldEditorClass;
+ (BOOL)_wantsFadedEdges;
+ (Class)_textPasteItemClass;
@end
