@interface UISlidingBarStateRequest : NSObject
@property (nonatomic) BOOL userInitiated;
@property (nonatomic) double leadingWidth;
@property (nonatomic) double leadingOffscreenWidth;
@property (nonatomic) double trailingWidth;
@property (nonatomic) double trailingOffscreenWidth;
@property (nonatomic) double supplementaryWidth;
@property (nonatomic) double supplementaryOffscreenWidth;
@property (nonatomic) double rubberBandInset;
@property (nonatomic) double mainWidth;
- (void)setUserInitiated:;
- (id)init;
- (void)setMainWidth:;
- (double)mainWidth;
- (double)supplementaryWidth;
- (void)setLeadingOffscreenWidth:;
- (double)leadingOffscreenWidth;
- (id)_closestEqualOrLargerState:;
- (void)setRubberBandInset:;
- (void)setLeadingWidth:;
- (id)_closestEqualOrLargerState:returningDistance:;
- (unsigned long long)hash;
- (double)leadingWidth;
- (id)_closestState:returningDistance:;
- (void)setSupplementaryOffscreenWidth:;
- (double)rubberBandInset;
- (void)setTrailingOffscreenWidth:;
- (double)trailingWidth;
- (id)_matchingState:;
- (id)_closestState:;
- (void)setTrailingWidth:;
- (id)description;
- (BOOL)userInitiated;
- (double)supplementaryOffscreenWidth;
- (double)trailingOffscreenWidth;
- (BOOL)isEqual:;
- (void)setSupplementaryWidth:;
- (id)copyWithZone:;
@end
