@interface UISwipeActionButton : UIButton
@property (nonatomic) <_UISwipeActionButtonDelegate> swipeActionButtonDelegate;
@property (nonatomic) UIView backgroundView;
@property (nonatomic) <UISwipeActionVisualStyle> visualStyle;
@property (nonatomic) UIColor defaultBackgroundColor;
@property (nonatomic) UIColor highlightedBackgroundColor;
@property (nonatomic) double buttonWidth;
@property (nonatomic) BOOL autosizes;
@property (nonatomic) UIView sourceView;
- (void)setVisualStyle:;
- (id)titleFont;
- (id)backgroundView;
- (void)setBackgroundColor:;
- (double)defaultButtonWidth;
- (id)sourceView;
- (void)setTitle:forState:;
- (id)defaultBackgroundColor;
- (id)initWithFrame:;
- (void)traitCollectionDidChange:;
- (void)contextMenuInteraction:willDisplayMenuForConfiguration:animator:;
- (void).cxx_destruct;
- (void)setBackgroundView:;
- (void)setHighlighted:;
- (void)contextMenuInteraction:willEndForConfiguration:animator:;
- (id)visualStyle;
- (id)highlightedBackgroundColor;
- (void)setHighlightedBackgroundColor:;
- (id)_allowableContentRectForContentRect:;
- (BOOL)_heightDemandsCompactLayout;
- (unsigned long long)_defaultLayoutForHeight:;
- (long long)_numberOfLinesForTitle:;
- (void)setDefaultBackgroundColor:;
- (double)buttonWidth;
- (id)titleFontOfSize:;
- (double)_minScaleFactorForFont:;
- (double)_minFontSizeForCurrentIdiom;
- (double)_maxFontSizeForCurrentIdiom;
- (double)_horizontalPaddingForCurrentIdiom;
- (double)_titleFontWeightForCurrentIdiom;
- (BOOL)autosizes;
- (void)setAutosizes:;
- (id)swipeActionButtonDelegate;
- (void)setSwipeActionButtonDelegate:;
@end
