@interface UITextInteractionAssistant : NSObject
@property (nonatomic) BOOL _wk_hasFloatingCursor;
@property (nonatomic) UIResponder<UITextInput> view;
@property (nonatomic) UIResponder<UITextInput> textDocument;
@property (nonatomic) UILongPressGestureRecognizer loupeGesture;
@property (nonatomic) UITapGestureRecognizer singleTapGesture;
@property (nonatomic) UIGestureRecognizer doubleTapGesture;
@property (nonatomic) UIGestureRecognizer forcePressGesture;
@property (nonatomic) BOOL inGesture;
@property (nonatomic) UIScrollView scrollView;
@property (nonatomic) BOOL autoscrolled;
@property (nonatomic) {CGPoint=dd} autoscrollUntransformedExtentPoint;
@property (nonatomic) BOOL externalTextInput;
@property (nonatomic) {CGPoint=dd} loupeGestureEndPoint;
@property (nonatomic) BOOL willHandoffLoupeMagnifier;
@property (nonatomic) UITextInteraction interactions;
@property (nonatomic) UITextInteraction externalInteractions;
@property (nonatomic) UITextLinkInteraction linkInteraction;
@property (nonatomic) UITextCursorAssertionController _assertionController;
@property (nonatomic) BOOL expectingCommit;
@property (nonatomic) BOOL needsGestureUpdate;
@property (nonatomic) _UIKeyboardTextSelectionController activeSelectionController;
@property (nonatomic) @ grabberSuppressionAssertion;
@property (nonatomic) @ keyboardSuppressionAssertion;
@property (nonatomic) UIContextMenuInteraction contextMenuInteraction;
@property (nonatomic) <UIContextMenuInteractionDelegate> externalContextMenuInteractionDelegate;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
@property (nonatomic) BOOL cursorBlinks;
@property (nonatomic) BOOL cursorVisible;
@property (nonatomic) BOOL ghostAppearance;
@property (nonatomic) BOOL canShowSelectionCommands;
@property (nonatomic) UIFieldEditor fieldEditor;
@property (nonatomic) BOOL interactiveSelectionDisabled;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (BOOL)_wk_hasFloatingCursor;
- (void)updateAutoscroll:;
- (void)selectionChanged;
- (void)scheduleReplacementsWithOptions:;
- (void)beginFloatingCursorAtPoint:;
- (void)addGestureRecognizersToView:;
- (void)endFloatingCursor;
- (BOOL)isDisplayingMenu;
- (void)detach;
- (id)initWithView:;
- (id)selectionView;
- (void)scrollSelectionToVisible:;
- (BOOL)autoscrolled;
- (void)startAutoscroll:;
- (void)dealloc;
- (void)cancelAutoscroll;
- (BOOL)containerIsBrowserView;
- (void)selectWord;
- (BOOL)inGesture;
- (void)rangeSelectionCanceled;
- (void)clearSelection;
- (void)attach;
- (void)setSelectionWithPoint:;
- (BOOL)requiresImmediateUpdate;
- (id)_asText;
- (id)doubleTapGesture;
- (id)_pointerInteractionDelegate;
- (BOOL)ghostAppearance;
- (BOOL)shouldSuppressSelectionCommands;
- (void)layoutChangedByScrolling:;
- (id)pointerInteraction:regionForRequest:defaultRegion:;
- (void)presentMenuForInputUI:;
- (long long)currentCursorBehavior;
- (void)pointerInteraction:willExitRegion:animator:;
- (void)updateFloatingCursorAtPoint:;
- (void)configureForSelectionMode;
- (BOOL)usesAsynchronousSelectionController;
- (void)pointerInteraction:willEnterRegion:animator:;
- (id)scrollView;
- (void)setGhostAppearance:;
- (BOOL)isDisplayingMenuForInputUI;
- (id)view;
- (BOOL)willHandoffLoupeMagnifier;
- (void)selectAll:;
- (id)interactions;
- (id)contextMenuInteraction;
- (void)setInGesture:;
- (void)loupeGestureWithState:location:translation:velocity:modifierFlags:shouldCancel:;
- (void)configureForPencilHighlightMode;
- (id)pointerInteraction:styleForRegion:;
- (BOOL)containerAllowsSelectionTintOnly;
- (void)configureForPencilDeletionPreviewMode;
- (id)attributedTextInRange:;
- (void)updateFloatingCursorAtPoint:animated:;
- (BOOL)isValid;
- (BOOL)containerAllowsSelection;
- (void).cxx_destruct;
- (void)updateSelectionWithPoint:;
- (id)textSelectionView;
- (void)configureForReplacementMode;
- (void)scrollSelectionToVisible;
- (void)configureForHighlightMode;
- (void)canBeginDragCursor:;
- (void)rangeSelectionStarted:;
- (void)rangeSelectionMoved:withTouchPoint:;
- (Class)selectionInteractionClass;
- (BOOL)wantsLinkInteraction;
- (void)rangeSelectionEnded:;
- (void)willBeginFloatingCursor:;
- (void)dismissMenuForInputUI;
- (void)invalidate;
- (void)detach:;
- (void)updateWithMagnifierTerminalPoint:;
- (void)activate;
- (void)extendSelectionToPoint:;
- (id)keyboardSuppressionAssertion;
- (void)setKeyboardSuppressionAssertion:;
- (id)_assertionController;
- (id)_selectionView;
- (BOOL)hasReplacements;
- (BOOL)viewCouldBecomeEditable:;
- (id)constrainedPoint:;
- (void)autoscrollWillNotStart;
- (id)initWithResponder:;
- (void)clearGestureRecognizers;
- (BOOL)isInteractiveSelectionDisabled;
- (BOOL)canShowSelectionCommands;
- (BOOL)canShowSelectionCommands;
- (id)fieldEditor;
- (id)initWithView:textInteractionMode:;
- (BOOL)needsGestureUpdate;
- (void)setNeedsGestureUpdate:;
- (id)grabberSuppressionAssertion;
- (void)setGrabberSuppressionAssertion:;
- (id)_scrollable;
- (void)setSuppressSystemUI:;
- (void)activateSelection;
- (void)deactivateSelection;
- (id)textDocument;
- (id)externalInteractions;
- (id)linkInteraction;
- (void)setExternalInteractions:;
- (id)activeSelectionController;
- (id)singleTapGesture;
- (id)loupeGesture;
- (id)forcePressGesture;
- (void)setLoupeGestureEndPoint:;
- (id)loupeGestureEndPoint;
- (void)setAutoscrolled:;
- (id)autoscrollUntransformedExtentPoint;
- (void)setAutoscrollUntransformedExtentPoint:;
- (BOOL)externalTextInput;
- (BOOL)expectingCommit;
- (void)setExpectingCommit:;
- (BOOL)containerIsTextField;
- (void)clearGestureRecognizers:;
- (BOOL)useGesturesForEditableContent;
- (id)_computeGestureStateForView:;
- (void)setGestureRecognizers;
- (BOOL)supportsIndirectInteractions;
- (id)externalContextMenuInteractionDelegate;
- (void)setExternalContextMenuInteractionDelegate:;
- (void)setFirstResponderIfNecessary;
- (void)setFirstResponderIfNecessaryActivatingSelection:;
- (void)setWillHandoffLoupeMagnifier;
- (void)resetWillHandoffLoupeMagnifier;
- (void)loupeMagnifierWithState:atPoint:;
- (void)rangedMagnifierWithState:atPoint:;
- (void)lollipopGestureWithState:location:locationOfFirstTouch:forTouchType:;
- (void)commitSelectionWithPoint:;
- (void)extendSelectionToLoupeOrSetToPoint:;
- (void)checkEditabilityAndSetFirstResponderIfNecessary;
- (void)selectWordWithoutShowingCommands;
- (void)showSelectionCommandsForSecondaryClickAtPoint:;
- (void)setAutomaticSelectionCommandsSuppressedForPointerTouchType:;
- (void)notifyKeyboardSelectionChanged;
- (void)_updateSelectionWithPoint:granularity:forceGranularity:;
- (void)selectionAnimationDidStop;
- (void)resignedFirstResponder;
- (void)stashCurrentSelection;
- (void)clearStashedSelection;
- (BOOL)didUseStashedSelection;
- (BOOL)viewConformsToAsynchronousInteractionProtocol;
- (void)willBeginSelectionInteraction;
- (void)didEndSelectionInteraction;
- (BOOL)hasActiveSelectionInteraction;
- (BOOL)cursorBlinks;
- (void)setCursorBlinks:;
- (BOOL)cursorVisible;
- (void)setCursorVisible:;
- (unsigned long long)currentDraggedHandle;
- (BOOL)didPerformLoupeSelectionHandoff;
- (void)scheduleReplacements;
- (void)_updateSelectionInViewIfNeeded:toRange:;
- (void)scheduleChineseTransliteration;
- (id)rangeForTextReplacement:;
- (BOOL)showMultilingualDictationReplacementWithRange:;
- (BOOL)handleMultilingualAlternativeWithString:range:;
- (void)scheduleDictationReplacementsForAlternatives:range:;
- (void)scheduleDictationReplacementsForMultilingualAlternatives:range:;
- (id)generatorForRange:withOptions:;
- (BOOL)scheduleReplacementsForRange:withOptions:;
- (BOOL)swallowsDoubleTapWithScale:atPoint:;
- (void)willStartScrollingOrZooming;
- (void)didEndScrollingOrZooming;
+ (long long)_nextGranularityInCycle:forTouchType:;
@end
