@interface UIWebPDFSearchController : NSObject
@property (nonatomic) NSArray results;
@property (nonatomic) NSString searchString;
@property (nonatomic) NSObject<UIWebPDFSearchControllerDelegate> searchDelegate;
@property (nonatomic) UIPDFDocument documentToSearch;
@property (nonatomic) double documentScale;
@property (nonatomic) Q startingPageIndex;
@property (nonatomic) Q resultLimit;
@property (nonatomic) BOOL searching;
@property (nonatomic) BOOL paused;
- (unsigned long long)resultLimit;
- (BOOL)paused;
- (void)setSearchString:;
- (id)init;
- (void)cancel;
- (void)dealloc;
- (id)searchString;
- (void)setResultLimit:;
- (void)resume;
- (id)results;
- (void)setSearchDelegate:;
- (id)searchDelegate;
- (void)pause;
- (void)search:;
- (void)setResults:;
- (BOOL)searching;
- (void)searchDidBegin:;
- (void)searchDidTimeOut:;
- (void)searchWasCancelled:;
- (void)searchLimitHit:;
- (void)searchDidFinish:;
- (void)search:hasPartialResults:;
- (double)documentScale;
- (unsigned long long)startingPageIndex;
- (void)setStartingPageIndex:;
- (id)documentToSearch;
- (void)setDocumentToSearch:;
- (void)setDocumentScale:;
- (unsigned long long)_actualStartingPageIndex;
- (void)_clearSearchQueue;
@end
