@interface UMUser : NSObject
@property (nonatomic) BOOL shouldFetchAttributes;
@property (nonatomic) I uid;
@property (nonatomic) I gid;
@property (nonatomic) NSString alternateDSID;
@property (nonatomic) NSURL homeDirectoryURL;
@property (nonatomic) NSString username;
@property (nonatomic) NSString givenName;
@property (nonatomic) NSString familyName;
@property (nonatomic) NSString displayName;
@property (nonatomic) NSURL photoURL;
@property (nonatomic) NSString userAuxiliaryString;
@property (nonatomic) @ _photo;
@property (nonatomic) NSDate creationDate;
@property (nonatomic) NSDate lastLoginDate;
@property (nonatomic) NSDate lastRemoteAuthDate;
@property (nonatomic) Q passcodeType;
@property (nonatomic) BOOL isLoginUser;
@property (nonatomic) BOOL isAuditor;
@property (nonatomic) BOOL isDisabled;
@property (nonatomic) BOOL isTransientUser;
@property (nonatomic) BOOL isPrimaryUser;
@property (nonatomic) BOOL isAdminUser;
@property (nonatomic) Q passcodeLockGracePeriod;
@property (nonatomic) NSArray languages;
@property (nonatomic) BOOL hasManagedCredentials;
@property (nonatomic) Q dataQuota;
@property (nonatomic) Q dataUsed;
@property (nonatomic) BOOL hasDataToSync;
@property (nonatomic) NSError errorCausingLogout;
@property (nonatomic) NSError debugErrorCausingLogout;
@property (nonatomic) NSDate firstLoginStartDate;
@property (nonatomic) NSDate firstLoginEndDate;
@property (nonatomic) NSDate lastCachedLoginStartDate;
@property (nonatomic) NSDate lastCachedLoginEndDate;
@property (nonatomic) NSDate lastLogoutStartDate;
@property (nonatomic) NSDate lastLogoutEndDate;
@property (nonatomic) NSArray allUserPersonas;
@property (nonatomic) Q userType;
@property (nonatomic) double passcodeBackOffInterval;
- (BOOL)isTransientUser;
- (id)debugErrorCausingLogout;
- (id)lastLoginDate;
- (id)givenName;
- (unsigned int)gid;
- (BOOL)isAdminUser;
- (void)setIsAuditor:;
- (void)setHasManagedCredentials:;
- (void)setIsAdminUser:;
- (id)alternateDSID;
- (void)setPropertiesFromUser:;
- (id)lastLogoutStartDate;
- (void)setFirstLoginStartDate:;
- (BOOL)isDisabled;
- (id)username;
- (id)init;
- (void)setPasscodeType:;
- (void)setLastCachedLoginEndDate:;
- (void)setAlternateDSID:;
- (void)setLastCachedLoginStartDate:;
- (void)setLastLogoutStartDate:;
- (void)setIsLoginUser:;
- (void)setHomeDirectoryURL:;
- (BOOL)hasDataToSync;
- (void)setHasDataToSync:;
- (unsigned long long)passcodeType;
- (void)setFamilyName:;
- (id)lastCachedLoginStartDate;
- (BOOL)isPrimaryUser;
- (BOOL)isEqualToUser:;
- (unsigned long long)userType;
- (BOOL)isAuditor;
- (void)fetchAttributesIfNeeded;
- (id)errorCausingLogout;
- (unsigned long long)dataQuota;
- (void)setIsPrimaryUser:;
- (void)set_photo:;
- (BOOL)commitChangesWithError:;
- (BOOL)hasManagedCredentials;
- (unsigned long long)dataUsed;
- (void)setShouldFetchAttributes:;
- (void)setCreationDate:;
- (void)setPhotoURL:;
- (void)setLastLogoutEndDate:;
- (void)setIsDisabled:;
- (void)setErrorCausingLogout:;
- (BOOL)inFirstLoginSession;
- (void)setLanguages:;
- (unsigned int)uid;
- (unsigned long long)passcodeLockGracePeriod;
- (void)setUserAuxiliaryString:;
- (id)lastLogoutEndDate;
- (id)firstLoginEndDate;
- (id)languages;
- (id)firstLoginStartDate;
- (BOOL)shouldFetchAttributes;
- (id)lastRemoteAuthDate;
- (id)userAuxiliaryString;
- (void)setFirstLoginEndDate:;
- (id)homeDirectoryURL;
- (void)setLastLoginDate:;
- (void)setLastRemoteAuthDate:;
- (BOOL)commitChanges;
- (void)setDebugErrorCausingLogout:;
- (BOOL)isLoginUser;
- (void)setIsTransientUser:;
- (void)setUid:;
- (void)setUsername:;
- (id)familyName;
- (double)passcodeBackOffInterval;
- (id)allUserPersonas;
- (void)setGivenName:;
- (id)photoURL;
- (id)_diskQuota;
- (void)setDataQuota:;
- (void)setDataUsed:;
- (void)setGid:;
- (void)setPasscodeLockGracePeriod:;
- (id)lastCachedLoginEndDate;
- (BOOL)fetchAttributesWithOutError:;
- (id)userPersonaFromIdentityString:;
- (id)_photo;
- (void)setDisplayName:;
- (id)displayName;
- (void).cxx_destruct;
- (id)description;
- (id)mutableCopyWithZone:;
- (BOOL)isEqual:;
- (id)copyWithZone:;
- (id)creationDate;
+ (id)userWithUID:;
@end
