@interface USOSchemaUSOEntityIdentifier : SISchemaInstrumentationMessage
@property (nonatomic) I nodeIndex;
@property (nonatomic) BOOL hasNodeIndex;
@property (nonatomic) NSString identifierNamespace;
@property (nonatomic) BOOL hasIdentifierNamespace;
@property (nonatomic) double probability;
@property (nonatomic) BOOL hasProbability;
@property (nonatomic) NSInteger sourceNluComponent;
@property (nonatomic) BOOL hasSourceNluComponent;
@property (nonatomic) NSInteger backingAppBundleType;
@property (nonatomic) BOOL hasBackingAppBundleType;
@property (nonatomic) I groupIndex;
@property (nonatomic) BOOL hasGroupIndex;
@property (nonatomic) I interpretationGroup;
@property (nonatomic) BOOL hasInterpretationGroup;
@property (nonatomic) NSData jsonData;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (unsigned int)groupIndex;
- (id)identifierNamespace;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (double)probability;
- (void)setProbability:;
- (void)setHasProbability:;
- (BOOL)hasProbability;
- (void)deleteProbability;
- (void)setNodeIndex:;
- (BOOL)hasNodeIndex;
- (void)setHasNodeIndex:;
- (void)deleteNodeIndex;
- (BOOL)hasIdentifierNamespace;
- (void)deleteIdentifierNamespace;
- (void)setSourceNluComponent:;
- (BOOL)hasSourceNluComponent;
- (void)setHasSourceNluComponent:;
- (void)deleteSourceNluComponent;
- (void)setBackingAppBundleType:;
- (BOOL)hasBackingAppBundleType;
- (void)setHasBackingAppBundleType:;
- (void)deleteBackingAppBundleType;
- (void)setGroupIndex:;
- (BOOL)hasGroupIndex;
- (void)setHasGroupIndex:;
- (void)deleteGroupIndex;
- (void)setInterpretationGroup:;
- (BOOL)hasInterpretationGroup;
- (void)setHasInterpretationGroup:;
- (void)deleteInterpretationGroup;
- (unsigned int)nodeIndex;
- (void)setIdentifierNamespace:;
- (int)sourceNluComponent;
- (int)backingAppBundleType;
- (unsigned int)interpretationGroup;
- (void)setHasIdentifierNamespace:;
@end
