@interface USOSchemaUSONode : SISchemaInstrumentationMessage
@property (nonatomic) I usoElementId;
@property (nonatomic) BOOL hasUsoElementId;
@property (nonatomic) I usoVerbElementId;
@property (nonatomic) BOOL hasUsoVerbElementId;
@property (nonatomic) NSString entityLabel;
@property (nonatomic) BOOL hasEntityLabel;
@property (nonatomic) NSString verbLabel;
@property (nonatomic) BOOL hasVerbLabel;
@property (nonatomic) NSData jsonData;
- (id)initWithJSON:;
- (id)suppressMessageUnderConditions;
- (id)initWithDictionary:;
- (void)writeTo:;
- (id)jsonData;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (BOOL)readFrom:;
- (id)dictionaryRepresentation;
- (BOOL)isEqual:;
- (void)setUsoElementId:;
- (BOOL)hasUsoElementId;
- (void)setHasUsoElementId:;
- (void)deleteUsoElementId;
- (unsigned int)usoElementId;
- (void)setUsoVerbElementId:;
- (BOOL)hasUsoVerbElementId;
- (void)setHasUsoVerbElementId:;
- (void)deleteUsoVerbElementId;
- (BOOL)hasEntityLabel;
- (void)deleteEntityLabel;
- (BOOL)hasVerbLabel;
- (void)deleteVerbLabel;
- (unsigned int)usoVerbElementId;
- (id)entityLabel;
- (void)setEntityLabel:;
- (id)verbLabel;
- (void)setVerbLabel:;
- (void)setHasEntityLabel:;
- (void)setHasVerbLabel:;
@end
