@interface VCAudioTransmitter : NSObject
@property (nonatomic) VCAudioTierPicker audioTierPicker;
@property (nonatomic) VCAudioPayloadConfig currentAudioPayloadConfig;
@property (nonatomic) VCPacketBundler audioBundler;
@property (nonatomic) VCAudioTier currentAudioTier;
@property (nonatomic) NSInteger audioTxBitrate;
@property (nonatomic) NSInteger actualAudioSendingBitrate;
@property (nonatomic) I lastSentAudioSampleTime;
@property (nonatomic) I sentAudioBytes;
@property (nonatomic) I encodedBytes;
@property (nonatomic) I redNumPayloads;
@property (nonatomic) I redMaxDelay20ms;
@property (nonatomic) NSDictionary dtxMetrics;
@property (nonatomic) NSInteger operatingMode;
@property (nonatomic) C inputMeter;
@property (nonatomic) <VCAudioTransmitterDelegate> delegate;
@property (nonatomic) BOOL isRedEnabled;
@property (nonatomic) BOOL ignoreSilence;
@property (nonatomic) I targetBitrate;
@property (nonatomic) I rateChangeCounter;
@property (nonatomic) {?=I[5I]Id{CGSize=dd}dIdII} currentChannelMetrics;
@property (nonatomic) BOOL isAudioStalled;
@property (nonatomic) NSInteger qualityIndicator;
@property (nonatomic) I maxIDSStreamIdCount;
@property (nonatomic) NSArray supportedNumRedundantPayload;
@property (nonatomic) BOOL sendActiveVoiceOnly;
@property (nonatomic) BOOL currentDTXEnable;
@property (nonatomic) C mediaControlInfoVersion;
@property (nonatomic) BOOL useWiFiTiers;
@property (nonatomic) BOOL periodicReportingEnabled;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (void)dealloc;
- (void)start;
- (id)initWithConfig:;
- (void)setDelegate:;
- (void)stop;
- (id)delegate;
- (int)operatingMode;
- (void)setOperatingMode:;
- (void)setQualityIndicator:;
- (int)qualityIndicator;
- (unsigned int)targetBitrate;
- (void)processNWConnectionNotification:;
- (void)pushAudioSamples:;
- (void)gatherRealtimeStats:;
- (void)setTargetBitrate:;
- (void)handleActiveConnectionChange:;
- (BOOL)sendActiveVoiceOnly;
- (void)setSendActiveVoiceOnly:;
- (void)setCurrentDTXEnable:;
- (int)actualAudioSendingBitrate;
- (void)redundancyController:redundancyPercentageDidChange:;
- (BOOL)isCurrentDTXEnabled;
- (unsigned int)lastSentAudioSampleTime;
- (unsigned char)mediaControlInfoVersion;
- (void)setMediaControlInfoVersion:;
- (void)redundancyController:redundancyIntervalDidChange:;
- (id)packetsPerBundle;
- (void)setInputMeter:;
- (unsigned char)inputMeter;
- (id)dtxMetrics;
- (unsigned int)rateChangeCounter;
- (void)registerReportingTask;
- (unsigned int)redNumPayloads;
- (unsigned int)redMaxDelay20ms;
- (void)setMaxIDSStreamIdCount:;
- (unsigned int)maxIDSStreamIdCount;
- (BOOL)isRedEnabled;
- (BOOL)ignoreSilence;
- (void)setStreamIDs:;
- (id)supportedNumRedundantPayload;
- (void)setSupportedNumRedundantPayload:;
- (unsigned int)redundancyControllerModeForOperatingMode:isRedEnabled:;
- (void)initAudioValues;
- (id)currentAudioPayloadConfig;
- (BOOL)shouldUpdateCodecBitrate:;
- (BOOL)shouldUpdateCodecBandwidth:;
- (BOOL)isCodecModeChangeRequestValid:;
- (void)handleCodecModeChangeEvent:didUpdateBandwidth:didUpdateBitrate:;
- (BOOL)sendCodecModeChangeEvent:;
- (void)setCellTech:remoteCellular:isIPV6:audioCap:;
- (BOOL)setupEncoderBuffer;
- (BOOL)setupAudio:;
- (void)updateAudioTxRate;
- (void)reportRedundancyConfigChange;
- (float)nextAudioInterval:;
- (BOOL)shouldUseDtx;
- (id)usedAudioPayloadForType:;
- (void)removeUnusedAudioPayloads;
- (BOOL)setupAudioEncoders;
- (BOOL)allocateLastInputSampleBuffer:;
- (unsigned int)maximumSamplesPerFrame;
- (void)encodeBundleAndSendAudio:sampleCount:;
- (int)encodeAudio:numInputSamples:outputBytes:numOutputBytes:withPayload:isTalking:;
- (BOOL)chooseAudioNetworkBitrate;
- (int)sendAudioBundle:atTimeStamp:nextInterval:;
- (int)bundleAndSendSamples:numEncodedBytes:withPayload:timeStamp:bufferedSamples:hasNewSamples:voiceActivity:priority:;
- (void)setupAudioHeaderSize;
- (BOOL)setupAudioTierPicker;
- (void)updateAudioTxBitrate;
- (void)useAudioPayload:withBitrate:;
- (void)useAudioTier:;
- (BOOL)sendAudioPacketImpl:bytesSent:;
- (id)generateControlInfo;
- (int)sendSframeEncryptedAudioPacket:;
- (int)sendAudioPacket:;
- (int)sendAudioPacket:payloadLength:payloadType:timestamp:priority:marker:nextInterval:padding:paddingLength:sendReport:;
- (unsigned int)sentAudioBytes;
- (unsigned int)sentAudioBytesShort;
- (unsigned int)encodedBytes;
- (void)logTierInfo:;
- (void)setRedNumPayloads:withMaxDelay:;
- (void)reportRTCPPacket;
- (void)audioIssueDetectorCreateAndConfigure;
- (void)audioIssueDetectorProcessFrame:payloadType:length:bitRate:;
- (void)audioIssueDetectorStopAndFinalize;
- (void)reportAWDMetrics;
- (id)audioBundler;
- (id)currentAudioTier;
- (int)audioTxBitrate;
- (void)setRateChangeCounter:;
- (BOOL)isAudioStalled;
- (void)setIsAudioStalled:;
- (id)currentChannelMetrics;
- (void)setCurrentChannelMetrics:;
- (BOOL)useWiFiTiers;
- (void)setUseWiFiTiers:;
- (id)audioTierPicker;
- (void)setAudioTierPicker:;
- (BOOL)periodicReportingEnabled;
- (void)setPeriodicReportingEnabled:;
@end
