@interface VCPayloadUtils : NSObject
+ (BOOL)isUseCaseWatchContinuity:primaryPayload:;
+ (BOOL)isPayloadSupportedInFaceTime:;
+ (unsigned int)sampleRateForPayload:;
+ (unsigned int)sampleRateForCodecBandwidth:;
+ (unsigned int)audioCodecTypeForPayload:;
+ (unsigned int)codecSamplesPerFrameForPayload:blockSize:;
+ (BOOL)canSetBitrateForPayload:;
+ (int)codecBandwidthForPayload:;
+ (id)codecModesForAMR8kHz;
+ (id)codecModesForAMR16kHz;
+ (id)codecModesForEVS8kHz;
+ (id)codecModesForEVS16kHz;
+ (id)codecModesForEVS32kHz;
+ (id)supportedCodecModesForBandwidth:payload:;
+ (id)allowedBitratesForPayload:supportedBitrates:supportedBandwidths:;
+ (int)codecRateModeForDesiredANBR:payload:supportedBitrates:supportedBandwidths:;
+ (BOOL)isEVSCodecModeSupported:forBandwidth:;
+ (BOOL)isAMRCodecModeSupported:forBandwidth:;
+ (BOOL)isCodecModeSupported:forBandwidth:withPayload:;
+ (BOOL)shouldUseCookieForPayload:;
+ (BOOL)canBundleExternallyForPayload:forBundlingScheme:operatingMode:;
+ (unsigned int)internalBundleFactorForPayload:;
+ (BOOL)shouldEnablePacketSizeLimitForPayload:;
+ (float)qualityForPayload:forBitrate:;
+ (long long)codecTypeForPayload:;
+ (int)payloadForCodecType:;
+ (unsigned int)bitrateForCodecType:mode:;
+ (BOOL)supportsCodecRateModesForCodecType:;
+ (BOOL)supportsCodecBandwidthUpdateForCodecType:;
+ (unsigned int)bitrateForAMRCodecMode:;
+ (unsigned int)bitrateForAMRWBCodecMode:;
+ (unsigned int)bitrateForEVSCodecMode:;
+ (long long)ctAudioCodecTypeForMediaStreamCodec:;
+ (long long)ctAudioCodecEVSBandwidthForAudioCodecBandwidth:;
+ (long long)ctAudioCodecEVSBitrateForBitrate:;
+ (int)vcAudioCodecBandwidthForAudioCodecBandwidth:;
+ (int)audioCodecBandwidthForVCAudioCodecBandwidth:;
@end
