@interface VCVideoReceiverDefault : VCVideoReceiverBase
@property (nonatomic) {tagVCVideoReceiverConfig=I[9{tagVCVideoReceiverStreamConfig={tagVCVideoReceiverStreamIDInfo=SSSI[9S][9S]}^{tagHANDLE}^{__CFDictionary}BSCBB^{tagVCCryptor}^v^viB}]iiqiiiIiiiiiiBBBBd^v^?^?^?^?^?^?^?QBSB^{tagWRMMetricsInfo}IBBBBBBBBBBBBBB^vBBIBBS^{tagVCJBTargetEstimatorSynchronizer}^{__CFString}^{__CFString}IBBBiBB{tagVCNACKGeneratorStoreBagsConfig=CffB[4f][4f]}B} videoReceiverConfig;
@property (nonatomic) VideoAttributes remoteVideoAttributes;
@property (nonatomic) NSInteger mode;
@property (nonatomic) BOOL shouldUpdateRemoteScreenAttributes;
@property (nonatomic) BOOL shouldEnableFaceZoom;
@property (nonatomic) BOOL shouldEnableMLEnhance;
- (void)dealloc;
- (void)setFeedbackDelegate:;
- (int)mode;
- (void)setMode:;
- (double)roundTripTime;
- (void)setSynchronizer:;
- (void)pauseVideo;
- (id)remoteVideoAttributes;
- (void)startVideo;
- (void)stopVideo;
- (void)handleActiveConnectionChange:;
- (void)setTargetStreamID:;
- (void)setEnableCVO:cvoExtensionID:;
- (void)setEnableRateAdaptation:maxBitrate:minBitrate:adaptationInterval:;
- (void)updateSourcePlayoutTimestamp:;
- (void)rtcpSendIntervalElapsed;
- (unsigned int)lastDisplayedFrameRTPTimestamp;
- (void)setShouldEnableFaceZoom:;
- (void)collectChannelMetrics:interval:;
- (double)lastReceivedVideoRTPPacketTime;
- (double)lastReceivedVideoRTCPPacketTime;
- (float)lastLastVideoStallDuration;
- (id)initWithConfig:delegate:reportingAgent:statisticsCollector:transmitterHandle:;
- (int)oneToOneStreamIndex;
- (void)setUpRemoteAspectRatios;
- (void)setUpRemoteAspectRatiosForPayload:;
- (void)setUpRemoteAspectRatiosFromFreatureListString:;
- (BOOL)initializeDisplayLink;
- (void)cleanUpDisplayLink;
- (void)handleRemoteFrame:timestamp:cameraStatusBits:;
- (void)handleSampleBuffer:;
- (void)handleRequestingKeyFrameGenerationWithStreamID:firType:;
- (void)handleKeyFrameRequestWithSizeAndFistMBs:count:didReceiveRTCPFB:didReceiveFIR:;
- (void)didSwitchFromStreamID:toStreamID:;
- (void)setShouldEnableMLEnhance:;
- (void)setRemoteVideoAttributes:;
- (BOOL)shouldEnableFaceZoom;
- (BOOL)shouldEnableMLEnhance;
- (BOOL)shouldUpdateRemoteScreenAttributes;
- (void)setShouldUpdateRemoteScreenAttributes:;
- (id)videoReceiverConfig;
- (void)setVideoReceiverConfig:;
@end
