@interface VCVideoStreamRateAdaptation : NSObject
@property (nonatomic) ^{tagHANDLE=i} rtpHandle;
@property (nonatomic) double packetLossPercentage;
@property (nonatomic) double roundTripTime;
@property (nonatomic) double owrd;
@property (nonatomic) double nowrd;
@property (nonatomic) double nowrdShort;
@property (nonatomic) double nowrdAcc;
@property (nonatomic) I operatingBitrate;
@property (nonatomic) I sendTmmbrBitrate;
@property (nonatomic) BOOL isOperatingAtMaxBitrate;
@property (nonatomic) BOOL isOperatingAtMinBitrate;
@property (nonatomic) double maxOWRD;
- (id)className;
- (void)dealloc;
- (double)roundTripTime;
- (double)owrd;
- (double)nowrd;
- (double)nowrdShort;
- (double)nowrdAcc;
- (void)reportingVideoStreamEvent:;
- (void)setEnableRateAdaptation:maxBitrate:minBitrate:adaptationInterval:;
- (id)initWithRTPHandle:reportingAgent:receiverStats:dumpID:reportingParentID:;
- (BOOL)runVideoStreamRateAdaptation;
- (void)receivedTMMBN:;
- (void)updateVideoStall:withStallDuration:;
- (void)updateRTPReceiveWithTimestamp:sampleRate:time:size:endOfFrame:;
- (void)setOperatingBitrate:;
- (unsigned int)averageReceivedBitrate;
- (void)scheduleTMMBR:;
- (id)rtpHandle;
- (BOOL)isOperatingAtMinBitrate;
- (BOOL)isOperatingAtMaxBitrate;
- (double)packetLossPercentage;
- (double)maxOWRD;
- (void)setMaxOWRD:;
- (unsigned int)sendTmmbrBitrate;
- (unsigned int)operatingBitrate;
@end
