@interface VEAudioEffectUnit : IESMMObject
@property (nonatomic) IESMMAudioLimiter limiterFilter;
@property (nonatomic) IESMMAudioPitch pitchFilter;
@property (nonatomic) IESMMAudioPitchV2 pitchFilterV2;
@property (nonatomic) IESMMAudioFade fadeFilter;
@property (nonatomic) IESMMAudioPitchSpeed speedFilter;
@property (nonatomic) IESMMAudioScratching audioScratchFilter;
@property (nonatomic) IESMMAudioDenoise denoiseFilter;
@property (nonatomic) IESMMAudioBalance balanceFilter;
@property (nonatomic) IESMMAudioDetection detectionFilter;
@property (nonatomic) IESMMAudioDSP dspFilter;
@property (nonatomic) IESMMAudioSamiFilter samiDenoiseFilter;
@property (nonatomic) IESMMAudioSamiProcessorFilter samiPitchFilter;
@property (nonatomic) q channels;
@property (nonatomic) double sampleRate;
@property (nonatomic) VEAudioConfig audioConfig;
@property (nonatomic) double audioKeyFrameVolume;
- (void)setAudioConfig:;
- (id)detectionFilter;
- (id)samiPitchFilter;
- (void)setPitchFilter:;
- (void)setSpeedFilter:;
- (id)audioConfig;
- (double)audioKeyFrameVolume;
- (id)audioScratchFilter;
- (id)balanceFilter;
- (id)denoiseFilter;
- (id)dspFilter;
- (id)fadeFilter;
- (double)getCurrentVolumnAtPts:;
- (double)getCurrentVolumnAtPts:withVolumeConfig:;
- (id)limiterFilter;
- (id)pitchFilter;
- (id)pitchFilterV2;
- (int)processBalance:samples:filter:;
- (int)processCurveSpeed:samples:maxSamples:filter:curveRatio:;
- (int)processDSP:samples:filter:;
- (int)processDenoise:samples:filter:;
- (int)processDetection:samples:filter:;
- (void)processFade:samples:filter:frameTime:;
- (unsigned int)processIntervalInput:inputSamples:bufferMaxSamples:frameTime:curveRatio:;
- (int)processPitch:samples:filter:;
- (int)processPitchV2:samples:filter:atTime:;
- (int)processSamiFtgru:samples:filter:;
- (int)processSamiPitch:samples:filter:atTime:;
- (int)processSpeed:samples:maxSamples:filter:;
- (void)processVolume:samples:filter:frameTime:;
- (id)samiDenoiseFilter;
- (void)setAudioKeyFrameVolume:;
- (void)setAudioScratchFilter:;
- (void)setBalanceFilter:;
- (void)setDenoiseFilter:;
- (void)setDetectionFilter:;
- (void)setDspFilter:;
- (void)setFadeFilter:;
- (void)setLimiterFilter:;
- (void)setPitchFilterV2:;
- (void)setSamiDenoiseFilter:;
- (void)setSamiPitchFilter:;
- (id)speedFilter;
- (long long)channels;
- (void)seekToTime:;
- (double)sampleRate;
- (id)initWithConfig:;
- (void).cxx_destruct;
- (void)setChannels:;
- (void)reset;
- (void)setSampleRate:;
@end
