@interface VEVideoFFmpeg : VEVideoReader
@property (nonatomic) NSError error;
@property (nonatomic) VEFFmpegReaderUnit readerUnit;
@property (nonatomic) VECompileVTDecoderUnit decodeUnit;
@property (nonatomic) Q asyncThreadStatus;
@property (nonatomic) VEVideoPlayAsyncQueue videoAyncQue;
@property (nonatomic) ^{__CVBuffer=} lastPixelBuffer;
@property (nonatomic) {?=qiIq} lastTime;
@property (nonatomic) q lastBufferSrcPts;
@property (nonatomic) {?=qiIq} lastReturnVideoTime;
@property (nonatomic) double lastSysTemTime;
@property (nonatomic) {?=qiIq} lastDuration;
@property (nonatomic) VEVideoConfig config;
@property (nonatomic) BOOL seekReq;
@property (nonatomic) BOOL isPreSeek;
@property (nonatomic) {?=qiIq} seekTime;
@property (nonatomic) {?=qiIq} lastSeekTime;
@property (nonatomic) NSObject<OS_dispatch_queue> decodeQueue;
@property (nonatomic) q seekReqCount;
@property (nonatomic) q seekCacheCount;
@property (nonatomic) q maxCacheCount;
@property (nonatomic) NSCondition condition;
@property (nonatomic) {?=qiIq} lastRequestTime;
@property (nonatomic) ^{opaqueCMFormatDescription=} vtDesc;
@property (nonatomic) BOOL isFastSeeking;
@property (nonatomic) double lastSeekTimestamp;
@property (nonatomic) VECurveTransUtils curveTransUtils;
@property (nonatomic) BOOL isPlaying;
@property (nonatomic) BOOL needForceSeek;
@property (nonatomic) BOOL enableSeekOpt;
@property (nonatomic) BOOL enableSeekOpt2;
@property (nonatomic) BOOL isAppActive;
@property (nonatomic) BOOL enableDecoderPreReleaseOpt;
@property (nonatomic) BOOL isPrepared;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)curveTransUtils;
- (double)getAvgFrameRate;
- (id)lastPixelBuffer;
- (void)p_releaseVtDesc;
- (void)setDecodeQueue:;
- (id)lastRequestTime;
- (void)p_updateLastPixelBuffer:atTime:;
- (BOOL)seekReq;
- (unsigned long long)asyncThreadStatus;
- (id)decodeQueue;
- (id)decodeUnit;
- (BOOL)enableDecoderPreReleaseOpt;
- (BOOL)enableSeekOpt;
- (BOOL)enableSeekOpt2;
- (id)getAllIFrameTimeStamp;
- (BOOL)isFastSeeking;
- (BOOL)isHitCache:;
- (BOOL)isPreSeek;
- (long long)lastBufferSrcPts;
- (id)lastReturnVideoTime;
- (id)lastSeekTime;
- (double)lastSeekTimestamp;
- (double)lastSysTemTime;
- (long long)maxCacheCount;
- (BOOL)needForceSeek;
- (BOOL)needSeekFlush;
- (id)p_convertTimeLineToVideoTime:;
- (id)p_convertVideoTimeToTimeLine:;
- (void)p_setVtDesc:;
- (void)p_updateVideoBufferWithLast:;
- (void)processTask;
- (id)readerUnit;
- (long long)seekCacheCount;
- (long long)seekReqCount;
- (void)seekToTimeProcess:;
- (void)setAsyncThreadStatus:;
- (void)setCurveTransUtils:;
- (void)setDecodeUnit:;
- (void)setEnableDecoderPreReleaseOpt:;
- (void)setEnableSeekOpt2:;
- (void)setEnableSeekOpt:;
- (void)setIsFastSeeking:;
- (void)setIsPreSeek:;
- (void)setLastBufferSrcPts:;
- (void)setLastDuration:;
- (void)setLastPixelBuffer:;
- (void)setLastRequestTime:;
- (void)setLastReturnVideoTime:;
- (void)setLastSeekTime:;
- (void)setLastSeekTimestamp:;
- (void)setLastSysTemTime:;
- (void)setMaxCacheCount:;
- (void)setNeedForceSeek:;
- (void)setReaderUnit:;
- (void)setSeekCacheCount:;
- (void)setSeekReq:;
- (void)setSeekReqCount:;
- (void)setVideoAyncQue:;
- (void)setVtDesc:;
- (void)startThread;
- (void)unPrepare;
- (void)updateSampleDataPts:;
- (id)videoAyncQue;
- (id)vtDesc;
- (id)condition;
- (void)becomeActive;
- (void)seekToTime:;
- (void)setCondition:;
- (BOOL)isPlaying;
- (void)dealloc;
- (void)setIsPlaying:;
- (void)play;
- (BOOL)isPrepared;
- (void)setConfig:;
- (id)initWithConfig:;
- (void)setError:;
- (void)stop;
- (void)prepare;
- (id)error;
- (void)enterBackground;
- (void).cxx_destruct;
- (void)enterForeground;
- (void)pause;
- (void)setSeekTime:;
- (id)config;
- (void)setLastTime:;
- (id)seekTime;
- (id)lastTime;
- (void)resignActive;
- (id)lastDuration;
- (void)setIsAppActive:;
- (BOOL)isAppActive;
- (void)stopThread;
- (void)updateVideoConfig:;
- (void)memoryWarning;
- (id)copySampleBufferAtTime:;
- (void)setIsPrepared:;
@end
