@interface VKAnalyticsVisualSearchEvent : VKAnalyticsEvent
@property (nonatomic) q eventType;
@property (nonatomic) BOOL didInteractWithResultItem;
@property (nonatomic) NSCountedSet allItemDomains;
@property (nonatomic) q itemCount;
@property (nonatomic) q focalPointItemCount;
@property (nonatomic) VKCVisualSearchResultItem interactedItem;
@property (nonatomic) double serverProcessingTime;
@property (nonatomic) BOOL serverResultWasCached;
@property (nonatomic) q nonFocalPointItemCount;
@property (nonatomic) NSString itemDomain;
@property (nonatomic) BOOL itemHasFocalPoint;
- (long long)itemCount;
- (long long)eventType;
- (void)setEventType:;
- (id)eventKey;
- (long long)type;
- (id)coreAnalyticsDictionary;
- (void).cxx_destruct;
- (id)description;
- (void)setItemCount:;
- (id)initWithType:items:interactedItem:serverProcessingTime:customIdentifier:;
- (void)processItems:;
- (long long)nonFocalPointItemCount;
- (id)itemDomain;
- (BOOL)itemHasFocalPoint;
- (BOOL)didInteractWithResultItem;
- (void)setDidInteractWithResultItem:;
- (id)allItemDomains;
- (void)setAllItemDomains:;
- (long long)focalPointItemCount;
- (void)setFocalPointItemCount:;
- (double)serverProcessingTime;
- (void)setServerProcessingTime:;
- (BOOL)serverResultWasCached;
- (void)setServerResultWasCached:;
- (id)interactedItem;
- (void)setInteractedItem:;
@end
