@interface VKCActionInfoView : VKPlatformView
@property (nonatomic) UIView containerView;
@property (nonatomic) UIView textButtonContainer;
@property (nonatomic) UIView visualSearchContainer;
@property (nonatomic) UIView moreButtonContainer;
@property (nonatomic) VKImageAnalysisButton liveTextButton;
@property (nonatomic) VKCVisualSearchCornerView visualSearchCornerView;
@property (nonatomic) VKCActionInfoButton moreButton;
@property (nonatomic) VKCActionInfoViewLayoutContext layoutContext;
@property (nonatomic) NSArray allViews;
@property (nonatomic) BOOL _quickActionsHidden;
@property (nonatomic) BOOL automaticVisualRectLayoutDisabled;
@property (nonatomic) BOOL alignQuickActionsWithVerticalCenter;
@property (nonatomic) double preferredQuickActionButtonHeight;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} visibleImageRect;
@property (nonatomic) BOOL wantsTranslucentActionInfoButtons;
@property (nonatomic) @? quickActionConfigurationUpdateHandler;
@property (nonatomic) BOOL isShowingSingleTapMoreButtonMenu;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} contentsRect;
@property (nonatomic) {CGRect={CGPoint=dd}{CGSize=dd}} normalizedVisibleRect;
@property (nonatomic) NSArray quickActions;
@property (nonatomic) BOOL quickActionsDisabled;
@property (nonatomic) BOOL liveTextButtonDisabled;
@property (nonatomic) BOOL visualSearchCornerViewDisabled;
@property (nonatomic) BOOL layoutUpdatesSuspended;
@property (nonatomic) {UIEdgeInsets=dddd} edgeInsets;
@property (nonatomic) BOOL shouldAnimateQuickActionVisibilityChanges;
- (void)setEdgeInsets:;
- (id)contentsRect;
- (void)updateLayoutIfNecessary;
- (void)setShouldAnimateQuickActionVisibilityChanges:;
- (BOOL)liveTextButtonDisabled;
- (BOOL)layoutUpdatesSuspended;
- (void)set_quickActionsHidden:;
- (void)setQuickActionsDisabled:;
- (BOOL)wantsTranslucentActionInfoButtons;
- (void)setVisualSearchCornerViewDisabled:;
- (BOOL)alignQuickActionsWithVerticalCenter;
- (id)sizeForView:scale:;
- (BOOL)containsInteractableItemAtPoint:;
- (void)layoutSubviews;
- (void)setWantsTranslucentActionInfoButtons:;
- (id)containerView;
- (BOOL)quickActionsDisabled;
- (void)setContainerView:;
- (id)layoutContext;
- (void)setIsShowingSingleTapMoreButtonMenu:;
- (id)configureView:isLeading:container:layoutContext:;
- (BOOL)isInteractableView:atPoint:;
- (id)visualSearchContainer;
- (id)createContainerForView:;
- (id)visibleImageRect;
- (void)setVisualSearchContainer:;
- (BOOL)isShowingSingleTapMoreButtonMenu;
- (id)visualSearchCornerView;
- (void)layoutContainerView;
- (void)updateFramesForContext:;
- (id)hitTest:withEvent:;
- (id)edgeInsets;
- (void)setMoreButton:;
- (void)updateMoreButtonMenuForContext:;
- (void)setVisualSearchCornerView:;
- (double)preferredQuickActionButtonHeight;
- (id)buildMoreButtonMenuFromQuickActions:moreButton:;
- (id)normalizedVisibleRect;
- (void)adjustContextToFitWidth:;
- (id)moreButtonContainer;
- (void)traitCollectionDidChange:;
- (id)quickActions;
- (void)setLayoutContext:;
- (void)setLiveTextButton:;
- (void)setAlignQuickActionsWithVerticalCenter:;
- (BOOL)_quickActionsHidden;
- (id)initWithLiveTextButton:cornerView:;
- (id)textButtonContainer;
- (BOOL)automaticVisualRectLayoutDisabled;
- (void)setLayoutUpdatesSuspended:;
- (void)setMoreButtonContainer:;
- (BOOL)shouldAnimateQuickActionVisibilityChanges;
- (void)setPreferredQuickActionButtonHeight:;
- (void)setContentsRect:;
- (void).cxx_destruct;
- (id)moreButton;
- (void)setQuickActionConfigurationUpdateHandler:;
- (id)quickActionConfigurationUpdateHandler;
- (void)setQuickActions:;
- (void)setHidden:;
- (void)_applyConfigurationUpdateHandlerToQuickActions;
- (void)setTextButtonContainer:;
- (void)setNormalizedVisibleRect:;
- (id)allViews;
- (void)showMoreButtonMenu:;
- (void)processView:hasContent:isLeading:layoutContext:;
- (void)setAutomaticVisualRectLayoutDisabled:;
- (BOOL)visualSearchCornerViewDisabled;
- (void)setLiveTextButtonDisabled:;
- (id)liveTextButton;
@end
