@interface WiFiP2PAWDLStateMonitor : NSObject
@property (nonatomic) @? stateUpdatedHandler;
@property (nonatomic) @? statisticsUpdatedHandler;
@property (nonatomic) @? lowLatencyStatisticsUpdatedHandler;
@property (nonatomic) @? realtimeModeUpdatedHandler;
@property (nonatomic) @? threadCoexistenceEventHandler;
@property (nonatomic) @? softAPChannelChangedEventHandler;
@property (nonatomic) @? channelSequenceUpdatedEventHandler;
@property (nonatomic) @? serviceAvailabilityUpdatedHandler;
@property (nonatomic) Q hash;
@property (nonatomic) # superclass;
@property (nonatomic) NSString description;
@property (nonatomic) NSString debugDescription;
- (id)init;
- (void)threadCoexistenceEvent:;
- (id)lowLatencyStatisticsUpdatedHandler;
- (id)exportedObject;
- (id)exportedInterface;
- (void)setThreadCoexistenceEventHandler:;
- (id)copySidecarStatistics;
- (void)updatedLowLatencyStatistics;
- (void)setServiceAvailabilityUpdatedHandler:;
- (id)channelSequenceUpdatedEventHandler;
- (void)registerAvailabilityUpdatesForService:;
- (id)threadCoexistenceEventHandler;
- (void)setChannelSequenceUpdatedEventHandler:;
- (void)channelSequenceChangedEvent:;
- (void)updatedAWDLState:;
- (id)copyStatistics;
- (void)availabilityUpdatedForService:error:;
- (void)setStateUpdatedHandler:;
- (id)statisticsUpdatedHandler;
- (void)endMonitoring;
- (id)realtimeModeUpdatedHandler;
- (void)setSoftAPChannelChangedEventHandler:;
- (void)setStatisticsUpdatedHandler:;
- (void)setLowLatencyStatisticsUpdatedHandler:;
- (void)updatedStatistics;
- (id)lowLatencyStatisticsDifferenceBetweenPrevious:current:;
- (int)queryAverageRSSIForPeer:;
- (void).cxx_destruct;
- (id)queryPeerDatabase;
- (id)copyActiveServiceUniqueIdentifiers;
- (void)startConnectionUsingProxy:completionHandler:;
- (id)stateUpdatedHandler;
- (id)serviceAvailabilityUpdatedHandler;
- (id)softAPChannelChangedEventHandler;
- (void)updatedRealtimeMode:;
- (void)beginMonitoring;
- (id)copyLowLatencyStatistics;
- (void)setRealtimeModeUpdatedHandler:;
- (void)softAPChannelChangedEvent:channelNumber:;
@end
